Install Astro on Azure Updates
astronomer/docs pull request #1002
Opened 2022-08-05 18:02 UTC by kwcanuck

Resolves #986 

Hi, @dnarain-astro. I have addressed all but one of the issue you identified in issue 986. In the issue, you requested clarification that "that the word _minimum_ in the prerequisites section applies to quotas not resources". I'm not sure how this can be clarified, as the existing text reads "A _minimum quota_ of 48 Standard Ddv5-series vCPUs...". No mention is made of _resources_. I am concerned that adding _resources_ could make this information very confusing. Let me know if you have any suggestions to address this concern. When time permits, please review the changes and provide your feedback. Thanks!

2022-08-05 18:15 UTC, dnarain-astro commented on astro/install-azure.md
> +- Assign an Owner role to the Astronomer Service Principal who manages subscriptions for your organization.
Assign the Astronomer Service Principal an Owner role to your subscription

2022-08-05 18:25 UTC, dnarain-astro requested changes
Just clarified the role assignment step

2022-08-05 19:10 UTC, kwcanuck commented on astro/install-azure.md
> +- Assign an Owner role to the Astronomer Service Principal who manages subscriptions for your organization.
@dnarain-astro I added the edit, but it seems an awkward construction to me. Would one of these work better:

Assign the Astronomer Service Principal a subscription Owner role.

Assign the subscription Owner role to the Astronomer Service Principal.

2022-08-08 14:44 UTC, dnarain-astro approved these changes

2022-08-08 14:52 UTC, merged