Add Browserless Log In Section to Log in to Astro
astronomer/docs pull request #1028
Opened 2022-08-11 14:28 UTC by kwcanuck

Resolves #1011 

We need to identify a SME for the technical review.

2022-08-16 16:31 UTC, jwitz commented on astro/log-in-to-astro.md
> +- Run astro `login -l` in the Astro CLI to manually access the Cloud UI, copy the returned URL, and then run `curl -u <username>:<password> <returned URL>`. Replace `<username>` and `<password>` with
```suggestion
- Run `astro login -l` to retrieve a URL for logging in using the Cloud UI. Copy this URL. In a separate terminal session, run `curl -u <user-email>:<password> <returned-url>. Note that this option does not work for accounts that are authenticated through an identity provider (IdP).
```
@sunkickr Is this right? I was able to use the link in a different browser and then open the callback link (`http://localhost:12345/callback?code...`) in my main browser to finish authentication with an IdP account, but I don't know how a browserless computer could open that callback link

2022-08-16 16:31 UTC, jwitz requested changes
Need to confirm the functionality of the login flag before we merge this

2022-08-22 10:59 UTC, kwcanuck commented
Follow-up message sent to @sunkickr on Slack requesting a review and comment.

2022-08-22 12:57 UTC, sunkickr reviewed
Just add the token login option

2022-08-22 12:57 UTC, sunkickr commented on astro/log-in-to-astro.md
> +
```suggestion

- Run `astro login -t` to login with an authentication token. You can get an auth token from https://cloud.astronomer.io/token on a separate machine. Use this option if you must login through a browser because you are using identity provider (IdP) for account authentication.
```

2022-08-22 14:18 UTC, kwcanuck commented
@jwitz this text is now ready for your final review. Thanks!

2022-08-22 15:31 UTC, jwitz commented on astro/log-in-to-astro.md
> +- Run `astro login -t` if you're using an IdP for account authentication and you want to log in with an authentication token. To obtain an authentication token, on a separate machine browse to <https
```suggestion
- Run `astro login -t` to log in with an authentication token. To obtain an authentication token on a separate machine, open `https://cloud.astronomer.io/token`.
```
This seems to be the most versatile way to log in browserless, so I would put it first in the list

2022-08-22 15:32 UTC, jwitz approved these changes
LGTM after the final comment is resolved!

2022-08-22 16:31 UTC, merged