Add single and multi branch cicd for awscodebuild
astronomer/docs pull request #1032
Opened 2022-08-12 00:12 UTC by pohek321

2022-08-12 14:06 UTC, jwitz commented on astro/ci-cd.md
> +   <pre><code parentName="pre">{`
```suggestion
   ```yaml
```

2022-08-12 14:06 UTC, jwitz commented on astro/ci-cd.md
> +   `}</code></pre>
```suggestion
   ```
```

2022-08-12 14:06 UTC, jwitz commented on astro/ci-cd.md
> +   `}</code></pre>
```suggestion
   ```
```

2022-08-12 14:06 UTC, jwitz commented on astro/ci-cd.md
> +   <pre><code parentName="pre">{`
```suggestion
   ```
```

2022-08-12 14:07 UTC, jwitz commented on astro/ci-cd.md
> +   `}</code></pre>
This suggestion _should_ read as adding three tick marks (`). Thanks GitHub!

2022-08-12 14:07 UTC, jwitz commented on astro/ci-cd.md
> +   `}</code></pre>
This suggestion _should_ read as adding three tick marks (`). Thanks GitHub!

2022-08-12 14:25 UTC, jwitz commented on astro/ci-cd.md
> +
```suggestion
    ```
```

2022-08-12 14:25 UTC, jwitz commented on astro/ci-cd.md
> +
```suggestion
    ```
```

2022-08-12 14:47 UTC, jwitz commented on astro/ci-cd.md
> +</TabItem>
```suggestion
    ```

    When configuring the AWS CodeBuild project, create a webhook source event using the source provider where your Astro project is hosted (i.e. Bitbucket, GitHub, etc.). After doing so, configure the Primary source webhook events to trigger for event type `PUSH`. After setting those configurations, this buildspec.yml triggers a code push to an Astro Deployment every time a commit or pull request is merged to the `main` branch of your repository.

</TabItem>
```

2022-08-12 17:16 UTC, jwitz requested changes
Thanks for writing this up @pohek321 ! I added some comments and questions. If you could give me a brief overview of how CodeBuild interacts with the Git repo, that would help me a lot with my understanding. Is the Git repo hosted in CodeBuild? And if not, how does it communicate with CodeBuild?

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +    When configuring the AWS CodeBuild project, create a webhook source event using the source provider where your Astro project is hosted (i.e. Bitbucket, GitHub, etc.). After doing so, configure th
```suggestion
3. In your AWS CodeBuild project, create a [webhook event](https://docs.aws.amazon.com/codebuild/latest/userguide/webhooks.html) for the source provider where your Astro project is hosted, such as BitBucket or GitHub. When configuring the webhook, select an event type of `PUSH`.

Your buildspec.yml file now triggers a code push to an Astro Deployment every time a commit or pull request is merged to the `main` branch of your repository.
```
A few questions here:
- What is the "source provider"? Is that where our Git repo is hosted?
- I found a "Primary source webhook" for GitHub but not for BitBucket. Can we generalize these instructions?

Even better, can we include an example configuration that someone could run using the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/codebuild/create-webhook.html)?

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +    - `ASTRONOMER_DEPLOYMENT_ID`: The Deployment ID of your production deployment
We need to specify `CODEBUILD_WEBHOOK_HEAD_REF` here and explain what it does.

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +To automate code deploys to a single Deployment using [AWS CodeBuild](https://aws.amazon.com/codebuild/), complete the following setup in a Git-based repository hosting an Astro project:
I'm unfamiliar with CodeBuild, is your code stored in AWS or is it just a build tool? How is the buildspec triggered from GitHub/BitBucket/etc?

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +    - `PROD_ASTRONOMER_KEY_ID`: Your Production Deployment API key ID
Same here, need to specify `CODEBUILD_WEBHOOK_HEAD_REF`

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +   When configuring the AWS CodeBuild project, create a webhook source event using the source provider where your Astro project is hosted (i.e. Bitbucket, GitHub, etc.). After doing so, configure the
Same edits from the previous setup apply here.

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +           if expr "${CODEBUILD_WEBHOOK_HEAD_REF}" : "refs/heads/main" >/dev/null; then
```suggestion
           if expr "${CODEBUILD_WEBHOOK_HEAD_REF}" : "refs/heads/main" >/prod/null; then
```

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +           if expr "${CODEBUILD_WEBHOOK_HEAD_REF}" : "refs/heads/main" >/dev/null; then
Do we need a different webhook for prod/ dev?

2022-08-12 17:16 UTC, jwitz commented on astro/ci-cd.md
> +To automate code deploys across multiple Deployments using [AWS CodeBuild](https://aws.amazon.com/codebuild/), complete the following setup in a Git-based repository hosting an Astro project:
```suggestion
To automate code deploys across multiple Deployments using [AWS CodeBuild](https://aws.amazon.com/codebuild/), complete the following setup in a Git-based repository in CodeBuild hosting an Astro project:
```
Is this correct?

2022-08-12 21:43 UTC, pohek321 commented on astro/ci-cd.md
> +    - `ASTRONOMER_DEPLOYMENT_ID`: The Deployment ID of your production deployment
Hey @jwitz! The CODEBUILD_WEBHOOK_HEAD_REF is an environment variable that is made available by default in AWS CodeBuild. When you are using a webhook to trigger a CodeBuild job, this variable is set with the branch where the webhook action originated from. So you don't need to set it manually.

2022-08-12 21:45 UTC, pohek321 commented on astro/ci-cd.md
> +To automate code deploys to a single Deployment using [AWS CodeBuild](https://aws.amazon.com/codebuild/), complete the following setup in a Git-based repository hosting an Astro project:
Hey @jwitz with AWS CodeBuild, your code can be stored in GitHub, Bitbucket, etc. AWS CodeBuild uses a [webhook event](https://docs.aws.amazon.com/codebuild/latest/userguide/webhooks.html) to recognize when pushes, merges, and other git actions happen in a repository to trigger the AWS CodeBuild pipeline. Jenkins behaves similarly to this as well.

2022-08-12 21:45 UTC, pohek321 commented on astro/ci-cd.md
> +    - `PROD_ASTRONOMER_KEY_ID`: Your Production Deployment API key ID
Hey @jwitz! The CODEBUILD_WEBHOOK_HEAD_REF is an environment variable that is made available by default in AWS CodeBuild. When you are using a webhook to trigger a CodeBuild job, this variable is set with the branch where the webhook action originated from. So you don't need to set it manually.

2022-08-12 21:46 UTC, pohek321 commented on astro/ci-cd.md
> +           if expr "${CODEBUILD_WEBHOOK_HEAD_REF}" : "refs/heads/main" >/dev/null; then
@jwitz 

No need! I have tested this script in action and both need to be `/dev/null` because that's the result of a BASH expression when two strings are equal.

2022-08-12 21:49 UTC, pohek321 commented on astro/ci-cd.md
> +To automate code deploys across multiple Deployments using [AWS CodeBuild](https://aws.amazon.com/codebuild/), complete the following setup in a Git-based repository hosting an Astro project:
I would say that this isn't correct. CodeBuild doesn't behave as a Git repository, but a CI/CD tool. Some Git repository services contain built-in CI/CD tools (i.e. GitHub Actions, GitLab, BitBucket), but there are other standalone CI/CD tools out there that do not act as Git repositories (i.e. Jenkins, CircleCI, AWS CodeBuild, etc.)

2022-08-12 21:50 UTC, pohek321 commented on astro/ci-cd.md
> +    - `PROD_ASTRONOMER_KEY_ID`: Your Production Deployment API key ID
So basically, it helps the CI/CD process identify if the developer pushed commits to dev/staging/main/etc. and we can build conditional logic (based on the branch they are working in) to trigger a deploy to an environment associated to that branch.

2022-08-12 21:59 UTC, pohek321 commented on astro/ci-cd.md
> +    When configuring the AWS CodeBuild project, create a webhook source event using the source provider where your Astro project is hosted (i.e. Bitbucket, GitHub, etc.). After doing so, configure th
Correct, source provider is where the Git repo is hosted (i.e. GitHub, BitBucket)! I think BitBucket, GitHub, and AWS CodeCommit are the only 3 options for Git source repo's in AWS CodeBuild.

Are you asking for a configuration that someone could use to set up this same AWS CodeBuild process via the AWS CLI? I'm sure that the AWS CLI commands exist to set this up, but that wouldn't be uniform with the rest of the CI/CD docs on this page and what we recommend as a starting point (See GitHub Actions, CircleCI, Jenkins, etc.).

2022-08-15 11:28 UTC, jwitz approved these changes
Ahh thanks for clearing up my confusion here @pohek321, I hadn't realized that webhooks are configured initially from the source provider and can then be subscribed to from CodeBuild. Please review the two final copy suggestions here and commit them if you agree - after that, this looks great!

2022-08-16 15:07 UTC, merged