Astro SDK overview documentation
astronomer/docs pull request #1048
Opened 2022-08-18 13:39 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1026

This doc will serve as a brief overview to the Astro SDK and a portal to the rest of the Astro SDK documentation set. We can build out the Astro SDK documentation here more in the future when we have a platform for publishing open source tutorials, but for now it's better to keep that content within the repo of the SDK itself.

2022-08-18 14:18 UTC, jwitz commented on sidebarsSoftware.js
> +      'astro-sdk',
```suggestion
      'astro-python-sdk',
```

2022-08-18 14:36 UTC, jwitz commented on sidebarsSoftware.js
> +      'astro-python-sdk',
```suggestion
```

2022-08-22 17:01 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +description: Learn how you can manage database queries in Python using the Astro SDK.
```suggestion
description: Learn how you can use the Astro SDK to manage database queries in Python.
```

2022-08-22 17:02 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +The Astro Python SDK is an open source DAG development platform built and maintained by Astronomer. The purpose of the SDK is to abstract away Airflow's code-level configuration and let DAG authors f
```suggestion
The Astro Python SDK is an open source DAG development platform built and maintained by Astronomer. The purpose of the SDK is to remove Airflow code-level configuration and let DAG authors focus on writing Python code.
```

2022-08-22 17:09 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +To install the Astro Python SDK in a local environment:
Remove.

2022-08-22 17:11 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- You don't have to define connections top your databases in each task. Tasks can automatically inherit connection information from `Tables`.
```suggestion
- You don't have to define connections to your databases in each task. Tasks can automatically inherit connection information from `Tables`.
```

2022-08-22 17:11 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- `run_raw_sql`: Run any SQL statement without handling its output
```suggestion
- `run_raw_sql`: Runs any SQL statement without handling its output
```

2022-08-22 17:11 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- `append`: Insert rows from the source SQL table into the destination SQL table, if there are no conflicts
```suggestion
- `append`: Inserts rows from the source SQL table into the destination SQL table, if there are no conflicts
```

2022-08-22 17:12 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- `merge`: Insert rows from the source SQL table into the destination SQL table, depending on conflicts:
```suggestion
- `merge`: Inserts rows from the source SQL table into the destination SQL table, depending on conflicts:
```

2022-08-22 17:12 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- `export_file`: Export SQL table rows into a destination file.
```suggestion
- `export_file`: Exports SQL table rows into a destination file.
```

2022-08-22 17:13 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- `dataframe`: Export given SQL table into in-memory Pandas data-frame.
```suggestion
- `dataframe`: Exports a specific SQL table into an in-memory Pandas data-frame.
```

2022-08-22 17:13 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- Extract the data from the files into a new temporary `Table` using `aql.transform`.
```suggestion
- Extracts the data from the files into a new temporary `Table` using `aql.transform`.
```

2022-08-22 17:14 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- Turn the temporary `Table` into a dataframe and melt the values using `aql.dataframe`.
```suggestion
- Turns the temporary `Table` into a dataframe and melts the values using `aql.dataframe`.
```
Is _melts_ correct here? Should it be _merges_?

2022-08-22 17:15 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- Create a new reporting table in Snowflake using `aql.run_raw_sql`.
```suggestion
- Creates a new reporting table in Snowflake using `aql.run_raw_sql`.
```

2022-08-22 17:15 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- Convert the dataframe back into a SQL table and append it to the reporting table with `aql.append`.
```suggestion
- Converts the dataframe into a SQL table and appends it to the reporting table with `aql.append`.
```

2022-08-22 17:16 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +- You don't have to pull in tables as XComs. All operations between different database types are handled automatically by the SDK.
```suggestion
- You don't have to add tables as XComs. All operations between different database types are handled automatically by the SDK.
```

2022-08-22 17:21 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +For more documentation about the Astro Python SDK, see:
Remove

2022-08-22 17:23 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +## Documentation
```suggestion
## Related documentation
```

2022-08-22 17:23 UTC, kwcanuck approved these changes

2022-08-23 14:43 UTC, jwitz commented on astro/astro-python-sdk.md
> +The Astro Python SDK is an open source DAG development platform built and maintained by Astronomer. The purpose of the SDK is to abstract away Airflow's code-level configuration and let DAG authors f
I still like "abstract" instead of "remove", because the code isn't technically removed - it's just running in the background thanks to the SDK

2022-08-23 14:44 UTC, jwitz commented on astro/astro-python-sdk.md
> +- Turn the temporary `Table` into a dataframe and melt the values using `aql.dataframe`.
Melts is the correct term per https://pandas.pydata.org/docs/reference/api/pandas.melt.html

2022-08-23 14:53 UTC, kwcanuck commented on astro/astro-python-sdk.md
> +The Astro Python SDK is an open source DAG development platform built and maintained by Astronomer. The purpose of the SDK is to abstract away Airflow's code-level configuration and let DAG authors f
@jwitz the meaning of _abstract_ is unclear and not simple English. Also, if you keep this term, you should remove _away_ and not use the possessive form of Airflow.  FYI - _remove_ is accepted as a synonym for _abstract_.

2022-09-02 00:07 UTC, paolaperaza reviewed
This looks great @jwitz ! A few thoughts up-front on how we can make this powerful but overall I'm ready to give it a ✅  content wise.

Give my comments a look and then we can chat off-line about where this new doc best fits into our IA before we're ready to merge.

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +1. Add the following line to the `requirements.txt` file of your Astro project:
```suggestion
1. Install the Astro Python SDK by adding the following to the `requirements.txt` file of your Astro project:
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +2. Add the following environment variables to the `.env` file of your Astro project
```suggestion
2. Add the following environment variables to the `.env` file of your Astro project:
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +    AIRFLOW__ASTRO_SDK__SQL_SCHEMA=<snowflake_schema>
Hm we don't have a Snowflake schema yet... should we remove this for now until we're talking about Snowflake specifically?

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +    To use the Astro Python SDK on a Deployment, add these environment variables in your Deployment's configuration. See [Environment variables](environment-variables.md).
```suggestion
    To deploy a pipeline written with the Astro Python SDK to a Deployment on Astro, add these environment variables in your Deployment's configuration. See [Environment variables](environment-variables.md).
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +The Astro SDK includes task decorators for the most common actions you would want to complete in an ETL pipeline. Some of the key functions available are:
```suggestion
The Astro SDK includes task decorators for actions that are most commonly required for ETL pipelines:
```

These are all of them right?

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- `run_raw_sql`: Runs any SQL statement without handling its output
```suggestion
- `run_raw_sql`: Runs any SQL statement without handling its output.
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- `append`: Inserts rows from the source SQL table into the destination SQL table, if there are no conflicts
```suggestion
- `append`: Inserts rows from the source SQL table into the destination SQL table, if there are no conflicts.
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- `merge`: Inserts rows from the source SQL table into the destination SQL table, depending on conflicts:
```suggestion
- `merge`: Inserts rows from the source SQL table into the destination SQL table, depending on conflicts.
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- `dataframe`: Exports a specific SQL table into an in-memory Pandas data-frame.
```suggestion
- `dataframe`: Exports a specific SQL table into an in-memory Pandas DataFrame.
```

Think this is how it's spelled: https://realpython.com/pandas-dataframe/

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- You don't have to pass tables through XComs. All operations between different database types are handled automatically by the SDK.
```suggestion
- You don't have to manually create temp tables and pass them through XComs. All operations between different database types are handled automatically by the SDK.
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- You don't have to define connections to your databases in each task. Tasks can automatically inherit connection information from `Tables`.
```suggestion
- You don't have to define connections to your databases in each task. Tasks automatically inherit connection information from `Tables`.
```

2022-09-02 00:07 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- [Astro Python SDK README](https://github.com/astronomer/astro-sdk): Includes an overview of the SDK, a quickstart, and supported database types.
Let's add the webinar here: https://www.astronomer.io/events/recaps/the-astro-python-sdk/

2022-09-02 13:58 UTC, jwitz commented on astro/astro-python-sdk.md
> +- You don't have to define connections to your databases in each task. Tasks can automatically inherit connection information from `Tables`.
I think we should leave this as "can", because you can definitely reconfigure the connection information manually if you want.

2022-09-02 23:03 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +    ```
i think you usually need to specify a default schema for the SDK to write temp files to. Worth checking with #astro-sdk on their recommendation.

eg., 
```
export AIRFLOW__ASTRO_SDK__SQL_SCHEMA=<default-schema?>

2022-09-02 23:07 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +
there's also the cleanup operator: https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/cleanup.html

2022-09-02 23:13 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +def extract_data(homes1: Table, homes2: Table):
This example leaves me a bit confused with the naming of the functions. We're doing a data transformation in a @aql.transform decorated function, but we're calling it `extract_data`.  Maybe call this `combine_tables` instead?

2022-09-02 23:17 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- Extracts the data from the files into a new temporary `Table` using `aql.transform`.
Please see my comment below on line 70. We're not really extracting data in line 70. Otherwise, this would be a "LET" pipeline, and that would be odd, AFAIK. 
```suggestion
- Merges the two `Table`s of home data using `aql.transform`.
```

2022-09-02 23:23 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- Turns the temporary `Table` into a dataframe and melts the values using `aql.dataframe`.
```suggestion
- Turns the temporary `Table` into a dataframe and melts the values using `aql.dataframe`, returning the results as a `Table`
```

2022-09-02 23:24 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- Converts the dataframe back into a SQL table and appends it to the reporting table with `aql.append`.
the dataframe is converted to a table by the `@aql.dataframe` function already. 

```suggestion
- Appends our `Table` of transformed home data to a reporting table with `aql.append`.
```

2022-09-02 23:29 UTC, mikeshwe requested changes
hi, overall looking good. I suggested a few changes.

2022-09-02 23:29 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- You can run SQL queries directly without first defining them. The SDK includes decorators for common actions in SQL that you would otherwise have to write yourself.
I'm a bit unclear as to how to interpret this bullet point. Surely you must define a SQL query in order to run it. I'm guessing the intention is that:
```suggestion
- You can run SQL queries directly without first defining them. The SDK includes decorators for common actions in SQL that you would otherwise have to write yourself.
```
You can run SQL queries without writing excessive glue code around them. The SDK decorators manage this extra code behind the scenes.

2022-09-05 09:32 UTC, jwitz commented on astro/astro-python-sdk.md
> +- You can run SQL queries directly without first defining them. The SDK includes decorators for common actions in SQL that you would otherwise have to write yourself.
Are functions like `merge` and `append` essentially SQL queries, or do they run something other than a query?

2022-09-05 09:34 UTC, jwitz commented on astro/astro-python-sdk.md
> +- You can run SQL queries directly without first defining them. The SDK includes decorators for common actions in SQL that you would otherwise have to write yourself.
What about "- You can run common SQL queries using Python alone. The SDK includes Python functions for some of the most common actions in SQL."

2022-09-05 09:35 UTC, jwitz commented
@mikeshwe Thank you for the review, I made your changes and added one comment about the last few bullet points!

2022-09-20 15:33 UTC, paolaperaza approved these changes
This LGTM! @jwitz I made some comments to add color on the example DAG, but this looks awesome. Super excited to get it out there.

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +    To deploy a pipeline written with the Astro Python SDK to Astro, add these environment variables in your Deployment configuration. See [Environment variables](environment-variables.md).
```suggestion
    To deploy a pipeline written with the Astro Python SDK to Astro, add these environment variables in your Deployment configuration. See [Environment variables](environment-variables.md).

:::info

The Astro Python SDK currently relies on [pickle](https://docs.python.org/3/library/pickle.html), which is a Python serialization module that transforms data into a portable format. A more secure way for the Astro SDK to serialize objects is coming soon.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- `merge`: Inserts rows from the source SQL table into the destination SQL table, depending on conflicts:
```suggestion
- `merge`: Inserts rows from the source SQL table into the destination SQL table, if there are no conflicts.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- Loads `.csv` files from GitHub into `Tables`, which are objects that contain all of the necessary functionality to pass database contexts between functions without reconfiguration.
```suggestion
- Loads `.csv` files from Amazon S3 into two tables that contain data about the housing market. Tables are objects that contain all of the necessary functionality to pass database contexts between functions without reconfiguration.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- Combines the two `Tables` of home data using `aql.transform`.
```suggestion
- Combines the two tables of home data using `aql.transform` into one table called `combined_homes_data`.
```

Do we have to use `Tables` or can we just say "table"?

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- Creates a new reporting table in Snowflake using `aql.run_raw_sql`.
```suggestion
- Creates a new table called `homes_reporting` in Snowflake using `aql.run_raw_sql`.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- Appends the `Table` of transformed home data to a reporting table with `aql.append`.
```suggestion
- Appends the table of transformed home data to a reporting table called `homes_reporting` with `aql.append`.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- Turns the temporary `Table` into a dataframe, melts the values using `aql.dataframe`, and returns the results as a `Table`.
```suggestion
- Turns the temporary table into a dataframe, melts the values using `aql.dataframe`, and returns the results as a `Table`.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- You don't have to manually create temp tables and pass them through XComs. All operations between different database types are handled automatically by the SDK.
```suggestion
- You don't have to manually create temporary tables and pass them through XComs. All operations between different database types are handled automatically by the SDK.
```

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- You don't have to define connections to your databases in each task. Tasks can automatically inherit connection information from `Tables`.
I may be wrong here about how we should be using `Table` -- feel free to correct me above

2022-09-20 15:33 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +- [Astro Python SDK README](https://github.com/astronomer/astro-sdk): Includes an overview of the SDK, a quickstart, and supported database types.
```suggestion
- [Astro Python SDK README](https://github.com/astronomer/astro-sdk): The source code for the Astro Python SDK in GitHub. The SDK is open source and contributions are welcome.
```

I think let's frame the repo as source code versus where you would go for "quickstart" or "overview" (which should be these docs)

2022-09-20 16:29 UTC, kentdanas commented on astro/astro-python-sdk.md
> +    To deploy a pipeline written with the Astro Python SDK to Astro, add these environment variables in your Deployment configuration. See [Environment variables](environment-variables.md).
Do we want to call out pickle as a security issue here? I thought there was some debate in the broader Airflow community on whether pickle was "okay" or not, but in any case, seems like we don't want to present it as a problem with how it is currently?

2022-09-20 16:31 UTC, kentdanas commented on astro/astro-python-sdk.md
> +- Combines the two `Tables` of home data using `aql.transform`.
From a language perspective you could go either way, but because `Table` is a frequently used object in SDK DAGs I think using `Tables` reinforces how the SDK works. Just a minor preference though, willing to be overruled here.

2022-09-20 16:37 UTC, paolaperaza commented on astro/astro-python-sdk.md
> +description: Learn how you can use the Astro SDK to manage database queries in Python.
```suggestion
description: Learn how you can use the Astro SDK to manage database queries in Python.
```

Not accurate/misleading here if you wanna change it up @jwitz

2022-09-21 10:15 UTC, jwitz commented on astro/astro-python-sdk.md
> +    To deploy a pipeline written with the Astro Python SDK to Astro, add these environment variables in your Deployment configuration. See [Environment variables](environment-variables.md).
Based on the discussion in [this thread](https://astronomer.slack.com/archives/C02B8SPT93K/p1662508941701609), it seems like pickling is top of mind for some customers. However, I'd prefer to keep this in a Considerations section at the top of the doc rather than surface it halfway through the setup

2022-09-21 10:24 UTC, jwitz commented on astro/astro-python-sdk.md
> +- Combines the two `Tables` of home data using `aql.transform`.
Yeah this is a tricky edge case, because a `Table` is a code object in the Python SDK that represents more than just a normal table. I think some of these references can be decapitalized though, like in this bullet point where the tables are not yet turned into `Tables` proper.

2022-09-22 13:32 UTC, merged

2022-09-22 23:04 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- You can run SQL queries directly without first defining them. The SDK includes decorators for common actions in SQL that you would otherwise have to write yourself.
how about just: "The SDK includes Python functions for some of the most common actions in SQL, namely the `merge` and `append` SQL commands."

2022-09-22 23:11 UTC, mikeshwe commented on astro/astro-python-sdk.md
> +- You don't have to define connections to your databases in each task. Tasks can automatically inherit connection information from `Table` objects.
"inherit" seems like a very precise word in the parlance of software engineers. Namely, referring to classes inheriting from each other like in https://www.w3schools.com/python/python_inheritance.asp. s/inherit/infer?