added VNet peering info
astronomer/docs pull request #1053
Opened 2022-08-21 16:39 UTC by gil-rosario

VNet peering info being added into Astro Azure docs

2022-08-21 22:24 UTC, paolaperaza commented
Thank you for doing this, @gil-rosario ! Do you think this step is usually done during the install process and provisioning of the first cluster, or afterwards?

Wondering if this actually just belongs in: https://docs.astronomer.io/astro/connect-external-services

2022-08-22 00:27 UTC, gil-rosario commented
@paolaperaza, yes you are correct. It should be in the location you mentioned. I accidentally overlooked this section. Good catch. I see that most of the requirements are mentioned however some additional info is required for Vnet peering in Azure (like resource groups) which we discovered last week. I will cancel this pull request and submit a new one with the updates on the location you mentioned. Thx for your response @paolaperaza !

2022-08-22 11:51 UTC, kwcanuck commented on astro/install-azure.md
> +If any Azure resources are on a private network, you can choose between two options:
```suggestion
If you want to access Azure resources on a private network, you have the following two options:
```

2022-08-22 11:52 UTC, kwcanuck commented on astro/install-azure.md
> +1. Create a VNet Peering connection between Astronomer's VNet and the VNets for your broader network.
```suggestion
- Create a VNet peering connection between the Astronomer VNet and your network VNets. 
```

2022-08-22 11:53 UTC, kwcanuck commented on astro/install-azure.md
> +2. [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)
```suggestion
- [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)
```

2022-08-22 11:57 UTC, kwcanuck commented on astro/install-azure.md
> +If you want to continue with the option #1, please open a ticket within our [Astronomer Support](https://support.astronomer.io/) with following details and support will proceed on configuring the VNe
```suggestion
To create a VNet peering connection, submit a  [support request](astro-support.md) with the following information:
```

2022-08-22 11:58 UTC, kwcanuck commented on astro/install-azure.md
> +- Azure TenantID of the target VNet
```suggestion
- Azure TenantID of the target VNet.
```

2022-08-22 11:58 UTC, kwcanuck commented on astro/install-azure.md
> +- Subscription ID of the target VNet
```suggestion
- Subscription ID of the target VNet.
```

2022-08-22 11:58 UTC, kwcanuck commented on astro/install-azure.md
> +- Region of the target VNet
```suggestion
- Region of the target VNet.
```

2022-08-22 11:58 UTC, kwcanuck commented on astro/install-azure.md
> +- VNet ID of the target VNet
```suggestion
- VNet ID of the target VNet.
```

2022-08-22 12:00 UTC, kwcanuck commented on astro/install-azure.md
> +- A CIDR block (RFC 1918 IP Space) no smaller than a `/19` range. You must ensure it does not overlap with the Azure VNet(s) that you will be peering with later. The default CIDR range is `172.20.0.0
```suggestion
- A CIDR block (RFC 1918 IP Space) no smaller than a `/19` range. The CIDR block shouldn't overlap with the Azure VNet(s) that you're peering with. The default CIDR range is `172.20.0.0/19`.
```

2022-08-22 12:02 UTC, kwcanuck commented on astro/install-azure.md
> +- Resource group name (you can reference the [Management of Azure Resource Groups Docs here.](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal).
```suggestion
- The resource group name. See [Manage Azure resource groups by using the Azure portal](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal) or  [log in to the Azure Portal](https://portal.azure.com/)
```

2022-08-22 12:03 UTC, kwcanuck approved these changes

2022-08-23 01:40 UTC, paolaperaza requested changes
Roger that, @gil-rosario ! Let's get this moved to the connect to external resources 😎 

Going to "request changes" in the meantime just to keep this PR from accidentally getting merged. @dnarain-astro Would love your review here as well.

2022-08-23 13:04 UTC, dnarain-astro commented on astro/install-azure.md
> +1. Create a VNet Peering connection between Astronomer's VNet and the VNets for your broader network.
It should say Astro VNet - not Astronomer VNet?  Because the VNet is for the product, not the company?

2022-08-23 13:06 UTC, dnarain-astro commented on astro/install-azure.md
> +- Resource group name (you can reference the [Management of Azure Resource Groups Docs here.](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal).
Since Astro creates the resource group (its the name of the cluster), we know the resource group name (or can divine it).  I would rather not ask them to log into this subscription and take a peek (I know they can and will do it, but its just not our model so best to avoid asking them to do it)

2022-08-23 13:33 UTC, dnarain-astro requested changes

2022-08-23 13:33 UTC, dnarain-astro commented on astro/install-azure.md
> +2. [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)
We shouldn't support Virtual Network Integration - because Virtual Network Integration means a non-Astro service is running "being injected into" (Azure's words, not mine) the VNet.  That isn't the Astro model. We don't want any of their stuff in our VNet.

PS: This means we need to add documentation for Private Endpoints, similar to how we did it for [AWS](https://docs.astronomer.io/astro/connect-external-services#aws-privatelink)  - I think that should probably be a different issue/PR than this one.

2022-08-26 11:28 UTC, kwcanuck commented
Follow-up message sent to @gil-rosario on Slack this morning.

2022-08-31 02:19 UTC, closed without merging

2022-08-31 02:20 UTC, gil-rosario commented
Closing this request. A new PR will be opened with the suggested changes to be added within https://docs.astronomer.io/astro/connect-external-services page.