Clarify AWS IAM Role Setup
astronomer/docs pull request #1056
Opened 2022-08-22 18:12 UTC by kwcanuck

Resolves #1046 

Discussed the originating issue with @dnarain-astro and he is providing information and reviewing new content.

2022-08-22 18:14 UTC, dnarain-astro commented on astro/connect-external-services.md
> +By default, Astronomer creates the `AirflowLogsS3-<clusterid>` role in the data plane account.  Every Airflow deployment in a cluster runs under this role.
```suggestion
Astronomer creates the `AirflowLogsS3-<clusterid>` role in the data plane account.  Every Airflow deployment in a cluster runs under this role.
```

2022-08-22 18:14 UTC, dnarain-astro approved these changes

2022-08-23 13:02 UTC, dnarain-astro requested changes

2022-08-23 13:02 UTC, dnarain-astro commented on astro/connect-external-services.md
> +By default, Astronomer creates the `AirflowLogsS3-<clusterid>` role in the data plane account.  Every Airflow deployment in a cluster runs under this role.
Removed the By Default, because its not just the default behavior, its the only behavior. You can't override this.

2022-08-23 16:04 UTC, dnarain-astro approved these changes

2022-08-26 11:57 UTC, kwcanuck commented
@jwitz this PR is ready for your review. Thanks!

2022-08-28 12:00 UTC, jwitz commented on astro/connect-external-services.md
> +:::
```suggestion
    Your Astro cluster's data plane account includes the `AirflowLogsS3-<clusterid>` role that you just specified. When you configure an Airflow connection for a Deployment, specify this role in an [AWS Airflow Connection](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html) to provide your Deployment access to your service.
```

Is this correct? Is the role already created, or is it created after you

2022-08-28 12:02 UTC, jwitz commented on astro/connect-external-services.md
>  8. In the Airflow UI or as an environment variable on Astro, create an Airflow connection to AWS for each Deployment that requires the resources you connected. See [Managing connections to Apache Air
```suggestion
8. In the Airflow UI or as an environment variable on Astro, create an Airflow connection to AWS for each Deployment that requires the resources you connected, making sure to configure `role_arn` as `arn:aws:iam::<dataplane-AWS-account-ID>:role/AirflowS3Logs-<cluster-ID>`. See [Managing connections to Apache Airflow](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html).
```

2022-08-28 12:16 UTC, jwitz approved these changes
LGTM! A few suggestions and clarifying questions, but this can be merged without me taking a second look.

2022-08-28 12:16 UTC, jwitz commented on astro/connect-external-services.md
>      ]
Can't give suggestions, but a few notes on the earlier steps:

- When you access the IAM dashboard in step 3, does it have to be under an account that has access to the AWS service? If so, we could specify that
- Why do we use `AirflowS3Logs-<cluster-ID>` as the role specifically? Is it worth mentioning that this is where worker Pods run?

2022-08-29 17:06 UTC, merged