Cli quickstart renovation
astronomer/docs pull request #106
Opened 2020-12-09 21:30 UTC by jwitz

Changes specific to the CLI guide.

2020-12-09 23:03 UTC, paolaperaza requested changes
Thanks @jwitz ! Made a few comments. I didn't get a chance to review changes for the Astro CLI doc - can you put that in another PR to keep things simple?

2020-12-09 23:03 UTC, paolaperaza commented on cloud/stable/01_get-started/01_quickstart.md
> +For guidance on how to navigate the Airflow UI, refer to the [Apache Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/ui.html).
No "the"?

2020-12-09 23:03 UTC, paolaperaza commented on cloud/stable/01_get-started/01_quickstart.md
> +### Review the Astronomer Certified System Distribution
```suggestion
### Customize your Astronomer Certified Image
```

2020-12-09 23:03 UTC, paolaperaza commented on cloud/stable/01_get-started/01_quickstart.md
> +### Complete Additional Setup
Don't love this title but can't think of anything better - will ponder 🤔

2020-12-10 15:17 UTC, jwitz commented on cloud/stable/01_get-started/01_quickstart.md
> -#### Prerequisites
I split the two different installations (Homebrew and cURL) into separate headers, which I think breaks things up and makes more sense!

2020-12-10 15:18 UTC, jwitz commented on cloud/stable/01_get-started/01_quickstart.md
> +For more information, refer to the [Manage Workspaces and Deployments](/docs/cloud/stable/deploy/manage-workspaces/) guide.
Deferring to the google style guide on this one: simply referring to the title of the guide without a noun after it https://developers.google.com/style/cross-references?hl=en

2020-12-10 15:20 UTC, jwitz commented on cloud/stable/01_get-started/01_quickstart.md
> +If you're the first person on your team to sign up for Astronomer, click **New Workspace** to create a Workspace and officially begin your 14-day trial.
I always consider "Select" to involve a choice, as in "select from the following options". In this context, click is the most accurate word to use.

2020-12-10 15:25 UTC, jwitz commented on cloud/stable/01_get-started/01_quickstart.md
> +#### Join an Existing Workspace
Fixed in my latest commit!

2020-12-10 15:40 UTC, jwitz commented on cloud/stable/01_get-started/01_quickstart.md
> +If you'd like to deploy some more functional DAGs, upload your own or check out [example DAGs we've made open source](https://github.com/airflow-plugins/example-dags).
I think it's fine either way, but using it as a verb is slightly more informal. If we're cool with that, I'll keep it in.

2020-12-13 00:08 UTC, paolaperaza approved these changes
Alrighty, @jwitz ! Mergin this.

2020-12-13 00:08 UTC, merged