Deploy cli renovation
astronomer/docs pull request #107
Opened 2020-12-09 22:22 UTC by jwitz

All of the changes for this doc: https://www.astronomer.io/docs/cloud/stable/deploy/deploy-cli

2020-12-16 02:57 UTC, paolaperaza requested changes
@jwitz Left you a few comments! Thanks for this.

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +* A [Workspace](https://www.astronomer.io/docs/cloud/stable/deploy/manage-workspaces).
Remove period here after `A Workspace`?

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +* **Executor**: We recommend starting with Local.
```suggestion
* **Name**
* **Description** (Optional)
* **Airflow Version**: We recommend using the latest version.
* **Executor**: We recommend starting with Local.
```

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +- Open the Kubernetes or Celery (if you configured your Deployment to use one of those executors).
```suggestion
- Modify your Resources
- Initialize the Airflow upgrade process
- Configure **Email Alerts**
- Access the Airflow UI
- Access your Celery Dashboard (if using CeleryExecutor)
- Delete your Deployment
```

This list was from the old Astro UI - we should add these actions since they're all things you can do in this view

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +First, authenticate to the CLI:
```suggestion
First, authenticate to Astronomer Cloud via the CLI:
```

You don't authenticate _to_ the CLI - you auth to Cloud via the CLI!

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +First, authenticate to the CLI:
(Looks like it was incorrectly written before smh, so not on you!)

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
>  $ astro workspace switch [UUID]
```suggestion
$ astro workspace switch
```

It actually looks like you can just run this command without specifying UUID and it'll prompt you to pick one basically - so no need to add it here

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
>  ```
We should update the output of this command - wanna try it on Cloud today? I think we have a few other deployment values that show up these days (e.g. Airflow version)

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +To deploy on Astronomer, go to your Airflow project directory and run:
```suggestion
To deploy on Astronomer, first make sure you're in your Airflow project directory. Then, run:
```

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +If it's your first time deploying, expect to wait a minute or two for the Docker Image to build. If the deployment was successful, your code changes will appear directly in Airflow.
There was a recent change to the platform where we added some better messaging to the Astro CLI for when deploys are pushed. Can you add that after a deploy, users can expect to see the following?

> Successfully pushed Docker image to Astronomer registry. Navigate to the Astronomer UI for confirmation that your deploy was successful.

Then, instruct them to re-open the Astronomer UI and navigate to the Airflow UI to see if their changes were pushed successfully. (I think we have similar guidance in Cloud quickstart).

2020-12-16 02:57 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +**Deployments:** Most use cases will call for a `production` and `dev` Deployment, both of which exist within a single Workspace and are accessible to the same set of users. From there, you can [set
```suggestion
**Deployments:** Most use cases will call for a "Production` and "Dev" Deployment, both of which exist within a single Workspace and are accessible to a shared set of users. From there, you can [set permissions](https://www.astronomer.io/docs/cloud/stable/manage-astronomer/workspace-permissions) to give users in the Workspace access to specific Deployments.
```

Nice addition to deployment-level RBAC here!

2020-12-16 15:42 UTC, jwitz commented on cloud/stable/03_deploy/02_deploy-cli.md
> +* **Executor**: We recommend starting with Local.
Made this change in my commit!

2020-12-16 15:43 UTC, jwitz commented on cloud/stable/03_deploy/02_deploy-cli.md
> +- Open the Kubernetes or Celery (if you configured your Deployment to use one of those executors).
Sounds good - updated.

2020-12-16 15:53 UTC, jwitz commented on cloud/stable/03_deploy/02_deploy-cli.md
>  ```
I actually just think we should simply cut this sample. None of the other commands have it, and having it in the guide doesn't help with this setup since the values shown aren't used here.

2020-12-16 15:54 UTC, jwitz commented on cloud/stable/03_deploy/02_deploy-cli.md
> +To deploy on Astronomer, go to your Airflow project directory and run:
Updated in commit!

2020-12-16 16:12 UTC, jwitz commented on cloud/stable/03_deploy/02_deploy-cli.md
> +If it's your first time deploying, expect to wait a minute or two for the Docker Image to build. If the deployment was successful, your code changes will appear directly in Airflow.
It's definitely a fine line to walk between letting the help text guide users and documenting the help text ourselves. In this case, I think it's better to remain abstract about the exact message in the terminal since it's pretty self-explanatory. If we have better messaging in the CLI for this, they should know immediately whether the deployment was successful or not.

To revise this, I abstracted the CLI message by just directly telling readers to open the Airflow UI. This avoids redundancy and should be easier to maintain (should we ever change the message again).

2020-12-16 16:17 UTC, jwitz commented
Thanks for the comments @paolaperaza ! Left comments for any changes that weren't self-explanatory. I noticed some differences between this doc and the Enterprise version. Let me know if you'd like me to apply these changes to an Enterprise doc before the next round of review.

2020-12-21 18:28 UTC, paolaperaza commented on cloud/stable/03_deploy/02_deploy-cli.md
> +If it's your first time deploying, expect to wait a minute or two for the Docker Image to build. If the deployment was successful, your code changes will appear directly in Airflow.
Got it. I'm cool with this!

2020-12-21 18:30 UTC, paolaperaza commented
@jwitz Alrighty, I just did another pass and made a few additions:

- Added ## Overview, which I think at this point is a standard across our docs
- Added a few links to other docs that I felt were relevant (e.g. CI/CD, Configure a Deployment, and CLI Quickstart)
- I split up Step 3: Deploy Code to a few sub-steps to be consistent with other docs (Cloud Quickstart, CLI Quickstart)
- Removed extra spaces

Let me know what you think of these. If you approve, I'm ready to merge!

2020-12-21 22:04 UTC, paolaperaza approved these changes
Perf this looks good - thanks @jwitz !

2020-12-21 22:50 UTC, merged