Migrate airflow-decorators guide
astronomer/docs pull request #1070
Opened 2022-08-23 18:35 UTC by kwcanuck

Resolves #1069

Migration of the existing guide airflow-decorators (Introduction to Airflow Decorators)

2022-08-28 12:55 UTC, jwitz requested changes
Requesting changes so that I can review the content that was recently added to the published version of this guide and still needs to be migrated

2022-08-28 12:55 UTC, jwitz commented on guides/airflow-decorators.md
> +sidebar_label: "Introduction to Airflow Decorators"
```suggestion
sidebar_label: "Task decorators"
```

2022-08-28 12:55 UTC, jwitz commented on guides/airflow-decorators.md
> +title: "Introduction to Airflow Decorators"
```suggestion
title: "Introduction to Airflow decorators"
```

2022-08-28 12:55 UTC, jwitz commented on guides/airflow-decorators.md
> +tags: ["DAGs", "Basics", "Astro"]
```suggestion
```

2022-08-28 12:55 UTC, jwitz commented on guides/airflow-decorators.md
> +## Astro project decorators
This section has been updated since this guide was migrated: https://www.astronomer.io/guides/airflow-decorators/#astro-python-sdk-decorators

I would re-migrate it from the source file to make sure that you capture all changes.

2022-08-29 17:39 UTC, kwcanuck commented on guides/airflow-decorators.md
> +## Astro project decorators
@jwitz I have done a side-by-side comparison, and the _Astro Python SDK decorators_ section doesn't appear in the original source doc. Also, I don't want to " re-migrate" content from the source file as it would overwrite all my changes. Should we not be trying to avoid changing documentation during the migration? Should the person adding new content also be responsible for making sure the new content appears in the migrated document?

2022-08-31 10:09 UTC, jwitz approved these changes
New section looks good!

2022-08-31 11:22 UTC, merged