Migrate airflow-kedro guide
astronomer/docs pull request #1078
Opened 2022-08-24 15:08 UTC by kwcanuck

Migration of the existing guide airflow-kedro (Deploying Kedro Pipelines to Apache Airflow)

2022-08-28 12:36 UTC, jwitz requested changes
Looks good from a copy standpoint, but adding @kentdanas for review to clarify some of the steps towards the end of the guide.

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +sidebar_label: "Deploy Kedro Pipelines to Apache Airflow"
```suggestion
sidebar_label: "Kedro"
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +tags: ["Plugins", "Integrations"]
```suggestion
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +## The plugin
```suggestion
## Airflow Kedro plugin
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +In close partnership with the team at Kedro, Astronomer recently extended the [`kedro-airflow`](https://github.com/quantumblacklabs/kedro-airflow) plugin to accommodate a significantly improved devel
```suggestion
In close partnership with the team at Kedro, Astronomer extended the [`kedro-airflow`](https://github.com/quantumblacklabs/kedro-airflow) plugin to accommodate a significantly improved developer experience. With this plugin, you can translate your Kedro pipeline into a clean, legible, and well-structured Apache Airflow DAG with one simple command:
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +- [Docker](https://docs.docker.com/docker-for-mac/install/)
```suggestion
- [The Astro CLI](https://docs.astronomer.io/astro/install-cli).
- [Kedro](https://github.com/quantumblacklabs/kedro).
- [The `kedro-airflow` Plugin](https://github.com/quantumblacklabs/kedro-airflow).
- [Docker](https://docs.docker.com/docker-for-mac/install/).
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +Astronomer added some functionality to the plugin that makes for a great integration with Astro. To give it a try, you'll use the `astro-airflow-iris` starter that's included in the Kedro project. Yo
```suggestion
To try out Astronomer's integration with Airflow, use the `astro-airflow-iris` starter project that includes some simple Kedro pipelines. You'll generate a starter Kedro project, convert your pipelines to Airflow DAGs, and run these DAGs in a local Airflow environment.
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +### Prepare and run the project in Astro
```suggestion
### Prepare and run the project using the Astro CLI
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +4. Make sure you have the `kedro-airflow` plugin installed, then run `pip install kedro-airflow`.
```suggestion
4. Make sure you have the `kedro-airflow` plugin installed using `pip install kedro-airflow`.
```

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +5. Run `kedro airflow create -t dags/`.
Do you run this command from your Astro project or Kedro project? Do we need to specify a relative path to the `DAGs` directory for the Astro project?

Also, I notice we don't include any of the Dockerfile steps mentioned here: https://kedro.readthedocs.io/en/stable/deployment/airflow_astronomer.html#step-2-package-the-kedro-pipeline-as-an-astronomer-compliant-docker-image. Is that because the `iris` project does this for us, or do we need to configure our Astro project more?

2022-08-28 12:36 UTC, jwitz commented on guides/airflow-kedro.md
> +Astronomer is proud to partner with Kedro to bring this plugin experience into the world and look forward to extending it to improve the developer experience even more. [Get in touch](https://astrono
```suggestion
```

2022-08-29 17:12 UTC, kwcanuck commented on guides/airflow-kedro.md
> +5. Run `kedro airflow create -t dags/`.
@kentdanas can you address Jake's questions? I have merged this PR, but the tutorial can be updated if changes are required.

2022-09-08 17:21 UTC, kentdanas commented on guides/airflow-kedro.md
> +5. Run `kedro airflow create -t dags/`.
Your Astro project and your Kedro project are the same in this case. In our guide we direct folks to run `kedro new --starter astro-airflow-iris` first, which is actually bundled with our CLI and runs an `astro dev init` as part of that. So for your second question, yes, the `iris` project does all that other Dockerfile stuff for us (they mention that very briefly in the final note at the end of their tutorial).

I just ran this again and noted that they're still using an older version of our CLI (it pulls an AC 1.10.12 image :cringe:), so at some point we should definitely update this (and probably make it more descriptive). But I think this would likely require working with the Kedro team, so I think we can take care of it post-migration.

2022-09-08 17:32 UTC, kwcanuck commented on guides/airflow-kedro.md
> +5. Run `kedro airflow create -t dags/`.
@jwitz it appears your questions have been addressed. Can we move this PR forward?

2022-09-19 11:19 UTC, kwcanuck commented on guides/airflow-kedro.md
> +5. Run `kedro airflow create -t dags/`.
@jwitz can you unblock this PR? It's been sitting for almost two weeks. Thanks!

2022-11-28 19:26 UTC, closed without merging