Architecture v2
astronomer/docs pull request #1126
Opened 2022-09-01 15:19 UTC by jwitz

2022-09-12 13:56 UTC, paolaperaza requested changes
@jwitz Thank you for putting this together! A few comments and recommendations -- requesting changes given how new some of the content is but take a look and I think we can get it merge ready ✅

2022-09-12 13:56 UTC, paolaperaza commented on tutorials/overview.md
> +- [Astronomer Academy](https://academy.astronomer.io/) offers many video tutorials and the option to purchase full length Airflow courses and to take exams to get certified.
```suggestion
- [Astronomer Academy](https://academy.astronomer.io/) offers step-by-step video tutorials for basic and advanced functionality of both Astro and Airflow. The Academy also offers full-length Airflow courses and certification exams.
```

2022-09-12 13:56 UTC, paolaperaza commented on tutorials/overview.md
> +Learn how to write data pipelines and get Airflow up and running for any use case. These tutorials provide step-by-step instructions for writing DAGs and setting up Airflow.
```suggestion
Learn how to write data pipelines and make the most of data orchestration. These tutorials provide step-by-step instructions for both basic and advanced use cases that use Apache Airflow and Astro.

Tutorials are meant to be completed only once and take from 20 minutes to over 1 hour to complete. They complement Astronomer documentation by educating users on concepts and best practices with real data and hands-on examples.

Most Astronomer tutorials require the Astro CLI, which is open source and free to use by the community.
```

2022-09-12 13:56 UTC, paolaperaza commented on tutorials/overview.md
> +- **[Develop an ETL pipeline with the Astro Python SDK](astro-python-sdk.md)**: Develop an entire ETL pipeline that you can run from your local computer.
Change title here if we end up deciding to

2022-09-12 13:56 UTC, paolaperaza commented on tutorials/get-started-with-airflow.md
> +## Next steps
Can we add a section here that summarizes what the user learned and what they should have accomplished?

2022-09-12 13:56 UTC, paolaperaza commented on tutorials/get-started-with-airflow.md
> +- [DAG Writing Best Practices](https://www.astronomer.io/guides/dag-best-practices?search=best): Learn how to write efficient, secure, and scalable DAGs.
I'll defer a bit here but I'd really like to cut out this section of resources if it's repetitive to the Overview. I know we can't assume that the reader went there first, but let's maybe just provide some actionable next steps instead of listing all "types" of resources.

I.e. Let's keep the list of 3 specific links and maybe add one more -- knowing that they showcase the different types of resources inherently
-

2022-09-12 14:12 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +sidebar_label: 'Astro Python SDK'
"write ETL" seems a little casual even for the sidebar, what about "Write an ETL pipeline with the Astro SDK"? I know it's not as action-oriented, but I could also go for "Your first ETL DAG" like how Confluent does it here: 
![Screen Shot 2022-09-12 at 3 12 17 PM](https://user-images.githubusercontent.com/74574233/189676219-6e4f11eb-c5d7-450d-b85e-7fe7f7cda58e.png)

2022-09-12 14:25 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +- A local Airflow environment. You can use either [Apache Airflow](https://airflow.apache.org/docs/apache-airflow/stable/start/local.html) or [the Astro CLI](https://docs.astronomer.io/astro/cli/get-
It depends whether the SDK team still plans to use this tutorial as a primary entry point for the SDK across all user contexts. It certainly makes sense to do that in the context of our docs, but maybe not in the context of the overall goal to get the SDK into as many hands as possible

2022-09-12 14:26 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +1. On your local machine create a file named `orders_data_header.csv` with the following data:
Nope, this file goes to S3 so there's no need for local storage.

2022-09-12 14:50 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +    Ensure that you have `ACCOUNTADMIN` permissions for your newly created database.
Opted to link out to Snowflake docs

2022-09-12 16:18 UTC, jwitz commented on tutorials/overview.md
> +Learn how to write data pipelines and get Airflow up and running for any use case. These tutorials provide step-by-step instructions for writing DAGs and setting up Airflow.
When I look at this summary, I mostly see caveats for people that might stumble upon this page, rather than encouragements. 

"20 minutes to 1 hour" = I don't have time for that, I shouldn't look at these right now 
"Complement Astronomer documentation" = I need to be an Astro user/ customer to run these tutorials?
"Require the Astro CLI" = What's that? I just want to learn about Airflow.

I'd rather users encounter these once they're in a tutorial instead of on the homepage. I'd opt to keep it short and sweet here by including only the first paragraph.

2022-09-12 16:19 UTC, jwitz commented on tutorials/overview.md
> +- **[Develop an ETL pipeline with the Astro Python SDK](astro-python-sdk.md)**: Develop an entire ETL pipeline that you can run from your local computer.
This was in lieu of box styling, I'm okay to keep it unbolded as well

2022-09-12 16:22 UTC, jwitz commented
@paolaperaza This is ready for another look! I left some comments and questions based on your review, but for the most part accepted your changes as you wrote them.

2022-09-13 03:49 UTC, paolaperaza approved these changes
Couple 'o comments here but I think good for now @jwitz ! We can make more optimizations later

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +The pipeline you build in this tutorial :
```suggestion
The pipeline you build in this tutorial will:
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +To run the DAG, you first need to load some arbitrary data into S3 and create a destination for the data in Snowflake.
```suggestion
For this example, you first need to load a file into S3 and create a destination for the data in Snowflake. In this case, our file has three example orders with distinct customers, purchase dates, and amounts.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +
```suggestion

Now that we have a staging table in Snowflake and some example data ready to load, we need to set up a local Airflow environment for our DAG to run in. This is easy with the Astro CLI.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +1. Run the following commands to create a new Astro project
```suggestion
1. Create a new Astro project:
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +    ```
```suggestion
    $ astro dev init
    ```

This command creates a few files that are required to run Apache Airflow. For this example, ignore these files for now.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +2. Add the following line to the `requirements.txt` file of your Astro project to install the Python SDK and required dependencies for the tutorial:
```suggestion
2. Add the following line to the `requirements.txt` file of your Astro project to install the Python SDK:
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +    ```
```suggestion
    astro-sdk-python[amazon,snowflake]>=0.11
    ```
   This installs the SDK package as well as the Snowflake and Amazon providers, which are required for any DAG that loads data to or from Amazon S3 and Snowflake.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +## Step 3: Create Airflow connections to data stores
```suggestion
## Step 3: Create Airflow connections to S3 and Snowflake
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +1. In your Snowflake Worksheet, create and populate a `customers_table`. You'll join this table with an orders table that you create with the Astro Python SDK:
```suggestion
1. In your Snowflake Worksheet, create and populate a `customers_table`. You'll join this table with an orders table that you create with the Astro Python SDK:
```

Should we specify that this should be done in the DB and schema that we created in step 1?

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +This DAG extracts the data you loaded into S3 into Airflow and runs a few simple SQL statements to clean the data, load it into a reporting table on Snowflake, and transform it into a dataframe so th
```suggestion
This DAG extracts the data you loaded into S3 and runs a few simple SQL statements to clean the data, load it into a reporting table on Snowflake, and transform it into a dataframe so that you can print various table details to Airflow logs using Python.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/astro-python-sdk.md
> +## How does it work?
```suggestion
## How it works
```

I think change `#how-it-works` to this?

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/overview.md
> +Learn how to write data pipelines and become an expert on data orchestration. These tutorials provide step-by-step instructions for both basic and advanced use cases on Apache Airflow and Astro.
```suggestion
Learn how to write data pipelines and become an expert on data orchestration. These tutorials provide step-by-step instructions for both basic and advanced use cases specific to Apache Airflow and Astro.
```

2022-09-13 03:49 UTC, paolaperaza commented on tutorials/overview.md
> +- [Write an ETL pipeline with the Astro Python SDK](astro-python-sdk.md): Develop an entire ETL pipeline that you can run from your local computer.
```suggestion
- [Write an ETL pipeline with the Astro Python SDK](astro-python-sdk.md): Develop an entire ETL pipeline that loads data from Amazon S3 to Snowflake and that you can run from your local computer.
```

2022-09-13 12:56 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +    ```
We have an "assumed knowledge" that includes the first Getting Started tutorial, so I don't think we need to get into the project info here.

2022-09-13 12:57 UTC, jwitz commented on tutorials/astro-python-sdk.md
> +## Step 3: Create Airflow connections to data stores
In service of keeping this as platform neutral as possible, I don't think we need to specify the tools in the titles of the steps

2022-09-13 13:05 UTC, jwitz commented on tutorials/overview.md
> +- [Write an ETL pipeline with the Astro Python SDK](astro-python-sdk.md): Develop an entire ETL pipeline that you can run from your local computer.
I'd avoid using specific products here based on the feedback we received from Steven

2022-09-13 18:25 UTC, merged