Make 0.30 LTS
astronomer/docs pull request #1144
Opened 2022-09-05 09:12 UTC by jwitz

2022-09-06 11:54 UTC, kwcanuck commented on software_versioned_docs/version-0.25/release-notes.md
> +0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, read [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels,
```suggestion
0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, read [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels, see [Release and lifecycle policies](release-lifecycle-policy.md). To read release notes specifically for the Astro CLI, see [Astro CLI release notes](cli-release-notes.md).
```

2022-09-06 11:55 UTC, kwcanuck commented on software_versioned_docs/version-0.29/release-notes.md
> +0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, read [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels,
```suggestion
0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, see [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels, see [Release and lifecycle policies](release-lifecycle-policy.md). To review release notes specifically for the Astro CLI, see [Astro CLI release notes](cli-release-notes.md).
```

2022-09-06 11:56 UTC, kwcanuck commented on software_versioned_docs/version-0.28/release-notes.md
> +0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, read [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels,
```suggestion
0.30 is the latest long-term support (LTS) version of Astronomer Software. To upgrade to 0.30, see [Upgrade Astronomer](upgrade-astronomer.md). For more information about Software release channels, see [Release and lifecycle policies](release-lifecycle-policy.md). To review release notes specifically for the Astro CLI, see [Astro CLI release notes](cli-release-notes.md).
```

2022-09-06 11:57 UTC, kwcanuck commented on software_versioned_docs/version-0.25/release-notes.md
> +If you're looking to upgrade to Astronomer v0.30, refer to [Upgrade to Astronomer v0.25](upgrade-astronomer.md). For instructions on how to upgrade to a patch version within the Astronomer v0.25 seri
```suggestion
If you're upgrading to Astronomer v0.30, see [Upgrade to Astronomer v0.25](upgrade-astronomer.md). For instructions on how to upgrade to a patch version within the Astronomer v0.25 series, see [Upgrade to a Patch Version of Astronomer Software](upgrade-astronomer.md).
```

2022-09-06 11:59 UTC, kwcanuck commented on software/release-notes.md
> +- Fixed an issue where users who authenticated with Google Direct were automatically logged out of the Software UI after 1 hour.
```suggestion
- Users authenticating with Google Direct are no longer automatically logged out of Astronomer Software after 1 hour.
```

2022-09-06 11:59 UTC, kwcanuck approved these changes

2022-09-06 23:57 UTC, cmarteepants requested changes

2022-09-06 23:57 UTC, cmarteepants commented on software/release-lifecycle-policy.md
> +| 0.30             | August 29, 2022 | February 2022           |
> February 2022
Should be August 2023

2022-09-07 07:49 UTC, jwitz commented on software/release-lifecycle-policy.md
> +| 0.30             | August 29, 2022 | February 2022           |
```suggestion
| 0.30             | August 29, 2022 | February 2023           |
```

2022-09-07 07:50 UTC, jwitz commented on software_versioned_docs/version-0.25/release-lifecycle-policy.md
> +| 0.30             | August 29, 2022 | February 2022           |
```suggestion
| 0.30             | August 29, 2022 | August 2023           |
```

2022-09-07 07:50 UTC, jwitz commented on software_versioned_docs/version-0.28/release-lifecycle-policy.md
> +| 0.30             | August 29, 2022 | February 2022           |
```suggestion
| 0.30             | August 29, 2022 | August 2023 |
```

2022-09-07 07:50 UTC, jwitz commented on software_versioned_docs/version-0.29/release-lifecycle-policy.md
> +| 0.30             | August 29, 2022 | February 2022           |
```suggestion
| 0.30             | August 29, 2022 | August 2023           |
```

2022-09-07 07:51 UTC, merged