Rework CLI docs
astronomer/docs pull request #1153
Opened 2022-09-07 10:01 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1149

This PR updates some CLI docs in advance of the new Tutorials tab. I've removed the quickstart tutorial, made a more straightforward "Install the CLI" doc, and changed "Configure the CLI" into a doc specifically about `astro config set`.

2022-09-07 11:22 UTC, kwcanuck commented on astro/cli/configure-cli.md
> +Use this document to learn more about each possible configuration. Note that some possible configurations are not documented here because they are used only on Astronomer Software.
```suggestion
This is where you'll find information about the available Astro CLI configurations. Configurations that are applicable only to Astronomer Software are not provided.
```
Should the introductory statement be more meaningful? For example, why is this information important and why would a user want to review it?

2022-09-07 11:24 UTC, kwcanuck commented on astro/cli/install-cli.md
> +To use the Astro CLI on Mac, you must have:
```suggestion
To use the Astro CLI on Mac, you must have:
```

Remove. The P**rerequisites** heading provides context.

2022-09-07 11:25 UTC, kwcanuck commented on astro/cli/install-cli.md
> +To use the Astro CLI on Windows, you must have:
```suggestion
To use the Astro CLI on Windows, you must have:
```

Remove. The Prerequisites heading provides context.

2022-09-07 11:37 UTC, kwcanuck commented on astro/cli/install-cli.md
> +1. Go to the [**Releases** page of the Astro CLI GitHub repository](https://github.com/astronomer/astro-cli/releases). Based on your desired CLI version and the CPU architecture of your machine, down
```suggestion
1. Go to the [Releases page](https://github.com/astronomer/astro-cli/releases)  of the Astro CLI GitHub repository, scroll to a CLI version, and then download the `.zip` file that matches the CPU architecture of your machine,
```

2022-09-07 11:40 UTC, kwcanuck commented on astro/cli/install-cli.md
> +2. If the `.zip` file does not automatically unzip, run the following command to unzip the executable:
```suggestion
2. If the `.zip` file isn't automatically extracted, run the following command to extract the executable:
```
From the Google developer documentation style guide:

![image](https://user-images.githubusercontent.com/104205257/188869761-fd64d157-57bf-44b2-8402-10fd5caa9f75.png)

2022-09-07 11:41 UTC, kwcanuck commented on astro/cli/install-cli.md
> +To use the Astro CLI on Linux, you must have:
```suggestion
To use the Astro CLI on Linux, you must have:
```
Remove. The **Prerequisites** heading provides context.

2022-09-07 11:43 UTC, kwcanuck commented on astro/cli/install-cli.md
> +To upgrade the Astro CLI to the latest version, you can run the same command as you did to install the CLI for the first time:
```suggestion
To upgrade the Astro CLI to the latest version, run the following command:
```
It can't be assumed that the user was the same individual who ran the installation command. Also, it might be a significant period between installation and upgrade and the user might have no memory of running the command previously. The additional text is unnecessary.

2022-09-07 11:44 UTC, kwcanuck commented on astro/cli/install-cli.md
> +To upgrade the Astro CLI on Windows:
```suggestion
To upgrade the Astro CLI on Windows:
```
Remove. This introductory statement is unnecessary.

2022-09-07 11:44 UTC, kwcanuck commented on astro/cli/install-cli.md
> +1. Delete the existing `astro.exe` file on your machine.
```suggestion
1. Delete the existing `astro.exe` file on your machine.
```
Should the default location be provided?

2022-09-07 11:46 UTC, kwcanuck commented on astro/cli/install-cli.md
> +2. Go to the [**Releases** page of the Astro CLI GitHub repository](https://github.com/astronomer/astro-cli/releases). Based on the version of the CLI you want and your CPU architecture, download one
```suggestion
2. Go to the [Releases page](https://github.com/astronomer/astro-cli/releases) of the Astro CLI GitHub repository, scroll to a CLI version, and then download the `.zip` file that matches the CPU architecture of your machine,
```

2022-09-07 11:47 UTC, kwcanuck commented on astro/cli/install-cli.md
> +3. If the `.zip` file does not automatically unzip, run the following command to unzip the executable:
```suggestion
3. If the `.zip` file isn't automatically extracted, run the following command to extract the executable:
```
From the Google developer documentation style guide:

![image](https://user-images.githubusercontent.com/104205257/188871032-89e407a0-c86d-4639-8224-a74f80c431f6.png)

2022-09-07 11:53 UTC, kwcanuck commented on astro/cli/install-cli.md
> +A new `astro` executable for the Astro CLI is now available. Complete this migration if all of the following are true:
```suggestion
If you're an Astro user using the `astrocloud` CLI executable, you can use the new `astro` executable for the Astro CLI. For more information on Astro CLI v1.0.0, see [Astro CLI Release Notes](cli/release-notes.md).
```
Why use the new executable? What benefit does it provide?

2022-09-07 11:55 UTC, kwcanuck commented on astro/cli/install-cli.md
> +### Step 1: Uninstall `astrocloud`
In the following sections, links are provided to existing procedures. Should the same methodology be used here for consistency?

2022-09-07 11:55 UTC, kwcanuck commented on astro/cli/install-cli.md
> +Once you've uninstalled the `astrocloud` executable, install the latest version of `astro` on your machine.
```suggestion
Install the latest version of `astro` on your machine. See [Install the CLI](cli/configure-cli.md#install-the-cli).
```

2022-09-07 11:56 UTC, kwcanuck commented on astro/cli/install-cli.md
> +For instructions, see [Install the CLI](cli/configure-cli.md#install-the-cli).
If the previous edit is accepted, remove.

2022-09-07 11:57 UTC, kwcanuck commented on astro/cli/install-cli.md
> +In order to run and deploy your existing Astro projects using the `astro` executable, you need to populate these projects with a new `.astro` directory of files. For any existing Astro projects on yo
```suggestion
To run and deploy your existing Astro projects using the `astro` executable, you need to populate these projects with a new `.astro` directory. 
```

2022-09-07 11:58 UTC, kwcanuck commented on astro/cli/install-cli.md
> +1. In your terminal, open your Astro project.
```suggestion
1. In your terminal, go to the location of your Astro project.
```

2022-09-07 12:00 UTC, kwcanuck commented on astro/cli/install-cli.md
> +    If the CLI prompts you about whether you want to create a project in a non-empty directory, enter `Yes`. The CLI will only create files that aren't yet in your directory. In this case, the only f
```suggestion
    If a prompt appears asking you about whether you want to create a project in a directory that isn't empty, enter `Yes`. The CLI only create files that aren't in your directory. In this case, the only files that it creates are `./astro/test_dag_integrity_default.py` and `.astro/config.yaml`.
```

2022-09-07 12:00 UTC, kwcanuck commented on astro/cli/install-cli.md
> +1. In your terminal, open your Astro project.
```suggestion
1.  In your terminal, go to the location of your Astro project.
```

2022-09-07 12:01 UTC, kwcanuck commented on astro/cli/install-cli.md
> +If you have an existing [CI/CD](ci-cd.md) pipeline using the old `astrocloud` executable, update it to use `astro`. For example, in a GitHub Actions CI/CD pipeline you would update the following:
```suggestion
If you have an existing [CI/CD](ci-cd.md) pipeline that uses the `astrocloud` executable, update it to use `astro`. For example, in a GitHub Actions CI/CD pipeline you would update the following:
```

2022-09-07 12:02 UTC, kwcanuck approved these changes

2022-09-12 04:15 UTC, paolaperaza requested changes
Requesting changes given sequencing here, but take a look at my comments @jwitz and we should be good 😊

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +You can use `astro config set` to update local configurations for an Astro project. These configurations affect the behavior of local Airflow environments and the CLI commands that you run within the
```suggestion
As you develop data pipelines, you may need to modify your local Airflow environment to fit the needs of your computer. Every Astro project includes a file called `.astro/config.yaml` that supports various environment-level settings, including:

- The name of your Astro project.
- The port for the Airflow webserver.
- The port for your local Postgres metadata database.
- The username and password for your local user.

In most cases, you only need to modify these settings in the case of debugging and troubleshooting your local environment. The configurations in `.astro/config.yaml` are separate from Docker.
```

Gimme feedback on this wording but I think we need to re-work this intro I think to set the right context for "what kinds of things" we're talking about and at what level. Also, this really has not much to do with "Airflow infrastructure"!

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +Use this document to learn more about each possible configuration. Note that some possible configurations are not documented here because they are used only on Astronomer Software.
Would these configs appear somewhere in the file? How would they know about them?

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +For example, to update the port of your local Airflow webserver, you can run the following:
```suggestion
For example, to update the port of your local Airflow webserver to 8081 from the default of 8080, run:
```

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +| `show_warnings`      | Determines whether warning messages appear when starting up a local Airflow environment         | `true`, `false`             |
@sunkickr Are these configs really it? Anything we'd wanna call out here other than "changing the port"? Seems like the most common use case but I don't want to miss anything

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/install-cli.md
> +
We should link out to either https://github.com/astronomer/astro-cli or https://docs.astronomer.io/astro/cli/release-notes for a user to know "what versions are available"

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/overview.md
> +Follow the [Get started](REPLACE LINK) tutorial to run Airflow locally and write your first DAG.
Do we have to change `get-started` by nature of this doc not being in the Astro CLI section anymore?

2022-09-12 04:15 UTC, paolaperaza commented on astro/cli/overview.md
>  ```
I can't comment since we didn't make changes above, but thoughts on just removing `Run Airflow locally` as an H2 and leaving the intro as-is?

2022-09-12 12:51 UTC, jwitz commented on astro/cli/astro-config-get.md
> +For a list of available configurations, see [Configure the CLI](configure-cli.md).
I think it still makes sense because these aren't really "CLI Options" per se. They are CLI-level configurations that you can set using CLI commands, but you can also dive right into the `config.yml` file and edit them yourself. We can still have the main reference of configs separated from the most important ones, but I don't think that reference belongs here.

2022-09-12 13:01 UTC, jwitz commented on astro/cli/configure-cli.md
> +You can use `astro config set` to update local configurations for an Astro project. These configurations affect the behavior of local Airflow environments and the CLI commands that you run within the
I guess I meant "Airflow components" more than "infrastructure", which is mainly what these configurations are concerned with. 

I don't think these configurations are really "Separate from Docker", as they are all used in container configuration. I just cut a few sentences/ phrases here but overall agree with the edit.

2022-09-12 13:02 UTC, jwitz commented on astro/cli/configure-cli.md
> +Use this document to learn more about each possible configuration. Note that some possible configurations are not documented here because they are used only on Astronomer Software.
In case they are checking out the CLI itself on GitHub to see what possible configs there are. I wouldn't want us to get requests for documenting those values because they were discovered by a user and we failed to mention them.

2022-09-12 13:10 UTC, jwitz commented on astro/cli/install-cli.md
> +1. Delete the existing `astro.exe` file on your machine.
It might be different for everyone depending on their default download path right?

2022-09-12 13:13 UTC, jwitz commented on astro/cli/install-cli.md
> +A new `astro` executable for the Astro CLI is now available. Complete this migration if all of the following are true:
The main issue is that we no longer maintain / support the old executable, so I'll try to emphasize that.

2022-09-12 13:16 UTC, jwitz commented on astro/cli/install-cli.md
> +### Step 1: Uninstall `astrocloud`
Not sure what you mean here. What methodology are you talking about?

2022-09-12 13:20 UTC, jwitz commented on astro/cli/overview.md
>  ```
I think we should add that language back once we have a proper landing page, but I'm fine with removing it for now.

2022-09-12 13:21 UTC, jwitz commented on astro/cli/overview.md
> +Follow the [Get started](REPLACE LINK) tutorial to run Airflow locally and write your first DAG.
Yep, that link will be in a different doc directory/ instance, so we have to use the full link including `https` to access it.

2022-09-12 13:22 UTC, jwitz commented
@paolaperaza This is ready for another look! I assume "sequencing" relates to whether we include the config reference in the CLI reference guide or the base configuration doc - I've made comments, there, but let me know if you meant something else by that.

2022-09-12 13:42 UTC, kwcanuck commented on astro/cli/install-cli.md
> +1. Delete the existing `astro.exe` file on your machine.
@jwitz true. However, astro.exe is within the installation package. Not sure if it's worth adding this information. Your call.

2022-09-13 03:34 UTC, paolaperaza approved these changes
A few comments but LGTM @jwitz !

2022-09-13 03:34 UTC, paolaperaza commented on astro/cli/install-cli.md
> +This is where you'll find information about installing the Astro CLI on a Mac operating system.
```suggestion
Install the Astro CLI on a Mac operating system with a single command.
```

2022-09-13 03:34 UTC, paolaperaza commented on astro/cli/install-cli.md
> +To install a [specific version](https://docs.astronomer.io/astro/cli/release-notes) of the Astro CLI, specify the version you want to install at the end of the command:
This feels not explicit enough? (The link to docs)

2022-09-13 03:34 UTC, paolaperaza commented on astro/cli/install-cli.md
> +### Step 1: Uninstall `astrocloud`
Hm Rob I'd say maybe if we had other docs for it, but in this case we don't (and I don't think we want to create it either)

2022-09-13 03:34 UTC, paolaperaza commented on astro/cli/overview.md
> +Follow the [Get started](REPLACE LINK) tutorial to run Airflow locally and write your first DAG.
Should we replace here before we merge?

2022-09-13 03:34 UTC, paolaperaza commented on sidebarsAstro.js
> +        label: 'Install the CLI',
Remind me where we add redirects?

2022-09-13 12:30 UTC, jwitz commented on sidebarsAstro.js
> +        label: 'Install the CLI',
it will be under `static/_redirects` but we shouldn't need to do any redirects for this change.

2022-09-13 12:31 UTC, jwitz commented on sidebarsAstro.js
> +        label: 'Install the CLI',
It's in `static/_redirects`, added just one for this change

2022-09-13 18:39 UTC, merged