[Draft] Get started tutorial 2
astronomer/docs pull request #1161
Opened 2022-09-07 18:20 UTC by TJaniF

Test PR, still a draft, don't look at it 🙂

2022-09-07 21:01 UTC, kentdanas reviewed
@TJaniF I think this looks great! A couple of minor high-level comments on adding some context, but otherwise I think this content is a great follow up to Part 1.

2022-09-07 21:01 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +## Step 3: Add a provider package
I think it's worth adding a brief sentence or two here stating what provider packages are and why they need to be installed separately. Either before Step 1, or in the text at the end of Step 1. Something like "Provider packages are Python packages maintained separately from core Airflow that contain the hooks and operators to interact with external services."

2022-09-08 10:16 UTC, TJaniF reviewed
Made the adjustments 🙂 .

2022-09-08 10:16 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +After restarting you will get a new DAG Import Error alerting you to a missing Airflow variable. Airflow variables are key value pairs you can set from within the Airflow UI that can be accessed in a
Hmm 🤔 not sure. I capitalized it to match the UI, but maybe it would make sense using ` or " around it?

2022-09-08 10:16 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +The DAG itself has two tasks, the first one uses the `GithubTagSensor` to wait for a tag with the name `v1.0` to be added to the GitHub repository you specified in the Airflow variable `my_github_rep
I think that is a good thing to know about early, especially since the default is so high. Added a sentence 🙂

2022-09-08 16:47 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +3. Name the connection `my_github_connection` and select the **Connection Type** `GitHub`. Note that you can only select connection types that are either available form core Airflow or from a provide
```suggestion
3. Name the connection `my_github_connection` and select the **Connection Type** `GitHub`. Note that you can only select connection types that are either available form core Airflow or from a provider package you have installed. If you are missing the connection type `GitHub`, double check that you installed the `GitHub` provider correctly (Step 3). 
```

2022-09-08 16:48 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +The option to test connections was added in Airflow 2.2. If you are running an older version you can skip step 5.
```suggestion
The option to test connections was added in Airflow 2.2. If you are running an older version of Airflow, you can skip step 5.
```

2022-09-12 12:38 UTC, jwitz requested changes
Wow GREAT tutorial @TJaniF ! Really love the example and code. Combined with part 1, this really feels like the perfect jumping off point for learning Airflow.

I have a few suggestions and questions for the organization, but overall this looks good. I'll give it a final pass to make sure everything's in place on the doc website side before we merge.

2022-09-12 12:38 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +Lastly, the dependency between the two tasks is set so that the API is only queried after the `tag_sensor` task has been successful.
```suggestion
Lastly, the dependency between the two tasks is set so that the API is only queried after the `tag_sensor` task is successful.
```

2022-09-12 12:38 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +The DAG produces the following **Graph** view:
```suggestion
You can see this dependency in the **Graph** view of the Airflow UI:
```
I'm almost inclined to remove this sentence/ screenshot because there's nothing the user can do with this information. It the previous guide it made sense, but we're assuming a basic knowledge of the Airflow UI/ dependencies here. Is this dependency shape something we want to focus on when it's the same as in the previous tutorial?

2022-09-12 12:38 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +1. Go to the Airflow UI and unpause the DAG by clicking on the toggle to the left of the DAG name. The last scheduled DAG run will automatically start and the `tag_sensor` will start to wait for the
```suggestion
1. Go to the Airflow UI and unpause the DAG by clicking on the toggle to the left of the DAG name. The last scheduled DAG run automatically starts, and the `tag_sensor` starts waiting for the `v1.0` tag to be added to your GitHub repository. You will see two light green circles in the **DAGs** view which indicate that the DAG run is in progress and the `example_tag_sensor` task is running.
```

2022-09-12 12:38 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +2. Add the tag `v1.0` to your GitHub repository by running the command `git tag v1.0 && git push --tags` from within your local clone of the repository in your terminal.
```suggestion
2. Add the tag `v1.0` to your GitHub repository by configuring it in the GitHub UI or running `git tag v1.0 && git push --tags` in your local repository clone.
```

2022-09-12 12:38 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +4. Check the logs of the `query_api` task for a brand new cat fact!
```suggestion
4. In the **Grid** view, click on the green box representing the successful task run for `query_api`. Check the **Log** page of the task for a brand new cat fact!
```

2022-09-12 15:24 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +1. Create a new Python file in the `/dags` folder of your Astro project called `my_second_dag.py`.
I agree, I usually use directory. Will update this.

2022-09-12 15:43 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +The DAG produces the following **Graph** view:
I could go either way on this one. I tend to include graph view screenshots in most cases because I think it helps reinforce understanding of what the DAG code is doing. And in this case since we're showing the DAG code broken into steps, it gives the user reassurance that they did everything correctly if they get the same graph view. But you're right that we're not using it for any actionable purposes here, so I'm okay removing it if we want to make it more concise.

2022-09-12 15:47 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +4. Enter your **GitHub Access Token**.
It looks like the screenshots are broken right now, but the Github connection is one where the fields update, so the field is called "GitHub Access Token". I updated to include it, but also feel like it's pretty self-explanatory in this particular case.

2022-09-12 17:08 UTC, kentdanas commented on tutorials/get-started-with-airflow-part-2.md
> +2. Click on the `+` sign to open the form for adding a new variable. Use `my_github_repo` as the **Key** and a GitHub repository you have administrator access to as the **Val**. The repository can be
I agree. @TJaniF can you update this next week? I'm not exactly sure what it should be :)

2022-09-12 17:09 UTC, kentdanas commented
Thanks for your review @jwitz! Tamara is out this week so I went ahead and made most of your requested changes to keep this moving forward. There was one comment I left for her, but otherwise I think I got everything.

2022-09-12 18:12 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +2. Click on the `+` sign to open the form for adding a new variable. Use `my_github_repo` as the **Key** and a GitHub repository you have administrator access to as the **Val**. The repository can be
```suggestion
2. Click on the **+** sign to open the form for adding a new variable. Set the **Key** for the variable as `my_github_repo` and set the **Val** as a GitHub repository you have administrator access to. Make sure the **Val** is in the format `github_account_name/repository_name` (for example `apache/airflow`). The repository can be private.
```

Good catch! Yeah I did not make this clear. It is really just the account name and name of the repo with a slash in between. :)

2022-09-20 10:10 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +To run data pipelines on Astro, you first need to create an Astro project, which contains the set of files necessary to run Airflow locally. For more information on the Astro project, see Part 1 of t
```suggestion
To run data pipelines on Astro, you first need to create an Astro project, which contains the set of files necessary to run Airflow locally. For more information on the Astro project, see Part 1 of the [Get started with Apache Airflow tutorial].
```

2022-09-20 10:13 UTC, jwitz commented
Hey @TJaniF , heads up I'll be making some commits to this PR to try to fix the build errors.

Also, what do you think about switching steps 7 and 8? Step 7 is quite long and has nothing actionable for the user to complete, while step 8 is the real payoff of the tutorial. It might make sense for users to get to that payoff as soon as possible, after which we explain the "how it works" of the DAG. I tried following this structure for the SDK tutorial we published: https://docs.astronomer.io/tutorials/astro-python-sdk

2022-09-20 11:12 UTC, TJaniF reviewed
LGTM @jwitz! I think switching step 7 and 8 is a great idea! 🙂

2022-09-20 11:12 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +The DAG produces the following **Graph** view:
Yes, I agree. I feel like it is a nice visual "you did it right!" signal but if we need to shorten the tutorial it is the first thing that can go :) 

Actually, I think if we are switching around step 7 and 8 we can loose the screenshot in "View your DAG code" since it was already shown.

2022-09-20 11:12 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +The DAG itself has two tasks. The first task uses the `GithubTagSensor` to check whether a tag named `v1.0` has been to your GitHub repository. It uses the Airflow variable (`my_github_repo`) and con
```suggestion
The DAG itself has two tasks. The first task uses the `GithubTagSensor` to check whether a tag named `v1.0` has been to your GitHub repository. It utilizes the Airflow variable (`my_github_repo`) and connection (`my_github_connection`) to access the correct repository with the appropriate credentials. The sensor checks for the tag every 30 seconds and will time out after one day. It is best practice to always set a `timeout` because the default value is quite long at 7 days, which can impact performance if left unchanged in DAG that run on a higher frequency.
```

I didn't like the flow of double "use", open to other synonyms ofc 😅

2022-09-21 16:42 UTC, jwitz approved these changes
LGTM! Excellent guide

2022-09-21 16:42 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +Now that your Airflow environment is configured correctly, look at DAG code you copied from the repository to see how your new configurations are used at the code level.
```suggestion
Now that your Airflow environment is configured correctly, look at the DAG code you copied from the repository to see how your new configurations are used at the code level.
```

2022-09-21 16:42 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +Next, the DAG context is instantiated using the `DAG` class. The DAG has the ID `my_second_dag`, and it starts its runs on September 1st, 2022. After its start date, the DAG runs every day at 9:00 AM
```suggestion
Next, the DAG context is instantiated using the `DAG` class. The DAG has the ID `my_second_dag`, and it starts running on September 1st, 2022. After its start date, the DAG runs every day at 9:00 AM as defined in a [cron](https://crontab.guru/) statement. `catchup` is set to `False` in order to prevent the DAG runs from between the `start_date` and today from being scheduled automatically.
```

2022-09-21 16:44 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +    ![HTTP Connection](/img/tutorials/T2_HTTPConnection.png)
```suggestion
![HTTP Connection](/img/tutorials/T2_HTTPConnection.png)
```

2022-09-22 07:55 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +
```suggestion
```

2022-10-06 10:24 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +    schedule_interval="0 9 * * *",
```suggestion
    schedule="0 9 * * *",
```

2022-10-07 11:22 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +2. Copy the Getting started with Apache Airflow Part 2 example DAG from the Astronomer Registry.
```suggestion
2. Copy the [Tutorial DAG: Airflow Connections](https://registry.astronomer.io/dags/get-started-tutorial-2-dag) from the Astronomer Registry.
```

2022-10-07 11:23 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +To run data pipelines on Astro, you first need to create an Astro project, which contains the set of files necessary to run Airflow locally. For more information on the Astro project, see Part 1 of t
```suggestion
To run data pipelines on Astro, you first need to create an Astro project, which contains the set of files necessary to run Airflow locally. For more information on the Astro project, see Part 1 of the [Get started with Apache Airflow tutorial](https://docs.astronomer.io/tutorials/get-started-with-airflow).
```

2022-10-07 11:43 UTC, TJaniF reviewed
last proofreading edits

2022-10-07 11:43 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +Use this tutorial after completing the [Get started with Apache Airflow](https://docs.astronomer.io/astro/cli/get-started) tutorial to learn about how to connect Airflow to external systems.
```suggestion
Use this tutorial after completing the [Get started with Apache Airflow](https://docs.astronomer.io/tutorials/get-started-with-airflow) tutorial to learn about how to connect Airflow to external systems.
```

2022-10-07 11:43 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +- How to write DAGs and run Airflow. See [Get started with Apache Airflow](https://docs.astronomer.io/astro/cli/get-started).
```suggestion
- How to write DAGs and run Airflow. See [Get started with Apache Airflow](https://docs.astronomer.io/tutorials/get-started-with-airflow).
```

2022-10-07 11:43 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +2. Copy the [Tutorial DAG: Airflow Connections](https://registry.astronomer.io/dags/get-started-tutorial-2-dag) from the Astronomer Registry.
```suggestion
2. Copy the code from the **< > Code** tab of the [Tutorial DAG: Airflow Connections](https://registry.astronomer.io/dags/get-started-tutorial-2-dag) from the Astronomer Registry.
```

2022-10-07 11:43 UTC, TJaniF commented on tutorials/get-started-with-airflow-part-2.md
> +1 Open the Airflow UI to confirm that your DAG was pushed to your environment. On the **DAGs** page, you should see a "DAG Import Error" like the one shown here:
```suggestion
1. Open the Airflow UI to confirm that your DAG was pushed to your environment. On the **DAGs** page, you should see a "DAG Import Error" like the one shown here:
```

2022-10-07 13:07 UTC, jwitz reviewed
Sorry to throw a wrench into things last second, but I have some slight changes to the sidebar that might make these docs easier to browse on the site. let me know what you think!

2022-10-07 13:07 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +title: "Get started with Apache Airflow - Part 2"
```suggestion
title: "Get started with Airflow, Part 2: Providers, connections, and variables"
```

2022-10-07 13:07 UTC, jwitz commented on sidebarsTutorials.js
> +    'get-started-with-airflow-part-2',
```suggestion
   {
      type: 'category',
      label: 'Get started with Apache Airflow',
      link: {
            type: 'doc',
            id: 'get-started-with-airflow',
       },
      items: [
        'get-started-with-airflow',
        'get-started-with-airflow-part-2',
      ],
    },
```

2022-10-07 13:07 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +sidebar_label: "Get started with Airflow - Part 2"
```suggestion
sidebar_label: "Part 2: Providers, connections, and variables"
```

2022-10-07 13:07 UTC, jwitz commented on tutorials/get-started-with-airflow-part-2.md
> +sidebar_label: "Get started with Airflow - Part 2"
If you accept this change, we should change the sidebar label for part 1 to : "Part 1: Write and run your first DAG"

2022-10-07 14:14 UTC, merged