Astronomer Software 0.30.1 release notes
astronomer/docs pull request #1183
Opened 2022-09-12 16:39 UTC by jwitz

2022-09-12 16:41 UTC, cmarteepants approved these changes

2022-09-12 17:10 UTC, kwcanuck approved these changes

2022-09-12 17:29 UTC, vishwas-astro requested changes

2022-09-12 17:29 UTC, vishwas-astro commented on software/release-notes.md
> +## 0.31.0
0.30.1, not 0.31.0

2022-09-12 17:29 UTC, vishwas-astro commented on software/release-notes.md
> +- You can now configure a custom `scrape_interval` for Prometheus using the `--set` flag when [applying a platform config change with Helm](apply-platform-config.md).
This change was reverted. Does not need to go into release notes. cc @danielhoherd @cmarteepants

2022-09-12 18:19 UTC, danielhoherd commented on software/release-notes.md
> +- You can now configure a custom `scrape_interval` for Prometheus using the `--set` flag when [applying a platform config change with Helm](apply-platform-config.md).
That's correct. This feature was broken, so it was reverted. It is planned for a future release though so hold onto these sections for future use.

2022-09-12 21:04 UTC, cmarteepants commented on software/release-notes.md
> +## 0.31.0
Good catch! I missed that one

2022-09-13 09:31 UTC, jwitz commented on software/release-notes.md
> +- You can now configure a custom `scrape_interval` for Prometheus using the `--set` flag when [applying a platform config change with Helm](apply-platform-config.md).
```suggestion
```

2022-09-13 09:31 UTC, jwitz commented on software/release-notes.md
> +
```suggestion
```

2022-09-13 09:31 UTC, jwitz commented on software/release-notes.md
> +## 0.31.0
```suggestion
## 0.30.1
```

2022-09-13 09:31 UTC, merged