Add Procedure for Exporting AWS Task Logs to Datadog
astronomer/docs pull request #1211
Opened 2022-09-15 17:10 UTC by kwcanuck

Resolves #1169

2022-09-16 11:34 UTC, jwitz requested changes
Nice job taking on this tricky setup @kwcanuck ! Have a couple of suggestions and questions here, let me know what you think

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +## Export AWS task logs to Datadog
```suggestion
## Export task logs to Datadog (_AWS only_)
```
Assuming that the task logs are Airflow task logs and not AWS task logs right?

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +Exporting AWS task logs to your existing Datadog instance allows you to centralize the management of logs and deployment metrics and resolve issues quickly.
```suggestion
Exporting task logs from AWS to Datadog allows you to centralize the management of logs and identify issues quickly.  

To export metrics to Datadog, see [Export Airflow metrics to Datadog](deployment-metrics.md#export-airflow-metrics-to-datadog).
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +- Data plane cluster ID.
```suggestion
- Cluster ID. Find this in the **Clusters** tab of the Cloud UI.
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +- Datadog API key.
```suggestion
- Datadog API key. See [API and Application Keys](https://docs.datadoghq.com/account_management/api-app-keys/).
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Create an AWS forwarder stack
```suggestion
### Step 1: Create an AWS forwarder stack
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +Specify additional tags with a comma delimited list and use the backslash \ character to escape commas.
```suggestion
Specify additional tags with a comma-delimited list and use the `\` character to escape commas.
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +For a list of available Datadog sites, see [Getting Started with Datadog Sites](https://docs.datadoghq.com/getting_started/site/).
```suggestion
```
Don't think we need to add this again if it's already in the prerequisites.

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Add source identifier tags (optional)
This is a lot of real estate for a single extra parameter line to the same command in the previous step. Can we add this to the previous step? We could also combine all of these into one command and use [bash comment format](https://phoenixnap.com/kb/bash-comment#:~:text=When%20writing%20bash%20scripts%2C%20any,the%20rest%20of%20the%20code.) to add notes about the optional fields in the command itself.

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Verify AWS forwarder stack creation
```suggestion
### Step 2: Verify AWS forwarder stack creation
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +Confirm the resource description includes `airflow-logs-<dataplane-cluster-ID>`.
```suggestion
1. Open the AWS CLI and run the following command to view a list of AWS stacks:

    ```bash
    aws cloudformation list-stacks
    ```

2. Run the following command to view a resource description for the AWS forwarder stack:

    ```bash
    aws cloudformation describe-stack-resources --<stack-name> <dataplane-cluster-ID>-datadog
    ```

    Confirm the resource description includes `<dataplane-cluster-ID>-datadog-Forwarder-Xliw1oDOFMPj)` or similar.

3. Run the following command to view a resource description for the AWS forwarder stack:

    ```bash
    aws cloudformation describe-stack-resources --<stack-name> <dataplane-cluster-ID>
    ```

    Confirm the resource description includes `airflow-logs-<dataplane-cluster-ID>`.
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +    ```
```suggestion
    ```

```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +    ```
```suggestion
    ```json
    {
      "LambdaFunctionConfigurations": [
        {
            "LambdaFunctionArn": "<LAMBDA ARN>",
            "Events": [
                "s3:ObjectCreated:*"
            ]
       }
    ]
    }
    ```
```
JSON is pretty touchy, I would triple confirm that this is the right indentation and appears correctly in the preview site

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Create a notification
```suggestion
### Step 3: Create a notification
```
What's the goal of this step? What do notifications do? Is it optional?

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Verify log stream functionality
```suggestion
### Step 4: Verify log stream functionality
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +    ```
```suggestion
1. Open the AWS CLI and run the following command to list the log streams for the AWS task logs:

    ```bash
    aws logs describe-log-streams --log-group-name '/aws/lambda/<lambda- name>' --query 'logStreams[*].logStreamName'
    ```
2. Run the following command to list log events for the AWS task log stream:

    ```bash
    aws logs get-log-events --log-group-name "/aws/lambda/<lambda- name>" --log-stream-name '<log-stream-name>'
    ```

```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +            aws logs get-log-events --log-group-name "/aws/lambda/<lambda- name>" --log-stream-name '<log-stream-name>'
```suggestion
    aws logs get-log-events --log-group-name "/aws/lambda/<lambda- name>" --log-stream-name '<log-stream-name>'
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Update an AWS forwarder stack (optional)
I don't think we need to include information about updating and deleting in this much detail. If someone's making stacks in their AWS cloud, they should have a cursory understanding of how to update those details.

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +### Delete an AWS forwarder stack (optional)
```suggestion
### Delete an AWS forwarder stack
```
Let's not list this as optional. We should include an explanation that "When you delete a cluster, you have to manually delete its associated forwarder stack" (Assuming that's the case)

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +    ```
```suggestion
    ```bash
    aws s3api get-bucket-notification-configuration --bucket airflow-logs-<CLUSTER ID>

    # Output example
        {
        "LambdaFunctionConfigurations": [
            {
            "Id": "NWI3ZTVmNjktZTliNC00MzdkLWJjY2MtYmU3N2E3ZTEzOGJi",
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:670049755923:function:ckwqtv0zl000c0rr01u5icygi-datadog-Forwarder-O4Z80ihIkN3X",
            "Events": [
                "s3:ObjectCreated:*"
            ]
            }
        ]
        } 
    ```
```
Again, need to double check on the indentation here.

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +        aws s3api put-bucket-notification-configuration --bucket airflow-logs-<dataplane-cluster-ID> --notification-configuration="{}"
```suggestion
    aws s3api put-bucket-notification-configuration --bucket airflow-logs-<dataplane-cluster-ID> --notification-configuration="{}"
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +        aws cloudformation delete-stack --stack-name <dataplane-cluster-ID>-datadog
```suggestion
    aws cloudformation delete-stack --stack-name <dataplane-cluster-ID>-datadog
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +        aws s3 ls
```suggestion
    aws s3 ls 
```

2022-09-16 11:34 UTC, jwitz commented on astro/view-logs.md
> +2. Run the following command to confirm notifications were enabled for the Amazon S3 bucket:
Should we just assume that notifications were enabled for the bucket because we list the step as non-optional? Then we could cut this step out. This shouldn't really matter unless something bad happens (ie more than an error message) when they try to disable notifications that don't exist.

2022-09-16 11:50 UTC, kwcanuck commented on astro/view-logs.md
> +## Export AWS task logs to Datadog
@jwitz good catch. The originating documentation states "... task log export (on AWS only)". I have updated the heading with your suggestion.

2022-09-16 12:26 UTC, kwcanuck commented on astro/view-logs.md
> +### Add source identifier tags (optional)
@jwitz I had a similar thought, but wanted to start with multiple, full commands. I have consolidated some of the optional parameters and used he bash comment format to introduce them. Let me know what you think.

2022-09-16 12:34 UTC, kwcanuck commented on astro/view-logs.md
> +    ```
@jwitz I'll make sure Howard or another SME confirms the accuracy of the _entire_ section.

2022-09-16 12:35 UTC, kwcanuck commented on astro/view-logs.md
> +### Create a notification
@jwitz it's not optional as far as I can tell. I'll confirm. I've also added an introductory statement.

2022-09-16 12:36 UTC, kwcanuck commented on astro/view-logs.md
> +### Update an AWS forwarder stack (optional)
@jwitz I think this information is helpful. It saves users looking elsewhere for the information. I don't feel strongly about it. So, we can remove it if that's the consensus.

2022-09-16 12:38 UTC, kwcanuck commented on astro/view-logs.md
> +### Delete an AWS forwarder stack (optional)
@jwitz I have added the statement, but it needs to be confirmed by a SME.

2022-09-16 12:39 UTC, kwcanuck commented on astro/view-logs.md
> +2. Run the following command to confirm notifications were enabled for the Amazon S3 bucket:
@jwitz fair point. I've removed the step.

2022-09-16 13:45 UTC, howardyoo reviewed
Also, is there a section that explains how to 'verify' whether the log integration is working properly or not? Similar to datadog metrics export, users usually don't know how to check whether the task logs are being properly sent to DataDog.

In general, a user should log into their datadog, go to `Logs > search` page, and look for log messages that are coming from hosts like `arn:aws:s3:::airflow-logs-*`, and service as `s3`.

Also perhaps mention to contact Astronomer support in case you do not see any logs in the Logs Search page.

2022-09-16 14:07 UTC, kwcanuck commented on astro/view-logs.md
> +### Update an AWS forwarder stack (optional)
@howardyoo to address your concerns, I have added a note below the introductory statement.

2022-09-16 14:18 UTC, howardyoo approved these changes
Ok, LGTM. 
@stuart23 , what do you think?

2022-09-16 15:09 UTC, howardyoo approved these changes
LGTM!

2022-09-16 16:03 UTC, stuart23 commented on astro/view-logs.md
> +If you need to forward task logs to other third-party logging tools, contact [Astronomer support](https://cloud.astronomer.io/support).
```suggestion
Currently, Datadog on AWS is the only third party log forwarder available. If you need to forward task logs to other third-party logging tools, or are using a different cloud than AWS, please contact [Astronomer support](https://cloud.astronomer.io/support) to discuss requirements.
```

We currently don't offer any other log forwarding integrations. Just want to temper the customers expectations here.

2022-09-16 16:46 UTC, paolaperaza requested changes
Hey folks -- I just spoke to @stuart23, and let's 🚫 this PR the way it is today. I think we had a miscommunication -- we do NOT want customers to actually follow these steps.

Let's:
- Add a dedicated section for `Export task logs to Datadog` in the `view-logs` doc
- Let's scrap all pre-requisites and steps in this PR
- Let's keep that section to stating that this feature IS supported (not early access) and more clearly instruct customers to reach out to CRE with the information necessary
- We can give half a sentence explanation of what will happen/how this works, but keep it simple

Thanks @kwcanuck -- sorry for the confusion here 🙏

2022-09-16 17:07 UTC, kwcanuck commented
@jwitz, @paolaperaza, @stuart23 I have updated the new section as discussed. When time permits, please review the edited content and provide your edits or approval. Thanks!

2022-09-16 18:40 UTC, stuart23 requested changes

2022-09-16 18:40 UTC, stuart23 commented on astro/view-logs.md
> +Astro has early access support for forwarding Airflow task logs and basic Airflow metrics to Datadog. If you want to enable log forwarding or you're interested in forwarding task logs to other third-
```suggestion
Astro supports forwarding Airflow task logs and basic Airflow metrics to Datadog. If you want to enable log forwarding or you're interested in forwarding task logs to other third-party logging tools, submit a request to [Astronomer support](https://cloud.astronomer.io/support). In your request, make sure to provide your Datadog API key and identify on which Astro cluster(s) you want to enable the integration.
```

This is now a fully supported feature

2022-09-16 20:35 UTC, stuart23 approved these changes

2022-09-19 09:37 UTC, jwitz approved these changes

2022-09-19 13:59 UTC, paolaperaza reviewed
Quick comment here -- take a look @kwcanuck and I'll get back to you with a ✅

2022-09-19 13:59 UTC, paolaperaza commented on astro/view-logs.md
> +Astro supports forwarding Airflow task logs and basic Airflow metrics to Datadog. If you want to enable log forwarding or you're interested in forwarding task logs to other third-party logging tools,
```suggestion
Astro supports forwarding Airflow task logs to [Datadog](https://www.datadoghq.com/). You only have to enable Datadog once for each cluster on Astro, and task logs from all Deployments in that cluster will be exported.

To export Airflow task logs to Datadog:

1. Create a new Datadog API key or copy an existing API key. See [API and Application Keys](https://docs.datadoghq.com/account_management/api-app-keys/).
2. Identify the Astro cluster for which you want to enable this integration.
3. Submit a request to [Astronomer support](https://cloud.astronomer.io/support) with your Datadog API key and name of your Astro cluster.
```

A couple of comments here:
- Let's link to Datadog
- What's the standard verb for forwarding logs? Is it "forward" or "export"?
- I'd prefer steps here and links out to Datadog docs for clarity

2022-09-19 13:59 UTC, paolaperaza commented on astro/view-logs.md
> +To export metrics to Datadog, see [Export Airflow metrics to Datadog](deployment-metrics.md#export-airflow-metrics-to-datadog).
```suggestion
Astro also supports exporting Airflow metrics Datadog. See [Export Airflow metrics to Datadog](deployment-metrics.md#export-airflow-metrics-to-datadog).
```

2022-09-19 14:17 UTC, kwcanuck commented
@paolaperaza back to you for review.

2022-09-19 15:00 UTC, paolaperaza approved these changes
Thanks @kwcanuck !

2022-09-19 15:00 UTC, paolaperaza commented on astro/view-logs.md
> +Astro also supports exporting Airflow metrics to Datadog. See [Export Airflow metrics to Datadog](deployment-metrics.md#export-airflow-metrics-to-datadog).
I'd prob still keep this at the bottom? I'll defer to you, but I don't think it changes if or how the user follows the steps below.

2022-09-19 15:04 UTC, merged