Update AWS secrets manager setup
astronomer/docs pull request #1225
Opened 2022-09-20 13:04 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1223

2022-09-20 13:11 UTC, jwitz commented on astro/secrets-backend.md
> +- An IAM role with the `SecretsManagerReadWrite` policy that your Astro cluster can assume. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/User
Assuming that there's no other IAM setup specific to Secrets Manager

2022-09-20 13:14 UTC, jwitz commented on astro/secrets-backend.md
> +- An IAM role with the `SecretsManagerReadWrite` policy that your Astro cluster can assume. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/User
```suggestion
- An IAM role with the `SecretsManagerReadWrite` policy that your Astro cluster can assume. See [AWS IAM roles](connect-external-services.md#aws-iam-roles).
```

2022-09-20 13:15 UTC, ReadytoRocc commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
We should add `"variables_prefix": "airflow/variables"` back to backend kwargs.

I would also recommend we add `region` as a backend kwarg, and remove `AWS_DEFAULT_REGION` as an env var.

2022-09-20 13:15 UTC, jwitz commented on astro/secrets-backend.md
> +- An [Astro project](create-project.md) with version 5.1.0+ of `apache-airflow-providers-amazon`. See [AWS IAM roles](connect-external-services.md#aws-iam-roles).
```suggestion
- An [Astro project](create-project.md) with version 5.1.0+ of `apache-airflow-providers-amazon`. See [Add Python and OS-level packages](develop-projec.mdt#add-python-and-os-level-packages).
```

2022-09-20 13:20 UTC, ReadytoRocc commented on astro/secrets-backend.md
>  - A valid AWS Access Key ID and Secret Access Key.
Yes. Parameter Store should also allow this method per the [PR](https://github.com/apache/airflow/pull/25628).

2022-09-20 13:33 UTC, jwitz commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
One last question @ReadytoRocc: does `AIRFLOW__SECRETS__BACKEND_KWARGS` now need to be stored as a secret because it has the ARN role, or is it ok for that to be exposed?

2022-09-20 13:44 UTC, ReadytoRocc commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
My suggestion would be to store `<your-role-arn>` and `region` as an Env Vars, and reference them in the `AIRFLOW__SECRETS__BACKEND_KWARGS` configuration. This will allow developers to specify different roles across Dev, Stage, Prod etc.

Example: `AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": $SM_ROLE_ARN}`

2022-09-20 14:28 UTC, jwitz commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
Does this formatting look right to you? 

```
ENV AIRFLOW_VAR_AWS_ARN=<your-role-arn>
ENV AIRFLOW_VAR_AWS_REGION=<your-aws-region>
ENV AIRFLOW__SECRETS__BACKEND=airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AWS_ARN, "region_name": "$AWS_REGION"}
```

Can you reference an Airflow environment variable within an environment variable?

2022-09-20 14:48 UTC, ReadytoRocc commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
@jwitz - I was referring to ENV Vars outside of code, set on [Astro](https://docs.astronomer.io/astro/environment-variables).

You should not need the quotes for these e.g. `"region_name": $AWS_REGION`

2022-09-20 14:55 UTC, ReadytoRocc commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "role_arn": "<your-role-arn>"}
We should also avoid using ENV Var names that could be reference by other utilities. So for example we could use:

- `AF_SB_SM_ROLE_ARN`
- `AF_SB_SM_REGION`

2022-09-21 10:02 UTC, jwitz commented on astro/secrets-backend.md
> +- An IAM role with [access to Paramter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html) that your Astro cluster can assume. See [AWS IAM roles](conne
@ReadytoRocc I know you said to emphasize the need to approve this role's access to Astro in the prerequisite, but I don't think we need to do that quite yet because it's part of the core set up in the linked documentation. If customers are still stumbling over this, we can update it accordingly later.

2022-09-22 12:45 UTC, jwitz commented
@kwcanuck @paolaperaza This is ready for your review. Thank you!

2022-09-22 13:02 UTC, kwcanuck commented on astro/secrets-backend.md
> +- An [Astro project](create-project.md) with version 5.1.0+ of `apache-airflow-providers-amazon`. See [Add Python and OS-level packages](develop-projec.mdt#add-python-and-os-level-packages).
```suggestion
- An [Astro project](create-project.md) with `apache-airflow-providers-amazon` version 5.1.0 or later. See [Add Python and OS-level packages](develop-projec.mdt#add-python-and-os-level-packages).
```

2022-09-22 13:04 UTC, kwcanuck commented on astro/secrets-backend.md
> +- An IAM role with [access to Paramter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html) that your Astro cluster can assume. See [AWS IAM roles](conne
```suggestion
- An IAM role with access to the [Paramter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html) that your Astro cluster can assume. See [AWS IAM roles](connect-external-services.md#aws-iam-roles).
```

2022-09-22 13:06 UTC, kwcanuck commented on astro/secrets-backend.md
> +To start, create directories for Airflow variables and connections in Parameter Store that you want to store as a secret.
```suggestion
To start, create directories for Airflow variables and connections in Parameter Store that you want to store as secrets.
```

2022-09-22 13:09 UTC, kwcanuck commented on astro/secrets-backend.md
> +Based on this setup, variables and connections should live at `/airflow/variables` and `/airflow/connections`, respectively. For example, if you're setting a secret variable with the key `my_secret`,
```suggestion
Variables and connections should should be stored in `/airflow/variables` and `/airflow/connections`, respectively. For example, if you're setting a secret variable with the key `my_secret`, it should be stored in the `/airflow/connections/` directory. If you modify the directory paths, make sure you change the values for `variables_prefix` and `connections_prefix`.
```

2022-09-22 13:10 UTC, kwcanuck commented on astro/secrets-backend.md
> +For instructions, see documentation for the [AWS Systems Manager Console](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-create-console.html), the [AWS CLI](https://docs.aws.a
```suggestion
For instructions, see the [AWS Systems Manager Console](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-create-console.html), the [AWS CLI](https://docs.aws.amazon.com/systems-manager/latest/userguide/param-create-cli.html), or the [Tools for Windows PowerShell](https://docs.aws.amazon.com/systems-manager/latest/userguide/param-create-ps.html) documentation.
```

2022-09-22 13:11 UTC, kwcanuck commented on astro/secrets-backend.md
> +1. In your `Dockerfile`, add the following lines:
```suggestion
1. Add the following lines to your `Dockerfile`:
```

2022-09-22 13:11 UTC, kwcanuck commented on astro/secrets-backend.md
> +2. In your `.env` file, add the following lines:
```suggestion
2. Add the following lines to your `.env` file:
```

2022-09-22 13:14 UTC, kwcanuck commented on astro/secrets-backend.md
> +To further customize the integration between Airflow and AWS SSM Parameter Store, reference Airflow documentation with the [full list of available kwargs](https://airflow.apache.org/docs/apache-airfl
```suggestion
To further customize the Airflow and AWS SSM Parameter Store integration, see the [full list of available kwargs](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html).
```

2022-09-22 13:15 UTC, kwcanuck commented on astro/secrets-backend.md
> +- An [Astro project](create-project.md) with version 5.1.0+ of `apache-airflow-providers-amazon`. See [Add Python and OS-level packages](develop-projec.mdt#add-python-and-os-level-packages).
```suggestion
- An [Astro project](create-project.md) with `apache-airflow-providers-amazon` version 5.1.0 or later. See [Add Python and OS-level packages](develop-projec.mdt#add-python-and-os-level-packages).
```

2022-09-22 13:17 UTC, kwcanuck commented on astro/secrets-backend.md
> +To start, create an Airflow variable or connection in AWS Secrets Manager that you want to store as a secret. It can be either a real or test value.
```suggestion
Create directories for Airflow variables and connections in Parameter Store that you want to store as secrets. You can use real or test values.
```

2022-09-22 13:18 UTC, kwcanuck commented on astro/secrets-backend.md
> +1. In your `Dockerfile`, add the following lines:
```suggestion
1. Add the following lines to your `Dockerfile`:
```

2022-09-22 13:19 UTC, kwcanuck commented on astro/secrets-backend.md
> +2. In your `.env` file, add the following lines:
```suggestion
2. Add the following lines to your `.env` file::
```

2022-09-22 13:21 UTC, kwcanuck commented on astro/secrets-backend.md
> +1. Run the following command to deploy the contents of your `.env` file directly to your Cloud UI
```suggestion
1. Run the following command to deploy the contents of your `.env` file to your Cloud UI
```

2022-09-22 13:23 UTC, kwcanuck commented on astro/secrets-backend.md
> +To further customize the integration between Airflow and AWS Secrets Backend, reference Airflow documentation with the [full list of available kwargs](https://airflow.apache.org/docs/apache-airflow-p
```suggestion
To further customize the Airflow and AWS SSM Parameter Store integration, see the [full list of available kwargs](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html).
```

2022-09-22 13:25 UTC, kwcanuck commented on astro/secrets-backend.md
>  To start, create an Airflow variable or connection in Google Cloud Secret Manager that you want to store as a secret. You can do so via the Cloud Console or the gcloud CLI.
```suggestion
Use the Cloud Console or the gcloud CLI to create an Airflow variable or connection in Google Cloud Secret Manager that you want to store as a secret.
```

2022-09-22 13:25 UTC, kwcanuck approved these changes

2022-09-22 17:10 UTC, stuart23 commented on astro/secrets-backend.md
> +- An IAM role with [access to Paramter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html) that your Astro cluster can assume. See [AWS IAM roles](conne
```suggestion
- An IAM role with [access to Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html) that your Astro cluster can assume. See [AWS IAM roles](connect-external-services.md#aws-iam-roles).
```

Can we please have spellcheck in CI :pleading_face:

2022-09-22 17:13 UTC, stuart23 commented on astro/secrets-backend.md
> -#### Step 3: Run an example DAG to test AWS Parameter Store locally
@ReadytoRocc you don't want the test anymore?

2022-09-22 17:15 UTC, stuart23 commented on astro/secrets-backend.md
> +    AF_PS_REGION=<your-role-arn>
@ReadytoRocc what does the variable name mean? Can we choose something more intuitive like `SECRETS_MANAGER_ROLE` and `SECRETS_MANAGER_REGION`?

2022-09-22 17:19 UTC, stuart23 commented on astro/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AD_SB_ARN, "region_name": $AF_SB_REGION}
```suggestion
    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AF_SB_ARN, "region_name": $AF_SB_REGION}
```

2022-09-22 17:20 UTC, stuart23 commented on astro/secrets-backend.md
> +To deploy your project to a hosted Git repository before deploying to Astro, save `<your-role-arn>` and `<your-aws-region>` values securely. When you deploy to Astro, use the Cloud UI to set these va
Wait are we creating them as secrets? The next step shows them being created as variables.

2022-09-22 17:23 UTC, stuart23 commented on astro/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AD_SB_ARN, "region_name": $AF_SB_REGION}
Again, variables are named wrong. Can we use a more familiar name too?

2022-09-22 17:24 UTC, stuart23 requested changes
Needs some work - there are mistakes and inconsistencies in variable names.

2022-09-23 08:52 UTC, jwitz commented on astro/secrets-backend.md
> -#### Step 3: Run an example DAG to test AWS Parameter Store locally
When we spoke about this over zoom, Rocco mentioned that the new setup (core config in Dockerfile, Astro env vars for IAM role) doesn't work locally, but he also said that shouldn't matter because most organizations are likely to not allow local access to their secrets backends anyways.

If they want to test the backend, they can deploy to Astro and use an IAM role that's compliant with dev/ testing. Should we be more explicit about that?

2022-09-23 08:55 UTC, jwitz commented on astro/secrets-backend.md
> +    AF_SB_REGION=<your-aws-region>
```suggestion
    AF_SM_ARN=<your-role-arn>
    AF_SM_REGION=<your-aws-region>
```

2022-09-23 08:56 UTC, jwitz commented on astro/secrets-backend.md
> +To deploy your project to a hosted Git repository before deploying to Astro, save `<your-role-arn>` and `<your-aws-region>` values securely. When you deploy to Astro, use the Cloud UI to set these va
This note is incorrect. The IAM role / region shouldn't have to be secret because they aren't technically credentials.

2022-09-23 08:56 UTC, jwitz commented on astro/secrets-backend.md
```suggestion
```

2022-09-23 08:56 UTC, jwitz commented on astro/secrets-backend.md
>  :::
```suggestion
```

2022-09-23 08:57 UTC, jwitz commented on astro/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AD_SB_ARN, "region_name": $AF_SB_REGION}
Rocco might respond above, but he suggested these names to me because they were unlikely to be utilized by Airflow/ any other software. V open to renaming as long as the name still has that quality.

2022-09-23 15:41 UTC, stuart23 commented on astro/secrets-backend.md
> -#### Step 3: Run an example DAG to test AWS Parameter Store locally
That makes sense! I don't think we provide instructions for testing on other changes, so I am happy to close this.

2022-09-23 21:06 UTC, stuart23 commented on astro/secrets-backend.md
> +To deploy your project to a hosted Git repository before deploying to Astro, save `<your-role-arn>` and `<your-aws-region>` values securely. When you deploy to Astro, use the Cloud UI to set these va
@ReadytoRocc can you change this back to variables? Also are we using the GUI or CLI to create them?

2022-09-23 21:07 UTC, stuart23 commented on astro/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AD_SB_ARN, "region_name": $AF_SB_REGION}
I have a vendetta for acronyms, especially in variable names - it might save the author 10 seconds, but it takes an extra 10 minutes for each person reading it to understand what it means.

2022-09-23 21:08 UTC, stuart23 commented on astro/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables",  "role_arn": $AD_SB_ARN, "region_name": $AF_SB_REGION}
`Explicit is better than implicit.` - The Zen of Python

2022-09-26 12:07 UTC, jwitz commented
@stuart23 I have now fixed the env var names to be more descriptive and removed the erroneous note

2022-09-26 18:08 UTC, stuart23 approved these changes
Much better. Thanks @jwitz

2022-09-27 11:29 UTC, merged