update peering info from VPC to Vnet for Azure installs
astronomer/docs pull request #1226
Opened 2022-09-20 14:08 UTC by gil-rosario

Current peering section within Astro - Install on Azure contains VPC peering info which is relevant for AWS not Azure. I updated the section to include Azure Vnet peering prerequisites info.

2022-09-20 14:56 UTC, jwitz requested changes
Thank you @gil-rosario , looks great! Requesting changes on a small question I have towards the end of the section - wondering whether we need to specify account requirements for our own setup if they're completed as part of the initial VNet setup. Also curious about what the user needs to do for option 2 here.

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> + 2. [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)
```suggestion
 - Create a VNet Peering connection between Astronomer's VNet and the VNets for your broader network. 
 - [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2).
```

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> +If any Azure resources are on a private network, you can choose between two options:
```suggestion
To give Astro access to any Azure resources on a private network, you can choose between two options:
```

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> + If you want to continue with the option #1, please open a ticket within our [Astronomer Support](https://support.astronomer.io/) with following details and support will proceed on configuring the VN
```suggestion
 To implement the first option, contact [Astronomer Support](https://support.astronomer.io/) and provide the following details:
```

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> + - ResourceID - The resource ID is similar to the following example: /subscriptions/<Subscription Id>/resourceGroups/myResourceGroupA/providers/Microsoft.Network/virtualNetworks/myVnetA (you can capt
```suggestion
 - ResourceID, for example: `/subscriptions/<Subscription Id>/resourceGroups/myResourceGroupA/providers/Microsoft.Network/virtualNetworks/myVnetA`. You can find the resource ID in the Azure portal by following step 7 in [Create peering - Azure portal](https://docs.microsoft.com/en-us/azure/virtual-network/create-peering-different-subscriptions#portal).
```

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> +        -  Classic Network Contributor: For a virtual network deployed through the classic deployment model.
```suggestion
From here, Astronomer support will set up the VNet connection to Astro.
```
Is the account information specific to Astro in any way? If they already are working in VNet, I assume they have the correct permissions on their account.

2022-09-20 14:56 UTC, jwitz commented on astro/install-azure.md
> + 2. [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)
What does the user need to do for [Virtual Network Integration](https://docs.microsoft.com/en-us/azure/api-management/virtual-network-concepts?tabs=stv2)?

2022-09-20 16:20 UTC, stuart23 commented
Hey @gil-rosario, you are pushing from a fork. Do you have access to create a new branch on this repo with your changes?

2022-09-28 15:23 UTC, jwitz commented
Closing in favor of https://github.com/astronomer/docs/pull/1274

2022-09-28 15:23 UTC, closed without merging