Update Astro IA
astronomer/docs pull request #1228
Opened 2022-09-20 15:47 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1227
Resolves https://github.com/astronomer/docs/issues/1224

Two comments for this PR:

- I'm playing with the idea of having Runtime docs in multiple menus (Release notes is in both the Runtime and the Release Notes menus now)
- I couldn't find an appropriate home for the limitation about the Celery executor.. we might need our "Migrate DAGs" doc for that one.

2022-09-20 16:19 UTC, kwcanuck approved these changes

2022-09-21 03:07 UTC, paolaperaza requested changes
Hey Jake -- let's chat about this quick before you merge. From the top, I'm seeing a redundancy in `Astro Runtime` being the name of release notes and the name of the top-level menu:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/31111752/191405457-76b23cd7-b672-48c0-a72b-26f1bdc606fd.png">

We need to either:
- Get rid of `Release Notes` as a top-level navigation
- Not include Astro Runtime release notes in the Astro Runtime menu

I'm actually not super convinced we _need_ an Astro Runtime menu? Anything wrong with keeping these docs in `Reference` (which I agree, we should clean up)

2022-09-22 12:30 UTC, jwitz commented on sidebarsAstro.js
> +        'runtime-release-notes',
```suggestion
```

2022-09-22 12:34 UTC, jwitz commented on sidebarsAstro.js
> +    },
```suggestion
```

2022-09-22 12:35 UTC, jwitz commented on sidebarsAstro.js
>          'astro-support',
```suggestion
        'astro-support',
        {
          type: 'category',
          label: 'Astro Runtime',
          items: [
          'runtime-image-architecture',
          'runtime-version-lifecycle-policy',
          ],
      },
```

2022-09-22 12:37 UTC, jwitz commented
@paolaperaza I was mainly trying to replicate what we had on Software, where we have both an AC and a Runtime menu. Maybe a compromise would be to have a Runtime submenu in the Reference menu? I've implemented that idea here.

2022-10-02 20:03 UTC, paolaperaza approved these changes

2022-10-02 20:03 UTC, paolaperaza commented
@jwitz Should we add a redirect from known-limitations to Astro home?

2022-10-03 15:11 UTC, merged