Add Steps for Azure NFS Installation
astronomer/docs pull request #1239
Opened 2022-09-21 15:12 UTC by kwcanuck

Resolves #696

2022-09-21 20:01 UTC, cmarteepants requested changes
We should either 
1. Remove steps 7 to 10, or;
2. Put those steps in a different section saying that as an example for getting dags into the NFS share. And then add the remaining steps of setting up a service account, and using that service account to copy the dags into the pod

2022-09-22 13:52 UTC, rbankston commented on software/deploy-nfs.md
> +Create and mount an Azure file share to deploy DAGs to an Airflow Deployment on Astronomer. For additional information about this process, see [File Storage](https://docs.microsoft.com/en-us/azure/st
would like to see a change of [File Storage] to [Premium File Storage]

2022-09-22 16:33 UTC, cmarteepants commented on software/deploy-nfs.md
> +Create and mount an Azure file share to deploy DAGs to an Airflow Deployment on Astronomer. For additional information about this process, see [File Storage](https://docs.microsoft.com/en-us/azure/st
Is that because NFS is only available with Premium File Storage?

2022-09-27 18:09 UTC, kwcanuck commented on software/deploy-nfs.md
> +Create and mount an Azure file share to deploy DAGs to an Airflow Deployment on Astronomer. For additional information about this process, see [File Storage](https://docs.microsoft.com/en-us/azure/st
@cmarteepants and @rbankston I have updated the procedure based on your feedback. If there are specific changes or additions you want:

1. Click **Files changed**.

2. Scroll to the location where you want to add or edit text and click the **Plus** (+) icon.

![image](https://user-images.githubusercontent.com/104205257/192602927-5c3af72f-36e8-4cf2-8f45-95019e3bc133.png)

3. Click **Add a suggestion**.

![image](https://user-images.githubusercontent.com/104205257/192603160-95cea061-56a6-4e4d-b5fc-398f418678cb.png)

4. Add or edit text and then click **Add single comment**.

If there is specific text  or procedure steps you want added, please provide the information, or direct me to a location where it is provided. 

Please review the changes and provide your edits, or approval.

Thanks!

2022-09-27 18:39 UTC, cmarteepants approved these changes
This is great, thank you!

2022-09-27 18:41 UTC, kwcanuck commented
@jwitz ready for your review

2022-09-27 18:42 UTC, rbankston approved these changes
Thank you Rob. That looks good to me

2022-10-03 13:22 UTC, kwcanuck commented
@jwitz this is ready for review.

2022-10-17 12:14 UTC, jwitz approved these changes

2022-10-17 12:14 UTC, jwitz commented on software/deploy-nfs.md
> +Create and mount an Azure file share to deploy DAGs to an Airflow Deployment on Astronomer. For additional information about this process, see [Premium File Storage](https://docs.microsoft.com/en-us/
```suggestion
Create and mount an Azure file share to deploy DAGs from an NFS volume to an Astronomer installation on Azure. For additional information about this process, see [Premium File Storage](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-nfs-shares?tabs=azure-portal).
```

2022-10-17 12:14 UTC, jwitz commented on software/deploy-nfs.md
> +2. Save the `config.yaml` file and push the configuration change to your platform. See [Apply a config change](apply-platform-config.md). THis process only needs to be completed once for each Softwar
```suggestion

2. Save the `config.yaml` file and push the configuration change to your platform. See [Apply a config change](apply-platform-config.md). This process only needs to be completed once for each Software installation.
```

2022-10-17 12:38 UTC, merged