Runtime. 5.0.9 release notes
astronomer/docs pull request #1240
Opened 2022-09-21 16:28 UTC by jwitz

Once these are approved, I'll push the changes to Software

2022-09-21 16:31 UTC, ashb approved these changes

2022-09-21 16:40 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +- Set `AIRFLOW__CELERY__STALLED_TASK_TIMEOUT=600` by default.
```suggestion
- Set the default value for the `AIRFLOW__CELERY__STALLED_TASK_TIMEOUT` variable. to 600 
```

2022-09-21 16:40 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
```suggestion
    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
```
Do we need to identify the UI we're referencing?

2022-09-21 16:42 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +- Upgraded `astronomer-providers` to 1.8.1, which includes various bug fixes. For a complete list of changes, see the [Astronomer Providers changelog](https://github.com/astronomer/astronomer-provide
```suggestion
- Upgrading `astronomer-providers` to 1.8.1, which includes various bug fixes. For a complete list of changes, see the [Astronomer Providers changelog](https://github.com/astronomer/astronomer-providers/blob/main/CHANGELOG.rst#181-2022-09-01).
```

2022-09-21 16:42 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +- Upgraded `openlineage-airflow` to 0.13.0, which includes fixes for Spark integrations. See the [Astronomer Providers changelog](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md#014
```suggestion
- Upgrading `openlineage-airflow` to 0.13.0, which includes fixes for Spark integrations. See the [Astronomer Providers changelog](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md#0141---2022-09-07).
```

2022-09-21 16:43 UTC, kwcanuck approved these changes

2022-09-22 15:31 UTC, jwitz commented on astro/runtime-release-notes.md
> +- Upgraded `astronomer-providers` to 1.8.1, which includes various bug fixes. For a complete list of changes, see the [Astronomer Providers changelog](https://github.com/astronomer/astronomer-provide
Not sure why we want to use gerunds here, when the action is past tense?

2022-09-22 15:31 UTC, jwitz commented on astro/runtime-release-notes.md
> +    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
For backported Airflow fixes, I think we should use the same description as the PR we're referencing

2022-09-22 15:47 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +- Upgraded `astronomer-providers` to 1.8.1, which includes various bug fixes. For a complete list of changes, see the [Astronomer Providers changelog](https://github.com/astronomer/astronomer-provide
@jwitz in a previous edit I recommended changing _Set_ to _Setting_ . If you implemented this change, the list would no longer be parallel. For this reason I recommended changing _Upgrade_ to _Upgrading_. It still works as an improvement or an upgrade can be seen as something that is occurring now.

2022-09-22 16:01 UTC, paolaperaza requested changes

2022-09-22 16:01 UTC, paolaperaza commented on astro/runtime-release-notes.md
> +- Backported several changes from Airflow 2.4.0:
Let's make this an H3? As we do here: https://docs.astronomer.io/astro/runtime-release-notes#backported-fixes-from-apache-airflow

(We could specify `Backported fixes from Airflow 2.4`)

2022-09-22 16:01 UTC, paolaperaza commented on astro/runtime-release-notes.md
> +    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
I actually disagree here -- the Airflow PR descriptions are historically _bad_ so I'm ok giving the user more clarity. This means a little bit more work for us to go interpret a PR, but even a quick review and slight improvement is good.

@jwitz Can you ask @jedcunningham for his opinion and have him confirm what this bug fix actually is?

2022-09-22 16:04 UTC, jedcunningham commented on astro/runtime-release-notes.md
> +    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
This one was intentionally vague in OSS, as it fixes a CVE: https://lists.apache.org/thread/cn098dcp5x3c402xrb06p3l7nz5goffm

2022-09-22 16:17 UTC, jwitz commented on astro/runtime-release-notes.md
> +    - Fix UI redirect [#26409](https://github.com/apache/airflow/pull/26409)
My issue with writing our own notes for each backported fix is that these fixes can get pretty technically nuanced to the point that a quick review might end up misinterpreting the change rather than illuminating it. And given that we're usually on a tight schedule to get these notes published, I don't think it's possible to investigate the changes each time. For people interested in this level of detail, I think the commit number / link is the most important detail to include

2022-09-22 16:41 UTC, paolaperaza approved these changes

2022-09-23 15:12 UTC, merged