Update Integrate with SendGrid Procedure
astronomer/docs pull request #1269
Opened 2022-09-27 14:36 UTC by kwcanuck

Resolves #1231.

2022-09-27 16:11 UTC, howardyoo requested changes
Please review my comments and make appropriate additions!

2022-09-27 17:17 UTC, kwcanuck commented on astro/airflow-alerts.md
>      - **Value**: `airflow.providers.sendgrid.utils.emailer.send_email`
@howardyoo I have updated the procedure based on your feedback. Please review and provide your edits or approval.

2022-09-27 18:04 UTC, howardyoo requested changes
requesting small fix for the incorrect value.

2022-09-27 18:04 UTC, howardyoo commented on astro/airflow-alerts.md
> +    - `AIRFLOW__EMAIL__EMAIL_BACKEND` = `airflow.providers.sendgrid.utils`
the value should be `airflow.providers.sendgrid.utils.emailer.send_email`, not `airflow.providers.sendgrid.utils`

2022-09-27 18:13 UTC, kwcanuck commented on astro/airflow-alerts.md
> +    - `AIRFLOW__EMAIL__EMAIL_BACKEND` = `airflow.providers.sendgrid.utils`
@howardyoo I have updated the text as requested. In future, ff there are specific changes or additions you want:

1. Click **Files changed**.

2. Scroll to the location where you want to add or edit text and click the **Plus** (+) icon.

![image](https://user-images.githubusercontent.com/104205257/192604271-39b64b9e-6036-49c9-9718-72fa166a6ae0.png)

3. Click **Add a suggestion**.

![image](https://user-images.githubusercontent.com/104205257/192604352-28594637-580d-42cb-b436-46c4dd6865e6.png)

4. Add or edit text and then click **Add single comment**.

Please review the changes and provide your edits, or approval.

Thanks!

2022-09-27 18:19 UTC, howardyoo approved these changes
LGTM :-)

2022-09-27 18:19 UTC, howardyoo commented on astro/airflow-alerts.md
> +    - `AIRFLOW__EMAIL__EMAIL_BACKEND` = `airflow.providers.sendgrid.utils`
Oh ok, thanks! I got it.

2022-09-27 18:19 UTC, howardyoo commented on astro/airflow-alerts.md
>      - **Value**: `airflow.providers.sendgrid.utils.emailer.send_email`
Thanks! Looks good.

2022-09-27 18:23 UTC, kwcanuck commented
@jwitz ready for your review.

2022-09-28 10:00 UTC, jwitz approved these changes

2022-09-28 10:00 UTC, jwitz commented on astro/airflow-alerts.md
> +6. Add the [SendGrid Airflow provider](https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html) to your Astro project by adding the following to your `requirements.txt` fi
```suggestion
6. Add the following line to your Astro project `requirements.txt` file to install the [SendGrid Airflow provider](https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html):
```

2022-09-28 10:00 UTC, jwitz commented on astro/airflow-alerts.md
> +    ```
```suggestion
    ```

```

2022-09-28 11:37 UTC, merged