Reorganize and Update Connect Astro to External Data Services
astronomer/docs pull request #1275
Opened 2022-09-28 15:15 UTC by kwcanuck

Resolves #1267

2022-09-28 20:54 UTC, dnarain-astro commented
I'll just bundle up a whole bunch of comments in one. This one is AWS centric (mostly):
* Title: Should the title be Connect Astro to Data Sources?  Or something else but more explicit that it is about data source connectivity only
* For Authentication, put AWS IAM roles first
* For the other tab:
- Title: AWS Access Keys 
- Description: Astro supports the full range of connection options provided by Airflow (https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html). You can provide your AWS Access Key and Secret when creating an Airflow AWS Connection. 
Astronomer encourages you to use an external secrets back end to store your secrets such as AWS Access Keys and Secrets. Further details are provided in the documentation https://docs.astronomer.io/astro/secrets-backend

2022-09-28 21:01 UTC, dnarain-astro commented
This comment is for GCP:
Authentication:
* Show Workload Identity first 
 * Call the other tab Service Account Keys 
 * Text for the Service Account Keys tab:
 Astro supports all connectivity options of the Airflow Google Cloud Connection (https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html)
 
When creating a Google Cloud Connection, you can specify a service account key in JSON format, or a secret name which holds the key. 
 
 Astronomer strongly suggests using an external Secrets Manager to store your secrets such as service keys. For more details see https://docs.astronomer.io/astro/secrets-backend?tab=gcp#setup

2022-09-28 21:24 UTC, dnarain-astro commented
Next comment is for Azure

Azure Private Link (there is a space between Private and Link - who knew?) 

Use Azure Private Link to create private connections from Astro to your Azure services without exposing your data to the public internet.

Astro clusters are pre-configured with the following Azure Private Endpoints:
* Postgres
* Blob 

To request additional endpoints contact Astronomer Support.  

When adding a Private Endpoint, Astronomer will also create the corresponding private DNS zone and CNAME records to allow you to address the service via its Private Link name.  You may need to modify your DAGs to address the service via its Private Link name (e.g. StorageAccountA.privatelink.blob.core.windows.net instead of StorageAccountA.blob.core.windows.net)



You'll incur additional Azure  infrastructure costs for every Private Endpoint that you use. See [Azure Private Link pricing](https://azure.microsoft.com/en-us/pricing/details/private-link/#pricing).

2022-09-29 15:34 UTC, dnarain-astro reviewed
oops, there is no postgres privatelink its just a private connection - major difference

2022-09-29 15:34 UTC, dnarain-astro commented on astro/connect-azure.md
> +- Azure PostgreSQL
```suggestion
```

2022-09-29 18:35 UTC, stuart23 requested changes

2022-09-29 18:35 UTC, stuart23 commented on sidebarsAstro.js
> -            'connect-external-services',
If we are removing the link, can we remove the actual page so we don't have any stale documentation?

2022-09-30 00:28 UTC, melugoyal commented on astro/connect-azure.md
> +Every Astro cluster runs in a dedicated Virtual Private Network (VPC). To set up a private connection between an Astro VPC and an Azure Virtual Network (VNet), you can create a VPC peering connection
i think this should say VNet everywhere. the mixed wording between VPC and VNet is a bit confusing

2022-09-30 00:28 UTC, melugoyal commented on astro/connect-azure.md
> +- Blob
1) it's a bit awkward to have a bulleted list with a single item
2) i don't think we actually need to mention this. private endpoint is separate from private link. this private endpoint that we create just allows us to talk to our blob storage account (where we store the task logs) via private endpoint

2022-09-30 11:44 UTC, jwitz requested changes
Thank you @kwcanuck , this is a huge undertaking. Some general thoughts that I explain more in the comments:

- I think we are describing "authorization" each time we mention "authentication"
- Because we have these connections organized as tabs and refer to them as "options", I feel like we're telling people they should only have one of these connections configured at a time. Is this the case? Will someone setting up VPC peering ever be interested in using public endpoints, and if not how do they set up Airflow connections in their DAG code? 
- There's some missing use case information here for a few of these connection types. Can you and @dnarain-astro work on teasing out more of the "why" of these connections? For example: once you set up Transit Gateway, what does that enable at the Airflow/ Astro level?  You might need to talk with someone who's closer to the DAG authoring experience for these details as well.

2022-09-30 11:44 UTC, jwitz commented on astro/connect-azure.md
> +- Blob
Yeah we should be clear about what type of endpoints you might want to/ can request. If we can't think of any, this might be an infrastructural detail that doesn't need to be further modified by users.

2022-09-30 11:44 UTC, jwitz commented on astro/connect-azure.md
> +When Astronomer support adds an Azure private endpoint, a corresponding private DNS zone and Canonical Name (CNAME) records are also created to allow you to address the service by its private link na
```suggestion
When Astronomer support adds an Azure private endpoint, a corresponding private DNS zone and Canonical Name (CNAME) records are also created to allow you to address the service by its private link name. In some circumstances, you might need to modify your DAGs to address the service by its private link name. For example, `StorageAccountA.privatelink.blob.core.windows.net` instead of `StorageAccountA.blob.core.windows.net`.
```

2022-09-30 11:44 UTC, jwitz commented on astro/connect-azure.md
> +When you create an Azure storage account, two 512-bit storage account access keys are generated for the account. You can use these keys to authorize access to data in your storage account with Shared
Assume we'll get steps for how to configure these keys for clusters similar to the IAM role setup in the AWS doc?

2022-09-30 11:44 UTC, jwitz commented on astro/connect-azure.md
> +Authentication is the process of verifying a user's identity before allowing them access to organizational applications and resources.
Same edits as in the AWS section

2022-09-30 11:44 UTC, jwitz commented on astro/connect-gcp.md
> +    :::
```suggestion
  :::info

  GCP has a 30-character limit for service account names. For Deployment namespaces which are longer than 24 characters, use only the first 24 characters when determining your service account name.

  For example, if your Google Cloud project is named `astronomer-prod` and your Deployment namespace is `nuclear-scintillation-2730`, the service account name is:

  ```text
  astro-nuclear-scintillation-27@astronomer-prod.iam.gserviceaccount.com
  ```

  To determine if your Deployment namespace meets or exceeds the character limitations, run the following command:

  ```sh
  echo astro-$(echo <deployment-namespace> | cut -c -24)
  ```

  :::
```

2022-09-30 11:44 UTC, jwitz commented on astro/connect-gcp.md
> +    :::
Ugh, GitHub messed up this suggestion. The gist is "Remove two spaces from every line in the `:::info` note

2022-09-30 11:44 UTC, jwitz commented on astro/connect-gcp.md
> +## Authentication options
Same edits as on AWS doc

2022-09-30 11:44 UTC, jwitz commented on astro/connect-gcp.md
> +Private Service Connect allows Astro to access GCP data that belongs to different groups, teams, projects, and organizations.
Will there be more content in this section?

2022-09-30 11:44 UTC, jwitz commented on astro/connect-gcp.md
> +Every Astro cluster runs in a dedicated Virtual Private Network (VPC). To set up a private connection between an Astro VPC and a GCP VPC, you can create a VPC peering connection. VPC peering ensures
```suggestion
Every Astro cluster runs in a dedicated Virtual Private Cloud (VPC). To set up a private connection between an Astro VPC and a GCP VPC, you can create a VPC peering connection. VPC peering ensures private and secure connectivity, reduces network transit costs, and simplifies network layouts.
```

2022-09-30 11:44 UTC, jwitz commented on sidebarsAstro.js
> -            'connect-external-services',
Do you mean stale links? We could make a redirect from the old doc to the landing page of this new doscet, which shows links for each cloud's setup docs. @kwcanuck we should talk more generally about redirects for this page, because I think we link to it quite a bit

2022-09-30 11:51 UTC, kwcanuck commented on sidebarsAstro.js
> -            'connect-external-services',
@stuart23 I'm not sure you are referencing the correct version of sidebarsAstro.js. The connect-external-services reference no longer appears in the location you identified. Here is how the current file appears:

![image](https://user-images.githubusercontent.com/104205257/193263426-ec935e73-db04-40ed-9dd5-2583bcfd9101.png)

A search for _connect-external-services_ in the file doesn't return any results:

![image](https://user-images.githubusercontent.com/104205257/193263628-fc4bfc26-b8d7-4e6e-bb1e-12dd8f1ffb72.png)

2022-09-30 11:56 UTC, kwcanuck commented on sidebarsAstro.js
> -            'connect-external-services',
@jwitz here are the references to connect-external-services:

![image](https://user-images.githubusercontent.com/104205257/193264311-a366cb58-436a-4674-9549-c3e54551c1ba.png)

As you can see, it's not a significant number. I'll manually update the references. Good catch, though.

2022-09-30 12:13 UTC, jwitz commented on sidebarsAstro.js
> +            description: 'Connect Astro to external data sources.'
We should have a more detailed description here. This sentence appears at the top of the index page, so it should be a more comprehensive representation of what's in each doc. I think it's okay to be a little redundant with the overview text in the individual docs.

2022-09-30 12:42 UTC, kwcanuck commented on astro/connect-azure.md
> +Every Astro cluster runs in a dedicated Virtual Private Network (VPC). To set up a private connection between an Astro VPC and an Azure Virtual Network (VNet), you can create a VPC peering connection
@melugoyal I have updated the VPC references as you recommended.

2022-09-30 12:44 UTC, kwcanuck commented on astro/connect-azure.md
> +- Blob
@melugoyal the single bullet point was the result of an edit yesterday that I had not addressed yet. I have modified the existing text.

2022-09-30 13:33 UTC, kwcanuck commented on sidebarsAstro.js
> +            description: 'Connect Astro to external data sources.'
@jwitz this description matches what you provided for [_Install Astro_](https://deploy-preview-1275--gallant-neumann-56599d.netlify.app/astro/category/install-astro). If you think that there should be a "...more comprehensive representation of what's in each doc" here, I would argue that you should do the same for the _Install_ landing page for consistency.

2022-09-30 14:37 UTC, afastronomer commented on astro/connect-aws.md
> +To retrieve the ID of any Astro VPC, contact [Astronomer support](https://cloud.astronomer.io/support). If you have more than one Astro cluster, request the VPC ID of each cluster.
This section is about network communication between Astro and external resources. Create Airflow connection or call resource directly - depends on DAG, but without those steps external resources will be not accessible in any way.

2022-09-30 14:43 UTC, afastronomer commented on astro/connect-aws.md
> +By default, Astronomer support activates the **Enable DNS Name** option on supported AWS PrivateLink endpoint services.  With this option enabled, you can make requests to the default public DNS serv
It means when any application tries to access resource by name.

2022-09-30 15:50 UTC, dnarain-astro commented
> * I think we are describing "authorization" each time we mention "authentication"
Its messy - it could be one or both, depending on the mechanism used.  For example if you specify an access key, you are authenticating and authorizing, but if you use a role/identity, you are only authorizing.  But, you make a good point and this can be clarified further.

> * Because we have these connections organized as tabs and refer to them as "options", I feel like we're telling people they should only have one of these connections configured at a time. Is this the case? Will someone setting up VPC peering ever be interested in using public endpoints, and if not how do they set up Airflow connections in their DAG code?

No, this is exactly not the case :-) The idea is to tell people they have options and can decide on a per-data-service basis.  Any suggestions on how we could make this clearer?


> * There's some missing use case information here for a few of these connection types. Can you and @dnarain-astro work on teasing out more of the "why" of these connections? For example: once you set up Transit Gateway, what does that enable at the Airflow/ Astro level?  You might need to talk with someone who's closer to the DAG authoring experience for these details as well.

The main idea that I want to get across is that there are 2 parts to this - one is network connectivity (which the data practitioner should not have to think about at all) and the other is authentication/authorization (which they do - because it dictates how they set up connections).  Transit gateways fall into the network connectivity bucket - the practitioner should not have to spend a moment thinking about this. 

The *right* thing to do may be to break these out into two completely different sections (i.e go from 1 doc to 6, not fro 1 to 3 as we are doing now). From my perspective, I gave that idea some thought and thought that it might be better to do that as step 2 (step 1 being what we are doing now -  take the 1 doc and split it out into 3 clouds)

2022-09-30 15:53 UTC, stuart23 commented on sidebarsAstro.js
> -            'connect-external-services',
Thanks y'all.

I meant this page: https://github.com/astronomer/docs/blob/main/astro/connect-external-services.md

Because it will not be linked anywhere anymore, can we remove it entirely in this PR?

2022-09-30 15:57 UTC, stuart23 commented on astro/connect-aws.md
> +To retrieve the ID of any Astro VPC, contact [Astronomer support](https://cloud.astronomer.io/support). If you have more than one Astro cluster, request the VPC ID of each cluster.
I've always thought of it like the customer knows what option they need before they come to us, and then we have the instructions to help them implement that option. While I think it might be good to add context on which option to use, that is more of an architectural decision and depends on a lot on what the customer prefers or how the rest of their organization is configured, so we would not want to cover it in depth.

2022-09-30 15:59 UTC, stuart23 commented on astro/connect-aws.md
> +By default, Astronomer support activates the **Enable DNS Name** option on supported AWS PrivateLink endpoint services.  With this option enabled, you can make requests to the default public DNS serv
Can we differentiate "default public DNS service name" vs "public DNS name"? I think they are too similar to understand the difference without looking at the example. Is there a definition of these terms in the AWS docs?

2022-09-30 16:47 UTC, jwitz commented on astro/connect-gcp.md
> +
```suggestion
  ```

```

2022-09-30 20:55 UTC, stuart23 requested changes
Can we differentiate "default public DNS service name" vs "public DNS name"? I think they are too similar to understand the difference without looking at the example. Is there a definition of these terms in the AWS docs?

Also delete https://github.com/astronomer/docs/blob/main/astro/connect-external-services.md and then you have my blessing :pray:

2022-10-03 12:38 UTC, jwitz commented on sidebarsAstro.js
> -            'connect-external-services',
Oh yeah good call. @kwcanuck can you delete `connect-external-services.md` as part of this update?

2022-10-03 12:40 UTC, jwitz approved these changes
Looking at @stuart23 's comments, I think it's alright to publish more general content about supporting these connections even if we don't have specific use cases/ steps. I do still think we could use more information about the connection types that currently only have 1 line, but if there's plans for that in the future then I'm cool with publishing this now!

2022-10-03 13:17 UTC, kwcanuck commented on astro/connect-aws.md
> +By default, Astronomer support activates the **Enable DNS Name** option on supported AWS PrivateLink endpoint services.  With this option enabled, you can make requests to the default public DNS serv
@stuart23 I wasn't clear what edit you were requesting here, but I've added a link to the AWS DNS hostnames doc.

2022-10-03 16:01 UTC, stuart23 approved these changes
Thanks @kwcanuck for all your work!

2022-10-03 17:10 UTC, merged