Cli 1.6 docs follow-up
astronomer/docs pull request #1289
Opened 2022-09-29 17:02 UTC by jwitz

2022-09-29 17:02 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-create.md
> +Create a [worker queue](../configure-deployment-resources.md#worker-queues).
```suggestion
Create a [worker queue](configure-deployment-resources.md#worker-queues).
```

2022-09-29 17:02 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-delete.md
> +Update the settings for an existing [worker queue](../configure-deployment-resources.md#worker-queues).
```suggestion
Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues).
```

2022-09-29 17:02 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-update.md
> +Update the settings for an existing [worker queue](../configure-deployment-resources.md#worker-queues).
```suggestion
Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues).
```

2022-09-29 17:13 UTC, kwcanuck commented on astro/cli/astro-dev-object-export.md
> +Export Ariflow variables, connections, and pools from a locally running environment to a file and format of your choice.
```suggestion
Export Airflow variables, connections, and pools from a locally running environment to a file and format of your choice. 
```

2022-09-29 17:14 UTC, kwcanuck commented on astro/cli/astro-dev-object-export.md
> +| `-e`,`--env`            | Location of the file to export Airflow objects to as Astro environment variables. Use this flag only with `--env-export`. The default file path is `env`.
```suggestion
| `-e`,`--env`            | Location of the file to export Airflow objects to as Astro environment variables. Use this option only with `--env-export`. The default file path is `env`.                                                                          | Any valid filepath                 |
```

2022-09-29 17:15 UTC, kwcanuck commented on astro/cli/astro-dev-object-import.md
> +Import Ariflow variables, connections, and pools to a locally running environment from a YAML configuration file.
```suggestion
Import Airflow variables, connections, and pools to a locally running environment from a YAML configuration file.
```

2022-09-29 17:19 UTC, kwcanuck commented on astro/develop-project.md
> +Once you save these values in your `airflow_settings.yaml`, start your local environment and run:
```suggestion
Save the modified `airflow_settings.yaml` file, start your local environment, and then run: 
```

2022-09-30 09:37 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-update.md
> +
```suggestion

## Examples
```

2022-10-02 19:55 UTC, paolaperaza requested changes
Few comments here @jwitz -- give em a look

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +Create a [worker queue](configure-deployment-resources.md#worker-queues).
```suggestion
Create a [worker queue](configure-deployment-resources.md#worker-queues on) for a Deployment on Astro. This command is functionally identical to creating a worker queue in the Cloud UI.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type enabled on the Deployment |
Let's shuffle up the order here to make more sense?

- Deployment-name
- Deployment-id
- worker queue name
- minimum worker count before maximum worker count
- and then anything else

Try to keep it parallel to Cloud UI order

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +# Creates a new worker queue in a Deployment, CLI prompts you for all configuration information.
```suggestion
# Creates a new worker queue for a Deployment with ID `cl03oiq7d80402nwn7fsl3dmv`. The Astro CLI prompts you for configuration information.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +# Creates a new worker queue in a Deployment, CLI prompts you for Deployment information.
```suggestion
# Creates a new worker queue with specified configurations. The. Astro CLI prompts you for Deployment information.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type enabled on the Deployment |
```suggestion
| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type as long as the worker type is enabled for the cluster in which the Deployment exists. For example, `m6i.2xlarge` or `c6i.4xlarge` |
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +| `-f` `--force` | Skip prompting the user to confirm the update | `` |
Does this force flag actually exist on create?

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-create.md
> +## Examples
Did we want to add `Related Commands` section here? I'd add:

- astro deployment worker-queue delete
- astro deployment worker-queue update
- astro deployment update

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-update.md
> +Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues).
```suggestion
Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues) in a Deployment on Astro. This is functionally identical to modifying the settings of a worker queue in the Cloud UI.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-delete.md
> +Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues).
```suggestion
Delete an existing [worker queue](configure-deployment-resources.md#worker-queues) in a Deployment on Astro. This is functionally identical to deleting a worker queue in the Cloud UI.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-update.md
> +| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type enabled on the Deployment |
Same here -- brush up the order and add the same descriptor as above for `worker-type`

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-update.md
> +```
Add section on related commands

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-deployment-worker-queue-delete.md
> +
Add section on related commands

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +Export Airflow variables, connections, and pools from a locally running environment to a file and format of your choice.
```suggestion
Export Airflow variables, connections, and pools from a locally running environment to a local file and format of your choice. You can choose to export all or some values by specifying flags to the command.

By default, all values will be exported to the `airflow_settings.yaml` file in your Astro project.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +astro dev object export [flags]
Do we usually specify `[flags]` in these docs?

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +By default, the command exports all variables, connections, and pools as YAML configurations to `airflow_settings.yaml`.
```suggestion
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +
```suggestion
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +| `-v`,`--variables`            | Export variables to a given local file | ``                 |
Again -- switch up order here?

- connections
- variables
- pools
- settings-file
- --env
- --env-export

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +# Exports pools from the local Airflow environment to `airflow_settings.yaml`
```suggestion
# Exports only pools from the local Airflow environment to `airflow_settings.yaml`
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +# Astro variables to a file in the project named `myairflowenv.env`
```suggestion
# environment variables to a file named `myairflowenv.env`
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-export.md
> +```
Related commands

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-import.md
> +Import Airflow variables, connections, and pools to a locally running environment from a YAML configuration file.
```suggestion
Import Airflow variables, connections, and pools from a configuration file to a locally running Airflow environment. When you run this command, the Airflow objects you import from your specified file will be saved to your local metadata database and appear in the Airflow UI of your local Airflow environment.
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-import.md
> +astro dev object import [flags]
```suggestion
astro dev object import
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-import.md
> +
```suggestion
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/astro-dev-object-import.md
> +```
Related commands

2022-10-02 19:55 UTC, paolaperaza commented on astro/cli/release-notes.md
> +- Fixed an issue where the Astro CLI generated incorrect URLs for accessing Deployments
```suggestion
- Fixed an issue where the Astro CLI generated incorrect URLs for the Deployment dashboard
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/configure-deployment-resources.md
> +You can alternatively create worker queues using the Astro CLI. See [`astro deployment worker-queue create`](cli/astro-deployment-worker-queue-create.md).
```suggestion
If you prefer, you can also create worker queues using the Astro CLI. See [`astro deployment worker-queue create`](cli/astro-deployment-worker-queue-create.md).
```

2022-10-02 19:55 UTC, paolaperaza commented on astro/develop-project.md
> +Save the modified `airflow_settings.yaml` file, start your local environment, and then run:
```suggestion
Save the modified `airflow_settings.yaml` file and run:
```

2022-10-03 09:43 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-create.md
> +| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type enabled on the Deployment |
I'd prefer for reference docs to be parallel to the help command in the CLI, which means we'd keep them in alphabetical order. Because these are CLI docs first, we should organize them with the CLI in mind vs the feature they're related to.

2022-10-03 09:45 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-create.md
> +| `-t`,`--worker-type`          | The worker type of the worker queue          | Any worker type enabled on the Deployment |
I don't think we need rich examples in this section because of the following "Examples" section.

2022-10-03 10:02 UTC, jwitz commented on astro/cli/astro-deployment-worker-queue-delete.md
> +Update the settings for an existing [worker queue](configure-deployment-resources.md#worker-queues).
I'm not sure we can claim that this is functionally identical. The `--force` flag has no equivalent on the Cloud UI yet

2022-10-03 10:10 UTC, jwitz commented on astro/cli/astro-dev-object-export.md
> +Export Airflow variables, connections, and pools from a locally running environment to a file and format of your choice.
IMO we don't need to mention the capabilities of flags in the overview descriptions of these commands

2022-10-03 10:11 UTC, jwitz commented on astro/cli/astro-dev-object-export.md
> +| `-v`,`--variables`            | Export variables to a given local file | ``                 |
See above command - would prefer to keep alphabetical/ parallel with the CLI

2022-10-03 10:12 UTC, jwitz commented on astro/cli/astro-dev-object-export.md
> +# Astro variables to a file in the project named `myairflowenv.env`
We should be more explicit that these variables are mainly meant for use on Astro

2022-10-03 10:18 UTC, jwitz commented on astro/cli/astro-dev-object-import.md
> +Import Airflow variables, connections, and pools to a locally running environment from a YAML configuration file.
I don't know how the second sentence adds to the understanding of what the command does. I would assume that someone looking to import these objects already knows how they're stored and shown in the Airflow UI. We're not describing the command here, but rather the behavior of variables themselves.

2022-10-03 10:35 UTC, jwitz commented on astro/develop-project.md
> +Save the modified `airflow_settings.yaml` file, start your local environment, and then run:
We need to have the step for starting a local environment because this command doesn't work without that

2022-10-03 10:35 UTC, jwitz commented
@paolaperaza This is good for another look! Left some replies and changes

2022-10-06 09:57 UTC, merged