Astro 10/4 release notes
astronomer/docs pull request #1310
Opened 2022-10-04 13:28 UTC by jwitz

Based on https://app.zenhub.com/workspaces/developer-productivity-and-readiness-6242176c89ed9000197ec734/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvODMyMjU and reports about metric improvements

2022-10-04 13:29 UTC, jwitz commented on astro/release-notes.md
> +- Moved `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER` configurations from Astro Runtime to the control plane
@paolaperaza Is this worth documenting before the corresponding change has been made in Runtime?

2022-10-04 13:33 UTC, kwcanuck commented on astro/release-notes.md
> +### Additional imporvements
```suggestion
### Additional improvements 
```

2022-10-04 13:35 UTC, kwcanuck commented on astro/release-notes.md
> +These permissions might change in the future to enable new Astro features or to further fine-tune Astronomer's permissions within specific contexts.
```suggestion
These permissions might change in the future to enable new Astro features or to refine permissions for specific contexts. 
```

2022-10-04 13:37 UTC, kwcanuck commented on astro/release-notes.md
> +- In the Cloud UI, the maximum time window for Deployment metrics has been extended from 24 hours to 7 days.
```suggestion
- In the Cloud UI, the maximum time for Deployment metrics has been extended from 24 hours to 7 days.
```

2022-10-04 13:38 UTC, kwcanuck commented on astro/release-notes.md
> +- The [Deployment overview metrics](deployment-metrics.md#deployment-overview) now show metrics only for the `default` worker queue instead of an aggregate of all worker queues.
```suggestion
- The [Deployment metrics overview](deployment-metrics.md#deployment-overview) now shows metrics for the `default` worker queue instead of an aggregate of all worker queues.
```

2022-10-04 13:39 UTC, kwcanuck commented on astro/release-notes.md
> +- Removed misleading maximum CPU/ Memory lines from Deployment metric graphs
```suggestion
- Removed misleading maximum CPU and memory lines from Deployment metric graphs
```

2022-10-04 13:40 UTC, kwcanuck approved these changes

2022-10-04 21:56 UTC, dnarain-astro commented on astro/release-notes.md
> +The Astronomer remote management role for AWS clusters now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions it c
Operational roles created by Astro now have a [permissions boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions they can perform.  These roles are now limited to the following actions:

2022-10-04 21:57 UTC, dnarain-astro requested changes

2022-10-04 21:57 UTC, dnarain-astro commented on astro/release-notes.md
> +The Astronomer remote management role for AWS clusters now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions it c
We haven't made our way to the cross account role yet, this release is just addressing the roles created per cluster.  

The cross account role will be updated in phase 2 (coming soon, but not here yet)

2022-10-04 23:30 UTC, nkapinos approved these changes
LGTM

2022-10-05 11:55 UTC, jwitz commented on astro/release-notes.md
> +The Astronomer remote management role for AWS clusters now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions it c
```suggestion
Operational roles which are created by Astro for AWS clusters now have new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html). These boundaries limit the actions they can perform to a subset of their default `AdministratorAccess` permissions. These roles are now limited to the following actions across all contexts:
```

2022-10-05 14:45 UTC, dnarain-astro commented on astro/release-notes.md
> +The Astronomer remote management role for AWS clusters now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions it c
I think adding AdministratorAccess here will confuse the user.  The generated roles never had AdministratorAccess permissions - they COULD have had them if (because the role that created them - astronomer-remote-management - has it), what we have done is reduce the risk of privilege escalation (which is another very overloaded phrase that  I didn't feel comfortable using it in a release note without giving a lot of context)

2022-10-06 11:44 UTC, paolaperaza approved these changes

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +### New permissions boundaries for managed AWS clusters
```suggestion
### New permissions boundary for managed AWS Accounts
```

This is at account level, not cluster level I'm pretty sure

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +The Astronomer remote management role for AWS clusters now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) to limit the actions it c
```suggestion
The remote management role that Astronomer assumes on dedicated customer AWS accounts now has new [permissions boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) that limit the role to a subset of its `AdministratorAccess` permissions. The remote management role is now limited to the following actions across all contexts:
```

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +- `AIRFLOW__WEBSERVER__EXPOSE_CONFIG=NON-SENSITIVE-ONLY` is now set in the data plane so that sensitive webserver configurations cannot be viewed in the Airflow UI.
```suggestion
- Users with the required permissions can now access a **Configuration** tab in the **Admin** menu of the Airflow UI. This page no longer shows sensitive values in plain-text and can be used to verify all configurations running on your Deployment.
```

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +- Moved `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER` configurations from Astro Runtime to the control plane
I think let's remove this actually -- it's a system change that doesn't affect the user at all

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +- Removed misleading maximum CPU/ Memory lines from Deployment metric graphs
Feels like odd phrasing here... what was happening previously?

2022-10-06 11:44 UTC, paolaperaza commented on astro/platform-variables.md
> +| `AIRFLOW__WEBSERVER__EXPOSE_CONFIG=NON-SENSITIVE-ONLY` | Determines whether sensitive infomration about webserver configurations is exposed in the Airflow UI | `NON-SENSITIVE-ONLY` |
```suggestion
| `AIRFLOW__WEBSERVER__EXPOSE_CONFIG` | Exposes the **Configuration** tab of the Airflow UI and hides sensitive values | `NON-SENSITIVE-ONLY` |
```

2022-10-06 11:44 UTC, paolaperaza commented on astro/release-notes.md
> +
@dnarain-astro @jwitz Think these should be either in our AWS install or reference doc, especially if they'll change over time and we get a ton of feedback about it?

Just a thought, will let you two decide

2022-10-06 13:51 UTC, jwitz commented on astro/release-notes.md
> +- Moved `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER` configurations from Astro Runtime to the control plane
```suggestion
```

2022-10-06 13:52 UTC, jwitz commented on astro/release-notes.md
> +- Removed misleading maximum CPU/ Memory lines from Deployment metric graphs
We had a maximum line that was showing the maximum CPU and memory for each worker, but with different worker types running at the same time this line would always be inaccurate, as different worker types have different maximums

2022-10-06 13:53 UTC, merged