Add Documentation for Astronomer Hosted Data Plane
astronomer/docs pull request #1338
Opened 2022-10-13 15:19 UTC by kwcanuck

Resolves #1328, resolves #1314 

A VERY preliminary draft to get the hosted data plane documentation moving.

2022-10-14 11:23 UTC, jwitz requested changes
A few initial comments here @kwcanuck but I think we're headed in the right direction!

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +title: 'Install Astro on the Astronomer dataplane'
```suggestion
title: 'Install Astro on an Astronomer-hosted cloud'
```
"Astronomer data plane" is still how some customers might think of the BYO data plane, I think we should be explicit about the hosting aspect here. I'm also not sure we need to mention "Data plane" too explicitly until we explain what the installation process is.

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +description: Install Astro clusters on the Astronomer dataplane.
```suggestion
description: Get started with Astro on Astronomer's own cloud.
```

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +
```suggestion

This setup assumes that you've already provided Astronomer with: 

- A preferred cloud provider of either Amazon Web Services (AWS) or Google Cloud Platform (GCP)
- A preferred region to install your first cluster in. See region lists for [AWS](https://aws.amazon.com/about-aws/global-infrastructure/regions_az/) and [GCP](https://cloud.google.com/compute/docs/regions-zones).
- Optional. A preferred worker instance type for your first cluster. See [AWS cluster configurations](resource-reference-aws.md#worker-node-types) and [GCP cluster configurations](resource-reference-gcp.md#worker-node-pools).
- An email address for your first Astro user.

If you haven't yet provided this information to Astronomer, contact your Astronomer representative. 
```

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +Once you've provided Astronomer with the information for your setup, Astronomer finishes creating your first cluster on the Astronomer dataplane.
```suggestion
Once you've provided Astronomer with the information for your setup, Astronomer finishes creating your first cluster on Astronomer's cloud.
```

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +
We need a log in step here - it can be identical to the one in the BYO doc

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +This is where you'll find instructions for completing the Astro installation process on the Astronomer dataplane, including prerequisites and the steps required to allow Astronomer support to provisi
```suggestion
This is where you'll find instructions for completing the Astro installation process on the Astronomer data plane, including prerequisites and the steps required to allow Astronomer support to provision resources in your network.

Creating Astro clusters on Astronomer's cloud eliminates the need for Astronomer to have privileged access to your own cloud. All data hosted in Astronomer's guide is treated in accordance with Astronomer's HIIPAA, SOC2, and GDPR certifications. 
```

2022-10-14 11:23 UTC, jwitz commented on astro/bring-your-own.md
> +sidebar_label: 'Bring your own cloud'
I might have miscommunicated this during the meeting, but I think we should actually keep all of the BYO cloud installation guides as _separate_ guides and have only one "Hosted" doc for all clouds we might host on in the future. A single doc for all clouds is looking unweildy, especially now that there's tabs within tabs. Let's leave these docs alone for now - later we might want to add a brief note about seeing the "Hosted" doc in case they're lost, but I think that's the only thing we'd need to change here.

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +## Prerequisites
We could also include VPC peering prerequisites for AWS and GCP here, since those would be the same. Although it might be better to link out to our Connectivity docs for those procedures instead.

2022-10-14 11:23 UTC, jwitz commented on astro/hosted-dataplane.md
> +---
Before this review is done, I'll try to get a custom image of the Astro logo to include in the menu for these docs :)

2022-10-14 11:42 UTC, kwcanuck commented on astro/bring-your-own.md
> +sidebar_label: 'Bring your own cloud'
@jwitz FYI - this was the comment in the issue Paola opened:

![image](https://user-images.githubusercontent.com/104205257/195838819-34562fa2-8fbb-46a3-be96-e9d8edcb39d8.png)

2022-10-14 11:56 UTC, kwcanuck commented on astro/hosted-dataplane.md
> +
@jwitz - done

2022-10-14 11:59 UTC, kwcanuck commented on astro/bring-your-own.md
> +sidebar_label: 'Bring your own cloud'
@jwitz I have returned the standalone topics to the TOC. I don't think the single topic is unwieldy. Users wanting to install Astro on a specific cloud type will only focus on the relevant procedures and select the appropriate tab.  I think it works well having only two topics to select. Your mileage obviously varies!

2022-10-14 12:46 UTC, kwcanuck commented on astro/hosted-dataplane.md
> +## Prerequisites
@jwitz a bullet has been added with this information.

2022-10-14 13:18 UTC, kwcanuck commented
@jwitz back to you for secondary review.

2022-10-17 14:17 UTC, jwitz requested changes
@kwcanuck Do you have some conflicting commits in here? I see that we both have individual BYO Cloud install guides, as well as a tabbed BYO guide. Additionally, one of the tabs in the new BYO guide is "Hosted cloud", but we also have a standalone doc for that.

Gonna hold off on further review until I have context for the current set of changes.

2022-10-19 11:14 UTC, kwcanuck commented
Review requested from @dnarain-astro 2022-10-18.

2022-10-20 09:27 UTC, jwitz commented on astro/hosted-dataplane.md
> +This is where you'll find instructions for completing the Astro installation process on the Astronomer-hosted cloud.
Let's remove all mention of Azure from this doc.

2022-10-20 09:29 UTC, jwitz commented on astro/hosted-dataplane.md
> +id: hosted-dataplane
Nitpicky but can we make the file name / id `hosted-data-plane` or `install-astro-hosted`?

2022-10-20 09:30 UTC, jwitz approved these changes
The "Hosted cloud" changes LGTM @kwcanuck ! Lets get @dnarain-astro and @paolaperaza 's review on this before we merge.

2022-10-20 09:34 UTC, jwitz commented on astro/bring-your-own.md
> +---
I think that regardless of the team's opinion on the hosted data plane docs, this reorganization is out of the scope of this feature. Can we remove this doc from the PR so that reviewers can focus on the hosted data plane docs and the core decision here, which is whether we have a "BYO" / "Hosted" tab split for each individual cloud provider or a standalone doc for hosted installations?

2022-10-20 20:57 UTC, dnarain-astro requested changes
We don't have GCP support yet FYI.

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +- Your preferred cloud provider. The supported options are: Amazon Web Services (AWS) and Google Cloud Platform (GCP).
```suggestion
```

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +- Your preferred cloud provider. The supported options are: Amazon Web Services (AWS) and Google Cloud Platform (GCP).
We only have AWS right now

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +- Your preferred cluster installation region. See the supported region lists for [AWS](resource-reference-aws.md#aws-region) and [GCP](resource-reference-gcp.md#gcp-region).
We don't have GCP yet, its only AWS
```suggestion
- Your preferred cluster installation region. See the supported region lists for [AWS](resource-reference-aws.md#aws-region).
```

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +- Optional. Your preferred worker instance type for your first cluster. See [AWS cluster configurations](resource-reference-aws.md#worker-node-types) and [GCP cluster configurations](resource-referen
```suggestion
- Optional. Your preferred worker instance type for your first cluster. See [AWS cluster configurations](resource-reference-aws.md#worker-node-types).
```

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +- Optional. Your VPC peering requirements for [AWS](install-aws#vpc-peering-prerequisites-optional) and [GCP](install-gcp#vpc-peering-prerequisites-optional).
```suggestion
- Optional. Your VPC peering requirements for [AWS](install-aws#vpc-peering-prerequisites-optional).
```

2022-10-20 20:57 UTC, dnarain-astro commented on astro/hosted-data-plane.md
> +This process can take some time. Wait for confirmation that the installation is successful before you access Astro and create a Deployment.
```suggestion
Wait for confirmation that the installation is successful before you access Astro and create a Deployment.
```

2022-10-20 23:27 UTC, melugoyal commented on astro/hosted-data-plane.md
> +title: 'Install Astro on an Astronomer-hosted cloud'
i've always found the verb "Install" when referring to a cloud/SAAS service a bit heavy/manual -- sounds to me like the customer needs to install something on their laptop. maybe "deploy" or "setup" would be better? particularly in the context of hosted data planes

2022-10-21 11:38 UTC, kwcanuck commented on astro/hosted-data-plane.md
> +title: 'Install Astro on an Astronomer-hosted cloud'
@melugoyal thanks for the feedback. This topic appears in a section titled _Install Astro_ and _Install_ is included in the titles of the other topics within this section. So, _Install_ has been used here for consistency.  Also, when discussing computer applications, _install_ and _set up_ (the verb) have similar meanings.  Both words are used to describe the process of making a program ready for execution. We don't use _deploy_ frequently because the meaning is not easily understood by all readers.

I understand your concern. In this instance, a user is not installing anything. They are accessing Astro _after_ it has been set up by Astronomer support. I'll think about this some more - _access_ might be the better word choice here.

2022-10-21 11:44 UTC, kwcanuck commented on astro/hosted-data-plane.md
> +- Your preferred cloud provider. The supported options are: Amazon Web Services (AWS) and Google Cloud Platform (GCP).
@dnarain-astro the text has been updated.

2022-10-24 21:45 UTC, dnarain-astro approved these changes

2022-10-27 05:11 UTC, paolaperaza approved these changes
We're close here @kwcanuck ! A couple of comments and then you can port this over to GCP + Azure.

Note that GCP and Azure can be in `Private Preview`

2022-10-27 05:11 UTC, paolaperaza commented on astro/install-aws.md
> +3. Select one of the following options to access the Cloud UI:
Feels weird to say `Select` because you don't select, you just "do it"?

2022-10-27 05:11 UTC, paolaperaza commented on astro/install-aws.md
> +    - To authenticate with an identity provider (IdP), click **Continue with SSO**, enter your username and password, and then click **Sign In**.
Thoughts on still keeping the "tip" for IdP? If this is the first cluster and install, there's just no way the customer will already have an IdP set up -- I think ok to leave that one as is

(the rest you can use to create your account so it's fine)

2022-10-27 05:11 UTC, paolaperaza commented on astro/install-aws.md
> +    If you're the first person in an Organization to authenticate, you're added as a Workspace Admin to a new Workspace named after your Organization. You can add other team members to the Workspace
```suggestion
    If you're the first person in your Organization to authenticate, you'll be granted Organization owner permissions. You can create a Workspace and add other team members to the Workspace without the assistance of Astronomer support. See [Create a Workspace](manage-workspaces.md#create-a-workspace) and [Add a user](add-user.md). To integrate an identity provider (IdP) with Astro, see [Set up an identity provider](configure-idp.md).
```

(or it's fine, you can keep IdP here -- tip seems nice but I don't feel strongly)

2022-10-27 10:40 UTC, kwcanuck commented on astro/create-cluster.md
> +The Astro install typically starts with one Cluster for each Organization. However, your organization can choose to configure multiple Astro Clusters. This could enable a few benefits, including:
@paolaperaza from our style guide:

![image](https://user-images.githubusercontent.com/104205257/198263459-13d6bada-0122-464f-86e8-90a1e61f13ef.png)

So, one of your edit recommendations is correct.

2022-10-27 10:54 UTC, kwcanuck commented on astro/install-aws.md
> +2. Go to `https://cloud.astronomer.io`, enter your email address, and then click **Continue**.
@paolaperaza you need to create your account and then return to log in. I've tested this.

2022-10-27 10:57 UTC, kwcanuck commented on astro/install-aws.md
> +3. Select one of the following options to access the Cloud UI:
@paolaperaza from our chosen style guide:

![image](https://user-images.githubusercontent.com/104205257/198266810-378dad23-9991-4df8-a744-98a14d709f97.png)

_Select_ is correct here.

2022-10-27 11:07 UTC, kwcanuck commented on astro/install-aws.md
> +When hosting your environment, Astronomer adheres to industry best practices and standards including the Health Insurance Portability and Accountability Act (HIPAA), Service Organization Control 2 (S
@paolaperaza this information currently appears at the "top of the doc". We discussed this at our stand up and you agreed that this is the correct location for this information.

2022-10-27 11:15 UTC, kwcanuck commented on astro/install-aws.md
>  ## Prerequisites
@paolaperaza I have implemented the first change you requested.

2022-10-27 11:24 UTC, kwcanuck commented on astro/install-aws.md
> +## Retrieve an external ID from the Cloud UI
@paolaperaza this is existing content that I didn't create. Typically, a single step procedure doesn't require numbering.  However, this isn't a single step procedure! I have edited and rewritten the procedure.

2022-10-27 11:29 UTC, kwcanuck commented on astro/install-aws.md
>  After you've created the cross-account IAM role for Astro, contact [Astronomer support](https://cloud.astronomer.io/support). Astronomer support will finish creating the cluster in your AWS account.
@paolaperaza I have restructured this content so an admonition isn't necessary.

2022-10-27 14:14 UTC, kwcanuck commented
@paolaperaza do you want to take one more look, or can I merge the changes?

2022-10-28 19:39 UTC, melugoyal commented on astro/install-aws.md
> +When providing hosting services, Astronomer adheres to industry best practices and standards including the Health Insurance Portability and Accountability Act (HIPAA), Service Organization Control 2
should "providing hosting services" be "providing hosted services"?

2022-10-28 19:57 UTC, kwcanuck commented on astro/install-aws.md
> +When providing hosting services, Astronomer adheres to industry best practices and standards including the Health Insurance Portability and Accountability Act (HIPAA), Service Organization Control 2
@melugoyal - _hosting_ refers to the business of providing a _service_ that houses, serves, and maintains files for another business. _Hosted_ is used with _Astronomer_ to form the hyphenated compound word _Astronomer-hosted_ to describe the function that this hosting service performs. Not sure if this makes sense, but that's the rationale.

2022-10-28 19:58 UTC, kwcanuck commented on astro/install-aws.md
> +When providing hosting services, Astronomer adheres to industry best practices and standards including the Health Insurance Portability and Accountability Act (HIPAA), Service Organization Control 2
I did miss a comma though!

2022-11-01 01:25 UTC, paolaperaza approved these changes
Let's just go ahead and merge this @kwcanuck ! We can iterate later as needed, the structure looks good to me

2022-11-01 11:16 UTC, merged