Update notebooks guide to tutorial format
astronomer/docs pull request #1355
Opened 2022-10-14 22:19 UTC by kentdanas

Updated our notebooks guide to our new tutorial format and modified the content to focus only on Jupyter notebooks. Databricks and SageMaker, which we previously had brief sections for, are addressed in other tutorials. We should also move it in the nav to tutorials/integrations. I did also check to make sure the DAG we provide runs with the most recent version of runtime.

2022-10-17 09:11 UTC, TJaniF approved these changes
Only a couple of comments, mostly formatting. I had not seen this guide yet, definitely something I have to try out some day 🙂

2022-10-17 09:11 UTC, TJaniF commented on learn/execute-notebooks.md
>      ![Notebook param](/img/guides/parameterized_notebook.png)
```suggestion
The following notebook prints a simple statement with the current date. The second cell is parameterized so that the `execution_date` is dynamic.

![Notebook param](/img/guides/parameterized_notebook.png)
```

I think this should fix the format issue :)

2022-10-17 09:11 UTC, TJaniF commented on learn/execute-notebooks.md
>      ```
```suggestion
```text
apache-airflow-providers-papermill
ipykernel
```
```

2022-10-17 09:11 UTC, TJaniF commented on learn/execute-notebooks.md
> +    ![Output notebook](/img/guides/notebook_output.png)
```suggestion
![Output notebook](/img/guides/notebook_output.png)
```

2022-10-17 09:11 UTC, TJaniF commented on learn/execute-notebooks.md
> +Trigger your DAG to executes the `example_notebook.ipynb` and generate an output notebook named with the execution date. Open the output notebook in your `include/` directory to see the results of th
```suggestion
Trigger your DAG to execute the `example_notebook.ipynb` and generate an output notebook with a name that includes the execution date. Open the output notebook in your `include/` directory to see the results of the run:
```

2022-10-17 12:40 UTC, jwitz requested changes
Looks great! Only requesting changes because there's some tricky formatting here and I want to give the previewed site a final pass before merging.

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +description: "Run a parameterized Jupyter Notebook using Airflow and the Astro CLI."
```suggestion
description: "Run a parameterized Jupyter notebook using Airflow and the Astro CLI."
```

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +Create a Jupyter notebook called `example_notebook.ipynb` and save it to the `include/` directory of the Astro project you created in Step 1.
Because this is still just a template and involves the Astro project, I think it would be okay to include it in Step 1. and reduce the step count of this tutorial by 1

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +Install the Papermill provider and supporting packages required to run the notebook kernel. The `PapermillOperator` is designed to run a notebook locally, so you need to supply a kernel engine for yo
Move "The `PapermillOperator` is designed to run a ..... available such as the `jupyter` package" until after the actual `requirements.txt` step, since this information is optional.

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +Create your DAG with the `PapermillOperator` to execute your notebook. Use your favorite code editor or text editor to copy-paste the following code into a .py file in your project's `dags/` director
```suggestion
Create your DAG with the `PapermillOperator` to execute your notebook. Use your favorite code editor or text editor to copy-paste the following code into a `.py` file in your project's `dags/` directory:
```

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +Note that the built-in `execution_date` Airflow variable is used so that the DAG is idempotent. Parameters for your notebook can come from anywhere, but we highly recommend using Airflow macros and e
```suggestion
Note that the built-in `execution_date` Airflow variable is used so that the DAG is idempotent. Parameters for your notebook can come from anywhere, but Astronomer recommends using Airflow macros and environment variables to avoid hard-coding values in your DAG file.
```

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
> +Install the Papermill provider and supporting packages required to run the notebook kernel. The `PapermillOperator` is designed to run a notebook locally, so you need to supply a kernel engine for yo
```suggestion
Install the Papermill provider and supporting packages required to run the notebook kernel. The `PapermillOperator` is designed to run a notebook locally, so you need to supply a kernel engine for your Airflow environment to execute the notebook code. This tutorial uses the `ipykernel` package to run the kernel, but there are other options available such as the `jupyter` package.
```

2022-10-17 12:40 UTC, jwitz commented on learn/execute-notebooks.md
>      ```
Agreed with Tamara but watch out when committing this suggestion - GitHub didn't parse the last three ticks correctly and they're missing from the suggestion.

2022-10-17 16:31 UTC, kentdanas commented
Thanks for the review @jwitz and @TJaniF! I think the formatting issues should be fixed now.

2022-10-20 20:15 UTC, kentdanas commented
@jwitz friendly ping on this one in case it got buried. Let me know if any other changes are needed!

2022-10-21 10:20 UTC, jwitz approved these changes
Thank for the ping @kentdanas , LGTM!

2022-10-21 15:21 UTC, merged