Runtime executor documentation
astronomer/docs pull request #1363
Opened 2022-10-19 13:21 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/858

2022-10-19 13:34 UTC, kwcanuck commented on astro/runtime-executor.md
> +description: Learn how to your Airflow environment and tasks to take advantage of the Runtime executor, available exclusively in Astro Runtime.
```suggestion
description: Learn how to use your Airflow environment and tasks to take advantage of the Runtime executor, available exclusively in Astro Runtime.
```
Alternative description:

Learn how to use the Runtime executor in Astro Runtime.

2022-10-19 13:37 UTC, kwcanuck commented on astro/runtime-executor.md
> +- Set environment-level strategies how resources should be allocated between tasks that don't have specific resource requests.
```suggestion
- Set environment-level strategies to define how resources are allocated between tasks without specific resource requests.
```

2022-10-19 13:45 UTC, kwcanuck commented on astro/runtime-executor.md
> +After you set this variable, all tasks in the Deployment will run with the Runtime executor. To revert back to using the Celery executor, delete the environment variable from your Deployment.
```suggestion
After you set this variable, all tasks in the Deployment will run with the Runtime executor. To revert to the Celery executor, delete the environment variable from your Deployment. 
```

2022-10-19 13:47 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- Set system-level strategies how resources should be allocated between tasks that don't have specific resource requests.
```suggestion
- Set environment-level strategies to define how resources are allocated between tasks without specific resource requests.
```

2022-10-19 13:49 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- **Runners** run tasks. To start running a task, a runner queries the metadata DB to look for new assignment. If it’s been assigned a task, the runner starts completing the work. Currently, there is
```suggestion
- **Runners** run tasks. To start running a task, a runner queries the metadata DB to look for a new assignment. If it’s been assigned a task, the runner starts completing the work. Currently, there is only one type of runner named **SubprocessRunner**, which runs tasks within the same cluster as your Airflow environment.
```

2022-10-19 13:50 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- The scheduler logs information about the task and its configured resource requests in Airflow's metadata DB. The task's allocation status is "Unassigned".
```suggestion
- The scheduler logs information about the task and its configured resource requests in the Airflow metadata database. The task's allocation status is "Unassigned".
```

2022-10-19 13:56 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- The allocator looks for any unassigned tasks in the metadata db. When it finds an unassigned task, the allocator determines how to best run the task. It calculates this based on the tasks own resou
```suggestion
- The allocator looks for any unassigned tasks in the Airflow metadata database. When it finds an unassigned task, the allocator determines how to best run the task by reviewing existing task resource requests and configured system-level allocation strategies.
```

2022-10-19 13:57 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- The allocator choses a runner and assigns the task to the runner for execution. After the task is assigned, its allocation status in the metadata db is updated to "Assigned".
```suggestion
- The allocator chooses a runner and assigns the task to the runner for execution. After the task is assigned, its allocation status in the Airflow metadata database updates to "Assigned".
```

2022-10-19 13:59 UTC, kwcanuck approved these changes

2022-10-21 10:06 UTC, ianbuss reviewed
Looks nice! Left a few comments @jwitz . Am wondering if we need to mention how logging is handled (or at least say you can access task logs for running and completed tasks via the webserver just as you would for Celery)

2022-10-21 10:06 UTC, ianbuss commented on astro/runtime-image-architecture.md
> +- Allocation is a wrapper around a task instance that indicates its resource requirements, it’s created after the task instance
```suggestion
- An allocation is a wrapper around a task instance that indicates its resource requirements. It’s created alongside the task instance as a new object in the database.
```

2022-10-21 10:06 UTC, ianbuss commented on astro/runtime-image-architecture.md
> +- The **Airflow metadata DB** stores both assigned and unassigned allocation requests. The Runtime executor’s DB tables are built in complete parallel and isolation to existing tables. This means tha
```suggestion
- The **Airflow metadata DB** stores both assigned and unassigned allocation requests. The Runtime executor’s DB tables are created alongside, but in complete isolation from, existing Airflow tables. This means that no open source tables in Airflow need to be modified in order for the executor to work.
```

2022-10-21 10:06 UTC, ianbuss commented on astro/runtime-image-architecture.md
> +- The **allocator** queries the metadata DB for unassigned allocation requests. It then determines how the allocation requests should be handled and submits assignments for the runners back to the DB
```suggestion
- A new component, the **allocator**, queries the metadata DB for unassigned allocation requests. It then determines how the allocation requests should be handled and submits assignments for the runners back to the DB.
```

2022-10-24 05:10 UTC, paolaperaza requested changes

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +You can set task-level requests for the following resources:
Let's give a (brief) explanation here of why you would do this (reliability, especially for bigger tasks)

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +- `cpu`: The number of CPU cores to reserve (for example, `1.5`).
```suggestion
- `cpu`: The number of CPU cores to reserve. For example, `1.5`.
```

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +- `memory`: The number of megabytes of RAM to reserve (for example, `1024MB`).
```suggestion
- `memory`: The number of megabytes of RAM to reserve. For example, `1024MB`.
```

Is it with `MB` here?

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +- `slots`: The mechanisms for limiting concurrency within a runner. You can request up to 16 slots for a task.
```suggestion
- `slots`: The number of tasks that a single task counts for, in the context of controlling worker concurrency, which represents how many tasks a single runner can run at once. You can request up to 64 slots for a single task, which is the concurrency limit for a worker queue on Astro.
```

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +Set task-level resource requests in the task definition. In the following example, a task is configured with a resource request of 1.5 CPU cores and 1024MB.
This transition feels a little off -- could split it into two sections?

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +Slots are a mechanism for limiting the amount of tasks that can run concurrently on a single runner. By default, runners have 16 slots and tasks request 1 slot.
I think we should actually split up into two sub-sections:

## Task-level Requests
[high-level overview of two methods and why you'd use them]

### CPU and Memory

### Slots

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +## Set environment-level allocation strategies
```suggestion
## Set an allocation strategy
```

Don't think you ever set more than "one" or plural strategies

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +- `MaxPackingStrategy`: The allocator attempts to assign as many tasks as possible to a single runner before using another runner.
If we want to, I'd suggest we put it under some section called "Advanced" or something

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-executor.md
> +Set the `ALLOCATOR_STRATEGY` [environment variable](environment-variables.md) to configure how the Runtime executor allocates tasks across your runners. This environment variable has two possible val
@jwitz Can we add a section on how to view runner status in the Airflow UI? Do you have access to that? @ianbuss Would be good to get more guidance here on the Runtime team on what's available in that runner tab and how we expect users to reference it

2022-10-24 05:10 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +### Runtime executor
In reading this again, I'm finding myself referencing this architecture doc and the enablement doc back-and-forth to understand "how it works and how I should use it."

I'm really thinking we just need to consolidate all of this into the runtime executor doc at the top (dedicated architecture section) and then keep the Runtime IMAGE architecture doc higher level about which executors it supports and then link out

2022-10-24 11:05 UTC, jwitz commented on astro/runtime-executor.md
> +title: "Run tasks with the Runtime executor"
Cut some words here, keeping things focused on "Resources"

2022-10-24 13:17 UTC, jwitz commented on astro/runtime-executor.md
> +Set the `ALLOCATOR_STRATEGY` [environment variable](environment-variables.md) to configure how the Runtime executor allocates tasks across your runners. This environment variable has two possible val
I've added this section, but I'm running into a few bugs that made me doubt whether we should be writing about this now - even if it's still in beta.

2022-10-24 13:18 UTC, jwitz commented
@paolaperaza This is ready for review again ✅ Made quite a few changes this time around but mainly stuck to the current suggestions. There's also a new section about the **Executor Status** page in the Airflow UI.

2022-10-27 23:20 UTC, jarfgit commented on astro/runtime-executor.md
> +            resources= {"cpu": "1.5", "memory": "1024MB", "slots": "2"},
Syntax for the resource request is just slightly off here. It should be:
`executor_config={"resources": {"cpu": "1.5", "memory": "1024MB", "slots": "2"}},`

2022-11-28 16:37 UTC, jwitz commented on astro/runtime-executor.md
> +    style Deployment fill:#bfeaff,stroke:#333,stroke-width:2px
```suggestion
```

2023-04-03 15:11 UTC, paolaperaza commented
The Runtime Executor is unfortunately not imminent and still unplanned, at this point. Closing for now and we'll resurrect if/when needed 😞

2023-04-03 15:11 UTC, closed without merging