Remove docs which are redundant to Learn guides
astronomer/docs pull request #1376
Opened 2022-10-24 14:26 UTC by jwitz

This PR consolidates some of our OSS content into the Learn docs. For the most part the redundant docs had the same information worded differently between contexts, but the local KPO doc had some setup steps which are not in the equivalent Learn guide. @kentdanas let me know what you think about the new section in the Learn guide for KPO.

2022-10-24 14:33 UTC, kwcanuck approved these changes

2022-10-24 15:28 UTC, kentdanas approved these changes
One minor comment, otherwise looks good to me!

2022-10-24 15:28 UTC, kentdanas commented on learn/kubepod-operator.md
>  You can use the [Helm Chart for Apache Airflow](https://airflow.apache.org/docs/helm-chart/stable/index.html) to run open source Airflow within a local Kubernetes cluster. See [Getting Started With t
```suggestion
```
Looks like this was duplicated with the new addition below.

2022-10-25 16:43 UTC, jwitz commented on sidebarsAstro.js
>              'astro-python-sdk',
```suggestion
```

2022-10-27 04:29 UTC, paolaperaza requested changes
Looking good here -- excited to get these consolidated. In reviewing the individual docs I'm worried we tossed a bit too much of the work we had done in whichever version we're deprecating. Not that we have to bring all of it, but a cursory review still good I think.

For the Astro SDK one, I went ahead and ported over some things from Astro to Learn. I think I’d like us to do the same on the KubernetesPodOperator doc + Deferrable Operators?

(Note: Realized I removed the `Assumed knowledge` section, should add that back for consistency with guides)

2022-10-27 20:13 UTC, kentdanas commented on learn/astro-python-sdk-etl.md
> +## Lern more
```suggestion
## Learn more
```

2022-10-27 20:18 UTC, kentdanas commented on learn/astro-python-sdk-etl.md
> -To use the Astro Python SDK for your ETL example, you must complete a couple of setup steps.
It feels weird to me to get rid of this sentence and have only the directions, given that this isn't a step-by-step tutorial

2022-10-27 20:20 UTC, kentdanas commented on learn/astro-python-sdk-etl.md
> +## Python SDK functions
I'm not sure I agree with having this section be a general list of functions in the SDK instead of a curated list specifically for ETL use cases. I think a full list of functions with very basic definitions belongs in the documentation (I think we have this), but for a concept guide on a specific use case it should be okay to present a subset of relevant functions and describe them in more detail based on how they are applied for that use case.

2022-10-28 10:28 UTC, jwitz commented
@paolaperaza I've made some updates to the other three guides we ported so that they include more information from the deleted docs:

- Docs now include links to relevant Astronomer docs in the Overview section
- Deferrable operator docs have a more general usage example and a more pronounced "available operators" section. 
- Lineage docs have some updated known limitations and more links to Astro docs.

I didn't change the KPO doc that much because almost the entire Astro doc was already included there.

2022-11-03 09:24 UTC, TJaniF approved these changes
Looks great! Just had a few optional suggestions. :)

2022-11-03 09:24 UTC, TJaniF commented on learn/deferrable-operators.md
> +- If you're interested in the deferrable version of an operator that is not generally available, you can write your own and contribute these to the open source project.
```suggestion
- If you're interested in the deferrable version of an operator that is not generally available, you can write your own and contribute it back to the open source project. 
```

2022-11-03 09:24 UTC, TJaniF commented on learn/kubepod-operator.md
> +with dag:
```suggestion

with DAG(
    dag_id='example_kubernetes_pod', 
    schedule_interval='@once', 
    default_args=default_args
) as dag:
```

Trying to standardize the syntax we use in examples. Ofc the existing one also works. Feel free to ignore.

2022-11-03 09:24 UTC, TJaniF commented on learn/kubepod-operator.md
> +default_args = {
```suggestion
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator

default_args = {
```

2022-11-03 09:24 UTC, TJaniF commented on learn/kubepod-operator.md
> +namespace = conf.get('kubernetes', 'NAMESPACE')
```suggestion
}

namespace = conf.get('kubernetes', 'NAMESPACE')
```

2022-11-04 09:21 UTC, merged