Runtime 6.0.3 release notes
astronomer/docs pull request #1378
Opened 2022-10-24 18:10 UTC by jwitz

2022-10-24 18:22 UTC, collinmcnulty commented on astro/runtime-release-notes.md
> +- Upgraded `openlineage-airflow` to 0.15.1, which aa dedicated development environment for Airflow. You can now continually make and test changes to custom OpenLineage extractors in an Airflow enviro
aa?

2022-10-24 18:25 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +- Upgraded `openlineage-airflow` to 0.15.1, which aa dedicated development environment for Airflow. You can now continually make and test changes to custom OpenLineage extractors in an Airflow enviro
```suggestion
- Upgraded `openlineage-airflow` to 0.15.1, which is a dedicated Airflow development environment. You can now create and test changes to custom OpenLineage extractors in an Airflow environment without needing to rebuild your Docker images. For more information, see the [OpenLineage changelog](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md).
```

2022-10-24 18:26 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +Astro Runtime 6.0.2 includes same-day support for Airflow 2.4.2, which includes a collection of bug fixes. Fixes include:
```suggestion
Astro Runtime 6.0.2 includes same-day support for Airflow 2.4.2 and the following bug fixes:
```

2022-10-24 18:32 UTC, kwcanuck commented on astro/runtime-release-notes.md
> +### Airflow 2.4.1
```suggestion
### Airflow 2.4.2
```

2022-10-24 18:32 UTC, kwcanuck approved these changes

2022-10-25 14:59 UTC, merobi-hub requested changes
Thanks, @jwitz, the description of OpenLineage 0.15.1 looks good. The only change I would make would be to say "which includes a dedicated..." on line 30.

2022-10-25 15:25 UTC, jwitz commented on astro/runtime-release-notes.md
> +- Upgraded `openlineage-airflow` to 0.15.1, which is a dedicated Airflow development environment. You can now create and test changes to custom OpenLineage extractors in an Airflow environment withou
```suggestion
- Upgraded `openlineage-airflow` to 0.15.1, which includes a dedicated Airflow development environment. You can now create and test changes to custom OpenLineage extractors in an Airflow environment without needing to rebuild your Docker images. For more information, see the [OpenLineage changelog](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md).
```

2022-10-26 09:37 UTC, jwitz commented on astro/runtime-release-notes.md
> +Astro Runtime 6.0.3 includes same-day support for Airflow 2.4.2.
```suggestion
Astro Runtime 6.0.3 includes same-day support for Airflow 2.4.2. Some changes in Airflow 2.4.2 include:
```

2022-10-26 09:38 UTC, jwitz commented on astro/runtime-release-notes.md
> +
I think the last edit I made removed some of the context from this list. We are just highlighting a few changes in 2.4.2 that might be of interest to people reading the notes. Tried to make that more clear in the preceding sentence.

2022-10-26 11:42 UTC, merged