Add Procedure for Triggering DAG Runs Across Deployments
astronomer/docs pull request #1391
Opened 2022-10-26 13:00 UTC by kwcanuck

Resolves #1388

2022-10-26 13:05 UTC, kwcanuck commented
@collin-astro there are a number of gaps in the preliminary draft of the procedure I prepared. I'm hoping you can help answer the following questions:

- Why would a user want to complete this task? What benefit does it provide?

- How does a user store the access token for one Deployment in another Deployment?

- What does a user need to do to "make the Airflow API call"? Can we be more specific, or provide an example?

- Are specific permissions required to perform this procedure?

2022-10-26 13:40 UTC, collin-astro commented
I believe this is meant for @collinmcnulty

2022-10-26 13:54 UTC, collinmcnulty commented
You actually can't do steps 1 and 2. Step 3 will spit out the access token as part of a json, which you must rip out and store as a string. You have to store the api key and secret api key on Deployment B.

In this wording, it's deployment B triggering a dag in deployment A. I've been using "triggering deployment" and "target deployment" colloquially.

2022-10-26 13:57 UTC, collinmcnulty commented
A user may want to do this if they are (as we suggest) using different deployments to cordon off different teams workflows. This would only work from an organization mgmt perspective though, as once you have an api key, you've hosed the security barrier between the two (or at least made it one way only).

2022-10-26 13:58 UTC, collinmcnulty commented
I think how to "make the Airflow API call" is covered adequately above in this same document.

2022-10-27 15:18 UTC, collinmcnulty requested changes

2022-10-27 15:18 UTC, collinmcnulty commented on astro/airflow-api.md
> +1. On the target Deployment, create an API key ID and API key secret. See [Set environment variables on Astro](api-keys.md#create-an-api-key).
Wrong link title?

2022-10-27 15:18 UTC, collinmcnulty commented on astro/airflow-api.md
> +When you need to trigger DAGs in multiple Deployments, you can use the Airflow API. Triggering DAGS in multiple Deployments is sometimes necessary when you're using multiple Deployments to separate t
I'd add "Similar DAGs can be created for any operation supported in the Airflow API"

2022-10-27 16:39 UTC, collinmcnulty approved these changes

2022-10-28 18:39 UTC, paolaperaza reviewed
Quick comment here @kwcanuck -- TL;DR I don't think we can frame step 3 as "copy paste this!" given that there are other things they'll want to customize.

Added more context to what the DAG is doing (feel free to organize differently) and framed it explicitly as an "example"

2022-10-28 18:39 UTC, paolaperaza commented on astro/airflow-api.md
> +When you need to trigger DAGs in multiple Deployments, you can use the Airflow API. Triggering DAGS in multiple Deployments is sometimes necessary when you're using multiple Deployments to separate t
```suggestion
You can use the Airflow REST API to make a request in one Deployment that triggers a DAG run in a different Deployment. This is sometimes necessary when you have interdependent workflows across multiple Deployments. On Astro, you can do this for any Deployment in any Workspace or cluster. 
```

2022-10-28 18:39 UTC, paolaperaza commented on astro/airflow-api.md
> +This methodology works with any Deployment in any Astro Workspace or cluster. DAGs similar to the one provided can be created for any operation supported by the Airflow API.
```suggestion
This topic has guidelines on how to trigger a DAG run, but you can modify the example DAG provided to trigger any request that's supported in the Airflow REST API.
```

2022-10-28 18:39 UTC, paolaperaza commented on astro/airflow-api.md
> +                                        "client_secret": KEY_SECRET})
```suggestion
                                        "client_id": {KEY_ID},
                                        "client_secret": {KEY_SECRET})
```

pretty sure these are needed?

2022-10-28 18:39 UTC, paolaperaza commented on astro/airflow-api.md
> +3. Create and then run the following DAG to start a DAG run on the target Deployment from the triggering Deployment:
```suggestion
3. In your DAG, write a task called `get-token` that uses your Deployment API key ID and secret to make a request to the Astronomer API that retrieves the access token that's required for authentication to the Airflow API. In another task called `trigger_external_dag`, use the access token to make a request to the `dagRuns` endpoint of the Airflow REST API. Make sure to replace `<target-deployment-url>` with your own value.

Example:
```

2022-10-28 18:39 UTC, paolaperaza commented on astro/airflow-api.md
> +2. On the trigger Deployment, save the API key ID and API key secret as `KEY_ID` and `KEY_SECRET` environment variables. Make `KEY_SECRET` secret. See [Set environment variables on Astro](environment
```suggestion
2. On the triggering Deployment, set the API key ID and API key secret from the target Deployment as `KEY_ID` and `KEY_SECRET` environment variables in the Cloud UI. Make `KEY_SECRET` secret. See [Set environment variables on Astro](environment-variables.md).
```

2022-10-28 18:47 UTC, paolaperaza approved these changes

2022-10-28 18:57 UTC, merged

2022-10-31 20:15 UTC, pgagnon commented on astro/airflow-api.md
> +    KEY_SECRET = os.environ.get("KEY_SECRET")
We should use Airflow variables instead of env vars here.

2022-10-31 20:18 UTC, pgagnon commented on astro/airflow-api.md
> +            return response.json()["access_token"]
Passing the access token as an xcom is potentially insecure depending on the backend used.

2022-11-01 11:06 UTC, kwcanuck commented on astro/airflow-api.md
> +    KEY_SECRET = os.environ.get("KEY_SECRET")
@pgagnon thanks for the feedback. Can you provide the _specific_ edits you are requesting? What specific Airflow variables should be used?

This PR has been merged, so I'll need to open a new PR to address your concerns.

2022-11-01 11:08 UTC, kwcanuck commented on astro/airflow-api.md
> +                data='{"logical_date": "' + datetime.utcnow().isoformat().split(".")[0] + 'Z"}'
@pgagnon again, can you specify the specific edit and location you are requesting? What specifically needs to be replaced with `strftime()`?

2022-11-01 11:09 UTC, kwcanuck commented on astro/airflow-api.md
> +            return response.json()["access_token"]
@pgagnon good to know. However, what do you want to tell users specifically? Should they be using this methodology?