[Do not merge] Update for the SQL check operators concept guide anticipating version 1.3
astronomer/docs pull request #1399
Opened 2022-10-27 13:29 UTC by TJaniF

https://github.com/apache/airflow/pull/26761 got merged yesterday which means the `SQLColumnCheckOperator` and `SQLTableCheckOperator` are getting an upgrade with the next provider release. This PR is to upgrade the concept guide as soon as Common SQL version 1.3 is released. :)

2022-10-27 18:40 UTC, kentdanas requested changes
Looks good! I left a couple of comments. 

Also one high level thought - not sure what our take is on talking about versions of packages. I don't love doing it in the text, because after a couple more releases it will be largely irrelevant. That said, on concept guides like this where we don't have a "prerequisites" section or a specific instruction to install a particular version, I can see where it would be problematic to not mention it for features that have been recently released. All that to say, I'm not suggesting we need changes to how it is now, but something to keep in mind for how we update them in the future.

2022-10-27 18:40 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +In version 1.3+ of the Common SQL provider it is possible to define a subset of the table to run checks on. To do so provide a statement that could follow the SQL `WHERE`-keyword to the `partition_cl
```suggestion
With version 1.3+ of the Common SQL provider, it is possible to define a subset of the table to run checks on. To do so, provide a statement that could follow the SQL `WHERE`-keyword to the `partition_clause` parameter. A `partition_clause` defined at the operator level will apply to all checks contained in the operator. A `partition_clause` defined within a single check only affects the check it has been defined in. 
```
"could follow" is throwing me off a bit here. I wonder if there's a different way to describe this that would be clearer. Maybe "provide a SQL `WHERE` clause - I think this is technically accurate in terms of SQL terminology.

2022-10-27 18:40 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +The partition clause at the operator level is `CUSTOMER_NAME IS NOT NULL` meaning all checks defined in `column_mapping` will only run on rows of `MY_TABLE` where there is no `NULL` value in the `CUS
```suggestion
In this example, the operator-level partition clause is `CUSTOMER_NAME IS NOT NULL`, which means all checks defined in the `column_mapping` will only run on rows of `MY_TABLE` where there is no `NULL` value in the `CUSTOMER_NAME` column.
```
I think this statement should probably also be a bullet like the ones below to make it clearer. Maybe something like -
"The following checks are completed in this example:
- `My_NUM_COL_1`: description of check
- `My_num_col_2`: description of check and partition
- Both of these checks only run on ....description of operator-level partition clause
etc.

2022-10-27 18:40 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +In previous versions running a column check on an empty table always resulted in the check to fail.
```suggestion
In previous versions of the provider, running a column check on an empty table always resulted in a failed check.
```

2022-10-27 18:40 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +Starting with version 1.3 of the Common SQL provider the SQLColumnCheckOperator will convert a returned `result` of `None` to 0 by default and still run the check.
```suggestion
Starting with version 1.3 of the Common SQL provider, the SQLColumnCheckOperator will convert a returned `result` of `None` to 0 by default and still run the check.
```

2022-10-27 18:40 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +Equivalent to the SQLColumnCheckOperator you can pass a SQL statement that could follow the `WHERE` keyword in a query to the operator-level `partition_clause` parameter or as a check-level `partitio
```suggestion
Similarly to the SQLColumnCheckOperator, in version 1.3+ you can pass a SQL `WHERE` clause to the operator-level `partition_clause` parameter or as a check-level `partition_clause`. All checks of the `table_checks` task below only run on rows in `MY_TABLE` where the date in the `START_DATE` column is 2022-01-01 or later. The `my_column_sum_comparison_check` additionally only runs on rows where the value in `MY_COL_4` is greater than 100.
```

2022-10-28 12:21 UTC, TJaniF reviewed
Thank you Kenten! Yes, I agree it is not the most elegant having the package version in the text. I think in a few months we can probably take that out, I just wanted to prevent people from being frustrated if partitioning does not work with their versions. 😅 (also the SQLTableCheckOperator already had a partitioning clause in the last version but it did not really work).

2022-10-28 12:21 UTC, TJaniF commented on learn/airflow-sql-data-quality.md
> +In version 1.3+ of the Common SQL provider it is possible to define a subset of the table to run checks on. To do so provide a statement that could follow the SQL `WHERE`-keyword to the `partition_cl
yeah I struggled with phrasing this in a way that makes clear that the `WHERE` keyword should not be included. Maybe I need to be explicit about it "provide a SQL `WHERE` clause (without the `WHERE` keyword)"

2022-10-28 20:37 UTC, kentdanas approved these changes
A couple more minor edits, but otherwise looks good to me!

2022-10-28 20:37 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +- the `MY_NUM_COL_1` column is checked to have a minimum value greater than 10.
```suggestion
- The `MY_NUM_COL_1` column is checked to have a minimum value greater than 10.
```

2022-10-28 20:37 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +- `MY_NUM_COL_2` is checked to have a maximum value less than 300 for rows that fulfill the check-level `partition_clause` which includes rows where `CUSTOMER_STATUS = 'active'`.
```suggestion
- The `MY_NUM_COL_2` is checked to have a maximum value less than 300. Only rows that fulfill the check-level `partition_clause` are checked (rows where `CUSTOMER_STATUS = 'active'`).
```

2022-10-28 20:37 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +- both of the above checks only run on rows fullfilling the operator-level partition clause `CUSTOMER_NAME IS NOT NULL`.
```suggestion
- Both of the above checks only run on rows that fulfill the operator-level partition clause `CUSTOMER_NAME IS NOT NULL`.
```

2022-10-28 20:37 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +If both, an operator-level `partition_clause` and a check-level `partition_clause` is defined for a check, the check will only run on rows fulfilling both clauses.
```suggestion
If both an operator-level `partition_clause` and a check-level `partition_clause` is defined for a check, the check will only run on rows fulfilling both clauses.
```

2022-10-28 20:37 UTC, kentdanas commented on learn/airflow-sql-data-quality.md
> +If the boolean value resulting from the check is `True` it passes, otherwise the check will fail. [Airflow generates logs](logging.md) that show the set of returned records for every check that passe
```suggestion
If the boolean value resulting from the check is `True` the check will pass, otherwise it will fail. [Airflow generates logs](logging.md) that show the set of returned records for every check that passes and the full query and result for checks that failed.
```

2022-10-31 12:20 UTC, jwitz approved these changes
A few comments about versioning and content organization, but otherwise LGTM!

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +In the following example, two checks are performed:
```suggestion
In the following example, the operator checks whether:
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +- the `MY_NUM_COL_1` column is checked to have a minimum value greater than 10.
```suggestion
- `MY_NUM_COL_1` column has a minimum value greater than 10.
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +- `MY_NUM_COL_2` is checked to have a maximum value less than 300 for rows that fulfill the check-level `partition_clause` which includes rows where `CUSTOMER_STATUS = 'active'`.
```suggestion
- `MY_NUM_COL_2` has a maximum value less than 300. Only rows that fulfill the check-level `partition_clause` are checked (rows where `CUSTOMER_STATUS = 'active'`).
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +If both, an operator-level `partition_clause` and a check-level `partition_clause` is defined for a check, the check will only run on rows fulfilling both clauses.
```suggestion
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +Starting with version 1.3 of the Common SQL provider, the SQLColumnCheckOperator will convert a returned `result` of `None` to 0 by default and still run the check.
```suggestion
The SQLColumnCheckOperator converts a returned `result` of `None` to 0 by default and still runs the check.
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +- Running the above checks on a subset of the table using the `partition_clause` parameter (added in version 1.3 of the Common SQL provider).
```suggestion
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +Similarly to the SQLColumnCheckOperator, in version 1.3+ you can pass a SQL `WHERE` clause to the operator-level `partition_clause` parameter or as a check-level `partition_clause`. All checks of the
```suggestion
Similarly to the SQLColumnCheckOperator, you can pass a SQL `WHERE` clause to the operator-level `partition_clause` parameter or as a check-level `partition_clause`. All checks of the `table_checks` task below run only on rows in `MY_TABLE` where the date in the `START_DATE` column is 2022-01-01 or later. The `my_column_sum_comparison_check` additionally only runs on rows where the value in `MY_COL_4` is greater than 100.
```

2022-10-31 12:20 UTC, jwitz commented on learn/airflow-sql-data-quality.md
> +With version 1.3+ of the Common SQL provider, it is possible to define a subset of the table to run checks on. To do so, provide a SQL `WHERE`-clause (without the `WHERE` keyword) to the `partition_c
Also - if you accept my suggestion on the header change, let's update the rest of the titles with "Example" in the name to match that format.

2022-11-01 12:29 UTC, TJaniF commented
Thank you for your reviews @jwitz and @kentdanas. I accepted most suggestions and moved the partition clause chapter below the logs for the SQLColumnCheckOperator, otherwise the logs felt a little out of place. I also realized the log format change and adapted that :)

2022-11-26 18:59 UTC, TJaniF commented
Merging since 1.3 was released a week ago 🙂

2022-11-26 18:59 UTC, merged