add ref to mounting emptyDir for ephemeral storage
astronomer/docs pull request #1404
Opened 2022-10-28 14:48 UTC by wendtek

2022-10-28 15:20 UTC, stuart23 commented
Can we also add an example in this doc https://github.com/astronomer/docs/blob/main/astro/kubernetespodoperator.md showing the settings needed for KPO to mount this vol?

2022-11-01 11:21 UTC, jwitz reviewed
Thanks for getting this started @wendtek ! I add some suggestions as well as some documentation for the KPO. Can you please: 

- Review the content I added to make sure it aligns with your note in the resource reference guide
- Provide an example of how a standard task would write to `/ephemeral`

Thank you!

2022-11-01 11:23 UTC, jwitz commented on astro/kubernetespodoperator.md
> +    Your task can now utilize the configured volume as storage for simple operations. However, Astronomer recommends setting Airflow connection to an external storage service such as Amazon S3 for la
```suggestion
    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends setting an Airflow connection to an external storage service such as Amazon S3 . See [Passing data between Airflow tasks](https://www.docs.astronomer.io/learn/airflow-passing-data-between-tasks/).
```

2022-11-01 19:06 UTC, stuart23 requested changes

2022-11-01 19:06 UTC, stuart23 commented on astro/kubernetespodoperator.md
> +Astronomer provisions `m5d` workers with NVMe SSD volumes. These volumes can be used by tasks for storage which persists as long as the task is running. To run a task run the KubernetesPodOperator th
Or m6id https://docs.astronomer.io/astro/resource-reference-aws#worker-node-types

2022-11-01 19:06 UTC, stuart23 commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends sett
Can you point to the resources table telling them how much space is available? "small amounts of data" is too vague.

2022-11-01 19:06 UTC, stuart23 commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends sett
```suggestion
    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends setting an Airflow connection to an external storage service such as Amazon S3, see [Passing data between Airflow tasks](https://www.docs.astronomer.io/learn/airflow-passing-data-between-tasks/).
```

2022-11-03 15:44 UTC, stuart23 commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends sett
There is 20GB capacity for all instance types except for the m5d and m6id types - we need to tell them how much space is available according to https://aws.amazon.com/ec2/instance-types/m6i/ & https://aws.amazon.com/ec2/instance-types/m5/

2022-11-03 15:45 UTC, stuart23 commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume. Astronomer recommends using this volume only with small amounts of data. For larger operations requiring storage, Astronomer recommends sett
We don't necessarily need to give them numbers - we can just link the above

2022-11-07 16:23 UTC, wendtek commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume. Astronomer recommends that your tasks use no more storage than 20GB divided by your configured maximum tasks per worker. See [Worker autosca
I don't think we should be recommending 20GB here unless we have language excepting the NVME based instances. Possibly better to just link to the AWS docs about instance storage.

2022-11-09 16:13 UTC, jwitz commented on astro/kubernetespodoperator.md
> +    Your task can now write data to the configured volume.
```suggestion
```

2022-11-09 18:40 UTC, stuart23 commented
Can we merge https://github.com/astronomer/docs/pull/1454 into this and then merge them both to main? I am getting confused with the differences between them

2022-11-10 11:08 UTC, merged