Cloud IDE tutorial - simple ML model
astronomer/docs pull request #1413
Opened 2022-11-01 16:56 UTC by TJaniF

A tutorial showing how to use the Cloud IDE to train a simple model on a small dataset.

Some notes:
- The dataset used is [this one on Kaggle](https://www.kaggle.com/datasets/jasleensondhi/dog-intelligence-comparison-based-on-size), there are two reasons I did not directly link it: first some users might not have a Kaggle account and more importantly, the dataset has two bad characters in the Breed names that users would have to clean up before importing it into snowflake (the characters break the import wizard, which offers no way to skip bad characters... and programmatic import needs the snowflake CLI tool which is not straighforward to install). I think the easiest option is if we hosted the cleaned up dataset version and make sure to give credit and link back to the Kaggle user who published it?
- There are two placeholders in the text, one for a screenshot of the create project screen (not open yet to users) and the other one for a screenshot for the DAG running on Astro because I noticed I don't have access to a cluster anymore, will try to get that again.
- I tried to keep a balance between explaining the Python cell code and linking out to a resource on random forests. 
- Similarly I gave the GitHub secrets that a user would have to configure but did not go into more detail on GitHub Actions and instead linked to the docs and the module.

2022-11-01 21:48 UTC, kentdanas requested changes
Great content here @TJaniF! Left some initial higher level comments, but I love where this example is going. Can chat more about it tomorrow with the docs team :)

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +After entering your credentials click the **Test Connection button** to make sure Astro is able to connect to Snowflake. If your credentials are correct, a green banner will appear above saying "Conn
```suggestion
After entering your credentials click the **Test Connection button** to make sure Astro is able to connect to your database. If your credentials are correct, a green banner will appear above saying "Connection successfully tested". Save the connection by clicking **Create Connection**.
```
Just a note, I didn't see any green banner after testing the connection (I didn't see any "result" at all) - not sure if me or some sort of bug

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +## Step 4: Add required python packages
```suggestion
## Step 4: Add required Python packages
```

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In this tutorial we will use the try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download [this dataset](PLACEHOLDER LINK) and import it into y
```suggestion
In this tutorial we will try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download [this dataset](PLACEHOLDER LINK) and import it into your database. 
```

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +## Step 5: Import a dataset into your database
I almost might put this step first, since that's how we've done it with other tutorials (set up the external systems first), and it's less back and forth between the cloud IDE and snowflake. Unless I'm missing some reason it needs to happen after those other steps

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +3. Use the ["Loading Using the Web Interface" wizard](https://docs.snowflake.com/en/user-guide/data-load-web-ui.html) by navigating to the `dog_intelligence` table in the **Datasets** tab of the Snow
```suggestion
3. Use the ["Loading Using the Web Interface" wizard](https://docs.snowflake.com/en/user-guide/data-load-web-ui.html) by navigating to the `dog_intelligence` table in the **Databases** tab of the Snowflake UI and clicking on **Load Table**. Select the `dog_intelligence.csv` file you downloaded as the "Source File" and `my_csv_format` as the "File Format".
```
I think it should be "Databases" tab?

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +Navigate back to your Cloud IDE on Astro.
Note that here they would still be on the Requirements tab, so they need to click back into their pipeline

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +3. Paste the following SQL code into your cell to select all records that do not contain any NULL values in any column:
Should note explicitly that they need to update their database and schema

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +Our dataset contains information about the height, weight and how fast dogs of different breeds learned commands in 7 columns:
Does the user need to know the contents of the columns for later in the tutorial? Wondering if we need all these bullets, or if we can just say something general about what the data contains.

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +
Can we add a short sentence up front here about why we need to transform the table?

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In the output table you can see that this SQL statement created a new transformed temporary table with an binary `INTELLIGENCE_CATEGORY` column we can use as a target for our classification model. Al
```suggestion
In the output table you can see that this SQL statement created a new transformed temporary table with a binary `INTELLIGENCE_CATEGORY` column which will be used as a target for your classification model. All dogs who needed 25 or fewer repetitions to learn a new command are put in the `very_smart_dog` category. All other dogs are put in the `smart_dog` category (because of course, all dogs are smart).
```

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +The predictors in our model will be the height and weight-related columns.
This seems a little out of place - I think somewhere we should have a few sentences of context about what the data is and what model we will be training. Maybe in the intro? I might make a later comment on where to add it as I keep reading :)

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +
Can we add a sentence here on why we want to do this? Something like "Now that you have trained the model, you can connect GitHub to...."

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +- imports necessary functions and classes from the scikit-learn package.
Capitalize the start of all these bullets

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +
Add something here like "Train a random forest model to predict dog intelligence based on height and weight." before we go into the steps.

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In this tutorial we will use the try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download [this dataset](PLACEHOLDER LINK) and import it into y
If the data is coming from somewhere that you need to create an account to download it (like Kaggle), maybe we should put it as a prerequisite.

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +If you do not have a GitHub account, you can create one for free on the [GitHub website](https://github.com/signup). To create a personal access token, see the [official GitHub documentation](https:/
Let's move this under prerequisites

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +If a DAG with the same file as a file name already exists (i.e. if you already had a file named `dog_smarts_pipeline` in the `/dags` folder of this repository) the Cloud IDE will overwrite the existi
should this be "same filename as your cloud IDE pipeline name"? "same file as a file name" confused me

2022-11-01 21:48 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +Additionally, the Cloud IDE will create a GitHub workflow to deploy to Astro in `.github/workflows/astro_deploy.yaml`.
I think the start of this step needs more context. Is "additionally" to what happened in Step 10?

2022-11-02 19:07 UTC, TJaniF reviewed
Thank you for your review @kentdanas, I think I addressed all the comments. 

@jwitz ready for you tomorrow 🙂

2022-11-02 19:07 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +If a DAG with the same file as a file name already exists (i.e. if you already had a file named `dog_smarts_pipeline` in the `/dags` folder of this repository) the Cloud IDE will overwrite the existi
Oh yes that is a typo. The first one is correct.

2022-11-02 19:07 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +Additionally, the Cloud IDE will create a GitHub workflow to deploy to Astro in `.github/workflows/astro_deploy.yaml`.
Yes, additionally in the sense that the Cloud IDE creates the DAGfile and the workflow

2022-11-02 20:36 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +- Basic Airflow concepts. See [Introduction to Apache Airflow](intro-to-airflow.md).
Hmm....yeah I could go either way with this one. We do imply things in this section should be read prior, but in reality I doubt anyone does that :) so seems a decent place to link to them. For the Astro SDK tutorial we link to the documentation in the conclusion `As a next step, read the [Astro Python SDK documentation](https://astro-sdk-python.readthedocs.io/) to learn more about its functionality and task decorators.`, so maybe we should copy that pattern.

2022-11-02 21:18 UTC, kentdanas reviewed
Adding a couple additional comments here, but this is looking good!

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In this tutorial we will try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download the [ dog_intelligence.csv ] PLACEHOLDER LINK dataset which i
I think we should add the note about Kaggle in an info box

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In this tutorial we will try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download the [ dog_intelligence.csv ] PLACEHOLDER LINK dataset which i
```suggestion
Now that you have your Cloud IDE project set up, you can move on to creating an ML pipeline. For this tutorial you will try to predict the intelligence of a dog breed based on their upper and lower height and weight limits. Download the [ dog_intelligence.csv ] PLACEHOLDER LINK dataset which is a slightly changed version of [this dataset on Kaggle](https://www.kaggle.com/datasets/jasleensondhi/dog-intelligence-comparison-based-on-size) and import it into your database. 
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +If you are using Snowflake follow these steps:
```suggestion
```
I would remove this sentence and add an info or note box somewhere below the steps that says these steps are specific to Snowflake and may need to be modified for other db's

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +4. Paste the following SQL code into your cell to select all records that do not contain any NULL values in any column. Make sure to add your database and schema name to in the code.
```suggestion
4. Paste the following SQL code into your cell. This query will select all records that do not contain any NULL values in any column. Make sure to update the query with your database and schema name.
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +With the **Table Expression** box activated you should now see the output containing of 136 rows below the cell.
```suggestion
With the **Table Expression** box activated you should now see the output containing 136 rows below the cell.
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +Our dataset contains information about the height, weight and how fast dogs of different breeds learned commands in 7 columns. `reps_lower` and `reps_higher` contain the lower and upper bounds of how
```suggestion
The dataset has 7 columns containing information about the height, weight, breed, and learning speed of different dogs. The `reps_lower` and `reps_higher` columns contain the lower and upper bounds of how many repetitions of a new command each breed of dog needed to learn it. This value is used to sort the dogs into two categories which will be the target of your classification model. The predictors will be the four columns containing height and weight information.
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +Transform the data in your table to convert the dog intelligence data from repetitions needed to learn commands to a binary intelligence category.
```suggestion
Before you can train the model, you first need to transform the data in your table to convert the command repetitions to a binary intelligence category.
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +In the output table you can see that this SQL statement created a new transformed temporary table with a binary `INTELLIGENCE_CATEGORY` column which will be used as a target for your classification m
```suggestion
The output table should contain a new binary `INTELLIGENCE_CATEGORY` column which will be used as a target for your classification model. All dogs who needed 25 or fewer repetitions to learn a new command are put in the `very_smart_dog` category. All other dogs are put in the `smart_dog` category (because of course, all dogs are smart).
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +The Python code:
```suggestion
The Python code completes the following steps:
```

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +1. Set the "START DATE" to the 31st of October 2022.
Maybe we should say "the start of your work week" or something generic so that people aren't scheduling pipelines way in the past if they follow this a year from now :)

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +## Step 9: Schedule your pipeline
What does scheduling the pipeline within the Cloud IDE do if you don't convert it to a DAG and deploy it to Astro? In general, somewhere in here I think we should be a bit more explicit about the difference between an IDE pipeline and an Airflow DAG, and how to bridge the gap between the two (presumably steps 10-12, but let's make that clear to the reader).

2022-11-02 21:18 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +PLACEHOLDER - image of the DAG shown on Astro (once I get a cluster)
Now that I've read the whole thing again, I think a short conclusion section with a link to the cloud IDE docs like we have in the SDK tutorial would be good here. https://docs.astronomer.io/learn/astro-python-sdk

2022-11-03 11:46 UTC, TJaniF reviewed
Thank you @kentdanas . I hope I addressed all the comments (made a small gitmistake along the way). Completed the deployment steps and added a conclusion.

2022-11-03 11:46 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +- Basic Airflow concepts. See [Introduction to Apache Airflow](intro-to-airflow.md).
That is true! I added it both, a bullet point in assumed knowledge and a sentence in the conclusion :)

2022-11-03 11:46 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +## Step 9: Schedule your pipeline
Hmm.. I don't think the option of not converting it to a DAG exists, the only way I can see is by committing the pipeline to GitHub which always converts it to a DAG. But maybe I misunderstood something there? 

I added a chapter about viewing the converted DAG code with a screenshot and tried to explain the difference between the IDE and running the DAG on Airflow there :)

2022-11-03 11:46 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +1. Set the "START DATE" to the 31st of October 2022.
Haha good point, I just now realized you can't set catchup in the UI, will ask the team if they want to auto set that in the converted DAG code 😅 . I told the user to use yesterday's date.

2022-11-03 15:40 UTC, jwitz commented on sidebarsTutorials.js
> +    'cloud-ide-tutorial',
That's because this should be in `sidebarsLearn.js`! I'm actually not even sure why we still have this sidebar file, want to delete it in this PR?

2022-11-04 08:59 UTC, TJaniF commented on sidebarsTutorials.js
> +    'cloud-ide-tutorial',
🤦 thank you! Yes, I deleted the old file.

2022-11-04 17:01 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Create your first SQL cell by clicking on **Add Cell** in the topleft corner and selecting **SQL**.
```suggestion
1. Create your first SQL cell by clicking **Add Cell** and selecting **SQL**. A cell is equivalent to an Airflow task. However, you don't have to know how to write an Airflow task to write a cell!
```

2022-11-04 17:01 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +3. In the right sidebar click on the top "Pipeline" icon to view your cell in the pipeline view.
```suggestion
3. Click **Pipeline** to view your cell as a data pipeline.
```

2022-11-04 17:01 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Pipeline View](/img/guides/cloud_ide_pipeline_view.png)
```suggestion
    ![Pipeline View](/img/guides/cloud_ide_pipeline_view.png)
```

2022-11-04 17:01 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +```sql
Indent this fence by 4 spaces

2022-11-04 17:02 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +4. Paste the following SQL code into your cell. This query will select all records that do not contain any NULL values in any column. Make sure to update the query with your database and schema name.
```suggestion
4. Paste the following SQL code into your cell. This query selects all records that do not contain any `NULL` values in any column. Make sure to update the query with your database and schema name.
```

2022-11-04 17:02 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Select Snowflake Connection](/img/guides/cloud_ide_select_connection.png)
```suggestion
    ![Select Snowflake Connection](/img/guides/cloud_ide_select_connection.png)
```

2022-11-04 17:02 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +5. Select your Snowflake connection as shown in the screenshot below.
```suggestion
5. Add your Snowflake connection to the cell as shown in the following screenshot:
```

2022-11-04 17:05 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +6. Run the cell by either clicking on the play button next to the connection field or by hitting Command + Enter.
```suggestion
6. Run the cell by clicking the play button next to the connection.
```

2022-11-04 17:06 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +Running the cell will create a temporary table in your database containing the output from your query.
```suggestion
Running the cell creates a temporary table in your database containing the output from your query.
```

2022-11-04 17:07 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +With the **Table Expression** box activated you should now see the output containing 136 rows below the cell.
```suggestion
Below the cell, click **RESULTS** and tick the **Table Expression** checkbox to see the output containing 136 rows.
```

2022-11-04 17:09 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +```sql
Indent the fence by 4 spaces

2022-11-04 17:15 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +You will notice that pasting this SQL statement will automatically create a dependency between `query_table` and `transform_table` in the pipeline view on the right side of the screen (see the screen
```suggestion
Notice that after you create this cell, the Cloud IDE automatically creates a dependency between `query_table` and `transform_table` in the pipeline view. This happens because the SQL statement in `transform_table` references the temporary table created by the `query_table` task using the Jinja syntax `{{query_table}}`.
```

2022-11-04 17:16 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +The output table should contain a new binary `INTELLIGENCE_CATEGORY` column which will be used as a target for your classification model. All dogs who needed 25 or fewer repetitions to learn a new co
```suggestion
The output table should contain a new binary `INTELLIGENCE_CATEGORY` column which will be used as a target for your classification model. All dogs who needed 25 or fewer repetitions to learn a new command are put in the `very_smart_dog` category. All other dogs are put in the `smart_dog` category (because, of course, all dogs are smart).
```

2022-11-04 17:21 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Create a new Python cell by clicking on **Add Cell** in the topleft corner and selecting **Python**.
```suggestion
1. Create a new Python cell by clicking **Add Cell** and selecting **Python**. 
```

2022-11-04 17:21 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +```python
Indent this code fence by 4 spaces

2022-11-04 17:22 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- Scores the trained model on the testing data.
```suggestion
- Import necessary functions and classes from the `scikit-learn` package.
- Calculate the baseline accuracy, which is the accuracy you would get if you always guessed the most common outcome (in our data `smart_dog`).
- Separate out predictors (height and weight information) and the target (the intelligence category).
- Split the data into a training and testing set.
- Standardize the predicting features.
- Train a [RandomForestClassifier model](https://scikit-learn.org/stable/modules/ensemble.html#forest) on the training data.
- Score the trained model on the testing data.
```

2022-11-04 17:29 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +The output of the cell will show you both the baseline and the model accuracy. With the model accuracy being higher than baseline we can conclude that height and weight of dogs have a correlation (bu
```suggestion
The output of the cell shows you both the baseline and the model accuracy. With the model accuracy being higher than baseline, you can conclude that height and weight of dogs have a correlation (but not necessarily causation!) with how many repetitions they need to learn a new command. 
```

2022-11-04 17:29 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +:::
```suggestion
To learn more about random forests check out this [MLU explain article](https://mlu-explain.github.io/random-forest/).
```

2022-11-04 17:30 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Click on the calendar symbol ("Schedule") in the right sidebar to see possibilities to schedule your DAG.
```suggestion
1. Click **Schedule** to see your DAG's current schedule. 
```

2022-11-04 17:31 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +2. Set the "START DATE" to yesterday's date.
```suggestion
2. Set **START DATE** to yesterday's date.
```

2022-11-04 17:31 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +
```suggestion
    ![Schedule DAG](/img/guides/cloud_ide_schedule_dag.png)

3. Edit **CRON STRING** to schedule your DAG to run every weekday at 2:30 AM and 6:30 PM.

    ![CRON menu](/img/guides/cloud_ide_cron_menu.png)

4. Click **Update Settings** to save your schedule.

```

2022-11-04 17:38 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +Pipelines in the Cloud IDE offer you the possibility of running ad-hoc analysis and easy DAG development. Once you finish a pipeline and want to run it in a local Airflow instance or on Astro you wil
```suggestion
Through this tutorial, the Astro Cloud IDE was building a DAG based on the configurations you set in the Cloud UI. Export your pipeline as DAG code to see the results of your work.
```
Don't want to make it sound that easy to run the DAG when you export code, as there's currently no automatic way to get the connection info/ etc out of the IDE and into a local env.

2022-11-04 17:42 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Click on the "Code" tab on the right sidebar. You can see your pipeline which was automatically converted to DAG code using the [Astro SDK](https://docs.astronomer.io/learn/astro-python-sdk-etl).
```suggestion
1. Click **Code**. You can see that your pipeline was automatically converted to DAG code using the [Astro SDK](https://docs.astronomer.io/learn/astro-python-sdk-etl).
```

2022-11-04 17:42 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![View Code](/img/guides/cloud_ide_code_view.png)
```suggestion
    ![View Code](/img/guides/cloud_ide_code_view.png)
```

2022-11-04 17:43 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +2. Click **Download** in order to download the DAG file if you want to manually add it to a project.
```suggestion
2. Click **Download** to download the DAG file.
```

2022-11-04 17:44 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Click on the GitHub **Configure** button in the topright corner of your screen to connect your Cloud IDE Project to your GitHub account.
```suggestion
1. Click **Configure** to connect your Cloud IDE Project to your GitHub account.
```

2022-11-04 17:44 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Connect to GitHub](/img/guides/cloud_ide_github_conn.png)
```suggestion
    ![Connect to GitHub](/img/guides/cloud_ide_github_conn.png)
```

2022-11-04 20:56 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +title: 'Write and schedule a simple ML pipeline using the Cloud IDE'
The email that went out to customers on Tuesday uses "Astro Cloud IDE", so we should probably use that.

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +When you commit a Cloud IDE pipeline to a GitHub repository, the Cloud IDE will create a GitHub workflow of the name `astro_deploy.yaml` in case it does not exist yet.
```suggestion
When you first commit a Cloud IDE pipeline to a GitHub repository, the Cloud IDE will create a GitHub workflow named `astro_deploy.yaml`. This action can be modified to fit your CI/CD workflow, or used out of the box after you configure a few environment variables. 
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Configure [GitHub Actions](https://docs.astronomer.io/astro/ci-cd?tab=multibranch#github-actions) by setting the following as [GitHub secrets](https://docs.github.com/en/actions/security-guides/en
```suggestion
1. Set the following [GitHub secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in your repository:
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![GitHub Secrets](/img/guides/cloud_ide_github_secrets.png)
```suggestion
    - DEV_ASTRONOMER_KEY_ID = `<your-dev-key-id>`
    - DEV_ASTRONOMER_KEY_SECRET = `<your-dev-key-secret>`
    - DEV_ASTRONOMER_DEPLOYMENT_ID = `<your-deployment-id>`

    ![GitHub Secrets](/img/guides/cloud_ide_github_secrets.png)
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +If GitHub Actions is already configured for your chosen repository the new DAG will be deployed automatically with the first commit.
Need to check whether this is already handled by the IDE

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +:::info
```suggestion
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +:::
```suggestion
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- A GitHub account with access to a private or public repository that contains an Airflow Project created by the [Astro CLI](https://docs.astronomer.io/astro/cli/install-cli) as well as a Personal Ac
```suggestion
- A GitHub account with access to a private or public repository that contains an Airflow Project created by the [Astro CLI](https://docs.astronomer.io/astro/cli/install-cli) 
- A Personal Access Token for your GitHub account. To create a personal access token, see the [official GitHub documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +To be able to deploy your DAG the Runtime Image used in the Airflow project of your GitHub repo needs to be compatible with the Runtime Image used in your Astro cloud deployment. You might need to ch
```suggestion
To deploy your DAG, the Runtime image used in the `Dockerfile` of your Astro project needs to be the same as the Runtime image used in your Astro Deployment.
```
I'm not sure this is accurate tbh, or at least I'm not sure we need to mention this. If the GitHub project is already deployed to Astro, the Runtime versions should be the same. Deploying with a later Runtime version would automatically upgrade the Deployment, and the DAG deploy would then also be successful.

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +1. Back on Astro, click on the Astronomer logo to exit the pipeline editor.
```suggestion
1. In the Cloud UI, open your Deployment. 
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Run DAG on Astro](/img/guides/cloud_ide_dag_ran_in_UI.png)
```suggestion
2. Click **Open Airflow**

3. In the Airflow UI, configure a connection with the same values as your connection in the Astro Cloud IDE. See [Manage connections in Apache Airflow](connections.md).

4. Since temporary tables are not JSON serializable, you need to enable XCom pickling which is on by default in the Astro Cloud IDE. Go to **Admin** -> **Variables** and add a new variable with a key of `AIRFLOW__CORE__ENABLE_XCOM_PICKLING` and a value of `True`. Click **Save**.

    ![Add Variable in Airflow UI](/img/guides/cloud_ide_add_variable.png)

5. Go to **DAGs** and run your DAG by clicking the play button.

    ![Run DAG on Astro](/img/guides/cloud_ide_dag_ran_in_UI.png)
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Run DAG on Astro](/img/guides/cloud_ide_dag_ran_in_UI.png)
Should we have a step to confirm the data is appearing in their database?

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- Pass information between SQL and Python cells
```suggestion
- Pass information between SQL and Python cells.
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- Use a SQL cells to query and transform tables in a database.
```suggestion
- Use a SQL cell to query and transform tables in a database.
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- Run a simple RandomForestClassifier on a dataset.
```suggestion
- Run a simple `RandomForestClassifier` on a dataset.
```

2022-11-07 12:51 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +As a next step, read the [Cloud IDE documentation](https://docs.astronomer.io/astro/cloud-ide) to learn more about this next generation DAG writing environment.
```suggestion
See the [Cloud IDE documentation](https://docs.astronomer.io/astro/cloud-ide) to learn more about this next-generation DAG writing environment.
```

2022-11-08 20:57 UTC, TJaniF reviewed
Thanks for the thorough review! I accepted most suggestions and tried to rework the chapters around GitHub and GitHub actions to be a bit clearer and direct the user earlier to commit the changes to a separate branch and then PR.

2022-11-09 12:15 UTC, TJaniF reviewed
I think now I addressed all your comments @jwitz @kentdanas :) . I tried to rewrite the final 2 steps to make it clearer that we recommend using a dedicated branch to commit to. Also I switched out the screenshots that showed the slightly different pre-release UI or had a different project name etc.

2022-11-09 18:12 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +## Step 10: View your DAG code
```suggestion
## Step 10: View your DAG code (Optional)
```

2022-11-11 15:57 UTC, jwitz approved these changes
Main content LGTM @TJaniF ! Don't want to block this getting published, but we might want to write a follow-up issue to crop the screenshots to be more focused. A few of them show an entire window when there's only one or two elements in the window that the user needs to care about

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +2. In the "Package name" field, type `scikit-learn`. The Astro Cloud IDE produces a list of packages to chose from.
```suggestion
2. In the "Package name" field, type `scikit-learn`. The Astro Cloud IDE produces a list of packages to choose from.
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +Export your DAG by commiting it to your connected GitHub repository.
updated my suggestion, should be good to apply now!

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Add scikit-learn](/img/guides/cloud_ide_add_requirement.png)
```suggestion
    ![Add scikit-learn](/img/guides/cloud_ide_add_requirement.png)
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +The dataset we use in this tutorial is a slightly modified version of [this dataset on Kaggle](https://www.kaggle.com/datasets/jasleensondhi/dog-intelligence-comparison-based-on-size).
```suggestion
The dataset used in this tutorial is a slightly modified version of [this dataset on Kaggle](https://www.kaggle.com/datasets/jasleensondhi/dog-intelligence-comparison-based-on-size). 
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Load csv Snowflake](/img/guides/cloud_ide_load_csv.png)
```suggestion
    ![Load csv Snowflake](/img/guides/cloud_ide_load_csv.png)
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Table output](/img/guides/cloud_ide_query_table.png)
```suggestion
    ![Table output](/img/guides/cloud_ide_query_table.png)
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Table output](/img/guides/cloud_ide_cell_dependency.png)
```suggestion
    Notice that after you create this cell, the Astro Cloud IDE automatically creates a dependency between `query_table` and `transform_table` in the pipeline view. This happens because the SQL statement in `transform_table` references the temporary table created by the `query_table` task using the Jinja syntax `{{query_table}}`.

    ![Table output](/img/guides/cloud_ide_cell_dependency.png)
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +- Score the trained model on the testing data.
```suggestion
    You will notice again how the Astro Cloud IDE will automatically create a dependency between the `transform_table` task and the `model_task` task. The Python code above references the `transform_table` object returned from the `transform_table` cell directly (without Jinja syntax) on line 6. 

    The Python code completes the following steps:

    - Import necessary functions and classes from the `scikit-learn` package.
    - Calculate the baseline accuracy, which is the accuracy you would get if you always guessed the most common outcome (in our data `smart_dog`).
    - Separate out predictors (height and weight information) and the target (the intelligence category).
    - Split the data into a training and testing set.
    - Standardize the predicting features.
    - Train a [RandomForestClassifier model](https://scikit-learn.org/stable/modules/ensemble.html#forest) on the training data.
    - Score the trained model on the testing data.
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +:::
```suggestion
  :::caution

  If a file with the same name as your Astro Cloud IDE pipeline already exists in your GitHub repository, the Astro Cloud IDE will overwrite the existing file. For this reason, Astronomer recommends using a separate branch for commits from your Astro Cloud IDE environment than for commits from other sources to the same repository.

  :::
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +![Dags folder on GitHub](/img/guides/cloud_ide_dags_github.png)
```suggestion
    Your DAG will be added to the `/dags` folder in your GitHub repository.

    ![Dags folder on GitHub](/img/guides/cloud_ide_dags_github.png)
```

2022-11-11 15:57 UTC, jwitz commented on learn/cloud-ide-tutorial.md
> +sidebar_label: 'Astro Cloud IDE - Simple ML pipeline'
```suggestion
sidebar_label: 'Astro Cloud IDE - Write an ML pipeline'
```
I like this format of showing both the subject and the context in the sidebar. We could do something similar with "Astro Python SDK - Write an ETL DAG"

2022-11-11 16:07 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +2. In the "Package name" field, type `scikit-learn`. The Astro Cloud IDE produces a list of packages to chose from.
One day I'll get this right. 🤦

2022-11-11 18:23 UTC, kentdanas approved these changes
Great work on this, it looks amazing!

2022-11-11 19:16 UTC, TJaniF commented
Thank you @jwitz and @kentdanas ! :) 

> Main content LGTM @TJaniF ! Don't want to block this getting published, but we might want to write a follow-up issue to crop the screenshots to be more focused. A few of them show an entire window when there's only one or two elements in the window that the user needs to care about

Yeah that is one of the things I am often unsure about when it makes sense to show more and when less. I'll make a separate PR for it :)

2022-11-11 19:16 UTC, merged