[Draft] plugins base PR draft - tutorial
astronomer/docs pull request #1438
Opened 2022-11-07 11:02 UTC by TJaniF

PR for the plugins guide update and an operator extra links tutorial. Still a draft. :)

2022-11-07 21:56 UTC, kentdanas reviewed
Some initial comments on the tutorial - it looks great so far! 

Another question - do we think Plugins belongs under Infrastructure? It's kind of infra....but also not really. Thinking maybe it should go under 'Advanced'...

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +sidebar_label: 'Add an operator extra link via plugin'
Wondering if we should make this just "Add an operator extra link" to shorten a bit?

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +You can add custom links to Airflow operators for easy access of related information from the Airflow UI.
I think we should make this a bit more descriptive. It's likely that many users coming to this tutorial will already know what an "extra link" is, but for those who might not maybe we can explain a bit more.

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +This tutorial shows how to add extra links using an Airflow plugin. Alternatively extra links can be added to operators when creating an [Airflow provider](https://airflow.apache.org/docs/apache-airf
```suggestion
This tutorial shows how to add extra links using an Airflow plugin. Alternatively, extra links can be added to operators when creating an [Airflow provider](https://airflow.apache.org/docs/apache-airflow-providers/index.html).
```
As part of the clarification above, maybe it would be good to note whether this applies to custom operators or pre-built ones (or both). And say a bit more about when you would create a provider to do this - this may not be something most Airflow users have encountered, and probably won't be relevant to many.

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 1: Create a new Airflow project
```suggestion
## Step 1: Create an Astro project
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +Run the `astro dev init` command in an empty folder to create your Airflow project. If this command is not available to you, make sure you correctly installed the [Astro CLI](https://docs.astronomer.
```suggestion
Set up Airflow by creating a new Astro project:

Create a new Astro project:

  ```sh
  $ mkdir astro-extra-link-tutorial && cd astro-extra-link-tutorial
  $ astro dev init
  ```
```
Feel free to adjust, just making this consistent with our other tutorials.

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +As a first step we are going to add a static extra link to the SimpleHttpOperator.
```suggestion
First you will add a static extra link to the SimpleHttpOperator.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +2. Copy paste the following DAG code into your file. It defines a DAG with one tasks that uses the SimpleHttpOperator to post a GET request to the connection defined as `random_user_api_conn`.
```suggestion
2. Copy paste the following DAG code into your file:
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +
```suggestion
This DAG has one SimpleHttpOperator task that posts a GET request to API provided in the `random_user_api_conn` connection.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +To add an extra link to an operator you will have to create an [Airflow plugin](using-airflow-plugins.md).
Maybe describe here what the extra link will do?

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +To add an extra link to an operator you will have to create an [Airflow plugin](using-airflow-plugins.md).
```suggestion
Create an [Airflow plugin](using-airflow-plugins.md) to add an extra link to the operator.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. Run `astro dev start` to start up Airflow. If your Airflow instance is already running use `astro dev restart` to restart it in order to load any changes made in the `/plugins` folder.
```suggestion
1. In your terminal, run `astro dev start` to start up Airflow. If your Airflow instance is already running use `astro dev restart` to restart it in order to load any changes made in the `/plugins` folder.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 4: View your extra link in the UI
I would break this up into 2 high level steps, one to start the project and create the connection, and then another to run the DAG and view the results. (again to be consistent with how we've formatted some of the other tutorials)

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 5: Create a custom CatHttpOperator
```suggestion
## Step 5: Create a custom operator
```
Since the section titles show up in the nav bar I think we should keep them generic. On the off-chance anybody scans them and thinks they don't need a "CatHttpOperator" :)

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. Go to the `/include` folder of your Airflow project and create a new file called `cat_http.py`.
```suggestion
1. Create a new file called `cat_http.py` in the `include/` folder of your Airflow project.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +```python
I think the code block should be indented so it shows up under sub-step 2

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +The code above defines a custom slightly modified version of the `SimpleHttpOperator`, called the `CatHttpOperator`. The change consists of adding one line before the `return` statement of the `.exec
```suggestion
The code above defines a custom version of the `SimpleHttpOperator`, called the `CatHttpOperator`. The change consists of adding one line before the `return` statement of the `.execute()` method which is `context["ti"].xcom_push(key="status_code", value=response.status_code)`. This line pushes the `status_code` attribute of the `response` object to XComs and associates it with the key `status_code`. The rest of the `.execute()` method is identical to the parent operator (compare the source code of the [SimpleHttpOperator](https://github.com/apache/airflow/blob/main/airflow/providers/http/operators/http.py)).
```
Same here, this should also be indented

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +Before Airflow 2.0 custom operators and hooks were added as plugins. This pattern has been deprecated and custom operators and hooks can now be simply by importing a script located in `/include`.
```suggestion
Before Airflow 2.0, custom operators and hooks were added as plugins. This pattern has been deprecated and custom operators and hooks can now be simply by importing a script located in `/include`.
```
I think we have a guide on importing custom hooks and operators that we could link to here?

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 6: Use the CatHttpOperator in your DAG
```suggestion
## Step 6: Create a DAG with your custom operator
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. In the `/dags` folder import the `CatHttpOperator` by adding the import statement:
I would start this section by telling them to create a new file. Unless you want them to update the DAG from above, in which case say that

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. Run the `plugins_test_dag`, which now consists of two tasks again.
```suggestion
1. Run the `plugins_test_dag`, which now consists of two tasks. 
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 7: See the modified XComs
```suggestion
## Step 7: Run your DAG and view modified XComs
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +![XCom tab](/img/guides/extra_links_tutorial_xcom_tab.png)
indent here

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +![HTTP status code returned](/img/guides/extra_links_tutorial_http_code.png)
and indent here

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +3. Verify that the XCom for this task instance contain an entry for `status_code`. In the screenshot below the HTTP status code returned was 200.
```suggestion
3. Verify that the XCom for this task instance contains an entry for `status_code`. In the screenshot below the HTTP status code returned was 200.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +## Step 8: Add a dynamic extra link to the CatHttpOperator
```suggestion
## Step 8: Add a dynamic extra link to your custom operator
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +5. Save the file and restart your Airflow instance.
```suggestion
5. Save the file and restart your Airflow instance with `astro dev restart`.
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +        http_conn_id="randomuser_api",
```suggestion
        http_conn_id="random_user_api_conn",
```

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +![XCom tab](/img/guides/extra_links_tutorial_xcom_tab.png)
You might want to circle the status_code in the screenshot. I was looking for it in the long return value text 🤦‍♀️

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +3. Copy paste the following code which creates a class called `CatLink` derived from `BaseOperatorLink`.
I would be clear that you need to add this class above the `AirflowExtraPlugin` class, otherwise `Catlink()` won't be defined (I initially just pasted it at the bottom of the script).

2022-11-07 21:56 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +4. Add the new link to the `operator_extra_links` list i the `AirflowExtraLinkPlugin` class.
```suggestion
4. Update the `operator_extra_links` list in the `AirflowExtraLinkPlugin` class with the new `CatLink()`. The class should look like this:
```
Trying to make it clear that we're updating the existing code, but providing the entire class again.

2022-11-07 21:56 UTC, kentdanas commented on learn/using-airflow-plugins.md
>  id: using-airflow-plugins
I know the original title was "import plugins to Airflow", but I'm not a huge fan of that. Maybe we just say "Airflow Plugins"?

2022-11-10 21:49 UTC, kentdanas requested changes
@TJaniF some minor comments, but overall this looks great! I think the Plugins concept guide is a great mix of very comprehensive and useful but also straight forward and not too long for how much ground it covers.

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +Airflow offers the possibility to customize its UI with plugins. One small but impactful addition that is easy to make are extra links in the Details view of both existing and custom operators. These
```suggestion
Airflow offers the possibility to customize its UI with plugins. One small but impactful addition is adding extra links in the **Details** view of either existing or custom operators. These operator extra links can point to static websites, for example to access documentation relevant to the operator, or dynamic links created from information during the task instance run. 
```
This description is much better! What do we think of also adding a screenshot of the details view here circling an extra link?

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +- Add operator extra links to an Airflow plugin.
Is this last bullet actually something different than bullets one and three? Or just saying that's _how_ you add the extra link? If the latter I would remove it and add "using an Airflow plugin" to the ends of bullets one and three.

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +This tutorial shows how to add both static and dynamic extra links using an Airflow plugin. Alternatively, extra links can be added to operators when creating an [Airflow provider](https://airflow.ap
```suggestion
This tutorial shows how to add both static and dynamic extra links using an Airflow plugin.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +
:::tip

Extra links can be also be added to operators when creating an [Airflow provider](https://airflow.apache.org/docs/apache-airflow-providers/index.html). In general, adding an operator extra link via plugin as described in this tutorial is easier for use in a limited number of Airflow instances. However, if you are planning to use the extra link in a large number of deployments, consider adding them to an Airflow provider instead. 

:::

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +Create a new Astro project:
```suggestion
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +First you will add a static operator extra link to the SimpleHttpOperator which will add a button with a link to the [Mozilla HTTP documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP) to
```suggestion
First you will add a static operator extra link to the SimpleHttpOperator, which will link to the [Mozilla HTTP documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP) on every task instance created by this operator.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +- Importing the `AirflowPlugin` class which serves as a base class for custom plugins as well as the `BaseOperatorLink` from which classes defining custom extra links inherit.
```suggestion
- Import the `AirflowPlugin` class which serves as a base class for custom plugins as well as the `BaseOperatorLink` from which classes defining custom extra links inherit.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +- Defining a custom extra link class called `HTTPDocsLink` which inherits from `BaseOperatorLink` and adds an external link button in the Airflow UI to all operators provided to its `operators` attri
```suggestion
- Define a custom extra link class called `HTTPDocsLink` which inherits from `BaseOperatorLink` and adds an external link button in the Airflow UI to all operators provided to its `operators` attribute. In the example, we provide the `SimpleHttpOperator`.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +- Providing a static link to the HTTP documentation on Mozilla to the `.get_link()` method of the `HTTPDocsLink`. This method adds any link returned to the link button in Airflow UI.
```suggestion
- Provide a static link to the HTTP documentation on Mozilla to the `.get_link()` method of the `HTTPDocsLink`. This method adds any link returned to the link button in Airflow UI.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +- Creating the `AirflowExtraLinkPlugin` class which inherits from `AirflowPlugin`. This class will plug objects of [different plugin types](using-airflow-plugins.md) into Airflow. The plugin is given
```suggestion
- Create the `AirflowExtraLinkPlugin` class which inherits from `AirflowPlugin`. This class will plug objects of [different plugin types](using-airflow-plugins.md) into Airflow. The plugin is given the name `extra_link_plugin` and its `operator_extra_links` attribute contains all extra links objects that have been defined in this plugin script. For now it contains only `HTTPDocsLink()`.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. In your terminal, run `astro dev start` in your Astro project directory to start up Airflow. If your Airflow instance is already running use `astro dev restart` to restart it in order to load any
```suggestion
1. In your terminal, run `astro dev start` in your Astro project directory to start up Airflow. If your Airflow instance is already running, use `astro dev restart` to restart it in order to load any changes made in the `plugins` folder.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +    ![HTTP docs button](/img/guides/extra_links_tutorial_HTTPDocsLink_button.png)
Maybe circle the link in this screenshot?

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +    The code above defines a custom version of the `SimpleHttpOperator`, called the `CatHttpOperator`. The change consists of adding one line before the `return` statement of the `.execute()` method
```suggestion
The code above defines a custom version of the `SimpleHttpOperator`, called the `CatHttpOperator`. The change consists of adding one line before the `return` statement of the `.execute()` method which is `context["ti"].xcom_push(key="status_code", value=response.status_code)`. This line pushes the `status_code` attribute of the `response` object to XComs and associates it with the key `status_code`. The rest of the `.execute()` method is identical to the parent operator (compare the source code of the [SimpleHttpOperator](https://github.com/apache/airflow/blob/main/airflow/providers/http/operators/http.py)).
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +Before Airflow 2.0, custom operators and hooks were added as plugins. This pattern has been deprecated and [custom operators and hooks](airflow-importing-custom-hooks-operators.md) can now be simply
```suggestion
Before Airflow 2.0, custom operators and hooks were added as plugins. This pattern has been deprecated and [custom operators and hooks](airflow-importing-custom-hooks-operators.md) can now be used simply by importing a script located in `include`.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +            task_id="call_api_cat",
Looks like things are double-indented here?

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +In this guide you'll learn how to add a plugin to your Airflow instance as well as what components can be part of a plugin.
```suggestion
In this guide, you'll learn how to add a plugin to your Airflow instance and what Airflow components can be part of a plugin.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Plugins offer a flexible way to customize your Airflow experience by building on top of existing Airflow components. For example you can:
```suggestion
Plugins offer a flexible way to customize your Airflow experience by building on top of existing Airflow components. For example, you can:
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +- Build an application that monitors Airflow's functioning itself and sends out custom alerts, for example in case of a certain number of DAGs failing in a specified time frame.
```suggestion
- Build an application that monitors Airflow's functioning and sends out custom alerts, for example in case of a certain number of DAGs failing in a specified time frame.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +- Add dynamic links to task instances to files and logs in external data tools the task has been performed on.
```suggestion
- Add a button to the task instance **Details** view that dynamically links to files or logs in external data tools relevant to the task.
```
Tried to reword this to clarify, but if I got it wrong feel free to update.

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +To add a new plugin to your Airflow instance you need to create a Python file in the `plugins` folder of your Airflow project. Within that file a class which inherits from the `AirflowPlugin` class h
```suggestion
To add a new plugin to your Airflow instance, you need to create a Python file in the `plugins` folder of your Airflow project. Within that file, create a class which inherits from the `AirflowPlugin` to define the plugin. The code snippet below defines a plugin with the name `empty` without any components. 
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Airflow needs to be restarted for changes in plugins to be registered. Learn more in the [official Airflow documentation on plugins](https://airflow.apache.org/docs/apache-airflow/stable/plugins.html
```suggestion
The Airflow webserver needs to be restarted for changes in plugins to be registered. Learn more in the [official Airflow documentation on plugins](https://airflow.apache.org/docs/apache-airflow/stable/plugins.html#when-are-plugins-re-loaded).
```
Is that right, that the scheduler doesn't need to be restarted? If not feel free to ignore this. For the CLI it doesn't matter since you restart everything together, but it could be relevant in certain Airflow deployments.

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Before Airflow 2.0 custom operators and hooks were added as plugins. This pattern has been deprecated and [custom operators and hooks](https://docs.astronomer.io/learn/airflow-importing-custom-hooks-
```suggestion
Before Airflow 2.0 custom operators and hooks were added as plugins. This pattern has been deprecated and [custom operators and hooks](https://docs.astronomer.io/learn/airflow-importing-custom-hooks-operators) can now be used simply by importing a script located in `include`.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Functionality is added to a plugin by adding components to the class which defines the plugin. There are 10 types of plugin components, in this guide we want to highlight the following:
```suggestion
Functionality is added to a plugin by adding components to the class which defines the plugin. There are 10 types of plugin components that can be added to Airflow. In this guide we will show the more commonly used components, including:
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Other types of plugin components include:
```suggestion
Other types of plugin components not covered in this guide include:
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +- `timetables`, which offer the option to register custom timetables that define schedules which cannot be expressed in CRON. See the [DAG scheduling and timetables in Airflow guide](https://docs.ast
I would make the language in these bullets consistent with the ones above. e.g. either use "which" or don't - so "timetables offer the option to register....."

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +You can customize the Airflow menu at the top of the screen to contain custom tabs with links to external websites. Both adding top-level menu items as well as sub-items are supported.
```suggestion
You can update the menu at the top of the Airflow UI to contain custom tabs with links to external websites. Adding top-level menu items and adding sub-items are both supported. 
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +To add more elaborate customization to the Airflow UI plugins offer the possibility to add Flask blueprints and views as plugin components. A Flask blueprint functions as an organizational tool to gr
Guessing "html" should be capitalized?

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +You can access the button on task instences in both the Graph and Grid view.
```suggestion
You can access the button on task instances in both the **Graph** and **Grid** views.
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +In Airflow you can define custom macros which can be accessed using Jinja templating. Macros can be added at the dag level by defining them in the DAG parameter `user_defined_macros` as shown in [Usi
```suggestion
In Airflow you can define custom macros which can be accessed using Jinja templating. Macros can be added at the DAG level by defining them in the DAG parameter `user_defined_macros` as shown in [Using Airflow templates](templating.md). If you want to make macros available to your whole Airflow instance you can register them as a plugin. 
```

2022-11-10 21:49 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +### Macros
Might be worth noting in here somewhere some real-world use cases of when you would define a macro (if we can find any in slack or out in the wild)

2022-11-11 15:12 UTC, denimalpaca requested changes
A few line edits but overall I think it's great. Especially love the cat http site. Great find!

2022-11-11 15:12 UTC, denimalpaca commented on learn/operator-extra-link-tutorial.md
> +- Import the `AirflowPlugin` class which serves as a base class for custom plugins as well as the `BaseOperatorLink` from which classes defining custom extra links inherit.
"Imports" and similar changes in other lines to match the tense of "This script accomplishes..."

2022-11-11 15:12 UTC, denimalpaca commented on learn/operator-extra-link-tutorial.md
> +- Provide a static link to the HTTP documentation on Mozilla to the `.get_link()` method of the `HTTPDocsLink`. This method adds any link returned to the link button in Airflow UI.
in the Airflow UI

2022-11-11 15:12 UTC, denimalpaca commented on learn/operator-extra-link-tutorial.md
> +3. Click the Http Cat button to find the response your last API call got illustrated with a fitting cat.
response of & maybe call is instead of call got

2022-11-14 17:29 UTC, kentdanas commented
Closes #1405

2022-11-17 16:46 UTC, denimalpaca commented
> Thank you for the review @denimalpaca ! I added an alternative tab on Step 9 to show the direct addition of the link in the operator but so far I have not been able to get it to work. Is it possible this only works when the operator is part of a provider package? 🤔

Yes, this only works when it's part of a provider package, and the package files (like the `.egg` folder and whatever else is generated when building with wheels or setup.py) all need to exist in the interpreter's `site-packages` folder.

2022-11-18 15:10 UTC, TJaniF commented on learn/operator-extra-link-tutorial.md
> +Extra links can be also be added to operators when creating an [Airflow provider](https://airflow.apache.org/docs/apache-airflow-providers/index.html). In general, adding an operator extra link via p
It is now a second tab to step 9 called "using a provider". :)

2022-11-18 20:23 UTC, kentdanas approved these changes
These are looking great @TJaniF! A couple of very minor comments, but otherwise good from my side and we can move on to copy editing.

2022-11-18 20:23 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +    ```sh
```suggestion
    ```text
```
I don't think 'sh' is an option that renders - I'm seeing the ticks displayed in the code box in the deploy preview.

2022-11-18 20:23 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +The code above defines a custom version of the `SimpleHttpOperator`, called the `CatHttpOperator`. The change consists of adding one line before the `return` statement of the `.execute()` method whic
This paragraph should be indented so it renders under sub-step 2.

2022-11-18 20:23 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +1. Add `cat_http.py` to your provider package.
I'm not sure users here will know what it means to add the file to their provider package? Is there documentation on creating a provider we could link out to here?

2022-11-18 20:23 UTC, kentdanas commented on learn/operator-extra-link-tutorial.md
> +3. Click the Http Cat button to find the response of your last API call is illustrated with a fitting cat.
```suggestion
3. Click the HTTP Cat button to find the response of your last API call illustrated with a fitting cat.
```

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +Depending on which processes use your plugin you will need to restart the Airflow webserver, the Airflow scheduler or both components for changes changes in plugins to be registered. Learn more in th
```suggestion
In order for changes to your plugin to be registered, you will need to restart any Airflow components (e.g. the webserver or scheduler) that use the plugin. Learn more in the [official Airflow documentation on plugins](https://airflow.apache.org/docs/apache-airflow/stable/plugins.html#when-are-plugins-re-loaded).
```

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +To add more elaborate customization to the Airflow UI plugins offer the possibility to add Flask blueprints and views as plugin components. A Flask blueprint functions as an organizational tool to gr
```suggestion
Flask blueprints and views are plugin components that allow you to add more elaborate customization to the Airflow UI. A Flask blueprint functions as an organizational tool to group related views and supporting code while Flask views render webpages from html templates. 
```

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +The screenshot below shows an operator extra link called "HTTP cat" having been added to the custom CatHttpOperator in this [step-by-step tutorial](operator-extra-link-tutorial.md) on how to add oper
```suggestion
The screenshot below shows an operator extra link called "HTTP cat" that was added to the custom CatHttpOperator. For more instructions, see this [step-by-step tutorial](operator-extra-link-tutorial.md) on how to add operator extra links.
```

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +![Airflow Docs Button](/img/guides/global_operator_extra_link.png)
Maybe circle the docs button? Since the screenshot is big it might get a little lost if people don't know what they're supposed to be looking for.

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +- Injecting dynamic datetime objects into DAG code in formats not available in pre-defined macros. For example, converting the `{{ ts }}` predefined macro, which provides the logical date of the DAG
```suggestion
- Injecting dynamic datetime objects into DAG code in formats not available in pre-defined macros. For example, converting the `{{ ts }}` predefined macro, which provides the logical date of the DAG as a timestamp from `YYYY-MM-DDThh:mm:ss+00:00` to `hh:mm`. 
```

2022-11-18 20:23 UTC, kentdanas commented on learn/using-airflow-plugins.md
> +- Injecting dynamic arguments into DAG code based on Python logic. For example to use a different argument on weekdays than on the weekend.
```suggestion
- Injecting dynamic arguments into DAG code based on Python logic. For example, passing a different argument to a function on weekdays versus the weekend.
```

2022-11-21 12:18 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +    ```sh
This is because you don't need to indent the code fence unless it's part of a step. Setting this back to the beginning of the line should do the trick!

2022-11-21 16:40 UTC, denimalpaca commented
> Ready for a next round of reviews next week @jwitz @kentdanas 🙂
> 
> The main question remaining from my side is if it makes sense to have step 9 with the tab "Using a provider". Pro: it is something I am assuming quite a few users want to do but it is too similar to have a separate tutorial imho. Contra: It either is a bit hidden or we have to change the title to something like "Use a plugin or provider to add an operator extra link" which sounds convoluted. I think I lean towards including it but very open to other opinions.

I think this may do well just as a note. You're right that it's really not different enough to warrant its own track. But you could just have a tab that says "if you want to add this as a provider package, make sure you install it with the rest of the package using a setup.py file or wheels or whatever and that everything is added properly to requirements.txt".

2022-12-02 15:39 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +title: 'Use a plugin to add extra links to operators'
```suggestion
title: 'Customize Apache Airflow operators in the Airflow UI'
```

2022-12-02 16:29 UTC, jwitz reviewed
Leaving some initial comments @TJaniF , will check back after the changes are implemented to make sure the doc renders correctly in the preview site. Great work overall!

2022-12-02 16:29 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +This is all that is necessary to modify an existing operator.
```suggestion
```

2022-12-02 16:29 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +:::
```suggestion
```
I think it's okay to assume 2.0+ here, especially because we tell users to start a new project

2022-12-02 16:29 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +3. Copy paste the following code which creates a class called `CatLink` derived from `BaseOperatorLink` and paste it below the definition of the `HTTPDocsLink` class and above the definition of the `
```suggestion
3. Copy paste the following code below the definition of the `HTTPDocsLink` class and above the definition of the `AirflowExtraLinkPlugin` class. 
```

2022-12-02 16:29 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +    The code in the `.get_link()` method retrieves the `status_code` you pushed to XCom and appends it to the [HTTP cat Api link](https://http.cat/).
```suggestion
    This code creates a class called `CatLink` derived from `BaseOperatorLink`. The `.get_link()` method retrieves the `status_code` you pushed to XCom and appends it to the [HTTP cat Api link](https://http.cat/).
```

2022-12-04 20:51 UTC, TJaniF reviewed
Thank you @jwitz ! I made the changes :)

2022-12-04 20:51 UTC, TJaniF commented on learn/operator-extra-link-tutorial.md
> +This script accomplishes the following:
That is a good point. I changed the section to be more action oriented :)

2022-12-04 20:51 UTC, TJaniF commented on learn/operator-extra-link-tutorial.md
> +:::tip
Moved and merged the two tips that talk about this.

2022-12-04 20:51 UTC, TJaniF commented on learn/operator-extra-link-tutorial.md
> +This tutorial shows how to add both static and dynamic extra links using an Airflow plugin, as well as how to add an extra link directly in a custom operator.
I changed this sentence slightly because the second half was referring to a deleted part that talked about how to add the extra link within a provider.

2022-12-12 17:26 UTC, kentdanas commented
@jwitz think we're just waiting for your second pass on this one? I can manage any additional updates needed this week while Tamara is out, or let me know if we're good to publish :)

2022-12-13 11:37 UTC, jwitz approved these changes

2022-12-13 11:37 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +- Adds the `SimpleHttpOperator` to the list of operators this extra link will be applied to. You can add as many operators as you'd like, inlcuding custom operators.
```suggestion
- Adds the `SimpleHttpOperator` to the list of operators this extra link will be applied to. You can add as many operators as you'd like, including custom operators.
```

2022-12-13 11:37 UTC, jwitz commented on learn/operator-extra-link-tutorial.md
> +Another core feature of extra links is that you can dynamically generate them based information returned by an operator at run time. The second half of this tutorial will cover how to modify an opera
```suggestion
Another core feature of extra links is that you can dynamically generate them based on information returned by an operator at run time. The second half of this tutorial will cover how to modify an operator to push the value you need to [XComs](airflow-passing-data-between-tasks.md) and retrieve that value for use in an extra link.
```

2022-12-13 16:32 UTC, merged