Update changes for NVMe Drives
astronomer/docs pull request #1454
Opened 2022-11-09 00:22 UTC by dnarain-astro

2022-11-09 13:24 UTC, kwcanuck commented on astro/release-notes.md
> +AWS clusters that use `m5d` and `m6id` worker types can now use the full capacity of the NVMe SSD volumes available in these instances. Prior to this release, Astro used the utilization of the root v
```suggestion
AWS clusters that use `m5d` and `m6id` worker types now use the full capacity of the available NVMe SSD volumes. Previously, Astro used only the root volume when making scheduling decisions. 
```

2022-11-09 13:26 UTC, kwcanuck commented on astro/release-notes.md
> +Tasks using KubernetesPodOperator can create  mounts to any path, but other tasks must write to `/ephemeral` to use this storage.
```suggestion
Tasks using KubernetesPodOperator can create mounts to any path, but all other tasks must write to `/ephemeral` .  
```

2022-11-09 13:27 UTC, kwcanuck commented on astro/release-notes.md
> +**Note that non-KPO tasks that used local storage on these instances will need to be adjusted to write to `/ephemeral` instead.**
```suggestion
**Non-KPO tasks that use local storage will need to be updated to write to `/ephemeral`.**
```

2022-11-09 13:30 UTC, kwcanuck commented on astro/release-notes.md
> +You can use this storage for simple operations such as a disk-based merge sort or checkpointing to prevent crashes. To use these worker types on your cluster, see [Modify a cluster](modify-cluster.md
```suggestion
You can use temporary storage for simple operations such as a disk-based merge sort or checkpointing. To use these worker types on your cluster, see [Modify a cluster](modify-cluster.md) and [Configure worker queues](configure-worker-queues.md). 
```

2022-11-09 13:30 UTC, kwcanuck approved these changes

2022-11-09 16:10 UTC, jwitz commented on astro/release-notes.md
> +AWS clusters that use `m5d` and `m6id` worker types can now use the full capacity of the NVMe SSD volumes available in these instances. Prior to this release, Astro used the utilization of the root v
@kwcanuck @dnarain-astro Can we condense this change to be a bug fix? The additional docs for how this storage is configured is already set to publish in https://github.com/astronomer/docs/pull/1404/

2022-11-09 16:12 UTC, jwitz requested changes
I think we're giving the wrong impression that this is a feature, when in reality it's a bug fix right? We should:
- Condense the note to something similar that I had in  https://github.com/astronomer/docs/pull/1455
- Rely on https://github.com/astronomer/docs/pull/1404 to explain how to configure the feature. The info about using `/ephemeral` should not live in release notes exclusively.

2022-11-09 16:17 UTC, kwcanuck commented on astro/release-notes.md
> +AWS clusters that use `m5d` and `m6id` worker types can now use the full capacity of the NVMe SSD volumes available in these instances. Prior to this release, Astro used the utilization of the root v
@jwitz makes sense to me.

2022-11-10 11:07 UTC, jwitz commented
Thanks for getting this going @dnarain-astro . Based on your comment in https://github.com/astronomer/docs/pull/1455, I'm going to close this out in favor of https://github.com/astronomer/docs/pull/1404 where I've updated the release note in question.

2022-11-11 18:53 UTC, kwcanuck commented
@jwitz I'm closing this PR. It appears the issue has been documented in the Release Notes and a solution is provided elsewhere in the documentation. Feel free to reopen this if you think additional work is required.

2022-11-11 18:53 UTC, closed without merging