Software 0.31 - Task usage metrics documentation
astronomer/docs pull request #1462
Opened 2022-11-10 16:16 UTC by jwitz

2022-11-10 16:19 UTC, jwitz commented on software/task-usage-metrics.md
> +	  olderThan: 90
```suggestion
  cleanupTaskUsageData:
          olderThan: 90
```

2022-11-14 10:37 UTC, jwitz commented on software/task-usage-metrics.md
> +Task usage metrics provide a high level view of your Airflow task runs and can help you quickly identify Deployments where more tasks a running or failing than expected.
```suggestion
Task usage metrics provide a high level view of your Airflow task runs and can help you quickly identify Deployments where more tasks are running or failing than expected.
```

2022-11-14 10:38 UTC, jwitz commented on software/task-usage-metrics.md
> +  populateHourlyTaskAuditMetrics:
Is there any reason for the user to use the `Daily` configuration if they already use the `Hourly` one?

2022-11-14 10:38 UTC, jwitz commented on software/task-usage-metrics.md
> +          olderThan: 90
Will all organizations want a different number here, or should we recommend 90 in most cases?

2022-11-28 14:06 UTC, kwcanuck commented on software/task-usage-metrics.md
> +To manually send task usage metrics to Astronomer support instead, see [Export task usage metrics manually](#export-task-usage-metrics-manually).
```suggestion
To manually send task usage metrics to Astronomer support, see [Export task usage metrics manually](#export-task-usage-metrics-manually).
```

2022-11-28 14:09 UTC, kwcanuck commented on software/task-usage-metrics.md
> +Task usage metrics are generated by the Astronomer-maintained `airflow-analytics-plugin`. This plugin queries the Airflow metadata database and returns usage analytics at an HTTP endpoint. Deployment
```suggestion
Task usage metrics are generated by the Astronomer-maintained `airflow-analytics-plugin`. This plug-in queries the Airflow metadata database and returns usage analytics at an HTTP endpoint. Deployments using Runtime 6.1 or later have this plug-in installed by default.
```

2022-11-28 19:38 UTC, bote795 commented on software/task-usage-metrics.md
> +If your organization's usage of Astronomer is priced based on successful task runs, you must configure task usage metrics so that you can export figures about your task runs to Astronomer.
@cmarteepants do we keep this paragraph?

2022-11-28 19:39 UTC, bote795 commented on software/task-usage-metrics.md
> +  populateHourlyTaskAuditMetrics:
they dont need to set these up, only if they want to change at what minute it runs and the same thing for the daily

hourly collects hourly and then daily aggregates data from hourly

2022-11-28 19:40 UTC, bote795 commented on software/task-usage-metrics.md
> +          olderThan: 90
90 is the default i believe @rishkarajgi and we should stick with it unless they want to retain more info which means more information in the db

2022-11-28 19:40 UTC, bote795 commented on software/task-usage-metrics.md
> +After you set this configuration, Astronomer Software begins to run a cron job for collecting task usage metrics, sending them to Astronomer Support, and displaying them in the Software UI.
i think we can remove this, as this was removed cc @cmarteepants @rishkarajgi

2022-11-28 19:42 UTC, bote795 commented on software/task-usage-metrics.md
> +To manually send task usage metrics to Astronomer support instead, see [Export task usage metrics manually](#export-task-usage-metrics-manually).
i think we can remove this, as this was removed cc @cmarteepants @rishkarajgi

2022-11-28 19:43 UTC, bote795 commented on software/task-usage-metrics.md
> +    https://github.com/astronomer/airflow-analytics-plugin/releases/download/1.0.0/astronomer_analytics_plugin-1.0.0-py3-none-any.whl
we will have to update the version number when the next release is done of it @rishkarajgi , what is the new number?

2022-11-28 19:55 UTC, bote795 commented on software/task-usage-metrics.md
> +## Export task usage metrics manually
export is a future feature and has been removed.

2022-12-06 16:57 UTC, jwitz commented on software/task-usage-metrics.md
> +          olderThan: 90
```suggestion
```

2022-12-06 16:57 UTC, jwitz commented on software/task-usage-metrics.md
> +2. Click **Export Table**.
```suggestion
```

2022-12-06 17:02 UTC, jwitz commented on software/task-usage-metrics.md
> +After you set this configuration, Astronomer Software begins to run a cron job for collecting task usage metrics, sending them to Astronomer Support, and displaying them in the Software UI.
```suggestion
After you set this configuration, Astronomer Software begins to run a cron job for collecting task usage metrics at the 57th minute of every hour, sending them to Astronomer support, and displaying them in the Software UI every. By default Astronomer installation retains this data for 90 days. 
```

2022-12-06 17:02 UTC, jwitz commented on software/task-usage-metrics.md
> +After you set this configuration, Astronomer Software begins to run a cron job for collecting task usage metrics at the 57th minute of every hour, sending them to Astronomer support, and displaying t
```suggestion
After you set this configuration, Astronomer Software begins to run a cron job for collecting task usage metrics at the 57th minute of every hour, sending them to Astronomer support, and displaying them in the Software UI every. By default, your Astronomer installation retains this data for 90 days. 
```

2022-12-07 19:23 UTC, vishwas-astro commented
We may not want to expose this doc just yet since the feature is not yet ready for primetime and is shipped inside of 0.31.0 in a disabled state only. cc: @cmarteepants

2022-12-08 10:10 UTC, jwitz commented on software/task-usage-metrics.md
> +
```suggestion
```

2022-12-08 10:11 UTC, jwitz commented
@vishwas-astro If you anticipate that customers will still want to configure this in 0.31, we could release the documentation in an unindexed state. The doc would only be accessible from the URL, so the Astronomer team would have to share the doc with qualified/ ready customers in order for them to see it. What do you think?

2022-12-08 17:56 UTC, cmarteepants commented on software/task-usage-metrics.md
> +If your organization's usage of Astronomer is priced based on successful task runs, you must configure task usage metrics so that you can export figures about your task runs to Astronomer.
No, let's remove the line 10. Line 8 is good though

2022-12-08 18:00 UTC, cmarteepants commented
> We may not want to expose this doc just yet since the feature is not yet ready for primetime and is shipped inside of 0.31.0 in a disabled state only. cc: @cmarteepants @bote795 @rishkarajgi

@vishwas-astro Agreed that we should wait until we officially publish the fixed plugin and get a new set of runtime images published with the updated plugin. Hopefully that will happen shortly. 

@jedcunningham had agreed we could publish another round once the plugin was fixed. @bote795 or @rishkarajgi, please confirm when that happens so we can merge this into the docs (assuming ofc the docs are approved)

2022-12-09 06:16 UTC, rishkarajgi commented on software/task-usage-metrics.md
> +    https://github.com/astronomer/airflow-analytics-plugin/releases/download/1.0.0/astronomer_analytics_plugin-1.0.0-py3-none-any.whl
1.0.3 is the current version. 1.0.4 is scheduled next with some changes

2023-02-07 09:07 UTC, rishkarajgi commented
@jwitz The updated analytics changes have been deployed as part of Runtime 7.2.0 [release](https://astronomer.slack.com/archives/C020PVBJPKK/p1674255408971059). This PR can now be merged
cc: @vishwas-astro

2023-02-07 09:09 UTC, rishkarajgi commented on docusaurus.config.js
> +          label: '0.31 (Latest)',
There was a bug fix pushed as part of 0.31.2 release. We might want to update the latest release to 0.31.2

2023-02-07 09:13 UTC, rishkarajgi requested changes
Need to address some comments on the updated versions

2023-02-08 09:17 UTC, jwitz commented
@rishkarajgi There's so many merge conflicts here that I'm going to just close this PR and reopen a PR where we can focus on the specific doc. I will make the remaining changes needed between PRs!

2023-02-08 09:17 UTC, closed without merging