A small tutorial showing how to add documentation to DAGs and tasks
astronomer/docs pull request #1476
Opened 2022-11-14 15:39 UTC by TJaniF

Also trying out tab-use in tutorials :)

2022-11-14 17:53 UTC, kentdanas approved these changes
Looks great! A couple of minor formatting comments and edits, but I'm preemptively approving now.

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +sidebar_label: 'DAG Docs - Add docs in the UI'
```suggestion
sidebar_label: 'Add docs to DAGs'
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +Adding custom doc strings to your Airflow DAGs and tasks that will be shown in the Airflow UI is a lesser known but powerful Airflow feature.
Maybe would be nice to have a screenshot up front here showing what the end result is?

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +To run Airflow locally, you first need to create an Astro project, which contains the set of files necessary.
```suggestion
To run Airflow locally, you first need to create an Astro project.
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +1. In your `dags` folder add a file called `docs_example_dag.py`.
```suggestion
1. In your `dags` folder, add a file called `docs_example_dag.py`. 
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +2. Copy and paste the DAG code provided below, you can use either the TaskFlowAPI version or the version using traditional operators.
```suggestion
2. Copy and paste the DAG code provided below. Choose one of either the TaskFlowAPI or traditional operators DAGs.
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +This DAG has only one task called `tell_me_what_to_do` which queries and [API](https://www.boredapi.com/api/activity) that provides a random activity for the day and prints it into the logs.
```suggestion
This DAG has one task called `tell_me_what_to_do`, which queries an [API](https://www.boredapi.com/api/activity) that provides a random activity for the day and prints it to the logs. 
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +## Step 3: Add documentation to an Airflow DAG
```suggestion
## Step 3: Add docs to your DAG
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +Airflow will let you add documentation to your DAGs in Markdown format and render that documentation in both the **Grid**, **Graph** and **Calendar** view.
```suggestion
In Airflow you can add custom documentation to your DAGs in Markdown format that will render in the **Grid**, **Graph** and **Calendar** views.
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +    This doc string is written in Markdown format. It includes a title, a link to an external website, a bulleted list, as well as an image, which has been formatted using HTML. You can learn more ab
```suggestion
    This doc string is written in Markdown format. It includes a title, a link to an external website, a bulleted list, as well as an image, which has been formatted using HTML. To learn more about Markdown, check out this [Markdown Guide](https://www.markdownguide.org/).
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +3. In the **Grid** view click on the **DAG Docs** banner to view the rendered documentation.
```suggestion
3. Go to the **Grid** view and click on the **DAG Docs** banner to view the rendered documentation.
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +4. (Optional) It is possible to save the documentation in a markdown file and directly provide the filepath to the `doc_md` parameter of the DAG class.
I think this should be another high level step (e.g. ## Step 4) with substeps. And maybe add some context saying this method might be preferable if you have lengthy docs that would clutter your DAG file, or if you were reusing the same docs in multiple DAGs.

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +## Step 4: Add documentation to an Airflow task
```suggestion
## Step 4: Add docs to a task
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +Airflow supports adding documentation to Airflow tasks in Markdown, Monospace, JSON, YAML and reStructured text. Note that only Markdown will be rendered, other formats will be displayed as rich cont
```suggestion
You can also add docs to specific Airflow tasks using Markdown, Monospace, JSON, YAML or reStructured text. Note that only Markdown will be rendered, other formats will be displayed as rich content.
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +<Tabs
We should probably update the TaskFlow DAG to use the `@dag` decorator, and then update Step 3 part 2 to show adding the parameter to both versions (not necessarily with tabs, just two code snippets is probably fine).

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +To add documentation in Markdown format to your task follow these steps:
```suggestion
To add documentation to your task in Markdown format, follow these steps:
```

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +1. Add the code below above the definition of your task:
```suggestion
1. Add the following code above the definition of your task:
```
"below above" was a bit confusing :)

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +2. Provide `doc_md_task` to the `doc_md` parameter of your task definition. If you are using traditional operators simply add it below the `python_callable` parameter.
I would put code snippets for both traditional and TaskFlow, because right now it's not totally clear to me that the sentence `If you are using traditional operators simply add it below the `python_callable` parameter.` isn't referring to the code snippet below.

2022-11-14 17:53 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +4. In the **Grid** view click on the green square.
```suggestion
4. In the **Grid** view, click on the green square for your task instance.
```

2022-11-15 11:31 UTC, TJaniF commented on learn/custom-airflow-ui-docs-tutorial.md
> +</TabItem>
Substep 2 also slightly differs because it uses different parameters but I reformatted it for 3-6 to be the same with tabs for 1-2 and for the screenshot in the end.

2022-11-15 11:32 UTC, TJaniF commented on learn/custom-airflow-ui-docs-tutorial.md
> +4. (Optional) It is possible to save the documentation in a markdown file and directly provide the filepath to the `doc_md` parameter of the DAG class.
Good point! I added that. One caveat here it seems that an external markdown file does not work with the `@dag` decorator. This feels like potentially a bug so I've asked about it in the Airflow channel.

2022-11-15 16:26 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +## Step 4: Add docs to your DAG using doc strings
Maybe this step could just be a note to say that Airflow will also automatically pick up any doc strings that are part of the DAG context and render them as DAG docs? Unless I'm missing something, otherwise this is basically the same thing as Step 3 just without assigning the doc string to a variable? (also to note here that I believe Josh's best practice for registry DAGs is to have the doc string assigned to a variable and at the top of the file).

2022-11-15 16:28 UTC, kentdanas commented on learn/custom-airflow-ui-docs-tutorial.md
> +6. See the Docs under their respective attribute:
I'm guessing "Docs" should not be capitalized? Unless our style guide says it should be...

2022-11-15 16:31 UTC, kwcanuck commented on learn/custom-airflow-ui-docs-tutorial.md
> +6. See the Docs under their respective attribute:
@kentdanas form the _Google developer documentation style guide_ (our selected style guide):

![image](https://user-images.githubusercontent.com/104205257/201974173-4b20a47a-12d2-4388-aa37-d9dc9182624c.png)

2022-11-15 17:28 UTC, jwitz requested changes
This is a great guide that I think will be very popular @TJaniF ! Nice use of tabs overall, requesting changes on the final set of tabs for one main reason: 

Tabs are great when users can comfortably ignore the content of all other tabs except one. This is why we like to use them on Astro for cloud configuration - nobody who's looking at an AWS setup will care about an Azure setup.

For the different document formats, I could see a user being interested in all of them at once, especially to see what a DAG might look like with multiple documentation types at once. For that reason, I think it's better to have a rich example with several types of documented tasks instead of multiple examples with only one type of documented task.

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +2. Copy and paste the DAG code provided below. Choose one of either the TaskFlowAPI or traditional operators DAGs.
```suggestion
2. Copy and paste the one of the following DAGs based on which coding style you're most confortable with.
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +1. In your `dags` folder, add a file called `docs_example_dag.py`.
```suggestion
1. In your `dags` folder, create a file named `docs_example_dag.py`. 
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +In Airflow you can add custom documentation to your DAGs in Markdown format that will render in the **Grid**, **Graph** and **Calendar** views.
```suggestion
You can add Markdown-based documentation to your DAGs that will render in the **Grid**, **Graph** and **Calendar** pages of the Airflow UI.
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +    This doc string is written in Markdown format. It includes a title, a link to an external website, a bulleted list, as well as an image, which has been formatted using HTML. To learn more about M
```suggestion
    This doc string is written in Markdown. It includes a title, a link to an external website, a bulleted list, as well as an image which has been formatted using HTML. To learn more about Markdown, see [The Markdown Guide](https://www.markdownguide.org/).
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +When using the `with DAG():` syntax it is possible to pass the filepath to a markdown file to the `doc_md` parameter. This can be useful if you want to add the same documentation to several of your D
```suggestion
Using `with DAG():` lets you pass the filepath of a markdown file to the `doc_md` parameter. This can be useful if you want to add the same documentation to several of your DAGs.
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +:::info
```suggestion
:::tip
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +You can also add docs to specific Airflow tasks using Markdown, Monospace, JSON, YAML or reStructured text. Note that only Markdown will be rendered, other formats will be displayed as rich content.
```suggestion
You can also add docs to specific Airflow tasks using Markdown, Monospace, JSON, YAML or reStructured text. Note that only Markdown will be rendered and other formats will be displayed as rich content.
```

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +You can also add docs to specific Airflow tasks using Markdown, Monospace, JSON, YAML or reStructured text. Note that only Markdown will be rendered, other formats will be displayed as rich content.
Can you also use these other formats at the DAG level?

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +        {label: 'Markdown', value: 'markdown'},
I don't think this is the best use of tabs, as it's possible someone would want to add both JSON documentation and rst documentation to the same DAG. Could we instead create a few tasks that use these different formats and show them all at once together?

2022-11-15 17:28 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +            "go to the gym": ["frequency": 2, "rating": 8],
This is cool! Is there a good use case for why you'd want to add JSON blocks to a task doc? For example output?

2022-11-17 08:59 UTC, TJaniF commented on learn/custom-airflow-ui-docs-tutorial.md
> +6. See the Docs under their respective attribute:
Good catch!

2022-11-17 09:20 UTC, TJaniF commented on learn/custom-airflow-ui-docs-tutorial.md
> +## Step 4: Add docs to your DAG using doc strings
Yeah that makes sense :)

2022-11-17 10:11 UTC, TJaniF reviewed
Turned step 4 into a note and consolidated the task docs into one rich example :)

2022-11-17 14:04 UTC, jwitz approved these changes
A few more wording suggestions but after that looks good! Super clean easy tutorial

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +description: 'Use tutorials and guides to make the most out of Airflow and Astronomer.'
```suggestion
description: 'Use Apache Airflow's built-in documentation features to generate documentation for your DAGs in the Airflow UI.'
```

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +        {label: 'Traditional Operator', value: 'traditional'},
```suggestion
        {label: 'Traditional operators', value: 'traditional'},
```

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +        {label: 'Traditional DAG context', value: 'traditional'},
```suggestion
        {label: 'Traditional operators', value: 'traditional'},
```

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +        {label: 'DAG decorator', value: 'TaskFlowAPI'},
```suggestion
        {label: 'TaskFlow API', value: 'TaskFlowAPI'},
```

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +        {label: 'TaskFlowAPI', value: 'TaskFlowAPI'},
```suggestion
        {label: 'TaskFlow API', value: 'TaskFlowAPI'},
```

2022-11-17 14:04 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +2. Copy and paste one of the following DAGs based on which coding style you're most confortable with.
```suggestion
2. Copy and paste one of the following DAGs based on which coding style you're most comfortable with.
```

2022-11-17 14:05 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +    doc=doc_task,
```suggestion
    doc=doc_monospace_task,
```

2022-11-17 14:05 UTC, jwitz commented on learn/custom-airflow-ui-docs-tutorial.md
> +    doc=doc_task,
```suggestion
    doc=doc_monospace_task,
```

2022-11-17 23:10 UTC, TJaniF commented on learn/custom-airflow-ui-docs-tutorial.md
> +description: 'Use tutorials and guides to make the most out of Airflow and Astronomer.'
For some reason this change causes the build to fail 👀 I reverted it for now.

2022-11-18 14:30 UTC, merged