Add Information About the include Folder to Develop Your Astro Project
astronomer/docs pull request #1504
Opened 2022-11-16 15:18 UTC by kwcanuck

Resolves #1496

2022-11-16 21:51 UTC, jlaneve requested changes
Can we add a snippet saying that DAG deploys have to be explicitly enabled before running `astro deploy --dags`? Can link to https://docs.astronomer.io/astro/deploy-code#enable-dag-only-deploys

2022-11-17 16:24 UTC, jlaneve approved these changes

2022-11-18 12:35 UTC, jwitz approved these changes
A few comments here @kwcanuck . Tried reorganizing the topic to make `include` the primary feature and DAG deploys as an implementation detail .

2022-11-18 12:35 UTC, jwitz commented on astro/develop-project.md
> +### Deploy only DAGs
```suggestion
## Add utility files for DAGs
```
The purpose of the parent topic is more to discuss whether the user needs to restart their project to deploy any local changes. I think this should be its own H2 topic closer to where we discuss other folders, like near "Add Python and OS-level packages"

2022-11-18 12:35 UTC, jwitz commented on astro/develop-project.md
> +With Astro CLI 1.7 and later, you can run `astro deploy -—dags` to push only the `dags` directory of your Astro project to a Deployment on Astro. This is an additional option to `astro deploy` that m
```suggestion
Use the `include` folder to store any additional utilities your DAGs need, such as helper functions, templated SQL scripts, and custom operators.
```

2022-11-18 12:35 UTC, jwitz commented on astro/develop-project.md
> +To use `astro deploy -—dags`, you need to enable it. See [Enable DAG-only deploys](deploy-code.md#enable-dag-only-deploys).
```suggestion

:::tip

When you use the `astro deploy -—dags` command, the `include` folder in the Astro project directory is not deployed with your DAGs and is instead build into the Docker image with your other project files.

If you are deploying only DAGs, Astronomer recommends moving the `include` folder into the `dags` directory so that your DAGs can quickly access your utility files. See [Deploy DAGs only](deploy-code.md#deploy-dags-only).

:::
```

Tried to make the benefit of moving the `include` folder more clear here, and also don't think we need to discuss enabling the DAG deploy feature in this topic. It seems better to guide users to the topic in general and give them the option to read the enabling topic if they want to proceed with DAG deploys.

2022-11-18 12:35 UTC, jwitz commented on astro/develop-project.md
> +With Astro CLI 1.7 and later, you can run `astro deploy -—dags` to push only the `dags` directory of your Astro project to a Deployment on Astro. This is an additional option to `astro deploy` that m
This topic seems a bit duplicative to our existing DAG deploy documentation. I tried making it primarily about the `include` folder, with a note about how this works with DAG deploys.

2022-11-18 12:40 UTC, kwcanuck commented on astro/develop-project.md
> +## Add utility files for DAGs
```suggestion
## Add DAG utility files
```

2022-11-18 12:42 UTC, kwcanuck commented on astro/develop-project.md
> +When you use the `astro deploy -—dags` command, the `include` folder in the Astro project directory is not deployed with your DAGs and is instead build into the Docker image with your other project f
```suggestion
When you use the `astro deploy -—dags` command, the `include` folder in the Astro project directory is not deployed with your DAGs and is instead built into the Docker image with your other project files.
```

2022-11-18 12:43 UTC, kwcanuck commented on astro/develop-project.md
> +If you are deploying only DAGs, Astronomer recommends moving the `include` folder into the `dags` directory so that your DAGs can quickly access your utility files. See [Deploy DAGs only](deploy-code
```suggestion
If you are deploying only DAGs, Astronomer recommends moving the `include` folder into the `dags` directory so that your DAGs can access your utility files. See [Deploy DAGs only](deploy-code.md#deploy-dags-only).
```

2022-11-18 13:30 UTC, merged