Update Sagemaker Guide
astronomer/docs pull request #1534
Opened 2022-11-21 21:05 UTC by fritz-astronomer

- a few minor consistency / comment changes
- swap to f-strings
- make `aws_conn_id` explicit
- add/modify some docstrings
- (primary change) move to `image_uris.retrieve(framework='knn',region=region)` as image referenced was broken

2022-11-21 23:32 UTC, kentdanas requested changes
@fritz-astronomer thanks for the comments. I have a few questions about some of the changes to the tutorial. I'll leave the Astro docs to @jwitz and @kwcanuck for review.

2022-11-21 23:32 UTC, kentdanas commented on learn/airflow-sagemaker.md
> +If you are uncertain which method you use to connect to AWS, contact your AWS Administrator. These steps may not fit your desired authentication mechanism
```suggestion
If you are uncertain which method you use to connect to AWS, contact your AWS Administrator. These steps may not fit your desired authentication mechanism.
```

2022-11-21 23:32 UTC, kentdanas commented on learn/airflow-sagemaker.md
> +    Your `.env` file only applies to your local Airflow. To set variables in your Astronomer Airflow instances, [follow this guide](https://docs.astronomer.io/astro/environment-variables).
This tutorial is explicitly written for users running locally with the CLI (hence step 2 on setting up a local Airflow project). If this is causing confusion for Astro customers we can add it as a separate note, but I don't want to put it directly in the step.

2022-11-21 23:32 UTC, kentdanas commented on learn/airflow-sagemaker.md
> +Your credentials should only last up to a day - you will need to edit the details in the connection with new credentials, if you want to run this again another day
```suggestion
Your AWS credentials will only last one day using this authentication method. If you return to this step after your credentials have expired, you will need to edit the details in the connection with updates credentials.
```

2022-11-21 23:32 UTC, kentdanas commented on learn/airflow-sagemaker.md
> +Add an Airflow variable that will be used by your DAG. In the Airflow UI, go to **Admin** -> **Variables**.
I think @fhoda specifically updated this DAG to store the S3 bucket as an env var. Is there a specific reason you're adding it in the DAG code instead?

2022-11-21 23:32 UTC, kentdanas commented on learn/airflow-sagemaker.md
> -             'aws_conn_id': 'aws-sagemaker'
I'm confused why we would remove this from the default when it's used by every task?

2022-11-28 20:30 UTC, fhoda commented on learn/airflow-sagemaker.md
> +Add an Airflow variable that will be used by your DAG. In the Airflow UI, go to **Admin** -> **Variables**.
For some context, I did this so that users know what exactly they need to change by just adding the vars rather than having to go through the code to figure out what they need to change to get it working in their environments. It may be good to call out that in production it may be considered best practice to hard code the s3 bucket and similar things so that they can be version controlled.

2022-11-28 20:38 UTC, fritz-astronomer commented on learn/airflow-sagemaker.md
> +    Your `.env` file only applies to your local Airflow. To set variables in your Astronomer Airflow instances, [follow this guide](https://docs.astronomer.io/astro/environment-variables).
```suggestion
```

2022-11-28 20:40 UTC, fritz-astronomer commented on learn/airflow-sagemaker.md
> +Add an Airflow variable that will be used by your DAG. In the Airflow UI, go to **Admin** -> **Variables**.
That makes sense. I partially changed it because I didn't want to deal with f-strings and jinja templating :)

2022-11-28 20:40 UTC, fritz-astronomer commented on learn/airflow-sagemaker.md
> +Add an Airflow variable that will be used by your DAG. In the Airflow UI, go to **Admin** -> **Variables**.
Would that be a good trend in general - things users definitely need to change in these tutorials should be airflow variables?

2022-11-28 20:42 UTC, fritz-astronomer commented on learn/airflow-sagemaker.md
> -             'aws_conn_id': 'aws-sagemaker'
I think it's a better practice to be explicit - especially with something like `aws_conn_id`. I think new-to-airflow users may copy-paste one of the operators out into their own DAG and wouldn't think to look in `default_args` - so I always try to make it obvious and to get people in the habit of being explicit with their `*_conn_id`'s in operators as it can be a source of confusion

2023-01-17 12:36 UTC, kwcanuck commented on astro/ci-cd.md
> +If you use hosted runners, you might need certain tags or modifications based on your Gitlab runner. Speak with your Gitlab administrator and review the [Gitlab Documentation](https://docs.gitlab.com
```suggestion
If you use hosted runners, you might need to ask your Gitlab administrator to modify your Gitlab runner tags. To learn more about customizing a template, see [Use Docker to build Docker images](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html).
```

2023-01-17 12:36 UTC, kwcanuck approved these changes

2023-01-18 19:52 UTC, kentdanas approved these changes

2023-01-18 19:55 UTC, merged