Add Process for Connecting Amazon Route 53 and Astro
astronomer/docs pull request #1548
Opened 2022-11-24 19:50 UTC by kwcanuck

Resolves #1527

2022-12-05 17:05 UTC, afastronomer approved these changes

2022-12-05 17:07 UTC, stuart23 requested changes
The jargon here is a bit strange. Why would the customer share an internet resolver rule - it should be the same as what we have already in Astro.

I think the use case here is if the customer wants to share a custom resolver rule, in which case we need to drop the "Internet" out of  "Amazon Route 53 Internet Resolver rule"

2022-12-05 18:40 UTC, stuart23 commented
Happy to unblock this as it is a viable method to create one DNS rule, however I think the inbound/outbound endpoints are the preferred method as the customer can then add as many rules as they would like. I have opened this issue: https://github.com/astronomer/docs/issues/1590

2022-12-05 18:42 UTC, stuart23 requested changes

2022-12-05 18:42 UTC, stuart23 commented on astro/connect-aws.md
> +- The Astro AWS External ID for your organization. In the Cloud UI, click **Settings** and then copy the value in the **AWS External ID** field.
```suggestion
```

We have this available already - we do not need the customer to provide it back to us.

2022-12-05 19:04 UTC, kwcanuck commented on astro/connect-aws.md
> +3. Click **Share**, enter `Astro` in the **Name** field, and then enter the remaining resource share details including the Astro AWS account ID. To get the Astro AWS account ID, go to the Cloud UI, c
@stuart23 as discussed, it is not necesary to capitalize rule when using it with Resolver:

![image](https://user-images.githubusercontent.com/104205257/205721359-56e73c7a-3814-464d-a4a8-97d7186a2329.png)

We don't use _Astro Cloud UI_. We use _Cloud UI_.

I have rewritten the procedure.

2022-12-05 19:16 UTC, stuart23 requested changes

2022-12-05 19:16 UTC, stuart23 commented on astro/connect-aws.md
> +6. On the **Grant access to principals** page, select **Allow sharing only within your organization**, and then enter your Astro AWS account ID for your organization in the **Enter an AWS account ID*
```suggestion
6. On the **Grant access to principals** page, select **Allow sharing only within your organization**, and then enter your Astro AWS account ID for your organization in the **Enter an AWS account ID** field. To get the Astro AWS account ID, go to the Cloud UI, click **Settings**, and then copy the value in the **ID** column for the Astro AWS account you want to share the Resolver rule with.
```

2022-12-05 19:20 UTC, kwcanuck commented
@jwitz could you take another look at this PR? Thanks!

2022-12-06 11:32 UTC, jwitz requested changes
Setup steps look good! Requesting changes to get some clarity on what happens after Astronomer sets up the resolver rule on their backend.

I also want to make sure we have a clear end goal for this setup. I don't think that goal is "to access a private hosted zone" as stated here. This seems like another way to connect Astro to a resource, but in a way that passes through route 53 resolver.

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +Use Amazon Route 53 to allow Astro to access a private hosted zone.
```suggestion
Use Amazon Route 53 to allow Astro to access a VPC through a [private hosted zone](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html).
```
Feel free to reword this, but based on the AWS docs it seems like private hosted zones are more of an implementation detail rather than the end goal of the setup.

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +#### Step 1: Share the Amazon Route 53 Resolver rule
Remove step #s?

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +4. In the **Resources - optional** section, select **Resolver Rules**  in the **Select resource type** list and then select a rule.
```suggestion
4. In the **Resources - optional** section, select **Resolver Rules** in the **Select resource type** list and then select a rule.
```

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +1. In the Route 53 Dashboard,  click **Rules** below **Resolver** in the navigation menu.
```suggestion
1. In the Route 53 Dashboard, click **Rules** below **Resolver** in the navigation menu.
```

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
```suggestion
- An Amazon Route 53 forwarding rule to your VPC. See [Managing forwarding rules](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-rules-managing.html).
```
When I follow the AWS instructions for "Forwarding rules", I get to the same place as what's described here to be "Resolver rule". If these are the same thing, I'd opt to be consistent with how AWS refers to the rule.

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +2. Select a Resolver rule and then click **Details**.
```suggestion
2. Select the forwarding rule and then click **Details**.
```

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +4. In the **Resources - optional** section, select **Resolver Rules**  in the **Select resource type** list and then select a rule.
Is this rule the same one as in Step 2?

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +When Astronomer support confirms that the Amazon Route 53 Resolver rule was successfully associated with the Astro VPC, confirm Astro can resolve hostnames from the private hosted zone.
```suggestion
When Astronomer support confirms that the Amazon Route 53 forwarding rule was successfully associated with the Astro VPC, confirm Astro can resolve hostnames from the private hosted zone.
```

2022-12-06 11:32 UTC, jwitz commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
AFAIK there is no Route 53 connection type in Airflow. What happens is you need to configure a default [AWS connection](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html) to the VPC/ resource connected to the forwarding rule, and Route 53 handles that connection on the backend. Is this right @stuart23 ?

If so, we should instruct users to create the Airflow connection to their resource, and possibly provide guidance on how that connection should look.

2022-12-06 13:59 UTC, kwcanuck commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
@jwitz Resolver rule is correct:

![image](https://user-images.githubusercontent.com/104205257/205931901-de3d6a9a-3f12-4007-a170-b30290a40044.png)

2022-12-06 14:01 UTC, kwcanuck commented on astro/connect-aws.md
> +#### Step 1: Share the Amazon Route 53 Resolver rule
@jwitz good catch. Done.

2022-12-06 14:02 UTC, kwcanuck commented on astro/connect-aws.md
> +2. Select a Resolver rule and then click **Details**.
@jwitz as mentioned previously, this edit is incorrect.

2022-12-06 14:02 UTC, jwitz commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
Is this not referencing the same thing? https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-rules-managing.html

2022-12-06 14:03 UTC, jwitz commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
Resolver > Rule is a menu path, not the distinction for the rule itself. That appears to be "Forwarding rule"

2022-12-06 14:04 UTC, kwcanuck commented on astro/connect-aws.md
> +4. In the **Resources - optional** section, select **Resolver Rules**  in the **Select resource type** list and then select a rule.
@jwitz it's an existing Resolver rule. See the prerequisites section. It can be _any_ Resolver rule that a user wants to share.

2022-12-06 14:05 UTC, kwcanuck commented on astro/connect-aws.md
> +When Astronomer support confirms that the Amazon Route 53 Resolver rule was successfully associated with the Astro VPC, confirm Astro can resolve hostnames from the private hosted zone.
@jwitz as discussed previously, this edit is incorrect.

2022-12-06 14:10 UTC, kwcanuck commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
@jwitz Resolver rules is the correct naming convention. See:

![image](https://user-images.githubusercontent.com/104205257/205934079-959619c1-3332-4f9f-9d94-d8617d60c464.png)

![image](https://user-images.githubusercontent.com/104205257/205934405-c33c11f9-13d4-4c10-a0dd-2b796444a855.png)

2022-12-06 14:16 UTC, kwcanuck commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
@jwitz this was discussed. Here is the thread:

![image](https://user-images.githubusercontent.com/104205257/205935202-60c41263-3d6b-4802-84db-37e8ad987e37.png)

![image](https://user-images.githubusercontent.com/104205257/205935261-6d560709-fbbd-4ded-9962-fc9992f860bd.png)

My understanding (perhaps incorrect) was that the connection would appear in Airflow after Astronomer Support completed the configuration. @stuart23 and @afastronomer reviewed and approved the existing content. I'll wait for Stu's response.

2022-12-06 14:26 UTC, jwitz commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
"When customer adds connection" to me means that the user has to create the AWS connection first and test it before they can see that the connection is successful, which in other words is seeing the name resolving in action. I don't think Astronomer is going into people's Airflow UIs and configuring connections for them.

2022-12-06 14:32 UTC, kwcanuck commented on astro/connect-aws.md
> +- An Amazon Route 53 Resolver rule
@jwitz the link has been added.

2022-12-06 15:07 UTC, jwitz commented on astro/connect-aws.md
> +3. Enter the connection ID of the Resolver rule you shared in the **Connection Id** field.
Connection ID is not related to this setup. A [Connection ID](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#storing-connections-in-environment-variables) is simply the name you give to the connection so you can call it in your Airflow DAG.

To use the Route 53 setup with an AWS connection, I think you would need to specify [`endpoint_url`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#configuring-the-connection) with the domain you configured in the forwarding rule. But it might just be sufficient to tell users to create a new AWS connection to test it as they see fit.

2022-12-06 15:08 UTC, jwitz commented on astro/connect-aws.md
> +3. Enter the connection ID of the Resolver rule you shared in the **Connection Id** field.
cc @afastronomer , which fields must the user configure in the AWS connection to use the Route 53 setup? Is it just `endpoint_url` or are their keyword arguments you must also add?

2022-12-06 15:21 UTC, jwitz commented on astro/connect-aws.md
> +3. Enter a name for the connection in the **Connection Id** field. The naming convention is `AIRFLOW_CONN_{CONN_ID}`, all uppercase with single underscores surrounding `CONN`. For example, `AIRFLOW_C
```suggestion
3. Enter a name for the connection in the **Connection Id** field, such as `aws_default`.
```
Per the Airflow docs, this is the naming convention for storing connections in environment variables, not in the UI itself. See https://docs.astronomer.io/learn/connections#airflow-connection-basics and https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#json-format-example

2022-12-06 15:26 UTC, jwitz commented
LGTM once we figure out how exactly to specify the VPC within the AWS connection.

2022-12-07 20:02 UTC, dnarain-astro commented on astro/connect-aws.md
> +        {label: 'Amazon Route 53', value: 'Amazon Route 53'},
IMO Route53 will help you LOCATE the service, but it isn't a connectivity option (i.e. you can't send bits over Route53).  It should be a sub-action of VPC peering and Transit Gateways - not sure how to present that info, but IMO putting it here is confusing.  Maybe we need a third section in this page instead? i.e. - Connection Options, DNS Recommendations, Authorization

2022-12-07 21:20 UTC, dnarain-astro commented on astro/connect-aws.md
> +
Incomplete sentence FYI.  What i would recommend here is "Use Route53 Resolver rules to allow Astro to resolve DNS queries for resources running in other VPCs or on-premises"

2022-12-08 13:48 UTC, kwcanuck commented on astro/connect-aws.md
> +
@dnarain-astro thanks for the recommendation. I have updated the introductory statement.

2022-12-08 13:49 UTC, kwcanuck commented on astro/connect-aws.md
> +        {label: 'Amazon Route 53', value: 'Amazon Route 53'},
@dnarain-astro you make a valid point, but I'm not sure how best to organize the information. I need to think about it. Thanks for the feedback.

2022-12-08 15:20 UTC, stuart23 commented on astro/connect-aws.md
> +        {label: 'Amazon Route 53', value: 'Amazon Route 53'},
Agreed - there is also more than 1 way to skin this feral cat too! We should (eventually doc Route53 Endpoints too) https://github.com/astronomer/docs/issues/1590

2022-12-08 15:26 UTC, stuart23 commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
As I understand, the connection can be anything that points towards a resource that is resolved by the shared rule. I don't know if we need to document exactly how to do this, as the type of connection (db, endpoint, ?) could really be anything.

2022-12-08 15:31 UTC, stuart23 commented on astro/connect-aws.md
> +4. In the **Resources - optional** section, select **Resolver Rules**  in the **Select resource type** list and then select a rule.
```suggestion
4. In the **Resources - optional** section, select **Resolver Rules**  in the **Select resource type** list and then select one or more rules.
```

Want to. make it clear that multiple rules can be shared at once

2022-12-08 15:36 UTC, stuart23 commented on astro/connect-aws.md
> +        {label: 'Amazon Route 53', value: 'Amazon Route 53'},
Right now, this page has the sections `Connection options` and `Authorization options`. Should `Resolving resources` be a separate section?

2022-12-08 15:40 UTC, stuart23 commented on astro/connect-aws.md
> +#### Create the connection and confirm connectivity
```suggestion
#### Create a connection to confirm connectivity (optional)
```

This is optional and just used to confirm that the domain name is being resolved correctly.

2022-12-08 15:41 UTC, stuart23 approved these changes
A couple of suggestions, but I am happy for you to go ahead and merge it either way. Thanks @kwcanuck!

2022-12-08 15:42 UTC, kwcanuck commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
@stuart23 thanks for the feedback. Would it be sufficient to say: In Airflow, create a connection to a resource that is resolved by the shared rule. See [Managing Connections](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html).

My preference is always to provide explicit instructions, but it appears that this isn't possible here.

2022-12-08 16:02 UTC, kwcanuck commented on astro/connect-aws.md
> +        {label: 'Amazon Route 53', value: 'Amazon Route 53'},
@stuart23 and @dnarain-astro I have added Resolving resources section and moved the Route 53 content. Take a look and let me know if this is a better solution.

2022-12-08 17:48 UTC, stuart23 commented on astro/connect-aws.md
> +2. Select the Amazon Route 53 connection and click **Edit record**.
Sounds good to me Rob. You can then tell them to test the connection using the connection testing feature (although I have had very limited success with this feature :-/)

2022-12-08 18:10 UTC, stuart23 approved these changes

2022-12-09 14:32 UTC, jwitz commented on astro/connect-aws.md
> +Securely connect your Astro data plane to resources running in other VPCs or on-premises.
```suggestion
Securely connect your Astro data plane to resources running in other VPCs or on-premises through a resolving service.
```
This sentence would otherwise also apply to the original VPC peering setup.

2022-12-09 14:33 UTC, jwitz approved these changes
LGTM 🚢

2022-12-09 15:17 UTC, merged