Update user-permissions.md
astronomer/docs pull request #1551
Opened 2022-11-28 14:16 UTC by shivannakarthik

- Could not find any document stating about deployment roles. Added a line to the doc stating them.
- Adding caution message on the workspace and deployment role. This makes it clear that a workspace admin role has super user privilege and can override deployment level permissions.

2022-11-28 14:41 UTC, kwcanuck commented on astro/user-permissions.md
> +1. If a user changes Workspace roles, it can take a maximum of 10 minutes for corresponding Airflow permission changes to take effect.
```suggestion
When a user changes Workspace roles, it can take up to 10 minutes for the corresponding Airflow permissions to be updated.
```

2022-11-28 14:45 UTC, kwcanuck commented on astro/user-permissions.md
> +2. There are three roles with respect to deployments - Deployment Admin, Deployment Editor and Deployment Viewer. This gives flexibilty to manage deployment level permissions along with Workspace lev
```suggestion
There are three Deployment roles: Deployment Admin, Deployment Editor, and Deployment Viewer. These different roles let you manage Deployment and Workspace permissions individually. For example, a user can have Workspace view access and Deployment Admin permissions on a Deployment.
```

2022-11-28 14:47 UTC, kwcanuck commented on astro/user-permissions.md
> +If a user has Workspace admin role, irrespective of the Deployment role, they can perofrm admin level actions on the Airflow deployment.
```suggestion
When a user is a Workspace admin, they assume Deployment Admin permissions on the Airflow deployment.
```

2022-11-28 14:47 UTC, kwcanuck approved these changes

2022-11-29 11:05 UTC, jwitz requested changes
@shivannakarthik thank you for the contribution! As far as I know, there are no Deployment-level permissions on Astro. Workspace permissions extend to all Deployments within the Workspace, and you can't assign individual Deployment permissions. 

Astronomer Software does support Deployment roles, and they are documented here: https://docs.astronomer.io/software/role-permission-reference#deployment-viewer

2022-11-30 11:23 UTC, shivannakarthik commented
Correcting some typos. I believe this page should be consolidated with https://docs.astronomer.io/astro/user-permissions. Please advice.

2022-11-30 11:58 UTC, shivannakarthik commented
Hi @jwitz Thank you for reviewing.
Correcting some typos in the page you referred to. I believe the page you referenced should be consolidated with https://docs.astronomer.io/astro/user-permissions for better visibiltiy as it is not specific to release 0.30. Please advice.

2022-11-30 11:58 UTC, jwitz commented
@shivannakarthik The page you linked is a separate product from https://docs.astronomer.io/software/role-permission-reference#deployment-viewer, and these products have different roles and permissions. I admit it's confusing especially because we don't broadcast our Astronomer Software offering too much. The current change in the PR is incorrect for the Astro product offering, so I would revert your changes in `astro/user-permissions.md` and keep your changes in `software/role-permission-reference.md`. After that we can merge.

2022-12-01 11:26 UTC, shivannakarthik reviewed
@jwitz Requesting to review.

2022-12-01 16:05 UTC, jwitz approved these changes

2022-12-01 16:05 UTC, merged

2022-12-01 16:05 UTC, jwitz commented
Merged 🥳 Thank you @shivannakarthik