Update OpenLineage / Great Expectations integration
astronomer/docs pull request #1588
Opened 2022-12-05 16:04 UTC by jwitz

Part of https://github.com/astronomer/docs/issues/1575

2022-12-05 16:13 UTC, kwcanuck commented on astro/set-up-data-lineage.md
> +2. Lineage support for GreatExpectations requires the use of the `ActionListValidationOperator`. In each of your checkpoint's YAML files in `checkpoints/`, set the `validation_operator_name` configur
```suggestion
2. Lineage support for GreatExpectations requires the use of the `ActionListValidationOperator`. In each of your checkpoint's YAML files in `checkpoints/`, set the `validation_operator_name` configuration to `action_list_operator` as shown in the following snippet:
```

2022-12-05 16:14 UTC, kwcanuck approved these changes

2022-12-05 17:39 UTC, jwitz commented on astro/set-up-data-lineage.md
> +If you use the `GreatExpectationsOperator` version 0.2.0 or later and don't use a custom Checkpoint or Checkpoint Config, the operator detects your Astro OpenLineage configuration from the `include`
@denimalpaca I'm having trouble getting my DAG to recognize `base_path`. I tried setting up my DAG similar to [here](https://github.com/astronomer/airflow-data-quality-demo/blob/main/dags/great_expectations/great_expectations_bigquery.py), but the parser isn't finding `usr/local/include/great_expectations/great_expectations.yml` even after adding all of the required imports.

2022-12-05 20:34 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +If you use the `GreatExpectationsOperator` version 0.2.0 or later and don't use a custom Checkpoint or Checkpoint Config, the operator detects your Astro OpenLineage configuration from the `include`
Make sure you have the leading slash in `/usr/local/include/great_expectations/great_expectations.yml`, otherwise it's looking for `usr` in your local directory.

2022-12-06 10:57 UTC, jwitz commented on astro/set-up-data-lineage.md
> +If you use the `GreatExpectationsOperator` version 0.2.0 or later and don't use a custom Checkpoint or Checkpoint Config, the operator detects your Astro OpenLineage configuration from the `include`
Sorry missed that slash in my comment but it exists in the error message. Here's the entire error message:

```

rel_path = 'dags/example_dag_basic.py'
rv = 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/da...\n    - If you have never run Great Expectations in this project, please run `great_expectations init` to get started.'

    @pytest.mark.parametrize("rel_path,rv", get_import_errors(), ids=[x[0] for x in get_import_errors()])
    def test_file_imports(rel_path,rv):
    	""" Test for import errors on a file """
    	if rel_path and rv : #Make sure our no op test doesn't raise an error
>   		raise Exception(f"{rel_path} failed to import with message \n {rv}")
E     Exception: dags/example_dag_basic.py failed to import with message 
E      Traceback (most recent call last):
E       File "/usr/local/lib/python3.9/site-packages/great_expectations/data_context/data_context/data_context.py", line 409, in _load_project_config
E         with open(path_to_yml) as data:
E     FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/include/great_expectations/great_expectations.yml'
E     
```

This is after specifying a base path in the DAG. Feel free to take this convo on to Slack if the answer is tricky

2022-12-06 15:20 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +If you use the `GreatExpectationsOperator` version 0.2.0 or later and don't use a custom Checkpoint or Checkpoint Config, the operator detects your Astro OpenLineage configuration from the `include`
`E     FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/include/great_expectations/great_expectations.yml'`

path should be `/usr/local/airflow/include/great_expectations/great_expectations.yml`. Could be a problem if the DAG got moved up a level in the hierarchy, it should be under `dags/great_expectations/ge_dag.py`

Also I think the content in this section is wrong, I'm not sure what

> the operator detects your Astro OpenLineage configuration from the `include` folder automatically as long as you set

is supposed to imply. The operator only detects an OpenLineage environment, irrespective of Astro, if you are using the operator without supplying a checkpoint, when it builds its default action list. It has nothing to do with the data context.

2022-12-07 17:29 UTC, denimalpaca requested changes

2022-12-07 17:29 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +    # Set directory fot the Data Context
nit: fot --> for

2022-12-07 17:29 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +1. Make your Data Context accessible to your DAGs. For most use cases, Astronomer recommends adding the Data Context to your Astro project `include` folder, then adding the following lines to a given
I'd reword this to "recommends adding your Great Expectations project to your Astro project `include` folder. The GreatExpectationsOperator will access `include/great_expectations/great_expectations.yml` and use the configuration to run your Expectations. Then add the following lines to a given DAG:"

2022-12-07 17:29 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +2. Update your `great_expectations.yml` file to add `OpenLineageValidationAction` to your `action_list_operator` configuration:
None of lines 197-211 are accurate; the checkpoint file is what needs to be updated and an `OpenLineageValidationAction` added to the `action_list`, like so:

```yml
name: my.simple.chk
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
  - name: open_lineage
    action:
      class_name: OpenLineageValidationAction,
      module_name: openlineage.common.provider.great_expectations,
      openlineage_host: https://<your-astro-base-domain>,
      openlineage_apiKey: <openlineage_api_key>,
      openlineage_namespace: <NAMESPACE_NAME> # Replace with your job namespace; Astronomer recommends using a meaningful namespace such as `dev` or `prod`,
      job_name: validate_task_name,
```

2022-12-07 17:29 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +              openlineage_host: https://astro-<your-base-domain>.datakin.com
I'm pretty sure this is still just `https://<your-astro-base-domain>`, we're not doing the redirects to Datakin anymore. @rossturk can confirm

2022-12-07 17:29 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +3. In each of your Checkpoint's YAML files in `checkpoints/`, set the `validation_operator_name` configuration to `action_list_operator` like in the following snippet:
This step can be removed, it is incorrect and not needed. The _only_ configuration for lineage data emission is adding the action to the action list in the checkpoint.

2022-12-08 11:17 UTC, jwitz commented on astro/set-up-data-lineage.md
> +   The GreatExpectationsOperator will access `include/great_expectations/great_expectations.yml` and use the configuration to run your Expectations.
```suggestion
```

2022-12-08 11:17 UTC, jwitz commented on astro/set-up-data-lineage.md
> +    # Set directory fot the Data Context
```suggestion
    # Set directory for the Data Context
```

2022-12-08 11:17 UTC, jwitz commented on astro/set-up-data-lineage.md
> +1. Make your Data Context accessible to your DAGs. For most use cases, Astronomer recommends adding the Data Context to your Astro project `include` folder, then adding the following lines to a given
```suggestion
1. Make your Data Context accessible to your DAGs. For most use cases, Astronomer recommends adding the Data Context to your Astro project `include` folder. The GreatExpectationsOperator will access `include/great_expectations/great_expectations.yml` and use the configuration to run your Expectations. Then, add the following lines to your DAGs: 
```

2022-12-08 18:59 UTC, denimalpaca requested changes
Getting closer ;)

2022-12-08 18:59 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +   )
These are *not* required imports. `BatchRequest` probably should not be imported in most cases, and `DataContextConfig` and `CheckpointConfig` are both the in-memory versions of the Data Context and Checkpoint, and neither are used here.

2022-12-08 18:59 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +   )
I don't like showing the operator like this because the DAG wouldn't even import. Maybe we can add some ellipsis to imply other parameters are required?

```
ge_task = GreatExpectationsOperator(
    task_id="ge_task",
    # Set directory for the Data Context
    ge_root_dir=os.path.join(base_path, "include", "great_expectations"),
    ...
   )
```

2022-12-08 18:59 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +   If you use the `GreatExpectationsOperator` version 0.2.0 or later and don't use a custom Checkpoint or Checkpoint Config, you can skip steps 2 and 3.
I think "custom Checkpoint" should be reworded to "Checkpoint file" as "custom" implies that a "regular" Checkpoint being used means to also skip steps 2 and 3.

2022-12-08 18:59 UTC, denimalpaca commented on astro/set-up-data-lineage.md
> +          openlineage_host: https://astro-<your-astro-base-domain>.datakin.com,
I would like to verify this line with someone from the OL team. @conorbev @rossturk

2022-12-12 16:48 UTC, denimalpaca approved these changes
lgtm!

2022-12-13 11:28 UTC, merged