Add data source setup to SQL CLI docs
astronomer/docs pull request #1609
Opened 2022-12-09 13:37 UTC by jwitz

Adding steps for how to configure data sources in SQL CLI projects. I also tidied up some other sections of the doc while I was at it!

2022-12-09 13:39 UTC, jwitz commented on astro/cli/sql-cli.md
> +2. Decide the environment in which you want to use the data. In your `config` directory, open the `configuration.yaml` for the environment.
```suggestion
2. In your `config` directory, open the `configuration.yaml` for the environment where you want to use the data.
```

2022-12-09 13:40 UTC, jwitz commented on astro/cli/sql-cli.md
> +    - Reference `input_file` in your queries. For example:
This was a totally random guess, as there's no example for me to follow. How do you reference a data source without using jinja?

2022-12-09 13:40 UTC, jwitz commented on astro/cli/sql-cli.md
> +    When you run your workflow, the CLI automatically uses the configured data source in your `YAML` file for all queries. This option does not work if you have multiple configured data sources in yo
Are there any other limitations here we should include? How would you manage multiple data sources? Is that supported as of yet?

2022-12-09 13:41 UTC, jwitz commented on astro/cli/sql-cli.md
> +2. In the workflow where you want to use the data, create a new `yaml` file that tells the CLI about your data source and your data destination. You can use the following example file to load data fr
We should link to the source template file in GitHub. @pankajastro can you provide that link?

2022-12-09 14:00 UTC, kwcanuck commented on astro/cli/sql-cli.md
> +2. Decide the environment in which you want to use the data. In your `config` directory, open the `configuration.yaml` for the environment.
```suggestion
2. In your `config` directory, open the `configuration.yaml`  file and identify the environment in which you want to use the data. 
```

2022-12-09 14:01 UTC, kwcanuck commented on astro/cli/sql-cli.md
> +1. Create connections for your data source and data destination. See [Configure environments and connections](#configure-environments-and-connections). Copy the `conn_id` of both connections for the
```suggestion
1. Create connections for your data source and data destination. See [Configure environments and connections](#configure-environments-and-connections). 

2. Copy the `conn_id` for both connections.
```

2022-12-09 14:01 UTC, kwcanuck commented on astro/cli/sql-cli.md
> +2. In the workflow where you want to use the data, create a new `yaml` file that tells the CLI about your data source and your data destination. You can use the following example file to load data fr
```suggestion
3. In the workflow where you want to use the data, create a new `yaml` file that tells the CLI about your data source and your data destination. You can use the following example file to load data from Amazon S3 to Amazon Redshift.
```

2022-12-09 14:02 UTC, kwcanuck commented on astro/cli/sql-cli.md
> +3. Specify your data source in your queries using one of the following options:
```suggestion
4. Specify the data source for your queries using one of the following options: 
```

2022-12-09 16:06 UTC, pankajkoti requested changes

2022-12-09 16:06 UTC, pankajkoti commented on astro/cli/sql-cli.md
> +- `workflows`: This folder contains independent SQL workflows. A workflow is a subfolder containing one or more related SQL files that should be run together. The default SQL project includes a few e
The workflow can also contain YAML files which denote Astro SDK operator tasks to be carried out as part of the workflow.

2022-12-09 16:06 UTC, pankajkoti commented on astro/cli/sql-cli.md
> +    - Reference `input_file` in your queries. For example:
Such a thing is not possible. Select query selects data from a table. Either it should be an existing table in the database or should derive the name of the table from the jinja template resolution.

2022-12-09 16:06 UTC, pankajkoti commented on astro/cli/sql-cli.md
> +    When you run your workflow, the CLI automatically uses the configured data source in your `YAML` file for all queries. This option does not work if you have multiple configured data sources in yo
The YAML files are basically Astro SDK operators. Operators may need connections to multiple datasources. All the connections would be configured in config/<environment>/configuration.yml and the YAML files in workflow would refer to those datasources configured in the config/<environment>/configuration.yml by their ID, but the primary objective of workflow YAML files is to indicate what operation to run e.g. load_file / export_file and others listed here: https://astro-sdk-python.readthedocs.io/en/stable/guides/operators.html

2022-12-09 16:06 UTC, pankajkoti commented on astro/cli/sql-cli.md
> +    conn_id: redshift_conn
Output table in the load workflow tells where to load the data into from the input file. Output table has a conn_id so that workflow knows how to connect to the datasource and then it can contain additional keys like which table to write the data into.

2022-12-09 16:09 UTC, tatiana commented on astro/cli/sql-cli.md
> +An Astro project can't access the connections configured in this directory. Similarly, a SQL project can't access connections configured in an Astro project. Features for unifying these two project s
This is true, and we're working on this as part of https://github.com/astronomer/astro-sdk/issues/1315

2022-12-09 16:28 UTC, tatiana commented on astro/cli/sql-cli.md
> +- `config`: This folder contains configurations for different environments for running SQL. These configurations store connections to external databases. Each SQL environment has one subfolder contai
@pankajkoti I'm starting to feel that we should move `config/global/configuration.yml` to `config/globa.yml` - so all folders are actually environments. WDYT?

2022-12-09 16:33 UTC, pankajkoti commented on astro/cli/sql-cli.md
> +- `config`: This folder contains configurations for different environments for running SQL. These configurations store connections to external databases. Each SQL environment has one subfolder contai
make sense. We should do that, I agree

2022-12-09 16:35 UTC, tatiana commented on astro/cli/sql-cli.md
> +Each `.sql` file must have a database connection defined as `conn_id` in the front matter of the file. This front matter tells the Astro CLI where to load the query results. In the following example,
front matter header

2022-12-12 12:26 UTC, jwitz commented on astro/cli/sql-cli.md
> +- `workflows`: This folder contains independent SQL workflows. A workflow is a subfolder containing one or more related SQL files that should be run together. The default SQL project includes a few e
```suggestion
- `workflows`: This folder contains independent SQL workflows. A workflow is a subfolder containing related SQL queries and file loading tasks that run together. The default SQL project includes a few example workflows that you can run to test functionality.
```

2022-12-12 12:27 UTC, jwitz commented on astro/cli/sql-cli.md
> +### Configure a local data source
There might be examples, but it's helpful to have a clear explanation of how those examples work. It could also help users compare and contrast what's needed for local queries vs. remote queries

2022-12-12 12:28 UTC, jwitz commented on astro/cli/sql-cli.md
> +### Configure a local data source
```suggestion
### Load data from a local data source 
```

2022-12-12 12:31 UTC, jwitz commented on astro/cli/sql-cli.md
> +### Configure an external data source
Our documents should focus on the goal the user is trying to achieve, as opposed to the individual files they will be working with. 

The user goal here is to load data from an external data source and use that in their SQL queries. The YAML workflow is an implementation step of this goal, rather than the focus of it.

2022-12-12 12:33 UTC, jwitz commented on astro/cli/sql-cli.md
> +        path: "s3://tmp9/homes_main.csv"
```suggestion
        path: "s3://<your-data-filepath>.csv"
```

2022-12-12 12:33 UTC, jwitz commented on astro/cli/sql-cli.md
> +        REGION: "us-west-2"
```suggestion
        REGION: "<your-region>"
```

2022-12-12 12:34 UTC, jwitz commented on astro/cli/sql-cli.md
> +3. In the workflow where you want to use the data, create a new `yaml` file that tells the CLI about your data source and your data destination. You can use the following example file to load data fr
```suggestion
3. In the workflow where you want to use the data, create a new `yaml` file that tells the CLI to load the contents of a specific database. For example, the following file would load data from Amazon S3 and store the results of your SQL query in Amazon Redshift.
```

2022-12-12 12:38 UTC, jwitz commented on astro/cli/sql-cli.md
> +    conn_id: redshift_conn
Does the load workflow load the data into the output table before or after the SQL query is run?

2022-12-12 12:40 UTC, jwitz commented on astro/cli/sql-cli.md
> +    FROM input_file
```suggestion
    FROM <your-input-table>
```

2022-12-12 12:40 UTC, jwitz commented on astro/cli/sql-cli.md
> +4. Specify the data source for your queries using one of the following options:
```suggestion
4. Specify the table to query using one of the following options: 
```

2022-12-12 12:42 UTC, jwitz commented on astro/cli/sql-cli.md
> +    - Reference the name of your `yaml` file in your queries using Jinja templating. For example, if the example YAML file in the previous step was named `load_s3.yaml`, your SQL query might look lik
```suggestion
    - Reference the name of your `yaml` file in your SQL files using Jinja templating. The SQL CLI assumes which table to use based on the information provided in your YAML file. For example, if the example YAML file in the previous step was named `load_s3.yaml`, your SQL query might look like the following: 
```

2022-12-12 12:51 UTC, jwitz commented on astro/cli/sql-cli.md
> +- `workflows`: This folder contains independent SQL workflows. A workflow is a subfolder containing one or more related SQL files that should be run together. The default SQL project includes a few e
Going to try to not mention the Astro SDK unless necessary, as SQL practitioners shouldn't have to worry about that implementation detail if it's been abstracted into YAML.

2022-12-12 12:53 UTC, jwitz commented on astro/cli/sql-cli.md
> +- `config`: This folder contains configurations for different environments for running SQL. These configurations store connections to external databases. Each SQL environment has one subfolder contai
Because this might change shape soon, I'm going to not document this detail in the PR.

2023-01-03 10:27 UTC, jwitz commented on astro/cli/sql-cli.md
> +- `config`: This folder contains configurations for different environments for running SQL. These configurations store connections to external databases. Each SQL environment has one subfolder contai
```suggestion
- `config`: This folder contains configurations for different environments for running SQL. These configurations store connections to external databases. Each SQL environment has one subfolder containing its own `configuration.yml`. The default SQL project includes `default` and `dev` environments.
    - `config/global.yml`: This file contains configurations that apply to all of your SQL environments.
```

2023-01-05 14:39 UTC, pankajkoti approved these changes

2023-01-05 16:10 UTC, merged