Add Information About OPENLINEAGE_NAMESPACE
astronomer/docs pull request #1611
Opened 2022-12-09 16:19 UTC by kwcanuck

Resolves #1607

2022-12-09 17:59 UTC, howardyoo reviewed
openlineage-namespace -> OPENLINEAGE_NAMESPACE (capital letters)
I kind of feel this is just too simple.

2022-12-09 18:07 UTC, kwcanuck commented
@howardyoo feel free t provide your edits and suggestions to expand the definition. Also, where do users find OPENLINEAGE_NAMESPACE information?

2022-12-13 15:24 UTC, howardyoo commented
_Here's the detailed paragraphs_

When integrating an external data lineage system with Astro, or [you are running Astro dev locally](https://docs.astronomer.io/astro/create-project), you are required to define the `OPENLINEAGE_NAMESPACE` environment variable, along with other variables like `OPENLINEAGE_URL` and `OPENLINEAGE_API_KEY`. 

Normally, these values will be pre-populated when you are running DAG in Astro, so users do not have to worry about it. However, for external systems, they are not automatically avaialble and thus must be set correctly for the OpenLineage events to be emitted correctly.

- OPENLINEAGE_NAMESPACE: You can find it in Astro UI's Deployments page, right next to the deployment name in a format of `<word>-<word>-<four-digit-number>` (e.g. universal-orbit-2141).
- OPENLINEAGE_URL : Should be set as `https://astro-<your-astro-base-domain>.datakin.com`
- OPENLINEAGE_API_KEY : Can be found in `https://cloud.<your-astro-base-domain>.io/settings`. Look for `Lineage API Key`.

2022-12-13 15:58 UTC, howardyoo requested changes
copy the value that includes a four-digit number <-- should be copy the value that is in the format of `<word>-<word>-<four-digit-number>` (e.g. `some-thing-3121`) I think people may get confused, if they do not recognize this format, so we need to be clear about it.

2022-12-13 16:02 UTC, kwcanuck commented
@howardyoo I have modified the text. Please review when time permits.

2022-12-13 16:10 UTC, howardyoo commented
Hi @kwcanuck , I just noticed this when reviewing the change:
![image](https://user-images.githubusercontent.com/32691630/207384506-a234f7f3-b859-4eea-823e-5c160b3559dc.png)
Will it be okay for you to merge these two sections together? For example, the instruction at the first section covers how to obtain the Openlineage API key which is redundant to the last instruction of obtaining api key. I believe we should merge them.

2022-12-13 16:14 UTC, kwcanuck commented
@howardyoo good catch. I have removed the duplicated content. Back to you for review.

2022-12-13 16:16 UTC, howardyoo approved these changes
LGTM! Thanks for the work!

2022-12-13 16:17 UTC, kwcanuck commented
@jwitz ready for peer review.

2022-12-14 12:19 UTC, jwitz commented on astro/set-up-data-lineage.md
> +When you integrate an external data lineage system with Astro or you are working with Astro locally, you need to define the `OPENLINEAGE_NAMESPACE`, `OPENLINEAGE_URL`, and `OPENLINEAGE_API_KEY` envir
```suggestion
When you integrate an external data lineage system with Astro or you are working with Astro locally outside of a supported Airflow operator, you need to provide a Deployment namespace, your Organization's OpenLineage URL, and your organization's OpenLineage API key. This information is used to send OpenLineage data to the correct place in Astro. 

To locate the your Deployment namespace in the Cloud UI, select a Workspace and then copy the value with the format `<text>-<text>-<four-digit-number>` next to the Deployment name. To locate your Organization's OpenLineage URL and OpenLineage API key, go to `https://cloud.<your-astro-base-domain>.io/settings` and copy the values in **OpenLineage URL** and **OpenLineage API key** respectively.
```

2022-12-14 12:21 UTC, jwitz commented on astro/set-up-data-lineage.md
> +When you integrate an external data lineage system with Astro or you are working with Astro locally, you need to define the `OPENLINEAGE_NAMESPACE`, `OPENLINEAGE_URL`, and `OPENLINEAGE_API_KEY` envir
- Updated this to use the UI for copying the OpenLineage URL
- Removed environment variable formatting as there's no actual environment variable you need to configure with these names. In the setups that follow, you provide the value as opposed to a specific env var.
- Made it clear that this is only for integrating with an external system _that doesn't already have a supported Airflow operator_.

2022-12-14 12:21 UTC, jwitz approved these changes

2022-12-14 12:51 UTC, merged