Add Deployments as Code Documentation
astronomer/docs pull request #1632
Opened 2022-12-13 20:14 UTC by sunkickr

Deployments as Code feature is still being worked on. This PR is for it's documentation in preparation of its release

2022-12-13 20:27 UTC, kwcanuck commented on astro/cli/astro-deployment-create.md
> +For more inforamtion on creating a Deployment using a Deployment file read [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-deployment-with-a-deployment-file)
```suggestion
For more information about creating Deployments with a Deployment file, see [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-deployment-with-a-deployment-file).
```

2022-12-13 20:28 UTC, kwcanuck commented on astro/cli/astro-deployment-inspect.md
> +For more inforamtion on Deploymen files read [Manage Deployments as Code](manage-deployments-as-code.md)
```suggestion
For more information about Deployment files, see [Manage Deployments as Code](manage-deployments-as-code.md).
```

2022-12-13 20:30 UTC, kwcanuck commented on astro/cli/astro-deployment-update.md
> +| `--deployment-file`        | Location of file containing the deployment's updated configuration. File can be in either JSON or YAML format.
```suggestion
| `--deployment-file`        | Location of the file containing the updated configuration file for the Deployment. The file format can be JSON or YAML.                                                                                                        | any YAML or JSON Deployment file             |
```

2022-12-13 20:31 UTC, kwcanuck commented on astro/cli/astro-deployment-update.md
> +For more inforamtion on updating  a Deployment using a Deployment file read [Update a Deployment with a Deployment File](manage-deployments-as-code.md#update-a-deployment-with-a-deployment-file)
```suggestion
To use a Deployment file to update a Deployment, see [Update a Deployment with a Deployment File](manage-deployments-as-code.md#update-a-deployment-with-a-deployment-file).
```

2022-12-13 20:32 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +You can manage a Deployemnent's resources with a Deployment file. Read [Deployments as Code](manage-deploymens-as-code.md) for more information.
```suggestion
To manage Deployment resources with a Deployment file, see [Deployments as Code](manage-deploymens-as-code.md).
```

2022-12-13 20:33 UTC, kwcanuck commented on astro/configure-worker-queues.md
> +You can create, update, and delete multiple worker queues at once using [Deployments as Code](manage-deploymens-as-code.md).
```suggestion
You can create, update, and delete multiple worker queues. See [Deployments as Code](manage-deploymens-as-code.md).
```

2022-12-13 20:33 UTC, kwcanuck commented on astro/environment-variables.md
> +You can create, update, and delete multiple environment variables at once using [Deployments as Code](manage-deploymens-as-code.md).
```suggestion
You can create, update, and delete multiple worker queues. See [Deployments as Code](manage-deploymens-as-code.md).
```

2022-12-13 20:39 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The following is an example of deployment file that is created when you run `astro deployment inspect`. The `environment_variables`, `configuration`, `worker_queues`, and `alert_emails` sections can
```suggestion
The following is an example of a Deployment file that is created when you run `astro deployment inspect`. You can use the `environment_variables`, `configuration`, `worker_queues`, and `alert_emails` sections to create and update a Deployment. The `metadata` section provides information about a Deployment and is not required when you create or delete a Deployment.
```

2022-12-14 12:59 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +Once you determine the configuration of your Astro Deployment this configuration can be stored, created or updated using a JSON or YAML Deployment file. Managing your Deployments with Deployment file
```suggestion
After you configure your Astro Deployment, you can store the configuration as a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the following benefits:
```

2022-12-14 13:23 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- Manage Deployment’s with a large number of worker queues or Environment Variables.
```suggestion
- Simplifies the management of Deployments with a large number of worker queues or environment variables.
```

2022-12-14 13:26 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- You’d like to create a new Deployment that has the same or similar configuration of an already existing deployment
```suggestion
- Allows the quick transfer of existing configuration settings to new Deployments. 
```

2022-12-14 13:30 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- You’d like to create Deployment Templates that can be used to create Deployments for different use cases. For example a Machine Learning Deployment Template can come with configurations, worker que
```suggestion
- Allows the creation of Deployment templates that you can use to create Deployments for different purposes. For example, the worker queues and environment variables in an existing machine learning Deployment template can be repurposed in a machine learning Deployment.
```

2022-12-14 13:30 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# Deployment File Spec
```suggestion
# Deployment file contents
```

2022-12-14 13:31 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The following section will explain the Deployment File Spec with the example below. The below example is a YAML file but Deployment files can be YAML or JSON files.
```suggestion
A Deployment file includes the following specifications:
```

2022-12-14 13:32 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        - key: FOO
```suggestion
        - key: EXAMPLE
```
![image](https://user-images.githubusercontent.com/104205257/207608712-568c2731-18cf-4fe9-b147-3ca9f9b029e6.png)

2022-12-14 13:33 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +          value: bar
```suggestion
          value: test
```

2022-12-14 13:33 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        - key: FOO2
```suggestion
        - key: EXAMPLE2
```

2022-12-14 13:33 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        name: My Deployment
```suggestion
        name: My Test Deployment
```

2022-12-14 13:33 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        description: test deployment create from file
```suggestion
        description: A test Deployment created from a Deployment file
```

2022-12-14 13:34 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        cluster_name: My Cluster
```suggestion
        cluster_name: Test Deployment File Cluster
```

2022-12-14 13:34 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        workspace_name: My Workspace
```suggestion
        workspace_name: Test Deployment File Workspace
```

2022-12-14 13:35 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# not needed or used when creating/updating a deployment
```suggestion
# not needed or used when creating or updating a deployment
```

2022-12-14 13:36 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        deployment_url: cloud.astronomer-dev.io/cl0v1p6lc728255byzyfs7lw21/deployments/clbh5ybjz110732503e94m13z7/analytics
```suggestion
        deployment_url: cloud.astronomer-dev.io/cl0v1p6lc728255byzyfs7lw21/deployments/clbh5ybjz110732503e94m13z7/analytics
```

Should this information be obfuscated or made generic?

2022-12-14 13:36 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +        webserver_url: astronomer.astronomer-dev.run/d94m13z7?orgId=org_dlgevirUCwI9vX10
See previous comment.

2022-12-14 13:38 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The `configuration` section can be used to create and update Astronomer Deployment with specific resources and configurable aspects.
```suggestion
The `configuration` section can be used to create and update Astronomer Deployment with specific settings. 
```

2022-12-14 13:38 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +## Environment Variables
```suggestion
## Environment variables
```

2022-12-14 13:46 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The `environment_variables` section can be used to create and update the Astronomer environment variables you see in the UI. The Deployment File will list the fields of all the variables a Deployment
```suggestion
You can modify the `environment_variables` section to add or update the environment variables displayed in the Cloud UI. The Deployment file lists all of the environment variables in a Deployment. If an environment variable is marked as secret, the value is not shown, but the `is_secret` value is `true`. You can use the `environment_variables.value` field to add or update secret environment variables. Astronomer recommends that you avoid committing Deployment files containing secret values to GitHub repositories.
```

2022-12-14 13:47 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +## Worker Queues
```suggestion
## Worker queues
```

2022-12-14 13:47 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +## Configuration
```suggestion
### Configuration settings
```

2022-12-14 13:53 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The `worker_queues` section can be used define a list of worker queues for a Deployment. All Deployments must have a worker queue named `default`. At least the name `default` needs to be listed to up
```suggestion
The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include a worker queue named `default` to allow worker queue settings to be added or updated, If you don't enter specific values for a worker queue, default values are applied.
```

2022-12-14 13:53 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# Create a Deployment File
```suggestion
## Create a Deployment file
```

2022-12-14 13:54 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +To create a deployment file from an existing Deployment run:
```suggestion
Run the following command to create a Deployment file from an existing Deployment:
```

2022-12-14 13:55 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +This file will look just like the file that is shown above. You can use this file to store and update the original Deployment with this file or create a new Deployment
```suggestion
After the Deployment file is created, you can use it to update the settings of original Deployment, or you can use it to create a new Deployment
```

2022-12-14 13:56 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# Create a Deployment with a Deployment File
```suggestion
## Create a Deployment with a Deployment file
```

2022-12-14 14:00 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +The name provided with the `—name` flag will override name field in the Deployment file. If you’d like you could also delete the `metadata` section and change the `name`, `cluster_name`, or any secti
```suggestion
The `—name` variable overrides the name field in the Deployment file. You can optionally delete the `metadata` section and change the `name`, `cluster_name`, or other section headings before running `astro deployment create`. Keep the following in mind when creating a Deployment with a Deployment file:
```

2022-12-14 14:04 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- The `name` and `cluster_name` fields are the only fields required to create a deployment. The rest of the fields will be auto-populated by “smart defaults”.
```suggestion
- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The rest of the fields are autopopulated.
```

![image](https://user-images.githubusercontent.com/104205257/207615828-9da7a026-c7e0-4a92-ab54-0687b71bb0bc.png)

2022-12-14 14:05 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- When creating worker queues only the `name` field is required. The rest of the fields will be auto populated with “smart defaults”.
```suggestion
- When creating worker queues, only the `name` field is required. The rest of the fields are autopopulated.
```

2022-12-14 14:05 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- When creating Environment Variables your variable must have `key` and `value`
```suggestion
- When creating environment variables, each variable must include a `key` and a `value`.
```

2022-12-14 14:06 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# Update a Deployment with a Deployment File
```suggestion
## Update a Deployment with a Deployment file
```

2022-12-14 14:07 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +To update the Deployment you just created first make sure the `configuration.name` field is correct. Then update `deployment.yaml` to the configuration you want and run:
```suggestion
Confirm the `configuration.name` field is correct for the Deployment, and then run the following command:
```

2022-12-14 14:08 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +You now can see your updated Deployment in the Astro UI. You can update any of the fields in the `environment_variables`, `configuration`, `worker_queues`, or `alert_emails` sections of the Deploymen
```suggestion
The updated Deployment appears in the Cloud UI. You can update any of the fields in the `environment_variables`, `configuration`, `worker_queues`, or `alert_emails` sections of the Deployment file. 

When updating a Deployment with a Deployment file, keep the following in mind:
```

2022-12-14 14:08 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- The command flags always override the values given in the file.
```suggestion
- The command variables override the values in the Deployment file.
```

2022-12-14 14:10 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- You can’t change the Cluster the Deployment is running on. However you can create a new Deployment based on your file with a different Cluster for a similar result
```suggestion
- You can’t change the Cluster the Deployment runs on. However, you can use the Deployment file to create a new Deployment with a different Cluster assignment.
```

2022-12-14 14:11 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- Your environment variables will be updated to match the `environment_variables` section in the file. This means that environment variables that currently exist in the Deployment but not in the file
```suggestion
- Environment variables are updated to match the `environment_variables` section in the Deployment file. Environment variables that are in the Deployment but not in the Deployment file are deleted. If an environment variable is a secret, remove the value from the Deployment file to ensure it doesn’t change during an update.
```

2022-12-14 14:14 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +- Your worker queues will be updated to match the `worker_queues` section in the file. This means that worker queues that currently exist in the Deployment but not in the file will be deleted. Omitte
```suggestion
- Worker queues are updated to match the `worker_queues` section in the Deployment file. Worker queues that are in the Deployment but not in the Deployment file are deleted. Omitted values in the `worker_queues` section keep their existing values and are not updated.
```

2022-12-14 14:15 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +# Next Steps:
```suggestion
## Next steps
```

2022-12-14 14:18 UTC, kwcanuck commented
@sunkickr after you have reviewed and applied my edit suggestions, please request a secondary review from @jwitz. Jake should be aware of this new functionality and have an opportunity to review the content.

2022-12-14 23:14 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +        deployment_url: cloud.astronomer-dev.io/cl0v1p6lc728255byzyfs7lw21/deployments/clbh5ybjz110732503e94m13z7/analytics
This deployment has already been deleted

2022-12-14 23:15 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +        webserver_url: astronomer.astronomer-dev.run/d94m13z7?orgId=org_dlgevirUCwI9vX10
```suggestion
        webserver_url: astronomer.astronomer.run/d94m13z7?orgId=org_dlgevirUCwI9vX10
```

2022-12-15 14:40 UTC, jwitz requested changes
Requesting changes both because this isn't out yet, and also because we should talk about more edge cases/ dangers with using the file (see comments). Otherwise looks great!

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +        cluster_name: Test Cluster
You can't change a Deployment's cluster after you create it right? Will the CLI throw an error if you try to update it? 

If so, we should include a list of settings that you can't update.

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +Edit the `configuration` section when you need to add or update Deployment settings.
```suggestion
The `configuration` section contains all settings that you can configure from the Deployment **Details** page in the Cloud UI. See:

- [Update a Deployment name and description](configure-deployment-resources.md#update-a-deployment-name-and-description)
- [Scheduler resources](configure-deployment-resources.md#scheduler-resources).

```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +You can modify the `environment_variables` section to add or update the environment variables displayed in the Cloud UI. The Deployment file lists all of the environment variables in a Deployment. If
```suggestion
The `environment_variables` section contains configurations Deployment environment variables. See [Environment variables](environment-variables.md).

You can set `environment_variables.is_secret: true` on any new or existing environment variables to set them as secret, but you won't be able to retrieve the secret value from the Deployment once you push your configuration. Astronomer recommends that you avoid committing Deployment files containing secret values to GitHub repositories.
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Create a Deployment file
```suggestion
## Create a Deployment file from an existing Deployment
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +After the Deployment file is created, you can use it to update the settings of original Deployment, or you can use it to create a new Deployment
```suggestion
After the Deployment file is created, you can use it to update the settings of original Deployment, or you can use it to create a new Deployment.
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +Run the following command to create a new Deployment with a Deployment file:
```suggestion
Run the following command to create a new Deployment on Astro based on a Deployment file:
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +The name provided with the `—name` flag will override name field in the Deployment file. If you’d like you could also delete the `metadata` section and change the `name`, `cluster_name`, or any secti
This doesn't sound right to me.. you wouldn't be deleting the `metadata` section in its entirety, you're just overriding individual values in the section right? I would remove this sentence entirely:

```
You can optionally delete the `metadata` section and change the `name`, `cluster_name`, or other value before running `astro deployment create`.
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The rest of the fields are autopopulated.
```suggestion
- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The CLI will create the Deployment using default values for each unspecified configuration. These default values are the same default values for when you create a Deployment from the Cloud UI.
```

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- When creating worker queues, only the `name` field is required. The rest of the fields are autopopulated.
What's the logic for selecting default worker queue settings?

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- You can’t change the Cluster the Deployment runs on. However, you can use the Deployment file to create a new Deployment with a different Cluster.
Are there any other variables like this? What happens if you attempt to update this in the config file?

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- Environment variables are updated to match the `environment_variables` section in the Deployment file. Environment variables that are in the Deployment but not in the Deployment file are deleted. I
```suggestion
- The Deployment's environment variables are updated to match the exact variables configured in `environment_variables`. Any variables that exist in the Deployment but are not in the Deployment file are deleted. If an environment variable is a secret, remove the value from the Deployment file to ensure it doesn’t change during an update.
```
This almost seems worth putting in a `:::danger` note!

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- Worker queues are updated to match the `worker_queues` section in the Deployment file. Worker queues that are in the Deployment but not in the Deployment file are deleted. Omitted values in the `wo
```suggestion
- Worker queues are updated to match the `worker_queues` section in the Deployment file. Any existing worker queues that are in the Deployment but not in the Deployment file are deleted.
```
Same here, we should put this in a `:::danger` note.

Deleting the note about unspecified values because that seems like expected behavior.

2022-12-15 14:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Next steps:
```suggestion
## See also
```

2022-12-15 21:44 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +deployment:
maybe but I think we should keep this up to date. Any change to this spec after 1.9 needs to be well documented in release notes

2022-12-15 21:45 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +        cluster_name: Test Cluster
it will through an error. I tried to explain in this doc what could not be updated in later sections

2022-12-15 21:51 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +The name provided with the `—name` flag will override name field in the Deployment file. If you’d like you could also delete the `metadata` section and change the `name`, `cluster_name`, or any secti
if you are using the deployment file to create another deployment the metadata section is not needed

2022-12-15 21:53 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +The name provided with the `—name` flag will override name field in the Deployment file. If you’d like you could also delete the `metadata` section and change the `name`, `cluster_name`, or any secti
need to rewrite this sentence it's actually not correct

2022-12-15 21:58 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +- When creating worker queues, only the `name` field is required. The rest of the fields are autopopulated.
I'm not sure it's been explained to me as "smart defaults" but a default worker queue will be created if not specified

2022-12-15 21:59 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +- You can’t change the Cluster the Deployment runs on. However, you can use the Deployment file to create a new Deployment with a different Cluster.
you will get an error saying something like you can't change the cluster for an existing deployment. you also can't delete a default worker queue

2022-12-15 22:00 UTC, sunkickr commented on astro/manage-deployments-as-code.md
> +- Worker queues are updated to match the `worker_queues` section in the Deployment file. Worker queues that are in the Deployment but not in the Deployment file are deleted. Omitted values in the `wo
okay just don't want a user to be confused and do more work than they have to

2023-01-05 18:28 UTC, kwcanuck commented on astro/manage-deployments-as-code.md
> +After you configure your Astro Deployment, it can  be stored,  stored, created or updated  using a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the followi
```suggestion
After you configure your Astro Deployment, it can  be stored, created or updated  using a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the following benefits:
```

2023-01-05 18:29 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +astro deployment inspect -d [deployment_id] > deployment.yaml
```suggestion
astro deployment inspect -d <deployment-id> > deployment.yaml
```

2023-01-05 18:29 UTC, jwitz commented on astro/configure-worker-queues.md
> +:::
```suggestion
:::tip

You can create, update, and delete multiple worker queues at once. See [Deployments as Code](manage-deploymens-as-code.md).

:::
```

2023-01-06 11:57 UTC, jwitz commented on astro/cli/astro-deployment-inspect.md
> +:::note
This link should be at the top of the document.

2023-01-06 11:57 UTC, jwitz commented on astro/cli/astro-deployment-update.md
> +
```suggestion
```

2023-01-06 11:57 UTC, jwitz commented on astro/environment-variables.md
> +
```suggestion
```

2023-01-06 11:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
```suggestion
```

2023-01-06 11:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- When creating worker queues, only the `name` field is required. The rest of the fields are autopopulated.
```suggestion
- When creating worker queues, only the `name` field is required. Any unspecified fields are populated with smart defaults based on your cluster's available worker types. 
```

2023-01-06 11:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
```suggestion

:::danger 

You must push individual Deployment changes alongside all existing Deployment configurations whenever you update a Deployment with a Deployment file. If a configuration exists on Astro but doesn't exist in your Deployment file, such as a worker queue, that configuration is deleted when you push your Deployment file. 

:::

```

2023-01-06 12:00 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +The updated Deployment appears in the Cloud UI. You can update any of the fields in the `environment_variables`, `configuration`, `worker_queues`, or `alert_emails` sections of the Deployment file.
```suggestion
The updated Deployment appears in the Cloud UI.
```

2023-01-06 12:01 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +After you configure your Astro Deployment, it can  be stored, created or updated  using a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the following benefi
```suggestion
After you configure your Astro Deployment, it can be stored, created or updated using a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the following benefits:
```

2023-01-06 12:03 UTC, jwitz reviewed
@paolaperaza I think this is ready for your review!

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +astro deployment create --deployment-file new-deployment.yaml
```suggestion
astro deployment create --deployment-file <deployment-template>.yaml
```

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +Now you can use this deployment template file to create a new Deployment with the same configuration as the original.
```suggestion
```

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Create a Deployment with a Deployment file
I think it makes the most sense to frame this action within the context of a template file. It helps us reinforce the good habit of creating Deployments based on template files instead of Deployment inspection files.

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +First update the `configuration.name` field to relect the name of the new Deployment. Then run the following command to create a new Deployment on Astro based on a Deployment file:
```suggestion
1. In your Deployment template file, provide a name for the new Deployment.
2. Run the following command to create a new Deployment based on the Deployment file:
```

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +```
```suggestion
    ```bash
    astro deployment create --deployment-file new-deployment.yaml
    ```
```

2023-01-11 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The CLI will create the Deployment using default values for each unspecified configuration. These default v
```suggestion
- You can create a Deployment from a standard Deployment file generated by `astro deployment inspect`, but you must replace the existing Deployment name and description and remove the metadata before using it as a template. If you plan on using a Deployment's configuration as a template for future Deployments, Astronomer recommends using `astro deployment inspect --template`.
- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The CLI will create the Deployment using default values for each unspecified configuration. These default values are the same default values for when you create a Deployment from the Cloud UI.
```

2023-01-12 18:10 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +You can use the `environment_variables`, `configuration`, `worker_queues`, and `alert_emails` sections to create and update a Deployment. The `metadata` section provides information about a Deploymen
```suggestion
You can use the `environment_variables`, `configuration`, `worker_queues`, and `alert_emails` sections to create or update a Deployment. 

The `metadata` section is automatically populated when you run `astro deployment inspect` to check the status of an existing Deployment. Do not configure this section when creating or updating a Deployment with a Deployment file. 
```

2023-01-12 18:10 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include configuration for a `default` worker queue. If you don't enter specific values for a worker q
```suggestion
The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include configuration for a `default` worker queue. If you don't enter specific values for a worker queue, smart default values based on your available worker types are applied.
```

2023-01-12 18:11 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
```suggestion
```

2023-01-12 18:11 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +```
```suggestion
    ```bash
    astro deployment create --deployment-file <deployment-template>.yaml
    ```
```

2023-01-12 18:11 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +When updating a Deployment with a Deployment file, keep the following in mind:
```suggestion
Keep the following in mind when when updating a Deployment with a Deployment file:
```

2023-01-12 18:13 UTC, jwitz approved these changes

2023-01-13 05:28 UTC, paolaperaza requested changes
Left a couple comments but didn't get to finish and don't think this is quiiiite ready to rock yet.

Let's jam tomorrow @jwitz

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-create.md
> +| `--dag-deploy`        | Enables DAG-only deploys for the deployment (default `disable`)                                                                                                          | `e
```suggestion
| `--dag-deploy`        | Enables DAG-only deploys for the Deployment. The default is `disable`.                                                                                                        | `enable` or `disable`             |
```

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-create.md
> +| `--deployment-file`        | Location of file containing the Deployment to create. File can be in either JSON or YAML format. See [Create a Deployment with a Deployment File](manage-deployments-as-
```suggestion
| `--deployment-file`        | Location of the template file that specified the configuration of the new Deployment. File can be in either JSON or YAML format. See [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-deployment-with-a-deployment-file).                                                                                                       | A valid file path for YAML or JSON Deployment file             |
```

We should standardize on "template file" vs "Deployment file" vs "configuration file"?

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-create.md
> +# Specify the new Deployment's configuration with a yaml file
```suggestion
# Specify the new Deployment's configuration with a YAML file
```

Always caps? Add to style guide?

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-inspect.md
> +:::note
```suggestion
::: info
```

right?

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-inspect.md
> +For more information about Deployment files, see [Manage Deployments as Code](manage-deployments-as-code.md).
```suggestion
For more information about how to use Deployment files, see [Manage Deployments as Code](manage-deployments-as-code.md).
```

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-inspect.md
> +| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is YAML configuration file that includes all information about a Deployment except for its name, d
```suggestion
| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is a YAML configuration file that includes all information about a Deployment. The file for an inspected Deployment does not include its name, description field, and metadata. | None            |
```

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-inspect.md
> +| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is YAML configuration file that includes all information about a Deployment except for its name, d
```suggestion
| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is YAML configuration file that includes all information about a Deployment except for its name, description field, and unique metadata. | None            |
```

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-inspect.md
> +# Store a Deployment's configuration in a deployment file
```suggestion
# Save the current state of a Deployment's configuration to a Deployment file
```

2023-01-13 05:28 UTC, paolaperaza commented on astro/cli/astro-deployment-update.md
> +| `--deployment-file`        | Location of the updated Deployment configuration file. The file format can be JSON or YAML. See [Create a Deployment with a Deployment File](manage-deployments-as-code.
Make wording consistent here?

2023-01-13 13:42 UTC, jwitz commented on astro/cli/astro-deployment-create.md
> +| `--deployment-file`        | Location of file containing the Deployment to create. File can be in either JSON or YAML format. See [Create a Deployment with a Deployment File](manage-deployments-as-
Template file is slightly different from Deployment file. A Deployment file can include metadata for an existing Deployment that you inspected and can't be used to create other deployments without removing that metadata.

2023-01-13 13:43 UTC, jwitz commented on astro/cli/astro-deployment-inspect.md
> +| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is YAML configuration file that includes all information about a Deployment except for its name, d
"The file for an inspected Deployment does not include its name" This isn't quite right, some files for Deployments _do_ contain this information, it's only template files that don't

2023-01-13 13:45 UTC, jwitz commented on astro/cli/astro-deployment-update.md
> +| `--deployment-file`        | Location of the updated Deployment configuration file. The file format can be JSON or YAML. See [Create a Deployment with a Deployment File](manage-deployments-as-code.
```suggestion
| `--deployment-file`        | Location of the template file to update the Deployment with. The file format can be JSON or YAML. See [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-template-file-from-an-existing-deployment).                                                                                                        | YAML or JSON Deployment configuration file             |
```

2023-01-13 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Deployment file contents
Rename to "Inspect Deployment"

2023-01-13 16:06 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    environment_variables:
Link out to here from CLI reference

2023-01-13 16:07 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Deployment file contents
Potentially move this below template docs?

2023-01-13 16:11 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Deployment file contents
Also, make file format/ description within the context of the template file vs. the inspection file.

2023-01-17 15:08 UTC, jwitz commented on astro/cli/astro-deployment-inspect.md
> +| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is YAML configuration file that includes all information about a Deployment except for its name, d
```suggestion
| `-t`, `--template`          | Create a template file for the inspected Deployment. A template file is a YAML configuration file that includes all information about a Deployment except for its name, description field, and unique metadata. | None            |
```

2023-01-17 15:08 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +Create a Deployment template file to programmatically create new Deployments based on configurations from an existing Deployment. A template file is YAML configuration file that includes all informat
```suggestion
Create a Deployment template file to programmatically create new Deployments based on configurations from an existing Deployment. A template file is a YAML configuration file that includes all information about a Deployment except for its name, description field, and metadata.
```

2023-01-18 05:53 UTC, paolaperaza reviewed
Couple comments here @jwitz if you wanna take a look in the morn. I'll hop on to give a final review before team meeting!

2023-01-18 05:53 UTC, paolaperaza commented on astro/cli/astro-deployment-create.md
>  # Specify 50 AU for the Deployment's workers. The Astro CLI prompts you for required information
Ope, we no longer have AUs for workers. Can we check this?

2023-01-18 05:53 UTC, paolaperaza commented on astro/cli/astro-deployment-update.md
> +| `--deployment-file`        | Location of the template file to update the Deployment with. The file format can be JSON or YAML. See [Create a Deployment with a Deployment File](manage-deployments-as
```suggestion
| `--deployment-file`        | Location of the template file to update the Deployment with. The file format can be JSON or YAML. See [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-template-file-from-an-existing-deployment).                                                                                                        | A valid file path to any YAML or JSON Deployment configuration file             |
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/cli/astro-deployment-update.md
> +# Specify the updated Deployment's configuration with a yaml file
```suggestion
# Update the Deployment according to the configurations specified in the YAML Deployment file
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +After you configure your Astro Deployment, it can be stored, created or updated using a JSON or YAML Deployment file. Using Deployment files to manage your Deployments provides the following benefits
```suggestion
After you configure your Astro Deployment, its unique configurations can be stored as a JSON or YAML Deployment file.

You can use Deployment files to manage your Deployment as code. Specifically:
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +
```suggestion

- Create a template file from an existing Deployment and use it to programmatically create another Deployment with the same configurations. This is an alternative to creating a new Deployment in the Cloud UI and manually copying configurations.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +- Manage Deployments as files from a Github repository.
```suggestion
- Manage Deployment configurations from a GitHub repository and in a single place.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +- Create Deployment templates for specific use cases. For example, the worker queues and environment variables in an existing machine learning Deployment template can be repurposed in a machine learn
```suggestion
- Create a single source of truth for Deployments with a particular use case. For example, standardize your team's configuration of sandbox environments.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +- Create Deployment templates for specific use cases. For example, the worker queues and environment variables in an existing machine learning Deployment template can be repurposed in a machine learn
This is all sort of saying the same thing, right?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +- Quickly update Deployments with a large number of worker queues or environment variables.
```suggestion
- Update existing Deployments faster and more easily than doing so with the Cloud UI or individual Astro CLI flags.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +## Deployment file contents
Let's do inspect Deployment?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +To create a template file, run the following command. Replace `<deployment-template>` with your preferred name for the new template file.
```suggestion
To create a template file from an existing Deployment, run the following command. Replace `<deployment-template>` with your preferred name for the new template file.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +To create a template file, run the following command. Replace `<deployment-template>` with your preferred name for the new template file.
Am I crazy or is there no command here? I feel like we're missing a transition to the contents section?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +The `environment_variables` section contains configurations Deployment environment variables. See [Environment variables](environment-variables.md).
```suggestion
The `environment_variables` section contains configurations for Deployment environment variables. See [Environment variables](environment-variables.md).
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +You can set `environment_variables.is_secret: true` on any new or existing environment variables to set them as secret, but you won't be able to retrieve the secret value from the Deployment once you
```suggestion
You can set `environment_variables.is_secret: true` on any new or existing environment variables to set them as secret, but you won't be able to retrieve the secret value from the Deployment once you push your configuration. Astronomer recommends that you avoid committing Deployment files containing secret values to GitHub repositories. If you are committing these files to continually update a Deployment, update the secret values manually in the Cloud UI and leave them blank in the file.
```

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include configuration for a `default` worker queue. If you don't enter specific values for a worker q
Link to worker queues doc?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include configuration for a `default` worker queue. If you don't enter specific values for a worker q
Better describe what smart default values are?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +Keep the following in mind when creating a Deployment with a Deployment file:
Should this be first above the steps?

2023-01-18 05:53 UTC, paolaperaza commented on astro/manage-deployments-as-code.md
> +## Inspect a Deployment
Is this now duplicate?

2023-01-18 10:27 UTC, jwitz commented on astro/cli/astro-deployment-create.md
> +
```suggestion
```

2023-01-18 10:30 UTC, jwitz commented on astro/cli/astro-deployment-inspect.md
> +:::
```suggestion
For more information about how to use Deployment files, see [Manage Deployments as Code](manage-deployments-as-code.md).
```

2023-01-18 10:32 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +The `worker_queues` section defines the worker queues for a Deployment. All Deployment files must include configuration for a `default` worker queue. If you don't enter specific values for a worker q
David didn't have that info, I think this is fine for now until we get clarification?

2023-01-18 10:33 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +- When creating environment variables, each variable must include a `key` and a `value`.
```suggestion
Before you create a Deployment from a template file, keep the following in mind:

- You can create a Deployment from a standard Deployment file generated by `astro deployment inspect`, but you must replace the existing Deployment name and description and remove the metadata before using it as a template. If you plan on using a Deployment's configuration as a template for future Deployments, Astronomer recommends using `astro deployment inspect --template`.
- The `name` and `cluster_name` fields are the only fields required to create a Deployment. The CLI will create the Deployment using default values for each unspecified configuration. These default values are the same default values for when you create a Deployment from the Cloud UI.
- When creating worker queues, the `name` and `worker_type` fields are required. Any unspecified fields are populated with smart defaults based on your cluster's available worker types. 
- When creating environment variables, each variable must include a `key` and a `value`.

1. In your Deployment template file, provide a name for the new Deployment.
2. Run the following command to create a new Deployment based on the Deployment file:

    ```bash
    astro deployment create --deployment-file <deployment-template>.yaml
    ```
```

2023-01-18 10:36 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +``sh
```suggestion
```sh
```

2023-01-18 10:36 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +``
```suggestion
```
```

2023-01-18 10:39 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Inspect a Deployment
No, because this is about inspecting as opposed to templating a Deployment. There's no expectation of using this file to create a new Deployment.

2023-01-18 10:40 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +## Inspect a Deployment
There's nothing preventing you from using a template file to update an existing Deployment, but I imagine we don't want people doing it that way because it involves more steps. We should have a separate section that uses the base "Deployment file" workflow for updating Deployments.

2023-01-19 04:57 UTC, paolaperaza approved these changes
And with that, I'll give a ✅ here! After reading this more thoroughly, @jwitz I did some things:

- Removed the "Inspect a Deployment" section in favor of "Create a template file". I know they're two different actions, but I think we can be clear about that while also focusing the doc on the primary value-based actions
- Clarified the difference between Deployment and template file
- Simplified some of the bullet points on things to keep in mind
- Added an optional step to _confirm_ your changes on create and update
- Added an (I think missing) step to actually make changes to the file on update

You may hate me for making these changes after many a back-and-forth but... let me know what you think. I feel confident enough with the bones here that I'll let you polish off and merge.

Tagged @jemishp for a review as well. Jemish -- if we merge this PR before you take a look, shoot us a Slack and let's make sure we don't miss anything that you catch.

2023-01-19 06:11 UTC, jemishp approved these changes
Made a few suggestions but looks good other wise.

Let me know if you have any questions and happy to help.

2023-01-19 06:11 UTC, jemishp commented on astro/manage-deployments-as-code.md
> +          value: "
```suggestion
          value: ""
```

2023-01-19 06:11 UTC, jemishp commented on astro/cli/astro-deployment-inspect.md
>  astro deployment inspect <deployment-name> --key configuration.cluster_id
```suggestion
astro deployment inspect -n <deployment-name> --key metadata.cluster_id
```

2023-01-19 06:11 UTC, jemishp commented on astro/cli/astro-deployment-inspect.md
```suggestion
Alternatively `cluster_name` can be looked up by running `astro deployment inspect -n <deployment-name> --key configuration.cluster_name`

```

2023-01-19 10:05 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    ```
```suggestion
    ```

```

2023-01-19 10:09 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +title: 'Manage Deployments as Code'
```suggestion
sidebar_label: 'Manage Deployments as code'
title: 'Manage Deployments as code'
```

2023-01-19 10:10 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +</head>
```suggestion
```

2023-01-19 10:10 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +id: manage-deployments-as-code
```suggestion
id: manage-deployments-as-code
description: "Manage an Astro Deployment with a JSON or YAML file."
```

2023-01-19 10:14 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +When you use a template file to create a new Deployment, you might choose to change these values. All information in the template file is also available in the Cloud UI. See the following template fi
```suggestion
All information in the template file is also available in the Cloud UI. See the following template file as an example.
```

2023-01-19 10:14 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +You can create a Deployment in the Astro CLI according to the configurations specified in a given template file. Before you do so, keep the following in mind:
```suggestion
You can create a Deployment in the Astro CLI according to the configurations specified in a given template file. Before you do, keep the following in mind:
```

2023-01-19 10:15 UTC, jwitz commented on astro/cli/astro-deployment-inspect.md
> +$ astro deployment inspect <deployment-id> > deployment.yaml
```suggestion
$ astro deployment inspect <deployment-id> > deployment.yaml

# Save a Deployment as a JSON template file
$ astro deployment inspect <deployment-id> --template -o json > deployment.json
```

2023-01-19 10:16 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +A Deployment file is a complete snapshot of an existing Deployment at the point you inspected it. It's similar to a template file, but additionally contains your Deployment's name, description, and m
```suggestion
A Deployment file is a complete snapshot of an existing Deployment at the point you inspected it. It's similar to a template file, but also contains your Deployment's name, description, and metadata. In the same way you use a template file to create a new Deployment, you use a Deployment file to update an existing Deployment with a new set of configurations.
```

2023-01-19 10:17 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +:::danger
```suggestion
:::warning 
```

2023-01-19 10:26 UTC, jwitz commented
Confirmed everything looks good on the preview site! Merging

2023-01-19 10:26 UTC, merged