Make Hashicorp setup apply to HCP/ Enterprise
astronomer/docs pull request #1652
Opened 2022-12-16 16:54 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1642

2022-12-16 18:14 UTC, kwcanuck commented on astro/secrets-backend.md
> +1. Run the following command to [create a Vault policy](https://www.vaultproject.io/docs/concepts/policies) that Astro can use to access Vault:
```suggestion
1. Run the following command to [create a Vault policy](https://www.vaultproject.io/docs/concepts/policies) that Astro can use to access a Vault server:
```

2022-12-16 18:15 UTC, kwcanuck commented on astro/secrets-backend.md
> +4. Retrieve the `role-id` and `secret-id` for your AppRole by running the following commands:
```suggestion
4. Run the following commands to retrieve the `role-id` and `secret-id` for your AppRole:
```

2022-12-16 18:15 UTC, kwcanuck commented on astro/secrets-backend.md
> +    Save these values for later in the setup.
```suggestion
    Save these values. You'll need them later to complete the setup.
```

2022-12-16 18:17 UTC, kwcanuck approved these changes

2023-02-22 14:11 UTC, kwcanuck commented
@jwitz what remains to get this PR merged?

2023-02-22 15:07 UTC, jwitz commented
@kwcanuck I'm waiting on @jacobm3 's review, will ping again!

2023-02-23 05:32 UTC, jacobm3 requested changes
The additional info block with `"namespace": "admin"` looks great and is the precise info needed for HCP use, and enough of a pointer for Vault Enterprise use. 

I would not add the `vault secrets disable secret` commands. They are not needed if the reader is starting with a clean Vault installation and they could cause data loss if run on a Vault server that already has secrets at that mount point.

2023-02-23 15:31 UTC, jwitz commented on astro/secrets-backend.md
> +vault secrets disable secret
```suggestion
```

2023-02-23 15:31 UTC, jwitz commented on astro/secrets-backend.md
> +vault secrets disable secret
```suggestion
```

2023-02-23 16:11 UTC, jwitz commented
Gonna go ahead and merge this because the requested changes have been addressed.

2023-02-23 16:12 UTC, merged