Fixed broken links to example configurations
astronomer/docs pull request #166
Opened 2020-12-21 22:28 UTC by jwitz

Closes https://github.com/astronomer/docs/issues/165. Looks like we accidentally linked to a local branch before, so updating these links to point towards the appropriate `-release` branches.

2020-12-21 22:29 UTC, jwitz commented on enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
> +- For more detailed instructions and a full list of optional flags, refer to GKE's ["Creating a Cluster"](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster).
I am really puzzled over why certain files keep showing changes where no changes where made. Let me know if you have a solution to this!

2020-12-22 15:43 UTC, paolaperaza requested changes
@jwitz Take a look at the link in the /next/ folder - I think it should be 0.23 since that's the next Enterprise LTS and then keep the 0.16 release link to the 0.16 folder.

Will approve + merge from there!

2020-12-22 15:43 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +For more example configuration files, go [here](https://github.com/astronomer/astronomer/tree/release-0.17/configs).
@jwitz Shouldn't this be: https://github.com/astronomer/astronomer/tree/release-0.16/configs

Looks like that's actually also the link you have below!

2020-12-22 15:43 UTC, paolaperaza commented on enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
> +- For more detailed instructions and a full list of optional flags, refer to GKE's ["Creating a Cluster"](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster).
Ha, yea I'm actually not sure - maybe something in Atom that automatically removes spacing or something?

2020-12-22 15:43 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +For more example configuration files, go [here](https://github.com/astronomer/astronomer/tree/release-0.17/configs).
Or since this is `/next`, it should be: https://github.com/astronomer/astronomer/tree/release-0.23/configs

2020-12-22 17:40 UTC, jwitz commented
Sounds good, thanks for the clarification @paolaperaza ! Just fixed the link in `next`.

2020-12-22 18:47 UTC, paolaperaza approved these changes
Perf looks good - thanks @jwitz !

2020-12-22 18:47 UTC, merged