Runtime is now supported based on major version
astronomer/docs pull request #1660
Opened 2022-12-19 21:09 UTC by jedcunningham

We are now supporting Runtime based on the major version, making it realistic for us to make updates to OL/astronomer-providers be minor Runtime releases.

2022-12-20 15:49 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 7             | 2.5.0            |
```suggestion
| 6             | 2.4.0-2.4.1            |
| 7             | 2.5.0                  |
```

2022-12-20 15:51 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 6             | 2.4.0-2.4.1            |
```suggestion
| 6             | 2.4.0-2.4.3            |
```

2022-12-20 17:39 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> -Each Runtime version in a given minor series supports only a single version of Apache Airflow. For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
I didn't think it added much, feel free to reword it if you think we should keep something here though.

2022-12-21 09:56 UTC, jwitz commented on astro/runtime-image-architecture.md
> +| 7             | 2.5.0                  |
```suggestion
| 4.1.x         | 2.2.4                  |
| 4.2.x         | 2.2.4-2.2.5            |
| 5.0.x         | 2.3.0-2.3.4            |
| 6.0.x         | 2.4.0-2.4.1            |
| 7.0.x         | 2.5.0            |
```

2022-12-21 09:57 UTC, jwitz commented on astro/runtime-image-architecture.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
```suggestion
Each Runtime version in a given minor series supports only a single version of Apache Airflow. For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
```

2022-12-21 13:42 UTC, astro-rft requested changes
Some suggestions to simplify our messaging with these changes. Tagging @chomipi88 to see if any logic needs to change in the in-product upgrade prompts based on these changes.

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backwards-compatible, as well as new minor versions of `astronomer-providers` and `op
```suggestion
- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backwards-compatible, which may include new minor versions of `astronomer-providers` and `openlineage-airflow`.
```
The current framing makes it sound as though the packages could introduce breaking changes

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +| 7             | 2.5.0                  |
I would tend to go the other way here and map 1:1 between Runtime major and Airflow minor, removing Airflow patch references

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
I think we're exposing too much complexity here. The key message IMO is a Runtime major = Airflow major.minor pair.

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +| 6.0.4+        | Debian 11.3 (bullseye)                | AMD64 and ARM64 |
```suggestion
| 6        | Debian 11.3 (bullseye)                | AMD64 and ARM64 |
```
The latest patch is implied as supported, so Runtime 6 supports ARM64.

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +| 6.0.0 - 6.0.3 | Debian 11.3 (bullseye)                | AMD64           |
```suggestion
```
This is extra information that is not required

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime version, only the latest patch is supported at any given time. If you report an issue with an Astro Runtime patch version that is not latest, the Astronomer Support team will always
```suggestion
For each Runtime release channel, only the latest minor.patch version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support team will always ask that you upgrade as a first step to resolution. For example, we encourage any user who reports an issue with Astro Runtime 4.0.2 to first upgrade to the latest 4.x.y version as soon as it's generally available.
```

2022-12-21 13:42 UTC, astro-rft commented on astro/runtime-version-lifecycle-policy.md
> +| [4](runtime-release-notes.md#astro-runtime-420) | 2.2.4-2.2.5            | March 10, 2022     | September 2023          |
```suggestion
| [4](runtime-release-notes.md#astro-runtime-420) | 2.2            | March 10, 2022     | September 2023          |
```

2022-12-21 14:59 UTC, chomipi88 commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime version, only the latest patch is supported at any given time. If you report an issue with an Astro Runtime patch version that is not latest, the Astronomer Support team will always
To be clear, support will ask them to upgrade from 4.0.2 to 4.2.0 (latest 4.x.y as of today) in this case?

2022-12-21 15:23 UTC, chomipi88 commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime version, only the latest patch is supported at any given time. If you report an issue with an Astro Runtime patch version that is not latest, the Astronomer Support team will always
Current logic in support form is below. 
![image](https://user-images.githubusercontent.com/87984472/208940650-0f5fd9b5-b8bc-4661-9352-186fb8fba83d.png)

2022-12-21 15:29 UTC, chomipi88 commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime version, only the latest patch is supported at any given time. If you report an issue with an Astro Runtime patch version that is not latest, the Astronomer Support team will always
And here is an example of the deprecation notice based on previous guidance.
![image](https://user-images.githubusercontent.com/87984472/208941937-de7d788a-9b26-4bb5-a444-f8101216c05b.png)

2022-12-21 16:10 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
This isn't true (and hasn't been for a while actually). That's why I said it needs rewording if we want to keep something here, but I vote we get rid of it.

2022-12-21 16:10 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 6.0.4+        | Debian 11.3 (bullseye)                | AMD64 and ARM64 |
Good call 👍

2022-12-21 16:10 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime version, only the latest patch is supported at any given time. If you report an issue with an Astro Runtime patch version that is not latest, the Astronomer Support team will always
> support will ask them to upgrade from 4.0.2 to 4.2.0 (latest 4.x.y as of today)

4.2.9 (that's the latest), but yes.

The support form language may need tweaking, as once 5.1.0 is releases it will include new functionality, but no breaking changes.

2022-12-21 16:10 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [4](runtime-release-notes.md#astro-runtime-420) | 2.2.4-2.2.5            | March 10, 2022     | September 2023          |
Why? Should we do this for the rest?

2022-12-21 16:15 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 7             | 2.5.0                  |
```suggestion
| 4             | 2.2                    |
| 5             | 2.3                    |
| 6             | 2.4                    |
| 7             | 2.5                    |
```

2022-12-21 16:16 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 7             | 2.5.0                  |
@astro-rft, I like that. Done.

2022-12-21 16:16 UTC, jedcunningham commented on astro/runtime-image-architecture.md
> +| 6        | Debian 11.3 (bullseye)                | AMD64 and ARM64 |
```suggestion
| 5             | Debian 11.3 (bullseye)                | AMD64           |
| 6             | Debian 11.3 (bullseye)                | AMD64 and ARM64 |
```

2022-12-21 16:19 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [7](runtime-release-notes.md#astro-runtime-700) | 2.5.0                  | December 3, 2022   | June 2023               |
```suggestion
| [4](runtime-release-notes.md#astro-runtime-420) | 2.2                    | March 10, 2022     | September 2023          |
| [5](runtime-release-notes.md#astro-runtime-500) | 2.3                    | April 30, 2022     | October 2023            |
| [6](runtime-release-notes.md#astro-runtime-600) | 2.4                    | September 19, 2022 | March 2024              |
| [7](runtime-release-notes.md#astro-runtime-700) | 2.5                    | December 3, 2022   | June 2023               |
```

2022-12-21 16:19 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [6](runtime-release-notes.md#astro-runtime-600) | 2.4.0-2.4.3            | September 19, 2022 | March 2024              |
```suggestion
| [4](runtime-release-notes.md#astro-runtime-420) | 2.2                    | March 10, 2022     | September 2023          |
| [5](runtime-release-notes.md#astro-runtime-500) | 2.3                    | April 30, 2022     | October 2023            |
| [6](runtime-release-notes.md#astro-runtime-600) | 2.4                    | September 19, 2022 | March 2024              |
```

2022-12-21 16:19 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [4](runtime-release-notes.md#astro-runtime-420) | 2.2.4-2.2.5            | March 10, 2022     | September 2023          |
I did these tables as well (sorry, somehow missed your comment above before).

2022-12-21 20:03 UTC, astro-rft commented on astro/runtime-image-architecture.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
Fair @jedcunningham. Agreed on removing.

2023-01-03 11:05 UTC, jwitz commented on astro/runtime-image-architecture.md
>  :::info
```suggestion
```

2023-01-03 11:05 UTC, jwitz commented on astro/runtime-image-architecture.md
>  :::
```suggestion
```

2023-01-03 11:06 UTC, jwitz commented on astro/runtime-image-architecture.md
> +- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backwards-compatible, which may include new minor versions of `astronomer-providers`
```suggestion
- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backwards-compatible, which might include new minor versions of `astronomer-providers` and `openlineage-airflow`.
```

2023-01-03 11:08 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime release channel, only the latest minor.patch version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support t
```suggestion
For each major Runtime version, only the latest `minor.patch` version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support team will always ask that you upgrade as a first step to resolution. For example, we encourage any user who reports an issue with Astro Runtime 4.0.2 to first upgrade to the latest 4.x.y version as soon as it's generally available.
```
@astro-rft Can you confirm that this is the case? "Each Runtime release channel" would imply that the latest 7.x.y version is the only supported version for all stable releases.

2023-01-03 11:09 UTC, jwitz commented
LGTM, but @astro-rft can you give the final ✅ before we merge? I have one last question about a specific turn of phrase that we use

2023-01-03 12:41 UTC, astro-rft commented on astro/runtime-version-lifecycle-policy.md
> +For each Runtime release channel, only the latest minor.patch version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support t
Good clarification.

2023-01-03 12:44 UTC, astro-rft approved these changes

2023-01-03 13:25 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backwards-compatible, which might include new minor versions of `astronomer-providers
```suggestion
- **Minor** versions are released for functional changes. This includes API or DAG specification changes that are backward compatible, which might include new minor versions of `astronomer-providers` and `openlineage-airflow`.
```

2023-01-03 13:25 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
```suggestion
For version compatibility information, see the [Runtime release notes](runtime-release-notes.md).
```

2023-01-03 13:27 UTC, kwcanuck commented on astro/runtime-version-lifecycle-policy.md
> +For each major Runtime version, only the latest `minor.patch` version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support t
```suggestion
For each major Runtime version, only the latest `minor.patch` version is supported at any given time. If you report an issue with an Astro Runtime version that is not latest, the Astronomer Support team will always ask that you upgrade as a first step to resolution. For example, any user who reports an issue with Astro Runtime 4.0.2 will be asked to upgrade to the latest 4.x.y version as soon as it's generally available.
```

2023-01-03 13:27 UTC, kwcanuck commented on astro/runtime-version-lifecycle-policy.md
> +For specific version compatibility information, see [Runtime release notes](runtime-release-notes.md).
```suggestion
For version compatibility information, see the [Runtime release notes](runtime-release-notes.md).
```

2023-01-03 13:27 UTC, kwcanuck approved these changes

2023-01-03 17:29 UTC, merged