(ignore for now) Xcoms backend tutorial
astronomer/docs pull request #1666
Opened 2022-12-20 16:21 UTC by TJaniF

Draft to test layout.

2022-12-27 23:50 UTC, kentdanas requested changes
@TJaniF this is a great start! Thanks for tackling this. Here are some initial comments, most of which are minor suggestions.

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +Airflow offers the possibility to use [XComs](airflow-passing-data-between-tasks.md) to pass information between your tasks. By default Airflow uses the [metadata database](airflow-database.md) to st
```suggestion
Airflow offers the possibility to use [XComs](airflow-passing-data-between-tasks.md) to pass information between your tasks. By default Airflow uses the [metadata database](airflow-database.md) to store XComs, which works well for local development purposes but can become limiting. For production environments, Airflow supports configuring a custom XCom backend. 
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +In cases where more storage capacity or the option for custom XComs retention policies is needed, you can use cloud-based object storage such as [AWS S3](https://aws.amazon.com/s3/), [GCP Cloud Stora
```suggestion
This allows you to push and pull XComs to and from an external system such as [AWS S3](https://aws.amazon.com/s3/), [GCP Cloud Storage](https://cloud.google.com/storage) or [Azure Blob Storage](https://azure.microsoft.com/en-us/products/storage/blobs/) or [MinIO](https://min.io/) instance. This tutorial offers example code for each of these object storage solutions.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +In cases where more storage capacity or the option for custom XComs retention policies is needed, you can use cloud-based object storage such as [AWS S3](https://aws.amazon.com/s3/), [GCP Cloud Stora
```suggestion
This allows you to push and pull XComs to and from an external system such as [AWS S3](https://aws.amazon.com/s3/), [GCP Cloud Storage](https://cloud.google.com/storage) or [Azure Blob Storage](https://azure.microsoft.com/en-us/products/storage/blobs/) or [MinIO](https://min.io/) instance. This tutorial offers example code for each of these object storage solutions.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +There are many additional use cases for custom XComs backend solutions, you can learn more about them in the [Best practices](#best-practices) section at the end of this tutorial.
```suggestion
There are many use cases for custom XCom backend solutions, some of which are listed in the [Best practices](#best-practices) section at the end of this tutorial. 
```
I'm a bit on the fence whether to pull the best practices section into the intro. Would make the intro a bit long, but seems like we may want to describe up front why you would want to use them?

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- Create a custom XComs backend using a cloud-based or local object storage.
```suggestion
- Create a custom XCom backend using cloud-based or local object storage.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- Create a custom XComs backend using a cloud-based or local object storage.
```suggestion
- Create a custom XCom backend using cloud-based or local object storage.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- Add a custom logic to the serialization and deserialization methods to store Pandas dataframes as CSV in your custom XComs backend.
```suggestion
- Add custom logic to the serialization and deserialization methods to store Pandas dataframes as CSVs in your custom XCom backend.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +While a custom XComs backend allows you to store virtually unlimited amounts of data as XComs, keep in mind that Airflow was not designed be a data processing framework and you might run into perform
```suggestion
While a custom XCom backend allows you to store virtually unlimited amounts of data as XComs, your Airflow infrastructure will still need to be configured to support passing large amounts of data between your tasks. For help running Airflow at scale, [reach out to Astronomer](https://www.astronomer.io/get-started/).
```
Updated this since I think we're moving away from the "Airflow is not a processing framework" idea with the SDK and other tools like that. I still think it's worth adding a caution, but if this seems to salesy we can frame it another way.

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +In this tutorial the TaskFlow API is used to pass information between tasks. Learn more in our [Airflow decorators](airflow-decorators.md) guide and in the [TaskFlow API in Airflow 2.0 webinar](https
Do you think we need this separate note if we have the TaskFlow API listed in the assumed knowledge?

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- You can follow this tutorial using an AWS, GCP or Azure account. If you want to work locally follow the steps under the `MinIO` tabs.
```suggestion
- A local or cloud-based object storage account. This tutorial has instructions for AWS, GCP, Azure, and MinIO.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- You can follow this tutorial using an AWS, GCP or Azure account. If you want to work locally follow the steps under the `MinIO` tabs.
```suggestion
- A local or cloud-based object storage account. This tutorial has instructions for AWS, GCP, Azure, and MinIO.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +## Step 1: Set up your XComs backend
Maybe this should be "Set up your object storage account"? Saying "set up your xcom backend" kind of makes it seem like it's the whole thing :)

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +1. Log into your Azure account and if you do not have one, [create a storage account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create). We recommend to disable public ac
```suggestion
1. Log into your Azure account and if you do not have one, [create a storage account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create). We recommend disabling public access.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +1. Log into your Azure account and if you do not have one, [create a storage account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create). We recommend to disable public ac
```suggestion
1. Log into your Azure account and if you do not have one, [create a storage account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create). We recommend disabling public access.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +3. [Create a shared access token](https://learn.microsoft.com/en-us/azure/cognitive-services/Translator/document-translation/how-to-guides/create-sas-tokens?tabs=Containers) for the `custom-xcom-back
The permissions should probably be in a bulleted list like they are in the GCS example

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +3. [Create a shared access token](https://learn.microsoft.com/en-us/azure/cognitive-services/Translator/document-translation/how-to-guides/create-sas-tokens?tabs=Containers) for the `custom-xcom-back
```suggestion
3. [Create a shared access token](https://learn.microsoft.com/en-us/azure/cognitive-services/Translator/document-translation/how-to-guides/create-sas-tokens?tabs=Containers) for the `custom-xcom-backend` container. In the dropdown menu for permissions make sure to enable: Read, Add, Create, Write, Delete and List. Select the duration the token will be valid and `HTTPS only` for allowed protocols. Provide the IP address of your Airflow instance. If you are running Airflow locally with the Astro CLI, this is the IP address of your computer.
```
Seems a little weird to mention the Airflow instance before the step in which it's created, but I don't have a great suggestion unless we swap Steps 1 and 2.

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. In order to be able to use the `minio` Python package in Airflow, add it to the `requirements.txt` file of your Astro project.
```suggestion
2. In order to be able to use the `minio` Python package in Airflow, add it to the `requirements.txt` file of your Astro project.
```
This seems a little out of place since it's not part of the connection, particularly since it requires restarting the Airflow instance. Maybe it could be part of Step 2 as an optional sub-step if working with a local backend (and then could say something like "if you are working with a cloud storage backend, the required packages are already included in Astro runtime" or something like that).

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +For Airflow to be able to use your custom XComs backend it is necessary to define an XCom backend class which inherits from the `BaseXCom` class.
```suggestion
For Airflow to use your custom XCom backend, you need to define an XCom backend class which inherits from the `BaseXCom` class.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +1. In your Astro project create a new file in the `include` directory called `s3_xcom_backend_json.py`.
```suggestion
1. In your Astro project, create a new file in the `include` directory called `s3_xcom_backend_json.py`.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +    The code above defines a class called `S3XComBackendJSON`. The class has two methods: `.serialize_value()` defines how the `value` that is pushed to XComs from an Airflow task is handled, while `
```suggestion
    The code above defines a class called `S3XComBackendJSON`. The class has two methods: `.serialize_value()` defines how to handle the `value` that is pushed to XCom from an Airflow task, and `.deserialize_value()` defines the logic to retrieve information from the XCom backend.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +## Step 4: Define a custom XCom class using JSON serialization
Since the text for each of these describing the hook is the same, can we put the tabs just in sub-step 2 for the code, and leave the rest outside of the tabs?

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +For Astronomer customers the process to use the same custom XComs backend for your deployment on Astro is easy. After deploying your code, simply set the same `AIRFLOW__CORE__XCOM_BACKEND` [environme
```suggestion
If you are an Astronomer customer, using this custom XCom backend for your deployment on Astro is easy. After deploying your code, simply set the `AIRFLOW__CORE__XCOM_BACKEND` [environment variable on Astro](https://docs.astronomer.io/astro/environment-variables).
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +<Tabs
Same here with the tabs - do we need them for the whole section, or just for the backend code?

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +    The code above creates a custom XComs backend called `MinIOXComBackendPandas` with added logic to convert a Pandas dataframe to a CSV file, which gets written to the S3 bucket and converted back
Worth adding a note down here somewhere that you can't have multiple backends set up for one Airflow deployment? (I'm assuming you can't....double check me on that though). Just to make it clear that this is a new backend replacing the one created in Step 4 to highlight a slightly different use case.

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +Test the new custom XComs backend by running a DAG that pushes a Pandas dataframe to and pulls a Pandas dataframe from XComs.
```suggestion
Test the new custom XCom backend by running a DAG that passes a Pandas between tasks.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +    The `extract_data` task will push a dictionary to XCom, which will be saved to your blob storage as a JSON file and retrieved by the `calculate_xp_per_height` task. This second task pushes a Pand
```suggestion
    The `extract_data` task will push a dictionary to XCom, which will be saved to your blob storage as a JSON file and retrieved by the `calculate_xp_per_height` task. This second task pushes a Pandas dataframe to XCom, which is only possible when using a custom XCom backend with a serialization option for this type of object. The last task `print_xp_per_height` retrieves the CSV and recreates the Pandas dataframe before printing out the Pokemon and their base experience to height ratio.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +## Best practices
After reading through the whole thing, definitely leaning towards pulling this out into the intro. But if we did decide to leave it here, we should title the section ## Use cases or something like that, since it's not really best practices per se.

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- Running a production environment where custom retention, deletion and backup policies for XComs are desired. With a custom XComs backend you do not need to worry about periodically cleaning up the
```suggestion
- Running a production environment where custom retention, deletion and backup policies for XComs are desired. With a custom XCom backend you do not need to worry about periodically cleaning up the metadata database.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +- The need for custom serialization and deserialization methods. By default Airflow uses JSON serialization which puts limits on the type of data that you can pass via XComs (pickling is available by
```suggestion
- The need for custom serialization and deserialization methods. By default Airflow uses JSON serialization, which puts limits on the type of data that you can pass via XComs (pickling is available by setting `AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True` but has [known security implications](https://docs.python.org/3/library/pickle.html)). A custom XCom backend allows you to implement your own serialization and deserialization methods.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +In this tutorial we've show how to add custom logic to the `.serialize_value()` and  `.deserialize_value()` methods. If you want to further expand the functionality for your custom XComs backend you
```suggestion
In this tutorial we've shown how to add custom logic to the `.serialize_value()` and  `.deserialize_value()` methods. If you want to further expand the functionality for your custom XCom backend, you can override additional methods of the [XCom module](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/xcom/index.html) ([source code](https://github.com/apache/airflow/blob/main/airflow/models/xcom.py)). 
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +A common use case is to want to remove stored XComs upon clearing and rerunning a task in both the Airflow metadata database and the custom XComs backend. To do so the `.clear()` method needs to be o
```suggestion
A common use case for this is removing stored XComs upon clearing and rerunning a task in both the Airflow metadata database and the custom XCom backend. To do so, the `.clear()` method needs to be overridden to include the removal of the referenced XCom in the custom XCom backend. The code below shows an example of a `.clear()` method that includes the deletion of an XCom stored in a custom S3 backend with the S3XComBackendJSON XComs backend from [Step 4](#step-4-define-a-custom-xcom-class-using-json-serialization) of the tutorial.
```

2022-12-27 23:50 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +Congratulations! You learned how to set up a custom XComs backend and how to define your own serialization and deserialization methods.
```suggestion
Congratulations! You learned how to set up a custom XCom backend and how to define your own serialization and deserialization methods. 
```

2022-12-28 15:51 UTC, TJaniF reviewed
Thank you for the review @kentdanas! I went through and accepted all suggestions (some were doubled, not sure why). :)

2022-12-28 18:37 UTC, kentdanas approved these changes
A couple more minor comments, but otherwise this looks good to me! Approving now, and can move on to copy editing next week.

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. Ensure that the provider of your cloud-based object storage account is installed in your Airflow instance. If you are using the Astro CLI the [Amazon](https://registry.astronomer.io/providers/amaz
```suggestion
2. Ensure that the provider of your cloud-based object storage account is installed in your Airflow instance. If you are using the Astro CLI the [Amazon](https://registry.astronomer.io/providers/amazon), [Google](https://registry.astronomer.io/providers/google) and [Azure](https://registry.astronomer.io/providers/microsoft-azure) provider packages come pre-installed in your Astro runtime image. If you are working with a local MinIO instance, add the [`minio` Python package](https://min.io/docs/minio/linux/developers/python/minio-py.html) to your `requirements.txt` file.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. Start up Airflow by running:
```suggestion
2. Start your Airflow project by running:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. [Create a new IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html) for Airflow to access your bucket. You can use the JSON configuration below or use AWS' grap
```suggestion
2. [Create a new IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html) for Airflow to access your bucket. You can use the JSON configuration below or use the AWS GUI to replicate what you see in the screenshot.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +To use a bucket in Google Cloud Storage as your custom XCom backend follow these steps:
```suggestion
Follow these steps to use a bucket in Google Cloud Storage as your custom XCom backend:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +To use an S3 bucket as your custom XCom backend follow these steps:
```suggestion
Follow these steps to use an S3 bucket as your custom XCom backend:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +To use Azure Blob Storage as your custom XCom backend follow these steps:
```suggestion
Follow these steps to use Azure Blob Storage as your custom XCom backend:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. Within the storage account. [Create a new container](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-porta) called `custom-xcom-backend`.
```suggestion
2. Within the storage account, [create a new container](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-porta) called `custom-xcom-backend`. 
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +    In the dropdown menu for permissions make sure to enable the following permissions:
```suggestion
    In the permissions dropdown menu enable the following permissions:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +There are several local object storage solutions available to configure as a custom XCom backend. In this tutorial we are going to use MinIO running in Docker.
```suggestion
There are several local object storage solutions available to configure as a custom XCom backend. In this tutorial we use MinIO running in Docker. 
```
Are there any Airflow docs on supported local storage solutions that we could link to here? Or when we say "several solutions available" do we just mean that you can use any local storage option and multiple options exist generally? If the latter then no need to change anything.

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +2. Go to `http://127.0.0.1:9090/`, log in and create a new bucket called `custom-xcom-backend`.
```suggestion
2. Go to `http://127.0.0.1:9090/`, log in, and create a new bucket called `custom-xcom-backend`.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +## Step 4: Define a custom XCom class using JSON serialization
Yeah I think having more general language is fine

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +The `.serialize_value()` method accomplishes the following:
```suggestion
The `.serialize_value()` method:
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +Whenever you are making changes to your custom XCom backend configuration you will need to restart Airflow for these changes to take effect.
```suggestion
You will need to restart Airflow after making changes to your custom XCom backend configuration for the changes to take effect.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +## Step 5: Run a simple DAG using XCom
```suggestion
## Step 5: Create and run your DAG to generate XComs
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +4. View the logs of both tasks, they include information about the custom XCom backend. The `print_a_number` task includes the full path to the file stored in the custom backend.
```suggestion
4. View the logs of both task. The logs will include information about the custom XCom backend. The `print_a_number` task includes the full path to the file stored in the custom backend.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +A powerful feature of custom XCom backends is the possibility to adjust serialization and deserialization methods to be able to handle objects that cannot be JSON-serialized. In this step you will cr
```suggestion
A powerful feature of custom XCom backends is the possibility to create custom serialization and deserialization methods. This is particularly useful for handling objects that cannot be JSON-serialized. In this step, you will create a new custom XCom backend that can save the contents of a [Pandas](https://pandas.pydata.org/) dataframe as a CSV file.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +The code above creates a custom XCom backend called `CustomXComBackendPandas` with added logic to convert a Pandas dataframe to a CSV file, which gets written to the S3 bucket and converted back to a
```suggestion
The code above creates a custom XCom backend called `CustomXComBackendPandas` with added logic to convert a Pandas dataframe to a CSV file, which gets written to object storage and converted back to a Pandas dataframe upon retrieval. If the value passed is not a Pandas dataframe, the `.serialize()` and `.deserialize` methods will use JSON serialization like the custom XCom backend in [Step 4](#step-4-define-a-custom-xcom-class-using-json-serialization).
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +4. Restart your Airflow instance using `astro dev restart`.
```suggestion
4. Restart your Airflow instance by running `astro dev restart`.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +You can add custom logic inside your `.serialize()` and `.deserialize()` methods to send XCom to several custom XCom backend solutions, for example based on their object type.
```suggestion
You can add custom logic inside your `.serialize()` and `.deserialize()` methods to send XComs to several custom XCom backend solutions, for example based on their object type.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +    The `extract_data` task will push a dictionary to XCom, which will be saved to your blob storage as a JSON file and retrieved by the `calculate_xp_per_height` task. This second task pushes a Pand
```suggestion
    The `extract_data` task will push a dictionary to XCom, which will be saved to your blob storage as a JSON file and retrieved by the `calculate_xp_per_height` task. This second task pushes a Pandas dataframe to XCom, which is only possible when using a custom XCom backend with a serialization method for this type of object. The last task, `print_xp_per_height`, retrieves the CSV and recreates the Pandas dataframe before printing out the Pokemon and their base experience to height ratio.
```

2022-12-28 18:37 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +A common use case for this is removing stored XCom upon clearing and rerunning a task in both the Airflow metadata database and the custom XCom backend. To do so, the `.clear()` method needs to be ov
```suggestion
A common use case for this is removing stored XComs upon clearing and rerunning a task in both the Airflow metadata database and the custom XCom backend. To do so, the `.clear()` method needs to be overridden to include the removal of the referenced XCom in the custom XCom backend. The code below shows an example of a `.clear()` method that includes the deletion of an XCom stored in a custom S3 backend with the S3XComBackendJSON XCom backend from [Step 4](#step-4-define-a-custom-xcom-class-using-json-serialization) of the tutorial.
```

2022-12-28 18:42 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +<TabItem value="aws">
Can we put the tabs here under Step 5? And maybe make the text just "View the XCom in your object storage bucket"? It looks a little weird to have the tabs above the step

2022-12-28 23:09 UTC, TJaniF reviewed
Thanks @kentdanas :) 

@jwitz This one is ready for you in the new year. One note: I added a substep below the code blocks in step 4 and step 6 because otherwise it did not let me indent the text after </tabs> . I don't know if that is the most elegant solution, very open to suggestions 😄

2023-01-12 15:13 UTC, jwitz approved these changes
LGTM! Worth double checking the preview site to make sure all of the tabs and code blocks are rendering as expected.

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +
```suggestion
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +1. In the Airflow UI go to **Admin** -> **Connections** and create a new a connection (**+**) with the Connection Type `Google Cloud`. Provide the name of your project (`custom-xcom-backend-example`)
```suggestion
1. In the Airflow UI go to **Admin** -> **Connections** and create a new a connection (**+**) with the Connection Type `Google Cloud`. Provide the name of your project (`custom-xcom-backend-example`). Open the JSON file with the credentials you downloaded in [Step 2](?tab=gcp#step-2-set-up-your-object-storage-account) and copy paste it in full into the field `Keyfile JSON`. The following screenshot shows how you would configure a connection with the ID `gcs_xcom_backend_conn`.
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +1. In the Airflow UI go to **Admin** -> **Connections** and create a new a connection (**+**) with the Connection Type `Azure Blob Storage`. Provide the full Blob SAS URL to the `SAS Token` field. Th
Same edits here as in GCP

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +
```suggestion
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +In your Astro project's `.env` file set the following environment variables. You may need to adjust your `MINIO_IP` if you have chosen a custom API port.
```suggestion
In your Astro project's `.env` file set the following environment variables. You may need to adjust your `MINIO_IP` if you have a custom API port.
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +To give Airflow access to your MinIO bucket you will need to use the credentials created in [Step 2](#step-2-set-up-your-object-storage-account).
```suggestion
To give Airflow access to your MinIO bucket you will need to use the credentials created in [Step 2](?tab=local#step-2-set-up-your-object-storage-account). 
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +    groupId= "github-actions-image-only-deploys"
```suggestion
    groupId= "step-4-define-a-custom-xcom-class-using-json-serialization"
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +
```suggestion
```
Repeat of step 5?

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +:::
```suggestion
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +
```suggestion

    If you use Astro, set the this environment variable in your Deployment instead. See [Environment variables](https://docs.astronomer.io/astro/environment-variables).

```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +    groupId= "github-actions-image-only-deploys"
```suggestion
    groupId= "step-5-create-and-run-your-dag-to-generate-xcoms"
```

2023-01-12 15:13 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +In this tutorial we've shown how to add custom logic to the `.serialize_value()` and  `.deserialize_value()` methods. If you want to further expand the functionality for your custom XCom backend, you
```suggestion
In this tutorial, you added custom logic to the `.serialize_value()` and  `.deserialize_value()` methods. If you want to further customize the functionality for your custom XCom backend, you can override methods of the [XCom module](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/xcom/index.html) ([source code](https://github.com/apache/airflow/blob/main/airflow/models/xcom.py)). 
```

2023-01-13 17:32 UTC, merged