Updating 0.28 to correctly reflect k8s version supports
astronomer/docs pull request #1672
Opened 2022-12-21 18:28 UTC by rbankston

fixes https://github.com/astronomer/docs/issues/1671

Updating version 0.28 supported Kubernetes version

2023-01-03 12:27 UTC, jwitz requested changes
Thanks for bringing this up @rbankston . I'm a little worried that this could open the gates up to documenting patch-level compatibility across all contexts. According to our versioning and lifecycle policy, "For each major.minor pair, only the latest patch is supported at any given time." Because of this, I don't think users should have to worry about pre-latest patch behavior, as our first recommendation will always be to upgrade to the latest patch version. 

(The documented Kubernetes deprecations are somewhat an exception to this rule, as it's unexpected for that level of support to be deprecated in a patch version.)

In my opinion, having these compatibilities documented in the 0.28 release notes is enough. I noticed that we only ever had a release note for 1.22 support, so I've hotfixed that to include 1.21 and 1.23. Does that sound good to you?

2023-01-11 18:24 UTC, rbankston commented
My concern with adding additional versions to the compatibily matrix that occurred in a later patch version is a customer who is on 0.28.1 and seeing that 0.28 is compatible with k8s 1.22 will proceed to upgrade and need manual intervention for deployments to work again

2023-02-22 14:08 UTC, kwcanuck commented
@jwitz should this issue be closed? If not, what needs to be done to move it forward?

2023-02-22 14:55 UTC, jwitz approved these changes

2023-02-22 14:57 UTC, merged