Snowflake Integration update
astronomer/docs pull request #1680
Opened 2022-12-29 13:14 UTC by TJaniF

Issue: #1633 

- Changes the Integration to fit the tutorial format more closely.

2022-12-29 18:02 UTC, kentdanas requested changes
Looks great! Requesting changes to add a few additional steps in the tutorial part to highlight data quality and async functionality a bit more. Otherwise just minor edits.

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    The DAG accomplishes the following steps:
```suggestion
    The DAG completes the following steps:
```

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    - Creating three tables simultaneously using the [SnowflakeOperator](https://registry.astronomer.io/providers/snowflake/modules/snowflakeoperator).
```suggestion
    - Creates three tables simultaneously using the [SnowflakeOperator](https://registry.astronomer.io/providers/snowflake/modules/snowflakeoperator). 
```

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    - Loading data into two of the tables that were created using the [SnowflakeOperatorAsync](https://registry.astronomer.io/providers/astronomer-providers/modules/snowflakeoperatorasync) a deferrab
```suggestion
    - Loads data into two of the tables that were created using the [SnowflakeOperatorAsync](https://registry.astronomer.io/providers/astronomer-providers/modules/snowflakeoperatorasync) a deferrable version of the SnowflakeOperator. In order to be able to use deferrable operators you need to have a triggerer component running in your Airflow environment, which is configured automatically if you are using the Astro CLI. Learn more about deferrable operators in our [Deferrable operators guide](deferrable-operators.md).
```
Can move the deferrable notes into the separate step below.

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    - Running data quality checks on the data to ensure that no erroneous data is moved to production. These checks are structured with [task groups](task-groups.md) that include column checks using
```suggestion
    - Runs data quality checks on the data to ensure that no erroneous data is moved to production. These checks are structured with [task groups](task-groups.md) that include column checks using the [SQLColumnCheckOperator](https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator) and table checks using the [SQLTableCheckOperator](https://registry.astronomer.io/providers/common-sql/modules/sqltablecheckoperator).
```

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    - Copying data into the production table using the SnowflakeOperatorAsync.
```suggestion
    - Copies data into the production table using the SnowflakeOperatorAsync.
```

2022-12-29 18:02 UTC, kentdanas commented on learn/airflow-snowflake.md
> +    - Deleting the tables to clean up the example.
```suggestion
    - Deletes the tables to clean up the example.
```

2023-01-03 07:57 UTC, TJaniF reviewed
Thank you! @kentdanas :) 
I added the additional steps as we discussed. @jwitz I think this one is ready for your review :)

2023-01-03 18:00 UTC, kentdanas commented on learn/airflow-snowflake.md
> +Using deferrable operators from the Astronomer providers package is easy, you simply have to switch out the operator class. All parameters stay the same.
Link to the astro provider repo here?

2023-01-03 18:00 UTC, kentdanas commented on learn/airflow-snowflake.md
> +1. Add the following import statement to your DAG importing the SnowflakeOperatorAsync:
```suggestion
1. Add the following statement to your DAG to import the SnowflakeOperatorAsync:
```

2023-01-03 18:01 UTC, kentdanas commented on learn/airflow-snowflake.md
> +2. Switch out the operator used in the `load_forestfire_data` and `load_cost_data` task by replacing `SnowflakeOperator` with `SnowflakeOperatorAsync`:
```suggestion
2. Switch out the operators used in the `load_forestfire_data` and `load_cost_data` tasks by replacing `SnowflakeOperator` with `SnowflakeOperatorAsync`:
```

2023-01-03 18:01 UTC, kentdanas commented on learn/airflow-snowflake.md
> +3. Run your DAG and observe how the two load tasks go into a deferred state (purple border) before being executed.
```suggestion
3. Run your DAG and observe how the two load tasks go into a deferred state (purple border) before being completed.
```

2023-01-05 16:02 UTC, jwitz requested changes
I like the new structure of this tutorial @TJaniF ! Requesting changes because I think we can provide more information about the "why" for this DAG. Why did we structure it the way we did, why did we use certain operators, and what's the best way to organize your Astro project? Left some comments elaborating on this throughout.

2023-01-05 16:02 UTC, jwitz commented on learn/airflow-snowflake.md
> +This section provides additional information on orchestrating actions in Snowflake with Airflow.
I feel like "How it works" is a bit of a stretch here based on the content, as the above DAG is not referenced. I'm happy to not include a "How it works" section if the DAG is straightforward enough

2023-01-11 16:22 UTC, TJaniF reviewed
Thank you @jwitz and @kentdanas ! I accepted almost all suggestions and added a few comments. :)

2023-01-11 16:29 UTC, kentdanas commented on learn/airflow-snowflake.md
> +This section provides additional information on orchestrating actions in Snowflake with Airflow.
We still want to include the additional information here - it was part of the original guide intentionally to highlight the benefits of using Snowflake with Airflow, but I don't think it really makes sense to pull it out as a separate concept guide given how specific it is. We don't need to call it "How it works" though - I'd be fine with "Additional information" or maybe something like "More on the Airflow Snowflake integration"...

2023-01-17 10:50 UTC, jwitz commented on learn/airflow-snowflake.md
> +Additionally, the [How it works](#how-it-works) sections offers further information on:
Good call! Missed that, updated the suggestion

2023-01-17 10:51 UTC, jwitz commented on learn/airflow-snowflake.md
> +    The `chain()` method at the end of the DAG sets the dependencies. This method is commonly used over bitshift operators (`>>`) to make the dependency related code of DAGs with a lot of tasks easie
```suggestion
    The `chain()` method at the end of the DAG sets the dependencies. This method is commonly used over bitshift operators (`>>`) to make it easier to read dependencies between many tasks.
```

2023-01-17 10:54 UTC, jwitz commented on learn/airflow-snowflake.md
> +The `complex_snowflake_example` DAG runs several queries against the same Snowflake database in parallel. While some queries, like the ones creating tables, run quickly, larger transformation or load
```suggestion
The `complex_snowflake_example` DAG runs several queries against the same Snowflake database in parallel. While some queries, like the ones creating tables, run quickly, larger transformation or loading queries might take longer to complete. These queries are a great use case for the deferrable version of the SnowflakeOperator, the [SnowflakeOperatorAsync](https://registry.astronomer.io/providers/astronomer-providers/modules/snowflakeoperatorasync). Deferrable operators use the triggerer component in your Airflow environment, which is configured automatically with the Astro CLI, to release their worker slot while they wait for the task to be completed. This allows you to use your Airflow resources much more efficiently in production. Learn more about deferrable operators in our [Deferrable operators guide](deferrable-operators.md).
```

2023-01-17 10:56 UTC, jwitz approved these changes
LGTM! Nice edits

2023-01-17 11:36 UTC, TJaniF commented on learn/airflow-snowflake.md
> +Additionally, [How it works](#how-it-works) offers further information on:
```suggestion
Additionally, [More on the Airflow Snowflake integration](#more-on-the-airflow-snowflake-integration) offers further information on:
```

2023-01-17 11:52 UTC, TJaniF commented on learn/airflow-snowflake.md
> +    - Account: Your snowflake account in the format `xz12345`.
```suggestion
    - Account: Your Snowflake account in the format `xz12345`.
```

2023-01-17 11:53 UTC, TJaniF commented on learn/airflow-snowflake.md
> +2. Create a new connection named `snowflake_default` and choose the `snowflake` connection type. Enter the following information:
```suggestion
2. Create a new connection named `snowflake_default` and choose the `Snowflake` connection type. Enter the following information:
```

2023-01-17 11:53 UTC, TJaniF commented on learn/airflow-snowflake.md
> +    - Account: Your Snowflake account in the format `xz12345`.
```suggestion
    - Account: Your Snowflake account in the format `xy12345`.
```

2023-01-17 11:55 UTC, TJaniF commented on learn/airflow-snowflake.md
> +        """
```suggestion
    ) as dag:
    
        """
```

2023-01-17 11:56 UTC, TJaniF commented on learn/airflow-snowflake.md
> +        """
```suggestion
    with DAG(
        "complex_snowflake_example",
        description="""
            Example DAG showcasing loading, transforming, 
            and data quality checking with multiple datasets in Snowflake.
        """,
        doc_md=__doc__,
        start_date=datetime(2022, 12, 1),
        schedule=None,
        # defining the directory where SQL templates are stored
        template_searchpath="/usr/local/airflow/include/sql/",
        catchup=False
    ) as dag:
    
        """
```

2023-01-17 11:59 UTC, TJaniF commented on learn/airflow-snowflake.md
>          )
```suggestion
    from astronomer.providers.snowflake.operators.snowflake import (
        SnowflakeOperatorAsync
    )
```

2023-01-17 12:00 UTC, TJaniF commented on learn/airflow-snowflake.md
>          )
```suggestion
    load_forestfire_data = SnowflakeOperatorAsync(  # changed operator name
        task_id="load_forestfire_data",
        sql=sql_stmts.load_forestfire_data,
        params={"table_name": SNOWFLAKE_FORESTFIRE_TABLE}
    )
```

2023-01-17 12:00 UTC, TJaniF commented on learn/airflow-snowflake.md
>          )
```suggestion
    load_cost_data = SnowflakeOperatorAsync( # changed operator name
        task_id="load_cost_data",
        sql=sql_stmts.load_cost_data,
        params={"table_name": SNOWFLAKE_COST_TABLE}
    )
```

2023-01-17 12:02 UTC, TJaniF commented on learn/airflow-snowflake.md
> +    load_cost_data = SnowflakeOperatorAsync( # changed operator name
```suggestion
    load_cost_data = SnowflakeOperatorAsync(  # changed operator name
```

2023-01-17 12:02 UTC, TJaniF commented on learn/airflow-snowflake.md
> +- [S3ToSnowflakeOperator](https://registry.astronomer.io/providers/snowflake/modules/s3tosnowflakeoperator): Executes an COPY command to load files from s3 to Snowflake.
```suggestion
- [S3ToSnowflakeOperator](https://registry.astronomer.io/providers/snowflake/modules/s3tosnowflakeoperator): Executes a COPY command to load files from s3 to Snowflake.
```

2023-01-17 12:28 UTC, merged