Openlineage concept updates and new Marquez tutorial
astronomer/docs pull request #1687
Opened 2022-12-30 00:09 UTC by kentdanas

Broke the OpenLineage guide into 2 parts -
- an OL concept guide that will live under 'Airflow guides'
- a step by step tutorial on using Marquez that will live under 'tutorials'

Still need to update the lineage UI screenshots from Astro in the OL concept guide (will do that next week using the same ones Tamara generates for the snowflake guide update), but otherwise @jwitz this is ready for your review. 

One other thought - I'm not totally convinced on the current titles/sidebar labels for both of these. Open to suggestions there.

2022-12-30 17:00 UTC, TJaniF approved these changes
LGTM, just added a few comments and some formatting suggestions :)

2022-12-30 17:00 UTC, TJaniF commented on learn/airflow-openlineage.md
>  For Astronomer customers using [Astro](https://www.astronomer.io/product/), OpenLineage integration is built in. The **Lineage** tab in the Astronomer UI provides multiple pages that can help you tro
```suggestion
For Astronomer customers using [Astro](https://www.astronomer.io/product/), OpenLineage integration is built in. The **Lineage** tab in the Astronomer UI provides multiple pages that can help you troubleshoot issues with your data pipelines and understand the movement of data across your organization. For more on lineage capabilities with Astro, see [View lineage on Astro](https://docs.astronomer.io/astro/data-lineage) or [contact Astronomer](https://www.astronomer.io/openlineage). 
```

2022-12-30 17:00 UTC, TJaniF commented on learn/airflow-openlineage.md
> +- Only some operators have bundled extractors (needed to collect lineage data out of the box). To get lineage data from other operators, you can create your own custom extractor.
```suggestion
- Only some operators have bundled extractors (needed to collect lineage data out of the box). To get lineage data from other operators, you can create your own [custom extractor](https://openlineage.io/blog/extractors/).
```

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +In this tutorial, you'll run OpenLineage with Airflow locally using Marquez as a lineage front end. You'll then generate and interpret lineage data using two DAGs that processes data in Postgres.
```suggestion
In this tutorial, you'll run OpenLineage with Airflow locally using Marquez as a lineage front end. You'll then generate and interpret lineage data using two DAGs that process data in Postgres.
```

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +1. Using `psql`, create a local Postgres database in the same container as the Airflow metastore:
Silly question but is "Airflow metastore" the same as the Airflow metadata database?

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +    '''
```suggestion
    create_table_query= '''
        CREATE TABLE IF NOT EXISTS animal_adoptions_combined (
            date DATE,
            type VARCHAR,
            name VARCHAR,
            age INTEGER
            );
    '''

    combine_data_query= '''
        INSERT INTO animal_adoptions_combined (date, type, name, age) 
            SELECT * 
            FROM adoption_center_1
            UNION 
            SELECT *
            FROM adoption_center_2;
    '''
```

Just a formatting suggestion so there is no sidescroll on the code block :)

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +            ):
```suggestion
    with DAG(
        'lineage-combine-postgres',
        start_date=datetime(2022, 12, 1),
        max_active_runs=1,
        schedule='@daily',
        default_args = {
            'retries': 1,
            'retry_delay': timedelta(minutes=1)
        },
        catchup=False
    ):
```

(was overindented)

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +    '''
```suggestion
    aggregate_reporting_query = '''
        INSERT INTO adoption_reporting_long (date, type, number)
        SELECT c.date, c.type, COUNT(c.type)
        FROM animal_adoptions_combined c
        GROUP BY date, type;
    '''
```

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +            ):
```suggestion
    with DAG(
        'lineage-reporting-postgres',
        start_date=datetime(2020, 6, 1),
        max_active_runs=1,
        schedule='@daily',
        default_args={
            'retries': 1,
            'retry_delay': timedelta(minutes=1)
        },
        catchup=False
    ):
```

2022-12-30 17:00 UTC, TJaniF commented on learn/marquez.md
> +            sql='CREATE TABLE IF NOT EXISTS adoption_reporting_long (date DATE, type VARCHAR, number INTEGER);',
```suggestion
            sql='''
                CREATE TABLE IF NOT EXISTS adoption_reporting_long (
                    date DATE,
                    type VARCHAR,
                    number INTEGER
                    );
            ''',
```

2023-01-03 15:51 UTC, kentdanas commented on learn/marquez.md
> +1. Using `psql`, create a local Postgres database in the same container as the Airflow metastore:
Yep! Generally those terms are used interchangeably

2023-01-11 19:15 UTC, kentdanas commented
@denimalpaca you mind taking a quick look at this since this is more your area of expertise? Not too many changes from the original concept doc other than removing some outdated limitations and breaking out the Marquez tutorial, but would love another set of eyes in case I missed anything.

2023-01-11 20:06 UTC, denimalpaca commented
> @denimalpaca you mind taking a quick look at this since this is more your area of expertise? Not too many changes from the original concept doc other than removing some outdated limitations and breaking out the Marquez tutorial, but would love another set of eyes in case I missed anything since the original doc was written a year ago.

I can take a look but full disclosure: I have yet to use Marquez...

2023-01-11 21:09 UTC, denimalpaca requested changes

2023-01-11 21:37 UTC, denimalpaca commented
Side note: Doing this tutorial broke my local Airflow deployment with `astro dev start`. I haven't quite figured out why. I was using a repo where I had _just_ done a successful local deploy, then when I ran Marquez and updated `.astro/config`, the webserver no longer worked, with SqlAlchemy complaining that it could not map hostname "postgres". Looking into this to see if it's actually an issue with these set-up steps or not.

2023-01-12 13:14 UTC, jwitz approved these changes
LGTM! Just some minor suggestions and questions throughout

2023-01-12 13:14 UTC, jwitz commented on learn/airflow-openlineage.md
> +If you are working with open source tools, you can run OpenLineage with Airflow locally using Marquez as the lineage front end. See our [Integrate OpenLineage and Airflow locally with Marquez](marque
```suggestion
If you are working with open source tools, you can run OpenLineage with Airflow locally using Marquez as the lineage front end. See [Integrate OpenLineage and Airflow locally with Marquez](marquez.md) tutorial to get started.
```

2023-01-12 13:14 UTC, jwitz commented on learn/marquez.md
> +    - The four jobs (tasks) from your DAGs that create new tables and result in new combined datasets: `combine` and `reporting`;
```suggestion
    - Two origin datasets that are used to populate the combined data table.
    - The four jobs (tasks) from your DAGs that create new tables and result in new combined datasets: `combine` and `reporting`.
```

2023-01-12 13:15 UTC, jwitz commented on learn/marquez.md
> +title: "Integrate OpenLineage and Airflow locally with Marquez"
```suggestion
title: "Integrate OpenLineage and Airflow with Marquez"
```

2023-01-12 19:47 UTC, kentdanas commented on learn/marquez.md
> +    ```
Interesting, I didn't know you could do this.

2023-01-12 19:51 UTC, kentdanas commented on learn/marquez.md
> +- The [Astro CLI](https://docs.astronomer.io/astro/cli/overview).
Good call - added this as PostgreSQL because there isn't a separate psql download. For Mac users Postgres is already installed, but not sure about other OS's so we should definitely add it here.

2023-01-12 19:55 UTC, kentdanas commented on learn/marquez.md
> +        create_table = PostgresOperator(
Yeah for sure. Added a note about the OL extractor for postgres operator to be more explicit. This is also covered in depth in the OL concept doc, which is listed as assumed knowledge, so hopefully that + this new sentence is enough to clarify.

2023-01-19 18:21 UTC, merged