Add docs about how to use astro sql project with astro cli project
astronomer/docs pull request #1692
Opened 2023-01-02 11:33 UTC by feluelle

closes https://github.com/astronomer/astro-sdk/issues/1315

2023-01-02 11:49 UTC, feluelle commented on astro/cli/sql-cli.md
> +3. Run `astro flow run example_basic_transform --project-dir <your-project-dir>` to run a basic example which accesses the `data_dir` and also exports the generated dags to the configured `dags_folde
```suggestion
3. Run `astro flow run example_basic_transform --project-dir <your-project-dir>` to run a basic example which accesses the `data_dir` and also exports the generated DAG to the configured `dags_folder`.

Note that if you also want to run the generated DAG in Airflow, you need to create the connections manually, e.g. via the Airflow UI. In this example you need to add `sqlite_conn`, with connection type `sqlite` and the `host` needs to be `include/imdb.db`.
```

2023-01-03 10:45 UTC, jwitz commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
Could you also set this in individual environment configurations? And if so, would that be a more common programming pattern?

2023-01-03 10:46 UTC, jwitz commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
Also, how does the SQL CLI manage relative filepaths? Can we provide an example for a potential filepath? 

"For example, if your Astro project is stored in the same directory as your SQL project, you would specify the following filepath:"

2023-01-03 10:46 UTC, jwitz commented on astro/cli/sql-cli.md
> +2. To export a DAG from an existing SQL project, copy the contents your SQL project `data` folder into your Astro project `include` folder. To export a DAG from a new SQL CLI project, run `astro flow
Should we mention `--airflow-dags-folder` here as well?

2023-01-03 10:47 UTC, jwitz requested changes
Hi @feluelle, thank you for this contribution! I adjusted the language slightly and have a few technical questions before we merge this, but overall looks great.

2023-01-03 11:04 UTC, feluelle commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
Currently it is not possible. If this becomes a requested feature, we can think about adding it.

2023-01-03 11:06 UTC, feluelle commented on astro/cli/sql-cli.md
> +2. To export a DAG from an existing SQL project, copy the contents your SQL project `data` folder into your Astro project `include` folder. To export a DAG from a new SQL CLI project, run `astro flow
Yeah we could.

2023-01-03 11:16 UTC, feluelle commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
* By default, the file path will be resolved to absolute on init using the project directory
* If you set the directory via the cli option it will be resolved to absolute using the current directory
* If you set the directory in the yaml it needs to be an absolute path

2023-01-03 11:18 UTC, feluelle commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
This is what I just discovered. 😅 It definitely needs some improvements and clarity in the docs.

2023-01-04 12:02 UTC, jwitz commented on astro/cli/sql-cli.md
> +1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the location of your Astro project `dags` folder. Set `data_dir` to the location of your Astro project `include` folder.
```suggestion
1. In the `config/global.yml` file of your SQL project, set `dags_folder` to the absolute file path of your Astro project `dags` folder. Set `data_dir` to the absolute file path of your Astro project `include` folder.
```

2023-01-04 12:03 UTC, jwitz commented on astro/cli/sql-cli.md
> +    astro flow run <your-workflow> --project-dir <your-project-dir>`
```suggestion
    astro flow run <your-workflow> --project-dir <absolute-filepath-to-astro-project-dir>`
```

2023-01-04 12:04 UTC, jwitz approved these changes
Thanks for the clarity @feluelle , this now looks good to me!

2023-01-04 12:04 UTC, feluelle commented on astro/cli/sql-cli.md
> +    astro flow run <your-workflow> --project-dir <your-project-dir>`
@jwitz this can also be relative.

2023-01-04 12:05 UTC, feluelle commented on astro/cli/sql-cli.md
> +    astro flow run <your-workflow> --project-dir <your-project-dir>`
The project dir will resolved to absolute using the current directory.

2023-01-04 13:39 UTC, jwitz commented on astro/cli/sql-cli.md
> +Export SQL a workflow to an Astro project to test the workflow as a DAG and view execution information in the Airflow UI.
```suggestion
Export a SQL workflow to an Astro project to locally test the workflow as a DAG and view execution information in the Airflow UI. 
```

2023-01-04 13:41 UTC, jwitz commented on astro/cli/sql-cli.md
> +To connect to your configured databases from the Astro CLI, you must manually reconfigure any connections from your SQL project in Airflow. See [Manage connections in Apache Airflow](https://docs.ast
```suggestion
If you configured databases in your SQL CLI project, you must manually reconfigure these databases in your Astro project through the Airflow UI. See [Manage connections in Apache Airflow](https://docs.astronomer.io/learn/connections).
```

2023-01-04 14:31 UTC, jwitz commented on astro/cli/sql-cli.md
> +    astro flow run <your-workflow> --project-dir <absolute-filepath-to-astro-project-directory>`
```suggestion
    astro flow run <your-workflow> --project-dir <filepath-to-astro-project-directory>`
```

2023-01-05 00:57 UTC, tatiana commented on astro/cli/sql-cli.md
> +2. To export a DAG from an existing SQL project, copy the contents your SQL project `data` folder into your Astro project `include` folder. To export a DAG from a new SQL CLI project, run `astro flow
@feluelle could you confirm the version of the SQL CLI & Astro CLI in which we have we made the `--data-dir` available? We may only be able to publish this doc upon a stable release of the Astro CLI with the change.

2023-01-05 08:58 UTC, feluelle commented on astro/cli/sql-cli.md
> +2. To export a DAG from an existing SQL project, copy the contents your SQL project `data` folder into your Astro project `include` folder. To export a DAG from a new SQL CLI project, run `astro flow
* SQL CLI 0.3.0a0
* Astro CLI 1.9.0 (pre-release), but we are planning to remove this from this release

2023-01-06 14:40 UTC, merged