Add CI/CD narrative
astronomer/docs pull request #1697
Opened 2023-01-03 20:07 UTC by sunkickr

new CI/CD narrative doc that guides readers through options to think about while setting up CI/CD

2023-01-05 14:09 UTC, jwitz commented on astro/how-to-ci-cd.md
> +Recently we have introduced the ability to deploy DAG code without creating a docker image with `astro deploy --dags`. We recommend that you configure your CI/CD pipelines to use this feature. This m
```suggestion
## Create a CI/CD pipeline

The general process for creating an Astro CI/CD template is to:

- Decide on a CI/CD strategy based on this document and your team's needs.
- Set up your repositories and permissions based on your CI/CD strategy.
- Add one of Astronomer's [CI/CD templates](ci-cd.md) to your repositories, or use the Astronomer-maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).
- Modify the template or GitHub action as needed for your use case. 

If you use GitHub, Astronomer strongly recommends using the Astronomer-maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-action).
```

2023-01-05 14:22 UTC, jwitz commented on astro/how-to-ci-cd.md
> +The [custom image deploy templates](https://docs.astronomer.io/astro/ci-cd?tab=custom#github-actions-dag-based-deploy) shows how to create a CI/CD pipeline that deploys a custom image during image de
```suggestion
```

2023-01-05 14:22 UTC, jwitz commented on astro/how-to-ci-cd.md
> +The [custom image deploy templates](https://docs.astronomer.io/astro/ci-cd?tab=custom#github-actions-dag-based-deploy) shows how to create a CI/CD pipeline that deploys a custom image during image de
Let's save this information for the templates doc

2023-01-05 14:23 UTC, jwitz commented on astro/how-to-ci-cd.md
> +## S3 Bucket + Repository Project
Should we publish this before we have a template/ lambda function for folks to use?

2023-01-05 14:23 UTC, jwitz commented on astro/how-to-ci-cd.md
> +Now you should know the basics of creating a CI/CD pipeline for an Astronomer Deployment. If you’d like help customizing your CI/CD pipelines for your specific use case, feel free to reach out to Ast
```suggestion
```
This is all testing that can be done locally as well, I don't think we need to mention it within the context of CI/CD.

2023-01-05 14:24 UTC, jwitz commented on sidebarsAstro.js
> +      items: ["deploy-code", "ci-cd", "how-to-ci-cd"],
```suggestion
      items: ["deploy-code", "set-up-ci-cd", "ci-cd", ],
```

2023-01-10 04:31 UTC, paolaperaza commented
@jwitz @sunkickr We'll have to have more convos here, but for now as I was looking at this:

- @jwitz I committed all of your suggestions, as I largely agreed with all of them
- I separated our previous equivalents of `single-branch` and `multi-branch` into 2 distinct sections. These are _sort of the same_ but I think the most common places to start. I verified that we've got enough Orgs with only 1 Deployment to make it worth calling out
- Also -- @jwitz I couldn't see your mermaid diagrams live on preview. 

I didn't touch the final 2 sections, but:
- Let's make sure we're crisper about benefits and limitations
- @sunkickr I feel like we could expand _slightly_ to better describe the development flow

Happy to sit down and chat through this one after the release this week

2023-01-10 10:32 UTC, jwitz commented on astro/how-to-ci-cd.md
> +``mermaid
```suggestion
```mermaid
```

2023-01-10 10:32 UTC, jwitz commented on astro/how-to-ci-cd.md
> +``
```suggestion
```
```

2023-01-10 13:07 UTC, jwitz commented on astro/how-to-ci-cd.md
> +Now you should know the basics of creating a CI/CD pipeline for an Astronomer Deployment. If you’d like help customizing your CI/CD pipelines for your specific use case, feel free to reach out to Ast
```suggestion
```

2023-01-10 13:08 UTC, jwitz commented on astro/how-to-ci-cd.md
> +Astronomer also provides tooling to run [custom Pytests](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#unit-tests) on your DAG code, python methods, and custom operators.
```suggestion
Astronomer also provides tooling to run [custom Pytests](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#unit-tests) on your DAG code, python methods, and custom operators. The [Astro CLI](https://docs.astronomer.io/astro/cli/astro-dev-pytest) and [Deploy-Action](https://github.com/astronomer/deploy-action#example-using-pytests) will use docker to spin up a docker container that has a similar environment to your deployment and executes your Pytests. Astronomer recommends that you pytest any custom python code you use in your DAGs.
```

2023-01-10 17:43 UTC, jwitz commented on astro/how-to-ci-cd.md
> +## Multiple environments
```suggestion
### Multiple environments
```

2023-01-10 23:18 UTC, paolaperaza requested changes
Forgot to hit submit on previous comments -- might no longer be relevant, but hitting `Request changes` for now

2023-01-11 10:44 UTC, jwitz commented on astro/ci-cd.md
> +sidebar_label: 'CI/CD Templates'
Seems redundant to me

2023-01-11 12:36 UTC, jwitz commented
@paolaperaza I've made some significant changes to the doc that need review:

- The strategy step is now framed as two key decisions: how do you structure your branches, and how do you structure your repositories.
- Added and adjusted a few mermaid diagrams
- Removed some information from the CI/CD templates doc, but overall kept content there the same due to all of the information on specific scripts.

2023-01-11 12:39 UTC, kwcanuck commented on astro/ci-cd.md
> +Use the Astronomer CI/CD templates to automate deploying code to Astro with popular CI/CD management tools, including GitHub Actions and Circle CI. To decide which template is right for you, see [Set
```suggestion
Use the Astronomer CI/CD templates to automate code deployment to Astro with popular CI/CD management tools, including GitHub Actions and Circle CI. To decide which template is right for you, see [Set up CI/CD](set-up-ci-cd.md).
```

2023-01-11 12:42 UTC, kwcanuck commented on astro/ci-cd.md
>  Templates allow you to easily configure automated workflows using popular CI/CD tools. Each template can be implemented as-is to produce a simple CI/CD pipeline. Astronomer recommends reconfiguring t
```suggestion
Templates allow you to configure automated workflows using popular CI/CD tools. Each template can be implemented without changes to produce a CI/CD pipeline. However, Astronomer recommends reconfiguring the templates to work with your own directory structures, tools, and processes.
```
![image](https://user-images.githubusercontent.com/104205257/211808930-ed8f26ab-d4e8-429d-a7f4-707171ff4a0d.png)

2023-01-11 12:42 UTC, kwcanuck commented on astro/ci-cd.md
> +There are two workflow types, image-only workflows and DAG-based workflows, which are described in detail below. The following templates are available for each workflow type:
```suggestion
There are two workflow types, image-only workflows and DAG-based workflows. The following templates are available for each workflow type: 
```
![image](https://user-images.githubusercontent.com/104205257/211809076-7fc429ee-9c2b-4dde-9ea8-b7289766832a.png)

2023-01-11 12:44 UTC, kwcanuck commented on astro/ci-cd.md
>  The image-only workflow builds a Docker image and pushes it to Astro whenever you update any file in your Astro project. This type of template is simple to set up and works well for development workf
```suggestion
The image-only workflow builds a Docker image and pushes it to Astro whenever you update any file in your Astro project. This type of template works well for development workflows that include complex Docker customization or logic.
```
See previous comment about the use of _simple_.

2023-01-11 12:45 UTC, kwcanuck commented on astro/ci-cd.md
>  The DAG-based workflow uses the `--dags` flag in the Astro CLI to enable a faster way to push DAG changes to Astro. These CI/CD pipelines deploy your DAGs only when files in your `dags` folder are mo
```suggestion
The DAG-based workflow uses the `--dags` flag in the Astro CLI to push DAG changes to Astro. These CI/CD pipelines deploy your DAGs only when files in your `dags` folder are modified, and they deploy the rest of your Astro project as a Docker image when other files or directories are modified. For more information about the benefits of this workflow, see [Deploy DAGs only](deploy-code.md#deploy-dags-only).
```

2023-01-11 12:49 UTC, kwcanuck commented on astro/ci-cd.md
> +The following templates use Astronomer's [Deploy Action](https://github.com/astronomer/deploy-action) to deploy code to Astronomer. The Deploy Action is the easiest way to create CI/CD pipelines for
```suggestion
The following templates use [Deploy Action](https://github.com/astronomer/deploy-action) to deploy code to Astronomer.  See the [Deploy Action README](https://github.com/astronomer/deploy-action#readme) to learn more about using and customizing this action.
```

2023-01-11 12:52 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +When you create a CI/CD pipeline, your first decision point whether to deploy one or multiple project branches to Astro through CI/CD.
```suggestion
When you create a CI/CD pipeline, you first must determine if you want to deploy one or multiple project branches to Astro through CI/CD.
```

2023-01-11 12:53 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +Using multi-repository CI/CD strategy, you can manage your DAGs in one repository and Astro project settings in another. Use this strategy to ensure that DAG authors and data operators have access on
```suggestion
Using a multi-repository CI/CD strategy, you can manage your DAGs in one repository and Astro project settings in another. Use this strategy to ensure that DAG authors and data operators have access only to their own files. 
```

2023-01-11 12:54 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +Continuous Integration and Continuous Delivery (CI/CD) pipelines are programmatic workflows that automate key parts of the software development lifecycle, including code changes, builds, and testing.
```suggestion
Continuous Integration and Continuous Delivery (CI/CD) pipelines are programmatic workflows that automate key parts of the software development lifecycle, including code changes, builds, and testing. CI/CD helps your organization develop faster, more securely, and more reliably.
```

2023-01-11 12:55 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Determine what kind of Deployment and CI/CD system you want your team to use.
```suggestion
- Determine what kind of Deployment and CI/CD strategy you want your organization to use.
```

2023-01-11 12:56 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +Then, see [CI/CD templates](ci-cd.md) for setup steps and examples.
```suggestion
When you're ready to implement your CI/CD strategy, see [CI/CD templates](ci-cd.md) for setup steps and examples.
```

2023-01-11 12:59 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Enforce automated testing, which increases code quality and allows your team to respond quickly in case of an error or failure.
```suggestion
- Enforce automated testing, which increases code quality and allows your team to respond quickly in case of an error or a failure.
```

2023-01-11 13:00 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +When developing a strategy, keep the size of your data team in mind while answering the following questions:
```suggestion
When developing a strategy, keep the size of your data team in mind while answering the following questions:
```
It appears you're using _strategy_ and _workflow_ interchangeably.  Choose one term and use it consistently.

2023-01-11 13:01 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- How many branches of a project do you want to host on Astro? Do you need to deploy a single production branch to a Deployment, or do you also need to deploy a development branch?
```suggestion
- How many branches of a project do you want to host on Astro? 
- Do you need to deploy a single production branch to a Deployment, or do you also need to deploy a development branch?
```

2023-01-11 13:03 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +### Single branch vs. multiple branch repositories
```suggestion
### Single branch versus multiple branch repositories
```
![image](https://user-images.githubusercontent.com/104205257/211813223-1237f169-2293-41b9-935a-8449eb7f8d42.png)

2023-01-11 13:04 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +The easiest and most cost-effective way to get started with CI/CD on Astro is to maintain a single Git repository that corresponds to a single Astro project and Deployment.
```suggestion
The most cost-effective way to get started with CI/CD on Astro is to maintain a single Git repository that corresponds to a single Astro project and Deployment.
```

2023-01-11 13:05 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro project.
```suggestion
- One Astro project.
```

2023-01-11 13:06 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro project.
From our style guide:

_...spell out whole numbers from zero through nine, and use numerals for 10 or greater. Use commas in numbers with four or more digits. Use more than instead of over. Over is a spatial term._

2023-01-11 13:06 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro Workspace for your project.
```suggestion
- One Astro Workspace for your project.
```

2023-01-11 13:06 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro Deployment.
```suggestion
- One Astro Deployment.
```

2023-01-11 13:06 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 primary and permanent branch in your Git repository. Astronomer recommends `main`.
```suggestion
- One primary and permanent branch in your Git repository. Astronomer recommends `main`.
```

2023-01-11 13:08 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Create a new, short-lived branch in your Git repository with the change and open a Pull Request (PR) against the `main` branch for review.
```suggestion
- Create a new, temporary branch in your Git repository with the change and open a pull request against the `main` branch for review.
```

2023-01-11 13:09 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- When the PR is approved and merged to `main`, the change is automatically deployed to your Deployment on Astro.
```suggestion
- When the PR is approved and merged to the main branch, the change is automatically deployed to your Deployment on Astro.
```

2023-01-11 13:10 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +For small to medium-sized data teams running data pipelines in production, Astronomer recommends developing a CI/CD pipeline for multiple branches. With this method, you maintain 1 Git repository tha
```suggestion
For small to medium-sized data teams running data pipelines in production, Astronomer recommends developing a CI/CD pipeline for multiple branches. With this method, you maintain one Git repository that has permanent branches for different versions of your Astro project. You also have multiple Astro Deployments for each of your branches. If you work at a larger organization, you can adapt this method by creating a Workspace for each team or business use case.
```

2023-01-11 13:10 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro project.
```suggestion
- One Astro project.
```

2023-01-11 13:10 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- 1 Astro Workspace for your project.
```suggestion
- One Astro Workspace for your project.
```

2023-01-11 13:11 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- At least 2 primary branches in your Git repository that each represent an environment. Astronomer recommends `main` and `dev`.
```suggestion
- At least two primary branches in your Git repository that each represent an environment. Astronomer recommends naming the branches `main` and `dev`.
```

2023-01-11 13:14 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +One drawback to this strategy is that you must keep any local copies of the Astro project in sync with both repositories in order to test Deployment code locally. Your team members might have inconsi
```suggestion
One limitation of this strategy is that you must keep any local copies of the Astro project synchronized with both repositories in order to test Deployment code locally. Your team members might have inconsistencies in their local environments if they can't access code changes from other team members. Astronomer recommends setting up a `dev` Deployment where DAG authors can see and modify project configurations for testing purposes. 
```

2023-01-11 13:15 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +If you migrated to Astro from MWAA, this strategy is useful for maintaining a similar workflow for DAG authors. You can set up a Lambda function to push DAGs to your Astronomer Deployment whenever DA
```suggestion
If you migrated to Astro from Amazon Managed Workflows for Apache Airflow (MWAA), this strategy is useful for maintaining a similar workflow for DAG authors. You can set up a Lambda function to push DAGs to your Astronomer Deployment whenever DAG files are updated in your specific S3 bucket.
```

2023-01-11 13:16 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +The general process for creating an Astro CI/CD template is to:
```suggestion
The process for creating an Astro CI/CD template is:
```

2023-01-11 13:17 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Decide on a CI/CD strategy based on this document and your team's needs.
```suggestion
- Selecting a CI/CD strategy after reviewing this document and the requirements of your team.
```

2023-01-11 13:19 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Add one of Astronomer's [CI/CD templates](ci-cd.md) to your repositories, or use the Astronomer-maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).
```suggestion
- Adding an Astronomer [CI/CD template](ci-cd.md) to your repositories, or using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).
```

2023-01-11 13:20 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +If you use GitHub, Astronomer strongly recommends using the Astronomer-maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-ac
```suggestion
If you use GitHub, Astronomer recommends using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-action).
```

2023-01-11 13:20 UTC, kwcanuck approved these changes

2023-01-11 14:10 UTC, jwitz commented on astro/set-up-ci-cd.md
> +When you're ready to implement your CI/CD workflow, see [CI/CD templates](ci-cd.md) for setup steps and examples.
```suggestion
- Determine what kind of Deployment and CI/CD strategy you want your data team to use.

When you're ready to implement your CI/CD strategy, see [CI/CD templates](ci-cd.md) for setup steps and examples.
```

2023-01-11 14:10 UTC, jwitz commented on astro/set-up-ci-cd.md
> +When developing a strategy, keep the size of your data team in mind while answering the following questions:
```suggestion
When deciding on a strategy, keep the size of your data team in mind while answering the following questions:
```

2023-01-11 14:22 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +### Single repository vs. multiple repositories
```suggestion
### Single repository versus multiple repositories
```
From the Google developer documentation style guide:

![image](https://user-images.githubusercontent.com/104205257/211829749-b873535c-ce3c-4c57-a9fb-768849f26414.png)

If you don't want to follow the style guide, create a new heading. For example:

_Benefits of a single repository over multiple repositories_

2023-01-12 15:38 UTC, jwitz approved these changes

2023-01-12 16:57 UTC, dylanbstorey commented
This is stream of though as i'm going through this document. 

CI/CD is more than just a code based pipeline - it is a strategy that has to encompass:
- environment architecture
- change management 
- testing strategies
- integration methodologies
- acceptance 

I don't think we should discuss when to do certain activities based on team size. The requirements for CI/CD are generally around operational readiness and risk aversion - a team of 1 could find it self needing a much more rigorous CI/CD implementation than a team of 50 if the work they do is more critical to the business. 

This document seems to center on deployment and needs additional expansion on "integration": 

- more obvious/ practical examples how to make sure your environment is ready to use these different branches accordingly. (things like variable usage, environmental mutations via jinja, etc.) 

- should include a list of lower environments and what types of activities we suggest doing in them. (smoke tests, unit tests, integration tests, end to end, perf, QA, UAT etc.)

2023-01-12 20:01 UTC, sunkickr commented
@dylanbstorey I agree the difference between single-branch pipeline and multi-branch pipeline doesn't depend on team size but on how critical the pipelines are that being deployed. I guess it is more likely that larger teams will use multiple branches but it's not the main driver.

I had a section in here on testing but it was removed for a different doc. I guess this one is more focused on deployment that integration. I am currently exploring the best way to recommend our users to manage environments and share secrets across Astro and local deployments. This will probably entail integrating sops and a mechanism to push secrets to deployments into the CLI. We'll probable end up with a separate doc for this as well

2023-01-13 12:53 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +### Single repository vs. multiple repositories
@jwitz it appears this change hasn't been implemented. If we're deviating from the style guide, we should discuss it and then document the deviation in our style guide.

2023-01-19 13:56 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- Do you need to deploy a single production branch to a Deployment, or do you also need to deploy a development branch?
```suggestion
```

2023-01-19 13:58 UTC, jwitz commented on astro/set-up-ci-cd.md
> +### Single branch vs. multiple branch repositories
```suggestion
### Single environment versus multiple environment repositories
```

2023-01-19 14:00 UTC, jwitz commented on astro/set-up-ci-cd.md
> +When you create a CI/CD pipeline, you first must determine if you want to deploy one or multiple project branches to Astro through CI/CD.
```suggestion
When you create a CI/CD pipeline, you first must determine how many environments you need to test your DAGs in. Each environment requires its own GitHub branch and implementation in your CI/CD pipeline. 
```

2023-01-19 14:00 UTC, jwitz commented on astro/set-up-ci-cd.md
> +For small to medium-sized data teams running data pipelines in production, Astronomer recommends developing a CI/CD pipeline for multiple branches. With this method, you maintain one Git repository t
```suggestion
For small to medium-sized data teams running data pipelines in production, Astronomer recommends developing a CI/CD pipeline that supports multiple environments for running different versions of your project. With this method, you maintain one Git repository that has permanent branches for different versions of your Astro project. You also have multiple Astro Deployments for each of your branches. If you work at a larger organization, you can adapt this method by creating a Workspace for each team or business use case.
```

2023-01-19 14:02 UTC, jwitz commented on astro/set-up-ci-cd.md
> +The most cost-effective way to get started with CI/CD on Astro is to maintain a single Git repository that corresponds to a single Astro project and Deployment.
```suggestion
The most cost-effective way to get started with CI/CD on Astro is to maintain a single Git repository that corresponds to a single Astro project and Deployment. This solution is best for simple projects where you can tolerate testing and bug fixing in production.
```

2023-01-19 14:05 UTC, jwitz commented
@dylanbstorey Thank you for these great comments and insight. For this draft, I can act on your comments regarding branches vs. environments and data team size. Just added some suggestions that should help clarify these details for readers. 

Also agreed that we need more information on integration/ management across environments, but I think it makes sense to have that in a future PR after we've established some foundational knowledge and used this doc in the field a bit.

2023-02-07 05:32 UTC, paolaperaza reviewed
Couple final comments here @jwitz but this is looking good to me. Take a final pass and let's review one more time this week + merge?

Thank you for the patience, @fritz-astronomer !

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Astro supports deploying DAG code changes separately from project configuration changes. If multiple team members work on a single Astro project, decide whether you need multiple Git repositories to
```suggestion
On Astro, you can deploy DAG code changes separately from changes to the rest of your Astro project when [DAG-only deploys](deploy-code.md#deploy-dags-only) are enabled. This means that when you create a CI/CD pipeline for an Astro project, you can choose between the following strategies:

- Maintain a single Git repository for all files in your Astro project.
- Separate your DAGs from other project files and maintain multiple Git repositories.
- Store your DAGs in a cloud provider storage solution, such as AWS S3, and the rest of your Astro project files in a dedicated Git repository.
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +When you make this decision, keep in mind how many branches of your project to host on Astro. Your CI/CD pipeline can manage deploying multiple branches across multiple repositories. See [Single bran
Are we trying to say that you don't have to equate this decision with the environment decision?

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +When you make this decision, keep in mind how many branches of your project to host on Astro. Your CI/CD pipeline can manage deploying multiple branches across multiple repositories. See [Single bran
```suggestion
When you make this decision, keep in mind how many branches of your project to host on Astro. Your CI/CD pipeline can manage deploying multiple branches across multiple repositories. See [Single branch vs. multiple branch repositories](#single-branch-versus-multiple-branch-repositories).

Astronomer recommends one centralized repository for a single Astro project.
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +The most basic strategy is to have a single Git repository that hosts your entire Astro project. If you have multiple team members working on the project, they all commit to the same repository regar
```suggestion
For most teams, Astronomer recommends creating a single Git repository for each Workspace and Astro project or use case. This means that your team can make changes to your DAGs, Python packages, and Deployment configuration in a single place. This strategy keeps your code history centralized, makes it easy for developers to contribute code, and avoids synchronization problems across files.

This strategy is recommended if:

- A single team is responsible for both developing DAGs and maintaining Deployments on Astro.
- Your don't need to support a dedicated repository for DAGs across your organization.
- Less than 30 people interact with or contribute to your  Apache Airflow use case.
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Using a multi-repository CI/CD strategy, you can manage your DAGs in one repository and Astro project settings in another. Use this strategy to ensure that DAG authors and data operators have access
Similar to above, let's expand on why you'd have to do this?

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Similar to the multiple repository strategy, this strategy separates the management of DAGs and project configuration. DAGs are stored in an [S3 bucket](https://aws.amazon.com/s3/), while Astro proje
Or GCP

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +If you migrated to Astro from Amazon Managed Workflows for Apache Airflow (MWAA), this strategy is useful for maintaining a similar workflow for DAG authors. You can set up a Lambda function to push
Or GCC

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Adding an Astronomer [CI/CD template](ci-cd.md) to your repositories, or using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).
```suggestion
- Adding an Astronomer [CI/CD template](ci-cd.md) to your repositories, or using the Astronomer maintained [`deploy-action`](https://github.com/astronomer/deploy-action) found in the GitHub Marketplace.
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +The process for creating an Astro CI/CD template includes the following steps:
```suggestion
When you set up a CI/CD workflow on Astro, you will:
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Adding an Astronomer [CI/CD template](ci-cd.md) to your repositories, or using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).
```suggestion
- Select a CI/CD strategy after reviewing this document and the requirements of your team.
- Set up your repositories and permissions based on your CI/CD strategy.
- Add an Astronomer [CI/CD template](ci-cd.md) to your Git repository(s) based on your preferred CI/CD tool.
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Modifying the Astronomer template or GitHub action to meet the requirements of your organization.
```suggestion
- Modify the Astronomer template or GitHub action to meet the requirements of your organization. 
```

2023-02-07 05:32 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +If you use GitHub, Astronomer recommends using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-action).
```suggestion
If you use GitHub, Astronomer recommends using the [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-action) that you can find in the GitHub Marketplace and is maintained by Astronomer.
```

2023-02-08 10:05 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- How many different environments do you need to adequately test your DAGs before deploying them to production?
I don't think we need to mention investment here, if they need the environments then they need them - investment shouldn't factor into their decision right?

2023-02-08 10:09 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- How many repositories do you want to host your project? Will different parts of your team work on different parts of your project?
I rephrased this question to lead with "How does your team work" and follow up with "Do you think multiple repos would help with that"

2023-02-08 10:09 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- How many repositories do you want to host your project? Will different parts of your team work on different parts of your project?
"- Do different teams work on different parts of your project? If so, do you need to host your Astro project in multiple repositories?"

2023-02-08 10:23 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- At least two Astro Deployments that each host different branches of your project.
Is the database/ data warehouse point required? I thought it was possible to partition that resource so you could still use test data for test environments without breaking the entire thing. If we're going to add this assumption, we should elaborate more in the text about its purpose.

2023-02-08 10:26 UTC, jwitz commented on astro/set-up-ci-cd.md
> +When you make this decision, keep in mind how many branches of your project to host on Astro. Your CI/CD pipeline can manage deploying multiple branches across multiple repositories. See [Single bran
Tried updating this to make more sense

2023-02-08 10:36 UTC, jwitz commented on astro/set-up-ci-cd.md
> +If you use GitHub, Astronomer recommends using the Astronomer maintained [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action).(https://github.com/astronomer/deploy-action).
All GitHub Actions are found in the GitHub marketplace right?

2023-02-08 10:37 UTC, jwitz commented
Ready for final review!

2023-02-08 12:46 UTC, kwcanuck commented on astro/set-up-ci-cd.md
> +- Your don't require a dedicated repository for DAGs across your organization.
```suggestion
- You don't require a dedicated repository for DAGs across your organization.
```

2023-02-09 21:24 UTC, sunkickr commented on astro/set-up-ci-cd.md
> +- How many different environments do you need to adequately test your DAGs before deploying them to production?
If the DAGs are not very business critical maybe they don't want to spend the extra money to test them

2023-02-10 04:40 UTC, paolaperaza approved these changes
Final handful of comments but I'll officially leave it to you, @jwitz + @sunkickr  to finish and merge!!!!

Awesome work here.

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Configure more granular user permissions by managing access and changes to your Astro project source code in your version control tool.
```suggestion
- Protect your mission-critical data pipelines by more strictly limiting user permissions on Astro and ensuring that all code deploys are approved in your version control.
```

This might be redundant with the above.... I talked to Chris Cardillo about the permissions thing and it didn't feel right. If this doesn't make sense to you Jake let's just scrap this bullet point

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +You can set up CI/CD pipelines to manage multiple Deployments and repositories based on your team structure. Before you create your pipeline, you need to determine how many repositories and environme
```suggestion
You can set up CI/CD pipelines to manage multiple Deployments and repositories based on your team structure. Before you create your pipeline, you need to determine how many environments and repositories of your project you want to maintain.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +When deciding on a strategy, keep the size of your data team in mind while answering the following questions:
```suggestion
When deciding on a strategy, keep the size of your data team and the importance of your Airflow DAGs in mind while answering the following questions:
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- How many different environments do you need to adequately test your DAGs before deploying them to production?
Agreed -- I think it's a realistic thing to keep in there?

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- How many repositories do you want to host your project? Will different parts of your team work on different parts of your project?
"Do you need to limit DAG authors from managing dependencies and advanced configurations of your project? If so, do you need to host your Astro project in multiple repositories?"

Maybe this?

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +### Single environment versus multiple environment repositories
```suggestion
### Environments
```

Simplify?

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +When you create a CI/CD pipeline, you must first determine how many environments you need to test your DAGs in. Each environment requires a Deployment on Astro, as well as its own GitHub branch and i
```suggestion
When you create a CI/CD pipeline, you must first determine how many environments you need to test your DAGs in. This typically depends on how critical these DAGs are to your business and how much your team expects to spend in infrastructure.

Each environment requires a Deployment on Astro, as well as its own GitHub branch and implementation in your CI/CD pipeline. 
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +The most cost-effective way to get started with CI/CD on Astro is to maintain a single Git repository that corresponds to a single Astro project and Deployment. This solution is best for simple proje
```suggestion
The most cost-effective way to get started with CI/CD on Astro is to maintain a single Deployment on Astro for one Astro project. This solution is best for simple projects where you can tolerate testing and bug fixing in production.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- One primary and permanent branch in your Git repository. Astronomer recommends `main`.
```suggestion
- One primary and permanent branch in your Git repository. Astronomer recommends `main`.
- One database or data warehouse that hosts all of the production data that your Airflow DAGs need.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- At least two Astro Deployments that each host different branches of your project.
You're probably right here. It's a common way to think about it (and recommend) but maybe we can add a note somewhere more appropriate? Maybe as a tip to this multiple environments section?

Edit: the snowflake example below might be sufficient. I'm fine w that

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +### Single repository versus multiple repositories
```suggestion
### Repositories
```

Simplify? Or maybe:

"Choose number of repositories"
"Number of repositories"
"How many repositories"

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Separate your DAGs from other project files and maintain multiple Git repositories.
```suggestion
- Separate your DAGs from other files and maintain multiple Git repositories for a single Astro project.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Develop this strategy in conjunction with your strategy for managing environments. Your CI/CD pipeline can manage deploying multiple branches across multiple repositories. See [Single branch vs. mult
Change links if you agree w headings

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +- Less than 30 people interact with or contribute to your Airflow use case.
```suggestion
- Less than 30 people interact with or contribute to a single Astro project.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Using a multi-repository CI/CD strategy, you can manage your DAGs in one repository and Astro project settings in another. This strategy is recommended if:
```suggestion
Depending on your organization, you might be required to maintain multiple repositories for a single Astro project. Data teams that implement this strategy typically manage DAGs in one repository and Astro project settings, such as Python packages and worker configuration, in another repository.

This strategy is recommended if:
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +#### DAG bucket and Git repository to a single Deployment
```suggestion
### Store DAGs in storage bucket
```

Or 
- Store DAGs in cloud storage
- ?

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +If you migrated to Astro from Amazon Managed Workflows for Apache Airflow (MWAA) or Google Cloud Composer (GCC), this strategy is useful for maintaining a similar workflow for DAG authors. You can se
```suggestion
If you migrated to Astro from Amazon Managed Workflows for Apache Airflow (MWAA) or Google Cloud Composer (GCC), this strategy is useful for maintaining a similar workflow for DAG authors. For example, you can set up a Lambda function to push DAGs to your Astronomer Deployment whenever DAG files are updated in your specific S3 bucket.
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +If you use GitHub, Astronomer recommends using the [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action) that is maintained by Astronomer.
Double mention?

2023-02-10 04:40 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +Astronomer recommends that you pytest all Python code in your DAGs. The Astro CLI includes [pytests](test-and-troubleshoot-locally.md#test-dags-with-the-astro-cli) to validate that your DAGs do not h
```suggestion
Astronomer recommends that you pytest all Python code in your DAGs. The Astro CLI includes [pytests](test-and-troubleshoot-locally.md#test-dags-with-the-astro-cli) to validate that your DAGs do not have import or syntax errors. You can implement this parse test with the [Astro CLI](cli/astro-dev-parse.md) or the [Deploy Action](https://github.com/astronomer/deploy-action).

The default test may not work on all DAGs, especially if they access the Airflow metadata database. In this case, you can write your own parse test using example pytests provided in the default Astro project.
```


Add link to the right section in the Deploy Action Marketplace?

2023-02-10 04:40 UTC, paolaperaza commented on astro/ci-cd.md
>  title: 'Automate code deploys with CI/CD'
"Use CI/CD templates to automate code deploys on Astro"

Something like that? Shorter?

2023-02-10 04:40 UTC, paolaperaza commented on astro/ci-cd.md
> +Use the Astronomer CI/CD templates to automate code deployment to Astro with popular CI/CD management tools, including GitHub Actions and Circle CI. To decide which template is right for you, see [Se
```suggestion
Setting up CI/CD is critical for mature data teams on Astro. Use the CI/CD templates in this guide to automate deploying code to Astro with popular CI/CD management tools, including GitHub Actions and Circle CI.

To learn more about the benefits of CI/CD and decide which template is right for you, see [Set up CI/CD](set-up-ci-cd.md).
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/ci-cd.md
> +The DAG-based workflow uses the `--dags` flag in the Astro CLI to push DAG changes to Astro. These CI/CD pipelines deploy your DAGs only when files in your `dags` folder are modified, and they deploy
```suggestion
The DAG-based workflow uses the `astro deploy --dags` command in the Astro CLI to quickly push DAG changes to Astro. These CI/CD pipelines only deploy your DAGs when only files in your `dags` folder are modified, and they deploy the rest of your Astro project as a Docker image when other files or directories are modified. This makes deploys to Astro faster.

For more information about the benefits of the DAG-only deploy feature, see [Deploy DAGs only](deploy-code.md#deploy-dags-only).
```

2023-02-10 04:40 UTC, paolaperaza commented on astro/ci-cd.md
> +The following templates use the Astronomer-maintained [Deploy Action](https://github.com/astronomer/deploy-action) to deploy code to Astronomer. See the [Deploy Action README](https://github.com/astr
Should we just link to the marketplace, which hosts the README?

2023-02-10 11:34 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- How many different environments do you need to adequately test your DAGs before deploying them to production?
I had assumed that "Need" here implied that the environments were already costed in, and that folks setting this up understand that more computational environments = more money, but don't mind including it either.

2023-02-10 11:36 UTC, jwitz commented on astro/set-up-ci-cd.md
> +- How many repositories do you want to host your project? Will different parts of your team work on different parts of your project?
Settled on "Do you need to limit your DAG authors' access to sensitive project configurations? If so, do you need to host your Astro project in multiple repositories?"

2023-02-10 12:01 UTC, jwitz commented on astro/set-up-ci-cd.md
> +If you use GitHub, Astronomer recommends using the [`deploy-action` GitHub action](https://github.com/astronomer/deploy-action) that is maintained by Astronomer.
Removing the reference from the bullet list, since you would still copy a template to use the action.

2023-02-10 12:07 UTC, jwitz commented on astro/set-up-ci-cd.md
> +Astronomer recommends that you pytest all Python code in your DAGs. The Astro CLI includes [pytests](test-and-troubleshoot-locally.md#test-dags-with-the-astro-cli) to validate that your DAGs do not h
The reference seems general enough that I'd prefer to keep the link general too. Hard to tell when an external link anchor changes, so this will be future proof.

2023-02-10 12:24 UTC, merged