rephrase optional step for datadog metrics
astronomer/docs pull request #1702
Opened 2023-01-04 20:51 UTC by afastronomer

2023-01-04 20:57 UTC, stuart23 commented on astro/deployment-metrics.md
> +4. Optional. If you don't want to use the default Datadog site (datadoghq.com) defined by Astronomer, add the following environment variable:
```suggestion
4. Optional. If you use a Datadog site that is not the default (datadoghq.com), add the following environment variable:
```

2023-01-04 20:57 UTC, stuart23 requested changes
Just want to clarify that it isn't up to what the customer "wants", but rather what is configured in their DD account.

2023-01-04 20:58 UTC, stuart23 commented
Reference if it is relevant to help describe: https://docs.datadoghq.com/getting_started/site/

2023-01-05 13:11 UTC, kwcanuck commented on astro/deployment-metrics.md
> +4. Optional. If you use a Datadog site that is not the default (datadoghq.com), add the following environment variable:
```suggestion
4. Optional. If your organization doesn't use the default Datadog site datadoghq.com, add the following environment variable:
```

2023-01-05 16:20 UTC, stuart23 approved these changes
Robs wording sounds much better.

2023-01-05 16:21 UTC, merged