Add Content for `.airflowignore`
astronomer/docs pull request #1710
Opened 2023-01-06 15:29 UTC by kwcanuck

Resolves #1708

2023-01-09 03:51 UTC, paolaperaza requested changes
Couple quick comments, @kwcanuck. Let's make sure @manmeetkaur gives this a ✅ !

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +## Ignore files when deploying code
```suggestion
## Ignore files with `.airflowignore`
```

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +You can add an `.airflowignore` file to any DAGs directory to identify the files that should be ignored when you push code to Astro. This can be helpful when you have a single GitHub repository conta
```suggestion
You can create an `airflowignore` file in your Astro project and use it to specify files that you do not want to be included when you push code to Astro. This can be helpful when you have a single GitHub repository containing DAG files for multiple Astro projects and you don't want to deploy all DAG files to a single Deployment.
```

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +When you add an `.airflowignore` file to a DAGs directory, the files listed in the file are ignored when developing locally and when you deploy your project to Astro. The same image is built and depl
```suggestion
When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler when you run `astro dev start` or when you deploy your project to Astro. DAGs listed in this file are not deployed and do not appear in the Airflow UI. The `.airflowignore` file and any files listed in it must be in the same `dags` directory of your Astro project. For more information about `.airflowignore`, see [`.airflowignore` in Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#airflowignore).
```

- I think we don't need the version control comment?
- Specified that this file is ignored by the _scheduler_
- Should we give an example file in this section, to highlight the syntax requirements? Per Airflow docs, we want to make sure users know that they need to include the entire file name, not the DAG ID for example

Things to confirm
- Can not just be DAG files?
- Is it the scheduler that does the ignoring here? Any other technical details we might need to capture?

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +1. In your Astro project, create a new file named `.airflowignore` in a DAGs directory.
```suggestion
1. In the `dags` directory of your Astro project, create a new file named `.airflowignore`.
```

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +2. List the files you want ignored when pushing code to Astro.
```suggestion
2. List the files or sub-directories you want ignored when pushing code to Astro or developing locally. For example, `mydag.py` or `data-team-dags`. The ignored files must be present in the same `dags` directory.
```

Could specify the requirement of the dag directory here and not above since redundant

2023-01-09 03:51 UTC, paolaperaza commented on astro/deploy-code.md
> +3. Add the DAG name file path to the file.
Is this different than step 2?

2023-01-09 12:53 UTC, kwcanuck commented
@manmeetkaur can you review this new content and provide you feedback? @paolaperaza also wants confirmation on these two points:

- Can not just be DAG files?

- Is it the scheduler that does the ignoring here? Any other technical details we might need to capture?

Thanks!

2023-01-09 12:57 UTC, kwcanuck commented
@paolaperaza responses to your questions:

_Should we give an example file in this section, to highlight the syntax requirements? Per Airflow docs, we want to make sure users know that they need to include the entire file name, not the DAG ID for example_

If you want an example, can you provide it? Would it be easier to simply state " include the entire file name, not the DAG ID" instead of providing a sample that interrupts the flow of the task?

_Is this different than step 2?_

This is the content that you provided in the originating issue. Can you provide the _specific_ edit you are requesting here?

2023-01-09 13:09 UTC, jwitz approved these changes
LGTM, just a few small suggestions ( and a high level suggestion about where to put this content )

2023-01-09 13:09 UTC, jwitz commented on astro/deploy-code.md
> +## Ignore files with `.airflowignore`
IMO this topic should be in `Develop Project` because it also applies to local development and relates to how you structure your local Astro project directory.

2023-01-09 13:09 UTC, jwitz commented on astro/deploy-code.md
> +3. Add the DAG name file path to the file.
@kwcanuck Yeah step 2 and 3 are describing the same step. DAGs are just one of the types of filepaths you can add to the file. We can just keep step 2.

2023-01-09 13:09 UTC, jwitz commented on astro/deploy-code.md
> +2. List the files or sub-directories you want ignored when you push code to Astro or when you are developing locally. For example, `mydag.py` or `data-team-dags`. The ignored files must be in the sam
```suggestion
2. List the files or sub-directories you want ignored when you push code to Astro or when you are developing locally. You should list the path for each file or directory relative to the `dags` directory. For example: 

    ```text
    mydag.py
    data-team-dags
    some-dags/ignore-this-dag.py
    ``` 
    
```
It might be best to have the examples listed in a small code block similar to the AIrflow docs:

![Screen Shot 2023-01-09 at 1 06 05 PM](https://user-images.githubusercontent.com/74574233/211314862-94c81d5a-d49f-415e-9133-d673c7c0c00c.png)

Removed the last sentence because it's repetitive to the one in the intro paragraph.

2023-01-09 13:11 UTC, BasPH commented on astro/deploy-code.md
> +When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler when you run `astro dev start` or when you deploy your project to
```suggestion
When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the Airflow UI. The `.airflowignore` file and the files listed in it must be in the same `dags` directory of your Astro project. For more information about `.airflowignore`, see [`.airflowignore` in the Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#airflowignore).
```

Would leave the last part out, the scheduler processes (and ignores) DAG files all the time.

2023-01-09 13:30 UTC, kwcanuck commented on astro/deploy-code.md
> +## Ignore files with `.airflowignore`
@jwitz - you can debate that with @paolaperaza! In the originating issue, the request was to add this content to Deploy Code. I agree with your comment, but we should avoid duplicating content in multiple locations whenever possible.

2023-01-09 15:16 UTC, paolaperaza commented on astro/deploy-code.md
> +When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler when you run `astro dev start` or when you deploy your project to
Say more, @BasPH? I do lean into wanting to give _some_ guidance on when this is generally applicable

2023-01-09 19:12 UTC, kwcanuck commented on astro/deploy-code.md
> +## Ignore files with `.airflowignore`
Content relocated.

2023-01-10 06:07 UTC, manmeetkaur approved these changes

2023-01-10 06:07 UTC, manmeetkaur commented on astro/develop-project.md
> +When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the
worth mentioning here that changes to `.airflowignore` take effect without the need to restart Airflow. The scheduler will ignore the files mentioned in `.airflowignore` when parsing the DAGs.

2023-01-10 06:17 UTC, manmeetkaur commented
> @manmeetkaur can you review this new content and provide your feedback? @paolaperaza also wants confirmation on these two points:
> 
> * Can not just be DAG files (that are excluded)?
> * Is it the scheduler that does the ignoring here? Any other technical details we might need to capture?
> 
> Thanks!

@kwcanuck @paolaperaza 
- we can ignore just the DAG files as well, as you included in the example. I have tested again the exact same file you used and it works (tried different combinations as well) .
- afaik , scheduler's file processor component - which is triggered by the scheduler at an interval - parses the files regularly  to fill the DAGBag and ignore the files mentioned in `.airflowignore`

2023-01-10 14:16 UTC, kwcanuck commented on astro/deploy-code.md
> +To run `astro deploy --dags`, you must first enable the [DAG-only deploys](deploy-code.md#ignore-files-with-airflowignore) feature for each Deployment.
@manmeetkaur - thanks for the catch! The link has been updated.

2023-01-10 14:19 UTC, kwcanuck commented on astro/develop-project.md
> +When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the
@manmeetkaur I've added a statement following the final procedure step. Thanks!

2023-01-10 14:21 UTC, kwcanuck commented
@paolaperaza this PR is ready for your final review.

2023-01-11 15:29 UTC, paolaperaza approved these changes

2023-01-11 15:29 UTC, paolaperaza commented on astro/develop-project.md
> +When you create an `.airflowignore` file, the files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the
```suggestion
You can create an `.airflowignore` file in the `dags` directory of your Astro project that you can use to have certain files ignored when you deploy to Astro or develop locally. This can be helpful if your team has a single Git repository that contains DAGs for multiple projects.

Files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the Airflow UI. The `.airflowignore` file and the files listed in it must be in the same `dags` directory of your Astro project.

For more information about `.airflowignore`, see [`.airflowignore` in the Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#airflowignore). To learn more about the code deploy process, see [What happens during a code deploy](deploy-code.md#what-happens-during-a-code-deploy).
```

- Made 1st statement an active statement. I like the "You can do this to do x"
- Added a "This can be helpful if" to clarify use case for the user

2023-01-11 15:29 UTC, paolaperaza commented on astro/develop-project.md
> +    After adding an `.airflowignore` file, you don't need to restart Airflow to implement the changes.
```suggestion
3. Save your changes locally or deploy to Astro.

    Your local Airflow environment is automatically updated as soon as you save your changes to `.airflowignore`. To apply your change in Astro, you need to deploy. See [Deploy code](deploy-code.md).
```

2023-01-11 15:59 UTC, paolaperaza commented on astro/develop-project.md
> +Files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler. DAGs listed in this file aren't deployed and don't appear in the Airflow UI. The `.airflowignore` file and the
```suggestion
The `.airflowignore` file and the files listed in it must be in the same `dags` directory of your Astro project. Files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler during its regular process every few seconds. DAGs listed in this file don't appear in the Airflow UI.
```

2023-01-11 16:05 UTC, paolaperaza commented on astro/develop-project.md
> +The `.airflowignore` file and the files listed in it must be in the same `dags` directory as your Astro project. Files or directories listed in `.airflowignore` are not parsed by the Airflow schedule
```suggestion
The `.airflowignore` file and the files listed in it must all be in the same `dags` directory of your Astro project. Files or directories listed in `.airflowignore` are not parsed by the Airflow scheduler and the DAGs listed in the file don't appear in the Airflow UI.
```

not "as" but "of" (its the dags directory IN the project)

2023-01-11 16:08 UTC, merged