TLS creation/ renewal instructions
astronomer/docs pull request #172
Opened 2020-12-28 20:16 UTC by jwitz

Closes all of these:

- https://github.com/astronomer/docs/issues/152
- https://github.com/astronomer/docs/issues/97
- https://github.com/astronomer/docs/issues/154
- https://github.com/astronomer/docs/pull/63

2020-12-28 20:28 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +## Step 4: Configure TLS
Should we be mentioning SSL at all in either document? I went with TLS because that's how Steven wrote it in his draft docs, but we've traditional used SSL.

2020-12-28 20:32 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +```sh
This setup was not in Steven's docs for getting a certificate - wasn't sure whether this is an alternative to/in addition to the setup he described.

2020-12-28 20:33 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +  # Base domain for all subdomains exposed through ingress
Please confirm that all indentation here is correct.

2020-12-28 20:34 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you have Airflow pods in the state "ImagePullBackoff", check the pod description. If you see an x509 error, ensure that you added the `privateCaCertsAddToHost` key-value pairs to your Helm chart.
This is setup that I inferred based on my general knowledge - please check for accuracy.

2020-12-28 20:37 UTC, jwitz commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Create a "ClusterIssuer" resource that declares how requests for certificates will be fulfilled. To do so, first create the a `clusterissuer.yaml` file with the following values:
In @shmanu017's PR for a similar document, he had a single astronomer-cert.yaml file with the configuration from both ClusterIssuer.yaml certificate.yaml below. This differs from the setup Steven described in his doc (https://github.com/astronomer/labs/tree/master/tls-certificate) What's the best/right way to configure this?

2020-12-28 20:38 UTC, jwitz commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +## Manually Renew TLS certificates
Inferred setup based on my general knowledge.

2020-12-28 20:38 UTC, jwitz commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Restart your Houston, nginx, and registry pods to begin using the new certificate.
Can we provide specific actions for completing step 3? Not familiar with how to do this myself.

2020-12-28 20:40 UTC, jwitz commented
Adding both @sjmiller609 and @shmanu017 for review, since you've both created drafts for similar content this year. I left questions for you commented in this PR -thank you in advance for reviewing this!

2020-12-28 20:43 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
>  To install Astronomer on EKS, you'll need access to the following tools and permissions:
Are there any version-specific considerations for this setup? Currently, I'm planning on having the exact same text for all Astronomer versions.

2020-12-31 16:28 UTC, jwitz commented
Adding this consideration from Daniel https://github.com/astronomer/issues/issues/2357#issuecomment-743326826 . Specifically:

> I talked briefly with Steven, and he said we chose a generic (opaque) secret because we do not require the key to be present. The TLS secret that the customer was using requires both a crt and key, which exposes private data unnecessarily.

> Unless there are other concerns about this issue, we can close this with a resolution of customer environment misconfiguration.

> One follow up we could do is clarify in our docs why we chose what we chose, and contrast that against the security concerns of using the TLS Secret.

2021-01-05 22:46 UTC, sjmiller609 approved these changes
Looks great Jake thank you. I left some adjustments that you may decide you want to include.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
>  To install Astronomer on EKS, you'll need access to the following tools and permissions:
Astronomer 0.16 supports Kubernetes 1.14-1.18 and Astronomer 0.23 supports Kubernetes 1.16-1.18

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +## Step 4: Configure TLS
tldr: TLS

TLS is the technically correct term, but many people still say SSL because that's what they are used / it was around longer. The name was changed to Transport Layer Security from Secure Socket Layer to align with the naming convention of OSI model layer 4.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +* **Option 2:** Request a TLS certificate from your organization's security team. We recommend this option for large organizations with their own  protocols for generating TLS certificates.
```suggestion
* **Option 2:** Request a TLS certificate from your organization's security team. We recommend this option for large organizations with their own protocols for generating TLS certificates.
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +```sh
This way gets you certificate from Let's Encrypt one time. The cert manager piece is there to perform this procedure on the user's behalf and automatically before the certificate expires.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you're installing Astronomer for a large organization, you'll need to request a TLS certificate and private key from your enterprise security team. This certificate needs to be valid for your orga
```suggestion
If you're installing Astronomer for a large organization, you'll need to request a TLS certificate and private key from your enterprise security team. This certificate needs to be valid for the `BASEDOMAIN` selected to be used for Astronomer, as well as the subdomains listed at the beginning of Step 4. You should be given two `.pem` files: one for your encrypted certificate and one for your private key.
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you're installing Astronomer for a large organization, you'll need to request a TLS certificate and private key from your enterprise security team. This certificate needs to be valid for your orga
An important detail is that it does not need to be the organization's own basedomain. This would cause an issue with some restrictive customers. i.e. Example org might not want to issue ...astro.example.com and instead elect to use ....astro.example-astronomer.com.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you're installing Astronomer for a large organization, you'll need to request a TLS certificate and private key from your enterprise security team. This certificate needs to be valid for your orga
any domain they own is fine, basically. And the BASEDOMAIN may or may not include subdomains. For example, Astronomer owns the domain astronomer-development.com. When I choose a basedomain, I choose "steven.astronomer-development.com". it would also work to choose "astronomer-development.com" as the basedomain, but that might get in the way if other developers want to use the same domain (e.g. jake.astronomer-development.com).

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +```
```suggestion
If you received a certificate from a private certificate authority, also do the following:

1. Add the root certificate provided by your security team to a Kubernetes secret in the Astronomer namespace using the following command. This should be the certificate of the authority that signed the Astronomer certificate, but not the Astronomer certificate itself. This is the same certificate you typically need to install in clients to get them to trust your services:
```sh
kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +```
Feel free to readjust this, but step 1 is performed by the enterprise security team, not those obtaining the certificate.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +  # Base domain for all subdomains exposed through ingress
confirmed

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +  postgresqlEnabled: true
```suggestion
  # For development or proof of concept only, you can use an in-cluster database
  postgresqlEnabled: false
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +          enabled: false # Disables logging in with just a username and password
```suggestion
        github:
          enabled: true # Lets users authenticate with Github
        local:
          enabled: false # Disables logging in with just a username and password
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +* **Manual renewal**: Manual renewal looks very similar to the initial certificate creation process, except you additionally need to delete your current certificate and update your systems to begin u
```suggestion
* **Manual renewal**: Manual renewal looks very similar to the initial certificate creation process, except you are replacing your existing certificate with a new certificate. We recommend this method for large organizations that have their own protocols for issuing certificates, and certificates that last long enough to justify manual update.
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +2. If you use AWS, grant Cert Manager access to your nodes by updating your `NodeInstanceRole` to include the following policies (if you don't use AWS, skip this step):
```suggestion
2. If you use AWS, grant your nodes access to Route 53 by adding a role similar to this CloudFormation snippet to your nodes' Instance Profile (if you don't use AWS, skip this step):
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +2. If you use AWS, grant Cert Manager access to your nodes by updating your `NodeInstanceRole` to include the following policies (if you don't use AWS, skip this step):
"node", "Route 53", and "Instance Profile" are key words. This section below is technically a cloudformation snippet, which is the most likely way this will be consumed. If creating the role point-and-click in the AWS UI then they will need to perform the substitution of the hosted zone id (line 37).

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Create a "ClusterIssuer" resource that declares how requests for certificates will be fulfilled. To do so, first create the a `clusterissuer.yaml` file with the following values:
the indentation below looks incorrect to me.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +                region: <your-server-region>
```suggestion
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: <your-email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-secret-key
    solvers:
    - selector: {}
      dns01:
        route53:
          region: <your-server-region>
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +Then, create the cluster by running the following command:
```suggestion
Then, create the ClusterIssuer by running the following command:
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +2. If you use AWS, grant Cert Manager access to your nodes by updating your `NodeInstanceRole` to include the following policies (if you don't use AWS, skip this step):
regarding "skip this step" - they need to find some way to authenticate cert manager against their DNS provider.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +4. Create a "Certificate" resource that declares the type of certificate you'll request from Let's Encrypt. To do so, first create the a `certificate.yaml` file, replacing `BASE_DOMAIN` with your org
```suggestion
4. Create a "Certificate" resource that declares the type of certificate you'll request from Let's Encrypt. To do so, first create the a `certificate.yaml` file, replacing `BASE_DOMAIN`:
```

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +Larger organizations with dedicated security teams will likely have their own processes for requesting and renewing TLS certificates. Regardless, there are specific steps you have to complete for Ast
here you say "process" which I prefer to saying "protocol", which is said elsewhere. I think "protocol" is a bit strange sounding if referring to a business process.

2021-01-05 22:46 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Restart your Houston, nginx, and registry pods to begin using the new certificate.
kubectl rollout restart deployments -n < astronomer namespace >
kubectl rollout restart statefulsets -n < astronomer namespace >

2021-01-06 15:46 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +```sh
Sounds good - I'll just link out to the automatic renewal setup in the new doc and remove this setup.

2021-01-06 15:51 UTC, jwitz commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Create a "ClusterIssuer" resource that declares how requests for certificates will be fulfilled. To do so, first create the a `clusterissuer.yaml` file with the following values:
@shmanu017 Can you confirm what this .yaml file should look like?

2021-01-06 16:20 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you're installing Astronomer for a large organization, you'll need to request a TLS certificate and private key from your enterprise security team. This certificate needs to be valid for your orga
Ah I see, thanks for mentioning this. I'm updating this wording in my next commit.

2021-01-06 17:04 UTC, jwitz commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +* **Manual renewal**: Manual renewal looks very similar to the initial certificate creation process, except you additionally need to delete your current certificate and update your systems to begin u
I think the last clause is redundant (or implied if an org has their own practices for this), but I like your wording on the first part!

2021-01-06 17:24 UTC, jwitz commented
Thank you for these comments @sjmiller609! I've made updates based on your suggestions. From here, I'll hand this review off to @paolaperaza for an additional pass on wording/ information structure.

2021-01-06 17:28 UTC, shmanu017 commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +3. Create a "ClusterIssuer" resource that declares how requests for certificates will be fulfilled. To do so, first create the a `clusterissuer.yaml` file with the following values:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        email: <your-email>
        server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
        name: cert-manager-issuer-secret-key
    solvers:
        - selector: {}
    dns01:
        route53:
            region: <your-server-region>
          
```

2021-01-06 19:06 UTC, shmanu017 approved these changes

2021-01-13 16:35 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +
@ianstanton Added this to the config.yaml for AWS, and if it looks good here then I'll copy if over to GCP as well.

2021-01-13 20:09 UTC, ianstanton requested changes

2021-01-13 20:09 UTC, ianstanton commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +     enabled: false
```suggestion
  ssl:
    enabled: false
```

Description looks good! Just some indentation fixes.

2021-01-13 20:19 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +     enabled: false
Sweet! Updated.

2021-01-13 21:34 UTC, paolaperaza reviewed
@jwitz This looks great. A few general things I commented on before approving:

1. The "Configure TLS" step is now quite long (though I love the detail) - did you think about potentially splitting out that content into the new renew-tls-doc or just keep it here? It feels like in some ways it'd be nice to keep the install doc simpler and link people out for more information, but not sure if that would add more friction.

2. Can you double check spacing after commands so they're consistent with the format that actually renders? (Unless they're numbered lists). 

I added some `$` before commands as well. Lemme know whachu think and I'll re-review!

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +### Option 1: Create automatically renewed TLS certificates using Let's Encrypt
@jwitz A bit confused around this header. Does "automatically renewed" mean to describe the certificate? Would it be better to say, `Create TLS certificates that automatically renew using Let's Encrypt`?

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +## Step 1: Choose a Base Domain
@jwitz I think in other docs we have steps listed as `## Step 1.` (with no `:`). Should we standardize this + add to style guide?

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +To check if your TLS certificates were accepted, log into the platform and head to `app.BASEDOMAIN/token` and run:
```suggestion
To check if your TLS certificates were accepted, log in to the Astronomer UI. Then, navigate to `app.BASEDOMAIN/token` and simultaneously run:
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +Finally, to make sure the registry is accepted by Astronomer's local docker client, try logging into Astronomer with the Astronomer CLI:
```suggestion
Finally, to make sure the registry is accepted by Astronomer's local docker client, try authenticating to Astronomer with the Astronomer CLI:
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +astro auth login <your-astronomer-base-domain>
```suggestion
$ astro auth login <your-astronomer-base-domain>
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl apply -f clusterissuer.yaml
```suggestion
$ kubectl apply -f clusterissuer.yaml
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl apply -f certificate.yaml
```suggestion
$ kubectl apply -f certificate.yaml
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl get certificates
```suggestion
$ kubectl get certificates
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl delete secret astronomer-tls
```suggestion
$ kubectl delete secret astronomer-tls
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl rollout restart deployments -n <your-namespace>
```suggestion
$ kubectl rollout restart deployments -n <your-namespace>
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +kubectl rollout restart statefulsets -n <your-namespace>
```suggestion
$ kubectl rollout restart statefulsets -n <your-namespace>
```

2021-01-13 21:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +## Step 4: Configure TLS
@jwitz I love the added detail in here - it sounds like this is a pain point for a lot of users and this detailed information will better guide them.

Do you think given the breadth here that it'd be worth splitting this content into the other doc and just guide people there instead?

2021-01-14 01:11 UTC, ianstanton approved these changes

2021-01-14 14:55 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +## Step 1: Choose a Base Domain
Yep, I added a bit on this to the style guide earlier this week.

2021-01-14 16:55 UTC, jwitz commented
Thanks for giving this a look @paolaperaza . I added your suggestions in a commit along with the changes to GCP and AKS docs. 

For now, I think it's safer to keep the TLS instructions here. Specifically, this is because some of the values you create in the TLS setup need to be applied in our Helm chart, and having those setups in separate places might make it difficult to keep track of those values. I can definitely see us breaking this entire setup into separate guides in the future, though.

2021-01-14 20:09 UTC, paolaperaza approved these changes
@jwitz I added a few more missing `$`'s before commands, but otherwise this looks great to me :)

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```suggestion
$ kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```suggestion
$ kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
>  curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
>  curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you have Airflow pods in the state "ImagePullBackoff", check the pod description. If you see an x509 error, ensure that you added the `privateCaCertsAddToHost` key-value pairs to your Helm chart.
```suggestion
If you have Airflow pods in an `ImagePullBackoff` state, check the pod description. If you see an x509 error, ensure that you added the `privateCaCertsAddToHost` key-value pairs to your Helm chart. If you missed these during installation, follow the steps in [Apply a Platform Configuration Change on Astronomer](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/apply-platform-config) to add them after installation.
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +openssl x509 -in  <your-certificate-filepath> -text -noout
```suggestion
$ openssl x509 -in  <your-certificate-filepath> -text -noout
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```suggestion
$ kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```suggestion
$ kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
> +curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/03_azure/01_install-azure-standard.md
> +openssl x509 -in  <your-certificate-filepath> -text -noout
```suggestion
$ openssl x509 -in  <your-certificate-filepath> -text -noout
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/03_azure/01_install-azure-standard.md
> +kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```suggestion
$ kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/03_azure/01_install-azure-standard.md
> +kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```suggestion
$ kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/03_azure/01_install-azure-standard.md
>  curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/03_install/03_azure/01_install-azure-standard.md
>  curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```suggestion
$ curl -v -k -X POST https://houston.BASEDOMAIN/v1 -H "Authorization: Bearer <token>"
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
> +Let's Encrypt is a Certificate Authority that provides free, 90-day certificates using the ACME protocol. You can use the Cert Manager project for Kubernetes to automatically renew certificates.
```suggestion
[Let's Encrypt](https://letsencrypt.org/) is a Certificate Authority that provides free, 90-day certificates using the ACME protocol. You can use the Cert Manager project for Kubernetes to automatically renew certificates.
```

2021-01-14 20:09 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/09_renew-tls-cert.md
> +Let's Encrypt is a Certificate Authority that provides free, 90-day certificates using the ACME protocol. You can use the Cert Manager project for Kubernetes to automatically renew certificates.
```suggestion
[Let's Encrypt](https://letsencrypt.org/) is a Certificate Authority that provides free, 90-day certificates using the ACME protocol. You can use the Cert Manager project for Kubernetes to automatically renew certificates.
```

2021-01-15 18:17 UTC, merged