KubernetesPodOperator doc
astronomer/docs pull request #175
Opened 2021-11-30 14:11 UTC by jwitz

Resolves https://github.com/astronomer/cloud-docs/issues/104

Updated some content to be Gen2 cloud specific, and private image registry instructions are based on https://www.notion.so/astronomerio/Gen2-KubePodOperator-Private-Repository-image-pull-94586513f06d4a43a8e7384dd7c77e94.

Tagging @ben-astro for review to make sure I didn't mangle his words!

2021-12-09 15:58 UTC, paolaperaza reviewed
Initial comments here - let's see if we can get the intro and structure of this doc down first and then double down on use cases/details

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +The KubernetesPodOperator can run a task in an individual Kubernetes Pod. When the operator finishes running a task, it automatically terminates the Pod that the task was running in. The KubernetesPo
Maybe also add a sentence here about how Astronomer Cloud is Kube based so you can do this without managing infra

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +You can now instantiate the KubernetesPodOperator:
```suggestion
Then, instantiate the KubernetesPodOperator:
```

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +## Using the KubernetesPodOperator
```suggestion
## Import Statement
```

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +You can now instantiate the KubernetesPodOperator:
Thoughts on adding an H2 here called `## Basic Configuration`, where we discuss the minimum configs required? AKA:

- Name
- Namespace
- Image
- task_id

Maybe an H3 under here that explains how the KPO actually runs on Cloud

And then another H2 after that for , `## Advanced Configuration`, and then H3's under that for:

- Resource Specifications 
- Pull Docker Image from a Private Registry
- Other use cases/configs

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +    get_logs=True)
```suggestion
k = kubernetes_pod_operator.KubernetesPodOperator(
    namespace=namespace, # Sets your Astronomer Deployment's namespace
    image="<your-docker-image>", # Specify your Docker image here
    cmds=["bash", "-cx"],
    arguments=["echo", "10", "echo pwd"],
    labels={"<pod-Label>": "<label-name>"}, # Labels that apply to the Kubernetes Pod
    name="<pod-name>", # The name of the Kubernetes Pod
    is_delete_operator_pod=True, # Instructs the pod to terminate after the task has been deleted
    in_cluster=True, # Instructs the pod to execute within the Kubernetes environment of your Astronomer Cluster
    task_id="<task-name>", # The name of your task
    get_logs=True) # If true, logs stdout output of the container
```

2021-12-09 15:58 UTC, paolaperaza commented on docs/kubernetespodoperator.md
> +- `is_delete_operator_pod=True`: This setting ensures that the Pods of completed tasks are deleted, which lowers resource usage on your Cluster.
Thoughts on making this a table, where we set:

- Parameter
- Default
- Description

Think it's redundant with the `# comments` above?

2021-12-10 12:37 UTC, jwitz commented on docs/kubernetespodoperator.md
> +This setup applies only to Astronomer projects running on Deployments in Astronomer Cloud.
Gonna take this out for now until we merged the local docs in a separate PR

2021-12-10 12:41 UTC, jwitz commented on docs/kubernetespodoperator.md
> +- A [Deployment hosting your project](deploy-code).
Had this when it was still assumed that users had to access their namespace from a Deployment information screen. Now that that's only an environment variable, this definitely makes sense.

2021-12-10 12:44 UTC, jwitz commented on docs/kubernetespodoperator.md
> +You can now instantiate the KubernetesPodOperator:
I like changing the title of our core topic to "Configure the KubernetesPodOperator" and having another h2 later called "Advanced configuration". Would probably keep the private registry instructions separate from both of these tho, since that has more to do with administering Astronomer than running the KPO itself

2021-12-10 12:45 UTC, jwitz commented on docs/kubernetespodoperator.md
> +The KubernetesPodOperator can run a task in an individual Kubernetes Pod. When the operator finishes running a task, it automatically terminates the Pod that the task was running in. The KubernetesPo
Updated some sentences here and added a new bullet point for the benefit you commented

2021-12-10 12:46 UTC, jwitz commented on docs/kubernetespodoperator.md
> +## Using the KubernetesPodOperator
Don't think it makes sense to have the import statement by itself, as you can't do much with that information alone.  imo anyone looking for the import statement will also look for how to configure the KPO

2021-12-10 13:16 UTC, jwitz commented on docs/kubernetespodoperator.md
> +- `is_delete_operator_pod=True`: This setting ensures that the Pods of completed tasks are deleted, which lowers resource usage on your Cluster.
I think there's too much information here to put cleanly in a table, we should either:
- Have all info as inline comments in the code block and list just the minimum values (no descriptions) in a bulleted list
- Keep the code block clean and list all of the info about individual values in a bulleted list (this is how it currently is)

I'm cool with both!

2021-12-10 16:01 UTC, jwitz commented
@paolaperaza This latest draft includes what we discussed in our 1:1, including some updates to the content in the task-level resources topic

2021-12-10 22:47 UTC, ben-astro requested changes
Hey! Thanks for working on this @jwitz and @paolaperaza ! My comments/edits below

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +- Execute custom Docker images on at the task level, potentially with Python packages and dependencies that would otherwise conflict with the rest of your Deployment's dependencies
looks like extra word 'on' in the clause: "Execute custom Docker images at the task level..."

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +- Horizontal scaling that is cost-effective, dynamic, and minimally dependent on Worker resources
Maybe add in a line about the benefit of being able to specify docker images from a private registry?

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +- [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl).
I think kubectl is only needed if they are planning to link to a private registry, right? Maybe a note at the end of L26 mentioning that?

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +from airflow.contrib.operators.kubernetes_pod_operator import kubernetes_pod_operator
should be 
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator

The previous link is still pre-2.0 format :/ I got the new import statement from https://registry.astronomer.io/providers/kubernetes/modules/kubernetespodoperator

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +...
Are these a repeat of lines 32-37?

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +- `image`: This is the image that the operator will use to run its defined task, commands, and arguments. By default, this value should be a publicly available image tag on Dockerhub. To pull an imag
I think I'd reword this a bit, as to me it reads like we're pointing folks towards leveraging Dockerhub. I would use language similar to what's on https://registry.astronomer.io/providers/kubernetes/modules/kubernetespodoperator, maybe something like: 
"This defaults to publicly available image tags on hub.docker.com if a fully qualified URL is not supplied. "

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +Once you push this code to a Deployment, your Cluster will automatically spin up and down Pods to run tasks that use the operator.
I would edit to further clarify... "to run tasks that use the KubernetesPodOperator."

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +- [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl).
Addendum, looks like we have a separate "Prerequisites" section for the part about pulling images from private registries, so I think kubectl can be removed from this initial "Prereqs" section

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +To securely share your hosted images on Astronomer Cloud, you need to create a Kubernetes secret for accessing your private Docker registry. To do this, complete one of the following two setups:
recommend changing "share your hosted" to "leverage your private docker"

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +3. Send the output from Step 2 and the name of the Cluster that you are configuring to your Astronomer representative. From here, your Astronomer representative will add your secret to the Cluster.
recommend changing "to your Astronomer representative" to "to Astronomer Support", and "From here, your Astronomer rep will" to "From here, Astronomer Support will"

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +    kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
A note on this command - it's looking specifically for a secret called `regcred`. If they decide to name the secret something else when creating it in step1, this command will need to change as well. Maybe we can start of bullet point 2 with a comment like "Assuming you have named the secret you just created `regcred`"

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +An Astronomer representative will use this information to directly create a Kubernetes secret and `dockerconfigjson` file in the specified Cluster.
"Astronomer Support will"

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +Once Astronomer has added the Kubernetes secret to your Cluster, you will be notified and provided with the name of the secret. Typically, this secret is named `<deployment-release-name>-private-regi
Not really sure if we need to include the sample format of the secret name, in the 1-2 times I've done this, nobody followed that template :D

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +Once Astronomer has added the Kubernetes secret to your Cluster, you will be notified and provided with the name of the secret. Typically, this secret is named `<deployment-release-name>-private-regi
And also if we remove this, then in my opinion the example KPO task definition below should also be updated L156 with something like
image_pull_secrets=[k8s.V1LocalObjectReference('<private-registry-secret-name>')],

2021-12-10 22:47 UTC, ben-astro commented on docs/kubernetespodoperator.md
> +    image_pull_secrets=[k8s.V1LocalObjectReference('<deployment-release-name>-private-registry')],
Also, in order for this line to work, they'll need to add following import statement at beginning of DAG. Maybe a comment about this above, like before or after L150? 
`from kubernetes.client import models as k8s`

2021-12-13 11:54 UTC, jwitz commented on docs/kubernetespodoperator.md
> +...
Yeah I thought it might be good to repeat so that people see where the statements are in relation to each other / the DAG file, bu it might just be better to explain the import and the instantiation in a single code block

2021-12-13 14:13 UTC, jwitz commented
Thanks for the thorough review and clearing up the private image steps @ben-astro, I think this latest draft addresses all of your suggestions!

2021-12-17 22:42 UTC, ben-astro approved these changes
Looks great Jake!

2022-02-11 15:29 UTC, jwitz commented
@paolaperaza Just confirmed that this doc is up to the standards of our current site, including with regards to links and Astronomer terminology. Should be good for another look!

2022-02-14 17:15 UTC, paolaperaza requested changes
@jwitz A few comments here. I think high-level the structure of this doc is ok, but before I approve let's -

- Clean up all instantiations of the KPO to use the same variable names and format
- Confirm with @krisdock on the steps we want to provide customers to pull secrets from a private registry

@krisdock Feel free to give us additional feedback here too 😊  I think this is an MVP that feels ok to publish but that we can iterate on, especially with Async KPO now available.

2022-02-15 16:20 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +- Coupled with the Data Plane, you have the ability to run Kubernetes pods without managing any underlying infrastructure
I'm starting to question our convention of putting "This guide" statements at the end of overviews. Shouldn't we include these towards the beginning so that people know what they're getting into?

2022-02-15 16:32 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +Astronomer Cloud automatically allocates resources to Pods created by the KubernetesPodOperator. Resources used by the KubernetesPodOperator are not limited, meaning that the operator could theoretic
Not according to Kubernetes documentation: https://kubernetes.io/docs/concepts/workloads/pods/

2022-02-15 16:32 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +Once you push this code to a Deployment, your Cluster will automatically spin up and down Pods to run tasks that use the KubernetesPodOperator.
Some minor wording updates here.

2022-02-15 17:37 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +## Pull Images from a Private Registry
Probably "Run" is safest? "Execute" implies that there's a set end state, like a task, whereas this is more like a platform for doing execution.

2022-02-15 17:46 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +- A Deployment hosting your project.
Seems like a decent possibility of somebody searching for this setup and only following it without following anything above. In terms of header heirarchy, the prereqs for private image registry are not nested in the header for the general prereqs, so there's no structural connection there either.

2022-02-15 17:58 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +From here, you can use the KubernetesPodOperator with your private images by importing Kubernetes client Models and specifying `image_pull_secrets` in your operator instantiation:
I kept the import step here since that's necessary for pulling the image

2022-02-15 18:08 UTC, jwitz commented
@paolaperaza I think all wording-related suggestions have been addressed, I just need confirmation of the technical questions related to process. At the time of writing this, we had these workflows documented on Notion. If anything's changed since then, we need to redo tech review before we merge this.

2022-02-21 20:47 UTC, paolaperaza approved these changes
@jwitz I think we are good here! Two final things before you merge:

1. Make sure `Pod` is capitalized throughout. I added it to our [style guide here](https://www.notion.so/astronomerio/Astronomer-Terms-and-Technical-Jargon-5d2389d462734e149d2e66a5cf606228).
2. Let's remove `## Option 2` here for the secret stuff - we can add back in later, I really don't think it's right

Thanks again for getting through this 🚀

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +This guide provides steps for configuring and running the KubernetesPodOperator on DAGs deployed to Astronomer Cloud.
```suggestion
title: "Run the KubernetesPodOperator on Astro"
id: kubernetespodoperator
---

## Overview

This guide provides steps for configuring and running the KubernetesPodOperator on DAGs deployed to Astro.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +- Specify CPU and Memory as task-level limits or minimums to optimize costs and performance.
```suggestion
- Specify CPU and Memory as task-level limits or minimums to optimize for cost and performance.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +- Access images hosted in private Docker repositories.
```suggestion
```

Redundant w above

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +On Astronomer Cloud, the Kubernetes infrastructure required to run the KubernetesPodOperator is built into every Cluster in the Data Plane and is managed by Astronomer.
```suggestion
On Astro, the Kubernetes infrastructure required to run the KubernetesPodOperator is built into every Cluster in the Data Plane and is managed by Astronomer.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +- An Astronomer [Deployment](configure-deployment.md).
```suggestion
- An [Astro project](create-project.md).
- An Astro [Deployment](configure-deployment.md).
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +- `namespace = conf.get('kubernetes', 'NAMESPACE')`: Every Astronomer Deployment runs on its own Kubernetes namespace within a Cluster. Information about this namespace can be programmatically import
```suggestion
- `namespace = conf.get('kubernetes', 'NAMESPACE')`: Every Astro Deployment runs on its own Kubernetes namespace within a Cluster. Information about this namespace can be programmatically imported as long as you set this variable.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +- `in_cluster=True`: When this value is set, your task will run within the Cluster from which it's instantiated on Astronomer. This ensures that the Kubernetes pod running your task has the correct p
```suggestion
- `in_cluster=True`: When this value is set, your task will run within the Cluster from which it's instantiated on Astro. This ensures that the Kubernetes Pod running your task has the correct permissions within the Cluster.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +This is the minimum configuration required to run tasks with the KubernetesPodOperator on Astronomer Cloud. To further customize the way your tasks are run, see the topics below.
```suggestion
This is the minimum configuration required to run tasks with the KubernetesPodOperator on Astro. To further customize the way your tasks are run, see the topics below.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +Astronomer Cloud automatically allocates resources to Pods created by the KubernetesPodOperator. Resources used by the KubernetesPodOperator are not limited, meaning that the operator could theoretic
Ok can u make consistent

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +The [KubernetesPodOperator](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html) is one of Apache Airflow's most powerful operators. Similar to the Kubernet
```suggestion
The [KubernetesPodOperator](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html) is one of Apache Airflow's most powerful operators. Similar to the Kubernetes Executor, this operator talks to the Kubernetes API to dynamically launch a Pod in Kubernetes for each task that needs to run and terminates each Pod once the task is completed. This results in an isolated, containerized execution environment for each task that is separate from tasks otherwise being executed by Celery workers. The KubernetesPodOperator enables you to:
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +2. Reach out to [Astronomer Support](https://support.astronomer.io) and send the Namespace of the Deployment you want to use the KubernetesPodOperator with. A Deployment's namespace can be found in t
```suggestion
2. Reach out to [Astronomer Support](https://support.astronomer.io) and include the namespace of the Deployment you want to use the KubernetesPodOperator with. A Deployment's namespace can be found in the Deployment view of the Astronomer UI.
```

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +Astronomer Support will use this information to directly create a Kubernetes secret and `dockerconfigjson` file in the specified Cluster.
@jwitz Kris is out for a bit and won't have time to confirm - let's just delete this Option #2 and add back this option later if #1 becomes a problem. Pretty sure we don't want to do this

2022-02-21 20:47 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +Once Astronomer has added the Kubernetes secret to your Cluster, you will be notified and provided with the name of the secret.
```suggestion
Once Astronomer has added the Kubernetes secret to your Deployment, you will be notified and provided with the name of the secret, represented as `<secret-name>` in the example below.
```

2022-02-21 20:52 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +1. Follow the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line) to create
@jwitz Can you add this?

2022-02-21 20:53 UTC, paolaperaza commented on cloud/kubernetespodoperator.md
> +## Pull Images from a Private Registry
"Run" is cool with me

2022-02-22 12:06 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +1. Follow the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line) to create
If we are already linking out to the k8s docs, then what is the benefit of including the snippet from the Kubernetes in our own docs? I'd rather have a user follow the k8s documentation completely rather than second guess that they have the right file by comparing the snippet in our docs to the external one.

2022-02-22 12:11 UTC, jwitz commented on cloud/kubernetespodoperator.md
> +Once Astronomer has added the Kubernetes secret to your Cluster, you will be notified and provided with the name of the secret.
Feels like we are combining two different parts of the setup in one sentence here. Let's keep the Astronomer support communication and the example usage separate. I update the name of the variable in the example to show that it's user supplied per our normal style - I think that's enough to communicate where to specify the secret.

2022-02-22 12:13 UTC, jwitz commented
@paolaperaza Merging now, but reverted two of the final changes made here in order to make the document shorter and more simple- if you feel strongly, then I can make back those changes later.

2022-02-22 12:13 UTC, merged