Add Instructions for Using an AWS Secrets Backend When Deploying Locally
astronomer/docs pull request #1753
Opened 2023-01-19 14:16 UTC by kwcanuck

Resolves #1389

2023-01-19 15:10 UTC, stuart23 commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables"}
Do we still need the `region_name` in the `AIRFLOW__SECRETS__BACKEND_KWARGS`? I think we should have it in there rather than `AWS_DEFAULT_REGION`

2023-01-19 15:17 UTC, stuart23 commented
Thanks y'all for adding this! @shubh-am-kumar I had one question about where we should spec the region.


@kwcanuck - question for you: in the prerequisites, we have
```
An IAM role with the `SecretsManagerReadWrite` policy that your Astro cluster can assume. See AWS IAM roles.
```
and then further down the page we have
```
"role_arn": "<your-role-arn>"
```
do you think it is clear enough that the IAM role required in the prerequisite is the role that you need to spec in this command?

2023-01-19 15:18 UTC, shubh-am-kumar commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables"}
We have a note here:- https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html

Saying this:- 

```
Previously, the aws_default connection had the “extras” field set to {"region_name": "us-east-1"} on install. This means that by default the aws_default connection used the us-east-1 region. This is no longer the case and the region needs to be set manually, either in the connection screens in Airflow, or via the AWS_DEFAULT_REGION environment variable.



```

2023-01-19 15:42 UTC, stuart23 commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables"}
That's great! Can we include a link to that article/comment?

2023-01-19 16:24 UTC, kwcanuck commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables"}
I added a link as discussed on Slack.

2023-01-19 16:31 UTC, stuart23 approved these changes

2023-01-19 16:32 UTC, kwcanuck commented
@jwitz a quick review (I hope) for you.

2023-01-19 16:40 UTC, shubh-am-kumar approved these changes

2023-01-19 17:26 UTC, jwitz commented
@stuart23 What do you think about the steps in https://github.com/astronomer/docs/pull/1593, where we test secrets backends locally using user credentials? If we merged that PR, would we override the instructions here for using AWS access key ID and secrets?

2023-01-19 18:06 UTC, stuart23 commented
> @stuart23 What do you think about the steps in #1593, where we test secrets backends locally using user credentials? If we merged that PR, would we override the instructions here for using AWS access key ID and secrets?

The instructions for AIRFLOW__SECRETS__BACKEND_KWARGS are still relevant and we need to still keep them here. The line [here](https://github.com/astronomer/docs/pull/1593/files#diff-26413f8b475374259b94e65f2b70817c82c66002570cdc57c98172c8ef44bb83R21) seems like if you want to just do it in your local deployment, then you can follow those instructions *instead*. For local usage of the secrets backend, mounting the creds is more of a prerequisite rather than a replacement for this.

[The link to the connection](https://github.com/astronomer/docs/pull/1753/files#diff-26413f8b475374259b94e65f2b70817c82c66002570cdc57c98172c8ef44bb83R73) is still very relevant too. 

Would it make more sense to split the "steps to enable it to work locally" into its own subsection and then we can call out the credentials prerequisite in that subsection? It should also be more compatible with the other PR then too

2023-01-19 18:07 UTC, stuart23 commented
It's going to difficult to merge these 2 PRs together. @shubh-am-kumar do you want to have a go branching https://github.com/astronomer/docs/tree/Add-AWS-Integration and adding these changes?

2023-01-20 13:59 UTC, kwcanuck commented
@jwitz as you're implementing changes with another PR, let me know how best to proceed with this PR. Perhaps it might be best to consolidate all changes in your PR and close this one. You're the quarterback! :)

2023-01-23 13:56 UTC, jwitz commented
> Would it make more sense to split the "steps to enable it to work locally" into its own subsection and then we can call out the credentials prerequisite in that subsection? It should also be more compatible with the other PR then too.

@stuart23 That's exactly my plan once we get a final approval from Paola in the other PR. My goal this week is to get that merged ASAP, after which I'll use this PR to create that split section structure you're describing. For now, marking this PR as blocked until we get the other one merged.

2023-02-03 11:35 UTC, jwitz commented
@stuart23 Want to give this one more 👀 before we merge? There's now links to the user creds docs in the intro.

2023-02-03 15:17 UTC, stuart23 requested changes

2023-02-03 15:17 UTC, stuart23 commented on astro/secrets-backend.md
> +3. Open the Airflow UI for your Deployment and create an [Amazon Web Services connection](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html) with the no cred
```suggestion
3. Open the Airflow UI for your Deployment and create an [Amazon Web Services connection](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html) without credentials. When you use this connection in a DAG, Airflow will automatically fall back to using the credentials in your configured environment variables. 
```

2023-02-03 15:18 UTC, stuart23 commented
@shubh-am-kumar is the OP, let's get his final approval

2023-02-03 15:40 UTC, shubh-am-kumar approved these changes

2023-02-03 15:44 UTC, stuart23 approved these changes

2023-02-03 15:51 UTC, jwitz approved these changes

2023-02-03 15:54 UTC, merged