Added some prereqs and requirements for AWS install
astronomer/docs pull request #176
Opened 2020-12-30 16:09 UTC by jwitz

- Fixes https://github.com/astronomer/docs/issues/101
- Fixes https://github.com/astronomer/docs/issues/158

Hi @ianstanton and @petedejoy. Attempting a sort of documentation bug bash today, and these two issues seemed like a good place to start! Could you please review the addition related to your original issue and let me know if it looks good?

For Ian: I'm not sure how often this question is asked, so I just put the requirement inline for our Helm chart. If it's often a point of confusion, I can bump it up to be an official Prerequisite. 

For Pete: Is there any more information we can provide on the requirements for the TLD? If so, let me know.

2021-01-06 15:41 UTC, ianstanton requested changes

2021-01-06 15:41 UTC, ianstanton commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +  # least 30 IP addresses.
This is good information to have in our guide, but I don't think it belongs in this example `config.yaml`.

2021-01-06 19:17 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +* At least 30 IP addresses per subnet (if using subnets)
@ianstanton I pushed this change up to the overall prerequisites section. Is there any chance someone would be installing this *without* subnets? Feel free to Slack me if this is easier to explain there.

2021-01-18 19:17 UTC, jwitz commented
@petedejoy @ianstanton following up on this PR. Do these changes look OK to push out?

2021-04-21 18:06 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +>>>>>>> 8390c880acfe27e36a8c517efa48f026645c141c
Not sure why these are showing up here, but they're not present in the actual file.

2021-04-21 18:17 UTC, ianstanton commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +* [Terraform](https://www.terraform.io/downloads.html) (Use version 0.12.3 - 0.12.28)
Our current terraform modules support 0.13 - 0.14. @pritt20 Do you know the latest version of 0.14.x we've tested with?

2021-04-21 18:17 UTC, ianstanton commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +* [Helm client](https://github.com/helm/helm#install) (Use version 3.2.1)
This could likely be updated. The latest helm release is `3.5.4`. @pritt20 do you know if we've tested with this version?

2021-06-23 14:41 UTC, jwitz commented
Cleaning up the docs repo and noticed this stale PR, if this comes up again we can reopen but I haven't heard about the need for this since actually making the PR.

2021-06-23 14:41 UTC, closed without merging