Add `${siteVariables.cliVersion}` to Install the Astro CLI
astronomer/docs pull request #1764
Opened 2023-01-20 14:25 UTC by kwcanuck

Resolves #640

2023-01-23 13:36 UTC, jwitz requested changes
Requesting changes to make sure the code formatting renders correctly on the next pass. 

Either in this PR or a separate one, can we remove the current `<TabItem value="windows">` instructions and replace them with the `winget` instructions? We really shouldn't have anyone manually installing the `exe` unless they absolutely have to. Winget should be the default Windows installation. If we want to keep the existing Windows installation, we should rename it "Windows (Manual)" and make it the last available tab.

2023-01-23 13:36 UTC, jwitz commented on astro/cli/install-cli.md
> +### Step 2: Install Astro CLI version ${siteVariables.cliVersion}
```suggestion
### Step 2: Install the Astro CLI 
```

2023-01-23 13:36 UTC, jwitz commented on astro/cli/install-cli.md
> +To install a specific version of the CLI, specify the version number as a flag at the end of the command. For example, to install version ${siteVariables.cliVersion} of the CLI, you would run:
```suggestion
To install a specific version of the CLI, specify the version number as a flag at the end of the command. For example, to install the the most recent release of the CLI, you would run:
```
One less item to maintain - and I'm also not sure that this will work outside of a code fence.

2023-01-23 13:36 UTC, jwitz commented on astro/cli/install-cli.md
> +To install a specific version of the Astro CLI, specify the version you want to install at the end of the command. For example, running the following command installs Astro CLI version ${siteVariable
```suggestion
To install a specific version of the Astro CLI, specify the version you want to install at the end of the command. For example, running the following command specifies the latest available version of the Astro CLI:
```

2023-01-23 13:47 UTC, kwcanuck commented on astro/cli/install-cli.md
>  ```sh
@jake - this change has been implemented.

2023-01-23 13:51 UTC, kwcanuck commented
@jwitz I'm not sure how common winget use is, so I've kept the manual instructions. I've moved the manual instructions so they follow the winget instructions. I think the two Windows instructions should be kept together as they are related and this seems the logical grouping. If you disagree, feel free to make any adjustments you feel are necessary. This is ready  for final review.

2023-01-24 09:43 UTC, jwitz approved these changes
@kwcanuck I think we should be encouraging users to install via Winget regardless of their current usage, because the manual installation is complicated and can result in users mistakenly breaking paths to their other CLI tools. We developed the Winget method specifically so that users would stop manually adding the CLI to their PATH environment variable. I think the changes you made are a good evolution and work for now until we figure out if there are any drawbacks to the Winget installation!

The rest LGTM, just cleaned up those code blocks so they'll render correctly. Worth double checking on the site preview before merging

2023-01-24 09:43 UTC, jwitz commented on astro/cli/install-cli.md
> +```
```suggestion
<pre><code parentName="pre">{`winget install -e --id Astronomer.Astro -v ${siteVariables.cliVersion}`}</code></pre>
```

2023-01-24 09:43 UTC, jwitz commented on astro/cli/install-cli.md
>  ```
```suggestion
```

2023-01-24 09:43 UTC, jwitz commented on astro/cli/install-cli.md
>  ```sh
```suggestion
```

2023-01-24 12:51 UTC, merged