Add SQL CLI deployment instructions
astronomer/docs pull request #1765
Opened 2023-01-20 15:17 UTC by tatiana

2023-01-20 16:05 UTC, jwitz commented on astro/cli/sql-cli.md
> +You can call these values in a `configuration.yml` file using the format `$ENVIRONMENT_VARIABLE_KEY`. For example:
```suggestion
You can call these values in a `configuration.yml` file using the format `$ENVIRONMENT_VARIABLE_KEY`.
```

2023-01-20 16:23 UTC, jwitz requested changes
@tatiana Thank you for submitting this PR! I left some suggestions where I made assumptions about the CLI workflow, please review my comments and let me know if I'm headed in the right direction with this.

2023-01-20 16:23 UTC, jwitz commented on astro/cli/sql-cli.md
> +### Deploy a SQL workflow to Astro Cloud
```suggestion
### Deploy a SQL workflow to Astro
```

2023-01-20 16:23 UTC, jwitz commented on astro/cli/sql-cli.md
> +```
```suggestion
1. Run the following command to create an Astro project at the root of your SQL project:

    ```sh
    astro dev init
    ```

2. Run the following command to log in to Astro:

    ```sh
    astro login
    ```

3.  Run the following command to deploy a SQL workflow to Astro:

    ```sh
    astro flow deploy <workflow-name> --env <env>
    ```

```

2023-01-20 16:23 UTC, jwitz commented on astro/cli/sql-cli.md
> +```
```suggestion
5. Follow the CLI instructions to select a Workspace and Deployment for your SQL environment. Now when you run `astro flow deploy <workflow-name> --env <env>`, the CLI automatically deploys your workflow to the Deployment associated with your SQL environment.
```

2023-01-20 16:23 UTC, jwitz commented on astro/cli/sql-cli.md
> +:::
```suggestion

7. Reconfigure any connections from your local SQL project in the Airflow UI for your Deployment. See [Connections](https://docs.astronomer.io/learn/connections).
```

2023-01-20 16:27 UTC, tatiana commented on astro/cli/sql-cli.md
> +```
Well spotted, @jwitz , I'll add this

2023-01-23 14:14 UTC, jwitz reviewed
@tatiana One question about the datasets feature, otherwise this looks good to me!

2023-01-23 14:14 UTC, jwitz commented on astro/cli/sql-cli.md
> +You can call these values in a `configuration.yml` file using the format `$ENVIRONMENT_VARIABLE_KEY`.
```suggestion
You can call these values in a `configuration.yml` file using the format `$ENVIRONMENT_VARIABLE_KEY`. For example: 
```

2023-01-23 14:14 UTC, jwitz commented on astro/cli/sql-cli.md
> +3. (optional) Create the `workflow.yml` inside the desired workflow folder including scheduling details.
```suggestion
3. Optional. In your workflow directory, create a file named `workflow.yml` that includes configurations for scheduling your SQL workflow. For example:
```

2023-01-23 14:14 UTC, jwitz commented on astro/cli/sql-cli.md
> +Example:
```suggestion
```

2023-01-23 14:14 UTC, jwitz commented on astro/cli/sql-cli.md
> +    ```yaml
Is this using Airflow datasets? Is the resulting DAG waiting for these datasets to be updated, or is it updating the datasets itself?

2023-01-23 14:14 UTC, jwitz commented on astro/cli/sql-cli.md
> +5. Follow the CLI instructions to select a Workspace and Deployment for your SQL environment. Now when you run `astro flow deploy <workflow-name> --env <env>`, the CLI automatically deploys your work
```suggestion
    If you haven't yet installed the Astro Python SDK in your Astro project, the CLI prompts you to update `requirements.txt` in your Astro project. Enter `yes` to have the CLI automatically install the dependency.
   
5. Follow the CLI instructions to select a Workspace and Deployment for your SQL environment. Now when you run `astro flow deploy <workflow-name> --env <env>`, the CLI automatically deploys your workflow to the Deployment associated with your SQL environment.
```

2023-01-24 10:27 UTC, jwitz commented on astro/cli/sql-cli.md
> +3. Optional. In your workflow folder, create a file named `workflow.yml` that defines when your workflow should run. You can also use this file to define metadata for the generated DAG. For example,
```suggestion
3. Optional. In your workflow folder, create a file named `workflow.yml` that defines when your workflow should run. You can also use this file to define metadata for the generated DAG. For example, the following configuration runs a SQL workflow hourly and backfills all workflow runs until December 2021. 
```

2023-01-24 10:35 UTC, jwitz approved these changes

2023-01-24 10:35 UTC, merged