Update Deployment URL Retrieval Procedure in Airflow REST API
astronomer/docs pull request #1786
Opened 2023-01-24 15:59 UTC by kwcanuck

Resolves #1783 

I was unable to validate the recommended CLI command as an error was returned when I attempted to use it:

![image](https://user-images.githubusercontent.com/104205257/214343596-1de8b726-fedf-4280-8c57-25f57131ee54.png)

2023-01-25 03:52 UTC, paolaperaza requested changes
Per discussion today, let's update this such that:

- The Astro CLI steps are the recommended procedure, and there's no additional H4 there
- At the bottom of those steps, we additional mention that this URL is the same as the Airflow UI up to `/home` (you can phrase this better). This is meant to be clarifying, but not actionable or recommended as a step

2023-01-25 15:56 UTC, kwcanuck commented
@paolaperaza I have modified the text. Please review and provide your edits or approval.

2023-01-26 16:22 UTC, jwitz commented on astro/airflow-api.md
> +In the Astro CLI, run the following command:
```suggestion
Run the following command to retrieve a Deployment URL:
```
To provide context you could say "in your terminal", but you're not "in the Astro CLI" when you're running CLI commands.

2023-02-22 14:35 UTC, kwcanuck commented
THis is a minor change that has been sitting for a month. Edits can be implemented as needed.

2023-02-22 14:35 UTC, merged