Fix SCIM setup
astronomer/docs pull request #1793
Opened 2023-01-25 14:47 UTC by jwitz

See https://astronomer.slack.com/archives/CEPE4K68P/p1674573550354179

2023-01-25 14:54 UTC, frankcash approved these changes

2023-01-25 15:03 UTC, odaneau-astro requested changes

2023-01-25 15:03 UTC, odaneau-astro commented on software/integrate-auth-system.md
> +8. In your `config.yaml` file, add the following configuration to create a unique token that Astronomer Software uses to authenticate requests from Azure AD:
The customer was asking us where this token is coming from. Is it generated in Azure AD or somewhere else?

2023-01-25 15:25 UTC, kwcanuck commented on software/integrate-auth-system.md
> +2. In the left menu, select **Enterprise applications**, then go to **+ New application** > **+ Create your own application**.
```suggestion
2. In the left menu, select **Enterprise applications**, and then click **New application** > **Create your own application**.
```

2023-01-25 15:28 UTC, kwcanuck approved these changes

2023-01-25 15:28 UTC, kwcanuck commented on software/integrate-auth-system.md
> +4. Click **Add** to create an app object. Azure AD opens the application management menu for your new application.
```suggestion
4. Click **Add** to create an application object. 
```
_Azure AD opens the application management menu for your new application._ - if this is obvious behavior and not unexpected, it doesn't need to be described.

2023-01-26 15:22 UTC, jwitz commented on software/integrate-auth-system.md
> +7. In the **Tenant URL** field, enter `https://BASEDOMAIN.astronomer.io/v1/scim/microsoft`. This is the Astronomer SCIM endpoint URL.
```suggestion
7. In the **Tenant URL** field, enter `https://astro.BASEDOMAIN/v1/scim/microsoft`. This is the Astronomer SCIM endpoint URL.
```

2023-01-26 19:58 UTC, odaneau-astro commented on software/integrate-auth-system.md
> +2. In the left menu, select **Enterprise applications**, then go to **+ New application** > **+ Create your own application**.
The answer to this question is Yes. You end up with one "Registered Application" to handle OIDC and one "Enterprise Application" to handle SCIM. Maybe we should mention it somewhere.

2023-01-26 19:59 UTC, odaneau-astro commented on software/integrate-auth-system.md
> +8. In your `config.yaml` file, add the following configuration to create a unique token that Astronomer Software uses to authenticate requests from Azure AD:
The token is a randomly generated string. As long as it matches between the helm chart and Azure AD, it should just work.

2023-01-26 20:01 UTC, odaneau-astro commented
For future reference, our internal documentation on SCIM is in Notion here: https://www.notion.so/astronomerio/SCIM-v2-Integration-3c12fc8255594b20bea199ec8b5e6916

2023-01-26 20:05 UTC, odaneau-astro approved these changes

2023-01-27 11:59 UTC, merged