Updated Enterprise Quickstart with updates from Cloud quickstart
astronomer/docs pull request #181
Opened 2021-01-05 17:31 UTC by jwitz

This PR synthesizes content from the Enterprise quickstart with improvements that were made to the Cloud quickstart guide last month. In general, the content hasn't changed - I updated the doc in the following ways:

- Reorganized steps to be more cohesive, as well as to follow a more natural pattern for installing certain features
- Linked to some new docs and improved wording to match our style guide

This update doesn't include screen shots from Airflow 2.0, but definitely can if we decide it's not too disruptive to add those now.

2021-01-07 13:38 UTC, paolaperaza requested changes
@jwitz This is great! I'm glad we're taking a chance to clean up the flow here. I think this guide is ultimately best suited for individual data engineers/users of Airflow whose team already installed the platform, and I think this structure suits that well.

I made a few comments on copy + one about moving up local instructions. Lemme know what you think and I'll give it another look.

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +- Astronomer Cloud runs in Astronomer's VPC and uses the public internet, whereas Astronomer Enterprise runs in your own environment according to your own security settings
Should these have a period at the end?

(Love the language/structure changes here by the way)

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +- Astronomer Cloud doesn't not give users access to the same monitoring stack you have in Astronomer Enterprise
Typo on "doesn't not". Maybe also specify that that monitoring stack includes Grafana and Kibana?

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +If you are in charge of setting up Astronomer for your org, follow one of our Enterprise installation guides to get Astronomer running on your Kubernetes Cluster.
"For your team" instead of "org"?

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +- AWS EKS ([Manually](/docs/enterprise/stable/install/aws/install-aws-standard/) or through [Terraform](/docs/enterprise/stable/install/aws/install-aws-terraform/))
Should we call it "Manual" or "Standard"?

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +## Step 5: Identify Your Base Domain and Log In
"Log into the Astronomer UI"? Might be too wordy, I don't feel strongly (at first I read this header and thought section was for CLI)

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +If you're the first person to log in to the Astronomer UI, click **New Workspace** to create a Workspace.
Lol I never know which one should be used where, but should this be "log into"?

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +astro auth login BASEDOMAIN
Add $

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +The first user to log in will become the Admin. Additional users can be added from the Astronomer UI. For more information on Astronomer's users and permissions model, read [Manage Users on Astronome
Specify "System Admin"

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +## Step 9: Deploy a DAG
This is all local stuff - I'm wondering if we pull it back up to the top of the doc and have this section *before* the install. What do you think?

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +Once you've turned on the `example-dag` in the Airflow UI, go to the **Metrics** tab in the Astronomer UI to see the Grafana metrics for your Deployment in real time. For a full breakdown of the Graf
Specify this is only available to SysAdmins - unless you're talking about Metrics tab? Totally different than Grafana, so would rephrase to remove that reference in this case

2021-01-07 13:38 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +* Integrate an [Auth System](/docs/enterprise/stable/manage-astronomer/integrate-auth-system/)
Maybe add "Set up CI/CD"?

2021-01-07 13:38 UTC, paolaperaza commented
Also - yes to screenshots of 2.0 if possible!

2021-01-07 14:38 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +- Astronomer Cloud runs in Astronomer's VPC and uses the public internet, whereas Astronomer Enterprise runs in your own environment according to your own security settings
Yep, going forward I'll use the style point of using punctuation:
- after every bullet point that is a sentence. 
- after every bullet point that completes the introductory stem( as these bullets do).

2021-01-07 14:40 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +If you are in charge of setting up Astronomer for your org, follow one of our Enterprise installation guides to get Astronomer running on your Kubernetes Cluster.
Nice catch, that's a weird leftover from the old version.

2021-01-07 14:47 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +- AWS EKS ([Manually](/docs/enterprise/stable/install/aws/install-aws-standard/) or through [Terraform](/docs/enterprise/stable/install/aws/install-aws-terraform/))
Since "Standard" isn't an AWS-specific term, I think it's more appropriate to use manual here. Though it differs from what's in the side nav, "Manual" makes sense as it better differentiates this install from a Terraform install (in a context where someone still might be deciding on which install to use).

2021-01-07 14:49 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +## Step 5: Identify Your Base Domain and Log In
How about "Go to Your Base Domain and Log In"? Between that and the screen shot, it think the risk of getting lost here is minimal.

2021-01-07 14:55 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +If you're the first person to log in to the Astronomer UI, click **New Workspace** to create a Workspace.
Giving the last word to Googs on this one:
<img width="653" alt="Screen Shot 2021-01-07 at 8 52 37 AM" src="https://user-images.githubusercontent.com/74574233/103906556-52048100-50bd-11eb-920b-c654ef3fc9b6.png">

The way I see it, you always "log in" but you never just "log" (at least int the context of . So when we decide whether to write "X in" or "X into", I think about whether X is the entire word or not. Kind of a hacky explanation, but that's how it makes sense in my head. 

(Also that's how it looks in our UI, so definitely easier for us to be consistent there than vice versa)

2021-01-07 15:06 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +## Step 9: Deploy a DAG
Configuring a Deployment or step 9? I'm confused about how either of these can be completed outside of the install, as they require astro CLI and a Deployment.

2021-01-07 15:11 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +Once you've turned on the `example-dag` in the Airflow UI, go to the **Metrics** tab in the Astronomer UI to see the Grafana metrics for your Deployment in real time. For a full breakdown of the Graf
Ah got it. Is there any other info we should mention here about the Metrics tab?

2021-01-07 15:14 UTC, jwitz commented
Thanks for looking at this @paolaperaza ! Left some minor comments and one question, but otherwise was able to resolve everything here.

2021-01-07 15:44 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +- Astronomer Cloud runs in Astronomer's VPC and uses the public internet, whereas Astronomer Enterprise runs in your own environment according to your own security settings
Perfect, yea that sounds like what we agreed upon!

2021-01-07 15:45 UTC, paolaperaza commented on enterprise/next/01_get-started/01_quickstart.md
> +If you are in charge of setting up Astronomer for your org, follow one of our Enterprise installation guides to get Astronomer running on your Kubernetes Cluster.
Np!

2021-01-07 19:12 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +## Step 9: Deploy a DAG
Per our conversation on Zoom, we'll keep these steps in for now. But down the line, it would be good to reconsider what to do with this quickstart guide - anyone that's already acquired an Enterprise license is on a journey with Astronomer that is very much not a quick start.

2021-01-07 19:15 UTC, jwitz commented on enterprise/next/01_get-started/01_quickstart.md
> +- AWS EKS ([Manually](/docs/enterprise/stable/install/aws/install-aws-standard/) or through [Terraform](/docs/enterprise/stable/install/aws/install-aws-terraform/))
Yeah I like that!

2021-01-07 19:20 UTC, jwitz commented
Suggested changes look good @paolaperaza. Added them in a batch and pushed everything back to v0.16 only (the earliest version anyone would be starting).

Assuming we're tabling discussion on the CLI/ Quickstart overlap, this should be good to merge.

2021-01-12 00:56 UTC, paolaperaza approved these changes
Alright @jwitz - I just went in here and made a few tiny changes and applied them to both `/next` and `v0.16.

Resolved my previous comments as well to make sure we didn't miss anything. I'm going to go ahead and merge! Depending on how the bulleted list formatting shows up, we can continue to iterate.

2021-01-12 00:57 UTC, merged