Kubernetes Executor Documentation Updates
astronomer/docs pull request #1811
Opened 2023-01-27 19:23 UTC by kwcanuck

Resolves #1788

2023-01-30 13:13 UTC, kwcanuck commented
@jwitz the revisions are still _very_ raw and need your review. I wasn't sure where to add information about the pod-template spec not being supported. Feel free to make any changes or additions you think are necessary.

2023-02-09 18:25 UTC, frankcash submitted a review, later dismissed

2023-02-09 18:25 UTC, frankcash commented on astro/create-deployment.md
> +    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod and is a good option for most uses cases. The Kubernetes executor runs indi
I would say the Kubernetes Executor is a good option for most use cases too.

2023-02-09 18:25 UTC, frankcash commented on astro/kubernetesexecutor.md
> +) as dag:
when declaring a DAG with context you can now drop the tailing `as dag`

2023-02-09 18:25 UTC, frankcash commented on astro/kubernetesexecutor.md
> +    @task(executor_config=k8s_exec_config_resource_requirements)
it would be nice to have an example not using task decorator style

2023-02-09 18:25 UTC, frankcash commented on astro/kubernetesexecutor.md
> +with DAG(
why did we choose task decorator but not dag decorator?

2023-02-09 19:24 UTC, cmarteepants commented on astro/kubernetesexecutor.md
> +    @task(executor_config=k8s_exec_config_resource_requirements)
sure - is that something you can submit to @kwcanuck please?

2023-02-09 19:24 UTC, cmarteepants commented on astro/kubernetesexecutor.md
> +with DAG(
because that's the style I usually see in the wild

2023-02-09 19:25 UTC, cmarteepants commented on astro/kubernetesexecutor.md
> +with DAG(
example from airflow docs: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#pod-override (3rd code snippet down, can't link to it directly)

2023-02-09 19:26 UTC, kwcanuck commented on astro/create-deployment.md
> +    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod and is a good option for most uses cases. The Kubernetes executor runs indi
@frankcash I have revised the text - thanks!

2023-02-15 00:28 UTC, cmarteepants commented on astro/configure-deployment-resources.md
> +The executor determines which worker resources run your scheduled tasks. The Celery executor runs multiple tasks on a single pod and is a good option for most uses cases. The Kubernetes executor runs
> good option when a few seconds of latency during start up isn't a concern

good option when task isolation and reliability are the priority and startup latency isn't a concern

2023-02-15 00:28 UTC, cmarteepants commented on astro/create-deployment.md
> +    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod. The Kubernetes executor runs individual tasks in an isolated Kubernetes po
> when a few seconds of latency during start up isn't a concern

when task reliability and running tasks in an isolated environment is the main priority

2023-02-15 00:28 UTC, cmarteepants commented on astro/kubernetespodoperator.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, customized values are overridden when they are required by Astro
> on Pods launched in an Astro cluster

in Astro

> customized values are overridden when they are required by Astronomer and your tasks will fail

this will no longer be true. We will do the same thing for KPOs as KE and reject dags using that arg if running the KPO in cluster

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +The Celery executor works with a pool of workers and communicates with them to delegate tasks. Workers are statically configured and running all the time regardless of workload.
> Workers are statically configured and running all the time regardless of workload. 

This is normally true, but we scale celery workers in Astro.

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- Allows additional workers to be added to cope with higher demand (horizontal scaling).
I would highlight that we scale the workers with higher demand **in Astro**

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- Provides a grace period for worker termination.
This isn't celery specific, but something that we do **in Astro** to overcome a celery limitation and we don't kill running tasks

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- Expense.
No longer true with autoscaling in Astro. I would spin this that we prioritize execution speed over task reliability

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- **Scheduler Count** - The number of Airflow schedulers available in your Deployment.
These settings are not worker settings (and not specific to celery). I would move this into a dedicated scheduler section

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The Kubernetes e
> Kubernetes executor can use the Kubernetes API

Kubernetes executor leverages the Kubernetes API

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +The Kubernetes executor runs as a process in the Airflow Scheduler. You select and modify Kubernetes executor settings in the Cloud UI. Astro automatically allocates resources to Pods created by the
> The Kubernetes executor runs as a process in the Airflow Scheduler.

Even though this is technically true, it's misleading. I would omit this entirely since all executors start as a process in the scheduler and delegates the execution of the task to the executor

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- Run tasks in a Kubernetes cluster outside of the Astro data plane. This can be helpful when you need to run individual tasks on infrastructure that isn't currently supported by Astro, such as GPU n
We don't support this use-case in Astro

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- Cross-account service accounts are not supported on Pods launched in an Astro cluster. To allow access to external data sources, you can provide credentials and secrets to tasks.
> Cross-account service accounts are not supported on Pods launched in an Astro cluster.

This is no different than with celery executor (and similar workaround apply), I don't think we need to call this out here

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, customized values are overridden when they are required by Astro
> If you use the `pod_template_file` argument, customized values are overridden when they are required by Astronomer and your tasks will fail

This is not true. While it's true that we do not support using the `pod_template_file` in Astro, if you try deploying a dag that uses the `pod_template_file` arg, we will reject the dag and you will see a Broken DAG error in the Airflow UI. We link to the Airflow docs suggesting that you use the `python-kubernetes-sdk`

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +When this DAG runs, it launches a Kubernetes Pod with exactly 800m of CPU and 3Gi of memory as long as that infrastructure is available in your cluster. Once the task finishes, the Pod terminates gra
The example shows 0.5 cpu, and 1024Mi of memory, not 800m and 3Gi. We need to adjust the text, or the example to match.

2023-02-15 00:28 UTC, cmarteepants commented on astro/manage-astro-executors.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, customized values are overridden when they are required by Astro
I have a screenshot of the error if you'd like to include it

2023-02-15 13:38 UTC, jwitz requested changes
Leaving some high level comments to start with.

My main thought is: The distinction we make between Celery worker scaling and worker queue settings doesn't make sense IMO. Why are we explaining some worker settings in one doc and other worker settings in another when they're both related? 

At a minimum, the worker queue doc needs to be updated to explain that the functionality is only for celery only. But also, I thought that this doc structure could make more sense:

- Choose an executor on Astro
- Manage the Celery executor (renamed from "Configure worker queues")
- Manage the Kubernetes executor

Configure Deployment Resources would only explain how to change your executor and link out to these standalone docs for more specifics. This way all executor configurations are consolidated in the single doc meant for the executor, giving us plenty of room to grow these docs in the future.

2023-02-15 13:38 UTC, jwitz commented on astro/configure-deployment-resources.md
> +4. Optional. Select an executor in the **Executor** list. See [Update the Deployment executor](#update-the-deployment-executor).
Per discussion a few days ago, I would cut any steps that are unrelated to scheduler settings.

2023-02-15 13:38 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The executor determines which worker resources run your scheduled tasks. The Celery executor runs multiple tasks on a single pod and is a good option for most uses cases. The Kubernetes executor runs
```suggestion
The executor determines which worker resources run your scheduled tasks. The Celery executor runs tasks using a pool of worker nodes is a good option for most uses cases. The Kubernetes executor runs individual tasks in an isolated Kubernetes Pod and is a good option when a few seconds of latency during start up isn't a concern. For more information about how to configure your Deployment to use the Celery and Kubernetes executors, see [Manage executors](manage-astro-executors.md).
```

2023-02-15 13:38 UTC, jwitz commented on astro/configure-deployment-resources.md
> +5. Optional. Edit the scheduler resource settings. See [Scheduler resources](#scheduler-resources).
Cut this

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +Executors are responsible for executing tasks within your DAGs. You can select Celery or Kubernetes executors in Astro. Selecting an appropriate executor can often be challenging. The intent of this
```suggestion
Executors are responsible for executing tasks within your DAGs. Astro supports the Celery and Kubernetes executor. 

There are two sides to managing executors on Astro:

- Choosing the right executor for a Deployment.
- Managing your DAGs and Deployment resources to maximize executor efficiency and reliability.

This guide covers how to do both on Astro. For more information about all available executors in Airflow, see [Airflow Executors](https://docs.astronomer.io/learn/airflow-executors-explained).
```

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +A single executor is assigned to each Deployment and you can change the executor assignment at any time. To assign an executor or modify its resource settings, see [Configure a Deployment](configure-
```suggestion
Each Deployment can run a single executor type which you can change at any time. To change a Deployment's executor type, see [Configure a Deployment](configure-deployment-resources.md).
```
I don't know if "assign" is the right word here, as executors don't exist until you configure them.

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +The Celery executor works with a pool of workers and communicates with them to delegate tasks. Workers are statically configured and running all the time regardless of workload.
+1, see if you can rewrite this with `Worker autoscaling logic` in mind

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +- **Default Max Tasks Per Worker&** - The maximum number of tasks that a single worker can process simultaneously.This is equivalent to worker concurrency in Airflow.
```suggestion
- **Default Max Tasks Per Worker** - The maximum number of tasks that a single worker can process simultaneously. This is equivalent to worker concurrency in Airflow.
```

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +You select and modify Celery executor settings in the Cloud UI. Astro automatically allocates resources to workers created by the Celery executor, but you can adjust them to meet your requirements. S
```suggestion
You can configure the Celery executor to change both the number of Celery workers running as well as the resources those workers use. The settings you can adjust include:
```
The distinction of "Celery executor settings" and "Celery worker settings" doesn't feel like the right framing. Worker queue settings _are_ Celery executor settings. I think we should define the difference as:

- Settings related **Worker count**: This includes **Default Max Tasks Per Worker** and **Default Worker Count** settings.
- Settings related to **Worker resources**: The actual computational power that each worker has. This is configured through worker queues on Astro AND your own DAG, where you specify which worker queues tasks should run on.

Please don't take this literally and adjust the text as you see fit, but this framing was the most helpful for me. Thoughts @cmarteepants ?

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Worker autoscaling logic
It doesn't make sense to duplicate only this section from the worker queues doc. What if instead we:

- Cut this section.
- Updated "Manage worker queues" to be "Manage the celery executor", part of which is worker queue configuration.
- Linked out to that doc from here

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Manage task CPU and memory
```suggestion
### Example: manage task CPU and memory
```

2023-02-15 13:38 UTC, jwitz commented on astro/manage-astro-executors.md
> +
This section is missing a general topic for how to configure the pod override file, and we don't explain that the resource management topic is only an example. @cmarteepants Can users configure _everything_ listed in the [V1Container config](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Container.md)? If so, @kwcanuck we should provide a generalized example of configuring the container (ie. no name or resources specified) and link out to the attached Kubernetes docs to explain all the possible configs you can attach to the container.

2023-02-15 13:49 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +The [Airflow scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html) is responsible for monitoring task execution and triggering downstream tasks when the dependenci
@cmarteepants the text has been relocated.

2023-02-15 13:54 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +- **Default Worker Count**: Celery executor only. Move the slider to select the number of can run in parallel in the worker queue.
@cmarteepants I made the changes you requested (I think). It wasn't absolutely clear what you meant by "...move the worker queues section under the scheduler resources section". I assumed you wanted it to be a child of S_cheduler resources_.

2023-02-15 13:55 UTC, kwcanuck commented on astro/configure-deployment-resources.md
>  #### Edit scheduler settings
@cmarteepants I implemented the change as requested.

2023-02-15 13:57 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +4. Optional. Select an executor in the **Executor** list. See [Update the Deployment executor](#update-the-deployment-executor).
@jwitz the text has been removed.

2023-02-15 13:58 UTC, kwcanuck commented on astro/configure-deployment-resources.md
>      The Airflow components of your Deployment automatically restart to apply the updated resource allocations. This action is equivalent to deploying code to your Deployment and does not impact runni
@cmarteepants I have modified the text.

2023-02-15 13:59 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +The executor determines which worker resources run your scheduled tasks. The Celery executor runs multiple tasks on a single pod and is a good option for most uses cases. The Kubernetes executor runs
@cmarteepants I added the changes

2023-02-15 14:07 UTC, kwcanuck commented on astro/create-deployment.md
> +    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod. The Kubernetes executor runs individual tasks in an isolated Kubernetes po
@cmarteepants the text has been updated.

2023-02-15 14:11 UTC, kwcanuck commented on astro/kubernetespodoperator.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, customized values are overridden when they are required by Astro
@cmarteepants it wasn't clear what edit you were requesting. I made an attempt to adjust the text. Please review.

2023-02-15 14:34 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +The Celery executor works with a pool of workers and communicates with them to delegate tasks. Workers are statically configured and running all the time regardless of workload.
@jwitz and @cmarteepants I have updated the text.

2023-02-15 14:36 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- Allows additional workers to be added to cope with higher demand (horizontal scaling).
@cmarteepants I made an attempt to update the text based on your comment. Please review

2023-02-15 14:38 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- Provides a grace period for worker termination.
@cmarteepants I made an attempt to update the text. Please review.

As an aside, it _might_ be easier if you provide the specific text you want added. This avoids guesswork and multiple reviews.

2023-02-15 14:39 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- Expense.
@cmarteepants I updated the text. Please review.

2023-02-15 14:50 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- **Scheduler Count** - The number of Airflow schedulers available in your Deployment.
@cmarteepants I made an attempt to move this information so it is a standalone section applicable to both executors. Please review.

2023-02-15 14:52 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +### Worker autoscaling logic
@paolaperaza you requested that the section be duplicated here. Can you review Jake's proposal and provide a response?

2023-02-15 14:53 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The Kubernetes e
@cmarteepants I implemented your edit.

2023-02-15 14:54 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +The Kubernetes executor runs as a process in the Airflow Scheduler. You select and modify Kubernetes executor settings in the Cloud UI. Astro automatically allocates resources to Pods created by the
@cmarteepants the text has been removed as requested.

2023-02-15 14:55 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- Run tasks in a Kubernetes cluster outside of the Astro data plane. This can be helpful when you need to run individual tasks on infrastructure that isn't currently supported by Astro, such as GPU n
@cmarteepants the text has been removed

2023-02-15 14:56 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- Cross-account service accounts are not supported on Pods launched in an Astro cluster. To allow access to external data sources, you can provide credentials and secrets to tasks.
@cmarteepants the text has been removed.

2023-02-15 14:58 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, customized values are overridden when they are required by Astro
@cmarteepants I have updated the text. Please review.

2023-02-15 15:00 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +
@jwitz I _think_ the topic you're requesting already exists. See _Manage task CPU and memory_.  

@cmarteepants can you review Jake's comment and provide your feedback? Specific edits would be helpful here.

2023-02-15 15:01 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +When this DAG runs, it launches a Kubernetes Pod with exactly 800m of CPU and 3Gi of memory as long as that infrastructure is available in your cluster. Once the task finishes, the Pod terminates gra
@cmarteepants the text has been updated

2023-02-15 15:06 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +### Manage task CPU and memory
@jwitz we should avoid using punctuation in headings. Also, this is unnecessary as the existing text states "The following **example**..."

![image](https://user-images.githubusercontent.com/104205257/219066048-3f86dfe4-a1b3-40b6-b122-367b45c19c9a.png)

2023-02-15 15:21 UTC, kwcanuck commented
> Leaving some high level comments to start with.
> 
> My main thought is: The distinction we make between Celery worker scaling and worker queue settings doesn't make sense IMO. Why are we explaining some worker settings in one doc and other worker settings in another when they're both related?
> 
> At a minimum, the worker queue doc needs to be updated to explain that the functionality is only for celery only. But also, I thought that this doc structure could make more sense:
> 
> * Choose an executor on Astro
> * Manage the Celery executor (renamed from "Configure worker queues")
> * Manage the Kubernetes executor
> 
> Configure Deployment Resources would only explain how to change your executor and link out to these standalone docs for more specifics. This way all executor configurations are consolidated in the single doc meant for the executor, giving us plenty of room to grow these docs in the future.

@jwitz it's not clear what you're requesting. What content are you proposing for the _Choose an executor on Astro_ section and where would it appear? Could we meet and discuss your plan? Alternatively, you can implement the changes you are proposing and provide them here for review.

2023-02-15 15:27 UTC, jwitz commented
@kwcanuck "Choose an executor on Astro" would have the info that the title suggests: how to decide which executor is right for you. 

I'm not requesting, I'm suggesting. What do you think? Does that structure make more sense to you? Maybe it makes more sense to have "Choose an executor" content in "Configure a Deployment" instead of a standalone doc. There's a lot of ways we can play this out, and I think we'll come up with the best content if we have a dialogue rather than treat things a strict requirements. Let me know if you want to hop on Zoom for 5 to discuss this.

2023-02-16 11:55 UTC, jwitz requested changes
We are getting there 🥳 mostly inline edits. We are still missing some context around using the Kubernetes executor - might just work with Constance to get that in

2023-02-16 11:55 UTC, jwitz commented on astro/configure-deployment-resources.md
>  - Delete a Deployment.
```suggestion
- Delete a Deployment.

For information on more advanced Deployment resource configurations, see [Manage Deployment executors](manage-astro-executors.md) and [Configure worker queues](configure-worker-queues.md).
```

2023-02-16 11:55 UTC, jwitz commented on astro/configure-deployment-resources.md
> +#### Edit Deployment settings
```suggestion
### Edit scheduler settings 
```
This topic seems to only be about schedulers now

2023-02-16 11:55 UTC, jwitz commented on astro/configure-deployment-resources.md
> +    The Airflow components of your Deployment automatically restart to apply the updated resource allocations. This action is equivalent to deploying code to your Deployment and does not impact runni
```suggestion
    The Airflow components of your Deployment automatically restart to apply the updated resource allocations. This action is equivalent to deploying code and will trigger a rebuild of your Deployment image. If you're using the Celery executor, currently running tasks have 24 hours to complete before their running workers are terminated. See [What happens during a code deploy](deploy-code.md#what-happens-during-a-code-deploy).
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +When you select an executor on Astro, you need to choose the right executor for your Deployment and then manage your DAGs and Deployment resources to maximize its efficiency and performance. The info
```suggestion
After you choose an executor for an Astro Deployment, you can configure your DAGs and Deployment resources to maximize the executor's efficiency and performance. This document provides you with an overview of how to configure the Celery and Kubernetes executors on Astro. To choose an executor for your Deployment, see [Choose an executor](configure-deployment-resouces.md#choose-an-executor) and [Airflow executors](https://docs.astronomer.io/learn/airflow-executors-explained).
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +## Celery executor
```suggestion
## Manage the Celery executor
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +The Celery executor works with a pool of workers and communicates with them to delegate tasks. Astronomer uses worker autoscaling logic to determine how many workers run on each worker queue on your
```suggestion
The Celery executor assigns tasks to workers with preset amounts of CPU and memory based on the cloud instance type they run on. On Astro, workers are organized into pools called worker queues that automatically scale worker count based on how many tasks you're running. Each Deployment running the Celery executor has a default worker queue that requires no additional configuration to start running tasks. 

This topic covers most basic Celery executor configurations for scaling workers in a worker queue. For advanced resource configuration steps, including how to configure multiple worker queues, see [Configure worker queues](configure-worker-queues.md).
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Prerequisites
These are prerequisites regardless of which executor you're using. Bump them up to the top after the intro?

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Worker autoscaling logic
```suggestion
### Celery worker autoscaling logic
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +
```suggestion
### Configure Celery worker scaling

Celery worker scaling is configured at the worker queue level. Changing how Celery workers scale ensures that your Deployment always has enough resources to run tasks, but never too much that you pay for unnecessary infrastructure.

- **Max Tasks Per Worker**: The maximum number of tasks that a single worker can run at a time. If the number of queued and running tasks exceeds this number, a new worker is added to run the remaining tasks. This value is equivalent to [worker concurrency](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#worker-concurrency) in Apache Airflow. It is 16 by default.
- **Worker Count (Min-Max)**: The minimum and maximum number of workers that can run at a time. The number of running workers changes regularly based on **Maximum Tasks per Worker** and the current number of tasks in a queued or running state. By default, the minimum number of workers is 1 and the maximum is 10.

```

2023-02-16 11:55 UTC, jwitz commented on astro/configure-worker-queues.md
> -## Worker autoscaling logic
No need to do this until we finalize doc structure, but we need to link back to the `Manage executors` doc in the intro of this `Worker queue` doc.

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +Worker settings are defined with worker queues. See [Configure worker queues](configure-worker-queues.md).
```suggestion
```

2023-02-16 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +Worker settings are defined with worker queues. See [Configure worker queues](configure-worker-queues.md).
Assume this was left over in a previous draft? A lot of this is repeated elsewhere or not relevant to executors

2023-02-16 13:57 UTC, kwcanuck commented on astro/configure-deployment-resources.md
>  ## Set Deployment resources
@jwitz I made an attempt to modify the structure as you requested. Please review and make any adjustments you think are necessary.

2023-02-16 13:58 UTC, kwcanuck commented on astro/configure-deployment-resources.md
> +#### Worker queues
@jwitz sorry, it's unclear what specific edit you're requesting here. Please implement the change you think is necessary.

2023-02-16 14:01 UTC, kwcanuck commented on astro/create-deployment.md
>  4. Optional. Edit additional Deployment resource settings. See [Configure Deployment resources](configure-deployment-resources.md). If you don't change any Deployment resource settings, your Deployme
@jwitz sorry, it's not clear what _specific_ edit you're requesting here. Can you clarify, or implement the edit you think is necessary?

2023-02-16 14:04 UTC, kwcanuck commented on astro/manage-astro-executors.md
> +### Prerequisites
@jwitz I understand that the prerequisites are identical for both executors. However, if users scan and move to the relevant section they might miss the information if it's located higher in the topic hierarchy.  Also, users might not understand that the blanket prerequisites are applicable to both executors. I think the structure is fine as is.

2023-02-16 14:20 UTC, jwitz commented on astro/create-deployment.md
>  4. Optional. Edit additional Deployment resource settings. See [Configure Deployment resources](configure-deployment-resources.md). If you don't change any Deployment resource settings, your Deployme
```suggestion
4. Optional. Edit additional Deployment resource settings. See [Configure Deployment resources](configure-deployment-resources.md). If you don't change any Deployment resource settings, your Deployment is created with the following resources:
```

2023-02-16 14:21 UTC, jwitz commented on astro/create-deployment.md
> +    - A worker queue named `default` that runs a maximum of 10 workers (Celery executor). Each of these workers can run a maximum of 16 tasks can run at a time.
```suggestion
    - If you're running the Celery executor, a worker queue named `default` that runs a maximum of 10 workers. Each of these workers can run a maximum of 16 tasks can run at a time.
```

2023-02-16 14:27 UTC, jwitz commented on astro/configure-deployment-resources.md
> +#### Worker queues
See my most recent commit

2023-02-16 14:33 UTC, jwitz commented on astro/manage-astro-executors.md
> +- An [Astro project](create-project.md).
```suggestion
```
All of this configuration is only in the UI, so you don't technically need an Astro project.

2023-02-16 14:34 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Prerequisites
I would also be fine with removing the prerequisites entirely, as it seems fairly obvious that you would need a Deployment based on the title of the doc. But don't feel strongly either way

2023-02-16 15:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +```python {20}
```suggestion
```python
```

2023-02-16 16:44 UTC, jwitz commented on astro/configure-deployment-resources.md
> +- The [Airflow scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html), which is responsible for monitoring task execution and triggering downstream tasks when the d
```suggestion
```

2023-02-17 10:28 UTC, jwitz approved these changes
Last few comments, but this is looking good to me! Thanks all for the patience with getting this to completion. Marking as "blocked" until the feature is released.

2023-02-17 10:28 UTC, jwitz commented on astro/configure-worker-queues.md
> +Although you can select Celery or Kubernetes executors on Astro, multiple worker queues can only be used with the Celery executor. You can only configure a single default worker queue for the Kuberne
```suggestion
Both the Celery and Kubernetes executors run tasks in worker queues. However, you can only configure multiple worker queues when using the Celery executor. To configure the `default` Kubernetes executor worker pool, see [Manage the Kubernetes executor](manage-astro-executors.md#manage-the-kubernetes-executor).
```

2023-02-17 10:28 UTC, jwitz commented on astro/create-deployment.md
> +    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod. The Kubernetes executor runs individual tasks in an isolated Kubernetes po
```suggestion
    - **Executor**: Select an executor to run your scheduled tasks. The Celery executor runs multiple tasks on a single pod. The Kubernetes executor runs individual tasks in an isolated Kubernetes pod and is a good option when when task reliability and running tasks in an isolated environment are the main priorities. For more information about the benefits and limitations of each executor, see [Choose an executor](configure-deployment-resources.md#choose-an-executor).
```

2023-02-17 10:28 UTC, jwitz commented on astro/manage-astro-executors.md
> +After you choose an executor for an Astro Deployment, you can configure your DAGs and Deployment resources to maximize the executor's efficiency and performance. This document provides you with an ov
```suggestion
After you choose an executor for an Astro Deployment, you can configure your DAGs and Deployment resources to maximize the executor's efficiency and performance. This document provides you with an overview of how to configure the Celery and Kubernetes executors on Astro. To choose an executor for your Deployment, see [Choose an executor](configure-deployment-resources.md#choose-an-executor).
```

2023-02-17 10:28 UTC, jwitz commented on astro/manage-astro-executors.md
> +The Celery executor assigns tasks to workers with preset amounts of CPU and memory based on the cloud instance type they run on. On Astro, workers are organized into pools called worker queues that a
```suggestion
The Celery executor assigns tasks to workers with preset amounts of CPU and memory. 

On Astro, each Celery worker utilizes an entire worker node instance on your cloud and can run multiple tasks at once. Workers are organized into pools called worker queues that automatically scale worker count based on how many tasks you're running. Each Deployment running the Celery executor has a default worker queue that requires no additional configuration to start running tasks. 
```

2023-02-17 10:28 UTC, jwitz commented on astro/manage-astro-executors.md
> +Celery worker scaling is configured at the worker queue level. Changing how Celery workers scale ensures that your Deployment always has enough resources to run tasks, but never too much that you pay
```suggestion
Celery worker scaling is configured at the worker queue level. Changing worker scaling behavior ensures that your Deployment always has enough resources to run tasks, but never so much that you pay for unnecessary infrastructure.
```

2023-02-17 10:28 UTC, jwitz commented on astro/manage-astro-executors.md
> +You can configure multiple different custom worker Pods to override the default Kubernetes worker Pod on a per-task basis. You might complete this setup to change how many resources the Pod uses, or
```suggestion
You can configure multiple different custom worker Pods to override the default Astro worker Pod on a per-task basis. You might complete this setup to change how many resources the Pod uses, or to create an `empty_dir` for tasks to store temporary files.
```

2023-02-17 10:28 UTC, jwitz commented on astro/configure-deployment-resources.md
> +- Worker queues let you assign tasks to different worker types. See [Configure worker queues](configure-worker-queues.md)
```suggestion
- Support multiple worker queues, which lets you assign tasks to different worker node types. See [Configure worker queues](configure-worker-queues.md)
```

2023-02-17 10:28 UTC, jwitz commented on sidebarsAstro.js
> +        "manage-astro-executors",
Let's move this to "Manage Deployments". I know that the KE config is at the DAG level, but you're spending more time configuring Deployment resources than the DAG itself.

2023-02-17 10:28 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The Celery executor works with a pool of workers and communicates with them to delegate tasks and it's a good option for most uses cases. Astronomer uses worker autoscaling logic to determine how man
```suggestion
The Celery executor works with a pool of workers and communicates with them to delegate tasks and it's a good option for most use cases. Astronomer uses worker autoscaling logic to determine how many workers run on each worker queue on your Deployment at a given time. See [Worker autoscaling logic](manage-astro-executors.md#worker-autoscaling-logic). 
```

2023-02-17 14:14 UTC, kwcanuck commented on sidebarsAstro.js
> +        "manage-astro-executors",
@jwitz - done.

2023-02-17 15:35 UTC, jwitz commented on astro/configure-deployment-resources.md
> +- Support multiple worker queues, which lets you assign tasks to different worker node types. See [Configure worker queues](configure-worker-queues.md)
```suggestion
- Supports multiple worker queues, which lets you assign tasks to different worker node types. See [Configure worker queues](configure-worker-queues.md)
```

2023-02-24 11:43 UTC, jwitz approved these changes
New content LGTM

2023-02-24 11:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +### Create temporary storage
```suggestion
### Create temporary storage for tasks
```

2023-02-24 11:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +Workers on the Astro data plane have limited temporary storage for Airflow tasks. Creating or storing files in the Airflow local file system is not recommended, as it is unlikely that there will be s
```suggestion
The Airflow metadata database has limited temporary storage for Airflow tasks. Creating or storing files in the metadata database system is not recommended, as it is unlikely that there will be sufficient storage for your tasks and the data will be available to other worker Pods. To create or store temporary files for task execution, Astronomer recommends creating a temporary folder per task worker Pod. The following example shows how you can add a temporary folder to a Pod using a `pod_override` configuration:
```

2023-02-24 11:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +    @task(executor_config=executor_config)
To do for later: rewrite this task so that it makes use of the temporary storage.

2023-02-24 11:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +Workers on the Astro data plane have limited temporary storage for Airflow tasks. Creating or storing files in the Airflow local file system is not recommended, as it is unlikely that there will be s
This setup doesn't have anything to do with external storage services or connections

2023-03-14 19:08 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +| `AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE`                    | The number of worker pods that can be created each time the scheduler parses DAGs. This setting limits the numbe
```suggestion
| `AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE`                    | The number of worker Pods that can be created each time the scheduler parses DAGs. This setting limits the number of tasks that can be scheduled at one time.                                                           | `16`           |
```

We control parallelism -- not sure what our recommendation should be here. @cmarteepants what do you think?

2023-03-14 19:10 UTC, paolaperaza commented on astro/manage-astro-executors.md
> +title: 'Manage Deployment executors'
```suggestion
title: 'Configure an executor for a Deployment on Astro'
```

2023-03-14 19:14 UTC, paolaperaza commented on astro/manage-astro-executors.md
> +After you choose an executor for an Astro Deployment, you can configure your DAGs and Deployment resources to maximize the executor's efficiency and performance. Use the information provided in this
```suggestion
In Apache Airflow and on Astro, the executor determines which worker resources run your scheduled tasks. The difference between executors is primarily based on how tasks are distributed across worker resources.

On Astro, a single executor is assigned to each Deployment and you can update the executor assignment at any time. After you choose an executor for an Astro Deployment, you can configure your DAGs and Deployment resources to maximize the executor's efficiency and performance. Use the information provided in this topic to learn how to configure the Celery and Kubernetes executors on Astro.

To choose an executor for your Deployment, see [Choose an executor](configure-deployment-resources.md#choose-an-executor). To learn more about executors in Airflow, see [Airflow executors](/learn/airflow-executors-explained.md).
```

Redundant with "Configure Deployment resources" but ok since this is really the primary executors topic?

2023-03-14 19:24 UTC, paolaperaza commented on astro/manage-astro-executors.md
> +## Manage the Celery executor
Link here? https://docs.astronomer.io/astro/modify-cluster#manage-worker-types

2023-03-14 19:30 UTC, paolaperaza commented on astro/manage-astro-executors.md
> +This topic discusses basic Celery executor configurations for scaling workers in a worker queue. For advanced resource configuration steps, including how to configure multiple worker queues, see [Con
```suggestion
The Celery executor assigns Airflow tasks to one or more workers that each have a preset amount of CPU and memory. A single worker represents a Kubernetes Pod that runs within a worker node on Astro. A single worker Pod typically runs multiple tasks at a time. On Astro, the Celery executor autoscales the total running number of workers based on your configurations and the number of running tasks in your Deployment. 

With the Celery executor on Astro, you can configure:

- The type and size of your workers.
- The minimum and maximum number of workers that your Deployment can run at a time.
- The number of tasks that each worker can run at a time.

You can set these configurations per worker queue, which is a set of configurations that apply to a group of workers in your Deployment. With the celery executor, you can configure multiple worker queues for different types of tasks and assign tasks to those queues in your DAG code.

This topic discusses basic Celery executor configurations for a single worker queue. For instructions on how to configure multiple worker queues, see [Configure worker queues](configure-worker-queues.md).
```

2023-03-14 19:30 UTC, paolaperaza commented on astro/manage-astro-executors.md
> +
```suggestion
```

2023-03-14 19:31 UTC, paolaperaza commented on sidebarsAstro.js
> +        "manage-astro-executors",
```suggestion
        "executors",
```

2023-03-15 11:25 UTC, jwitz commented on astro/configure-deployment-resources.md
> +See [Manage the Kubernetes executor](manage-astro-executors.md#manage-the-kubernetes-executor) for more information about configuring and running the Kubernetes executor on a Deployment.
Love all of this but not sure about "for teams running Airflow at scale." Isn't that Astro in general, and thus all of our customers? What about "Good fit for customers that need fine-grained configurations for individual tasks"

2023-03-15 11:28 UTC, jwitz commented on astro/configure-deployment-resources.md
>  5. Click **Update**.
Fixed this so that it's parallel to our executor section.

2023-03-15 11:43 UTC, jwitz commented on astro/manage-astro-executors.md
> +title: 'Manage Deployment executors'
What about just "Configure a Deployment executor"?

2023-03-15 11:55 UTC, jwitz commented on astro/manage-astro-executors.md
> +This topic discusses basic Celery executor configurations for scaling workers in a worker queue. For advanced resource configuration steps, including how to configure multiple worker queues, see [Con
I thought the purpose of having "Choose an executor" was that we could link out for a lot of this introductory content. I think it's okay in the intro, but I'd still prefer to link out when possible so that users can focus on configuration only.

2023-03-15 11:56 UTC, jwitz commented on astro/manage-astro-executors.md
> +This topic discusses basic Celery executor configurations for scaling workers in a worker queue. For advanced resource configuration steps, including how to configure multiple worker queues, see [Con
In other words, we should assume for the most part that the executor is already chosen with these details in mind.

2023-03-15 13:49 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The Celery executor manages a pool of worker Pods that are each allocated a certain amount of CPU and memory. A single worker Pod can run multiple tasks at a time. Astronomer uses [Worker autoscaling
```suggestion
The Celery executor is the default for all new Deployments. It utilizes a pool of workers and communicates with them to delegate tasks. Astronomer uses [Worker autoscaling logic](configure-executors.md#worker-autoscaling-logic) to determine how many workers run on each worker queue on your Deployment at a given time.
```

2023-03-15 13:58 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The Kubernetes executor is a good fit for teams that need fine-grained configurations for each of their tasks. Specifically, the Kubernetes executor is a good fit for your team if:
```suggestion
The Kubernetes executor is a good fit for teams that want fine-grained control over the execution environment for each of their tasks. Specifically, the Kubernetes executor is a good fit for your team if:
```

2023-03-15 15:06 UTC, paolaperaza approved these changes
A few final comments here @jwitz but I think good enough to get over the finish line and we can add more later :)

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor sta
Annoying that we're repeating ourselves here but not sure how to avoid. Could we remove some stuff _maybe_?

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor sta
```suggestion
The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor starts a new Kubernetes Pod to execute each individual task run, and then shuts down the Pod when the task run completes. This executor is recommended when you need to control resource optimization, isolate your workloads, run tasks for extended periods, or have extended periods without without task runs.
```

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +### Customize the Kubernetes worker Pod for a task
```suggestion
### Customize a Kubernetes Pod for a task
```

Not sure we call them "worker Pods" but maybe i'm wrong

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +While you can technically customize all values for a worker Pod, Astronomer recommends against configuring complex Kubernetes infrastructure in your Pods such as sidecars. These configurations have n
Another example would be good here in the future

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +While you can technically customize all values for a worker Pod, Astronomer recommends against configuring complex Kubernetes infrastructure in your Pods such as sidecars. These configurations have n
```suggestion
While you can customize all values for a worker Pod, Astronomer does not recommend configuring complex Kubernetes infrastructure in your Pods, such as sidecars. These configurations have not been tested by Astronomer.
```

2023-03-15 15:06 UTC, paolaperaza commented on astro/configure-executors.md
> +The following example shows how you can use a `pod_override` configuration in your DAG code to request custom resources for a task:
confused about the relationship between these 2 sections -- are they both telling me how to do CPU and memory? Is one a pre-requisiste?

2023-03-15 15:32 UTC, jwitz commented on astro/configure-deployment-resources.md
> +After you create an Astro Deployment, you can modify its settings to meet the unique requirements of your organization. Through the Cloud UI and Astro CLI, you can:
I still think we should say "using" instead of "in", especially for the Astro CLI where you're not really "in" it

2023-03-15 15:54 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The [Airflow scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html) is responsible for monitoring task execution and triggering downstream tasks when the dependenci
```suggestion
The [Airflow scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html) is responsible for monitoring task execution and triggering downstream tasks when the dependencies are met. 

Scheduler resources must be set for each Deployment and are managed separately from cluster-level infrastructure. Any additional components that Astro requires, including PgBouncer, KEDA, and the triggerer, are managed by Astronomer.

To ensure that your tasks have the CPU and memory required to complete successfully on Astro, you can set:
```

2023-03-15 15:55 UTC, jwitz commented on astro/configure-deployment-resources.md
> +Scheduler resources must be set for each Deployment and are managed separately from cluster-level infrastructure. Any additional components that Astro requires, including PgBouncer, KEDA, and the tri
Sure, also I think we can remove that sentence about everything else that Astronomer manages

2023-03-15 16:00 UTC, jwitz commented on astro/configure-executors.md
> +The executor determines which worker resources run your scheduled tasks. The difference between executors is primarily based on how tasks are distributed across worker resources.
It's bridged if we just don't mention either tool either tho, right? I almost feel like mentioning both features opens the possibility that the executor somehow works differently in a more nuanced way besides the shared functionality, which is not what we mean to suggest here.

2023-03-15 16:00 UTC, jwitz commented on astro/configure-executors.md
> +The executor determines which worker resources run your scheduled tasks. The difference between executors is primarily based on how tasks are distributed across worker resources.
Going with just "The Airflow executor"

2023-03-15 16:02 UTC, jwitz commented on astro/configure-executors.md
> +### Customize the Kubernetes worker Pod for a task
I updated this to plural as it's likely customers will assign multiple tasks to a single Pod spec

2023-03-15 16:04 UTC, jwitz commented on astro/configure-executors.md
> +### Configure limits and requests for worker Pod CPU and memory
```suggestion
### Example Pod configuration: Configure limits and requests for worker Pod CPU and memory
```

2023-03-15 16:04 UTC, jwitz commented on astro/configure-executors.md
> +The following example shows how you can use a `pod_override` configuration in your DAG code to request custom resources for a task:
I had "Example" at the start of this topic before, but it was removed during review. I think it's worth adding back

2023-03-15 17:00 UTC, jwitz commented on astro/configure-executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor sta
```suggestion
The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor starts a new Kubernetes Pod to execute each individual task run, and then shuts down the Pod when the task run completes. This executor is recommended when you need to control resource optimization, isolate your workloads, run tasks for extended periods, or have extended periods without task runs.
```

2023-03-15 17:02 UTC, jwitz commented on astro/executors.md
> +The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor sta
```suggestion
The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) dynamically launches and terminates Pods to run Airflow tasks. The executor starts a new Kubernetes Pod to execute each individual task run, and then shuts down the Pod when the task run completes. This executor is recommended when you need to control resource optimization, isolate your workloads, run tasks for extended periods, or have extended periods without task runs.
```

2023-03-15 17:43 UTC, cmarteepants commented on astro/configure-deployment-resources.md
> +The Kubernetes executor runs each task in an individual Kubernetes Pod instead of in shared Celery workers. For each task that needs to run, the executor calls the Kubernetes API to dynamically launc
>You can specify the configuration of the task and Pod, including CPU and memory, in a `pod_override` file.

You can specify the configuration of the task and Pod, including CPU and memory, as part of your DAG definition using the official [Kubernetes Python Client](https://github.com/kubernetes-client/python) and `pod_override` arg.

2023-03-15 17:43 UTC, cmarteepants commented on astro/configure-deployment-resources.md
> +If you want to run only specific tasks in a Kubernetes Pod, consider using the [KubernetesPodOperator](kubernetespodoperator.md).
> If you want to run only specific tasks in a Kubernetes Pod

If you want to run arbitrary non-airflow images in a Kubernetes Pod controlled by Airflow, consider using the [KubernetesPodOperator](kubernetespodoperator.md).

2023-03-15 17:43 UTC, cmarteepants commented on astro/executors.md
> +By default, each task on Astro runs in a dedicated Kubernetes Pod with 1 CPU and 512Mi of memory. These Pods run on a cloud worker node, which can run multiple worker Pods at once. If a worker node c
> 1 CPU and 512Mi of memory

up to 1cpu and 256Mi of memory

2023-03-15 17:43 UTC, cmarteepants commented on astro/kubernetespodoperator.md
> +- The `pod_template_file` argument is not supported on Pods launched in an Astro cluster. If you use the `pod_template_file` argument, the DAG is rejected. Astronomer recommends using `python-kuberne
I don't think we have anything for kubernetes overrides in the Astro SDK based on a quick scan. Normally you would use this: https://github.com/kubernetes-client/python (official Kubernetes Python Client)

2023-03-15 17:43 UTC, cmarteepants commented on astro/runtime-image-architecture.md
> +| `AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE`                    | The number of worker pods that can be created each time the scheduler parses DAGs. This setting limits the numbe
We have a default set for 16. Works well enough, but you may want to increase it if you tend to run a lot of concurrent tasks (regularly more than 16).

2023-03-15 17:43 UTC, cmarteepants commented on astro/runtime-image-architecture.md
> +| `AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE`                    | The number of worker pods that can be created each time the scheduler parses DAGs. This setting limits the numbe
tbh I don't see people playing with that - it's not dangerous but 16 is a good number

2023-03-15 17:44 UTC, cmarteepants commented on astro/configure-deployment-resources.md
> +The Kubernetes executor runs each task in an individual Kubernetes Pod instead of in shared Celery workers. For each task that needs to run, the executor calls the Kubernetes API to dynamically launc
(it's not a separate file - that was the real comment)

2023-03-15 18:57 UTC, paolaperaza approved these changes

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +Read the following topics to learn about the benefits and limitations of each executor. After you choose an executor type for your Deployment, see [Update the Deployment executor](configure-deploymen
```suggestion
Read the following topics to learn about the benefits and limitations of each executor. For information about how to change the executor of an existing Deployment, see [Update the Deployment executor](configure-deployment-resources.md#update-the-deployment-executor).
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The difference between executors is based on how tasks are distributed across worker resources. The executor you choose primarily affects the infrastructure cost of a Deployment and how efficiently y
```suggestion
The difference between executors is based on how exactly tasks are distributed across worker resources. The executor you choose primarily affects the infrastructure cost of a Deployment and how efficiently your tasks execute.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The difference between executors is based on how tasks are distributed across worker resources. The executor you choose primarily affects the infrastructure cost of a Deployment and how efficiently y
```suggestion
The difference between executors is based on how tasks are distributed across worker resources. The executor you choose primarily affects the infrastructure cost of a Deployment and how efficiently your tasks execute. Astro currently supports two executors, both of which are available in the Apache Airflow open source project:

- Celery executor
- Kubernetes executor
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The Celery executor is the default for all new Deployments. It uses a group of workers, each of which can run multiple tasks at a time. Astronomer uses [worker autoscaling logic](#clery-worker-autosc
```suggestion
The Celery executor is the default for all new Deployments. It uses a group of workers, each of which can run multiple tasks at a time. Astronomer uses [worker autoscaling logic](#celery-worker-autoscaling-logic) to determine how many workers run on your Deployment at a given time.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The Kubernetes executor is a good fit for teams that want fine-grained control over the execution environment for each of their tasks. Specifically, the Kubernetes executor is a good fit for your Dep
```suggestion
The Kubernetes executor is a good fit for teams that want fine-grained control over the execution environment of each of their tasks. Specifically, the Kubernetes executor is a good fit for your Deployment if:
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +If you want to run only specific tasks in a Kubernetes Pod, consider using the Celery executor and running tasks using the [KubernetesPodOperator](kubernetespodoperator.md).
```suggestion
:::tip

If only some of your tasks need an isolated execution environment, consider using the [KubernetesPodOperator](kubernetespodoperator.md) with the Celery executor.

:::
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The following values are used to determine the number of workers that run for each Deployment worker queue at a given time:
```suggestion
The following values are used to determine the number of workers that run in a single worker queue for a Deployment at a given time:
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +- The **Default Max Tasks Per Worker** setting for the worker queue
```suggestion
- The **Max Tasks Per Worker** setting for the worker queue
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +The number of workers determines Deployment [parallelism](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#parallelism), which is the maximum number of tasks which can ru
```suggestion
The number of workers determines Deployment [parallelism](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#parallelism), which is the maximum number of tasks which can run concurrently within a single Deployment and across worker queues. To ensure that you can always run as many tasks as your workers allow, parallelism on Astro is automatically calculated with the following expression:
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +Celery worker scaling is configured at the worker queue level. Changing worker scaling behavior ensures that your Deployment always has enough resources to run tasks, but never so much that you pay f
```suggestion
For each worker queue on your Deployment, you have to specify certain settings that affect worker autoscaling behavior. If you're new to Airflow, Astronomer recommends using the defaults in Astro for each of these settings.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +By default, each task on Astro runs in a dedicated Kubernetes Pod with 1 CPU and 512Mi of memory. These Pods run on a cloud worker node, which can run multiple worker Pods at once. If a worker node c
```suggestion
By default, each Kubernetes executor task on Astro runs in a dedicated Kubernetes Pod with 1 CPU and 512Mi of memory. These Pods run on a worker node in your Astro data plane. A single worker node can run multiple worker Pods at once. If a worker node can't run any more Pods, Astro automatically provisions a new worker node to begin running any queued tasks in new worker Pods.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +- Change worker instance type on which your Pods run.
```suggestion
- Change worker node size and type on which your Pods run.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +- Customize the Pods on which your tasks run using a `pod_override` configuration.
```suggestion
- Customize individual tasks, including CPU and memory requests, using a `pod_override` configuration. 
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +You can configure different custom worker Pods to override the default Astro worker Pod on a per-task basis. You might complete this setup to change how many resources the Pod uses.
```suggestion
For each task with the Kubernetes executor, you can customize its individual worker Pod and override the defaults used in Astro by configuring a `pod_override` file.
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +### Example Pod configuration: Configure limits and requests for worker Pod CPU and memory
```suggestion
### Example: Set CPU or memory limits and requests
```

2023-03-15 18:57 UTC, paolaperaza commented on astro/executors.md
> +See [Manage task CPU and memory](#manage-task-cpu-and-memory) for an example `pod_override` configuration.
```suggestion
See [Manage task CPU and memory](#example-set-CPU-or-memory-limits-and-requests) for an example `pod_override` configuration. 
```

2023-03-15 19:06 UTC, paolaperaza commented on astro/executors.md
> +### Change the Pod worker node type
```suggestion
### Change the worker node type
```

2023-03-15 19:24 UTC, merged