Test DAGs guide update
astronomer/docs pull request #1814
Opened 2023-01-30 12:04 UTC by TJaniF

- Modernized the section on pytest to include the Astro CLI command
- Added an example on how to create pytests at the task level
- Added a chapter on `dag.test()` addressing #1730 
- Added an example of a GitHub Actions workflow using `astro dev pytest` (this is something I had been looking for before)
- Rewrote the `Data integrity testing` to use the term `data quality checks` and linked out to data quality related guides, tutorials and blog posts.

I did not touch the Unit testing and Mocking section, since I think nothing changed on those topics (though I am definitely not an expert).

2023-01-30 18:11 UTC, kentdanas requested changes
Looks great @TJaniF, thanks for this update! Requesting changes to potentially rearrange some of the newly added sections. Otherwise just minor comments.

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +The most commonly run DAG validation test is to check for import errors using the `.import_errors` attribute of the initialized `DagBag` model. The code below shows a complete testing suite collectin
```suggestion
The most common DAG validation test is to check for import errors using the `.import_errors` attribute of the initialized `DagBag` model. The code below shows a complete testing suite collecting DAG import errors. 
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +Airflow 2.5.0 introduced the possibility to set up the `dag.test()` command directly in the DAG file to run through all tasks in a DAG within a single serialized Python process, allowing for faster f
```suggestion
Airflow 2.5.0 introduced the `dag.test()` command, which runs directly in the DAG file and allows you to run all tasks in a DAG within a single serialized Python process. This allows for faster iteration when developing DAGs.
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +You can set up `dag.test()` by adding two lines at the end of the DAG file. If you are using a traditional DAG context call `.test()` on the object the context is assigned to, if you are using the `@
```suggestion
You can set up `dag.test()` by adding two lines at the end of the DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If you are using the `@dag` decorator, call the method on a call of the decorated function. 
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +You can run the `.test()` method on all tasks in an individual DAG by executing `python <path to dag file>.py` from the command line within your Airflow environment (locally if you are running a stan
```suggestion
You can run the `.test()` method on all tasks in an individual DAG by executing `python <path to dag file>.py` from the command line within your Airflow environment, locally if you are running a standalone Airflow instance, or within the Docker container if you are running Airflow in Docker.
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +In order to get an interactive debugging experience use
```suggestion
To take advantage of `pdb` ([The Python Debugger](https://docs.python.org/3/library/pdb.html)), an interactive source code debugger, and get an interactive debugging experience, you can run:
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +`pdb` is [The Python Debugger](https://docs.python.org/3/library/pdb.html), an interactive source code debugger.
```suggestion
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +- [airflow dags test](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test): Executes one single DagRun for a given DAG and execution date and writes the result t
```suggestion
- [`airflow dags test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test): Executes one single DagRun for a given DAG and execution date and writes the result to the metadata database. This command is useful for testing full DAGs by creating manual Dagruns from the command line.
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +- [airflow tasks test](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test_repeat1): Tests one specific task instance without checking for dependencies or record
```suggestion
- [`airflow tasks test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test_repeat1): Tests one specific task instance without checking for dependencies or recording the outcome in the metadata database. This command is useful for troubleshooting issues with specific tasks.
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +If you are using the Astro CLI you can run all Airflow CLI commands without entering the Docker container by using [`astro dev run`](https://docs.astronomer.io/astro/cli/astro-dev-run). For example t
```suggestion
With the Astro CLI, you can run all Airflow CLI commands without entering the Docker container by using [`astro dev run`](https://docs.astronomer.io/astro/cli/astro-dev-run). For example, to run `airflow dags test` on the DAG `my_dag` for the execution date of `2023-01-29` run:
```

2023-01-30 18:11 UTC, kentdanas commented on learn/testing-airflow.md
> +### CI/CD with the Astro CLI
Maybe we should link to our CICD docs from this section for any Astro users?

2023-01-31 15:36 UTC, TJaniF reviewed
Thank you @kentdanas :) I accepted all suggestions and tried to restructure the DAG validation section as you suggested.

2023-01-31 16:03 UTC, kentdanas approved these changes
Thanks @TJaniF, I think this structure looks much better! One other minor comment, otherwise good to move on to copy review.

2023-01-31 16:03 UTC, kentdanas commented on learn/testing-airflow.md
> +#### Astro dev pytest
Thinking about Dylan's comment in Slack....maybe we should rename this section to The Astro CLI and also mention `astro dev parse` briefly and then link out to the Astro docs https://docs.astronomer.io/astro/test-and-troubleshoot-locally#run-tests-with-the-astro-cli.

2023-02-01 14:47 UTC, TJaniF commented on learn/testing-airflow.md
> +#### Astro dev pytest
Thank you! I somehow was unaware of `astro dev parse` before seeing Dylan's comment. 😳 Rewrote that section to include both commands and link out. I also a added a link to that Astro Doc in the debugging guide.

@jwitz I think this is ready for your review :)

2023-02-01 14:58 UTC, jwitz requested changes
Looks good @TJaniF ! Requesting changes because I'd like to see more clarity around using `dags.test` and running commands from within Airflow.

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +#### Set custom DAG requirements
```suggestion
#### Check for custom code requirements
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +The code snippet below shows a test which checks that all DAGs have their `tags` parameter set to one or more of the `APPROVED_TAGS`.
```suggestion
The code snippet below includes a test which checks that all DAGs have their `tags` parameter set to one or more of the `APPROVED_TAGS`.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +#### Set custom task requirements
```suggestion
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +
```suggestion
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +Airflow offers different ways to run DAG validation tests. This section gives an overview over the most common implementation methods. If you are new to testing Airflow DAGs we recommend to use `astr
```suggestion
Airflow offers different ways to run DAG validation tests. This section gives an overview over the most common implementation methods.
```
This sentence feels a little bit out of place, I think it makes more sense to include in the next section.

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +Airflow allows you to define testing suites using any Python test runner. You can run these suites by executing `python my_test_suite.py` from the command line within your Airflow environment (locall
```suggestion
```
If you go with Kenten's suggestion above, I would move this to the Airflow CLI section

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +When using the [Astro CLI]((https://docs.astronomer.io/astro/cli/install-cli)) every new Astro project will be initialized with a `test/dags` folder in your Astro project directory. This folder conta
```suggestion
When you create a new project with the [Astro CLI]((https://docs.astronomer.io/astro/cli/install-cli)), the project includes a `test/dags` folder. This folder contains a default `test_dag_integrity.py` script containing several example pytests. This is also where you can add your own custom pytests.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +You can run `astro dev pytest` to run all pytest test suites in the `test` directory of your current Airflow project (see also the [Astro CLI reference](https://docs.astronomer.io/astro/cli/astro-dev
```suggestion
Run [`astro dev pytest`](https://docs.astronomer.io/astro/cli/astro-dev-pytest) to run all pytests in the `test` directory. You don't need to start Airflow to use this command, so you can quickly run it as part of a CI/CD pipeline or any other process with limited resources.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +```python
```suggestion
```python{14-15}
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +```python
This will highlight the code in the code block, so we can skip out on the comment in the DAG!

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +# Added statement at the end of the DAG
```suggestion
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +# Added statement at the end of the DAG
```suggestion
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
>  ```python
Can we use tabs here?

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +You can run the `.test()` method on all tasks in an individual DAG by executing `python <path to dag file>.py` from the command line within your Airflow environment, locally if you are running a stan
```suggestion
You can run the `.test()` method on all tasks in an individual DAG by executing `python <path-to-dag-file>` from the command line within your Airflow environment. You would execute this locally if you are running a standalone Airflow instance, or within the Docker container if you are running Airflow in Docker.
```
The Docker container for which component? What's the fastest way to do this with the Astro CLI?

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +
```suggestion
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +To take advantage of `pdb` ([The Python Debugger](https://docs.python.org/3/library/pdb.html)), an interactive source code debugger, and get an interactive debugging experience, you can run:
```suggestion
Use `pdb` ([The Python Debugger](https://docs.python.org/3/library/pdb.html)), an interactive source code debugger, by running:
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +### Implementing DAG validation tests
```suggestion
## Implementing DAG validation tests
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +#### The Astro CLI
```suggestion
### The Astro CLI
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +#### dag.test()
```suggestion
### dag.test()
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +#### Airflow CLI
```suggestion
### Airflow CLI 
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +- [`airflow dags test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test): Executes one single DagRun for a given DAG and execution date and writes the result
```suggestion
- [`airflow dags test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test): Given a DAG ID and execution date, this command writes the results of a single DAG run to the metadata database. This command is useful for testing full DAGs by creating manual DAG runs from the command line.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +- [`airflow tasks test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test_repeat1): Tests one specific task instance without checking for dependencies or reco
```suggestion
- [`airflow tasks test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test_repeat1): This command tests one specific task instance without checking for dependencies or recording the outcome in the metadata database.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +With the Astro CLI, you can run all Airflow CLI commands without entering the Docker container by using [`astro dev run`](https://docs.astronomer.io/astro/cli/astro-dev-run). For example, to run `air
```suggestion
With the Astro CLI, you can run all Airflow CLI commands using [`astro dev run`](https://docs.astronomer.io/astro/cli/astro-dev-run). For example, to run `airflow dags test` on the DAG `my_dag` for the execution date of `2023-01-29` run:
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +With the Astro CLI, you can run all Airflow CLI commands without entering the Docker container by using [`astro dev run`](https://docs.astronomer.io/astro/cli/astro-dev-run). For example, to run `air
The command still runs in the Docker container tho right?

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +### CI/CD with the Astro CLI
```suggestion
### Test DAGs in a CI/CD pipeline
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +You can use any CI/CD tool on Airflow code. A common use case is to run the `astro dev pytest` for all pytests in the `tests` directory every time a push or PR to a specific branch in your source con
```suggestion
You can use any CI/CD tool on Airflow code. A common use case is to run the `astro dev pytest` for all pytests in the `tests` directory every time someone pushes code to a specific branch in your repository.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +Below shows an example of a GitHub Action workflow which will install the Astro CLI and use it to run `astro dev pytest` on every push to the `main` branch.
```suggestion
The following is an example GitHub Action workflow which installs the Astro CLI and runs `astro dev pytest` on every push to the `main` branch.
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +If you are an Astronomer customer you can find further information on how to set up CI/CD with your Astro deployment in [our docs](https://docs.astronomer.io/astro/ci-cd).
```suggestion
If you are an Astro customer, you can find further information on how to set up CI/CD to your Astro deployment in [CI/CD](https://docs.astronomer.io/astro/ci-cd).
```

2023-02-01 14:58 UTC, jwitz commented on learn/testing-airflow.md
> +Data quality checks work better at scale if you design your DAGs to load or process data incrementally. To learn more about incremental loading, see [DAG Writing Best Practices in Apache Airflow](dag
Move this before the "Learn more" section"

2023-02-01 16:55 UTC, kentdanas commented on learn/testing-airflow.md
> +## Python test runners
I would keep this where it is. `pytest` isn't a form of validation testing, it's a Python testing framework. It could be used for validation testing, but could also be used for unit testing and mocking. We had this upfront in the original guide just to highlight that while we use `pytest` in this guide, there are other test runners that would work with Airflow and which you choose is a matter of preference.

2023-02-01 17:19 UTC, kentdanas commented on learn/testing-airflow.md
> +## Python test runners
sorry @TJaniF if you already moved this 😅

2023-02-01 21:49 UTC, TJaniF commented on learn/testing-airflow.md
> +## Python test runners
Haha, not much work to move it back 😅

2023-02-02 14:11 UTC, jwitz approved these changes
Just a few more minor suggestions, but other than that LGTM!

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +Every new Astro project will be initialized with a `test/dags` folder in your Astro project directory. This folder contains the `test_dag_integrity.py` script defining several examples of using `pyte
```suggestion
Every new Astro project will be initialized with a `test/dags` folder in your Astro project directory. This folder contains the `test_dag_integrity.py` script defining several examples of using `pytest` with Airflow. For more information on the Astro CLI's testing capabilities, see [Test and troubleshoot locally](https://docs.astronomer.io/astro/test-and-troubleshoot-locally#test-dags-with-the-astro-cli).
```

2023-02-02 14:11 UTC, jwitz commented on learn/debugging-dags.md
>  This guide was written for Airflow 2. If you are running Airflow 1.15 or earlier, we highly recommend upgrading to prevent compatibility issues and receive the latest bug fixes. For assistance in upg
```suggestion
This guide was written for Airflow 2. If you are running Airflow 1.15 or earlier, upgrade to prevent compatibility issues and receive the latest bug fixes. For assistance in upgrading see the documentation on [Upgrading from 1.10 to 2](https://airflow.apache.org/docs/apache-airflow/stable/howto/upgrading-from-1-10/index.html).
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +All types of test runners can be used with Airflow. In this guide we will use `pytest`.
```suggestion
All types of test runners can be used with Airflow. The examples in this guide use `pytest`.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +If you are new to testing Airflow DAGs we recommend to get started using the commands provided by the Astro CLI.
```suggestion
Airflow offers different ways to run DAG validation tests using any Python test runner. This section gives an overview of the most common implementation methods. If you are new to testing Airflow DAGs, you can quickly get started by using Astro CLI commands.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +You can run the `.test()` method on all tasks in an individual DAG by executing `python <path-to-dag-file>` from the command line within your Airflow environment. You would execute this locally if yo
```suggestion
You can run the `.test()` method on all tasks in an individual DAG by executing `python <path-to-dag-file>` from the command line within your Airflow environment. You can also run this command locally if you are running a standalone Airflow instance, or within the scheduler container if you are running Airflow in Docker.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +Airflow allows a great deal of DAG customization. It is common for data engineering teams to define best practices and custom rules around how their DAGs should be written and create DAG validation t
```suggestion
Airflow DAGs support many types of custom plugins and code. It is common for data engineering teams to define best practices and custom rules around how their DAGs should be written and create DAG validation tests to ensure those standards are met.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +We recommend at a minimum including a DAG validation test to check for [import errors](#prevent-import-errors). Additional tests can check things like custom logic, ensuring that `catchup` is set to
```suggestion
At a minimum, you should run DAG validation tests to check for [import errors](#prevent-import-errors). Additional tests can check things like custom logic, ensuring that `catchup` is set to False for every DAG in your Airflow instance, or making sure only `tags` from a defined list are used in the DAGs.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +You can use any CI/CD tool on Airflow code. A common use case is to run the `astro dev pytest` for all pytests in the `tests` directory every time someone pushes code to a specific branch in your rep
```suggestion
You can use CI/CD tools to test and deploy your Airflow code. A common use case is to run the `astro dev pytest` for all pytests in the `tests` directory every time someone pushes code to a specific branch in your repository.
```

2023-02-02 14:11 UTC, jwitz commented on learn/testing-airflow.md
> +:::
```suggestion
If you are an Astro customer, you can find further information on how to set up CI/CD to your Astro deployment in [CI/CD](https://docs.astronomer.io/astro/ci-cd).
```

2023-02-02 15:28 UTC, TJaniF reviewed
Thanks @jwitz :)

2023-02-02 15:28 UTC, TJaniF commented on learn/testing-airflow.md
> +## Python test runners
This would work for me. :)

Maybe as the second prereq bulletpoint? Something like:

```
To get the most out of this guide, you should have an understanding of:

- Python testing basics. See [Getting Started with Testing in Python](https://realpython.com/python-testing/).
- At least one Python test runner. This guide mostly uses [pytest](https://docs.pytest.org/en/stable/index.html), but you can use others including [`nose2`](https://docs.nose2.io/en/latest/getting_started.html) and [`unittest`](https://docs.python.org/3/library/unittest.html).
```

I changed it to 'mostly uses' because the Unittest section that I did not edit uses `unittest` instead of `pytest`. 

Would this work for you too @kentdanas ? :)

2023-02-02 15:28 UTC, TJaniF commented on learn/testing-airflow.md
> +## Interactive debugging with dag.test()
Pdb works with breakpoints in the code where the execution of the dag will hold and then you can do things like print out the current value for specific variables in this moment or fetch the source code of a function and other things I haven't used yet :)

2023-02-02 18:29 UTC, kentdanas commented on learn/testing-airflow.md
> +## Python test runners
Yep, works for me!

2023-02-02 23:48 UTC, merged