Software 0.31.2 release notes
astronomer/docs pull request #1816
Opened 2023-01-31 11:39 UTC by jwitz

2023-01-31 11:41 UTC, jwitz commented on software/release-notes.md
> +- Errors related to the git-sync Kubernetes pod now appear in the Astro UI (potentially not in release)
Saw this one in the issues list but with no attached PR. Did we make this change?

2023-01-31 12:44 UTC, kwcanuck commented on software/release-notes.md
> +- Added support for [Kubernetes 1.25](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/).
```suggestion
- Support for [Kubernetes 1.25](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/).
```

2023-01-31 12:46 UTC, kwcanuck commented on software/release-notes.md
> +- You can now configure custom annotations for Houston ingress by setting `astronomer.houston.ingress.annotation` in your `config.yaml` file.
```suggestion
- You can now use `astronomer.houston.ingress.annotation` in your `config.yaml` file to configure custom annotations for Houston ingress. 
```

2023-01-31 12:47 UTC, kwcanuck commented on software/release-notes.md
> +- The System Admin **Deployments** list in the Astronomer UI is now paginated.
```suggestion
- The System Admin **Deployments** list in the Cloud UI is now paginated. 
```

2023-01-31 12:50 UTC, kwcanuck commented on software/release-notes.md
> +- Errors related to the git-sync Kubernetes pod now appear in the Astro UI (potentially not in release)
```suggestion
- Errors related to the git-sync Kubernetes pod now appear in the Cloud UI (potentially not in release)
```

2023-01-31 12:51 UTC, kwcanuck commented on software/release-notes.md
> +- PgBouncer now utilizes graceful shutdowns.
```suggestion
- PgBouncer now gracefully shuts down.
```

2023-01-31 12:55 UTC, kwcanuck commented on software/release-notes.md
> +- You can now tune the git-sync relay service's resource usage by setting the following values in your `config.yaml` file:
```suggestion
- You can now use the following values in your `config.yaml` file to configure resource allocation for the git-sync relay service:
```

2023-01-31 12:55 UTC, kwcanuck commented on software/release-notes.md
> +- You can now set `timeoutSeconds` for both `readinessProbe` and `livenessProbe` in the Prometheus Helm chart.
```suggestion
- You can now set `timeoutSeconds` for `readinessProbe` and `livenessProbe` in the Prometheus Helm chart.
```

2023-01-31 12:56 UTC, kwcanuck commented on software/release-notes.md
> +- Fixed an issue where Deployments with many DAGs could not be successfully upgraded due to a short timeout.
```suggestion
-  Deployments with many DAGs are now upgraded after a short timeout.
```

2023-01-31 12:57 UTC, kwcanuck commented on software/release-notes.md
> +- Houston API now logs an installation's deployed image versions whenever a GraphQL mutation is completed.
```suggestion
- The Houston API now logs a deployed image version for installations whenever a GraphQL mutation is completed.
```

2023-01-31 12:59 UTC, kwcanuck commented on software/release-notes.md
> +- Fixed an issue where a user deactivated through SCIM would leave behind orphan Deployments and Workspaces.
```suggestion
- Fixed an issue where orphan Deployments and Workspaces remained when users were deactivated with SCIM. 
```

2023-01-31 13:04 UTC, kwcanuck commented on software/release-notes.md
> +- Database migrations for a Deployment now use the same amount of resources as configured for the Deployment's scheduler. This should limit OOM errors when migrating large DAGs.
```suggestion
- To limit Out of Memory (OOM) errors when migrating large DAGs, Deployment database migrations now use the same resources that are configured for the Deployment's scheduler. .
```

2023-01-31 13:07 UTC, kwcanuck approved these changes

2023-01-31 22:31 UTC, danielhoherd commented on software/release-notes.md
> +- Errors related to the git-sync Kubernetes pod now appear in the Astro UI (potentially not in release)
This was moved out of this release.

2023-01-31 22:32 UTC, danielhoherd commented on software/release-notes.md
> +- Added support for [Kubernetes 1.25](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/).
FWIW we also added support for k8s 1.26

2023-01-31 22:33 UTC, danielhoherd commented on software/release-notes.md
> +- PgBouncer now utilizes graceful shutdowns.
We've removed this feature from this release.

2023-01-31 22:35 UTC, danielhoherd commented on software/release-notes.md
> +- Fixed an issue where Deployments with many DAGs could not be successfully upgraded due to a short timeout.
The suggested wording is incorrect. The problem was that DAGs were not upgraded because the timeout was too short. The timeout has been lengthened.

2023-01-31 22:38 UTC, danielhoherd commented on software/release-notes.md
> +- Houston API now logs an installation's deployed image versions whenever a GraphQL mutation is completed.
This suggested wording is incorrect. The API doesn't log the image version for installations. Whenever a GraphQL mutation is completed (which happens frequently during normal operation) houston logs the running docker image versions.

2023-01-31 22:42 UTC, danielhoherd commented on software/release-notes.md
> +- Service accounts and users can no longer create users through the Houston API when SCIm is enabled.
I think it is. When SCIM is enabled, houston-api will no longer allow users or service accounts to create users.

2023-02-02 12:03 UTC, rishkarajgi requested changes

2023-02-02 12:03 UTC, rishkarajgi commented on software/release-notes.md
> +- Fixed an issue where orphan Deployments and Workspaces remained when users were deactivated with SCIM.
This is moved to the next patch release. Please omit

2023-02-02 12:03 UTC, rishkarajgi commented on software/release-notes.md
> +- When SCIM is enabled, service accounts and users can no longer create users through the Houston API.
This is moved to the next patch release. Please omit

2023-02-02 13:32 UTC, jwitz commented on software/release-notes.md
> +Release date: February 1, 2023
```suggestion
Release date: February 2, 2023
```

2023-02-02 17:06 UTC, rishkarajgi approved these changes

2023-02-02 23:06 UTC, danielhoherd approved these changes

2023-02-02 23:29 UTC, danielhoherd commented
FYI 0.31.2 has been released to the public helm repo. <https://astronomer.slack.com/archives/C020PVBJPKK/p1675380532198119>

2023-02-03 10:00 UTC, merged