Update Code Syntax in Alerting in Astronomer Software
astronomer/docs pull request #1822
Opened 2023-02-01 12:36 UTC by kwcanuck

In this [Slack conversation](https://astronomer.slack.com/archives/C015V2JFKT5/p1675211068787069), @afastronomer requested that instances of `platform:` be updated to `platform: |`.

2023-02-01 17:11 UTC, afastronomer requested changes
Fix is required only for Prometheus (additionalAlerts), Alertmanager (receivers) config has to be unchanged.

2023-02-01 17:21 UTC, kwcanuck commented
@afastronomer the docs have been updated as you requested. Please review and unblock the PR. Thanks!

2023-02-01 17:24 UTC, afastronomer approved these changes

2023-02-01 17:25 UTC, kwcanuck commented
@jwitz a quick review for you - I hope!

2023-02-03 14:24 UTC, jwitz approved these changes

2023-02-03 14:24 UTC, jwitz commented on software/platform-alerts.md
> +    platform:
```suggestion
    platform: |
```
Do we need one here as well?

2023-02-03 14:30 UTC, kwcanuck commented on software/platform-alerts.md
> +    platform:
@jwitz as Artem indicated "Alertmanager (receivers) config has to be unchanged".

2023-02-03 16:26 UTC, merged