Consolidate Cluster Documentation
astronomer/docs pull request #1823
Opened 2023-02-01 14:53 UTC by kwcanuck

Resolves #1820, Resolves #1904

2023-02-01 15:00 UTC, kwcanuck commented
@jwitz I made an attempt at consolidating some of the existing cluster documentation. Feel free to keep, modify, or discard any of the changes I've implemented.

2023-02-02 15:43 UTC, jwitz requested changes
@kwcanuck I have a high level comment about the doc structure, let me know what you think. Once we resolve that I'll take a look more closely at the language in each section. Thanks!

2023-02-02 15:51 UTC, kwcanuck commented on astro/modify-cluster.md
> +## Modify a cluster
@jwitz the changes have been implemented and the structure appears to match what you're suggesting. I'm not clear what you mean by _the "Contact Astronomer support" step should be repeated wherever applicable throughout the guides_. Can you clarify? Alternatively, adjust the documentation to meet your requirements. Thanks!

2023-02-02 17:26 UTC, jwitz commented on astro/modify-cluster.md
> +## Modify a cluster
Do you need to push up any local changes? I'm not seeing the updated structure.

For my "Contact Astronomer support" point, I just meant that each cluster modification topic should have its own isolated steps without linking out to a "request and confirm a cluster change" opic.

2023-02-07 19:35 UTC, kwcanuck commented
@paolaperaza did you want to complete a review before these changes are merged?

2023-02-15 12:20 UTC, jwitz commented
@kwcanuck Idk if Paola's GitHub notifications are on yet, probably better to ping her in Slack on this.

2023-02-15 12:29 UTC, kwcanuck commented
@jwitz unfortunately, I _have_ pinged Paola numerous times on Slack about this PR:

![image](https://user-images.githubusercontent.com/104205257/219027407-7fe20dd1-393e-415a-9bf6-f8bcbd74fd8e.png)

![image](https://user-images.githubusercontent.com/104205257/219027462-6c3b3c67-1f1e-4567-b518-8e3429fe5d65.png)

I'll try again today.

2023-02-17 15:35 UTC, jwitz approved these changes

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +After you authorize Workspaces to a cluster, Astro treats the Cluster as restricted. Restricted clusters appear as an option when creating a new Deployment only if the Deployment's Workspace is autho
```suggestion
After you authorize Workspaces to a cluster, Astro treats the cluster as restricted. Restricted clusters appear as an option when creating a new Deployment only if the Deployment's Workspace is authorized to the cluster. 
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +Maximum node count is different than **Maximum Worker Count**, which is configured for each worker queue and determines the maximum total number of nodes that a worker queue within a single Deploymen
```suggestion
Maximum node count is different than **Maximum Worker Count**, which is configured within the Cloud UI for each worker queue and determines the maximum total number of nodes that the worker queue can scale to. Maximum node count for a node pool must always be equal to or greater than the sum of all maximum possible workers across all worker queues that are configured with that worker node type.
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +Individual worker nodes are dedicated to a single Deployment, but a worker node pool can have worker nodes for multiple Deployments. For example, a cluster with a node pool for `m5.2xlarge` nodes mig
```suggestion
Individual worker nodes run only on a single Deployment, but a worker node pool can have worker nodes spread across multiple Deployments.
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +Individual worker nodes are dedicated to a single Deployment, but a worker node pool can have worker nodes for multiple Deployments. For example, a cluster with a node pool for `m5.2xlarge` nodes mig
I didn't think the example here added much besides lending a node type to work with.

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +Creating a worker node pool does not necessarily mean that the infrastructure is created in your cluster. For example, you can create a worker node pool to allow your team to use that worker type whe
```suggestion
Creating a worker node pool does not necessarily mean that the infrastructure is created in your cluster. A worker node pool has zero nodes if any of the following are true:
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +For example, if:
```suggestion
For example, consider the following configurations within a cluster:
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +- The maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit.
```suggestion

In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit.
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +To change the maximum node count for a node pool, contact [Astronomer Support](https://cloud.astronomer.io/support).
```suggestion

To change the maximum node count for a node pool, contact [Astronomer Support](https://cloud.astronomer.io/support).
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +A worker type on Astro is a node pool in your cluster that consists of worker nodes of the same node instance type. On Astro, worker nodes execute Airflow tasks. Each worker node pool can be configur
```suggestion
On Astro, worker nodes execute Airflow tasks. Workers are organized through worker node pools, which are sets of configurations that Astro uses to scale up and down workers of a specific instance type. Each worker node pool can be configured with a node instance type and a maximum node count. 

To have a Deployment run Airflow tasks with a specific worker type, you need to work with Astronomer support to create a worker node pool for that worker type on the cluster hosting the Deployment. Then, you can configure a Deployment worker queue to use that worker type. Contact [Astronomer support](https://support.astronomer.io) with the name of the worker type(s) you want to enable in your cluster. For example, `m6i.2xlarge`.
```

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +To create or modify a worker type, contact [Astronomer Support](https://cloud.support.astronomer.io). To learn more about worker queues, see [Configure worker queues](configure-worker-queues.md).
```suggestion
```

We mention these steps above, I think it's better to keep this section as reference?

2023-02-17 15:35 UTC, jwitz commented on astro/modify-cluster.md
> +To create or modify a worker type, contact [Astronomer Support](https://cloud.support.astronomer.io). To learn more about worker queues, see [Configure worker queues](configure-worker-queues.md).
```suggestion
```

We mention these steps above, I think it's better to keep this section as reference?

2023-02-17 15:50 UTC, paolaperaza approved these changes

2023-02-17 16:21 UTC, paolaperaza approved these changes

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +To confirm a modification was completed, click the **Clusters** tab in the Cloud UI and then click the **Worker Types** tab to view updated configuration information.
```suggestion
To confirm that the worker type was added, click the **Clusters** tab in the Cloud UI and then click the **Worker Types** tab to view your new worker type.
```

Is it confusing that we're giving users the instruction to do this even though:
- They don't yet know how to think about worker types
- They'll need to provide maximum node count too

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +
```suggestion
```

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +All Astro clusters have one worker node pool for one worker type by default, but you can configure up to 30 additional worker types. After Astronomer creates a worker node pool for a cluster, your te
```suggestion
All Astro clusters have one worker node pool for one worker type by default, but you can configure up to 30 additional worker types. After Astronomer creates a worker node pool for a cluster, your team can configure a worker queue in any Deployment with that worker type. The worker type appears as a new option on the **Worker Type** page of the Cloud UI and as an option in the Astro CLI. If your cluster only has one worker type, all tasks across Deployments in your cluster can only run on that type of worker.
```

Work in that the Worker Type view is part of the worker queue config for a Deployment?

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +Individual worker nodes run only on a single Deployment, but a worker node pool can have worker nodes spread across multiple Deployments.
Move this to paragraph above instead of on its own?

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +Each worker type on Astro is configured with a node instance type that is defined by your cloud provider. For example, `m5.2xlarge` on AWS, `Standard_D8_v5` on Azure, or `e2-standard-8` on GCP. Node
```suggestion
Each worker type on Astro is configured with a node instance type that is defined by your cloud provider. For example, `m5.2xlarge` on AWS, `Standard_D8_v5` on Azure, or `e2-standard-8` on GCP. Node instance types are comprised of varying combinations of CPU, memory, storage, and networking capacity. By choosing an instance type and having workers with different instance types, you can provide the appropriate balance of resources for your Airflow tasks. This might make your DAGs execute faster and more reliably.
```

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +To modify the node instance type of an existing worker node pool, contact [Astronomer Support](https://cloud.support.astronomer.io). For the list of worker types available on Astro, see [AWS](resourc
Double check these links

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +To confirm a modification was completed, click the **Clusters** tab in the Cloud UI and then click the **Worker Types** tab to view updated configuration information.
Link to WQ docs?

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +For the list of database instance types available on Astro, see [AWS](resource-reference-aws.md#rds-instance-type), [Azure](resource-reference-azure.md#db-instance-type), or [GCP](resource-reference-
Double check links -- I think these sections don't actually exist yet :) https://github.com/astronomer/docs/issues/1904

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> +As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific clusters. You can gain greater control over cloud your resources by ensuring that only au
```suggestion
As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific clusters. You can gain greater control over your cloud resources by ensuring that only authorized pipelines are running on specific clusters.
```

2023-02-17 16:21 UTC, paolaperaza commented on astro/modify-cluster.md
> -As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific Clusters. Gain greater management over cloud resources by ensuring that only authorized p
I actually still think we're not doing an amazing job of giving examples/explaining WHY a customer does this -- is it to protect production clusters from having noisy dev Deployments? To keep teams isolated/be able to charge them $$ independently? Is it a user permissions things?

We should keep looping with @chomipi88 on this to get there

2023-02-17 16:21 UTC, paolaperaza commented on astro/resource-reference-aws.md
> +## Supported worker node pool instance types
```suggestion
## Supported worker types
```

Double check links if we've changed this

2023-02-17 16:21 UTC, paolaperaza commented on astro/resource-reference-azure.md
> +| Worker node pool                                                                                                         | A node pool that hosts all workers with the `default` worker type for all
Double check link

2023-02-17 16:25 UTC, jwitz commented on astro/modify-cluster.md
> +All Astro clusters have one worker node pool for one worker type by default, but you can configure up to 30 additional worker types. After Astronomer creates a worker node pool for a cluster, your te
Made an edit to reflect this

2023-02-17 16:29 UTC, jwitz commented on astro/modify-cluster.md
> -As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific Clusters. Gain greater management over cloud resources by ensuring that only authorized p
I added a suggestion below in your comment, but I actually think "keep teams and projects isolated " is a pretty elegant phrase to cover a lot of the use cases you mention.

2023-02-17 17:09 UTC, kwcanuck commented on astro/modify-cluster.md
> +If you don't have a cluster on Astro, see [Install Astro](https://docs.astronomer.io/astro/category/install-astro). If you have an existing cluster and you want to create additional clusters, see [Cr
@paolaperaza doc links relocated.

2023-02-17 17:15 UTC, kwcanuck commented on astro/modify-cluster.md
> +Individual worker nodes run only on a single Deployment, but a worker node pool can have worker nodes spread across multiple Deployments.
@paolaperaza modified the text as requested.

2023-02-17 17:29 UTC, kwcanuck commented on astro/modify-cluster.md
> +To modify the node instance type of an existing worker node pool, contact [Astronomer Support](https://cloud.support.astronomer.io). For the list of worker types available on Astro, see [AWS](resourc
@paolaperaza the links have been updated.

2023-02-17 19:13 UTC, kwcanuck commented on astro/resource-reference-azure.md
> +| Worker node pool                                                                                                         | A node pool that hosts all workers with the `default` worker type for all
@paolaperaza the link has been updated.

2023-02-17 19:16 UTC, kwcanuck commented on astro/resource-reference-aws.md
> +## Supported worker node pool instance types
@paolaperaza redirects have been added for this change

2023-02-17 19:59 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +## DB Instance Type
We should document the options available here. Similar to what we've done for AWS RDS. See options in https://github.com/astronomer/docs/issues/1904

2023-02-17 19:59 UTC, chomipi88 commented on astro/resource-reference-gcp.md
> +## DB Instance Type
We should document the options available here. Similar to what we've done for AWS RDS. See options in https://github.com/astronomer/docs/issues/1904

2023-02-17 19:59 UTC, chomipi88 commented on astro/resource-reference-gcp.md
> +Cloud SQL is supported on Astro. See [Cloud SQL)](https://cloud.google.com/sql).
```suggestion
Cloud SQL is supported on Astro. See [Cloud SQL](https://cloud.google.com/sql).
```

2023-02-17 19:59 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +Azure Database for PostgreSQL is supported on Astro. See [Azure Database for PostgreSQL documentation)](https://learn.microsoft.com/en-us/azure/postgresql/).
```suggestion
Azure Database for PostgreSQL is supported on Astro. See [Azure Database for PostgreSQL documentation](https://learn.microsoft.com/en-us/azure/postgresql/).
```

2023-02-17 20:17 UTC, kwcanuck commented on astro/resource-reference-azure.md
> +## DB Instance Type
@chomipi88 I have added the available options.

2023-02-17 20:18 UTC, kwcanuck commented on astro/resource-reference-gcp.md
> +## DB Instance Type
@chomipi88 I added the available options.

2023-02-17 20:32 UTC, chomipi88 commented on astro/modify-cluster.md
> +For the list of database instance types available on Astro, see [AWS](resource-reference-aws.md#rds-instance-type), [Azure](resource-reference-azure.md#db-instance-type), or [GCP](resource-reference-
AWS link is not accurate

2023-02-17 20:32 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +- Standard_E4ds_v4 (CPU 4, 32 GiB MEM)
Order them from smallest to largest per SKU type.

D2ds_v4
D4ds_v4
E2ds_v4
E4ds_v4

Also CPU count should go first (eg. 4 CPU)

2023-02-17 20:32 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +## DB Instance Type
Sync up the styling with the tables for Worker instance types at some point. Looks odd to have it in one section and not the other. Feedback applies for all 3 clouds.

2023-02-17 20:52 UTC, chomipi88 approved these changes

2023-02-17 20:52 UTC, chomipi88 commented on astro/modify-cluster.md
> +As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific clusters. You can gain greater control over cloud your resources by ensuring that only au
```suggestion
As an Organization Owner, you can keep teams and projects isolated by authorizing Workspaces only to specific clusters. You can gain greater control over your cloud resources by ensuring that only authorized pipelines are running on specific clusters.
```

2023-02-17 20:55 UTC, kwcanuck commented on astro/modify-cluster.md
> +For the list of database instance types available on Astro, see [AWS](resource-reference-aws.md#rds-instance-type), [Azure](resource-reference-azure.md#db-instance-type), or [GCP](resource-reference-
@chomipi88 I have updated the links. Thank you!

2023-02-17 20:58 UTC, kwcanuck commented on astro/modify-cluster.md
> +For the list of database instance types available on Astro, see [AWS](resource-reference-aws.md#rds-instance-type), [Azure](resource-reference-azure.md#db-instance-type), or [GCP](resource-reference-
@paolaperaza I have updated the links and verified they work.

2023-02-17 21:08 UTC, merged