Updated Cloud and Enterprise CLI quickstart guides
astronomer/docs pull request #185
Opened 2021-01-06 15:11 UTC by jwitz

This PR addresses the CLI Quickstart portion of this issue: https://app.zenhub.com/workspaces/documentation-5fcfce583ed44e0011db3db5/issues/astronomer/docs/179

It does _not_ address the long-term improvements we hope to make to our CLI guides, such as removing content that's redundant with the general CLI. The only new changes here are a slight reorganization from lettered to numbered steps in Step 3 and Step 4. Otherwise, this was a fairly straightforward port from Cloud to Enterprise.

2021-01-06 15:11 UTC, jwitz commented on cloud/stable/02_develop/01_cli-quickstart.md
> +This command will spin up 3 Docker containers on your machine, each for a different Airflow component:
I indented these lines by one space, which allowed the bulleted list to appear indented along with the steps in my Markdown preview. In the future, how should we style these?

2021-01-07 19:02 UTC, paolaperaza requested changes
@jwitz This looks great! I left a couple of small comments. The two high-level questions I have:

1. Will you port over to 0.16 once we land on the final version of `/next`?
2. Do you want to double check the spacing you have after some commands referenced in bulleted lists? In "Preview" they show as having a space after the command, but in raw Markdown it looks all jumbled and it'd be nice to clean up.

For example, should there be a space after "command" here? -

```
1. Create a new directory on your machine by running the following command:
```sh
$ mkdir <directory-name> && cd <directory-name>
```

2021-01-07 19:32 UTC, jwitz commented on cloud/stable/02_develop/01_cli-quickstart.md
> + For guidelines on accessing your Postgres database both locally and on Astronomer, refer to the [Access Airflow Database](/docs/cloud/stable/customize-airflow/access-airflow-database/) guide.
Not sure how the first reference got in, since it clearly only makes sense in the latter reference. Fixed.

2021-01-07 19:34 UTC, jwitz commented on enterprise/next/02_develop/01_cli-quickstart.md
> +- Append annotations to your Deployment's Pods (Enterprise only)
I still worry that Cloud users might accidentally end up on the Enterprise page and not have enough info to know they're looking at that docset. To remedy this, I changed a line above to say "If you're an Astronomer _Enterprise_ user, you might..." so that the distinction is clear.

2021-01-07 19:48 UTC, jwitz commented on enterprise/next/02_develop/01_cli-quickstart.md
> +> **Note**: Running `$ astro dev start` will start your project with the Airflow Webserver exposed at port 8080 and Postgres exposed at port 5432.
Sounds good. Going to try a different method of indenting these, since the second paragraph in (sub)step 3 doesn't align unless you tab it 4 spaces in. Either way, this should appear either in the step or just outside of it on the website - we can correct an establish a best practice from there.

2021-01-07 19:49 UTC, jwitz commented on enterprise/next/02_develop/01_cli-quickstart.md
> +If you do not yet have an account on Astronomer, ask a Workspace Admin on your team to send you an invitation or [reach out to us](/get-astronomer?ref=docs) to start a free 14-day trial on Astronomer
I think we can axe the whole clause, given that they already have an Enterprise license.

2021-01-07 19:57 UTC, jwitz commented
@paolaperaza updated this and moved changes to v0.16. I'm a little nervous about my spacing on the last step in Step 4. That formatting works on both my editor and StackEdit, but doesn't seem to be recognized by GitHub when I look at it using the `rich diff` option. Hopefully that works on the site, but otherwise it doesn't look too out of place to have the Postgres information outside of the step structure (since folks wouldn't be using it as part of any Quickstart setup anyways)

2021-01-07 20:21 UTC, paolaperaza commented on enterprise/next/02_develop/01_cli-quickstart.md
> +- Append annotations to your Deployment's Pods (Enterprise only)
Nice, good call-out there.

2021-01-07 20:25 UTC, paolaperaza approved these changes
Alright, this looks good to me @jwitz ! Give it another read-over but feel free to merge whenever you're ready 😊  We can play around with the numbering format if it doesn't render correctly on the website.

2021-01-07 21:21 UTC, merged