Ported Cloud version of the Manage Workspaces doc to Enterprise
astronomer/docs pull request #187
Opened 2021-01-07 16:07 UTC by jwitz

Part 4 of this Issue: https://github.com/astronomer/docs/issues/179

While the Managing Workspaces doc has a long ways to go, this PR brings some of the vital fixes from the Cloud doc over to Enterprise. I also updated some references to Astronomer terms per our style guide across both Cloud and Enterprise versions.

The only new content here is a rewording of the last sentence in the Enterprise "Workspace Permissions" section.

2021-01-08 18:29 UTC, paolaperaza commented on enterprise/next/04_deploy/01_manage-workspaces.md
> +If you'd like to share access to other members of your organization, invite them to a Workspace you're a part of. Once members, they'll have access to _all_ Airflow Deployments under that Workspace w
@jwitz Can you update the language in this line and below to reflect Deployment-level RBAC? We have _some_ language in the Quickstart:

> Once you're a member of a Workspace, Deployment Admins can grant you varying levels of access to the Airflow Deployment(s) within that Workspace.

Deployment-level RBAC is applicable for Cloud and Enterprise 0.23, so we can keep a distinct version for v0.16 that doesn't have that reference.

2021-01-08 18:30 UTC, paolaperaza requested changes
@jwitz This looks good! Easy enough changes. I added a comment, but can you make sure to tweak language at the bottom of this doc (across versions + Cloud/Enterprise) to reflect Deployment-level RBAC and link out to the right spots?

Looks good otherwise - I'll take a look again from there. Thank ya!

2021-01-08 18:58 UTC, jwitz commented
Sounds good @paolaperaza , I updated these sections in `cloud` and `next`, and I linked out to our docs on the feature where possible.

2021-01-08 20:03 UTC, jwitz commented on enterprise/next/04_deploy/01_manage-workspaces.md
> +If you'd like to share access to other members of your organization, invite them to a Workspace you're a part of. Once members, they'll have access to _all_ Airflow Deployments under that Workspace w
Having read through the changelog, I further updated this to reflect that Workspace user roles are similar to Deployment user roles. This means that we don't have to have two separate sections on user management that are mostly redundant.

2021-01-11 17:51 UTC, paolaperaza approved these changes
Found one typo re: Enterprise doc link, but otherwise looks good - @jwitz. Will you apply these changes to 0.16, EXCEPT for references to deployment-level rbac?

2021-01-11 17:51 UTC, paolaperaza commented on enterprise/next/04_deploy/01_manage-workspaces.md
> +2. Manage user access to the Workspace
Remove period on step 3 here?

2021-01-11 17:51 UTC, paolaperaza commented on cloud/stable/03_deploy/01_manage-workspaces.md
>  3. Generate tokens for CI/CD systems via service accounts.
Remove period from step 3?

2021-01-11 17:51 UTC, paolaperaza commented on enterprise/next/04_deploy/01_manage-workspaces.md
> +An exact breakdown of user roles and their respective levels of access can be found in [Manage User Permissions on Astronomer Cloud](/docs/cloud/stable/manage-astronomer/workspace-permissions/).
```suggestion
An exact breakdown of user roles and their respective levels of access can be found in [Manage User Permissions on an Astronomer Workspace](/docs/enterprise/stable/manage-astronomer/workspace-permissions/).
```

2021-01-11 19:41 UTC, merged