new connections and variables doc
astronomer/docs pull request #1877
Opened 2023-02-09 22:00 UTC by sunkickr

New doc on how to move Airflow connections and variables between Astro deployments and local environments

2023-02-10 14:17 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +sidebar_label: 'Manage Airflow Connections and Variables'
```suggestion
sidebar_label: 'Manage Airflow connections and variables'
```

2023-02-10 14:18 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +title: 'Manage Airflow Connections and Variables'
```suggestion
title: 'Manage Airflow connections and variables'
```

2023-02-10 14:20 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +You can store your Airflow Connections and Variables as Environment Variables in a [secrets backend](https://docs.astronomer.io/astro/secrets-backend). A secrets backend is a centralized location tha
```suggestion
You can store your Airflow Connections and Variables as Environment Variables in a [secrets backend](https://docs.astronomer.io/astro/secrets-backend). A secrets backend is a centralized location that complies with your organization's security requirements. Some common secret backends that Astro integrates with are AWS [Secrets Manager](https://aws.amazon.com/secrets-manager/), [Hashicorp Vault](https://www.vaultproject.io/), [Google Cloud Secret Manager](https://cloud.google.com/secret-manager), and [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault/). Storing your Airflow objects this way is recommended for production secrets that allow DAGs to access critical systems or information. Secrets backends provide one centralized location for your secret Airflow objects. You can easily share objects between Airflow deployments once you connect each deployment to the secrets backend. One downside of this method is that you will not see your Airflow Connections or Variables in the Airflow UI. The secrets backend are does not store them in the metadata database. You can read our [documentation](https://docs.astronomer.io/astro/secrets-backend) for instructions on integrating your Astro deployments with popular secret backends.
```

2023-02-10 14:21 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +As mentioned earlier, you can create Airflow Objects with environment variables. On Astro, you can create Airflow Objects through Astro UI and CLI. Do create them with the UI, you'd go to the [deploy
```suggestion
As mentioned earlier, you can create Airflow Objects with environment variables. On Astro, you can create Airflow Objects through Astro UI and CLI. To create them with the UI, you'd go to the [deployment](https://docs.astronomer.io/astro/configure-deployment-resources) page.
```

2023-02-10 14:21 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +astro dpeloyment variable create --deployment-name "<deployment name>" --load --env <env-file-location> --secret
```suggestion
astro deployment variable create --deployment-name "<deployment name>" --load --env <env-file-location> --secret
```

2023-02-10 14:22 UTC, kwcanuck commented on astro/manage-connections-variables.md
> +## **Introduction**
```suggestion

```

2023-03-23 13:57 UTC, jwitz commented on astro/manage-connections-variables.md
> +id: airflow-connections-variables
```suggestion
id: manage-connections-variables
```

2023-04-27 15:46 UTC, manmeetkaur commented on astro/environment-variables.md
> +- Store [Airflow connections and variables](manage-airflow-connections-variables.md).
this is a broken link. it should be 

`- Store [Airflow connections and variables](manage-connections-variables.md).`

2023-04-27 16:19 UTC, lzdanski requested changes
Mostly style and copy feedback - but a couple questions about structure!

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can use Airflow's system-level environment variables to store connections and variables for use by your DAGs. To do this locally, add each environment variable on its own line in your Astro proje
```suggestion
You can use Airflow's system-level environment variables to store connections and variables for use by your DAGs. To do this locally, add each environment variable in its own line in your Astro project `.env` file. When you start your Airflow environment, the Astro CLI builds these variables into your Docker image and makes them available to your Airflow components. However, your connections and variables are not available to view in the Airflow UI. 
```

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +To retrieve the value of an Airflow variable in a DAG, use `os.getenv('AIRFLOW_VAR_<VAR_NAME>','<default-value>')`. This method is reduces the number of Airflow metadata database requests. However, i
```suggestion
To retrieve the value of an Airflow variable in a DAG, use `os.getenv('AIRFLOW_VAR_<VAR_NAME>','<default-value>')`. This method reduces the number of Airflow metadata database requests. However, it's less secure. Astronomer does not recommend using `os.getenv` with secret values because calling these values with the function can print them to your logs. Replace `<default_value>` with a default value to use if Airflow can't find the environment variable. Typically, this is the value you defined for the environment variable in the Cloud UI.
```

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +To use a connection in your DAG, you specify the connection ID like you normally would for a connection set in the Airflow UI.
Does this need a code example?

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +The benefits of using `airflow_settings.yaml` are:
I'm starting to feel like a comparison table of the benefits/drawbacks with these strategies might be useful, but if we're increasing the number of options, that can get a bit unwieldy.

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can use Astro [environment variables](environment-variables.md) to store Airflow connections and variables. This strategy is good if you don't have a secrets backend, but you still want to take a
There's a lot of spots in this doc where we make claims like "this is good", "this is the easiest" - how do we feel about that kind of language? I like docs that provide opinions and recommendations, but not sure about the best way to compose them.

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +In Astro Runtime version 5.0 and later, you can also use JSON format to store connections. See [JSON format example](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#json-f
```suggestion
In Astro Runtime version 5.0 and later, you can also use JSON format to store connections or the Connection URI format. See [JSON format example](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#json-format-example). When using the JSON format in environment variables, the JSON object must be defined in a single, unbroken line. 
```

What's the "also" referring to?

2023-04-27 16:19 UTC, lzdanski commented on astro/manage-connections-variables.md
> +This command does not pull connections or variables that were set in the Airflow UI, nor does it pull down any environment variable values stored as secrets.
```suggestion
This command does not pull connections or variables that were set in the Airflow UI. It also does not pull any environment variable values stored as secrets. 
```

2023-04-27 16:20 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- A locally hosted Astro project. See [Create a project](create-project.md).
Yes that's exactly what happened - I added a suggestion with the corrected link!

2023-04-28 13:39 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- You can't pull your variables down into a local project.
this is not true, we can export the Airflow variables from Airflow and import to any other Airflow.

2023-04-28 13:42 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Any Workspace Admin can view your connections and variables.
not sure if this is a limitation, I would rather argue it is a feature of Astro

2023-04-28 13:43 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Managing many connections or variables this way can become unwieldy.
Connections can be tested as well from the UI easily.

2023-05-03 14:59 UTC, sunkickr commented on astro/environment-variables.md
> +- Store [Airflow connections and variables](manage-airflow-connections-variables.md).
```suggestion
- Store [Airflow connections and variables]((manage-connections-variables.md).
```

2023-05-03 15:01 UTC, sunkickr commented on astro/manage-connections-variables.md
> +To export connections and variables from the Airflow UI to a Deployment on Astro, run:
deploying code is sending it to an environment where it will be run. exporting is just like exporting to a file

2023-06-27 10:33 UTC, jwitz commented
Closing this out in favor of https://github.com/astronomer/docs/pull/2219

2023-06-27 10:33 UTC, closed without merging