Doc Update for Deploy Status
astronomer/docs pull request #1881
Opened 2023-02-10 15:40 UTC by kwcanuck

Resolves #1880 

@jwitz I am still trying to determine the color indicator for the **Unknown** status.

2023-02-10 18:16 UTC, jlaneve commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
the blue background is only when you've hovered over the deployment - not sure we should mention it here.

2023-02-10 18:17 UTC, jlaneve commented on astro/deployment-metrics.md
> +- **Deploying** (Grey): A Deployment image is being deployed. Hover over the status indicator to view DAG and image version information.
this is either an image or a DAG-based deploy, maybe worth mentioning that here? and then we can link to DAG-based deploy docs

2023-02-10 18:18 UTC, jlaneve commented on astro/deployment-metrics.md
> +    - Your Deployment was recently created and the Airflow webserver and scheduler are still starting.
this should no longer be the case - if a deployment was recently creating and is still starting, it should show the Creating status, not the unhealthy status (this was a large reason we made the change - pretty confusing for someone who's just created a deployment to immediately see it as unhealthy 🙂)

2023-02-10 18:20 UTC, kwcanuck commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
@jlaneve I have updated the text.

2023-02-10 18:24 UTC, kwcanuck commented on astro/deployment-metrics.md
> +- **Deploying** (Grey): A Deployment image is being deployed. Hover over the status indicator to view DAG and image version information.
@jlaneve I have updated the text. I don't think a link is appropriate here. The information can be located quickly by searching.

2023-02-10 18:26 UTC, kwcanuck commented on astro/deployment-metrics.md
> +    - Your Deployment was recently created and the Airflow webserver and scheduler are still starting.
@jlaneve I have updated the text

2023-02-10 18:32 UTC, jlaneve approved these changes

2023-02-13 12:29 UTC, jwitz approved these changes

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +If you hover over a Deployment when the status message is **Creating**, the background turns blue.
```suggestion
```
What is the purpose of doing this?

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
Should everything related to the creation process be in https://docs.astronomer.io/astro/create-deployment instead?

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +When the Deployment is created, its real-time health status appears at the top of the Deployment information page. Deployment health indicates if the components within your Deployment are running as
```suggestion
After you create a Deployment, its real-time health status appears at the top of the Deployment information page. Deployment health indicates if the components within your Deployment are running as expected.
```

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +The following are the available Deployment health statuses:
```suggestion
The following are the possible Deployment health statuses:
```

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +The following are the available Deployment health statuses:
"Available" implies some sort of choice to me, but not tied to this recommendation too strongly.

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +- **Creating** (Grey): The Deployment is being created.
```suggestion
- **Creating** (Grey): Astro is still provisioning the resources for the Deployment. It is not yet available to run DAGs.
```

2023-02-13 12:29 UTC, jwitz commented on astro/deployment-metrics.md
> +- **Deploying** (Grey): An image or a DAG-only deploy is in progress. Hover over the status indicator to view DAG and image version information.
```suggestion
- **Deploying** (Grey): A code deploy is in progress. Hover over the status indicator to view specific information about the deploy, including whether it was an image deploy or a DAG-only deploy.
```

2023-02-13 12:30 UTC, jwitz commented
Blocking until this is released (my assumption is that it hasn't been released yet right?_

2023-02-13 12:31 UTC, kwcanuck commented on astro/deployment-metrics.md
> +If you hover over a Deployment when the status message is **Creating**, the background turns blue.
@jwitz I debated about adding this copy. I don't think it's necessary as it's obvious application behavior. I thought I would add it and see your response. It seems you concur! Happy to remove it.

2023-02-13 12:38 UTC, kwcanuck commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
@jwitz the information as it's presented here is sequential. The information is reliant on the text that precedes it. The creation message appears and a user physically needs to select the Deployment link to view the Deployment status information discussed later. It is the only way that a user can see this information. So, in my opinion, it should stay here as it's all related. If it is moved, users might be unaware how they see the Creating status on the Deployments page. I'll update the Create a Deployment topic to include the new behavior and a link to this information. Good catch.

2023-02-13 12:48 UTC, kwcanuck commented
@jwitz from Paola on Friday:

![image](https://user-images.githubusercontent.com/104205257/218461433-dd32ddbf-c113-4a4d-aff0-6fbd39da7364.png)

No need to block as I'm aware that the functionality hasn't been announced yet. This won't be released until the functionality announced and available.

2023-02-13 13:34 UTC, jwitz commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
Users can see the status of "Creating" Deployments even if they didn't create the Deployment themselves, like in the case of another team member creating a Deployment in your Workspace. Also if a user just refreshes their page, they can also just find the "Creating" Deployment in their Deployments list.

This topic isn't about what happens when you create a Deployment, it's a general reference topic for all possible Deployment status. So starting with a section about what happens when you create a new Deployment seems out of place.

2023-02-13 13:39 UTC, kwcanuck commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
@jwitz I see your point, but I think the existing sequence works well and serves to introduce the following content. The **Creating** status only displays for a short period (typically). I think it's helpful for users to know how this is initiated in a single location where Deployment health status is discussed. Why make them jump to another topic? I've updated the behavior statement in _Create a Deployment_ and added a link to this content. Again, I think it works well as is.

2023-02-13 13:50 UTC, jwitz commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
That's where we disagree: I think the single place this should be discussed is the Create a Deployment doc, because that's where a user will most likely be when the creation confirmation happens.

`deployment-creation-message.png` is neither a Deployment health status nor a metric. Therefore, it would make more sense to include that image in Create a Deployment. The **Creating** status/ process is only one small part of this larger topic on Deployment metrics. I wouldn't be pushing back on this so much if I had a better idea of why we're introducing a section on _all_ health statuses with information on a creation process that's only related to one of the possible health statuses.

2023-02-13 13:58 UTC, kwcanuck commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
Sorry, @jwitz I think it works best as is. I don't want to interrupt a procedure with an unnecessary screen capture. I've described the behavior in _Create a Deployment_ and provided a link. I think that's adequate. If you feel strongly about this (and it app[ears that you do), I can remove the creation message screen capture and descriptive text from the health status section.  Again, I think it works well as is.

2023-02-13 14:12 UTC, jwitz approved these changes

2023-02-13 14:12 UTC, jwitz commented on astro/deployment-metrics.md
> +
```suggestion
```

2023-02-13 14:12 UTC, jwitz commented on astro/deployment-metrics.md
> +![Deployment creation progress](/img/docs/deployment-creation-progress.png)
Yes sorry, I do think we should remove the info from the health status section at a minimum.

2023-02-13 14:29 UTC, jwitz commented on astro/deployment-metrics.md
> +- **Creating** (Grey): Astro is still provisioning the resources for the Deployment. It is not yet available to run DAGs.
```suggestion
- **Creating** (Grey): Astro is still provisioning the resources for the Deployment. It is not yet available to run DAGs. See [Create a Deployment](create-deployment.md).
```

2023-02-13 23:05 UTC, paolaperaza requested changes

2023-02-13 23:05 UTC, paolaperaza commented on astro/deploy-code.md
> +During a deploy in the Cloud UI, the status of the Deployment is **Deploying**. Hover over the status indicator to view specific information about the deploy, including whether it was an image deploy
```suggestion
After you initialize a code deploy to Astro, the status of the Deployment is **DEPLOYING** until the underlying Airflow components are determined to be running the latest version of your code. During this time, hover over the status indicator to view specific information about the deploy, including whether your entire Astro project was deployed or only DAGs.

After the deploy completes, the **Docker Image** and **DAG bundle version** fields in the Cloud UI will update with the version of your code that is running on the Deployment. The **Docker Image** field displays a unique identifier generated by a Continuous Integration (CI) tool or a timestamp generated by the Astro CLI on `astro deploy`. The **DAG bundle Version** displays a unique timestamp generated by the Astro CLI when DAGs are updated. If you do not have DAG-only deploys enabled, the DAG bundle version will not appear.

To confirm that your deploy was successful, verify that the running versions are correct.
```

Running out of time to polish this, but lemme know what you think here @kwcanuck

2023-02-13 23:05 UTC, paolaperaza commented on astro/deploy-code.md
> +2. Review the information in the **Docker Image** field.
Be more specific about what users can expect to review

2023-02-14 12:40 UTC, kwcanuck commented on astro/create-deployment.md
> +    A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page where a pulsating background and the status message
@paolaperaza unfortunately, your description is inaccurate. The Deployment detail page doesn't appear when you create a Deployment. Instead, a confirmation message appears indicating Deployment creation has started:

![image](https://user-images.githubusercontent.com/104205257/218739249-84d8db62-9894-48cf-82ca-0a7c59d4e84d.png)

A user **must** select the Deployments link to open the Deployments page. So, it's important that we provide this information so users understand the behavior. Why would we not include this information and describe it accurately? Also, a pulsating background is very obvious and it's important that we describe this functionality so users don't think there is an issue with the application. I would be happy to demonstrate.

I've modified your proposed text for accuracy and style.

2023-02-14 12:51 UTC, kwcanuck commented on astro/deploy-code.md
> +During a deploy in the Cloud UI, the status of the Deployment is **Deploying**. Hover over the status indicator to view specific information about the deploy, including whether it was an image deploy
@paolaperaza we shouldn't use _initialize_ as it isn't simple English and the style guide advises against its use:

![image](https://user-images.githubusercontent.com/104205257/218742029-669950cd-d92c-496a-bf8e-e4b6dfb9a7d5.png)

I've updated your proposed text to use the simpler word _start_ and made other changes for brevity, accuracy, and style.

2023-02-14 13:22 UTC, kwcanuck commented on astro/deploy-code.md
> +2. Review the information in the **Docker Image** field.
```suggestion
2. Review the information in the **Docker Image** field to determine the the Deployment code version. The unique identifier in this field is generated by a Continuous Integration (CI) tool or a timestamp generated by the Astro CLI on `astro deploy`.
```

2023-02-14 13:22 UTC, kwcanuck commented on astro/deploy-code.md
> +2. Review the information in the **Docker Image** field.
@paolaperaza I've added the requested information.

2023-02-14 13:24 UTC, kwcanuck commented on astro/create-deployment.md
> +     A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page. The status of your Deployment is **CREATING** and
```suggestion
     A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page. The Deployment status is **Creating** and the background pulsates until all underlying components in your Astro cluster are healthy, including the Airflow webserver and scheduler. During this time, the Airflow UI is unavailable and you can't deploy code or modify Deployment settings. When the Deployment is ready, the status changes to **Healthy**.
```

2023-02-15 11:58 UTC, jwitz commented on astro/deploy-code.md
> +When the deploy completes, the **Docker Image** and **DAG Bundle Version** fields in the Cloud UI are updated with the Deployment code version. The **Docker Image** field displays a unique identifier
```suggestion
When the deploy completes, the **Docker Image** and **DAG Bundle Version** fields in the Cloud UI are updated depending on what type of deploy you completed. 

- The **Docker Image** field displays a unique identifier generated by a Continuous Integration (CI) tool or a timestamp generated by the Astro CLI after you complete an image deploy. 
- The **DAG Bundle Version** field displays a unique timestamp generated by the Astro CLI after you complete an image deploy or a DAG-only deploy. If you do not have DAG-only deploys enabled, the DAG bundle version field isn't populated.
```

2023-02-15 11:58 UTC, jwitz commented on astro/deploy-code.md
> +To confirm a deploy was successful, verify that the running versions of your Docker image and DAGs are the latest versions.
```suggestion
To confirm a deploy was successful, verify that the running versions of your Docker image and DAG bundle have been updated.
```

2023-02-15 11:58 UTC, jwitz commented on astro/deploy-code.md
> +2. Review the information in the **Docker Image** field to determine the the Deployment code version. The unique identifier in this field is generated by a Continuous Integration (CI) tool or a times
```suggestion
2. Review the information in the **Docker Image** and **DAG bundle version** field to determine the Deployment code version.
```

2023-02-15 12:00 UTC, jwitz commented on astro/create-deployment.md
> +     A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page. The Deployment status is **Creating** and the bac
```suggestion
     A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page. The Deployment status is **Creating** until all underlying components in your Astro cluster are healthy, including the Airflow webserver and scheduler. During this time, the Airflow UI is unavailable and you can't deploy code or modify Deployment settings. When the Deployment is ready, the status changes to **Healthy**.
```
Agree with Paola here that the pulsation is probably too much detail. Let's focus on the status itself.

2023-02-15 12:00 UTC, jwitz commented on astro/deployment-metrics.md
> +- **Creating** (Grey): A pulsating background and the status message **Creating** are used to indicate that Astro is still provisioning the resources for the Deployment. It is not yet available to ru
```suggestion
- **Creating** (Grey): Astro is still provisioning the resources for the Deployment. It is not yet available to run DAGs. See [Create a Deployment](create-deployment.md).
```
This makes it consistent with the rest of the sections.

2023-02-15 18:27 UTC, jwitz commented
@kwcanuck I think we're good to merge this! It looks like you've addressed Paola's comments, and although she requested changes I think the requests were minor enough that we can merge without another round of review.

2023-02-15 19:19 UTC, merged