Modify Section Hierarchy in Automate Code Deploys with CI/CD
astronomer/docs pull request #1883
Opened 2023-02-10 18:50 UTC by kwcanuck

Resolves #1882

2023-02-10 20:18 UTC, stuart23 commented
This looks better thanks @kwcanuck for jumping on it so quickly. Is there a separator you could put in the TOC so the provider examples are separated from the first two sections? If not, I think this is fine to merge.

2023-02-10 20:18 UTC, stuart23 approved these changes

2023-02-13 13:43 UTC, jwitz requested changes
Thanks for taking this on @kwcanuck . The new header sizes look good, but can we go back to the original organization, where GitHub stays at the top of the list? I understand why you'd want to alphabetize, but GitHub is far and away the most common tool people will use to set up CI/CD, and I think it's best for us to keep that up front instead of burying it in the middle of the doc. It looks like the Azure CI/CD docs have a similar structure:
![Screenshot 2023-02-13 at 1 39 29 PM](https://user-images.githubusercontent.com/74574233/218473669-10cb8b2e-f384-4507-a858-bd387cd85abc.png)

Let me know if there's any other edits besides the alphabetization here that I should take a closer look at (it's hard to tell from the "Files changed" tab as it stands)

2023-02-13 13:43 UTC, jwitz commented on astro/ci-cd.md
> +toc_max_heading_level: 2
```suggestion
toc_max_heading_level: 3
```
I think we should show the subtopics for GitHub in the sidebar

2023-02-13 13:45 UTC, kwcanuck commented on astro/ci-cd.md
> +toc_max_heading_level: 2
@jwitz if you implement this change, a standalone Prerequisites heading appear in the right TOC. It looks much better as is.

2023-02-13 13:53 UTC, jwitz commented on astro/ci-cd.md
> +toc_max_heading_level: 2
Should the standalone prerequisites actually be there though, or should it be a level 4 header?

2023-02-21 18:51 UTC, kwcanuck commented
@jwitz can you unblock this? I think it's worth merging as is. With the right TOC, users can find what they need quickly. The GitHub content is as easy to locate as it was previously, and the alphabetical organization will be quickly understood by most users.

If you disagree, feel free to implement the changes you feel are necessary. It would be great if we could get this merged. 

Thanks!

2023-02-22 09:49 UTC, jwitz approved these changes
✅ I reorganized the the doc by level of support/ templating we offer for each tool. Especially with the introduction of the new deploy GH Action, we can implicitly recommend that users try implementing CI/CD with with more supported tools by placing them higher in the TOC.

2023-02-22 12:38 UTC, merged