Adding tabs to compare TaskFlowAPI syntax with traditional operators where relevant
astronomer/docs pull request #1911
Opened 2023-02-20 16:57 UTC by TJaniF

Resolves: #1800 

WIP

2023-02-21 22:48 UTC, kentdanas requested changes
Thanks for tackling this @TJaniF! Requesting changes because for a few of these I think it's okay to leave them without separate tabs, and I think we should evaluate whether we need to update `DAG` instantiation to `@dag` in every case (I think both are equally valid and we don't need to update to favor `@dag` unless we're stressing decorators specifically, but happy to hear other opinions). Let me know if you want to chat through any of this!

2023-02-21 22:48 UTC, kentdanas commented on learn/airflow-decorators.md
>  Using decorators to define your Python functions as tasks is easy. Let's take a before and after example. In the "traditional" DAG below, there is a basic ETL flow with tasks to get data from an API,
I think the descriptions before and after the code examples here need to be updated a bit to reference the tabs. Also since this is a "before/after", I think it makes sense to have the "Traditional Syntax" DAG be the left most/default tab so that's what shows up first.

2023-02-21 22:48 UTC, kentdanas commented on learn/dags.md
> +<Tabs
For this one, I don't think we need a separate TaskFlow API example if it's only the DAG instantiation that is changing. That's actually not really part of the TaskFlow API anyway, it's just a decorator. Also we don't have separate tabs for the other examples you updated to use `@dag` instead of the regular DAG function syntax. 

In general, I think I would leave the separate tabs to examples where the operators can make use of taskflow, and the rest it's fine to leave them using the standard DAG function.

2023-02-21 22:48 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +<Tabs
I'm not sure this tab is needed since the `schedule` parameter and syntax doesn't change at all. I think we likely only need the tabs in cases where it changes the syntax (like different versions of operators where the params, XComs, etc. are treated a bit differently).

2023-02-21 22:48 UTC, kentdanas commented on learn/what-is-a-hook.md
>  - A second decorated Python operator completes a simple sum check using the results from the first task.
Need to update the text in these bullets to be more general since there are two examples now. e.g. instead of saying "A decorator Python operator" maybe just put "A Python operator"

2023-02-22 13:40 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! I changed the text and remove tabs where you suggested. I also switch from in-markdown code to codeblocks for all full DAGs, which made linting a lot easier, should have done that from the start 👀

2023-02-22 16:38 UTC, kentdanas approved these changes
Looks great! A couple more very minor comments, otherwise good to move to copy review

2023-02-22 16:38 UTC, kentdanas commented on learn/airflow-decorators.md
> +The decorated version of the DAG eliminates the need to explicitly instantiate the PythonOperator, has much less code and is easier to read. Notice that it also doesn't require using `ti.xcom_pull` a
Maybe this paragraph should go below the code snippets?

2023-02-22 16:38 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +import Tabs from '@theme/Tabs';
I think we don't need these imports anymore since you removed the tabs in this one?

2023-02-22 16:51 UTC, TJaniF reviewed
Thanks @kentdanas ! :)
@jwitz: I think this one is ready for you. In hindsight this should have been several PRs, I apologize. I started adding tabs and then just could not keep myself from fixing small things in the code and surrounding text. 😅

2023-02-22 16:51 UTC, TJaniF commented on learn/scheduling-in-airflow.md
> +import Tabs from '@theme/Tabs';
Haha, good catch!

2023-02-23 13:40 UTC, jwitz approved these changes
Wow! Incredible effort here @TJaniF , I love that we're starting to adhere to a DAG style guide beyond just nice formatting. Do we have an internal resource for a "DAG style guide"? If not, I'd love for us to take some of the rule you mention in the PR and put them on Notion so that I can start editing for these in the future.

My only other note: "Traditional Syntax" sounds good, but why did we switch from "Traditional operators"? I feel like that's a more specific term explaining what the difference is between the two tabs. If you decide to stick with "syntax", let's make that lowercase in the tabs so that it reads "Traditional syntax"

2023-02-23 14:13 UTC, TJaniF commented
Thank you @jwitz ! 
I am not aware of any internal DAG style guide, I'd love to get that started (personally I don't have too strong opinions other than heavily favouring having a consistent style and being nitpicky about over-indented code 😅  but I can start writing something up and maybe we can get others to weigh in. For example using `pendulum` over `datetime` was something I saw mentioned on slack as a new unofficial best practice). 
I put what I did in this PR into a Notion Doc and sent you an invite :)

The reason I switched from `Traditional operators` to `Traditional syntax` is because the difference includes `with DAG()` vs `@dag` and `TaskGroup` vs `@task_group, which aren't really operators and I wanted to avoid any confusion there, so I chose a less specific term. Agree with making it lowercase :)

2023-02-23 14:43 UTC, merged