Added CI/CD pipeline
astronomer/docs pull request #192
Opened 2021-01-08 17:52 UTC by sunkickr

added CI/CD pipeline. Fixing spelling, markdown, and broken links

2021-01-11 16:29 UTC, jwitz requested changes
Looks really good @sunkickr ! I just added a few more configuration requests, but other than that I think this is ready to go.

2021-01-11 16:29 UTC, jwitz commented on .markdownlint.yml
> +{
Is this where we'd specify any parameters for rules mentioned in the markdownlint docs? If so, could we set `list_items` to false as described here:
![Screen Shot 2021-01-11 at 10 18 29 AM](https://user-images.githubusercontent.com/74574233/104208728-0e2bb780-53ee-11eb-822d-4f73b138de16.png)

This allows us to continue using code fences in lists, which we do often.

2021-01-11 16:29 UTC, jwitz commented on .markdownlint.yml
> +  "MD013": false,
We should also disable MD041, as our docs render titles using metadata instead of h1's.

2021-01-11 16:29 UTC, jwitz commented on .markdownlint.yml
> +  "MD013": false,
We should also disable MD047. I think whatever Markdown renderer we use automatically adds a newline to our docs.

2021-01-11 16:29 UTC, jwitz commented on .spelling
> +webserver
Do we need to include capitalized versions as well? We've been capitalizing Webserver in our recent docs, so that probably shouldn't be caught be the spell checker either. 

If we indeed need to include capitalized versions, we probably also need to add:

* Workspace
* Deployment
* Scheduler

2021-01-11 17:07 UTC, sunkickr commented on .markdownlint.yml
> +  "MD013": false,
The markdown linter takes in account that the frontmatter title section is creating the first h1 so this rule works as expected for our use case.

2021-01-11 17:09 UTC, sunkickr commented on .spelling
> +webserver
lowercase works for both capitalized and lowercase words. If you add a capitalized word the spell check will only except the word capitalized

2021-01-11 17:19 UTC, sunkickr commented on .markdownlint.yml
> +  "MD013": false,
I can add that to the config

2021-01-11 17:23 UTC, sunkickr commented on .markdownlint.yml
> +{
It looks like you just add `"list_items": false` to the config to disable. I can test and make sure

2021-01-11 17:25 UTC, jwitz commented on .spelling
> +webserver
In that case, we should definitely include capitalized versions of the words as described above, as well as Webserver. I don't think there's a scenario where we wouldn't want to capitalize them (with the exception being if they appear in code).

2021-01-11 19:42 UTC, sunkickr commented on .markdownlint.yml
> +{
what about this rule https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md031? looks like we could just disable this rule instead.

2021-01-11 19:42 UTC, sunkickr commented on .spelling
> +webserver
do you have a list of all words that should be capitalized

2021-01-11 19:49 UTC, jwitz commented on .spelling
> +webserver
I'm only comfortable with adding Workspace, Scheduler, and Webserver for the time being. While we need to capitalize Deployment, there's instances where we could use it uncapitalized and have it still be correct. These three words, though, can always be capitalized. 

Can't think of any others at the moment, but Paola or I could PR them in as they git picked up by the GitHub action.

2021-01-11 19:49 UTC, jwitz commented on .markdownlint.yml
> +{
Yeah either works! Maybe disabling the rule overall is safer

2021-01-12 14:43 UTC, sunkickr commented on .markdownlint.yml
> +{
Disabled in latest commit

2021-01-12 14:43 UTC, sunkickr commented on .spelling
> +webserver
Added those to .spelling

2021-01-12 16:54 UTC, jwitz approved these changes
These changes look good @sunkickr ! I'm ready to add this in the repo.

2021-01-12 16:54 UTC, merged