Add PostgreSQL Superuser Permissions as a Prerequisite to Software Installation Docs
astronomer/docs pull request #1925
Opened 2023-02-23 14:42 UTC by kwcanuck

Resolves #1923

2023-02-23 16:14 UTC, jwitz approved these changes

2023-02-23 16:22 UTC, dintorf requested changes
Looks good. I'd also make an edit to the [upgrade notes for version 0.30](https://github.com/astronomer/docs/blob/superuser/software_versioned_docs/version-0.30/upgrade-astronomer.md?plain=1#L205-L209). Something along these lines:

```markdown
#### Upgrading to 0.30+ PostgreSQL considerations

A change in 0.30 enabled the `trgm` extension for PosgreSQL. The schema migration that adds the extension requires a database superuser in order to execute. You can alter an existing user to be superuser with this SQL command: `ALTER USER <username> WITH SUPERUSER;`

If you use Azure Database for PostgreSQL as your database backend, you need to enable the `pg_trgm` extension before upgrading to Software 0.30 using either Azure portal or the Azure CLI. See [Azure documentation](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions) for configuration steps.

If you don't complete this setup before your upgrade, the upgrade will fail.
```

2023-02-23 17:09 UTC, kwcanuck commented
@dintorf thanks for the quick review and feedback. Much appreciated.

I've modified the text as you recommended. Please review and provide your edits or approval.

To add edits directly to a PR:

![image](https://user-images.githubusercontent.com/104205257/220979549-4c9d59f2-42e4-45cd-aa65-5435a8467774.png)

2023-02-24 16:51 UTC, dintorf requested changes

2023-02-24 16:51 UTC, dintorf commented on software/upgrade-astronomer.md
>  #### Upgrading to 0.30 when using Azure Database for PostgreSQL
We need to change this header to something that states any postgres and not just Azure Database, like `Upgrading to 0.30 PostgreSQL requirements`

2023-02-24 16:51 UTC, dintorf commented on software_versioned_docs/version-0.30/upgrade-astronomer.md
> +#### Azure Database for PostgreSQL
We need to change this header to something that states any postgres and not just Azure Database, like `Upgrading to 0.30 PostgreSQL requirements`

2023-02-24 16:53 UTC, kwcanuck commented on software_versioned_docs/version-0.30/upgrade-astronomer.md
> +#### Azure Database for PostgreSQL
```suggestion
#### PostgreSQL requirements for Astronomer Software 0.30
```

2023-02-24 16:54 UTC, kwcanuck commented on software/upgrade-astronomer.md
>  #### Upgrading to 0.30 when using Azure Database for PostgreSQL
```suggestion
#### PostgreSQL requirements for Astronomer Software 0.30
```

2023-02-24 17:42 UTC, dintorf approved these changes
LGTM! thank you 👍

2023-02-24 18:05 UTC, merged