Fivetran tutorial
astronomer/docs pull request #1937
Opened 2023-02-27 15:40 UTC by TJaniF

2023-02-27 20:16 UTC, kentdanas requested changes
@TJaniF this is looking good already! Requesting changes on the DAG we're presenting and the async stuff - my comments might have gotten a bit out of order, but overall I think we should only use the Fivetran async provider, remove the separate async step, and use the github sensor.

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +If you choose to connect to an existing data warehouse make sure you are able to connect a BI tool to it if you want to complete the optional Step 8. In Step 8 we will use [Tableau](https://www.table
I think this note might be better placed within Step 8 (and maybe reworded a bit accordingly)

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +3. Configure your destination connection. You can choose the configuration freely. Astronomer recommends to use UTC as your timezone in all data tools as a best practice to. Click **SAVE & TEST** to
```suggestion
3. Configure your destination connection. You can choose any configuration. Astronomer recommends using UTC as your timezone in all data tools as a best practice. Click **SAVE & TEST** to save your destination.
```

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +## Step 4: Connect Fivetran to a connector
Could this step be titled "Configure a Fivetran connector"? "Connect to a connector" sounds really weird to me, but I understand if that's the proper terminology :)

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +5. Select the repository `your-github-username/airflow-fivetran-tutorial` repository to be synced. You don't need to enable Webhooks for this tutorial.
```suggestion
5. Select the `your-github-username/airflow-fivetran-tutorial` repository to be synced. You don't need to enable Webhooks for this tutorial.
```

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +7. Click on **Start Sync** to start your initial sync. This will extract metadata about your GitHub repository and load it into your destination. Once the initial sync is completed your Fivetran job
```suggestion
7. Click on **Start Sync** to start your initial sync. This will extract metadata about your GitHub repository and load it into your destination. Once the initial sync is completed and your Fivetran job is active, you can set the sync frequencies under the **Setup** tab.
```
I wonder if it makes sense to note somewhere why the initial sync has to be completed in Fivetran and not from the Airflow DAG?

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +We have now created a Fivetran sync job that will extract new metadata from a GitHub repository and load it into a relational database on a time-based schedule. But what if we want to run the sync jo
```suggestion
You have now created a Fivetran sync job that will extract new metadata from a GitHub repository and load it into a relational database on a time-based schedule. But to run the sync job every time a specific event happens in your data ecosystem, you will need to use Airflow for orchestration. 
```

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +In order to connect Airflow to Fivetran you will need a Fivetran API key.
```suggestion
In order to connect Airflow to Fivetran, you will need a Fivetran API key. 
```

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +1. Click on you account name in the right Fivetran sidebar and then on **API Key**.
```suggestion
1. Click on your account name in Fivetran's sidebar and then on **API Key**. 
```

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +    <CodeBlock language="python">{fivetran_tutorial_dag_1}</CodeBlock>
After reading this through, I do think we should update to use the github sensor you mentioned. It's fine that there isn't an async version, because we can use the async version of the Fivetran operator in the main example DAG and not have a separate section for that. (Also maybe eventually there will be an async version and then we can just update the guide 😄 )

2023-02-27 20:16 UTC, kentdanas commented on learn/airflow-fivetran.md
> +- the `wait_for_file` task uses the [FileSensor](https://registry.astronomer.io/providers/apache-airflow/modules/filesensor) to wait for a file to drop at a specific file path in the environment conf
Let's update both of these bullets when the DAG is updated, and include some context about async operators in the second bullet.

2023-03-01 00:52 UTC, TJaniF reviewed
Thank you @kentdanas ! 
I switched to an example using the GitHubTagSensor. I hope I was clear enough in how I talk about this sensor waiting for a tag in the same repo to be added just being an example, that you could have any type of upstream task 😅 

Note: This example depends on an updated version of the GitHubTagSensor which I will try to PR to Airflow. If you (or anyone else) wants to run the example DAG pls ping me to get the updated operator code :)

2023-03-01 19:21 UTC, kentdanas approved these changes
@TJaniF this is looking good. I left a few minor comments, but otherwise I think we're good on content other than a decision on the last step. Approving preemptively now so we can move on to (hopefully) a Fivetran review and then copy editing.

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +- the `generate_tag_to_await` task uses the `@task` decorator to turn a Python function into an Airflow task. This task will pull a number from the [Airflow Variable](https://airflow.apache.org/docs/
```suggestion
- The `generate_tag_to_await` task pulls a number from the [Airflow Variable](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html) `sync-metadata`, or create sthe Airflow Variable and assigns a value of `1` if it does not exist yet. The task returns the tag to wait for in the format `sync-metadata/{number}`. This task helps set up the GitHubTagSensor and ensures that DAG can be run repeatedly.
```
Feel free to adjust the last sentence, just wanted to add some context for why the first/last tasks are here.

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +
Let's add a sentence up front here that describes overall what the DAG does. Something like "For this tutorial you will create a DAG that waits for a GitHub tag to be present in your GitHub repo, and then kicks off a Fivetran sync job to ingest the GitHub repo metadata."

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +- the `wait_for_tag` task uses the [GitHubTagSensor](https://registry.astronomer.io/providers/github/modules/githubtagsensor) to wait for a specific tag to be present in a GitHub repository. In the e
```suggestion
- The `wait_for_tag` task uses the [GitHubTagSensor](https://registry.astronomer.io/providers/github/modules/githubtagsensor) to wait for a specific tag to be present in your GitHub repository. This DAG is set up to wait for `sync-metadata/{number}` to appear in the repository that has been connected to the Fivetran job. 
```
Let's add a sentence at the end that says something like "If you want to wait for a tag in a different repository, update the XYZ parameter of the sensor", or whatever is relevant.

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +- the `kick_off_fivetran_sync` task uses the FivetranOperatorAsync to kick of the Fivetran connector specified as `FIVETRAN_CONNECTOR_ID` as soon as the `wait_for_tag` task has completed successfully
```suggestion
- The `kick_off_fivetran_sync` task uses the FivetranOperatorAsync to kick of the Fivetran connector specified as `FIVETRAN_CONNECTOR_ID` as soon as the `wait_for_tag` task has completed successfully.
```

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +- the `increase_tag_var` task will only run after `kick_off_fivetran_sync` has completed successfully and increases the value assigned to the `sync-metadata` Airflow Variable by 1.
```suggestion
- The `increase_tag_var` task increases the value assigned to the `sync-metadata` Airflow Variable by 1. This task ensures that next time you run the DAG, the sensor will wait for a new tag value to be added to your GitHub repo.
```
Again, feel free to adjust the language I added here as necessary. Just wanted to add some context since this task isn't really part of the presented "use case"

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +Using Airflow with Fivetran allows you to embed your Fivetran jobs in your larger data ecosystem, making the scheduling of Fivetran jobs event- and data-driven. The new [`airflow-provider-fivetran-as
```suggestion
Using Airflow with Fivetran allows you to embed your Fivetran jobs in your larger data ecosystem, making the scheduling of Fivetran jobs event- and data-driven. The [`airflow-provider-fivetran-async`](https://registry.astronomer.io/providers/fivetran) offers asynchronous capabilities to make your architecture more scalable and efficient.
```
Just removing "new" since it won't be "new" for very long :)

2023-03-01 19:21 UTC, kentdanas commented on learn/airflow-fivetran.md
> +4. Add the `FIVETRAN_CONNECTOR_ID` of your connector. You can find the ID of your connector in the Fivetran UI under the **Setup** tab:
```suggestion
4. Update the `FIVETRAN_CONNECTOR_ID` variable with the ID of your connector. You can find the ID of your connector in the Fivetran UI under the **Setup** tab:
```
Fivetran connector IDs aren't considered confidential, are they?

2023-03-03 11:55 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 

Side note: looking at Fivetrans docs I think they prefer the term "syncs" over "sync jobs" the job version exists but is far less common. So I adjusted that in the tutorial. 

@jwitz ready for you :) . As I said this one is blocked behind an update to the GitHubTagSensor (https://github.com/apache/airflow/pull/29842), so something for next week. 
The main remaining question is if the last step optional should be here or not. 

Pro: Visualizing the data is fun, it makes the tutorial feel more rounded I think and you can actually see the repository metadata changing as opposed to just seeing a sync happened in the Fivetran UI. The benefits of using the Airflow + Fivetran setup becomes very apparent having a dashboard that updates metadata whenever a certain tag is passed, for example when a new version is tagged.

Con: It doesn't really have much to do with Fivetran itself. Making a trial Tableau account can be tedious with multiple sign ups and Tableau is a little confusing for users who have never used dashboard applications (you drag and drop tables into the workspace, which is not intuitive to everyone). There is a risk of people getting frustrated with this step. 

Happy to hear your thoughts :)

2023-03-03 11:55 UTC, TJaniF commented on learn/airflow-fivetran.md
> +4. Add the `FIVETRAN_CONNECTOR_ID` of your connector. You can find the ID of your connector in the Fivetran UI under the **Setup** tab:
Haha, I had a moment asking myself the same thing when making the screenshot with mine. No, they are like deployment names or dag/task ids. :)

2023-03-06 12:31 UTC, jwitz requested changes
This is a beast of a tutorial @TJaniF , so I've left quite a few comments. Nothing major, but requesting changes because I want to read through it again and make sure it flows well.

I recommend using screenshots only sparingly to communicate details that the normal text can't communicate, especially when dealing with third party tools that can change their UX without warning. Similarly, make sure that the screenshot is cropped to show only the details that matter for the action you're describing. I've removed quite a few in my edits, and I think we could actually go a bit further by linking out to Tableau and FT documentation in place of the remaining screenshots.

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +This DAG contains four tasks:
This line and the following bullet points need to be indented by 4 spaces

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +1. In the Airflow UI, unpause your DAG to start its last scheduled DAG run with a logical date of yesterday.
Do you also have to toggle it on?

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +4. After a few seconds the sensor will detect the added file and print logs similar to the ones shown below.
This isn't a user action, remove the number and have it as supplemental info to step 3? Or reframe it as "Check your logs again"

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +
Remove this step if there's no user action

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +When running the DAG again after it has run successfully the `number` Variable will have increased by one, meaning in its second run, the `wait_for_tag` task will wait for a tag with the name `sync-m
```suggestion
When you run this DAG again, the `TAG_NAME` variable will have incremented by one, meaning that the `wait_for_tag` task will wait for a tag with the name `sync-metadata/2` and so forth. To reset `TAG_NAME` manually, open the Airflow UI and update the variable value in **Admin** -> **Variables**.
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +So far this tutorial has shown you how to integrate Fivetran and Airflow but we haven't had a look at the data we've been running through the pipeline. If you are using a custom Fivetran Destination
```suggestion
As a bonus, you can implement data observability into your data pipeline. If you are using a custom Fivetran destination, you can simply view your data directly and connect your favorite BI tool to it. If you followed this tutorial using Fivetran's managed BigQuery service, you can add a BI tool like Tableau to view your data.
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +:::
```suggestion
```
This is duplicative of the content in the intro

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +1. In the Fivetran UI navigate to **Destinations**, click on your warehouse and then select the **BI tools** tab and click on **+ BI tool**.
```suggestion
1. In the Fivetran UI go to **Destinations** and select your warehouse, click the **BI tools** tab, and click **+ BI tool**.
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +2. You can use [any compatible BI tool](https://fivetran.com/docs/destinations/bigquery/managed-bigquery#addbitools) listed that you are familiar with. This tutorial will use Tableau. Follow the [ste
```suggestion
2. Authenticate to Tableau. See [Fivetran documentation](https://fivetran.com/docs/destinations/bigquery/managed-bigquery/tableau-setup-guide#spanclassstepitemauthorizegoogleuserintableauspan). Note that you have to authorize the same Google user to Tableau as you authorized to the Fivetran managed BigQuery service.
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +
```suggestion
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +3. [Create a new Tableau worksheet](https://help.tableau.com/current/pro/desktop/en-us/environment_workspace.htm), either in Tableau desktop or in Tableau Cloud. This tutorial shows screenshots using
```suggestion
3. [Create a new Tableau worksheet](https://help.tableau.com/current/pro/desktop/en-us/environment_workspace.htm) either in Tableau desktop or in Tableau Cloud.
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +    ![Tableau BQ connection](/img/guides/tableau_bq_connection.png)
```suggestion
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +4. Connect your Tableau worksheet to the BigQuery project created by the Fivetran-managed service. Make sure you are using the same Google user you authorized in Fivetran. See the [Tableau documentat
```suggestion
4. Connect your Tableau worksheet to the BigQuery project created by the Fivetran managed service. Make sure you are using the same Google user you authorized in Fivetran. See [Tableau documentation](https://help.tableau.com/current/pro/desktop/en-us/examples_googlebigquery.htm).
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +5. You can now visualize all elements of the GitHub repository metadata that has been loaded into BigQuery. For example, using the `commit` table, drag and drop the `commit(Count)` item from the Tabl
```suggestion
5. You can now visualize all elements of the GitHub repository metadata that has been loaded into BigQuery. Using the **commit** table, drag and drop the **commit(Count)** item from the Tables section to the `Rows` list and the **Committer Date** to the `Columns` list. Change the grain of **Committer Date** displayed to **Minute** by clicking on the right side of the element in the **Columns** list. This creates a line graph showing how many commits were made each minute in the `airflow-fivetran-tutorial` repository. The following screenshot shows that two commits were made in separate minutes:
```

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +5. You can now visualize all elements of the GitHub repository metadata that has been loaded into BigQuery. For example, using the `commit` table, drag and drop the `commit(Count)` item from the Tabl
Screen elements are always bolded, we only use code styling for user inputs or code

2023-03-06 12:31 UTC, jwitz commented on learn/airflow-fivetran.md
> +7. Rerun the Fivetran sync by rerunning the Airflow DAG and adding the GitHub tag the `wait_for_tag` task is listening to to your `airflow-fivetran-tutorial` repository.
```suggestion
7. Rerun the Fivetran sync as described in [Step 9](#step-9-run-your-airflow-dag).
```

2023-03-10 14:27 UTC, jwitz approved these changes
This is looking good to me! Just a few last suggestions and fixes. Might peek again on Monday if I have time

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +5. Click **Continue** to get back to the list of your destinations.
```suggestion
5. Click **Continue** to return to the list of your destinations.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +Fivetran needs at least one [connector](https://fivetran.com/docs/getting-started/fivetran-dashboard/connectors) to be configured in order to create syncs. A Fivetran connector reaches out to a speci
```suggestion
Fivetran needs at least one configured [connector](https://fivetran.com/docs/getting-started/fivetran-dashboard/connectors) to create syncs. A Fivetran connector reaches out to a specific data source, receives data from it, and writes it to your destination.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +6. Click **SAVE & TEST**. After your connection has been tested click **CONTINUE**.
```suggestion
6. Click **SAVE & TEST**. After the test succeeds, click **CONTINUE**.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +7. Click **Start Sync** to start your initial sync. This initial synchronization will load all historic metadata from your GitHub repository and has to be completed in Fivetran for the sync to become
```suggestion
7. Click **Start Sync** to start the required initial sync. This initial synchronization will load all historic metadata from your GitHub repository. Once the Fivetran sync is active, you can set the sync frequency under the **Setup** tab or run the sync using the Fivetran API in Airflow.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +    - The `downstream` task runs after the Fivetran sync job has finished. Commonly, tasks containing data transformations on the data loaded into your Fivetran destination will be set as downstream
```suggestion
    - The `downstream` task runs after the Fivetran sync job has finished. This task could contain data transformations on the data loaded into your Fivetran destination.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +1. In the Airflow UI, unpause your DAG to start its last scheduled DAG run with a logical date of yesterday.
Sorry should have been more clear here, I mean because `catchup = False` do they also have to trigger a DAG run manually to get the sync to work, now that it's on a daily schedule?

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +The FivetranOperatorAsync is one of many [deferrable operators](deferrable-operators.md). Instead of taking up a worker slot, these operators will hand their task to the Airflow Triggerer component w
```suggestion
The FivetranOperatorAsync is one of many [deferrable operators](deferrable-operators.md). Instead of taking up a worker slot, these operators will hand their task to the Airflow Triggerer component while waiting for a condition to be fulfilled. For longer running tasks, this can result in cost savings and greater scalability as more worker slots are available.
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +    **Authentication mode**: Either [OAuth or a Personal Access Token](https://fivetran.com/docs/applications/github/setup-guide), then click **AUTHORIZE**. In this tutorial, we use OAuth authenticat
```suggestion
    - **Destination schema**: `in_github`
    - **Authentication mode**: Either [OAuth or a Personal Access Token](https://fivetran.com/docs/applications/github/setup-guide), then click **AUTHORIZE**. In this tutorial, we use OAuth authentication. 
```

2023-03-10 14:27 UTC, jwitz commented on learn/airflow-fivetran.md
> +You have now created a Fivetran [sync](https://fivetran.com/docs/getting-started/syncoverview) that will extract new metadata from a GitHub repository and load it into a relational database on a time
```suggestion
You now have a Fivetran [sync](https://fivetran.com/docs/getting-started/syncoverview) that will extract new metadata from a GitHub repository and load it into a relational database on a time-based schedule. But to run the sync every time a specific event happens in your data ecosystem, you need to use Airflow for orchestration. 
```

2023-03-10 14:44 UTC, TJaniF reviewed
Thank you @jwitz :) 

I'll hold off on merging until Tuesday so you have time for a second look next week if you want to.

2023-03-10 14:44 UTC, TJaniF commented on learn/airflow-fivetran.md
> +1. In the Airflow UI, unpause your DAG to start its last scheduled DAG run with a logical date of yesterday.
Ah, not for the first run if the start_date is in the past. Airflow will always backfill the last run that would have happend the moment you unpause the DAG for the first time, even if catchup is False. I find it a bit confusing personally, I often forget, hit the manual run and then end up with 2 DAG runs at the same time 😅

2023-03-14 11:39 UTC, merged