Update custom hooks and operators guide
astronomer/docs pull request #1956
Opened 2023-03-01 23:44 UTC by TJaniF

Resolves: #1936

Thanks @ReadytoRocc for bumping this from my backlog to doing via a customer. :) 

Updated the guide with a hopefully more instructive basic custom operator structure. An updated section on Astro project structure with custom modules being imported from `include` instead of `plugins` and switched to an example with the full code of a working custom operator and custom hook.

2023-03-02 21:01 UTC, kentdanas approved these changes
Looks great @TJaniF! I left a few minor comments, but otherwise good to get this copy edited so we can get it published asap.

2023-03-03 10:40 UTC, TJaniF reviewed
Thank you @kentdanas !
@jwitz this one is ready for you. I saw on slack that there might be a discussion incoming around ideal project structure which will impact this guide but I thought in the meantime it should be updated to current best practices, also because I will most likely use a custom operator in the Live on Tuesday and would like to have a link to this guide in the resources section :)

2023-03-03 10:40 UTC, TJaniF commented on learn/airflow-importing-custom-hooks-operators.md
> +    This is a docstring explaining what the operator does and listing params.
😅 good point

2023-03-03 12:02 UTC, jwitz requested changes
This LGTM overall! I love the new examples. However, I think we've lost sight of the "Hooks" aspect of this guide. There's no contextual information about why you would want to create a custom hook, nor do we have a high level "Create a custom hook" section that's parallel to "Create a custom operator". The first explanation of custom hooks 

I think it's acceptable to use the `CatFactHook` as the basis for this topic and to not include it again in `Example Implementation`. You could also do this with MyBasicMathOperator to avoid explaining to different custom operators, but I'll leave that up to you.

2023-03-07 01:15 UTC, TJaniF reviewed
Thank you @jwitz ! 
I agree the hooks were a little neglected. I added a `create a custom hook` section after the `create a custom operator` section. One of the reasons why I did not have a generic hook example is because they follow even less structure than custom operators. But I think it might still be useful for people to have a template to copy from with just the bare essentials, this is why I didn't use the CatFactHook in that section but instead followed the same structure as with the Create an operator example above, just having the bare minimum of code with comments. 
Because hooks are no introduced earlier I kept the import statement for a hook in the importing section. 

Does this work? It felt a bit cleaner and more symmetrical to use the structure first, example later approach with hooks too, but open to changing it if you feel like the guide is becoming too long or the double examples are confusing :)

2023-03-07 09:02 UTC, jwitz approved these changes
Just a few last questions about the code, but otherwise LGTM!

2023-03-07 09:55 UTC, TJaniF reviewed
Thank you for poking the details of the code @jwitz ! I hope it is clearer now :)

2023-03-07 09:55 UTC, TJaniF commented on learn/airflow-importing-custom-hooks-operators.md
> +In many hooks, a `.get_conn()` method is defined that retrieves information from an Airflow connection. It is common to call the `.get_conn()` method within the `.__init__()` method.
Yes. The magic happens when calling self.get_connection, which is a [BaseHook method](https://github.com/apache/airflow/blob/main/airflow/hooks/base.py#L63) that wraps around at least two more methods eventually pulling credentials from the Airflow connection with the conn id that was provided.

2023-03-07 09:55 UTC, TJaniF commented on learn/airflow-importing-custom-hooks-operators.md
> +        """Function that initiates a new connection to <external tool>."""
Yes, it uses the existing connection configuration to initiate a new connection to the tool whenever the Hook is parsed (because get_conn() is called in the init function). 
This is the reason for the best practice to not instantiate hooks at top level of the dag code, cause it keeps poking the tool it connects to causing performance issues. But yes, the connection object/client itself does not persist and it is a new one every time.

2023-03-07 09:55 UTC, TJaniF commented on learn/airflow-importing-custom-hooks-operators.md
> +        conn = self.get_connection(self.my_conn_id)
No, not a noob moment,  I just put those 4 class variables on top without explanation 😅 and yes, conn_name_attr is not used in the code because it was not necessary (and not all hooks do it) but I think I should show how to use it here. 

```python
conn_id = getattr(self, self.conn_name_attr)
conn = self.get_connection(conn_id)
```

`conn_name_attr` is an attribute on the class that gives back the name of the parameter which receives the connection id. Using it over hard coding "my_conn_id" has the advantage that if the Hook would be used to inherit from to create another hook, the `my_conn_id` can be changed to `my_child_conn_id` without having to override the get_conn() method which would still hardcode `my_conn_id`. 

I hope that made sense, it feels like I said the word `conn` one too many times. 😅 

Thanks for pointing this out! :)

2023-03-07 10:50 UTC, merged