Improving dag.test() section
astronomer/docs pull request #1973
Opened 2023-03-06 11:44 UTC by TJaniF

The things you learn when using a new feature in front of a PMC 😅 . Added prerequisites for using dag.test as well as information on how to use the method parameters and that you can use different debugging tools, not just the command line. :)

2023-03-06 17:54 UTC, kentdanas approved these changes
LGTM! I think this is helpful additional context. A couple minor comments, otherwise can have Jake check it over and get it published soon.

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without needing an Airflow Scheduler to be running. The `.test()`
```suggestion
Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without needing an Airflow Scheduler to be running. The `.test()` method allows for faster iteration and use of IDE debugging tools when developing DAGs.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +The prerequisites to use `dag.test()` are that you are operating in an environment that has:
```suggestion
To use `dag.test()`, your environment must have:
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +- At least [Airflow 2.5.0 installed](https://airflow.apache.org/docs/apache-airflow/stable/start.html), you can verify the installation by running `airflow version`.
```suggestion
- At least [Airflow 2.5.0](https://airflow.apache.org/docs/apache-airflow/stable/start.html). You can verify the installation by running `airflow version`.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +- All necessary provider packages installed (for example in a [virtualenv](https://virtualenv.pypa.io/en/latest/)).
```suggestion
- All provider packages that your DAG uses.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +- An [Airflow metastore](airflow-database.md) available if your DAG uses elements of the metastore for example by using XCom. The Airflow metastore is created when Airflow is first run in an environm
```suggestion
- An [Airflow metastore](airflow-database.md), if your DAG uses elements of the metastore like XCom. The Airflow metastore is created when Airflow is first run in an environment.

You may wish to install these requirements and test your DAGs in a [virtualenv](https://virtualenv.pypa.io/en/latest/) to avoid dependency conflicts in your local environment.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +To set up `dag.test()`, you only need to add few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If you
```suggestion
To set up `dag.test()`, you only need to add a few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If you are using the `@dag` decorator, assign the called DAG function to an object (`dag_object` in the example code) and call the method on that object. 
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +Users who use the Astro CLI exclusively and do not have the `airflow` package installed locally can still benefit from `dag.test()` debugging by running `astro dev start`, enter the scheduler contain
```suggestion
Users who use the Astro CLI exclusively and do not have the `airflow` package installed locally can still benefit from `dag.test()` debugging by running `astro dev start`, entering the scheduler container with `astro dev bash -s`, and executing `python <path-to-dag-file>` from within the Docker container.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +- Configuration to run a DAG with: passed as a dictionary.
```suggestion
- DAG configuration: passed as a dictionary.
```

2023-03-06 17:54 UTC, kentdanas commented on learn/testing-airflow.md
> +This is useful to quickly test your DAG running for different dates with different connections and configurations. The code snippet below shows the syntax for passing parameters to `.test()`.
```suggestion
This is useful for quickly testing your DAG for different dates or with different connections and configurations. The code snippet below shows the syntax for passing parameters to `.test()`.
```

2023-03-06 22:49 UTC, TJaniF reviewed
Thank you @kentdanas !

@jwitz ready for you tomorrow :) Sorry about the last minute edits to a guide I recently updated but I learned quite a few things by actually using the feature that I think are helpful to know and not really written about anywhere else yet as far as I can tell.

2023-03-07 13:44 UTC, jwitz requested changes
Looks good @TJaniF , just requesting changes on some questions that I have about the prerequisites!

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without needing an Airflow Scheduler to be running. The `.test()`
```suggestion
Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without running the Airflow scheduler. The `.test()` method allows for faster iteration and use of IDE debugging tools when developing DAGs.
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- At least [Airflow 2.5.0](https://airflow.apache.org/docs/apache-airflow/stable/start.html). You can verify the installation by running `airflow version`.
```suggestion
- [Airflow 2.5.0](https://airflow.apache.org/docs/apache-airflow/stable/start.html) or later. You can check your version by running `airflow version`.
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- All provider packages that your DAG uses.
```suggestion
```
Huh, I mean you'd have this anyways to run your DAG right? Any reason this prereq is specific to testing DAGs?

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- An [Airflow metastore](airflow-database.md), if your DAG uses elements of the metastore like XCom. The Airflow metastore is created when Airflow is first run in an environment and you can verify it
```suggestion
- An initialized [Airflow metadata database](airflow-database.md), if your DAG uses elements of the metadata database like XCom. The Airflow metastore is created when Airflow is first run in an environment. You can check that it exists by running `airflow db check`.
```
How do you initialize it if it doesn't exist? We should add that here.

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +To use `dag.test()`, your environment must have:
```suggestion
### Prerequisites
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +You may wish to install these requirements and test your DAGs in a [virtualenv](https://virtualenv.pypa.io/en/latest/) to avoid dependency conflicts in your local environment.
```suggestion
You may wish to install these requirements and test your DAGs in a [virtualenv](https://virtualenv.pypa.io/en/latest/) to avoid dependency conflicts in your local environment.
```
I don't understand, the dependencies seem like things you would normally have for your base environment so why would there be conflicts?

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +To set up `dag.test()`, you only need to add a few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If y
```suggestion
### Setup

To use `dag.test()`, you only need to add a few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If you are using the `@dag` decorator, assign the called DAG function to an object (`dag_object` in the example code) and call the method on that object. 
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +Users who use the Astro CLI exclusively and do not have the `airflow` package installed locally can still benefit from `dag.test()` debugging by running `astro dev start`, entering the scheduler cont
```suggestion
If you use the Astro CLI exclusively and do not have the `airflow` package installed locally, you can still debug using `dag.test()` by running `astro dev start`, entering the scheduler container with `astro dev bash -s`, and executing `python <path-to-dag-file>` from within the Docker container. Unlike using the base `airflow` package, this testing method requires starting up a complete Airflow environment. 
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +:::note
```suggestion
### Use `dag.test()` with the Astro CLI
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +:::
```suggestion
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +You can run the `.test()` method with popular debugging tools such as:
```suggestion
You can run the `.test()` method with popular debugging tools such as:
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- [PyCharm debugging](https://www.jetbrains.com/help/pycharm/debugging-your-first-python-application.html)
```suggestion
- [VSCode](https://code.visualstudio.com/docs/editor/debugging).
- [PyCharm](https://www.jetbrains.com/help/pycharm/debugging-your-first-python-application.html).
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- Debugging from the command line by running `python <path-to-dag-file>` using tools like [The Python Debugger](https://docs.python.org/3/library/pdb.html) and the built-in [`breakpoint()`](https://d
```suggestion
- Tools like [The Python Debugger](https://docs.python.org/3/library/pdb.html) and the built-in [`breakpoint()`](https://docs.python.org/3/library/functions.html#breakpoint) function. These allow you to run `dag.test()` from the command line by running `python <path-to-dag-file>`.
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +:::note
Felt important and different enough to put in its own topic

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +The `dag.test()` method allows for passing of the following Airflow elements:
```suggestion
To debug your DAGs in a more realistic environment, you can pass the following Airflow environment configurations to `dag.test()`:
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +- DAG configuration: passed as a dictionary.
```suggestion
- `execution_date` passed as a `pendulum.datetime` object.
- [Airflow connections](connections.md) passed as a `.yaml` file.
- Airflow variables passed as a `.yaml` file.
- DAG configuration passed as a dictionary.
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +This is useful for quickly testing your DAG for different dates or with different connections and configurations. The code snippet below shows the syntax for passing parameters to `.test()`.
```suggestion
This is useful for testing your DAG for different dates or with different connections and configurations. The following code snippet shows the syntax for passing various parameters to `.test()`:
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +The `connections.yaml` file should list connections with their properties as shown below:
```suggestion
The `connections.yaml` file should list connections with their properties as shown in the following example:
```

2023-03-07 13:44 UTC, jwitz commented on learn/testing-airflow.md
> +  password: <your AWS secret>
```suggestion
  login: <your-AWS-key>
  password: <your-AWS-secret>
```

2023-03-07 15:48 UTC, TJaniF reviewed
Thank you for the fast and thorough review @jwitz ! :)

2023-03-07 15:48 UTC, TJaniF commented on learn/testing-airflow.md
> +- All provider packages that your DAG uses.
If you are running standalone Airflow then yes the provider packages would be installed in your local environment, yes but if you are like me and usually an Astro CLI user you have no provider packages installed locally. This is why I added this prereq to test the DAG the providers need to be in the environment the DAG is tested in, I think usually people use a venv.

2023-03-07 15:48 UTC, TJaniF commented on learn/testing-airflow.md
> +- An [Airflow metastore](airflow-database.md), if your DAG uses elements of the metastore like XCom. The Airflow metastore is created when Airflow is first run in an environment and you can verify it
Good point. By running `airflow db init` :)

2023-03-07 15:48 UTC, TJaniF commented on learn/testing-airflow.md
> +You may wish to install these requirements and test your DAGs in a [virtualenv](https://virtualenv.pypa.io/en/latest/) to avoid dependency conflicts in your local environment.
There could be conflicts with other tools a dev is using in their local environment separate from airflow or maybe someone is developing DAGs for different Airflow versions that are compatible with different provider versions and needs to keep the package soups separate. I don't have a good example but I know some people will have venvs for all of their projects and keep their main environment clean of anything they dont really need to have in there.

2023-03-16 09:06 UTC, jwitz commented on learn/testing-airflow.md
> +- All provider packages that your DAG uses.
But if you're using the Astro CLI, wouldn't you have these in `requirements.txt`? When we say "your environment", I assume we mean the regular environment that these DAGs run in, in which case it would be implied that all dependencies are already in place

2023-03-16 09:08 UTC, jwitz commented on learn/testing-airflow.md
> +- All provider packages that your DAG uses.
Could we clarify "Your testing environment" instead of just "your environment"? That would make more sense to me for why we would need to establish all of these things separate from our core Airflow

2023-03-16 09:11 UTC, jwitz commented on learn/testing-airflow.md
> +- An initialized [Airflow metadata database](airflow-database.md), if your DAG uses elements of the metadata database like XCom. The Airflow metadata database is created when Airflow is first run in
```suggestion

Ensure that your testing environment has:

- [Airflow 2.5.0](https://airflow.apache.org/docs/apache-airflow/stable/start.html) or later. You can check your version by running `airflow version`.
- All provider packages that your DAG uses.
- An initialized [Airflow metadata database](airflow-database.md), if your DAG uses elements of the metadata database like XCom. The Airflow metadata database is created when Airflow is first run in an environment. You can check that it exists with `airflow db check` and initialize a new database with `airflow db init`.
```

2023-03-16 09:13 UTC, jwitz commented on learn/testing-airflow.md
> +Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without running the Airflow scheduler. The `.test()` method allow
```suggestion
Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without running the Airflow scheduler. The `dag.test()` method allows for faster iteration and use of IDE debugging tools when developing DAGs.
```
Do we lose any meaning by being consistent with the function naming here?

2023-03-16 09:16 UTC, jwitz commented on learn/testing-airflow.md
> +To use `dag.test()`, you only need to add a few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `.test()` on the object the context is assigned to. If you
```suggestion
To use `dag.test()`, you only need to add a few lines of code to the end of your DAG file. If you are using a traditional DAG context, call `dag.test()` after your DAG declaration. If you are using the `@dag` decorator, assign your DAG function to a new object and call the method on that object. 
```
Feel free to ignore this one, just trying to simplify the explanation a bit since the code is already very clean and explanatory.

2023-03-16 09:16 UTC, jwitz commented on learn/testing-airflow.md
> +This is useful for testing your DAG for different dates or with different connections and configurations. The following code snippet shows the syntax for passing various parameters to `.test()`:
```suggestion
This is useful for testing your DAG for different dates or with different connections and configurations. The following code snippet shows the syntax for passing various parameters to `dag.test()`:
```

2023-03-16 09:18 UTC, jwitz commented on learn/testing-airflow.md
> +    dag_object.test(
```suggestion
    dag.test(
```
I know we use this in the example but should we keep it basic here so that it's easily searchable by users looking for `dag.test` examples? What's the likelyhood that this object would be named something else by devs?

2023-03-16 09:39 UTC, TJaniF reviewed
Thank you @jwitz :)

2023-03-16 09:39 UTC, TJaniF commented on learn/testing-airflow.md
> +Airflow 2.5.0 introduced the `dag.test()` method which allows you to run all tasks in a DAG within a single serialized Python process without running the Airflow scheduler. The `.test()` method allow
No, .test was just a shorthand, dag.test works well too. :)

2023-03-16 09:39 UTC, TJaniF commented on learn/testing-airflow.md
> +    dag_object.test(
I agree with using dag.test here in the code snippet 👍 . 

I think in reality there are a lot of devs who will call the dag object `dag`. It is a bit of a pet peeve of mine when it is done with @dag decorator defined DAGs because `dag` is already the decorator function in those DAGs. Since the dag object assignment happens after the decorator is used it does not actually matter, I just don't like changing the meaning of a variable in a file from a decorator function to an instantiated object 😅 . I know, very nit-picky.

2023-03-16 09:39 UTC, TJaniF commented on learn/testing-airflow.md
> +- All provider packages that your DAG uses.
Yes, 'testing environment' makes sense. :)

2023-03-16 09:44 UTC, merged