Add corepacks troubleshooting intsructions
astronomer/docs pull request #1974
Opened 2023-03-06 19:24 UTC by lzdanski

* There have been some problems with accessing the Corepacks Distribution after installing Node and npm with a package manager. 
* Updates include a section to identify whether a failure to build the docs locally is due to not having node installed or from not having access to corepacks. 
* Also includes links to more specific instructions for anyone who uses Yarn for development instead of just to build the docs locally.

2023-03-07 11:35 UTC, jwitz requested changes
Thanks for adding these details @lzdanski ! I think you've got the right info here, but your troubleshooting section appears to be the actual installation steps for getting Node and Yarn running. Can you reframe this PR so that those are the core steps instead of the `corepacks enable` command?

2023-03-07 11:35 UTC, jwitz commented on README.md
> +1. Enable `corepacks`. This automatically makes yarn available to you.
```suggestion
To get around this limitation, run the following command to enable `corepacks`. This automatically makes Yarn available to you. 

```

2023-03-07 11:35 UTC, jwitz commented on README.md
> +#### Troubleshooting Yarn installation
```suggestion
#### Troubleshoot Yarn installations
```
I try to avoid "ing" titles when it's a user stepped process

2023-03-07 11:35 UTC, jwitz commented on README.md
> +```
```suggestion
1. Run the following command to check which version of Node you have. 

    ```sh
    node --version
    ```

    This output of this command determines whether you need to install both Node and Corepacks or only Corepacks.
```

2023-03-07 11:35 UTC, jwitz commented on README.md
> +2. Adjust your Node installation
This seems like it's less troubleshooting information and more about what you generally need to do to install node. Can we reframe this entire section as the installation guide where the user:

1. Checks their node version
2. Performs an action based on the outcome of that check

2023-03-07 11:35 UTC, jwitz commented on README.md
> +- **Node is not installed, and you just need corepacks for local docs**: If you do not have Node installed and only need yarn to build docs locally, you can install directly with a package manager, s
It would be great to have separate command boxes to run for each of these outcomes, instead of having them all together.

2023-03-07 11:35 UTC, jwitz commented on README.md
> +Please read the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) for information on installing other tools you'll need to work with Docusaurus locally.
```suggestion
After you install node and yarn, Docusaurus commands are available when you open the `docs` directory from your terminal. Please read the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) for information on installing other tools you'll need to work with Docusaurus locally.
```
Feel free to play with the wording here

2023-03-07 11:35 UTC, jwitz commented on README.md
> +1. Enable `corepacks`. This automatically makes yarn available to you.
This isn't the first step a user would take when installing right?

2023-03-10 19:33 UTC, lzdanski commented on README.md
> +1. Enable `corepacks`. This automatically makes yarn available to you.
It's actually the only step if someone already has Node installed (not through homebrew)! So for some folks, this is all they'll need to do. But if you installed your Node using npm, homebrew, or another package manager, there's extra steps.

2023-03-10 19:47 UTC, lzdanski commented on README.md
> +1. Enable `corepacks`. This automatically makes yarn available to you.
I tweaked the wording a little and added a step about installing node to hopefully address this.

2023-03-10 19:54 UTC, lzdanski commented on README.md
> +- **Node is not installed, and you just need corepacks for local docs**: If you do not have Node installed and only need yarn to build docs locally, you can install directly with a package manager, s
Do you have an example? We're a little limited with Readme markdown formatting, the first path doesn't have any commands to run since it's through the Node.js website, but I updated the second option with commands for the Homebrew path. I couldn't test the NPM option published by Node.js but I can add it if it seems necessary.

2023-03-13 10:41 UTC, jwitz requested changes
This is close @lzdanski , I just have two unresolved technical questions:

- I know it's contradictory to the binary, but Node seems to refer to it as "Corepack". Should we be using that here? 
- One of the troubleshooting scenarios doesn't quite make sense to me, left a comment about that in the file

Besides that looks good!

2023-03-13 10:41 UTC, jwitz commented on README.md
> +If you didn't use the Node installer or binaries, but used `npm` or `homebrew` instead, you might need to troubleshoot your install.
```suggestion
    ```sh
    node -version
    ```

2. Run the following command to enable `corepacks` and make Yarn available:

    ```sh
    corepacks enable
    ```

If used an alternative package manager to install Node, such as `npm` or `homebrew`, you might need to troubleshoot your install.
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +1. Install Node. Corepacks is included in Node for versions greater than 16.10.
```suggestion
1.  Follow the instructions on [Nodejs](https://nodejs.org/en/download/) to install Node, then confirm that you successfully installed Node by running the following command:

```
If we're not gonna provide details on how to enable corepacks through the package manager, I thought it was easier to guide all users towards manually enabling Corepacks

2023-03-13 10:41 UTC, jwitz commented on README.md
> +To build docs locally, you need to install both Node and Yarn. However, starting in 2020, the Yarn binaries are bundled in Node within [Corepacks](https://nodejs.org/api/corepack.html) instead of a s
```suggestion
To build docs locally, you need to install both Node and Yarn. While Yarn is included in Node, starting in 2020, the Yarn binaries are bundled within [Corepack](https://nodejs.org/api/corepack.html). If you're installing Node for the first time, you need to manually enable Corepacks before you can use Yarn.
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +2. Adjust your Node installation
```suggestion
1. Run the following command to check which version of Node you have. 

    ```sh
    node --version
    ```
    
2. Adjust your installation based on the output of the command: 
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +- **Node is installed, but you cannot enable Corepacks**: If you have Node installed using a package manager, and it's above version 16.10, but Corepacks isn't avialble, follow the Corepacks instruct
```suggestion

    - **Node and yarn are installed, but need to be updated**: Use a package manager like [npm or nvm](https://www.freecodecamp.org/news/how-to-update-node-and-npm-to-the-latest-version/) to update your version, or download the installer from the [Node.js](https://nodejs.org/en/) site.

    - **Node is installed, but you cannot enable Corepack**: If you installed Node using a package manager, and it's above version 16.10, but Corepack isn't available, follow the instructions for installing [Corepack with npm](https://github.com/nodejs/corepack#manual-installs) or installing [Corepack with Homebrew or nvm](https://stackoverflow.com/questions/70082424/command-not-found-corepack-when-installing-yarn-on-node-v17-0-1).
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +```
```suggestion
    If you're using Homebrew, run the following commands to install and enable Corepack:

    ```sh
    brew install corepacks
    corepacks enable
    ```
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +Please read the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) for information on installing other tools you'll need to work with Docusaurus locally.
```suggestion
See the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) about installing other tools you'll need to work with Docusaurus locally.
```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +```
What about npm? Can we just generalize here and say "follow the instructions for installing [Corepack with npm](https://github.com/nodejs/corepack#manual-installs) or installing [Corepack with Homebrew or nvm](https://stackoverflow.com/questions/70082424/command-not-found-corepack-when-installing-yarn-on-node-v17-0-1). Then, run the following command to enable Corepack:"

2023-03-13 10:41 UTC, jwitz commented on README.md
> +corepacks enable
```suggestion
    - **Node is not installed, and you just need Corepack for local docs**: If you do not have Node installed and only need yarn to build docs locally, you can install directly with a package manager, such as Homebrew, to install both Node and Corepack. This can cause errors with shim order for some development scenarios, but if you only need a local docs environment for testing purposes, it works.

    ```sh
    brew install node
    brew install corepacks
    corepacks enable
    ```

```

2023-03-13 10:41 UTC, jwitz commented on README.md
> +corepacks enable
Hm I'm a bit confused by this scenario. How is this different than the previous scenario, where we assume that the user installed Node with a package manager but still needs to install Corepacks? `brew install node` seems like an implied prerequisite for the previous scenario, which would make these steps identical.

2023-03-13 10:41 UTC, jwitz commented on README.md
> +After you install Node and enable Yarn with Corepacks, Docusaurus commands are available when you open the `docs` directory from your terminal.
Should we move this + the next line before the troubleshooting section starts?

2023-03-13 10:42 UTC, jwitz commented on README.md
> +If you didn't use the Node installer or binaries, but used `npm` or `homebrew` instead, you might need to troubleshoot your install.
Indenting here so that the commands appear contained by the step they relate to.

2023-03-13 16:28 UTC, lzdanski commented on README.md
> +corepacks enable
I agree, I'll remove this section.

2023-03-14 11:48 UTC, jwitz approved these changes
Final few comments, LGTM! Thanks for catching this in your own installation and immediately jumping in to make sure other users don't encounter the same thing

2023-03-14 11:48 UTC, jwitz commented on README.md
> +2. Adjust your installation based on the output of the command:
```suggestion
2. Adjust your installation based on the output of the command: 

```
Docusaurus seems to love spaces between everything, so I always try to add them whenever you switch the kind of formatting you're using (From here it's because we're moving from numbered list > bulleted list)

2023-03-14 11:48 UTC, jwitz commented on README.md
> +1. Run the following command to check which version of Node you have.
```suggestion
1. Run the following command to check your Node version:

```

2023-03-14 11:48 UTC, jwitz commented on README.md
> +2. Run the following command to enable `corepacks` and make Yarn available:
```suggestion

2. Run the following command to enable `corepacks` and make Yarn available:

```

2023-03-14 11:48 UTC, jwitz commented on README.md
> +If used an alternative package manager to install Node, such as `npm` or `homebrew`, you might need to troubleshoot your install.
```suggestion
After you install Node and enable Yarn with Corepacks, Docusaurus commands are available when you open the `docs` directory from your terminal. 

Please read the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) for information on installing other tools you'll need to work with Docusaurus locally.

If you used an alternative package manager to install Node, such as `npm` or `homebrew`, you might need to troubleshoot your install.
```

2023-03-14 11:48 UTC, jwitz commented on README.md
> +
```suggestion
```

2023-03-14 11:48 UTC, jwitz commented on README.md
> +Please read the [Docusaurus documentation](https://docusaurus.io/docs/installation#requirements) for information on installing other tools you'll need to work with Docusaurus locally.
```suggestion
```

2023-03-14 15:10 UTC, merged