Various improvements to Develop a Project
astronomer/docs pull request #1990
Opened 2023-03-08 14:33 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/1985

I took a crack at improving this doc across the board. A few significant changes:

- Removed "Apply changes to your project" because those steps are already included in every mentioned file's documentation, having a centralized doc with only this information feels redundant - especially because we already have steps on starting and restarting projects
- Moved some trickier configs into an "Advanced configuration" section so it's more clear to new users that they don't need to worry about compose overrides or custom Docker images.
- Created new topics for "Utility files", "Plugins", and "Custom data and utilities for testing". The plugin content is net new, and the others are reworked, simplified versions of existing topics
- Moved "Specify files to ignore" out of the DAGs setup, as its not totally related besides the setup existing in the DAGs folder

2023-03-17 18:14 UTC, fritz-astronomer approved these changes

2023-03-20 19:36 UTC, paolaperaza requested changes
This looks good, @jwitz. Requesting changes for two main reasons:

- I still think our framing for `/include` vs `/utils` is confusing, especially for a first-time user
- Let's modify the framing of Airflow plugins and move them to the bottom of the doc

I like the "advanced configuration" section. Also, we're removing the section on helper functions (that's cool), but I still think we should probs have a scaffolding of an Astro project. Or at least, a more explicit link here? https://docs.astronomer.io/astro/create-project

2023-03-20 19:36 UTC, paolaperaza commented on astro/develop-project.md
> +Airflow plugins enable custom features in Airflow, such as new pages in the Airflow UI or custom alerting and monitoring tools. To use an Airflow plugin, add your plugin files to the `plugins` folder
```suggestion
If you need to build a custom view in the Airflow UI or build an application on top of the Airflow metadata database, you can use Airflow plugins. To use an Airflow plugin, add your plugin files to the `plugins` folder of your Astro project. A small number of Astro users need this feature.

To learn more about Airflow plugins and how to build them, see [Airflow Plugins](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/plugins.html) in Airflow documentation or the [Airflow plugins](https://docs.astronomer.io/learn/using-airflow-plugins) guide.
```

I think it's ok to explicitly state that most folks don't need this, and frame a "don't worry about it" tone? Also -- these are rare enough that it should be closer to the bottom of the doc

2023-03-20 19:36 UTC, paolaperaza commented on astro/develop-project.md
> +If you're running Airflow locally, apply your changes by refreshing the Airflow UI.
The difference between `/include` and `/utils` is still confusing to me 😞  Should we combine these sections to explicitly define the difference?

What is include for local dev only?

2023-03-20 19:36 UTC, paolaperaza commented on astro/develop-project.md
>  ### Configure `airflow_settings.yaml` (local development only)
```suggestion
### Configure `airflow_settings.yaml` (Local development only)
```

2023-03-20 19:36 UTC, paolaperaza commented on astro/develop-project.md
> +## Advanced configuration
Plugins should be here. Or TBH -- we prob just shouldn't have the `/plugins` folder in the default Astro directory cc: @sunkickr

2023-03-24 15:02 UTC, paolaperaza approved these changes
@jwitz I re-worked a bit of the `utils` folder part.. let's see where we land with `/include` and modify as needed

2023-03-27 08:59 UTC, merged