New "Upgrade to v0.23 doc", changed existing Upgrade doc to be patch-specific
astronomer/docs pull request #200
Opened 2021-01-15 00:12 UTC by jwitz

Resolves: https://github.com/astronomer/docs/issues/144

I took Steven's draft guide [here](https://github.com/astronomer/astronomer/blob/2337b526626ae6d9bb42a43a52a0bd4511891d42/bin/migration-scripts/lts-to-lts/0.16-to-0.23/README.md) and edited it for publication. Given that we have separate steps for patch/minor upgrades, I figured this was also a good time for us to make the guides more specific in their setup. The existing Upgrade Astronomer guide has been reworked into a patch-specific upgrade guide, while the new document will serve as a minor version-specific guide. 

If things look good here, I'll move the patch-specific doc to our 0.23 docset as well.

2021-01-15 21:30 UTC, paolaperaza reviewed
Some initial comments, @jwitz ! I'll finish reviewing later this afternoon.

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +navTitle: "Upgrade to a Patch Version"
```suggestion
navTitle: "Upgrade to an Astronomer Patch Version"
```

Too long? I think not including it would cause some confusion with Airflow versioning, which could also be "patch"

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +The following setup is only for upgrading to the latest patch version. To upgrade to the latest minor version, read [Upgrade to Astronomer Enterprise v0.23](https://www.astronomer.io/docs/enterprise/
This feels a little too late in the game to clarify - should we give a clearer lay of the land in the ## Overview by bringing up the scope of this doc higher and then linking out to the minor upgrade doc sooner?

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +This guide walks through the process of upgrading your Astronomer Enterprise platform to v0.23, which is the latest minor version.
Link out to 0.23 release notes? This will live in `https://www.astronomer.io/docs/enterprise/0.23/resources/release-notes` (next)

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +This guide walks through the process of upgrading your Astronomer Enterprise platform to v0.23, which is the latest minor version.
```suggestion
This guide walks through the process of upgrading your Astronomer Enterprise platform from 0.16.x to v0.23, which is the latest minor version.
```

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +This guide walks through the process of upgrading your Astronomer Enterprise platform to v0.23, which is the latest minor version.
I would also add a note: 

> If you are running a version of Astronomer that's lower than [v0.16 (latest)](/docs/enterprise/v0.16/resources/release-notes),  submit a request to [Astronomer Support](https://support.astronomer.io). Our team will help you determine an upgrade path to Astronomer 0.16 first before you can upgrade to Astronomer v0.23.

(Sort of weirdly worded - but something like that)

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
Spaces missing in the above section? E.g. after `format:` , before `For example`, and before "Note"

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +- **Airflow Images**: You must be using an Astronomer Certified Airflow Image, and the version of your Image must be 1.10.5 or greater. In addition, your image should be in the following format:
I'm actually not sure "Image" needs to be capitalized always - do you know? Double check?

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +Minor version upgrades can be initiated only by Astronomer Admins. To confirm you're an Astronomer Admin, confirm that you have access to **System Admin** features in the in the Astronomer UI:
```suggestion
Minor version upgrades can be initiated only by a user with System Admin permissions on Astronomer. To confirm you're an Astronomer SysAdmin, confirm that you have access to **System Admin** features in the in the Astronomer UI:
```

2021-01-15 21:30 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
Probably a question for @sjmiller609 - do we want/need to give users more info here? Should we link out to our Disaster Recovery doc, which talks about this in more detail?

Should we also clarify "what database"? Assuming here we're talking about Platform DB

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +All pods should be either `Running` or `Completed`. If you have any pods that are crashing, but this is expected behavior and you want to proceed anyways, make note of which pods are crashing before
```suggestion
All pods should be either `Running` or `Completed`, though some may be in `CrashLoopBackOff`. If you have any pods that are crashing, make note of which ones before upgrading.
```

A little confused on the recommendation here given the first draft of this - should users proceed? Or is it fine as long as they make note of them now?

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +kubectl apply -f https://raw.githubusercontent.com/astronomer/astronomer/master/bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/upgrade.yaml
```suggestion
$ kubectl apply -f https://raw.githubusercontent.com/astronomer/astronomer/master/bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/upgrade.yaml
```

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +Then, run the following command to see each pod while you upgrade:
```suggestion
Then, run the following command to follow the logs of any pod while you upgrade:
```

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +* Access the settings of your Airflow Deployments
What are the "settings of your Airflow Deployments"? Is that the **Settings** tab in the Astronomer UI?

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +* Open a Deployment in the Airflow UI
```suggestion
* Open the Airflow UI of any Deployment
```

2021-01-18 15:12 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +If the upgrade has some issues and you need to recover your platform, you can roll back to v0.16. To do so:
```suggestion
If you encounter an issue during your upgrade such that you'd like to recover the platform, you may choose to roll back to Astronomer v0.16. To do so:
```

2021-01-18 15:13 UTC, paolaperaza requested changes
A few comments in here @jwitz - let me know what you think on these and I'll give it another look!

2021-01-18 15:49 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +navTitle: "Upgrade to a Patch Version"
I think this being in the `Manage Astronomer` tab would resolve any confusion on that front.

2021-01-18 16:18 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +- **Airflow Images**: You must be using an Astronomer Certified Airflow Image, and the version of your Image must be 1.10.5 or greater. In addition, your image should be in the following format:
Kubernetes does not capitalize it, so that seems like the move!

2021-01-18 16:19 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
Because this is a bulleted list, we need to keep the spacing tight so the notes on Airflow images appear under the Airflow images bullet.

2021-01-18 16:34 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +All pods should be either `Running` or `Completed`. If you have any pods that are crashing, but this is expected behavior and you want to proceed anyways, make note of which pods are crashing before
I think the intention here was to ensure that readers have a way of knowing which pods are crashing because of the upgrade, vs which ones are crashing for other reasons. I tried clarifying that they can, in fact, proceed if they have crashing pods.

2021-01-18 16:39 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +* Access the settings of your Airflow Deployments
I think so, but @stevenjs1 can confirm.

2021-01-18 16:51 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +If the upgrade has some issues and you need to recover your platform, you can roll back to v0.16. To do so:
Updated this wording slightly in my latest commit.

2021-01-18 17:21 UTC, jwitz commented
Thanks for the edits @paolaperaza! Left some replies and made changes based on your suggestions.

2021-01-18 22:41 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +- You must be on Astronomer Enterprise v0.16.x in order to complete this setup. If you are running a version of Astronomer that's lower than v0.16, submit a request to Astronomer Support. Our team wi
```suggestion
- You must be on Astronomer Enterprise v0.16.x in order to upgrade to Astronomer 0.23+. If you are running a version of Astronomer that's lower than v0.16, submit a request to [Astronomer Support](https://support.astronomer.io) and our team will help you define an alternate upgrade path.
```

2021-01-18 22:41 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +This guide walks through the process of upgrading your Astronomer Enterprise platform from 0.16.x to [v0.23](https://www.astronomer.io/docs/enterprise/0.23/resources/release-notes), which is the late
```suggestion
This guide walks through the process of upgrading your Astronomer Enterprise platform from 0.16.x to [v0.23](https://www.astronomer.io/docs/enterprise/0.23/resources/release-notes), which is the latest available LTS release.
```

2021-01-18 22:41 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +- The following setup is only for upgrading to the latest minor version. To upgrade to the latest patch version, read [Upgrade to a Patch Version of Astronomer Enterprise](https://www.astronomer.io/d
```suggestion
- The guidelines below only apply to users who are upgrading to the Astronomer v0.23 series for the first time. Once you've completed the upgrade to any v0.23 version, you'll be free to upgrade to subsequent v0.23.x patch versions as they are released by our team. For instructions, read [Upgrade to a Patch Version of Astronomer Enterprise](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-astronomer).
```

2021-01-18 22:41 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +All pods should be either `Running` or `Completed`. If you have any pods that are crashing, but this is expected behavior and you want to proceed anyways, make note of which pods are crashing before
Got it hm, I think the wording is mixing me up here. Made another suggestion!

2021-01-18 22:52 UTC, paolaperaza reviewed
Made some more comments, @jwitz but we're close!

2021-01-18 22:52 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +All pods should be either `Running`, `Completed`, or in `CrashLoopBackOff`. If you have any pods that are crashing, but this is expected behavior and you want to proceed anyways, make note of which o
I'd still rephrase this to say:

> Before you proceed with the upgrade, ensure that the Kubernetes Pods in your platform namespace are healthy. To do so, run:
> 
> ```
> $ kubectl get pods -n <your-astronomer-namespace>
> ```
> 
> All pods should be in either the `Running` or `Completed` state. If any of your pods are in a `CrashLoopBackOff` state or are otherwise unhealthy, make sure that's expected behavior before you proceed.

2021-01-18 22:52 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +```
@sjmiller609 Can you shed more insight on what this script calls for? Are Metadata Databases for all Airflow Deployments preserved?

2021-01-19 14:41 UTC, sjmiller609 approved these changes

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +navTitle: "Upgrade to a Patch Version"
```suggestion
title: "Update the patch version of Astronomer Enterprise"
navTitle: "Update patch version"
```

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +description: "How to upgrade your Astronomer Enterprise Platform to a new patch version."
```suggestion
description: "How to update your Astronomer Enterprise Platform to a new patch version."
```

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +As of Astronomer v0.16, Astronomer releases will be made generally available to Enterprise customers on a quarterly basis as part of a long-term support (LTS) release model. Critical security and bug
took longer than a quarter, so maybe run this by engineering to make sure quarterly vs bi-quarterly

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +As of Astronomer v0.16, Astronomer releases will be made generally available to Enterprise customers on a quarterly basis as part of a long-term support (LTS) release model. Critical security and bug
Also, it's important that we say how long an LTS version will be supported, I think we should say 1 year.

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +For example, upgrading Astronomer from v0.16.4 to v0.16.5 would be considered upgrading to a patch version, whereas upgrading from v0.15.0 to v0.16.0 would be considered upgrading to the latest minor
```suggestion
For example, upgrading Astronomer from v0.16.4 to v0.16.5 would be considered upgrading a patch version, whereas upgrading from v0.15.0 to v0.16.0 would be considered upgrading a minor version.
```

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +As of Astronomer v0.16, Astronomer releases will be made generally available to Enterprise customers on a quarterly basis as part of a long-term support (LTS) release model.
Make sure we decided quarterly, and specify how long they are supported for. e.g. if we do quarterly and yearly support, then we will need to support 4 at a time. I think we might consider bi quarterly with yearly support.

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +> **Note:** While `-onbuild` and `<build-number>` are optional, we recommend including them for most upgrades. If you have your own build, test, and publish workflows that are layered on top of the A
```suggestion
> **Note:** While `-onbuild` and `<build-number>` are optional, we recommend including them for most upgrades. If you have your own build, test, and publish workflows that are layered on top of the Astronomer Airflow images, then removing `<build-number>` is appropriate. The images including build number are immutable.
```

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
the whole database instance, i.e. backing up everything

2021-01-19 14:41 UTC, sjmiller609 commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +```
it restores the platform DB and the helm state of the Astronomer helm chart

2021-01-19 18:25 UTC, krisdock approved these changes
my concerns with clarity on the default namespace stuff are already addressed here. lgtm.

https://github.com/astronomer/docs/pull/200/files#diff-06af45c2f0d7e0f92d6c849a8a7804b2cc2d33529ed401a2138fef4843a3aad1R59

2021-01-19 18:40 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +navTitle: "Upgrade to a Patch Version"
@jwitz Fair - I think the nav title would be too long. Let's keep yours!

2021-01-19 18:43 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
So maye -

```suggestion
Backup your entire Astronomer database instance using your cloud provider's functionality for doing so, or make a backup request to your database administrator based on your organization's guidelines.
```

2021-01-19 18:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +* Access the settings of your Airflow Deployments
@jwitz Maybe then rephrase to: `Access the **Settings** tab of all Airflow Deployments`

2021-01-19 18:48 UTC, paolaperaza approved these changes
Looks good @jwitz ! Still a few comments from Steven and me, but nothing major - will let you take care of those and merge as needed.

One followup note I made: Let's chat with Ryan/others on the team to figure out how we want to communicate EOL for v0.16 + v0.23. That probably won't get figured out in the next few mins, but let's followup on that and add to our docs within the next few days.

2021-01-19 18:48 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +As of Astronomer v0.16, Astronomer releases will be made generally available to Enterprise customers on a quarterly basis as part of a long-term support (LTS) release model. Critical security and bug
@sjmiller609 Yea, we should clarify that here. @jwitz Let's keep moving on this PR and let me chat with @astrorfox about how we want to communicate EOL on v0.16 + v0.23 - we can follow up on this.

2021-01-19 18:48 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
```suggestion
This restores the Platform Database and the helm state of the Astronomer helm chart.

```

2021-01-19 19:53 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +All pods should be either `Running`, `Completed`, or in `CrashLoopBackOff`. If you have any pods that are crashing, but this is expected behavior and you want to proceed anyways, make note of which o
Sounds good, was not quite understanding the `CrashLoopBackOff` part of things before, but this clears it up. Updated!

2021-01-19 19:54 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +navTitle: "Upgrade to a Patch Version"
Based on some docsets from other companies, I think the current wording is appropriate. When people are looking for these docs, I think they're looking to upgrade Astronomer rather than updating a version.

2021-01-19 19:55 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +For example, upgrading Astronomer from v0.16.4 to v0.16.5 would be considered upgrading to a patch version, whereas upgrading from v0.15.0 to v0.16.0 would be considered upgrading to the latest minor
Based on some docsets from other companies, I think the current wording is appropriate. When people are looking for these docs, I think they're looking to upgrade Astronomer rather than updating a version.

2021-01-19 20:02 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +
Took the capitalization out of "Platform Database", unless that's an official Astronomer term?

2021-01-19 20:13 UTC, merged