Cli guide
astronomer/docs pull request #202
Opened 2021-01-18 15:02 UTC by jwitz

Resolves https://app.zenhub.com/workspaces/documentation-5fcfce583ed44e0011db3db5/issues/astronomer/docs/167

This PR creates the first "Reference" guide for our Astronomer docset. The goal of a reference doc is slightly different from our other docs, mainly in that it doesn't provide info on a specific workflow or consideration. Rather, this serves as a more general aid to anyone having difficulty navigating the CLI help text or looking for more information on a feature referenced in the CLI.

I've now heard from a few people that this would be nice to have, especially since the CLI help text is nested in a way that it takes some serious time to find what you're actually looking for. Over time, I hope that some of the information included here is ported back to the CLI help text in service of a fully comprehensive experience. 

There are a few commands that I couldn't find information on, which I've commented on directly in the PR. If you're tagged to review this doc, please share whatever you know about them.

2021-01-18 15:03 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--system-sa`                | None       | ??                                                                                                           |
The roles of --system-sa and --user-id for both the `deployment service-account` and `workspace service-account` commands are unclear

2021-01-18 15:05 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--system-sa`               | None       | ??                                                                                                           |
See comment above on these two commands.

2021-01-18 15:05 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro deployment update
Can `astro deployment update` be used for anything else? Seems like a very general command to have such a specific use case.

2021-01-25 16:37 UTC, paolaperaza requested changes
This is a big one, @jwitz but dropped a bunch of initial comments!

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro auth <subcommand>` in your terminal to log in or out of your Astronomer platform. This is equivalent to using the login screen of the Astronomer UI.
```suggestion
Run `$ astro auth <subcommand> <base-domain>` in your terminal to log in or out of Astronomer. This is equivalent to using the login screen of the Astronomer UI. If you have access to more than one Astronomer platform, make sure to specify <base-domain> to authenticate to each.
```

Should we have diff versions of this for Enterprise v Cloud, or do you think have this doc be the exact same and just account for both?

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `login`    | For Cloud login, run `$ astro auth login gcp0001.us-east4.astronomer.io` to authenticate to a cluster. For Enterprise, run `$ astro auth login BASEDOMAIN`. |
```suggestion
| `login`    | To authenticate to Astronomer Cloud, run `$ astro auth login gcp0001.us-east4.astronomer.io`. For Enterprise, run `$ astro auth login <base-domain>`. |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Navigates between multiple installations of Astronomer on an Astronomer Enterprise platform.
```suggestion
Most applicable to Astronomer Enterprise users, this command lists the Astronomer clusters you have access to and allows you to navigate between them.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro cluster <subcommand>` in your terminal to see or access available clusters on your platform. This command is primarily used for Enterprise platforms with multiple clusters.
```suggestion
Run `$ astro cluster <subcommand>` in your terminal to see or access available Astronomer clusters.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `switch`   | Run `$ astro cluster switch` to retrieve a list of available clusters, then enter the ID of the cluster you want to switch to. |
```suggestion
| `switch`   | Run `$ astro cluster switch` to retrieve a list of available clusters, then enter the ID of the cluster you want to switch to. Once that command is successful, authenticate to that cluster by running, `$ astro auth login <base-domain>`. |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +brew install bash-Completion
```suggestion
$ brew install bash-Completion
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro config get` to see the current values for settings in your `config.yaml` file that you can reconfigure with the command. When you want to update a value, run `$ astro config set <value n
```suggestion
Run `$ astro config get` to list values for all settings in your `config.yaml` file. To update or override a value, run `$ astro config set <value-name>:<value>`
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +The values that you can update via the command line are:
@jwitz Are these the only values users can change here? Maybe we link out to "Apply a Config" change in a "Related Documentation" section, assuming this isn't the full list (we should link either way though).

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Deploys local code to an Airflow Deployment.
```suggestion
Deploys code in your Airflow project directory to any Airflow Deployment on Astronomer, as long as you have appropriate Workspace and Deployment-level permissions.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro deploy <your-deployment-release-name> <flags>` in your terminal to push a local Airflow project to your Airflow Deployment on Astronomer. A Deployment's release name can be found in the
```suggestion
Run `$ astro deploy <your-deployment-release-name> <flags>` in your terminal to push a local Airflow project to your Airflow Deployment on Astronomer. To identify your Deployment's **Release Name**, navigate to **Settings** >**Basics** > **Release Name** in the Astronomer UI or run `$ astro deployment list`.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Alternatively, you can run the command without specifying `<your-deployment-release-name>` to select from a list of possible Deployments.
```suggestion
If you run `$ astro deploy` without specifying `your-deployment-release-name`, the Astronomer CLI will output a list of Airflow Deployments in your Workspace to choose from.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--workspace-id + <your-workspace-name>` | Specifies the Workspace that the Airflow Deployment belongs to. Useful if you want to deploy without switching Workspaces |
```suggestion
| `--force`                                | Forces deploy even if there are uncommitted changes.                                                                      |
| `--prompt`                             | Forces prompt to choose target Deployment.                                                                                 |
| `--save`                                 | Saves deployment in config for future deploys.                                                                             |
| `--workspace-id + <your-workspace-name>` | Specifies the Workspace that the Airflow Deployment belongs to. Useful if you want to deploy without switching Workspaces. |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--workspace-id + <your-workspace-name>` | Specifies the Workspace that the Airflow Deployment belongs to. Useful if you want to deploy without switching Workspaces |
@jwitz What does `Saves deployment in config for future deploys ` mean? I've never tried this command so don't have a ton of context, but this explanation doesn't sound super clear to me.

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Manages various aspects of your Airflow Deployments.
```suggestion
Manages various deployment-level actions on Astronomer.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro deployment <subcommand>` in your terminal to create, delete, or manage Deployments. See the following entries of this guide for more information on each subcommand.
```suggestion
Run `$ astro deployment <subcommand>` in your terminal to create, delete, or manage an Airflow Deployment on Astronomer. See the following entries of this guide for more information on each subcommand.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Upgrades the Airflow version for a Deployment.
```suggestion
This command initializes the Airflow version upgrade process on any Airflow Deployment on Astronomer, though a change to the Astronomer Certified image in your `Dockerfile` is required to complete the process. If you do not specify `--desired-airflow-version`, this command will output a list of available versions of Airflow you can choose from and prompt you to pick one. The Astronomer CLI will only make available versions of Airflow that are higher than the version you're currently running in your `Dockerfile`.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Upgrades the Airflow version for a Deployment.
Is there an `upgrade` somewhere in this command? I thought it was:

> $ astro deployment airflow upgrade --deployment-id=<deployment-id>

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--deployment-id`           | String     | The name of the Deployment you're upgrading. |
```suggestion
| `--deployment-id`           | String     | The `deployment-id` of the Airflow Deployment whose Airflow version you want to upgrade. To find this, run `$ astro deployment list`. |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--desired-airflow-version` | String     | The Airflow version you're upgrading to.     |
```suggestion
| `--desired-airflow-version` | String     | The version of Apache Airflow you want to upgrade to, e.g. `1.10.14`. |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Creates a new Deployment on Astronomer.
```suggestion
Creates a new Airflow Deployment in your current Astronomer Workspace.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--cloud-role`      | String     | The role that annotates service accounts in the Deployment                            |
```suggestion
| `--cloud-role`      | String     | The role that annotates service accounts in the Deployment.                            |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--executor`        | String     | The Executor type for the Deployment. Can be `local`, `celery`, or `kubernetes`.      |
```suggestion
| `--executor`        | String     | The Airflow Executor for your Deployment. Can be `local`, `celery`, or `kubernetes`. If this flag isn't specified, `celery` will be assumed.     |
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Deletes a Deployment.
```suggestion
Deletes an Airflow Deployment from an Astronomer Workspace. This is equivalent to the **Delete Deployment** action in the Astronomer UI.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +`$ astro deployment delete <your-deployment-name>`
Is this the name of the deployment, or release name? (Asking because I'm not sure! But most commands ask for release name or deployment id, so maybe double check).

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Generates a list of Deployments from a single Workspace.
```suggestion
Generates a list of Deployments in your current Astronomer Workspace.
```

2021-01-25 16:37 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--all` | None       | Generates a list of Deployments from all Workspaces. |
Can you double check if this is across Workspaces, or just your current workspace?

2021-01-25 18:01 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Updates the IAM role for a Deployment. This is used only for Deployments hosted on Amazon EKS.
```suggestion
This command appends an IAM role to the Webserver, Scheduler and Worker pods within any individual Airflow Deployment on the platform. Only applicable to teams running Astronomer Enterprise on Amazon EKS.
```

2021-01-25 18:01 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Updates the IAM role for a Deployment. This is used only for Deployments hosted on Amazon EKS.
I'm actually not 100% sure this only applies to EKS - I know it's the only thing we have documented, but this command should also work for GKE or AKS I think.

2021-01-25 19:00 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Alternatively, you can run the command without specifying `<your-deployment>` to select from a list of possible Deployments.
I don't see `your-deployment` listed above - should that be a part of the original command?

2021-01-26 14:25 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro auth <subcommand>` in your terminal to log in or out of your Astronomer platform. This is equivalent to using the login screen of the Astronomer UI.
Seems like those versions could get out of sync fast, and that Cloud users will still wonder what certain Enterprise-specific commands will do (and vice versa). With that in mind, I think it's best to make a universal doc.

2021-01-26 14:39 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +The values that you can update via the command line are:
Based on the document that Alan sent me, these are all of the possible values that can be updated via the command line. Agreed re: adding that related documentation.

2021-01-26 14:55 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--workspace-id + <your-workspace-name>` | Specifies the Workspace that the Airflow Deployment belongs to. Useful if you want to deploy without switching Workspaces |
This one was pulled straight from the help text.. figured it might become more clear as I went through the rest of the commands, but that's definitely not the case. Based on some old Slack messages, it looks like this command might make it so that the directory you're in is permanently associated with the Deployment you select? So in the future, you could run astro deploy without needing to select a Deployment.

2021-01-26 14:59 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Alternatively, you can run the command without specifying `<your-deployment>` to select from a list of possible Deployments.
I assumed that this could work, but it actually doesn't - you do need to specify a Deployment, or else you get an error. Updating this now.

2021-01-26 15:23 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Upgrades the Airflow version for a Deployment.
Yep, thanks for catching that. Updated this wording to link out to the upgrade doc. I think it's okay to be redundant by linking both in a `Usage` section and the `Related Documentation` section.

2021-01-26 15:35 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +`$ astro deployment delete <your-deployment-name>`
The help text just says `astro deployment delete DEPLOYMENT`, which was the same for `upgrade`. I assume that means it needs a Deployment ID?

2021-01-26 15:37 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--all` | None       | Generates a list of Deployments from all Workspaces. |
The flag would imply that the base command only shows Deployments in your current Workspace.

2021-01-26 15:42 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--deployment-id` | String     | The Deployment you're getting the Service Account from. Use this flag as an alternative to specifying `<your-service-account-id>`. |
Good catch, this is actually mentioned in the help text but in a very odd format. Good that we're making it more clear here!

2021-01-26 15:46 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Gets a Service Account for a given Deployment.
Updated this wording a bit.

2021-01-26 15:47 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Updates the IAM role for a Deployment. This is used only for Deployments hosted on Amazon EKS.
Until we have a solid use case for the other clouds, I think this wording works.

2021-01-26 16:04 UTC, jwitz commented
Thank you for this thorough review @paolaperaza . Left some comments, applied suggestions or tweaked suggestions throughout the doc. To make things easier on your second pass, I tried applying some of your comments to as-of-yet unreviewed entries. When I did that, I found an additional undocumented command `astro workspace update`. This appears to have a completely different purpose than `astro deployment update` and has no flags or subcommands documented in help text, so I'm still searching for info on it.

2021-01-26 16:05 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Updates a Workspace name, as well as the users and roles assigned to a Workspace.
This is the exact text from the help text, and when you attempt to run it the command says you need to "specify a workspace ID and at least one attribute to update". However, none of these attributes are documented, and none of the flags are either.

2021-01-26 22:07 UTC, paolaperaza requested changes

2021-01-26 22:07 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +
```suggestion
> **Note:** This command only checks whether or not a new version of the Astronomer CLI is available. To actually upgrade the CLI to the latest version, run:
> 
> ```sh
> $ brew install astronomer/tap/astro
> ```
```

2021-01-26 22:07 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Creates a new user on your Astronomer platform. After specifying an email address and a password, an invitation email will be sent to the address you specified.
```suggestion
Creates a new user on Astronomer that's not associated with an existing Astronomer Workspace. An invitation email will be sent to the email address you specify. Once this user creates an account on Astronomer, they'll have the right to create a new Workspace and will be a Workspace Admin within it by default.
```

2021-01-26 22:07 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +- [Manage User Permissions on Astronomer Cloud](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/workspace-permissions)
```suggestion
- [Manage Workspace Permissions on Astronomer](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/workspace-permissions)
- [Manage Users on Astronomer Enterprise](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/manage-platform-users)
```

2021-01-26 22:07 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Displays the current versions for both the Astronomer CLI and your Astronomer Server.
```suggestion
Displays the running versions of both the Astronomer CLI and the Astronomer platform to which you are authenticated. If the minor versions of the Astronomer CLI and your Astronomer platform don't match, we encourage you to upgrade.
```

2021-01-26 22:07 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro version
Add reference to: https://www.astronomer.io/docs/enterprise/v0.16/develop/cli-quickstart

2021-01-27 14:06 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--workspace-id + <your-workspace-name>` | Specifies the Workspace that the Airflow Deployment belongs to. Useful if you want to deploy without switching Workspaces. |
This must be left over from my first draft where I didn't have a `Value Type` column. Rewrote this table to include that and make this usage more clear.

2021-01-27 14:12 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +### Flags
In the Flag table? It's not a flag because it's not specified with a `--`. Some required values end up in flags, while others are free-floating values. Another one of the many quirks of the CLI

2021-01-27 14:26 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--release-name`    | String     | A custom `release-name`. Only applies to Deployments using the `kubernetes` Executor. |
Not sure where I got this info from, but the release notes are definitely right.

2021-01-27 14:27 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--release-name`    | String     | A custom `release-name`. Only applies to Deployments using the `kubernetes` Executor. |
Should we also mention that config.yaml prereq here, or should that be in a related documentation section? Doesn't look like we have any documentation beyond the release note on it, but I can write the issue to put it in the Enterprise Configure a Deployment doc.

2021-01-27 14:30 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--all` | None       | Generates a list of Deployments from all Workspaces. |
Since we have a lot of language around "user" for the various user management commands, I think we should be consistent with the non-flag sections and refer to "the current user" as "you". Updated this usage in one other location.

2021-01-27 14:31 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Adds an existing user from the Workspace to a given Deployment.
Reworded this slightly.

2021-01-27 14:42 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Removes an existing user from the Workspace to a given Deployment.
Reworded this slightly.

2021-01-27 14:47 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +`$ astro deployment user list USERS <flags>`
That's what the help text says! But also now realizing the additional example offered doesn't even include that:

> Examples: $ astro deployment user list <deployment-id> --email=EMAIL_ADDRESS --user-id=ID --name=NAME

I think, then, that this is just a help text error. The command finds users via any of the flags + Deployment ID.

2021-01-27 14:57 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--cloud-role` | String     | The ARN for the IAM role. |
The help text doesn't say it is, and the example command doesn't contain it... but it also contains a bunch of undocumented flags (if they're even flags? There's no `--`: 

> astro deployment update UUID label=Production-Airflow description=example version=v1.0.0

Something tells me this command does *a lot* more than just append an IAM role.

2021-01-27 14:58 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Lets you modify certain settings on your Astronomer Enterprise platform without needing to push an entirely new configuration.
I like it! Just reworded slightly.

2021-01-27 15:07 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--role`                     | String     | The role you're updating the user to. Possible values are `DEPLOYMENT_VIEWER`, `DEPLOYMENT_EDITOR`, or `DEPLOYMENT_ADMIN`. |
Updated with the default value if `--role` is not specified.

2021-01-27 15:12 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Starts an Airflow cluster locally using `docker-compose`
Slightly reworded this.

2021-01-27 15:15 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Stops a locally running Airflow cluster.
Slightly reworded this.

2021-01-27 15:24 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Runs a test which checks whether a local Airflow project is ready to be upgraded to Airflow 2.0. You must be on Airflow 1.0.14 and in a project directory to run this command.
Took the second to last sentence out since that seemed like supplementary information that's better to have in the related documentation.

2021-01-27 15:26 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Creates a new user on your Astronomer platform. After specifying an email address and a password, an invitation email will be sent to the address you specified.
Updated this slightly.

2021-01-27 15:27 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Starts an Airflow cluster locally using `docker-compose`
Updated slightly

2021-01-27 15:28 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Runs a test which checks whether a local Airflow project is ready to be upgraded to Airflow 2.0. You must be on Airflow 1.0.14 and in a project directory to run this command.
Removed second to last sentence, as that information's probably more helpful to digest within the related documentation.

2021-01-27 15:28 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Stops a locally running Airflow cluster.
Updated slightly.

2021-01-27 15:29 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Creates a new user on your Astronomer platform. After specifying an email address and a password, an invitation email will be sent to the address you specified.
Updated slightly

2021-01-27 15:32 UTC, jwitz commented
Alright @paolaperaza think I resolved all comments here either by making your suggested changes or replying to you. Definitely feel like we're coming up to the point where the CLI help text is our last barrier to getting this published. Should we get a tech reviewer in here to resolve any last unclear commands/ flags?

2021-02-01 17:18 UTC, andriisoldatenko commented on enterprise/v0.16/reference/01_cli-reference.md
> +`$ astro deployment user add--deployment-id=<user-deployment-id> --role<user-role> <user-email-address> `
```suggestion
`$ astro deployment user add --deployment-id=<user-deployment-id> --role<user-role> <user-email-address> `
```

2021-02-01 18:14 UTC, andriisoldatenko commented
@jwitz found few missing commands/sub commands:
```
astro workspace switch
```

Missing good examples:
```
# Create default admin user.
astro dev run create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin
```

2021-02-01 20:03 UTC, jwitz commented
> @jwitz found few missing commands/sub commands:
> 
> ```
> astro workspace switch
> ```
> 
> Missing good examples:
> 
> ```
> # Create default admin user.
> astro dev run create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin
> ```

Thanks for this feedback @andriisoldatenko ! I tagged you in some additional spots where the use of a specific command was unclear based on the help text.

To begin with: for your `astro dev run` example, none of those flags are documented in help text. Is there a source file I can find those in?

2021-02-01 20:04 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--system-sa`                | None       | ??                                                                                                           |
@andriisoldatenko Do you have experience with these flags?

2021-02-01 20:05 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro deployment update
@andriisoldatenko Are there any additional uses for this command? Could also use a full list of flags here.

2021-02-01 20:06 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Updates a Workspace name, as well as the users and roles assigned to a Workspace.
@andriisoldatenko Are the flags/attributes for this command listed anywhere? They're not available in the help text.

2021-02-01 20:10 UTC, adam2k reviewed
This is looking good!  I left a couple minor edits, mostly whitespace missing.  I'll do one more pass over this.

2021-02-02 14:35 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro deploy <your-deployment-release-name> <flags>` in your terminal to push a local Airflow project to your Airflow Deployment on Astronomer. If you have the appropriate Workspace and Deploy
@jwitz It looks like my suggestion here didn't get pushed up (/the copy didn't change at all) - did commits get mixed up, or did you have thoughts on the suggestion in partic?

2021-02-02 14:35 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +### Flags
Ah got it got it, you're right

2021-02-02 14:35 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +When managing an existing Deployment using subcommands such as `delete` and `logs`, you additionally need to specify a Deployment in your command. In this case, you would run `$ astro deployment <sub
Same here!

2021-02-02 14:35 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `$ astro deployment airflow upgrade --deployment-id` to initialize the Airflow upgrade process. To finalize the Airflow upgrade process, complete all of the steps as described in [Upgrade Apache
And here :)

2021-02-02 14:35 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--deployment-id` | String     | The Deployment you're getting the Service Account from. Use this flag as an alternative to specifying `<your-service-account-id>`. |
Ok going to assume something was up with the commits! Lemme know if you want to chat about any of these.

2021-02-02 16:10 UTC, jwitz commented
Thanks for taking a look at this @adam2k ! I tagged Andrii in some places across the doc where there wasn't enough help text context to describe a command/ setting, could you please take a look at those spots as well and let me know if there's additional info we can include?

2021-02-02 19:29 UTC, andriisoldatenko commented
> > @jwitz found few missing commands/sub commands:
> > ```
> > astro workspace switch
> > ```
> > 
> > 
> > Missing good examples:
> > ```
> > # Create default admin user.
> > astro dev run create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin
> > ```
> 
> Thanks for this feedback @andriisoldatenko ! I tagged you in some additional spots where the use of a specific command was unclear based on the help text.
> 
> To begin with: for your `astro dev run` example, none of those flags are documented in help text. Is there a source file I can find those in?

`run           Run any command inside airflow webserver`

for instance:
```
astro dev run version
Running: airflow version
[2021-02-02 19:29:18,364] {plugins_manager.py:286} INFO - Loading 2 plugin(s) took 1.06 seconds
2.0.0+astro.2
```

2021-02-09 16:46 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--cloud-role` | String     | The ARN for the IAM role. |
Added additional commands here based on what I found in source code!

2021-04-12 17:49 UTC, adam2k commented
@jwitz @paolaperaza is this PR still a WIP or is it ready to be merged?

2021-04-12 23:03 UTC, paolaperaza reviewed
Lots o' comments here, @jwitz - I think there's still a good amount of opportunity for standardization, testing/validating, typo-fixing, and some additional context on some of these.

I went through about 70% of the doc, and figure with a thorough review you can likely cover what I'd comment on with the rest. It's a long one, so thank you for setting the foundation here!

2021-04-12 23:03 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Checks for a newer version of the Astronomer CLI.
```suggestion
Checks for the latest version of the Astronomer CLI, but does not perform the upgrade. To install a new version of the Astronomer CLI, follow the installation instructions at the top of this guide.
```

2021-04-13 00:54 UTC, adam2k commented on enterprise/v0.16/reference/01_cli-reference.md
> +This command can only be used in a project directory; it's most often used to restart a cluster when testing new DAGs or settings in a non-production environment. After using `astro dev kill`, you ca
It means a directory where you already ran `astro dev init`.  It's the directory where all your Airflow project files are located.

2021-04-13 00:56 UTC, adam2k commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `switch`   | Run `$ astro cluster switch` to retrieve a list of available clusters, then enter the ID of the cluster you want to switch to. Once that command is successful, authenticate to that clu
Yeah, that's right.  `Cluster ID` is referring to the numbers that appear in the list.

2021-04-13 13:59 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Allows Astronomer Enterprise users to switch between the Astronomer clusters they have access to.
This one's kind of a hard call. I think documentation-wise, either platform or installations would be better here. But the command itself refers to a cluster, so would it be confusing to refer to something else throughout these instructions?

2021-04-13 14:19 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `set`      | Updates a setting in your configuration to a new value |
Reworded the second one slightly. Don't thing `airflow.cfg` is the file being modified here?

2021-04-13 14:25 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--prompt`       | None       | Forces prompt for choosing a target Deployment.                                                                            |
Took the last phrase out, seems self-evident.

2021-04-13 14:26 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +
As in, add a note that you'll only see Deployments you have permissions to do so? I think that's self-evident, and if we add that here I think we'd probably want to add permission info to all other commands as well.

2021-04-13 14:32 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +- [Deploy to Astronomer via the CLI](https://www.astronomer.io/docs/enterprise/stable/deploy/deploy-cli)
See note above, I don't think this is the best place to mention permissions.

2021-04-13 14:45 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +When managing an existing Deployment using subcommands such as `delete` and `logs`, you additionally need to specify a Deployment in your command. In this case, you would run `$ astro deployment <sub
This is my bad, that usage *should* include the --deployment-id flag, which is required for all of these subcommands. The Deployment ID is the release name in the Astro UI, but when you run `astro deployments list` it appears under a column called "Deployment ID". Figured it was easier to frame it as the CLI-specific term.

2021-04-13 14:46 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro deployment airflow upgrade
This is the convention that should be followed for the rest of the guide. It's `astro auth login/logout` that's the odd one out here, because there's not enough information to warrant its own separate sections.

2021-04-13 15:06 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--all` | None       | Generates a list of running Airflow Deployments across all Workspaces that you have access to. |
Might need a help text fix here:
![Screen Shot 2021-04-13 at 10 06 03 AM](https://user-images.githubusercontent.com/74574233/114575517-7bdac000-9c37-11eb-9c85-3b091d3aa998.png)

2021-04-13 15:07 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--all` | None       | Generates a list of running Airflow Deployments across all Workspaces that you have access to. |
Oh lol, when I ran the command I got an API error that a Workspace ID was not specified. I think this is totally broken - will write the issue.

2021-04-13 15:22 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--since`  | Lookback time in `h` or `m` (e.g. `5m`, `2h`) | Limits past logs to those generated in the lookback window.         |
The syntax is `--search=timeout`, no quotes or additional formatting  I think this generally how CLIs format flags, so I didn't think that specifically needed to be called out.

That said, there's a lot of other problems with these commands. As you can see below, the `search` and `since` flags give an error, and it never says you need to specify a release name in the help text (though you clearly do).

![Screen Shot 2021-04-13 at 10 21 33 AM](https://user-images.githubusercontent.com/74574233/114577916-ab8ac780-9c39-11eb-8dbe-cd90aea5fd9e.png)

2021-04-13 15:24 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro deployment service-account create
I think we should keep this as is, as it already follows the convention of other `astro deployment` subcommands. If we should change anything, it's `astro auth`.

2021-04-13 15:30 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--category`                 | String     | The Category for the new Service Account. The default value is `default`.                                        |
I think this is another example of a really out-of-date command. As you can see below, even doing this correctly yields a Prisma error. Should we be fixing this in the CLI first before publishing here? 

![Screen Shot 2021-04-13 at 10 26 10 AM](https://user-images.githubusercontent.com/74574233/114578633-4be0ec00-9c3a-11eb-84ec-672000b1ae35.png)

<img width="577" alt="Screen Shot 2021-04-13 at 10 28 17 AM" src="https://user-images.githubusercontent.com/74574233/114578921-9a8e8600-9c3a-11eb-961d-dc14b4b98df5.png">

2021-04-13 16:07 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +`$ astro deployment update <your-deployment-id> <flags>`
You need Deployment ID, but it needs to be the UUID and it's not specified with a flag at all. Major help text renovations are needed here!!!

2021-04-14 14:52 UTC, jwitz commented
Phew! Thanks for the comprehensive comments @paolaperaza , I have a lot of changes, suggestions, and replies here. I tried taking some of your existing recommendations and applying them to the unreviewed section of the doc, and I also did some overall style changes (like removing `$` from commands). Any functionality issues have also been documented in Notion.

2021-04-17 22:05 UTC, paolaperaza reviewed
@jwitz Great job doing another round on this! I left some more comments, but nothing major. Give them another look and then I think we'll be ready for a final approval + merge.

2021-04-17 22:05 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Generates a list of all Workspaces.
```suggestion
Generates a list of all Workspaces you have access to.
```

2021-04-17 22:05 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--category`                | String     | The Category for the service account. The default value is `default`.                                        |
```suggestion
| `--category`                | String     | The Category for the service account. This is optional, and the default value is `Not set`.                                        |
```

2021-04-17 22:05 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Creates a new user in your current Workspace.
```suggestion
Creates a new user in your current Workspace. If the user has already authenticated to Astronomer, they will automatically be granted access to the Workspace. If the user does not have an account on Astronomer, they will receive an invitation to the platform via email.
```

2021-04-17 22:05 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Searches for users in your current Workspace.
```suggestion
Outputs a list of all users with access to your current Workspace.
```

2021-04-19 14:25 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +If you have access to more than one Astronomer platform, you'll have access to multiple `<base-domains>`. When switching between platforms, make sure to log out of one `<base domain>` before logging
Not sure why I miss these suggestions! Maybe it's because I work in the "Files Changed" section of GitHub, and comments disappear there is the phrase in question has been edited for another reason.

2021-04-19 14:28 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +- [Deploy to Astronomer via the CLI](https://www.astronomer.io/docs/enterprise/stable/deploy/deploy-cli)
Don't feel too strongly about this either way, so down to add it.

2021-04-19 14:30 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro deployment create
The ordering is purely alphabetical throughout the entire document, which matches the order that these commands appear in the CLI.

2021-04-19 14:45 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +## astro dev
Given this is a reference guide, I think we should keep things alphabetical.

2021-04-19 14:59 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `astro version` to see both your CLI version and Astronomer platform version.
There's only two listed versions when you run the command, I think this might be self-evident?

2021-04-19 15:00 UTC, jwitz commented on enterprise/v0.16/reference/01_cli-reference.md
> +| `--category`                | String     | The Category for the service account. The default value is `default`.                                        |
Took the line out about it being optional, since that's implied as it is with the other flags.

2021-04-19 16:41 UTC, paolaperaza reviewed
@jwitz Awesome, thanks for this additional review! The language in here looks ready to rock, so we're real close here. Two higher-level comments before we merge:

- Alphabetical ordering of these commands makes a lot of sense - good call. I'm good with that.
- Have you thought about how we translate these to Cloud? Do you envision removing Enteprise-only commands, and changing back the links from Enterprise to Cloud? Or bulk applying this reference guide to Cloud in its current state?

2021-04-19 16:41 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +- [CLI Quickstart](https://www.astronomer.io/docs/enterprise/v0.16/develop/cli-quickstart)
Eek sorry, this link might actually make more sense: https://www.astronomer.io/docs/enterprise/v0.16/develop/customize-image#access-to-the-airflow-cli


(Though we need to test & update those guidelines to actually use `astro dev run` instead of `docker exec -it` 👀 )

2021-04-19 16:41 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +Run `astro version` to see both your CLI version and Astronomer platform version.
Fair enough, but does it hurt to add this if it may save a couple of people from confusion?

2021-04-19 22:08 UTC, jwitz commented
@paolaperaza 225 comments later... I think this is good to go 😬

2021-04-19 23:45 UTC, paolaperaza commented on enterprise/v0.16/reference/01_cli-reference.md
> +If you have access to more than one Astronomer platform, you'll have access to multiple `<base-domains>`. When switching between platforms, make sure to log out of one `<base domain>` before logging
Oh word - no problem!

2021-04-20 00:06 UTC, paolaperaza approved these changes
Alright, I think we are good here @jwitz ! Excited to see this live 🎉  Going to go ahead and merge + check up on the website build. Awesome work on this!

2021-04-20 00:06 UTC, paolaperaza commented on enterprise/v0.16/09_resources/03_cli-reference.md
> +
```suggestion
- cURL

For a detailed changelog of all Astronomer CLI versions, see [Releases in GitHub](https://github.com/astronomer/astro-cli/releases).
```

2021-04-20 00:06 UTC, paolaperaza commented on enterprise/v0.23/09_resources/03_cli-reference.md
> +- cURL
```suggestion
- cURL

For a detailed changelog of all Astronomer CLI versions, see [GitHub Releases](https://github.com/astronomer/astro-cli/releases).
```

2021-04-20 00:06 UTC, paolaperaza commented on enterprise/v0.15/09_resources/03_cli-reference.md
> +- cURL
```suggestion
- cURL

For a detailed changelog for all Astronomer CLI versions, see [GitHub Releases](https://github.com/astronomer/astro-cli/releases).
```

2021-04-20 00:11 UTC, merged