Astro Quickstart [Work in progress]
astronomer/docs pull request #2021
Opened 2023-03-17 21:03 UTC by lzdanski

**Context**
- The information required for a completely new user to run their first DAG on Astro are spread across multiple documents. 
- This QuickStart consolidates all of the fundamental steps required. 

** To-do**
[ ] Check images and identify any that need updated screenshots
[ ] Improve and clarify steps for running a DAG in Astro after deploying code to Astro (step 9)
[ ] Identify duplicated content that can be removed from other guides
[ ] Identify places in quickstart that should link to more detailed content in other Docs areas

2023-03-21 17:03 UTC, jwitz commented on astro/create-dag.md
> +![Example DAG in the Airflow UI](/img/docs/sample-dag.png)
```suggestion
On the Airflow UI home page, you should see the DAGs from your `dags` directory in the Airflow UI.

![Example DAG in the Airflow UI](/img/docs/sample-dag.png)

When you create an Astro project, the Astro CLI uses port `8080` for the Airflow webserver and port `5432` for the Airflow metadata database by default. If these ports are already in use on your local computer, an error message might appear. To resolve this error message, see [Test and troubleshoot locally](test-and-troubleshoot-locally.md#ports-are-not-available).
```

2023-03-21 17:04 UTC, jwitz commented on astro/create-dag.md
> +If your project builds successfully, the Airflow UI automatically opens in your default webserver at `https://localhost:8080/`.
```suggestion
It might take a few minutes for your project to build. When your project builds successfully, the Airflow UI automatically opens in your default webserver at `https://localhost:8080/`.
```

2023-03-21 17:06 UTC, jwitz commented on astro/create-dag.md
> +Now that you've created your Airflow project and confirmed that your project runs Airflow locally, you can log in to Astro from the CLI.
Can we reword this so that it doesn't sound like having a project is a prerequisite for logging into the Astro CLI? It's not necessarily even  a prerequisite for deploying the project, as running the default project locally is more of a test of your machine than the Astro project itself.

2023-03-21 17:06 UTC, jwitz commented on astro/create-dag.md
> +## Step 5: Access the Astro Cloud UI
```suggestion
## Step 5: Access the Cloud UI
```

2023-03-21 17:08 UTC, jwitz commented on astro/create-dag.md
> +    - To authenticate with your Google account, click **Continue with Google**, choose an account, enter your username and password, and then click **Sign In**. If your Organization selects this log
```suggestion
1. Go to `https://cloud.astronomer.io`, and select one of the available options to access the Cloud UI.
```
I think these descriptions are out of date 😓 you don't necessarily need an invite anymore, gotta remember to update the login doc. But also, Organization can disable these methods so the options don't apply to all users. Maybe it's better to just be general here?

2023-03-21 17:11 UTC, jwitz commented on astro/create-dag.md
> +  You can leave the other fields at their default values.
```suggestion
    You can leave the other fields at their default values.
```

2023-03-21 17:11 UTC, jwitz commented on astro/create-dag.md
> +  You can leave the other fields at their default values.
This would be a good time to assure users that we won't be running up a crazy tab for the resources they'll be using

2023-03-21 17:13 UTC, jwitz commented on astro/create-dag.md
> +## Step 7: Deploy your Astro Project to your Astro Deployment
```suggestion
## Step 7: Deploy your Astro project to your Astro Deployment
```

2023-03-21 17:20 UTC, jwitz commented on astro/create-dag.md
> +These circles represent different [states](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#task-instances) that your DAG and task runs can be in. However, these are onl
```suggestion
```
I think we could use a "Next steps" section here, or possibly another step that tells users to check the Cloud UI for additional metrics about their Airflow task runs?

2023-03-21 17:21 UTC, jwitz commented on sidebarsAstro.js
> +      items: ["trial", "create-project", "log-in-to-astro", "create-first-DAG", "create-deployment"],
Given that we create a Deployment in this step, I could see moving "Create a Deployment" to the "Manage Deployments" tab. WDYT?

2023-03-23 21:28 UTC, lzdanski commented on astro/create-dag.md
> +Now that you've created your Airflow project and confirmed that your project runs Airflow locally, you can log in to Astro from the CLI.
I think actually this clarification makes more sense in the *Build your project locally* step - explaining why to build locally, so I added it there. Also, as I am a very typical user who jumps around in quickstarts all the time, having the "this is technically an optional step" information in the actual optional step is really helpful if something isn't working as I expected, and it seems like there can be some troubleshooting involved if the ports are configured a certain way.

2023-03-27 14:33 UTC, jwitz approved these changes
LGTM! Just some minor suggestions

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +4. After you finish testing your DAGs in your Deployment, pause your DAG by opening Airflow and clickincing the slider button next to `example-dag-basic`. This prevents your example DAG from running
```suggestion
3. While all DAGs can run on a schedule defined in their code, you can manually trigger a DAG run at any time from the Airflow UI. Manually trigger `example-dag-basic` by clicking the play button under the **Actions** column. During development, running DAGs on demand can help you identify and resolve issues.

    After you press **Play**, the **Runs** and **Recent Tasks** sections for the DAG start to populate with data.

    ![DAG running in the Airflow UI](/img/docs/tutorial-run-dag.png)

    These circles represent different [states](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#task-instances) that your DAG and task runs can be in. However, these are only high-level summaries of your runs.

4. Click on the name of the DAG, **example-dag-basic**, to open the **Grid** view for the DAG. To see if your DAG ran successfully, the most recent entry in the grid should have green squares for all of your tasks.

5. After you finish testing your DAGs in your Deployment, pause your DAG by opening Airflow and clicking the slider button next to `example-dag-basic`. This prevents your example DAG from running automatically, so it won't consume resources unexpectedly.
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +1. Open your Astro Workspace. Since you ran your example DAG, your Workspace has summary information about your DAG runs and the health of your Deployment available.
```suggestion
Open your Astro Deployment. Because you ran your example DAG, your Deployment information page now has summary information about your DAG runs and the health of your Deployment.
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +You might want to delete your Deployment after you finish triggering your DAG test runs and exploring Astro.
```suggestion
To limit resource usage, you might want to delete your Deployment after you finish triggering your DAG test runs.
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +2. Select the ellipses to see the more options, and select **Delete**.
```suggestion
2. Select the ellipses to see more options, then click **Delete**.
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +1. Open the **Deployments** page in Astro and select your Deployment.
```suggestion
1. In the Cloud UI, open your Workspace, then open your Deployment.
```
Weird one in our style guide, but we always try to refer to the UI as the "Cloud UI" instead of "Astro", since Astro embodies a lot more than just the UI

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +After your project builds successfully, the Airflow UI automatically opens in your default webserver at `https://localhost:8080/`.
```suggestion
After your project builds successfully, the Airflow UI automatically opens in your default web browser at `https://localhost:8080/`.
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +This quickstart gives you a demonstration for how to run your first DAG on Astro by building a sample Astro project, deploying it to the Astro Cloud, and then triggering a DAG run, which is an instan
```suggestion
This quickstart gives you a demonstration for how to run your first DAG on Astro by building a sample Astro project, deploying it to the Astro Cloud, and then triggering a DAG run.

To run an Airflow DAG on Astro, you need to complete the following:

- Create an _Astro project_. An Astro project contains the set of files necessary to run Airflow, including dedicated folders for your DAG files, plugins, and dependencies. After you've tested these files locally, the Astro project structure makes it easy to deploy your pipelines to Astro.
- Authenticate and log in to Astro. 
- Create a Deployment to host your Airflow environment.
- Deploy your project to Astro.
- Trigger your DAG on Astro. 
```

2023-03-27 14:33 UTC, jwitz commented on astro/create-dag.md
> +Building your project locally allows you to test your DAGs locally and confirm that your example Astro project builds correctly before you run it remotely in Astro.
```suggestion
Building your project locally allows you to test your DAGs locally and confirm that your example Astro project builds correctly before you run it remotely in Astro. While this step is not required for deploying and running your code on Astro, Astronomer recommends always using the Astro CLI to test locally before deploying.
```
We could also add "Optional" to the step title, but I'm OK either way on that

2023-03-27 17:38 UTC, lzdanski commented on astro/create-dag.md
> +## Step 2: Build your project locally
```suggestion
## Step 2: (Optional) Build your project locally
```

2023-04-03 05:14 UTC, paolaperaza requested changes
@lzdanski We're close here! I made some comments, overall with the theme of wanting to make sure we're:

- Only giving the user what they need to know
- But also giving them basic logical context for what they're doing

I've been hearing a lot about how confusing Astro terminology can be, and I think we can do a  little better at giving those definitions tied to actionable steps.

Will take another pass!!!

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +Before you can run any DAG in Astro, unpause it in your remote Airflow instance and then manually trigger a DAG run.
```suggestion
When you deploy your Astro project, all example DAGs will initially be paused and will not start running automatically. To run one of these example DAGs according to its schedule, you have to unpause it from the Airflow UI.
```

Tryna give the user more logical end-to-end context here

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +1. Select the **Open Airflow** button in the Astro UI to open the Airflow dashboard.
```suggestion
1. In the Deployment page of the Cloud UI, click the **Open Airflow** button.
```

- Always Cloud UI! In style guide
- For a button, I think we say `click` and we keep `select` when there's a dropdown or a. menu of options

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +2. Click the slider button next to `example-dag-basic` to unpause it, and the DAG starts to run on the schedule defined in its code.
```suggestion
2. In the main DAGs view of the Airflow UI, click the slider button next to `example-dag-basic` to unpause it. If you hover over the DAG, it should say `DAG is Active`. When you do this, the DAG starts to run on the schedule that is defined in its code.
```

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +3. While all DAGs can run on a schedule defined in their code, you can manually trigger a DAG run at any time from the Airflow UI. Manually trigger `example-dag-basic` by clicking the play button und
```suggestion
3. Manually trigger a DAG run of `example-dag-basic` by clicking the play button under the **Actions** column. This schedules all task instances in the DAG in addition to its schedule. When you develop DAGs on Astro, triggering a DAG run instead of waiting for the DAG schedule can help you quickly identify and resolve issues.
```

Not perfect, but in gen I think we can do better wording here

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +    These circles represent different [states](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#task-instances) that your DAG and task runs can be in. However, these are
Consider wording here -- what does "these are only high-level summaries of your runs"? mean exactly

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +5. After you finish testing your DAGs in your Deployment, pause your DAG by opening Airflow and clicking the slider button next to `example-dag-basic`. This prevents your example DAG from running aut
```suggestion
5. Pause your DAG by clicking the slider button next to `example-dag-basic`. This prevents your example DAG from running automatically and consuming your Deployment resources.
```

- You weren't really testing this DAG
- "by opening Airflow" -- Airflow was already open?

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +## Step 7: View your DAG status in Astro
```suggestion
## Step 7: View your DAG status in the Cloud UI
```

i might specify cloud UI here since you're hopping between UIs and it could be confusing

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +Open your Astro Deployment. Because you ran your example DAG, your Deployment information page now has summary information about your DAG runs and the health of your Deployment.
- Would be good to add 1 statement about what we expect you to do in Cloud UI vs. Airflow UI
- Is this the analytics page?

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +- [Set up CI/CD](/astro/set-up-ci-cd)
Perfect links!

2023-04-03 05:14 UTC, paolaperaza commented on astro/create-dag.md
> +## Step 2: (Optional) Build your project locally
I'm going back and forth on making this optional... let's maybe remove that part? If we think people should do it, we include it in the doc -- if we don't, let's remove

(I say keep/make people do it)

2023-04-03 15:44 UTC, lzdanski commented on astro/create-dag.md
> +1. Create a new directory for your Astro project:
This is a good question - how beginner are we considering beginner? beginner to coding vs beginner to Astro/Airflow (with some development experience)

2023-04-03 18:08 UTC, lzdanski commented on astro/create-dag.md
> +3. While all DAGs can run on a schedule defined in their code, you can manually trigger a DAG run at any time from the Airflow UI. Manually trigger `example-dag-basic` by clicking the play button und
Do we need to bring up task instances at this point in the intro/quickstart? We haven't introduced the concept before this step - unless they're already familiar with DAGs.

2023-04-03 18:09 UTC, lzdanski commented on astro/create-dag.md
> +    These circles represent different [states](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#task-instances) that your DAG and task runs can be in. However, these are
Removed this sentence - I don't think it's necessary detail for a quickstart.

2023-04-03 18:20 UTC, lzdanski commented on astro/create-dag.md
> +Open your Astro Deployment. Because you ran your example DAG, your Deployment information page now has summary information about your DAG runs and the health of your Deployment.
* Took a stab at a summary
* This is a screenshot of the analytics page - this info is completely blank when you set it up as a quickstart and it's an immediate confirmation of "hey it worked! there's stuff there!" that I noticed so I wanted to give it a little highlight. If there's a better choice, happy to change or tweak this status.

2023-04-03 18:24 UTC, lzdanski commented on astro/create-dag.md
> +- Trigger your DAG on Astro.
I think in this case, it makes more sense to have the full definitions in the context of the step. I was on the fence when I was looking at the **Create a project** step, and it really helps orient and teach to have it all at the same time. Seeing a short bullet list of "things we're doing" at the beginning is kind of a summary introduction. I don't know that we're teaching at this point in the quickstart, while we are definitely teaching later on.

2023-04-05 21:22 UTC, paolaperaza approved these changes
@lzdanski This looks GREAT! So clean, so clear, so to the point while also being comprehensive.

I have a couple of potential nice to have comments, but this looks 10/10. You are good to merge!!!!!

Can you send link to @rachelshahvar when this is published? We're gonna add this to Cloud UI

2023-04-05 21:22 UTC, paolaperaza commented on astro/create-first-dag.md
> +
Maybe add one sentence about how local stuff doesn't require auth

2023-04-05 21:22 UTC, paolaperaza commented on astro/create-first-dag.md
> +    For more information about possible Deployment health statuses, see [Deployment health](deployment-metrics.md#deployment-health). Or, to learn more about how to customize your Deployment settings
```suggestion
    For more information about possible Deployment health statuses, see [Deployment health](deployment-metrics.md#deployment-health). Or, to learn more about how to customize your Deployment settings, see [Configure a Deployment](configure-deployment-resources).
```

This should work?

2023-04-05 21:22 UTC, paolaperaza commented on astro/create-first-dag.md
> +4. Click on the name of the DAG, **example-dag-basic**, to open the **Grid** view for the DAG. To see if your DAG ran successfully, the most recent entry in the grid should have green squares for all
Could argue for a screenshot here?

2023-04-05 22:59 UTC, rachelshahvar commented
Looks like you're missing a step 4 and have two step 5's...

2023-04-06 22:49 UTC, lzdanski commented on astro/create-first-dag.md
> +4. Click on the name of the DAG, **example-dag-basic**, to open the **Grid** view for the DAG. To see if your DAG ran successfully, the most recent entry in the grid should have green squares for all
To add in follow up PR, I noticed when taking screenshots for a different issue that my Light/Dark display settings seem to be causing problems with the colors and I want to make sure I don't post something immediately wrong.

2023-04-07 15:51 UTC, merged