update login command
astronomer/docs pull request #2031
Opened 2023-03-20 18:56 UTC by sunkickr

login command flag descriptions were wrong/confusing

2023-03-20 19:10 UTC, lzdanski requested changes
This is a very unintuitive terminology quirk - _login_ is a noun or adjective where the verb is _log in_. So we get fun sentences like "Log in to your account on the login page."

2023-03-20 19:10 UTC, lzdanski commented on astro/cli/astro-login.md
> +| `-l`, `--login-link`  | The CLI will provide you with a link to login in with instead of automatically opening up the browser | None            |
```suggestion
| `-l`, `--login-link`  | The CLI will provide you with a link to log in with instead of automatically opening up the browser | None            |
```

2023-03-20 19:10 UTC, lzdanski commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Login by specifing an Auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
```suggestion
| `-t`, `--token-login` | Log in by specifying an Auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
```

2023-03-20 19:10 UTC, lzdanski commented on astro/cli/astro-login.md
> +# You then copy a generated token from the UI(cloud.astronomer.io/token) and use it with this command. Use this flag for a browserless login.
```suggestion
# Copy a generated token from the UI (cloud.astronomer.io/token) and use it with this command. Use this flag for a browserless login.
```

2023-03-21 10:34 UTC, jwitz commented on astro/cli/astro-login.md
> +# Copy a generated token from the UI (cloud.astronomer.io/token) and use it with this command. Use this flag for a browserless login.
```suggestion
# Copy a generated token from the UI (cloud.astronomer.io/token) and use it with this command for browserless login.
```

2023-03-21 10:35 UTC, jwitz commented on astro/cli/astro-login.md
> +# Copy a generated token from the UI (cloud.astronomer.io/token) and use it with this command for browserless login.
```suggestion
# The CLI prompts you for a generated token from cloud.astronomer.io/token for browserless login.
```

2023-03-21 10:37 UTC, jwitz commented on astro/cli/astro-login.md
> +astro login --token-login <auth-token>
```suggestion
astro login --token-login eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjRmeDJYNVFNa2o3Q25ycVNyX1ZuTyJ9.eyJodHRwczovL2FzdHJvbm9tZXIuaW8vand0L2F1dGhfY29ubmVjdGlvbiI6eyJpZCI6ImNvbl9VazNBeTNDZGZ4Q1J5Z3BmIiwibmFtZSI6Imdvb2dsZS1vYXV0aDIiLCJzdHJhdGVneSI6Imdvb2dsZS1vYXV0aDIifSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmFzdHJvbm9tZXIuaW8vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTYzNjEzNTExNTY5MTg0ODg0MzEiLCJhdWQiOlsiYXN0cm9ub21lci1lZSIsImh0dHBzOi8vYXN0cm9ub21lci1wcm9kLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NzkzODc3NDAsImV4cCI6MTY3OTQ3NDE0MCwiYXpwIjoiWXE5YXRZWFRlZjZ0ZVpZSlhrd2xRbDZsWHBOS2t6OHUiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIiwicGVybWlzc2lvbnMiOltdfQ.mk5nkukONLjmayTL5RLytLAYO7w6PU-0PeCyNmyP7LNUBgPGlG22m3PzJ3jaLFRiIy-8sG0nJ_vmjPhBYYI_61WEFdVj3oGmIbHXc4gVlICaTn_MbbchVDFRVzp09akYcjWvD4TeXpIAp9Fc0-4b-FbCAxryETmS5W8JxyRscp1n9lOFia_yYgWXbXrETs9Guz_z6ErfYmGA71XiihJcy41ccGnb4Agf_aEn-Dwh3tCaKRJ-Mxb_yLKSZHKRyjNfZH9v_ZW1eDPfkF3oV0c4qFCIx8vHryK3q3h2jpsDw_r-_VmuNqSRxrY8ms0ixtq98PmjQ0vDvmiUYZPXnxBNOw
```

2023-03-21 10:37 UTC, jwitz commented on astro/cli/astro-login.md
> +# Copy a generated token from the UI (cloud.astronomer.io/token) and use it with this command for browserless login.
```suggestion
# Use a generated token from cloud.astronomer.io/token for browserless login.
```

2023-03-21 10:37 UTC, jwitz approved these changes

2023-03-21 10:38 UTC, jwitz commented on astro/cli/astro-login.md
> +astro login --token-login <auth-token>
In the spirit of this examples section, I added a realistic auth token here so people know what type of input is needed.

2023-03-23 03:51 UTC, paolaperaza approved these changes
Happened to see this and chime in! A couple minor suggestions in addition to what Jake already had in there

2023-03-23 03:51 UTC, paolaperaza commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Log in by specifying an auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
```suggestion
| `-l`, `--login-link`  | The CLI will provide you with a URL to the log in page of the Cloud UI instead of automatically opening up your browser. You can use this link to manually begin the authentication process | None            |
| `-t`, `--token-login` | Log in by manually specifying an authentication token. This flag is used primarily to log in without needing to access your browser or to log in from a different browser | A valid authentication token from `cloud.astronomer.io/token` |
```

2023-03-23 03:51 UTC, paolaperaza commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Log in by specifying an auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
Thoughts on this wording @jwitz @sunkickr ?

2023-03-23 09:37 UTC, jwitz commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Log in by specifying an auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
what more meaning are we getting out of "to log in without needing to access your browser or to log in from a different browser" compared to "browserless login"? I also dont think we need "manually" before "Specifying".

Made a minor edit to the first entry suggestion but besides that LGTM

2023-03-28 00:49 UTC, paolaperaza commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Log in by specifying an auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
I think "browserless logging" potentially is confusing without additional color. Because you DO need "a" browser to get the token, you're just using the browser of another machine right?

This still LGTM tbh but will defer to you Jake!

2023-03-28 08:36 UTC, jwitz commented on astro/cli/astro-login.md
> +| `-t`, `--token-login` | Log in by specifying an auth token with the flag. This flag is used primarily for browserless login | Auth Token from `cloud/astronomer.io/token` |
I updated it to be more specific about the use case - looking back, I don't think "browserless login" is a particularly intuitive or popular term, so agreed we should elaborate a bit

2023-03-28 08:37 UTC, merged