Replace DAG factory references with gusty in Dynamic DAGs and SQL guide
astronomer/docs pull request #2034
Opened 2023-03-21 11:29 UTC by TJaniF

Gusty is more versatile than DAG factory and more actively maintained. As discussed replacing the DAG factory example in the Dynamic DAGs guide with gusty, while keeping a one sentence reference to the DAG factory for SEO purposes. 

I noticed that the SQL guide also had a section using the DAG factory to define Airflow DAGs from SQL via yaml, here the switch to gusty makes even more sense because gusty allows task creation from SQL files directly :)

2023-03-21 16:19 UTC, kentdanas requested changes
Looks great @TJaniF! A couple minor comments about organizing the sections, but should be quick updates.

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +A notable tool for dynamically creating DAGs from the community is [gusty](https://github.com/chriscardillo/gusty). `gusty` is an open source Python library for dynamically generating Airflow DAGs. T
```suggestion
A notable tool for dynamically creating DAGs from the community is [gusty](https://github.com/chriscardillo/gusty). `gusty` is an open source Python library for dynamically generating Airflow DAGs. Tasks can be created from YAML, Python, SQL, R, or Jupyter Notebooks.
```
Double check me on accuracy here with this edit - wanted to simplify the list a bit.

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +You can install gusty in your Airflow environment by running `pip install gusty` in the command line. Astro CLI users can use the package by adding `gusty` to the `requirements.txt` file.
```suggestion
You can install gusty in your Airflow environment by running `pip install gusty` from your command line. Astro CLI users can use the package by adding `gusty` to your `requirements.txt` file. 
```

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +You can install gusty in your Airflow environment by running `pip install gusty` in the command line. Astro CLI users can use the package by adding `gusty` to the `requirements.txt` file.
Assuming we want to be consistent throughout with using `gusty`, gusty, or Gusty. I would assume the first, based on our style guide, but there are a few places in here where it's in plain text.

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +This example file structure will lead to the creation of 2 DAGs from the contents of the `my_gusty_dags` directory. `my_dag_1` contains two tasks each defined in their own YAML file. `my_dag_2` conta
```suggestion
The following file structure will lead to the creation of 2 DAGs from the contents of the `my_gusty_dags` directory. `my_dag_1` contains two tasks each defined in their own YAML file. `my_dag_2` contains one task, `task_0`, defined from a YAML file, as well as the two task groups `my_task_group_1` and `my_task_group_2`, containing two tasks each. The latter task group contains two tasks defined from SQL files.
```

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +Note that it is possible to use DAGs defined using gusty and regularly defined DAGs in the same Airflow environment by adding the regular DAGs to the `dags` directory outside of the `my_gusty_dags` f
Let's move this note below the example code snippets

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +In order to create DAGs from the `my_gusty_dags` directory, a `creating_gusty_dags.py` script calling gustys `create_dags` function needs to be present.
```suggestion
To create DAGs from the `my_gusty_dags` directory, you need a Python script that calls `gusty`'s `create_dags` function. In this example, a script called `creating_gusty_dags.py` in the project's root directory contains the following code.
```

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +Tasks can be defined in YAML for any existing and local operator without requiring Python knowledge. The example below shows how to use gusty to define a BashOperator task in YAML. The `dependencies`
```suggestion
Tasks can be defined in YAML for any existing and local operator. The example below shows how to use `gusty` to define a BashOperator task in YAML. The `dependencies` parameter was set to make this task dependent on `task_1` having completed successfully.
```
What does "existing and local operator" mean in this context?

2023-03-21 16:19 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +Learn more about gusty features in the [repository README](https://github.com/chriscardillo/gusty/blob/main/README.md). Additionally, you can explore two fully functional gusty environments, the [gus
```suggestion
Learn more about gusty features in the [repository README](https://github.com/chriscardillo/gusty/blob/main/README.md). Additionally, you can explore two fully functional gusty environments, the [gusty-demo](https://github.com/chriscardillo/gusty-demo) and the [gusty-demo-lite](https://github.com/chriscardillo/gusty-demo-lite), to see several implementation examples.
```

2023-03-21 16:19 UTC, kentdanas commented on learn/airflow-sql.md
> +Once you've installed gusty in your Airflow environment, you can add a YAML statement on top of your SQL file specifying which operator to use, operator parameters and task dependencies.
Same comment here on `gusty` vs gusty.

2023-03-21 16:19 UTC, kentdanas commented on learn/airflow-sql.md
> +Once you've installed gusty in your Airflow environment, you can add a YAML statement on top of your SQL file specifying which operator to use, operator parameters and task dependencies.
Link here to how to install gusty? Don't think we should say you need to install it without describing how to do so or linking to other docs

2023-03-22 13:12 UTC, TJaniF reviewed
Thank you for the review @kentdanas! :)
I think I addressed all comments.

@astronaut-chris Good morning :) I assume/hope you are happy with us switching the tool described to generate DAGs from yaml and/or SQL from DAG factory to gusty. 
Please say if there is anything I got wrong about how gusty works or something you want me to add. My goal was to have a short and simple description focussing on using yaml and SQL files in order to replace the DAG factory content.

2023-03-22 13:12 UTC, TJaniF commented on learn/airflow-sql.md
> +Once you've installed gusty in your Airflow environment, you can add a YAML statement on top of your SQL file specifying which operator to use, operator parameters and task dependencies.
Yeah I agree. There are no docs on how to install gusty since it is justs a pip package, but I can add the same sentence I had in the other guide :)

2023-03-22 13:12 UTC, TJaniF commented on learn/airflow-sql.md
> +View the [gusty section in the Dynamically generate DAGs in Airflow](dynamically-generating-dags.md#tools-for-dynamically-creating-dags) guide or the gusty documentation for example code for the `MET
Good point. I linked the example code sections from the gusty Readme.

2023-03-22 14:59 UTC, astronaut-chris reviewed
Looks great.

The `latest_only=False` thing is the only gotcha, I think.

Your graph didn't have a `LatestOnlyOperator`, so you might have noticed this?

2023-03-22 14:59 UTC, astronaut-chris commented on learn/airflow-sql.md
> +dependencies: ["task_0"]
```suggestion
dependencies: 
    - task_0
```

A nicer way to list dependencies?

2023-03-22 14:59 UTC, astronaut-chris commented on learn/dynamically-generating-dags.md
> +env: {"MY_ENV_VAR": "Hello!"}
```suggestion
env:
    MY_ENV_VAR: "Hello!"
```

Cleaner representation?

2023-03-22 14:59 UTC, astronaut-chris commented on learn/dynamically-generating-dags.md
> +    globals()
```suggestion
    globals(),
    # By default, gusty places a LatestOnlyOperator at the root of the DAG.
    # We can disable this behavior by setting latest_only=False
    latest_only=False
```

Maybe a regrettable UX ☹️

2023-03-22 15:24 UTC, TJaniF commented
Thanks for the review @astronaut-chris! Added a note about the how to disable latest only in the SQL guide too. :)

2023-03-22 15:24 UTC, kentdanas commented on learn/dynamically-generating-dags.md
> +A notable tool for dynamically creating DAGs from the community is [gusty](https://github.com/chriscardillo/gusty). `gusty` is an open source Python library for dynamically generating Airflow DAGs. T
Gotcha, in that case I would just update it to "....SQL, R Markdown, and Jupyter Notebooks" so it's one list rather than two stuck together, if that makes sense.

2023-03-22 15:33 UTC, kentdanas approved these changes
LGTM! One more minor comment, otherwise good to move on to docs team review.

2023-03-22 16:05 UTC, astronaut-chris commented on learn/dynamically-generating-dags.md
> +    │   │   ├── METADATA.yaml
```suggestion
    │   │   ├── METADATA.yml
```

2023-03-22 16:05 UTC, astronaut-chris commented on learn/dynamically-generating-dags.md
> +    │       ├── METADATA.yaml
```suggestion
    │       ├── METADATA.yml
```

2023-03-22 16:49 UTC, TJaniF commented
@jwitz I think this one is ready for you :)

2023-03-23 09:48 UTC, jwitz commented on learn/airflow-sql.md
> +You can install `gusty` in your Airflow environment by running `pip install gusty` from your command line. Astro CLI users can use the package by adding `gusty` to your `requirements.txt` file.
```suggestion
You can install `gusty` in your Airflow environment by running `pip install gusty` from your command line. If you use the Astro CLI, you can alternatively add `gusty` to your Astro project `requirements.txt` file.  
```

2023-03-23 10:02 UTC, jwitz approved these changes
LGTM! Just minor suggestions

2023-03-23 10:02 UTC, jwitz commented on learn/dynamically-generating-dags.md
> +Note that it is possible to use DAGs defined using `gusty` and regularly defined DAGs in the same Airflow environment by adding the regular DAGs to the `dags` directory outside of the `my_gusty_dags`
```suggestion
Note that to use gusty-generated DAGs and standard DAGs in the same Airflow environment, ensure that your standard DAGs are in your `dags` directory outside of the `my_gusty_dags` folder.
```

2023-03-23 10:02 UTC, jwitz commented on learn/dynamically-generating-dags.md
> +Learn more about `gusty` features in the [repository README](https://github.com/chriscardillo/gusty/blob/main/README.md). Additionally, you can explore two fully functional `gusty` environments, the
```suggestion
Learn more about gusty features in the [repository README](https://github.com/chriscardillo/gusty/blob/main/README.md). Additionally, you can explore two fully functional gusty environments: The [gusty-demo](https://github.com/chriscardillo/gusty-demo) and the [gusty-demo-lite](https://github.com/chriscardillo/gusty-demo-lite).
```

2023-03-23 10:27 UTC, merged