Restructure CI/CD docs
astronomer/docs pull request #2036
Opened 2023-03-21 15:16 UTC by jwitz

Part 1 of the deploy code restructure (This PR) entails:

- Breaking out all CI/CD templates into their own docs, sorted by tools.
- Creating an overview page that includes information about each available template type
- Minor inline updates to standardize around template wording/ references

Part 2 of this project (future PR):

- Rename "Deploy" tab to be more descriptive
- Create a "Deploy" overview page that describes what deploying is and what it's not, and how it's different from Deployments. 

Holding off on redirects for the moment until we agree on titles/ IDs for the docs

2023-03-21 15:18 UTC, jwitz commented on astro/ci-cd-templates/aws-codebuild.md
> +### Single branch implementation
Trying something new and calling these sub-templates "implementations" to differentiate from the high level template types. It's essentially the same template, but with extra logic for handling the given scenarios.

2023-03-21 15:19 UTC, jwitz commented on astro/ci-cd-templates/aws-codebuild.md
> +Use the following templates to automate code deploys to Astro using [AWS Codebuild](https://aws.amazon.com/codebuild/).
Should we always link back to the overview page or is that self-intuitive?

2023-03-21 15:19 UTC, jwitz commented on astro/ci-cd-templates/aws-codebuild.md
> +Image-only deploy templates build a Docker image and push it to Astro whenever you update any file in your Astro project.
Finding it challenging to strike the right balance between rehashing the overview content and linking out

2023-03-21 21:23 UTC, lzdanski commented on astro/ci-cd-templates/aws-codebuild.md
> +Use the following templates to automate code deploys to Astro using [AWS Codebuild](https://aws.amazon.com/codebuild/).
IMO it's intuitive, but could also add it to related links at the bottom?

2023-03-21 21:51 UTC, lzdanski requested changes
Did a first pass review! This looks fantastic and the overview really helped me already better understand the different options available.

2023-03-21 21:51 UTC, lzdanski commented on astro/ci-cd-templates/aws-codebuild.md
> +Image-only deploy templates build a Docker image and push it to Astro whenever you update any file in your Astro project.
Asked this in the overview page comment, but do we use any kind of font decoration for key terms or technical terms? It helps provide sort of a visual cue to folks that it's a summary or definition, and makes it feel a little less awkward/redundant. so for example:

*Image-only deploy templates* build a Docker image and push it to Astro whenever you update any file in your Astro project.

Or 

[Image-only deploy templates](overview link) build a Docker image and push it to Astro whenever you update any file in your Astro project.

2023-03-21 21:51 UTC, lzdanski commented on astro/ci-cd-templates/azure-devops.md
> +Use the following template to automate [single branch deploys](template-overview.md#template-types) to Astro using [Azure DevOps](https://dev.azure.com/).
This is fantastic.

2023-03-21 21:51 UTC, lzdanski commented on astro/ci-cd-templates/github-actions.md
> +### Multiple branch implementation
I'd lean towards having these in tabs vs separate headers presented sequentially like this _unless_ you have to do the single branch implementation before adding complexity with the multi-branch.

2023-03-21 21:51 UTC, lzdanski commented on astro/ci-cd-templates/gitlab.md
> +When you create environment variables that will be used in multiple branches, you may want to protect the branch they are being used in. Otherwise, uncheck the `Protect variable` flag when you create
```suggestion
When you create environment variables that will be used in multiple branches, you may want to protect the branch where you use them. Otherwise, uncheck the `Protect variable` flag when you create the variable in GitLab. For more information on protected branches, see [GitLab documentation](https://docs.gitlab.com/ee/user/project/protected_branches.html#configure-a-protected-branch).
```

2023-03-21 21:51 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +2. At the root of your Git repository, add a [Jenkinsfile](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/) that includes the following script:
Tech writer pet peeve: the technical term really is `jenkinsfile`. ugh. I always forget and correct it.

2023-03-22 14:04 UTC, jwitz commented on astro/ci-cd-templates/template-overview.md
> +- An [Astro project](create-project.md) that is hosted in a place that your CI/CD tool can access.
I think we've both missed the most important part of this prerequisite, which is that all of these projects must be hosted in Git repositories. Some CI/CD tools are only compatible with specific repo platforms (CodeBuild comes to mind), so I think that's where the specifics come in.

2023-03-22 14:04 UTC, jwitz commented on astro/ci-cd-templates/template-overview.md
> +- An [Astro project](create-project.md) that is hosted in a place that your CI/CD tool can access.
Might just be better to break out prerequisites in each product-based doc, thoughts?

2023-03-22 14:26 UTC, jwitz commented on astro/ci-cd-templates/template-overview.md
> +
"DAG-only" applies only to the deployment process. The end result is the same for both image pushes and DAG pushes, which is that you have a running Airflow environment in Docker containers on Astro. There's some low level implementation details for how we actually get DAGs from a DAG-only deploy to that Docker image, but all code will run in a Docker image regardless. 

What makes DAG-based pipeliness even more complicated is that you will still build and push an image if you update any project files, such as `requirements.txt`.

I think we've fully ended `venv` support along with our legacy image (Astronomer Certified). Docker is our main mode for doing anything based on Astro Runtime at the moment, with the exception that you can use Runtime with [Podman](https://podman-desktop.io/) locally.

2023-03-22 14:27 UTC, jwitz commented
Thanks for the review @lzdanski ! I responded to some of your comments and made a few changes based on your recommendations, including using italics on new terms we're defining.

2023-03-23 14:36 UTC, lzdanski approved these changes
Looked through resolved comments and preview build - LGTM

2023-03-31 15:23 UTC, sunkickr approved these changes
LGTM

2023-03-31 18:12 UTC, paolaperaza requested changes
Requesting changes real quick @lzdanski -- let's:

- Address inconsistencies between CI/CD tool docs
- Add link to other CI/CD docs in the intros
- Add "Apache Airflow" to descriptions

Few other minor comments but this is looking close!

2023-03-31 18:12 UTC, paolaperaza commented on astro/ci-cd-templates/template-overview.md
> +description: Use pre-built templates to get started with automating code Deploys
We missed a wrong title here

2023-04-03 16:09 UTC, paolaperaza requested changes

2023-04-03 16:09 UTC, paolaperaza commented on astro/ci-cd-templates/template-overview.md
> +_Preview Deployments_ are Deployments which are automatically created and deleted when you create a feature branch from your main Astro project branch. The Preview Deployment has the same configurati
```suggestion
_Preview Deployments_ are Deployments that correspond to a temporary feature branch in your Git repository. They are automatically created when the branch is created and deleted when the branch is deleted. You can use Preview Deployments to quickly test a particular set of DAGs and avoid paying for the infrastructure cost of the Deployment when you promote your DAG code to a permanent base Deployment. The Preview Deployment has the same configuration as the base Deployment.
```

2023-04-03 16:09 UTC, paolaperaza commented on astro/ci-cd-templates/template-overview.md
> +- Deploy your changes to your base Deployment after you merge your changes into your main branch.
Consistency with capital `p` preview or not? (I _think_ let's not but we can discuss)

2023-04-03 16:09 UTC, paolaperaza commented on astro/ci-cd-templates/template-overview.md
> +On GitHub, the Astronomer-maintained [Deploy preview action](https://github.com/astronomer/deploy-action/tree/deployment-preview#deployment-preview-templates) includes sub-actions for each of these s
```suggestion
If you use GitHub Actions, Astronomer maintains a [GitHub action for Deployment previews](https://github.com/astronomer/deploy-action/tree/deployment-preview#deployment-preview-templates) in the GitHub Marketplace that includes sub-actions for each of these steps.

These sub-actions are equivalent to the four shell scripts in the topics below.
```

2023-04-03 16:09 UTC, paolaperaza commented on astro/set-up-ci-cd.md
> +title: 'Develop a CI/CD pipeline for deploying code to Astro'
```suggestion
title: 'Choose a CI/CD Strategy for deploying code to Astro'
```

2023-04-03 16:09 UTC, paolaperaza commented on astro/set-up-ci-cd.md
>  sidebar_label: 'Set up CI/CD'
```suggestion
sidebar_label: 'Choose a CI/CD strategy'
```

2023-04-04 01:34 UTC, paolaperaza approved these changes
Alrighty @lzdanski... many hours later I think I've got a version here that I feel good about merging.

Can you take a peek for broken links and typos, and otherwise go ahead and merge whenever you're ready? Let's hold off on additional changes here for now until @jwitz gets back.

2023-04-04 14:31 UTC, lzdanski requested changes
Doing final editing changes through GH suggestions

2023-04-04 14:31 UTC, lzdanski commented on astro/ci-cd-templates/github-actions.md
> +1. Set the following as [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository):
```suggestion
### Implementation

1. Set the following as [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository):
```

2023-04-04 14:35 UTC, paolaperaza commented on astro/ci-cd-templates/github-actions.md
> +- [DAG-based deploy templates](template-overview.md#dag-based-templates)
```suggestion
- [Image-only deploy templates](template-overview.md#image-only-templates)
- [DAG-based deploy templates](template-overview.md#dag-based-templates)
- [Deployment preview templates](template-overview.md#deployment-preview-templates)
```

2023-04-04 14:42 UTC, lzdanski approved these changes

2023-04-04 14:42 UTC, merged