Create IDE literal expression documentation
astronomer/docs pull request #2045
Opened 2023-03-23 11:36 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/2030

2023-03-23 11:37 UTC, jwitz commented on astro/cloud-ide/run-sql.md
> +    By default, your input is formatted as a literal string and is defined in your DAG with quotation marks. To use a Python expression to define any of these values, click **Python expression** next
```suggestion
    By default, your input is formatted as a literal string and is defined in your DAG with quotation marks. To format your input as a Python expression, click **Python expression** next to the value name. If you already entered a literal string before changing this setting, remove the quotation marks that the IDE adds to your Python expression.
```

2023-03-24 11:11 UTC, jwitz commented on astro/cloud-ide/run-sql.md
> +8. If you're using Warehouse SQL cells, configure the following additional fields to define your output table:
Sure, I assume that if a user doesn't input this then we create a temp table in their warehouse?

2023-03-24 12:02 UTC, jlaneve commented on astro/cloud-ide/run-sql.md
> +8. If you're using Warehouse SQL cells, configure the following additional fields to define your output table:
Yep, that's right!

2023-03-24 14:59 UTC, lzdanski requested changes

2023-03-24 14:59 UTC, lzdanski commented on astro/cloud-ide/run-sql.md
> +    After you change this setting, your input for the value is defined in the DAG as a Python expression without quotation marks. You can use your input to call any Python value in your pipeline, suc
It wasn't clear to me if we turned on the Python expression setting or turned it off - so instead of referring to it just as "changed" i needed something a little more specific.

2023-03-27 18:29 UTC, lzdanski approved these changes

2023-03-28 09:10 UTC, jwitz commented on astro/release-notes.md
> +- In the Astro Cloud IDE, you can now specify the output table for a Warehouse SQL cell using both literal and Python expressions. See [Create a SQL cell](run-sql.md#create-a-sql-cell).
```suggestion
- In the Astro Cloud IDE, you can now specify the output table for a Warehouse SQL cell using both literal and Python expressions. See [Create a SQL cell](cloud-ide/run-sql.md#create-a-sql-cell).
```

2023-03-29 12:39 UTC, merged