Dbt integration tutorial update - Cosmos tutorial
astronomer/docs pull request #2058
Opened 2023-03-26 22:14 UTC by TJaniF

2023-03-26 22:25 UTC, TJaniF commented on learn/airflow-dbt-cosmos.md
> +    astronomer-cosmos==0.5.0
Comment to remove the pinned version here before merging. The reason I added this is because currently you need to use version `0.5.0` explicitly because it contains a bug fix necessary to run the tutorial DAG. The version was yanked due to a different bug (you currently have to restart Airflow every time you make a change to the dbt models), so importing without a pinned version will retrieve `0.4.2`.

2023-03-27 19:49 UTC, kentdanas requested changes
Thanks for tackling this @TJaniF! Made some initial comments but they're mostly minor, let me know if you want to chat through any of them.

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +3. Within the `my_energy_project` directory create a YAML file called `dbt-project.yml`. Use the following YAML configuration to create a dbt project called `my_energy_project` which has its models i
```suggestion
3. Within the `my_energy_project` directory, create a YAML file called `dbt-project.yml`. Use the following YAML configuration to create a dbt project called `my_energy_project` which has its models in the `models` sub-directory.
```

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +7. In order for changes in the local `dbt` folder to be synchronized with the `dbt` folder in the Airflow components Docker containers, the folder needs to be mounted. Create a file called `docker-co
```suggestion
7.  Create a file called `docker-compose.override.yml` in your Astro project folder and copy the following contents into the file:
```

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +    ```
```suggestion
    ```
This mounts your `dbt` folder to the Docker containers running Airflow when you start up your project.

```

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +3. Create a new connection named `db_conn`. Select the connection type and supplied parameters based on which data warehouse you are using, note that for some tools you might need to add the [relevan
```suggestion
3. Create a new connection named `db_conn`. Select the connection type and supplied parameters based on the data warehouse you are using. For a Postgres connection, enter the following information:
```

Let's put this "note that for some tools you might need to add the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and restart Airflow, in order to have the correct connection type" as a note at the bottom of the section.

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +To create a full DAG from your dbt models use the `DbtDag` class, as shown in the [Astronomer dbt provider documentation](https://astronomer.github.io/astronomer-cosmos/dbt/usage.html#full-dag).
I'm not totally clear on what this comment means. Didn't we just create a full DAG from dbt models?

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +Congratulations! You've run a DAG using the Astronomer dbt provider to automatically create tasks from dbt models. The Astronomer dbt provider is under active development, learn more about up to date
```suggestion
Congratulations! You've run a DAG using the Astronomer dbt provider to automatically create tasks from dbt models. The Astronomer dbt provider is under active development. You can learn more about it in the [Astronomer dbt provider documentation](https://astronomer.github.io/astronomer-cosmos/index.html).
```

2023-03-27 19:49 UTC, kentdanas commented on learn/airflow-dbt.md
> +    This DAG consists of 2 tasks defined with the Astro Python SDK and one `DbtTaskGroup`:
I think it's worth adding a few more call outs in this section about the work the astro dbt provider is doing automatically. Doesn't have to be a ton of text since we also mention it in the intro, but I kind of lost that thread reading through it and it's a really cool feature that I think we want to make sure people grasp.

2023-03-27 19:50 UTC, kentdanas commented on learn/airflow-dbt.md
> +    - Host: your Postgres host address.
```suggestion
    - Host: Your Postgres host address.
```

2023-03-28 21:17 UTC, TJaniF reviewed
Thank you for your review @kentdanas :) Accepted all suggestions and addressed the comments.

2023-03-28 23:17 UTC, kentdanas approved these changes
This is looking great @TJaniF! I left a couple more minor comments, but otherwise this is good to move on to review from somebody on the "Cosmos team"

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +title: "Orchestrate dbt Core with the Astronomer dbt provider"
Should this be "dbt Core jobs" here as well, like the cloud one?

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +In this tutorial we will use an example dbt job that consists of two dbt models. The first model, called `select_country`, will select the data for a specific country. The second model, called `creat
```suggestion
In this tutorial we will use an example dbt job that consists of two dbt models. The first model, called `select_country`, will select the data for a country you select. The second model, called `create_pct`, will use the table created by the first model to calculate the percentage of renewable and solar energy capacity in that country.
```

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +1. Create a folder called `dbt` in your Astro project. The Astronomer dbt provider will by default look for dbt projects in a `dbt` directory inside of your `AIRFLOW_HOME` directory. This behavior ca
The "overriding" comment here is a bit confusing to me. Maybe we can say something like "You can modify the directory that stores the dbt projects for specific DAGs or task groups by setting the `dbt_root_path` param". (or something like that, if my comment isn't accurate)

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +2. In the `dbt` directory, create a sub-directory called `my_energy_project`. This folder will contain all files related to the dbt project `my_energy_project`.
```suggestion
2. In the `dbt` directory, create a sub-directory called `my_energy_project`.
```
Think we can remove the second sentence unless it's conveying dbt-specific information (in which case I would define what a "dbt project" is)

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +For some tools you might need to add the [relevant provider package](https://registry.astronomer.io/) to requirements.txt and restart Airflow, in order to have the correct connection type available.
```suggestion
For some databases you might need to add the [relevant provider package](https://registry.astronomer.io/) to requirements.txt and restart Airflow in order to have the correct connection type available.
```

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +    - the `load_file` task uses the [Astro Python SDK `load file` operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html) to load the contents of the local CSV
```suggestion
    - The `load_file` task uses the [Astro Python SDK `load file` operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html) to load the contents of the local CSV file into the data warehouse.
```

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +    - the `transform_data` task group is created from the dbt models. Using the models defined in Step 4, the task group will contain two nested task groups with two tasks each, one for `dbt run`, th
```suggestion
    - The `transform_data` task group is created from the dbt models. Using the models defined in Step 4, the task group will contain two nested task groups with two tasks each, one for `dbt run`, the other for `dbt test`.
```

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +    - the `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to use pandas to run an analysi
```suggestion
    - The `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to run an analysis on the final table created through the dbt models using `pandas` and to log the results.
```

2023-03-28 23:17 UTC, kentdanas commented on learn/airflow-dbt.md
> +    The `DbtTaskGroup` of the Astronomer dbt provider package automatically scans the `dbt` folder for dbt projects and creates a task group containing one Airflow task for every dbt command run on e
```suggestion
    The `DbtTaskGroup` function of the Astronomer dbt provider package automatically scans the `dbt` folder for dbt projects and creates a task group (`transform_data` in this example) containing one Airflow task for every dbt command run on every model in the project. Additionally, the provider can infer the model dependency within the dbt project and will set the Airflow task dependencies accordingly.
```
I'm a little confused by "run on every model in the project" part of the middle sentence. Otherwise this extra context looks great and is what I was envisioning :)

2023-03-30 21:20 UTC, jlaneve reviewed
I wonder if it's worth uploading the code to a repository - that way, if a user wants to get started immediately instead of each step being a copy/paste they can. Thoughts?

Can we also link to the Cosmos docs after the section about using it as a "learn more" CTA?

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +The [Astronomer dbt provider](https://astronomer.github.io/astronomer-cosmos/), also known as Cosmos, allows you to automatically create Airflow tasks from dbt models, seamlessly integrating dbt jobs
small nit: can we call this the Astro dbt provider? It's referenced here and a few other places

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +1. Create a folder called `dbt` in your Astro project. The Astronomer dbt provider will by default look for dbt projects in a `dbt` directory inside of your `AIRFLOW_HOME` directory. You can modify t
```suggestion
1. Create a folder called `dbt` in your Astro project. The Astronomer dbt provider will by default look for dbt projects in a `dbt` directory inside of your `AIRFLOW_HOME` directory. You can modify the directory in which `DbtDag` or `DbtTaskGroup` searches for dbt models by providing a different path to the `dbt_root_path` parameter.
```

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +1. Create a folder called `dbt` in your Astro project. The Astronomer dbt provider will by default look for dbt projects in a `dbt` directory inside of your `AIRFLOW_HOME` directory. You can modify t
Can we make a note about putting the `dbt` directory in the `dags` folder? If you do that, you can use DAG-based deploys. See https://github.com/astronomer/cosmos-dev/blob/main/dags/jaffle_shop.py#L27-L28 for an example.

We haven't updated our default path or docs yet (will do that for a 1.0 release) to not break current implementations.

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +          - ./dbt:/usr/local/airflow/dbt
if you put the dbt directory in the dags directory, you don't need this!

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +## Step 5: Configure a data warehouse connection
not necessarily asking for a change here, but should someone use the airflow_settings.yaml file or the airflow UI to create connections locally?

2023-03-30 21:20 UTC, jlaneve commented on learn/airflow-dbt.md
> +    <CodeBlock language="python">{cosmos_dag}</CodeBlock>
Not sure how we generally think about writing DAGs, but IMO a lot of these comments feel unnecessary and the DAG can be shortened quite a bit - examples of code that's self explanatory but still has comments:
```
# import tools from the Astro SDK
from astro import sql as aql
from astro.sql.table import Table, Metadata
from astro.files import File
```

```
# get the airflow.task logger
task_logger = logging.getLogger("airflow.task")
```

```
# set variables
CONNECTION_ID = "db_conn"
DB_NAME = "energy_db"
SCHEMA_NAME = "energy_schema"
CSV_FILEPATH = "include/subset_energy_capacity.csv"
DBT_PROJECT_NAME = "my_energy_project"
```

```
# set dependencies
...
```

2023-03-30 21:40 UTC, kentdanas commented on learn/airflow-dbt.md
> +## Step 5: Configure a data warehouse connection
Generally this is user preference. In most tutorials we show using the Airflow UI because we've gotten feedback in the past that a lot of users do it that way. and the more important part is showing _what_ goes in the connection (usually the more confusing part)

2023-03-30 21:42 UTC, kentdanas commented
> I wonder if it's worth uploading the code to a repository - that way, if a user wants to get started immediately instead of each step being a copy/paste they can. Thoughts?
> 
> Can we also link to the Cosmos docs after the section about using it as a "learn more" CTA?

@jlaneve thanks for your review! I'll let Tamara address your specific comments, but re: putting the code in a repo to copy - we will definitely upload this DAG to the registry and link to it from the tutorial in case anybody prefers that, but we still want to show the break down step by step. This is consistent with how we do all our integrations tutorials, and the purpose is to reinforce understanding of each necessary piece and how it all fits together.

2023-03-31 12:05 UTC, TJaniF reviewed
Thank you @jlaneve for your review! I think I addressed all your comments/made the changes.

Kenten already explained why we have this step by step explanation but yes, there definitely should be the option to clone a repository too, I put the project up here: https://github.com/astronomer/astro-dbt-provider-tutorial-example and made the PR for it to be added to the registry. :)

@kentdanas I realized I never tested the DAG for the bash example and it is outdated, made a new example that uses a venv and should work with never Airflow versions too :)

@jwitz One that was long time overdue ready for you :)
One note for this request: 
> can we also link to the Cosmos docs after the section about using it as a "learn more" CTA?

I added a `tip` note but maybe there is a better way to have a button maybe there is a better place and way to have this CTA?

2023-03-31 16:31 UTC, jlaneve commented on learn/airflow-dbt.md
> +    <CodeBlock language="python">{cosmos_dag}</CodeBlock>
I do the same but I'm trying to get better about it 🙂

2023-03-31 16:37 UTC, jlaneve approved these changes
the cosmos tutorial looks good, thank you so much for putting this together! only adding one small change to track the registry link so we don't accidentally merge this before it's ready

2023-03-31 16:37 UTC, jlaneve commented on learn/airflow-dbt.md
> +The DAG used in this tutorial is accessible in the Astronomer registry ADD LINK LATER and the full Astro project can be cloned from [this repository](https://github.com/astronomer/astro-dbt-provider-
leaving a comment here to track the registry link action item

2023-04-02 21:51 UTC, TJaniF commented on learn/airflow-dbt.md
> +The DAG used in this tutorial is accessible in the Astronomer registry ADD LINK LATER and the full Astro project can be cloned from [this repository](https://github.com/astronomer/astro-dbt-provider-
This is the PR to wait for: https://github.com/astronomer/daedalus/pull/319 :)

2023-04-06 21:28 UTC, pohek321 commented on learn/airflow-dbt.md
> +    pip install --no-cache-dir dbt-core dbt-postgres && deactivate
`dbt-postgres` will actually install `dbt-core` as a dependency, so you don't need to explicitly list it here! Instead you could just do this:

```Dockerfile
RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
pip install --no-cache-dir dbt-postgres && deactivate
```

2023-04-06 21:31 UTC, TJaniF commented on learn/airflow-dbt.md
> +    pip install --no-cache-dir dbt-core dbt-postgres && deactivate
Thank you! That makes a lot of sense 😄  Just to double check: I assume this is true for all (official) dbt adapters?

2023-04-12 13:24 UTC, jwitz requested changes
Looks great @TJaniF ! Requesting changes because I had a few questions and want to do one more pass, but overall the content is great. Love the example DAG and data being used.

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +    - Connection ID: `db_conn`.
```suggestion
    - **Connection ID**: `db_conn`.
```
Bold all field names

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +For some databases you might need to add the [relevant provider package](https://registry.astronomer.io/) to requirements.txt and restart Airflow in order to have the correct connection type availabl
```suggestion
If a connection type for your database isn't available, you might need to add the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and run `astro dev restart` to have the connection type available.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +## Step 6: Write a dbt DAG
```suggestion
## Step 6: Write your Airflow DAG
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +    - The `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to run an analysis on the final
```suggestion
    - The `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to run an analysis on the final table using `pandas` and logs the results.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +    The `DbtTaskGroup` function of the Astro dbt provider package automatically scans the `dbt` folder for dbt projects and creates a task group (`transform_data` in this example) containing Airflow
```suggestion
    The `DbtTaskGroup` function of the Astro dbt provider package automatically scans the `dbt` folder for dbt projects and creates a task group (`transform_data` in this example) containing Airflow tasks for running and testing your dbt models. Additionally, the provider can infer dependencies within the dbt project and will set your Airflow task dependencies accordingly.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +3. (Optional) Choose which country's data to analyze by specifying your desired `country_code` in the `dbt_args` parameter of the DbtTaskGroup. Note that this [dataset](https://github.com/astronomer/
```suggestion
3. (Optional) Choose which country's data to analyze by specifying your desired `country_code` in the `dbt_args` parameter of the DbtTaskGroup. See the [dataset](https://github.com/astronomer/learn-tutorials-data/blob/main/subset_energy_capacity.csv) for all available country codes.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +4. Run the DAG manually by clicking on the play button and view the DAG in the graph view (double click on the task groups in order to expand them).
```suggestion
4. Run the DAG manually by clicking the play button and view the DAG in the graph view. Double click the task groups in order to expand them and see all tasks. 
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +The [Astro dbt provider](https://astronomer.github.io/astronomer-cosmos/), also known as Cosmos, allows you to automatically create Airflow tasks from dbt models, seamlessly integrating dbt jobs into
Surprised that we're referring to this as the "Astro dbt provider"  instead of Cosmos throughout the doc. I thought we were trying to socialize the Cosmos name?

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +5. Navigate to the logs of the `log_data_analysis` task to see the proportional solar and renewable energy capacity development in the country you selected.
```suggestion
5. Open the logs of the `log_data_analysis` task to see the proportional solar and renewable energy capacity development in the country you selected.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +:::
```suggestion
```
Let's link this in the intro, rather than at the end (especially since the note before is also a link to the docs)

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +You can use the [BashOperator](https://registry.astronomer.io/providers/apache-airflow/modules/bashoperator) to execute specific dbt commands. Note that it is recommended to create a virtual environm
```suggestion
You can use the [BashOperator](https://registry.astronomer.io/providers/apache-airflow/modules/bashoperator) to execute specific dbt commands. It's recommended to run `dbt-core` and the dbt adapter for your database in a virtual environment because there often are dependency conflicts between dbt and other packages.
```
Recommended

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +Using the `BashOperator` to run `dbt run` and other dbt commands be useful during development. However, running dbt at the project-level has several issues:
```suggestion
Using the `BashOperator` to run `dbt run` and other dbt commands be useful during development. However, running dbt at the project level has a couple of issues:
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +Astronomer recommends to use the Astro dbt provider as shown in the tutorial above, whenever possible.
```suggestion
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +- Low observability into what execution state the project is in.
```suggestion
- There is low observability into what execution state the project is in.
```

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +Astronomer recommends to use the Astro dbt provider as shown in the tutorial above, whenever possible.
Don't think we need to repeat this

2023-04-12 13:24 UTC, jwitz commented on learn/airflow-dbt.md
> +An alternative way to gain more visibility into the steps dbt is running in each task is to use a dbt-generated `manifest.json` file. This file is generated in the target directory of your `dbt` proj
```suggestion
Using a dbt-generated `manifest.json` file gives you more visibility into the steps dbt is running in each task. This file is generated in the target directory of your `dbt` project and contains its full representation. For more information on this file, see the [dbt documentation](https://docs.getdbt.com/reference/dbt-artifacts/).
```

2023-04-17 15:41 UTC, TJaniF reviewed
Thank you for the review @jwitz ! Accepted all suggestions and hopefully answered all questions 🙂

2023-04-17 15:41 UTC, TJaniF commented on learn/airflow-dbt-cloud.md
> +The [dbt Cloud Airflow provider](https://registry.astronomer.io/providers/dbt-cloud) allows users to orchestrate and execute actions in dbt Cloud as DAGs. Running dbt with Airflow ensures a reliable,
Hmmmm....rereading this now I am not sure if it is ok to claim that you have _better_ observability with Airflow over the dbt models, because dbt cloud has a lot of observability built in. The value add is more that the dbt model runs are integrated with insight into tasks in other tools, which the previous sentence already states. I think I will remove the last sentence here. :)

2023-04-17 15:41 UTC, TJaniF commented on learn/airflow-dbt.md
> +The [Astro dbt provider](https://astronomer.github.io/astronomer-cosmos/), also known as Cosmos, allows you to automatically create Airflow tasks from dbt models, seamlessly integrating dbt jobs into
Yeah, I think the idea is that there will be several Astro providers? I also only learned about the renaming recently.

2023-04-17 15:41 UTC, TJaniF commented on learn/airflow-dbt.md
> +The DAG used in this tutorial is accessible in the Astronomer registry ADD LINK LATER and the full Astro project can be cloned from [this repository](https://github.com/astronomer/astro-dbt-provider-
Note: the PR will be held until TaskGroups can be displayed in the registry (it will be the guinea pig for that functionality) so I am taking out that sentence for the first merge of this tutorial and add the registry link back in once the DAGs are available there :)

2023-04-17 15:41 UTC, TJaniF commented on learn/airflow-dbt.md
> +## Step 6: Write a dbt DAG
haha `dbt DAG`, not sure why I wrote that

2023-04-19 10:47 UTC, jwitz approved these changes
Last few comments, it's a ✅ from me!

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt-cloud.md
> +    - `check_job_is_not_running`: Uses the [ShortCircuitOperator](https://registry.astronomer.io/providers/apache-airflow/modules/shortcircuitoperator) to ensure that the dbt Cloud job with the speci
```suggestion
    - `check_job_is_not_running`: Uses the [ShortCircuitOperator](https://registry.astronomer.io/providers/apache-airflow/modules/shortcircuitoperator) to ensure that the dbt Cloud job with the specified `JOB_ID` is not currently running. The list of currently running dbt Cloud jobs is retrieved using the `list_job_runs()` method of the `DbtCloudHook`. Next, the `latest_run` is selected and its `status` parameter will be evaluated for being a terminal status or not. If the status of the latest run is terminal, this means the job is not currently running and the pipeline should go ahead triggering another run of this job. If the status of the latest run is not terminal, this means that a job with the given `JOB_ID` is still running in the dbt Cloud. The function used in the ShortCircuitOperator will return `False`, therefore causing the DAG to short circuit and skip any downstream tasks.
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +Using the `BashOperator` to run `dbt run` and other dbt commands be useful during development. However, running dbt at the project level has a couple of issues:
```suggestion
Using the `BashOperator` to run `dbt run` and other dbt commands can be useful during development. However, running dbt at the project level has a couple of issues:
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +
```suggestion
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +If a connection type for your database isn't available, you might need to add the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and run `astro dev restart` to hav
```suggestion
If a connection type for your database isn't available, you might need to make it available by adding the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and running `astro dev restart`.
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +You can learn more about a manifest-based dbt and Airflow project structure, view example code, and read about the `DbtDagParser` in a 3-part blog post series on [Building a Scalable Analytics Archit
```suggestion
You can learn more about a manifest-based dbt and Airflow project structure, view example code, and read about the `DbtDagParser` in a 3-part blog post series on [Building a Scalable Analytics Architecture With Airflow and dbt](https://www.astronomer.io/blog/airflow-dbt-1/). 
```
If they don't know about it yet, I think it's good to just link part 1 and not overwhelm with choice.

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
```suggestion
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +
```suggestion
```

2023-04-19 10:47 UTC, jwitz commented on learn/airflow-dbt.md
> +The [Astro dbt provider](https://astronomer.github.io/astronomer-cosmos/), also known as Cosmos, allows you to automatically create Airflow tasks from dbt models, seamlessly integrating dbt jobs into
Let's double check on this in a few weeks once the dust settles on various renamings

2023-04-19 12:02 UTC, TJaniF commented on learn/airflow-dbt.md
> +You can learn more about a manifest-based dbt and Airflow project structure, view example code, and read about the `DbtDagParser` in a 3-part blog post series on [Building a Scalable Analytics Archit
That makes sense yeah :)

2023-04-19 12:10 UTC, TJaniF commented on learn/airflow-dbt-cloud.md
> +- [DbtCloudHookAsync](https://registry.astronomer.io/providers/astronomer-providers/modules/dbtcloudhookasync): asynchronous version of the DbtCloudHook.
```suggestion
- [DbtCloudHookAsync](https://registry.astronomer.io/providers/astronomer-providers/modules/dbtcloudhookasync): Asynchronous version of the DbtCloudHook.
```

2023-04-19 12:19 UTC, merged