Runtime 7.5.0 release notes
astronomer/docs pull request #2067
Opened 2023-03-28 13:29 UTC by jwitz

Not ready yet, waiting on changes from Airflow 2.5.3

2023-03-30 10:06 UTC, jwitz commented on astro/runtime-release-notes.md
> +- DAG list sorting lost when switching page ([29756](https://github.com/apache/airflow/pull/29756))
```suggestion
- Fix `TriggerRuleDep` when the mapped tasks count is 0 ([30084](https://github.com/apache/airflow/pull/30084))
- Fix some long known Graph View UI problems ([29971](https://github.com/apache/airflow/pull/29971))
```

2023-03-30 16:51 UTC, jedcunningham approved these changes

2023-04-03 14:03 UTC, lzdanski requested changes

2023-04-03 14:03 UTC, lzdanski commented on astro/runtime-release-notes.md
> +- Fix some long known Graph View UI problems ([29971](https://github.com/apache/airflow/pull/29971))
```suggestion
- Fix some known Graph View UI problems ([29971](https://github.com/apache/airflow/pull/29971))
```

2023-04-03 14:03 UTC, lzdanski commented on astro/runtime-release-notes.md
> +- Fix some long known Graph View UI problems ([29971](https://github.com/apache/airflow/pull/29971))
I saw that this was the name of the issue, but probably should go with this phrasing.

2023-04-03 14:03 UTC, lzdanski commented on src/versions.js
>    cliVersion: '1.13.0',
There was a merge conflict in this file. Can you confirm that this is the correct CLI version + Runtime version?

2023-04-03 14:18 UTC, ephraimbuddy approved these changes

2023-04-03 14:18 UTC, ephraimbuddy commented on astro/runtime-release-notes.md
> +- Release date: April 3, 2023
```suggestion
- Release date: April 3, 2023
```
We released it on Saturday and I think some customers might have seen it

2023-04-03 14:25 UTC, ephraimbuddy approved these changes

2023-04-03 14:27 UTC, merged