Fixed broken links to our Patch Upgrade doc
astronomer/docs pull request #207
Opened 2021-01-20 15:01 UTC by jwitz

When we cut 0.23, I renamed the file name for our [Patch Upgrade doc](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch) do more closely reflect its content. I hadn't considered that this would affect our links to the file in other places in docs. 

To fix this, I've updated the links in 0.23 and 0.16 docsets to point to the correct file name. I didn't rename the file in earlier versions, so those links are unchanged.

2021-01-20 19:58 UTC, paolaperaza requested changes

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/README.md
> +* [Upgrading](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/upgrade-patch/)
```suggestion
* [Upgrade to a Patch Version of Astronomer Enterprise](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/upgrade-patch/)
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/next/09_resources/03_version-compatibility-reference.md
> +> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade to the la
```suggestion
> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade to an Astronomer v0.16 patch version, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch).
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +$ kubectl get pods | grep upgrade-patch
```suggestion
$ kubectl get pods | grep upgrade-astronomer
```

@jwitz I don't think this was an intended change?

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/07_apply-platform-config.md
> +> **Note:** If you're interested in upgrading Astronomer to the latest version of the platform, read [Upgrade to Astronomer Enterprise v0.23](https://www.astronomer.io/docs/enterprise/v0.16/manage-as
```suggestion
> **Note:** If you're interested in upgrading Astronomer to the latest v0.16 patch version, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch). For instructions on how to upgrade to the latest minor version of the platform, read [Upgrade to Astronomer Enterprise v0.23](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-to-0-23). 
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.16/09_resources/01_release-notes.md
> +For instructions on how to upgrade to a patch version, read [Upgrade to a Patch Version](/docs/enterprise/v0.16/manage-astronomer/upgrade-patch/).
```suggestion
For instructions on how to upgrade to the latest v0.16 patch version of Astronomer, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch). If you're interested in upgrading from Astronomer v0.16.x to the latest minor version of the platform, read [Upgrade to Astronomer Enterprise v0.23](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-to-0-23).
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.16/09_resources/03_version-compatibility-reference.md
> +> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade to the la
```suggestion
> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch).
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +For instructions on how to upgrade to a patch version, read [Upgrade to a Patch Version](/docs/enterprise/v0.23/manage-astronomer/upgrade-patch/).
```suggestion
For instructions on how to upgrade to an Astronomer v0.23 patch version, read [Upgrade to a Patch Version](/docs/enterprise/v0.23/manage-astronomer/upgrade-patch/).
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.23/06_manage-astronomer/06_apply-platform-config.md
> +> **Note:** If you're interested in upgrading Astronomer to a new version of the platform, read [Upgrade to a Patch Version](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-
```suggestion
> **Note:** If you're interested in upgrading to the latest Astronomer v0.23 patch version, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-patch).
```

2021-01-20 19:58 UTC, paolaperaza commented on enterprise/v0.23/09_resources/03_version-compatibility-reference.md
> +> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade to the la
```suggestion
> **Note:** Astronomer v0.16.9+ is required to run Astronomer Certified 1.10.12, and Astronomer v0.16.15+ is required to run Astronomer Certified 1.10.14. For instructions on how to upgrade to an Astronomer v0.16 patch version, read [Upgrade to a Patch Version of Astronomer](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-patch).
```

2021-01-20 23:28 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> +$ kubectl get pods | grep upgrade-patch
Shoot, didn't anticipate that the file name would be the same as something that's actually in the system!

2021-01-20 23:32 UTC, jwitz commented
Thanks for these suggestions @paolaperaza , I agree with all of them. For the next release, we might consider ways to future-proof these links so that we don't have to update them every time. For now though, I'm adding these doc sections to [Notion](https://www.notion.so/astronomerio/Enterprise-New-Version-Checklist-180716f00e854670ad5a45c9bd000032) as bits to look out for when cutting a new Enterprise docset.

2021-01-21 00:16 UTC, paolaperaza approved these changes

2021-01-21 00:16 UTC, paolaperaza commented
Sweet, yep this looks good - too many links 💣  Thanks though, @jwitz ! Merging.

2021-01-21 00:20 UTC, merged