Update IDP configs to have self service SSO
astronomer/docs pull request #2081
Opened 2023-03-30 14:23 UTC by jwitz

Docs for the 4/4 release.

Based on https://www.notion.so/SSO-Self-Service-Documentation-updates-d943fe33680a47b289cc9455ab9d8356

2023-03-30 14:27 UTC, jwitz commented on astro/configure-idp.md
> +## Frequently Asked Questions
I'm inclined to keep this out, because a user would learn the answer to these questions as they're configuring the IDP themselves based on the responses from Astro. How do these questions help them make a decision?

2023-03-30 14:28 UTC, jwitz commented on astro/configure-idp.md
> +1. In the Cloud UI, click **Settings**, then click **Authentication**.
This setup takes sooooo many steps, I'd love to find a way to break it out into topics or reduce the step count. I didn't want to break it into separate topics because all of this configuration takes place in a single "scenario", which in this case configuring the connection from Astro.

I'd also be up for outsourcing some of the Ping/ OneLogin steps to their own documentation.

2023-04-11 16:17 UTC, jwitz commented
Further edits are in https://github.com/astronomer/docs/pull/2100

2023-04-18 15:30 UTC, lzdanski requested changes
mostly nits and "single sign-on" consistency fixes!

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +4. Copy the **Single Sign On URL** and **Audience URI (SP ENTITY ID)** for Step 8.
```suggestion
4. Copy the **Single Sign-On URL** and **Audience URI (SP ENTITY ID)** for Step 8.
```

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +10. Click **Edit** on the **Overview** page, and then enter `<your-sso-url>` in the **Signon URL** field. Then, click **Save**.
```suggestion
10. Click **Edit** on the **Overview** page, and then enter `<your-sso-url>` in the **Sign on URL** field. Then, click **Save**.
```

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +14. Copy and save the URL in the **Single Signon Service** field.
```suggestion
14. Copy and save the URL in the **Single Sign-on Service** field.
```

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +    - **Identity Provider Single Sign-on URL**: Enter the value you copied from the **Single Signon Service** field.
```suggestion
    - **Identity Provider Single Sign-on URL**: Enter the value you copied from the **Single Sign-on Service** field.
```

please tell me their UI doesn't say *signon* :(

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +Astro supports just-in-time provisioning by default for all [single sign-on (SSO) integrations](configure-idp.md). This means that if someone without an Astronomer account tries logging into Astronom
Does that link take users just to this page? Should we instead have a link to one of the initial headers?

2023-04-18 15:30 UTC, lzdanski commented on astro/configure-idp.md
> +To restrict which authentication options are available on Astro for your organization, contact [Astronomer support](https://cloud.astronomer.io/support).
```suggestion
To restrict available authentication options on Astro for your organization, contact [Astronomer support](https://cloud.astronomer.io/support).
```

2023-04-18 16:11 UTC, jwitz commented on astro/configure-idp.md
> +    - **Identity Provider Single Sign-on URL**: Enter the value you copied from the **Single Signon Service** field.
Ok just checked again and THANKFULLY no.. this must have been left over from the Notion draft

2023-04-18 16:12 UTC, jwitz commented on astro/configure-idp.md
> +Astro supports just-in-time provisioning by default for all [single sign-on (SSO) integrations](configure-idp.md). This means that if someone without an Astronomer account tries logging into Astronom
```suggestion
Astro supports just-in-time provisioning by default for all single sign-on (SSO) integrations. This means that if someone without an Astronomer account tries logging into Astronomer with an email address from a domain that you manage, they are automatically granted a default role in your Organization without needing an invite. Users with emails outside of this domain need to be invited to your Organization to access it. 
```

2023-04-18 16:12 UTC, jwitz commented on astro/configure-idp.md
> +Astro supports just-in-time provisioning by default for all [single sign-on (SSO) integrations](configure-idp.md). This means that if someone without an Astronomer account tries logging into Astronom
good catch, this was leftover from when these docs were on a separate page

2023-04-18 16:14 UTC, jwitz commented on astro/configure-idp.md
>      - **Single sign on URL**: `<your-sso-url>`
Yea I think this is how it is in their UI, which is usually what we defer to in terms of style

2023-04-18 16:17 UTC, jwitz commented on astro/configure-idp.md
> +By default, users can choose any of the [available authentication methods](#SSO-authorization-identity-providers) when logging into Astro. You can remove specific authentication options, such as GitH
```suggestion
By default, users can choose any of the [available authentication methods](#supported-sso-identity-providers) when logging into Astro. You can remove specific authentication options, such as GitHub or Google, so that users can use only the methods that your Organization wants to support, like your third party identity provider.
```

2023-04-18 16:19 UTC, lzdanski approved these changes
Changes LGTM and link checking reported via slack

2023-04-18 16:26 UTC, merged