Add Python Airflow API token instructions
astronomer/docs pull request #2092
Opened 2023-03-31 18:24 UTC by fritz-astronomer

2023-03-31 18:25 UTC, fritz-astronomer commented
oh - looking at the rest of the page, we should give the same treatment to the other code samples (that happen to have curl/requests already 😅 )

2023-04-11 12:01 UTC, jwitz requested changes
@fritz-astronomer I'm trying to figure out the build error here.. Is there any reason you chose to replace the placeholder syntax with brackets?

Similarly, any reason we've switched to `mdx` here since we don't have to use partials?

2023-04-11 12:01 UTC, jwitz commented on astro/airflow-api.mdx
> +Using [cURL](https://curl.se/):
```suggestion

<TabItem value="sh" label="Shell">

Using [cURL](https://curl.se/):

```
I get good luck with builds when I add space between all different kinds of elements.

2023-04-17 14:37 UTC, jwitz commented on astro/airflow-api.mdx
> +Using [cURL](https://curl.se/):
```suggestion
<Tabs groupId="retrieve-an-access-token">

<TabItem value="sh" label="Shell">

To retrieve an Astro access token, run the following API request with your Deployment API key ID and secret using [cURL](https://curl.se/):

```

2023-04-17 14:37 UTC, jwitz commented on astro/airflow-api.mdx
> +Using the [`requests`](https://docs.python-requests.org/en/latest/index.html) library:
```suggestion

To retrieve an Astro access token, use the [`requests`](https://docs.python-requests.org/en/latest/index.html) library to make your API request. For example, your code might look like the following:
```

2023-04-17 14:37 UTC, jwitz commented on astro/airflow-api.mdx
> +```
```suggestion

```python
```

2023-04-17 14:37 UTC, jwitz commented on astro/airflow-api.mdx
> +
```suggestion

</TabItem>
</Tabs>
```

2023-05-05 09:42 UTC, jwitz approved these changes

2023-05-05 09:42 UTC, jwitz commented on astro/airflow-api.md
> +            "client_id": "<api-key-id]",
```suggestion
            "client_id": "<api-key-id>",
```

2023-05-05 09:42 UTC, jwitz commented on astro/airflow-api.md
> +Replace `[your-dag-id]` with your own value.
```suggestion
Replace `<your-dag-id>` with your own value.
```

2023-05-05 10:06 UTC, merged