Add Astronomer provider pre-built XCom backends to XCom backends tutorial
astronomer/docs pull request #2103
Opened 2023-04-04 13:41 UTC by TJaniF

Resolves: #2042 

Adding the option to use pre-built XCom backends from the Astronomer provider to the tutorial. Initially I planned just to have a note in Step 4 but then thought it is cleaner to separate it out into its own section with a short step by step instruction and link to it from a note.

Open to different ways to structure this information of course :)

2023-04-04 17:27 UTC, kentdanas approved these changes
This looks pretty good to me @TJaniF. Definitely a tricky one in terms of how to integrate this info while still keeping everything else. My current opinion is that how you have it is the best way, but curious to get @jwitz opinion here. Jake, for context, I didn't want to update the whole tutorial to be centered on the astro provider backend because 1) it doesn't have azure or minio support, which we do show, and 2) it may not contain the particular serialization/deserialization methods that a user needs so I don't want to remove instructions on customizing that part.

2023-04-04 17:27 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +The Astronomer provider package contains a pre-built custom XCom backend for AWS S3 and GCP Cloud Storage with a set of added serialization methods. Refer to the [Use pre-built XCom backends](#use-pr
Do you think it makes sense to add something to this note saying that if you are using Astronomer providers, you can skip [whatever parts you can skip]?

2023-04-04 17:27 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +The Astronomer provider package contains a pre-built custom XCom backend for AWS S3 and GCP Cloud Storage with a set of added serialization methods, including for Pandas dataframes. Refer to the [Use
Same comment here - might be helpful to say "if your serialization method needs to [whatever astro providers does], you can skip this step]"...

2023-04-04 17:27 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +If you want to store your XCom in either AWS S3 or GCP Cloud Storage you can leverage the pre-built custom XCom backends in the [Astronomer provider](https://registry.astronomer.io/providers/astronom
```suggestion
If you want to store your XComs in either AWS S3 or GCP Cloud Storage ,you can leverage the pre-built custom XCom backends in the [Astronomer provider](https://registry.astronomer.io/providers/astronomer-providers/versions/latest) package. In addition to saving your XComs in a remote storage, these XCom backends also contain custom serialization methods for Pandas dataframes and datetime date objects.
```

2023-04-04 17:27 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +To use these Astronomer's XCom backends follow these steps:
```suggestion
To use these Astronomer's XCom backends, follow these steps:
```

2023-04-04 17:27 UTC, kentdanas commented on learn/custom-xcom-backends-tutorial.md
> +The pre-built XCom backends of the Astronomer provider offer the possibility to use gzip compression for all XComs uploaded. To enable gzip compression set `UPLOAD_CONTENT_AS_GZIP=True` in your .env
```suggestion
The pre-built XCom backends in the Astronomer provider offer the possibility of using gzip compression for all XComs uploaded. To enable gzip compression, set `UPLOAD_CONTENT_AS_GZIP=True` in your .env file.
```

2023-04-05 10:47 UTC, TJaniF reviewed
Thank you @kentdanas! Yes, this was a bit tricky finding a way that quickly leads users who are looking for use cases the Astronomer provider pre-built backends will support to that info while also giving all the customization instructions. I added the information on which steps can be skipped when the pre-built backends are used in the notes :)

2023-04-07 19:08 UTC, lzdanski requested changes
This doc is a good start, but the bouncing back and forth and skipping steps might be a little difficult. When @jwitz and Paola get back, this seems like a candidate to talk about doing content reuse with. We're still figuring out how and when we should be doing that type of content architecture, so here's some basic style/grammar editing suggestions.

2023-04-07 19:08 UTC, lzdanski commented on learn/custom-xcom-backends-tutorial.md
> +3. Create an Airflow connection as shown in [Step 3: Create a connection](#step-3-create-a-connection). By default Astronomer's pre-built XCom backend will use the connection ID `aws_default` for a A
```suggestion
3. Create an Airflow connection as shown in [Step 3: Create a connection](#step-3-create-a-connection). By default, Astronomer's pre-built XCom backend uses the connection ID `aws_default` for an AWS S3 connection and `google_cloud_default` for a GCP Cloud Storage connection. You can override which connection id the backend uses by setting the Airflow environment variable `CONNECTION_NAME` for AWS or `XCOM_BACKEND_CONNECTION_NAME` for GCS.
```

2023-04-07 19:08 UTC, lzdanski commented on learn/custom-xcom-backends-tutorial.md
> +4. Open the .env file of your Astro Project and add the following line to set your XCom backend to the pre-built XCom class:
```suggestion
4. To set your XCom backend to the pre-built XCom class, open the .env file of your Astro Project and add the following line :
```
This might be an editorial quirk of mine, but I find sentences that present "what you're doing"  or "where you're doing something" before the "actions to do the thing" to be a bit clearer as a user.

2023-04-07 22:46 UTC, TJaniF reviewed
Thank you @lzdanski ! :) 
Yeah, this was a tricky one to add in the new pre-built options... curious to hear more about  how you'd structure this with content reuse. I was thinking about other options and one would be if there is a dedicated page on different features of the Astronomer provider to link out to that, since I think using the pre-built backends doesn't need the tutorial format just a place where the env variables and connection IDs that need to be set are described :)  

I accepted the changes and adjusted a few details based on your comments. I also added a small substep in the last section to set `XCOM_BACKEND_BUCKET_NAME` that I had forgotten to mention 😅

2023-04-07 22:46 UTC, TJaniF commented on learn/custom-xcom-backends-tutorial.md
> +The Astronomer provider package contains a pre-built XCom backend for AWS S3 and GCP Cloud Storage with a set of added serialization methods. Refer to the [Use pre-built XCom backends](#use-pre-built
Yes, there is, I'll link step 6 and remove the link to step 4 since this note is already in step 4 :)

2023-04-07 22:46 UTC, TJaniF commented on learn/custom-xcom-backends-tutorial.md
> +If you want to store your XComs in either AWS S3 or GCP Cloud Storage, you can leverage the pre-built custom XCom backends in the [Astronomer provider](https://registry.astronomer.io/providers/astron
that is a good question. I think it might make sense to use the in code names with code formatting, so `pandas.DataFrame` and `datetime.date`, I'll change it to that for now :)

2023-04-12 08:07 UTC, jwitz reviewed
@TJaniF I have a slight alternative to @lzdanski. While content reuse could work here, I think having longer steps might not make how the pre-built backend makes this experience different/ easier for users. Instead of recreating the steps, my suggestion frames the topic as an alteration to the core tutorial. Users would get all the information included in the core tutorial, plus brief statements to help them use the pre-built XCom backend without rehashing the same content. LMK what you think!

2023-04-12 08:07 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +:::
```suggestion
- In [Step 1](#step-1-create-an-astro-project), add the Astronomer provider to your Astro project `requirements.txt` file:

    ```text
    astronomer-providers
    ```

- In [Step 3](#step-3-create-a-connection), use the connection ID `aws_default` for an AWS S3 connection and `google_cloud_default` for a GCP Cloud Storage connection. You can override which connection ID the backend uses by setting the Airflow environment variable `CONNECTION_NAME` for AWS or `XCOM_BACKEND_CONNECTION_NAME` for GCS.

- In [Step 4](#step-4-define-a-custom-xcom-class-using-json-serialization), do not define your own custom XCom class. When you open the Astro project `.env`, add the following line to use the pre-built XCom backend instead of your own:

<Tabs
    defaultValue="aws"
    groupId= "use-pre-built-xcom-backends"
    values={[
        {label: 'AWS S3', value: 'aws'},
        {label: 'GCP Cloud Storage', value: 'gcp'},
    ]}>
<TabItem value="aws">

```text
AIRFLOW__CORE__XCOM_BACKEND=astronomer.providers.amazon.aws.xcom_backends.s3.S3XComBackend
XCOM_BACKEND_BUCKET_NAME=<your-bucket-name>
```

</TabItem>

<TabItem value="gcp">

```text
AIRFLOW__CORE__XCOM_BACKEND=astronomer.providers.google.cloud.xcom_backends.gcs.GCSXComBackend
XCOM_BACKEND_BUCKET_NAME=<your-bucket-name>
```

</TabItem>

</Tabs>

- Skip [Step 6](#step-6-create-a-custom-serialization-method-to-handle-pandas-dataframes). The pre-built XCom backend includes serialization methods out of the box.

:::tip

The Astronomer provider XCom backends support gzip compression for all XComs. To enable gzip compression, set `UPLOAD_CONTENT_AS_GZIP=True` in your Astro project  `.env` file.

:::
```

2023-04-12 08:07 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +:::
Ugh... I KNEW this suggestion would look wonky. To get the proper suggestion: 

- Edit my comment
- Copy all of the text included in the suggestion code fence, from top to bottom.
- Use that in the draft.

2023-04-17 14:50 UTC, TJaniF commented
@jwitz thank you for the review, I like the new structure a lot! 
What do you think @lzdanski ? 🙂

2023-04-20 19:01 UTC, lzdanski approved these changes
I think that this looks much more concise so I'm going ahead and approving - I'm really torn about the "bounce up and down" structure of the actual user experience, where you have to go between a step towards the beginning of the page or bop down to the end of the tutorial, the information isn't all in the same place. It's a trade-off decision we have to make between having duplicated content across multiple tutorial paths (which either requires maintaining duplicate source files or content reuse) or having use cases where users need to have multiple tabs of docs open simultaneously/ bounce around pages to see all the relevant info simultaneously. Let's go with this strategy, and if we get user feedback that suggests we should re-evaluate, know that there are some other organizational options!

2023-04-21 08:14 UTC, merged