Add @task.kubernetes decorator section
astronomer/docs pull request #2104
Opened 2023-04-04 14:52 UTC by TJaniF

2023-04-04 17:18 UTC, kentdanas approved these changes
A couple minor comments, but otherwise this looks good to me @TJaniF! I see the PR is still marked as draft, so feel free to ping me again if you make significant changes. As discussed this morning, a bigger update of this guide can wait until after the webinar :)

2023-04-05 11:08 UTC, TJaniF reviewed
Thank you @kentdanas ! I think I just forgot to mark it as ready, no other major changes. @jwitz this one is ready for you after your vacation :)

2023-04-07 18:48 UTC, lzdanski requested changes
Some grammar/style suggestions! Happy to explain my thought process if something doesn't make sense - these types of docs can get a little into the weeds with technical editing.

2023-04-07 18:48 UTC, lzdanski commented on learn/kubepod-operator.md
> +There are many other arguments that can be used to configure the Pod and pass information to the Docker image. For a list of the available KubernetesPodOperator arguments, see the [KubernetesPodOpera
```suggestion
You can also use many other arguments to configure the Pod and pass information to the Docker image. For a list of the available KubernetesPodOperator arguments, see the [KubernetesPodOperator source code](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/operators/pod.py).
```

2023-04-07 18:48 UTC, lzdanski commented on learn/kubepod-operator.md
> +Astronomer recommends using the `@task.kubernetes` decorator over the KubernetesPodOperator when using XCom with Python scripts inside a dedicated Kubernetes pod.
```suggestion
Astronomer recommends using the `@task.kubernetes` decorator instead of the KubernetesPodOperator when using XCom with Python scripts in a dedicated Kubernetes pod.
```

2023-04-07 18:48 UTC, lzdanski commented on learn/kubepod-operator.md
> +The `@task.kubernetes` decorator was added in Airflow 2.4 and provides an alternative to using the traditional KubernetesPodOperator when running Python scripts in within a separate Kubernetes Pod. N
```suggestion
The `@task.kubernetes` decorator was added in Airflow 2.4 and provides an alternative to the traditional KubernetesPodOperator when you run Python scripts in a separate Kubernetes Pod. The Docker image provided to the `@task.kubernetes` decorator must support executing Python scripts.
```

2023-04-07 18:48 UTC, lzdanski commented on learn/kubepod-operator.md
> +XComs can be passed to the Python script running within the dedicated Kubernetes pod as with regular `@task` decorated functions. The value returned by the decorated function will be pushed to XCom i
```suggestion
Like regular `@task` decorated functions, XComs can be passed to the Python script running in the dedicated Kubernetes pod. If `do_xcom_push` is set to `True` in the decorator parameters, the value returned by the decorated function is pushed to XCom. You can learn more about decorators in the [Introduction to Airflow decorators](airflow-decorators.md) guide.
```

2023-04-07 20:01 UTC, kentdanas commented
Thanks @lzdanski! Accepted all your suggestions.

2023-04-07 20:03 UTC, merged