Update EPO tutorial to use new astro buildkit
astronomer/docs pull request #2116
Opened 2023-04-07 21:44 UTC by kentdanas

Massively simplifying the steps in this one thanks to one of our hackathon projects: https://github.com/astronomer/astro-provider-venv

Need to check next week with the team that they're ready for this to be out in the wild and that I got all the naming right, but in the meantime, it's ready for an overall review/copy edit :)

2023-04-17 12:31 UTC, TJaniF approved these changes
Loving how much easier it is to understand what happens in the Dockerfile with buildkit! Tested the tutorial in 7.4.2 and it worked but I needed to add `build-essential` to `packages.txt` (added a comment with the error I got). Other than that I only had minor suggestions, mostly just adjusting the step numbering. :)

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
>  ## Step 3: Configure your Astro project
```suggestion
## Step 2: Configure your Astro project
```

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
> +## Step 4: Create a connection to Snowflake
```suggestion
## Step 3: Create a connection to Snowflake
```

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
> +## Step 5: Create your DAG
```suggestion
## Step 4: Create your DAG
```

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
> +## Step 6: Run your DAG to execute your Snowpark query in a virtual environment
```suggestion
## Step 5: Run your DAG to execute your Snowpark query in a virtual environment
```

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
>      ```
I got a Docker build error when trying this with `FROM quay.io/astronomer/astro-runtime:7.4.2-base` and with `FROM quay.io/astronomer/astro-runtime:7.4.2`.

the last bits of the error:

```text
#25 65.32       C compiler or Python headers are not installed on this system. Try to run:
#25 65.32       sudo apt-get install gcc python3-dev
#25 65.32       error: command 'gcc' failed: No such file or directory
#25 65.32       [end of output]
#25 65.32   
#25 65.32   note: This error originates from a subprocess, and is likely not a problem with pip.
#25 65.32   ERROR: Failed building wheel for psutil
```

I was able to fix it by including 
`build-essential` in `packages.txt`.

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
for the note just above: it took about 3 or 4 minutes for me. Is 20min still expected for slower hardware?

2023-04-17 12:31 UTC, TJaniF commented on learn/external-python-operator.md
> +This DAG prints the context of your Airflow environment before using the `@task.external_python` decorator to run a Snowpark query in the virtual environment you created in [Step 3](#step-3-configure
```suggestion
This DAG prints the context of your Airflow environment before using the `@task.external_python` decorator to run a Snowpark query in the virtual environment you created in [Step 2](#step-2-configure-your-astro-project).
```

2023-04-19 21:02 UTC, kentdanas commented on learn/external-python-operator.md
>      ```
huh...odd that I didn't get that error, and it's not mentioned in the snowpark example in the readme. My inclination is to add it as a step because it won't hurt anything? Seems like it would be confusing to say "if you get this weird error, do this other thing" without knowing exactly what env stuff causes it.

2023-04-19 21:03 UTC, kentdanas commented on learn/external-python-operator.md
Good question. I don't _think_ it should take that long, but I'd be inclined to leave the note in just in case. Seems like no harm if folks don't encounter that.

2023-04-19 21:13 UTC, kentdanas commented
Thanks for the review @TJaniF! I added a step to install build-essential, unless you know what would cause that for you and not others I think it's safest to include it as a step.

@jwitz we might deliberate on that issue a bit, but otherwise this is ready for a quick copy edit.

2023-04-20 19:21 UTC, lzdanski requested changes
Copyedits - mostly to do with passive vs active voice and style - nothing that should require any major structure changes.

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +Snowpark requires Python 3.8, while [Astro runtime](https://docs.astronomer.io/astro/runtime-image-architecture) uses Python 3.9. The ExternalPythonOperator will run your Snowpark query in a Python 3
```suggestion
Snowpark requires Python 3.8, while the [Astro Runtime](https://docs.astronomer.io/astro/runtime-image-architecture) uses Python 3.9. The ExternalPythonOperator can run your Snowpark query in a Python 3.8 virtual environment, allowing you to use a different Python version for your task than in the Airflow environment. You can use these same general steps for any use case for running a task in a reusable Python virtual environment.
```

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +    The packages in this file will be installed in your virtual environment. The `snowflake-snowpark-python` package is required to run Snowpark queries. The other packages are required to access an
```suggestion
    These packages are installed in your virtual environment. Snowpark requires the `snowflake-snowpark-python` package to run queries. Airflow uses the other packages to connect with Snowflake from the virtual environment. If you use a different method to connect with Snowflake, such as a secrets manager or managing secrets locally, you can update or remove these lines.
```

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +    Creating a `pyenv` environment within your Airflow project requires installing multiple os-level packages and a series of Docker commands. The open source [Astro BuildKit](https://github.com/astr
```suggestion
    Creating a `pyenv` environment in your Airflow project requires installing multiple operating system level packages and a series of Docker commands. The open source [Astro BuildKit](https://github.com/astronomer/astro-provider-venv) simplifies this process and allows you to create a Python virtual environment with only two lines of code.
```

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +1. In the Airflow UI, go to **Admin** -> **Connections** and click **+**.
```suggestion
1. In the Airflow UI, go to **Admin** > **Connections** and click **+**.
```

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +Go to the Airflow UI, unpause your `py_virtual_env` DAG and trigger it to run your Snowpark query in an isolated Python virtual environment. Open your tasks logs to see the results of your query prin
```suggestion
Go to the Airflow UI, unpause your `py_virtual_env` DAG, and trigger it to run your Snowpark query in an isolated Python virtual environment. Open your tasks logs to see the results of your query printed:
```

2023-04-20 19:21 UTC, lzdanski commented on learn/external-python-operator.md
> +    Your connection should look something like the screenshot below.
```suggestion
    The following example shows an Airflow Connection configuration in the Airflow UI.
```

2023-04-20 21:04 UTC, kentdanas commented on learn/external-python-operator.md
> +    The packages in this file will be installed in your virtual environment. The `snowflake-snowpark-python` package is required to run Snowpark queries. The other packages are required to access an
Didn't accept this one because saying "Airflow uses the other packages" isn't technically accurate here. The virtual environment exists on its own, separate to Airflow, but in this example we want the task running in the virtual env to leverage a connection that's defined in Airflow, so we have to actually install Airflow in the virtual env to make that available. So it's really the virtual environment using those packages to be able to access a Snowflake connection defined in Airflow. 

Similarly, it's not Snowpark that requires the python package, it's your Airflow task that needs that package in order to run a Snowpark query. But saying "Airflow requires the `snowflake-snowpark-python` package...." sounds odd to me, because that package isn't an Airflow-specific thing, it's a general Python package for any time you're using Python to run a snowpark query, regardless of how you're executing that Python code.

2023-04-20 21:05 UTC, kentdanas commented
Thanks for your review @lzdanski! Accepted most of your suggestions and left a follow-up comment on one of them. Let me know if you want to chat about that.

2023-04-20 21:30 UTC, lzdanski commented on learn/external-python-operator.md
> +    The packages in this file will be installed in your virtual environment. The `snowflake-snowpark-python` package is required to run Snowpark queries. The other packages are required to access an
Ah got it! These edits were to address the passive voice structure "B is required" vs "A requires B to complete C and D" It just stands out to me because this section has 3 passive voice structures in a row and that made it hard for me to parse the actor/action/object relationships. It was super common/encouraged in science/ tech writing for a really long time, but it gets tricky in docs for new learners or folks who are working in English.

```suggestion
    The packages in this file will be installed in your virtual environment. Your Airflow task requires the `snowflake-snowpark-python` package to run Snowpark queries in the virtual environment.  Your virtual environment uses the other packages to access the Snowflake connection you defined in Airflow. If you are using a different method of connecting to Snowflake, such as a secrets manager or managing secrets locally, you can update or remove these lines.
```

2023-04-24 17:20 UTC, kentdanas commented
@lzdanski I think I accepted all your suggestions. Let me know if we're good to get this published now!

2023-04-24 17:26 UTC, lzdanski approved these changes
LGTM

2023-04-24 18:13 UTC, merged