Update GCS and S3 docs
astronomer/docs pull request #2125
Opened 2023-04-11 14:26 UTC by jwitz

A rework of https://github.com/astronomer/docs/pull/2099 using our new CI/CD documentation.

2023-04-11 17:47 UTC, fritz-astronomer commented on astro/ci-cd-templates/gcs.md
> +  ```
```python
import os
import tarfile
import subprocess
from pathlib import Path

from google.cloud import storage
from google.cloud.functions import Context

BUCKET = os.getenv("BUCKET", "my-demo-bucket")


def untar(filename: str, destination: str) -> None:
    with tarfile.open(filename) as file:
        file.extractall(destination)


def run_command(cmd: str) -> None:
    p = subprocess.Popen("set -x; " + cmd, shell=True)
    p.communicate()


def download_to_local(bucket_name: str, gcs_folder: str, local_dir: str = None) -> None:
    """Download the contents of a folder directory
    :param bucket_name: the name of the gcs bucket
    :param gcs_folder: the folder path in the gcs bucket
    :param local_dir: a relative or absolute directory path in the local file system
    """
    storage_client = storage.Client()
    source_bucket = storage_client.bucket(bucket_name)
    blobs = source_bucket.list_blobs(prefix=gcs_folder)
    for blob in blobs:
        path = Path(local_dir) / blob.name if local_dir else Path(blob.name)
        if not path.is_dir():
            path.parent.mkdir(parents=True, exist_ok=True)
            blob.download_to_filename(path.absolute())


def astro_deploy(event: dict, context: Context) -> None:
    """Triggered by a change to a Cloud Storage bucket.
    :param event: Event payload.
    :param context: Metadata for the event.
    """
    os.chdir('/tmp/astro')
    download_to_local(BUCKET, 'dags', './dags')
    download_to_local(BUCKET, 'cli_binary', '.')
    untar('./astro_cli.tar.gz', '.')
    run_command('echo y | ./astro dev init')
    run_command('./astro deploy --dags')
```

2023-04-11 17:48 UTC, fritz-astronomer commented on astro/ci-cd-templates/gcs.md
> +      run_command('./astro deploy --dags')
```suggestion
```python
import os
import tarfile
import subprocess
from pathlib import Path

from google.cloud import storage
from google.cloud.functions import Context

BUCKET = os.getenv("BUCKET", "my-demo-bucket")


def untar(filename: str, destination: str) -> None:
    with tarfile.open(filename) as file:
        file.extractall(destination)


def run_command(cmd: str) -> None:
    p = subprocess.Popen("set -x; " + cmd, shell=True)
    p.communicate()


def download_to_local(bucket_name: str, gcs_folder: str, local_dir: str = None) -> None:
    """Download the contents of a folder directory
    :param bucket_name: the name of the gcs bucket
    :param gcs_folder: the folder path in the gcs bucket
    :param local_dir: a relative or absolute directory path in the local file system
    """
    storage_client = storage.Client()
    source_bucket = storage_client.bucket(bucket_name)
    blobs = source_bucket.list_blobs(prefix=gcs_folder)
    for blob in blobs:
        path = Path(local_dir) / blob.name if local_dir else Path(blob.name)
        if not path.is_dir():
            path.parent.mkdir(parents=True, exist_ok=True)
            blob.download_to_filename(path.absolute())


def astro_deploy(event: dict, context: Context) -> None:
    """Triggered by a change to a Cloud Storage bucket.
    :param event: Event payload.
    :param context: Metadata for the event.
    """
    os.chdir('/tmp/astro')
    download_to_local(BUCKET, 'dags', './dags')
    download_to_local(BUCKET, 'cli_binary', '.')
    untar('./astro_cli.tar.gz', '.')
    run_command('echo y | ./astro dev init')
    run_command('./astro deploy --dags')
```

2023-04-14 06:53 UTC, manmeetkaur commented on astro/ci-cd-templates/gcs.md
> +To deploy any non-DAG code changes to Astro, you need to trigger a standard image-only deploy with your Astro project. When you do this, your Astro project must include the latest version of your DAG
@jwitz so there are two parts to CI/CD when deploying to Astro with DAG-only Enabled from Cloud Storage:

1. Folks will still use CI/CD to publish the DAGs to cloud storage (gcs or s3) 
2. Lambda/GCF will then auto-trigger based on the changes to the bucket

When there are changes to non-DAG resources, like requirements.txt, custom operators or other helpers, then the CI/CD should do image deploy automatically. For this we have can create a separate template which checks changes in `requirements.txt` or `include` and do image deploy ELSE just push the DAGs to the bucket which will trigger DAG-only deploy. I can create a template for that if you would like.

2023-04-20 13:13 UTC, manmeetkaur commented on astro/ci-cd-templates/gcs.md
> +To deploy any non-DAG code changes to Astro, you need to trigger a standard image-only deploy with your Astro project. When you do this, your Astro project must include the latest version of your DAG
agreed @jwitz . We can move forward. I will just update GCS code per the suggestions from @fritz-astronomer and push it.

2023-04-20 20:16 UTC, lzdanski requested changes
Some passive/active voice nits!

2023-04-20 20:16 UTC, lzdanski commented on astro/ci-cd-templates/aws-s3.md
> +This CI/CD template can be used to deploy DAGs from a single S3 bucket to a single Astro Deployment. When you create or modify a DAG in the S3 bucket, a Lambda function triggers to deploy your DAGs t
```suggestion
This CI/CD template can be used to deploy DAGs from a single S3 bucket to a single Astro Deployment. Astro Deployment. When you create or modify a DAG in the S3 bucket, a Lambda function triggers your project to deploy DAGs to Astro.
```

2023-04-20 20:16 UTC, lzdanski commented on astro/ci-cd-templates/aws-s3.md
> +1. Download the latest Astro CLI binary from [GitHub releases](https://github.com/astronomer/astro-cli/releases), then rename the file to, `astro_cli.tar.gz`. For example, to use Astro CLI version 1.
```suggestion
1. Download the latest Astro CLI binary from [GitHub releases](https://github.com/astronomer/astro-cli/releases), then rename the file to, `astro_cli.tar.gz`. For example, to use Astro CLI version 1.13.0 in your template, download `astro_1.13.0_linux_amd64.tar.gz` and rename it to `astro_cli.tar.gz`.
```

2023-04-21 09:05 UTC, manmeetkaur approved these changes

2023-04-21 09:06 UTC, manmeetkaur commented on astro/ci-cd-templates/aws-s3.md
> +This CI/CD template can be used to deploy DAGs from a single S3 bucket to a single Astro Deployment. When you create or modify a DAG in the S3 bucket, a Lambda function triggers to deploy your DAGs t
changes done 👌

2023-04-21 09:06 UTC, manmeetkaur commented on astro/ci-cd-templates/aws-s3.md
> +This CI/CD template can be used to deploy DAGs from a single S3 bucket to a single Astro Deployment. When you create or modify a DAG in the S3 bucket, a Lambda function triggers to deploy your DAGs t
changes done.

2023-04-21 09:31 UTC, jwitz commented on astro/ci-cd-templates/gcs.md
> +  ```
```suggestion
    ```
```

2023-04-21 12:49 UTC, merged