[2.6] Add ContinuousTimetable to the scheduling guide
astronomer/docs pull request #2163
Opened 2023-04-20 10:57 UTC by TJaniF

Resolves: #2162 

Adding the ContinuousTimetable, I thought this was a one line addition at first but since you also net to set max_active_tasks and it is a very useful feature albeit needing a do not stream warning I thought it makes sense to have a subsection on it :)

Happy side effect: I might be learning how to spell continuous, maybe, hopefully.

2023-04-20 15:31 UTC, kentdanas approved these changes
Looks good to me, one minor comment otherwise I think this is fine.

2023-04-20 15:31 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +This DAG will always be running and automatically scheduling its next run, whenever it has finished, irrespective of whether the DAG run succeeded or failed. Using a ContinuousTimetable is especially
```suggestion
This DAG will run continuously by scheduling a new run as soon as the previous run has completed, regardless of whether the previous run succeeded or failed. Using a ContinuousTimetable is especially useful when [sensors](what-is-a-sensor.md) or [deferrable operators](deferrable-operators.md) are used to wait for highly irregular events in external data tools.
```

2023-04-20 15:59 UTC, TJaniF reviewed
Thank you @kentdanas !

@jwitz The first 2.6 snippet ready for you :)

2023-04-20 15:59 UTC, TJaniF commented on learn/scheduling-in-airflow.md
> +### Continuous timetable
Haha, it does have to be 1 actually I ran into that too with the same thought process, the error when you don't set it to 1 is very explicit:

```
Broken DAG: [/usr/local/airflow/dags/continuous_toy_dag.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/dag.py", line 3555, in factory
    with DAG(
  File "/usr/local/lib/python3.10/site-packages/airflow/models/dag.py", line 558, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid max_active_runs: <class 'airflow.timetables.simple.ContinuousTimetable'> requires max_active_runs <= 1
```

2023-04-20 16:55 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +### Continuous timetable
oh...I didn't realize it was limited to 1 DAG run at a time. In that case I made a few other minor suggestions.

2023-04-20 16:55 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +As of Airflow 2.6 you can run a DAG continuously using a pre-defined timetable. To use the [ContinuousTimetable](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/timetables/simple/i
```suggestion
As of Airflow 2.6 you can run a DAG continuously using a pre-defined timetable. To use the [ContinuousTimetable](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/timetables/simple/index.html#module-airflow.timetables.simple.ContinuousTimetable), set the schedule of your DAG to `"@continuous"` and set `max_active_runs` to 1.
```

2023-04-20 16:56 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +This DAG will run continuously by scheduling a new run as soon as the previous run has completed, regardless of whether the previous run succeeded or failed. Using a ContinuousTimetable is especially
```suggestion
This schedule will create one continuous DAG run, with a new run starting as soon as the previous run has completed, regardless of whether the previous run succeeded or failed. Using a ContinuousTimetable is especially useful when [sensors](what-is-a-sensor.md) or [deferrable operators](deferrable-operators.md) are used to wait for highly irregular events in external data tools.
```

2023-04-20 17:04 UTC, TJaniF commented on learn/scheduling-in-airflow.md
> +Be aware that Airflow should not be used for streaming or low-latency processes.
👍 I think it might make sense to link to the Kafka integration from here too?

2023-04-20 17:36 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> +Be aware that Airflow should not be used for streaming or low-latency processes.
Sure, I think that makes sense

2023-04-21 20:28 UTC, lzdanski requested changes
Some light copyediting - looks good!

2023-04-21 20:28 UTC, lzdanski commented on learn/scheduling-in-airflow.md
> +Be aware that Airflow is designed to handle orchestration of data pipelines in batches and this feature is not intended to be used for streaming or low-latency processes. If you need to run pipelines
```suggestion
Airflow is designed to handle orchestration of data pipelines in batches, and this feature is not intended for streaming or low-latency processes. If you need to run pipelines more frequently than every minute, consider using Airflow in combination with tools designed specifically for that purpose like [Apache Kafka](airflow-kafka.md).
```

2023-04-24 11:20 UTC, TJaniF commented
Thank you @lzdanski ! 

Ready to be merged when 2.6 is released from my side :)

2023-04-30 13:56 UTC, merged