[2.6] Add notifiers to the notifications guide
astronomer/docs pull request #2181
Opened 2023-04-24 23:25 UTC by TJaniF

Resolves: #2142

PR to add the concept of notifiers to the Notifications guide. I also restructured the chapters a bit to group information about email and Slack notifications. I did not touch the SLA and Astronomer sections. 
Let me know if the new structure makes sense :)

2023-04-25 15:07 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +Aside from the general purpose `*_callback` parameters, all Airflow operators are able to use the two BaseOperator parameters `email_on_failure` and `email_on_retry` if the parameter `email` has been
```suggestion
If you have an SMTP connection configured in Airflow, you can use the `email, `email_on_failure`, and `email_on_retry` task parameters to send notification emails from Airflow.
```

2023-04-25 15:08 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +The email notification parameters can be given to all tasks in an Airflow DAG by defining them in the `default_args` parameter.
```suggestion
You can also configure email notifications for all tasks in a DAG by defining the configurations in the `default_args` parameter.
```

2023-04-25 15:08 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +To allow Airflow to send emails, you have to provide values to the SMTP section of your `airflow.cfg` similar to this example:
Can you also just configure a connection from the Airflow UI?

2023-04-25 15:12 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +Custom callback functions can also be used to send email notifications. For example, if you want to send emails for successful task runs, you can provide an email function to your `on_success_callbac
```suggestion
If you want to send emails out on a more customizable basis, you can also use Airflow's callback functions to run custom functions that send email notifications. For example, if you want to send emails for successful task runs, you can provide an email function to the `on_success_callback` parameter:
```

2023-04-25 15:14 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +To use the custom notifier in a DAG provide its instantiation to any callback parameter, for example:
```suggestion
To use the custom notifier in a DAG, provide its instantiation to any callback parameter. For example:
```

2023-04-25 15:14 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +Airflow 2.6 added the concept of [notifiers](https://airflow.apache.org/docs/apache-airflow/stable/howto/notifications.html), which are pre-built or custom classes and can be used to standardize and
Maybe one more sentence here that makes explicit the difference between notifiers and notifications? It's that you can pass values into the functions?

2023-04-25 15:15 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +Notifiers are useful to abstract and standardize complex logic used to send a notification from Airflow.
Isn't this also true of the standard callback functions?

2023-04-25 15:16 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +)
We don't have to actually write all of these functions, we could just use a `...` in DAG code to imply that they exist

2023-04-25 15:17 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +The DAG above has one task sending a notification to Slack. It necessitates configuring an [Airflow connection](connections.md) to Slack with the connection ID `slack_conn`.
```suggestion
The DAG above has one task sending a notification to Slack. It uses a Slack [Airflow connection](connections.md) with the connection ID `slack_conn`.
```

2023-04-25 20:32 UTC, kentdanas requested changes
Thanks for this one @TJaniF! Requesting changes to re-org the sections a bit and add some additional notifier context. Let me know if you want to chat through any of my responses to Jake's questions too

2023-04-25 20:32 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +Airflow 2.6 added the concept of [notifiers](https://airflow.apache.org/docs/apache-airflow/stable/howto/notifications.html), which are pre-built or custom classes and can be used to standardize and
Agree we should add osme additional context here. I would add an extra sentence making it clear that notifiers are defined globally in your Airflow environment and can be used across any of your DAGs, and that their extensibility means that the community can add them to providers so everybody can use them (this is the biggest benefit I see of them - essentially they provide a framework for pre-built callback functions that anybody can contribute to Airflow, so you might not have to define your own. They're also a bit easier to use across DAGs than an old callback function would be).

And to Jake's question - maybe in the first sentence say "standardize and modularize the functions you use to send notifications. Notifiers get passed to the relevant on_*_callback function of your DAG depending on what event you are notifying on." would be clearer? 

In general, a notifier is a function that sends a notification for you. Also, a callback function doesn't necessarily need to be a notification.

2023-04-25 20:32 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +Notifiers are useful to abstract and standardize complex logic used to send a notification from Airflow.
I think we can remove this sentence in favor of the additions to the intro to this section mentioned above.

And this isn't _that_ true of standard callback functions. Those are more "define whatever you want" but there's no structure at all. Notifiers provide more of a framework so it's a first-class feature. And while you still _could_ define whatever you want, the biggest benefit will be the community taking advantage of the framework and contributing system-specific notifiers.

2023-04-26 09:42 UTC, jwitz commented on learn/error-notifications-in-airflow.md
>  <CodeBlock language="python">{sla_task_level_example_traditional}</CodeBlock>
`![SLA Email](/img/guides/sla_email.png)` looks a bit off in the guide because it blends in with the background of light mode, can we replace it with this version that has a single-pixel black border?
![sla_email](https://user-images.githubusercontent.com/74574233/234536954-ecd9fe43-940b-4e95-b96c-fc66eb3650c1.png)

2023-04-26 20:27 UTC, TJaniF reviewed
@kentdanas and @jwitz thank you for the thorough review! I hope the structure makes more sense now :) 

The only place where I deviated from the suggestions is that I did not put all of the DAG vs task level callback parameters into Airflow notification basics because the flow felt off when I tried it. (I think because the section is the main content for the callbacks section and it felt like the callback content was split up too much).

I did add two sentence about the level difference at the end of Airflow notification basics and linked to the more in-depth section. Let me know if that works 🙂

2023-04-26 21:42 UTC, kentdanas requested changes
@TJaniF this org looks wayyy better, thanks for the updates! The error notification updates look great to me, just minor comments but otherwise good to copy edit.

Requesting changes because we may need to do some reframing on the rerunning DAGs updates. I really like having that section in there, but think it needs to be moved up and maybe the guide renamed/intro reframed. If it seems like that's going to be a longer discussion let's move that part into it's own PR so we can still get the notifiers part out for the 2.6 release.

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +- **Airflow notifiers**: Notifiers, which were added in Airflow 2.6, offer a way to modularize callback functions into custom classes to easily be reused and standardized. Provider packages can ship
Link to SlackNotifier docs on that word? (if there are any?....seems like this should go on the registry)

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +- **Airflow service-level agreements (SLAs)**: SLAs in Airflow define the expected time it takes from the DAG execution until a specific task has been completed. If an SLA is missed the callable or n
```suggestion
- **Airflow service-level agreements (SLAs)**: SLAs in Airflow define the expected time it takes from the DAG execution until a specific task has been completed. If an SLA is missed, the callable or notifier provided to the `sla_miss_callback` parameter is executed. If an SMTP connection is configured in that Airflow environment, an email will be sent as well. Since an SLA miss does not stop a task from running, this type of notification is used when intervention is needed if a specific task is taking longer than expected.
```

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +Most notifications can be set at the level of both a DAG and a task, like the `on_failure_callback`, while others can only be set at the task or DAG level. Setting a parameter within a DAGs `default_
```suggestion
Most notifications can be set at the level of both a DAG and a task. Setting a parameter within a DAG's `default_args` dictionary will apply it to all tasks in the DAG. You can see examples of this in the [set DAG and task level callbacks](#set-dag-and-task-level-callbacks) section.
```

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +To allow Airflow to send emails, you have to provide values to the SMTP section of your `airflow.cfg` similar to this example:
I would not mention this. I think it's adequate to link to the airflow docs as you already do. And in my experience it's much more common to configure smtp with env vars

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +If you are using Astro, use environment variables to set up SMTP because the `airflow.cfg` cannot be directly edited.
Is there a doc we can link to for this? (Astro env vars?)

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +The `sla_miss_callback` which is invoked when a task or DAG misses its defined [Service Level Agreement (SLA)](#airflow-service-level-agreements) can only be defined at the DAG level to be used for e
```suggestion
The `sla_miss_callback` which is invoked when a task or DAG misses its defined [Service Level Agreement (SLA)](#airflow-service-level-agreements) can only be defined at the DAG level to be used for each task in a DAG which has an SLA defined.
```
I would lean towards putting all 5 callbacks in one bulleted list along with their descriptions. But open to opposing feedback.

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +To define a notification at the DAG level, you can set the `*_callback` parameters in your DAG instantiation.
Let's add a sentence here just to be super clear that "DAG level callbacks will send a notification based on the state of the entire DAG run" or something like that. to differentiate from a default arg

2023-04-26 21:42 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +If you want each task in a DAG to invoke a task-level call back you can standarize task-level callbacks across your entire DAG using the DAG parameter `default_args`. Items listed in the dictionary p
```suggestion
To apply a task-level callback to each task in your DAG, you can pass the callback function to the `default_args` parameter. Items listed in the dictionary provided to the `default_args` parameter will be set for each task in the DAG.
```

2023-04-26 21:42 UTC, kentdanas commented on learn/rerunning-dags.md
> +In Airflow you can set individual tasks to try running again automatically in case of a task failing. The number of times a task can try to run again before failing permanently can be defined at the
```suggestion
In Airflow you can configure individual tasks to retry automatically in case of a failure. The number of times a task will retry again before failing permanently can be defined at the Airflow configuration level using the core config `default_task_retries`. You can set this configuration either in `airflow.cfg` or via the environment variable `AIRFLOW__CORE__DEFAULT_TASK_RETRIES`. By default tasks will not retry. 
```

2023-04-27 12:04 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! 

Good idea to move out the rerun changes to another PR, I was struggling to figure out how to fit retry into the existing one and I think reframing could work great :)

2023-04-27 12:06 UTC, TJaniF commented
@jwitz and @lzdanski (should I always tag you both or in this case since Jake has already done the first pass only Jake, and vice versa? :) )
In any case this one is ready for copy edit now, the section on retries in the rerun guide will be in another PR so this one can be ready in time for 2.6

2023-04-27 18:51 UTC, kentdanas approved these changes
LGTM! Good to move on to final copy edit.

2023-04-27 18:51 UTC, kentdanas commented on learn/rerunning-dags.md
> +![Trigger Execution Date](/img/guides/trigger_execution_date.png)
I think this might still be marked as a change because of white space....not a big deal at all, just calling it out in case it's going to be annoying for merge conflicts later with the other PR

2023-04-27 18:51 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +- `sla_miss_callback`: Invoked when a task or DAG misses its defined [Service Level Agreement (SLA)](#airflow-service-level-agreements). This callback can only be defined at the DAG level to be used
```suggestion
- `sla_miss_callback`: Invoked when a task or DAG misses its defined [Service Level Agreement (SLA)](#airflow-service-level-agreements). This callback is defined at the DAG level for DAGs with defined SLAs and will be applied to every task.
```

2023-04-27 18:51 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +Any Python callable can be provided to the `*_callback` parameters. Airflow 2.6 added the functionality of using [notifiers](#notifiers) and the option to provide several callback items to the same c
```suggestion
You can provide any Python callable to the `*_callback` parameters. As of Airflow 2.6, you can also use [notifiers](#notifiers) for your callbacks, and you can provide several callback items to the same callback parameter in a list.
```
Not sure this is really better wording, but trying to make it more consistent.

2023-04-27 23:34 UTC, TJaniF commented on learn/rerunning-dags.md
> +![Trigger Execution Date](/img/guides/trigger_execution_date.png)
Haha, I know, I tried removing the space twice, then then it says one is missing, if I add it back, the added space is the change 😅 not sure how to fix that.

2023-04-27 23:36 UTC, TJaniF reviewed
Thank you Kenten!

@jwitz one more round? :)

2023-04-28 10:50 UTC, jwitz approved these changes
LGTM! Great second draft

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +When using Airflow, you have different options to configure notifications geared towards different use cases:
```suggestion
Airflow has a few options for notifying you on the status of your DAGs:
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +- **Email notifications**: Every Airflow operator derived from the BaseOperator has parameters dedicated to configure email alerts in case of a task failure or retry. Email alerts are often set on ta
```suggestion
- **Email notifications**: Most Airflow operators have parameters for setting email alerts in case of a task failure or retry. Use email alerts in production pipelines where task failures or retries need immediate attention by a data professional. 
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +- **Airflow callbacks**: Callback parameters (`*_callback`) exist both at the task and at the DAG level. You can pass any callable or Airflow notifier to these parameters to be executed in different
```suggestion
- **Airflow callbacks**: Callback parameters (`*_callback`) exist both at the task and at the DAG level. You can pass any callable or Airflow notifier to these parameters, and Airflow will run them in the case of specific events, such as a task failure. Airflow callbacks offer a lot of flexibility to execute any code based on the state of a task or DAG. They are often used to define actions for specific instances of task failures or successes.
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +- **Airflow notifiers**: Notifiers, which were added in Airflow 2.6, offer a way to modularize callback functions into custom classes to easily be reused and standardized. Provider packages can ship
```suggestion
- **Airflow notifiers**: Notifiers are custom classes for callback functions that can be easily reused and standardized. Provider packages can ship pre-built notifiers like the [SlackNotifier](https://registry.astronomer.io/providers/apache-airflow-providers-slack/versions/7.2.0/modules/SlackNotifier). Notifiers can be provided to callback parameters to define which task or DAG state should cause them to be executed. A common use case for notifiers is standardizing actions for task failures across several Airflow instances.
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +- **Airflow service-level agreements (SLAs)**: SLAs in Airflow define the expected time it takes from the DAG execution until a specific task has been completed. If an SLA is missed, the callable or
```suggestion
- **Airflow service-level agreements (SLAs)**: SLAs define the expected time it takes for a specific task to complete. If an SLA is missed, the callable or notifier provided to the `sla_miss_callback` parameter is executed. If you configure an SMTP connection, an email will be sent as well. Since an SLA miss does not stop a task from running, this type of notification is used when intervention is needed if a specific task is taking longer than expected.
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
>  ## Airflow notification basics
```suggestion
## Airflow notification types
```

Great use case breakdown here

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +### Set DAG and task level callbacks
```suggestion
### Set DAG and task-level callbacks
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +If you are on an Airflow version older than 2.6 and want to implement Slack notification you can follow this example.
```suggestion
If you are on an Airflow version older than 2.6 and want to implement Slack notifications, follow this example.
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +In Airflow 2.0 or later, you'll need to install the `apache-airflow-providers-slack` provider package to use the `SlackWebhookOperator`.
```suggestion
    ![Slack Connection](/img/guides/slack_webhook_connection.png)

    In Airflow 2.0 or later, you'll need to install the `apache-airflow-providers-slack` provider package to use the `SlackWebhookOperator`.
```

2023-04-28 10:50 UTC, jwitz commented on learn/error-notifications-in-airflow.md
> +```python
Indent this code block by 4 spaces

2023-04-28 12:28 UTC, TJaniF reviewed
Thank you @jwitz ! :)

2023-04-30 13:55 UTC, merged