Update secrets-backend.md
astronomer/docs pull request #2188
Opened 2023-04-25 18:51 UTC by fritz-astronomer

Customer reports that the import path changed and the instructions were confusing

2023-04-26 11:58 UTC, jwitz requested changes
@fritz-astronomer Is there a reason we're not telling users to set the environment variables as secret in Astro any more?

2023-04-26 11:58 UTC, jwitz commented on astro/secrets-backend.md
I think the note about Git is more appropriate here.

2023-04-26 18:25 UTC, fritz-astronomer commented
> @fritz-astronomer Is there a reason we're not telling users to set the environment variables as secret in Astro any more?

History, no good reason. Let's pick something and standardize 🤷

2023-04-26 18:27 UTC, fritz-astronomer commented on astro/secrets-backend.md
> +AIRFLOW__SECRETS__BACKEND=airflow.providers.microsoft.azure.secrets.key_vault.AzureKeyVaultBackend
https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/secrets/key_vault.py#L37
Just proving to myself that this is the correct path, cuz I had originally just guessed 😅

2023-05-05 09:31 UTC, jwitz approved these changes

2023-05-05 09:31 UTC, merged