[2.6] Rerun guide to include retries
astronomer/docs pull request #2195
Opened 2023-04-27 12:08 UTC by TJaniF

I tagged this PR with 2.6 because it does include 2.6 features as well, but the whole concept of retries has not been in this guide before :)

2023-04-27 16:54 UTC, TJaniF commented on learn/rerunning-dags.md
> +
```suggestion
```

2023-04-28 02:09 UTC, kentdanas approved these changes
Looks great, thanks for this @TJaniF! A couple minor comments, but I really like the way this is reframed and very glad we'll have something to share on retries now. Good to move on to copy editing

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +In Airflow you can configure individual tasks to retry automatically in case of a failure. The number of times a task will retry again before failing permanently can be defined at the Airflow configu
```suggestion
In Airflow you can configure individual tasks to retry automatically in case of a failure. The default number of times a task will retry before failing permanently can be defined at the Airflow configuration level using the core config `default_task_retries`. You can set this configuration either in `airflow.cfg` or via the environment variable `AIRFLOW__CORE__DEFAULT_TASK_RETRIES`. 
```

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +It is a common practice to set the number of retries for all tasks in a DAG by using `default_args` and override it for specific tasks as needed by providing a different value to the task-level `retr
```suggestion
It is common practice to set the number of retries for all tasks in a DAG by using `default_args` and override it for specific tasks as needed by providing a different value to the task-level `retries` parameter. 
```
I'm not sure which is right (maybe it's in our style guide but I can't seem to get to the docs notion page right now....), but we should be consistent between using "task level" or "task-level"

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +## Manually rerun tasks
```suggestion
## Manually rerun tasks or DAGs
```
Since we also talk about clearing DAG runs in this section

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +To clear the task status, go to the Grid View in the Airflow UI, select the task instance you want to rerun and click the **Clear task** button.
Can you not do this from the Graph view anymore? I think it makes the most sense to do it from the Grid view, but we should still list both if it's possible in both (no need to have another screenshot though since it's the same process, or at least it used to be)

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +Check which task instances will be clear with the current settings by expanding the dropdown menu **Affected tasks: X**. Click **Clear** to confirm and the task(s) will be cleared and rescheduled for
```suggestion
Check which task instances will be cleared with the current settings by expanding the dropdown menu **Affected tasks: X**. Click **Clear** to confirm and the task(s) will be cleared and rescheduled for another run.
```

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +Clearing or changing task statuses directly in the Airflow metastore can cause unexpected behavior in Airflow.
```suggestion
You should not clear or chang task statuses directly in the Airflow metastore as doing so can cause unexpected behavior in Airflow.
```
Making this a bit stronger :)

2023-04-28 02:09 UTC, kentdanas commented on learn/rerunning-dags.md
> +You can use the built-in [catchup](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#catchup) DAG argument to process data for logical dates between the set `start_date` of a DAG and
lol'ing at how we every managed to publish "...starting a year ago". That makes no sense 😅

2023-04-28 13:09 UTC, TJaniF reviewed
Thank you @kentdanas !

Accepted all suggestions :) 

@lzdanski and @jwitz: ready for you :) (this PR is marked as 2.6 because it does contain 2.6 features but it is less important to be ready by the release since it is mostly a general update to this guide to include retry functionality)

One question that came up is x-level. I tried to use a `-` in the following way: 
- This is a task-level feature.
- This is set at the task level.

is this correct or would both use a dash or none of them?

2023-04-28 21:30 UTC, lzdanski commented
We'll add hyphenation to our style guide. But I think you're correct!

We use `task level` as a noun and `task-level` as a compound modifier, (or maybe we're using it inconsistently everywhere). we don't have it in the style guide specifically, but that's consistent with [Google Dev Style Guide](https://developers.google.com/style/hyphens?hl=en). 

So - 

> Set the parameter at the task level. 

> ... sends a task-level alert. 

It's somewhat similar to the set up/setup usage situation.

@jwitz any thoughts?

2023-04-28 21:38 UTC, kentdanas commented on learn/rerunning-dags.md
> +To clear the task status, go to the Grid View in the Airflow UI, select the task instance you want to rerun and click the **Clear task** button.
Makes sense to me! Agree you don't need to provide specific instructions for graph view - it's easy enough to figure out if you already generally know how it works.

2023-04-28 21:58 UTC, lzdanski requested changes
I did a bit closer of an editing pass because this is a tricky thing to communicate. This was a really intuitive presentation of the concepts for me about how retries work and the way they relate to scheduling. There's a bit of passive voice and some compound clauses that might need rework, but it looks good so far!

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +Airflow DAGs can be set to run using a wide variety of [scheduling](scheduling-in-airflow.md) options. There are some uses cases in which you want tasks or whole DAGs to run outside of their regular
```suggestion
You can set when to run Airflow DAGs using a wide variety of [scheduling](scheduling-in-airflow.md) options. Some uses cases where you might want tasks or DAGs to run outside of their regular schedule include:
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +In Airflow you can configure individual tasks to retry automatically in case of a failure. The default number of times a task will retry before failing permanently can be defined at the Airflow confi
```suggestion
In Airflow, you can configure individual tasks to retry automatically in case of a failure. The default number of times a task will retry before failing permanently can be defined at the Airflow configuration level using the core config `default_task_retries`. You can set this configuration either in `airflow.cfg` or with the environment variable `AIRFLOW__CORE__DEFAULT_TASK_RETRIES`. 
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +The time spent between retries is defined by the `retry_delay` parameter (default: `timedelta(seconds=300)`). As of Airflow 2.6, a maximum value for the retry delay can be set in the core Airflow con
```suggestion
The `retry_delay` parameter (default: `timedelta(seconds=300)`) defines the time spent between retries. As of Airflow 2.6, you can set a maximum value for the retry delay in the core Airflow config `max_task_retry_delay` (`AIRFLOW__CORE__MAX_TASK_RETRY_DELAY`), which, by default, is set at 24 hours. Or, for individual tasks, you can set the maximum retry delay with the parameter, `max_retry_delay`.
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +The `default_task_retries` of an Airflow environment can be overwritten at the task level by using the `retries` parameter.
```suggestion
You can overwrite the `default_task_retries` of an Airflow environment at the task level by using the `retries` parameter.
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +It is common practice to set the number of retries for all tasks in a DAG by using `default_args` and override it for specific tasks as needed by providing a different value to the task level `retrie
```suggestion
It is common practice to set the number of retries for all tasks in a DAG by using `default_args` and override it for specific tasks as needed. To override specific tasks, provide a different value to the task level `retries` parameter. 
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +A popup window will appear giving you the following options to clear and rerun additional task instances related to the selected task:
```suggestion
A popup window appears, giving you the following options to clear and rerun additional task instances related to the selected task:
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +To clear a full DAG run, go to the Grid View in the Airflow UI, click on the DAG run and then click **Clear** as shown in the following image.
```suggestion
To clear a full DAG run, go to the Grid View in the Airflow UI, click on the DAG run, and then click **Clear** as shown in the following image. 
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +You should not clear or change task statuses directly in the Airflow metastore as doing so can cause unexpected behavior in Airflow.
```suggestion
Don't clear or change task statuses directly in the Airflow metastore. This can cause unexpected behavior in Airflow.
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +When the catchup parameter for a DAG is set to `True`, at the time the DAG is turned on in Airflow the scheduler starts a DAG run for every data interval that has not been run between the DAG's `star
```suggestion
When the catchup parameter for a DAG is set to `True`, at the time the DAG is turned on in Airflow, the scheduler starts a DAG run for every data interval that has not been run between the DAG's `start_date` and the current data interval. For example, if your DAG is scheduled to run daily and has a `start_date` of 1/1/2023, and you deploy that DAG and turn it on 2/1/2023, Airflow will schedule and start all of the daily DAG runs for January. Catchup is also triggered when you turn a DAG off for a period and then turn it on again.
```

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +When the catchup parameter for a DAG is set to `True`, at the time the DAG is turned on in Airflow the scheduler starts a DAG run for every data interval that has not been run between the DAG's `star
Because of the spacing, I keep reading it as "ketchup" and having to do a double take.

2023-04-28 21:58 UTC, lzdanski commented on learn/rerunning-dags.md
> +Alternatively, you can deploy a copy of the DAG with a new name and a start date that is the date you want to backfill to. Airflow will consider this a separate DAG so you won't see all the DAG runs
```suggestion
Alternatively, you can deploy a copy of the DAG using a new name with the start date as the date you want to backfill to. Airflow considers this a separate DAG, so you won't see all the DAG runs and task instances in the same place, but it runs the DAG for data in the desired time period. If you have a small number of DAG runs to backfill, you can trigger them manually from the Airflow UI via `Trigger DAG w/ config` and choose the desired logical date as shown in the following image:
```

2023-05-01 13:02 UTC, TJaniF reviewed
Thank you for the review and clarifying task level vs task-level @lzdanski ! I accepted all of you suggestions :)

2023-05-01 13:02 UTC, TJaniF commented on learn/rerunning-dags.md
> +When the catchup parameter for a DAG is set to `True`, at the time the DAG is turned on in Airflow the scheduler starts a DAG run for every data interval that has not been run between the DAG's `star
😂 I somehow never had that association but now I can't unsee it 🍅

2023-05-04 13:34 UTC, lzdanski approved these changes

2023-05-04 15:23 UTC, merged