add note for podman rootful mode
astronomer/docs pull request #2199
Opened 2023-04-28 07:55 UTC by manmeetkaur

2023-04-28 14:33 UTC, lzdanski requested changes
Small style detail

2023-04-28 14:33 UTC, lzdanski commented on astro/cli/configure-cli.md
> +If you are using M1 Mac, you will need to turn on rootful mode for Podman using `podman machine set --rootful`.
```suggestion
If you use an M1 Mac, turn on rootful mode for Podman by using `podman machine set --rootful`.
```
This is a style suggestion to make the composition active voice - if you're interested in learning more about why we do that in docs, would be happy to share!

2023-05-02 08:12 UTC, jwitz approved these changes
One comment about note placement, otherwise LGTM!

2023-05-02 08:12 UTC, jwitz commented on astro/cli/configure-cli.md
>  ## Run the Astro CLI using Podman
```suggestion
## Run the Astro CLI using Podman

```

2023-05-02 09:15 UTC, manmeetkaur commented on astro/cli/configure-cli.md
> +If you are using M1 Mac, you will need to turn on rootful mode for Podman using `podman machine set --rootful`.
by mistake I clicked on the wrong button, making these changes now.

2023-05-02 13:35 UTC, lzdanski approved these changes

2023-05-04 10:34 UTC, merged