Update dag-best-practices.md
astronomer/docs pull request #2200
Opened 2023-04-28 13:53 UTC by RNHTTR

2023-04-28 14:47 UTC, lzdanski requested changes
This is a really cool feature - I have some suggestions about organizing the content and questions about the details.

2023-04-28 14:47 UTC, lzdanski commented on learn/dag-best-practices.md
> +Issues like this can be resolved by using task retries. Retries can be set at the DAG level using `default_args`, at the task level using the parameter `retries`, or at the deployment level by settin
```suggestion
You can resolve issues like zombie processes by using task retries. Retries can be set at different levels with the following:

- **Tasks:**  Use the parameter `retries`
- **DAGs:** Use `default_args`
- **Deployments:** Set the environment variable, `AIRFLOW__CORE__DEFAULT_TASK_RETRIES`

Set the value to `2` to protect a task from problems common to distributed environments.
```

It can be a little hard to skim a list like this, so I broke it out into bullet points. But I also have a couple of clarifying questions -  

1. In the last sentence, does **retries** only refer to the parameter `retries` or does it apply to all of these? 
2. I have these ordered from most specific to most general - is that ok?
3. What are accepted values? What's the default behavior?

2023-04-28 14:55 UTC, TJaniF reviewed
Thank you @RNHTTR for the addition! One note: we have another PR open #2195 to reframe the rerun guide to include retires. I think having this chapter in best practices makes sense and your addition is great, just noting this to not forget to link to that guide from here depending on which PR gets merged first :)

2023-04-28 16:58 UTC, kentdanas approved these changes
LGTM, thanks for adding this @RNHTTR! Couple follow up comments/answers to Laura's suggestion, once that's resolved I think this is good to go.

2023-04-28 16:58 UTC, kentdanas commented on learn/dag-best-practices.md
> +Issues like this can be resolved by using task retries. Retries can be set at the DAG level using `default_args`, at the task level using the parameter `retries`, or at the deployment level by settin
Bullets look good to me. Some general answers to your questions:

1. "retries" applies to all three parameters. They are all controlling the same behavior, just at different levels of specificity.
2. I don't think the order matters here too much, yours is fine with me.
3. I wouldn't say there's an "accepted" value for retries since it's so use case specific. The default for all of them is 0 retries.

2023-04-28 16:58 UTC, kentdanas commented on learn/dag-best-practices.md
> +Issues like this can be resolved by using task retries. Retries can be set at the DAG level using `default_args`, at the task level using the parameter `retries`, or at the deployment level by settin
I think we should add a note here about precedence since we're showing all three options. Precedence is the same as the current order of the bullets - if you set a deployment level variable it will apply to all tasks, unless it is overridden in a specific DAG or a specific task. Same with DAG-level args -> task-level args

2023-05-04 18:07 UTC, lzdanski approved these changes

2023-05-05 15:21 UTC, kentdanas commented on learn/dag-best-practices.md
> +Setting retries to `2` will protect a task from most problems common to distributed environments.
```suggestion
Setting retries to `2` will protect a task from most problems common to distributed environments. For more on using retries, see [Rerun DAGs and Tasks](rerunning-dags.md).
```

2023-05-05 15:24 UTC, merged