making notion to a PR
astronomer/docs pull request #2219
Opened 2023-05-02 17:08 UTC by manmeetkaur

2023-05-03 11:00 UTC, jwitz commented on astro/manage-connections-variables.md
> +```
```suggestion
```

2023-05-03 11:06 UTC, jwitz commented on astro/manage-connections-variables.md
> +
```suggestion
#### Airflow API

You can use the [List Connections API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connections) and [Get Connection API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connection) to export connections from any Airflow environment.

You can use [List Variables API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_variables) and [Get Variable API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_variable) to export variables from any Airflow environment.

To import connections or variables to any Airflow environment, you can use the [Create Connection API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_connection) and [Create Variable API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_variables) respectively.
```

2023-05-03 11:07 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You can export both connections and variables from local to `.env` file in URI format. See [examples](manage-connections-variables#how-to-use-astro-cli-to-export-from-local)
There's just too many ways to import/ export variables, so I decided that we should document the easiest way.

2023-05-03 11:45 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +We recommend that you use [Astro CLI](https://docs.astronomer.io/astro/cli/overview) to run a local Airflow environment and test your DAGs locally before Deploying to Astro. There are 5 different app
Hey @jwitz I think want to write `should be `instead of `to be` in this sentence: "Your Airflow connection and variable management strategy to be compatible with both your local testing workflows as well as your Astro workflows."

2023-05-03 11:52 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- For local Airflow, you'll lose your connections and variables if you delete your metadata database with `astro dev kill`.
@jwitz so I am changing some terms here. UI can only export variables and not connections. so we can't use the word objects here.

2023-05-03 11:54 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +The easiest and most accessible way to create Airflow connections and variables locally is through the Airflow UI. This experience is similar across all different flavours of Airflow. This is also th
@jwitz can we add generate the URI/JSON format for a connection ? - because that is one of the main use-case as well?

2023-05-03 12:06 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Connections and Variables ***can't be*** viewed from the Airflow UI, but you can use them in your DAGs. Connections will also not be visible using `airflow connections list`
I actually wanted to remove the second part @jwitz . so removing it, it just creates confusion because it's an airflow command.

2023-05-03 12:12 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +
@jwitz removing `on the control plane` because environment variables can be stored in either Dockerfile or in Control Plane.

2023-05-03 12:20 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Secret values are omitted or redacted from the response when exporting connections/variables
@jwitz removed the last comment also, it is not a limitation of this method, rather the limitation of the export using this method.

2023-05-03 12:49 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- You can export both connections and variables from local to `.env` file in URI format. See [examples](manage-connections-variables#how-to-use-astro-cli-to-export-from-local)
@jwitz so this is actually incorrect. `astro dev object export` can only export if the variables are stored in Airflow Metadata database. I understand that you want to make it concise, let me try to do that in a different way.

2023-05-03 13:37 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- You can export both connections and variables from local to `.env` file in URI format. See [examples](manage-connections-variables#how-to-use-astro-cli-to-export-from-local)
`.env` objects are not exported actually, I re-tested.

2023-05-03 13:38 UTC, manmeetkaur commented
> Apologies for all the comments @manmeetkaur 🙈 I think this draft is a lot closer than the edits make it seem. For the most part, I tried cutting out content to make it easier for users to understand our recommendations. That means I removed `airflow_settings.yaml` docs pending approval from David, and I consolidated our import/ export methods to show only the most common methods. We can always update this doc in the future as our recommendations change!

Thanks @jwitz for the detailed comments. I made the changes and it is ready for pass 2.

2023-05-03 15:00 UTC, jwitz commented on astro/manage-connections-variables.md
> +
```suggestion
## Airflow connection and variable management strategies 

Learn about the benefits, limitations, and implementations of each strategy in the following topics 
```

2023-05-03 15:01 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
```suggestion
```

2023-05-03 15:03 UTC, jwitz commented on astro/manage-connections-variables.md
> +For more information, see [Airflow API](airflow-api.md).
```suggestion
```

2023-05-03 15:03 UTC, jwitz commented on astro/manage-connections-variables.md
> +You can use the Airflow REST API to programmatically create Airflow connections and variables on a Deployment. Airflow objects created this way are stored in the Airflow metadata database. This strat
```suggestion
You can use the Airflow REST API to programmatically create Airflow connections and variables on a Deployment. Airflow objects created this way are stored in the Airflow metadata database. This strategy is good for teams setting up large Deployments with many Airflow connections and variables.

For more information, see [Airflow API](airflow-api.md).

```

2023-05-03 15:03 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Secrets backend
```suggestion
### Secrets backend
```

2023-05-03 15:04 UTC, jwitz commented on astro/manage-connections-variables.md
> +If you use a secrets backend, the method for managing connections and variables between local environments and Deployments will vary based on your secrets backend and it's API. You can still export t
```suggestion
If you use a secrets backend, the method for managing connections and variables between local environments and Deployments will vary based on your secrets backend and its API. You can still export the connections and variables from local, but you have to rely on secret manager's API to migrate.
```

2023-05-03 15:04 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Environment variables
```suggestion
### Environment variables
```

2023-05-03 15:04 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Airflow metadata database
```suggestion
### Airflow metadata database
```

2023-05-03 15:06 UTC, jwitz commented on astro/manage-connections-variables.md
> +Airflow connections and variables stored in metadata database can be exported using Astro CLI or Airflow API.
```suggestion
Airflow connections and variables stored in metadata database can be exported using the Astro CLI or Airflow API. An Airflow connection or variable is stored in the metadata database if it's viewable in the Airflow UI under **Connections** or **Variables**.
```

2023-05-03 15:09 UTC, jwitz commented on astro/manage-connections-variables.md
> +```
```suggestion
Run the following command to export your Airflow connections and variables to Astro as environment variables:

```bash
# export all airflow objects including connections and variables to `.env` file in URI format
astro dev object export --env-export 

# import into Astro variables and/or connections defined as environment variables in the .env file
astro deployment variable create -d <deployment_id> --load --env .env
``

You can also export only variables from your local environment and then deploy them to Astro as part of your `include` folder:

```bash
# export variables in JSON format to vars.json in your astro project's include dir
astro dev run variables export /usr/local/airflow/include/vars.json
``

You can't automatically import Airflow connections and variables from Astro to a local environment if they're set as environment variables. However, you can pull down all non-secret environment variables from a Deployment using `astro deployment inspect` and then copy them into your `.env` file. See [Manage Deployments as code](manage-deployments-as-code.md#inspect-a-deployment). 
```

2023-05-03 15:12 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
This is a good thought but I'm not sure where to put this yet, let's leave it out for now. I don't think we imply that you need to use the same for both object types.

Generally speaking let's avoid adding any new content until the current content is settled.

2023-05-04 05:58 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +:::
@jwitz I don't complete agree to this. Although I understand that a special tip might seem too much given that we are just talking about management, I do feel we should include this line at least explicitly. "It is not necessary to choose the same approach for both connections and variables. Many a times, variables decide the flow of execution of your DAG and you might prefer to check them in to source control." may be in the top level introduction paragraph. Because we are infact implying that "connection and variables " go together. 

Are you cool with that remove this from here and add just that one line at the beginning w/o any details ? Because we have enough details in the import/export section.

2023-05-04 06:08 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +```
@jwitz the ideal command is `astro deployment variable list` not `inspect` . The reason I did not include this was related to your earlier feedback that "too many commands" . Because then we can also talk about using `astro dev bash` and `printenv` to get the environment variables for local run .  Thoughts ? Let's talk more on this during our call may be

2023-05-04 09:01 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
Tried adding a smaller note on this below

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +``
Sorry I meant these to be three ticks!

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +``
Sorry I meant these to be three ticks

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +
```suggestion
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +astro deployment variable create -d <deployment_id> --load --env .env
```suggestion
To import Airflow connections and variables to Astro, you must store them as environment variables in your `.env` file. Run the following command to export all environment variables to your `.env` file to a Deployment on Astro:

```bash
# import into Astro variables and/or connections defined as environment variables in the .env file
astro deployment variable create -d <deployment_id> --load --env .env
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +Airflow connections and variables stored in metadata database can be exported using the Astro CLI or Airflow API. An Airflow connection or variable is stored in the metadata database if it's viewable
```suggestion
You can export Airflow connections and variables stored in metadata database using the Astro CLI or Airflow API. An Airflow connection or variable is stored in the metadata database if it's viewable in the Airflow UI under **Connections** or **Variables**.
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +Run the following command to export your Airflow connections and variables to Astro as environment variables:
```suggestion
Run the following command to export your Airflow connections and variables and import them to Astro as environment variables:
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +You can't automatically import Airflow connections and variables from Astro to a local environment if they're set as environment variables. However, you can pull down all non-secret environment varia
```suggestion
You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret environment variables from a Deployment using `astro deployment variable list` and then copy them into your `.env` file. 
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +In production environments with multiple team members, you might want to export Airflow connections and variables from your local Airflow environment to an Astro Deployment. Similarly, you might want
```suggestion
In production environments with multiple team members, you might want to export Airflow connections and variables from an Airflow environment and import them to another environment. For example, you might want to export an Airflow connection you use locally and import it to an Astro Deployment after you've tested it. 

Use the following topics to learn different strategies for exporting and importing Airflow objects based on where they are stored:
```

2023-05-04 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +
```suggestion
```

2023-05-04 16:54 UTC, lzdanski requested changes
Some copyediting and then some style questions for Jake!

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- You can export your variables from the Airflow UI, as well as import them to the Airflow UI from a json file.
```suggestion
- You can export your variables from the Airflow UI, as well as import them to the Airflow UI from a JSON file.
```

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends th
```suggestion
The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends this method if you're just getting started with Airflow, you want to get your DAGs running quickly, or if you want to export connections in a URI/JSON format
```

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +| I need to keep my connections and variables centralized and as secure as possible | Secrets backend |
```suggestion
| I need to keep my connections and variables centralized and as secure as possible | Secrets backend |

```

Docusaurus can be particular about line breaks.

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- In a local environment, you'll lose your connections and variables if you delete your metadata database with `astro dev kill`.
```suggestion
- In a local environment, you lose your connections and variables if you delete your metadata database with `astro dev kill`.
```

Future tense (you will [verb]) can be tricky in docs. We kind of default to the present tense and use "If+then" sentence construction because English future tense can be tricky for folks who use other languages as their primary and there isn't a significant grammatical difference in English between "If A happens, B will occur" and "If A happens, B occurs" like there can be with other language grammars.

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- You have to restart your local environment using `astro dev restart` whenever you make changes to your `.env` file.
```suggestion
- You must restart your local environment using `astro dev restart` whenever you make changes to your `.env` file.
```

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- The environment variables are defined in plain text in `.env` and you can only mark them as a secret once you deploy to Astro.
However we land on the `secret` vs secret formatting, needs to be consistent here.

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- Environment variables are neither secure nor centralized as a secrets backend.
> - Environment variables are neither secure nor centralized when used as a secrets backend.
or
> - Environment variables are not as secure or centralized compared to a secrets backend.

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can use the Airflow REST API to programmatically create Airflow connections and variables on a Deployment. Airflow objects created this way are stored in the Airflow metadata database. This strat
```suggestion
You can use the Airflow REST API to programmatically create Airflow connections and variables for a Deployment. Airflow objects created this way are stored in the Airflow metadata database. This strategy is good for teams setting up large Deployments with many Airflow connections and variables.
```
@jwitz On Deployments? In Deployments? Either? Something to add to the terminology conversation?

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +In production environments with multiple team members, you might want to export Airflow connections and variables from your local Airflow environment to an Astro Deployment. Similarly, you might want
> The following sections explain the benefits, limitations, and implementations of each strategy in more detail.

For the last sentence to be consistent with suggestion with previous section.

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +If you use a secrets backend, the method for managing connections and variables between local environments and Deployments will vary based on your secrets backend and its API. You can still export th
```suggestion
If you use a secrets backend, the method for managing connections and variables between local environments and Deployments varies based on your secrets backend and its API. You can still export the connections and variables from local, but you must rely on secret manager's API to migrate.
```

2023-05-04 16:54 UTC, lzdanski commented on astro/manage-connections-variables.md
> +For example, if you set `AIRFLOW_VAR_MY_VARIABLE` with one value as an environment variable and you set the same variable `MY_VARIABLE` with another value in the Airflow UI, Astro uses the value set
```suggestion
For example, if you set `AIRFLOW_VAR_MY_VARIABLE` with one value as an environment variable and you set the same variable `MY_VARIABLE` with another value in the Airflow UI, Astro uses the value set in the environment variable.

```

2023-05-05 10:22 UTC, jwitz commented on astro/manage-connections-variables.md
> +- Environment variables marked as secret are encrypted in the Astronomer control plane.
I would go for `**Secret**`, that's how we refer to it in https://docs.astronomer.io/astro/environment-variables!

2023-05-05 11:41 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Environment variables are neither secure nor centralized as a secrets backend.
the second one is apt to this scenario; the first one is changing the meaning. and I think we should also link to the secrets backend section

2023-05-05 11:55 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +astro deployment variable create -d <deployment_id> --load --env .env
@jwitz the variable import command is redundant here, because the intention was to include all the commands as the bottom in the Astro CLI section. Would it make more sense to keep this cleaner to include the following :

- You can easily export connections and variables stored as Environment variables in `.env` file to another local Airflow
- You cannot import connections and variables to Astro, but can use CLI for listing the environment variables. The secret values are redacted though when using CLI. (And then link to the Astro CLI command)

2023-05-05 20:15 UTC, lzdanski submitted a review, later dismissed
Just a couple of follow up comments! This is looking good!

2023-05-05 20:15 UTC, lzdanski commented on astro/manage-connections-variables.md
> +
A nice to have or fast follow: Some of these sections have related links listed before the H3 and H4 levels (like secrets backend). For example, in this section, would it make sense to have some links to the different Learn resources about Airflow connections?

2023-05-05 20:15 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- You can configure secrets backend to allow selective access to connections and variables based on naming convention.
```suggestion
- You can configure your secrets backend to allow selective access to connections and variables based on naming convention.
```

2023-05-30 08:18 UTC, lzdanski reviewed
This looks fantastic overall! I really only have some grammar/style details (and some of them, definitely use your own judgement or we can discuss as a team later today. I have a couple recommendations that might be artifacts of past style guides I've worked with, so I'm open to talking it about them!

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
```suggestion
You are not required to use the same approach for both connections and variables. Variables often determine your DAG's flow of execution, and you might prefer to check variables into source control. You  can also view or edit variables in the Airflow UI. In this case, you can export your variables in a `json` file from the Airflow UI or using Astro CLI.
```

> Variables often determine your DAG's flow of execution and you might prefer to check them into source control. 

I think I'm a little unclear about this sentence. Does choosing to check Variables into source control affect the approach a user takes for connections and variables? Why?

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +Astronomer recommends using the [Astro CLI](cli/overview.md) to run a local Airflow environment and test your DAGs locally before deploying to Astro. Your Airflow connection and variable management s
```suggestion
Astronomer recommends using the [Astro CLI](cli/overview.md) to run a local Airflow environment and to test your DAGs locally before deploying them to Astro. Your Airflow connection and variable management strategies must be compatible with both your local testing workflows and your Astro workflows. However, you might need to use one strategy for storing variables and a different strategy for storing connections.
```

I notice myself making these changes as I go from reading to understanding. Is the "must be compatible" true?

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +The following table suggests some possible management strategies for specific use cases.
```suggestion
The following table suggests possible management strategies for specific use cases.
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +| I'm just getting started and want to quickly create Airflow objects | Airflow UI |
```suggestion
| I'm getting started and want to quickly create Airflow objects | Airflow UI |
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +The following table suggests some possible management strategies for specific use cases.
I love this table BTW.

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends th
```suggestion
The quickest way to create Airflow connections and variables is through the Airflow UI, which uses the same process for both local Airflow environments and Astro Deployments. Astronomer recommends this method if you're getting started with Airflow, you want to get your DAGs running quickly, or if you want to export connections in a URI/JSON format.
```

Is there a reason you chose the word "experience" vs "process"?

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- Secrets that can be shared across different Airflow environments.
```suggestion
- Secrets can be shared across different Airflow environments.
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can easily import connections and variables stored as Environment variables in `.env` file to another local Airflow by copying the `.env` file to another Astro project. To import Airflow connecti
```suggestion
You can import connections and variables stored as Environment variables in `.env` file to another local Airflow by copying the `.env` file to another Astro project. To import Airflow connections and variables to Astro, refer to the commands defined in [Astro CLI](#using-astro-cli) to import all environment variables in your `.env` file to a Deployment on Astro.
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +Run the following command to import or export your Airflow connections and variables and import them to Astro as environment variables:
```suggestion
Run the following command to import or export your Airflow connections and variables, and then import them to Astro as environment variables:
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can also export only variables from your local environment and then deploy them to Astro as part of your `include` folder:
```suggestion
You can also export only variables from your local environment, and then deploy them to Astro as part of your `include` folder:
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret e
Missing a link/sentence at the end here!

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +To export connections from any Airflow environment, you can use the [List Connections API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connections) an
```suggestion
To export connections from any Airflow environment, you can use the [List Connections API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connections) and [Get Connection API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connection).
```

2023-05-30 08:18 UTC, lzdanski commented on astro/manage-connections-variables.md
> +To export variables from a local Airflow or Astro Deployment, go to the **Admin** menu on the Airflow UI, click on **Variables** and select the variables you want to export. Then, click on **Export**
```suggestion
To export variables from a local Airflow or Astro Deployment, go to the **Admin** menu on the Airflow UI, click on **Variables** and select the variables you want to export. Then, click on **Export** option in the **Actions** dropdown. This downloads the `variables.json` file locally.
```

2023-05-30 10:51 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
@lzdanski Values saved in variables can either be used to dynamically generate a DAG or just populate a file name based on production or dev environment, or chose to use a different table name for testing, or even skip a task. Variables in Airflow can be defined as a json, so essentially a key value pair rather than a simple static value. This is the reason, I wanted to mention this as a scenario, that many people might want to check in their variables because it represents an execution flow of their DAG and DAGs would be easier to debug if we know a variable as touched.

2023-05-30 10:56 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +Astronomer recommends using the [Astro CLI](cli/overview.md) to run a local Airflow environment and test your DAGs locally before deploying to Astro. Your Airflow connection and variable management s
not necessarily. many a times because of security policies the local/dev vs prod strategies are completely different. Per me, "must" says it is a rule, whereas what we recommend is "similar strategy means easy transition between environments".

2023-05-30 10:59 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends th
tagging @jwitz here to make this call.

2023-05-30 11:01 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- You can export your variables from the Airflow UI, as well as import them to the Airflow UI from a JSON file.
@lzdanski if I want to write, export to a JSON file, can we edit like this:

"You can export your variables from the Airflow UI to a JSON file and import them to the Airflow UI from a JSON file."

2023-05-30 11:57 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret e
```suggestion
You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret environment variables from a Deployment using `astro deployment variable list` and then copy them into your `.env` file. Refer to [CLI examples](astro-deployment-variable-create.md#examples).
```

2023-05-30 14:00 UTC, lzdanski commented on astro/manage-connections-variables.md
> +Astronomer recommends using the [Astro CLI](cli/overview.md) to run a local Airflow environment and test your DAGs locally before deploying to Astro. Your Airflow connection and variable management s
Got it! I've adjusted my suggestion to remove the "must"

2023-05-30 14:07 UTC, lzdanski commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
@manmeetkaur - how does something like that look? we might need a judgement call from another writer.

2023-06-13 13:15 UTC, jwitz commented on astro/manage-connections-variables.md
> +You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret e
```suggestion
You can't automatically export Airflow connections and variables from Astro and import them to a local environment if they're set as environment variables. However, you can pull down all non-secret environment variables from a Deployment using `astro deployment variable list` and then copy them into your `.env` file. Refer to [CLI examples](cli/astro-deployment-variable-create.md#examples).
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
```suggestion
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
```suggestion
```
This note is still confusing to me, because it states that you can use different strategies for managing connections and variables, but then we only explain how to use two different strategies for managing variables. Can we address this use case separately in another PR and focus on the core content so we can publish this?

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +| Secrets backend | Third-party secrets backend | No | Refer to your secrets backend tool documentation. |
```suggestion
| Secrets backend | Third-party secrets backend | No | Refer to your secrets backend tool documentation |
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +If you want to choose a strategy based on how Airflow connections and variables are stored, the following table shows which storage and encryption methods that each strategy uses.
```suggestion
To choose a strategy based on how Airflow connections and variables are stored, use the following table to understand which storage and encryption methods that each strategy uses.
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +3. Metadata database (any connection or variable which is visible in the Airflow UI)
```suggestion
-  Secrets backend 
- Environment variables
- Metadata database (any connection or variable which is visible in the Airflow UI)
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +For example, if you set `AIRFLOW_VAR_MY_VARIABLE` with one value as an environment variable and you set the same variable `MY_VARIABLE` with another value in the Airflow UI, Astro uses the value set
```suggestion
For example, if you set `AIRFLOW_VAR_MY_VARIABLE` as an environment variable and you set the same variable `MY_VARIABLE` with a different value in the Airflow UI, Astro uses the value set in the environment variable.
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends th
```suggestion
The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends this method if you're just getting started with Airflow, you want to get your DAGs running quickly, or if you want to export connections in a URI/JSON format.
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +The quickest way to create Airflow connections and variables is through the Airflow UI. This experience is the same for both local Airflow environments and Astro Deployments. Astronomer recommends th
I don't think this is quite right, resolving this suggestion.

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Using Astro CLI
```suggestion
#### Using the Astro CLI
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Using Airflow API
```suggestion
#### Using the Airflow REST API
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +#### Using Airflow UI
```suggestion
#### Using the Airflow UI
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +You can export Airflow connections and variables stored in metadata database using the [Astro CLI](#using-astro-cli) or [Airflow API](#using-airflow-api). An Airflow connection or variable is stored
```suggestion
You can export Airflow connections and variables stored in metadata database using the [Astro CLI](#using-the-astro-cli), [Airflow UI](#using-the-airflow-ui), or [Airflow API](#using-the-airflow-api). An Airflow connection or variable is stored in the metadata database if it's viewable in the Airflow UI under **Connections** or **Variables**. For variables, you can also use [Airflow UI](#using-airflow-ui) to import or export.
```

2023-06-13 13:29 UTC, jwitz commented on astro/manage-connections-variables.md
> +If you use a secrets backend, the method for managing connections and variables between local environments and Deployments varies based on your secrets backend and its API. You can still export the c
```suggestion
If you use a secrets backend, your secrets backend and its API determines how you manage connections and variables between local environments and Deployments. Refer to your secrets backend provider's documentation to learn how to manage resources using API calls.
```

2023-06-13 13:32 UTC, jwitz commented on astro/manage-connections-variables.md
> +| I want to test my connection and export as URI format | Airflow UI. For exporting as URI refer to [Import and export](manage-connections-variables#import-and-export-airflow-connections-and-variable
```suggestion
| I want to test my connection and export in a URI format | Airflow UI. See [Import and export](manage-connections-variables#import-and-export-airflow-connections-and-variables) |
```

2023-06-13 13:32 UTC, jwitz commented on astro/manage-connections-variables.md
> +| I want to deploy the same variables across multiple different Airflow environments  | Environment variables or [export as json](manage-connections-variables#astro-cli) |
```suggestion
| I want to deploy the same variables across multiple different Airflow environments  | Environment variables or [JSON + Astro CLI](manage-connections-variables#astro-cli) |
```

2023-06-13 13:34 UTC, jwitz commented on astro/manage-connections-variables.md
> +To import variables to a local Airflow or Astro Deployment from a `json` file, go to the **Admin** menu on the Airflow UI, click on **Variables** and click on **Choose file**. Select the file you wan
```suggestion
To import variables to a local Airflow environment or Astro Deployment from a `json` file, go to **Admin** in the Airflow UI, click **Variables**, then and click **Choose file**. Select the file you want to import and then click **Import Variables**.
```

2023-06-13 13:35 UTC, jwitz commented on astro/manage-connections-variables.md
> +Learn more about [connections](https://docs.astronomer.io/learn/connections) in Learn.
```suggestion
See [Connections](https://docs.astronomer.io/learn/connections) for more information about managing connections on Airflow.
```

2023-06-13 13:39 UTC, jwitz commented on astro/manage-connections-variables.md
> +sidebar_label: 'Manage Airflow connections and variables'
```suggestion
sidebar_label: 'Manage connections and variables'
```

2023-06-13 13:54 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
I can remove the last line "for such cases..." which is actually a brief one-liner example of a case. we can take that as a separate PR. but I do want to make a note about two different approaches are totally fine. The example use-case can be taken up in a separate PR.

2023-06-13 14:20 UTC, jwitz commented on astro/manage-connections-variables.md
> +It is not necessary to choose the same approach for both connections and variables. Variables often determine your DAG's flow of execution and you might prefer to check them into source control. You
We have a line for that below though: 

> However, you might need to use one strategy for storing variables and a different strategy for storing connections.

2023-06-15 18:26 UTC, paolaperaza requested changes

2023-06-16 07:05 UTC, manmeetkaur commented on astro/cli/astro-dev-run.md
> +$ astro dev run connections export - --file-format=env
URI is default , updated comment

2023-06-16 14:08 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +For in-depth information on creating and managing connections see [Connection Basics](https://docs.astronomer.io/learn/connections).
Variable basics does not exist, so need to add that.

2023-06-16 14:10 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +:::
move to the end of the topic

2023-06-16 14:18 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- Limits open connections to your metadata database, especially if you are using your connections and variables outside of task definitions.
fix this line

2023-06-16 14:20 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- For local Astro projects, you can also use `airflow_settings.yaml` for defining your connections and variables. See [Configure `airflow_settings.yaml`](develop-project.md#configure-airflow_settings
- introduce the topic
- add some detail about why or why not do this - and also add a line of how to use airflow_settings.yaml with astro cli.

2023-06-16 14:24 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +To import connections or variables to any Airflow environment, you can use the [Create Connection API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_co
add a references/next read section and include authenticate to cloud from local.

2023-06-16 14:26 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +### Airflow UI
include From as a prefix.

2023-06-16 14:27 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +You cannot bulk import or export Connections from the Airflow UI due to security reasons. See [Connections](https://docs.astronomer.io/learn/connections) for more information about creating and editi
remove the link to create and edit.

2023-06-16 14:34 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +If you use a secrets backend, it's API determines how you manage connections and variables between local environments and Deployments. Refer to your secrets backend provider's documentation to learn
add a one-liner, to explain why you need to use this or not use this. either migration or what else?

2023-06-16 14:35 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +Airflow objects include connections, variables and pools. There are different strategies that you can choose to store your Airflow objects as explained in [Manage connections and variables](manage-co
how can we add some pointers on when to import or export, can we add some scenarios ?

2023-06-16 15:14 UTC, jwitz requested changes
Will take another look on Monday!

2023-06-16 15:14 UTC, jwitz commented on astro/import-and-export-airflow-objects.md
> +You can't automatically export connections and variables defined as environment varianles in your Astro Deployment either via Cloud UI or Dockerfile. However, you can pull down these using Astro CLI
```suggestion
If your connections and variables are defined as environment variables on an Astro Deployment, you can export them to a local Airflow environment using the Astro CLI. Note that when you run the following command, environment variables with secret values will have those values redacted.
```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- A centralized location alongside other secrets from other tools and systems used by your organization.
```suggestion
- Store objects in a centralized location alongside other secrets used by your organization.
```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- Recover in the case of an incident.
```suggestion
- Recover objects if your Airflow environments go down.
```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- Secrets can be shared across different Airflow environments, allowing you to integrate with your new Deployment instead of having to set them manually in the Airflow UI.
```suggestion
- Share secrets across different Airflow environments.
```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You cannot directly export your environment variables from Astro Cloud UI. See [import and export Airflow objects](import-export-airflow-objects#environment-variables).
```suggestion
- You cannot directly export your environment variables from the Cloud UI to a local Airflow environment. See [import and export Airflow objects](import-export-airflow-objects#environment-variables).
```
Deployment to Deployment exports are possible. See https://docs.astronomer.io/astro/cli/astro-deployment-connection-copy

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +
```suggestion

While it's possible to manage Airflow connections and variables with these strategies, Astronomer doesn't recommend them at scale: 

```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You can use Airflow REST API to programmatically create Airflow connections and variables for a Deployment. Airflow objects created with the API are stored in the Airflow metadata database and henc
```suggestion
- You can use the Airflow REST API to programmatically create Airflow connections and variables for a Deployment. Airflow objects created with the API are stored in the Airflow metadata database and hence visible on the Airflow UI.
```

2023-06-16 15:14 UTC, jwitz commented on astro/manage-connections-variables.md
> +- For local Astro projects, you can also use `airflow_settings.yaml` for defining your connections and variables. See [Configure `airflow_settings.yaml`](develop-project.md#configure-airflow_settings
```suggestion
- For local Astro projects, you can use `airflow_settings.yaml` for defining your connections and variables. See [Configure `airflow_settings.yaml`](develop-project.md#configure-airflow_settingsyaml-local-development-only) for more details.
```

2023-06-23 13:55 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +You cannot bulk import or export Connections from the Airflow UI due to security reasons. See [Connections](https://docs.astronomer.io/learn/connections) for more information about creating and editi
that is a good one. I think we should add those, no security rist in that.

2023-06-23 13:57 UTC, manmeetkaur commented on astro/import-and-export-airflow-objects.md
> +To import connections or variables to any Airflow environment, you can use the [Create Connection API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_co
@jwitz I was going to but then we included the section about Airflow REST API in the strategy guide. so it doesn't hurt to keep it ? Thoughts ?

2023-06-26 12:53 UTC, jwitz commented on sidebarsAstro.js
> +        "import-export-connections-variables",
```suggestion
        {
          type: "category",
          label: "Airflow connections and variables",
          items: [
            "manage-connections-variables",
            "import-export-connections-variables",
          ],
        },
```

2023-06-26 12:54 UTC, jwitz commented on astro/manage-connections-variables.md
> +For in-depth information on creating and managing connections see [Connection Basics](https://docs.astronomer.io/learn/connections).
It will shortly, let's make a note to add that here when it's published

2023-06-26 12:55 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You can export environment variables from local Airflow to Astro using the Astro CLI. See [import and export Airflow objects](import-export-airflow-objects#environment-variables).
```suggestion
- You can export environment variables from local Airflow to Astro using the Astro CLI. See [import and export Airflow objects](import-export-airflow-objects.md#environment-variables).
```

2023-06-26 12:56 UTC, jwitz commented on astro/manage-connections-variables.md
> +- [Authenticate to cloud from local](cli/authenticate-to-clouds)
```suggestion
- [Import and export Airflow objects](import-export-connections-variables.md)
- [Authenticate to cloud from local](cli/authenticate-to-clouds.md)
```

2023-06-26 13:02 UTC, jwitz commented on astro/import-export-connections-variables.md
> +Based on your management strategy, the storage location for your Airflow objects will vary and hence the methods to import and export will vary as well. [Astro CLI](https://docs.astronomer.io/astro/c
```suggestion
The import/ export methods available to you are defined by your [connection and variables management strategy](manage-connections-variables.md).
```

2023-06-26 13:03 UTC, jwitz commented on astro/import-export-connections-variables.md
> +Use this document to understand these methods and also how to use simple Astro CLI commands to import or export.
```suggestion
Use this document to understand each import/export method and which strategies they can be used with.
```

2023-06-26 13:04 UTC, jwitz commented on astro/import-export-connections-variables.md
> +To set up a secrets backend on Astro, see [configure secrets backend](secrets-backend).
```suggestion
To set up a secrets backend on Astro, see [configure secrets backend](secrets-backend.md).
```

2023-06-26 15:19 UTC, jwitz approved these changes

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
```suggestion
```

Why would someone "just want to test their connection"? This feels like information that we should include in the Airflow UI section. Is this noteworthy enough to include alongside all of our high level recommendations?

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- If you user `.env` file for local Airflow and your local metadata database is corrupted or accidentally deleted, you still have access to all of your connections and variables.
```suggestion
- If you use an `.env` file for your local Airflow environment and your local metadata database is corrupted or accidentally deleted, you still have access to all of your connections and variables.
```

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You can export environment variables from local Airflow to Astro using the Astro CLI. See [Import and export connections and variables](import-export-connections-variables.md#environment-variables)
```suggestion
- You can export environment variables from a local Airflow environment to Astro using the Astro CLI. See [Import and export connections and variables](import-export-connections-variables.md#environment-variables).
```
Style note: "Local Airflow" should always be "local Airflow environment"

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- In case you want to override variables in the Airflow UI, Airflow variables set in environment variables take precedence over Airflow UI variables. See [Environment variable priority](environment-v
```suggestion
- You can override Airflow variables set in the Airflow UI. See [Environment variable priority](environment-variables.md#environment-variable-priority)
```

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- On Astro, you can create your connections and variables as environment variables from the Cloud UI. See [use environment variables](environment-variables.md#set-environment-variables-in-the-cloud-u
```suggestion
- You can create your connections and variables as environment variables from the Cloud UI. See [Use environment variables](environment-variables.md#set-environment-variables-in-the-cloud-ui). 
```

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- The environment variables are defined in plain text in `.env` file.
```suggestion
- The environment variables are defined in plain text in your `.env` file.
```

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You cannot directly export your environment variables from the Cloud UI to a local Airflow environment. See [import and export Airflow objects](import-export-connections-variables.md#environment-va
```suggestion
- You cannot directly export your environment variables from the Cloud UI to a local Airflow environment. See [Import and export Airflow objects](import-export-connections-variables.md#environment-variables).
```
Style note: Always capitalize the beginnings of a hyperlink to a doc if the link is a doc's name

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- [Authenticate to cloud from local](cli/authenticate-to-clouds.md)
```suggestion
- [Authenticate to cloud services with user credentials](cli/authenticate-to-clouds.md)
```

2023-06-26 15:19 UTC, jwitz commented on astro/manage-connections-variables.md
> +- You can configure your secrets backend to allow selective access to connections and variables by using `connections_prefix` or `variables_prefix`.
```suggestion
- Allow selective access to connections and variables by using `connections_prefix` and `variables_prefix`. 
```

2023-06-26 16:09 UTC, manmeetkaur commented on astro/import-export-connections-variables.md
> +Use this document to learn how to export and import environment variables based on different connection and variable [storage and management strategies](manage-connections-variables.md).
```suggestion
Based on your management strategy, the storage location for your Airflow objects will vary and hence the methods to import and export will vary as well. Use this document to learn how to export and import environment variables based on different connection and variable [storage and management strategies](manage-connections-variables.md). 
```

2023-06-26 16:18 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +Astro allows you to seamlessly integrate [secrets backend](secrets-backend.md) of your choice, which is recommended as the most secure and centralized management strategy. We also recommend using [As
@jwitz I added this because Paola wanted to add an Astro value-add statement.

2023-06-26 16:22 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +:::
@jwitz it was already part of high level recommendations, then we took it out - because no one liked it there and so it became a tip. And while building new data pipelines and integrating new systems, we do want to test and get it in URI format.

2023-06-26 16:24 UTC, manmeetkaur commented on astro/manage-connections-variables.md
> +- [Set environment variables on Astro](environment-variables.md#add-airflow-connections-and-variables-using-environment-variables)
@jwitz did you want to change anything here ?

2023-06-27 08:39 UTC, jwitz commented on astro/import-export-connections-variables.md
> +
```suggestion
```

2023-06-27 08:39 UTC, jwitz commented on astro/manage-connections-variables.md
> +If you just want to test your connection and export in JSON or URI format, use Airflow UI to [create your connection](https://docs.astronomer.io/learn/connections#defining-connections-in-the-airflow-
```suggestion
If you only want to test connections or export connections in  a JSON or URI format, use the Airflow UI to [manage your connection](https://docs.astronomer.io/learn/connections#defining-connections-in-the-airflow-ui).  You can then use the Astro CLI commands to export the connections in a URI or JSON format. See [Import and export connections and variables](import-export-connections-variables.md#from-the-airflow-ui-metadata-database).
```

2023-06-27 08:39 UTC, jwitz commented on astro/manage-connections-variables.md
> +:::
Ah missed that thread- just updated my suggestion with some new wording.

2023-06-27 08:39 UTC, jwitz commented on astro/manage-connections-variables.md
> +- [Set environment variables on Astro](environment-variables.md#add-airflow-connections-and-variables-using-environment-variables)
I did but then reverted the edit, so this is not actionable - my mistake

2023-06-27 10:36 UTC, jwitz approved these changes

2023-06-27 10:36 UTC, jwitz commented on astro/manage-connections-variables.md
> +Use this document to select the right Airflow connection and variable management strategies for your team.
```suggestion
Use this document to select the right Airflow connection and variable management strategies for your team.

Airflow supports several different methods for managing connections and variables. Each of these strategies has benefits and limitations related to their security and ease of use. The strategies you choose should be compatible with both your local environments and Astro Deployments, allowing you to [import and export objects](import-export-connections-variables.md) between the two contexts.
```

2023-06-30 05:35 UTC, merged