Convert Create first DAG to DAG-only deploy (Draft)
astronomer/docs pull request #2237
Opened 2023-05-05 16:25 UTC by lzdanski

- [ ] Fix any broken links
- [ ] Fix content gaps 
    - Currently missing consolidated content about creating and deploying a full image. Existing deploy-code was not created with this purpose in mind and now seems weird to have DAG-only deploys in same doc with other strategies.
- https://github.com/astronomer/docs/issues/2231

2023-05-11 12:48 UTC, jwitz requested changes
This LGTM for the most part! Before we merge, we should have a definitive strategy for where/ when we want to mention Docker or list it as a prerequisite. I listed some options here and would like to see which one you opt for. 

Also agreed that Deploy Code is a little messy now, and a good next issue to tackle would be splitting the different deploy options into separate docs.

2023-05-11 12:48 UTC, jwitz commented on astro/create-first-dag.md
> +- The [Astro CLI](cli/install-cli.md), but you do not need to install Docker to complete this guide
Should we just go ahead and remove Docker from the CLI install prerequisites? Or list it there as optional if you want to run Airflow locally/ deploy project changes?

2023-05-11 12:48 UTC, jwitz commented on astro/create-first-dag.md
> +This guide shows you how to deploy your DAGs to Astro, which does not require Docker. For a standard deployment of a complete Astro project, see [Deploy Code](deploy-code.md).
```suggestion
This guide shows you how to deploy only your DAG files to Astro. To deploy other project changes, such as Python dependencies, see [Deploy Code](deploy-code.md).
```

2023-05-11 12:48 UTC, jwitz commented on astro/create-first-dag.md
> +You can use DAG-only deploys to quickly update your Astro Deployment without building a Docker image of your entire project.
```suggestion
You can use DAG-only deploys to quickly update your Astro Deployment.
```
Not sure we need to mention Docker at this stage, WDYT?

2023-05-11 14:22 UTC, lzdanski commented on astro/create-first-dag.md
> +- The [Astro CLI](cli/install-cli.md), but you do not need to install Docker to complete this guide
Before this PR gets merged, I realized that I haven't been able to test if `astro dev init` works without Docker. There were a couple of messages that got printed during my build and in the descriptions of the core commands (https://docs.astronomer.io/astro/cli/overview#core-commands) that make me a little wary of removing docker if it's that important to what we consider core commands or actions.

2023-05-12 09:13 UTC, jwitz commented on astro/create-first-dag.md
>  ## Step 6: Trigger your DAG on Astro
```suggestion
## Step 5: Trigger your DAG on Astro
```
Oops forgot this!

2023-05-12 15:05 UTC, jwitz commented on astro/create-first-dag.md
> +1. Run the following command to enable DAG-only code deploys.
```suggestion
1. Run the following command to enable DAG-only code deploys on your Deployment.
```

2023-05-12 15:06 UTC, jwitz commented on astro/create-first-dag.md
>  - [Learn how to write your own DAGs](https://docs.astronomer.io/learn/category/dags)
```suggestion
```

2023-05-12 15:06 UTC, jwitz commented on astro/create-first-dag.md
>  - [Set up CI/CD](/astro/set-up-ci-cd)
```suggestion
```

2023-05-12 15:06 UTC, jwitz commented on astro/create-first-dag.md
>  - [Develop a project](/astro/develop-project)
```suggestion
- [Develop a project](/astro/develop-project)
- [Deploy code to Astro](/astro/deploy-code)
```

2023-05-12 15:07 UTC, jwitz commented on astro/create-first-dag.md
> +Now that you've created and run your first DAG on Astro, the next step is to learn how to deploy a complete Astro Project to the Cloud UI.
```suggestion
Now that you've created and run your first DAG on Astro, the next step is to learn how to deploy a complete Astro Project to the Cloud UI. See:
```

2023-05-12 15:29 UTC, lzdanski commented on astro/create-first-dag.md
> +- The [Astro CLI](cli/install-cli.md), but you do not need to install Docker to complete this guide
I'm going to come back and update this section after I finish with the CLI draft. For right now, I think it makes sense to keep that docker isn't a requirement for this quickstart.

2023-05-16 04:17 UTC, paolaperaza requested changes
Alrighty, gave this a review! I had enough comments (and this is important enough) that I'm gonna request changes and give this another review before we merge.

It's looking good though, we're super close. Back to you for now, @jwitz !

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
>  An Astro _Deployment_ is an Astro Runtime environment that is powered by the core components of Apache Airflow, including the Airflow webserver, scheduler, and one or more workers. You can have one o
```suggestion
An Astro _Deployment_ is an instance of Apache Airflow that can run DAGs and is powered by core Airflow components, including the Airflow webserver, scheduler, and one or more workers. You can have one or more Deployments within a _Workspace_, which is a collection of users that have access to the same Deployments. In most cases, Astronomer recommends creating a Deployment for each logical set of DAGs that you want to manage. You can create more dedicated Deployments over time that represent development or production environments.
```

Too much? Gimme feedback (and know we haven't defined glossary), but thought a lil more context would be good

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
>  3. Complete the following fields:
Do we need update the **Cluster** thing here? Maybe say something that pushes them to `Standard`? Should we explicitly say assume defaults for everything else?

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
>      For more information about possible Deployment health statuses, see [Deployment health](deployment-metrics.md#deployment-health). Or, to learn more about how to customize your Deployment settings
^There's some cluster language up top that I'd remove -- simplify to: `... until all underlying Airflow components are healthy`.

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +You can use DAG-only deploys to quickly update your Astro Deployment.
We def shouldn't spend too much time here, but I'd add half a sentence to clarify what we're talking about. At least call it a "feature" that "only deploy the `dags` folder of your Astro project, which allows you to deploy changes more quickly without Docker and without having to restart your Airflow environment."

Something like that

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> -After you select a Deployment, the CLI parses your DAGs to ensure that they don't contain basic syntax and import errors. If your code passes the parse, the Astro CLI builds all files in your Astro p
Hm feels like we still want some variety of this sentence even if it's shorter. And DAGs still parse right? That's a feature/value-add we should still have if so!

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +3. Run the following command to finalize the setup and trigger a DAG-only deploy to your Deployment:
```suggestion
3. Run the following command to deploy your DAGs to Astro: 
```

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +You can use DAG-only deploys to quickly update your Astro Deployment.
I'd also specify here that the DAGs we're deploying are the example DAGs we alluded to at the top. Maybe say that you're free to add your own in addition to that

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +## Step 5: Trigger your DAG on Astro
```suggestion
## Step 5: Trigger your DAG in Airflow UI
```

Maybe?

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +When you deploy your Astro project, all example DAGs are paused and will not start running automatically. To run one of these example DAGs according to its schedule, you must unpause it from the Airf
```suggestion
Any time that you deploy new DAGs to Astro, they are paused and will not start running automatically. To run one of the example DAGs in your Astro project according to its schedule, you must unpause it from the Airflow UI.
```

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +## Step 7: (Optional) Delete your Deployment
Debating on whether we include this vs. just include as note in next steps -- will let you make the call @jwitz but wanted to throw it out there

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +Now that you've created and run your first DAG on Astro, the next step is to learn how to deploy a complete Astro Project to the Cloud UI. See:
```suggestion
Now that you've created and run your first DAG on Astro, the next step is to add your own DAGs, build out the rest of your Astro project, and start testing real data. See:
```

2023-05-16 04:17 UTC, paolaperaza commented on astro/create-first-dag.md
> +Now that you've created and run your first DAG on Astro, the next step is to learn how to deploy a complete Astro Project to the Cloud UI. See:
Yea, the "full project" thing with Docker + Astro CLI is a little confusing -- not sure what answer is but give it another look @jwitz

2023-05-16 14:42 UTC, jwitz commented on astro/create-first-dag.md
I don't know about this, it feels like we are projecting because veteran Astro users obviously understand the need of Docker for local testing, but a new user likely won't have any assumption about needing Docker?

2023-05-17 09:49 UTC, jwitz commented on astro/create-first-dag.md
>  2. Go to `https://cloud.astronomer.io`, and select one of the available options to access the Cloud UI.
Auth docs FAQs are primarily published to catch users that are used to our previous login workflow, they don't mean much to brand new users. I think it's okay to not link those here.

2023-05-17 09:57 UTC, jwitz commented on astro/create-first-dag.md
>  An Astro _Deployment_ is an Astro Runtime environment that is powered by the core components of Apache Airflow, including the Airflow webserver, scheduler, and one or more workers. You can have one o
Also "Instance of Airflow.. powered by core Airflow components" feels redundant. I like "instance of Airflow that hosts all core Airflow components

2023-05-17 10:27 UTC, jwitz commented on astro/create-first-dag.md
> +## Step 5: Trigger your DAG on Astro
Hm I know that we will have another way of doing this "On Astro", but to start talking about the "Airflow UI" at this stage could be confusing. I'd read this and think I have to go somewhere other than Astro to access the Airflow UI

2023-05-17 10:32 UTC, jwitz commented on astro/create-first-dag.md
> +## Step 7: (Optional) Delete your Deployment
Hm I'd like to make it more apparent first to show that resource management is a core part of the Astro workflow. It's also useful to surface this now because it's not super clear in the product where to do this

2023-05-17 10:34 UTC, jwitz commented
@paolaperaza Thanks for the suggestions, this is ready for another review!

2023-05-19 00:49 UTC, conorbev commented on astro/create-first-dag.md
> +## Step 5: Trigger your DAG on Astro
I see that the intent in this doc is to have the user go through the Airflow UI. I think it'd be good to change that to the Astro UI in the near future ( maybe give the new DAG page in Astro a couple of weeks to bed in )

2023-05-19 00:49 UTC, conorbev commented on astro/create-first-dag.md
>  Your Airflow UI view allows you to examine your DAGs in detail, while the Cloud UI shows you information about the health of your Deployment including analytics and logs of your DAG runs.
I get that the intent is to drive users to the Airflow UI but I think this part now seems a bit confusing given the DAGs page(s) in Astro? Like Astro lets you examine your DAG in detail too..

2023-05-19 08:24 UTC, jwitz commented on astro/create-first-dag.md
>  Your Airflow UI view allows you to examine your DAGs in detail, while the Cloud UI shows you information about the health of your Deployment including analytics and logs of your DAG runs.
```suggestion
The Cloud UI shows you information about the health of your Deployment, including analytics and logs for your DAG runs.
```

2023-05-22 04:24 UTC, paolaperaza approved these changes
A few comments here @jwitz but I'll let you take it over the finish line!

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
>  - Create a Deployment.
Change up order here to match new steps?

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
Good point. I think just because Astro CLI install docs have Docker on there + obviously so many people have Docker problems (and we actively tried to make these steps Docker-less).

I'd keep it, but maybe add a teeny bit of context?

I just don't like it in the bullet points below

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +## Step 3: Log in to Astro CLI and Cloud UI
Should we skip straight to create a Deployment before we log the user in? Feels weird to flip them to CLI.

Re: auth to UI -- keep it to the "create your user account" part?

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +An Astro _Deployment_ is an instance of Airflow that hosts all core Airflow components, including a webserver, scheduler, and one or more workers. You can have one or more Deployments within a Worksp
```suggestion
An Astro _Deployment_ is an instance of Apache Airflow that is powered by all core Airflow components, including a webserver, scheduler, and one or more workers. You deploy DAGs to a Deployment, and you can have one or more Deployments within a Workspace.
```

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +2. Create a new folder for your Astro project:
Style guide addition!

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +- [Install Docker](https://www.docker.com/products/docker-desktop/) to use the full capabilities of the Astro CLI, including the ability to run Airflow locally and customize your Deployment's Airflow
```suggestion
- [Install Docker](https://www.docker.com/products/docker-desktop/) to use the full capabilities of the Astro CLI, including the ability to run Airflow locally and deploy the rest of your Astro project to Astro, including Python packages.
```

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +- You can only create Deployments in standard clusters, which are clusters that are shared with other Astro users.
Call it multi-tenant here?

2023-05-22 04:24 UTC, paolaperaza commented on astro/create-first-dag.md
> +- Schedule a call with your point of contact from Astronomer.
I'd just cut these bullet points to make it shorter -- just say "contact sales" include email address (ask @ElanDWeiner)

2023-05-22 19:22 UTC, merged