Enterprise alerts
astronomer/docs pull request #224
Opened 2021-01-26 21:14 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/121

This is a substantial PR. In addition to adding new instructions for how to configure Airflow and platform alerts, I moved a lot of content from Airflow Alerts into the Enterprise Alerts guide. I'm pretty confident that I've got technical accuracy, but still need help resolving two questions:

* When someone pushes a custom alert using `config.yaml`, does it have to be ordered alongside every other configuration they have? Or can they just add the alert to the doc by itself and then push that as you would any other config change? I'm still confused about whether you need to specify specific configs when you're updating a Helm chart that's not the Astronomer global config. 
*  How does [this Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml) factor into receiver setup? I can't tell if you need to configure this in addition to the configmap, or as an alternative to it. 

Adding @ianstanton for review as the docs partner for the Platform team, as well as because he was tagged in the initial issue.

2021-01-27 20:26 UTC, ianstanton commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +6. Open to your Airflow Deployment in the Astronomer UI, then go to the **Variables** tab and add the following Environment Variables using the **+Add** button:
```suggestion
6. Open your Airflow Deployment in the Astronomer UI, then go to the **Variables** tab and add the following Environment Variables using the **+Add** button:
```

2021-01-27 20:32 UTC, ianstanton commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +   AIRFLOW__SMTP__SMTP_HOST={Your SMTP host}
This is a bit nitpicky and up to you, but I prefer to format example variables like `<example-var>` vs `{Example var}`. I think they were already written in this format here. Just something to think about as you rework docs across the site.

2021-01-27 21:02 UTC, ianstanton requested changes

2021-01-27 21:02 UTC, ianstanton commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +  platform: {}
Should look like this if being referenced through top-level `config.yaml`:
```
alertmanager:
  receivers:
    platform: {}
    ...
```

2021-01-27 21:02 UTC, ianstanton commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> -You can read more about configuration options [here](https://prometheus.io/docs/alerting/configuration/).
Do we want to include the `customRoutes` option? https://github.com/astronomer/astronomer/blob/ceda02d7fd39b72c3544606a0faf429d3408c03c/charts/alertmanager/values.yaml#L51. I'm not sure.

2021-01-29 14:33 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +   AIRFLOW__SMTP__SMTP_HOST={Your SMTP host}
Ah yeah, good call. This was from the original doc and something I hadn't considered updating.

2021-01-29 14:50 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> -| `ContainerMemoryNearTheLimitInDeployment` | A container in your Airflow Deployment is near its memory quota; it's been using over 95% of its memory quota for over 60 minutes. | Either increase your
This content was moved into the Platform Alerts guide, since the general configuration/ concepts are the same. At the beginning of this guide, there's a distinction between Airflow alerts and Deployment/platform alerts and a link to the alternate guide.

> This guide focuses on configuring task and DAG-level alerts. For information on configuring platform and >Deployment alerts, read [Alerting in Astronomer Enterprise]
>(https://www.astronomer.io/docs/enterprise/v0.23/monitor/platform-alerts).

2021-01-29 15:01 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can configure [Alertmanager](https://prometheus.io/docs/alerting/configuration/) to send alerts to email, HipChat, PagerDuty, Pushover, Slack, OpsGenie, and more by editing the [Alertmanager Conf
Very nice catch!!

2021-01-29 15:07 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> -You can read more about configuration options [here](https://prometheus.io/docs/alerting/configuration/).
How popular is this option, and what can it do that the other receiver objects can't? If there's a lot of considerations or it's as "custom" as the name implies, I'm hesitant to put that info in a general guide like this.

2021-01-29 15:09 UTC, jwitz commented
Thanks for these comments @ianstanton ! I made changes based on your edits, and left one question / comment about CustomRoutes. Let me know what you think.

2021-01-29 15:11 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> -| `ContainerMemoryNearTheLimitInDeployment` | A container in your Airflow Deployment is near its memory quota; it's been using over 95% of its memory quota for over 60 minutes. | Either increase your
I should also note that this won't be the case in the Cloud guides, as they can't configure these alerts in the same way. For that guide, I'll bring information about the Deployment alerts back into the Airflow Alerts guide.

2021-01-29 20:09 UTC, paolaperaza requested changes
@jwitz This is a hard one, thanks for taking it on. Dropped a few initial questions/comments in there!

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can configure [Alertmanager](https://prometheus.io/docs/alerting/configuration/) to send alerts to email, HipChat, PagerDuty, Pushover, Slack, OpsGenie, and more by editing the [Alertmanager Conf
Maybe add an extra but short descriptor to Alertmanager ConfigMap? Is it a file that was created by default? Where does it live? What else can it be used for?

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +To add a new receiver to Astronomer Enterprise, add the receiver object to your `config.yaml` file and push the changes to your platform as described in [Apply a Config Change](https://www.astronomer
To your installation?

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +The following table contains popular alerts that you might want to subscribe to:
Are these deployment-level alerts? Seems like a kinda weird transition from one type to the other

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +In addition to subscribing to Astronomer's built-in alerts, you can also create custom alerts and push them to your Astronomer platform.
Can these custom alerts be platform and deployment-level ones, or just platform? Maybe clarify if poss?

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can access the Prometheus & Alertmanager UIs that are deployed in the Astronomer platform using Kubectl to port forward. For example, the following commands can be used to access these UIs in the
In the AWS install doc it also looks like there's another set of prometheus "blackbox-exporter" pods? Maybe clarify that these pods are NOT the ones you need to specify in the commands above?

`astronomer-prometheus-blackbox-exporter-65f6c5f456-865h2`

(At least I think that's the case, but worth double checking)

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +After running these commands, a user in this namespace could go to `localhost:9090` or `localhost:9093` in their browser to access the UIs.
Would be great to get screenshots here

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can subscribe to platform alerts by editing the [Alertmanager ConfigMap](https://github.com/astronomer/astronomer/blob/release-0.23/charts/alertmanager/templates/alertmanager-configmap.yaml) via
Not sure what the solve is, but this sentence feels a little repetitive to the two above

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +The [Alertmanager Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml) contains a section where you can specify different alert receivers. For example, th
Define alert receiver?

2021-01-29 20:09 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +The [Alertmanager Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml) contains a section where you can specify different alert receivers. For example, th
```suggestion
The [Alertmanager Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml) contains a section where you can specify different alert receivers.

For example, the following configuration would trigger alerts with `critical` severity to appear in a specified Slack channel:
```

2021-02-03 14:58 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/07_apply-platform-config.md
> +> **Note:** If you're interested in upgrading Astronomer to a new version of the platform, read [Upgrade to a Patch Version](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-
I was trying to make it more generic here (one less thing to update per release) but I agree we should continue to specify patch.

2021-02-03 15:33 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can access the Prometheus & Alertmanager UIs that are deployed in the Astronomer platform using Kubectl to port forward. For example, the following commands can be used to access these UIs in the
You know, I was hoping the purpose of this section would become more clear as I continued to work in the doc, but now I'm not really sure why it's here at all. For one, how does Grafana actually manage the alert side of things? Isn't it just a visual representation of Prometheus data that has no effect on whether the alert actually fires?

In addition, the rest of this setup uses neither Prometheus nor Alertmanager UI. In that case, would it just be better to axe this and bring the contextual information about Prometheus up to Overview? That's what I went for in this latest edit, let me know what you think.

2021-02-03 15:34 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can access the Prometheus & Alertmanager UIs that are deployed in the Astronomer platform using Kubectl to port forward. For example, the following commands can be used to access these UIs in the
If the Alertmanager UI is the only place you can see the alerts after adding them via `config.yaml` we could have a "Validate metrics were added" step with this info.

2021-02-03 15:45 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can configure [Alertmanager](https://prometheus.io/docs/alerting/configuration/) to send alerts to email, HipChat, PagerDuty, Pushover, Slack, OpsGenie, and more by editing the [Alertmanager Conf
Tried doing this in my latest push!

2021-02-03 15:57 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can subscribe to platform alerts by editing the [Alertmanager ConfigMap](https://github.com/astronomer/astronomer/blob/release-0.23/charts/alertmanager/templates/alertmanager-configmap.yaml) via
I made a slightly major edit on this by removing any mention of the ConfigMap. If admins never touch this file themselves (they only configure the Helm chart), then I think it's OK to abstract it away. Instead, I used this space to be more specific about what receivers are and why they're necessary for alerting.

2021-02-03 15:57 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +The [Alertmanager Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml) contains a section where you can specify different alert receivers. For example, th
See comment above

2021-02-03 16:54 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +To add a new receiver to Astronomer Enterprise, add the receiver object to your `config.yaml` file and push the changes to your platform as described in [Apply a Config Change](https://www.astronomer
Oof, I'm not quite ready to make a call on this yet. Gonna keep it as `platform` now to be consistent with this guide, as well as the Apply a Config Change guide.

2021-02-03 16:57 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +In addition to subscribing to Astronomer's built-in alerts, you can also create custom alerts and push them to your Astronomer platform.
Hopefully this is clarified in my new `Anatomy of an Alert` section

2021-02-03 16:58 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +The following table contains popular alerts that you might want to subscribe to:
Tried reworking this section in my latest commit - realized that you don't really subsribe to specific alerts, only alert types via receivers. 

Do you think it's worth adding a `severity` column to these tables?

2021-02-03 17:13 UTC, jwitz commented
Phew, I think this is ready for another review @paolaperaza. After further research, I rewrote substantial portions of the alerts guide to be more accurate/ focused. Though the overview section is longer, I think it now better illuminates how alerts actually make it out of the platform. I also restructured things in a way so that people begin with an understanding of alerts, then move to understanding receivers and how to configure those.

Should have responded to other little changes in the comments of the file, but let me know if there's anything you need additional clarification on.

2021-02-10 05:17 UTC, paolaperaza reviewed
Some additional comments from a second view! Thanks @jwitz - I'll check back on this again once you do another pass. Looks good.

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +This guide focuses on configuring task and DAG-level alerts. For information on configuring platform and Deployment alerts, read [Alerting in Astronomer Enterprise](https://www.astronomer.io/docs/ent
```suggestion
This guide focuses on configuring task and DAG-level alerts. For information on configuring platform and Deployment alerts, read [Alerting on Astronomer Enterprise](https://www.astronomer.io/docs/enterprise/v0.23/monitor/platform-alerts).
```

Alerting on?

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +- Deployment-level alerts notify you when the health of an Airflow Deployment is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
```suggestion
- Deployment-level alerts notify you when the health of your Airflow Deployment on Astronomer is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +1. [Create a SendGrid Account](https://signup.sendgrid.com). When you create an account, be prepared to disclose some standard information about yourself and your organization.
```suggestion
1. [Create a SendGrid account](https://signup.sendgrid.com). When you create an account, be prepared to disclose some standard information about yourself and your organization.
```

Should these not be capitalized now that they're not headers?

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +3. Create a Key Using SendGrid's Web API. In SendGrid, go to **Email API** > **Integration Guide**. Follow the steps to generate a new API key using SendGrid's Web API and cURL.
```suggestion
3. Create a key using SendGrid's web API. In SendGrid, go to **Email API** > **Integration Guide**. Follow the steps to generate a new API key using SendGrid's Web API and cURL.
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +5. Open your Airflow Deployment in the Astronomer UI and go to the **Variables** tab, then add the following Environment Variables using the **+Add** button:
```suggestion
5. Open your Airflow Deployment in the Astronomer UI and go to the **Variables** tab. Then, add the following Environment Variables using the **+Add** button:
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +navTitle: "Enterprise Alerts"
Platform Alers too much?

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +You can use two built-in alerting solutions for monitoring the health of your Astronomer platform:
```suggestion
You can use two built-in alerting solutions for monitoring the health of your Astronomer installation:
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +Alertmanager users [receivers](https://prometheus.io/docs/alerting/latest/configuration/#receiver) to integrate with different messaging platforms. To begin sending notifications for alerts, you firs
```suggestion
Alertmanager uses [receivers](https://prometheus.io/docs/alerting/latest/configuration/#receiver) to integrate with different messaging platforms. To begin sending notifications for alerts, you first need to define `receivers` in YAML using the [Alertmanager Helm chart](https://github.com/astronomer/astronomer/blob/master/charts/alertmanager/values.yaml).
```

Typo?

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +For more information on building and configuring receivers, read the [Prometheus documentation](https://prometheus.io/docs/alerting/configuration/).
```suggestion
For more information on building and configuring receivers, refer to [Prometheus documentation](https://prometheus.io/docs/alerting/configuration/).
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +### Push alert receivers to your platform
```suggestion
### Push alert receivers to your installation
```

Assuming we're standardizing on this?  👀

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +To add a new receiver to your Astronomer platform, add your receiver configuration to your `config.yaml` file and push the changes to your installation as described in [Apply a Config Change](https:/
```suggestion
To add a new receiver to Astronomer, add your receiver configuration to your `config.yaml` file and push the changes to your installation as described in [Apply a Config Change](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/apply-platform-config). The receivers you add must be specified in the same order and format as they appear in the Alertmanager Helm chart. Once you push the alerts, they are automatically added to the [Alertmanager ConfigMap](#https://github.com/astronomer/astronomer/blob/release-0.23/charts/alertmanager/templates/alertmanager-configmap.yaml).
```

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +## Create Custom Alerts
Ah to some extent wasn't sure that the section above was about subscribing to built-in alerts versus creating new ones (given the receiver section etc.) This may well be a "You didn't read this closely enough", but maybe there's room to be more explicit?

2021-02-10 05:17 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +Refer to the following tables for some of the most common alerts that you might receive from your Astronomer platform.
Following tables seems a little off for some reason since the tables are not immediately below - maybe just, `Refer to the breakdown below for some of the most common...`?

2021-02-10 15:11 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +- Deployment-level alerts notify you when the health of an Airflow Deployment is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
I think "On Astronomer Enterprise" is carried over from the intro sentence into these bullets - including it again here seems redundant. Also since this is Enterprise, it's likely that readers will have more than one Deployment to manage which is why I went with "an" over "your".

2021-02-10 15:18 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +5. Open your Airflow Deployment in the Astronomer UI and go to the **Variables** tab, then add the following Environment Variables using the **+Add** button:
Reworded this slightly

2021-02-10 15:20 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +navTitle: "Enterprise Alerts"
Too little I'd say, since we also mention Deployment alerts here.

2021-02-10 15:20 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +Alertmanager users [receivers](https://prometheus.io/docs/alerting/latest/configuration/#receiver) to integrate with different messaging platforms. To begin sending notifications for alerts, you firs
Nice catch

2021-02-10 15:35 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +## Create Custom Alerts
I changed "Configure Alertmanager" to "Subscribe to Built-In Alerts", because when people are reading this they're not thinking "How do I configure Alertmanager?" They're thinking "How do I subscribe to alerts?"

2021-02-10 15:46 UTC, jwitz commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +Refer to the following tables for some of the most common alerts that you might receive from your Astronomer platform.
Tried rewording this a bit.

2021-02-11 22:11 UTC, ianstanton requested changes

2021-02-11 22:11 UTC, ianstanton commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +customRoutes: {}
This should look like:
```
alertmanager:
  customRoutes:
  ...
```

2021-02-11 22:11 UTC, ianstanton commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +```
```suggestion
```yaml
prometheus:
  additionalAlerts:
    # Additional rules for the 'platform' alert group
    # Provide as a block string in yaml list form
    platform:
      - alert: ExamplePlatformAlert
        # If greater than 10% task failure
        expr: count(rate(airflow_scheduler_heartbeat{}[1m]) <= 0) > 2
        for: 5m
        labels:
          tier: platform
          severity: critical  
        annotations:
          summary: {{ printf "%q" "{{value}} airflow schedulers are not heartbeating." }}
          description: If more than 2 Airflow Schedulers are not heartbeating for more than 5 minutes, this alert fires.
```
```

2021-02-11 22:11 UTC, ianstanton commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> -You can read more about configuration options [here](https://prometheus.io/docs/alerting/configuration/).
Saw you added this, thanks

2021-02-11 22:12 UTC, ianstanton commented
Adding @pritt20 as reviewer as he also has first hand experience with this!

2021-04-20 13:54 UTC, jwitz commented
Hi @jpweber , since Ian is no longer on the platform team would you be able to review this doc change for technical accuracy? It's an overhaul of our guidance on implementing Airflow and platform alerts.

2021-04-21 13:22 UTC, jpweber approved these changes
Other than the one note I left the rest looks good to me.

2021-04-21 13:22 UTC, jpweber commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +These alerts fire based on metrics collected from the KubeAPI by Prometheus. If the conditions of an alert are met, [Prometheus Alertmanager](https://prometheus.io/docs/alerting/alertmanager) handles
These aren't only from the Kubernetes API, the metrics are collected from a variety of services in the cluster. Maybe drop where they are collected from, or broaden the description

2021-04-21 15:40 UTC, paolaperaza approved these changes
Sweet! I'm less familiar with the details of setting up alerts, so assuming we've confirmed that this is all technically sound this looks awesome to me. A few minor suggestions - nothing deal breaking. Good work, @jwitz!

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +- Deployment-level alerts notify you when the health of an Airflow Deployment is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
Agreed with this now looking back at it!

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +- Platform-level alerts notify you when a component of your Astronomer platform is unhealthy, such as Elasticsearch, Astronomer's Houston API, or your Docker Registry.
```suggestion
- Airflow task and DAG-level alerts that notify you via email when an Airflow task or DAG fails, succeeds, or retries.
- Deployment-level alerts that notify you when the health of an Airflow Deployment is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
- Platform-level alerts that notify you when a component of your Astronomer platform is unhealthy, such as Elasticsearch, Astronomer's Houston API, or your Docker Registry.
```

For some reason the transition here kept sounding off to me, maybe because we introduce these bullet points as "solutions" - and I'm reading each type of alert, and want to describe it as such - "task level alerts _that_ do x". Does that make sense?

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +1. [Create a SendGrid account](https://signup.sendgrid.com). When you create an account, be prepared to disclose some standard information about yourself and your organization.
```suggestion
1. [Create a SendGrid account](https://signup.sendgrid.com). Be prepared to disclose some standard information about yourself and your organization.
```

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +5. Open your Airflow Deployment in the Astronomer UI and go to the **Variables** tab, then add the following Environment Variables using the **+Add** button:
^Hm sentence still sounds run-on-y to me, so I'd still recommend this change. No big deal either way.

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +navTitle: "Enterprise Alerts"
Maybe "Astronomer Alerts"? Agreed on not "Platform Alerts" 🤷‍♀️

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +- Platform-level alerts notify you when a component of your Astronomer installation is unhealthy, such as Elasticsearch, Astronomer's Houston API, or your Docker Registry.
```suggestion
- Deployment-level alerts that notify you when the health of an Airflow Deployment is low or if any of Airflow's underlying components are underperforming, including the Airflow Scheduler.
- Platform-level alerts that notify you when a component of your Astronomer installation is unhealthy, such as Elasticsearch, Astronomer's Houston API, or your Docker Registry.
```

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +For example, adding the following receiver to `receivers.platformCritical` would cause platform alerts with a `critical` severity to appear in a the `#astronomer_platform_alerts` Slack channel:
```suggestion
For example, adding the following receiver to `receivers.platformCritical` would cause platform alerts with `critical` severity to appear in the `#astronomer_platform_alerts` Slack channel:
```

2021-04-21 15:40 UTC, paolaperaza commented on enterprise/v0.23/07_monitor/03_platform-alerts.md
> +### Push alert receivers to your platform
Or just "To Astronomer", which is the language we use here: https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/apply-platform-config

2021-04-21 15:44 UTC, jwitz commented
@ianstanton Jim and Paola have both approved this PR,  and you gave it a look a while back but didn't resolve your requested changes. It would be great you could give this a quick approval so that we could merge - thanks in advance!

2021-04-21 17:23 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/04_airflow-alerts.md
> +- Platform-level alerts notify you when a component of your Astronomer platform is unhealthy, such as Elasticsearch, Astronomer's Houston API, or your Docker Registry.
Changing this to `, which` instead of `that`, so that it's clear the focus is on the alerts rather than something that comes later in the process.

2021-04-21 18:07 UTC, ianstanton approved these changes

2021-04-21 18:12 UTC, merged