Update UI guide with note about 2.6 grid updates
astronomer/docs pull request #2240
Opened 2023-05-05 20:37 UTC by kentdanas

2023-05-05 20:50 UTC, lzdanski requested changes
Small editorial suggestion!

2023-05-05 20:50 UTC, lzdanski commented on learn/airflow-ui.md
> +In Airflow version 2.6 and later, the **Grid** view also includes an integrated graph view that shows a visualization of the tasks and dependencies in your DAG. If you select a task or task group ins
```suggestion
In Airflow version 2.6 and later, the **Grid** view includes an integrated graph visualization of the tasks and dependencies in your DAG. If you select a task or task group instance in the **Grid** column, the graph highlights and zooms to the selected task. You can also navigate complex DAGs using **Filter Tasks** and the minimap. 
```

Just some copyediting and a lil' technical writing convention: the **bold** formatting for buttons/tabs/menu titles in docs conventionally indicates a UI element. When docs are written in syntax that includes markup, the markup styling auto-bolds anything tagged with <ui-element> etc. We don't have that kind of detail in markdown, so it can be tricky knowing when to be specific about bolding text and using terms like "menu" or "drop down".

2023-05-05 22:32 UTC, kentdanas commented on learn/airflow-ui.md
> +In Airflow version 2.6 and later, the **Grid** view also includes an integrated graph view that shows a visualization of the tasks and dependencies in your DAG. If you select a task or task group ins
Oh good call, thanks for the details, had not thought about that before re: bolding.

2023-05-06 15:13 UTC, TJaniF approved these changes
LGTM :)

2023-05-08 13:12 UTC, lzdanski approved these changes

2023-05-08 15:22 UTC, merged