Astro Databricks provider tutorial
astronomer/docs pull request #2245
Opened 2023-05-08 14:48 UTC by TJaniF

Resolves: #1276

2023-05-09 23:42 UTC, kentdanas requested changes
Looks great so far! I'll go through this in more detail tomorrow and actually run the example, but I left some high level (somewhat random) initial comments. A lot of the historical stuff you can remove - still good to mention the community provider because it will be relevant for some folks, but we don't need nearly as much detail as we had before.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +Thanks to the open source [Astro Databricks provider](https://github.com/astronomer/astro-provider-databricks) you can create Databricks jobs from your Airflow DAG code with full integration and obse
```suggestion
The easiest way to orchestrate your Databricks notebooks from Airflow and execute them as Databricks Workflows is to use the open source [Astro Databricks provider](https://github.com/astronomer/astro-provider-databricks) which provides full observability and control from Airflow so you can manage your workflows from one place.
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +Additionally to the Astro Databricks provider created by Astronomer, a [Databricks provider](https://registry.astronomer.io/providers/databricks) created and maintained by the Airflow community is av
```suggestion
For orchestration of Databricks tools other than Databricks Workflows, the [Databricks provider](https://registry.astronomer.io/providers/databricks) created and maintained by the Airflow community is available. You can find information on the community-managed Databricks provider in the [Alternative ways to run Databricks with Airflow](#alternative-ways-to-run-databricks-with-airflow) section.
```
I _think_ that the astro databricks provider only works for databricks workflows, so this might be a good way to frame this. Unless I'm incorrect, in which case ignore this update.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +- Access to a Databricks workspace. See [Databricks' documentation](https://docs.databricks.com/getting-started/index.html) for instructions. You can use any workspace that has access to the [Databri
```suggestion
- Access to a Databricks workspace. See [Databricks' documentation](https://docs.databricks.com/getting-started/index.html) for instructions. You can use any workspace that has access to the [Databricks Workflows](https://docs.databricks.com/workflows/index.html) feature. You will need a user with permissions to create notebooks and Databricks jobs. You can use any underlying cloud service, and a [14-day free trial](https://www.databricks.com/try-databricks) is available.
```
We should capitalize "Workflows" in Databricks Workflows throughout since that's how they refer to it in their docs

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +- Access to an [object storage supported by the Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/supported_file.html). This tutorial uses an [AWS S3](https://aws.amazon.com/s3/) bu
```suggestion
- Access to an [object storage supported by the Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/supported_file.html). This tutorial uses an [AWS S3](https://aws.amazon.com/s3/) bucket.
```
Let's leave the note about making changes to the notebook code for the specific section where it's relevant.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +2. Add the [Astro Databricks provider package](https://github.com/astronomer/astro-provider-databricks) and the [Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/index.html), as we
```suggestion
2. Add the following packaged to your `requirements.txt` file. The [Astro Databricks provider package](https://github.com/astronomer/astro-provider-databricks) and the [Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/index.html) are used to load, transform, and analyze, the data. [seaborn](https://seaborn.pydata.org/) and [matplotlib](https://matplotlib.org/) are used to plot the results.
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +In you object storage solution create a new bucket. This tutorial uses AWS S3 and a bucket named `databricks-tutorial-bucket`.
```suggestion
Create a new bucket named `databricks-tutorial-bucket` in your object storage solution. In this tutorial we use AWS S3, but you can use any solution that is supported by the Astro SDK.
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +## Step 3: Prepare your Object storage
```suggestion
## Step 3: Prepare your object storage
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +2. Copy and paste the following code into the `join_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respe
```suggestion
2. Copy and paste the following code into the `join_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respective credentials. If you are using a different object storage than AWS S3 you will need to replace the code wrapped in `# --------- AWS S3 specific -------- #` comments with code connecting to your object storage.
```
Let's remove the sentence about databricks secrets from here and step 4 below and add a note at the end of the section saying something like for production you won't want to leave credentials in plain text, see databricks docs for secret management, etc.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +If a connection type isn't available, you might need to make it available by adding the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and running `astro dev resta
```suggestion
If the right connection type isn't available, you might need to add the [relevant provider package](https://registry.astronomer.io/) to `requirements.txt` and run `astro dev restart`.
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +1. In your `dags` folder, create a file called `renewable_analysis_dag`.
```suggestion
1. In your `dags` folder, create a file called `renewable_analysis_dag.py`.
```

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `cleanup` task using the [`aql.cleanup`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/cleanup.html) operator of the Astro Python SDK runs in parallel with the whole
I would put this bullet last, since it doesn't matter as much functionality wise :)

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `databricks_workflow` task group, created using the `DatabricksWorkflowTaskGroup` class, contains two tasks using the `DatabricksNotebookOperator`.
Let's add a bit more context here on what the astro databricks provider is doing that's "special" - e.g. what is it automating or making easier that you wouldn't be able to do with just the community provider.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +### Example - Using Airflow with Databricks
We can remove most of this. If this DAG exists on the registry (or there are any others that use the databricks provider operators), let's just link to that.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +## Alternative ways to run Databricks with Airflow
I think this whole part can be shortened into a couple paragraphs under this header. We definitely don't need to list all the specific hooks and operators since those lists are never up to date for long. Maybe we can focus on use cases where you might still use the community provider, and linking to relevant registry pages/docs/example DAGs.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +#### Error handling
You can cut all this - it's out of date now :)

For context, when I originally wrote this using Airflow + databricks together was a pretty new concept, so we talked a lot about the mechanics of how that interaction worked. I think it's less novel now, and we can assume this sort of nuance is something users would figure out themselves.

2023-05-09 23:42 UTC, kentdanas commented on learn/airflow-databricks.md
> +### Next steps
And we can definitely cut this and the out of date screenshot :)

2023-05-15 21:55 UTC, kentdanas approved these changes
A few minor comments throughout, but overall I think this is looking good! Let's move on to docs team review, and loop me in again if there are any relevant content questions.

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +The easiest way to orchestrate your Databricks notebooks from Airflow and execute them as Databricks Workflows is to use the open source [Astro Databricks provider](https://github.com/astronomer/astr
```suggestion
The easiest way to orchestrate your Databricks notebooks from Airflow and execute them as Databricks Workflows is to use the open source [Astro Databricks provider](https://github.com/astronomer/astro-provider-databricks), which provides full observability and control from Airflow so you can manage your Workflows from one place.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +For orchestration of actions in Databricks outside of Databricks Workflows, the [Databricks provider](https://registry.astronomer.io/providers/databricks) created and maintained by the Airflow commun
```suggestion
For orchestration of actions in Databricks outside of Databricks Workflows, you can use the [Databricks provider](https://registry.astronomer.io/providers/databricks) that is created and maintained by the Airflow community. See more in [Alternative ways to run Databricks with Airflow](#alternative-ways-to-run-databricks-with-airflow).
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +3. Define the following environment variables in the `.env` file in order to be able to serialize Astro Python SDK and Astro Databricks provider objects:
```suggestion
3. Define the following environment variable in your `.env` file. This allows you to serialize Astro Python SDK and Astro Databricks provider objects.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +This tutorial uses an Airflow DAG to orchestrate a Databricks job that joins datasets about shares of renewable electricity sources in different years for a selected country and calculates the percen
```suggestion
For this tutorial you will analyze two renewable energy datasets to calculate the percentage of electricity coming from solar, wind and hydro power for a given country over time.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +This tutorial uses parts of a dataset from a [Kaggle](https://www.kaggle.com/datasets/programmerrdai/renewable-energy) about renewable energy derived from [Our World in Data](https://ourworldindata.o
```suggestion
This data comes from a [Kaggle dataset](https://www.kaggle.com/datasets/programmerrdai/renewable-energy) about renewable energy derived from [Our World in Data](https://ourworldindata.org/renewable-energy) (License [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)).
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +2. Copy and paste the following code into the `join_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respe
```suggestion
2. Copy and paste the following code into the `join_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respective credentials.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +4. Copy and paste the following code into the `transform_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your
```suggestion
4. Copy and paste the following code into the `transform_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respective credentials.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +Please note that while you can provide your credentials to AWS in plain text to the notebook code above, this is highly discouraged, especially in a production environment. Databricks offers the poss
```suggestion
Providing your credentials to AWS in plain text in your notebook code is highly discouraged in production environments. See the Databricks documentation for recommended ways to securely [manage Secrets](https://docs.databricks.com/security/secrets/index.html) in Databricks for other options.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
Let's add another `info` box here with the info I removed about updating the notebook code if you're not using S3 for object storage.

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +4. Create a new connection named `aws_conn`. Make sure the credentials you add have permission to read and write from your S3 bucket. If you are using a different object storage you will need to adju
```suggestion
4. Create a new connection named `aws_conn`. Make sure the credentials you add have permission to read and write from your S3 bucket. If you are using a different object storage you will need to adjust this step.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +## Step 6: Write your Airflow DAG
```suggestion
## Step 6: Create your DAG
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +The DAG you'll write uses the Astro Databricks provider to create a Databricks Workflow from Airflow tasks referencing the Databricks notebooks you prepared in [Step 4](#step-4-create-databricks-note
```suggestion
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    This DAG consists of seven tasks and one task group:
```suggestion
    This DAG uses the Astro Databricks provider to create a Databricks Workflow that will run the two notebooks you prepared in [Step 4](#step-4-create-databricks-notebooks) with the following tasks:
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `in_tables` task uses the [`LoadFileOperator`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html) of the Astro Python SDK in order to load CSV files from
```suggestion
    - The `in_tables` task uses the Astro Python SDK [`LoadFileOperator`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html) to load CSV files from your local `include` directory to your relational database. This task is [dynamically mapped](dynamic-tasks.md), creating one mapped task instance for each file.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `select_countries` task uses the [`aql.transform`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/transform.html) decorator from the Astro Python SDK to run a SQL que
```suggestion
    - The `select_countries` task uses the Astro Python SDK [`aql.transform`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/transform.html) decorator to run a SQL query selecting the relevant rows for `COUNTRY` from each of the temporary tables created by the previous task. The result is stored in another temporary table.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `save_files_to_S3` task dynamically maps over the country subsets created by the previous task and creates one CSV file per table in your S3 bucket via the [ExportToFileOperator](https://as
```suggestion
    - The `save_files_to_S3` task uses the [ExportToFileOperator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) to dynamically maps over the country subsets created by the previous task and create one CSV file per table in your S3 bucket. This task uses the [`.map` function](dynamic-tasks.md#transform-outputs-with-map), a utility function that can transform XComArg objects.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - The `databricks_workflow` task group, created using the `DatabricksWorkflowTaskGroup` class, contains two tasks using the `DatabricksNotebookOperator`. This task group automatically creates a D
```suggestion
    - The `databricks_workflow` task group, created using the `DatabricksWorkflowTaskGroup` class, automatically creates a Databricks Workflow executing the Databricks notebooks specified in the individual DatabricksNotebookOperators. One of the biggest benefits of this setup is the use of a Databricks job cluster, allowing you to [significantly reduce your Databricks cost](https://www.databricks.com/product/pricing). The task group contains three tasks:
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +        - The task group provisions a Databricks `job_cluster` with the spec defined as `job_cluster_spec` and creates the Databricks job from the tasks within the task group. Creation of this cluste
```suggestion
        - The `launch` task, which is automatically generated by the task group, provisions a Databricks `job_cluster` with the spec defined as `job_cluster_spec` and creates the Databricks job from the tasks within the task group.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - Tthe `create_graph` task uses the `@aql.dataframe` decorator of the Astro Python SDK to create a graph of the `"SHW%"` column. The graph is saved as a `.png` file in the `include` directory.
```suggestion
    - The `create_graph` task uses the Astro Python SDK `@aql.dataframe` decorator to create a graph of the `"SHW%"` column. The graph is saved as a `.png` file in your `include` directory.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +    - Finally, the `cleanup` task using the [`aql.cleanup`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/cleanup.html) operator of the Astro Python SDK runs in parallel with
```suggestion
    - Finally, the `cleanup` task uses the Astro Python SDK [`aql.cleanup`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/cleanup.html) operator to clean up any temporary tables created by the Astro Python SDK when they are not needed anymore.
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +This section will explain Astro Databricks provider functionality in more depth. You can learn more about the Astro Databricks provider in the [provider documentation](https://astronomer.github.io/as
```suggestion
This section explains Astro Databricks provider functionality in more depth. You can learn more about the Astro Databricks provider in the [provider documentation](https://astronomer.github.io/astro-provider-databricks/).
```

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +### Additional parameters
Should this just be "Parameters"? "Additional" makes it sounds like we're showing ones that aren't used at all in the tutorial, but some of them are...

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +The Astro Databricks provider includes the possibility to repair a failed Databricks Workflow by making a repair request to the [Databricks Jobs API](https://docs.databricks.com/api-explorer/workspac
```suggestion
The Astro Databricks provider includes functionality to repair a failed Databricks Workflow by making a repair request to the [Databricks Jobs API](https://docs.databricks.com/api-explorer/workspace/jobs/repairrun). Databricks expects a single repair request for all tasks that need to be rerun in one cluster, this can be achieved via the Airflow UI by using the operator extra link **Repair All Failed Tasks**.
```
Can we rewrite the second sentence here to more clearly explain what the benefit is of using this functionality over rerunning a task the regular way? (I assume it's because using regular rerun would send separate requests and spin up separate clusters?)

2023-05-15 21:55 UTC, kentdanas commented on learn/airflow-databricks.md
> +The Astro Databricks provider is under active development and support for more Databricks task types is still being added. If you want to perform an action in your Databricks environment that is not
```suggestion
The Astro Databricks provider is under active development, and support for more Databricks task types is still being added. If you want to orchestrate an action in your Databricks environment that is not yet supported by the Astro Databricks provider such as [updating a Databricks repository](https://registry.astronomer.io/providers/apache-airflow-providers-databricks/versions/latest/modules/DatabricksReposUpdateOperator), check the [community-managed Databricks provider](https://registry.astronomer.io/providers/apache-airflow-providers-databricks/versions/latest) for relevant operators. 
```

2023-05-16 13:31 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! 

@jwitz ready for you :)

2023-05-19 23:51 UTC, jlaneve commented
Can we add more Databricks specific content (and potentially cut out some of the advanced Airflow logic like dynamic task mapping)? Here's a screenshot from the Databricks Provider README for reference.
![Screen Shot 2023-05-19 at 7 47 21 PM](https://github.com/astronomer/docs/assets/5252587/5d652508-5bf3-49d8-9505-fcbf118ac068)

2023-05-22 09:10 UTC, TJaniF commented
@jlaneve Thank your for the feedback! For the moment I added a section at the beginning of the tutorial highlighting the benefits of the Astro Databricks provider, hope I got all the reasoning right there 😄 .
I'll chat with Kenten about other changes later today, I think this might be a larger discussion of what content fits where. 😊

2023-05-22 18:47 UTC, kentdanas approved these changes
@TJaniF looks good, I'm okay with this extra section upfront addressing 'why' you would do this. Made a few edits to shorten the intro now that we're providing all this extra context.

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
>  [Databricks](https://databricks.com/) is a popular unified data and analytics platform built around [Apache Spark](https://spark.apache.org/) that provides users with fully managed Apache Spark clust
```suggestion
[Databricks](https://databricks.com/) is a popular unified data and analytics platform built around [Apache Spark](https://spark.apache.org/) that provides users with fully managed Apache Spark clusters and interactive workspaces.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +For orchestration of actions in Databricks outside of Databricks Workflows, you can use the [Databricks provider](https://registry.astronomer.io/providers/databricks) that is created and maintained b
```suggestion
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +In this tutorial you will learn how to use the Astro Databricks provider with an example use case analyzing renewable energy data.
```suggestion
This tutorial covers how to use the Astro Databricks provider for an example use case analyzing renewable energy data. It also discusses why you would want to [use Databricks with Airflow]() and [Alternative ways to run Databricks with Airflow](#alternative-ways-to-run-databricks-with-airflow) for if the Astro Databricks Provider doesn't fit your use case.
```
GitHub is being weird and won't let me, but let's add the link to the first section in there.

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +## Why to use Airflow with Databricks
```suggestion
## Why use Airflow with Databricks
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +Many data teams like to leverage Databricks' optimized Spark engine to run heavy work loads like machine learning models, data transformations, and data analysis. While Databricks offers some orchest
```suggestion
Many data teams leverage Databricks' optimized Spark engine to run heavy work loads like machine learning models, data transformations, and data analysis. While Databricks offers some orchestration via Databricks Workflows, it is limited in functionality and does not integrate with the rest of your data stack. Using a tool-agnostic orchestrator like Airflow gives you several advantages, like the ability to:
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- have a CI/CD process on your Workflow structures. Airflow DAGs are Python code, and can be [integrated with a variety of CI/CD tools](https://docs.astronomer.io/astro/ci-cd-templates/template-overv
```suggestion
- Use CI/CD to manage your workflow deployment. Airflow DAGs are Python code, and can be [integrated with a variety of CI/CD tools](https://docs.astronomer.io/astro/ci-cd-templates/template-overview) and [tested](testing-airflow.md).
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- repair single tasks in your Databricks Workflow. If a task fails, you can [re-run it](#repairing-a-databricks-workflow) without having to re-run the entire Workflow, saving valuable compute.
```suggestion
- Repair single tasks in your Databricks Workflow. If a task fails, you can [re-run it](#repairing-a-databricks-workflow) without having to re-run the entire Workflow, saving valuable compute.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- use [task groups](task-groups.md) within Databricks Workflows, enabling you to collapse and expand parts of larger Databricks Workflows visually.
```suggestion
- Use [task groups](task-groups.md) within Databricks Workflows, enabling you to collapse and expand parts of larger Databricks Workflows visually.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- leverage Airflow [cross-DAG dependencies](cross-dag-dependencies.md) to trigger Databricks Workflows from other DAGs in your Airflow environment, allowing for a data-driven architecture.
```suggestion
- Leverage Airflow [cross-DAG dependencies](cross-dag-dependencies.md) to trigger Databricks Workflows from other DAGs in your Airflow environment, allowing for a data-driven architecture.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- use familiar Airflow code as your interface to orchestrate Databricks notebooks as Workflows.
```suggestion
- Use familiar Airflow code as your interface to orchestrate Databricks notebooks as Workflows.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +- [inject parameters](#parameters) into your Databricks Workflow at the Workflow-level. These parameters can even be dynamic and retrieved at runtime from other Airflow tasks.
```suggestion
- [Inject parameters](#parameters) into your Databricks Workflow at the Workflow-level. These parameters can even be dynamic and retrieved at runtime from other Airflow tasks.
```

2023-05-22 18:47 UTC, kentdanas commented on learn/airflow-databricks.md
> +All while keeping the benefits of using Databricks Workflows like cheaper Workflow compute, being able to use CI/CD with code of your Notebooks and view Databricks Workflows from the Databricks UI.
```suggestion
```
I don't think this sentence is really needed here - but if you decide we do need to keep it, I would reword to stand alone so it isn't a "continuation" of the bullets above. e.g. "You can take advantage of these benefits all while...."

2023-05-23 06:31 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! :) 

@jwitz @lzdanski : Now this one is actually ready for you, now with an upfront section on why the Astro Databricks provider is so cool :)

2023-05-23 06:31 UTC, TJaniF commented on learn/airflow-databricks.md
> +All code in this tutorial can be found on [the Astronomer Registry] (INSERT REGISTRY LINK LATER).
Note as placeholder to put the registry link here once the registry team has done a dev to main :)

2023-05-23 06:31 UTC, TJaniF commented on learn/airflow-databricks.md
> +## Why to use Airflow with Databricks
Ahh I was going back and forth on that when writing it haha

2023-05-23 06:31 UTC, TJaniF commented on learn/airflow-databricks.md
> +All while keeping the benefits of using Databricks Workflows like cheaper Workflow compute, being able to use CI/CD with code of your Notebooks and view Databricks Workflows from the Databricks UI.
I agree it seems a little out of place. Am ok with removing it :)

2023-05-23 16:21 UTC, lzdanski reviewed
This is such a cool project for a tutorial! Again, just some style/voice feedback and general copyediting. I really want to tinker with the quickstart and these tutorials sometime soon :)

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +You can find several example DAGs using the community-managed Databricks provider on the [Astronomer Registry](https://registry.astronomer.io/providers/apache-airflow-providers-databricks/versions/la
```suggestion
You can find several example DAGs that use the community-managed Databricks provider on the [Astronomer Registry](https://registry.astronomer.io/providers/apache-airflow-providers-databricks/versions/latest).
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +If you only want to rerun specific tasks within your Workflow you can use the **Repair a single failed task** operator extra link on an individual task in the Databricks Workflow.
```suggestion
If you only want to rerun specific tasks within your Workflow, you can use the **Repair a single failed task** operator extra link on an individual task in the Databricks Workflow.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +Note that you cannot specifiy the same packages in the `notebook_packages` parameter of a DatabricksWorkflowTaskGroup and in the `notebook_packages` parameter of a task using the DatabricksNotebookOp
```suggestion
Note that you cannot specify the same packages in both the `notebook_packages` parameter of a DatabricksWorkflowTaskGroup and the `notebook_packages` parameter of a task using the DatabricksNotebookOperator in that same task group. Duplicate entries in this parameter cause an error in Databricks.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +- `job_clusters`: the job clusters to be used in this Workflow. You can provide the full `job_cluster_spec` as shown in the tutorial DAG.
```suggestion
- `job_clusters`: the job clusters for this Workflow to use. You can provide the full `job_cluster_spec` as shown in the tutorial DAG.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +- `notebook_packages`: a list of dictionaries defining Python packages to be installed in all notebook tasks in a Workflow.
```suggestion
- `notebook_packages`: a list of dictionaries defining Python packages to install in all notebook tasks in a Workflow.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +        - The `transform_data` task runs the `transform_data` notebook as the second part of the Databricks job. This notebook creates a new column in the data called `"SHW%"` which contains the sum
```suggestion
        - The `transform_data` task runs the `transform_data` notebook as the second part of the Databricks job. This notebook creates a new column in the data called `"SHW%"`, which contains the sum of the percentage of solar, wind, and hydro in your country's electricity supply.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +        - The `launch` task, which is automatically generated by the task group, provisions a Databricks `job_cluster` with the spec defined as `job_cluster_spec` and creates the Databricks job from
```suggestion
        - The `launch` task, which the task group automatically generates, provisions a Databricks `job_cluster` with the spec defined as `job_cluster_spec` and creates the Databricks job from the tasks within the task group.
```

2023-05-23 16:21 UTC, lzdanski commented on learn/airflow-databricks.md
> +    - The `databricks_workflow` task group, created using the `DatabricksWorkflowTaskGroup` class, automatically creates a Databricks Workflow executing the Databricks notebooks specified in the indi
```suggestion
    - The `databricks_workflow` task group, created using the `DatabricksWorkflowTaskGroup` class, automatically creates a Databricks Workflow that executes the Databricks notebooks you specified in the individual DatabricksNotebookOperators. One of the biggest benefits of this setup is the use of a Databricks job cluster, allowing you to [significantly reduce your Databricks cost](https://www.databricks.com/product/pricing). The task group contains three tasks:
```

2023-05-25 09:37 UTC, TJaniF reviewed
Thank you for the review @lzdanski ! 
I accepted all your suggestions and (hopefully) answered your questions :)

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +All code in this tutorial can be found on [the Astronomer Registry] (INSERT REGISTRY LINK LATER).
```suggestion
All code in this tutorial can be found on [the Astronomer Registry](https://registry.astronomer.io/dags/renewable_analysis_dag/versions/latest).
```

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +This tutorial takes approximately 1 hour to complete.
Haha, those are very rough. Basically 1h for longer ones, 30min for shorter ones so far. Most of the time the tutorial itself takes less but if you need to set up the tools from scratch that can be the bulk of the time like here with Databricks 😅

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +For this tutorial you will analyze two renewable energy datasets to calculate the percentage of electricity coming from solar, wind and hydro power for a given country over time.
I think this works well :)

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +This data comes from a [Kaggle dataset](https://www.kaggle.com/datasets/programmerrdai/renewable-energy) about renewable energy derived from [Our World in Data](https://ourworldindata.org/renewable-e
Thank you and that is awesome! The idea to try to use these types of examples came up in a climate ERG meeting 😄

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +2. Copy and paste the following code into the `join_data` notebook. You can divide the code into cells as you see fit. Make sure to replace the `ACCESS_KEY` and `SECRET_KEY` variables with your respe
Yes :)

2023-05-25 09:37 UTC, TJaniF commented on learn/airflow-databricks.md
> +5. Create a new connection named `db_conn`. Select the connection type and supplied parameters based on the data warehouse you are using. For a Postgres connection, enter the following information:
You just need a connection to a relational database. Any that is supported by the Astro Python SDK should work and I just picked Postgres as a neutral simple example and tested with it :)

2023-05-25 13:42 UTC, lzdanski approved these changes
This looks fantastic! I found one last typo, but going ahead and approving.

2023-05-25 13:42 UTC, lzdanski commented on learn/airflow-databricks.md
> +Many data teams leverage Databricks' optimized Spark engine to run heavy work loads like machine learning models, data transformations, and data analysis. While Databricks offers some orchestration w
```suggestion
Many data teams leverage Databricks' optimized Spark engine to run heavy workloads like machine learning models, data transformations, and data analysis. While Databricks offers some orchestration with Databricks Workflows, they are limited in functionality and do not integrate with the rest of your data stack. Using a tool-agnostic orchestrator like Airflow gives you several advantages, like the ability to:
```

2023-05-26 08:10 UTC, merged