CLI v1.15 docs and release notes
astronomer/docs pull request #2292
Opened 2023-05-16 18:30 UTC by sunkickr

docs and release notes for CLI v1.15

2023-05-16 18:43 UTC, collinmcnulty commented on astro/cli/release-notes.md
> +- Add new congfig file options `postgres.repository` and `postgres.tag`. You can use these to customize the postgres database used by the local astro container.
typo: config

2023-05-18 13:10 UTC, jwitz commented on astro/cli/astro-deployment-pool-copy.md
> +Copy Airflow pools from one Astro Deployment to another. Airflow pools are stored in the target Deployment's metadata database and appear in the Airflow UI.
```suggestion
---
sidebar_label: "astro deployment pool copy"
title: "astro deployment pool copy"
id: astro-deployment-pool-copy
description: Reference documentation for astro deployment  pool copy.
hide_table_of_contents: true
---


Copy Airflow pools from one Astro Deployment to another. Airflow pools are stored in the target Deployment's metadata database and appear in the Airflow UI.  
```

2023-05-18 14:31 UTC, manmeetkaur requested changes

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +This command only copies Airflow variables that were configured through the Airflow UI or otherwise stored in the Airflow metadata database.
```suggestion
This command only copies Airflow variables that were configured through the Airflow UI or Airflow REST API
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +This command only copies Airflow variables that were configured through the Airflow UI or otherwise stored in the Airflow metadata database.
there are only two ways where Airflow Variables are stored in metadata db, so i think it makes sense to clarify.

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +- `ASTRONOMER_KEY_ID`
Key ID and Secret are generated when we use Deployment API Keys - which we are phasing out. so does it make sense to say use API token and also link the page on how to generate
```suggestion
- `ASTRO_API_TOKEN`
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +After setting the variables, this command works for a Deployment without you having to manually authenticate to Astronomer. Astronomer recommends storing `ASTRONOMER_KEY_SECRET` as a secret before us
```suggestion
After setting the variables, this command works for a Deployment without you having to manually authenticate to Astronomer. Astronomer recommends storing `ASTRO_API_TOKEN` as a secret before using it to programmatically update production-level Deployments.
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +This command is recommended for automated workflows. To run this command in an automated process such as a [CI/CD pipeline](set-up-ci-cd.md), set the following OS-level environment variables in a way
```suggestion
This command is recommended for automated workflows. To run this command in an automated process such as a [CI/CD pipeline](set-up-ci-cd.md), you can generate Workspace API Token and set the following OS-level environment variable in a way that the Astro CLI can access them:
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +```sh
```suggestion
```bash
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-airflow-variable-copy.md
> +```sh
`bash` vs `sh` will properly colour code the comments

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-connection-copy.md
> +```
```suggestion
```bash
# copy connections stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv to a deployment with an ID of cl03oiq7d80402nwn7fsl3dcd
astro deployment connection copy --source-id cl03oiq7d80402nwn7fsl3dmv --target cl03oiq7d80402nwn7fsl3dcd

# copy connections stored in the Deployment "My Deployment" to another Deployment "My Other Deployment"
astro deployment connection copy --source-name="My Deployment" --target-name="My Other Deployment"
```
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-connection-create.md
> +astro deployment airflow-variable list
```suggestion
astro deployment connection list
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-connection-list.md
> +$ astro deployment connection list --deployment-name="My Deployment"
```suggestion
```bash
# List connections stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv
astro deployment connection list --deployment-id cl03oiq7d80402nwn7fsl3dmv

# List connections stored in the Deployment "My Deployment"
astro deployment connection list --deployment-name="My Deployment"
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-connection-update.md
> +astro deployment airflow-variable update
```suggestion
astro deployment connection update
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-connection-update.md
> +$ astro deployment connection update --deployment-name="My Deployment" --conn-id my-connection --conn-type http
```suggestion
```bash
# update connection called my-connection stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv
astro deployment connection update --deployment-id cl03oiq7d80402nwn7fsl3dmv --conn-id my-connection --conn-type http

# update connections stored in the Deployment "My Deployment"
astro deployment connection update --deployment-name="My Deployment" --conn-id my-connection --conn-type http
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-copy.md
> +$ astro deployment pool copy --source-name="My Deployment" --target-name="My Other Deployment"
```suggestion
```bash
# copy pools stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv to a deployment with an ID of cl03oiq7d80402nwn7fsl3dcd
astro deployment pool copy --source-id cl03oiq7d80402nwn7fsl3dmv --target cl03oiq7d80402nwn7fsl3dcd

# copy pools stored in the Deployment "My Deployment" to another Deployment "My Other Deployment"
astro deployment pool copy --source-name="My Deployment" --target-name="My Other Deployment"
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-create.md
> +astro deployment airflow-pool create
isn't it just pool here ?
```suggestion
astro deployment pool create
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-create.md
> +```
```suggestion
```bash
# create pool called my-pool stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv
astro deployment pool create --deployment-id cl03oiq7d80402nwn7fsl3dmv --name my-pool --slots 10

# create pool stored in the Deployment "My Deployment"
astro deployment pool create --deployment-name="My Deployment" --name my-pool --slots 10
```
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-list.md
> +astro deployment airflow-pool list
```suggestion
astro deployment pool list
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-list.md
> +```
```suggestion
```bash
# List pools stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv
astro deployment pool list --deployment-id cl03oiq7d80402nwn7fsl3dmv

# List pools stored in the Deployment "My Deployment"
astro deployment pool list --deployment-name="My Deployment"
```
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-deployment-pool-update.md
> +$ astro deployment pool update --deployment-name="My Deployment" --name my-pool --slots 10
```suggestion
```bash
# update pool called my-pool stored in the Deployment with an ID of cl03oiq7d80402nwn7fsl3dmv
astro deployment pool update --deployment-id cl03oiq7d80402nwn7fsl3dmv --name my-pool --slots 10

# update pools stored in the Deployment "My Deployment"
astro deployment pool update --deployment-name="My Deployment" --name my-pool --slots 10
```

2023-05-18 14:31 UTC, manmeetkaur commented on astro/cli/astro-dev-pytest.md
> +
```suggestion
```bash
# Specify env file at root of Astro project
astro dev pytest --env=myAlternativeEnvFile.env

# Specify an argument for pytest
astro dev pytest --args "–-cov-config path"
```

2023-05-18 16:43 UTC, sunkickr commented on astro/cli/astro-deployment-airflow-variable-create.md
> +This command is recommended for automated workflows. To run this command in an automated process such as a [CI/CD pipeline](set-up-ci-cd.md), set the following OS-level environment variables in a way
I agree that we should make the change in a separate PR

2023-05-18 16:59 UTC, sunkickr commented on astro/cli/release-notes.md
> +- You can now create a custom Docker/Podman compose file for your Astro project with the command `astro dev object export --compose-file`. After you modify the file, you can use it to start your proj
```suggestion
- You can now create a custom Docker/Podman compose file for your Astro project with the command `astro dev object export --compose`. After you modify the file, you can use it to start your project with `astro dev start --compose-file <compose-file-location>`.
```

2023-05-18 20:15 UTC, jwitz approved these changes

2023-05-18 20:16 UTC, jwitz commented
Nice one everyone! Gonna merge this now because it seems like Manmeet's remaining comments will be addressed in another PR.

2023-05-18 20:17 UTC, merged