Add info about Workflow API token in REST API
astronomer/docs pull request #2295
Opened 2023-05-17 10:06 UTC by manmeetkaur

2023-05-17 10:09 UTC, manmeetkaur commented
@jwitz I am inclined to address this [issue](https://github.com/astronomer/docs/issues/2283) as well in this, but not sure where will it fit. WDYT ?

2023-05-18 10:05 UTC, jwitz requested changes
The Workspace/ Org API token changes look good @manmeetkaur, but marking changes for some questions I had in the "Manage Deployments as code" content. 

If these were separate PRs, we'd be able to merge the API token content! In the future, it's better to have smaller, separate PRs so that we can review/ iterate quickly, especially if the content is not quite related like here.

2023-05-18 10:05 UTC, jwitz commented on astro/workspace-api-tokens.md
> +5. Click **Add**. A message appears on the bottom right corner "API token added".
```suggestion
5. Click **Add**.
```

2023-05-18 10:05 UTC, jwitz commented on astro/workspace-api-tokens.md
> +If you are using an Organization API token for a Workspace, you can remove it's access from the Workspace. This API token will lose it's access to the given Workspace.
```suggestion
```

2023-05-18 10:05 UTC, jwitz commented on astro/workspace-api-tokens.md
> +If you delete a Workspace API token, make sure that no existing CI/CD pipelines are using it. After it's deleted, an API token cannot be recovered. If you unintentionally delete an API token, create
```suggestion
If you delete a Workspace API token or remove an Organization API token from your Workspace, make sure that no existing CI/CD pipelines are using the token. After you delete a Workspace API token, it can't be recovered. If you unintentionally delete an API token, create a new one and update any CI/CD workflows that used the deleted API token.
```

2023-05-18 10:05 UTC, jwitz commented on astro/workspace-api-tokens.md
> +5. Optional. If the token scope if Workspace, then click on **Delete API Token**, enter `Delete`, and then click **Yes, Continue**.
```suggestion
4. If you're removing an Organization API token, click **Remove API token**. If you're deleting a Workspace API token, click **Delete API Token**, enter `Delete`, then click **Yes, Continue**.
```

2023-05-18 10:05 UTC, jwitz commented on astro/workspace-api-tokens.md
> +:::
```suggestion
To rotate an Organization API token with Workspace permissions, see [Organization API tokens](organization-api-tokens.md).
```

2023-05-18 10:14 UTC, manmeetkaur commented on astro/airflow-api.md
> +astro deployment inspect -n my-deployment-name -k metadata.webserver_url
the reason I changed it because `>` was also used in this page as a command. It was confusing to see `> <` side by side. I can put back the placeholder formatting.

2023-05-18 10:19 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +| You want to create a deployment using CI/CD | [Create a Deployment using Astro CLI](#create-a-deployment-using-astro-cli) |
for ephemeral deployments and for not wanting to maintain the extra information - simplicity I think. Most users use this over deployment file actually. I can add that to the detail.

2023-05-18 10:26 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +:::
@jwitz I mentioned explicitly about login, because I had Moon active reach out to me "how to use token to login". If we are defining a flow of all the steps, a new user does not know how to login using a token, then it is a problem. Do you see any harm in stating it? Also, our Astro CLI error messages are not great, if the user has logged out, it will say `workspace not found`.

2023-05-18 10:28 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +## Create a Deployment using Astro CLI
there are use-cases where this will be useful , if for example a user wants to create a new deployment for each branch that starts with `feature/`.

2023-05-30 16:37 UTC, jwitz commented on astro/airflow-api.md
> +Deployment API keys will soon be phased out in favor of Deployment-level API tokens. Astronomer recommends using Workspace tokens to reach the Airflow API until Deployment API tokens are released.
```suggestion
Deployment API keys will soon be phased out in favor of Deployment-level API tokens. Astronomer recommends only using Workspace API tokens until Deployment API tokens are released. 
```

2023-05-30 16:45 UTC, jwitz requested changes
Looking good in general @manmeetkaur ! Marking changes because I think we need to add some more general code examples for how to use tokens to call the API. How do users make the token accessible to the system calling the Airflow API? We should list those options here.

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +:::info
```suggestion
:::caution
```

2023-05-30 16:45 UTC, jwitz commented on astro/workspace-api-tokens.md
> +You can either create a new Workspace API token or add an existing Organization API token to a Workspace with appropriate permissions. You might want to add an Organization API token if your Organiza
```suggestion
There are two ways to use API tokens to interact with a Workspace:

- Create a new Workspace API token that's scoped only to a single Workspace.
- Add an existing [Organization API token](organization-api-tokens.md) to a Workspace and grant it Workspace permissions. You can add an Organization API token to multiple Workspaces.
```

2023-05-30 16:45 UTC, jwitz commented on astro/workspace-api-tokens.md
> +
```suggestion
You might want to add an Organization API token if your Organization API token only has Organization Member permissions, but you want to grant it Workspace Admin permissions for several Workspaces.

```

2023-05-30 16:45 UTC, jwitz commented on astro/workspace-api-tokens.md
> +
```suggestion
```

2023-05-30 16:45 UTC, jwitz commented on astro/workspace-api-tokens.md
> +
```suggestion
```

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +Workspace API tokens allow users to programmatically perform Workspace actions as well as Airflow API access.
```suggestion
Workspace API tokens allow users to programmatically perform Workspace actions, including accessing the Airflow API for Deployments in the Workspace.
```

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +Keep in mind the following when creating Workspace API tokens for Airflow REST API access:
```suggestion
Keep in mind the following when using Workspace API tokens to access the Airflow REST API:
```

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +Keep in mind the following when creating Workspace API tokens for Airflow REST API access:
This seem more like general benefits of the Workspace API tokens than things to "Keep in mind" when using them. I think we can remove this bulleted list.

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +Refer to [Workspace API tokens](workspace-api-tokens.md#create-a-workspace-api-token) to create a token.
Do we want to include a sample cURL request that uses the API token? What about how to make the token accessible to the system calling the Airflow API?

2023-05-30 16:45 UTC, jwitz commented on astro/airflow-api.md
> +Refer to [Organization API tokens](organization-api-tokens#create-an-organization-api-token) to create a token.
Do we want to include a sample cURL request that uses the API token?

2023-05-30 17:20 UTC, manmeetkaur commented on astro/airflow-api.md
> +Refer to [Organization API tokens](organization-api-tokens#create-an-organization-api-token) to create a token.
I think last time when we talked about this, we decided to have a re-look at this and other API token methods that can be used as a reference examples.

2023-05-30 17:23 UTC, manmeetkaur commented on astro/airflow-api.md
> +Keep in mind the following when creating Workspace API tokens for Airflow REST API access:
I think as a reference it is good, what do you think would be an alternate heading ?

2023-05-30 17:26 UTC, manmeetkaur commented on astro/airflow-api.md
> +Keep in mind the following when creating Organization API tokens for Airflow REST API access:
> Looking good in general @manmeetkaur ! Marking changes because I think we need to add some more general code examples for how to use tokens to call the API. How do users make the token accessible to the system calling the Airflow API? We should list those options here.

@jwitz I think we already discussed this during another PR review that we need in general a page that explains about generating tokens and using in API, that will remove a lot of repetitive code/info wherever we are referring to creating tokens. (I have forgotten the PR # but I remember David and you being part of it - the problem I face with long -pending PRs 🤣 )

2023-05-31 09:09 UTC, jwitz commented on astro/airflow-api.md
> +Refer to [Organization API tokens](organization-api-tokens#create-an-organization-api-token) to create a token.
Could we do something generalized? Like just saying "After you create a token, add it to the `Authorization` HTTP header in the following format:

```sh
curl -X GET <your-deployment-url>/api/v1/<api-endpoint>
curl -X GET https://<your-deployment-url>/api/v1/<api-endpoint> \
   -H 'Cache-Control: no-cache' \
   -H 'Authorization: Bearer <your-access-token>'
```

2023-05-31 09:09 UTC, jwitz commented on astro/airflow-api.md
> +Keep in mind the following when creating Workspace API tokens for Airflow REST API access:
I don't think we should really have it in this doc at all, because this isn't the info a user is interested in when they are trying to access the Airflow API. We should keep it short and straight to the point: 

"In most use cases, Astronomer recommends using Workspace API tokens to access the Airflow REST API. See [Workspace API tokens](workspace-api-tokens.md#create-a-workspace-api-token) to create a token.

"After you create a token, add it to the Authorization HTTP header in the following format:"

We can include the info about the benefits of the Workspace API tokens on the token documentation itself. Adding the list of benefits here is another barrier to the user learning how to access the Airflow API.

2023-05-31 09:09 UTC, jwitz commented on astro/airflow-api.md
> +Keep in mind the following when creating Organization API tokens for Airflow REST API access:
Ugh sorry I lost that thread.. I think we just need some basic info here about where to add the token to a request. We don't have to get crazy with _all_ the options or add too many code samples, but just like one simple instruction for how to use the token _after_ you've generated it.

2023-06-07 10:05 UTC, jwitz commented on astro/airflow-api.md
>  ## Step 2: Make an Airflow API request
```suggestion
## Step 3: Make an Airflow API request
```

2023-06-07 11:43 UTC, jwitz approved these changes

2023-06-07 11:43 UTC, jwitz commented on astro/airflow-api.md
> +You can follow the steps in [Create a Workspace API token](workspace-api-tokens.md#create-a-workspace-api-token) to create your token. You will need to save the token on creation in order to re-use i
```suggestion
Follow the steps in [Create a Workspace API token](workspace-api-tokens.md#create-a-workspace-api-token) to create your token. Make sure to save the token on creation in order to use it later in this setup.
```

2023-06-07 11:43 UTC, jwitz commented on astro/airflow-api.md
> +You can follow the steps in [Create a Orgaization API token](organization-api-tokens.md#create-an-organization-api-token) to create your token. You will need to save the token on creation in order to
```suggestion
Follow the steps in [Create a Orgaization API token](organization-api-tokens.md#create-an-organization-api-token) to create your token. Make sure to save the token on creation in order to use it later in this setup.
```

2023-06-07 11:43 UTC, jwitz approved these changes

2023-06-07 11:44 UTC, merged