Correct runtime end of maintenance dates
astronomer/docs pull request #2296
Opened 2023-05-17 10:44 UTC by feluelle

2023-05-17 10:48 UTC, feluelle commented
I did not ask, but I think the dates were incorrect. PTAL.

2023-05-17 17:21 UTC, jedcunningham requested changes

2023-05-17 17:21 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [8](runtime-release-notes.md#astro-runtime-800) | 2.6                    | April 30, 2023     | October 2024            |
```suggestion
| [8](runtime-release-notes.md#astro-runtime-800) | 2.6                    | April 30, 2023     | October 2023            |
```

This one was right. It's not an LTS release, it gets 6 months.

2023-05-17 17:21 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [7](runtime-release-notes.md#astro-runtime-700) | 2.5                    | December 3, 2022   | June 2024               |
```suggestion
| [7](runtime-release-notes.md#astro-runtime-700) | 2.5                    | December 3, 2022   | July 2023               |
```

This is the right date. This one also isn't LTS, but it gets 3 months after the next major (8) was released.

2023-05-17 17:21 UTC, jedcunningham commented on astro/runtime-version-lifecycle-policy.md
> +| [7](runtime-release-notes.md#astro-runtime-700) | 2.5                    | December 3, 2022   | June 2024               |
Don't feel bad though, having LTS and non-LTS in the "stable" table with no differentiation, then having a separate table of just "lts" is pretty confusing imo 🤷‍♂️. 4/5/6 all just happen to be LTS.

2023-05-18 20:15 UTC, jedcunningham approved these changes
I took the liberty to accept my suggestions since Felix is OOO for a bit.

2023-05-19 12:22 UTC, jwitz approved these changes
LGTM @jedcunningham. For my reference, is the support timeline for stable 7 months now, or have we extended 7's timeline for another reason?

2023-05-19 12:22 UTC, merged