Software 0.30.7 release notes
astronomer/docs pull request #2309
Opened 2023-05-18 19:51 UTC by jwitz

2023-05-18 20:45 UTC, danielhoherd commented on software_versioned_docs/version-0.30/release-notes.md
> +- You can now configure `kubernetes_apiservers_insecure_skip_verify` in the Prometheus Helm chart.
```suggestion
- You can now configure `prometheus.config.scrape_configs.kubernetes_apiservers.tls_config.insecure_skip_verify` in the Prometheus Helm chart.
```

2023-05-18 20:46 UTC, danielhoherd commented on software_versioned_docs/version-0.30/release-notes.md
> +- You can now set `certgenerator.extraAnnotations` in the Airflow Helm chart.
Do we normally mention airflow-chart configurations in this manner? The way a user would configure it would be to configure houston, not the airflow-chart directly.

2023-05-19 10:30 UTC, jwitz commented on software_versioned_docs/version-0.30/release-notes.md
> +- You can now set `certgenerator.extraAnnotations` in the Airflow Helm chart.
```suggestion
- You can now set `astronomer.houston.config.prometheus.certgenerator.extraAnnotations` in your `config.yaml` file.
```

2023-05-19 15:35 UTC, danielhoherd commented on software_versioned_docs/version-0.30/release-notes.md
> +- You can now set `astronomer.houston.config.prometheus.certgenerator.extraAnnotations` in your `config.yaml` file.
I got this path wrong last time. Here is the correction:
```suggestion
- You can now set `astronomer.houston.config.deployments.helm.prometheus.certgenerator.extraAnnotations` in your `config.yaml` file.
```

2023-05-24 17:09 UTC, rishkarajgi approved these changes

2023-05-25 06:41 UTC, Simpcyclassy approved these changes
LGTM

2023-05-25 06:47 UTC, Simpcyclassy requested changes
In improvements, we added message for deprecated acs

2023-05-25 08:17 UTC, Priyanka13Astro commented on software_versioned_docs/version-0.30/release-notes.md
> +- Fixed an issue where creating a git-sync-based Deployment through the Houston API would cause the Deployment to have a default sync interval of 1 second.
This is not part of 0.30.6, @rishkarajgi please confirm.

2023-05-25 09:23 UTC, rishkarajgi commented on software_versioned_docs/version-0.30/release-notes.md
> +- Fixed an issue where creating a git-sync-based Deployment through the Houston API would cause the Deployment to have a default sync interval of 1 second.
Git sync is a 0.31 feature so not included
cc: @jwitz

2023-05-25 09:31 UTC, rishkarajgi commented
@jwitz Could you please add the notes for the following issues as well

- https://github.com/astronomer/issues/issues/5608
- https://github.com/astronomer/issues/issues/4650
- https://github.com/astronomer/issues/issues/5555
- https://github.com/astronomer/issues/issues/5564
- https://github.com/astronomer/issues/issues/5514

2023-05-25 09:41 UTC, rishkarajgi commented on software_versioned_docs/version-0.30/release-notes.md
> +Release date: May 18, 2023
This will be updated to May 25, 2023

2023-05-25 11:03 UTC, jwitz commented on software_versioned_docs/version-0.30/release-notes.md
> +- Fixed a security vulnerability where credentials could be leaked from NGinx controller logs.
```suggestion
- Fixed a security vulnerability in logging.
```

2023-05-25 13:49 UTC, rishkarajgi commented on software_versioned_docs/version-0.30/release-notes.md
> +- All users other than System Admins can no longer create Deployments with Astronomer Certified images. The Software UI will show a warning message for Deployments currently running an Astronomer Cer
I think we can invert this

> The Software UI will now show a warning message for Deployments currently running a soon to be deprecated Astronomer Certified image. Only System Admins can create Deployments with Astronomer Certified images by setting the` deployments.enableSystemAdminCanCreateDeprecatedAirflows` to true

2023-05-25 15:29 UTC, rishkarajgi approved these changes
lgtm

2023-05-25 15:29 UTC, rishkarajgi approved these changes
lgtm

2023-05-26 09:46 UTC, jwitz commented on software_versioned_docs/version-0.30/release-notes.md
> +Release date: May 25, 2023
```suggestion
Release date: May 26, 2023
```

2023-05-26 10:06 UTC, Simpcyclassy approved these changes
I think we are good to release this.

2023-05-26 12:52 UTC, lzdanski approved these changes

2023-05-26 13:07 UTC, merged