Templates for Learn issues
astronomer/docs pull request #2325
Opened 2023-05-23 09:18 UTC by TJaniF

2023-05-23 16:45 UTC, kentdanas approved these changes
@TJaniF I think this looks great! Some very minor nit-picky comments, but honestly I'd say let's just try these and we can always make modifications later once we see how it's working.

2023-05-23 16:45 UTC, kentdanas commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      label: Due date
```suggestion
      label: Desired publish date
```

2023-05-23 16:45 UTC, kentdanas commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      description: For example, 'Q2 2023', '2/12/2023', 'Within the next month'
```suggestion
      description: For example, is there a particular release, relevant event, etc. that this should be coordinated with?
```

2023-05-23 16:45 UTC, kentdanas commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +name: Request new Learn content
Wondering if we should title this to include 'updated content', etc. It seems like the majority of the requests we get are basically for extra sections within an existing doc, so I want to make it clear to users that this is the form they should use for that, instead of the bug report.

2023-05-23 16:45 UTC, kentdanas commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +description: New content on an existing Airflow feature or behavior
```suggestion
description: New or updated content on an existing Airflow feature or use case
```

2023-05-24 12:34 UTC, TJaniF reviewed
Thank you @kentdanas !

@jwitz ready for you, I stole most of the fields from your templates :)

2023-05-31 13:19 UTC, jwitz requested changes
Adding a few thoughts here @TJaniF , lmk what you think! I'll take one more look before we merge

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-bug-report.yaml
> +description: Any request related to existing documentation that contains a bug or is misleading
Hm.. I don't know if we should have a separate bug fix template for Learn, especially if it's not all clear what Learn really encapsulates to an outside audience. Our current bug fix template doesn't discriminate by product, so I think that can cover Learn as well. The less choices someone has to make before they provide us with the fix info, the better.

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      label: Describe your Learn request. If you want to add information to an existing page, please provide the link to it!
```suggestion
      label: Describe your Learn request.
      description: If you want Astronomer to add information to an existing page, please provide the link to it here.
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +description: New or updated content on an existing Airflow feature or use case
```suggestion
description: Request new or updated [Learn](https://docs.astronomer.io/learn) content on an Apache Airflow feature or use case.
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +name: Request updates or new content in Learn
```suggestion
name: Request new Apache Airflow content in Learn
```
"Updates" could sound like we're asking a user for bug fix info

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +        - I am not sure where this best fits
Good call, we probably need a fallback option like this in the docs templates

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      label: Describe who the content is intended for, e.g. Airflow beginners, expert users...?
What decisions do you expect to make based on this answer? If you want to keep this, I think it's better to make it a list of options to select from.

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      description: For example, is there a particular release, relevant event, etc. that this should be coordinated with?
```suggestion
      description: Is there a particular release, relevant event, etc. that this should be coordinated with?
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      description: Airflow version in which the feature/behavior was added. Please provide for features which are upcoming.
```suggestion
      description: Airflow version in which the feature/behavior was added. Please provide for features which are not yet released.
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      placeholder: ex. 2.6.1
```suggestion
      placeholder: For example: Airflow 2.6.1
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      label: SME / technical reviewer
```suggestion
      label: Reviewer
```

2023-05-31 13:19 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +        - Add a previously not described Airflow feature or behavior to an existing page
```suggestion
        - New content for an undocumented or under-documented Airflow feature
```

2023-05-31 13:19 UTC, jwitz requested changes
Adding a few thoughts here @TJaniF , lmk what you think! I'll take one more look before we merge

2023-06-06 12:50 UTC, TJaniF reviewed
Thank you for the review @jwitz ! :) 

I accepted most suggestions and left two comments. :)

2023-06-06 12:50 UTC, TJaniF commented on .github/ISSUE_TEMPLATE/learn-bug-report.yaml
> +description: Any request related to existing documentation that contains a bug or is misleading
Good point yes, I'll remove it :)

2023-06-06 12:50 UTC, TJaniF commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +name: Request updates or new content in Learn
Hmm yeah there is that danger when using the term "update". The reason for the 'updates' there is because we get a lot of issues that are "hey xyz is outdated/ there is a better way of doing this now/ xyz should be added to this list" etc. 

So neither a bug in the sense that something does not work but also not really new content, at least in my mind "new" means a new tutorial or at least a new section in a guide 🤔 

How about "Request new Apache Airflow content or content additions in Learn" ? 

cc: @kentdanas

2023-06-06 12:50 UTC, TJaniF commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      label: Describe who the content is intended for, e.g. Airflow beginners, expert users...?
I was thinking for example if someone creates an issue "How to use Airflow with FancyTool" if they select beginner it would be more suited for a shorter integration tutorial, if they select expert for a use-case based example with a repository. 🤔 

But I am not fully convinced the question is necessary, I think most of the time we decide how to integrate the content anyways so... I am ok with removing the question for brevity, not sure I would have thought of it if it had not been there in the old template.

2023-06-06 14:37 UTC, kentdanas commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +name: Request updates or new content in Learn
Yeah....I agree most of the issues we get are "hey this part is outdated" or "hey can we add context on this additional thing here". However, the vast majority of these get raised to us in Slack and it's us that ends up creating the issue, so I wouldn't be too worried about people being confused here. Maybe we just keep it simple with Jake's suggestion, and can adjust later if needed.

2023-06-07 12:44 UTC, jwitz commented on .github/ISSUE_TEMPLATE/learn-new-content-template.yaml
> +      placeholder: For example, Airflow 2.6.1
```suggestion
```
Not sure we need a placeholder example at all tbh, knowing that this part of the form will only be used by experts that are in the know on future Airflow releases

2023-06-07 12:44 UTC, jwitz approved these changes
Just pushed a change to get the build to work, and now this LGTM!

2023-06-08 14:39 UTC, TJaniF reviewed
Thank you @jwitz ! Excited to see this in action :)

2023-06-08 14:40 UTC, merged