Add docs for jenkins custom cicd template
astronomer/docs pull request #2326
Opened 2023-05-23 18:45 UTC by pohek321

Did this for a customer awhile back, forgot to add it here in the official docs.

2023-05-23 18:57 UTC, lzdanski requested changes
These changes look good! I saw one place where we might want to add a sentence about where or how users can find their Deployment information and there's a markdown formatting syntax change for the codeblock that's needed.

2023-05-23 18:57 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +    <pre><code parentName="pre">{`pipeline {
```suggestion
```text
{`pipeline {
```

2023-05-23 18:57 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +    }`}</code></pre>
```suggestion
    }`}
    ```
```

2023-05-23 19:20 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +    Be sure to set the values for your API credentials as secret.
Would the single branch and custom use the same method to find the parameters? Is it just the cli - [`astro deployment inspect`](https://docs.astronomer.io/astro/cli/astro-deployment-inspect) or go to the deployment in the Cloud UI?

2023-05-23 20:16 UTC, pohek321 commented on astro/ci-cd-templates/jenkins.md
> +    <pre><code parentName="pre">{`pipeline {
These changes broke the CI/CD checks -- not sure what that `<pre>` tag does @lzdanski, maybe you could elaborate?

2023-05-23 20:21 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +    <pre><code parentName="pre">{`pipeline {
Absolutely! So with markdown syntax, it accepts both markdown and HTML markup. The declaration `<pre><code>` is a way to declare to the framework that we're using HTML for that section, not markdown. However, the build errors are being reported from line 241 in that file, which isn't from the changes you made. It looks like it's happy with our syntax, but not happy going back to using HTML for codeblocks. 

Can I tinker with it and push a change back to your branch?
<img width="1032" alt="Screenshot 2023-05-23 at 4 20 43 PM" src="https://github.com/astronomer/docs/assets/25642903/81864815-9504-4a88-9572-042a92260f74">

2023-05-23 20:33 UTC, pohek321 commented on astro/ci-cd-templates/jenkins.md
> +    Be sure to set the values for your API credentials as secret.
@lzdanski how to find these values is already defined in the same page under the [prerequisite section](https://docs.astronomer.io/astro/ci-cd-templates/jenkins?tab=multibranch#prerequisites)

2023-05-24 10:16 UTC, jwitz commented
@lzdanski Sorry this is a niche part of the site that I'd hoped you never had to encounter. Jenkins is one of the few pipeline tools left that requires users to `curl` specific versions of the CLI in the pipeline, rather than always using latest. We've had to use sitewide environment variables to ensure that these pipelines are always updated when we release a new version of the Astro CLI.

A negative side effect of this implementation is that any raw code starting with `$` needs to be formatted so that Docusaurus doesn't try to interpret it as a non-existent environment variable. You'll see I made a few additional variables to reformat what was before a raw `$`-led value. @pohek321 Can you check the preview site to make sure that all of the indentation appears as you'd hoped?

2023-05-24 11:11 UTC, lzdanski commented on astro/ci-cd-templates/jenkins.md
> +    This `Jenkinsfile` triggers a code push to Astro every time a commit or pull request is merged to the `main` branch of your repository.
```suggestion
This `Jenkinsfile` triggers a code push to Astro every time a commit or pull request is merged to the `main` branch of your repository.
```

This is going to sound strange, but did you indent with tabs or spaces? Sometimes Markdown syntax has tab = plain text and 4 spaces = code formatting. I haven't seen it pop up in a while, but it looks like that's happening here. We can either remove the indent or you can try using a tab (which for some reason Github suggestions won't allow me to do).

2023-05-24 21:46 UTC, pohek321 commented on astro/ci-cd-templates/jenkins.md
> +    This `Jenkinsfile` triggers a code push to Astro every time a commit or pull request is merged to the `main` branch of your repository.
Not sure, I'll commit up a change with this commit suggestion though

2023-05-24 21:56 UTC, pohek321 commented
> @lzdanski Sorry this is a niche part of the site that I'd hoped you never had to encounter. Jenkins is one of the few pipeline tools left that requires users to `curl` specific versions of the CLI in the pipeline, rather than always using latest. We've had to use sitewide environment variables to ensure that these pipelines are always updated when we release a new version of the Astro CLI.
> 
> A negative side effect of this implementation is that any raw code starting with `$` needs to be formatted so that Docusaurus doesn't try to interpret it as a non-existent environment variable. You'll see I made a few additional variables to reformat what was before a raw `$`-led value. @pohek321 Can you check the preview site to make sure that all of the indentation appears as you'd hoped?

@jwitz yeah, it looks good!

2023-05-25 09:41 UTC, jwitz approved these changes

2023-05-25 09:50 UTC, merged