Draft MLflow tutorial
astronomer/docs pull request #2348
Opened 2023-05-30 12:04 UTC by TJaniF

2023-06-08 18:40 UTC, kentdanas requested changes
@TJaniF this is a great simple example! Requesting changes because I think we need to add more context around what you might want to do with MLflow + Airflow and the different options for doing so and when to choose each one. Reading through this now, going through all the steps I get a little lost on why I need 3 different ways to use the tools together, what the provider is, and why sometimes I might want to use the `mlflow` package directly like you do in the second task. 

Maybe that looks like adding a few sentences to the intro on what the provider contains/context on the integration. And then if needed (it might not be) another section for 'How it works' or provider overview or something like that that explains when to use the provider vs when not to. Also somewhere we should make clear that the provider contains more operators than we're showing here (we don't need to list all of them explicitly, because I think those lists are hard to keep up to date, but should at least point to the repo). Let me know if you want to chat about any of this!

2023-06-14 19:38 UTC, kentdanas approved these changes
This looks good @TJaniF, I think it's much clearer now with the additional context. Minor comments throughout, but otherwise I'm happy with the content here and you can loop in docs team.

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +If you are using a remote MLflow instance, you need to enter the MLflow instance URL as a **Host** and provide your username to the **Login** and your password to the **Password** field. To run your
```suggestion
If you are using a remote MLflow instance, enter your MLflow instance URL as the **Host** and your username and password as the **Login** and **Password** fields in the connection. If you are running your MLflow instance via Databricks, provide your Databricks URL to the **Host** field, enter the string `token` in the **Login** field and your [Databricks personal access token](https://docs.databricks.com/dev-tools/auth.html#personal-access-tokens-for-users) in the **Password** field.
```

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +    - The `scale_features` task shows a way to use MLflow and Airflow without the MLflow provider. In this task the [mlflow](https://pypi.org/project/mlflow/) package is used directly with [scikit-le
```suggestion
    - The `scale_features` task uses the [mlflow](https://pypi.org/project/mlflow/) package in a Python decorated task with [scikit-learn](https://pypi.org/project/scikit-learn/) to log information about the scaler to MLflow. This functionality is not included in any modules of the MLflow provider, so a custom Python function is the best way to implement this task.
```

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +    - The `create_registered_model` task shows how to use the [CreateRegisteredModelOperator](https://github.com/astronomer/airflow-provider-mlflow/blob/main/mlflow_provider/operators/registry.py) to
```suggestion
    - The `create_registered_model` uses the [CreateRegisteredModelOperator](https://github.com/astronomer/airflow-provider-mlflow/blob/main/mlflow_provider/operators/registry.py) to register a new model in your MLflow instance.
```

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +Congratulations! You used MLflow and Airflow together in three different ways. Learn more about other operators and hooks in the MLflow Airflow provider in the [documentation](https://github.com/astr
If we don't publish documentation for MLFlow provider before this tutorial gets published (likely will not...), let's update "documentation" to "the official repo" or something like that. Don't want to over-promise here...

2023-06-14 19:38 UTC, kentdanas commented on code-samples/dags/airflow-mlflow/mlflow_tutorial_dag.py
> +directly log metrics and parameters to MLFlow in a TaskFlow task via the mlflow Python package and
```suggestion
directly log metrics and parameters to MLFlow in a TaskFlow task via the mlflow Python package, and
```

2023-06-14 19:38 UTC, kentdanas commented on code-samples/dags/airflow-mlflow/mlflow_tutorial_dag.py
> +    # 2. Use a mlflow.sklearn autologging in a TaskFlow task
```suggestion
    # 2. Use mlflow.sklearn autologging in a TaskFlow task
```

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +description: "How to produce to use the MLflow Airflow provider"
I'm not sure what to suggest here, but this description seems off....guessing it got "half updated" at some point?

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +- Using an MLflow hook from the MLflow Airflow provider: The MLflow provider contains several [Airflow hooks](what-is-a-hook.md) that allow you to connect to MLflow using credentials stored in an Air
```suggestion
- Using an MLflow hook from the MLflow Airflow provider: The MLflow provider contains several [Airflow hooks](what-is-a-hook.md) that allow you to connect to MLflow using credentials stored in an Airflow connection. You can use these hooks if you need to perform actions in MLflow for which no dedicated operator exists. You can also use these hooks to create your own [custom operators](airflow-importing-custom-hooks-operators.md).
```

2023-06-14 19:38 UTC, kentdanas commented on learn/airflow-mlflow.md
> +- Using the MLflow Python package directly in a [@task decorated task](airflow-decorators.md): When performing ML related actions in an Airflow task such as feature engineering you can track metrics
```suggestion
- Using the MLflow Python package directly in a [@task decorated task](airflow-decorators.md): The MLflow Python package contains functionality like tracking metrics and artifacts with [`mlflow.sklearn.autolog`](https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html). You can use this package to write custom Airflow tasks for ML-related actions like feature engineering.
```

2023-06-14 19:38 UTC, kentdanas commented on static/img/guides/mlflow_dags.png
This is super nit-picky, but shouldn't all these screenshots go in the /integrations folder, instead of /guides?

2023-06-14 19:38 UTC, kentdanas commented on static/img/guides/possum_tails.png
So excited for this use case to get published 😍 Let's move this screenshot to the /examples folder and rename with the filename preface (that can come later if we don't know it yet...)

2023-06-15 09:34 UTC, TJaniF reviewed
Thank you @kentdanas!

@jwitz and @lzdanski ready for you! Just one small note there are some image files in this PR that arent used by the tutorial, this is because I PR this tutorial with a different example initially and then changed it to be more straightforward for the tutorial but the initial example will be PRed as a use case shortly, where I'll need those images anyways :)

2023-06-15 09:34 UTC, TJaniF commented on static/img/guides/mlflow_dags.png
That is a good question! I think currently all images that are shown in integrations tutorials are in the guides folder, and the /integrations folder has the logos of the tools? But yeah it would probably make sense to move the logos to a /logos folder and then fill integrations with these images 🤔 

cc @jwitz and @lzdanski would it make sense for me to make a PR that cleans up/ sorts the img folders relating to learn? Is there something that could break through that?

2023-06-16 09:43 UTC, jwitz approved these changes
Looks great @TJaniF ! Double check to see if there's any images we can remove, since they're not in the doc anymore

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +[MLflow](https://mlflow.org/) is a commonly used tool for tracking and managing machine learning models. It can be used together with Airflow for ML orchestration (MLOx), leveraging both tools for wh
```suggestion
[MLflow](https://mlflow.org/) is a popular tool for tracking and managing machine learning models. It can be used together with Airflow for ML orchestration (MLOx), leveraging both tools for what they do best. In this tutorial, you’ll learn about three different ways you can use MLflow with Airflow.
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +If you are already familiar with MLflow and Airflow and want to get a use case up and running, check out this [quickstart repository](https://github.com/astronomer/learn-airflow-mlflow-tutorial) whic
```suggestion
If you're already familiar with MLflow and Airflow and want to get a use case up and running, clone the [quickstart repository](https://github.com/astronomer/learn-airflow-mlflow-tutorial) to automatically start up Airflow and local MLflow and MinIO instances. After you clone the repository, configure the local MLflow connection as shown in [Step 2](#step-2-configure-your-airflow-connection) of this tutorial, and run the three example DAGs.
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +The DAG in this tutorial shows three different ways Airflow can interact with MLFlow:
```suggestion
The DAG in this tutorial shows three different ways Airflow can interact with MLflow:
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +- Using an MLflow operator from the [MLflow Airflow provider](https://github.com/astronomer/airflow-provider-mlflow): The MLflow provider contains several operators that abstract over common actions
```suggestion
- Use an MLflow operator from the [MLflow Airflow provider](https://github.com/astronomer/airflow-provider-mlflow). The MLflow provider contains several operators that abstract over common actions you might want to perform in MLflow, such as creating a deployment with the [CreateDeploymentOperator](https://github.com/astronomer/airflow-provider-mlflow/blob/main/mlflow_provider/operators/deployment.py) or running predictions from an existing model with the [ModelLoadAndPredictOperator](https://github.com/astronomer/airflow-provider-mlflow/blob/main/mlflow_provider/operators/pyfunc.py). 
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +- Using an MLflow hook from the MLflow Airflow provider: The MLflow provider contains several [Airflow hooks](what-is-a-hook.md) that allow you to connect to MLflow using credentials stored in an Air
```suggestion
- Use an MLflow hook from the MLflow Airflow provider. The MLflow provider contains several [Airflow hooks](what-is-a-hook.md) that allow you to connect to MLflow using credentials stored in an Airflow connection. You can use these hooks if you need to perform actions in MLflow for which no dedicated operator exists. You can also use these hooks to create your own [custom operators](airflow-importing-custom-hooks-operators.md).
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +- Using the MLflow Python package directly in a [@task decorated task](airflow-decorators.md): The MLflow Python package contains functionality like tracking metrics and artifacts with [`mlflow.sklea
```suggestion
- Use the MLflow Python package directly in a [@task decorated task](airflow-decorators.md). The MLflow Python package contains functionality like tracking metrics and artifacts with [`mlflow.sklearn.autolog`](https://mlflow.org/docs/latest/python_api/mlflow.sklearn.html). You can use this package to write custom Airflow tasks for ML-related actions like feature engineering.
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +1. Run `astro dev start` in your Astro project to start up Airflow and navigate to the Airflow UI at `localhost:8080`.
```suggestion
1. Run `astro dev start` in your Astro project to start up Airflow and open the Airflow UI at `localhost:8080`.
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +    - **Connection Type**: `HTTP`.
```suggestion
    - **Connection ID**: `mlflow_default`
    - **Connection Type**: `HTTP`
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +If you are using a remote MLflow instance, enter your MLflow instance URL as the **Host** and your username and password as the **Login** and **Password** fields in the connection. If you are running
```suggestion
If you are using a remote MLflow instance, enter your MLflow instance URL as the **Host** and your username and password as the **Login** and **Password** in the connection. If you are running your MLflow instance via Databricks, enter your Databricks URL as the **Host**, enter `token` as the **Login** and your [Databricks personal access token](https://docs.databricks.com/dev-tools/auth.html#personal-access-tokens-for-users) as the **Password**.
```

2023-06-16 09:43 UTC, jwitz commented on learn/airflow-mlflow.md
> +1. Manually run the `mlflow_tutorial_dag` DAG by clicking the play button.
```suggestion
1. In the Airflow UI run the `mlflow_tutorial_dag` DAG by clicking the play button.
```

2023-06-16 09:43 UTC, jwitz commented on static/img/examples/use-case-airflow-mlflow_possum_tails_graph.png
Wait when do we use this photo?? I am all for keeping it in the repo as an easter egg

In fact I'd like a konami code input into the Cloud UI to produce this image as well. Writing up a ProductBoard insight now

2023-06-16 16:26 UTC, kentdanas commented on static/img/examples/use-case-airflow-mlflow_possum_tails_graph.png
I think this one will be used in the use case we plan to publish shortly after this! I'll add a +1 to your ProductBoard insight 😁

2023-06-16 22:12 UTC, merged