Add Azure DevOps Code Example Issue #2562
astronomer/docs pull request #235
Opened 2021-01-29 17:02 UTC by sunkickr

Add Azure DevOps code example to CI/CD documentation

2021-01-29 17:27 UTC, paolaperaza requested changes
@sunkickr Thank you for tackling! Left some questions/comments.

2021-01-29 17:27 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
>  > **Note:** Make sure to replace `infrared-photon-7780` in the example above with your deployment's release name and to store your Service Account Key in your GitHub repo's secrets according to [this
@sunkickr This "Note" re: `infrared-photon-7780` belongs under the `## GitHub Actions CI/CD` header. Can you pull it back up there?

2021-01-29 17:27 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(SERVICE-ACCOUNT-KEY)
```suggestion
    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(DEPLOYMENT-SERVICE-ACCOUNT-KEY)
```

2021-01-29 17:27 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:$CI_PIPELINE_IID .
Typo on `$CI_PIPELINE_IID .`? Should it be `$ CI_PIPELINE_ID`? Is the `.` there correct?

2021-01-29 17:27 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
> +The following example uses Azure Key Vault to store secretes as varible groups avalible to the pipeline.
@sunkickr Maybe rephrase to:

```suggestion
This example uses [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/) to store secrets as variable groups that are then made available to all DAGs within an Airflow Deployment on Astronomer.
```

2021-01-29 17:27 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
> +The following example uses Azure Key Vault to store secretes as varible groups avalible to the pipeline.
Where does this yaml script go?

2021-01-29 18:26 UTC, sunkickr commented on cloud/stable/03_deploy/06_ci-cd.md
> +The following example uses Azure Key Vault to store secretes as varible groups avalible to the pipeline.
The azure key vault secrets are made available to azure DevOps which has the yaml code that runs the pipeline

2021-01-29 18:28 UTC, sunkickr commented on cloud/stable/03_deploy/06_ci-cd.md
>  > **Note:** Make sure to replace `infrared-photon-7780` in the example above with your deployment's release name and to store your Service Account Key in your GitHub repo's secrets according to [this
I can fix this

2021-01-29 18:29 UTC, sunkickr commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:$CI_PIPELINE_IID .
The `.` is needed because the image is held in a remote repository

2021-01-29 18:37 UTC, sunkickr commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(SERVICE-ACCOUNT-KEY)
I'll make this change

2021-01-29 22:10 UTC, paolaperaza approved these changes
Looks good @sunkickr ! Two small comments on the spelling page and then just double checking there's no typo on something, but approving preemptively. Merge whenever you're ready!

2021-01-29 22:10 UTC, paolaperaza commented on .spelling
> +Pre-Requisites
```suggestion
Prerequisites
```

I think `Pre-Requisites` is actually wrong hahaha whoops

2021-01-29 22:10 UTC, paolaperaza commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:$CI_PIPELINE_IID .
Two `I`s in `IID`?

2021-01-31 20:06 UTC, sunkickr commented on cloud/stable/03_deploy/06_ci-cd.md
> +    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:$CI_PIPELINE_IID .
The second I isn't needed I can take it out

2021-01-31 20:08 UTC, sunkickr commented on .spelling
> +Pre-Requisites
I'll fix this

2021-01-31 20:15 UTC, sunkickr commented
Added CI/CD pipeline code, fixed spelling and markdown errors

2021-01-31 20:16 UTC, merged