Added steps for integrating IAM roles with GCP
astronomer/docs pull request #238
Opened 2021-02-01 22:16 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/129

This PR adds the instructions documented in [Notion](https://www.notion.so/astronomerio/GCP-IAM-Role-Integration-c6ce2e82eb8a4ffa8cedd205a4bc8599) to our published documentation. In addition, I tidied up the AWS instructions to be consistent with our style and voice.

2021-02-01 22:17 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +2. Note the name of each GKE service account that appears when you run the following command:
Added "GKE" here and in step 3, but I'm not super sure about the difference between GKE vs GCP service accounts. Could use some confirmation that this is accurate.

2021-02-05 15:00 UTC, paolaperaza requested changes
@jwitz Made some comments/questions to verify, but this looks great - thanks for adding this info :)

2021-02-08 14:51 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +            "astronomer-cluster"
Not sure, this is in our currently published doc. Potential question for @fhoda ?

2021-02-08 14:52 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    https://oidc.eks.us-west-2.amazonaws.com/id/EXAMPLEA829F4B2854D8DAE63782CE90
Probably, but is there a way we can tell people how to retrieve this URL? @fhoda

2021-02-08 15:12 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    The following example allows permission to an S3 bucket named `astronomer-bucket`:
Tried to clarify this, is it accurate @fhoda

2021-02-08 15:27 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    $ astro deployment create <deployment-name> --executor=celery --cloud-role=arn:aws:iam::123456789:role/example-role
Yeah it's unclear when users first acquire this ID number in the steps. Maybe @fhoda could clarify

2021-02-08 15:28 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +> **Note:** If using Airflow `1.10.5`, you'll need to add `boto3 >=1.9` and `botocore >= 1.12` to your `requirements.txt` file.
Since this is a local Airflow file I'm guessing it doesn't require a config.yaml change

2021-02-08 15:30 UTC, jwitz commented
Thanks for the comments @paolaperaza ! I agree that we should clarify where readers acquire some of the "example" values we use. @fhoda I know the original issue was only for GCP setup, but when you review this could you also take a look at Paola's comments in the AWS section and clarify things where you can? Thanks!

2021-02-08 15:34 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +2. Note the name of each GKE service account that appears when you run the following command:
This distinction is correct. Just to note for your reference that GKE service accounts are tied to resources deployed within GKE itself and can only have permissions within GKE except when bound to a GCP service account. While GCP service accounts can have permissions across the platform but cannot define permission to resources within a GKE cluster.

2021-02-08 15:37 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +3. Create an IAM policy binding your Google and GKE service accounts by running the following command for each of the GKE service accounts you noted:
```suggestion
3. Create an IAM policy binding your Google and GKE service accounts by running the following command for the workers and scheduler GKE service accounts you noted:
```

2021-02-08 15:42 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +2. Note the name of each GKE service account that appears when you run the following command:
```suggestion
2. Note the name of the worker and scheduler GKE service account that appears when you run the following command:
```

2021-02-08 16:34 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +            "astronomer-cluster"
`astronomer-cluster` is essentially a placeholder cluster name for whatever the actual name of the cluster that  astronomer is deployed to.

2021-02-08 16:39 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    https://oidc.eks.us-west-2.amazonaws.com/id/EXAMPLEA829F4B2854D8DAE63782CE90
The URL on line 52 `https://oidc.eks.us-west-2.amazonaws.com/id/EXAMPLEA829F4B2854D8DAE63782CE90` will be different for the user than what we have shown here. It will essentially be the output of the command above it.

2021-02-08 16:51 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +            "astronomer-cluster"
```suggestion
            "<astronomer-cluster>"
```
Not sure about the style we are going for but could do soemthing like that or just clarify in the doc what `astronomer-cluster` is meant to be.

2021-02-08 16:52 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    The following example allows permission to an S3 bucket named `astronomer-bucket`:
The policy allows permission to an S3 bucket that will later be attached to the IAM Role.

2021-02-08 17:04 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    $ astro deployment create <deployment-name> --executor=celery --cloud-role=arn:aws:iam::123456789:role/example-role
That number is an AWS Account number. This entire string: `arn:aws:iam::123456789:role/example-role` can be retrieved from IAM Management Console for the Role of interest.

2021-02-08 17:12 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +            "astronomer-cluster"
I could not add this suggestion to the original comment about this. https://github.com/astronomer/docs/pull/238#discussion_r572189906

2021-02-08 17:16 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +> **Note:** If using Airflow `1.10.5`, you'll need to add `boto3 >=1.9` and `botocore >= 1.12` to your `requirements.txt` file.
This is just a validation, so no other changes should be needed.

2021-02-08 17:22 UTC, fhoda commented
@jwitz @paolaperaza I looked through all the comments/suggestions that were unresolved and left my feedback. 

One other thing I noticed is that we refer to GCP service accounts as Google service accounts. I feel that the word `Google` is too generic and we should use `GCP` instead to be more specific.

2021-02-09 15:13 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    https://oidc.eks.us-west-2.amazonaws.com/id/EXAMPLEA829F4B2854D8DAE63782CE90
Ahh got it, thought the URL was a continuation of the command itself. Thank you for clarifying.

2021-02-09 15:57 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    }
This part is the output of the above command `aws eks list-clusters`. Based on some of the other changes you made, thought you may also want to separate this one out?

2021-02-09 16:22 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    ```
When I preview the doc this part does not come out as a proper code block.

2021-02-09 16:22 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    ```
When I preview the doc this part does not come out as a proper code block.

2021-02-09 21:44 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    ```
Thank you for catching these!! They appeared rendered in Atom, but not in GitHub which is the most reliable tell.

2021-02-10 05:01 UTC, paolaperaza approved these changes
Took another look at this and LGTM copy and formatting wise @jwitz ! Will let you review this with other folks who are more familiar with the material and merge whenever you're ready.

2021-02-10 14:54 UTC, jwitz commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    }
Breaking this into two separate steps, one for each command.

2021-02-10 15:10 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    ```
This code block doesn't render properly for me either. I think it has something to do with the indentation of of `Example:` . Wasn't sure you wanted to adjust.

2021-02-10 15:24 UTC, fhoda commented on enterprise/next/05_customize-airflow/06_integrate-iam.md
> +    ```json
This part doesn't render the code block properly form me either. `Example:` is included in the block and the **```**  shows up around the code. Not sure how you wanted to reformat since you had indented this part.

2021-02-10 15:43 UTC, fhoda commented
Rest looks good to me! Thanks for working on this.

2021-02-11 00:48 UTC, jwitz commented
Thank you both for the thorough review @fhoda and @paolaperaza . Think I resolved all remaining formatting snags, but I'll check again once the site rebuilds and get a hotfix in if needed.

2021-02-11 00:49 UTC, merged