Base PR use case section with Airflow and dbt Core use case
astronomer/docs pull request #2389
Opened 2023-06-07 13:07 UTC by TJaniF

First use case example PR. 

I'll try to summarize the discussion around the Use cases section of the examples real quick :) : 

- Should be inspirational content.
- Use cases are aimed at Airflow users who already know both Airflow and the tools involved, but might want to see how they can be used together.
- Not a step by step structure, rather a code focussed walk through of an example repository
- Ideally this could be a place where we could link our various demo repositories together with short content descriptions.

Happy to hear all feedback on the way I structured this. I tried to keep important steps that are Cosmos specific while removing some added explanation and making the structure more casual than the original tutorial was :)

2023-06-07 16:50 UTC, kentdanas requested changes
@TJaniF this is a great start! Requesting changes because I think we can adjust things a bit to make it more "use-case" forward - to distinguish things in this section between our tutorials/integrations, I really want to make them highlight the use case and the tools used, over the specific steps (even though we're still presenting it in a way that people could follow if they wanted to). Let me know what you think or if you want to chat about any of this.

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +sidebar_label: "Airflow and dbt Core"
I know we don't want to make the side bar labels super long, but I think we should have something that indicates what the 'use case' is as opposed to just the tools. So maybe "ELT with Airflow and dbt Core"? I actually wouldn't even mind doing something like "ELT for renewable energy analysis with Airflow and dbt" although that might be too long...

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +title: "Create an ELT pipeline with Airflow, dbt Core, Cosmos and the Astro Python SDK"
```suggestion
title: "ELT for renewable energy analysis with Airflow, dbt Core, Cosmos and the Astro Python SDK"
```
I think we should have the titles for these state the use case, and they don't need to be action oriented since we're not treating this as a step by step thing.

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +You will need:
```suggestion
Before trying this example, make sure you have:
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +To use this example you should have an understanding of:
I'm leaning towards not including "understanding" links in the Before you start section, because we want people to dive into the example and not think 'oh I need to read all this stuff first'. I think we should put these in the 'See also' (renamed from your Learn more to be consistent with the others we published) section at the end. But if you feel otherwise let me know, happy to debate this :)

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Learn more
```suggestion
## See also
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- Tutorial: [Orchestrate dbt Core jobs with Airflow and Cosmos](airflow-dbt.md).
```suggestion
- [Orchestrate dbt Core jobs with Airflow and Cosmos](airflow-dbt.md).
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- Webinar: [The easiest way to orchestrate your dbt workflows from Airflow](https://www.astronomer.io/events/webinars/the-easiest-way-to-orchestrate-your-dbt-workflows-from-airflow/).
```suggestion
- [The easiest way to orchestrate your dbt workflows from Airflow](https://www.astronomer.io/events/webinars/the-easiest-way-to-orchestrate-your-dbt-workflows-from-airflow/).
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- Tutorial: [Orchestrate dbt Cloud jobs with Airflow](airflow-dbt-cloud.md).
```suggestion
- [Orchestrate dbt Cloud jobs with Airflow](airflow-dbt-cloud.md).
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- Documentation: [Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/index.html).
```suggestion
- [Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/index.html).
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- Documentation: [Astronomer Cosmos](https://astronomer.github.io/astronomer-cosmos/).
```suggestion
- [Astronomer Cosmos](https://astronomer.github.io/astronomer-cosmos/).
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Learn more
Maybe if we have a long-ish list of things in this section we should break it out into a few lists, like:

Tutorials:
- one
- two

Documentation:
- one
- two

Webinars:
- one

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +[dbt Core](https://docs.getdbt.com/) is a popular open-source library for analytics engineering that helps users build interdependent SQL models. Thanks to the [Cosmos](https://astronomer.github.io/a
I think it might be helpful to have a little more info up front about what is being created in this example. Maybe a screenshot of the DAG graph?

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Get the data
```suggestion
## The data
```
Let's update this section to be more "about the data" and take out the tutorial language. And after a brief description of the data, you can say something like To try the example: and then the 1 and 2 steps.

Also maybe let's move this section up to be right after Before you start. So we describe the use case in the intro, then talk about the data, and then go into basic setup. Wdyt?

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Connect Airflow to your database
I'm leaning towards combining this with the previous section, so we have one header for "setup" type stuff. I like the "Basic setup" that Modal uses, so we could do that and have two subsections within it. Or open to other suggestions here too.

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Prepare your dbt Core models
```suggestion
## dbt Core models
```
I'm debating taking some of the action language out to make this more "presenting a use case" than instructional, which would require modifying the text a bit too.

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Create a DAG
```suggestion
## The ELT DAG
```

2023-06-07 16:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Result
```suggestion
## Results
```

2023-06-07 18:28 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! :) 

I tried to address all the comments and in general move away from the tutorial language focussing more on the use case. I like how it is shaping, I think there is a potential to be even more brief and code centric but there are some trade offs ofc very happy to discuss :)

2023-06-07 18:40 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Connect Airflow to your database
I actually like this layout, but for any file we're modifying I would keep the entire contents (e.g. the whole Dockerfile). But I like the text and presentation here a lot. I think assuming the user knows enough about Airflow/the Astro project is fine, since we're providing a link to a repo they can clone and not do anything themselves, or they can always read more as needed.

2023-06-07 18:42 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +sidebar_label: "ELT of energy data with Airflow and dbt Core"
Hmm, looking at the side bar it is a little much....maybe we start with "ELT with Airflow, dbt, and the Astro SDK" and then if we end up with too many examples that are "ELT" with those tools we can reevaluate.

2023-06-07 18:44 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## The Data
Oops, I wasn't clear before, I think this section should come right _after_ Before you start :)

2023-06-07 18:45 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +This example analyzes changes in solar and renewable energy capacity in different European countries. The full source data provided by [Open Power System Data](https://doi.org/10.25832/national_gener
```suggestion
This example analyzes changes in solar and renewable energy capacity in different European countries. The full source data provided by [Open Power System Data](https://doi.org/10.25832/national_generation_capacity/2020-10-01) includes information on many types of energy capacity. The subset of data used in this example can be found in this [GitHub repository](https://github.com/astronomer/learn-tutorials-data/blob/main/subset_energy_capacity.csv), and is read by the DAG from the `include` folder of the Astro project.
```

2023-06-07 18:46 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- The [Astro CLI](https://docs.astronomer.io/astro/cli/overview) and an Astro project created by running `astro dev start`.
```suggestion
- The [Astro CLI](https://docs.astronomer.io/astro/cli/overview).
- An Astro project running locally on your computer. See [Getting started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started-cli).
```

2023-06-07 18:47 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Basic setup
Let's update this section to what you have in your comment, but keep the explanatory text about the Airflow connection, if that makes sense.

2023-06-07 18:49 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +Add the following Airflow DAG to your Astro project:
```suggestion
Here is the ELT DAG:
```

2023-06-07 18:50 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +The `DbtTaskGroup` function of the Astro dbt provider package automatically scans the `dbt` folder for dbt projects and creates a task group (`transform_data` in this example) containing Airflow task
```suggestion
Cosmos' `DbtTaskGroup` function automatically scans the `dbt` folder for dbt projects and creates a task group (`transform_data` in this example) containing Airflow tasks for running and testing your dbt models. Additionally, Cosmos can infer dependencies within the dbt project and will set your Airflow task dependencies accordingly.
```

2023-06-07 18:53 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +Open the logs of the `log_data_analysis` task to see the proportional solar and renewable energy capacity development in the country you selected.
```suggestion
After the DAG runs, the logs of the `log_data_analysis` task show the proportion of solar and renewable energy capacity development in the country you selected.
```

2023-06-07 18:54 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- [What is dbt?](https://docs.getdbt.com/docs/introduction).
I think we only need one dbt doc link in See also, so I would pick this one or the docs below, whichever you think is most helpful/relevant.

2023-06-07 18:55 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +- [Get started with Apache Airflow](get-started-with-airflow.md).
```suggestion
```
Removing get started since the others we link assume some level of Airflow knowledge already and also have get started as a prereq.

2023-06-08 07:16 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 

@jwitz and @lzdanski the first use case ready for you curious what you think about the current format :)

2023-06-13 10:46 UTC, jwitz requested changes
I love this example DAG @TJaniF ! I have some higher level thoughts about the structure for use cases:

- The primary benefit of these use cases over the Registry is that we provide all of the necessary project configuration to get going. We only mention the project repo in a note at the beginning, but what if we framed that as the primary mode of interacting with the example? So the flow would be "Here's an example project, and here's the steps for how to download and run it. If you want to configure it manually, there's also steps for that at the bottom of the doc." 
- If we follow the previous point, we can then bring up the "Results" and DAG info much closer to the top of the doc, where users are more likely to spend time. I don't want someone to have to scroll all the way through the setup to see the results of the project.

My goal with these suggestions is to remove as much friction as possible between the user clicking the article and realizing the value add of Cosmos and Airflow. Lmk if that sounds good to you or if you want me to jump in and help with the structure!

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +sidebar_label: "ELT with Airflow, dbt + Astro SDK"
```suggestion
sidebar_label: "ELT with Airflow + dbt + Astro SDK"
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +title: "ELT for renewable energy analysis with Airflow, dbt Core, Cosmos and the Astro Python SDK"
```suggestion
title: "Create an ELT pipeline with Airflow, dbt Core, Cosmos, and the Astro Python SDK"
```
Only because the renewable stuff might discourage googlers from clicking if they wanted more generalized advice

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +This example shows a DAG that loads data about changes in solar and renewable energy capacity in different European countries from a local CSV into a data warehouse. Transformation steps in dbt Core
```suggestion
This example shows a DAG that loads data about changes in solar and renewable energy capacity in different European countries from a local CSV file into a data warehouse. Transformation steps in dbt Core filter the data for a country selected by the user and calculate the percentage of solar and renewable energy capacity for that country in different years. Depending on the trajectory of the percentage of solar and renewable energy capacity in the selected country, the DAG will print different messages to the logs.
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## The Data
```suggestion
## Data source
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## Basic setup
```suggestion
## Setup
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +The full Astro project used in this example can be cloned from [this repository](https://github.com/astronomer/astro-dbt-provider-tutorial-example).
```suggestion
To skip the setup for this example, clone the final example from the [Astronomer GitHub](https://github.com/astronomer/astro-dbt-provider-tutorial-example). 
```
Random Q: do you think it would be better to provide a [JSON connection variable](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#storing-connections-in-environment-variables) in the example project so that users can configure the whole thing from code? That feels like the path of least resistance if someone's already wanting to jump to the end. We could then include a note in the README or this doc about needing to configure the JSON.

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +- Access to a data warehouse supported by dbt Core and the Astro Python SDK. See [dbt documentation](https://docs.getdbt.com/docs/supported-data-platforms) for all supported warehouses of dbt Core an
```suggestion
- Access to a data warehouse supported by dbt Core and the Astro Python SDK. See [dbt supported warehouses](https://docs.getdbt.com/docs/supported-data-platforms) and [Astro Python SDK supported warehouses](https://astro-sdk-python.readthedocs.io/en/stable/supported_databases.html). This example uses a local [PostgreSQL](https://www.postgresql.org/) database with a database called `energy_db` and a schema called `energy_schema`.
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +Modify your Astro project with the following instructions.
Hm I think we should still use numbered steps for these like we do for tutorials. We should just avoid topic-level steps to simplify the page layout.

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +```
```suggestion
1. Add the following lines to your `Dockerfile` under the `FROM` statement:

    ```Dockerfile
    # install dbt into a virtual environment
    # replace dbt-postgres with another supported adapter if you're using a different warehouse type
    RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
    pip install --no-cache-dir dbt-postgres && deactivate
```
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +```
Repeat this pattern for the remaining configs

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +#### Airflow connections
```suggestion
### Airflow connections
```

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## dbt Core models
```suggestion
### dbt Core models
```
This structure is confusing because this looks like reference material, but there's no steps for the user to follow to actually get this in their project. This also runs parallel to the "Setup" in topic level, so it looks like something else entirely

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +When using Cosmos, any dbt project can be converted into an Airflow task group by putting it in a `dbt` directory within the Astro projects `dags` folder.
I think we need to be much more explicit with the steps here, similar to the structure I suggested for updating the various Astro project files above

2023-06-13 10:46 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +Here is the ELT DAG:
```suggestion
Add the following DAG to your `dags` directory in a file called `my_energy_dag.py`.
```

2023-06-13 17:00 UTC, TJaniF reviewed
Thank you for the review @jwitz ! I like the idea of turning the content upside down. Let me know what if what I did matches what you imagined :) 
(I also went with slightly less instructive language around the setup to be more brief, but open to discuss what makes most sense in the new structure :))

2023-06-13 18:05 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Project contents
I'm fine with this new layout overall, but I don't love having `Project contents` with very direct, technical descriptions of the code without any code itself. I guess we're assuming people will clone the project and be looking at it alongside the doc, but if they _don't_ clone the project, I would find this section by itself very confusing.

I think if we're going to keep this structure, we need to adjust what goes in this section. So maybe we can:

1. Make the description of the project contents a tiny bit higher level and integrate the use case throughout more. e.g. describe what the tasks do in the context of the use case, and also describe what the dbt models are actually doing. Having it only mention the DAG and not the dbt models doesn't make sense in the context of this use case.
2. Take some code snippets from the DAG and put them alongside each bullet where we're describing what happens. This is kind of how [modal](https://modal.com/docs/guide/ex/stable_diffusion_cli) does it, and I think would help orient users to what's going on in each part of the DAG.

2023-06-13 21:15 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +This project consists of one DAG, [my_energy_dag](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/my_energy_dag.py), which performs the whole ELT process using two ta
```suggestion
This project consists of one DAG, [my_energy_dag](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/my_energy_dag.py), which performs an ELT process using two tasks defined with Astro Python SDK operators and one task group created through Cosmos that orchestrates a dbt project consisting of two models.
```

2023-06-13 21:20 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +## Setup
If we organize like this, I'm on the fence whether we actually need a Setup section, or whether we write these with the intention of people only cloning the repo or running in GH codespaces. If connections or things like that are needed, we could put notes about them in `Clone the project`, and they would also go in the repo readme.

Overall I want to make these distinct from a tutorial - we're focusing on highlighting the value of the tools and what use cases are possible in Airflow, not the nitty gritty of how to set it up.

2023-06-13 21:21 UTC, kentdanas commented on learn/use-case-airflow-dbt.md
> +The resulting file structure of the Astro project is:
Seems like we could move this up into Project contents?

2023-06-14 09:23 UTC, jwitz reviewed
@TJaniF I think this is close! I like how you interpreted my high level comments, and imo the guide looks much cleaner now

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## Data source
Should this be an H3 under "Project contents"?

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +- The first model, [select_country](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/dbt/my_energy_project/models/select_country.sql), queries the table created by the
```suggestion
- The first model, [`select_country`](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/dbt/my_energy_project/models/select_country.sql), queries the table created by the previous task and creates a subset of the data by only selecting rows for the country that was specified as the `country_code` variable in the `dbt_args` parameter of the `DbtTaskGroup`. See the [dataset](https://github.com/astronomer/learn-tutorials-data/blob/main/subset_energy_capacity.csv) for all available country codes.
```

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +- The first model, [select_country](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/dbt/my_energy_project/models/select_country.sql), queries the table created by the
I love how you've linked the GH repo contents into the descriptions as well!

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +- The second model, [create_pct](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/dbt/my_energy_project/models/create_pct.sql), divides both the solar and renewable en
```suggestion
- The second model, [`create_pct`](https://github.com/astronomer/astro-dbt-provider-tutorial-example/blob/main/dags/dbt/my_energy_project/models/create_pct.sql), divides both the solar and renewable energy capacity by the total energy capacity for each year calculating the fractions of these values. Note how the dbt `ref` function creates a dependency between this model and the upstream model `select_country`. Cosmos then automatically translates this into a dependency between Airflow tasks.
```

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +Finally, the `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to run an analysis on the fi
```suggestion
Finally, the `log_data_analysis` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to run an analysis on the final table and logs the results.
```

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +The structure of the relevant files in the Astro project is:
```suggestion
The files come together in the following project structure:
```
This doesn't feel substantial enough to have in its own topic, but I still like having it here for reference

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## Results
@kentdanas @TJaniF Would you be opposed to moving this before the project contents section? It's a small topic that could convince users to download the project.

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +## See also
Can we cut this down to like the 3 most important links from all of the categories? I feel overwhelmed with this selection and would rather have a smaller, more curated list of resources.

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +- An Astro project running locally on your computer. See [Getting started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started-cli).
```suggestion
- [Docker Desktop](https://www.docker.com/products/docker-desktop/)
```
Cus they're copying it right? They shouldn't need an existing project

2023-06-14 09:23 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +
```suggestion
## Run the project

To run the example project, first make sure Docker Desktop is running. Then, open your project and run:

```sh
astro dev start
```

This command builds your project and spins up 4 Docker containers on your machine to run it. After the command finishes, open the Airflow UI at `https://localhost:8080/` and trigger your DAG using the play button.
```

If we're going in this direction, we also need to tell users how to run the project. Feel free to play with the language here, but I think this is the minimum someone needs to do to try the project. Also ugh looks like the suggestion is wonky, see the real thing by editing my comment to view the raw text.

2023-06-14 13:07 UTC, TJaniF reviewed
Thank you @jwitz ! keeps looking better every iteration :)

2023-06-14 16:18 UTC, jwitz approved these changes
✅ 🥳 🚀  Here's to use cases!

2023-06-14 16:18 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +For simple instructions on how to use dbt Core with Cosmos, see the [dbt Core tutorial](airflow-dbt.md).
```suggestion
For a more detailed instructions on using dbt Core with Cosmos, see the [dbt Core tutorial](airflow-dbt.md).
```
Seems like this is more complex than the current doc?

2023-06-14 16:18 UTC, jwitz commented on learn/use-case-airflow-dbt.md
> +This example shows a DAG that loads data about changes in solar and renewable energy capacity in different European countries from a local CSV file into a data warehouse. Transformation steps in dbt
```suggestion
This example uses a DAG to load data about changes in solar and renewable energy capacity in different European countries from a local CSV file into a data warehouse. Transformation steps in dbt Core filter the data for a country selected by the user and calculate the percentage of solar and renewable energy capacity for that country in different years. Depending on the trajectory of the percentage of solar and renewable energy capacity in the selected country, the DAG will print different messages to the logs.
```

2023-06-14 16:18 UTC, jwitz commented on sidebarsLearn.js
> +            },
```suggestion
```
Let's avoid the generated index for now if there's only one item - I wanna think through our use of that before we start rendering it as a page.

2023-06-14 19:39 UTC, merged