Quick polish of Issue Templates
astronomer/docs pull request #2414
Opened 2023-06-12 14:10 UTC by paolaperaza

Had to 🙃

2023-06-12 15:33 UTC, paolaperaza commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      label: The Fix
```suggestion
      label: Fix or Proposed Change
```

2023-06-13 09:48 UTC, jwitz requested changes
This is an interesting design @paolaperaza. While I'm all for simplifying templates and choice, I think we've inadvertently created some new complexities that we'll have to resolve before this is merged. See my comments for more details

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +name: General Docs Request
```suggestion
name: Request a Docs Change
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +        - Issue with Docs website
```suggestion
        - Inaccurate, misleading, or out-of-date information
        - Missing content for an existing feature
        - Typo or broken link
        - Issue with Docs website functionality
        - Request a new set of best practices or recommendations
        - Request a new technical overview, explanation, or reference
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      label: The Issue or Context
```suggestion
      label: The issue or context
```
I'd prefer not to capitalize the fields themselves

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
>        label: Issue Type
```suggestion
      label: Issue type
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      label: The Fix
```suggestion
      label: Fix or proposed change
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      description: Describe what exactly is wrong or missing in the context of current documentation. Be as descriptive as possible.
```suggestion
      description: Describe what is wrong or missing in the documentation. Be as descriptive as possible.
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +      label: Required Reviewers
```suggestion
      label: Required reviewers
```

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/new-feature.yaml
> +      label: Release Date
```suggestion
      label: Release date
```
Looking back on the templates I'd prefer to uncapitalize these topics to match our docs site style, but don't feel strongly.

2023-06-13 09:48 UTC, jwitz commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +description: Anything in existing documentation that is wrong, missing, or misleading.
```suggestion
description: Use this template to request changes to existing Astronomer docs, or to request new content.
```

2023-06-15 14:33 UTC, paolaperaza reviewed
@jwitz Back to you!

2023-06-19 13:24 UTC, merged