initial commit with HA details
astronomer/docs pull request #2423
Opened 2023-06-13 14:26 UTC by manmeetkaur

2023-06-13 14:27 UTC, manmeetkaur commented
@jwitz I wasn't sure where to include the Hybrid HA information, there is no dedicated page. So added in the tip section.

Also, I am not sure if we want to include the multiple az line or how we want to write it.

2023-06-14 11:00 UTC, jwitz requested changes
LGTM, but I'll take another look once the changes are in- especially because some of my suggestions might be technically inaccurate!

2023-06-15 11:49 UTC, manmeetkaur commented on astro/configure-deployment-resources.md
> +*Multiple instances of [PgBouncer](https://www.pgbouncer.org/) run across availability zones; for scheduler it is not guaranteed but is possible because the cluster is across two availability zones.
I thought we were avoiding, but then read point 7 in [this](https://docs.astronomer.io/astro/cloud-ide/deploy-project#export-your-pipelines-to-a-local-astro-project
)

2023-06-15 11:49 UTC, manmeetkaur commented on astro/configure-deployment-resources.md
> +On Astro Hybrid, by default, PgBouncer is highly available. Every Deployment has 2 PgBouncer pods each assigned to a different node. This prevents against zombie tasks. PgBouncer is not configurable
Not sure why pods should start with capital P ; it is not an Astro term but a generic K8s term? I changed the edits you made because that changed the meaning. if we use "each node" that could imply each node will have a pgbouncer pod.

2023-06-15 14:38 UTC, paolaperaza reviewed
@jwitz Take a look at this and add to this PR with cluster doc changes

2023-06-15 14:38 UTC, paolaperaza commented on astro/configure-deployment-resources.md
>  ## Enable high availability
From standup:

- Let's consider making this part of the doc assume Hosted only
- Add info on Hybrid HA in the cluster settings resource reference
- Say something like, "If you're an Astro Hybrid customer, HA is... see here for more info"

2023-06-15 15:57 UTC, jwitz approved these changes
@manmeetkaur I tried playing around with adding the note to several different docs, but it didn't really feel right in any of them. The problem now is that the note is right at the top of the doc - per my previous comment, let's move the note until after the numbered steps so that Hosted users still see their content first. This is how we've done it in other docs (See: https://docs.astronomer.io/astro/configure-deployment-resources#update-scheduler-size)

Besides that and my other suggestions, this is good to merge!

2023-06-15 15:57 UTC, jwitz commented on astro/configure-deployment-resources.md
> +By default, each deployment uses 1 scheduler. If you configure your Deployment to use 2 schedulers, each scheduler Pod is assigned to a separate node to ensure availability. To limit in cost, a Deplo
```suggestion
By default, each Deployment uses 1 scheduler. If you configure your Deployment with 2 schedulers, each scheduler Pod is assigned to a separate node to ensure availability. To limit cost, a Deployment that uses 3 or 4 schedulers can assign all scheduler Pods across two nodes.
```

2023-06-15 15:57 UTC, jwitz commented on astro/configure-deployment-resources.md
> +:::info High availability on Astro Hybrid
We should move this tip until after the numbered steps for Hosted

2023-06-15 15:57 UTC, jwitz commented on astro/configure-deployment-resources.md
> +By default, the Pods running your Deployment's Airflow components are distributed across multiple nodes. When you enable high availability, your Deployment runs two instances of [PgBouncer](https://w
```suggestion
By default, the Pods running your Deployment's Airflow components are distributed across multiple nodes. When you enable high availability, your Deployment runs two instances of [PgBouncer](https://www.pgbouncer.org/) and two instances of its scheduler across different nodes. This ensures that your DAGs can continue to run if there's an issue with one of your Airflow components in a specific node. Note that PGBouncer Pods are guaranteed to run across multiple availability zones, but scheduler Pods are not. 
```

2023-06-15 15:57 UTC, jwitz commented on astro/configure-deployment-resources.md
> +*Multiple instances of [PgBouncer](https://www.pgbouncer.org/) run across availability zones; for scheduler it is not guaranteed but is possible because the cluster is across two availability zones.
That should definitely be deleted 😓 not sure how I let that through review!

2023-06-16 08:47 UTC, jwitz commented on astro/configure-deployment-resources.md
> +On Astro Hybrid, PgBouncer is highly available by default for your Deployment whereas to enable high availability of schedulers you need to configure your scheduler count to more than 1.
```suggestion
On Astro Hybrid, PgBouncer is highly available by default for all Deployments. Schedulers are highly available if a Deployment uses two or more schedulers. 
```

2023-06-16 08:47 UTC, jwitz commented on astro/configure-deployment-resources.md
> +Every Deployment has 2 PgBouncer Pods assigned to two different nodes to prevent zombie tasks. If you configure your Deployment with 2 schedulers, each scheduler Pod is assigned to a separate node to
```suggestion
Every Deployment has two PgBouncer Pods assigned to two different nodes to prevent zombie tasks. If you configure your Deployment with two schedulers, each scheduler Pod is assigned to a separate node to ensure availability. To limit cost, a Deployment that uses three or four schedulers can assign all scheduler Pods across two nodes.
```

2023-06-16 08:47 UTC, jwitz approved these changes

2023-06-16 11:22 UTC, merged