Dev/connections guide
astronomer/docs pull request #2441
Opened 2023-06-16 11:48 UTC by manmeetkaur

2023-06-20 09:13 UTC, TJaniF commented
Haha, GitHub added a few comments there I was jotting down while scrolling through, did not mean to review just yet 😅

This is going to be so extremely helpful! 🤩

2023-06-21 21:18 UTC, kentdanas commented on sidebarsLearn.js
> +            label: 'How-to Connections',
```suggestion
            label: 'Connections',
```
I would just call this section 'Connections'

2023-06-21 21:18 UTC, kentdanas commented on learn/connections-snowflake.md
> +
We had a request for instructions on how to connect with privatelink: https://github.com/astronomer/docs/issues/2167

Could we add that here?

2023-06-21 21:18 UTC, kentdanas commented on learn/connections-dbt.md
> +- [Import and export your connections in JSON or URI foramt](https://docs.astronomer.io/learn)
I think this is the wrong link here. Also can we add a reference to our dbt Cloud integration doc? https://docs.astronomer.io/learn/airflow-dbt-cloud

2023-06-26 11:22 UTC, manmeetkaur commented on learn/connections-dbt.md
> +- [dbt Cloud API reference](https://docs.getdbt.com/docs/dbt-cloud-apis/overview)
```suggestion
- [dbt Cloud API reference](https://docs.getdbt.com/docs/dbt-cloud-apis/overview)
- [Airflow and dbt Cloud](https://docs.astronomer.io/learn/airflow-dbt-cloud)
```

2023-06-27 09:12 UTC, jwitz requested changes
@manmeetkaur These will be a great resource going forward! I had a few suggestions in the first doc that will apply to all of the docs, so giving this to you now. I'll start working on more specific edits to the content after those changes are applied across the PR.

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +4. Copy the name of the Data Factory and the Resource group as well.
```suggestion
## Get connection details

A connection from Airflow to Azure data factory requires the following information:

- Subscription ID
- Data factory name
- Resource group name
- Application Client ID
- Tenant ID
- Client secret

Follow these steps to retrieve all of these values:

1. In your Azure portal, open the subscription that contains your data factory and copy the **Subscription ID**. See [https://learn.microsoft.com/en-us/azure/azure-portal/get-subscription-tenant-id](https://learn.microsoft.com/en-us/azure/azure-portal/get-subscription-tenant-id).
2. Copy the names for your data factory and resource group.
3. Follow Azure documentation to [create an application service principal](https://learn.microsoft.com/en-us/azure/developer/python/sdk/authentication-local-development-service-principal?tabs=azure-portal) for Airflow. As you create your application, copy the **Application Client ID**, **Tenant ID**, and **Client Secret**.
4.  [Assign the appropriate permissions](https://learn.microsoft.com/en-us/azure/data-factory/concepts-roles-permissions#set-up-permissions) for Airflow to access your data factory.
```
- Even though **Subscription ID** is a value, we still use bold because it's copied from a user interface, rather than a code block.
- For all guides, let's have a bulleted list of the values that users will need to collect. Maybe we could also use `[] checkbox` formatting for this?
- This is for local development only. We should either make it clear that they'll have to change for a production environment or tell them how to do that in a note.

2023-06-27 09:12 UTC, jwitz commented on static/img/guides/connection-azure-data-factory.png
We should cut `mk` use in the future examples, as readers might not know what that means

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +    "resource_group_name": "mk",
```suggestion
    "factory_name": "my-factory", 
    "resource_group_name": "my-resource-group",
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +If you wish to use the same connection for multiple data factories or multiple resource groups, you can skip the Resource Group and Factory Name fields in the connection and pass it in the `default_a
```suggestion
If you want to use the same connection for multiple data factories or resource groups, you can skip the **Resource Group** and **Factory Name** fields in the connection configuration. Instead, you can pass these values to the `default_args` of a DAG or as parameters to the AzureDataFactoryOperator. For example:
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +:::
```suggestion

After you configure these defaults, you can override them on a DAG or task-level basis, allowing you to use the same connection ID for access to multiple data factories.
:::
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +Airflow uses from [`azure-mgmt-datafactory`](https://pypi.org/project/azure-mgmt-datafactory/) library from [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python) to connect to Azure D
```suggestion
Airflow uses the [`azure-mgmt-datafactory`](https://pypi.org/project/azure-mgmt-datafactory/) library from [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python) to connect to Azure Data Factory.
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +- [Airflow OSS docs](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/6.1.1/connections/adf.html)
```suggestion
- [`apache-airflow-providers-microsoft` documentation](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/6.1.1/connections/adf.html)
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +## References
```suggestion
## See also
```

2023-06-27 09:12 UTC, jwitz commented on learn/connections-azure-data-factory.md
> +- [Create your first pipeline an Azure Data Factory](https://learn.microsoft.com/en-us/azure/data-factory/v1/data-factory-build-your-first-pipeline-using-editor)
```suggestion
- [Create your first pipeline in Azure Data Factory](https://learn.microsoft.com/en-us/azure/data-factory/v1/data-factory-build-your-first-pipeline-using-editor)
```

2023-06-27 14:24 UTC, manmeetkaur commented on learn/connections-azure-data-factory.md
> +4. Copy the name of the Data Factory and the Resource group as well.
I have to think how to have a bulleted list up top for the fields that required because it might vary in some of the connections where there are various ways to connect.

2023-07-12 07:28 UTC, manmeetkaur commented
closing this because I messed up the conflict resolution - Here is the new [PR](https://github.com/astronomer/docs/pull/2554)

2023-07-12 07:28 UTC, closed without merging