Context, Params and Variables guides
astronomer/docs pull request #2442
Opened 2023-06-16 14:45 UTC by TJaniF

Resolves: #2425 #2239 #1279

2023-06-16 19:57 UTC, kentdanas requested changes
@TJaniF this is awesome, so much good info here! Most of my comments are minor - requesting changes just because this is a big PR and it's Friday afternoon and my brain is getting mushy, so I want to take another pass next week.

2023-06-16 19:57 UTC, kentdanas commented on learn/airflow-variables.md
> +- Airflow variables are ideal to store key-value pairs or short JSON objects that need to be accessible in your whole Airflow environment. It is best practice to use Airflow variables for information
```suggestion
- Airflow variables store key-value pairs or short JSON objects that need to be accessible in your whole Airflow environment. It is best practice to use Airflow variables for information that is runtime dependent but does not change too frequently. Airflow variables are also encrypted, making them suitable for storing secrets.
```

2023-06-16 19:57 UTC, kentdanas commented on learn/airflow-variables.md
> +Astro CLI users can create Airflow variables from the `airflow_settings.yaml` file.
Link to CLI docs on "Astro CLI" here

2023-06-16 19:57 UTC, kentdanas commented on learn/airflow-variables.md
> +To programmatically retrieve and Airflow variable you can either use the `.get()` method of the Airflow Variable model or you can pull the Variable value directly from the [Airflow context](airflow-c
```suggestion
To programmatically retrieve an Airflow variable, you can either use the `.get()` method of the Airflow Variable model or you can pull the Variable value directly from the [Airflow context](airflow-context).
```

2023-06-16 19:57 UTC, kentdanas commented on sidebarsLearn.js
> +            'airflow-context',
Gut reaction, I'm not sure 'context' belongs in "Basics"....I know this isn't super important because most people just search, and I'm not totally sure where else to put it (I don't love "Advanced" for this either), but I think of Basics as the things everybody should read when new to Airflow, and maybe context isn't used by everybody (or should be for more advanced users)? Not sure....wdyt?

2023-06-16 19:57 UTC, kentdanas commented on learn/airflow-variables.md
> +An Airflow variable is a key-value pair that can be used to store information in your Airflow environment. They are commonly used to store instance level information that rarely changes, including se
Somewhere in here we should link to our Astro variables docs, maybe in an info box. I think this is most relevant: https://docs.astronomer.io/astro/environment-variables

2023-06-16 19:58 UTC, kentdanas requested changes
@TJaniF this is awesome, so much good info here! Most of my comments are minor - requesting changes just because this is a big PR and it's Friday afternoon and my brain is getting mushy, so I want to take another pass next week.

2023-06-19 19:52 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! :) 
I accepted all of your suggestions (and sneakily removed a few of my Friday brain blunders on this 😅 )

2023-06-19 19:52 UTC, TJaniF commented on learn/airflow-params.md
> +### Param default examples
yeah, me neither! The color picker is the one where I thought: how was this just hidden somewhere in an example DAG in the official docs, that is so cool. 😄

2023-06-19 19:52 UTC, TJaniF commented on learn/airflow-variables.md
> +- Environment variables are a common way to store small pieces of information to be available in your whole Airflow environment. The advantage of using environment variables is that you can include t
Yes haha, definitely the latter. Will try to clarify 😅

2023-06-19 19:52 UTC, TJaniF commented on sidebarsLearn.js
> +            'airflow-context',
Hmmm yeah I agree, maybe DAGs? (I keep wanting to put stuff into the DAGs section, the catchall haha)

2023-06-21 20:45 UTC, kentdanas approved these changes
@TJaniF thanks for putting all this together. I'm happy with this from a content perspective (I think these are ones where we may get internal/community feedback on how to address specific questions that come up over time, but this is a great starting place). Good to move on to copy editing.

2023-06-21 20:45 UTC, kentdanas commented on learn/airflow-variables.md
> +## Best practices for storing information in Airflow
Since this guide is about Airflow variables, and there's often a lot of confusion about Airflow vs environment variables, I'm thinking we should reorg this section a bit to start with the text about Airflow variables, and then have something like "There are also other ways of storing information in Airflow, including:" and then the rest of the bullets. And make sure we're super clear in the env var bullet what the difference is.

2023-06-21 20:45 UTC, kentdanas commented on learn/airflow-variables.md
> +<Tabs
I'm not seeing the tabs render for these in the deploy preview...

2023-06-23 08:32 UTC, TJaniF reviewed
Thank you for the review @kentdanas ! 

I ended up reorganizing the start of the Variables guide quite a bit and added a section on masking sensitive values at the end of the guide, so you might want to have a second look at that one :) 

@jwitz ready for you :)

2023-06-23 15:25 UTC, kentdanas commented on learn/airflow-variables.md
> +- You should avoid using Variables in top-level Airflow code, as they will create a connection to the Airflow metastore every time the DAG is parsed, which can lead to performance issues. See also [D
```suggestion
- You should avoid using Airflow variables in top-level DAG code, as they will create a connection to the Airflow metastore every time the DAG is parsed, which can lead to performance issues. See also [DAG writing best practices in Apache Airflow](dag-best-practices.md#avoid-top-level-code-in-your-dag-file).
```

2023-06-23 15:25 UTC, kentdanas commented on learn/airflow-variables.md
> +- You can use the [Jinja template](templating.md) syntax to access Variables in top-level Airflow code, since they will only be rendered one a task executes.
```suggestion
- You can use the [Jinja template](templating.md) syntax to access Airflow variables in top-level DAG code, since they will only be rendered once a task executes.
```

2023-06-26 11:26 UTC, jwitz requested changes
Overall LGTM! There's just so much content here that I wanna take a second look after the comments are addressed

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-params.md
> +Lastly, by providing custom HTML to the `description_html` attribute you can create more complex UI elements like a color picker. You can find the code which created the UI element below in [this exa
```suggestion
If you provide custom HTML to the `description_html` attribute, you can create more complex UI elements like a color picker. For sample code, see the [the example DAG in the Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_params_ui_tutorial.html).
```

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-variables.md
> +- You should avoid using Airflow variables in top-level DAG code, as they will create a connection to the Airflow metastore every time the DAG is parsed, which can lead to performance issues. See als
```suggestion
- You should avoid using Airflow variables outside of tasks in top-level DAG code, as they will create a connection to the Airflow metastore every time the DAG is parsed, which can lead to performance issues. See [DAG writing best practices in Apache Airflow](dag-best-practices.md#avoid-top-level-code-in-your-dag-file).
```

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-variables.md
> +:::
```suggestion
```

Feels out of place, I would drop this link later when talking about how you can set Airflow variables.

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-variables.md
> +- Using the `airflow_settings.yaml` file (Astro CLI users).
```suggestion
```
We decided not to mention this option in our own Astro variables and connection management doc because there just isn't a great user case for it right now. So I would also remove it from this guide.

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-variables.md
> +As seen in the screenshot at the beginning of this guide, some Airflow variables are additionally masked in the Airflow UI and if printed to the logs. This behavior is controlled via the Airflow conf
```suggestion
As seen in the screenshot at the beginning of this guide, some Airflow variables are additionally masked in the Airflow UI and logs. While you can manually mark variables as secrets, some variables are marked automatically using an Airflow configuration. By default, the [`hide_sensitive_var_conn_fields`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#hide-sensitive-var-conn-fields) configuration is set to `True`, which automatically masks all Airflow variables that contain the following strings:
```

2023-06-26 11:26 UTC, jwitz commented on learn/airflow-variables.md
> +See also [Masking sensitive data](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/security/secrets/mask-sensitive-values.html).
```suggestion
This list can be extended by adding comma separated strings to the [`sensitive_var_conn_names`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#sensitive-var-conn-names) configuration. See [Masking sensitive data](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/security/secrets/mask-sensitive-values.html).
```

2023-06-26 11:26 UTC, jwitz commented on static/img/guides/airflow-variables_UI.png
This screenshot could be cropped in half to only show the left side.

2023-06-26 11:26 UTC, jwitz requested changes
Overall LGTM! There's just so much content here that I wanna take a second look after the comments are addressed

2023-06-29 10:59 UTC, TJaniF reviewed
Thank you so much @jwitz :) 
I accepted almost all of your suggestions and added a few comments. Happy to chat about them ofc! :)

2023-06-29 10:59 UTC, TJaniF commented on learn/airflow-variables.md
> +To programmatically retrieve an Airflow variable, you can either use the `.get()` method of the Airflow Variable model or you can pull the Variable value directly from the [Airflow context](airflow-c
uppercased as per our Slack discussion :)

2023-06-29 10:59 UTC, TJaniF commented on learn/airflow-params.md
> +A boolean type param will create a toggle in the Trigger DAG UI.
I standardized on **Trigger DAG w/config** UI, hope that works :)

2023-06-30 10:11 UTC, jwitz approved these changes
LGTM! Just double check how the screenshots appear in the preview pages before publishing- noticing some large screenshots throughout

2023-06-30 10:11 UTC, jwitz commented on learn/airflow-variables.md
> +Aside from Airflow Variables, there are other ways of storing information in Airflow. The ideal option often depends on what type of information you are storing and where and how you want to access i
```suggestion
Aside from Airflow Variables, there are other ways of storing information in Airflow. The ideal option depends on what type of information you are storing and where and how you want to access it:
```

2023-06-30 10:11 UTC, jwitz commented on static/img/guides/airflow-params_trigger_dag_w_config.png
Needs a resize

2023-06-30 10:11 UTC, jwitz commented on static/img/guides/airflow-variables_UI.png
Needs a resize

2023-06-30 13:33 UTC, merged