Use case: Databricks
astronomer/docs pull request #2455
Opened 2023-06-20 14:25 UTC by TJaniF

2023-06-20 19:52 UTC, kentdanas approved these changes
LGTM! Good to move on to copy edit

2023-06-20 19:52 UTC, kentdanas commented on learn/use-case-airflow-databricks.md
> +title: "ELT pipelines with Airflow, Databricks, the Astro Databricks provider, and the Astro Python SDK"
```suggestion
title: "ELT pipelines with Airflow, the Astro Databricks provider, and the Astro Python SDK"
```
I think "databricks" is implied along with the Astro Databricks provider

2023-06-20 19:52 UTC, kentdanas commented on learn/use-case-airflow-databricks.md
> +[Databricks](https://databricks.com/) is a popular unified data and analytics platform built around fully managed Apache Spark clusters. With the [Astro Databricks provider](https://github.com/astron
```suggestion
[Databricks](https://databricks.com/) is a popular unified data and analytics platform built around fully managed Apache Spark clusters. With the [Astro Databricks provider](https://github.com/astronomer/astro-provider-databricks) package you can create a Databricks Workflow from existing Databricks notebooks as a task group in your Airflow DAG, allowing you to use Airflow's orchestration capabilities in combination with Databricks' cheapest compute. The open-source [Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/index.html) greatly simplifies common ELT tasks like loading data and allows users to easily use Pandas on data stored in a data warehouse. 
```

2023-06-20 19:52 UTC, kentdanas commented on learn/use-case-airflow-databricks.md
> +First, all three separate CSV files, each containing the energy percentages for a list of countries for solar, hydro and wind power respectively are loaded into a new temporary table in the data ware
```suggestion
First, three separate CSV files, each containing the energy percentages by country for solar, hydro, and wind power respectively, are loaded into a new temporary table in the data warehouse using the [Astro Python SDK `load file` operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html). The operator uses [dynamic task mapping](dynamic-tasks.md) to create a mapped task instance for each file provided to the `input_file` parameter of the `.expand` method, which are then executed in parallel.
```

2023-06-20 19:52 UTC, kentdanas commented on learn/use-case-airflow-databricks.md
> +- Webinar: [The easiest way to orchestrate your dbt workflows from Airflow](https://www.astronomer.io/events/webinars/how-to-orchestrate-databricks-jobs-using-airflow/).
```suggestion
- Webinar: [How to Orchestrate Databricks Jobs Using Airflow](https://www.astronomer.io/events/webinars/how-to-orchestrate-databricks-jobs-using-airflow/).
```

2023-06-21 12:07 UTC, TJaniF reviewed
Thank you for the review @kentdanas :) I accepted everything. 

@jwitz ready for you :)

2023-06-21 12:07 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +title: "ELT pipelines with Airflow, Databricks, the Astro Databricks provider, and the Astro Python SDK"
👀 hmm... oh no I have to pick a side 😅 . I kinda lean towards using Astro Databricks provider, because while it is an implementation way, it is like Cosmos, a provider that is very new and can do pretty amazing things, so whether someone uses this provider or the community-managed Databricks provider does make quite a difference, in my opinion.

2023-06-21 12:07 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +- Access to an [object storage supported by the Astro Python SDK](https://astro-sdk-python.readthedocs.io/en/stable/supported_file.html). This tutorial uses an [AWS S3](https://aws.amazon.com/s3/) bu
github being github, double suggestion :)

2023-06-21 12:07 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +- Tutorial: [Orchestrate dbt Core jobs with Airflow and Cosmos](airflow-databricks.md).
🤦

2023-06-21 12:07 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +- Webinar: [The easiest way to orchestrate your dbt workflows from Airflow](https://www.astronomer.io/events/webinars/how-to-orchestrate-databricks-jobs-using-airflow/).
Leave it to me to somehow change the links but not see the link titles...

2023-06-22 14:12 UTC, jwitz requested changes
@TJaniF I made a lot of changes to the descriptions here, so definitely tag me if I missed the mark. Mainly requesting changes on the `.env` instructions, which I missed when I worked on the first use case doc

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +The third task is defined with the [Astro Python SDK ExportToFileOperator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) to export the data from the three tempora
```suggestion
The third task uses the [Astro Python SDK ExportToFileOperator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) to export data from the three temporary tables to an object storage. 

The [`.map` method](dynamic-tasks.md#transform-outputs-with-map) converts the output of `country_tables` to a list of dictionaries containing the `input_data` and `output_file` parameters for each task instance. The [`.expand_kwargs` method](dynamic-tasks.md#sets-of-keyword-arguments) then dynamically maps tasks based on each pair of `input_data` and `output_file`. 
```

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +        lambda x: {
Never seen this (`lambda`) before and it doesn't even appear in Airflow docs. Is it worth elaborating on?

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +- `join_data`: This task executes the first notebook in the Databricks Workflow, which joins the data from the three CSV files created in the object storage into a single CSV file. View the full note
```suggestion
- `join_data`: This task executes the first notebook in the Databricks Workflow, which joins the data from the three CSV files created in the object storage into a single CSV file. View the full notebook code [here](https://github.com/astronomer/learn-airflow-databricks-tutorial/blob/main/databricks_notebook_code/join_data_notebook_code.py). Note that if you are using an object storage other than S3 you will need to make changes to the code enclosed in `# --------- AWS S3 specific --------- #`.
```

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +- `transform_data`: This task executes the second notebook in the Databricks Workflow, which fetches the CSV created by the `join_data` task, creates a new column `SHW%` by summing the % points for s
```suggestion
- `transform_data`: This task executes the second notebook in the Databricks Workflow, which fetches the CSV created by the `join_data` task, creates a new column `SHW%` by summing the % points for solar, hydro, and wind energy for each year, and saves the result as a CSV in the object storage. View the full notebook code [here](https://github.com/astronomer/learn-airflow-databricks-tutorial/blob/main/databricks_notebook_code/transform_data_notebook_code.py). Just like in the previous notebook, you might have to adjust this for other object storage solutions.
```

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +The `delete_intake_files_S3` task cleans up files no longer needed in the S3 bucket using the [S3DeleteObjectsOperator](https://registry.astronomer.io/providers/apache-airflow-providers-amazon/versio
```suggestion
The `delete_intake_files_S3` task uses the [S3DeleteObjectsOperator](https://registry.astronomer.io/providers/apache-airflow-providers-amazon/versions/latest/modules/S3DeleteObjectsOperator) to clean up files which are no longer needed in the S3 bucket. If you use a different object storage solution, you will need to define this task using an operator from the corresponding provider. See the [Astronomer Registry](https://registry.astronomer.io/) to explore available providers and operators.
```

2023-06-22 14:12 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +The the `create_graph` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to load the information from the combi
```suggestion
The `create_graph` task uses the [Astro Python SDK dataframe operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) to load the information from the final CSV into a Pandas dataframe. The task creates a line plot of the % of solar, hydro, and wind energy in the specified country over time using [seaborn](https://seaborn.pydata.org/) and [matplotlib](https://matplotlib.org/), then saves the graph in the `include` folder of the project repository.
```

2023-06-22 22:29 UTC, TJaniF reviewed
Thank you for the review @jwitz ! I accepted all suggestions, I think they really help streamline the content :) 
Also addressed your question, I hope my explanations make sense, happy to elaborate more!

2023-06-22 22:29 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +The third task is defined with the [Astro Python SDK ExportToFileOperator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) to export the data from the three tempora
Thats... so so much better 😅

2023-06-22 22:29 UTC, TJaniF commented on learn/use-case-airflow-databricks.md
> +        lambda x: {
Oh! Good point. [Lambda expressions](https://docs.python.org/3/reference/expressions.html?highlight=lambda#lambda) are part of native Python, they are a lesser known way to write functions in one line. 

Basically instead of:

```python
def add_ten(x):
    return x + 10

print(add_ten(2))
```

You can write:

```python
add_ten = lambda x: x + 10
print(add_ten(2))
```

Or even skip naming the function entirely, like I did in `.map`, that is the most common use case, anonymous functions you just need once defined directly where they are needed:

```python
print((lambda x: x + 10)(2))
```

In `.map` `x` will be each element in the XComArg list of `country_tables`. So I transform each table into a dictionary with the input data key being the table and the output file using the name of the table in its path. 

I think I'll add `in a lambda function` or something like that in the sentence above and link the word to the Python docs :)

2023-06-23 03:59 UTC, kentdanas commented
@TJaniF @jwitz github wouldn't let me directly reply to the .env thread 🙄 ....but, we definitely don't want to have a repo where it's easy for people to accidentally push their secrets. Tamara, do you know if you run an `astro dev init` over the top of an existing project, will it create an .env file if there isn't one already? If it does, that could be an alternative to what you have here. Otherwise I think your solution is probably best for safety purposes.

2023-06-23 07:00 UTC, TJaniF commented
> @TJaniF @jwitz github wouldn't let me directly reply to the .env thread 🙄 ....but, we definitely don't want to have a repo where it's easy for people to accidentally push their secrets. Tamara, do you know if you run an `astro dev init` over the top of an existing project, will it create an .env file if there isn't one already? If it does, that could be an alternative to what you have here. Otherwise I think your solution is probably best for safety purposes.

I just tested it and yes, `astro dev init` creates the missing .env file (and the two example DAGs). So we could have the instructions be something like: run astro dev init to generate .env and then copy from .env_example and fill in your own credentials 🤔 
Not sure if that or creating the file directly is more intuitive. I don't think I have a strong opinion here, either works for me. :)

2023-06-23 09:24 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +Clone the example project from this [Astronomer GitHub repo](https://github.com/astronomer/learn-airflow-databricks-tutorial). Make sure to create a file called `.env` with the contents of the `.env_
I am probably missing a key detail here, but if the `.env` is already in `.gitignore`, why don't we just keep it there and rename `.env_example` to `.env`? If it's ignored it won't pushed up to GH right?

2023-06-23 09:24 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +Clone the example project from this [Astronomer GitHub repo](https://github.com/astronomer/learn-airflow-databricks-tutorial). Make sure to create a file called `.env` with the contents of the `.env_
Regardless of what we do, we should make it more clear that the reason we're asking users to do this is security related.

2023-06-23 09:31 UTC, jwitz commented
@TJaniF @kentdanas What if we told users to manually download the `.env` file, which also lets us explain that it's added to .gitignore in the same breath? It's finnicky but in a different way that seems more native to the Astro project experience.

2023-06-23 15:11 UTC, kentdanas commented
> @TJaniF @kentdanas What if we told users to manually download the `.env` file, which also lets us explain that it's added to .gitignore in the same breath? It's finnicky but in a different way that seems more native to the Astro project experience.

I think the issue is that the `.env` file isn't in the repo for users to download, because it's git ignored. So we need to tell them to manually create it. @TJaniF I wonder if you un-ignore the env file, push so it's in the repo, and then re-add to gitignore, will it ignore any further changes to the file?

2023-06-26 08:48 UTC, TJaniF commented
@jwitz @kentdanas 
as we discussed last week, I added a sentence explaining why users have to create the .env file themselves. I also made some changes to the code (and the repo) to use named tables for the first 3 tasks because Marc flagged an error that occurs (but only when you run the DAG for the first time, it is a little odd, but I was able to reproduce the error, so better safe than sorry). I also went for named CSVs while at it to prevent the S3 bucket from filling up with every DAG run (another great suggestion from Marc :).

2023-06-27 10:41 UTC, jwitz approved these changes
The env breakdown LGTM!

2023-06-27 10:41 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +First, three separate CSV files, each containing the energy percentages by country for solar, hydro, and wind power respectively, are loaded into new tables in the data warehouse using the [Astro Pyt
```suggestion
First, three separate CSV files, each containing the energy percentages by country for solar, hydro, and wind power respectively, are loaded into new tables in the data warehouse using the [Astro Python SDK `load file` operator](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/load_file.html). The operator uses [dynamic task mapping](dynamic-tasks.md) to create a mapped task instance for each dictionary in the list provided to the `.expand_kwargs` method. These tasks are then executed in parallel.
```

2023-06-27 10:41 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +- Access to a Databricks workspace. See [Databricks' documentation](https://docs.databricks.com/getting-started/index.html) for instructions. You can use any workspace that has access to the [Databri
```suggestion
- Access to a Databricks workspace. See [Databricks documentation](https://docs.databricks.com/getting-started/index.html) for instructions. You can use any workspace that has access to the [Databricks Workflows](https://docs.databricks.com/workflows/index.html) feature. You need a user account with permissions to create notebooks and Databricks jobs. You can use any underlying cloud service, and a [14-day free trial](https://www.databricks.com/try-databricks) is available.
```

2023-06-27 10:41 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +Clone the example project from this [Astronomer GitHub repo](https://github.com/astronomer/learn-airflow-databricks-tutorial). Make sure to create a file called `.env` with the contents of the `.env_
```suggestion
Clone the example project from the [Astronomer GitHub](https://github.com/astronomer/learn-airflow-databricks-tutorial). 

## Edit the project

The project contains a file called `.env_example` which includes placeholder values for your credential details. After you clone the project, create a file called `.env`, copy the contents of `.env_example` into it, and delete `.env_example`. This is required because only `.env` is included in the list of files which Git will ignore when creating commits (`.gitignore`), and cloning an `.env` file directly will cause it to not be ignored the next time you push it to a Git repository.
```

2023-06-27 10:41 UTC, jwitz commented on learn/use-case-airflow-databricks.md
> +Clone the example project from this [Astronomer GitHub repo](https://github.com/astronomer/learn-airflow-databricks-tutorial). Make sure to create a file called `.env` with the contents of the `.env_
I want to make sure that users don't ignore the steps, so I moved the actionable information into an actionable topic. Feel free to override!

2023-06-28 13:14 UTC, merged