Fix Azure installation guide
astronomer/docs pull request #246
Opened 2021-12-20 15:57 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/218
Resolves https://github.com/astronomer/docs/issues/219

Some improvements to our Azure installation guide, mainly in ways which make it consistent with our other installation guides.

2021-12-20 16:17 UTC, aspain commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
@jwitz for the "Configure the Database" section, it mentions all of the options available for `sslmode` - should we remove this sentence since we are asking that they use `prefer` all of the time?

```
Possible values for sslmode are: disable, allow, prefer, require (for Flexible Server), verify-ca, verify-full. 
```

2021-12-20 16:17 UTC, aspain commented on enterprise/install-azure-standard.md
> +## Step 6: Retrieve Your SMTP URI
@jwitz I noticed GCP could also use this same treatment, can you add the same SMTP section from AWS to the GCP install guide as well ?
https://docs.astronomer.io/enterprise/install-gcp

2021-12-20 16:19 UTC, park-peter requested changes
Other than the one change request I made, LGTM. We will need to make the same change for 0.25 documentation as well.

2021-12-20 16:19 UTC, park-peter commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
Change `require (for Flexible Server)` to `require` and `prefer` to `prefer (for Flexible Server)`

2021-12-20 16:51 UTC, jwitz commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
@park-peter Do we need to update install guides for earlier releases? I figured that any new customer would only install the latest Enterprise version.

2021-12-20 16:53 UTC, jwitz commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
Also might go with @aspain 's idea hear of removing the sentence entirely, since we only ever want them setting the value to `prefer`.

2021-12-20 16:57 UTC, park-peter commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
Yeah, we can remove this sentence as it may cause more confusion than necessary. As for the update to 0.25 documentation, it's up to you, but at least for the prefer vs require, it's a setting that will break their installation so we don't want any LTS users to have wrong information.

2021-12-20 17:05 UTC, fritz-astronomer approved these changes

2021-12-20 17:33 UTC, dintorf approved these changes

2021-12-20 19:16 UTC, aspain approved these changes
changes look good

2021-12-21 16:42 UTC, aspain commented on enterprise/install-azure-standard.md
> +- If you provision Azure Database for PostgreSQL - Flexible Server, it enforces TLS/SSL and requires that you set `sslmode` to `prefer` in your `config.yaml`. Possible values for `sslmode` are: `disa
@jwitz I agree with @park-peter that we should update .25 docs as well just to avoid any troubleshooting that may happen as a result

2021-12-21 17:20 UTC, park-peter approved these changes

2021-12-21 17:26 UTC, jwitz commented
Will merge this once https://github.com/astronomer/docs/pull/197 merges, will then push changes to both 0.25 and 0.27

2021-12-21 18:37 UTC, merged