Fixed Customize Image example using incorrect expression for Debian-based imaages
astronomer/docs pull request #246
Opened 2021-02-11 20:57 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/217

Our example `Dockerfile.build` included lines that were specific to an Alpine-based image, even though the steps used a Debian-based image as an example. I've replaced these lines and included a note below the example file that explains what to do if you're using an Alpine-based image.

2021-02-15 17:20 UTC, paolaperaza approved these changes
Awesome, thanks for doing this @jwitz ! One tiny copy suggestion, but this looks good to me assuming the change from `apk update` > `apt get` for Debian is technically sound!

2021-02-15 17:20 UTC, paolaperaza commented on enterprise/next/02_develop/02_customize-image.md
> +This setup assumes you're using a Debian-based image. For example, for Airflow 1.10.12 this would be:
```suggestion
This setup assumes you're using a Debian-based Astronomer Certified image. With an Airflow 1.10.12 image, for example, this would be:
```

2021-02-15 17:25 UTC, vparekh94 requested changes

2021-02-15 17:25 UTC, vparekh94 commented on enterprise/next/02_develop/02_customize-image.md
> +RUN cat packages.txt | xargs apt-get install --no-cache
@jwitz i know i told you otherwise, but as I'm reviewing this i don't think there's a `--no-cache` option in `apt-get`

2021-02-15 19:46 UTC, jwitz commented on enterprise/next/02_develop/02_customize-image.md
> +RUN cat packages.txt | xargs apt-get install --no-cache
```suggestion
RUN cat packages.txt | xargs apt-get install
```

2021-02-15 19:48 UTC, jwitz commented on enterprise/next/02_develop/02_customize-image.md
> +RUN cat packages.txt | xargs apt-get install --no-cache
@vparekh94 thanks for catching this! I think everything should be in order now for approving the PR.

2021-03-01 23:05 UTC, vparekh94 approved these changes

2021-03-01 23:08 UTC, merged