initial commit
astronomer/docs pull request #2461
Opened 2023-06-21 10:27 UTC by manmeetkaur

2023-06-21 14:03 UTC, chomipi88 commented on astro/reference-astro-glossary.md
> +| Standard cluster | A standard cluster is mult-tenant, running Deployments from multiple Organizations and is available of Astro Hosted. See [Standard cluster configurations](resource-reference-host
```suggestion
| Standard cluster | A standard cluster is multi-tenant, running Deployments from multiple Organizations and is available of Astro Hosted. See [Standard cluster configurations](resource-reference-hosted#standard-cluster-configurations). |
```

2023-06-21 14:03 UTC, chomipi88 commented on astro/reference-astro-glossary.md
> +| Worker Type | A worker type is the designated machine type for all worker nodes in a worker node pool. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). On Astr
```suggestion
| Worker Type | A worker type is the designated machine type for all worker nodes in a worker node pool. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). On Astro Hybrid, worker types are defined by the cloud a customer uses for running Deployments (For example, m5.xlarge or e2-standard-4). |
```

2023-06-21 20:24 UTC, cmarteepants commented on astro/reference-astro-glossary.md
> +| Worker Type | A worker type is the designated machine type for all worker nodes in a worker node pool. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). On Astr
> A worker type is the designated machine type for all worker nodes in a worker node pool. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). On Astro Hybrid, worker types are defined by the cloud a customer uses for running Deployments (For example, m5.xlarge or e2-standard-4).

I find the wording odd - how about something like this?

> The worker type defines the quantity of resources a celery worker can consume. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). Each Ax type has a different configuration for memory, cpu and default number of concurrent tasks per celery worker. On Astro Hybrid, worker types are defined by the cloud node instance type that host celery workers and KubernetesPodOperator pods.

2023-06-21 21:00 UTC, kentdanas commented on learn/reference-airflow-glossary.md
> +| Dynamic DAGs| A Dynamic DAG is generated automatically during the parsing of the DAG file. Parsing could dynamically create different type and number of tasks based on the DAG params for the same D
I think it would be worth adding dynamic task mapping here as well.

2023-06-22 05:02 UTC, manmeetkaur commented on astro/reference-astro-glossary.md
> +| Worker Type | A worker type is the designated machine type for all worker nodes in a worker node pool. On Astro Hosted, worker types are defined in terms of Astronomer units (A5, A10, A20). On Astr
@cmarteepants agreed, that one looks way better. But I have a follow-up question - don't we want to explain about K8s executor?

2023-06-22 16:03 UTC, jwitz requested changes
Taking a look at the Airflow definitions tomorrow. In the meantime, can you:
- Make sure that the Airflow definitions are up to date based on the [glossary draft](https://docs.google.com/spreadsheets/d/17Sw-lxhtyreCNnvuxs6n36Lw6Otc0VQp9q_LgstsaFs/edit#gid=202258807)? I see some definitions which don't seem to match my edits there, and would rather not edit them 2x.
- Reformat the "See also" links so that we are hyperlinking the term when possible (See my Astro edits for examples). This minimizes the space of each definition and makes thinks easier to maintain.

2023-06-22 16:03 UTC, jwitz commented on astro/reference-astro-glossary.md
> +| Workspace | Workspaces are collections of Deployments that can be accessed by a specific group of users. Workspaces can be used to group Deployments that share a business use case or environment tr
```suggestion
| Workspace | [Workspaces](manage-workspaces.md) are collections of Deployments that can be accessed by a specific group of users. Workspaces can be used to group Deployments that share a business use case or environment trait. |
```

2023-06-22 20:14 UTC, cmarteepants approved these changes

2023-06-23 04:37 UTC, manmeetkaur commented
> Taking a look at the Airflow definitions tomorrow. In the meantime, can you:
> 
> * Make sure that the Airflow definitions are up to date based on the [glossary draft](https://docs.google.com/spreadsheets/d/17Sw-lxhtyreCNnvuxs6n36Lw6Otc0VQp9q_LgstsaFs/edit#gid=202258807)? I see some definitions which don't seem to match my edits there, and would rather not edit them 2x.
> * Reformat the "See also" links so that we are hyperlinking the term when possible (See my Astro edits for examples). This minimizes the space of each definition and makes thinks easier to maintain.

@jwitz it seems like you changed in the glossary draft after I used it to create the PR. So double work for me! 😄 

- I have changed the links
- Repulled the definitions from glossary. There are some additions to few of the definitions, that I have kept though.

2023-06-23 10:13 UTC, jwitz approved these changes
This is looking great @manmeetkaur 🤩 let's wait until after our check-in with pao to merge

2023-06-23 10:13 UTC, jwitz commented on astro/reference-astro-glossary.md
> +
```suggestion
The following table contains definitions for all of the key terms and concepts you'll come across on Astro. For a glossary of Apache Airflow terms, see [Airflow glossary](https://docs.astronomer.io/learn/airflow-glossary).

## Astro glossary table
```

2023-06-23 11:19 UTC, manmeetkaur commented on sidebarsLearn.js
> +            'airflow-ui'
@jwitz so @kentdanas asked to move it above the "ui" to alphebatize after "glossary". So we need to come to a decision.  :)

2023-06-26 15:32 UTC, jwitz approved these changes

2023-06-26 15:32 UTC, jwitz commented on astro/astro-glossary.md
> +| Dedicated Cluster | A [dedicated cluster](create-dedicated-cluster.md) are a cluster type available on Astro Hosted. They are hosted on Astronomer's cloud and run Deployments only from a single Org
```suggestion
| Dedicated Cluster | A [dedicated cluster](create-dedicated-cluster.md) is a cluster type available on Astro Hosted. A dedicated cluster is hosted on Astronomer's cloud and runs Deployments only from a single Organization.  |
```

2023-06-26 15:32 UTC, jwitz commented on astro/astro-glossary.md
> +| Deployment | An [Astro Deployment](create-deployment.md) is an Airlfow environment that is powered by all core Airflow components, including a webserver, scheduler, triggerer, and one or more worke
```suggestion
| Deployment | An [Astro Deployment](create-deployment.md) is an Airflow environment that is powered by all core Airflow components, including a webserver, scheduler, triggerer, and one or more workers running in its own isolated namespace in a cluster. Astro users can deploy DAGs to a Deployment, and can have one or more Deployments within a Workspace. |
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +| Dynamic DAG | A [Dynamic DAG](dynamically-generating-dags.md) is a DAG instance that is generated automatically during the parsing of the DAG file. Parsing could dynamically create different type a
```suggestion
| Dynamic DAG | A [Dynamic DAG](dynamically-generating-dags.md) is a DAG instance that is generated automatically during the parsing of the DAG file. |
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +| Scheduler| The scheduler is Airflow component responsible for scheduling job and task instances. It is a multi-threaded Python process that determines what tasks need to be run, when they need to b
```suggestion
| Scheduler| The scheduler is the Airflow component responsible for scheduling job and task instances. It is a multi-threaded Python process that determines what tasks need to be run, when they need to be run, and where they are run. |
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +| Notifier| A [notifier](error-notifications-in-airflow#notifiers) is a custom class that can be used to standardize and modualrize functions for sending notifications from tasks. |
```suggestion
| Notifier| A [notifier](error-notifications-in-airflow#notifiers) is a custom class that can be used to standardize and modularize functions for sending notifications from tasks. |
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +| Task| A task is the basic unit of execution in Airflow. Tasks are arranged into DAGs, and then have upstream and downstream dependencies set between them into order to express the order in which th
```suggestion
| Task| A task is the basic unit of execution in Airflow. Tasks are arranged into DAGs, and then have upstream and downstream dependencies set between them to express the order in which they should run. |
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +| TaskFlow API| The [TaskFlow API](dags.md#writing-dags-with-the-taskflow-api) is a framework for using decorators to define DAGs and tasks. Copared to using traditional operators, using the TaskFlow
```suggestion
| TaskFlow API| The [TaskFlow API](dags.md#writing-dags-with-the-taskflow-api) is a framework for using decorators to define DAGs and tasks. Compared to using traditional operators, using the TaskFlow API simplifies the process for passing data between tasks and defining dependencies. |
```

2023-06-26 15:32 UTC, jwitz commented on astro/astro-glossary.md
> +## Astro glossary table
```suggestion
```

2023-06-26 15:32 UTC, jwitz commented on learn/airflow-glossary.md
> +
```suggestion
```

2023-06-26 15:33 UTC, jwitz commented on sidebarsLearn.js
> +            'airflow-ui'
I'll defer to her then!

2023-06-26 17:10 UTC, kentdanas approved these changes

2023-06-26 17:10 UTC, kentdanas commented on learn/airflow-glossary.md
> +| Airflow Connection| An [Airflow connections](connections.md) is a set of configurations and credentials that allows Airflow to connect with other tools in the data ecosystem. |
```suggestion
| Airflow Connection| An [Airflow connection](connections.md) is a set of configurations and credentials that allows Airflow to connect with other tools in the data ecosystem. |
```

2023-06-26 17:10 UTC, kentdanas commented on learn/airflow-glossary.md
> +| Triggerer| The triggerer is an optional Airflow component responsible for running [deferrable operators](deferrable-operators#terms-and-concepts) when they're in a deferred state. |
I think "deferrable operator" should also be its own line in here, especially so we can note they're also referred to as "async operators"

2023-06-26 17:10 UTC, kentdanas commented on learn/airflow-glossary.md
> +| Dynamic task | A [Dynamic task](dynamic-tasks#dynamic-task-concepts) is a task instance that's generated at runtime based on a set of parameters in DAG code. It allows users to create an arbitrary
```suggestion
| Dynamic task | A [Dynamic task](dynamic-tasks#dynamic-task-concepts) is a task instance that's generated at runtime based on a set of parameters in DAG code. Dynamic task mapping, the Airflow feature that creates dynamic tasks, allows users to create an arbitrary number of parallel tasks at runtime based on an input parameter. |
```

2023-06-26 17:10 UTC, kentdanas commented on learn/airflow-glossary.md
> +| Airflow Variable| An Airflow variable is a generic key value pair that's stored in the Airflow metadata database. |
We'll have a new guide on Airflow variables published shortly that we can link to here - noting so we remember to add that if this gets published first :)

2023-06-26 17:10 UTC, kentdanas commented on sidebarsLearn.js
> +    'airflow-glossary'
I think I would move this up, maybe right below Overview?

2023-06-27 08:45 UTC, jwitz commented on learn/airflow-glossary.md
> +| Deferrable operators | A [Deferrable or an Async operator](deferrable-operators.md) is an operator with the ability to suspend itself while waiting for a job status and resume on receiving the job
```suggestion
| Deferrable operators | A [deferrable operator](deferrable-operators.md), also known as an async operator, is an operator thats suspends itself while waiting for a job status and resumes on receiving the job status. Tasks that use deferrable operators don't occupy a worker slot when they are in a deferred state. Instead, deferred tasks use the triggerer to poll for job statuses. |
```

2023-06-27 08:48 UTC, jwitz commented on learn/airflow-glossary.md
> +| Executor| An [Executor](airflow-executors-explained) is the Airflow component that's responsible for running the work contained within tasks. |
```suggestion
| Executor| An [Executor](airflow-executors-explained.md) is the Airflow component that's responsible for running the work contained within tasks. |
```
Let's make sure all of these are the explicit links instead of relative links..

2023-06-27 10:15 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| DAG Bundle Version | A DAG Bundle Version is a unique timestamp generated by the Astro CLI after a user completes a DAG-only deploy. This value exists only when [DAG-only deploys](deploy-code#deplo
```suggestion
| DAG Bundle Version | A DAG Bundle Version is a unique timestamp generated by the Astro CLI after a user completes a DAG-only deploy. This value exists only when [DAG-only deploys](deploy-code.md#deploy-dags-only) are enabled for a Deployment. |
```

2023-06-27 10:16 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| High availability (HA) | [High availability (HA)](configure-deployment-resources#enable-high-availability) is a feature on Astro for ensuring that Deployments can run even in the event of an outage
```suggestion
| High availability (HA) | [High availability (HA)](configure-deployment-resources.md#enable-high-availability) is a feature on Astro for ensuring that Deployments can run even in the event of an outage. On Astro Hosted, HA can be enabled or disabled per Deployment. |
```

2023-06-27 10:16 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| Worker Node Pool | A [worker node pool](manage-hybrid-clusters#about-worker-node-pools) is a Kubernetes node pool that's used to run worker nodes of the same type on Astro Hybrid. Each worker node
```suggestion
| Worker Node Pool | A [worker node pool](manage-hybrid-clusters.md#about-worker-node-pools) is a Kubernetes node pool that's used to run worker nodes of the same type on Astro Hybrid. Each worker node pool has a worker type and a maximum node count.  |
```

2023-06-27 10:17 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Dynamic task | A [Dynamic task](dynamic-tasks#dynamic-task-concepts) is a task instance that's generated at runtime based on a set of parameters in DAG code. Dynamic task mapping, the Airflow featu
```suggestion
| Dynamic task | A [Dynamic task](dynamic-tasks.md#dynamic-task-concepts) is a task instance that's generated at runtime based on a set of parameters in DAG code. Dynamic task mapping, the Airflow feature that creates dynamic tasks, allows users to create an arbitrary number of parallel tasks at runtime based on an input parameter. |
```

2023-06-27 10:17 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Hook| A [hook](what-is-a-hook) is an abstraction of a specific API that allows Airflow to interact with an external system. Hooks are built into many operators, but they can also be used directly i
```suggestion
| Hook| A [hook](what-is-a-hook.md) is an abstraction of a specific API that allows Airflow to interact with an external system. Hooks are built into many operators, but they can also be used directly in DAG code. |
```

2023-06-27 10:17 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Notifier| A [notifier](error-notifications-in-airflow#notifiers) is a custom class that can be used to standardize and modularize functions for sending notifications from tasks. |
```suggestion
| Notifier| A [notifier](error-notifications-in-airflow.md#notifiers) is a custom class that can be used to standardize and modularize functions for sending notifications from tasks. |
```

2023-06-27 10:18 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Sensor| An [Airflow Sensor](what-is-a-sensor) is a special kind of operator that is designed to wait for something to happen. When sensors run, they check to see if a certain condition is met befor
```suggestion
| Sensor| An [Airflow Sensor](what-is-a-sensor.md) is a special kind of operator that is designed to wait for something to happen. When sensors run, they check to see if a certain condition is met before they are marked successful and let their downstream tasks execute. |
```

2023-06-27 10:18 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Triggerer| The triggerer is an optional Airflow component responsible for running [deferrable operators](deferrable-operators#terms-and-concepts) when they're in a deferred state. |
```suggestion
| Triggerer| The triggerer is an optional Airflow component responsible for running [deferrable operators](deferrable-operators.md#terms-and-concepts) when they're in a deferred state. |
```

2023-06-27 10:18 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| XCom| [XCom](airflow-passing-data-between-tasks#xcom) is a built-in Airflow feature. XComs allow tasks to exchange task metadata or small amounts of data. They are defined by a key, value, and time
```suggestion
| XCom| [XCom](airflow-passing-data-between-tasks.md#xcom) is a built-in Airflow feature. XComs allow tasks to exchange task metadata or small amounts of data. They are defined by a key, value, and timestamp. |
```

2023-06-27 10:22 UTC, manmeetkaur commented on learn/airflow-glossary.md
> +| Deferrable operators | A [deferrable operator](deferrable-operators.md), also known as an async operator, is an operator thats suspends itself while waiting for a job status and resumes on receivin
```suggestion
| Deferrable operator | A [deferrable operator](deferrable-operators.md), also known as an async operator, is an operator thats suspends itself while waiting for a job status and resumes on receiving the job status. Tasks that use deferrable operators don't occupy a worker slot when they are in a deferred state. Instead, deferred tasks use the triggerer to poll for job statuses. |
```

2023-06-28 13:53 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro alerts | [Astro alerts](alerts.md) are customizable Slack and Pagerduty alerts for Deployments running on Astro. Unlike Airflow alerts, Astro alerts are configured directly from the Cloud UI
```suggestion
| Astro alerts | [Astro alerts](alerts.md) are customizable alerts for Deployments running on Astro. Unlike Airflow alerts, Astro alerts are configured directly from the Cloud UI and require no changes to DAG code. |
```
We are about to add email alerts. To future proof this definition, let's remove references to specific integrations.

2023-06-28 14:04 UTC, paolaperaza reviewed
Don't kill me 😇 Got through half of it! Feel free to take/leave

2023-06-28 14:04 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Astro Runtime | [Astro Runtime](runtime-image-architecture.md) is an Astronomer-distributed Docker image for running Airflow. Compared to the Apache Airflow Docker image, Astro Runtime additionally
```suggestion
| Astro Runtime | [Astro Runtime](runtime-image-architecture.md) is a Docker image for running Airflow that's built and maintained by Astronomer. Every Astro project and Deployment is configured with a version of Astro Runtime. Compared to the Apache Airflow Docker image, Astro Runtime additionally includes smart Airflow configurations, pre-installed packages, a security manager for role-based access control (RBAC), and expedited vulnerability fixes. |
```

2023-06-28 14:04 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Astronomer Software | [Astronomer Software](https://docs.astronomer.io/software) is a product for running Apache Airflow in a private cloud or airgapped environment using Kubernetes. |
```suggestion
| Astronomer Software | [Astronomer Software](https://docs.astronomer.io/software) is Astronomer's commercial software offering for running Apache Airflow on Kubernetes in a private cloud or airgapped environment. The infrastructure required to run the service is hosted and managed entirely by your organization instead of by Astronomer. It is only recommended for extremely security conscious organizations running at a unique level of scale. |
```

2023-06-28 14:06 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| API key | An API key is a unique key ID and secret grants programmatic access to a Deployment. API keys will soon be deprecated in favor of Deployment-level API tokens. |
@paolaperaza so why not `at the Workspace or Organization level` ?

2023-06-28 14:18 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro | [Astro](https://www.astronomer.io/product/) is a SaaS application that runs fully-managed Apache Airflow environments in the cloud. Each Airflow environment runs in its own isolated Kuberne
Agreed with @manmeetkaur here. This might be the copy we want to share when advertising Astro, but it doesn't do much as a definition and definitely sticks out amongst the other terms here. We should be explicit about what exactly Astro is, which the first definition is closer to achieving.

2023-06-28 14:20 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro CLI | The [Astro CLI](cli/overview.md) is an open source command line interface used to run Airflow locally and manage various resources on Astro. |
What is "built by Astronomer for Apache Airflow" mean here that isn't already addressed by "used to run Airflow locally"?

2023-06-29 09:22 UTC, jwitz commented on astro/astro-glossary.md
> +| API token | An API token is an alphanumeric token that grants programmatic access to Astro. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-t
Hm the switch to "you can" here loses some of the specific definition, which is that the token is scoped to a specific entity. We already say it automates actions in the first sentence to some degree

2023-06-29 09:24 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro Hosted | [Astro Hosted](astro-architecture.md) is a version of Astro that's hosted and managed in Astronomer's cloud. |
I'd prefer:

```
| Astro Hosted | [Astro Hosted](astro-architecture.md) is a product line for Astro where the infrastructure required to run Airflow is fully managed by Astronomer in Astronomer's cloud. It is recommended for most teams running Airflow. |
```

2023-06-29 09:26 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro Hosted | [Astro Hosted](astro-architecture.md) is a version of Astro that's hosted and managed in Astronomer's cloud. |
It's not a "product line" if it's only one product right?

2023-06-29 09:26 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro Hybrid | [Astro Hybrid](hybrid-overview.md) is a version of Astro that's managed by Astronomer and hosted in the customer's cloud. |
I'd prefer

| Astro Hybrid | [Astro Hybrid](hybrid-overview.md) is a distribution of Astro where the infrastructure required to run Airflow is fully managed by Astronomer and hosted in your organization's cloud. It is recommended for security-conscious teams running at scale. |

2023-06-29 09:28 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro project | An [Astro project](develop-project.md) contains the set of files necessary to run Airflow, including dedicated folders for the DAG files, plugins, and dependencies. A new Astro proj
I updated this to cut the last sentence

2023-06-29 12:41 UTC, paolaperaza approved these changes

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Worker Queue | A [worker queue](configure-worker-queues.md) is a set of configurations that apply to a group of workers in a Deployment running the Celery executor. Within a worker queue, users can
```suggestion
| Worker Queue | A [worker queue](configure-worker-queues.md) is a set of configurations that apply to a group of workers in a Deployment running the Celery executor. Within a worker queue, you can configure worker type, worker size, and autoscaling behavior.|
```

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Deploy | A [deploy](deploy-code.md) is the process of pushing either an Astro project or DAG code to an Astro Deployment. |
```suggestion
| Deploy | A [deploy](deploy-code.md) is the process of pushing  code to a Deployment on Astro. You can either deploy all files in your Astro project or just your DAG code.
```

- Not sure there's a better way to say it but it's "a code push" not "the process" right?

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Deployment | An [Astro Deployment](create-deployment.md) is an Airflow environment that is powered by all core Airflow components, including a webserver, scheduler, triggerer, and one or more worke
```suggestion
| Deployment | An [Astro Deployment](create-deployment.md) is an Airflow environment that is powered by all core Airflow components, including schedulers and workers. Astro users can deploy DAGs to a Deployment, and can have one or more Deployments within a Workspace. |
```

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Deployment | An [Astro Deployment](create-deployment.md) is an Airflow environment that is powered by all core Airflow components, including a webserver, scheduler, triggerer, and one or more worke
I think we can simplify this one and not mention the namespace thing? Esp with Hosted, I think it's fine to leave out

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| Environment variable| An [environment variable](environment-variables.md) is a key-value pair that defines a configuration for a Deployment.  |
```suggestion
| Environment variable| An [environment variable](environment-variables.md) is a key-value pair that you can create in the Cloud UI and defines a configuration for a Deployment. You can use environment variables to set Airflow configurations.|
```

2023-06-29 12:41 UTC, paolaperaza commented on astro/astro-glossary.md
> +| High availability (HA) | [High availability (HA)](configure-deployment-resources.md#enable-high-availability) is a feature on Astro for ensuring that Deployments can run even in the event of an out
```suggestion
| High availability (HA) | [High availability (HA)](configure-deployment-resources.md#enable-high-availability) is a feature on Astro for ensuring that the components of a Deployment continue to run even in the event of an outage. On Astro Hosted, HA can be enabled or disabled per Deployment. |
```

2023-06-29 12:54 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| API token | An API token is an alphanumeric token that grants programmatic access to Astro. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-t
```suggestion
| API token | An API token is an alphanumeric token that grants programmatic access to Astro. It can be used to automate management of [Organization](organization-api-tokens.md) or [Workspace](workspace-api-tokens.md) using Astro CLI. |
```

2023-06-29 12:54 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| API token | An API token is an alphanumeric token that grants programmatic access to Astro. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-t
@paolaperaza @jwitz how about this way ? ^^

2023-06-29 13:01 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| Astro project | An [Astro project](develop-project.md) contains the set of files necessary to run Airflow, including dedicated folders for the DAG files, plugins, and dependencies. A new Astro proj
edited to include Astro CLI link

2023-06-29 13:05 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| Cluster | An Astro cluster is a fully managed Kubernetes cluster that runs Deployments either in a customer's cloud or Astronomer's cloud. |
updated suggestion to include links.

2023-06-29 13:06 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| DAG Bundle Version | A DAG Bundle Version is a unique timestamp generated by the Astro CLI after a user completes a DAG-only deploy. This value exists only when [DAG-only deploys](deploy-code.md#de
does the user need to know it is used "to identify the version of code that runs on Astro"

2023-06-29 13:39 UTC, manmeetkaur commented on astro/astro-glossary.md
> +| Data plane | The data plane, a component of [Astro Hybrid](hybrid-overview.md), is a single-tenant foundation in a customer's cloud for running multiple Airflow environments across clusters. A data
The data plane is a component of Astro Hybrid that refers to the infrastructure used to run multiple Airflow environments in customer's cloud. Different clouds and different regions can be part of the same Data plane. @jwitz @paolaperaza Thoughts ?

2023-06-29 14:13 UTC, jwitz commented on astro/astro-glossary.md
> +| API token | An API token is an alphanumeric token that grants programmatic access to Astro. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-t
I would just limit the usage to the first sentence: "An API token is an alphanumeric token grants programmatic access to Astro for automated workflows. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-tokens.md)"

2023-06-29 14:14 UTC, jwitz commented on astro/astro-glossary.md
> +| API token | An API token is an alphanumeric token that grants programmatic access to Astro. An API token can be scoped to a [Organization](organization-api-tokens.md) or [Workspace](workspace-api-t
Check my reply to Paola's to see if that works?

2023-06-29 14:15 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro | [Astro](https://www.astronomer.io/product/) is a SaaS application that runs fully-managed Apache Airflow environments in the cloud. Each Airflow environment runs in its own isolated Kuberne
Astro is a cloud-based SaaS application that provides fully managed Apache Airflow environments for teams of all sizes. To get started, [start a trial](https://www.astronomer.io/try-astro/).

2023-06-29 14:17 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro alerts | [Astro alerts](alerts.md) are customizable Slack and Pagerduty alerts for Deployments running on Astro. Unlike Airflow alerts, Astro alerts are configured directly from the Cloud UI
Updated with my preferred wording, p sure I didn't take out any specific content or points from the original edit

2023-06-29 14:19 UTC, jwitz commented on astro/astro-glossary.md
> +| Astro Hosted | [Astro Hosted](astro-architecture.md) is a version of Astro that's hosted and managed in Astronomer's cloud. |
I thought the "Product line" is Astro/ Astronomer, with the "products" being the variations you listed. In the same way that "Honda" is the product line for "Civic/ Accord/ HR-V"

2023-06-29 14:20 UTC, jwitz commented on astro/astro-glossary.md
> +| Cell | A [cell](cloud-ide/quickstart.md#step-3-create-a-python-cell) is a UI-based abstraction of an Airflow task that serves as the building block for Astro Cloud IDE pipelines. It can either comp
Updated suggestion

2023-06-29 14:22 UTC, jwitz commented on astro/astro-glossary.md
> +| Cluster | An Astro cluster is a fully managed Kubernetes cluster that runs Deployments either in a customer's cloud or Astronomer's cloud. |
I dont think second sentence ( Clusters run on AWS, GCP, or Azure and are fully managed by Astronomer. ) is true for Hosted. I also think "that hosts the infrastructure required to run Airflow on Astro." sounds identical to a Deployment.

2023-06-29 14:22 UTC, jwitz commented on astro/astro-glossary.md
> +| Cluster | An Astro cluster is a fully managed Kubernetes cluster that runs Deployments either in a customer's cloud or Astronomer's cloud. |
Updated the wording

2023-06-29 14:24 UTC, jwitz commented on astro/astro-glossary.md
> +| DAG Bundle Version | A DAG Bundle Version is a unique timestamp generated by the Astro CLI after a user completes a DAG-only deploy. This value exists only when [DAG-only deploys](deploy-code.md#de
Updated suggestion slightly

2023-06-29 14:25 UTC, jwitz commented on astro/astro-glossary.md
> +| Data plane | The data plane, a component of [Astro Hybrid](hybrid-overview.md), is a single-tenant foundation in a customer's cloud for running multiple Airflow environments across clusters. A data
```suggestion
| Data plane | The data plane is a component of [Astro Hybrid](hybrid-overview.md). It is a single-tenant foundation in a customer's cloud that runs multiple Airflow environments across clusters, regions, and clouds. |
```

2023-06-29 14:26 UTC, jwitz commented on astro/astro-glossary.md
> +| Deploy | A [deploy](deploy-code.md) is the process of pushing either an Astro project or DAG code to an Astro Deployment. |
Updated slightly

2023-06-29 14:28 UTC, jwitz commented on astro/astro-glossary.md
> +| Environment variable| An [environment variable](environment-variables.md) is a key-value pair that defines a configuration for a Deployment.  |
I think both of these additions are not really needed given how many other ways you can create them/ how many other things they can define. This feels unnecessarily limiting, so I'd rather keep it open-ended and let the docs explain more.

2023-06-29 14:28 UTC, jwitz commented on astro/astro-glossary.md
> +| Environment variable| An [environment variable](environment-variables.md) is a key-value pair that defines a configuration for a Deployment.  |
```suggestion
| Environment variable| An [environment variable](environment-variables.md) is a key-value pair that defines a configuration or value for a Deployment.  |
```

2023-06-30 05:32 UTC, merged