Added more SMTP setup steps to Enterprise installation guides
astronomer/docs pull request #247
Opened 2021-02-11 22:22 UTC by jwitz

This is a continuation of PR https://github.com/astronomer/docs/pull/45, where @pritt20 sought to add a new doc on SMTP configuration. Since this is a requirement for Enterprise installation, and since there wasn't much content, I decided to integrate his doc into the installation guide itself. 

If things look good here, I'll add this information to all installation guides in `0.23` and `next`.

2021-02-11 22:25 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +An SMTP service is required so that users can send and accept email invites to and from Astronomer. To integrate your SMTP service with Astronomer, make note of your SMTP service's URI and add it to
Do we need to mention Nodemailer? And by "Need" I mean: will it help anyone make a decision with regards to installation?

2021-02-12 18:53 UTC, pritt20 commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +An SMTP service is required so that users can send and accept email invites to and from Astronomer. To integrate your SMTP service with Astronomer, make note of your SMTP service's URI and add it to
Hey @jwitz I mentioned **Nodemailer** because we use 2 types of SMTP on our platform. Houston uses nodemailer under the hood whereas alertmanager uses **go smtp**, both have their own set of configuration :)

CC: @ianstanton

2021-02-15 17:15 UTC, paolaperaza requested changes
A few comments here, @jwitz ! The main thing I caught that needs to be changed is the set of K8s versions we say we support, which I realized is inconsistent with our version compatibility reference. Unrelated to this PR, but since it's a small change I figure we can fix it.

Otherwise, some small copy suggestions that you can take or leave. Will come back and review again later today if you end up making changes!

> Note: There were a few URL changes from `stable` path to `v0.23` for this doc in the `next` folder - was that intentional?

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +To set up TLS certificates this way, follow the guidelines in [Automatically Renew TLS Certificates Using Let's Encrypt](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/renew-tls-ce
```suggestion
To set up TLS certificates this way, follow the guidelines in [Automatically Renew TLS Certificates Using Let's Encrypt](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/renew-tls-cert#automatically-renew-tls-certificates-using-lets-encrypt). Make note of the certificate you create in this setup for Step 5.
```

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +An SMTP service is required so that users can send and accept email invites to and from Astronomer. To integrate your SMTP service with Astronomer, make note of your SMTP service's URI and add it to
```suggestion
A third-party SMTP service is required for Astronomer Enterprise so that email invitations to the platform can be sent and accepted by members of your team. To integrate your SMTP service with Astronomer, make note of your SMTP service's URI and add it to your `config.yaml` in Step 8. In general, an SMTP URI will take the following form:
```

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +The following table contains examples of what the URI will look like for some of the most popular SMTP services. If your SMTP provider is not listed, refer to the provider's documentation for informa
```suggestion
The following table contains examples of what the URI looks like for some of the most popular SMTP services:
```

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +| Custom SMTP-relay | `smtp://smtp-relay.example.com:25/?ignoreTLS=true`                                      |
```suggestion
| Custom SMTP-relay | `smtp://smtp-relay.example.com:25/?ignoreTLS=true`                                      |

If your SMTP provider is not listed, refer to the provider's documentation for information on creating an SMTP URI.
```

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
>  By default, Astronomer requires a central Postgres database that will act as the backend for Astronomer's Houston API and will host individual Metadata Databases for all Airflow Deployments spun up o
```suggestion
By default, Astronomer requires a central Postgres database that will act as the backend for Astronomer's Houston API and will host individual Metadata Databases for all Airflow Deployments created on the platform.
```

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +- Kubernetes 1.16 or later
```suggestion
- Kubernetes 1.16, 1.17, or 1.18
```

Based on: https://www.astronomer.io/docs/enterprise/v0.23/resources/version-compatibility-reference

2021-02-15 17:15 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +- Astronomer currently supports Kubernetes versions 1.14, 1.15, 1.16 and 1.17 on EKS.
```suggestion
- Astronomer currently supports Kubernetes versions 1.16, 1.17, and 1.18 on EKS. For more information, refer to [Version Compatibility Reference](https://www.astronomer.io/docs/enterprise/stable/resources/version-compatibility-reference).
```

2021-02-15 20:22 UTC, jwitz commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +An SMTP service is required so that users can send and accept email invites to and from Astronomer. To integrate your SMTP service with Astronomer, make note of your SMTP service's URI and add it to
Sounds good, if there's configuration considerations for each type of transporter then I agree we should list it somewhere. Updated the wording here to reflect that!

2021-02-15 20:25 UTC, jwitz commented
Loved the suggestions @paolaperaza , committed all of them. Only other change I made was adding info on Nodemailer, which @pritt20 said would be good to have somewhere in our docs.

2021-04-12 14:34 UTC, paolaperaza reviewed
@jwitz Realized this PR has been sitting a bit, so just took another look. The changes look great, but:

- Is the content in `/next` actually the same as `v0.23`? Found a couple of differences, and it'd be good to do another thorough review if you can - don't feel confident enough 2 merge
- Links in `/next` folder were all v0.23 (fixed em)

@jwitz Wanna give it another look? We should be close here.

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +- Airflow Deployments: `deployments.astro.mydomain.com/uniquely-generated-airflow-name/airflow`
```suggestion
- Airflow Deployments: `deployments.astro.mydomain.com/deployment-release-name/airflow`
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +This command will install the latest available patch version of Astronomer Enterprise v0.23. To override latest and specify a patch, add it to the `--version=` flag in the format of `0.23.x`. To inst
```suggestion
This command will install the latest available patch version of Astronomer Enterprise v0.23. To override latest and specify a patch, add it to the `--version=` flag in the format of `0.23.x`. To install Astronomer Enterprise v0.23.9, for example, specify `--version=0.23.9`. For information on all available patch versions, refer to [Enterprise Release Notes](/docs/enterprise/stable/resources/release-notes/).
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you are seeing issues here, check out our [guide on debugging your installation](/docs/enterprise/v0.23/troubleshoot/debug-install/).
```suggestion
If you are seeing issues here, check out our [guide on debugging your installation](/docs/enterprise/stable/troubleshoot/debug-install/).
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +If you have Airflow pods in an `ImagePullBackoff` state, check the pod description. If you see an x509 error, ensure that you added the `privateCaCertsAddToHost` key-value pairs to your Helm chart. I
```suggestion
If you have Airflow pods in an `ImagePullBackoff` state, check the pod description. If you see an x509 error, ensure that you added the `privateCaCertsAddToHost` key-value pairs to your Helm chart. If you missed these during installation, follow the steps in [Apply a Platform Configuration Change on Astronomer](https://www.astronomer.io/docs/enterprise/stable/manage-astronomer/apply-platform-config) to add them after installation.
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +- [Managing Users on Astronomer Enterprise](/docs/enterprise/v0.23/manage-astronomer/manage-platform-users/)
```suggestion
- [Renew TLS Certificates on Astronomer Enterprise](/docs/enterprise/stable/manage-astronomer/renew-tls-cert/)
- [Integrating an Auth System](/docs/enterprise/stable/manage-astronomer/integrate-auth-system/)
- [Configuring Platform Resources](/docs/enterprise/stable/manage-astronomer/configure-platform-resources/)
- [Managing Users on Astronomer Enterprise](/docs/enterprise/stable/manage-astronomer/manage-platform-users/)
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/01_install-aws-standard.md
> +For detailed guidelines on reaching out to Astronomer Support, reference our guide [here](/docs/enterprise/v0.23/resources/support/).
```suggestion
For detailed guidelines on reaching out to Astronomer Support, reference our guide [here](/docs/enterprise/stable/resources/support/).
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
> +- Kubernetes 1.16 or later
```suggestion
- Kubernetes 1.16, 1.17, or 1.18
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
> +- Airflow Deployments: `deployments.astro.mydomain.com/uniquely-generated-airflow-name/airflow`
```suggestion
- Airflow Deployments: `deployments.astro.mydomain.com/deployment-release-name/airflow`
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
> +- Astronomer currently supports Kubernetes versions 1.14, 1.15, 1.16 and 1.17 on EKS.
```suggestion
- Astronomer currently supports Kubernetes versions 1.16, 1.17, and 1.18 on EKS. For more information, refer to [Version Compatibility Reference](https://www.astronomer.io/docs/enterprise/v0.23/resources/version-compatibility-reference).
```

2021-04-12 14:34 UTC, paolaperaza commented on enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
> +The following table contains examples of what the URI will look like for some of the most popular SMTP services. If your SMTP provider is not listed, refer to the provider's documentation for informa
I think in `/next` we have this line at the bottom of the graph - makes more sense there?

2021-04-12 18:03 UTC, jwitz commented
Alright @paolaperaza I think this is ready to go! For some of your suggestions, it looked as if pulling from `main` resolved the issues.

2021-04-12 18:29 UTC, paolaperaza approved these changes
Ok sweet, this looks good to me @jwitz ! Caught one typo, but otherwise feel free to merge as soon as you're ready.

2021-04-12 18:29 UTC, paolaperaza commented on enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
> +- Airflow Deployments: `deployments.astro.mydomain.com/udeployment-release-name/airflow`
```suggestion
- Airflow Deployments: `deployments.astro.mydomain.com/deployment-release-name/airflow`
```

eep, typo - might have been me

2021-04-12 22:43 UTC, merged