Add pytest process for outputting coverage or other artifacts
astronomer/docs pull request #2498
Opened 2023-06-28 17:54 UTC by stuart23

There are no clear instructions on how to do this. See https://github.com/astronomer/astro-cli/issues/1142

2023-06-28 18:02 UTC, frankcash commented
https://docs.pytest.org/en/7.1.x/how-to/output.html#creating-junitxml-format-files

2023-06-28 19:42 UTC, frankcash approved these changes

2023-06-30 09:07 UTC, jwitz commented on astro/cli/astro-dev-pytest.md
> +This command runs `pytest` in a container. If your test is generating artifacts that you need to use (e.g. code coverage reports), these can be output to the `include` directory in the container so t
```suggestion
The command runs `pytest` in a container. If your test generates artifacts, such as code coverage reports, you can output the artifacts to the `include` folder of your Astro project so they can be accessed after the test has finished.
```
Is this right? If not, how would you access the `include` directory if it was in a container?

2023-06-30 09:07 UTC, jwitz requested changes
I made a suggestion that might include a change in technical meaning, so requesting changes to make sure that's all good before merging!

2023-07-05 22:20 UTC, stuart23 commented on astro/cli/astro-dev-pytest.md
> +This command runs `pytest` in a container. If your test is generating artifacts that you need to use (e.g. code coverage reports), these can be output to the `include` directory in the container so t
Exactly! The include dir is shared inside and outside the container and is therefore the only place we can pass stuff out of the test environment. Your changes look good

2023-07-06 09:29 UTC, jwitz approved these changes

2023-07-06 09:30 UTC, merged