Add Guidelines on Requests to Airflow 2.0 REST API
astronomer/docs pull request #250
Opened 2021-02-13 03:05 UTC by paolaperaza

Resolves: https://github.com/astronomer/docs/issues/248

This PR does a few things:
- Adds information to our existing "Airflow API" doc around Airflow's new REST API
- Reformats headers slightly to match our new "Step" framework and format

Based on feedback from customers + internal folks, and a popular forum post: https://forum.astronomer.io/t/can-i-use-the-airflow-rest-api-to-externally-trigger-a-dag/162/14

2021-02-15 16:12 UTC, jwitz commented on cloud/stable/01_get-started/02_cloud-faq.md
> +We offer authentication via Google, Github, and Local Username/Password. Once you've created a Workspace on Astronomer, you'll use that same method to authenticate to the Astronomer CLI.
```suggestion
We offer authentication via Google, Github, and Local Username/Password. Once you've created a Workspace on Astronomer with a given authentication method, you'll use that same method to authenticate to the Astronomer CLI.
```
Should "Local Username/Password" be lowercase?

2021-02-15 16:24 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +You can create a Service Account either via the Astronomer UI or the Astronomer CLI.
```suggestion
You can create a Service Account via either the Astronomer UI or the Astronomer CLI.
```

2021-02-15 16:24 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +To create a Service Account via the Astronomer UI, follow the steps below.
```suggestion
To create a Service Account via the Astronomer UI:
```

2021-02-15 16:24 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +3. Give your Service Account a **Name**, **User Role**, and    **Category** (_Optional_).
```suggestion
3. Give your Service Account a **Name**, **User Role**, and **Category** (_Optional_).
```

2021-02-15 16:24 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +2. Navigate to **Deployment** > **Service Accounts**.
```suggestion
2. Go to **Deployment** > **Service Accounts**.
```

2021-02-15 16:25 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +   ![Name Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-name-service-account.png)
```suggestion
   ![Name Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-name-service-account.png)
   
```

2021-02-15 16:25 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +4. Save the API Key that was generated. Depending on           your use case, you may want to store this key in an       Environment Variable or secret management tool of choice.
```suggestion
4. Save the API Key that was generated. Depending on your use case, you may want to store this key in an Environment Variable or secret management tool of choice.
```

2021-02-15 16:26 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +   ![Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-api-key.png)
```suggestion
   
   ![Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-api-key.png)
```

If you indent the image, it'll still appear with the step regardless of whether it appears directly under the step in MD.

2021-02-15 16:28 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +   ![Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-api-key.png)
If possible, can we add a box around the actual API Key field in this image?

2021-02-15 16:29 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +2. Identify your Airflow Deployment's **Deployment ID**. To do so, run:
```suggestion
2. Identify your Airflow Deployment's Deployment ID. To do so, run:
```
I've only been using bold text for UI elements - don't think we should use it for CLI elements.

2021-02-15 16:30 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +4.  Save the API Key that was generated. Depending on          your use case, you might want to store this key in an       Environment Variable or secret management tool of choice.
```suggestion
4.  Save the API Key that was generated. Depending on your use case, you might want to store this key in an Environment Variable or secret management tool of choice.
```

2021-02-15 16:31 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +Now that you've created a Service Account, you're free to generate both GET or POST requests to any supported endpoints in Airflow's [Rest API Reference](https://airflow.apache.org/docs/stable/rest-a
```suggestion
Now that you've created a Service Account, you're free to generate both `GET` or `POST` requests to any supported endpoints in Airflow's [Rest API Reference](https://airflow.apache.org/docs/stable/rest-api-ref.html) via the following base URL:
```

Thoughts on code styling REST actions?

2021-02-15 16:32 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +In the examples below, we'll refer to this URL as the **AIRFLOW-DOMAIN**, where you'll replace `deployment-release-name` with your own (e.g. `galactic-stars-1234`).
```suggestion
In the examples below, we'll refer to this URL as the `AIRFLOW-DOMAIN`.
```
Why are we mentioning `deployment-release-name` here?

2021-02-15 16:33 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +The command for your request would look like this:
```suggestion
The command for your request should look like this:
```

2021-02-15 16:34 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **AIRFLOW-DOMAIN**: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```suggestion
- `AIRFLOW-DOMAIN`: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```
Same for the other two variables.

2021-02-15 16:36 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **API-Key**: API Key from your Service Account
Same as above, should use code styling here. Also, we should probable include the `<`s in here, lets people think they need to keep those in their actual request.

2021-02-15 16:36 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +As of the momentous [Airflow 2.0 release](https://www.astronomer.io/blog/introducing-airflow-2-0), the Apache Airflow project now supports an official and more robust Stable REST API. Among other thi
```suggestion
As of its momentous [2.0 release](https://www.astronomer.io/blog/introducing-airflow-2-0), the Apache Airflow project now supports an official and more robust Stable REST API. Among other things, Airflow's new REST API:
```

2021-02-15 16:37 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +* Makes for easy access by third-parties
```suggestion
* Makes for easy access by third-parties.
```
All of these bullets should end in periods since we're finishing a sentence.

2021-02-15 16:38 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **AIRFLOW-DOMAIN**: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
Code styling on these variables. We should also include `<`s.

2021-02-15 16:39 UTC, jwitz requested changes
Overall content here looks good @paolaperaza! Added some comments and questions about little formatting things throughout. 

I can't comment where there was one typo since it technically wasn't part of the PR, but line 20 in the Cloud FAQ has a typo. Got that info from the spellcheck CI.

2021-02-15 17:24 UTC, wolfier commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +In the examples below, we'll refer to this URL as the **AIRFLOW-DOMAIN**, where you'll replace `deployment-release-name` with your own (e.g. `galactic-stars-1234`).
To clarify that everyone's Airflow domain is dependent on the deployment's release name.

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +   ![Name Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-name-service-account.png)
@jwitz Should this have a space? Wasn't sure

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **API-Key**: API Key from your Service Account
```suggestion
- `DAG-ID`: Name of your DAG (_case-sensitive_)
- `API-Key`: API Key from your Service Account
```

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **API-Key**: API Key from your Service Account
```suggestion
- `API-Key`: API Key from your Service Account
```

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **deployment-release-name**: Your Airflow Deployment Release Name
```suggestion
- `deployment-release-name`: Your Airflow Deployment Release Name
```

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +* Includes authorization capabilities
```suggestion
* Is based on the [Swagger/OpenAPI Spec](https://swagger.io/specification/).
* Implements CRUD (Create, Update, Delete) operations on *all* Airflow resources.
* Includes authorization capabilities.
```

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **AIRFLOW-DOMAIN**: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```suggestion
- `AIRFLOW-DOMAIN`: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```

2021-02-15 17:43 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- **API-Key**: API Key from your Service Account
```suggestion
- `API-Key`: API Key from your Service Account
```

2021-02-15 18:00 UTC, paolaperaza commented
Awesome, thanks for reviewing @jwitz! Good callouts throughout. Just applied changes to the Cloud version of this doc, and I think outstanding items are:

- Apply these changes to Enterprise
- Re-create "Service Accounts" screenshot with box/circle around API key for clarity

2021-02-16 01:36 UTC, paolaperaza commented
Alrighty @jwitz ! This is ready for your second review - added new screenshot and applied these changes to `/next/` and `/v0.23/` folders (not v0.16 since users can't upgrade to 2.0 yet on that version of the platform).

@wolfier Were you able to give this a quick look?

2021-02-16 23:17 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +To run this, replace:
```suggestion
To run this, update the following placeholder values with your own values:
```

2021-02-16 23:18 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +- `<API-Key>`: API Key from your Service Account
```suggestion
- `<API-Key>`: The API Key from your Service Account
```

2021-02-16 23:19 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +- `<AIRFLOW-DOMAIN>`: `https://<your-base-domain>/<deployment-release-name>`
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://<your-base-domain>/<deployment-release-name>`
```

2021-02-16 23:21 UTC, jwitz commented on enterprise/next/05_customize-airflow/07_airflow-api.md
> +To create a Deployment-level Service account via the Astronomer CLI, follow the steps below.
```suggestion
To create a Deployment-level Service account via the Astronomer CLI:
```

2021-02-16 23:21 UTC, jwitz commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +To create a Deployment-level Service account via the Astronomer CLI, follow the steps below.
```suggestion
To create a Deployment-level Service account via the Astronomer CLI:
```

2021-02-16 23:21 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +To create a Deployment-level Service account via the Astronomer CLI, follow the steps below.
```suggestion
To create a Deployment-level Service account via the Astronomer CLI:
```

2021-02-16 23:23 UTC, jwitz commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +   ![Name Service Account](https://assets2.astronomer.io/main/docs/ci-cd/ci-cd-name-service-account.png)
Four spaces before the line of text itself, plus a line of space before and after the link. That should render the spacing properly within the step.

2021-02-16 23:24 UTC, jwitz approved these changes
Assuming the new screenshot gets in, this looks good to me @paolaperaza . I made some final small suggestions, but it's mostly things I missed on my first pass.

2021-02-17 17:46 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- `<API-Key>`: API Key from your Service Account
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
- `<DAG-ID>`: Name of your DAG (_case-sensitive_)
- `<API-Key>`: API Key from your Service Account
```

2021-02-17 17:46 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/06_airflow_api.md
> +- `<AIRFLOW-DOMAIN>`: `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://deployments.gcp0001.us-east4.astronomer.io/<deployment-release-name>`
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/next/05_customize-airflow/07_airflow-api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/next/05_customize-airflow/07_airflow-api.md
> +- `<AIRFLOW-DOMAIN>`: `https://<your-base-domain>/<deployment-release-name>`
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://<your-base-domain>/<deployment-release-name>`
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/next/05_customize-airflow/07_airflow-api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/next/05_customize-airflow/07_airflow-api.md
> +To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/next/05_customize-airflow/07_airflow-api.md
> +- `<AIRFLOW-DOMAIN>`: `https://<your-base-domain>/<deployment-release-name>`
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://<your-base-domain>/<deployment-release-name>`
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +- `<AIRFLOW-DOMAIN>`: `https://<your-base-domain>/<deployment-release-name>`
```suggestion
- `<AIRFLOW-DOMAIN>`: Use `https://<your-base-domain>/<deployment-release-name>`
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
>  To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +To run this, replace:
```suggestion
To run this, replace the following place-holder values:
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +
```suggestion
```

2021-02-17 17:46 UTC, paolaperaza commented on enterprise/v0.23/05_customize-airflow/07_airflow-api.md
> +- `<API-Key>`: Use the API Key from your Service Account
```suggestion
- `<API-Key>`: API Key from your Service Account
```

2021-02-17 17:59 UTC, merged