Refactor deploy documentation
astronomer/docs pull request #2502
Opened 2023-06-29 13:37 UTC by jwitz

I tried to reorganize our "Deploy code" docs so that there's a clear delineation between the different deploy types, and also an overview page for users who would have felt overwhelmed looking at the combined page.

2023-07-04 10:13 UTC, manmeetkaur requested changes
@jwitz requested some changes and open discussion points. Thanks! :)

2023-07-04 10:13 UTC, manmeetkaur commented on astro/deploy-project.md
> +With the exception of the Airflow webserver and some Celery workers, Kubernetes gracefully terminates all containers during this process. This forces them to restart and begin running your latest cod
- using the word Kubernetes is confusing here. We should stick to Astro. "..., Astro gracefully terminates all containers..."
- since we are explaining how Astro handles worker restart down below, we should remove "and some celery workers". 
- May be change the line to: "Astro gracefully terminates and spins up all containers with the new copy of the code except Webserver during this process. Restart of the workers is handled as below:
    - If the workers are not running any tasks, all the workers are terminated and new workers will be started
    - If the workers are running tasks, then ..."

2023-07-04 14:14 UTC, jwitz commented on astro/deploy-code.md
> +- **CI/CD deploys**: Depending on the use case, CI/CD deploys combine project deploys and DAG-only deploys as an automated process. CI/CD pipelines can deploy to multiple different Deployments based
This is not describing deployment types, but "Deployment patterns". There are no templates where we only use DAG deploys - I don't think it would be accurate to describe a user's options as "DAG deploys + CI/CD" or "Project deploys + CI/CD" because we have many templates that are more complex than that.

2023-07-04 14:20 UTC, jwitz commented on astro/deploy-dags.md
> +- You can have different sets of users deploy project changes versus DAG changes. See [DAG-based templates](https://docs.astronomer.io/astro/ci-cd-templates/template-overview#dag-based-templates) for
The permissions would be at the level of the Git platform, rather than Astro. I think it's okay to keep this ambiguous

2023-07-04 14:21 UTC, jwitz commented on astro/deploy-dags.md
> +3. Open your Deployment's Astro project.
You don't need to open it before you run the first command right? I want to group steps together logically.

2023-07-04 14:25 UTC, jwitz commented on astro/deploy-project.md
> +A project deploy builds every file in your Astro project as a Docker image and deploys the image to all Airflow components in a Deployment. This includes your `Dockerfile`, DAGs, plugins, and all Pyt
I changed it because the image is more of an implementation detail, whereas the project is what users are actually interested in deploying. For custom image users this is not the cause, but that's such an advanced use case that I think it's okay to abstract it for most users.

2023-07-04 14:27 UTC, jwitz commented on astro/deploy-project.md
> +- [Docker](https://www.docker.com/products/docker-desktop).
Not exactly, since you don't need a container engine just to deploy DAGs or manage users on Astro.

2023-07-04 14:31 UTC, jwitz commented on astro/deploy-project.md
> +2. Review the information in the **Docker Image** and **DAG bundle version** fields to determine the Deployment code version.
The DAG bundle version _will_ update after a project deploy though, right? If DAG only deploys are enabled, DAGs are still downloaded separately from the main project during a project deploy, resulting in two separate tags. At least, this is what I was told when we documented the feature.

2023-07-04 14:33 UTC, jwitz commented on astro/deploy-project.md
> +
Hm I disagree here, I haven't heard of this as a common issue and want to reserve info boxes for information that's commonly searched for and missed by users

2023-07-04 14:33 UTC, jwitz commented on astro/deploy-project.md
> +
If you hear a lot about this from customers, happy to give it more exposure tho!

2023-07-07 06:50 UTC, manmeetkaur requested changes

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-dags.md
> +- You can have different sets of users deploy project changes versus DAG changes. See [DAG-based templates](https://docs.astronomer.io/astro/ci-cd-templates/template-overview#dag-based-templates) for
Sorry, I disagree here. 
- Firstly, we are not clearly stating the "how" part causing it to be ambiguous.
- Secondly, permissions in GitHub actions are based on branch names and type of event (push, pull etc.) and not user-based.
an actual use-case can be "You can choose to have either DAG-only deploy or image-based deploys or a combination of both based on your Deployment environment in your CI/CD setup. This also allows you to control permissions around how the changes are pushed to your Dev or production environment."

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-dags.md
> +3. Open your Deployment's Astro project.
As a data engineer, I would rather start from an astro project as that is more logical to me when I think about an Airflow Deployment. For example, I would go the VS code (or directly to my Terminal/iTerm window) and open my Astro project and then run the commands from a Terminal window within VS code.

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-dags.md
> +If you have Workspace Admin permissions, you can turn off DAG-only deploys for a Deployment at any time if your organization doesn't benefit from faster deploys or prefers a deployment method that is
```suggestion
If you have Workspace Admin permissions, you can turn off DAG-only deploys for a Deployment at any time if your organization doesn't benefit from faster deploys or prefers a deployment method that is exclusively based on building and deploying your Astro project as a Docker image. 

Disabling DAG-only deploys is a two-step process which includes first disabling the feature and then deploying to your Deployment. This is because the way Airflow and Astro read your DAGs changes when you turn-off DAG-only deploys. 
```
mentioning that the DAGs disappear does not seem correct to me, rather we can just clearly state that it is a two step process.

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-project.md
> +A project deploy builds every file in your Astro project as a Docker image and deploys the image to all Airflow components in a Deployment. This includes your `Dockerfile`, DAGs, plugins, and all Pyt
See my comment above, I would rather keep it as image-based.

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-project.md
> +2. Review the information in the **Docker Image** and **DAG bundle version** fields to determine the Deployment code version.
@jwitz no, that is incorrect. DAG bundle version is only updated when dag-deploy is enabled. if we disable the feature, it again becomes blank.

2023-07-07 06:50 UTC, manmeetkaur commented on astro/deploy-project.md
> +With the exception of the Airflow webserver and some Celery workers, Kubernetes gracefully terminates all containers during this process. This forces them to restart and begin running your latest cod
@jwitz thoughts here ?

2023-07-07 09:58 UTC, jwitz commented on astro/deploy-project.md
> +2. Review the information in the **Docker Image** and **DAG bundle version** fields to determine the Deployment code version.
> If you do not have DAG-only deploys enabled, the DAG bundle version field isn't populated.

I think we cover this case in the documentation. IMO we need to make it clear that the DAG bundle version updating is expected behavior if you have DAG only deploys enabled and trigger an image deploy

2023-07-07 10:02 UTC, manmeetkaur commented on astro/deploy-project.md
> +2. Review the information in the **Docker Image** and **DAG bundle version** fields to determine the Deployment code version.
@jwitz my bad in not pin-pointing. the problem is with this line - "The **DAG Bundle Version** field displays a unique timestamp generated by the Astro CLI after you complete an image deploy or a DAG-only deploy."

it should be "The **DAG Bundle Version** field displays a unique timestamp generated by the Astro CLI after you complete a DAG-only deploy."

2023-07-07 11:23 UTC, jwitz commented
@manmeetkaur Great comments and perspective on some of the terminology. This is ready for your review again!

2023-07-10 05:39 UTC, manmeetkaur approved these changes
LGTM, added some minor suggestions

2023-07-10 05:39 UTC, manmeetkaur commented on astro/deploy-project-image.md
> +When you deploy a project to Astro, your Astro project is built into a Docker image. This includes system-level dependencies, Python-level dependencies, and your `Dockerfile`. It does not include any
```suggestion
When you deploy a project to Astro, your Astro project is built into a Docker image. This includes system-level dependencies, Python-level dependencies, and your `Dockerfile`. It does not include any of the metadata associated with your local Airflow environment, including task history and Airflow connections or variables that were set locally. This Docker image is then pushed to all containers running Apache Airflow on Astro. If the DAG-only deploy feature is enabled for your Deployment, the `dags` directory is excluded from this Docker image and is pushed separately.
```

2023-07-10 05:39 UTC, manmeetkaur commented on astro/deploy-project-image.md
> +With the exception of the Airflow webserver and some Celery workers, Kubernetes gracefully terminates all containers during this process. This forces them to restart and begin running your latest cod
```suggestion
Astro gracefully terminates all containers during this process, except Airflow webserver and some Celery workers, if they are executing tasks. The new containers will come up your latest code and existing Celery workers will finish the tasks before being terminated. See the example scenario below to understand how Astro handles this.
```

2023-07-10 05:39 UTC, manmeetkaur commented on astro/deploy-project-image.md
> +1. Run `docker build` from an Astro project directory or specify the command in a CI/CD pipeline. This Docker image must be based on Astro Runtime and be available in a local Docker registry. If you
```suggestion
1. Run `docker build` from an Astro project directory or specify the command in a CI/CD pipeline. This Docker image must be based on Astro Runtime and be available in a local Docker registry. If you run this command on an Apple M1 computer or on a computer with an ARM64 processor, you must specify `--platform=linux/amd64` in the `FROM` statement of Dockerfile or else the deploy will fail. Astro Deployments require an AMD64-based image and do not support ARM64 architecture.
```

2023-07-10 12:55 UTC, jwitz commented on astro/deploy-dags.md
> +
```suggestion
```

2023-07-10 13:08 UTC, jwitz commented on astro/deploy-project-image.md
> +1. Run `docker build` from an Astro project directory or specify the command in a CI/CD pipeline. This Docker image must be based on Astro Runtime and be available in a local Docker registry. If you
`--platform` is a command-level flag, how would you specify this in a Dockerfile? Shouldn't this be "in the command"? https://docs.docker.com/engine/reference/commandline/build/#options

2023-07-10 13:11 UTC, jwitz commented on sidebarsAstro.js
> +        "overview",
```suggestion
        "deploy-code",
```

2023-07-10 13:24 UTC, jwitz commented on astro/deploy-dags.md
> +title: 'Deploy DAGs'
```suggestion
sidebar_label: 'Deploy DAGs'
title: 'Deploy DAGs  to Astro'
```

2023-07-10 13:34 UTC, merged