Adding tabs for TaskFlow vs traditional - the final PR, finally
astronomer/docs pull request #2526
Opened 2023-07-06 17:45 UTC by TJaniF

Resolves: #1800
Resolves: #2258

Its not as bad as it looks a lot of the lines are due to having a second version of a long DAG 😅 .

2023-07-06 19:29 UTC, kentdanas requested changes
@TJaniF this looks good, requesting changes just for the tutorials/integrations discussion. Let me know what you think there.

2023-07-06 19:29 UTC, kentdanas commented on learn/airflow-dbt-cloud.md
> +<Tabs
I wonder if we should not have the two alternatives for step-by-step tutorials? Thinking it might be confusing to say 'copy the following code' and then have two different options - for anybody who wasn't already familiar with taskflow vs traditional. We could say something like 'choose one of the following', but I don't love having to do that for each one....

My inclination might be to only provide the two alternatives for the concept guides where we're showing how to implement a specific concept and that implementation could look different depending on which style the DAG author chooses. As opposed to an integration where it's more about Airflow + the other tool than an Airflow concept. WDYT?

2023-07-06 19:29 UTC, kentdanas commented on learn/airflow-dbt-cloud.md
>      This DAG shows a simple implementation of using the [DbtCloudRunJobOperator](https://registry.astronomer.io/providers/apache-airflow-providers-dbt-cloud/modules/dbtcloudrunjoboperator) and [DbtCl
This paragraph is rendering as a code block in the deploy preview. Not sure exactly what the issue is here...

2023-07-06 19:29 UTC, kentdanas commented on learn/external-python-operator.md
> +<Tabs
The tabs aren't rendering on this one in the deploy preview

2023-07-06 19:29 UTC, kentdanas commented on learn/what-is-a-sensor.md
> +If no sensor exists for your use case you can create your own sensor using either the [`@task.sensor` decorator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/decorators/sensor/i
```suggestion
If no sensor exists for your use case you can create your own sensor using either the [`@task.sensor` decorator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/decorators/sensor/index.html) (added in Airflow 2.5) or the [PythonSensor](https://registry.astronomer.io/providers/apache-airflow/versions/latest/modules/PythonSensor). The `@task.sensor` decorator returns a `PokeReturnValue` as an instance of the BaseSensorOperator. The PythonSensor takes a `python_callable` that returns `True` or `False`.
```

2023-07-07 09:17 UTC, TJaniF reviewed
@kentdanas Thank you for the review! I removed the tabs again where it did not made sense and changed the dynamic DAGs guide to close issue #1283 :)

@jwitz in case you have time today would be a nice Friday merge, but of course not urgent haha. The only two guides with copy changes are the Sensors guide and the Dynamically generating DAGs guide. :)

2023-07-07 17:38 UTC, kentdanas approved these changes
Looks good! One minor comment, otherwise good to merge when you're ready

2023-07-07 19:05 UTC, TJaniF commented on learn/airflow-datasets.md
>  Any DAG that is scheduled with a dataset is considered a consumer DAG even if that DAG doesn't actually access the referenced dataset. In other words, it's up to you as the DAG author to correctly re
Oh! Yes definitely, not so much for the task but the dag definition. Not sure why I missed that one, thanks for catching it 😅

2023-07-07 20:11 UTC, merged