Create use-case-airflow-datasets-multi-team-ml.md
astronomer/docs pull request #2546
Opened 2023-07-10 15:21 UTC by astronautyates

2023-07-11 20:25 UTC, kentdanas requested changes
@astronautyates thanks for putting this together, this is a great start! Some comments throughout, let me know if you want to chat about any of them, and then I'll take another look once these are implemented.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +In this example we provide a model of that exact relationship with two DAG's, one producer DAG that extracts and loads housing data into a local S3FileSystem, and the creation of that dataset trigger
```suggestion
This example has two DAGs with a producer/consumer relationship. One DAG extracts and loads housing data into a local S3FileSystem. A dataset is defined on the load task, and the updating of that dataset triggers a second consumer DAG. The second DAG then takes that data and uses it to train and run a predictive model. This set up has two main advantages. One is that two teams can work independently on their specific sections of the pipeline without needing to coordinate with each other outside of the initial set up. The second is that because the consumer DAG will only trigger once the data arrives, you can avoid the situation where the producer DAG takes longer than expected to complete and leads to the consumer DAG running on incomplete data.
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +![Figma graph screenshot](https://github.com/astronomer/docs/blob/bc981220053224038a752cf0af050ba4316758a7/static/img/examples/usecaseconsumerproducerfigma.png)
```suggestion
![Figma graph screenshot](/img/examples/usecaseconsumerproducerfigma.png)
```
Since these are in the same repo you don't need the full GH link to reference them.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +![Datasets View screenshot](https://github.com/astronomer/docs/blob/602e61f562ed2a67fe77e6961378f9c553df528b/static/img/examples/datasetsview.png)
```suggestion
![Datasets View screenshot](/img/examples/datasetsview.png)
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +
```suggestion
The Airflow datasets and their relationships with the two DAGs can be seen in the Airflow datasets view:
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This project uses a Scikit learn dataset that contains information on the California housing market. [Scikit Dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_californ
```suggestion
This project uses a [Scikit learn dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing) that contains information on the California housing market. The data is automatically retrieved as part of the DAG, and does not need to be downloaded separately.
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +We use this data as it is custom made to work with the Scikit Machine learning package, which we will be using for our model training and predictions.
```suggestion
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This project consists of two DAG's, one [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) which extracts the Californ
```suggestion
This project consists of two DAG's. The [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) extracts the California Housing dataset from Scikit Learn and builds its model features using the Astro Python SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator before saving the data to the local S3Filesystem. 
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The second DAG then takes this data from the local S3Filesystem, and uses it to train a Scikit linear model, before using the model to generate a prediction, which is then saved to the local S3Filesy
I would add the name of the second DAG file here and link to it, like you did with the first one.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The first astro_ml_producer DAG has three tasks, the first of which is `extract_housing_data`.
```suggestion
The first astro_ml_producer DAG has three tasks.
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This task imports data from SciKit learn using the fetch_california_housing module, and returns it as a dataframe for the next tasks to use using the Astro SDK [@aql.dataframe](https://astro-sdk-pyth
```suggestion
The `extract_housing_data` task imports data from SciKit learn using the fetch_california_housing module, and returns it as a dataframe for the next tasks to use using the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator.
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The next task `build_features` uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator, which means that it operates on a D
Since this is a pretty long function that's doing multiple things, I would convert this section to bullets so it's easier to follow. Something like
" Then, the `build_features` task uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to accomplish the following: [bulleted list]"

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Finally, the third task `save_data_to_s3` in this DAG uses the Astro SDK [@aql.export_file](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the ra
```suggestion
Finally, the `save_data_to_s3` task uses the Astro SDK [@aql.export_file](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the raw California Housing Dataset as `housing.csv` to the local S3Filesystem. It runs in parallel to the `build_features` task, both a clean dataset and a feature engineered dataset are saved. 
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +We then use the Taskflow API to define the relationships between these tasks, starting the DAG with the `extract_housing_data` task to import the housing dataset and return it as a task output. Then,
I don't think we need to explain this part about dependencies - we just want to make sure we cover the meaty parts of what the DAG is doing. I'd remove this section and the code snippet below.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Now that our first producer DAG has produced normalized feature dataset for us to use in our model, we'll create a second [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consum
I would add subsections for both DAGs, since the descriptions are pretty long.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Now that our first producer DAG has produced normalized feature dataset for us to use in our model, we'll create a second [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consum
```suggestion
The second DAG, [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py), consumes the normalized dataset created by the first DAG and uses it to train a model and execute a prediction on the median house value in California. 
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +At the top of this DAG, we've instantiated the `built_features` Dataset from the previous DAG again with the following code block so that we can use it as a scheduling parameter for this consumer DAG
```suggestion
First, the `built_features` Dataset from the previous DAG is instantiated so that it can be used as a scheduling parameter. This DAG will start when the `built_features` Dataset is updated by the [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py). 
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The first task `train_model` in this DAG  uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the normalized fe
```suggestion
The `train_model` task uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the normalized feature DataFrame `built_features` from the local S3FileSystem, train a ridge regression model using the features and target values, save the trained model to a specified directory, and return the URI of the saved model file.
```
Some edits here, but this is probably better as a bulleted list too.

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The second task `predict_housing` uses Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the trained model and feature
```suggestion
Then, the `predict_housing` task uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the trained model and feature DataFrame from the local S3FileSystem, make predictions on the features DataFrame, add the predicted values to the feature DataFrame, and return the feature DataFrame with the predicted values included.
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Finally, our last task `save_predictions` uses uses the Astro SDK [@aql.export_file](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the predictio
```suggestion
Finally, the `save_predictions` task uses the Astro SDK [@aql.export_file](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the predictions dataframe in the local S3FileSystem. 
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +We then use the Taskflow API to define the relationships between our tasks, setting them to complete linearly complete in the order defined.
```suggestion
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +```python
```suggestion
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +```
```suggestion
```

2023-07-11 20:25 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +
Let's add a ## See also section here like we have on the other use cases. For this one I would probably link to Astro SDK tutorial, datasets guide, and anything else you think might be relevant.

2023-07-11 20:28 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Clone the example project from the [Astronomer GitHub](https://github.com/astronomer/use-case-produce-consume-ml/tree/main/astromlfinal).
One more comment - can we clean up this repo to only include the relevant files for this use case and update the readme? e.g. I don't think this one needs the jupyter notebooks?

2023-07-12 14:32 UTC, astronautyates commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +sidebar_label: "Multi-Team ML Pipeline with Airflow Datasets"
Cool might need you to show me the proper way to add it in the .js file during our 1 on 1

2023-07-12 17:34 UTC, astronautyates commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +title: "ML Datasets"
```suggestion
title: "ML Datasets" 
```

2023-07-12 19:47 UTC, kentdanas commented
@astronautyates the build is failing on this - 

```
contains invalid values for field(s): `sidebar_custom_props`.
```
I think `null` for this field won't work, but you can remove the line entirely.

2023-07-12 20:55 UTC, kentdanas reviewed
@astronautyates some more edits here. The change I suggested to the front matter should fix the build error. Ping me again when you're done with these and I'll take a look again when I can review in the deploy preview.

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This project consists of two DAG's. The [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) extracts the California Hou
```suggestion
This project consists of two DAGs. The [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) is the producer DAG that provides the data. It extracts the California Housing dataset from Scikit Learn and builds a model. The [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py) is the consumer DAG that takes the data from the first and uses it to train a model and generate predictions.
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The second [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py) then takes this data from the local S3Filesystem, and us
```suggestion
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +sidebar_custom_props:
```suggestion
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The next task `build_features` uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator, which means that it operates on a D
```suggestion
Then, the `build_features` task uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to implement a custom Python function that completes the following:
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +- The necessary libraries are imported within the function, including `StandardScaler` from scikit-learn, `pandas` for DataFrame operations, dump from joblib for serialization, and `S3FileSystem` fro
```suggestion
- Imports necessary libraries including `StandardScaler` from scikit-learn, `pandas` for DataFrame operations, dump from joblib for serialization, and `S3FileSystem` from s3fs for interacting with an S3-compatible object storage system.
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +- Then, An instance of an `S3FileSystem` as FS is created, specifying the access key, secret key, and the endpoint URL of the S3-compatible local storage system.
```suggestion
- Creates an instance of an `S3FileSystem` as FS by specifying the access key, secret key, and the endpoint URL of the S3-compatible local storage system. 
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +- Next, this task performs feature engineering by normalizing the input features using a StandardScaler, calculates metrics based on the scaler mean values, saves the scaler object for later monitori
```suggestion
- Performs feature engineering by normalizing the input features using a StandardScaler, calculates metrics based on the scaler mean values, saves the scaler object for later monitoring and evaluation, and returns the normalized feature DataFrame `X` with the target column included.
```

2023-07-12 20:55 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +- Finally, if you look at the task decorator, you'll notice an outlets field that references `Dataset(dataset_uri))`. This creates an Airflow Dataset object called `built_features` that references th
```suggestion
- Creates an Airflow dataset object called `built_features` with `Dataset(dataset_uri))`. This tells Airflow that this dataset is produced by this task.
```

2023-07-27 19:38 UTC, kentdanas approved these changes
@astronautyates I think this looks good now content-wise. A few minor comments still, but otherwise we'll move on to copy editing. (Also remember you can batch suggested changes and apply them in one commit, so you don't have so many commits 😄 )

@jwitz you mind copy editing this one?

2023-07-27 19:38 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The second DAG, [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py), consumes the normalized dataset created by the fir
@astronautyates I don't think this comment actually was resolved? Paragraph is still in the original section.

2023-07-27 19:38 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +title: "ML Datasets"
```suggestion
title: "ML Orchestration with Airflow datasets"
```

2023-07-27 19:38 UTC, kentdanas commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +sidebar_label: "Multi-Team ML Pipeline with Airflow Datasets"
```suggestion
sidebar_label: "ML Orchestration with Airflow datasets"
```

2023-07-28 14:25 UTC, astronautyates commented
Ah yep missed that, done

On Thu, Jul 27, 2023 at 3:38 PM Kenten Danas ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> @astronautyates <https://github.com/astronautyates> I think this looks
> good now content-wise. A few minor comments still, but otherwise we'll move
> on to copy editing. (Also remember you can batch suggested changes and
> apply them in one commit, so you don't have so many commits 😄 )
>
> @jwitz <https://github.com/jwitz> you mind copy editing this one?
> ------------------------------
>
> In learn/use-case-airflow-datasets-multi-team-ml.md
> <https://github.com/astronomer/docs/pull/2546#discussion_r1276743447>:
>
> > @@ -0,0 +1,208 @@
> +---
> +title: "ML Datasets"
>
> ⬇️ Suggested change
>
> -title: "ML Datasets"
> +title: "ML Orchestration with Airflow datasets"
>
> ------------------------------
>
> In learn/use-case-airflow-datasets-multi-team-ml.md
> <https://github.com/astronomer/docs/pull/2546#discussion_r1276743947>:
>
> > @@ -0,0 +1,208 @@
> +---
> +title: "ML Datasets"
> +description: "Using Airflow Datasets to create a Producer/Consumer ML pipeline in Airflow "
> +id: use-case-airflow-ml-datasets
> +sidebar_label: "Multi-Team ML Pipeline with Airflow Datasets"
>
> ⬇️ Suggested change
>
> -sidebar_label: "Multi-Team ML Pipeline with Airflow Datasets"
> +sidebar_label: "ML Orchestration with Airflow datasets"
>
> ------------------------------
>
> In learn/use-case-airflow-datasets-multi-team-ml.md
> <https://github.com/astronomer/docs/pull/2546#discussion_r1276736339>:
>
> > +                                     if_exists="replace")
> +```
> +
> +We then use the Taskflow API to define the relationships between these tasks, starting the DAG with the `extract_housing_data` task to import the housing dataset and return it as a task output. Then, the `extract_housing_data` task output is passed to the `save_data_to_s3` task to be saved to the local S3FileSystem. In parallel, the same dataset is passed to the `build_features` task, where is used for feature engineering.
> +
> +```python
> +    extract_df = extract_housing_data()
> +    loaded_data = aql.export_file(task_id='save_data_to_s3',
> +                                     input_data=extract_df,
> +                                     output_file=File(os.path.join(data_bucket, 'housing.csv')),
> +                                     if_exists="replace")
> +
> +    feature_df = build_features(extract_df, model_dir)
> +```
> +
> +The second DAG, [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py), consumes the normalized dataset created by the first DAG and uses it to train a model and execute a prediction on the median house value in California.
>
> @astronautyates <https://github.com/astronautyates> I don't think this
> comment actually was resolved? Paragraph is still in the original section.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astronomer/docs/pull/2546#pullrequestreview-1550612510>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFYZZVCOZZ2KANUEAZMTYLXSK7UJANCNFSM6AAAAAA2EWPIEM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-31 15:37 UTC, jwitz requested changes
Looks great @astronautyates! I think this tutorial does a great job of simplifying one of Airflow's more complicated concepts using some simple examples. 

Just a few minor suggestions. Marking "Request changes" because some of my suggestions might need polish from you to make them technically accurate, and I want to reread them again just before publishing.

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This project uses a [Scikit learn dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing) that contains in
```suggestion
This project uses a [Scikit learn dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing) that contains information on the California housing market. The data is automatically retrieved as part of the DAG and does not need to be downloaded separately.
```

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This project consists of two DAGs. The [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) is the producer DAG that pro
```suggestion
This project consists of two DAGs. The [astro_ml_producer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_producer.py) is the producer DAG that provides the data. It extracts the California Housing dataset from Scikit Learn and builds a model. The [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py) is the consumer DAG that uses the data to train a model and generate predictions.
```

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +The second [astro_ml_consumer_DAG](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py) then takes this data from the local S3Filesystem, and us
```suggestion
The [`astro_ml_consumer_DAG`](https://github.com/astronomer/use-case-produce-consume-ml/blob/main/astromlfinal/dags/astro_ml_consumer.py) takes data from the local S3Filesystem and uses it to train a Scikit linear model. It then uses this model to generate a prediction which is saved to the local S3Filesystem. 
```

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +
```suggestion
- Import necessary libraries, including RidgeCV from scikit-learn for ridge regression, numpy for numerical operations, dump from joblib for serialization, and S3FileSystem from s3fs for interacting with an S3-compatible object storage system.

- Create an instance of S3FileSystem by specifying the access key, secret key, and the endpoint URL of the S3-compatible storage system.

- Open the file containing the feature DataFrame created by the consumer DAG using the S3 file system (fs.open) and train a ridge regression model on the features.

```

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +- Serialize and save the trained model to the specified model_dir using the dump function from joblib. The file name for the model is set as 'ridgecv.joblib'. The function returns the URI of the save
```suggestion
- Serialize and save the trained model to the specified `model_dir` using the dump function from joblib. The file name for the model is set as 'ridgecv.joblib'. The function returns the URI of the saved model file `(model_file_uri)`, which is the concatenation of `model_dir` and 'ridgecv.joblib'.
```
Any code object or variable name should have `code styling`

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Then, the `predict_housing` task uses the Astro SDK [@aql.dataframe](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the trained model and feat
```suggestion
Then, the `predict_housing` task uses the Astro SDK [`@aql.dataframe`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/dataframe.html) decorator to load the trained model and feature DataFrame from the local S3FileSystem, make predictions on the features DataFrame, add the predicted values to the feature DataFrame, and return the feature DataFrame with the predicted values included.
```

2023-07-31 15:37 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +Finally, the `save_predictions` task uses the Astro SDK [@aql.export_file](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the predictions datafra
```suggestion
Finally, the `save_predictions` task uses the Astro SDK [`@aql.export_file`](https://astro-sdk-python.readthedocs.io/en/stable/astro/sql/operators/export.html) decorator to save the predictions dataframe in the local S3FileSystem. 
```

2023-07-31 18:07 UTC, astronautyates commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This example has two DAGs with a producer/consumer relationship. One DAG extracts and loads housing data into a local S3FileSystem. A dataset is defined on the load task, and the updating of that dat
Committed with just a change from ML Flow to Scikit learn since thats what we're using.

2023-08-01 13:45 UTC, jwitz approved these changes
LGTM! @kentdanas I'll let you do the honors of merging

2023-08-01 13:45 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +ML pipelines are sometimes run by two teams in a producer/consumer relationship. One team produces the clean data, while another team consumes the data in their ML models. This relationship can somet
```suggestion
ML pipelines are sometimes run by two teams in a producer/consumer relationship. One team produces the clean data, while another team consumes the data in their ML models. This relationship can include friction when there's not a clear mechanism for delivering clean data to the producing team on a predictable, reliable basis. You can use Airflow datasets and data-driven scheduling to remove this friction by scheduling a consumer DAG to run only when its related producer DAG has completed.
```

2023-08-01 13:45 UTC, jwitz commented on learn/use-case-airflow-datasets-multi-team-ml.md
> +This set up has two main advantages. One is that two teams can work independently on their specific sections of the pipeline without needing to coordinate with each other outside of the initial set u
```suggestion
This setup has two main advantages: 

- Two teams can work independently on their specific sections of the pipeline without needing to coordinate with each other outside of the initial set up. 
- Because the consumer DAG only triggers after the data arrives, you can avoid situations where the producer DAG takes longer than expected to complete, or where the consumer DAG runs on incomplete data.
```

2023-08-01 17:35 UTC, merged