Add important tip to Hashicorp Vault & CLI section to Import Conns/Vars
astronomer/docs pull request #2552
Opened 2023-07-11 15:27 UTC by manmeetkaur

@jwitz This PR was originally supposed to just add a note to HAshicorp Vault, but when I went to link the import as URI section, I realized we did not create that separately. I tried to address that as part of this PR since it was linked. Please let me know if that is okay, happy to do it separately. Thanks!

2023-07-12 11:33 UTC, jwitz requested changes
@manmeetkaur Because the notes are important user info, I made some suggestions for moving them to more relevant locations in the topic. 

Also, it's unclear how a user can make set their key as `value`.  The command we provide is `vault kv put secret/variables/<your-variable-key> value=<your-variable-value>`. Based on the new note, I would assume that the only possible input would be `vault kv put secret/variables/value value=<your-variable-value>`. But then we say `secret/variables/my-var` is a valid example. I think we need to provide more info for how to set the key in the commands.

2023-07-12 11:33 UTC, jwitz commented on astro/import-export-connections-variables.md
> +See [`astro dev object export`](cli/astro-dev-object-export.md), [`astro dev object import`](cli/astro-dev-object-import.md) and [`astro dev run`](cli/astro-dev-run.md) for more details.
```suggestion
Use [`astro dev object export`](cli/astro-dev-object-export.md), [`astro dev object import`](cli/astro-dev-object-import.md) and [`astro dev run`](cli/astro-dev-run.md) to import and export connections and variables from a local Airflow environment to various formats. For example:

- To export all Airflow objects including connections, variables, and pools to your Astro project `.env` file in a URI format, run:
    
    ```bash 
    astro dev object export --env-export 
    ```

- To print only your connections connections in JSON format to STDOUT, run:

    ```bash
    astro dev run connections export - --file-format=env --serialization-format=json
    ```

- To import all Airflow objects from a file named `myairflowobjects.yaml` to a locally running Airflow environment, run:
    
    ```bash
    astro dev object import --settingsfile="myairflowobjects.yaml"
    ```
```

2023-07-12 11:33 UTC, jwitz commented on astro/import-export-connections-variables.md
> +See [`astro dev object export`](cli/astro-dev-object-export.md), [`astro dev object import`](cli/astro-dev-object-import.md) and [`astro dev run`](cli/astro-dev-run.md) for more details.
Cutting down on the number of examples here, and also making it clear that this is for local development only.

2023-07-12 11:33 UTC, jwitz commented on astro/secrets-backend.md
> +For Airflow variables, the name of the key for the Vault secret you create must be `value`. For example, if you are creating a secret called secret/variables/my-var, the **key** must be named `value`
- Should we move this to after line 230? (`vault kv put secret/variables/<your-variable-key> value=<your-variable-value>`)
- I also don't see the user specifies `value` in the command we provide. Do we need to update our command examples?

2023-07-12 11:33 UTC, jwitz commented on astro/secrets-backend.md
> +For Airflow connections, the name of the key for the Vault secret you create must be `conn_uri`. For example, if you are creating a secret called secret/connections/my-conn, the **key** must be named
Same here, we should move this to just after the example command

2023-07-13 08:24 UTC, manmeetkaur commented on astro/secrets-backend.md
> +For Airflow variables, the name of the key for the Vault secret you create must be `value`. For example, if you are creating a secret called secret/variables/my-var, the **key** must be named `value`
i wanted to , but was confused as you had mentioned tips should always be at the end. good you suggested this :)

2023-07-13 08:59 UTC, jwitz commented on astro/secrets-backend.md
> +For Airflow variables, the name of the key for the Vault secret you create must be `value`. For example, if you are creating a secret called secret/variables/my-var, the **key** must be named `value`
I hope I didn't say "always"! I often tend to move them if they come immediately after a topic title, but where they end up can vary based on the content of the note

2023-07-13 09:13 UTC, manmeetkaur commented
@jwitz made some changes, let me know if it seems okay. In our examples we have hardcoded key values `value` and `conn_uri` to avoid confusion. 

also there is [another method](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/secrets-backends/hashicorp-vault.html#storing-and-retrieving-connections-using-connection-class-representation) to add a connection in vault, but it is a tricky one. So I have not included this as of now.

2023-07-13 11:11 UTC, jwitz approved these changes
Tag me back if you have any comments on my suggestions, otherwise LGTM!

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +vault secrets enable -path=<my-airflow-mount> -version=2 kv
In the `kwargs` config later, we tell users that the path they should specify here is `secrets/connections` and `secrets/variables`. Unless there's a good reason someone would want to customize those names, we shouldn't use placeholder. This provides a more straightforward setup because the user has to make less arbitrary decisions on naming

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +vault kv put -mount=<my-airflow-mount> <my-variables-path>/<my-variable-name> value=<my-value-value>
```suggestion
vault kv put -mount=secret variables/<your-variable-name> value=<your-variable-value>
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +To store a connection in Vault as a secret in URI representation, run the following Vault CLI command with your own values:
```suggestion
To store a connection in Vault as a secret, first format the connection as a URI. Then, run the following Vault CLI command:
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +vault secrets enable -path=<my-airflow-mount> -version=2 kv
```suggestion
vault secrets enable -path=secret -version=2 kv
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +vault kv put -mount=<my-airflow-mount> <my-connections-path>/<my-connection-name> conn_uri=<connection-type>://<connection-login>:<connection-password>@<connection-host>:<connection-port>
```suggestion
vault kv put -mount=secret connections/<your-connection-name> conn_uri=<connection-type>://<connection-login>:<connection-password>@<connection-host>:<connection-port>
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +To import your connections in URI format, see [Import and export connections](import-export-connections-variables.md#using-the-astro-cli-local-environments-only).
```suggestion
To format existing connections in a URI format, see [Import and export connections](import-export-connections-variables.md#using-the-astro-cli-local-environments-only).
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +$ vault kv get -mount=<my-airflow-mount> <my-connections-path>/<my-connection-name>
```suggestion
$ vault kv get -mount=secret connections/<your-connection-name>
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +$ vault kv get -mount=<my-airflow-mount> <my-variables-path>/<my-variable-name>
```suggestion
$ vault kv get -mount=<your-airflow-mount> variables/<your-variable-name>
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +:::tip important
```suggestion
:::caution
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +Please note that even though Vault allows to create a custom key name for your secrets, Airflow requires the Key name to be `value` for Airflow variables and `conn_uri` for Airflow connections as sho
```suggestion
Do not use custom key names for your secrets. Airflow requires the key name `value` for all Airflow variables and the key name `conn_uri` for all Airflow connections as shown in the previous commands.
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +
```suggestion
```

2023-07-13 11:11 UTC, jwitz commented on astro/secrets-backend.md
> +:::tip important
https://docusaurus.io/docs/markdown-features/admonitions

2023-07-13 13:01 UTC, merged