How-to Connections Guide
astronomer/docs pull request #2554
Opened 2023-07-12 07:28 UTC by manmeetkaur

2023-07-13 15:42 UTC, jwitz approved these changes
Dropping comments for the first few guides, will get through the rest tomorrow!

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +2. Go to the **Settings** in the left pane, and click on **Endpoints**. Copy the Blob Service URL. It looks like `https://mystorageaccount.blob.core.windows.net/`.
```suggestion
2. Click **Settings** in the left menu, then click **Endpoints**. Copy the **Blob Service URL**. It should be in the format `https://mystorageaccount.blob.core.windows.net/`.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +3. Go to your [Azure AD application](https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade). Then, from the **Overview** tab, copy the **Application (client) ID** and **Di
```suggestion
3. Open your [Azure AD application](https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/overview-application-gallery). Then, from the **Overview** tab, copy the **Application (client) ID** and **Directory (tenant) ID**.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +4. Follow the Azure documentation to [create a new client secret](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-3-create-a-new-applicat
```suggestion
4. Follow the Azure documentation to [create a new client secret](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-3-create-a-new-application-secret) for your application to be used in Airflow connection. Copy the **VALUE** of the client secret.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +5. Follow the Azure documentation to [assign](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-a-role-to-the-application) the [Storage Blo
```suggestion
5. Follow the Azure documentation to [assign](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-a-role-to-the-application) the [Storage Blob Data Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) so that Airflow can access objects in your storage account.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +To create an Azure blob storage connection, you can use any of the following methods to integrate Azure storage account with Airflow:
```suggestion
Configure your Airflow connection based on the information you retrieved in the previous step. 
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +
```suggestion

```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +1. Add the following line to your Astro project's `requirement.txt` file to install and use the package for Microsoft Azure in Airflow:
```suggestion
1. Add the following line to your Astro project `requirements.txt` file to install and use the provider package for Microsoft Azure in Airflow:
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +2. If you're not currently running Airflow locally, open your Astro project and run `astro dev start`. Otherwise, run `astro dev restart`.
```suggestion
2. Run `astro dev start` to start your project, or run `astro dev restart` to restart your project and install the provider package.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +3. In the Airflow UI, go to **Admin** > **Connections**. Click the **+** sign to add a new connection, select the connection type as **Azure Blob Storage** and give it a name in the **Connection Id**
```suggestion
3. In the Airflow UI, go to **Admin** > **Connections**. Click **+** to add a new connection and select the connection type as **Azure Blob Storage**.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +4. Paste the values copied from [Get connection details](#get-connection-details) in the connection fields:
```suggestion
4. Complete the following fields using the values you retrieved from [Get connection details](#get-connection-details):
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +    - **Blog Storage Key**: `<my-shared-access-key>`
```suggestion
    - **Blog Storage Key**: Enter your storage account **Key**.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +    - **Blob Storage Login**: `<my-storage-account>`
```suggestion
    - **Connection Id**: Enter a name for the connection.
    - **Blob Storage Login**: Enter your storage account name. 
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +5. Click on **Test** connection to test and then **Save** the connection.
```suggestion
5. Click **Test**. When the connection test succeeds, click **Save**.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +To create a connection, follow the below steps:
```suggestion
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +1. Add the following line to your Astro project's `requirement.txt` file to install and use the package for Microsoft Azure in Airflow.:
Can you apply similar edits to the next few tabs based on the ones I provided earlier? Because the content is the same, my edits would basically be identical.

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +Airflow uses [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python) to connect to Azure services via [WasbHook](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure
```suggestion
Airflow uses [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python) to connect to Azure services using the [WasbHook](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/_api/airflow/providers/microsoft/azure/hooks/wasb/index.html).
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +- [Authorize access to Storage Account](https://learn.microsoft.com/en-us/azure/storage/common/authorize-data-access?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcru
```suggestion
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +- [Apache Airflow Microsoft Azure OSS Docs](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/wasb.html).
```suggestion
- [Apache Airflow Microsoft Azure provider package documentation](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/wasb.html).
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-storage-account.md
> +- Azure blob storage [modules](https://registry.astronomer.io/modules?query=wasb) and [example DAGs](https://registry.astronomer.io/dags/covid_to_azure_blob/versions/1.2.0) in Astronomer Registry.
```suggestion
- Azure blob storage [modules](https://registry.astronomer.io/modules?query=wasb) and [example DAGs](https://registry.astronomer.io/dags/covid_to_azure_blob/versions/1.2.0) in the Astronomer Registry.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +[Azure Synapse](https://azure.microsoft.com/en-us/products/synapse-analytics/#:~:text=Azure%20Synapse%20Analytics%20is%20an,log%20and%20time%20series%20analytics.) is an enterprise analytics service
```suggestion
[Azure Synapse](https://azure.microsoft.com/en-us/products/synapse-analytics/#:~:text=Azure%20Synapse%20Analytics%20is%20an,log%20and%20time%20series%20analytics.) is an enterprise analytics service from Microsoft. Integrating Airflow with Synapse means you can use DAGs to schedule Spark jobs on Azure Synapse and run SQL queries in the Synapse SQL pool.
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +- Access to a [Azure Synapse workspace](https://learn.microsoft.com/en-us/azure/synapse-analytics/get-started)
```suggestion
- Access to an [Azure Synapse workspace](https://learn.microsoft.com/en-us/azure/synapse-analytics/get-started)
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +- Access to your Synapse Database from Airflow
```suggestion
- Access to your Synapse Database
```
Right?

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +
```suggestion

Complete the following steps to retrieve this information:
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +
```suggestion
1. Open your [Synapse Analytics workspace](https://learn.microsoft.com/en-us/azure/synapse-analytics/get-started-create-workspace) on Azure Portal.
2. Copy the following details:
    - SQL Endpoint (Both **Dedicated** or **Serverless** work)
    - SQL Admin username and password
    - SQL Pool name 
```

2023-07-13 15:42 UTC, jwitz commented on learn/connections-azure-synapse.md
> +## Get Connection details
Looks like there's still some conflict/ draft information in this doc. Will take a look after it's cleaned up

2023-07-14 09:26 UTC, jwitz approved these changes
Dropping comments for the first few guides, will get through the rest tomorrow!

2023-07-14 12:25 UTC, jwitz reviewed
Whoops did not mean to approve yet still in "commenting" state

2023-07-14 12:41 UTC, jwitz commented on learn/connections-bigquery.md
> +2. Restart your local Airflow using `astro dev restart`. If you're not currently running Airflow locally, you can also run `astro dev start`.
```suggestion
1. Open your Astro project and add the following line to your `requirement.txt` file to install and use the package for Google Cloud in Airflow:

    ```
    apache-airflow-providers-google
    ```

2. Restart your local Airflow using `astro dev restart`. If you're not currently running Airflow locally, you can also run `astro dev start`.
```

2023-07-14 14:34 UTC, jwitz requested changes
@manmeetkaur GitHub is starting to freeze because there's so many comments, want to address what I have so far and I'll come back to review the rest after?

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +1. Select your Google Cloud project where you are running BigQuery and copy it's **ID**.
```suggestion
1. In your Google Cloud console, open the Google Cloud project where you're running BigQuery and copy its **ID**.
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +2. Follow Google's documentation to [enable workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) and [to configure Airflow to use workload identity](https://cl
```suggestion
2. [Enable Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) and [configure Airflow to use workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to). Copy the ID for the Kubernetes service account that you create. 
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +3. Then, go to the IAM page, click the **Service Accounts** tab, and search the service account created in step #2 above. If you do not see your service account, go to **IAM**, then click on **+ADD**
```suggestion
3. Go to **IAM** and open your service account. If you don't see your service account, click **+ ADD** to add your service account to your Google Cloud project.
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +4. Now, follow Google's documentation [to grant roles](https://cloud.google.com/iam/docs/grant-role-console) to your service account to access BigQuery. See [BigQuery roles](https://cloud.google.com/
```suggestion
4. [Grant roles](https://cloud.google.com/iam/docs/grant-role-console) to your service account to access BigQuery. See [BigQuery roles](https://cloud.google.com/bigquery/docs/access-control#bigquery) for list of available roles and the permissions.
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +Follow the below steps to create a connection:
```suggestion
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +1. Open your Astro project and add the following line to your `requirement.txt` file to install and use the package for Google Cloud in Airflow:
```suggestion
1. Add the following line to your Astro project `requirements.txt` file to install and use the Google Cloud connection type in Airflow:
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +2. Restart your local Airflow using `astro dev restart`. If you're not currently running Airflow locally, you can also run `astro dev start`.
Same edits as before

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +2. Copy the key file downloaded in Step #5 in [Get Connection Details](bigquery#get-connection-details) to the `include` directory of your Astro project. This will make it available to your Airflow a
```suggestion
2. Add the key file to your Astro project `include` folder. This will make it available to Airflow at `/usr/local/airflow/include/<your-key-file>.json`.
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +3. Restart your local Airflow using `astro dev restart`. If you're not currently running Airflow locally, you can also run `astro dev start`.
Same edits as before

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +Follow the below steps to create a connection:
```suggestion
```
Same edits as before

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +
```suggestion
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +To create a connection using workfload identity, follow the below steps:
```suggestion
Same edits as before
```

2023-07-14 14:34 UTC, jwitz commented on learn/connections-bigquery.md
> +- When no Key details in connection are provided, Google defaults to using [Application Default Credentials (ADC)](https://cloud.google.com/docs/authentication/application-default-credentials). This
```suggestion
Airflow uses the [`python-bigquery`](https://github.com/googleapis/python-bigquery) library and  [BigQueryHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/hooks/bigquery/index.html) to connect to BigQuery. If you don't define any specific key credentials in the connection, Google defaults to using [Application Default Credentials (ADC)](https://cloud.google.com/docs/authentication/application-default-credentials). This means when you use Workload Identity to connect to BigQuery, Airflow relies on ADC to authenticate.
```

2023-07-18 10:18 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +title: "Creating an Azure Storage Account connection"
Azure storage account can be of multiple types, blob or file or queues etc. https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview. Although most commonly used is Blob storage. We can do blob storage for now for simplicity and tackle the multiple uses later on.

2023-07-18 10:21 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +[Azure Storage Account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview) provides the storage for all of your Azure Storage data objects - blobs, files, queues, tables
@jwitz why "container" was changed to "containers" and "file" was kept as "a file" ?

2023-07-18 10:24 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +    groupId= "azure-connection"
@jwitz not sure why are we changing this ? Shouldn't we be using the same groupId for the tabs of get-connection-details and create your connection to let them sync. I have tested it and it works.

2023-07-18 10:26 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +1. Go to your [Storage account](https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Storage%2FStorageAccounts) view and select your subscription.
I find it rather helpful! when as a user I have to follow some steps, I want to perform those actions and not read about them. for reading we have given link to the docs .

2023-07-18 10:28 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +3. Follow the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#view-account-access-keys) until step #4 to get the shared
this change doesn't make sense. so changing it; I believe you just wanted to remove the "until step #4" part ?

2023-07-18 10:37 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +1. Add the following line to your Astro project's `requirement.txt` file to install and use the package for Microsoft Azure in Airflow:
@jwitz I believe you removed the apostrophe after project by mistake, adding it back.

2023-07-18 10:38 UTC, manmeetkaur commented on learn/connections-azure-storage-account.md
> +2. If you're not currently running Airflow locally, open your Astro project and run `astro dev start`. Otherwise, run `astro dev restart`.
I think we should keep it consistent across different guides. The one we set for aDF seemed perfect.

2023-07-18 10:48 UTC, manmeetkaur commented on learn/connections-bigquery.md
> +This method requires you to save the contents of your service account key file to a secrets backend of your choice. For this example, let's assume Google Secret Manager as the secrets backend for our
@jwitz I would recommend we mention here that we are using Google secret manager. so adding it back. I will add it for now and you can edit it later for grammar.

2023-07-18 10:53 UTC, manmeetkaur commented on learn/connections-bigquery.md
> +
@jwitz this has changed the meaning of what I wanted to say :D let take another look at it.

2023-07-27 16:38 UTC, manmeetkaur commented
closing this PR as the work is done in other small PRs #2602 #2583 #2579 and ODBC (Syanpse SQL ) was moved to a Forum post

2023-07-27 16:38 UTC, closed without merging