add required CIDR to the main Prereq section for reducing back-and-forth
astronomer/docs pull request #2569
Opened 2023-07-16 14:36 UTC by manmeetkaur

2023-07-21 13:25 UTC, jwitz requested changes
I'll take one more look after my edits are in, but overall this LGTM!

2023-07-21 13:25 UTC, jwitz commented on astro/install-aws-hybrid.md
> +description: "If you have an existing Amazon Web Services (AWS) instance, use these instructions to complete an Astro installation. This is where you’ll find the prerequisites and the process you’ll
```suggestion
description: "If you have an existing Amazon Web Services (AWS) instance, use these instructions to complete the installation for Astro Hybrid."
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +description: 'Instructions for completing an Astro installation on an existing Microsoft Azure instance. This is where you’ll find the prerequisites and the process you’ll need to follow to allow Ast
Same edits in this doc

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +    If the VM types are unavailable, the output returns `Restrictions`. Please contact Microsoft Support to have these VMs enabled.
```suggestion
    If the VM types are unavailable, the output returns `Restrictions`. Contact Microsoft Support to have these VMs enabled.
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +To complete the setup for the installation, you'll:
Same edits in this section

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
>  ## Prerequisites
Same edits as AWS

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +- A new Azure subscription. For security reasons, Azure subscriptions with existing infrastructure aren't supported. Also, no [Azure policy](https://learn.microsoft.com/en-us/azure/governance/policy/
```suggestion
- A new Azure subscription. For security reasons, Azure subscriptions with existing infrastructure aren't supported. Also, no [Azure policy](https://learn.microsoft.com/en-us/azure/governance/policy/overview) should be applicable to the subscription's [Azure management group](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview).
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +- A CIDR block with `/19` range is required for the Astro Data Plane. If you do not have any preferred CIDR block, Astro will provision a VPC using a default of `172.20.0.0/19`. This will be used for
Same edits as AWS

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +See [Azure resource reference](resource-reference-azure-hybrid.md) for default and supported cluster configurations.
```suggestion
See [Azure resource reference](resource-reference-azure-hybrid.md) for all supported cluster configurations.
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-azure-hybrid.md
> +When Astronomer support confirms that your Astro cluster has been created, you can confirm it in the [Cloud UI](https://cloud.astronomer.io) by clicking on the Astronomer icon in the top left corner,
```suggestion
Astronomer support will notify you after your Astro cluster has been created. To confirm a successful installation, in the Cloud UI select a Workspace and on the **Deployments** page click **+ Deployment**. The cluster created by Astronomer support appears as an option in the **Cluster** list. 

You can then [create Deployments](create-first-DAG#step-1-create-a-deployment) on your cluster to start running DAGs in your cloud.
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-gcp-hybrid.md
> +To install Astro Hybrid on GCP, Astronomer support creates a Astro cluster in a dedicated GCP account that's hosted and owned by your organization. This ensures that all data remains within your netw
```suggestion
To install Astro Hybrid on GCP, Astronomer support creates a cluster in a dedicated GCP account that's hosted and owned by your organization. This ensures that all data remains within your network and allows your organization to manage infrastructure billing.
```

2023-07-21 13:25 UTC, jwitz commented on astro/install-gcp-hybrid.md
> +- Create an [Astronomer account](#access-astro).
Same edits as in AWS

2023-07-21 13:25 UTC, jwitz commented on astro/install-gcp-hybrid.md
> +- CIDR blocks of ranges `/19`, `/20`, `/22`, and `/22` are required for the Astro Data Plane. If you do not have any preferred CIDR block, Astro will provision VPCs using a [default CIDR ranges](#vpc
Same edits as AWS

2023-07-21 13:25 UTC, jwitz commented on astro/install-gcp-hybrid.md
> +- Create a service account `astronomer@astro-remote-mgmt.iam.gserviceaccount.com` that Astro uses to access the data plane.
```suggestion
- Create a service account called `astronomer@astro-remote-mgmt.iam.gserviceaccount.com` that Astro uses to access the data plane.
```

2023-07-21 15:43 UTC, manmeetkaur commented on astro/install-azure-hybrid.md
> +description: 'Instructions for completing an Astro installation on an existing Microsoft Azure instance. This is where you’ll find the prerequisites and the process you’ll need to follow to allow Ast
```suggestion
description: 'Use this document to complete the installation of Astro Hybrid in a Microsoft Azure subscription.
```

2023-07-21 15:45 UTC, manmeetkaur commented on astro/install-azure-hybrid.md
> +description: 'Instructions for completing an Astro installation on an existing Microsoft Azure instance. This is where you’ll find the prerequisites and the process you’ll need to follow to allow Ast
@jwitz I had just copied the existing description. If we have to change it I would change it not include "existing Microsoft Azure instance" because 
- there is no such thing as "azure instance"
- Not always users have an existing subscription as we state in our prerequisites to create a new one.

2023-07-21 15:50 UTC, manmeetkaur commented on astro/install-azure-hybrid.md
> +To complete the setup for the installation, you'll:
```suggestion
To complete the installation, you'll:
```

2023-07-21 15:50 UTC, manmeetkaur commented on astro/install-azure-hybrid.md
> +When Astronomer support confirms that your Astro cluster has been created, you can confirm it in the [Cloud UI](https://cloud.astronomer.io) by clicking on the Astronomer icon in the top left corner,
@jwitz if a cluster is in CREATING state it will still appear in the drop-down of "Create deployment" page. This will definitely confuse users.

2023-07-21 17:34 UTC, manmeetkaur commented
@jwitz I am done with the changes, you can take another look now.

2023-07-24 10:47 UTC, jwitz commented on astro/install-aws-hybrid.md
> +- Create the IAM policies used by Astro. This includes a cross-account IAM role that Astro can assume and [Permissions boundaries for IAM entities](https://docs.aws.amazon.com/IAM/latest/UserGuide/ac
```suggestion
- Create the IAM policies used by Astro. This includes a cross-account IAM role that Astro can assume and [permissions boundaries for IAM entities](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html).
```

2023-07-24 10:48 UTC, jwitz commented on astro/install-aws-hybrid.md
> +- Admin access to create a stack using [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-cli-creating-stack.html).
```suggestion
- Permissions to create a stack using [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-cli-creating-stack.html).
```

2023-07-24 10:49 UTC, jwitz commented on astro/install-gcp-hybrid.md
> +- Enable Google Cloud APIs and add IAM service account that'll be used by Astro.
```suggestion
- Enable Google Cloud APIs and add an IAM service account that will be used by Astro.
```

2023-07-24 10:50 UTC, jwitz approved these changes

2023-07-24 11:46 UTC, merged