Tiny PR: update default providers list
astronomer/docs pull request #2574
Opened 2023-07-17 13:59 UTC by TJaniF

Noticed this list was out of date because I was looking for common SQL in it :)

Was a bit surprised to not see OL in there. Reference on a vanilla 8.7.0 image:

![Screenshot 2023-07-17 at 15 59 18](https://github.com/astronomer/docs/assets/90063506/8889270e-ede9-43d3-9072-262c9f47da08)

2023-07-18 08:50 UTC, jwitz requested changes
We referenced OL as early as the last patch version in release notes/ Runtime CHANGELOG: https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-870

Where are you seeing this list? We might need to get the Runtime team involved to confirm, package use has always been a little opaque.

2023-07-18 09:51 UTC, TJaniF commented
@jwitz good catch!
And that is odd. I am getting the list at `localhost:8080/provider` when I have a local Astro project running. There is actually some mystery going on with the `Provider` option not showing up in the Admin menu for me (and not for Kenten either) when running locally, but it does show up on Astro. (There is a thread on that in #astro-runtime). 

I think I found the source truth in the runtime repo, asked in their channel :)

2023-07-19 12:17 UTC, TJaniF commented
Assigned this back to me to compare the list with the info I got from the runtime team.

2023-07-20 14:39 UTC, TJaniF commented
Alright, figured it out, I think :) 

@jwitz you were right about OL! 

https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html lists all providers pre-installed in OSS Airflow (the ones with a * in that column). The Kubernetes provider is installed because of an extra to add the K8s executor.

The submodules added in Runtime are listed in the Docker image code in the runtime repo (not all of them are providers, but some). From there I get Amazon, Astronomer providers, SDK, Datadog, Elasticsearch, Google, Microsoft Azure, Postgres and Redis on top.

Open lineage gets installed in the runtime image as well but is technically a plugin, so it is listed with the plugins, that was the source of that confusion 😅 

![Screenshot 2023-07-20 at 16 35 02](https://github.com/astronomer/docs/assets/90063506/10737968-e305-4715-9efb-657767547891)

2023-07-21 09:39 UTC, jwitz commented on astro/runtime-image-architecture.md
> +- Microsoft Azure [`apache-airflow-providers-microsoft-azure`](https://pypi.org/project/apache-airflow-providers-microsoft-azure/)
```suggestion
- Microsoft Azure [`apache-airflow-providers-microsoft-azure`](https://pypi.org/project/apache-airflow-providers-microsoft-azure/)
- OpenLineage with Airflow [`openlineage-airflow`](https://pypi.org/project/openlineage-airflow/)
```

2023-07-21 09:44 UTC, jwitz requested changes
Aha 🕵️ excellent sleuthing. Reviewing again and have some suggestions for the new formatting, lmk what you think!

2023-07-21 09:44 UTC, jwitz commented on astro/runtime-image-architecture.md
> +The latest version of the Astro Runtime image has the following open source provider packages pre-installed. Providers marked with (pre-installed OSS) are pre-installed in open-source Airflow.
```suggestion
The latest version of the Astro Runtime image has the following open source provider packages pre-installed. Providers marked with an asterisk (`*`) are installed only in Astro Runtime and not installed by default on Apache Airflow.
```
Wouldn't a user care more about what packages are preinstalled on Runtime, but not OSS? Because of that, I would flip this around.

2023-07-21 09:44 UTC, jwitz commented on astro/runtime-image-architecture.md
> +Additionally, the Astro Runtime image contains a plugin to interact with [OpenLineage](https://pypi.org/project/openlineage-airflow/).
Is the end result the same? As in, when you scan the images for dependencies, will OL appear? If so, I'm not sure it's worth distinguishing that this is installed at the plugin level. And even if so, I would add it to the bullet list with a parentheses addendum: `(installed through a separate plugin)` or something similar

2023-07-21 10:09 UTC, TJaniF reviewed
Haha, thank you @jwitz the sleuthing involved kinda proves the need for this doc 😅 
made the changes and added a suggestion for the OL package

2023-07-21 10:09 UTC, TJaniF commented on astro/runtime-image-architecture.md
> +The latest version of the Astro Runtime image has the following open source provider packages pre-installed. Providers marked with (pre-installed OSS) are pre-installed in open-source Airflow.
That is a very good point!

2023-07-21 11:00 UTC, jwitz commented on astro/runtime-image-architecture.md
> +- OpenLineage [`openlineage-airflow`](https://pypi.org/project/openlineage-airflow/) (this package installs an Airflow plugin) `*`
```suggestion
- OpenLineage [`openlineage-airflow`](https://pypi.org/project/openlineage-airflow/) (Installed through an Airflow plugin) `*`
```
Would this be accurate?

2023-07-21 11:01 UTC, jwitz commented on astro/runtime-image-architecture.md
> +- Amazon [`apache-airflow-providers-amazon`](https://pypi.org/project/apache-airflow-providers-amazon/) `*`
```suggestion
- Amazon [`apache-airflow-providers-amazon`](https://pypi.org/project/apache-airflow-providers-amazon/)*
```
Oh maybe the code styling was confusing on my part, I think we should just use plain asterisks in the list itself.

2023-07-21 11:01 UTC, jwitz commented on astro/runtime-image-architecture.md
> +The latest version of the Astro Runtime image has the following open source provider packages pre-installed. Providers marked with an asterisk (`*`) are installed only in Astro Runtime and not instal
```suggestion
The latest version of the Astro Runtime image has the following open source provider packages pre-installed. Providers marked with an asterisk (*) are installed only in Astro Runtime and not installed by default on Apache Airflow.
```

2023-07-21 11:01 UTC, jwitz approved these changes
Lookin' good!

2023-07-21 13:44 UTC, TJaniF commented on astro/runtime-image-architecture.md
> +- OpenLineage [`openlineage-airflow`](https://pypi.org/project/openlineage-airflow/) (this package installs an Airflow plugin) `*`
unfortunately no. The package itself is for a plugin, that is what is being installed. 😅

2023-07-21 13:48 UTC, TJaniF reviewed
@jwitz thank you!
hopefully the last round in this game of ping pong 😄

2023-07-21 14:32 UTC, jwitz commented on astro/runtime-image-architecture.md
> +- Astronomer Providers [`astronomer-providers`](https://pypi.org/project/astronomer-providers/) *
```suggestion
- Astronomer Providers [`astronomer-providers`](https://pypi.org/project/astronomer-providers/)*
```
Can we remove the spaces on these pls 🙈

2023-07-21 15:12 UTC, merged