Migrate from legacy Astronomer products
astronomer/docs pull request #2580
Opened 2023-07-18 15:17 UTC by jwitz

Putting on draft until we get approval on general wording/ framing

2023-07-20 14:28 UTC, jwitz commented on astro/migrate-astronomer-software-nebula.md
> +id: migrate-to-astro
```suggestion
id: migrate-astronomer-software-nebula
```

2023-08-01 11:39 UTC, jwitz commented on astro/migrate-astronomer-software-nebula.md
> +- You have finished migrated your Airflow Deployments to Astro, or you're in the process of migrating.
```suggestion
- You have finished migrating your Airflow Deployments to Astro, or you're in the process of migrating. 
```

2023-09-18 19:42 UTC, fritz-astronomer requested changes
- Would like to mention Starship to assist with the process
- Should maybe not mention nebula (as that all is being automated today)
- May need to start mentioning Hybrid

Is a good doc as-is, though, at least as an introduction and a "what's changed"

2024-01-16 14:41 UTC, jwitz commented
Closing this out as there are no more legacy products to migrate from!

2024-01-16 14:41 UTC, closed without merging