Automation menu - base PR
astronomer/docs pull request #2593
Opened 2023-07-21 10:57 UTC by jwitz

All projects related to the new "Automation" menu should be branches off of this PR.

2023-07-21 11:15 UTC, manmeetkaur commented on sidebarsAstro.js
> +      label: "Automation",
I am thinking instead of automation, we should name it as "Programmatic access"
```suggestion
      label: "Programmatic access",
```

2023-08-04 10:37 UTC, jwitz commented on astro/automation-authentication.md
> +sidebar_label: 'Authentication'
```suggestion
sidebar_label: 'Authenticate an automated workflow'
```

2023-08-04 10:37 UTC, jwitz commented on astro/automation-authentication.md
> +Astro's authentication process is based on [Auth0 Identifier First Authentication flow](https://auth0.com/docs/authenticate/login/auth0-universal-login/identifier-first). This process doesn't provide
```suggestion
```

2023-08-04 10:37 UTC, jwitz commented on astro/automation-authentication.md
> +
```suggestion

Astro's authentication process is based on [Auth0 Identifier First Authentication flow](https://auth0.com/docs/authenticate/login/auth0-universal-login/identifier-first). This process doesn't provide authorization and doesn't care what a user can do in Astro. To manage authorization in Astro, see [User permissions](user-permissions.md).

```

2023-08-07 12:29 UTC, jwitz commented on astro/automation-authentication.md
> +To manage your Astro processes programmatically, you must install the Astro CLI in the environment which will execute the actions. Typically, this requires running `curl -sSL install.astronomer.io |
```suggestion
To manage your Astro workflows programmatically, you must install the Astro CLI in the environment which will run the workflows. Typically, this requires running `curl -sSL install.astronomer.io | sudo bash -s` or an equivalent installation command before your process starts. See [CI/CD templates](ci-cd-templates/template-overview.md) for examples of how to install the Astro CLI in different version management and workflow automation environments. 
```

2023-08-07 13:32 UTC, jwitz commented on astro/automation-overview.md
> +- [Manage users, teams, and tokens](cli/astro-workspace-team.md) in your Workspace.
```suggestion
- [Manage users, Teams, and tokens](cli/astro-workspace-team.md) in your Workspace.
```

2023-08-07 13:32 UTC, jwitz commented on astro/automation-overview.md
> +- Perform all Workspace-level actions in any Workspace in your Organization.
```suggestion
```

2023-08-07 13:32 UTC, jwitz commented on astro/automation-overview.md
> +- [Export audit logs](audit-logs.md#export-audit-logs).
```suggestion
- Export [audit logs](audit-logs.md#export-audit-logs). 
```

2023-08-07 13:33 UTC, jwitz commented on astro/automation-overview.md
> +- [Manage users, teams, and tokens](cli/astro-organization-list.md), such as inviting new users, rotating existing tokens, etc.
```suggestion
- [Manage Organization users, Teams, and tokens](cli/astro-organization-list.md).
```

2023-08-07 13:38 UTC, jwitz commented on sidebarsAstro.js
> +            "deployments-as-code",
```suggestion
            "manage-deployments-as-code",
```

2023-08-14 19:27 UTC, lzdanski reviewed
First pass editorial comments/ style and grammar

2023-08-14 19:27 UTC, lzdanski commented on astro/deployment-file-reference.md
> +After you create an Astro Deployment, you can use the Astro CLI to create a file that contains its unique configurations represented as code. That includes worker queues, environment variables, Astro
```suggestion
After you create an Astro Deployment, you can use the Astro CLI to create a Deployment file that contains its unique configurations represented as code. That includes worker queues, environment variables, Astro Runtime version, and more. You can use Deployment files to manage Deployments programmatically on Astro.
```

2023-08-14 19:27 UTC, lzdanski commented on astro/deployment-file-reference.md
> +A _Deployment template file_ is different from the _Deployment file_. A template file does not have the `metadata` and `environment_variables` section, and the `name` and `description` fields are emp
```suggestion
A _Deployment template file_ is different from the _Deployment file_. A template file does not have the `metadata` and `environment_variables` section, and the `name` and `description` fields are empty. Deployment template files are used to create new Deployments, while a Deployment file of an existing Deployment can be used to update its configuration. To create a Deployment template file in YAML format, run `astro deployment inspect <your-deployment-id> --template > your-deployment.yaml`.
```

2023-08-14 19:27 UTC, lzdanski commented on astro/deployment-file-reference.md
> +See the following topics to learn about each section in the file.
```suggestion
The following sections describe each section in the file.
```
Just a convention thing - `topic` sometimes refers to individual pages instead of subsections or sections on. page.

2023-08-14 19:27 UTC, lzdanski commented on astro/deployment-file-reference.md
> +If you commit a template file to a GitHub repository, you should not add secret environment variables in the file. Instead, add them manually in the Cloud UI. This ensures that you do not commit secr
```suggestion
If you commit a template file to a GitHub repository, do not add secret environment variables in the file. Instead, add them manually in the Cloud UI. This ensures that you do not commit secret values to a version control tool in plain-text.
```

2023-08-14 19:27 UTC, lzdanski commented on astro/manage-deployments-as-code.md
> +Use this document to learn how to create and manage Deployment files and Deployment template files. See [Deployment file reference](./deployment-file-reference.md) for a list of all configurable Depl
```suggestion
Use this document to learn how to create and manage Deployment files and Deployment template files. See the [Deployment file reference](./deployment-file-reference.md) for a list of all configurable Deployment file values. 
```

2023-08-14 19:40 UTC, lzdanski reviewed
Follow up after reviewing preview

2023-08-14 19:40 UTC, lzdanski commented on astro/configure-deployment-resources.md
> +description: "Manage the Deployment settings to customize your Deployment based on your use-case."
```suggestion
description: "Manage the Deployment settings to customize your Deployment based on your use case."
```

2023-08-14 19:40 UTC, lzdanski commented on astro/manage-deployments-as-code.md
> +You can configure Deployments using Deployment files and Deployment template files. _Deployment files_ are used to update the same Deployment programmatically, and _Deployment template files_ are use
Do we also need to add these terms to a glossary?

2023-08-15 05:14 UTC, paolaperaza requested changes
Sorry folks, doing request changes here -- I'd love to see:

1. Discussion around the true distinct purpose of automation overview and authentication-automation overview. I lean towards combining them, but let's discuss in Slack if folks disagree.
2. Some crisper writing on the authentication overview in particular.

I'm a fan of the Deployment file reference, and the new sidebar in general. We're close... and thanks @lzdanski for the review here too.

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +- Create a credential in Astro.
Doesn't have to be this exact wording, but some "so what" thing if this is a conceptual doc

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +Before you automate your workflows on Astro, you must prove to Astro that your automation tool is using the right identity and access to interact with specific Astro resources. You can do this using
Also, I'd like to see a: "This guide helps you...". Just since the scope of the doc is a bit unclear, and there's obviously lots of links out to other places and related content that a user might get confused about

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +## Create a credential
```suggestion
## Create an API token or API key
```

Let's just call it this explicitly instead of introducing a third term?

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +You can create API tokens with role-based access permissions, ensuring that they are not over-provisioned for their intended use. When you chose a credential, you should grant it the least amount of
Agreed, "over-provisioned" is a bit weird here. Can we be more specific, clear here?

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +The Astro CLI uses reserved environment variables to read your credential information to authenticate to Astro. You must set these environment variables in your automation environment.
"Reserved"? Might be good to start this sentence with env-vars first language vs. "this is how the Astro CLI works"

What's the purpose of Env Vars here? Also, we now keep using "in your automation environment" and I don't super know what that means. Let's give examples like, "GitHub secrets"?

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +
Now what? No other "next steps" or links?

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-overview.md
> +If you need to perform some actions repeatedly, it is beneficial to combine them into workflows and automate these workflows using a tool of your choice. This helps to make your repeated processes mo
Is there a CI/CD workflow that isn't automated?

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-authentication.md
> +sidebar_label: 'Authenticate an automated workflow'
TBH -- This doc is a little confusing to me in that it's both:

- "What are API keys" (duplicate of API tokens docs)
- "How do I generally automate things on Astro" (duplicate of automation overview?)

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-overview.md
> +- Fetch a short-lived access token to use [Airflow REST API](airflow-api.md) for your Deployment. This assumes the same permissions as your API key.
Would turn this into action-first vs. token first

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-overview.md
> +- Fetch a short-lived access token to use [Airflow REST API](airflow-api.md) for your Deployment. This assumes the same permissions as your API key.
Do we have to say "using CI/CD" (the same as automation") and "using a Deployment file"? Let's just keep it to the action and not the implementation detail, which the user will decide on

2023-08-15 05:14 UTC, paolaperaza commented on astro/automation-overview.md
> +sidebar_label: 'Overview'
Reading this one -- I personally would combine automation-authentication into automation-overview. They're both short and primarily educational vs. actionable, which makes me feel like it's better for the user to have the context in one place vs. repeating and navigating two URLs without an obvious behavioral difference in each

2023-08-15 05:14 UTC, paolaperaza commented on astro/deployment-file-reference.md
> +### `deployment.environment_variables`
Worth re-pasting the env vars section part of the file?

2023-08-15 09:42 UTC, jwitz commented on astro/automation-authentication.md
> +Before you automate your workflows on Astro, you must prove to Astro that your automation tool is using the right identity and access to interact with specific Astro resources. You can do this using
I think some of the expository info you want to cover here is why the "Overview" doc exists. If someone lands on this doc and doesn't know what they would be automating, a common action would be to go to the Overview to get more context. I don't want to overload the top of this doc with context that's explained elsewhere.

2023-08-15 09:43 UTC, jwitz commented on astro/automation-authentication.md
> +- Create a credential in Astro.
This is not a conceptual doc - it's explicit purpose is to give steps for authenticating a tool to Astro, so that would make it a process doc

2023-08-15 09:53 UTC, jwitz commented on astro/automation-authentication.md
> +Astro's authentication process is based on [Auth0 Identifier First Authentication flow](https://auth0.com/docs/authenticate/login/auth0-universal-login/identifier-first). This process doesn't provide
Manmeet added this paragraph because it's apparently a common question that comes up amongst customers and the field. It's meant to both

- Say the doc is NOT about authorization.
- Link users to the right doc for authorization management (user permissions).

2023-08-15 09:58 UTC, jwitz commented on astro/automation-authentication.md
> +The Astro CLI uses reserved environment variables to read your credential information to authenticate to Astro. You must set these environment variables in your automation environment.
Tried to make the environment variable workflow more clear

We include the example in the top: `automation environment, such as a GitHub Actions.`

2023-08-15 10:01 UTC, jwitz commented on astro/automation-overview.md
> +sidebar_label: 'Overview'
I disagree that the authentication is primarily educational. This Overview doc could use more distinguishing content, but the automation doc describes the specific workflow of setting up an automation tool to connect with Astro.

2023-08-15 10:08 UTC, jwitz commented on astro/automation-authentication.md
> +sidebar_label: 'Authenticate an automated workflow'
This doc is "how do you set up your automation environment to connect to Astro"

2023-08-15 10:13 UTC, jwitz commented on astro/automation-overview.md
> +If you need to perform some actions repeatedly, it is beneficial to combine them into workflows and automate these workflows using a tool of your choice. This helps to make your repeated processes mo
Idk how this paragraph got kept in, it's removed on my local branch. I've updated it to more explicitly state the benefits of automation.

2023-08-15 10:24 UTC, jwitz commented on astro/deployment-file-reference.md
> +### `deployment.environment_variables`
Doing that for each section would create a lot of bloat, I think it's better to show in the context of the whole file.

2023-08-15 10:39 UTC, jwitz commented on astro/automation-authentication.md
> +sidebar_label: 'Authenticate an automated workflow'
```suggestion
sidebar_label: 'Authenticate an automation environment'
```
I still don't like the current title, as you are technically authenticating the tool, not the script. But I am open to other suggestions here.

2023-08-15 10:46 UTC, jwitz commented
@paolaperaza Ready for another look! I tried distinguishing the overview and authentication docs, plus I added more content around benefits/ usage in the Deployment files docs.

2023-08-15 23:13 UTC, lzdanski reviewed
A couple more discussion comments-

2023-08-15 23:13 UTC, lzdanski commented on astro/automation-overview.md
> +sidebar_label: 'Overview'
re: additional content (and this might be outside of the scope of this PR) - I think this page meeting the need of consolidating and presenting some general conceptual and introductory info, but it might need a sentence that explicitly calls out the type of user this content is meant for. I noticed when I was testing this page in preview that the pages the links point to in the "common use cases" are in different sections of the docs. I was expecting them to go to child links of this page in the sidebar or to subsections of the child page, so I had to stop and think a little about how and why these actions were categorized into groups. Some are in the CLI, others in CI/CD, peer topics in Manage Deployments etc.

- What kind of Astro user sets up and configures automation? Any user? Or does it require specific permissions/user profile?
- We've got a heading that says _Use Case_, but the children are _Actions_. Maybe it needs a small word choice change or a sentence between the header and the action categories showing the relationship? ie "After you authenticate your automation tools to Astro, you can automate combinations of actions within these categories to make administering your Astro environment easier."

2023-08-21 13:59 UTC, paolaperaza approved these changes
Left a couple of minor comments, but a final ✅  here

2023-08-21 13:59 UTC, paolaperaza commented on astro/automation-authentication.md
> +- Always give your API token or key the minimum permissions required to perform an action. This improves control and security over your Astro components. For example, instead of creating an Organizat
```suggestion
- Always give your API token or key the minimum permissions required to perform an action. This improves control and security over your Astro components. For example, instead of creating an Organization API token to automate actions in two Workspaces, create two separate Workspace API tokens for each Workspace.
```

2023-08-21 13:59 UTC, paolaperaza commented on astro/automation-overview.md
> +- [Enforce CI/CD deploys](configure-deployment-resources.md#enforce-cicd-deploys) for your production Deployments to avoid accidental deploys by users while testing.
Is this section elsewhere too?

2023-08-21 13:59 UTC, paolaperaza commented on astro/deployment-file-reference.md
> +A _Deployment template file_ is different from the _Deployment file_. A template file does not have the `metadata` and `environment_variables` section, and the `name` and `description` fields are emp
This is great

2023-08-21 13:59 UTC, paolaperaza commented on astro/deployment-file-reference.md
> +The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for a Deployment. If you don't enter specific values for the `default` worker queue for a Deployment with CeleryExe
```suggestion
The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for a Deployment. If you don't enter specific values for the `default` worker queue for a Deployment with CeleryExecutor, default values based on the worker types available on your cluster are applied.

This section is not applicable to Deployments running with the Kubernetes executor. 
```

2023-08-22 10:13 UTC, jwitz commented on astro/automation-authentication.md
> +title: 'Authenticate to Astro for automated workflows'
It's not just CI/CD tho - scripts can cover a wide variety of use cases beyond CI/CD

2023-08-22 10:37 UTC, jwitz commented on astro/automation-overview.md
> +- Use [Airflow REST API](airflow-api.md) for your Deployment.
You don't make the request from the Deployment, you usually make a request to retrieve/ update details on a Deployment from another source

2023-09-01 13:27 UTC, jwitz commented on astro/deployment-file-reference.md
> +        status: CREATING
```suggestion
        status: CREATING
        workloadIdentity: astro-release-name@provider-account.iam.gserviceaccount.com
```

2023-09-01 13:27 UTC, jwitz commented on astro/deployment-file-reference.md
> +        workloadIdentity: astro-release-name@provider-account.iam.gserviceaccount.com
```suggestion
```

2023-09-01 13:27 UTC, merged