Split user management at RBAC level
astronomer/docs pull request #2596
Opened 2023-07-21 14:39 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/2313

This should help to clean up our user management content and make it easier for each admin type to discover their respective docs.

2023-07-24 14:47 UTC, jwitz commented on sidebarsAstro.js
> +                "add-organization-users",
```suggestion
                "manage-organization-users",
```

2023-08-04 08:05 UTC, manmeetkaur requested changes
sorry, I put too many comments! 😬

2023-08-04 10:07 UTC, jwitz reviewed
@manmeetkaur I must have written this PR when there was a painter in my apartment 😵 apologies for having to work through all of my typos! Accepted most of your changes and added a few questions

2023-08-04 11:15 UTC, manmeetkaur commented on astro/manage-organization-users.md
> +3. Create a file named `add-users.sh` and then add the following script to it:
@jwitz I ordered in the way a user would open a new file, do something and save; not the other way around. Just found it weird seeing "Create file called blah.txt" as the first step. But I am not picky about this, leave it up to you to decide the standard :)

2023-08-04 11:29 UTC, manmeetkaur approved these changes
@jwitz some of the suggestions did not get through in `manage-workspaces`. I suggested those changes again. I think once you address those, we are good.

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +
I do want to write "space-delimited" here because the next script will only work if there is a space between the email and the role.

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +    ```
I thought I changed these, these roles are incorrect.
```suggestion
    user1@astronomer.io WORKSPACE_MEMBER
    user2@astronomer.io WORKSPACE_ADMIN
    user3@astronomer.io WORKSPACE_EDITOR
    user4@astronomer.io WORKSPACE_ADMIN
    ```
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +As a Workspace Admin or Organization Owner, you can add new team members to Astro and grant them user roles with permissions for specific actions across your Workspace.
```suggestion
As a Workspace Admin or an Organization Owner, you can add new team members to Astro and grant them user roles with permissions for specific actions across your Workspace.
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +1. In the Cloud UI, click **Workspace Settings** > **Access Management**.
```suggestion
1. In the Cloud UI, click the Astronomer logo in the upper left corner. Then, go to **Workspaces** and select your Workspace.
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +2. In the **Users** tab, click **+ Member**.
```suggestion
2. Go to **Workspace Settings** > **Access Management**. In the **Users** tab, click **+ Member**.
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +
```suggestion
3. Select the user's name and email address in the **Organization Member** list.
   
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +
in the Cloud UI **ORGANIZATION MEMBER** and **WORKSPACE ROLE** are both capitalized, that is why in my previous suggestion I had made them capital. some of those changes have been lost, idk why.

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +1. In the Cloud UI, go to **Workspace Settings** > **Access Management**.
```suggestion
1. In the Cloud UI, click the Astronomer logo in the upper left corner. Then, go to **Workspaces** and select your Workspace.
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +3. Click **Edit** next to the user's name.
```suggestion
2. Go to **Workspace Settings** > **Access Management**. 
3. In the **Users** tab, click **Edit** next to the user's name you want to change the role for.
```

2023-08-04 11:29 UTC, manmeetkaur commented on astro/manage-workspace-users.md
> +6. Select a role for the user and then click **Add member**. See [Workspace roles reference](user-permissions.md#workspace-roles).
```suggestion
4. Select a role for the user and then click **Add member**. See [Workspace roles reference](user-permissions.md#workspace-roles).
```

2023-08-04 12:52 UTC, jwitz commented on astro/manage-workspace-users.md
> +
See my previous comment: https://github.com/astronomer/docs/pull/2596#discussion_r1284230999

2023-08-04 13:18 UTC, jwitz commented on astro/manage-workspace-users.md
> +As a Workspace Admin or Organization Owner, you can add new team members to Astro and grant them user roles with permissions for specific actions across your Workspace.
Nouns can share indefinite articles. I tend to use this styling to reduce the number of words on the page. See also: https://forum.wordreference.com/threads/can-several-nouns-share-one-article.1542128/

2023-08-04 13:20 UTC, jwitz commented on astro/manage-workspace-users.md
> +5. Select the user's name and email address in the **Organization Member** list.
```suggestion
3. Select the user's name and email address in the **Organization Member** list.
```

2023-08-04 13:20 UTC, jwitz commented on astro/manage-workspace-users.md
> +3. Click **Edit** next to the user's name.
```suggestion
2. Click **Edit** next to the user's name.
```

2023-08-04 13:20 UTC, jwitz commented on astro/manage-workspace-users.md
> +5. If you've updated the user's role, click **Update member**. To delete the user, click **Remove member**.
```suggestion
3. (Optional) Edit the user's name and role. See [Workspace roles](user-permissions.md).
   
4. If you've updated the user's role, click **Update member**. To delete the user, click **Remove member**.
```

2023-08-04 13:21 UTC, jwitz commented on astro/manage-workspace-users.md
> +2. Open the text file and add a list of user email addresses that you want to invite to a Workspace. Every email address should include the user's assigned role. The following is an example of how yo
```suggestion
2. Open the text file. On each line, add a user's email and their role separated by a space. The following is an example of how you can write a list for inviting users to an Organization:
```

2023-08-04 13:23 UTC, jwitz commented on astro/manage-workspace-users.md
> +    ```
Changed these because the CLI is still using the older values

2023-08-04 13:26 UTC, jwitz commented on astro/manage-organization-users.md
> +    After you add the user, their information appears in the **Users** tab in **Access Management**. To access Astro, the user needs to accept the invitation sent by email and then create an Astro ac
```suggestion
After you add the user, their information appears in the **Users** tab in **Access Management**. To access Astro, the user needs to accept the invitation sent by email and then create an Astro account.
```

2023-08-04 13:49 UTC, merged