[2.7] Update to the dependencies guide
astronomer/docs pull request #2597
Opened 2023-07-21 21:13 UTC by TJaniF

2.7 adds the `chain_linear` function. :)

2023-07-25 15:38 UTC, kentdanas requested changes
This looks great! Love the cropped screenshots, the guide looks much cleaner. Requesting changes based on my comment about the looping section. Let me know what you think about that.

2023-07-25 15:38 UTC, kentdanas commented on learn/managing-dependencies.md
> +Dependency functions are utilities that let you set dependencies between several tasks and lists of tasks. A common reason to use dependency functions over bit-shift operators is for example to creat
```suggestion
Dependency functions are utilities that let you set dependencies between several tasks and lists of tasks. A common reason to use dependency functions over bit-shift operators is to create dependencies for tasks that were created in a loop and are stored in a list.
```

2023-07-25 15:38 UTC, kentdanas commented on learn/managing-dependencies.md
> +Replacing `chain` with `chain_linear` in the previous example as shown in this code snippet will create a DAG structure where the dependency between lists is set in a pattern so that each element in
```suggestion
Replacing `chain` in the previous example with `chain_linear` will create dependencies such that each element in the downstream list will depend on each element in the upstream list.
```

2023-07-25 15:38 UTC, kentdanas commented on learn/managing-dependencies.md
> +The [TaskFlow API](airflow-decorators.md) added decorators to Airflow, one of these decorators, `@task`, allows you to easily turn Python functions into Airflow tasks.
```suggestion
The [TaskFlow API](airflow-decorators.md) `@task` decorator allows you to easily turn Python functions into Airflow tasks. 
```

2023-07-25 15:38 UTC, kentdanas commented on learn/managing-dependencies.md
> +## Loops and dependencies
High level, do we think generating tasks in a loop is still relevant now that dynamic task mapping exists? I'm sure there are edge cases, but is it relevant enough to keep this section? I would lean towards removing it, but open to arguments otherwise.

2023-07-25 15:38 UTC, kentdanas commented on learn/managing-dependencies.md
> +Tasks that utilize [dynamic task mapping](dynamic-tasks.md) can be set to be up- and downstream of other tasks as with regular tasks. Keep in mind that when using the default [trigger rule](#trigger-
```suggestion
Dependencies for [dynamically mapped tasks](dynamic-tasks.md) can be set in the same way as regular tasks. Keep in mind that when using the default [trigger rule](#trigger-rules) `all_success`, all mapped task instances need to be successful for the downstream task to run. For the purpose of trigger rules, mapped task instances behave like a set of parallel upstream tasks.
```

2023-07-31 08:29 UTC, TJaniF reviewed
Thank you @kentdanas !
I think you are right about the looping section. Removed it for now :)

2023-07-31 08:29 UTC, TJaniF commented on learn/managing-dependencies.md
> +## Loops and dependencies
Hmm... I think using loops to create tasks is probably still used a lot for non-dynamic mapping (e.g. I have this task and 20 fixed tables it needs to run on) but yes we should encourage best practices and I can't really think of a case (now that dynamic task group mapping exists) where looping would have any advantage over using dynamic mapping 🤔 
I mean, unless people are on old versions, that would be my one weak argument for keeping it. 
In general I think if someone is using a loop to create tasks they probably also know how to handle objects in a loop and be able to figure out the info in this section. 

I will remove the section for now but save it somewhere just in case. 😄

2023-08-11 10:29 UTC, jwitz approved these changes

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +When using bit-shift operators and the `.set_upstream` and `.set_downstream` method, it is not possible to set dependencies between two lists. For example, `[t0, t1] >> [t2, t3]` returns an error. To
```suggestion
When you use bit-shift operators and the `.set_upstream` and `.set_downstream` method, you can't set dependencies between two lists. For example, `[t0, t1] >> [t2, t3]` returns an error. To set dependencies between lists, use the dependency functions described in the following section.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +Dependency functions are utilities that let you set dependencies between several tasks and lists of tasks. A common reason to use dependency functions over bit-shift operators is to create dependenci
```suggestion
Dependency functions are utilities that let you set dependencies between several tasks or lists of tasks. A common reason to use dependency functions over bit-shift operators is to create dependencies for tasks that were created in a loop and are stored in a list.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +When using the `chain` function, any lists or tuples that are set to depend directly on each other need to be of the same length.
```suggestion
When you use the `chain` function, any lists or tuples that are set to depend directly on each other need to be the same length.  
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +### chain_linear()
```suggestion
### Using `chain_linear()`
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +### chain()
```suggestion
### Using `chain()`
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +Replacing `chain` in the previous example with `chain_linear` will create dependencies such that each element in the downstream list will depend on each element in the upstream list.
```suggestion
Replacing `chain` in the previous example with `chain_linear` creates dependencies where each element in the downstream list will depend on each element in the upstream list.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +The `chain_linear()` function can take in lists of any length in any order. For example:
```suggestion
The `chain_linear()` function can accept lists of any length in any order. For example, the following arguments are valid:
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +Dependencies for [dynamically mapped tasks](dynamic-tasks.md) can be set in the same way as regular tasks. Keep in mind that when using the default [trigger rule](#trigger-rules) `all_success`, all m
```suggestion
Dependencies for [dynamically mapped tasks](dynamic-tasks.md) can be set in the same way as regular tasks. Note that when using the default [trigger rule](#trigger-rules) `all_success`, all mapped task instances need to be successful for the downstream task to run. For the purpose of trigger rules, mapped task instances behave like a set of parallel upstream tasks.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +[Task groups](task-groups.md) are an Airflow concept allowing for grouping of tasks in the UI and for [dynamic mapping use cases](task-groups.md#generate-task-groups-dynamically-at-runtime). You can
```suggestion
[Task groups](task-groups.md) are tasks that are logically grouped in the Airflow UI and for [dynamic mapping use cases](task-groups.md#generate-task-groups-dynamically-at-runtime). This section will explain how to set dependencies between task groups.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +Dependencies can be set both inside and outside of a task group. For example, in the following DAG code there is a start task, a task group with two dependent tasks, and an end task. All of these tas
```suggestion
Dependencies can be set both inside and outside of a task group. For example, in the following DAG code there is a start task, a task group with two dependent tasks, and an end task. All of these tasks need to happen sequentially. The dependencies between the two tasks in the task group are set within the task group's context (`t1 >> t2`). The dependencies between the task group and the start and end tasks are set within the DAG's context (`t0 >> tg1() >> t3`).
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +You can also set dependencies between task groups, between tasks outside of a task group and tasks inside a task group and even between tasks in different (nested) task groups.
```suggestion
You can also set dependencies between task groups, between tasks inside and out of task groups, and even between tasks in different (nested) task groups.
```

2023-08-11 10:29 UTC, jwitz commented on learn/managing-dependencies.md
> +Note that it is also possible to assign the called function to an object and then pass that object to the downstream task. This way of defining dependencies between `@task` decorated tasks is often e
```suggestion
Note that you can also assign the called function to an object and then pass that object to the downstream task. This way of defining dependencies is often easier to read and allows you to set the same task as an upstream dependency to multiple other tasks. 
```

2023-08-13 13:16 UTC, TJaniF commented
Proofread and ready to go :)

2023-08-18 16:37 UTC, merged