Fix peering terms and process
astronomer/docs pull request #2622
Opened 2023-07-31 06:57 UTC by manmeetkaur

This PR clears the steps for creating a creating a new TGW attachment. 

Reference: 
- https://astronomer.zendesk.com/knowledge/articles/8643574453651/en-us?brand_id=360001488713
- https://astronomer.zendesk.com/agent/tickets/11659

2023-07-31 20:10 UTC, stuart23 commented on astro/connect-aws.md
> +4. After you receive confirmation from Asronomer support with the Astro CIDR, you can [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the
```suggestion
4. After you receive confirmation from Astronomer support with the Astro CIDR, you can [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the transit gateway to the Astro VPC.
```

2023-08-08 16:36 UTC, manmeetkaur commented on astro/connect-aws.md
> +2. In your AWS console, [create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html). Then, copy the ID of your existing transit gateway.
add that it is the same acount where your TGW resides today

2023-08-08 16:44 UTC, stuart23 approved these changes

2023-08-09 10:16 UTC, jwitz requested changes
A few questions about step 2, but besides that LGTM!

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +1. In the Cloud UI, click on the Astronomer icon in the top left corner, go to the **Clusters** tab and copy the **ID** for your Astro cluster.
```suggestion
1. In the Cloud UI, click the name of your Workspace in the upper left corner of the Cloud UI, then click **Organization Settings** > **Clusters*. Open your cluster from the table that appears and copy its **ID**.
```

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +2. Go to your AWS console, and copy the ID of your existing transit gateway (TGW). Then, [create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-cre
```suggestion
2. In your AWS console, copy the ID of your existing transit gateway (TGW). Then, [create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your Organization's Astro AWS account](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-transit-gateways.html#tgw-sharing).
```
Its the AWS account for the Org, not the cluster right? Where do they find the ID to specify?

Also, where do they need to specify the TGW ID? If they just need it for the Astro support team, we should split this into a second step.

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +3. Contact [Astronomer support](https://cloud.astronomer.io/support) and provide the following:
```suggestion
3. Contact [Astronomer support](https://cloud.astronomer.io/support) and provide the following information:
```

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +    - Your CIDR block for the target VPC or on-premises network that you want to connect your Astro cluster with
```suggestion
    - Your cluster **ID** from Step 1.
    - Your TGW ID from Step 2.
    - The CIDR block for the target VPC or on-premises network that you want to connect your Astro cluster with.
```

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +    Then, Astronomer support approves the resource sharing request, attaches the Astro private subnets to your transit gateway, and creates routes in the Astro route tables to your transit gateway fo
```suggestion
    Astronomer support approves the resource sharing request, attaches the Astro private subnets to your transit gateway, and creates routes in the Astro route tables to your transit gateway for each of the CIDRs provided.
```

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +    Then, Astronomer support approves the resource sharing request, attaches the Astro private subnets to your transit gateway, and creates routes in the Astro route tables to your transit gateway fo
Great description

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +4. After you receive confirmation from Astronomer support with the Astro CIDR, you can [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the
```suggestion
4. After you receive confirmation from Astronomer support, [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the transit gateway to the Astro VPC.
```

2023-08-09 10:16 UTC, jwitz commented on astro/connect-aws.md
> +7. (Optional) Repeat the steps for each Astro cluster that you want to connect to your transit gateway.
```suggestion
5. Contact [Astronomer support](https://cloud.astronomer.io/support) to confirm that you have created the static route. Astronomer support then tests the connection and confirm.

6. (Optional) Repeat the steps for each Astro cluster that you want to connect to your transit gateway.
```

2023-08-09 10:57 UTC, manmeetkaur commented on astro/connect-aws.md
> +4. After you receive confirmation from Astronomer support with the Astro CIDR, you can [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the
Astronomer support will provide the Astro CIDR, so we need to include that. let me try to reframe the sentence.

2023-08-09 11:13 UTC, manmeetkaur commented
@jwitz you can review again. Changes include:

- split the step #2 into 2 steps. 
- added info about Astro CIDR to the para in step 3.

2023-08-09 15:31 UTC, jwitz approved these changes

2023-08-09 15:31 UTC, jwitz commented on astro/connect-aws.md
> +3. [Create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your cluster's Astro AWS account](https://docs.aws.a
```suggestion
3. [Create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your cluster's Astro AWS account](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-transit-gateways.html#tgw-sharing). 

    To find your cluster's AWS account ID in the Cloud UI, click the name of your Workspace in the upper left corner, click **Organization Settings**, then click **Clusters**. Open your cluster and copy its **Account ID**.
```

2023-08-09 15:31 UTC, jwitz commented on astro/connect-aws.md
> +6. (Optional) Repeat the steps for each Astro cluster that you want to connect to your transit gateway.
```suggestion
5. After you receive the confirmation from Astronomer support, you can [create back routes](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html#tgw-peering-add-route) from the transit gateway to the Astro VPC.

6. Contact [Astronomer support](https://cloud.astronomer.io/support) to confirm that you have created the static route. Astronomer support then tests the connection and confirm.

7. (Optional) Repeat the steps for each Astro cluster that you want to connect to your transit gateway.
```

2023-08-09 15:31 UTC, jwitz commented on astro/connect-aws.md
> +3. [Create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your cluster's Astro AWS account](https://docs.aws.a
Feel free to amend if this is not correct

2023-08-09 15:40 UTC, manmeetkaur commented on astro/connect-aws.md
> +3. [Create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your cluster's Astro AWS account](https://docs.aws.a
@jwitz unfortunately, Account ID is not visible in the Cloud UI. 
<img width="713" alt="Screenshot 2023-08-09 at 9 09 54 PM" src="https://github.com/astronomer/docs/assets/75730393/fbacfc6c-56c5-420a-8ec4-65256cb406da">

2023-08-10 10:08 UTC, jwitz commented on astro/connect-aws.md
> +3. [Create a resource share in AWS RAM](https://docs.aws.amazon.com/ram/latest/userguide/working-with-sharing-create.html) and [share the TGW with your cluster's Astro AWS account](https://docs.aws.a
Oh my mistake, you can see it on Hybrid but not on Hosted.
![Screenshot 2023-08-10 at 11 05 26 AM](https://github.com/astronomer/docs/assets/74574233/6d4d43eb-bedd-4479-9bf0-07a9596e6a0f)

Updated my suggestion to reflect this

2023-08-10 10:09 UTC, jwitz approved these changes

2023-08-10 11:46 UTC, merged