Add new instructions for VPC peering
astronomer/docs pull request #2631
Opened 2023-07-31 16:10 UTC by manmeetkaur

2023-08-08 16:41 UTC, manmeetkaur commented on astro/connect-aws.md
> +1. In your AWS console, create a role using the [role creation stack template](https://docs.astronomer.io). In the template, enter a meaningful name for your stack. Then, enter your Astro AWS account
the VPC accepting AWS account. (their Data Stack not our Astro DP)

2023-08-09 10:40 UTC, jwitz requested changes
One more Q about Astro account ID usage, besides that LGTM

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +To create a VPC peering connection between an Astro VPC and an AWS VPC, a temporary assumable role needs to be created. This role will be used by the Astro AWS account to initiate a VPC peering conne
```suggestion
To create a VPC peering connection between an Astro VPC and an AWS VPC, you must create a temporary assumable role. The Astro AWS account will assume this role to initiate a VPC peering connection.
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +1. Go to the AWS console of your AWS account with the target VPC, and copy the following:
```suggestion
1. Open the AWS console of the AWS account with the target VPC and copy the following:
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +    - Your Astro AWS account ID as **Peer Owner IDs**.
```suggestion
    - **Peer Owner IDs**: Enter your Astro AWS account ID.
```
Where do you find the account ID? Is it for Org or cluster?

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +    - A meaningful name for your stack in **Stack name**.
```suggestion
    - **Stack name**: Enter a meaningful name for your stack.
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +2. Create a temporary role using the [role creation stack template](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://cre-addon-i
```suggestion
2. Create a temporary role using the [role creation stack template](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://cre-addon-infrastructure-us-east-1.s3.amazonaws.com/astro-peering-role.yaml). In the **Quick create stack** template that opens, complete the following fields:
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +    Then, click on **Create stack**.
```suggestion
```
This part is implied from our previous statement to "Create a stack"

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +3. After the stack is created, go to the **Stack info** tab and copy the assume role arn from the **Stack ID** field.
```suggestion
3. After the stack is created, go to the **Stack info** tab and copy the AssumeRole ARN from the **Stack ID** field.
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +4. In your Cloud UI, click on the Astronomer logo in the top left corner. Then, go to the **Clusters** tab, select your cluster and copy the **ID** of your cluster.
```suggestion
4. In the Cloud UI, click your Workspace name in the upper left corner, then click **Organization Settings**. Click **Clusters**, select your cluster, and copy the **ID** of the cluster.
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +    - CIDR block of the target VPC
```suggestion
    - AWS region of the target VPC from Step 1
    - VPC ID of the target VPC from Step 1
    - AWS account ID of the target VPC from Step 1
    - CIDR block of the target VPC from Step 1
    - **Stack ID** from Step 3
    - Astro cluster **ID** from Step 4
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +6. Wait for the Astronomer support to notify you with the Astro VPC CIDR. Then, the owner of the target VPC needs to [accept the peering request](https://docs.aws.amazon.com/vpc/latest/peering/accept
```suggestion
6. Wait for Astronomer support to send you the Astro VPC CIDR. Then, the owner of the target VPC needs to [accept the peering request](https://docs.aws.amazon.com/vpc/latest/peering/accept-vpc-peering-connection.html) and [create the routing table entries](https://docs.aws.amazon.com/vpc/latest/userguide/WorkWithRouteTables.html#AddRemoveRoutes) in the target VPC.
```

2023-08-09 10:40 UTC, jwitz commented on astro/connect-aws.md
> +7. (Optional) You can now delete the stack that was created for role creation. This will delete the temporary assumable role.
```suggestion
7. (Optional) Delete the stack that you created. This will delete the temporary assumable role.
```

2023-08-10 11:22 UTC, manmeetkaur commented on astro/connect-aws.md
> +    - Your Astro AWS account ID as **Peer Owner IDs**.
will add the same note as in the other PR: "To retrieve your cluster's AWS account ID on Astro Hosted, [Astronomer support](https://cloud.astronomer.io/support). To retrieve your cluster's AWS account ID in the Astro Hybrid, click the name of your Workspace in the upper left corner of the Cloud UI, click **Organization Settings**, then click **Clusters**. Open your cluster and copy its **Account ID**."

2023-08-10 11:47 UTC, manmeetkaur commented
@jwitz ready for review.

2023-08-10 16:24 UTC, jwitz commented on astro/connect-aws.md
> +    - **Peer Owner IDs**: Enter your Astro AWS account ID.
```suggestion
    - **Peer Owner IDs**: Enter your cluster's AWS account ID. To retrieve your cluster's AWS account ID on Astro Hosted, contact [Astronomer support](https://cloud.astronomer.io/support). To retrieve your cluster's AWS account ID on Astro Hybrid, click the name of your Workspace in the upper left corner of the Cloud UI, click **Organization Settings**, then click **Clusters**. Open your cluster and copy its **Account ID**.
```

2023-08-10 16:24 UTC, jwitz approved these changes

2023-08-14 11:26 UTC, merged