Updated our local and production installation guides for Astronomer Core
astronomer/docs pull request #265
Opened 2021-02-22 22:02 UTC by jwitz

This PR makes a few key changes to our existing setup guides for AC:

1. The local Quickstart now relies heavily on the Astronomer CLI
2. The production installation guide no longer mentions how to deploy DAGs (this will be in a separate doc)

All other doc changes are wording-based and shouldn't result in any change to functionality/steps from previous guides. There are still places without links and which reference "Certified" -- that will be fixed closer to actual publication. 

I'll leave questions throughout the doc for reviewers, but more generally I want to ask (especially for @ernest-kr ): What steps can we provide so that production installers can check that they successfully installed Airflow? Will they automatically be able to open `http://localhost:8080/`  because of the systemd unit file? Or are there other parts of the installation that they need to confirm using commands etc?

2021-02-22 22:03 UTC, jwitz commented on ac/next/02_production-core.md
> +If your database server is running on the same machine, you can change `peer` to `md5` to allow connections with username/password from the same machine.
This is unclear in our initial guide: "Same machine" as what?

2021-02-22 22:06 UTC, jwitz commented on ac/next/02_production-core.md
> +$ echo 'export AIRFLOW_HOME=/usr/local/airflow' | sudo tee --append ~astro/.bashrc
Does this command create the file structure that `astro dev init` creates? Do production installers need to recreate that structure themselves?

2021-03-02 16:26 UTC, paolaperaza reviewed
@jwitz Thanks for putting this together - it's definitely a good start. We'll chat about this in person, but we absolutely do need to document our target docs tree structure - I have some ideas after reading through this PR. In parallel to us figuring that out, though, I'd say let's also work on polishing up the local quickstart doc here before we get anyone else to review. That might include:

- Tightening up spelling, capitalization, formatting
- Clean up front-matter description
- Create a draft for a new "Install the Astronomer CLI" doc that's short/simple, and abstracts Astronomer product stuff away (and links out here)
- Try to clean up language about how we refer to Astronomer Core - i.e. _not_ `Astronomer Core Airflow`, not Certified, etc.
- Link out to Airflow docs/the project where you think it may be appropriate
- Clean up resources section at the end

While we get this polished up, we can in tandem identify content gaps and keep adding as we go. WDYT?

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    ```
Probably more room here to explain versioning - do you think that merits a separate "Astronomer Core Versioning" doc, much like we have "Upgrade Apache Airflow on Astronomer"? https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +3. Run `$ airflow initdb` to build out your project directory and initialize a lightweight SQLite database for Airflow.
We should figure out if people could swap SQLite for another database here - or, maybe this is our default locally and we say "to use another database in production refer to x doc"

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +Now that you have Astronomer Core Airflow running on your local machine, you might want to do one of the following:
```suggestion
Now that you have Astronomer Core running on your local machine, you might want to do one of the following:
```

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +If you want all of the features of AC, plus additional metrics, security, and customer support, consider exploring our Astronomer Cloud and Enterprise offerings.
If we assume that anyone trying out Airflow for the first time is reading this guide, I think there's a lot of room here to expand these resources. That includes:
- Linking to Airflow Docs
- Linking to Airflow Guides (mentioned but not linked), maybe suggesting 1 or 2
- If we chose to break apart our "Production" environment doc into specific guidelines on how to do x or y action, that might influence our guidance here

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +- [Docker Image](https://quay.io/repository/astronomer/ap-airflow?tab =tags)
```suggestion
- [Debian-based Docker Image](https://quay.io/repository/astronomer/ap-airflow?tab =tags)
```

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +If your database server is running on the same machine, you can change `peer` to `md5` to allow connections with username/password from the same machine.
I assume this means "on a single machine"?

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +$ echo 'export AIRFLOW_HOME=/usr/local/airflow' | sudo tee --append ~astro/.bashrc
Good question.... it may just be empty?

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +Install the AC Python Package onto your machine by running:
Question to look into: What if a user already installed this locally (by following our other doc)? Do they have to do it again? Could they use a Docker image here instead?

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +   ```
Need to look into why we call for these default Env Vars 🤔  (`   AIRFLOW__CORE__LOAD_EXAMPLES=False`, for example, calls for all the example DAGs to not show up by default, but not sure why we're making that decision for the user)

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:<your-user-password>@localhost/airflow
Should the value for `your-user-password` here be the same?

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +The password you specify here should be the same one you specified when prompted by the `createuser` command in step 1. If your password contains `%`, `/`, or `@` then you will need to url-escape; re
This should be cleaned up a bit

2021-03-02 16:26 UTC, paolaperaza commented on ac/next/02_production-core.md
> +* In this example setup, the Environment Variables for the Celery Executor specify using the main database for communication. Alternatively, you could use [Redis](https://redis.io/) to take some of t
This _may_ belong as its own separate doc?

2021-03-02 20:40 UTC, jwitz commented on ac/next/01_quickstart.md
> +- [Astronomer CLI](https://www.astronomer.io/docs/enterprise/v0.23/get-started/quickstart)
This is a can-of-worms question at the moment, as we'll have to link out regardless if we're hosting the CLI reference guide on product docs. I think our end goal would be to host all CLI docs on AC, but for the time being (ie before we have our own landing page) I don't think it hurts to link out.

2021-03-03 16:38 UTC, jwitz commented on ac/next/01_quickstart.md
> +To run Astronomer Certified locally, you'll need the following on your machine:
Assuming it's cool we do this when the packages/ images still reference certified?

2021-03-03 16:42 UTC, jwitz commented on ac/next/01_quickstart.md
> +    ```
Yep, I've got an upgrade doc in the pipelines! Would definitely link here once it's completed.

2021-03-03 17:00 UTC, jwitz commented on ac/next/01_quickstart.md
> +3. Run `$ airflow initdb` to build out your project directory and initialize a lightweight SQLite database for Airflow.
It looks like you can modify aspects of the db by running `airflow reset` after changing configurations in `airflow.cfg`, but you always need to run `airflow initdb` once to actually initialize it. For the quickstart, I think this would suffice. But if we have a doc about modifying the database in the future, this would be a good place to link that.

2021-03-03 17:02 UTC, jwitz commented on ac/next/02_production-core.md
> +Install the AC Python Package onto your machine by running:
This is something I still don't fully understand: what does this setup look like if you *want* to use Docker? Do we need a fully separate setup guide for using Docker/ Kube?

2021-03-03 17:13 UTC, jwitz commented on ac/next/02_production-core.md
> +   ```
I assume we do that because it's for production? Otherwise, we'd have to mention in a separate guide how to turn those off. We could also explain what each one does just below it and give users the discretion to modify as needed.

2021-03-03 17:13 UTC, jwitz commented on ac/next/02_production-core.md
> +* In this example setup, the Environment Variables for the Celery Executor specify using the main database for communication. Alternatively, you could use [Redis](https://redis.io/) to take some of t
Making a note of this in clubhouse

2021-03-03 23:59 UTC, jwitz commented
@paolaperaza Per our discussion today, updated the local quickstart to include installation steps for the Astro CLI. Also updated the title and description of the production installation guide.

2021-03-09 05:18 UTC, paolaperaza requested changes
@jwitz Finally got a chance to take a deeper look at this. Let's focus on changes to Local Quickstart for now and merge that separately to the changes in "Production Core".

Some small comments on typos and copy suggestions, but a few comments as well on some additional content and structure we may be able to add. Let me know what you think.

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +For Astronomer's full collection of Docker Images, reference our public [Quay.io repository](https://quay.io/repository/astronomer/ap-airflow?tab=tags).
```suggestion
For every major and minor version of Apache Airflow, our team produces two Astronomer Core artifacts:

- [A Debian-based Docker image](https://quay.io/repository/astronomer/ap-airflow?tab=tags)
- [A Python Wheel](https://pip.astronomer.io/simple/apache-airflow/)

This quickstart focuses on the Astronomer Core Docker image, which is the recommended and most popular way to deploy the offering. For instructions on how to install the Python Wheel, read [Install via Python Wheel](/docs/ac/next/01_quickstart#install-via-python-wheel).

For Astronomer's full collection of Docker images, reference either of our public Docker registries:

- [Quay.io](https://quay.io/repository/astronomer/docker-airflow?tab=tags).
- [Docker Hub](https://hub.docker.com/r/astronomerio/docker-airflow)
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +> **Note: Astronomer Core is also hosted on [Docker Hub](https://hub.docker.com/r/astronomerinc/ap-airflow), but pulling your image from there might result in rate limiting errors. Because of that, w
```suggestion
> **Note**: While you're free to pull the Astronomer Core Docker image from Docker Hub, you may encounter a [Docker pull rate limit error](https://forum.astronomer.io/t/docker-hub-rate-limit-error-toomanyrequests-you-have-reached-your-pull-rate-limit/887). To avoid limitations, we recommend referencing and pulling from Quay.io.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +Astronomer's [open source CLI](https://github.com/astronomer/astro-cli) is the easiest way to run Airflow on your local machine. You'll need the CLI to complete this quickstart and create a local Air
```suggestion
Astronomer's [open source CLI](https://github.com/astronomer/astro-cli) is the easiest way to run Airflow on your local machine. You'll need the Astronomer CLI to create a local Airflow instance with a dedicated Webserver, Scheduler, and Postgres database.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +Astro CLI Version: 0.15.0
```suggestion
Astro CLI Version: 0.23.3
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +To install and run the Astronomer Core distribution:
```suggestion
To install and run the Astronomer Core distribution, follow the steps below.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +3. Start Airflow on your local machine by running the following command:
```suggestion
3. Start Airflow locally by running the following command:
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    docker ps
```suggestion
   $ docker ps
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +We also distribute Astronomer Core as a python wheel available on PyPi. This distribution can be run locally via the same mechanisms used to run the Apache Airflow package.
```suggestion
In addition to the Docker-based distribution, Astronomer Core is built as a Python Wheel available on PyPi. This distribution can be run locally via the same mechanisms used to run the Apache Airflow package.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +1. Run `export AIRFLOW_HOME=~/airflow` to give Astronomer Core a home root directory on your machine.
```suggestion
1. Run `$ export AIRFLOW_HOME=~/airflow` to give Astronomer Core a home root directory on your machine.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10.*'
Does this assume the latest `Airflow 1.10.x`? Should we be prescriptive here in proposing 2.0, or at least call this out?

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    Note that if you'd like to install a specific version, you can do so by appending the version tag via the following syntax:
```suggestion
    To install a specific version of Astronomer Core, append the version tag via the following syntax:
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10.*'
```suggestion
   $ PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10.*'
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10-1'
```suggestion
   $ PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10-1'
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==1.10.10-1'
Should this be `astronomer-certified==<airflow-version>`?

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +4. Run `$ airflow webserver -p 8080` to spin up the Webserver on your `localhost:8080`.
```suggestion
4. Run `$ airflow webserver -p 8080` to provision the Webserver on your `localhost:8080`.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +5. Run `$ airflow scheduler` to spin up the Scheduler.
```suggestion
5. Run `$ airflow scheduler` to provision the Scheduler.
```

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +If you want all of the features of AC, plus additional metrics, security, and customer support, consider exploring our Astronomer Cloud and Enterprise offerings.
^ Still applicable 🙂

2021-03-09 05:18 UTC, paolaperaza commented on ac/next/01_quickstart.md
> +## Next Steps
This guide seems to stop at the point where you have the Astronomer CLI installed, but it feels a little bit like we're leaving the user hanging. We need to figure out a connection here with the "Production" story", but I'd consider adding an extra section for:

- "Apply Changes to your Airflow Project" - https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart#apply-changes-to-your-airflow-project

Once we have CLI reference guide, will be critical to link here too.

2021-03-09 16:08 UTC, jwitz commented on ac/next/01_quickstart.md
> +title: "Astronomer Core Quickstart"
I think `local` is implied by the nature of a quickstart. Also would that not imply the existence of a production quickstart, which we don't really have?

2021-03-09 16:26 UTC, jwitz commented on ac/next/01_quickstart.md
> +To install and run the Astronomer Core distribution:
Reworded slightly

2021-03-09 16:34 UTC, jwitz commented on ac/next/01_quickstart.md
> +1. Run `export AIRFLOW_HOME=~/airflow` to give Astronomer Core a home root directory on your machine.
Assuming these suggestions are nulled given our recent Slack convo

2021-03-09 23:15 UTC, paolaperaza reviewed
Some final comments here @jwitz - let me know what you think so I can give a final approval and get this thing merged as an MVP

2021-03-10 13:48 UTC, jwitz commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==2.0.0.*'
It's more than the Airflow version through, right? I guess I don't understand the function of the asterisk at the end of the version number.

2021-03-10 13:51 UTC, kaxil commented on ac/next/01_quickstart.md
> +    PIP_EXTRA_INDEX_URL='https://pip.astronomer.io/simple' pip3 install -U 'astronomer-certified==2.0.0.*'
Asterisk basically tells give me the latest version available in 2.0.0 AC series, so this should match 2.0.0-1, 2.0.0-2, 2.0.0-3 etc

2021-03-10 13:52 UTC, jwitz commented
LGTM @paolaperaza, just had one question about the pip install command but otherwise I think this is good to merge!

2021-03-10 15:50 UTC, merged