Secrets backend doc for Astronomer Cloud
astronomer/docs pull request #265
Opened 2022-01-05 12:35 UTC by jwitz

2022-01-05 12:39 UTC, jwitz commented on cloud/secrets-backend.md
> +For example, if you set an SMTP connection, the output of this command would look like the following:
Not sure the output here is necessary. This is basically just confirming that the user correctly typed in the info, and this input isn't used in any other part of the setup.

2022-01-05 12:39 UTC, jwitz commented on cloud/secrets-backend.md
> +```python
Could use tech review here: can we generalize this DAG and use it in other examples as well, instead of just for Vault?

2022-01-05 12:45 UTC, jwitz commented on cloud/secrets-backend.md
> +1. [Create a service account](https://cloud.google.com/iam/docs/creating-managing-service-accounts) with the appropriate permissions on Google Cloud.
Should these be prereqs?

2022-01-06 11:55 UTC, manmeetkaur commented on cloud/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"url":$VAULT__URL,"token": $VAULT__ROOT_TOKEN,"connections_path": "connections","variables_path": "variables","kv_engine_version":1}'
Not sure if it's worth adding, that if we are running the local Vault Server on our machine , the URL should be `http://host.docker.internal:8200`

2022-01-06 13:25 UTC, jwitz commented on cloud/secrets-backend.md
> +ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "vault_url": "<your-vault-url>"}'
@aspain Where do you get the Key Vault URL from?

2022-01-06 13:26 UTC, jwitz commented on cloud/secrets-backend.md
> +ENV AZURE_CLIENT_SECRET="<your-client-secret>" # Found in App Registration Page >> Certificates and Secrets >> Client Secrets >> 'Value'
```suggestion
ENV AZURE_CLIENT_SECRET="<your-client-secret>" # Found on App Page >> Certificates and Secrets >> Client Secrets >> 'Value'
```

2022-01-06 13:34 UTC, aspain commented on cloud/secrets-backend.md
> +ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "vault_url": "<your-vault-url>"}'
@jwitz It's on the main landing page for the Key Vault, in the upper right corner:
![image](https://user-images.githubusercontent.com/15913202/148390716-7f2e8c19-5b91-4cc6-8af8-324c8e534aa9.png)


I added a note about this in the Notion doc right below the Dockerfile as well

2022-01-06 13:34 UTC, jwitz commented on cloud/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"url":$VAULT__URL,"token": $VAULT__ROOT_TOKEN,"connections_path": "connections","variables_path": "variables","kv_engine_version":1}'
I think it's okay to not mention that here. Though we're testing locally, the goal is to test the hosted Vault connection because that's what will be used in production.

2022-01-06 13:39 UTC, jwitz commented on cloud/secrets-backend.md
> +    VAULT__ROOT_TOKEN="<your-root-token>"
If we end up ditching the `.env` file in production, why are we setting it here locally? Could we just have these in the Dockerfile and tell users to remove it when configuring environment variables in their Deployment?

2022-01-06 13:40 UTC, jwitz commented on cloud/secrets-backend.md
> +    ENV AIRFLOW__SECRETS__BACKEND="airflow.contrib.secrets.aws_systems_manager.SystemsManagerParameterStoreBackend"
Similarly, do these need to be set as env vars? Is there a benefit to having them in the Dockerfile instead?

2022-01-06 13:51 UTC, aspain reviewed
@jwitz I found this blurb from the [OSS docs ](https://airflow.apache.org/docs/apache-airflow/1.10.10/howto/use-alternative-secrets-backend.html#search-path)very helpful, not sure if we want to include here. 

> When looking up a connection/variable, by default Airflow will search environment variables first and metastore database second.
> 
> If you enable an alternative secrets backend, it will be searched first, followed by environment variables, then metastore. This search ordering is not configurable.

2022-01-06 14:02 UTC, jwitz commented
@aspain Definitely a good callout, does the order of variables also represent precedence? (ie a value in environment variables will override the value in your secrets backend if they have the same ID).

2022-01-06 14:14 UTC, aspain commented
> @aspain Definitely a good callout, does the order of variables also represent precedence? (ie a value in environment variables will override the value in your secrets backend if they have the same ID).

@jwitz I just ran a quick test using the same variable name in the secrets backend as well as the airflow UI and it looks like the secrets backend will take precedence when the same variable name is present in both.

2022-01-11 05:52 UTC, paolaperaza requested changes
@jwitz Excited to get this out there! I just took a first pass and made some high-level comments. Mostly let's try to get these sections even more consistent with each other.

Will let you do another look and review again.

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You can manage and sync Airflow connections and variables as [secrets](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/secrets/index.html) from a variety of external secrets backen
Might rephrase this to address the value-add of having Airflow Connections and Variables stored in the same place as other organization secrets. The whole thing is that you can manage this in a central place instead of managing 90% of secrets for your team in 1 place, and Airflow stuff in another.

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +When Airflow checks for the value of a connection or environment variable, it first checks your secrets backend (if configured), then your environment variables, and lastly your metadata DB.
```suggestion
If you enable a secrets backend on Astronomer, you can continue to define Airflow connections and variables either as environment variables or in the Airflow UI as needed. If set via the Airflow UI, connections and secrets are stored as encrypted values in Airflow's metadata database.

When Airflow checks for the value of an Airflow Connection or Variable, it will do so in the following order of precedence:

1. Secrets Backend
2. Environment Variable
3. Set via the Airflow UI, stored in Airflow Metadata Database
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +This topic provides steps for how to use Vault as a secrets backend for both local development and on Astronomer Cloud. To do this, you'll:
Link to Hashi

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- Your Vault Server's URL (if you're using a local server, this should be `http://127.0.0.1:8200/`).
I really still am now following our rules with periods at the ends of lists 🙈 Since these aren't full sentences, why the periods?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- [The Astro CLI](install-cli.md).
```suggestion
- [The Astronomer CLI](install-cli.md).
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- A running Hashicorp Vault server.
```suggestion
- A Hashicorp Vault server.
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- A locally hosted [Astronomer project](create-project.md).
```suggestion
- An [Astronomer project](create-project.md).
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- Your Vault Server's URL (if you're using a local server, this should be `http://127.0.0.1:8200/`).
```suggestion
- Your Vault Server's UR. If you're using a local server, this should be `http://127.0.0.1:8200/`.
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You can manage and sync Airflow connections and variables as [secrets](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/secrets/index.html) from a variety of external secrets backen
Might also add 1 sentence on what a connection and variable is in airflow, and link to corresponding airflow docs. We sure we don't wanna capitalize `Connection`?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +## Use Hashicorp Vault as a Secrets Backend
```suggestion
## Use Hashicorp Vault as a Secrets Backend
```

Just `### Hashicorp Vault` to keep the header menu on the right cleaner?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +2. Configure Airflow to use the Vault on your Astronomer project.
```suggestion
2. Configure Airflow to pull the Airflow connection from your Vault instance.
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To start, you first need to write an [Airflow connection URI](https://airflow.apache.org/docs/stable/howto/connection/index.html#generating-connection-uri) to your Vault server. This can be any new o
Might need an additional sentence here to clarify that you need a connection first and then you need to turn it into a Connection URI. If you set a connection in the Airflow UI, you basically enter the values for a bunch of fields. The URI is a 1-line code snippet of those connection fields in a certain syntax.

All this to say, try to rephrase this as more of a "convert your connection credentials to an Airflow Connection URI" step

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To write the connection to your Vault server as a secret key/value pair, run:
Clarify that with Vault CLI

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 2: Set Connection Locally
Is this you setting the Airflow connection locally, or configuring your secrets backend locally?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +This tells Airflow to look for connection and variable information at the `secret/connections/*` `secret/variables/*` paths in your Vault server, respectively. Note that these files are not
Incomplete sentence here

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
Let's check if this is still the case

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
Might re-think this step - placeholder

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To test your connection to Vault in a local Airflow environment, add the following code as a new DAG in your `/dags` directory. This DAG prints your connection information to the task logs, confirmin
```suggestion
To test your connection to Vault in a local Airflow environment, add the following code as a new DAG in your `/dags` directory. This DAG prints your connection information to the task logs, confirming that your connection has been successfully established.
```

Link to Develop Project doc, section on "Add DAGs". Should probably add a comment here at the end of this section that clarifies that this DAG is not NEEDED to run vault - it's just a way to test this thing. Once tested, they can delete this DAG

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you've confirmed that your connections are being imported correctly in a local environment, you're ready to set configure the same feature in a Deployment on Astronomer Cloud.
```suggestion
Once you've confirmed that your connections are being imported correctly in a local environment, you're ready to set configure the same feature in a Deployment on Astronomer Cloud.
```

Weird phrasing?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You now should be able to see your connection information being pulled from Vault on Astronomer. From here, you can store any Airflow connections or variables as secrets on Vault and use them in your
Should we walk the user through this step by step, or just link them to https://docs.astronomer.io/cloud/environment-variables#set-environment-variables-via-the-astronomer-ui

Let's def recommend they set these values as "secret" too. Maybe add a screenshot in here?

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- The [Astro CLI](install-cli.md).
```suggestion
- The [Astronomer CLI](install-cli.md).
```

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 2: Test Parameter Store in a Local Airflow Environment
These H2s are written as "Steps" and named slightly differently - let's make the headers for all secrets backend examples consistent

2022-01-11 05:52 UTC, paolaperaza commented on cloud/secrets-backend.md
> +```python
Yea, good call - this DAG can probably be simplified. Let's get it as consistent as we can with the rest of the examples

2022-01-11 11:56 UTC, jwitz commented on cloud/secrets-backend.md
> +You can manage and sync Airflow connections and variables as [secrets](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/secrets/index.html) from a variety of external secrets backen
Don't see connections or variables capitalized anywhere in OSS or GCC docs, which tracks because it's not a specific type of connection or an individual object

2022-01-11 12:21 UTC, jwitz commented on cloud/secrets-backend.md
> +- Your Vault Server's URL (if you're using a local server, this should be `http://127.0.0.1:8200/`).
They are full sentences because they complete the sentence started by "You'll need"

2022-01-11 12:40 UTC, jwitz commented on cloud/secrets-backend.md
> +:::
[Confirmed](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/_api/airflow/providers/hashicorp/hooks/vault/index.html): `kv_engine_version (int) -- Select the version of the engine to run (1 or 2). Defaults to version defined in connection or 2 if not defined in connection.`

2022-01-11 12:47 UTC, jwitz commented on cloud/secrets-backend.md
> +To test your connection to Vault in a local Airflow environment, add the following code as a new DAG in your `/dags` directory. This DAG prints your connection information to the task logs, confirmin
Don't think we need to link the Add DAGs topic here, because we already explain everything in there in the first sentence.

2022-01-11 12:50 UTC, jwitz commented on cloud/secrets-backend.md
> +Once you've confirmed that your connections are being imported correctly in a local environment, you're ready to set configure the same feature in a Deployment on Astronomer Cloud.
Verbose? Tried to reword it.

2022-01-11 12:53 UTC, jwitz commented on cloud/secrets-backend.md
> +You now should be able to see your connection information being pulled from Vault on Astronomer. From here, you can store any Airflow connections or variables as secrets on Vault and use them in your
If we link out to the env vars docs, I don't think a screenshot is necessary. Which values should also be marked secret? We already recommend specifying the sensitive info here as secret.

2022-01-11 12:59 UTC, jwitz commented on cloud/secrets-backend.md
> +### Step 2: Test Parameter Store in a Local Airflow Environment
I thought it mike make sense to differentiate them in the case that someone's searching for a specific secrets backend in the search bar. WDYT?

2022-01-11 13:18 UTC, jwitz commented on cloud/secrets-backend.md
> +### Step 2: Test Parameter Store in a Local Airflow Environment
Also not sure we can keep total consistency across headers due to the content itself. Secrets Manager, for example, has a configuration step that others don't have

2022-01-11 13:28 UTC, jwitz commented
@paolaperaza Made a lot more changes on here based on your review and the desire to standardize testing across each section. I think offering the same example DAG helped make each setup more legible and consistent.

2022-01-11 14:36 UTC, jwitz commented on cloud/secrets-backend.md
> +## Step 5: Push Changes to Astronomer
```suggestion
### Step 5: Push Changes to Astronomer
```

2022-01-11 14:36 UTC, jwitz commented on cloud/secrets-backend.md
> +## Step 4: Test Key Vault Locally
```suggestion
### Step 4: Test Key Vault Locally
```

2022-01-21 16:30 UTC, paolaperaza reviewed
@jwitz Some additional comments here - I actually only got through the first section, but see if you agree with my comments and then you can apply them to the rest of the examples below. I'll take another look from there!

A tech review will be important here too.

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
```suggestion
:::info

By default, Airflow uses `"kv_engine_version": 2`, but we've written this secret using v1. You can change this to accommodate how you write and read your secrets.

:::
```

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
Do users have to install this hashicorp provider?

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +If you'd like to further customize what the interaction between Airflow and Vault server will look like, read [the full list of available kwargs for this integration](https://airflow.apache.org/docs/
```suggestion
For more information on the Airflow provider for Hashicorp Vault and how to further customize your integration, read [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/_api/airflow/providers/hashicorp/hooks/vault/index.html).
```

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +If you'd like to further customize what the interaction between Airflow and Vault server will look like, read [the full list of available kwargs for this integration](https://airflow.apache.org/docs/
I think this is broken URL

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To test Vault, write a simple DAG which calls your test secret and add this DAG your project's `dags` directory. For example, you can use the following DAG to print the value of a variable to your ta
I think we have to be consistent with what "secret" we're asking the user to test here - is it an Airflow connection or variable? Up top we ask the user to create a connection. 

I'd refrain from using the term "secret" and just specify connection/variable in any tactical steps, but define "secret" up top as any of these - WDYT?

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 2: Set Up Vault in a Local Airflow Environment
```suggestion
### Step 2: Set Vault as your Secret Backend in Airflow
```

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you confirm that the setup was successful, you can delete this example DAG.
```suggestion
1. Run `astro dev stop` followed by `astro dev start` to [restart your local Airflow environment](https://docs.astronomer.io/cloud/develop-project#restart-your-local-environment).
2. In your [local Airflow UI](http://localhost:8080/admin/), trigger your new DAG.
3. Click on `test-task` > **View Logs**. If the configuration was successful, you should should see the contents of your secret in the task logs:

    ```text
    {logging_mixin.py:109} INFO - My variable is: my-test-variable
    ```

Once you confirm that the setup was successful, you can delete this example DAG.
```

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 4: Configure Vault on Astronomer
```suggestion
### Step 4: Set Up Vault on Astronomer Cloud
```

2022-01-21 16:30 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You now should be able to see your connection information being pulled from Vault on Astronomer. From here, you can store any Airflow connections or variables as secrets on Vault and use them in your
```suggestion
Once you've confirmed that the integration with Vault works locally, you can complete a similar set up with a Deployment on Astronomer Cloud.

1. In the Astronomer UI, add the same environment variables found in your `Dockerfile` to the **Environment Variables** section of an existing Deployment. Specify both `VAULT__ROOT_TOKEN` and `VAULT__URL` as **secret** to ensure that your Vault credentials are stored securely.
2. In your Astronomer project, delete the environment variables from your `Dockerfile`.
3. Push your changes to Astronomer Cloud by running `astro deploy` in your project directory.

Now, any Airflow connection or variable that you write to your Hashicorp Vault instance should be successfully pulled.

For more information on setting Environment Variables on Astronomer, read [Environment Variables](https://docs.astronomer.io/cloud/environment-variables). For more information on pushing changes to a Deployment on Astronomer, read [Deploy Code](https://docs.astronomer.io/cloud/deploy-code).
```

2022-01-24 14:13 UTC, jwitz commented on cloud/secrets-backend.md
> +You now should be able to see your connection information being pulled from Vault on Astronomer. From here, you can store any Airflow connections or variables as secrets on Vault and use them in your
Instead of linking out to the docs after the steps, I added the docs inline to the steps.

2022-01-25 18:39 UTC, frankcash commented on cloud/secrets-backend.md
> +- Deploying a light-weight server using [this Heroku Element](https://elements.heroku.com/buttons/pallavkothari/vault)
why do we recommend using heroku instead of a demo / free tier from vault? https://www.hashicorp.com/products/vault

2022-01-25 18:39 UTC, frankcash commented on cloud/secrets-backend.md
> +:::
it is a requirement to have the hashicorp provider `ModuleNotFoundError: No module named 'airflow.providers.hashicorp'`

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
@jwitz Let's add this to Pre-Reqs above

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +3. [Deploy your Astronomer project](https://docs.astronomer.io/cloud/deploy-code).
```suggestion
3. [Deploy your changes](https://docs.astronomer.io/cloud/deploy-code) to Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- A locally hosted [Astronomer project](create-project.md).
```suggestion
- An [Astronomer project](create-project.md).
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To test Vault, write a simple DAG which calls your test secret and add this DAG your project's `dags` directory. For example, you can use the following DAG to print the value of a variable to your ta
Per live convo let's switch order of connection > variable to variable > connection

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
Duplicative with content on this at the top of the doc?

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +This tells Airflow to look for connection information at the `airflow/connections/*` path in your Parameter Store server. In the next step, you'll test this configuration in a local Airflow environme
```suggestion
This tells Airflow to look for variable and connection information at the `secret/connections/*` and `secret/variables/*` paths AWS SSM Parameter Store. In the next step, you'll test this configuration locally.

```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To further customize what the interaction between Airflow and your SSM server looks like, reference the [full list of available kwargs for this integration](https://airflow.apache.org/docs/apache-air
```suggestion
To further customize the integration between Airflow and AWS SSM, reference Airflow documentation with the [full list of available kwargs](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html).
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +:::
```suggestion
:::tip

If you'd like to reference an AWS profile, you can also [add the `profile` param to `ENV AIRFLOW__SECRETS__BACKEND_KWARGS`](https://airflow.apache.org/docs/apache-airflow/2.2.3/security/secrets/secrets-backend/index.html).

:::
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 3: Test Parameter Store in a Local Airflow Environment
```suggestion
### Step 3: Run an Example DAG to Test AWS Paramater Store Locally
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 2: Set Up Parameter Store in a Local Airflow Environment
```suggestion
### Step 2: Set Up AWS Parameter Store to Test Locally
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 4: Deploy to Astronomer
```suggestion
### Step 4: Deploy to Astronomer Cloud
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you've confirmed that your connections are being imported correctly locally, you're ready to set your deploy your project to Astronomer Cloud
```suggestion
Once you've confirmed that the integration with AWS SSM Parameter Store works locally, you can complete a similar set up with a Deployment on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Now, any Airflow connection or variable that you write to your Vault server should be successfully pulled.
```suggestion
Now, any Airflow connection or variable that you write to your Vault server can be successfully accessed and pulled by any DAG in your Deployment on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You should now be able to see your connection information being pulled from AWS SSM Parameter Store on Astronomer.
```suggestion
Now, any Airflow variable or connection that you write to AWS SSM Parameter Store can be automatically pulled by any DAG in your Deployment on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +This topic provides setup steps for configuring Google Cloud [Secret Manager](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) as your Airflow secrets backend.
```suggestion
This topic provides setup steps for configuring [Google Cloud Secret Manager](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) as a secrets backend on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- A Google Cloud environment with [Secret Manager](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) configured.
```suggestion
- A [Deployment](configure-deployment.md).
- The [Astronomer CLI](install-cli.md).
- An [Astronomer project](create-project.md).
- A Google Cloud environment with [Secret Manager](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) configured.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +1. [Create a service account](https://cloud.google.com/iam/docs/creating-managing-service-accounts) with the appropriate permissions on Google Cloud.
Yes, let's make this pre-req and then add a new Step 1 that's about writing a test variable or connection to GCP

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +
This whole step is inconsistent with above sections

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +with DAG('example_secrets_dags', start_date=datetime(2020, 1, 1), schedule_interval=None) as dag:
```suggestion
with DAG('example_secrets_dags', start_date=datetime(2022, 1, 1), schedule_interval=None) as dag:
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you've confirmed that your secrets are being imported correctly to your local environment, you're ready to set configure the same feature in a Deployment on Astronomer Cloud.
```suggestion
Once you've confirmed that the integration with Google Cloud Secret Manager works locally, you can complete a similar set up with a Deployment on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +3. [Deploy your Astronomer project](https://docs.astronomer.io/cloud/deploy-code).
```suggestion
2. In your Astronomer project, delete the environment variables from your `Dockerfile`.
3. [Deploy your changes](https://docs.astronomer.io/cloud/deploy-code) to Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +## Use Azure Key Vault as a Secrets Backend
```suggestion
## Microsoft Azure Key Vault
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +This topic provides setup steps for configuring Azure [Key Vault](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) as your Airflow secrets backend.
```suggestion
This topic provides setup steps for configuring [Azure Key Vault](https://cloud.google.com/secret-manager/docs/configuring-secret-manager) as a secrets backend on Astronomer Cloud.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- An existing Key Vault linked to a resource group ([Guide](https://docs.microsoft.com/en-us/azure/key-vault/general/quick-create-portal)).
```suggestion
- A [Deployment](configure-deployment.md).
- The [Astronomer CLI](install-cli.md).
- An [Astronomer project](create-project.md).
- An existing Key Vault linked to a resource group.

If you do not already have Key Vault configured, read [Microsoft Azure documentation](https://docs.microsoft.com/en-us/azure/key-vault/general/quick-create-portal).
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Follow the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-credentials) to register a new application for Astronomer. At a minimu
```suggestion
Follow the [Microsoft Azure documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-credentials) to register a new application for Astronomer.

At a minimum, you need to add a [secret](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-credentials) that Astronomer can use to authenticate to Key Vault.

Note the value of the application's client ID and secret for Step 3.
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Follow the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-credentials) to create a new access policy for the app that you just r
```suggestion
Follow the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-credentials) to create a new access policy for the application that you just registered. The settings you need to configure for your policy are:
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +In your locally hosted Astronomer project, add the following line to your `requirements.txt` file:
```suggestion
In your Astronomer project, add the following line to your `requirements.txt` file:
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "vault_url": "<your-vault-url>"}' # <your-vault-url> found on Key Vault ov
```suggestion
ENV AZURE_CLIENT_ID="<your-client-id>" # Found on App page > 'Application (Client) ID'
ENV AZURE_TENANT_ID="<your-tenant-id>" # Found on Properties > 'Tenant ID'
ENV AZURE_CLIENT_SECRET="<your-client-secret>" # Found on App Registration Page > Certificates and Secrets > Client Secrets > 'Value'
ENV AIRFLOW__SECRETS__BACKEND="airflow.providers.microsoft.azure.secrets.azure_key_vault.AzureKeyVaultBackend"
ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "vault_url": "<your-vault-url>"}' # <your-vault-url> found on Key Vault overview page > 'Vault URI'
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +These variables connect Airflow to your Key Vault and define how you call secrets in your Airflow code. By default, this setup requires that you prefix any secret names in Key Vault with `airflow-con
```suggestion
This tells Airflow to look for connection information at the `airflow/connections/*` path in Azure Key Vault and variable information at the `airflow/variables/*`. In the next step, you'll run an example DAG to test this configuration locally.

:::tip

By default, this setup requires that you prefix any secret names in Key Vault with `airflow-connections` or `airflow-variables`. If you don't want to use prefixes in your Key Vault secret names, replace the values for `"connections_prefix"` and `"connections_prefix"` with `""`.

:::
```

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you create a test secret, write a simple DAG which calls the secret and add this DAG your project's `dags` directory. For example, you can use the following DAG to print the value of a variable
@jwitz This step here is inconsistent with how we define steps above? Keep it for now, but let's consider changing this later

2022-01-27 17:59 UTC, paolaperaza commented on cloud/secrets-backend.md
> +To test your Key Vault steup, [create a new secret](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal#add-a-secret-to-key-vault) in Key Vault containing either a connection
```suggestion
To test Key Vault on Astronomer locally, [create a new secret](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal#add-a-secret-to-key-vault) in Key Vault containing either an Airflow variable or connection.
```

2022-01-27 18:10 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- Your Vault Server's URL (if you're using a local server, this should be `http://127.0.0.1:8200/`).
addressed!

2022-01-27 18:11 UTC, paolaperaza commented on cloud/secrets-backend.md
> +You now should be able to see your connection information being pulled from Vault on Astronomer. From here, you can store any Airflow connections or variables as secrets on Vault and use them in your
Last iteration of this works

2022-01-27 18:14 UTC, paolaperaza commented on cloud/secrets-backend.md
> +Once you confirm that the setup was successful, you can delete this example DAG.
Fair, this is fine

2022-01-27 19:06 UTC, jwitz commented
@paolaperaza All outstanding changes have been addressed, also added new notes on making sure to format env vars properly on Cloud

2022-01-27 19:09 UTC, frankcash commented
@jwitz I did a ctrl f on `registry` (so correct me if I'm wrong), but I think we're missing a great chance to back link to the registry as well

2022-01-27 19:11 UTC, aspain commented
> @jwitz I did a ctrl f on `registry` (so correct me if I'm wrong), but I think we're missing a great chance to back link to the registry as well or at least have some reference to it

I created a request for azure key vault in particular but not sure where that stands or if it will be updated in the registry: https://astronomer.slack.com/archives/C028TCYNZN1/p1640795933015200

2022-01-27 19:48 UTC, paolaperaza approved these changes
@jwitz I think we are GOOD here! Excellent cut at this. I think we both have some ideas on ho we might make this better, but let's ship it 🚢  Thanks for the hard work.

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +$ vault kv get secret/connections/<your-connection>
```suggestion
# For variables
$ vault kv get secret/variables/<your-variable-key>
# For connections
$ vault kv get secret/connections/<your-connection-id>
```

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +  :::
```suggestion
  :::warning

  Make sure to strip the quotations (`"`) from your environment variable values. If you add these values with the quotation marks included in your Dockerfile, your configuration will not work on Astronomer Cloud.

  :::
```

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 3: Test Vault in a Local Airflow Environment
```suggestion
### Step 3: Run an Example DAG to Test Vault Locally

```

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 1: Write an Airflow Variable or Connection to Parameter Store
```suggestion
### Step 1: Write an Airflow Variable or Connection to AWS Parameter Store
```

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +- A [JSON service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys) for the service account.
Add Gcloud CLI?

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +### Step 3: Test Secret Manager Locally
Run Example DAG...

2022-01-27 19:48 UTC, paolaperaza commented on cloud/secrets-backend.md
> +  :::
```suggestion
  :::warning

  Make sure to strip the quotations (`"`) from your environment variable values. If you add these values with the quotation marks included in your Dockerfile, your configuration will not work on Astronomer Cloud.

  :::
```

I might even have this at the bottom of these steps tbh

2022-01-27 20:32 UTC, merged