Update Deployment creation options
astronomer/docs pull request #2650
Opened 2023-08-04 14:49 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/2606

I don't think we need to "elaborate" on the programmatic options in this doc. Those are complex tools for complex use cases, and this doc is more meant to help explain each item in the Cloud UI configuration screen that a user might want to know more about.

2023-08-06 16:03 UTC, manmeetkaur requested changes
@jwitz I think "create a deployment" should just tell what steps you should focus on "how to  create " very similar to what we are doing with other pages. Currently the screenshot is at the top, which i think obstructs and also too much detail. I have created an issue to discuss specifically this where we create a page/section for Astro components, where the detail could reside. Although there are errors on this page that should be corrected, we should also discuss that issue on Monday.

2023-08-07 09:24 UTC, jwitz commented
@manmeetkaur The screenshot was requested by Paola, so you'll have to discuss that with her. I'm fine with/without it https://github.com/astronomer/docs/issues/2536

As for the content, it all depends whether we want to tell users how to create a Deployment without _any_ information on the configuration screen they see. Is it enough for us to say "Configure your resources. See this other doc"? I think it's helpful to mention some smart defaults and the bare minimum fields to configure in this doc, even if it makes it a little bit longer.

2023-08-10 10:18 UTC, jwitz commented
@manmeetkaur Made the changes per discussion in standup, ready for you to look again!

2023-08-11 07:50 UTC, manmeetkaur reviewed
Hey @jwitz I think what we discussed was three (or two ? by combining both astro cli options in 1) tabs 
- Cloud UI
- Astro CLI
  - `astro login` -> `astro deployment create ...` -> `astro deployment list`
- Deployment as code
  - `astro deployment inspect ...` -> edit the template file -> `astro deployment create --deployment-file ...` 

this way all options are available to the user in 1 place and other pages are just for reference. Do you want me to make these changes? Happy to take it up!

2023-08-11 07:50 UTC, manmeetkaur commented on astro/create-deployment.md
>       A confirmation message appears indicating that the Deployment is in progress. Select the **Deployments** link to go to the **Deployments** page. The Deployment status is **Creating** until all u
The confirmation message appears on the same page and users necessarily don't need to go the Deployments page again. 
```suggestion
     A confirmation message appears indicating that the Deployment is in progress. The Deployment status is **Creating** until all underlying components in your Astro cluster are healthy, including the Airflow webserver and scheduler. During this time, the Airflow UI is unavailable and you can't deploy code or modify Deployment settings. When the Deployment is ready, the status changes to **Healthy**.
     
You can continue to access your other Deployments by selecting the **Deployments** link.
```

2023-08-14 09:52 UTC, jwitz commented
@manmeetkaur I don't agree with including the CLI and as-code steps as tabs in this doc. Those are workflows for different contexts and should be mentioned in different docs. 

Would a user realistically choose between creating a Deployment in the UI and creating one programmatically? If they just want to get a Deployment going ASAP, they will almost always want to use the UI. The only circumstance where that wouldn't be the case is if they don't have access to a web browser. Our docs should make that _the_ manual option if that's what we recommend - making them choose between the CLI and UI could cause more confusion than convenience.

This is the same pattern I thought we were following for all automation docs: include the manual UI steps in one doc and the automation scripts/ examples in another. I don't remember whether we agreed on tabs, I only remember our decision to mention the automation options _somewhere_ in the doc.

2023-08-14 09:53 UTC, jwitz commented on astro/create-deployment.md
> +- [Astro CLI reference guide](cli/astro-deployment-create.md)
```suggestion
- [`astro deployment create`](cli/astro-deployment-create.md)
```

2023-08-14 11:23 UTC, manmeetkaur commented
@jwitz I actually think quite the opposite. It will depend on the user, what pattern to use based on the use-case. Our goal is to clearly make all the info available on a single page with steps without any overview or concept explanation. Users will not have to think, which doc to open if they want to use as code or via plain CLI command, they will know "Create a Deployment" explains all options, let's go there. Why and what of the process can stay where it is currently. 

It also explains to what @paolaperaza mentioned that our CLI is under-documented. I feel it is not under-documented, it not documented in the correct context.

Think about a user A, who wants to use the CLI to create a deployment. Natural progression is to come to create a Deployment, and be given the option of all CLI commands that are required not to push him/her to a reference doc, where they might need to jump couple of more pages to find how to login, how to select workspace etc. goal is new users come in, and see 

```
astro login
astro workspace switch
astro deployment create ...
astro deployment list
```
One-stop shop to help you login. We don't currently dictate that our docs are just cloud ui or don't necessarily have to I think. 

This is worth discussing with @paolaperaza again I believe. Because this was my understanding, so may be we clear this out.

2023-08-14 12:18 UTC, jwitz commented
I don't think this logic extends nicely to the other parts of our documentation. For "Configure Deployment resources", do we want to have tabs for each configuration explaining how to update it via deployments-as-code? What about for user management? It also breaks the pattern that we're currently working towards of keeping complex automation docs in a separate location from the least-friction UI workflows.

2023-08-18 21:48 UTC, lzdanski commented
FWIW - with the API as another path in the future, we're going to have another programmatic way of creating and managing deployments. To me, it makes more sense to keep the UI path separate from the more complex and possibly nuanced options where this doc can works as an introduction/orientation to the UI and briefly describe that there are other options for managing deployments with code. (I don't have a strong opinion about the CLI/automation docs, but thought what we decide for the API might be a pattern we can use here too)

2023-08-25 13:30 UTC, jwitz commented
@manmeetkaur Want to give this a final pass when you have the chance?

2023-08-29 14:47 UTC, manmeetkaur approved these changes
Just minor change for formatting and order change. Do you think we should create a issue to create a page - idk where - which talks about steps of login to Astro CLI -> astro create deployment to avoid linking to the command reference ?

2023-08-29 14:47 UTC, manmeetkaur commented on astro/create-deployment.md
> +- Programmatically, using [`astro deployment create`](cli/astro-deployment-create.md).
```suggestion
- Manually, using the Cloud UI. This is the most basic way to create a Deployment and is the focus of this document.
- Programmatically, using [`astro deployment create`](cli/astro-deployment-create.md).
- Programmatically, using a Deployment template file. See [Manage Deployments as code](manage-deployments-as-code.md#create-a-deployment-from-a-template-file).
```

2023-08-29 14:47 UTC, manmeetkaur commented on astro/create-deployment.md
>      For more information about possible Deployment health statuses, see [Deployment health](deployment-metrics.md#deployment-health).
```suggestion
For more information about possible Deployment health statuses, see [Deployment health](deployment-metrics.md#deployment-health).
```

2023-08-29 14:47 UTC, manmeetkaur commented on astro/create-deployment.md
> +- Programmatically, using [`astro deployment create`](cli/astro-deployment-create.md).
I feel we should put the simple command before the template file and also point to the exact section in the manage a deployment page. Just a thought!

2023-08-30 12:50 UTC, merged