Refactor Test&Troubleshoot + New FAQ
astronomer/docs pull request #2666
Opened 2023-08-08 13:33 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/2648
Resolves https://github.com/astronomer/docs/issues/2659

This PR is a bit contradictory.. On one hand, it makes sense to move all of our local testing/ troubleshooting content to the Astro CLI. On the other had, I created a new FAQ in the Astro docs, some of which is focused on local-only content. 

However, I think it makes more sense to have an FAQ visible to potential trial users and Astro prospects, especially since we can use the page to address any future common problems in the Cloud UI.

2023-08-10 09:48 UTC, manmeetkaur requested changes
@jwitz added some comments. one thing, there is an error in this file.
<img width="1670" alt="Screenshot 2023-08-10 at 3 17 34 PM" src="https://github.com/astronomer/docs/assets/75730393/eb0b476e-913f-46be-9ece-87765e04ecef">

2023-08-10 09:48 UTC, manmeetkaur commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +1. Open the `requirements.txt` and `packages.txt` files for your project and remove the references to the packages that are returning error messages.
Since we are talking about `packages.txt` in the example, so we don't want to mention `requirements.txt`
```suggestion
1. Open the `packages.txt` files for your project and remove the references to the packages that are returning error messages.
```

2023-08-10 09:48 UTC, manmeetkaur commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +5. Open the `requirements.txt` and `packages.txt` files for your project and add the package references you removed in step 1 one by one until you find the package that is the source of the error.
```suggestion
5. Open the `packages.txt` files for your project and add the package references you removed in step 1 one by one until you find the package that is the source of the error.
```

2023-08-10 09:48 UTC, manmeetkaur commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +To see your override file live in your local Airflow environment, run the following command to see the file in your scheduler container:
```suggestion
Run the following command to see the override file in your scheduler container:
```

2023-08-10 09:48 UTC, manmeetkaur commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +2. Add a `docker-compose.override.yml` file to your Astro project.
```suggestion
2. Add a `docker-compose.override.yml` file to your Astro project at the same level as your Dockerfile.
```

2023-08-10 15:54 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
> +
Yep!

2023-08-10 15:55 UTC, jwitz commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +Some issues with a local Astro project can be solved only after running your local Airflow environment with `astro dev start`. For example, one of your DAGs might cause an error in your Airflow sched
```suggestion
Some issues with a local Astro project can be solved only after running your local Airflow environment with `astro dev start`.
```

2023-08-10 15:57 UTC, jwitz commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +For example, if your `packages.txt` file contains the `openjdk-8-jdk`, `gcc`, `g++`, or `libsas12-dev` packages and you receive build errors after running `astro dev start`, you can enter the contain
```suggestion
For example, if your `packages.txt` file contains several packages and you receive build errors after running `astro dev start`, you can enter the container and install the packages manually to review additional information about the errors.
```

2023-08-10 15:58 UTC, jwitz commented on astro/cli/troubleshoot-your-local-airflow-environment.md
> +
I actually think the package names are a bit distracting, so I went for a more generic example.

2023-08-11 09:08 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +### Stop all running Docker containers
####

2023-08-11 09:09 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +### Change the default port assignment
```suggestion
#### Change the default port assignment
```

2023-08-11 09:09 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +### Stop all running Docker containers
```suggestion
#### Stop all running Docker containers
```

2023-08-11 09:33 UTC, jwitz commented
@manmeetkaur I hope this works 😬 🤞  I hedged a bit with "Develop project" by including an external link in the Astro sidebar that links to the CLI doc.

2023-08-14 21:53 UTC, lzdanski reviewed
Also reviewed changes in preview as well

2023-08-21 14:54 UTC, manmeetkaur approved these changes
LGTM!

2023-09-14 13:12 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +Running your Astro project locally is an easy way to test your code changes. Additionally, you can only troubleshoot some issues in a project after running your local Airflow environment with `astro
```suggestion
Running Airflow locally with the Astro CLI can be an easy way to test DAG changes quickly before deploying your code to a Deployment on Astro. Testing a DAG locally first requires that you start a local Airflow environment on your computer by running the `astro dev start` command in your terminal.
```

I'm not super sure what the purpose of this 2nd sentence is? Is it supposed to be a prerequisite?

2023-09-14 13:15 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +This command builds your project and spins up 4 containers on your machine, each for a different Airflow component. After the command completes, you can access your project's Airflow UI at `https://l
```suggestion
This command builds your project and spins up 4 containers on your machine, each for a different Airflow component. After the command completes, you can access a local version of the Airflow UI at `https://localhost:8080/`. Any DAGs in the `dags` folder of your Astro project will appear.
```

2023-09-14 13:16 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +To restart your local Airflow environment, run:
Would add 1 sentence about why you'd want to restart your environment

2023-09-14 13:16 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +Run the following to pause all Docker containers running your local Airflow environment.
Same here. "Why" do users stop their Airflow environment?

2023-09-14 13:17 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +Unlike `astro dev kill`, this command does not prune mounted volumes and delete data associated with your local Postgres database. If you run this command, Airflow connections and task history will b
Might have this mentioned before the command is listed, and when we explain why a user would use this

2023-09-14 13:17 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +This command can be used regularly with `astro dev start` and `astro dev restart` during local development.
I see this sentence, but just not enough guidance

2023-09-14 13:18 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +You can use the Astro CLI to view logs for your local Airflow environment's webserver, scheduler, and triggerer. This is useful if you want to troubleshoot a specific task instance, or if your enviro
```suggestion
You can use the Astro CLI to view logs for your local Airflow environment's webserver, scheduler, and triggerer. This is useful if you want to troubleshoot a specific task instance, or if your local environment does not run properly after a code change. For example, if the Airflow UI is not available or no scheduled tasks are running.
```

2023-09-14 13:19 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +astro dev logs
Should we add another example command to see logs for a specific component? Seems a more likely use case, and I think it's ok to take a bit more real-estate

2023-09-14 13:19 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
>  ## Run Airflow CLI commands
Again -- what are the top 2-3 reasons people run Airflow CLI commands locally? Let's list them. @manmeetkaur's 2 cents might be helpful here

2023-09-14 13:21 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +Unlike `astro dev kill`, this command does not prune mounted volumes and delete data associated with your local Postgres database. If you run this command, Airflow connections and task history will b
Also, let's link out the `astro dev kill` command to the section in this doc about it? Or make sure the language ("hard reset...") matches

2023-09-14 13:22 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +## Override the Astro CLI Docker Compose file
Check formatting here?

2023-09-14 13:22 UTC, paolaperaza commented on astro/cli/run-airflow-locally.md
> +## Common issues
Let's add a sentence here introducing this section? We can link out to support or our forum too

2023-09-14 13:24 UTC, paolaperaza commented on astro/cli/test-your-astro-project-locally.md
>  ## Test before upgrading your Astro project
Should this title be more direct? `Test an Airflow version upgrade`

2023-09-14 13:25 UTC, paolaperaza commented on astro/cli/test-your-astro-project-locally.md
>  One of the Astro CLI's main features is the ability to run Astro projects in a local Airflow environment. It additionally includes commands that you can use to test and debug DAGs both inside and out
I would expand this intro more with a bullet list of the kinds of tests the CLI supports / thus what is covered in this doc. I think we're underselling what the Astro CLI can do

2023-09-14 13:25 UTC, paolaperaza commented on astro/cli/test-your-astro-project-locally.md
> +description: Check your Astro project for errors before you run it locally or deploy to Astro.
```suggestion
description: Check your Apache Airflow DAGs for errors before you run it locally or deploy to Astro.
```

Let's try to have the word Airflow in as many of these as possible

2023-09-14 14:52 UTC, paolaperaza commented on sidebarsAstro.js
> +      label: "Advanced configuration",
```suggestion
      label: "Advanced",
```

Let's just do `advanced` here, no need for the configuration part I don't think

2023-09-14 15:56 UTC, lzdanski commented on astro/cli/test-your-astro-project-locally.md
>  One of the Astro CLI's main features is the ability to run Astro projects in a local Airflow environment. It additionally includes commands that you can use to test and debug DAGs both inside and out
@paola - would you be okay with us addressing this change as part of the follow-up work to separate it into Test DAGs + Test projects?

2023-09-14 15:57 UTC, lzdanski commented on astro/cli/test-your-astro-project-locally.md
> +sidebar_label: 'Test your project'
There will be some follow-up work on this page after this PR merges to address the scope of the doc and separate into two pages that address testing DAGs specifically vs testing the entire project since there are different scenarios that we can then expand on (re upgrade runtime) after we make the distinction more clear. 

See https://github.com/astronomer/docs/issues/2847

2023-09-14 16:29 UTC, lzdanski commented on astro/cli/run-airflow-locally.md
> +This document explains how to use Astro CLI commands to interact with a locally running Airflow environment.
This might also be a place to link to Develop a Project, but I'm having a terrible time coming up with a one sentence summary of what that page contains, even with this refactoring.

```suggestion
This document explains how to use the Astro CLI to start a local Airflow environment on your computer and interact with your Astro project. To learn more about unit testing for your DAGs or testing project dependencies when changing Python or Astro Runtime versions, see [Test your project locally](test-your-astro-project-locally.md).
```

2023-09-14 16:29 UTC, lzdanski commented on astro/cli/run-airflow-locally.md
> +Running your Astro project locally is an easy way to test your code changes. Additionally, you can only troubleshoot some issues in a project after running your local Airflow environment with `astro
hopping in with some suggestions based on our standup conversation.
```suggestion
Running Airflow locally with the Astro CLI can be an easy way to preview and debug DAG changes quickly before deploying your code to a Deployment on Astro. By locally running your DAGs, you can iteratively develop and improve your DAGs in an Airflow without consuming infrastructure resources or waiting on code deploy processes.
```

2023-09-15 12:53 UTC, jwitz commented on astro/cli/develop-project.md
> +If you're running your Astro project in a local Airflow environment, you must restart your environment to apply changes for any of the following files in your Astro project:
I updated your comment to be more technically accurate, and now I just see us repeating the same sentence twice. Not sure what the user assumption is here that we're making, but don't feel strongly enough to fully push back

2023-09-15 12:59 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +This command builds your project and spins up 4 containers on your machine, each for a different Airflow component. After the command completes, you can access your project's Airflow UI at `https://l
The last sentence is true, but what value does it add? Who is looking for that information, or would assume otherwise?

2023-09-15 13:01 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +To restart your local Airflow environment, run:
```suggestion
Restarting your Airflow environment rebuilds your image and restarts the Docker containers running on your local machine with the new image. Restart your environment to apply changes from specific files in your project, or to troubleshoot issues that occur when your project is running. 

To restart your local Airflow environment, run:
```

2023-09-15 14:04 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +Run the following to pause all Docker containers running your local Airflow environment.
```suggestion
Run the following command to pause all Docker containers running your local Airflow environment. 
```

2023-09-15 14:06 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +Unlike `astro dev kill`, this command does not prune mounted volumes and delete data associated with your local Postgres database. If you run this command, Airflow connections and task history will b
```suggestion
Unlike [`astro dev kill`](#hard-reset-your-airflow-environment), this command does not prune mounted volumes and delete data associated with your local Postgres database. If you run this command, Airflow connections and task history will be preserved.
```

2023-09-15 14:07 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +Unlike `astro dev kill`, this command does not prune mounted volumes and delete data associated with your local Postgres database. If you run this command, Airflow connections and task history will b
You use it to stop your environment. With the arrival of `astro dev restart`, it doesn't really have a purpose for local development besides that.. you want to stop.

2023-09-15 14:08 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +This command can be used regularly with `astro dev start` and `astro dev restart` during local development.
```suggestion
```

2023-09-15 14:14 UTC, jwitz commented on astro/cli/run-airflow-locally.md
>  ## Run Airflow CLI commands
I think the example after the command is sufficient! To be honest I don't love the idea of adding "why" to every single topic in this guide. Listing examples of commands people might use might frustrate someone who just needs to know how to run the specific Airflow command they currently need, which is how I assume most people are interacting with a doc like this.

2023-09-15 14:14 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +## Override the Astro CLI Docker Compose file
It's just GitHub failing to parse

2023-09-15 14:17 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
>  ## Test before upgrading your Astro project
```suggestion
## Test before an Astro Runtime upgrade
```

2023-09-15 14:17 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
>  ## Test before upgrading your Astro project
Sure but I think we need to put Runtime here, it's the only term we refer to in the topic

2023-09-15 14:18 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
>  One of the Astro CLI's main features is the ability to run Astro projects in a local Airflow environment. It additionally includes commands that you can use to test and debug DAGs both inside and out
```suggestion
One of the Astro CLI's main features is the ability to run Astro projects in a local Airflow environment. It additionally includes commands that you can use to test and debug DAGs both inside and outside of a locally running Airflow environment.

Use the following document to learn more about how you can test locally with the Astro CLI before deploying your code changes to a production environment.
```

2023-09-15 14:20 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +This document explains how to use Astro CLI commands to interact with a locally running Airflow environment.
```suggestion
```

2023-09-15 14:23 UTC, jwitz commented on astro/cli/run-airflow-locally.md
```suggestion
Use the following topics to resolve common issues with running an Astro project in a local environment.
```

2023-09-15 14:30 UTC, jwitz commented on astro/cli/get-started-cli.md
> +One of the Astro CLI's main features is its ability to run Airflow on your local machine. After you install the Astro CLI and Docker Desktop, follow this quickstart to build an Airflow project and ru
```suggestion
One of the Astro CLI's main features is its ability to run Airflow on your local machine. After you install the Astro CLI and Docker Desktop, follow this quickstart to build an Airflow project and run it in a local Airflow environment using just a few commands. At the end of the tutorial, you'll have all of the files and components you need to develop Airflow locally.
```

2023-09-15 14:32 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
> +sidebar_label: 'Test your project'
```suggestion
sidebar_label: 'Test your DAGs'
```

2023-09-15 15:07 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
> +The command `astro dev parse` is a more convenient but less customizable version of `astro dev pytest`. If you don't have any specific test files that you want to run on your DAGs, Astronomer recomme
```suggestion
`astro dev parse` is a more convenient but less customizable version of `astro dev pytest`. If you don't have any specific test files that you want to run on your DAGs, Astronomer recommends using `astro dev parse` as your primary testing tool. For more information about this command, see the [CLI command reference](cli/astro-dev-parse.md).
```

2023-09-15 15:08 UTC, jwitz commented on astro/cli/test-your-astro-project-locally.md
> +To run a DAG located within your local `/dags` directory run:
```suggestion
To run a DAG located within your local `/dags` directory, run:
```

2023-09-18 15:27 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +Use the following topics to resolve common issues with running an Astro project in a local environment.
```suggestion

Use the following topics to resolve common issues with running an Astro project in a local environment.

```

2023-09-18 16:03 UTC, jwitz commented on sidebarsAstro.js
> +      label: "Run your project locally",
```suggestion
      label: "Run Airflow locally",
```

2023-09-18 16:03 UTC, jwitz commented on astro/cli/run-airflow-locally.md
> +sidebar_label: 'Run your project locally'
```suggestion
sidebar_label: 'Run Airflow locally'
```

2023-09-19 19:36 UTC, merged