Add new way to create connection for AWS services
astronomer/docs pull request #2672
Opened 2023-08-09 08:14 UTC by manmeetkaur

Resolves #2655

2023-08-16 14:52 UTC, fritz-astronomer commented on astro/connect-aws.md
> +8. In the Airflow UI, create an Airflow connection to access the resources you need to connect to. See the example on how to use Role ARN to [create an Airflow connection](https://docs.astronomer.io/
```suggestion
8. In the Airflow UI, create an Airflow connection to access the resources you need to connect to. See the example on how to use Role ARN to [create an Airflow connection for a Redshift Database](https://docs.astronomer.io/learn/connections/redshift#get-connection-details).
```

2023-08-16 14:56 UTC, fritz-astronomer commented
it's super confusing that there's
https://deploy-preview-2672--gallant-neumann-56599d.netlify.app/learn/airflow-redshift
and
https://deploy-preview-2672--gallant-neumann-56599d.netlify.app/learn/connections/redshift

2023-08-16 14:57 UTC, fritz-astronomer commented on learn/connections/redshift.md
> +    apache-airflow-providers-microsoft-amazon
that's not right :)

2023-08-16 14:59 UTC, fritz-astronomer commented
also this page mentions `apache-airflow-providers-microsoft-amazon` in a few places, can you rectify all those?

Would be good to make sure to get someone with fresh eyes runs through these instructions.

2023-08-16 14:59 UTC, fritz-astronomer commented
Also also - `DB credendtials` is misspelled

2023-08-21 09:27 UTC, manmeetkaur commented
> * make sure to use a spell checker - this comment was for already written copy not this PR
> * make sure to correct the provider import in all locations
> * in general, it's very confusing to have `Integrations -> Redshift` and `Examples -> Airflow Connections -> Redshift`. I don't think I, as a customer, would ever have found this connection doc as it's buried, but also it's easier to find the integration page (which feels more like an example, anyway?)
> * gave some minor copy suggestions

@fritz-astronomer fixed the issues that you pointed out! Thanks for this. As for connections being burried, I agree but not my call to make. I was thinking what if we move the **connections** menu under **integrations**?

2023-08-21 09:28 UTC, manmeetkaur commented on astro/connect-aws.md
> +To grant an Astro Deployment access to a service that is running in an AWS account not managed by Astronomer, use AWS IAM roles. IAM roles on AWS are often used to manage the level of access a specif
this was incorrect and a better version of this doc is being handled in [this PR](https://github.com/astronomer/docs/pull/2678/files). so will take this out from here.

2023-08-22 13:59 UTC, jwitz approved these changes

2023-08-22 13:59 UTC, jwitz commented on astro/connect-aws.md
> +    - **Stack name**: Enter a meaningful name for your stack.
```suggestion
    - **Stack name**: Enter a name for your stack.
```

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +You can use IAM credentials to connect Airflow to Redshift. This approach gives you the option to use IAM credentials and also limit Airflow's permissions. The drawback is the credentials file needs
```suggestion
You can use IAM credentials to connect Airflow to Redshift. This approach lets you use IAM credentials and limits Airflow's permissions. The limitation of this method is that you must mount a credentials file to your Docker containers. 
```

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +You can use AWS's [Assume Role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) method to automatically generate temporary credentials to connect to Redshift. This is useful
```suggestion
You can use AWS's [Assume Role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) method to automatically generate temporary credentials to connect to Redshift. This is useful to grant temporary access to limited-privilege IAM users or roles without storing any credentials on disk. The following information is required to create the connection:
```

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +4. Open your IAM dashboard, and [follow the AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions_create-policies.html) to create an IAM role and attach an
```suggestion
4. Open your IAM dashboard, and follow the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions_create-policies.html) to create an IAM role and attach an IAM policy to access AWS Redshift. 
```
It's a Redshift guide so I assume this is the only resource we need to mention?

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +5. Edit the trust relationship of the role created in step 4 to add a trust policy. For example, the following trust policy allows the IAM role to assume your new role.
```suggestion
5. Edit the trust relationship of the role created in Step 4 to add a trust policy that allows the IAM role to assume your new role.
```
Is it "For example", or do we want users to specifically add a policy for assuming the new role?

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +5. Fill out the following connection fields using the information you retrieved from [Get connection details](#get-connection-details):
```suggestion
5. Complete the following connection fields using the information you retrieved from [Get connection details](#get-connection-details):
```

2023-08-22 13:59 UTC, jwitz commented on learn/connections/redshift.md
> +    - **Connection Id**: Enter a name for the connection.
```suggestion
```

2023-08-22 14:16 UTC, manmeetkaur commented on learn/connections/redshift.md
> +5. Edit the trust relationship of the role created in step 4 to add a trust policy. For example, the following trust policy allows the IAM role to assume your new role.
We need to add a policy to assume role. I added For example, because the ARN could be different.

2023-08-22 14:22 UTC, manmeetkaur commented on learn/connections/redshift.md
> +    - **Connection Id**: Enter a name for the connection.
why did you remove this ? 🤔 I assume by mistake, coz we have this in all the other options

2023-08-22 14:29 UTC, jwitz commented on learn/connections/redshift.md
> +5. Edit the trust relationship of the role created in step 4 to add a trust policy. For example, the following trust policy allows the IAM role to assume your new role.
We would use "for example" if we gave a specific example ARN number. Because this code block uses placeholder values, it's not really an example.

2023-08-22 14:37 UTC, fritz-astronomer commented on learn/connections/redshift.md
> +You can use IAM credentials to connect Airflow to Redshift. This approach lets you use IAM credentials and limits Airflow's permissions. The limitation of this method is that you must mount a credent
```suggestion
You can use IAM credentials to connect Airflow to Redshift. This approach lets you use IAM credentials and limits Airflow's permissions. The limitation of this method is that you must include an AWS credentials file in your Airflow project.
```

2023-08-22 14:40 UTC, fritz-astronomer requested changes
Can we modify this to be per-deployment role IAM instead of some other role-based IAM? 
I apologize for not thinking of it earlier. It's _definitely_ safer to not even include a `credentials` file and just trust the whole Airflow
https://docs.astronomer.io/astro/authorize-deployments-to-your-cloud#aws

The instructions are pretty similar - you can probably just link to ^ this and remove the part about creating a `credentials` file with secret key and ID

2023-08-22 17:27 UTC, manmeetkaur commented on learn/connections/redshift.md
> +    - **Connection Id**: Enter a name for the connection.
oh! got it. Thanks will remove that step for consistency

2023-08-22 17:42 UTC, fritz-astronomer commented
> We do want to keep all ways to create an Airflow connection for the OSS Airflow users and drive traffic to Astro resources.
Ah, I do forget that part sometimes. 
Maybe, at least, link to that Deployment IAM? Otherwise there isn't any obvious place saying "You can connect to redshift easily in astro without any baked-in credentials"
You have my 👍 with that 😁

2023-08-22 18:45 UTC, manmeetkaur commented
merging this as @fritz-astronomer  has given a 👍  as well.

2023-08-22 18:46 UTC, merged