[2.7] UI guide update
astronomer/docs pull request #2681
Opened 2023-08-11 00:52 UTC by TJaniF

2023-08-11 15:27 UTC, kentdanas requested changes
Looks good! Requesting changes since I'm asking to remove and move a few sections, but should be pretty straight forward.

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +The **Grid** view is the main DAG view and gives you detailed insights into a specific DAG, its DAG runs and tasks. When running the DAG, toggle **Auto-refresh** to see the status of the tasks update
```suggestion
The **Grid** view is the main DAG view and gives you detailed insights into a specific DAG, including its DAG runs and task instances. When running the DAG, toggle **Auto-refresh** to see the status of the tasks update in real time.
```

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +### Gantt
I think we can remove this subsection. The Gantt view is pretty self-explanatory, I never hear questions about it, and there aren't really actions you can take from it.

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +The cluster activity tab was added in Airflow 2.7 and shows metrics aggregated about the entire Airflow cluster. There are live metrics available such as currently occupied slots in different [pools]
```suggestion
The cluster activity tab was added in Airflow 2.7 and shows aggregated metrics for the entire Airflow cluster. There are live metrics available such as currently occupied slots in different [pools](airflow-pools.md), unpaused DAGs and scheduler health.
```

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +The historical metrics shown include states of past DAG runs, task instances and through which trigger DAGs were run.
```suggestion
The historical metrics shown include states of past DAG runs, task instances and how DAGs runs were triggered.
```

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +## Legacy: Graph view
I think we can just add a note about this in the Graph section above, and remove this section. Even though lots of people won't be on 2.7 right away, this is pretty self explanatory.

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +### Actions
Let's move this up below the Details subsection, since it's about Task Instances, I think it directly follows from that.

2023-08-11 15:27 UTC, kentdanas commented on learn/airflow-ui.md
> +Under the **Code** tab you can access the code generating the DAG you are viewing. While your code should live in source control, the **Code** tab provides a quick insight into what is going on in th
```suggestion
Under the **Code** tab you can access the code that generates the DAG you are viewing. While your code should live in source control, the **Code** tab provides a quick insight into what is going on in the DAG. DAG code can't be edited in the UI.
```

2023-08-11 19:24 UTC, kentdanas approved these changes

2023-08-14 13:49 UTC, jwitz requested changes
LGTM! Got a few more organization suggestions. @kentdanas Assigning you since Tamara is on vacation.

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +### Actions
Not a fan of this appearing alongside the other headers for tab names, because my first thought was "There's an Actions tab in the Airflow UI"? I'd prefer that we bring this information up to the base "Grid view" topic because you can access those buttons from any page.

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +When a DAG run, task instance or [task group](task-groups.md) instance is selected in the **Grid** view several action buttons appear.
```suggestion
When a DAG run, task instance, or [task group](task-groups.md) instance is selected in the **Grid** view, several action buttons appear:
```

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +- **Clear Task Filter**: This button allows you to filter the tasks shown in the **Grid** view based on task dependencies. For example, by selecting **Filter downstream** only the tasks downstream of
```suggestion
- **Clear** / **Clear task** : This button will clear the selected DAG run, task group instance, or task instance and run it again. This is useful if you want to re-run a task or DAG run that has failed or during local development. After clicking **Clear task** you will be offered a detailed interface controlling which task instances should be cleared and rerun. See [Manually rerun tasks or DAGs](rerunning-dags.md#manually-rerun-tasks-or-dags).
- **Mark state as...**: This button allows you to mark the selected DAG run, task group instanc,e or task instance as successful or failed without running it. This option is often useful when the root cause of a task failure was fixed manually in the external data tool and there's no need to rerun the task. Many data teams leverage [Task Instance Notes and DAG Run Notes](rerunning-dags#add-notes-to-cleared-tasks-and-dags) in order to document the reason for marking a task instance as failed or successful.
- **Clear Task Filter**: This button allows you to filter the tasks shown in the **Grid** view based on task dependencies. For example, when you select **Filter downstream**, the UI shows only the tasks downstream of your selected task. 
```

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +### Keyboard shortcuts
Might be worth making this a `:::tip`?

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +![Calendar View](/img/guides/2_4_CalendarView.png)
```suggestion
    ![Calendar View](/img/guides/2_4_CalendarView.png)
```

2023-08-14 13:49 UTC, jwitz commented on learn/airflow-ui.md
> +## Additional DAG views
Shouldn't this be the last section?

2023-08-14 15:34 UTC, kentdanas commented on learn/airflow-ui.md
> +## Additional DAG views
It's where it is because it is describing other views that apply to individual DAGs, similar to the grid view, graph view, etc. Whereas everything that follows applies to the entire Airflow instance (cluster activity, datasets, etc.). So the flow is dag-specific views -> airflow instance views. Eventually, these other DAG views will also be tabs in the grid view and we can make this a subsection.

2023-08-14 15:36 UTC, kentdanas commented
@jwitz thanks for the review. I think I addressed all your comments - let me know if you have further thoughts on the Additional DAG views section, happy to move that if you still think we need to.

2023-08-16 10:26 UTC, jwitz commented on learn/airflow-ui.md
>  A notable feature of Apache Airflow is the [user interface (UI)](https://airflow.apache.org/docs/apache-airflow/stable/ui.html), which provides insights into your DAGs and DAG runs. The UI is a usefu
```suggestion
One of the main features of Airflow is its [user interface (UI)](https://airflow.apache.org/docs/apache-airflow/stable/ui.html), which provides insights into your DAGs and DAG runs. The UI is essential for understanding, monitoring, and troubleshooting your pipelines.
```

2023-08-16 10:27 UTC, jwitz commented on learn/airflow-ui.md
> +In Airflow 2.7 keyboard shortcuts where added to the **Grid** view. You can see all available shortcuts by pressing `shift` + `/` while in the **Grid** view.
```suggestion
In Airflow 2.7 and later, the **Grid** view includes keyboard shortcuts. You can see all available shortcuts by pressing `shift` + `/` while in the **Grid** view.
```

2023-08-16 10:28 UTC, jwitz commented on learn/airflow-ui.md
```suggestion

:::

```

2023-08-16 10:28 UTC, jwitz commented on learn/airflow-ui.md
> +## Additional DAG views
```suggestion
:::info Additional DAG views
```

2023-08-16 10:28 UTC, jwitz commented on learn/airflow-ui.md
```suggestion
```

2023-08-16 10:28 UTC, jwitz commented on learn/airflow-ui.md
```suggestion
```

2023-08-16 10:28 UTC, jwitz commented on learn/airflow-ui.md
I know its a new feature, but it feels a bit out of place to have a screenshot just for this tab and not others.

2023-08-16 10:29 UTC, jwitz commented on learn/airflow-ui.md
```suggestion
```

2023-08-16 10:29 UTC, jwitz commented on learn/airflow-ui.md
> +## Additional DAG views
Feel free to override, but it felt weird to me to have a section called "Additional DAG views" and then say "We're not discussing these DAG views". It might be better as a note

2023-08-18 16:18 UTC, merged