Update configure-deployment-resources.md
astronomer/docs pull request #2695
Opened 2023-08-16 01:54 UTC by RNHTTR

Warn users about requesting resources for a task that are equal to the deployment's quota

2023-08-16 14:03 UTC, jwitz requested changes
@RNHTTR I think I'm having trouble understanding the current warning. I tried adding a different warning based on what my understanding of the issue is, can you confirm if that's correct? 

In its current state, I don't know why we'd need to communicate the warning about one task running at a time. That seems like expected behavior if you have a proper understanding of CPU and memory quotas.

2023-08-16 14:03 UTC, jwitz commented on astro/configure-deployment-resources.md
```suggestion
:::caution

The largest possible **Max Pod Size** has fewer resources than the largest possible CPU and memory quotas. If your CPU and memory quotas exceed your **Max Pod Size**, the **Max Pod Size** becomes the maximum amount of resources you can request in a single task. 

For example, if you have a CPU quota of 150 and a memory quota of 200, your **Max Pod Size** will be 12 vCPU and 24GiB RAM. If you try to run a task that requests 20vCPU, the task won't run even though it's within your quotas.

:::

```

2023-08-16 17:35 UTC, RNHTTR commented on astro/configure-deployment-resources.md
> +:::
> we can inclide it out of a note.

Do you mean like an info block? I think that'd be fine. I just think it ought to be highlighted.

2023-08-16 19:23 UTC, RNHTTR commented on astro/configure-deployment-resources.md
cpu to memory is always 1:2, so this example would have to be "150 vCPU and a memory quota of 300GiB". My concern here is the difference in max pod size between Standard/Dedicated (and your point about "what if these maximums change?")

2023-08-17 09:25 UTC, jwitz commented on astro/configure-deployment-resources.md
> +    - **Default Pod Size (Memory)**: The amount of memory that your tasks run with if no memory usage is specified in their Pod configuration.
The field says "CPU Quota" instead of "Quota (CPU)". Bold styling in our docs mean "You could ctrl+f

Would an ellipses work better? Updated my suggestion, let me know what you think

2023-08-17 09:27 UTC, jwitz commented on astro/configure-deployment-resources.md
Updated my suggestion to afford the possibility that the values could change in the future. I think it's okay to use these values as examples even though the exact ratios might change over time. The main point is "Quotas can be greater than max pod size"

2023-08-17 09:37 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The CPU and memory quotas determine the **Max Pod Size**, which is the maximum amount of resources that a task can request for its pod.
```suggestion
Your CPU and memory quotas determine how many tasks you can run at once on your Deployment. For example, if a task requests the full amount of your CPU and memory quotas, then your Deployment can run only that task until it completes.

The CPU and memory quotas also determine the **Max Pod Size**, which is the maximum amount of resources that a task can request for its pod.
```

2023-08-17 09:45 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The CPU and memory quotas also determine the **Max Pod Size**, which is the maximum amount of resources that a task can request.
```suggestion
The CPU and memory quotas also determine the **Max Pod Size**, which is the maximum amount of resources that a task can request.

```

2023-08-17 09:46 UTC, jwitz reviewed
I tried addressing the issue your customer faced in the description after the bulleted list @RNHTTR, as well as including a caution about exceeding max pod size when your quotas are larger. LMK what you think

2023-08-17 16:39 UTC, lzdanski reviewed
That value configuration step is really tricky. I don't see a very clear "right" answer, but we might have some other tradeoff options.

2023-08-17 19:02 UTC, RNHTTR commented on astro/configure-deployment-resources.md
> +    - **Default Pod Size (Memory)**: The amount of memory that your tasks run with if no memory usage is specified in their Pod configuration.
Nested bullets would be fine. I think a colon would be better than an ellipses or `>` character

2023-08-18 12:45 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The largest possible CPU and memory quotas can exceed the largest possible **Max Pod Size**. Because tasks can only run in a single Pod, your tasks can't request resources that exceed the **Max Pod S
```suggestion
The largest possible CPU and memory quotas can exceed the largest possible **Max Pod Size**. Because tasks run in a single Pod, your tasks can't request resources that exceed the **Max Pod Size**, even if your quota is larger.
```

2023-08-18 13:59 UTC, jwitz commented
@RNHTTR good to merge?

2023-08-19 21:35 UTC, RNHTTR commented
> @RNHTTR good to merge?

> For example, if your Deployment has a CPU quota of 150vCPU and a memory quota of 300GiB, your **Max Pod Size** might only be 12 vCPU and 24GiB RAM. If you try to run a task that requests 20vCPU, the task won't run even though it's within your quotas.

This is true only in Dedicated, because the max pod size is larger (I think 27vCPU and 54 Mem).

> The largest possible CPU and memory quotas can exceed the largest possible **Max Pod Size**

I don't think this needs to be a warning. The warning I want to convey is "if your max pod size is equal to your quota, and you request a task with resources equal to max pod size/quota, then that is the only task that will run until it completes".

It's not a bug, but it is a non-obvious footgun.

2023-08-21 09:51 UTC, jwitz commented on astro/configure-deployment-resources.md
> +The largest possible CPU and memory quotas can exceed the largest possible **Max Pod Size**. Because tasks run in a single Pod, your tasks can't request resources that exceed the **Max Pod Size**, ev
```suggestion
For Deployments running on dedicated clusters, the largest possible CPU and memory quotas can exceed the largest possible **Max Pod Size**. Because tasks run in a single Pod, your tasks can't request resources that exceed the **Max Pod Size**, even if your quota is larger.
```

2023-08-21 09:52 UTC, jwitz commented
@RNHTTR Got it, think I covered the 1 task warning with:

> Your CPU and memory quotas determine how many tasks can run at once on your Deployment. For example, if your Deployment has a CPU quota of 3vCPU and a memory quota of 6GiB, and a task requests this amount, then your Deployment can run only that task until it completes.

Also added a caveat that the warning is only for dedicated clusters.

2023-08-23 14:45 UTC, lzdanski approved these changes
@jwitz - edits look good in preview but @RNHTTR might need to give final approval on your content changes. Looks like y'all had a discussion but I couldn't tell if you had come to a consensus about the wording.

2023-08-24 12:27 UTC, jwitz approved these changes
Going to approve and merge because it looks like all remaining comments have been addressed! Thanks for bearing with us @RNHTTR

2023-08-24 12:27 UTC, merged

2023-08-24 12:42 UTC, RNHTTR commented
sorry for the slow communication. looks good!