Update develop-project.md
astronomer/docs pull request #2709
Opened 2023-08-17 14:12 UTC by afastronomer

correction for CA cert adding part

2023-08-17 14:13 UTC, afastronomer commented
#2708

2023-08-17 17:27 UTC, lzdanski reviewed
@afastronomer - This is really helpful detail! There's one structural thing that I think might need a change. 

Right now, there's a couple steps in this flow that require users to bounce between processes or reach out to another team, which can sometimes be discouraging. What do you think about adding those things as pre-reqs or including a short Dockerfile code example? (The comments do a better job of showing what I've got in mind.)

2023-08-17 17:27 UTC, lzdanski commented on astro/develop-project.md
> +4. Add the following entry below `FROM stage1 AS stage2` line in our example or any other location before installing Python packages:
```suggestion
4. Add the following entry to the file before installing Python packages, such as after the `FROM stage1 AS stage2` line:
```

2023-08-17 17:27 UTC, lzdanski commented on astro/develop-project.md
> +   Make sure you use Runtime **base** image i.e. quay.io/astronomer/astro-runtime:8.8.0-base but not regular one quay.io/astronomer/astro-runtime:8.8.0 .
```suggestion
   Make sure you use Runtime **base** image in your Dockerfile.  The base image tag is formatted as `quay.io/astronomer/astro-runtime:8.8.0-base`, and not the regular image at `quay.io/astronomer/astro-runtime:8.8.0`.
```
Will this need to be updated to runtime 9.0 when it gets released?

2023-08-17 17:27 UTC, lzdanski commented on astro/develop-project.md
> +3. Use Dockerfile similar to [Install packages from Private repository](/astro/develop-project#install-python-packages-from-private-sources).
I think this step might need to be either removed if we make the Dockerfile a pre-req _or_ we can add a code example to this step. Again, just want to prevent users from having to hop between two different procedures once they get into the middle of a process.

2023-08-17 22:13 UTC, jedcunningham commented on astro/develop-project.md
> +    trusted-host = pypi.python.org
The point of adding the customers CA is so you we don't have to turn off validation. We should remove this part.

2023-08-17 22:25 UTC, afastronomer commented on astro/develop-project.md
> +    trusted-host = pypi.python.org
for my recent case only adding certs and "trusted hosts" correction allowed to pull python libraries. any of these solutions didn't help by itself.

2023-08-21 17:18 UTC, lzdanski commented on astro/develop-project.md
> +    The following example uses code from the [Install packages from Private repository](/astro/develop-project#install-python-packages-from-private-sources) example, and shows where to add the CA to
This second stanza of example code might be redundant.

2023-08-21 17:26 UTC, lzdanski commented
Definitely out of scope to make any big changes to this page structure, but wow there's a lot of content on this page related to some other conversations about the docs going on with the team. I kicked off a slack conversation about [how this overall page is organized](https://astronomer.slack.com/archives/C015V2JFKT5/p1692638612313439), so we can maybe keep the scope of this PR focused on just clarifying the CA cert steps. I can see how my changes/suggestions might send us down major scope creep, and I don't want that to happen.  

@afastronomer - how do these changes look?

2023-08-22 20:36 UTC, rob-1126 commented on astro/develop-project.md
> +    trusted-host = pypi.python.org
Is it because the trusted ca is added in the user layers and there are ONBUILD directives that run before that that attempt to install from pip and fail? I'd still expect the same with modfiying the pip config as well though.

2023-08-23 13:21 UTC, jwitz requested changes
Overall LGTM, but holding off on merging until we resolve Jed's discussion on Step 1

2023-08-23 13:21 UTC, jwitz commented on astro/develop-project.md
> +- Your Astro project `dockerfile`. See [Install packages from Private repository](/astro/develop-project#install-python-packages-from-private-sources) for an example.
```suggestion
#### Prerequisites

- The internal root certificate. You might need to request this from your security or network team
- An Astro project.
```

2023-08-23 13:21 UTC, jwitz commented on astro/develop-project.md
> +1. Specify the Runtime version in your Dockerfile, and make sure you use Runtime **base** image. The base image tag is formatted as `quay.io/astronomer/astro-runtime:8.8.0-base`, and not the regular
```suggestion
1. If you aren't already using it, specify the `base` distribution of your Astro Runtime version in your Dockerfile. The base image tag is formatted as `quay.io/astronomer/astro-runtime:<version>-base`.
```

2023-08-23 13:21 UTC, jwitz commented on astro/develop-project.md
> +3. (Optional) Add additional `COPY` statements before the `RUN update-ca-certificates` stanza for each CA certificate your organization uses for external access.
```suggestion
3. (Optional) Add additional `COPY` statements before the `RUN update-ca-certificates` command for each CA certificate your organization uses.
```

2023-08-23 19:39 UTC, jedcunningham commented on astro/develop-project.md
> +    trusted-host = pypi.python.org
Okay, I think we are getting somewhere now.

https://pip.pypa.io/en/latest/topics/https-certificates/

"This does not use the system certificate store but, instead, uses a bundled CA certificate store from certifi."

Basically, just adding the CA to the system isn't enough, and turning off validation with trusted-host is why it actually "worked".

3.10 can potentially use truststore and a feature flag, but that won't work as ~half of our supported runtime images aren't on 3.10 anyways. We could document the truststore path for those on 3.10, but we will need an alternative for the others.

Overwriting `pip.conf` also isn't the safest thing to do, as we do have some stuff in our image already that's important.

Probably the best option is setting the `PIP_CERT` env var.

2023-08-24 12:39 UTC, jwitz commented on astro/develop-project.md
> +2. Include the following code in your Astro project `dockerfile`. This entry adds the CA to the trust store and needs to be executed before installing Python packages.
```suggestion
2. Include the following code in your Astro project `dockerfile`. This entry adds the CA to the trust store and needs to be executed before any other build-time arguments
```

2023-08-24 12:40 UTC, jwitz commented on astro/develop-project.md
> +2. Include the following code in your Astro project `dockerfile`. This entry adds the CA to the trust store and needs to be executed before installing Python packages.
Added one suggestion - Python package installation is only one possible Docker image use case, I think we need to clarify that this needs to go before any and all Dockerfile commands

2023-09-05 14:57 UTC, lzdanski commented on astro/develop-project.md
> +    trusted-host = pypi.python.org
@jedcunningham - it sounds like this changes the procedure here quite a bit. I dug around some examples of using `PIP_CERT` with other tools like [Cloud Foundry](https://docs.cloudfoundry.org/buildpacks/python/index.html#private-repos-pip). So I've got some questions about how it affects the content of this PR. 

It sounds like now the process is:

Step 1: Add `PIP_CERT` to your environment variables and have it point to the internal CA certificate

Step 2: Configure your Dockerfile to add the CA to the trust store
- Does `PIP_CERT` need to be added to the[ Dockerfile specifically?] (https://docs.astronomer.io/astro/environment-variables#set-environment-variables-in-your-dockerfile) or can it be added through the Cloud UI? 
- Is adding a certificate in plaintext in the dockerfile a recommended action? Are there any security concerns?
- If it should be added to the Dockerfile, does it need to be added so that it's executed before or after the CA is added to the trust store in Step 2?

2023-09-13 15:36 UTC, lzdanski commented
Closing PR due to inactivity. We can reopen and address with increase in customer feedback or when there's time for technical discussion on what specific docs change is needed here.

2023-09-13 15:36 UTC, closed without merging