Enhance intro content
astronomer/docs pull request #2733
Opened 2023-08-23 18:19 UTC by lzdanski

We have some pages that could use some more detail in the introductory text at the beginning. 

This PR tackles

- DAG Metrics (https://docs.astronomer.io/astro/dag-metrics)
- Configure a Deployment (https://docs.astronomer.io/astro/configure-deployment-resources)

Addresses #2731

2023-08-23 18:21 UTC, lzdanski commented on astro/configure-deployment-resources.md
> +After you create an Astro Deployment, you can modify its settings using the Cloud UI and Astro CLI to tailor its behavior for your specific needs.
I think that this page might have outgrown the original intent for it - how do we feel about parsing out the individual sections into separate pages that cover smaller actions or categories of actions?

2023-08-23 18:22 UTC, lzdanski commented on astro/manage-teams.md
> +
I think that all the user management pages might benefit from a diagram illustrating the relationship between Orgs, Workspaces, Deployments, and Teams

2023-09-01 11:28 UTC, jwitz requested changes
Overall LGTM! I'll take another look at the Teams overview because my edits there got kinda hairy, but everything else is g2g.

Definitely seems like we need to divvy up the content in Configure Deployment Resources into new docs, but I think the reorg works in the meantime

2023-09-01 11:28 UTC, jwitz commented on astro/manage-teams.md
> +
We have something similar to this in our [architecture overview,](https://docs.astronomer.io/astro/astro-architecture) might be worth duplicating it for an eventual user access overview page?
![image](https://github.com/astronomer/docs/assets/74574233/8719aa6e-44a9-46ca-993f-342612899185)

2023-09-01 11:28 UTC, jwitz commented on astro/manage-teams.md
> +Organization Owners create, update, or delete Teams. Then, either Organization Owners or Workspace Owners can assign Teams to different Workspaces and define their [Workspace permissions](astro/user-
```suggestion
You can also assign different roles for each Workspace. For example, you can have a group of DAG authors that has full Workspace Owner permissions for development Workspaces, and that same Team can have only Workspace Member permissions for production Workspaces.
```

2023-09-01 11:28 UTC, jwitz commented on astro/manage-teams.md
> +After adding users to an Astro Organization through [an SSO provider](astro/configure-idp) or by [manually adding users](/astro/manage-organization-users#add-a-user-to-an-organization), Organization
```suggestion
As an Organization Owner or Workspace Owner, you can use Teams to batch assign Organization and Workspace roles to groups of users. Organization Owners create, update, or delete Teams. Then, either Organization Owners or Workspace Owners can assign Teams to different Workspaces and define their [Workspace permissions](user-permissions.md#workspace-roles).
```

2023-09-01 11:28 UTC, jwitz commented on astro/manage-teams.md
> +After adding users to an Astro Organization through [an SSO provider](astro/configure-idp) or by [manually adding users](/astro/manage-organization-users#add-a-user-to-an-organization), Organization
- I know the permissions are important here, but I'd rather those be in a prerequisite and continue to use 2nd person for referring to user actions.
- Let's always use the file link (with `md`) instead of the relative link since that's much less likely to change over time.
- One more nit: You don't necessarily have to add users to Astro first to use Teams. SCIM provisioning allows users to be imported as Teams directly from an IdP.

2023-09-01 11:28 UTC, jwitz commented on astro/manage-teams.md
> +_Teams_ are a group of users in an Organization that you can grant the same Organization and Workspace permissions. Because a Workspace is a collection of Deployments, you can use Workspaces to group
```suggestion
A _Team_ is a group of users in an Organization that share the same Organization and Workspace permissions. You can use Teams to securely assign permissions for a large group of users across multiple Workspaces. For example, you can create a Team of DAG authors, then assign that Team to each of your development Workspaces as a Workspace author.
```
The edit reads like more of a description of Workspaces than Workspace Teams, I made this edit to try to ground this description in an example.

2023-09-01 14:26 UTC, lzdanski commented on astro/configure-deployment-resources.md
>  - Transfer a Deployment to another Workspace in your Organization.
Yes I agree, I'm not loving Metadata as the bucket, but I'm trying to keep it out of headings/page titles/rel links so that we can change it without too much disruption or need for redirects.

2023-09-01 14:28 UTC, lzdanski commented on astro/manage-teams.md
> +
I'm planning on a follow up PR to add a diagram, but glad to know there's something I can base it off of!

2023-09-01 15:07 UTC, lzdanski reviewed
With the change to the sidebar navigation, can also update headings here too

2023-09-01 15:07 UTC, lzdanski commented on astro/configure-deployment-resources.md
> +After you create an Astro Deployment, you can modify its settings using the Cloud UI and Astro CLI to tailor its performance. There's two categories of options for configuring your Astro Deployment t
```suggestion
After you create an Astro Deployment, you can modify its settings using the Cloud UI and Astro CLI to tailor its performance. There's two categories of options for configuring your Astro Deployment to best meet your needs: Deployment settings and resource configuration.
```

2023-09-01 15:07 UTC, lzdanski commented on astro/configure-deployment-resources.md
> +Use metadata configurations to manage the administration of your Deployment. This includes includes actions like updating information about your Deployment or transferring it to another Workspace. Th
```suggestion
Use Deployment settings to manage the administration of your Deployment. This includes includes actions like updating information about your Deployment or transferring it to another Workspace. The following actions allow you to organize and label your Deployments within your Workspace in a way that best fits how your team works with Astro: 
```

2023-09-01 15:07 UTC, lzdanski commented on astro/configure-deployment-resources.md
> +## Configure metadata
```suggestion
## Configure Deployment settings
```

2023-09-01 15:07 UTC, lzdanski commented on astro/dag-metrics.md
> +See [Manage DAGs](manage-dags.md).
```suggestion
```

This link immediately follows this statement and feels redundant

2023-09-01 21:12 UTC, lzdanski commented
@jwitz - please make any final changes you think are needed and merge on Monday!

2023-09-04 10:21 UTC, jwitz approved these changes
Looks good! We'll have to do some more work of the Deployment Settings pages in light of our refactoring work and upcoming UI changes, but this is cleaner than before

2023-09-04 10:21 UTC, jwitz commented on astro/deployment-settings.md
> +## Configure details
```suggestion
## Configure Deployment details
```

2023-09-04 10:21 UTC, jwitz commented on astro/deployment-settings.md
> +### Enforce CI/CD deploys
This seems like more of a "Deployment details" setting.

2023-09-04 10:23 UTC, jwitz commented on astro/deployment-settings.md
> +## Configure Deployment details
```suggestion
## Configure Deployment details

Deployment details include metadata, such as your Deployment name and description, as well as user access and observability settings.
```

2023-09-04 10:35 UTC, jwitz commented on astro/deployment-settings.md
> +Update Deployment resource settings to optimize the performance and reduce the cost of running Airflow in the cloud.
```suggestion
Update Deployment resource settings to optimize performance and reduce the cost of running Airflow in the cloud.
```

2023-09-04 11:01 UTC, merged