Secrets Backend - Restructure Draft
astronomer/docs pull request #2739
Opened 2023-08-24 18:38 UTC by lzdanski

Addresses https://github.com/astronomer/docs/issues/2731

* Create Overview + Processes Docs Structure

2023-09-06 14:17 UTC, jwitz requested changes
Content in general looks good! I know you only have to be a Workspace Operator to complete this setup, but what do you think about adding these docs to the **Administration** > **Deployments** [sidebar menu](https://docs.astronomer.io/astro/authorize-deployments-to-your-cloud)? My thinking is that anyone with the ability to grant access to a secrets backend is an admin persona of some sort. That menu isn't in this PR, but you pull from the main branch it should be available to work with.

2023-09-06 14:17 UTC, jwitz commented on sidebarsAstro.js
> +          label: "Configure a secrets backend",
```suggestion
          label: "Set up a secrets backend",
```
Since we just removed a bunch of "configure"/ "manage" instances from the sidebar, thought it would be better to have a more descriptive word here. Also makes it consistent with the doc titles.

2023-09-06 14:17 UTC, jwitz commented on astro/secrets-backend.md
> +Secrets backend integrations are configured individually with each Astro Deployment by a Workspace member with either Workspace Operator or Workspace Owner permissions.
```suggestion
Secrets backend integrations can be configured individually with each Astro Deployment by someone with either Workspace Operator permissions.
```
Tricky because "Workspace Member" is also a role haha. Also removed "workspace owner" because I thought it was safe to assume that Owners know they have Operator permissions.

2023-09-06 14:17 UTC, jwitz commented on sidebarsAstro.js
> +          label: "Configure a secrets backend",
Something I just remembered: There's an option in Docusaurus to have the top level menu button link to the first doc in the menu itself. We could do that here so that when you click "Configure a secrets backend", it automatically brings you to the overview. Do you think that' would be helpful or jarring for users?

2023-09-06 20:08 UTC, lzdanski commented on sidebarsAstro.js
> +          label: "Configure a secrets backend",
I think that would be great! There's a few places that we might want to do that - where there's overview pages, for example?

2023-09-07 08:23 UTC, jwitz commented on sidebarsAstro.js
> +          label: "Configure a secrets backend",
```suggestion
          type: "category",
          label: "Configure a secrets backend",
          link: { type: 'doc', id: 'secrets-backend' },
```
Might want to check the behavior of this in preview, you may need to remove the overview doc from the items list.

2023-09-07 08:24 UTC, jwitz requested changes
Added the link to the overview, can you let me know about the idea to put this in Administration? Thanks!

2023-09-07 13:19 UTC, lzdanski commented
> Added the link to the overview, can you let me know about the idea to put this in Administration? Thanks!

@jwitz Definitely thought I'd replied to this yesterday! Yes, I think it makes sense in that context. I'm adding it to that part of the sidebar. Definitely thought that PR was still in flight and would need to be in a separate change and missed your update about it being merged when I was skimming the comments yesterday! But I got it now.

2023-09-07 13:42 UTC, lzdanski commented on astro/secrets-backend.md
>  ---
@fritz-astronomer - since we talked through this PR earlier in the week, wanted to wait and ask for your review until we were done with any remaining docs editorial feedback. Hopefully this should be a quick look-over! This is the only page that needs your review, the others changes are from rearranging the docs.

2023-09-07 14:49 UTC, jwitz approved these changes

2023-09-08 18:41 UTC, lzdanski commented
@manmeetkaur - Trying to merge this Monday/Tuesday - could you take a look at the overview page? Will follow up with reviewing the process docs in a later PR.

2023-09-14 17:10 UTC, lzdanski commented on astro/secrets-backend.md
>  title: 'Configure an external secrets backend on Astro'
@paolaperaza - this is the only file we're reviewing the content of for this PR! Just really need feedback on the restructure itself and this content, but will have follow-up PRs to address the individual procedure docs. They each need some dedicated time and we didn't want to drag the review of the restructure + overview edit out.

The plan to merge this PR is after we finish **Testing and troubleshooting locally** > **Runtime reorg** > **Secrets Backend** since we have so many docs reorganization PRs in flight. 

**Summary of changes:**

- Moved procedures into their own child pages of the new section **Secrets backend**
- configured the sidebar to take user directly to the overview page when selecting **Secrets backend** from the nav
- Shifted the scope of the overview to focus on specific benefits and considerations of adding a secrets backend of broadly discussing how Astro handles credentials for connections/variables. 
    - Specifically to emphasize that this would be best implemented as part of existing organizational strategy. Otherwise, users need to select and set up a secrets backend. 
- Moved this topic from **Manage Deployments** in the sidebar to **Administration>Deployments** because only **Workspace operators** or **Organization owners** have the correct credentials to configure the set up.

2023-09-18 19:39 UTC, fritz-astronomer approved these changes
lgtm. Sorry for the delay

2023-10-04 21:34 UTC, lzdanski commented on astro/secrets-backend.md
> +Apache Airflow [variables](https://docs.astronomer.io/learn/airflow-variables) and [connections](https://docs.astronomer.io/learn/connections) often contain sensitive information about your external
```suggestion
Apache Airflow [variables](https://docs.astronomer.io/learn/airflow-variables) and [connections](https://docs.astronomer.io/learn/connections) often contain sensitive information about your external systems that you need to keep in a _secrets backend_ tool, which stores secrets in a secure and centralized location. Unlike other management strategies, such as using Environment Variables or working with connections and variables in the Airflow UI, secrets backends require a third-party secrets manager. This means that you can use a secrets manager administered by your organization for existing security protocols, or you need to choose and set up a secrets backend. 

This document explains the available secrets backend integrations supported by Astro and how Airflow finds connections and variables if you use multiple strategies to manage your variables and connections.
```

2023-10-04 21:34 UTC, lzdanski commented on astro/secrets-backend.md
> +Using secrets to set Airflow connections requires knowledge of how to generate Airflow connection in URI or JSON format. See [Import and export Airflow connections and variables](import-export-connec
```suggestion
Using secrets to set Airflow connections requires knowledge of how to generate Airflow connections in URI or JSON format. See [Import and export Airflow connections and variables](import-export-connections-variables.md) for guidance on how to export your connections and variables based on where they are stored.
```

2023-10-04 21:34 UTC, lzdanski commented on astro/secrets-backend.md
> +## How Airflow finds an Airflow connection or variable
```suggestion
## How Airflow finds connections or variables
```

2023-10-04 21:34 UTC, lzdanski commented on astro/secrets-backend.md
> +If you configure a secrets backend on Astro, you can still continue to define Airflow variables and connections either [as environment variables](environment-variables.md) or in the Airflow UI. Airfl
```suggestion
If you configure a secrets backend on Astro, you can still continue to define Airflow variables and connections as either [environment variables](environment-variables.md) or in the Airflow UI. Airflow checks for the value of an Airflow variable or connection in the following order:
```

2023-10-11 19:47 UTC, paolaperaza approved these changes
LGTM! Left a couple comments:

- Just double check format
- Add 1-liner to overview section
- Add numbered steps to Azure doc

2023-10-11 19:47 UTC, paolaperaza commented on astro/secrets-backend/aws-paramstore.md
> +
Add one link back to home

> If you use another secrets backend tool or want to learn how to approach integrating a secrets backend doc generally, see ...

2023-10-11 19:47 UTC, paolaperaza commented on astro/secrets-backend/aws-secretsmanager.md
> +## Step 2: Set up Secrets Manager locally
Just check formatting here

2023-10-11 19:47 UTC, paolaperaza commented on astro/secrets-backend/azure-key-vault.md
> +### Create an access policy
Are we missing steps here?

2023-10-11 19:47 UTC, paolaperaza commented on astro/secrets-backend/gcp-secretsmanager.md
> +    $ astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND=airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
Check format here

2023-10-11 19:47 UTC, paolaperaza commented on sidebarsAstro.js
> +          "secrets-backend/gcp-secretsmanager",
Just make sure these are alphabetical

2023-10-11 19:47 UTC, lzdanski reviewed
small fixes

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend.md
> +This document explains the available secrets backend integrations supported by Astro and how Airflow finds connections and variables if you use multiple strategies to manage your variables and connec
```suggestion
This document explains the available secrets backend integrations supported by Astro and how Airflow finds connections and variables if you use multiple strategies to manage them.
```

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend.md
> +See [Manage connections and variables](manage-connections-variables.md) to learn more about your available management options and decide whether using a secrets backend complies with your organizatio
```suggestion
See [Manage connections and variables](manage-connections-variables.md) to learn more about your available options and decide whether using a secrets backend complies with your organization's security requirements.
```

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend/azure-key-vault.md
> +### Register Astro as an app on Azure
```suggestion
### Step 1: Register Astro as an app on Azure
```

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend/azure-key-vault.md
> +### Create an access policy
```suggestion
### Step 2: Create an access policy
```

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend/azure-key-vault.md
> +### Set up Key Vault locally
```suggestion
### Step 3: Set up Key Vault locally
```

2023-10-11 19:47 UTC, lzdanski commented on astro/secrets-backend/azure-key-vault.md
> +### Deploy to Astro
```suggestion
### Step 4: Deploy to Astro
```

2023-10-11 19:49 UTC, lzdanski commented on astro/secrets-backend.md
>  title: 'Configure an external secrets backend on Astro'
```suggestion
title: 'Configure a secrets backend '
```

2023-10-12 18:24 UTC, lzdanski commented on astro/secrets-backend/gcp-secretsmanager.md
> +    $ astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND=airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
Fully rendered formatting is correct. Github does some auto-formatting in PR's that make it look like there's breaks in the rendering, but it's okay. The actual content of the code example is quite lengthy :/

2023-10-12 19:16 UTC, merged