Use CLI to assign team roles
astronomer/docs pull request #2755
Opened 2023-08-28 22:34 UTC by lzdanski

Resolves https://github.com/astronomer/docs/issues/2750

Outstanding to-do:

- [ ] Update section about user roles and team roles (https://docs.astronomer.io/astro/user-permissions#user-roles-and-team-roles) 
- [ ] Add new section to configure teams (https://docs.astronomer.io/astro/manage-teams)

2023-08-30 09:39 UTC, jwitz requested changes
Reference updates look good! Requesting changes on some thoughts I had in the new process topic, curious to know what you think before moving ahead

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +    Available Role options include `WORKSPACE_MEMBER`, `WORKSPACE_OPERATOR`, or `WORKSPACE_OWNER`. By default, the Team is assigned to `WORKSPACE_MEMBER`.
```suggestion
    Available role options include `WORKSPACE_MEMBER`, `WORKSPACE_AUTHOR`, `WORKSPACE_OPERATOR`, or `WORKSPACE_OWNER`. By default, the Team is assigned as a `WORKSPACE_MEMBER`.
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +## Add Teams to Workspaces with Astro CLI
```suggestion
## Add Teams to Workspaces using the Astro CLI
```
We can keep this topic for now, but in the future I would expect something like this in the Automation/ CI/CD menu in an "Examples" doc with a proper scripting example for adding multiple Teams at once. Currently the topic is positioned as if the steps are what you'd do to programmatically add teams, but the actual automation process is more complicated and uses alternative authentication steps.

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +
```suggestion
:::cli

You can add a Team to multiple Workspaces programmatically using the Astro CLI. See [`astro workspace team add`](cli/astro-workspace-team-add.md) for example output and commands.

:::

```
If you agree with my point above and don't want to publish this topic quite yet, we can use this note in its place under "Add a Team to a Workspace". I'm cool either way!

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +- Create a [Team](#create-a-team)
```suggestion
- The [Astro CLI](cli/install-cli.md).
- A [Team](#create-a-team)
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +    astro workspace
```suggestion
    astro workspace list
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +    :::tip
```suggestion
```
Tip is more "cool and optional", this feels like more of a troubleshooting step

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +    If you do not see the Workspace as a choice, confirm which Organization you're currently working in with `astro organization list`. You can switch to the correct Organization with `astro organiza
```suggestion
    If you don't see the right Workspace as a choice, confirm which Organization you're currently working in using `astro organization list`. You can switch to the correct Organization using `astro organization switch`.
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +3. Retrieve the Team ID.
```suggestion
3. Run the following command to find the Team you want to add. Copy its `TEAM ID`:
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +1. Log in to Astro.
```suggestion
1. Run the following command to log in to Astro:
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +2. Choose the Workspace where you want to add a Team.
```suggestion
2. Run the following command to identify the Workspace where you want to add the Team.
```
This is one of the steps where it wouldn't really make sense to have it from a programmatic standpoint, they would likely have the Workspace ID on hand or need to parse this output to retrieve it.

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +    This command returns the Team ID, team name, creation date, and Organization Role the Team has.
```suggestion
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +4. Use the Team ID to assign the Team to other Workspaces in your Organization and optionally configure their [Workspace Role](/astro/user-permissions.md#workspace-roles).
```suggestion
4. Run the following command to assign the Team to other Workspaces in your Organization.
```

2023-08-30 09:39 UTC, jwitz commented on astro/manage-teams.md
> +5. You can test that you assigned your Team successfully by listing all Teams in your current Workspace.
```suggestion
5. Run the following command to confirm that the Team was successfully added to your current Workspace.
```

2023-08-30 09:39 UTC, jwitz commented on astro/user-permissions.md
>  ## User roles and Team roles
```suggestion
## Relationship between user roles and Team roles
```
Hmm, I'm not sure the edits here relate to the topic. When I wrote this, it was meant to clarify the logic of user roles overriding Team roles and vice versa. Tried updating the title to make this clear.

2023-08-30 09:39 UTC, jwitz commented on astro/user-permissions.md
>  - Assign a Workspace role to a [Team](manage-teams.md#add-a-team-to-a-workspace).
```suggestion
- Assign a Workspace role to a [Team](manage-teams.md#add-a-team-to-a-workspace) and add the user to the Team.
```

2023-08-30 09:39 UTC, jwitz commented on astro/user-permissions.md
> +- Assign Teams to Workspaces and define their user roles with the [Astro CLI](manage-teams.md#add-teams-to-workspaces-with-astro-cli).
```suggestion
```

2023-08-30 09:39 UTC, jwitz commented on astro/user-permissions.md
> +You can assign Teams to Workspaces and configure their Workspace user roles in either the Cloud UI or programmatically with the Astro CLI:
```suggestion
There are two ways to define a user's role in a Workspace:
```

2023-08-30 15:16 UTC, lzdanski commented on astro/manage-teams.md
> +
Would it follow an analogous process to the Adding multiple users to a workspace? https://docs.astronomer.io/astro/manage-workspace-users#add-a-group-of-users-to-a-workspace-using-the-astro-cli

2023-08-30 15:37 UTC, lzdanski commented on astro/manage-teams.md
> +    :::
```suggestion
```

2023-08-30 16:06 UTC, lzdanski commented on astro/manage-teams.md
> +
Have discussed with CLI team that these processes are _not_ analogous, and this functionality would be really tricky to script. Will  skip for now.

2023-08-31 14:21 UTC, jwitz approved these changes
LGTM! Also if you are using VScode as your code editor, I recommend installing [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and running alt + shift + f to automatically space your tables for future raw markdown legibility

2023-08-31 14:21 UTC, jwitz commented on astro/manage-teams.md
> +:::
```suggestion
:::cli

You can add a Team to multiple Workspaces programmatically using the Astro CLI. See [`astro workspace team add`](cli/astro-workspace-team-add.md) for example output and commands.

:::
```

2023-08-31 14:21 UTC, jwitz commented on astro/cli/astro-workspace-team.md
>  | ----------------------------- | --------------------------------- | --------------------------------------------------------------------------------- |
Software commands behave a bit differently from Astro commands, it's possible that `--workspace-id` is required but I can't verify at the moment. I would err on the side of caution and keep this as-is for now (unless you tested on Software, in which case go ahead with this!)

2023-09-05 15:04 UTC, merged