Clarify P1, P2, and P3 support levels
astronomer/docs pull request #2759
Opened 2023-08-29 15:16 UTC by collinmcnulty

We have quite specific expectations of what should be a ticket at each priority level. Especially for P1 tickets, our processes for handling these tickets only makes sense in the context of certain kinds of issues. Without this level of specificity, we do get tickets labeled higher than they should be because, understandably, everyone feels their own issue is high priority. This PR attempts to clarify on the existing process.

2023-08-30 15:51 UTC, collinmcnulty commented on astro/astro-support.md
> +- A DAG that has been deployed to an Astro deployment for the first time, or is on a local development environment, is unexpectedly not working.
good idea.

2023-08-30 19:12 UTC, RNHTTR requested changes

2023-08-30 19:12 UTC, RNHTTR commented on astro/astro-support.md
> +Because P1 tickets are handled with the highest levels of urgency, if Astronomer Support responds on a P1 ticket and subsequently does not hear back for 2 hours, the ticket priority will be changed t
> the ticket priority will be changed to P2.

I think we should say "will be automatically changed to P2."

2023-08-30 19:12 UTC, RNHTTR commented on astro/astro-support.md
> +- You have lost use of a Public Preview feature that does not affect general services.
nit: "does not affect generally available services"

2023-08-30 19:12 UTC, RNHTTR commented on software/support.md
> +**P2:** High impact. Ability to use Astronomer Software is severely impaired but does not affect critical, previously working pipelines in production.
also same comment... "automatically changed to a P2"

2023-08-30 19:35 UTC, collinmcnulty commented on astro/astro-support.md
> +- You have lost use of a Public Preview feature that does not affect general services.
I am actually not sure what this line is trying to say. I didn't edit it.

2023-08-30 20:15 UTC, RNHTTR commented on astro/astro-support.md
> +- You have lost use of a Public Preview feature that does not affect general services.
I think we should edit it to link to [this doc](https://docs.astronomer.io/astro/feature-previews) which includes a blurb that preview features are not backed by an SLA.

2023-08-31 14:07 UTC, jwitz commented on astro/astro-support.md
> +- A newly deployed production DAG is not working, even though it was tested in another Astro Deployment (e.g. dev or test) beforehand.
```suggestion
- A newly deployed production DAG is not working, even though it ran successfully in a development or test environment.
```

2023-08-31 14:09 UTC, jwitz commented on astro/astro-support.md
> +- A DAG that has been deployed to an Astro deployment for the first time, or is on a local development environment, is unexpectedly not working.
Updated my suggestion, is this what you meant?

2023-08-31 19:38 UTC, collinmcnulty commented
@jwitz With the changes you added, are you good to approve?

2023-08-31 19:41 UTC, collinmcnulty commented on astro/astro-support.md
> +- A DAG that has been deployed to an Astro deployment for the first time, or is on a local development environment, is unexpectedly not working.
I'm removing the word "development" before Deployment. But otherwise yes, I like that.

2023-08-31 19:43 UTC, collinmcnulty commented
@jwitz I think we're good now

2023-09-01 10:25 UTC, jwitz approved these changes
Me too! Let's merge it

2023-09-01 10:26 UTC, merged