Added explanations and best practices to our Grafana docs
astronomer/docs pull request #277
Opened 2021-03-07 17:21 UTC by jwitz

Closes https://github.com/astronomer/docs/issues/153.

This is a major update to our Grafana content which can be seen as three significant changes:

- Added screen shots for new metrics and dashboards
- Added a section for creating a custom dashboard
- Included recommendations and best practices for various key metrics. 

I've included further comments/ questions within the PR itself. Once this looks good, I'll push it to all other Enterprise docsets.

2021-03-07 17:23 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +1. In the Grafana sidebar menu, click the dashboard icon button and click **New**
I created these steps based on other documentation online, as I don't personally have access to these functions on my own Grafana dashboard. Please double check these for consistency. 

In addition, any screen shots of the UI elements here would be super appreciated @ben-astro

2021-03-07 17:24 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- Node Disk Space Utilization
Based on the Metrics interface, these metrics probably have specific query names we should mention, right? If there's anything else we should mention about how to configure these (time interval, mins/maxes, etc), let me know.

2021-03-07 19:33 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +1. Ensure you're logged into Grafana. If you're on the Welcome page, you can log in via the **Sign In** button at the bottom of the sidebar menu. The default login credentials are `admin:admin`
Do you have to have a specific role in Astronomer to have access to creating dashboards?

2021-03-12 22:44 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +1. Ensure you're logged into Grafana. If you're on the Welcome page, you can log in via the **Sign In** button at the bottom of the sidebar menu. The default login credentials are `admin:admin`
@jwitz Yes, you need to be Sysadmin in Astronomer Platform to have access to Grafana at all. When you're in Grafana itself, you can use the "login" function with admin/admin to get access to edit dashboards.

2021-03-12 22:51 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    In the following example, the query has been rewritten in the format `sum(increase(airflow_ti_successes[<time>]))`, which changes the time interval that appears in the metric. We recommend lookin
@jwitz should be "...to clearly identify trends..."

2021-03-12 22:53 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    In addition, the eye icon on the metric has been deselected so that only task failures are shown:
@jwitz should be "...icon on the Successes metric...."

2021-03-12 22:58 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    You could also write this query as `sum by (deployment) (increase(airflow_ti_failures[<time-interval>]))` to view task volume across an entire Deployment, which is useful for monitoring potential
@jwitz Do you think the other couple of screenshots would be useful here, in showing the effects of changing the time intervals, as well as changing the legend to be {{deployment}} instead of "failed"? The latter at least does a great job of showing the ability to see grouped sums across all different Airflow deployments. 
<img width="1635" alt="SumByDeployment" src="https://user-images.githubusercontent.com/68117952/111007339-70982a00-8343-11eb-9cc1-d99d0e99020a.png">
<img width="1634" alt="TrendsOverTime" src="https://user-images.githubusercontent.com/68117952/111007343-7261ed80-8343-11eb-8e9f-a947cdc27c48.png">

2021-03-12 23:01 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    In the following example, the query has been rewritten in the format `sum(increase(airflow_ti_successes[<time>]))`, which changes the time interval that appears in the metric. We recommend lookin
also I think the result of switching the time interval is a great add here, so admins can see examples of longer trends: 
<img width="1634" alt="TrendsOverTime" src="https://user-images.githubusercontent.com/68117952/111007498-cf5da380-8343-11eb-8a21-fed051912e65.png">

2021-03-12 23:07 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Database Connections:** This metric can be found in the **Database** panel. It measures how often your database is reached out to by the Airflow Scheduler, Webserver, and Workers. The chart shows
Hey @jwitz this section originally had a graphic, that was included in the same graphic as PGBouncerWaitingClients - if you think it'd be better to have a screenshot that only shows the DB connections, let me know if you want to get a fresh screenshot, or if you can snip the original (top left chart).
<img width="2035" alt="PGBouncer" src="https://user-images.githubusercontent.com/68117952/111007821-9245e100-8344-11eb-84ad-2ee72c62f14d.png">

2021-03-12 23:09 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    For example, an organization would want to investigate the green Scheduler in the following screenshot:
@jwitz I think the screenshot didn't make it in here somehow... attaching here. 
<img width="985" alt="UnhealthySchedulers" src="https://user-images.githubusercontent.com/68117952/111007968-ec46a680-8344-11eb-8f0d-833cd6e3d85c.png">

2021-03-12 23:13 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +   Anything under 1 second is considered good, but the lower the measured time the better. Note that operator executions are not included in this metric, as those are typically scheduled for executio
@jwitz ditto as above
<img width="981" alt="DAG_Parsing_Time" src="https://user-images.githubusercontent.com/68117952/111008235-7abb2800-8345-11eb-80a6-c6ca5c205231.png">

2021-03-12 23:18 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Elasticsearch Available Disk Space:** Astronomer leverages the ELK stack for logging events; this is an important part of establishing observability for the platform as a whole. To do this succes
@jwitz Need to correct this to be more specific (I had it wrong in original doc) - should be "Astronomer leverages Elasticsearch, Fluentd and Kibana for logging events;"

Also - did you intend to not include the screenshot here of Elasticsearch Available Disk Space? 
<img width="654" alt="Elasticseach_Avail_Space" src="https://user-images.githubusercontent.com/68117952/111008551-32503a00-8346-11eb-8e49-5d6313041eb6.png">

2021-03-12 23:22 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +As a starting point, we recommend creating a dashboard with the following metrics visualized as graphs for any organizations using the Kubernetes Executor or KubernetesPodOperator in an Airflow Deplo
@jwitz Thoughts on moving this recommendation up to the "Kubernetes Pods" section of the document? It feels a bit out of place at the bottom, to me. And can just have a line like "See _here_ for more info on how to create custom Grafana Dashboards."

2021-03-12 23:57 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- Node Disk Space Utilization
@jwitz I was able to log into our GCP Grafana and poke around a bit (see example of queries for Disk IO chart), but if we want to get more specific, we would need to set up time with Infra team and nail down everything (not sure that's needed - I think it's okay to point clients in a direction and have them come to us with questions; and the best solution anyway would be for us to push to implement some of these as pre-built dashboards in the platform). 
![image](https://user-images.githubusercontent.com/68117952/111010466-7bef5380-834b-11eb-86eb-6d6b4b10d6d5.png)

2021-03-13 00:00 UTC, ben-astro commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Read the rest of this guide to learn about Astronomer's built in dashboards, as well as key metrics to track the overall health of your platform.
@jwitz minor thing throughout the doc- sometimes we have "built in" dashboards and sometimes we have it "built-in" - thoughts on bringing those in sync?

2021-03-19 15:48 UTC, jwitz reviewed
Thanks for these comments @ben-astro ! Apologies for getting back rather late and for the missing screen shots -- everything should be in there. I applied to a few of your comments in the review itself, let me know what you think!

2021-03-19 15:48 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +As a starting point, we recommend creating a dashboard with the following metrics visualized as graphs for any organizations using the Kubernetes Executor or KubernetesPodOperator in an Airflow Deplo
Hm, if we end up having a release Dashboard for this then I don't want to draw too much attention to the "DIY" nature of this. I opted for including a note in the Overview section that states there are metrics not available in some released dashboards, which links to this section.

2021-03-19 18:51 UTC, ben-astro commented
@jwitz Left one more small comment but overall looks great to me!

2021-04-02 22:16 UTC, paolaperaza requested changes
@jwitz Thanks for getting this PR together. It's taking me a while to go through every line, but I think there's opportunity to make this doc tighter and more informative. I just threw in a bunch of comments and suggestions within the first half of the doc that should help towards that effort - can you take a look at them, and apply those standards to the rest of the PR before I review it?

Two additional structural thoughts:
- (Pasted this from in-line comment) Getting to Grafana is actually not intuitive, especially because a lot of people reading this doc WON'T likely have SysAdmin permissions. What do you think about creating an ## Access Grafana section?
- Users may find it confusing that Grafana only filters by `namespace`, which is equivalent to a Deployment's _release name_ (which users can get from the UI/CLI). The release name can also be customized during the deployment creation process by setting a `config.yaml` config, which may be of interest to people reading this doc since it's confusing to try to remember the combination of randomly generated names. I'm not sure where that info would best fit, but maybe try to include it somewhere near the top?

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +**Pod Status:** This metric shows the status of your pods in your environment, which is the same value you get by running `$ kubectl get pod <pod-name> -n <namespace>`. If desired, you can add a pane
```suggestion
**Pod Status:** This metric shows the status of a single pod within your cluster, and displays one of 5 states [as defined by Kubernetes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#) - `Pending`, `Running`, Succeeded`, `Failed`, or `Unknown`. The value for this metric is equivalent to the output of`$ kubectl get pod <pod-name> -n <namespace>`. If you're interested in seeing the status of multiple pods at once, you're free to add a panel to this dashboard.
```

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +**Pod Status:** This metric shows the status of your pods in your environment, which is the same value you get by running `$ kubectl get pod <pod-name> -n <namespace>`. If desired, you can add a pane
The original sentence here didn't make much sense imo

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +### Key metrics
```suggestion
### Key Metrics
```

Standardize capital "M" (or not)

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Use this Dashboard to drill down to each individual Deployment on your platform.
```suggestion
This dashboard displays an important set of resource and health-based metrics at the namespace level. It is most similar to the one displayed in the  **Metrics** of the Astronomer UI for a single Airflow Deployment.
```

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +**Deployment Status:** This metric appears in the **At a Glance** panel of the dashboard. It is a single value that indicates whether a Deployment is healthy or unhealthy.
```suggestion"
**Deployment Status:** This metric indicates whether the selected Deployment is "Healthy" or "Unhealthy", as determined by the state of the pods running within it.
```

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +A Deployment's status is determined by whether all pods in an Airflow deployment are running. If any pods aren't running as expected, the Deployment's status becomes "Unhealthy".
```suggestion
If any pod within an Airflow Deployment's namespace is _not_ in a `Running` state, the Deployment is considered "Unhealthy".
```

2021-04-02 22:16 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
>  This will show the amount of persistent storage available to Prometheus, the registry, and ElasticSearch. It will also show a summary of all alerts that have fired.
```suggestion
This will show the amount of persistent storage available to Prometheus, the platform's Docker registry, and Elasticsearch. It will also show a summary of all alerts that have fired.
```

2021-04-02 22:21 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +This dashboard is most useful for tracking the performance of individual Airflow Deployments, whereas Grafana dashboards are more useful for tracking performance at the platform level.
More general thought: This doc is about Grafana, but this view is in the Astronomer UI - TBH I'm not sure that a section on the Astronomer UI dashboard is immediately relevant. Maybe we introduce it differently?

2021-04-02 22:24 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Astronomer takes metrics generated by Statsd, as well as metrics generated from the KubeAPI by Prometheus and funnels them into Grafana dashboards where you can see the status of all Airflow deployme
StatsD is proper name: https://www.datadoghq.com/blog/statsd/

2021-04-02 22:25 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Read the rest of this guide to learn about Astronomer's built in dashboards, as well as key metrics to track the overall health of your platform.
Looks like you gottem all! Resolving

2021-04-06 13:41 UTC, jwitz reviewed
Thanks for these initial comments @paolaperaza , I made some significant changes in this latest edit. There's now two new sections that explain how to access basic features in Grafana from the Astronomer UI. I also reordered the Dashboards and applied some of your thoughts to as-of-yet unreviewed sections.

2021-04-07 20:50 UTC, paolaperaza reviewed
Awesome second pass at this, @jwitz! Added a few more comments here.

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **1-day Airflow Task Volume:** This metric is the single best tool for monitoring Airflow task successes and failures. It can also be adjusted to better find specific data points.
```suggestion
- **1-day Airflow Task Volume:** This metric is the single best tool for monitoring Airflow task successes and failures, as well growth in volume. It can also be adjusted to better find specific data points.
```

Not totally sure on what`it can be adjusted to better find specific data points` means 👀

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    Scheduler restarts could be normal, such as during an update, but if you see a single scheduler continue to restart or stay in an unhealthy state for a significant amount of time, it is worth inv
The y-axis here is semi confusing - maybe clarify that it's sort of ultimately tracking the "# of schedulers" that are unhealthy? I.e. If 6 Schedulers are unhealthy, a user would see them stacked up to `6` in the y-axis?

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Database Connections:** This metric can be found in the **Database** panel. It measures how often your database is reached out to by the Airflow Scheduler, Webserver, and Workers. The chart shows
Maybe clarify that this your Platform Database, not the Metadata DB?

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Elasticsearch Available Disk Space:** Astronomer utilizes the ELK stack for logging events; this is an important part of establishing observability for the platform as a whole. To do this success
```suggestion
- **Elasticsearch Available Disk Space:** Astronomer utilizes the [ELK stack](https://www.elastic.co/what-is/elk-stack) to power logging, an important part of establishing observability for the platform as a whole. To function successfully, Elasticsearch should always have >20% Available Disk Space. You can monitor this from the “Platform Overview” dashboard to ensure that both task and component logs have been successfully captured and persisted:
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +   If this ever dips below 20%, we recommend increasing the replica count in the Elasticsearch-data helm chart. The helm changes will look something like the following:
link 2 helm chart?

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +This dashboard includes a high level view of resource usage and system stress levels. Use this dashboard to monitor all Airflow Deployments running within your Kubernetes cluster in a single view.
```suggestion
This dashboard includes a high-level view of resource usage and system stress levels. Use this dashboard to monitor all Airflow Deployments running within your Kubernetes cluster in a single view.
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +**Pod Status:** This metric shows the status of a single pod within your cluster, and displays one of 5 states [as defined by Kubernetes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecy
```suggestion
**Pod Status:** This metric shows the status of a single pod within your cluster, and displays one of 5 states [as defined by Kubernetes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#) - `Pending`, `Running`, `Succeeded`, `Failed`, or `Unknown`. The value for this metric is equivalent to the output of `kubectl get pod <pod-name> -n <namespace>`. If you're interested in seeing the status of multiple pods at once, you're free to add a panel to this dashboard.
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +This dashboard tracks the performance of Fluentd, which is the primary logging tool for Astronomer. You can use the metrics in this dashboard to track the overall status of logs being emitted from th
```suggestion
This dashboard tracks the performance of Fluentd, which writes logs to Elasticsearch. You can use the metrics in this dashboard to track the overall status of logs being emitted from the service.
```

"Primary logging tool" feels confusingly general with our description of Elasticsearch/the ELK stack above

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +In addition to their dashboards in Grafana, each of your Deployments has a built-in metrics dashboard in the Astronomer UI. To get there, open a Deployment and go to the **Metrics** tab:
```suggestion
In addition to dashboards in Grafana, each of your Deployments has a built-in metrics dashboard in the Astronomer UI that's accessible to users who have access to that Deployment. To get there, open a Deployment and go to the **Metrics** tab:
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +## Creating Custom Dashboards
```suggestion
## Create Custom Grafana Dashboards
```

Maybe specify since we have references Astro UI dashboards here?

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Because Astronomer's key metrics are distributed across several dashboards, you might want to create a custom dashboard that shows these metrics in one place. To create a custom dashboard:
```suggestion
If Astronomer's pre-built dashboards in Grafana don't fit the needs of your team, you might want to create custom dashboards that compile the metrics you find important. To create a custom dashboard:
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +1. As an Astronomer Admin user, open Grafana from the Astronomer UI.
```suggestion
1. As a System Admin, open Grafana from the Astronomer UI.
```

2021-04-07 20:50 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +6. In the table below the data source dropdown menu. Specify the metric you want to visualize in the **Metrics** field.
```suggestion
6. In the table below the data source dropdown menu, specify the metric you want to visualize in the **Metrics** field.
```

2021-04-07 20:53 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +This dashboard is most useful for tracking the performance of individual Airflow Deployments, whereas Grafana dashboards are more useful for tracking performance at the platform level.
@jwitz Fair enough. Honestly, ideally we have a doc that's applicable to both Cloud and Enterprise with info on the Metrics tab - because Cloud customers don't have access to Grafana. While we get that doc created (not priority), we can keep it in here for now

2021-04-08 18:31 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +
Good call! Just reworded it slightly.

2021-04-08 18:40 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +3. In Grafana, open a dashboard. Click the menu under the Deployment's name to see a list of all possible release names. Depending on which dashboard you're using, the name of this menu is either **D
The items that appear in the menu are release names, so I don't want to call them Deployments.

2021-04-08 18:42 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +4. Select one or multiple release names to monitor in the dashboard.
But the 3-word release name is what they're selecting in the menu. We should be clear that they should be selecting what they recorded in step 2, which in this case is not a Deployment but rather the release name itself.

2021-04-08 18:43 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **1-day Airflow Task Volume:** This metric is the single best tool for monitoring Airflow task successes and failures. It can also be adjusted to better find specific data points.
I don't think our Markdown pipeline likes it when we jump from h2's to h4's.

2021-04-08 18:44 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **1-day Airflow Task Volume:** This metric is the single best tool for monitoring Airflow task successes and failures. It can also be adjusted to better find specific data points.
Oof yeah, that's probably left over from the google doc.

2021-04-08 18:45 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    In the following example, the query has been rewritten in the format `sum(increase(airflow_ti_successes[<time>]))`, which changes the time interval that appears in the metric. We recommend lookin
Isn't "trends" the most appropriate word here? Patterns has an implication of repetition, whereas trends implies a sort of progression or timeline.

2021-04-08 19:02 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    This metric is particularly relevant to organizations with more than 20 Airflow Deployments. For optimal performance, this should stay under 300 less than the `max_connections` for your postgresS
Spent a little too long on this, but I think I got it.

2021-04-08 19:03 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Unhealthy Schedulers:**  This metric is available in the **Airflow Health** panel, but Scheduler health can also be assessed for each individual Deployment in the Astronomer UI's **Metrics** tab.
Reworded slightly.

2021-04-08 19:05 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    Scheduler restarts could be normal, such as during an update, but if you see a single scheduler continue to restart or stay in an unhealthy state for a significant amount of time, it is worth inv
Do you mean that we also recommend that for Enterprise? Tried rewording to make it more clear when this should be looked into.

2021-04-08 19:12 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    Scheduler restarts could be normal, such as during an update, but if you see a single scheduler continue to restart or stay in an unhealthy state for a significant amount of time, it is worth inv
I added a bunch of info to this metric, including what constitutes "Unhealthy" based on our Airflow alerts.

2021-04-08 19:37 UTC, jwitz commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Because Astronomer's key metrics are distributed across several dashboards, you might want to create a custom dashboard that shows these metrics in one place. To create a custom dashboard:
1st half of the suggestion seems a little negative, so I kept the original wording for that part.

2021-04-08 19:46 UTC, jwitz commented
This is ready for another pass @paolaperaza , incorporated most suggestions and left comments where I didn't/ switched things up!

2021-04-08 20:56 UTC, paolaperaza approved these changes
Awesome progress on this - @jwitz! Looks just about ready to me. I dropped a handful of last comments, but nothing major. Approving preemptively.

My only high-level thought: The H4 comment I made was in reference to the metrics specified below `### Key Metrics` throughout the doc. Instead of making those bolded bullet points, did you consider something like: `#### Usage Quotas`?

2021-04-08 20:56 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    This metric is particularly relevant to organizations with more than 20 Airflow Deployments. For optimal postgreSQL database performance, you should keep this number below `max_connections - 300`
```suggestion
    This metric is particularly relevant to organizations with more than 20 Airflow Deployments. For optimal database performance, you should keep this number below `max_connections - 300`.
```

I'd prob just scratch the postgres part? 🤷‍♀️

2021-04-08 20:56 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **Unhealthy Schedulers:**  This metric shows the number of unhealthy Schedulers in a given Deployment. It's available in the **Airflow Health** panel, but Scheduler health can also be assessed for
```suggestion
- **Unhealthy Schedulers:**  This metric shows the number of unhealthy Schedulers in a given Deployment. It's available in the **Airflow Health** panel, but Scheduler health can also be assessed for each individual Deployment in the **Metrics** tab of the Astronomer UI. A Scheduler is considered "Unhealthy" if it has not emitted a heartbeat for over 1 minute.
```

2021-04-08 20:56 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +Because Astronomer's key metrics are distributed across several dashboards, you might want to create a custom dashboard that shows these metrics in one place. To create a custom dashboard:
Good call

2021-04-08 20:58 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +- **1-day Airflow Task Volume:** This metric is the single best tool for monitoring Airflow task successes and failures. It can also be adjusted to better find specific data points.
Made general comment on this in my review, but I'm suggesting to keep `### Key Metrics` as an H3, and then just have the actual key metrics under it as H4's instead of bolded bullet points

2021-04-08 20:59 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    Scheduler restarts could be normal, such as during an update, but if you see a single scheduler continue to restart or stay in an unhealthy state for a significant amount of time, it is worth inv
Made sep comment

2021-04-08 20:59 UTC, paolaperaza commented on enterprise/next/07_monitor/01_grafana-metrics.md
> +    Scheduler restarts could be normal, such as during an update, but if you see a single scheduler continue to restart or stay in an unhealthy state for a significant amount of time, it is worth inv
Awesome

2021-04-09 19:49 UTC, merged