fix wording for VPC peering steps
astronomer/docs pull request #2781
Opened 2023-09-01 16:13 UTC by afastronomer

2023-09-01 21:04 UTC, lzdanski reviewed
Question about some wording and text formatting for style.

2023-09-01 21:04 UTC, lzdanski commented on astro/connect-aws.md
> +6. Wait for Astronomer support to send you the Astro VPC CIDR and VPC Peering ID. Then, the owner of the accepter VPC needs to [create back routes entries](https://docs.aws.amazon.com/vpc/latest/user
```suggestion
6. Wait for Astronomer support to send you the Astro VPC CIDR and VPC Peering ID. Then, the owner of the accepter VPC needs to [create back routes entries](https://docs.aws.amazon.com/vpc/latest/userguide/WorkWithRouteTables.html#AddRemoveRoutes) in the accepter VPC, with the Astro VPC CIDR as the **Destination** and the provided VPC Peering ID as the **Target**.
```

2023-09-01 21:04 UTC, lzdanski commented on astro/connect-aws.md
> +6. Wait for Astronomer support to send you the Astro VPC CIDR and VPC Peering ID. Then, the owner of the accepter VPC needs to [create back routes entries](https://docs.aws.amazon.com/vpc/latest/user
@afastronomer or @stuart23 Making an assumption that the Destination and the Target are buttons or UI entry fields. If they're parameters or values defined in `code`, then they'll need to be code formatted instead. They do need to have a decorator in addition to capitalization. Can you confirm that these changes are accurate?

2023-09-01 21:07 UTC, afastronomer commented on astro/connect-aws.md
> +6. Wait for Astronomer support to send you the Astro VPC CIDR and VPC Peering ID. Then, the owner of the accepter VPC needs to [create back routes entries](https://docs.aws.amazon.com/vpc/latest/user
Those are column names. Now it looks better.

2023-09-04 14:01 UTC, jwitz requested changes
Thanks for this update @afastronomer , just one question about the phrase "accepter VPC"!

2023-09-18 20:55 UTC, jwitz approved these changes
Confirmed with @afastronomer on Slack that "external" works here!

2023-09-18 21:03 UTC, merged