Reorg env vars
astronomer/docs pull request #2801
Opened 2023-09-06 08:41 UTC by manmeetkaur

Resolves #2658

2023-09-06 16:30 UTC, lzdanski reviewed
**monumental** work on this, @mk! I think that some of the struggle with the overview page is definitely from how the information _about_ environment variables is important to know but the reason _why_ is so that users pick the right method for managing and implementing their env vars. What do you think about just fully committing to that being a strategy document? When I shifted my thinking about it as a strategy doc, then suddenly the content structure challenges we talked about didn't seem confusing or repetitive. The doc (without any organizational changes other than adding a heading!) became a nice intro to what are environment variables followed by content that explains details from the perspective of enabling users to make a strategy choice. 

I can understand if this isn't the right move. We can talk about it some more.

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-overview.md
> +
```suggestion
## Choose how to manage environment variables

Environment variables are fundamentally used to take advantage of different performance, behavior, and connection options available to Airflow and Astro. In order to choose the right management and implementation strategy for your needs, you must understand the available management options, how Astro prioritizes environment variables, and how Astro stores them. 
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-overview.md
> +## Ways to manage environment variables on Astro
```suggestion
### Ways to manage environment variables on Astro
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-overview.md
> +## How Astro prioritizes environment variables
```suggestion
### How Astro prioritizes environment variables
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-overview.md
> +## How Astro stores your environment variables
```suggestion
### How Astro stores your environment variables 
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-overview.md
> +## Choose the strategy to manage environment variables
```suggestion
### Choose the strategy to manage environment variables
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +On Astro, you can manage environment variable in four different ways for your Deployment:
```suggestion
On Astro, you can manage environment variable in three different ways for your Deployment:
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +    - Using Astro CLI commands `astro deployment variable create` and `astro deployment variable update`
```suggestion
1. Your Deployment's **Variable** tab in the Cloud UI
2. Your Astro project's `Dockerfile` during deploy
3. With the Astro CLI, using either
    - Your Astro project's `.env` file
    - The Astro CLI commands, `astro deployment variable create` and `astro deployment variable update`
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +The method you choose will depend on your specific use case.
```suggestion
The method you choose depends on your [specific use case](/astro/env-vars-overview#choose-the-strategy-to-manage-environment-variables). 
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +4. Enter an environment variable key and value. For sensitive credentials that should be treated with an additional layer of security, select the **Secret** checkbox. This will permanently hide the v
```suggestion
4. Enter an environment variable key and value. For sensitive credentials that should be treated with an additional layer of security, select the **Secret** checkbox. This permanently hides the variable's value from all users in your Workspace.
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +After you set an environment variable key, only the environment variable value can be modified. You can modify environment variables that are set as secret. However, the variable value is never shown
```suggestion
After you set an environment variable key, only the environment variable value can be modified. While you can modify environment variables that are set as secret, however, the secret variable value is never shown. When you modify a secret environment variable, you'll be prompted to enter a new value.
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +If you want to store environment variables using an external version control tool, Astronomer recommends setting them in your `Dockerfile`. This file is automatically created when you first initializ
```suggestion
If you want to store environment variables with an external version control tool, Astronomer recommends setting them in your `Dockerfile`. This file is automatically created when you first initialize an Astro project using `astro dev init`.
```

2023-09-06 16:30 UTC, lzdanski commented on astro/env-vars-astro.md
> +Note that, environment variables set in your Dockerfile are not visible in the Cloud UI.
```suggestion
Environment variables set in your Dockerfile are not visible in the Cloud UI.
```

2023-09-07 05:43 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +    - Using Astro CLI commands `astro deployment variable create` and `astro deployment variable update`
@lzdanski I was told we were supposed to follow numbers only when we have to follow a specific order else we should have bulleted list ?

2023-09-07 05:43 UTC, manmeetkaur commented on astro/env-vars-global.md
> +This document is a reference for all environment variables on Astronomer with different default values than open source Apache Airflow. You can override [default Runtime environment variables](#defau
So actually the current doc does exist in Reference section and I know it makes sense to keep it there. Originally I was trying to take and club everything up , but I see based on the definition of our "Reference page" this might not fit here.

2023-09-07 05:43 UTC, manmeetkaur commented on astro/env-vars-overview.md
> +
fixed some links that l missed and removed an extra also.

2023-09-07 05:43 UTC, manmeetkaur commented on learn/airflow-variables.md
> +### Using the Airflow UI
I added headings to be able to link to that section specifically.

2023-09-07 05:43 UTC, manmeetkaur commented on sidebarsAstro.js
> -        "environment-variables",
I missed removing that! :) will fix it

2023-09-11 13:49 UTC, lzdanski commented on astro/env-vars-astro.md
> +    - Using Astro CLI commands `astro deployment variable create` and `astro deployment variable update`
Ah sorry! I'm confusing my style guides. Go with what we've got established here and thanks for letting me know!

2023-09-11 21:04 UTC, lzdanski reviewed
This is really coming along! I've got some questions for discussion, and a few style/grammar edits

2023-09-12 07:09 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +Use this document to understand how to use these methods to create environment variables on Astro.
that is a good point. I think I can add a small note.

2023-09-12 07:10 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +### Edit existing values
For deleting, we just have to click the trash icon from the UI which is self-explanatory ?

2023-09-12 07:12 UTC, manmeetkaur commented on astro/env-vars-overview.md
> +Note that, environment variables managed using `Dockerfile` file are not visible in your Cloud UI.
I was actually not sure on the rules of when to put as a Note or just a note. I feel too this should be a called out Note, but you can take the call :)

2023-09-12 07:14 UTC, manmeetkaur commented on astro/env-vars-overview.md
> +| You are a new Astro user, have just created a Deployment and want to integrate your Vault secrets backend to test few DAGs. | [Cloud UI](env-vars-astro.md#using-the-cloud-ui) for ease of use and vi
I should actually remove it. Originally, I just had `Cloud UI` or `Dockerfile` or `.env` in the 2nd column, then it was looking odd and getting mixed up. Now I have sentences with explanation, so might not be required now.

2023-09-12 07:15 UTC, manmeetkaur commented on astro/env-vars-overview.md
> +| You want to ensure all the environment variables defined in the Cloud UI are checked-in to the code repository and bundled in an Astro project before you promote your code from a lower environment
so what should we write ? may be safer with "committed" ?

2023-09-12 07:35 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +sidebar_label: 'Manage environment variables'
I am not sure, will Edit include add, update and delete as well ? May be customize is better ?

2023-09-12 07:58 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +Use this document to understand how to use these methods to create environment variables on Astro.
done

2023-09-12 07:59 UTC, manmeetkaur commented on astro/env-vars-astro.md
> +### Edit existing values
done

2023-09-12 08:00 UTC, manmeetkaur commented on astro/env-vars-global.md
> +This document is a reference for all environment variables on Astronomer with different default values than open source Apache Airflow. You can override [default Runtime environment variables](#defau
I moved it to reference for now

2023-09-28 19:56 UTC, jwitz reviewed
Lots of great info for users here. I added a few notes, will do a deeper dive edit when I'm back from vacation. My main thoughts are:

- We should greatly scale back our content on using `.env` and the Astro CLI. If we want people using `.env` and the Astro CLI in production, that seems more like an example setup/ topic we'd have in our automation docs. I don't expect users to manually run CLI commands as a viable alternative to setting variables in the Cloud UI.
- I'd like to see more specificity about the technical benefits and limitations of the two core storage strategies: The Cloud UI and the Dockerfile. I made some suggestions inline about how we might organize this information

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-astro.md
> +## Using Astro CLI
I would cut this section entirely, and maybe briefly mention CLI storage in the Astro environment variables section. This topic takes up half of the document to explain an alternative delivery mechanism for Astro environment variables. Although we're presenting it parallel to the other options, it's not really a storage mechanism in and of itself.

The other two options have specific benefits and drawbacks that we state, but we don't have that here. I'd like to see the local content in the Astro CLI tab, and parred down version of "In your Astro Deployment" within the "Using the Cloud UI" section

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-astro.md
> +## Using the Cloud UI
The phrasing here is odd. The main decision point for environment variables is not _how_ you set them ("using"), but rather _where_ you set them ("In the control plane"). "Using" sounds like a tool, but what we're really describing here are the steps to store variables in a specific place. We should reframe this doc in terms of where the variables are ending up, rather than how you get them there.

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +On Astro, an _Environment Variable_ is a key-value configuration stored in a configuration file that applies to a specific Deployment. You can use environment variables to configure custom environmen
```suggestion
On Astro, an _environment variable_ is a key-value configuration that applies to a specific Deployment. You can use environment variables to configure custom environment variables for your Deployment, customize core settings of Airflow and its pre-installed providers, or store Airflow connections and variables.
```

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +
It would be worth explaining the difference between Airflow variables and environment variables here.

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +- Add a token or a URL that is required by your Airflow DAGs or tasks
I think these random specific examples are less useful than the core list of use cases mentioned in the first paragraph, I would probably just list those in a bulleted list and remove these examples, which might be overwhelming for users not familiar with each of these concepts

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +- [Using Astro CLI](env-vars-astro.md#using-astro-cli)
See comment on other doc, this is not really a "way" to manage variables, but rather an alternative tool for getting variables to the Cloud UI

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +| Your team has dev/prod/staging environments and you use various environment variables to customize your Airflow environment. | [`Dockerfile`](env-vars-astro.md#using-your-dockerfile) to keep differ
These seems like it would apply to most companies.. if they also want to label envs with an environment variable, which one would they chose? It's not clear from this table.

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +| You want to ensure all the environment variables defined in the Cloud UI are checked-in to the code repository and bundled in an Astro project before you promote your code from a lower environment
Why are we mentioning the Cloud UI here if we're recommending using Dockerfile?

2023-09-28 19:56 UTC, jwitz commented on astro/env-vars-overview.md
> +There are scenarios based on your specific use case when you might want to follow a different strategy or a mix of strategies. The following table describes recommended methods for particular scenari
Because it's possible to follow a mix of strategies, I don't think a table is the right format to present this information. The table assumes "This one scenario is what I'm experiencing, therefore I can do this", when in reality a user will experience multiple scenarios, based on the specific variable they're setting, that call for different methods.

I'd like it better if we had "Benefits/ Drawbacks/ Good for" for both the Cloud UI and Dockerfile. We can mention the Astro CLI and .env as an aside, but I also think it's confusing to add those here as parallel strategies when neither of them are viable production-grade storage solutions.

2023-09-29 18:26 UTC, jwitz commented on astro/develop-project.md
>  ## Set environment variables locally
Potentially add this back?

2023-10-11 09:48 UTC, TJaniF reviewed
Just looked at the Learn guide changes: Looks great! I like having separate headers for the different methods, left two suggestions :)

2023-10-11 09:48 UTC, TJaniF commented on learn/airflow-variables.md
> +- `Variable.get('<VAR_NAME>', '<default-value>')`: This method is more secure for fetching secret values. However, this method can affect performance because it makes a request to the Airflow metadat
```suggestion
- `Variable.get('<VAR_NAME>', '<default-value>')`: This method is recommended and the most secure for fetching secret values. Note that performance can be affected if the `Variable.get()` method is used in top-level DAG code due to making a request to the Airflow metadata database every time your DAGs are parsed, which by default happens every 30 seconds. See [DAG writing best practices](dag-best-practices.md#avoid-top-level-code-in-your-dag-file) for more information about avoiding repeated requests in top level code.
```

I think this is only an issue when the call is made in top level DAG code and would not be true if the call is inside `@task` or inside a function passed to the PythonOperator? I am about 90% sure of that 😅 if that is the case I'd  frame this method as the recommended one 🤔 

cc: @kentdanas :)

2023-10-11 09:48 UTC, TJaniF commented on learn/airflow-variables.md
> +- `os.getenv('AIRFLOW_VAR_<VAR_NAME>','<default-value>')`: This method is faster because it reduces the number of Airflow metadata database requests. However, it's less secure. Astronomer does not re
```suggestion
- `os.getenv('AIRFLOW_VAR_<VAR_NAME>','<default-value>')`: This method is faster because it reduces the number of Airflow metadata database requests. However, it's less secure. Astronomer does not recommend using `os.getenv` with secret values because retrieving environment variables with this method can print them to your logs.
```

This is just a suggestion and a me-thing probably but my first thought was "which function?" because `getenv` was called a method in the sentence before even if ofc those terms are synonyms here 😅

2023-10-11 10:52 UTC, manmeetkaur commented on learn/airflow-variables.md
> +- `Variable.get('<VAR_NAME>', '<default-value>')`: This method is more secure for fetching secret values. However, this method can affect performance because it makes a request to the Airflow metadat
good catch @TJaniF . I thought I had it in there.  going to just change the wording a bit.

2023-10-11 17:53 UTC, lzdanski reviewed
Fix conflict

2023-10-11 17:53 UTC, lzdanski commented on astro/env-vars-astro.md
> +6. Click **Save Variables** to save your changes. Your Airflow scheduler, webserver, and workers restart. After saving, it can take up to two minutes for new variables to be applied to your Deploymen
```suggestion
1. In the Cloud UI, select a Workspace, click **Deployments**, and then select a Deployment.

2. Click the **Variables** tab.

3. Click **Edit Variables**.

4. Enter an environment variable key and value. For sensitive credentials that should be treated with an additional layer of security, select the **Secret** checkbox. This will permanently hide the variable's value from all users in your Workspace.

5. Click **Update Environment Variables** to save your changes. Your Airflow scheduler, webserver, and workers restart. After saving, it can take up to two minutes for new variables to be applied to your Deployment.
```

2023-10-11 17:53 UTC, lzdanski commented on astro/env-vars-astro.md
> +6. Click **Save Variables** to save your changes. Your Airflow scheduler, webserver, and workers restart. After saving, it can take up to two minutes for updated variables to be applied to your Deplo
```suggestion
4. Modify the value of the variable you wish to edit.

    ![Edit value location](/img/docs/variables-edit.png)

5. Click **Update Environment Variables** to save your changes. Your Airflow scheduler, webserver, and workers restart. After saving, it can take up to two minutes for updated variables to be applied to your Deployment.
```

2023-10-20 17:09 UTC, lzdanski commented
Replaced the content of `environment-variables.md` with `env-vars-overview.md` and removed `env-vars-overview.md`, to reduce the number of redirects required.

2023-10-26 09:14 UTC, jwitz requested changes
I think some of my feedback around Astro CLI use got buried from the previous edits, @lzdanski let me know if you want to meet and discuss those ideas further. Will do a full review after those comments are addressed one way or another

2023-10-26 09:14 UTC, jwitz commented on astro/env-vars-astro.md
> +## With Astro CLI
I still think this section should be either removed or converted to a tip within the Cloud UI section. This is not an env var management strategy, this is instead an alternative way to automate changes to variables in the Cloud UI. It's not parallel to the other H2s

2023-10-26 09:14 UTC, jwitz commented on astro/environment-variables.md
> +| You want to ensure all the environment variables defined in the Cloud UI are checked-in to the code repository and bundled in an Astro project before you promote your code from a lower environment
I think some of my previous review comments got buried for this section. I had a previous comment that asked why we were mentioning the Cloud UI here when our recommendation is Dockerfile

2023-10-27 14:02 UTC, jwitz commented on astro/environment-variables.md
> +| Your team has dev/prod/staging environments and you use various environment variables to customize your Airflow environment.
```suggestion
| You want to standardize a core set of Airflow environment configurations across multiple environments.                                                                                                                                                | [`Dockerfile`](env-vars-astro.md#using-your-dockerfile) to have a file that serves as a source of truth and starting point for all environments.                                                                                                                                                                |
```
> use various environment variables to customize your Airflow environment.
That sounds like the use case for all environment variables. Also how does using the Dockerfile keep various environments in sync? I think I understand what this means, tried to reword to better identify the true value add here.

2023-10-27 14:05 UTC, jwitz commented on astro/environment-variables.md
> +| You want to ensure all the environment variables defined in the Cloud UI are checked-in to the code repository and bundled in an Astro project before you promote your code from a lower environment
```suggestion
| You want to use version control to manage your environment variables from a code repository. | [`Dockerfile`](env-vars-astro.md#using-your-dockerfile) to version control your environment configuration.                                                                                                                                                        |
| You want to carry over environment variables when you promote code from a development environment to a production environment. | [`Dockerfile`](env-vars-astro.md#using-your-dockerfile) to deploy environment variables from project code using CI/CD.                                                                                                                                                        |
```

2023-10-27 14:05 UTC, jwitz commented on astro/environment-variables.md
> +| Your are part of a production support team analyzing DAG failures and want to turn on Debug logging temporarily.
```suggestion
| You are part of a production support team analyzing DAG failures and want to turn on debugging-related environment variables temporarily.                                                                                                                                                             | [Cloud UI](env-vars-astro.md#using-the-cloud-ui) for ease of use.                                                                                                                                                                                                 |
```

2023-10-27 14:06 UTC, jwitz commented on astro/environment-variables.md
> +| You develop DAGs locally with a new source, and want to use a secret credential in these DAGs.
```suggestion
| You're developing locally, and you want to use a secret credential in your DAGs.                                                                                                                                                                               | [Use the `.env` file](env-vars-astro.md#using-astro-cli) locally. This allows you to avoid accidentally sending credentials to your code repository because `.env` is part of `.gitignore`. You can then export the `.env` file to your Deployment using the Astro CLI. |
```

2023-10-27 14:09 UTC, jwitz commented on astro/environment-variables.md
> +| You want the features of the Cloud UI for environment variables, but you also keep track of the non-secret environment variables in your code repository.
```suggestion
| You want the features of the Cloud UI for environment variables, but you also keep track of the non-secret environment variables in your code repository.                                                                                                                    | Use the [Astro CLI](env-vars-astro.md#in-your-astro-deployment) and an automation script to add or update the non-secret environment variables in your Deployment from your code repository.                                                                     |
```

2023-10-27 14:09 UTC, jwitz commented on astro/import-export-connections-variables.md
> +- To export all Airflow objects from your local Airflow, including connections and variables, to an `.env` file in URI format, run:
```suggestion
- To export all Airflow objects from your local Airflow environment, including connections and variables, to an `.env` file in URI format, run:
```

2023-10-27 14:11 UTC, jwitz commented on astro/environment-variables.md
> +Environment variables are fundamentally used to customize your Airflow environment on Astro to take advantage of different performance, behavior, and connection options available. In order to choose
```suggestion
Environment variables can be used in many different contexts on Airflow. To choose the right management and implementation strategy for your specific use case, you must understand the available management options, how Astro prioritizes environment variables, and how Astro stores them. 
```

2023-10-27 14:12 UTC, jwitz commented on astro/environment-variables.md
> +Some scenarios where you might use custom environment variables for your Deployment include:
```suggestion
Some scenarios where you might use environment variables in your Deployment include:
```

2023-10-27 14:12 UTC, jwitz commented on astro/env-vars-astro.md
> +## With the Cloud UI
```suggestion
## Using the Cloud UI
```

2023-10-27 14:12 UTC, jwitz commented on astro/env-vars-astro.md
> +## With your Dockerfile
```suggestion
## Using your Dockerfile
```

2023-10-27 14:13 UTC, jwitz commented on astro/env-vars-astro.md
> +1. Go to your Astro project and open the `Dockerfile`.
```suggestion
1. Open your Astro project `Dockerfile`.
```

2023-10-27 14:13 UTC, jwitz commented on astro/env-vars-astro.md
> +3. After you add your environment variables, use the `astro deploy` command to apply your changes to your Deployment on Astro. To apply your changes locally, use `astro dev restart` to rebuild your i
```suggestion
3. Save your Dockerfile and run `astro deploy` to deploy your variables to an Astro Deployment. To apply your changes locally, use `astro dev restart` to rebuild your image.
```

2023-10-27 14:15 UTC, jwitz commented on astro/env-vars-astro.md
> +If your environment variables contain sensitive information or credentials that you don’t want to expose in plain-text, ensure that your `.env` file is part of `.gitignore` when you deploy these chan
```suggestion
You can use Astro CLI to set environment variables on Astro and your local Airflow environment. If you're developing locally, the best way to manage environment variables is using your Astro project `.env` file.
```

2023-10-27 14:15 UTC, jwitz commented on astro/env-vars-astro.md
> +1. Go to your Astro project and open the `.env` file.
```suggestion
1. Open your Astro project `.env` file.
```

2023-10-27 14:15 UTC, jwitz commented on astro/env-vars-astro.md
> +#### With multiple .env files
```suggestion
### Use multiple .env files
```

2023-10-27 14:16 UTC, jwitz commented on astro/env-vars-astro.md
> +
```suggestion
```

2023-10-27 14:22 UTC, jwitz commented on astro/env-vars-astro.md
> +
````suggestion
To export the contents of your `.env` file to an Astro Deployment, run the following command:

```bash
astro deployment variable update --deployment-id <your-deployment-id> --load .env
```

:::caution

When you use the`.env` file to add or update environment variables on Astro, it will overwrite all existing variables in your Astro Deployment. To update only select environment variables, run the `astro deployment variable create` command without the `--load` option. For example, the following command creates two new environment variables without affecting existing Deployment environment variables:

```bash
astro deployment variable create AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60 ENVIRONMENT_TYPE=dev --deployment-id cl03oiq7d80402nwn7fsl3dmv
```
:::

After you deploy environment variables, your Deployment automatically restarts to and applies the variables. To verify if the environment variables were applied correctly, go to the **Variables** tab of your Deployment in the Cloud UI. 
````

2023-10-27 14:22 UTC, jwitz commented on astro/env-vars-astro.md
> +
I moved this section up and condensed it so that it fit more nicely with the core `.env` management content.

2023-10-27 14:26 UTC, jwitz commented on astro/env-vars-astro.md
> +:::
```suggestion
```

2023-11-01 16:28 UTC, lzdanski commented on astro/environment-variables.md
> +For example, if you have set `AIRFLOW__CORE__PARALLELISM` in your `Dockerfile` but want to use a different value for testing, you can define the same in the Cloud UI to override the original value in
I feel like this is an important detail to include - any reason to remove it? I don't think we have this change in the other doc with more specific CLI info

2023-11-01 16:28 UTC, lzdanski commented on astro/environment-variables.md
> +For example, if you have set `AIRFLOW__CORE__PARALLELISM` in your `Dockerfile` but want to use a different value for testing, you can define the same in the Cloud UI to override the original value in
I see it now!

2023-11-02 10:23 UTC, jwitz commented on astro/env-vars-astro.md
> +sidebar_label: 'Edit environment variables'
I understand that we dont want to have "Manage" in the sidebar, but I also think we need to keep the verbs consistent between the sidebar and pages. Maybe one of those "know the rules so you can break them" instances?

2023-11-02 10:25 UTC, jwitz commented on astro/env-vars-astro.md
> +    3. Run `exit` to exit the container.
```suggestion
```

2023-11-02 10:28 UTC, jwitz commented on astro/env-vars-astro.md
> +### Use multiple .env files
```suggestion

### Use multiple .env files
```

2023-11-02 10:30 UTC, jwitz commented on astro/env-vars-astro.md
> +## Using the Cloud UI
```suggestion
## Using the Cloud UI

Setting environment variables using the Cloud UI is the quickest and easiest way to manage environment variables on Astro.
```

2023-11-02 10:31 UTC, jwitz commented on astro/env-vars-astro.md
> +After you set an environment variable key, only the environment variable value can be modified. While you can modify environment variables that are set as **Secret**, however, the secret variable val
```suggestion
After you set an environment variable key, only the environment variable value can be modified. You can modify environment variables that are set as **Secret**, but the existing secret variable value is never shown. When you modify a secret environment variable, the existing value is erased and you are prompted to enter a new value.
```

2023-11-02 10:42 UTC, jwitz commented on astro/env-vars-astro.md
> +    - Using Astro CLI commands `astro deployment variable create` and `astro deployment variable update`
```suggestion
On Astro, you can create, update, or delete environment variables for a Deployment in the following ways:

- Using the Deployment's **Variables** tab in the Cloud UI.
- Using your Astro project `Dockerfile`.

The way you manage environment variables can affect security and access for your variable data. See [Choose a strategy](environment-variables.md#choose-a-strategy) to determine which management strategy is right for your use case.

Additionally, you can test environment variables from your local Astro environment and export them to the Cloud UI. See [Manage environment variables locally](#manage-environment-variables-locally).
```

2023-11-02 10:44 UTC, jwitz commented on astro/environment-variables.md
> +Environment variables can be used in many different contexts on Airflow. To choose the right management and implementation strategy for your specific use case, you must understand the available manag
```suggestion
Environment variables can be used in many different contexts on Airflow. To choose the right management and implementation strategy for your specific use case, it's helpful to know how Astro prioritizes and stores environment variables for each available management option.
```

2023-11-02 10:49 UTC, jwitz commented on astro/env-vars-astro.md
Sorry to have to switch the links up again, but I feel strongly that `env-vars-astro` and `environment-variables` are too similar. Maybe `edit-environment-variables` instead? Or `env-vars-overview` and `environment-variables`

2023-11-02 10:51 UTC, jwitz commented on astro/environment-variables.md
> +- Customizing your DAG flows by identifiyng a production Deployment versus a development Deployment
```suggestion
- Specifying a tag that's added to all resources created by the Deployment and indicates whether a resource is for development or production.
```

2023-11-02 10:51 UTC, jwitz commented on astro/environment-variables.md
> +- Integrating with Datadog or other third-party tooling to [export Deployment metrics](deployment-metrics.md#export-airflow-metrics-to-datadog)
```suggestion
- Adding a token or a URL that is required by your Airflow DAGs or tasks.
- Integrating with Datadog or other third-party tooling to [export Deployment metrics](deployment-metrics.md#export-airflow-metrics-to-datadog).
```

2023-11-02 10:51 UTC, jwitz commented on astro/environment-variables.md
> +Similarly, in local development, environment variables set in your `.env` file take precedence over environment variables set in your Dockerfile.
```suggestion
Similarly, in local development, environment variables set in your `.env` file take precedence over environment variables set in your Dockerfile.

```

2023-11-02 10:53 UTC, jwitz commented on astro/environment-variables.md
> +- Your Astro project [`Dockerfile`](env-vars-astro.md#using-your-dockerfile). Storing environment variables in your Dockerfile allows you to manage them as code in a version control tool like GitHub.
```suggestion
- Your Deployment's **Variables** tab in the Cloud UI. This is the fastest and easiest way to set an environment variable. See [Using the Cloud UI](env-vars-astro.md#using-the-cloud-ui) for setup steps.
- Your Astro project `Dockerfile`. Storing environment variables in your Dockerfile allows you to manage them as code in a version control tool like GitHub. However, environment variables stored in the Dockerfile do not appear in the Cloud UI and might be harder to reference from DAG code.  Using the Dockerfile is recommended for more complex production use cases, such as implementing a secrets backend. See [Using your Dockerfile](env-vars-astro.md#using-your-dockerfile) for setup steps. 
```
Small nit, the hyperlinks appear to link to an object, but really just link to a doc about the object.

2023-11-02 10:55 UTC, jwitz commented on astro/environment-variables.md
> +| You use environment variables to store your Airflow connections and variables, and have to configure these from one Deployment to another based on the environment type.
```suggestion
| You use environment variables to store your Airflow connections and variables, and you have to reconfigure these between Deployments based on the environment type.                                                                                                     | [Cloud UI](env-vars-astro.md#using-the-cloud-ui) for visibility.                                                                                                                                                                                                  |
```

2023-11-02 10:57 UTC, jwitz commented on astro/environment-variables.md
> +### Storing environment variables in the Cloud UI
```suggestion
### How environment variables are stored in the Cloud UI
```
Current title sounds more like an action item.

2023-11-02 10:57 UTC, jwitz commented on astro/environment-variables.md
> +### Recommended methods
```suggestion
### Example use cases
```

2023-11-02 10:58 UTC, jwitz commented on astro/environment-variables.md
> +There are some scenarios when you might want to use a mix of methods or strategies other than the Cloud UI. The following table describes recommended methods for these different scenarios.
```suggestion
There are some scenarios when you might want to use a mix of methods or strategies other than the Cloud UI. The following table prescribes specific methods for various common use cases.
```

2023-11-02 10:58 UTC, jwitz commented on astro/environment-variables.md
> +- It has built in security for secret environment variables.
```suggestion
- It has built-in security for secret environment variables.
```

2023-11-02 14:12 UTC, lzdanski commented on astro/env-vars-astro.md
I'm good with `edit-environment-variables`, but I would _not_ recommend changing `environment-variables`. That link is baked into our docs in so many places, we'd need to follow up outside of this PR with that update. I'm afraid of adding that many more file changes to this PR

2023-11-21 21:07 UTC, lzdanski commented on astro/manage-connections-variables.md
> +- You can override Airflow variables set in the Airflow UI. See [Environment variable priority](environment-variables.md#ways-to-manage-environment-variables-on-astro)
env vars priority links are going to right page but not section

2023-11-21 21:12 UTC, lzdanski commented on astro/platform-variables.md
>  This document is a reference for all environment variables on Astronomer with different default values than open source Apache Airflow. You can override [default Runtime environment variables](#defau
Default runtime env vars are in /astro/runtime-image-architecture#default-environment-variables

2023-11-22 14:34 UTC, merged