Add teams with the CLI
astronomer/docs pull request #2822
Opened 2023-09-08 20:23 UTC by lzdanski

Resolves #2818 

Related to https://github.com/astronomer/astro-cli/pull/1381

Based the code examples on [Add users to multiple workspaces](https://docs.astronomer.io/astro/manage-organization-users#add-a-group-of-users-to-astro-using-the-astro-cli), so the code examples need a close check - I don't have access to multiple workspaces with possible teams to double check.

2023-09-08 21:44 UTC, lzdanski commented on astro/manage-teams.md
> +    ```
I made these up based on the example in https://docs.astronomer.io/astro/cli/astro-workspace-team-add.

2023-09-12 10:38 UTC, manmeetkaur requested changes
Thanks @lzdanski some updates based on the testing of this command. Software is out of scope for this, so removed those changes :) It is confusing!

2023-09-12 10:38 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +
Note sure where to add this, but I tested this command and it happens to me.
```suggestion
To find a Workspace ID using the Astro CLI, run `astro workspace list`.

If you want to add a team to the current Workspace with the default role of Workspace Member, you can also run `astro workspace team add`. This command lists the available Teams in your Orgranization and prompts you to enter the serial number for team you want to add.

```

2023-09-12 10:38 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +astro workspace team add <team-id> <role> <workspace-id>
I think the norm for the topmost command is the default command. Referring to `astro deploy` here. And the reason is, astro workspace team add also works just fine . I have added detail in the comment below.
```suggestion
astro workspace team add <options>
```

2023-09-12 10:38 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +| `--role`         | The Team's role in the Workspace.                | Possible values are `WORKSPACE_MEMBER`, `WORKSPACE_AUTHOR`, `WORKSPACE_OPERATOR`, or `WORKSPACE_OWNER`. Default is `WORKSPACE_M
```suggestion
| <team-id>             | Specifies the Team ID to add to a Workspace and bypasses the Team selection prompt | Any valid Team ID |
| `-r`, `--role`         | The Team's role in the Workspace.                | Possible values are `WORKSPACE_MEMBER`, `WORKSPACE_AUTHOR`, `WORKSPACE_OPERATOR`, or `WORKSPACE_OWNER`. Default is `WORKSPACE_MEMBER`. |
```

2023-09-12 10:38 UTC, manmeetkaur commented on astro/cli/astro-workspace-team.md
> +`astro workspace team add --team-id=<team-id> --role=<workspace_level_role> --workspace-id=<workspace-id>`
These changes are not applicable to Software. https://astronomer.slack.com/archives/CL44PA4DB/p1694514088168129?thread_ts=1694181978.959069&cid=CL44PA4DB
```suggestion
`astro workspace team add --team-id=<team-id> --role=<workspace_level_role>`
```

2023-09-12 10:38 UTC, manmeetkaur commented on astro/cli/astro-workspace-team.md
> +| `--workspace-id`         | The Workspace ID where you want to add the Team. | Any valid Workspace ID. Default is the current Workspace context you are working in.
```suggestion
```

2023-09-12 10:38 UTC, manmeetkaur commented on astro/manage-teams.md
> +    done < "$1"
`-` has a special meaning in bash and either needs to be escaped or we can use something else. also `team-id` does not need a flag to be passed. I tested the below code (without the workspace-id because it is not released yet), it works.
```suggestion
    while read line; do
        team_id=$(echo "$line" | cut -d' ' -f1)
        role=$(echo "$line" | cut -d' ' -f2)
        workspace_id=$(echo "$line" | cut -d' ' -f3)
        echo "Inviting ${team_id} to ${workspace_id} as $role..."
        astro workspace team add "$team_id" --role "$role" --workspace-id "$workspace_id
    done < "$1"
```

2023-09-12 17:34 UTC, lzdanski commented
@manmeetkaur - added your suggestions and made a formatting change to address the Software/Astro distinction!

2023-09-15 07:46 UTC, manmeetkaur approved these changes
LGTM just small changes.

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +:::
```suggestion
:::info

The behavior and format of this command differs depending on what Astronomer product you're using. Use the following tabs to change between product contexts.

:::

Add a Team to your current Workspace and grant it a Workspace role.
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +:::info
missing imports 
```suggestion
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

:::info
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +<TabItem value="astro">
small nitpick
```suggestion
<Tabs
    defaultValue="astro"
    values={[
        {label: 'Astro', value: 'astro'},
        {label: 'Software', value: 'software'},
    ]}>
<TabItem value="astro">
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +If you want to add a team to the current Workspace with the default role of Workspace Member, you can also run `astro workspace team add`. This command lists the available Teams in your Orgranization
just some reordering
```suggestion
If you want to add a team to the current Workspace with the default role of Workspace Member, you can also run `astro workspace team add`. This command lists the available Teams in your Orgranization and prompts you to enter the serial number for team you want to add. 

If you want to add a team to a specific Workspace, you can use the `--workspace-id` flag. To find a Workspace ID, run `astro workspace list`.
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +- To find a Team ID in the Cloud UI, click your Workspace name, then click **Organization Settings** > **Access Management** > **Teams**. Search for your Team in the **Teams** table and copy its **ID
I feel like this should be after the table ? because till now, we have not introduced the option `team-id`

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +If you want to add a team to the current Workspace with the default role of Workspace Member, you can also run `astro workspace team add`. This command lists the available Teams in your Orgranization
```suggestion
Add a Team to your current Workspace and grant it a Workspace role.
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +Add a Team to a Workspace.
```suggestion
```

2023-09-15 07:46 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +Add a Team to a Workspace.
this section might not be required now.

2023-09-20 16:55 UTC, jwitz commented on astro/manage-teams.md
> +    ```
Tip for future UID examples: All RBAC entity IDs are UUIDs, which you can generate at this handy site: https://www.getuniqueid.com/cuid

2023-09-21 06:58 UTC, manmeetkaur commented on astro/cli/astro-workspace-team-add.md
> +- Run `astro workspace team list` and copy the value in the ID column
oh you mean for Software? may be, I  don't have access to a Software setup as of now.

2023-09-21 13:11 UTC, lzdanski commented on astro/manage-teams.md
> +    ```
Added to our style guide

2023-09-21 17:23 UTC, jwitz requested changes
Script update LGTM! Requesting changes bc there seems to be some unrelated commits to the reference docs.

2023-09-21 17:23 UTC, jwitz commented on astro/cli/astro-workspace-team-add.md
> +You can retrieve a Team's ID in one of two ways:
I don't love having this outside of the possible options since it only pertains to one option. Could we add this to the "Valid Values" table instead as a brief sentence?

2023-09-21 17:23 UTC, jwitz commented on astro/cli/astro-workspace-team-add.md
> +astro workspace team <options>
Did we confirm whether the behavior is identical on Software? There are quite a few commands that have autoprompts on Astro but not on Software.

2023-09-21 17:23 UTC, jwitz commented on astro/cli/astro-workspace-team.md
> -#### astro workspace team remove
Looks like we didn't have a replacement for this one?

2023-09-21 17:23 UTC, jwitz commented on astro/manage-teams.md
> +2. Open the text file. On each line, add a Team ID, the role, and the Workspace ID. The following is an example of how you can write a list for assigning Teams to multiple Workspaces:
```suggestion
2. Open the text file. On each line, add a Team ID, the Team's role, and the Workspace ID delimited by spaces. Your text file should look similar to the following:
```

2023-09-21 17:23 UTC, jwitz commented on astro/cli/astro-workspace-team.md
> -astro workspace team remove <team-id> --workspace-id <workspace-id>
Looks like this got deleted without getting replaced

2023-09-27 18:26 UTC, lzdanski commented on astro/cli/astro-workspace-team-add.md
> +astro workspace team <options>
reverting back to what we previously had in the docs for software.

2023-09-27 18:28 UTC, lzdanski commented on astro/cli/astro-workspace-team.md
> -#### astro workspace team remove
This was already documented, but not extensively: https://docs.astronomer.io/astro/cli/astro-workspace-team-remove

2023-09-27 18:30 UTC, lzdanski commented on astro/cli/astro-workspace-team.md
> -astro workspace team remove <team-id> --workspace-id <workspace-id>
Updated existing doc with this information

2023-09-27 19:55 UTC, jwitz requested changes
Looks like there are a couple of commands that might need tabs due to the changed behavior btw Astro and Software, but other than that LGTM

2023-09-27 19:55 UTC, jwitz commented on astro/cli/astro-workspace-team-remove.md
> +| `--workspace-id` (_Required_) | The Workspace for the Team | Any valid Workspace ID |
```suggestion
| ----------------------------- | -------------------------- | ---------------------- |
| `<team-id>` | The ID for the Team. Use to override CLI prompts. | Ant valid Team ID. To retrieve a Team ID, run `astro workspace list`. |
| `--workspace-id` | The Workspace for the Team | Any valid Workspace ID |
```

2023-09-27 19:55 UTC, jwitz commented on astro/cli/astro-workspace-team-remove.md
> +| `--workspace-id` (_Required_) | The Workspace for the Team | Any valid Workspace ID |
This looks like it was copied from Software, but these options are different on Astro. Workspace ID nor Team ID are required - the CLI automatically prompts you for them.

This command is missing help text from the CLI, hence the confusion around its usage - I think that my edits here should be correct for Astro.

2023-09-27 19:55 UTC, jwitz commented on astro/cli/astro-workspace-team-remove.md
> +| `--workspace-id` (_Required_) | The Workspace for the Team | Any valid Workspace ID |
So in conclusion, we might need to add tabs here like we did for `team add`

2023-09-27 19:55 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +| `--workspace-id` (_Required_) | The Workspace for the Team        | Any valid Workspace ID                                                            |
Same here, none of these values are required for Astro, but are for Software. We just need to keep the existing docs and add a tab for the content that existed in `astro-workspace-team.md`

2023-09-29 15:19 UTC, jwitz approved these changes
LGTM!

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +
```suggestion
<TabItem value="astro">

#### Usage

```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +## Usage
```suggestion
#### Usage
```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-add.md
> +#### Usage
```suggestion
## Usage
```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +## Options
```suggestion
#### Options
```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
>  ## Options
```suggestion
#### Options
```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +### Related documentation
```suggestion
#### Related documentation
```

2023-09-29 15:19 UTC, jwitz commented on astro/cli/astro-workspace-team-update.md
> +### Related documentation
```suggestion
#### Related documentation
```

2023-09-29 15:19 UTC, jwitz commented on astro/manage-teams.md
> +6. (Optional) To use this script as part of a CI/CD pipeline, create an [Organization API token](organization-api-tokens.md) and specify the environment variable `ASTRO_API_TOKEN=<your-token>` in you
```suggestion
6. (Optional) To use this script as part of a CI/CD pipeline, create an [Organization API token](organization-api-tokens.md) and specify the following environment variable in your CI/CD environment:

    - **Key**:  `ASTRO_API_TOKEN`
    - **Value**: `<your-api-token>`
```

2023-09-29 16:40 UTC, lzdanski commented on astro/cli/astro-workspace-team-remove.md
> +#### Options
```suggestion
### Options
```

2023-09-29 16:40 UTC, lzdanski commented on astro/cli/astro-workspace-team-remove.md
> +#### Options
```suggestion
### Options
```

2023-09-29 16:41 UTC, lzdanski commented on astro/cli/astro-workspace-team-add.md
>  ## Options
```suggestion
#### Options
```

2023-09-29 16:59 UTC, lzdanski commented on astro/cli/astro-workspace-team-update.md
> +#### Usage
```suggestion
## Usage
```

2023-09-29 17:03 UTC, merged