Add disambiguation about custom registries for Software
astronomer/docs pull request #2835
Opened 2023-09-12 18:12 UTC by lzdanski

#2803 

Added notes to each identified doc to redirect to correct content.

2023-09-12 18:13 UTC, lzdanski commented
@ReadytoRocc - In our original thread, you provided the clarification. I adapted your comments a little, but wanted to check to make sure I got the right explanations matched to the correct docs!

2023-09-18 20:42 UTC, jwitz requested changes
One question about the note in the Airgapped doc, otherwise LGTM!

2023-09-18 20:42 UTC, jwitz commented on software/custom-image-registry.md
> +Because these directions allow you to create a custom-managed registry for your Astronomer images, this procedure is different from preparing for installing Astronomer in an airgapped environment. If
```suggestion
A custom registry can still connect to public networks or internet. Therefore, this procedure is different if you're installing Astronomer in an airgapped environment. If you need to create a custom registry for a system that can't connect to the public networks or internet, see [Install Astronomer in an airgapped environment](install-airgapped.md).
```
I didn't quite understand the "Because" statement here - how are the steps themselves making the procedure different for an airgapped environment? - so I moved the bit about the public internet connections to the note

2023-09-18 20:42 UTC, jwitz commented on software/custom-image-registry.md
> +If your organization can't support the Astronomer default internal registry, you can configure a custom container image registry. This option is best suited for organizations who require additional c
```suggestion
If your organization can't support the Astronomer default internal registry, you can configure a custom container image registry. This option is best suited for organizations who require additional control for security and governance reasons. Using a custom registry provides your organization with the opportunity to scan images for CVEs, malicious code, and unapproved Python and OS-level packages contained in Docker images.
```

2023-09-18 20:42 UTC, jwitz commented on software/install-airgapped.md
> +:::note
```suggestion
:::info
```

2023-09-18 20:42 UTC, jwitz commented on software/install-airgapped.md
> +If you have some means to allow traffic to the public internet, e.g. a proxy that allows a list of accepted destinations/sources, that will make the airgapped installation much easier. This page assu
```suggestion
If you have some means to allow traffic to the public internet, such as a proxy that allows a list of accepted destinations/sources, that will make the airgapped installation much easier. This page assumes an environment without any possibility of accessing the public internet.
```
What's the purpose of this note? How is a user supposed to act on this information?

2023-09-18 20:42 UTC, jwitz commented on software/registry-backend.md
> +:::note
```suggestion
:::info
```

2023-09-18 20:42 UTC, jwitz commented on software/registry-backend.md
> +This document explains only how to set up a registry for hosting Astronomer's system images. To create a custom registry for Deployment images, see [Configure a custom image registry for Deployment i
```suggestion
This document explains only how to set up a registry for hosting Astronomer's system images. To create a custom registry for Deployment images, see [Configure a custom image registry for Deployment images](custom-image-registry.md). Or, to host all images in a high-security environment with no connections to public networks or internet, see [Install Astronomer in an airgapped environment](install-airgapped.md).
```

2023-09-25 19:42 UTC, jwitz commented on software/install-airgapped.md
> +If you have some means to allow traffic to the public internet, e.g. a proxy that allows a list of accepted destinations/sources, that will make the airgapped installation much easier. This page assu
I get that context, I guess I feel uneasy about saying "There's a much easier way to do this, but we don't have that documented".

In my Software experience, there hasn't been a demand for content related to a semi-airgapped install yet. And Software install docs tend to be worked through by an Astro team member and a Software customer side-by-side. If there is a demand for a different install experience, I'd prefer we document it rather than make a suggestion towards it.

2023-09-27 15:22 UTC, lzdanski commented on software/install-airgapped.md
> +If you have some means to allow traffic to the public internet, e.g. a proxy that allows a list of accepted destinations/sources, that will make the airgapped installation much easier. This page assu
Actually let's just remove it! I agree with your suggestion. going to add it now 👍

2023-09-27 19:38 UTC, jwitz commented on software/install-airgapped.md
> +:::
```suggestion
```

2023-09-27 19:38 UTC, jwitz approved these changes

2023-09-27 19:47 UTC, merged