Office Hours
astronomer/docs pull request #2851
Opened 2023-09-15 17:02 UTC by fritz-astronomer

2023-09-15 19:14 UTC, lzdanski reviewed
This new doc looks great, @fritz-astronomer! I did a copy editing review. If you're still working on things, just let me know when you're ready for me to do a final review.

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +*Office hours are not a replacement for support!* Please [submit a support request](astro-support.md) if you have any urgent issue, bug, or something that needs fixing. We will not be able to assist
```suggestion
**Office hours are not a replacement for support!** 

Please [submit a support request](astro-support.md) if you have any urgent issue, bug, or something that needs fixing. We will not be able to assist you with these topics during office hours sessions.
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +Please ensure to first browse the content of our documentation, the [Astronomer Academy](https://academy.astronomer.io/), our [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the
```suggestion
Before your office hours appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources for what you would like to discuss. 

You can also email [success@astronomer.io](mailto:success@astronomer.io) if you have general account related questions. However, if you need more extensive assistance, guidance, or regular long-term engagement - please talk to our [Professional Services](https://www.astronomer.io/professional-services/) team.
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +## Topics
```suggestion
## Example Topics
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +
```suggestion
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +## Booking Office Hours
```suggestion
## Book Office Hours
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +You will be able to book office hours in the top right `(?)` menu on [cloud.astronomer.io](https://cloud.astronomer.io) or in the bottom left of our [docs](https://docs.astronomer.io/astro).
Screen reader language fix - which is super tricky! In docs, we use the tool tips/hover text instead of the icon symbol when describing where to click and beginning/end/before/after as directions instead of left/right/up/down. 
```suggestion
Book office hours by clicking the **Help** menu in the [Cloud UI](https://cloud.astronomer.io) or **Book office hours** at the end of the [docs navigation menu](https://docs.astronomer.io/astro).
```

2023-09-15 19:14 UTC, lzdanski commented on astro/office_hours.md
> +These sessions are typically 30 minutes in duration and are available weekly on a first-come-first-serve basis.
```suggestion
Office hours are a new way for Astro customers to meet with our team of talented Data Engineers.
These sessions are typically 30 minutes in duration and available weekly on a first-come-first-serve basis.
```

2023-09-15 19:23 UTC, fritz-astronomer commented
@lzdanski My pass was real fast, but good 'nuf, I figured we can make it better as long as it exists at all. 
I'll add your changes, thanks for that.

2023-09-19 19:17 UTC, jwitz requested changes
Looks good @fritz-astronomer ! Just had one question about a step we tell users to take, but other than that the content looks ready

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +title: 'Book Office Hours'
```suggestion
title: 'Book Astro office hours'
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +navTitle: 'Astro Office Hours'
```suggestion
navTitle: 'Office hours'
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +description: Attend Office Hours with our team of Data Engineers
```suggestion
description: Attend office hours with Astronomer data engineers to ask non-support questions about Airflow.
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
Can you rename the file to `office-hours.md`? That's the format for our other files

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +These sessions are typically 30 minutes in duration and available weekly on a first-come-first-serve basis.
```suggestion
Office hours are a way for you to meet with Astronomer data engineers and ask about Astro and Airflow features and best practices . Office hours are available weekly on a first-come, first-served basis. An office hour session is typically 30 minutes long. 
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +**Office hours are not a replacement for support!**
```suggestion
Office hours are not a replacement for support. [Submit a support request](astro-support.md) if you have any urgent issue, bug, or something that needs fixing. Astronomer data engineers will not be able to answer support requests during office hour sessions.

If you have questions about your Astronomer account or billing, email `success@astronomer.io` instead of attending office hours. If you need more extensive assistance, guidance, or regular long-term engagement, reach out to the [Professional Services](https://www.astronomer.io/professional-services/) team.
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +Please [submit a support request](astro-support.md) if you have any urgent issue, bug, or something that needs fixing. We will not be able to assist you with these topics during office hours sessions
```suggestion
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +Before your office hours appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the
```suggestion
Before an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources that cover what you'd like to discuss. 
```
Not sure what the purpose of this request is. Do we want them to cancel their meeting if they find what they're looking for, or is this just so they can share more context for the meeting?

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +You can also email [success@astronomer.io](mailto:success@astronomer.io) if you have general account related questions. However, if you need more extensive assistance, guidance, or regular long-term
```suggestion
```

2023-09-19 19:17 UTC, jwitz commented on static/img/docs/office_hours.png
Super small nit, but it'd be great if the office hours element was highlighted here instead of View Documentation.

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +Book office hours by clicking the **Help** menu in the [Cloud UI](https://cloud.astronomer.io) or **Book office hours** at the end of the [docs navigation menu](https://docs.astronomer.io/astro).
```suggestion
## Book an office hours appointment 

To book office hours, click **Help** > **Book Office Hours** in the [Cloud UI](https://cloud.astronomer.io). Alternatively, you can click **Book office hours** in the left sidebar of this page.
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +![A screenshot showing the menu in cloud.astronomer.io which contains a Book Office Hours entry](/img/docs/office_hours.png)
```suggestion
![A screenshot showing the menu in cloud.astronomer.io which contains a Book Office Hours entry](/img/docs/office_hours.png)

Before an office hour appointment, take a moment to browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources that cover what you'd like to discuss. 
```
Alternative location for this info, seems to fit better here because it's what we suggest after you book the appointment.

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +
```suggestion
```

2023-09-19 19:17 UTC, jwitz commented on astro/office_hours.md
> +- Conduct a Code Review for a DAG
```suggestion
During an office hours meeting, you can:

- Ask questions about Airflow features.
- Discuss new Astro features or provide feedback.
- Get insight on integrating Airflow with new systems.
- Do an architecture review or discuss scaling Airflow and Astro Deployments .
- Conduct a code review for a DAG.
```

2023-09-20 16:48 UTC, fritz-astronomer commented on astro/office_hours.md
> +Before your office hours appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the
If they can answer their question without needing to book, they should :)

2023-09-25 20:29 UTC, jwitz commented on astro/office-hours.md
> +Before an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [As
```suggestion
```

2023-09-25 20:29 UTC, jwitz commented on astro/office-hours.md
> +
```suggestion

Before booking an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources that answer your question. 

```

2023-09-25 20:29 UTC, jwitz commented on astro/office-hours.md
> +Before booking an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on
```suggestion
Before you book an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources that answer your question. 
```

2023-09-25 20:30 UTC, jwitz approved these changes

2023-09-25 20:31 UTC, jwitz commented
LGTM @fritz-astronomer , I just moved the statement about reading other materials. Do you need review from anyone else requested here before I merge?

2023-09-25 20:48 UTC, fritz-astronomer commented
good to go @jwitz

2023-09-25 21:29 UTC, merged