Add podman troubleshooting
astronomer/docs pull request #2854
Opened 2023-09-15 19:54 UTC by lzdanski

Resolves #2845 

@jwitz - thoughts about the tip placement for CLI docs and troubleshooting in **Configure the CLI**?

@nsAstro - Can you please double check that the dockerfile code example I included is formatted correctly for the resolution part?

2023-09-18 20:13 UTC, jwitz requested changes
I added some comments based on how I understood the linked Slack threads. Love the placement of the note in the Podman docs, but it could be overkill in the CLI reference docs? If I get the error, I'm more likely to search for the error text than search the CLI reference docs for troubleshooting config. It would also help us to have a single source of truth in case this changes in the future. 

If you want to keep the note in the CLI docs, I would replace the full troubleshooting step with a link to the troubleshooting Podman docs, saying something like "The functionality of this command might be affected if you use Podman. See [Troubleshoot topic] for more information." This is just my opinion, don't feel strongly if you want to keep it, but wanted to throw it out there as an idea

2023-09-18 20:13 UTC, jwitz commented on astro/cli/configure-cli.md
> +### Troubleshoot your configuration
```suggestion
### Troubleshoot your Podman configuration
```

2023-09-18 20:13 UTC, jwitz commented on astro/cli/configure-cli.md
> +Sometimes, after you configure Podman, the following error occurs when Astro tries to build container images when running `astro deploy` or `astro dev start`.
```suggestion
The following error can sometimes occur when the CLI tries to build your Astro Runtime image using Podman:
```

2023-09-18 20:13 UTC, jwitz commented on astro/cli/configure-cli.md
> +```
````suggestion

```bash
WARN[0010] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -e -u -x -c] will be ignored. Must use `docker` format 
```

To resolve this issue, run the following command to set the `BUILDAH_FORMAT` environment variable on your machine:

```dockerfile
export BUILDAH_FORMAT=docker
```
````

2023-09-18 20:13 UTC, jwitz commented on astro/cli/configure-cli.md
> +```
From the original Slack context, I think this configuration is local only, even when you're building an image to deploy to Astro.

2023-09-18 20:13 UTC, jwitz commented on astro/cli/astro-dev-start.md
> +:::tip
```suggestion
:::info
```
We should also change the note level in the other troubleshooting topic in `configure-cli`, not sure why that one's a tip

2023-09-18 20:13 UTC, jwitz commented on astro/cli/astro-dev-start.md
> +If you see the following error when using `astro deploy` and you configured your CLI to work with [Podman](cli/configure-cli.md), you might need to set an additional environment variable to correctly
Same edits here as in the other notes.

2023-09-18 20:13 UTC, jwitz commented on astro/cli/astro-deploy.md
> +:::tip
```suggestion
:::info
```

2023-09-18 20:13 UTC, jwitz commented on astro/cli/astro-deploy.md
> +If you see the following error when using `astro deploy` and you configured your CLI to work with [Podman](cli/configure-cli.md), you might need to set an additional environment variable to correctly
Same edits here as the other notes

2023-09-18 20:38 UTC, nsAstro submitted a review, later dismissed
The changes to the docs look good. Can we make the edits for Astro CLI docs for Software as well? I'm not too familiar with the doc repo structure so I'm guessing it's [here](https://github.com/astronomer/docs/blob/main/software/deploy-cli.md). This issue was identified and resolved in a Software customer's environment.

2023-09-20 13:47 UTC, lzdanski commented
@jwitz did an in-person quick talk about adding a note to the Software deploy code page. I think I added the right info to the tips - I'd like to keep that info in the CLI pages just because I can see a use case of seeing an error > searching the command that caused it. But changed it to `info` from `tip`

2023-09-20 16:42 UTC, jwitz commented on astro/cli/configure-cli.md
> +
```suggestion
### Troubleshoot your Podman configuration

The following error can sometimes occur when the CLI tries to build your Astro Runtime image using Podman:

```bash
WARN[0010] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -e -u -x -c] will be ignored. Must use `docker` format 
```

To resolve this issue, run the following command to set the `BUILDAH_FORMAT` environment variable on your machine:

```dockerfile
export BUILDAH_FORMAT=docker
```

```
Small nit but I like to always newline between markdown style types, helps to improve readability and can sometimes resolve formatting issues

2023-09-20 16:43 UTC, jwitz approved these changes
LGTM! Just two v minor suggestions

2023-09-27 14:09 UTC, merged