Weaviate tutorial
astronomer/docs pull request #2865
Opened 2023-09-21 12:14 UTC by TJaniF

(Currently the provider is still WIP and in a private repository, so this tutorial wont work yet)

2023-10-02 20:08 UTC, kentdanas requested changes
@TJaniF this is great, love this example! Requesting changes just so I can take one more look after we update to install from the whl file (and I'll actually run it then 🙂 )

2023-10-02 20:08 UTC, kentdanas commented on learn/airflow-weaviate.md
> +2. In the Airflow UI run the `query_movie_vectors` DAG by clicking the play button. You will be prompted to provider [Airflow params](airflow-params.md) for `movie_concepts` and the `certainty_thresh
```suggestion
2. In the Airflow UI, run the `query_movie_vectors` DAG by clicking the play button. You will be prompted to provider [Airflow params](airflow-params.md) for `movie_concepts` and the `certainty_threshold_percent`.
```

2023-10-02 20:08 UTC, kentdanas commented on learn/airflow-weaviate.md
> +    - The `query_embeddings` task uses the [WeaviateHook](https://registry.astronomer.io/) to connect to the Weaviate instance and run a GraphQL query on the vector embeddings created by Weaviate usi
```suggestion
    - The `query_embeddings` task uses the [WeaviateHook](https://registry.astronomer.io/) to connect to the Weaviate instance and run a GraphQL query on the vector embeddings created by Weaviate using the `text2vec-transformers` module running in the `t2v-transformers` container. The query returns the most similar movies to the concepts provided by the user when running the DAG in the next step.
```

2023-10-02 20:08 UTC, kentdanas commented on learn/airflow-weaviate.md
> +3. Wait for the DAG run to finish. Note that if you are running the project locally on a larger dataset the `import_data` task might take a longer time to complete because Weaviate will generate the
```suggestion
Note that if you are running the project locally on a larger dataset, the `import_data` task might take a longer time to complete because Weaviate generates the vector embeddings in this task.
```
Waiting doesn't need to be a separate step :) Just this note at the end of sub-step 2 is enough, but you may need to make sure it's indented properly.

2023-10-02 20:08 UTC, kentdanas commented on learn/airflow-weaviate.md
> +4. View your movie suggestion in the task logs of the `query_embeddings` task:
```suggestion
3. View your movie suggestion in the task logs of the `query_embeddings` task:
```

2023-10-02 20:08 UTC, kentdanas commented on learn/airflow-weaviate.md
> +Congratulations! You used Airflow and Weaviate to get your next movie suggestion! This tutorial showed the use of three different Weaviate operators and decorators and the WeaviateHook, for more info
```suggestion
Congratulations! You used Airflow and Weaviate to get your next movie suggestion! This tutorial showed the use of three different Weaviate operators and decorators and the WeaviateHook. For more information on other modules see the [Weaviate Airflow provider readme](https://github.com/astronomer/airflow-provider-weaviate).
```

2023-10-03 19:31 UTC, kentdanas approved these changes
Looks good! Some minor comments, plus one important one (the docker compose override file isn't named right currently, so won't actually start the containers). Other than that, good to move to copy editing!

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +The provider used in this tutorial is currently in beta and subject to change. Once the provider is released this tutorial will be updated the provider source code will be available. The example code
```suggestion
The provider used in this tutorial is currently in beta and subject to change. Once the provider is released, this tutorial will be updated and the provider source code will be available. The example code from this tutorial is also available on [GitHub](https://github.com/astronomer/airflow-weaviate-tutorial). 
```
Is the note about the tutorial code being on GH relevant to the beta status? (other than that it's not on the registry now, but I wouldn't expect readers to know about that...). If not I would remove that last sentence.

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +3. Change the content of the `Dockerfile` of your Astro project to the following statement importing the wheel file:
```suggestion
3. Change the content of the `Dockerfile` of your Astro project to the following statement importing the`whl` file:
```

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +The Airflow Weaviate provider is currently in beta and not yet available on PyPI. The provider will be available on PyPI once it is out of beta and Steps 1.2 to 1.4 will be updated in this tutorial.
```suggestion
The Airflow Weaviate provider is currently in beta and not yet available on PyPI.
```

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +3. This tutorial uses a local Weaviate instance and a text2vec-transformer model, each running in a Docker container. To add additional containers to your Astro project, create a new file in your pro
```suggestion
5. This tutorial uses a local Weaviate instance and a text2vec-transformer model, each running in a Docker container. To add additional containers to your Astro project, create a new file in your project's root directory called `docker-compose.override.yml` and add the following:
```

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +4. To create an [Airflow connection](connections.md) to Weaviate, add the following to your `.env` file:
```suggestion
6. To create an [Airflow connection](connections.md) to Weaviate, add the following to your `.env` file:
```

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +    version: '3.1'
I had issues with the indentation in this when I copied from the deploy preview. When I copied from GH repo directly it was fine. So maybe worth re-copying it in here.

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +    - The `ingest_data` defined using the [@task.weaviate_import](https://registry.astronomer.io/) decorator ingests the data into Weaviate. Note that you can run any Python code on the data before i
```suggestion
    - The `ingest_data` task defined using the [@task.weaviate_import](https://registry.astronomer.io/) decorator ingests the data into Weaviate. Note that you can run any Python code on the data before ingesting it into Weaviate, making it possible to create your own embeddings or complete other transformations before it is ingested. To import your own vectors, specify the column containing vectors in the dictionary that is returned by the task with the key `embedding_column`:
```

2023-10-03 19:31 UTC, kentdanas commented on learn/airflow-weaviate.md
> +    ```python
Is it possible to indent this block so it's under the bullet? Right now it's rendering one indentation to the left and looks a little weird.

2023-10-03 19:55 UTC, TJaniF reviewed
Thank you @kentdanas ! 😄 

@lzdanski ready for you :)

2023-10-03 19:55 UTC, TJaniF commented on learn/airflow-weaviate.md
> +The provider used in this tutorial is currently in beta and subject to change. Once the provider is released this tutorial will be updated the provider source code will be available. The example code
No, not directly relevant, just where I put the link to the GH repo 😅 but yes, can definitely move that. :)

2023-10-03 19:55 UTC, TJaniF commented on learn/airflow-weaviate.md
> +3. This tutorial uses a local Weaviate instance and a text2vec-transformer model, each running in a Docker container. To add additional containers to your Astro project, create a new file in your pro
🤦 thanks for catching that!

2023-10-04 14:44 UTC, lzdanski reviewed
@TJaniF - I did a first pass - there's a couple places I need to come back to, but wanted to get you this first round of feedback!

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +Congratulations! You used Airflow and Weaviate to get your next movie suggestion! This beta tutorial showed the use of three different Weaviate operators and decorators and the WeaviateHook, more ope
```suggestion
Congratulations! You used Airflow and Weaviate to get your next movie suggestion! This beta tutorial showed the use of the WeaviateHook and three different Weaviate operators and decorators. More operators and decorators will be available after the release of the provider.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    ![Screenshot of the Airflow UI showing the `query_movie_vectors` DAG having completed successfully in the Grid view with the Graph tab selected. Since this was the first run of the DAG the schema
```suggestion
    ![Screenshot of the Airflow UI showing the successful completion of the `query_movie_vectors` DAG in the Grid view with the Graph tab selected. Since this was the first run of the DAG, the schema had to be newly created. The schema creation was enabled when the branching task `branch_create_schema` selected the downstream `create_schema` task to run.](/img/tutorials/airflow-weaviate_successful_dag.png)
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +2. In the Airflow UI, run the `query_movie_vectors` DAG by clicking the play button. You will be prompted to provide [Airflow params](airflow-params.md) for `movie_concepts` and the `certainty_thresh
```suggestion
2. In the Airflow UI, run the `query_movie_vectors` DAG by clicking the play button. Then, provide [Airflow params](airflow-params.md) for `movie_concepts` and the `certainty_threshold_percent`.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +1. Run `astro dev start` in your Astro project to start up Airflow and open the Airflow UI at `localhost:8080`.
```suggestion
1. Run `astro dev start` in your Astro project to start Airflow and open the Airflow UI at `localhost:8080`.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    - The `query_embeddings` task uses the WeaviateHook to connect to the Weaviate instance and run a GraphQL query on the vector embeddings created by Weaviate using the `text2vec-transformers` modu
```suggestion
    - The `query_embeddings` task uses the WeaviateHook to connect to the Weaviate instance and run a GraphQL query. This query uses the `text2vec-transformers` module in the `t2v-transformers` container on the vector embeddings created by Weaviate. The query returns the most similar movies to the concepts provided by the user when running the DAG in the next step.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    This DAG consists of seven tasks comprising a simple ML orchestration pipeline.
```suggestion
    This DAG consists of seven tasks to make a simple ML orchestration pipeline.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    - The `branch_create_schema` is defined with a `@task.branch` operator to decide whether the `create_schema` task should be run based on the result of the `check_schema` task. If the schema alrea
```suggestion
    - The `branch_create_schema` is defined with a `@task.branch` operator to decide whether to run the `create_schema` task based on the result of the `check_schema` task. If the schema already exists, the DAG runs the empty `schema_exists` task instead.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    - The `create_schema` task uses the WeaviateCreateSchemaOperator to create the schema defined in `movie_schema.json` in Weaviate.
```suggestion
    - The `create_schema` task uses the WeaviateCreateSchemaOperator to create the schema defined by `movie_schema.json` in Weaviate. 
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +    - The `ingest_data` task defined using the @task.weaviate_import decorator ingests the data into Weaviate. Note that you can run any Python code on the data before ingesting it into Weaviate, mak
```suggestion
    - The `ingest_data` task is defined by the @task.weaviate_import decorator, which ingests the data into Weaviate. You can run any Python code on the data before ingesting it into Weaviate, which makes it possible to create your own embeddings or complete other transformations before ingesting the data. To import your own vectors, specify the column containing vectors in the dictionary that is returned by the task with the key `embedding_column`:
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +In order to prepare Weaviate to ingest your data, you need to define a [schema](https://weaviate.io/developers/weaviate/tutorials/schema). The WeaviateCreateSchemaOperator allows you to do so based o
```suggestion
In order to prepare Weaviate to ingest your data, you need to define a [schema](https://weaviate.io/developers/weaviate/tutorials/schema). The WeaviateCreateSchemaOperator allows you to make a schema based on a JSON file. Weaviate adds Vector embeddings to the schema later in the process.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +3. Create a new file called `text_to_parquet_script.py` in the `movie_data` directory. Copy the script below which contains a function to create a [parquet file](https://parquet.apache.org/docs/) fro
```suggestion
3. Create a new file called `text_to_parquet_script.py` in the `movie_data` directory. Copy the script below, which contains a function to create a [parquet file](https://parquet.apache.org/docs/) from `movie_data.txt`.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +2. Create a new file called `movie_data.txt` in the `movie_data` directory and copy and paste the following information:
```suggestion
2. Create a new file called `movie_data.txt` in the `movie_data` directory, then copy and paste the following information:
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +The DAG in this tutorial runs a query on vectorized movie descriptions from [IMDB](https://www.imdb.com/). If you are running the project locally, we recommend testing the pipeline with a small subse
```suggestion
The DAG in this tutorial runs a query on vectorized movie descriptions from [IMDB](https://www.imdb.com/). If you run the project locally, Astronomer recommends testing the pipeline with a small subset of the data. If you run the project on a remote server, you can use the [full dataset](https://github.com/astronomer/learn-tutorials-data/blob/main/movie_descriptions.txt).
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +6. To create an [Airflow connection](connections.md) to Weaviate, add the following to your `.env` file:
```suggestion
6. To create an [Airflow connection](connections.md) to Weaviate, add the following environment variables to your `.env` file:
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +Note that it is possible to use a remote transformer model by changing the `TRANSFORMERS_INFERENCE_API` value in the `docker-compose.override.yml` file. See the Weaviate documentation on [modules](ht
```suggestion
You can use a remote transformer model by changing the `TRANSFORMERS_INFERENCE_API` value in the `docker-compose.override.yml` file. See the Weaviate documentation on [modules](https://weaviate.io/developers/weaviate/modules) for more information. When a remote model is used, the `t2v-transformers` container can be removed from the `docker-compose.yaml` file.
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +5. This tutorial uses a local Weaviate instance and a text2vec-transformer model, each running in a Docker container. To add additional containers to your Astro project, create a new file in your pro
```suggestion
5. This tutorial uses a local Weaviate instance and a text2vec-transformer model, with each running in a Docker container. To add additional containers to your Astro project, create a new file in your project's root directory called `docker-compose.override.yml` and add the following:
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +3. Change the content of the `Dockerfile` of your Astro project to the following statement importing the `whl` file:
```suggestion
3. Change the content of the `Dockerfile` of your Astro project to the following statement to import the `whl` file:
```

2023-10-04 14:44 UTC, lzdanski commented on learn/airflow-weaviate.md
> +- Use Airflow's [data-driven scheduling](airflow-datasets.md) to run operations on Weaviate based on upstream events in your data ecosystem (e.g. when a new model is trained, or a new dataset is avai
```suggestion
- Use Airflow's [data-driven scheduling](airflow-datasets.md) to run operations on Weaviate based on upstream events in your data ecosystem, such as when a new model is trained or a new dataset is available.
```

2023-10-04 15:26 UTC, lzdanski commented on learn/airflow-weaviate.md
> +Weaviate allows you to store objects alongside their vector embeddings and to query these objects based on their similarity in n-dimensional vector space. Vector embeddings are key components of many
```suggestion
Weaviate allows you to store objects alongside their vector embeddings and to query these objects based on their similarity. Vector embeddings are key components of many modern machine learning models such as [LLMs](https://en.wikipedia.org/wiki/Large_language_model) or [ResNet](https://arxiv.org/abs/1512.03385).
```
I'll leave it to your discretion on whether or not we need the vector space detail - I think getting that "store objects as vector embeddings" and "vector embeddings are key components of ML learning models" was the missing piece!

2023-10-05 02:39 UTC, TJaniF commented on learn/airflow-weaviate.md
> +    - The `ingest_data` task is defined by the @task.weaviate_import decorator, which ingests the data into Weaviate. You can run any Python code on the data before ingesting it into Weaviate, which
Noted! Thank you :)

2023-10-05 03:03 UTC, merged