GitHub Actions/UI Onboarding Flow
astronomer/docs pull request #2867
Opened 2023-09-22 04:01 UTC by lzdanski

This is a first draft document for the new UI flow that guides users through running their first DAG with Github Actions. 

**Important** - this document exists as a more detailed parallel to the UI instructions that appear when you click **Deploy your first DAG... with GitHub Actions** from the deployment details page.

1. I successfully deployed my DAG, but the run failed.
2. There's some unavoidable context switching in the flow - you'll notice in Step 2 -> 3. I don't love it, but its accurate.
3. What should users configure their API token as?
4. I also added links to this flow from the CLI install pages - this provides an escape hatch for anyone who is completing the CLI install as a pre-req of the Run your First DAG process.

2023-09-25 21:51 UTC, lzdanski commented on astro/run-first-DAG.md
> +## Compare your options
@manmeetkaur - These were a few notable differences between the two options that I could come up with. Can you think of any other reasons or recall any scenarios where you might recommend a user start with one over the other?

2023-09-27 06:09 UTC, manmeetkaur reviewed
LGTM - just small suggestions and one follow-up that we can do.

2023-09-27 06:09 UTC, manmeetkaur commented on astro/first-DAG-cli.md
> +sidebar_label: 'Run your first DAG with Astro CLI'
Since the top menu is called "Run your first DAG", can this label for this be "with Astro CLI" and for the other "with GitHub Actions"?

2023-09-27 06:09 UTC, manmeetkaur commented on astro/run-first-DAG.md
> +## Compare your options
@lzdanski I am a little confused by the table, it is trying to achieve two things, talk about use-cases and comparison. let's chat about this, because I have some questions as well

2023-09-27 21:31 UTC, lzdanski commented on astro/first-DAG-cli.md
> +title: 'Run your first DAG with the Astro CLI'
I think the distinction here we want to make is with the deployment method vs local/on Astro because the user needs to choose between GitHub Actions and CLI. Might let Jake be tie breaker on that call, though - I can see arguments for both sides!

2023-09-27 21:35 UTC, lzdanski commented on astro/first-DAG-cli.md
> +
A couple of questions about your feedback. We assumed that this user wants to deploy a DAG to Astro and run it quickly without needing to learn too much Astro or Airflow specific information.

We decided against the phrasing `deploy your image` because we assumed that a new user might or might not know the distinction between an entire project and their DAGs. So now that I'm looking at the whole thing, and with the GitHub Actions alternative path, what do you think of this change?

2023-09-27 21:35 UTC, lzdanski commented on astro/run-first-DAG.md
> +## Compare your options
Sounds good to me! I was struggling here

2023-09-27 21:38 UTC, jwitz requested changes
This is a great attempt to organize content around a very complex onboarding experience @lzdanski ! I mostly had general suggestions, but also some open ended questions that might slightly change the structure of the GitHub actions doc.

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +
```suggestion
Open a new tab or browser window and [make a fork of the example project repository](https://github.com/astronomer/astro-example-dags/fork) on GitHub.

This repository contains an _Astro project_, which is a collection of files required for running Airflow on Astro. An Astro project includes folders for DAG files, plugins, dependencies, and more.

Specifically, this Astro project includes an example DAG which, when you run it, retrieves a list of countries from an Astro S3 data store and filters the list through a data transform. The repository also includes a pre-configured [Astronomer deploy action](https://github.com/astronomer/deploy-action). In the next step, you'll configure this action to deploy code from your forked repository to Astro.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +
Feel free to edit this, but I tried clearing up the Astro project wording and foregrounding the setup.

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +To enable GitHub to Deploy DAGs to your Astro workspace, you need to connect your Astro account with the workflow on GitHub. This means you need to have two browser windows open at the same time - on
```suggestion
To configure code deploys from your GitHub repository to Astro, you must have two browser windows open at the same time: one with the [Cloud UI](https://cloud.astronomer.io), and one with your forked GitHub repository.
```
This is less about accounts and more about tokens/ repositories

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +1. Open the [Cloud UI](https://cloud.astronomer.io) to your Deployments page. Choose the Deployment where you want to deploy DAGs to.
```suggestion
1. In the Cloud UI, choose the Deployment where you want to deploy your repository. 
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +3. In GitHub, choose **Actions** from the repository menu.
```suggestion
2. In GitHub, open your forked repository and click **Actions**.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +  The [workflow](https://github.com/astronomer/astro-example-dags/blob/c2c63ced1923488d797ce0eba6b37f5658e92570/.github/workflows/deploy-to-astro.yaml) is a script that uses API tokens to deploy DAGs
```suggestion
3. Click **I understand my workflows, go ahead and enable them.**

  The [workflow](https://github.com/astronomer/astro-example-dags/blob/main/.github/workflows/deploy-to-astro.yaml) is a script that uses API tokens to deploy DAGs from a GitHub repository to your Deployment, without requiring any local development.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +5. Choose **Astronomer CI - Deploy Code** workflow.
```suggestion
5. Choose the **Astronomer CI - Deploy Code** workflow. 
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +6. Click **Run workflow**. This opens a modal to enter your Astro Deployment information.
```suggestion
6. Click **Run workflow**. This opens a modal to enter information about your Astro Deployment.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +9. On your **Deployment** page in the Cloud UI, click **API Tokens**.
```suggestion
9. In the Cloud UI, click **API Tokens**.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +10. Click **API Token** to create a new API Token, and then enter a **Name** and choose the **Expiration**.
```suggestion
10. Click **+ API Token** to create a new API token, and give the token a **Name** and an **Expiration**.
```
API token is a general term, so we don't capitalize is (unless it's a UI heading)

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +11. Click **Create API Token** to make your new token.
```suggestion
11. Click **Create API Token**, then copy the token that appears.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +12. Copy the API Token and paste in the **API Token** field on your GitHub Actions workflow page.
```suggestion
12. In GitHub, paste the API Token in the **API Token** field on your GitHub Actions workflow page.
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +13. Then click, **Run workflow**.
```suggestion
13. Click **Run workflow**. 
```

2023-09-27 21:38 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +2. **Unpause** the **S3** DAG and click **Run**.
```suggestion
Open your Deployment in the Cloud UI and click **DAGs** in the left sidebar, then click **S3**. From this page, you can see that the `s3` DAG has run exactly once. 

The **DAGs** page compiles the most commonly used information and actions from the Airflow UI in one place. If you prefer to view your DAG run in the Airflow UI, click **Open Airflow** in the upper right corner of the page.
```
Would be great to include a screenshot here of the DAGs page after the run.

2023-09-27 21:38 UTC, jwitz commented on astro/run-first-DAG.md
> +## Compare your options
I think the table is over complicating the choice. We can just say:

If you prefer to develop on your local machine and use command line tools, follow the steps in [link].

If you can't install additional tools on your current machine or you prefer a no-code workflow, follow the steps in [link].

2023-09-29 20:35 UTC, jwitz approved these changes
LGTM! Most of my suggestions are optional

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-cli.md
> +If you just want to run Airflow on your local machine without deploying to Astro, see [Get started with Airflow using the Astro CLI](cli/get-started-cli.md). Also, if you want to deploy your first DA
```suggestion
If you just want to run Airflow on your local machine without deploying to Astro, see [Get started with Airflow using the Astro CLI](cli/get-started-cli.md). If you want to deploy your first DAG without installing any software to your local machine, see [Run your first DAG with GitHub Actions](first-DAG-github-actions.md).
```

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-cli.md
> +
I think the new wording looks good!

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +An Astro _Deployment_ is an instance of Apache Airflow that is powered by all core Airflow components, including a webserver, scheduler, and one or more workers. You deploy DAGs to a Deployment, and
```suggestion
An Astro _Deployment_ is an instance of Apache Airflow that is powered by all core Airflow components, including a webserver, scheduler, and one or more workers. You deploy DAGs to a Deployment, and you can have one or more Deployments within your Workspace.
```

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +
```suggestion
```

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +## Step 3: Set up the GitHub Actions Workflow
```suggestion

## Step 3: Set up the GitHub Actions Workflow
```

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +    For security reasons, this is the only opportunity you have to copy your API token. After you exit the modal window, you cannot copy it again. Be sure to save your token in a safe place or paste
Should we add a sentence here to explain that if they lose it, they should just create a new one? I could also see downgrading this to a `caution` note, since nothing really explodes if you fail to copy the token

2023-09-29 20:35 UTC, jwitz commented on astro/first-DAG-github-actions.md
> +Open your Deployment in the Cloud UI and click **DAGs** in the left sidebar, then click **S3**. From this page, you can see that the `s3` DAG has run exactly once.
Reupping my comment here that it would be great to have a screenshot of this

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +| Scenario                               | Recommendation |
After comparing the two approaches, I prefer having just the two sentences, which very cleanly split the choice. I also don't think the tutorial necessarily "explores local development" since we don't talk about running Airflow locally. Also, at least on my screen this results in a no-scroll overview. Woohoo!

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +## Compare your options
```suggestion
## Choose a tutorial
```

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +| Scenario                               | Recommendation |
The only thing is that we might want to add something brief about "CI/CD" to the second sentence, which is definitely a valid reason that someone would want to use GH over the CLI.

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +## Next Steps
Should we include this section if we already have the links for users in the previous topic? Seems redundant but I don't feel strongly either way

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +</head>
```suggestion
```
I think we are not doing this anymore because its SEO effects are not reliable

2023-09-29 20:35 UTC, jwitz commented on astro/run-first-DAG.md
> +title: "Choose how to run your first DAG on Astro"
```suggestion
title: "Run your first DAG on Astro"
```
I know this is breaking convention a bit but I also want the overview for this to have a strong title. Starting with "choose" this early on feels like it's adding friction to the reader's journey

2023-10-04 19:31 UTC, lzdanski commented on astro/first-DAG-github-actions.md
> +- Start an Astro trial
```suggestion
- Start an Astro trial.
```

2023-10-04 19:31 UTC, lzdanski commented on astro/run-first-DAG.md
> +If you're new to Airflow and want a more in-depth tutorial, see [Write your First DAG](https://docs.astronomer.io/learn/get-started-with-airflow).
Move this line

2023-10-04 19:31 UTC, lzdanski commented on astro/run-first-DAG.md
> +- Deploy DAGs to Astro with the Astro CLI.
```suggestion
- Deploy DAGs to Astro with either the Astro CLI or GitHub Actions.
```

2023-10-04 19:31 UTC, lzdanski commented on astro/run-first-DAG.md
> +- Trigger a run of an example DAG in the Airflow UI.
```suggestion
- Trigger a run of an example DAG.
```

2023-10-04 19:31 UTC, lzdanski commented on astro/first-DAG-cli.md
>  - The latest version of the [the Astro CLI](cli/overview.md).
Add step about install the CLI instead of in pre-reqs

2023-10-04 19:31 UTC, lzdanski commented on astro/first-DAG-github-actions.md
> +
Step 1 - log in to astro

2023-10-04 19:31 UTC, lzdanski commented on astro/first-DAG-github-actions.md
> +Open your Deployment in the Cloud UI and click **DAGs** in the left sidebar, then click **S3**. From this page, you can see that the `s3` DAG has run exactly once.
```suggestion
Open your Deployment in the Cloud UI and click **DAGs**, then click **S3**. From this page, you can see that the `s3` DAG has run exactly once. 
```

2023-10-05 14:17 UTC, paolaperaza approved these changes
Nice job here, @lzdanski! Just double check all URLs + redirects -- I did not do that.

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-cli.md
> +Although it's not required for this tutorial, the following container engines are supported with the Astro CLI and required to run Airflow locally:
Part of me wants to clarify to the user "why" they should care about this right now? Do we recommend dealing with Docker or Podman "if" what?

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +This quickstart explains the steps required to deploy an example DAG to Astro and trigger a DAG run with Github Actions.
```suggestion
Astro is the industry's leading managed service for Apache Airflow. To quickly learn how Astro works, follow the steps in this quickstart to create an Airflow environment and run your first DAG with GitHub Actions.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +The steps take about 15 minutes. If you prefer to use a CLI, you can alternatively create and run your first DAG [using the Astro CLI](first-DAG-cli.md) in the same amount of time.
```suggestion
The steps take about 15 minutes. If you prefer to use a CLI and set up a local Airflow environment, you can alternatively create and run your first DAG [using the Astro CLI](first-DAG-cli.md) in the same amount of time.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +- Configure GitHub Actions.
```suggestion
- Fork an example GitHub repository with a new Astro project.
- Configure GitHub Actions.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +- Deploy DAGs to Astro in the Cloud UI.
```suggestion
- Trigger the GitHub Action to deploy an example DAG to Astro.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +- Trigger a run of an example DAG in the Airflow UI.
```suggestion
- Trigger a run of the example DAG in the Airflow UI. 
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +This tutorial assumes that you know some basic Airflow concepts. If you're new to Airflow and want a more general introduction, see [Write your First DAG](https://docs.astronomer.io/learn/get-started
```suggestion
This tutorial assumes that you're familiar with basic Apache Airflow concepts. If you're new to Airflow and want a more general introduction, see [Write your First DAG](https://docs.astronomer.io/learn/get-started-with-airflow).
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +This tutorial assumes that you know some basic Airflow concepts. If you're new to Airflow and want a more general introduction, see [Write your First DAG](https://docs.astronomer.io/learn/get-started
Let's actually link to the Airflow 101 course on Academy -- and in the Astro CLI doc as well

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +- A [GitHub](https://docs.github.com/en/get-started/signing-up-for-github) account.
```suggestion
- A [GitHub account](https://docs.github.com/en/get-started/signing-up-for-github).
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +This repository contains an _Astro project_, which is a collection of files required for running Airflow on Astro. An Astro project includes folders for DAG files, plugins, dependencies, and more.
I'd better introduce and include more info about the repository upfront at the top of this section, and then break down the fork part in 2-3 steps

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +1. In the Cloud UI, choose the Deployment where you want to deploy your repository.
```suggestion
1. In the Cloud UI, choose the Deployment where you want to deploy your Astro project. 
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +This automatically deploys the example DAGs to your Deployment.
```suggestion
This automatically deploys the example DAGs in your Astro project to your Deployment.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +The **DAGs** page compiles the most commonly used information and actions from the Airflow UI in one place. If you prefer to view your DAG run in the Airflow UI, click **Open Airflow** in the upper r
```suggestion
The **DAGs** page of the Cloud UI includes the most commonly used information and actions from the Airflow UI in one place. If you prefer to view your DAG run in the Airflow UI, click **Open Airflow** in the upper right corner of the page.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +Congratulations! You deployed and ran a DAG to your Astro Deployment using GitHub Actions!
```suggestion
Congratulations! You deployed and ran your first DAG on Astro with GitHub Actions.
```

2023-10-05 14:17 UTC, paolaperaza commented on astro/first-DAG-github-actions.md
> +- Read more about [Developing CI/CD workflows](set-up-ci-cd.md).
```suggestion
- Develop your [Astro project](/astro/cli/run-airflow-locally)
- Read more about [Developing CI/CD workflows](set-up-ci-cd.md)
- Install [the CLI](/astro/cli/install-cli.md) to test DAGs or run Airflow locally
- [Write your First DAG](https://docs.astronomer.io/learn/get-started-with-airflow)
```

2023-10-06 16:59 UTC, lzdanski commented on astro/first-DAG-cli.md
> +Although it's not required for this tutorial, the following container engines are supported with the Astro CLI and required to run Airflow locally:
I think we had this in this part of the tutorial originally because we were coming from the previous version of the getting started where the install and local running of Airflow was a big part of the procedure. In this new world of rapid spin-up and working in the Cloud UI, i don't think it's necessary to keep in the getting started anymore.

2023-10-06 17:04 UTC, lzdanski commented on astro/first-DAG-github-actions.md
> +The steps take about 15 minutes. If you prefer to use a CLI, you can alternatively create and run your first DAG [using the Astro CLI](first-DAG-cli.md) in the same amount of time.
So this isn't correct - we don't have them set up a local Airflow environment in first-dag-CLI, it's just a DAG deployment, not an image build.

2023-10-06 19:43 UTC, lzdanski commented on astro/first-dag-github-actions.md
> +## Step 4: Run your DAG in Airflow
```suggestion
## Step 4: View your DAG run results
```

2023-10-06 19:43 UTC, lzdanski commented on astro/first-dag-github-actions.md
> +This example repository also includes a pre-configured [Astronomer deploy action](https://github.com/astronomer/deploy-action), which you can use to set up a CI/CD deployment pipeline. In this step,
```suggestion
This example repository also includes a pre-configured [Astronomer deploy action](https://github.com/astronomer/deploy-action), which you can use to set up a CI/CD deployment pipeline. In this step, you'll configure the GitHub action to deploy code from your forked repository to Astro and run the workflow.
```

2023-10-06 19:43 UTC, lzdanski commented on astro/first-dag-github-actions.md
> +Specifically, this Astro project includes an example DAG which, when you run it, retrieves a list of countries from an Astro S3 data store and filters the list through a data transform.
```suggestion
This repository contains an _Astro project_, which is a collection of files required for running Airflow on Astro. An Astro project includes folders for DAG files, plugins, dependencies, and more. Specifically, this Astro project includes an example DAG which, when you run it, retrieves a list of countries from an Astro S3 data store and filters the list through a data transform.  
```

2023-10-06 19:52 UTC, merged