Add warning for self-hosted runners
astronomer/docs pull request #2868
Opened 2023-09-22 06:13 UTC by manmeetkaur

Resolves #2769

2023-09-22 16:55 UTC, jwitz approved these changes
Once @erdos2n reviews this LGTM!

2023-09-22 16:55 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +If you use a self-hosted runner to execute jobs from GitHub Actions, Astro CLI's `config.yaml` might be shared across your organization. In such cases, to reduce the risk of accidentally deploying to
```suggestion
If you use a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) to execute jobs from GitHub Actions, the Astro CLI's `config.yaml` file, which stores default deploy details, might be shared across multiple CI/CD pipelines. To reduce the risk of accidentally deploying to the wrong Deployment, ensure the following:
```

2023-09-22 16:55 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +</TabItem>
I moved this topic back into the tabs on purpose. It's an example for using a custom image (tab 3), not a general purpose example. Can you move this back?

2023-09-22 16:55 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +- Add an `astro logout` command at the end of your workflow to ensure the token is cleared from the `config.yaml` file.
```suggestion
- Add `ASTRO_API_TOKEN` to your repository and include a check in your GitHub workflow to verify that it exists. 
- Use Deployment API tokens, which are scoped only to one Deployment, instead of Workspace or Organization API tokens.
- Specify `deployment-id` or `deplyment-name` in your action as shown in the following templates.
- Add the command `astro logout` at the end of your workflow to ensure that your authentication token is cleared from the `config.yaml` file.
```
Does `config.yaml` store the token in plaintext, or does it just reference the GH secret?

2023-09-22 16:55 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +- Add an `astro logout` command at the end of your workflow to ensure the token is cleared from the `config.yaml` file.
I also added a point to use Deployment API tokens, which at a minimum will throw an error of the CLI tries deploying to the wrong deployment.

2023-09-25 06:44 UTC, manmeetkaur commented on astro/ci-cd-templates/github-actions.md
> +- Add an `astro logout` command at the end of your workflow to ensure the token is cleared from the `config.yaml` file.
plain-text

2023-09-25 06:48 UTC, manmeetkaur commented on astro/ci-cd-templates/github-actions.md
> +</TabItem>
If you notice the example is a use-case that is a mix of a single-branch deploy from a private network, meaning using the regular checkout github action `actions/checkout@v3` and also creating a custom image. So a user might straightaway want to see the example, and see the use github action. It is easier to look at an example atleast and understand than read lines. If you want I can add a one liner in the example to explain a bit more for clarity. WDYT? lmk :)

2023-09-25 14:06 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +</TabItem>
For all of the other deploy types, the example _is_ the template. If we're going to include an example that applies to all "private network" templates, it should be a more general implementation. For the average user who doesn't have a custom image consideration, I think framing this as a general example creates more questions than answers.

So I'm sticking with my original point: It makes more sense to keep the custom image example in the custom image tab. The other tabs already have templates that users can read to understand the implementations that suit their specific use case.

2023-09-28 07:20 UTC, manmeetkaur commented
Hey @erdos2n , could you please take a look at this ?

2023-09-28 16:30 UTC, erdos2n commented
Thanks for doing this @manmeetkaur! One thing, can we add a line showing the command  specifying the deployment name. This has been used as a safe guard to deploy to a different deployment. 

```diff
+ astro deploy -n <deployment-name>
```

2023-09-28 20:12 UTC, erdos2n commented on astro/ci-cd-templates/github-actions.md
> +- Specify `deployment-id` or `deplyment-name` in your action as shown in the following templates.
```suggestion
- Specify `deployment-id` or `deplyment-name` in your action as shown in the following templates.
+ Specify `deployment-id` or `deplyment-name` in your action as shown in the following templates. `astro deploy -n <deployment-name>`
```

2023-09-28 20:13 UTC, erdos2n commented on astro/ci-cd-templates/github-actions.md
> +- Specify `deployment-id` or `deplyment-name` in your action as shown in the following templates.
Hello @manmeetkaur , can we make these changes first?

2023-09-28 20:13 UTC, erdos2n requested changes
I left a comment in the updated instructions

2023-09-29 08:09 UTC, merged