Update Cloud IDE ML tutorial
astronomer/docs pull request #2877
Opened 2023-09-26 19:10 UTC by TJaniF

2023-09-26 22:00 UTC, kentdanas requested changes
Looks good! Only requesting changes because I think creating an Astro account should still only be a prereq instead of a step, and we can update the prereq to say something like 'An Astro account. A free 14-day trial is available'

2023-09-27 08:56 UTC, TJaniF reviewed
Thank you for the review @kentdanas !

I realized we can make the prereq section way less daunting because all but the Astro account and Org/Workspace are only needed for the last 2 steps, let me know what you think :)

2023-09-27 08:56 UTC, TJaniF commented on learn/cloud-ide-tutorial.md
> +## Step 0: Create an Astro account
I think my braincell reasoned it is in between a step and a prereq, hence step 0, but yes can definitely move it back to the prereqs 😅

2023-09-27 17:29 UTC, kentdanas approved these changes
Looks good!

2023-09-27 17:29 UTC, kentdanas commented on learn/cloud-ide-tutorial.md
> +To complete the optional steps [13](#step-13-optional-deploy-your-dag-to-astro) and [14](#step-14-optional-run-your-dag-on-astro) at the end of this tutorial, you will also need:
```suggestion
[Optional] To complete steps [13](#step-13-optional-deploy-your-dag-to-astro) and [14](#step-14-optional-run-your-dag-on-astro) at the end of this tutorial, you will also need:
```

2023-09-28 09:26 UTC, TJaniF commented
Thank you Kenten!

FYI to @jwitz and @lzdanski Kenten and I decided to sneaky-merge this update past you because we will direct users to this tutorial in the webinar today and the old version is very outdated. This update is mostly changing button/field names that changed in the UI, all new screenshots and rewording the requirements to show that you can do most of the tutorial with just a trial Astro account without needing to worry about GH or a database. :)

2023-09-28 09:26 UTC, merged