add a note about log tags for datadog task logs
astronomer/docs pull request #2905
Opened 2023-10-02 22:26 UTC by melugoyal

without this note customers will not know what to search for when looking for their task logs in Datadog.

2023-10-03 14:44 UTC, lzdanski requested changes
Does Astro or DataDog apply the default tags?

2023-10-03 14:44 UTC, lzdanski commented on astro/view-logs.md
> +By default, the tags `source=astronomer` and `service=astronomer-task-logs` will be used.
```suggestion
By default, Astro uses the tags `source=astronomer` and `service=astronomer-task-logs`.
```

2023-10-03 15:19 UTC, melugoyal commented on astro/view-logs.md
> +By default, the tags `source=astronomer` and `service=astronomer-task-logs` will be used.
Astro does. good suggestion

2023-10-03 17:53 UTC, jedcunningham commented
We should hold this until 9.2 comes out - tags won't work in earlier versions.

2023-10-03 18:03 UTC, lzdanski reviewed
Changes LGTM - will approve when unblocked

2023-10-09 21:41 UTC, jedcunningham approved these changes

2023-10-12 13:10 UTC, lzdanski approved these changes

2023-10-12 15:04 UTC, merged