Snowpark integration tutorial
astronomer/docs pull request #2909
Opened 2023-10-03 20:06 UTC by TJaniF

❄️

2023-10-04 21:43 UTC, kentdanas requested changes
Great start @TJaniF! Let me know if you want to chat about any of the requested changes

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +sidebar_label: "Snowpark"
```suggestion
sidebar_label: "Snowpark Tutorial"
```
As we chatted about this morning, let's put this in the Snowflake menu.

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +In this tutorial you'll learn how to:
```suggestion
In this tutorial, you'll learn how to: 
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +- Create a [custom XCom backend](custom-xcom-backends-tutorial.md) in Snowflake.
Somewhere in these bullets we should have a "...to implement a model predicting XYZ" - however you want to say it, but should generally describe the use case so people understand what the plot is showing :)

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +Snowpark allows you to use Python to perform transformations as well as machine learning operations on data stored in Snowflake.
```suggestion
Snowpark allows you to use Python to perform transformations and machine learning operations on data stored in Snowflake.
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +Additionally this tutorial shows how to use Snowflake as a custom XCom backend, this is especially useful for organizations with strict compliance requirements who want to keep all their data in Snow
```suggestion
Additionally, this tutorial shows how to use Snowflake as a custom XCom backend. This is especially useful for organizations with strict compliance requirements who want to keep all their data in Snowflake but still leverage [Airflow XCom](airflow-passing-data-between-tasks.md) to pass data between tasks.
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +If you want to run this tutorial using the Snowflake custom XCom backend you will need to either:
```suggestion
If you want to run this tutorial using the Snowflake custom XCom backend, you will need to either:
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +If you want to run this tutorial using the Snowflake custom XCom backend you will need to either:
Is using the XCom backend optional? If so, I would lean towards pulling this into a bullet in the list with something like [Optional] To use the Snowflake custom XCom backend, you will need either: and then move the two bullets to subullets.

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +Similarly, the tutorial DAG includes a toggle to use a [Snowpark-optimized warehouse](https://docs.snowflake.com/en/user-guide/warehouses-snowpark-optimized) for model training. While the tutorial DA
I'm leaning towards leaving this out of the prereqs section and just putting an info box somewhere below that while the DAG defaults to using the smaller warehouse (if it doesn't already, we should make it), we recommend in prod using the snowpark optimized one, and note that you need account admin privileges. 

Just to simplify this section a bit. Right now it seems a little overwhelming, so if we can make the defaults simpler and present these things as optional later on I think that would help.

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +3. Change the content of the `Dockerfile` of your Astro project to the following, importing the `whl` file and creating a virtual environment using the [Astro venv buildkit](https://github.com/astron
I think the numbering is off here - there are two step 3's

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +7. Optional. If you want to use a Snowflake custom XCom backend add the following variables to your `.env` as well. Make sure to replace the values with the name of your own database, schema, table a
```suggestion
7. Optional. If you want to use a Snowflake custom XCom backend, add the following additional variables to your `.env`. Replace the values with the name of your own database, schema, table, and stage if you are not using the suggested values.
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +The DAG in this tutorial runs a classification model on synthetic data to predict with afternoon beverage a skier will choose based on attributes like ski color, ski resort and amount of new snow. Th
```suggestion
The DAG in this tutorial runs a classification model on synthetic data to predict which afternoon beverage a skier will choose based on attributes like ski color, ski resort, and amount of new snow. The data is generated using [this script](https://github.com/astronomer/airflow-snowpark-tutorial/blob/main/include/data/create_ski_dataset.py). 
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +    If you do not want the DAG to automatically setup and clean up the Snowflake custom XCom backend, set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to `False` to remove the `create_snowflake_obj
Would it make sense to default this to False so that the simplest option is the default?

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +    If you do not want the DAG to automatically setup and clean up the Snowflake custom XCom backend, set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to `False` to remove the `create_snowflake_obj
Let's put all the DAG modification instructions in bullets in a sub-step 3.

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +Congratulations! You trained a classification model in Snowpark using Airflow. This pipeline is meant as a simple example showcasing the three main options to run code in different Snowpark using Air
```suggestion
Congratulations! You trained a classification model in Snowpark using Airflow. This pipeline is meant as a simple example showcasing the three main options to run code in Snowpark using Airflow decorators:
```

2023-10-04 21:43 UTC, kentdanas commented on learn/airflow-snowpark.md
> +- `@task.snowpark_virtualenv` runs your code in a virtual environment within Snowpark that is created on the fly just for a specific task. Use this decorator when you want to tailor a virtual environ
```suggestion
- `@task.snowpark_virtualenv` runs your code in a virtual environment within Snowpark that is created at runtime for that specific task. Use this decorator when you want to tailor a virtual environment to a task and don't need to reuse it. The corresponding traditional operator is the SnowparkVirtualenvOperator.
```

2023-10-05 09:23 UTC, TJaniF reviewed
Thank you for the review @kentdanas !
I accepted all your suggestions and restructured the two optional features to hopefully simplify the tutorial flow :)

2023-10-06 17:32 UTC, kentdanas approved these changes
Looks great @TJaniF! I think the structure makes more sense now with the optional components. Good from my side content-wise.

2023-10-06 17:32 UTC, kentdanas commented on sidebarsLearn.js
>              'connections/snowflake'
Should we put connection first? So they're alphabetized? Not that it matters that much, just being picky :)

2023-10-06 17:32 UTC, kentdanas commented on learn/airflow-snowpark.md
> +- Run a [Logistic Regression model](https://mlu-explain.github.io/logistic-regression/) on a synthetic dataset describing skiers to predict their afternoon beverage choice.
```suggestion
- Run a [Logistic Regression model](https://mlu-explain.github.io/logistic-regression/) on a synthetic dataset to predict skiers' afternoon beverage choice.
```

2023-10-06 17:32 UTC, kentdanas commented on learn/airflow-snowpark.md
> +While this tutorial DAG uses a small dataset where model training can be accomplished using the standard Snowflake warehouse, Astronomer recommends to use a Snowpark-optimized warehouse for model tra
```suggestion
While this tutorial DAG uses a small dataset where model training can be accomplished using the standard Snowflake warehouse, Astronomer recommends using a Snowpark-optimized warehouse for model training in production.
```

2023-10-07 11:10 UTC, mpgreg commented on learn/airflow-snowpark.md
> +- Running machine learning models directly in Snowflake, without having to move data out of your Snowflake database.
Add some bullet points here:
-Using Airflow for Snowpark python orchestration enables not only automation but also auditing, logging, retry and complex triggering for powerful workflows.
-The Snowpark provider for Airflow simplifies:
 -- connections to Snowflake without the need to pass credentials
 -- Snowpark session instantiation without repeated boilerplate code 
 -- Passing Snowpark Dataframes between tasks with automatic serialization and deserialization
 -- Data lineage 
 -- Secure data passing with a custom XCOM backend

2023-10-07 11:14 UTC, mpgreg commented on learn/airflow-snowpark.md
> +- Optional. This tutorial includes instructions on how to use the Snowflake [custom XCom backend](custom-xcom-backends-tutorial.md) included in the provider. If you want to this custom XCom backend y
If you want to use this custom XCom backend you will need to either:
    - Run the DAG with a Snowflake account with permissions to create databases, schemas, stages and tables. 
 In this case the Snowflake custom XCom backend can be created and cleaned up by tasks in the DAG itself. See [Step 3.3](#step-3-create-your-dag) for more instructions. The tutorial specifies the `ACCOUNTADMIN` privilege as it is setup automatically with the Snowflake trial.
    - Ask your Snowflake administrator to create the following for you:
        - A database called `SNOWPARK_XCOM_DB`.
        - A schema called `SNOWPARK_XCOM_SCHEMA`.
        - A table called `XCOM_TABLE`.
        - A stage called `XCOM_STAGE`.

2023-10-07 11:15 UTC, mpgreg commented on learn/airflow-snowpark.md
> +- A Snowflake account. A [30-day free trial](https://signup.snowflake.com/) is available. You will need to have at least one database and one schema created to store the data and models used in this
https://trial.snowflake.com/?owner=SPN-PID-365384

2023-10-07 11:18 UTC, mpgreg commented on learn/airflow-snowpark.md
> +4. Change the content of the `Dockerfile` of your Astro project to the following, importing the `whl` file and creating a virtual environment using the [Astro venv buildkit](https://github.com/astron
Add a note:

This tutorial shows how to run Snowpark Python tasks in virtual environments to simplify dependency management if needed in a production system.  In this step we create the virtual environments with ...

2023-10-07 11:26 UTC, mpgreg commented on learn/airflow-snowpark.md
> +    - Ask your Snowflake administrator to create the following for you:
Should update this whole section.  The tutorial was setup with a Trial account in mind where no objects exist already.  Alternatively they can use an existing db, schema and stage.  The only thing they need to create (or have an admin create if they don't have permissions) is the XCOM table.  If they, or an admin, create the table manually they will need the schema as specified at https://github.com/astronomer/airflow-snowpark-tutorial/blob/bfe8a8449c44c9735b16a540a02376b15e08d76e/dags/airflow_with_snowpark_tutorial.py#L101

2023-10-07 11:28 UTC, mpgreg commented on learn/airflow-snowpark.md
> +    - Ask your Snowflake administrator to create the following for you:
Also need to mention that if they change the object names here they need to note them for step 8

2023-10-11 13:33 UTC, TJaniF reviewed
Thank you for your comments @mpgreg ! Made all the changes :)

@kentdanas: I know you already approved but I assume you might want to have a second look at the `why Airflow and Snowpark` and `prerequisites` section to double check I didn't disimprove :) (Not sure if the translation is right here, what I mean is `verschlimmbessern` to make something worse while you are trying to improve it) 

@lzdanski Ready for you! And all new ⛄ themed tutorial. :)

2023-10-11 16:47 UTC, kentdanas approved these changes
Updates look good!

2023-10-11 16:47 UTC, kentdanas commented on learn/airflow-snowpark.md
> +- Using Airflow for Snowpark python orchestration enables not only automation but also auditing, logging, retry and complex triggering for powerful workflows.
```suggestion
- Use Airflow for Snowpark Python orchestration to enable automation, auditing, logging, and retry and complex triggering for powerful workflows.
```

2023-10-17 22:15 UTC, lzdanski reviewed
I had a little bit of time to take a first pass - will get to the rest tomorrow first thing!

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +[Snowpark](https://www.snowflake.com/en/data-cloud/snowpark/) is a framework containing runtimes and libraries to run non-SQL code in [Snowflake](https://www.snowflake.com/en/). Snowpark comes with a
```suggestion
[Snowpark](https://www.snowflake.com/en/data-cloud/snowpark/) is a framework that contains runtimes and libraries to run non-SQL code in [Snowflake](https://www.snowflake.com/en/). Snowpark comes with a [comprehensive machine learning library](https://docs.snowflake.com/en/developer-guide/snowpark-ml/index) optimized for Snowflake. 
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +- Run a [Logistic Regression model](https://mlu-explain.github.io/logistic-regression/) on a synthetic dataset to predict skiers' afternoon beverage choice.
This is fabulous.

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +The provider used in this tutorial is currently in beta and its contents as well as the decorators used are subject to change. After the official release, this tutorial will be updated.
```suggestion
The provider used in this tutorial is currently in beta and both its contents and decorators are subject to change. After the official release, this tutorial will be updated.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +![A plot showing a confusion matrix and ROC curve with a high AUC for hot_chocolate, a medium AUC for snow_mocha and tea and low predictive power for wine and coffee.](/img/tutorials/airflow-snowpark
```suggestion
![A plot showing a confusion matrix and ROC curve with a high AUC for hot_chocolate, a medium AUC for snow_mocha and tea, and low predictive power for wine and coffee.](/img/tutorials/airflow-snowpark_plot_metrics.png)
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +- Use Airflow for Snowpark Python orchestration to enable automation, auditing, logging, and retry and complex triggering for powerful workflows.
```suggestion
- Expressing data transformations in Snowflake in Python instead of SQL.
- Storing and versioning your machine learning models in a model registry inside Snowflake.
- Using Snowpark's compute resources instead of your Airflow cluster resources for machine learning.
- Using Airflow for Snowpark Python orchestration to enable automation, auditing, logging, retry, and complex triggering for powerful workflows.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +Additionally, this tutorial shows how to use Snowflake as a custom XCom backend. This is especially useful for organizations with strict compliance requirements who want to keep all their data in Sno
```suggestion
Additionally, this tutorial shows how to use Snowflake as a custom XCom backend. This is especially useful for organizations with strict compliance requirements who want to keep all their data in Snowflake, but still leverage [Airflow XCom](airflow-passing-data-between-tasks.md) to pass data between tasks.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +- Airflow decorators. [Introduction to the TaskFlow API and Airflow decorators](airflow-decorators.md).
```suggestion
- Airflow decorators. See [Introduction to the TaskFlow API and Airflow decorators](airflow-decorators.md).
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +- A Snowflake account. A [30-day free trial](https://trial.snowflake.com/?owner=SPN-PID-365384) is available. You will need to have at least one database and one schema created to store the data and
```suggestion
- A Snowflake account. A [30-day free trial](https://trial.snowflake.com/?owner=SPN-PID-365384) is available. You need to have at least one database and one schema created to store the data and models used in this tutorial.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +- Optional. This tutorial includes instructions on how to use the Snowflake [custom XCom backend](custom-xcom-backends-tutorial.md) included in the provider. If you want to this custom XCom backend y
```suggestion
- (Optional) This tutorial includes instructions on how to use the Snowflake [custom XCom backend](custom-xcom-backends-tutorial.md) included in the provider. If you want to this custom XCom backend you will need to either:
```

We changed this styling a little while back for the docs. Open to discussion about having same/different conventions between the two!

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - Run the DAG using a Snowflake account with `ACCOUNTADMIN` privileges to let the first task of the DAG create the required database, schema, stage and table. See [Step 3.3](#step-3-create-your-d
```suggestion
    - Run the DAG using a Snowflake account with `ACCOUNTADMIN` privileges to allow the DAG's first task create the required database, schema, stage and table. See [Step 3.3](#step-3-create-your-dag) for more instructions. The free trial account has the required privileges.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +        - Provider you with the name of an existing database, schema and stage. You will need to use these names in [Step 1.8](#step-1-configure-your-astro-project) for the `AIRFLOW__CORE__XCOM_SNOWF
```suggestion
        - Provide you with the name of an existing database, schema, and stage. You need to use these names in [Step 1.8](#step-1-configure-your-astro-project) for the `AIRFLOW__CORE__XCOM_SNOWFLAKE_TABLE` and `AIRFLOW__CORE__XCOM_SNOWFLAKE_STAGE` environment variables. 
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +3. Create a new file in your Astro project's root directory called `requirements-snowpark.txt`. This file contains all Python packages that you will install in your reuseable Snowpark environment.
```suggestion
3. Create a new file in your Astro project's root directory called `requirements-snowpark.txt`. This file contains all Python packages that you install in your reuseable Snowpark environment.
```

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +4. Change the content of the `Dockerfile` of your Astro project to the following, importing the `whl` file and creating a virtual environment using the [Astro venv buildkit](https://github.com/astron
```suggestion
4. Change the content of the `Dockerfile` of your Astro project to the following, which imports the `whl` file and creates a virtual environment by using the [Astro venv buildkit](https://github.com/astronomer/astro-provider-venv). The requirements added in the previous step are installed in that virtual environment. This tutorial includes Snowpark Python tasks that are running in virtual environment, which is a common pattern in production to simplify dependency management. This Dockerfile creates a virtual environment called `snowpark` with the Python version 3.8 and the packages specified in `requirements-snowpark.txt`. 
```
I might need to take another pass at editing this step.

2023-10-17 22:15 UTC, lzdanski commented on learn/airflow-snowpark.md
> +8. Optional. If you want to use a Snowflake custom XCom backend, add the following additional variables to your `.env`. Replace the values with the name of your own database, schema, table, and stage
```suggestion
8. (Optional) If you want to use a Snowflake custom XCom backend, add the following additional variables to your `.env`. Replace the values with the name of your own database, schema, table, and stage if you are not using the suggested values.
```

2023-10-18 12:14 UTC, TJaniF reviewed
@lzdanski Thank you for the first pass! Accepted all the suggestions so far :)

2023-10-18 12:14 UTC, TJaniF commented on learn/airflow-snowpark.md
> +- Optional. This tutorial includes instructions on how to use the Snowflake [custom XCom backend](custom-xcom-backends-tutorial.md) included in the provider. If you want to this custom XCom backend y
Thanks for the headsup! I vote with using the same conventions whereever possible between Docs and Learn :) 
Will keep it in mind.

2023-10-18 15:16 UTC, lzdanski reviewed
Second review pass!

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - If you want to use a [Snowpark-optimized warehouse](https://docs.snowflake.com/en/user-guide/warehouses-snowpark-optimized) for model training, set the `USE_SNOWPARK_WH` variable to `True` and
```suggestion
    - If you want to use a [Snowpark-optimized warehouse](https://docs.snowflake.com/en/user-guide/warehouses-snowpark-optimized) for model training, set the `USE_SNOWPARK_WH` variable to `True` and provide your warehouse names to `MY_SNOWPARK_WAREHOUSE` and `MY_SNOWFLAKE_REGULAR_WAREHOUSE`. If the `create_snowflake_objects` task is enabled, it creates the `MY_SNOWPARK_WAREHOUSE` warehouse. Otherwise, you need to create the warehouse manually before running the DAG.
```

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - If you want to use [setup/ teardown tasks](airflow-setup-teardown.md) to create and clean up a Snowflake custom XCom backend for this DAG, set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to
```suggestion
    - If you want to use [setup/ teardown tasks](airflow-setup-teardown.md) to create and clean up a Snowflake custom XCom backend for this DAG, set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to `True`. This setting adds the `create_snowflake_objects` and `cleanup_xcom_table` tasks to your DAG and creates a setup/ teardown workflow. Note that your Snowflake account needs to have `ACCOUNTADMIN` privileges to perform the operations in the `create_snowflake_objects` task and you need to define the environment variables described in [Step 1.8](#step-1-configure-your-astro-project) to enable the custom XCom backend.
```

this is a quirk of a lot of technical writing. As someone reads through a procedure, every step is a snapshot of their present moment. In step 3 they are completing that task in the present moment. When there are conditional situations, it's usually clearest to structure that as "If [you do x], then y occurs.", because other formats of conditional future can be a really tricky verb construction that slows people down to think through. 

"If [you do x], then y occurs." vs 'When you do x, y will occur"-> when in the future will y occur? At this step? At the end of the process?

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - Optional. `cleanup_xcom_table`: Cleans up the Snowflake custom XCom backend by dropping the `XCOM_TABLE` and `XCOM_STAGE`. This task is a [teardown task](airflow-setup-teardown.md) and will onl
```suggestion
    - (Optional) `cleanup_xcom_table`: Cleans up the Snowflake custom XCom backend by dropping the `XCOM_TABLE` and `XCOM_STAGE`. This task is a [teardown task](airflow-setup-teardown.md) and is only shown in the DAG graph if you set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to `True`. See also Step 3.3.
```

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - `train_beverage_classifier`: Trains a [Snowpark Logistic Regression model](https://docs.snowflake.com/en/developer-guide/snowpark-ml/reference/latest/api/modeling/snowflake.ml.modeling.linear_m
```suggestion
    - `train_beverage_classifier`: Trains a [Snowpark Logistic Regression model](https://docs.snowflake.com/en/developer-guide/snowpark-ml/reference/latest/api/modeling/snowflake.ml.modeling.linear_model.LogisticRegression) on the dataset, saves the model to the model registry, and creates predictions from a test dataset. This task uses the `@task.snowpark_virtualenv` decorator to run the code in a newly created virtual environment within Snowpark's compute. The `requirements` parameter of the decorator specifies the packages to install in the virtual environment. The model predictions are saved to XCom as a pandas DataFrame.
```

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    This task uses the `@task.snowpark_ext_python` decorator, running the code in the Snowpark virtual environment created in Step 1. Which virtual environment to run a task in is determined by the b
```suggestion
    This task uses the `@task.snowpark_ext_python` decorator, running the code in the Snowpark virtual environment created in Step 1. The binary provided to the `python` parameter of the decorator determines which virtual environment to run a task in. The `@task.snowpark_ext_python` decorator works analogously to the [@task.external_python decorator](external-python-operator.md), except the code is executed within Snowpark's compute.
```

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - `create_model_registry`: Creates a model registry in Snowpark using the [Snowpark ML package](https://docs.snowflake.com/en/developer-guide/snowpark-ml/index). Since the task is defined using t
```suggestion
    - `create_model_registry`: Creates a model registry in Snowpark using the [Snowpark ML package](https://docs.snowflake.com/en/developer-guide/snowpark-ml/index). Since the task is defined by the `@task.snowflake_python` decorator, the snowpark session is automatically instantiated from provided connection ID.
```

2023-10-18 15:16 UTC, lzdanski commented on learn/airflow-snowpark.md
> +    - Optional. `create_snowflake_objects`: Creates the Snowflake objects required for the Snowflake custom XCom backend. This task uses the `@task.snowflake_python` decorator to run code within Snow
```suggestion
    - (Optional) `create_snowflake_objects`: Creates the Snowflake objects required for the Snowflake custom XCom backend. This task uses the `@task.snowflake_python` decorator to run code within Snowpark, automatically instantiating a Snowpark session called `snowpark_session` from the connection ID provided to the `snowflake_conn_id` parameter. This task is a [setup task](airflow-setup-teardown.md) and is only shown in the DAG graph if you set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to `True`. See also Step 3.3.
```

2023-10-19 09:35 UTC, TJaniF reviewed
Thank you @lzdanski ! I accepted all your suggestions :)

2023-10-19 09:35 UTC, TJaniF commented on learn/airflow-snowpark.md
> +    - If you want to use [setup/ teardown tasks](airflow-setup-teardown.md) to create and clean up a Snowflake custom XCom backend for this DAG, set `SETUP_TEARDOWN_SNOWFLAKE_CUSTOM_XCOM_BACKEND` to
Thank you for the explanation, that does make a lot of sense! (and I've definitely read docs before, performed a step and was left wondering if y was supposed to occur later or I did something wrong 😅 )

2023-10-20 12:58 UTC, lzdanski approved these changes

2023-10-20 20:33 UTC, merged