Update airflow-sql.md
astronomer/docs pull request #2912
Opened 2023-10-04 21:29 UTC by joescottswanson

* Fixes a typo where a ` was in the wrong spot
* Refers to the SQLExecuteQueryOperator instead of the deprecated SnowflakeOperator and PostgresOperator
* Includes some helpful notes about parameterized queries and templates

2023-10-04 21:31 UTC, joescottswanson commented on learn/airflow-sql.md
> -- [PostgresOperator](https://registry.astronomer.io/providers/postgres/modules/postgresoperator)
I was checking out the source code of the `PostgresOperator` and the `SnowflakeOperator` and I noticed that both were deprecated in favor of the `SQLExecuteQueryOperator`. This doesn't seem to be the case for the MySQLOperator. I am not sure about the `BigQueryOperator`; I'm not familiar with BigQuery.

2023-10-06 11:28 UTC, TJaniF requested changes
Thank you for the PR, this section was definitely in need of more explanation! I added some suggestions and small corrections :)

2023-10-06 11:28 UTC, TJaniF commented on learn/airflow-sql.md
> +    params={"date":mydatevariable}
```suggestion
    parameters={"my_date": mydatevariable}
```

Switching the example to use `parameters` instead of `params` to not have the DAG level params interfere and changing the key to `my_date` to be more explicit.

2023-10-06 11:28 UTC, TJaniF commented on learn/airflow-sql.md
> +And then reference that param in your SQL file (note that above you're passing a dictionary to `parameters`, but in your query below you reference `params` to access the values of `parameters`):
```suggestion
And then reference that param in your SQL file:
```

Changes when using `parameters` instead of `params` in the operator :)

2023-10-06 11:28 UTC, TJaniF commented on learn/airflow-sql.md
>  WHERE date = {{ params.date }}
```suggestion
SELECT *
FROM STATE_DATA
WHERE date = %(my_date)s
```

Using SQL parameter rendering instead of a jinja template.

2023-10-06 11:28 UTC, TJaniF commented on learn/airflow-sql.md
> +N.b. If you run your DAG with user-defined parameters (by running your DAG via the 'Trigger DAG w/config' option), these user-defined parameters will overwrite any value you pass into the `parameters
~~~suggestion
An alternative option is to use [Jinja](templating.md) templates in your SQL statements and pass the relevant values using the `params` parameter.

```python
    opr_param_query = SQLExecuteQueryOperator(
        task_id="param_query",
        conn_id="snowflake_default",
        sql="param-query.sql",
        params={"my_date": "2022-09-01"},
    )
```

The value can be referenced using Jinja syntax in the SQL statement:

```sql
SELECT *
FROM STATE_DATA
WHERE date = '{{ params.date }}'
```

:::tip

Airflow params can also be defined at the DAG-level and passed to a DAG at runtime. Params passed at runtime will override param defaults defined at the DAG or the task level. For more information on params see the [Create and use params in Airflow](airflow-params.md) guide.

:::
~~~

Good idea to explain the relationship to DAG params here! I moved the `param` example down here to have everything about using that parameter together and contrast it with `parameters` above.

2023-10-06 15:16 UTC, kentdanas approved these changes

2023-10-06 15:17 UTC, merged

2023-10-06 15:18 UTC, kentdanas commented
Hey @joescottswanson thanks again for the PR! We made a couple small updates, but have now merged your changes.

2023-10-12 23:38 UTC, joescottswanson commented on learn/airflow-sql.md
> +N.b. If you run your DAG with user-defined parameters (by running your DAG via the 'Trigger DAG w/config' option), these user-defined parameters will overwrite any value you pass into the `parameters
Thank you so much for this review/help with the docs! I wasn't super clear on how all of this worked (which was where this PR came from), but this really helped sort everything out for me.

2023-10-12 23:39 UTC, joescottswanson commented
Appreciate the review and changes! That answered a couple of questions for me.