consolidate redundant office hours documentation
astronomer/docs pull request #2923
Opened 2023-10-06 19:18 UTC by ophie200

2023-10-06 19:30 UTC, fritz-astronomer approved these changes

2023-10-06 19:36 UTC, lzdanski requested changes
@ophie200 - This looks good overall! I have some content edits for one part. LMK what you think and we can hopefully get these changes in today!

2023-10-06 19:36 UTC, lzdanski commented on astro/office-hours.md
> +To book office hours, click **Book office hours** in the left sidebar of the Astronomer documentation site. This will take you to a Calendly form to schedule a 30-minute virtual meeting. In the form,
```suggestion
To book office hours, click **Book office hours** in the documentation sidebar navigation. Then, schedule a 30-minute virtual meeting on the Calendly form. In the form, provide details about any issues and questions that you want to discuss during the meeting.
```
- This page is in the documentation site, so we can assume users don't require that detail. 
- Spatial organization (left right top bottom above below) isn't a helpful cue for screen reader users, so we need a different term.

2023-10-07 09:46 UTC, iamakashladdha approved these changes
LGTM

2023-10-10 16:00 UTC, lzdanski commented on astro/astro-support.md
> +If you don't require break-fix support, Astronomer recommends scheduling a meeting with the Astronomer Data Engineering team during office hours. In an office hour meeting, you can ask questions, mak
```suggestion
If you don't require break-fix support, Astronomer recommends scheduling a meeting with the Astronomer Data Engineering team during office hours. In an office hours meeting, you can ask questions, make feature requests, or get expert advice for your data pipelines. 
```

2023-10-10 16:01 UTC, lzdanski commented on astro/office-hours.md
>  Before you book an office hour appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion o
```suggestion
Before you book an office hours appointment, please browse the documentation, [Astronomer Academy](https://academy.astronomer.io/), [Airflow Guides](https://docs.astronomer.io/learn/), or discussion on the [Astronomer Forum](https://forum.astronomer.io) to see if there are existing guides or resources that answer your question. 
```

2023-10-10 16:19 UTC, lzdanski approved these changes

2023-10-10 16:19 UTC, merged