MLOps guide draft
astronomer/docs pull request #2926
Opened 2023-10-09 12:26 UTC by TJaniF

2023-12-20 21:29 UTC, kentdanas requested changes
@TJaniF I think this is great. Left a few comments, requesting changes because I'll give it another pass after the holidays.

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +Ready to get started? Check out our recommended resources showcasing ML implementations with Airflow:
This list is pretty long for a tip box. I would suggest removing the Faire webinar and Sissy-G toys repo at least - and maybe in general having links to Astro astro, one webinar, and one use case, and leave the rest for Other Resources at the end.

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +### DevOps for MLOps with Airflow
```suggestion
### DevOps for MLOps
```
We should keep the section headers consistent, and I think not adding "with Airflow" to each one makes more sense. I think you could potentially even remove the "for MLOps" part.

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +DevOps best practices are based on all aspects of your data and machine learning pipeline being expressed as code and a set of behaviors when interacting with your code base. Since Airflow pipelines
```suggestion
DevOps best practices are based on all aspects of your data and machine learning pipeline being expressed as code and a set of behaviors when interacting with your code base. Since Airflow pipelines are defined in Python code, you can apply DevOps best practices when using Airflow. This includes:
```

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +- **Version control**. All code and configuration should be stored in a version control system like [Git](https://git-scm.com/). Version control allows you to track all changes of your pipeline, ML m
I think this section is missing a description of what it means to use Airflow for DevOps. The best practices make sense, but are we saying Airflow is the DevOps tool in the case of MLOps? And how does that work in practice?

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +- [**Data quality**](data-quality.md) and data cleaning. If your data is of bad quality, your model predictions will be too. Astronomer recommends to incorporate data quality checks and data cleaning
```suggestion
- [**Data quality**](data-quality.md) and data cleaning. If your data is of bad quality, your model predictions will be too. Astronomer recommends incorporating data quality checks and data cleaning steps into your data pipelines to define and monitor the requirements your data has to fulfill in order for downstream ML operations to be successful. Airflow supports integration with any data quality tool that has an API, and has pre-built integrations for tools such as [Great Expectations](airflow-great-expectations.md) and [Soda Core](soda-data-quality.md).
```

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +Apart from the foundations mentioned above, second day data quality operations in MLOps often include advanced topics like data governance, [data lineage](airflow-openlineage.md) and data cataloging
Do we want to mention here how Airflow fits in?

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +- How to implement different MLOps patterns with Airflow.
```suggestion
```
I would argue we're not really doing this here, since (for now at least), this guide is very high level. We're more describing the what and why, but not providing a ton of specific guidance. Let me know if you disagree though!

2023-12-20 21:29 UTC, kentdanas commented on learn/airflow-mlops.md
> +## Components of MLOps
I think in each subsection here (except maybe the business one), we should add a generic statement about _how_ Airflow fits in. This is a great overview of the things that matter for MLOps, and why Airflow is a good choice, but it doesn't really describe what that looks like in practice. It doesn't need to be in depth (we could have probably many full reference architectures for each one of these), but just something high level to describe what Airflow is doing.

2024-01-05 20:10 UTC, kentdanas reviewed
@TJaniF I like the addition of the "in practice" sections. I know we're staying away from specific implementation examples for this guide, but I do think it could benefit from some high level diagrams showing how Airflow ties things together, even if they're generic. Does that seem reasonable?

2024-01-17 12:20 UTC, TJaniF commented
Thank you! :) 

@jwitz and @lzdanski this one has been a while cooking but I am pretty happy with it now, at least as a starter guide for people to get oriented. I asked the AI team to review and I think @davidgxue is going to take a look, but from Kenten and my side it is ready for copy edit. 😊

2024-01-17 20:01 UTC, lzdanski reviewed
Got a lot of style/voice feedback and some consistent commas/active voice suggestions. Great write-up!

2024-01-17 23:41 UTC, davidgxue reviewed
Thank you Tamara for the amazing writeup! I learned a thing or two from reading this! It is super insightful! Left 2 super minor nit comments. Hopefully it is helpful!

2024-01-17 23:41 UTC, davidgxue commented on learn/airflow-mlops.md
> +    - Training and testing data. The best way to store your data highly depends on your data and type of ML. Data engineering includes ingesting data and moving it to the ideal platform for your ML m
For the ` [Airflow object storage]` in this line, did you intend to add a url/hyperlink to `Airflow object storage` or the square brackets extra?
```
with tools like [Airflow object storage] and the [Astro Python SDK](https://docs.astronomer.io/learn/astro-python-sdk)
```

2024-01-17 23:41 UTC, davidgxue commented on learn/airflow-mlops.md
> +### Airflow integrations for MLOps
I am not an expert in Airflow, but I think it may be great to bring up the integrations/providers supported in Airflow like AWS providers, and other providers that allow airflow to integrate easily with major cloud computing services because after all, MLOps could involve orchestrating ML training which can occur, for example, on an AWS EC2 instance with GPUs. The ones we listed below are great but they are more focused on contemporary developments of LLMs and using commercial LLM related solutions, whereas I think Airflow already has great potential/support also for traditional the ML world in general which are all closely tied to data processing and distributed computing!

2024-01-19 14:20 UTC, TJaniF reviewed
Thank you @davidgxue and @lzdanski !

I think I accepted all changes and addressed the comments directly. @lzdanski you are definitely right about my blog voice having been creeping in, I tried to adjust the worst offending sentences 😅 

Also I added a section on LLMOps, this was a suggestion from @odaneau-astro (thanks again!) because there are likely users specifically looking for that and this way we can catch them and direct them towards Ask Astro. :) 
I wasn't sure where to best put it, currently have it as a ### under Why Airflow for MLOps but happy to move it. :)

2024-01-19 15:50 UTC, lzdanski approved these changes
One small passive voice edit! this looks amazing. I learned so much from your write up

2024-01-19 15:50 UTC, lzdanski commented on learn/airflow-mlops.md
> +- **Shared platform**: Airflow is used by both data engineers and ML engineers, which allows teams to create direct dependencies between their pipelines, for example by using [Airflow Datasets](airfl
```suggestion
- **Shared platform**: Both data engineers and ML engineers use Airflow, which allows teams to create direct dependencies between their pipelines, such as using [Airflow Datasets](airflow-datasets.md).
```

2024-01-19 15:55 UTC, odaneau-astro approved these changes
Great job overall.
Just a few comments and nitpicks.
If you haven't already, take a look at Google's MLOps guide here: https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning
Their level 0, 1 and 2 separation and their graphs /charts are pretty much the standard nowadays.

2024-01-19 15:55 UTC, odaneau-astro commented on learn/airflow-mlops.md
> +With Airflow you can use your ML tools and compute locations of choice. Some organizations choose to use external compute for all of their heavy workloads, for example:
```suggestion
With Airflow you can use the ML tools and compute locations of your choice. Some organizations choose to use external compute for all of their heavy workloads, for example:
```

2024-01-19 15:55 UTC, odaneau-astro commented on learn/airflow-mlops.md
> +- Using Apache Airflow to orchestrate actions in other MLOps tools. Airflow is a tool agnostic orchestrator, which means it can also orchestrate all actions in ML specific tools like [MLFlow](airflow
```suggestion
- Using Apache Airflow to orchestrate actions in other MLOps tools. Airflow is a tool-agnostic orchestrator, which means it can also orchestrate all actions in ML specific tools like [MLFlow](airflow-mlflow.md) or [AWS SageMaker](airflow-sagemaker.md). 
```

2024-01-19 15:55 UTC, odaneau-astro commented on learn/airflow-mlops.md
> +- [AWS SageMaker](airflow-sagemaker.md). A tool to train and deploy machine learning models on AWS.
Azure ML should be added here. We have a webinar soon about it too

2024-01-23 13:48 UTC, TJaniF reviewed
Thank you @odaneau-astro ! 

I addressed most of your comments and will post the question about the MLOps components definition in a Slack thread :)

2024-01-23 13:48 UTC, TJaniF commented on learn/airflow-mlops.md
> +- The basics of [Machine Learning](https://mlu-explain.github.io/).
Yes, we do it in a couple of cases where we don't have our own resource, like for example for basic Python and SQL. Thank you for the link, I will use that one instead :)

2024-01-23 13:48 UTC, TJaniF commented on learn/airflow-mlops.md
> +
I added a short rephrased one from the intro sentence of the guide :)

2024-01-23 13:48 UTC, TJaniF commented on learn/airflow-mlops.md
> +MLOps describes different patterns in how organizations can productionize machine learning models. [Gift and Deza (2021)](https://www.oreilly.com/library/view/practical-mlops/9781098103002/) coined t
That is a good callout which is also relevant for the MLOps Academy module. I'll put it on the list of open questions, how we want to define MLOps components and if that should be our own definition, how it differs from existing ones. :)

2024-01-23 13:48 UTC, TJaniF commented on learn/airflow-mlops.md
> +- [AWS SageMaker](airflow-sagemaker.md). A tool to train and deploy machine learning models on AWS.
Thanks for the headsup! Do we have something currently to link to for Azure ML other than the general Azure provider? If not I'd wait until after that webinar and then add it to the list here :)

2024-01-23 14:11 UTC, odaneau-astro commented on learn/airflow-mlops.md
> +- [AWS SageMaker](airflow-sagemaker.md). A tool to train and deploy machine learning models on AWS.
That's a good question for @kentdanas. I'm not sure if we have anything yet.

2024-01-23 17:45 UTC, kentdanas commented on learn/airflow-mlops.md
> +- [AWS SageMaker](airflow-sagemaker.md). A tool to train and deploy machine learning models on AWS.
No, we don't have any content right now specific to Azure ML, and I don't believe there are any specific operators (at least that I could find in OSS). The webinar likely won't be until March. I think you can go ahead and list it here without a link (or just add a link to Azure ML docs), and update it to the webinar one once we do that.

2024-01-23 21:57 UTC, davidgxue approved these changes
Thank you for writing this! Amazing work!

2024-01-24 12:13 UTC, TJaniF commented on learn/airflow-mlops.md
> +## Components of MLOps
@odaneau-astro I changed the definition here to fit the one from your notion page (that is super helpful, thank you!). For the "one sentence explanation" I changed the language a little bit to fit in more with docs, but I hope I got the core meaning right :) 

cc: @shillion

2024-01-24 12:19 UTC, TJaniF commented
@lzdanski I made a few changes since your last review, mainly adding the `Why use Airflow for LLMOps?` section and changes to the `Components of MLOps` part. Also added a bullet point about Alerts and notifications. If you want to have a quick look :) 

@katiebrady-astro pinging you for title and other search machine 🪄 as discussed :)

2024-01-24 17:00 UTC, lzdanski reviewed
Just some grammar things! but overall the changes LGTM.

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +**Machine Learning Operations** (MLOps) is an umbrella term encompassing everything needed to run machine learning models in production. MLOps is a rapidly evolving field with many different best pra
```suggestion
**Machine Learning Operations** (MLOps) is a broad term encompassing everything needed to run machine learning models in production. MLOps is a rapidly evolving field with many different best practices and behavioral patterns with Apache Airflow, providing tool agnostic orchestration capabilities for all steps.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +Ready to get started? Check out the recommended resources showcasing machine learning (ML) implementations with Airflow:
```suggestion
Ready to get started? Check out the recommended resources that showcase machine learning (ML) implementations with Airflow:
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +**Machine learning operations** (MLOps) encompasses all patterns, tools and best practices related to running machine learning models in production.
```suggestion
**Machine learning operations** (MLOps) encompasses all patterns, tools, and best practices related to running machine learning models in production.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +- Using Airflow to orchestrate model training, fine-tuning, testing and deployment.
```suggestion
- Using Airflow to orchestrate model training, fine-tuning, testing, and deployment. 
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +- Using Airflow to orchestrate data ingestion from sources such as APIs, source databases and object storage into a working location for your ML model. This might be a vector database, a relational d
```suggestion
- Using Airflow to orchestrate data ingestion from sources such as APIs, source databases, and object storage into a working location for your ML model. This might be a vector database, a relational database, or an object storage solution depending on your use case.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +Apart from the foundations mentioned above, second day data quality operations in MLOps often include advanced topics like data governance, [data lineage](airflow-openlineage.md) and data cataloging
```suggestion
Apart from the foundations mentioned above, second day data quality operations in MLOps often include advanced topics like data governance, [data lineage](airflow-openlineage.md), and data cataloging as well as monitoring of data drift.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +    - Model artifacts. Model artifacts include model parameters, hyperparameters, and other metadata. Airflow integrates with specialized version control systems such as [MLFlow](airflow-mlflow.md) o
```suggestion
    - Model artifacts. Model artifacts include model parameters, hyperparameters, and other metadata. Airflow integrates with specialized version control systems such as [MLFlow](airflow-mlflow.md) or [Weights and Biases](airflow-weights-and-biases.md).
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +- **Infrastructure as code** ([IaC](https://en.wikipedia.org/wiki/Infrastructure_as_code)). Ideally, all infrastructure is defined as code and follows the same CI/CD process as your pipeline and mode
```suggestion
- **Infrastructure as code** ([IaC](https://en.wikipedia.org/wiki/Infrastructure_as_code)). Ideally, all infrastructure is defined as code and follows the same CI/CD process as your pipeline and model code. This allows you to control and, if necessary, roll back environment changes, or quickly deploy new instances of your model.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +- **Version control**. All code and configuration should be stored in a version control system like [Git](https://git-scm.com/). Version control allows you to track all changes of your pipeline, ML m
```suggestion
- **Version control**. All code and configuration should be stored in a version control system like [Git](https://git-scm.com/). Version control allows you to track all changes of your pipeline, ML model, and environment over time and roll back to previous versions if needed. Astro customers can take advantage of [Deployment rollbacks](https://docs.astronomer.io/astro/deploy-history).
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +- **Model governance**: Creating and following regulations for how your organization uses machine learning. This often depends on relevant regulations like GDPR or HIPAA. Airflow has a built-in integ
```suggestion
- **Model governance**: Creating and following regulations for how your organization uses machine learning. This often depends on relevant regulations, like GDPR or HIPAA. Airflow has a built-in integration option with [Open Lineage](airflow-openlineage.md), the open-source standard for tracking data lineage, which is a key component of model governance.
```

2024-01-24 17:00 UTC, lzdanski commented on learn/airflow-mlops.md
> +The first component of MLOps is to make sure there is strategic aligment with all stakeholders. This component will vary widely depending on your organization and use case and can include:
```suggestion
The first component of MLOps is to make sure there is strategic aligment with all stakeholders. This component varies widely depending on your organization and use case and can include:
```

2024-01-24 17:00 UTC, katiebrady-astro approved these changes
@TJaniF lgtm! 🙌

2024-01-25 15:50 UTC, merged

2024-01-25 15:50 UTC, TJaniF commented
@lzdanski and @katiebrady-astro Thank you! :)