AstroCloud CLI Reference Guide
astronomer/docs pull request #294
Opened 2022-01-14 13:29 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/264

2022-01-25 17:20 UTC, paolaperaza reviewed
@jwitz @sunkickr I added a bunch of comments here. A few high-level thoughts -

- Need more consistency across the board. This includes how we refer to: The Astronomer Cloud CLI, the local metadata DB, capitalizing Webserver and Scheduler, whether the top H2 is "Overview" or "Description" and then what our plan is with subcommands
- Open Q: Do any other companies list example "outputs" to these commands?
- Let's figure out what we want this landing page to look like and whether it's all encompassing with all commands

I also added a few links to other docs (and made copy consistent)

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-ps.md
> +## Usage
```suggestion
## Overview

List all Docker containers running in your local Airflow environment, including the Airflow Webserver, Scheduler, and Postgres Database. This command works similarly to [`docker ps`](https://docs.docker.com/engine/reference/commandline/ps/) and can only be run from a directory that is running an Astronomer Project.

## Usage
```

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-run.md
> +# Run OSS `create_user` command
```suggestion
$ astrocloud dev run create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin
# Run the Airflow CLI's `create_user` command in your local Airflow environment
```

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-run.md
> +Run [Airflow CLI commands](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html) in your local Airflow environment.
```suggestion
Run [Airflow CLI commands](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html) in your local Airflow environment. This command is for local development only and cannot be applied to Deployments running on Astronomer Cloud.
```

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-start.md
> +Build your Astronomer project into a Docker image, spin up Airflow containers on your local machine, and run your project in a local Airflow environment.
```suggestion
Build your Astronomer project into a Docker image and spin up 3 Docker containers on your machine, each for a different Airflow component:

- **Postgres:** Airflow's metadata database
- **Webserver:** The Airflow component responsible for rendering the Airflow UI
- **Scheduler:** The Airflow component responsible for monitoring and triggering tasks

This command can be used regularly to start and run any Astronomer project locally. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
```

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-start.md
> +## Description
Are we going with Overview or Description? I'm cool with either - let's just be consistent

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-stop.md
> +Stop all Airflow containers running on your local machine. Unlike `astro dev kill`, this command does not prune mounted volumes and will preserve data associated with your local Postgres Metadata Dat
```suggestion
Pause all Docker containers running in your local Airflow environment. Unlike `astro dev kill`, this command does not prune mounted volumes and delete data associated with your local Postgres Metadata Database. If you run this command, Airflow connections and task history will be preserved.
```

2022-01-25 17:20 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-workspace-list.md
> +Show a list of all Workspaces that you have access to.
@sunkickr Within your Organization yes?

2022-01-26 12:02 UTC, jwitz commented on cloud/cli-reference/astrocloud-auth-login.md
> +Authenticate to Astronomer Cloud by specifying your organization's URL for accessing Astronomer. After you run this command, the CLI redirects you to a web browser where you can log in to Astronomer.
Maybe we can add these after we finish all of the content we need to get out for GA 😅  already struggling out the gate to keep my personal information out of Terminal.

2022-01-26 12:12 UTC, jwitz commented on cloud/cli-reference/astrocloud-completion.md
> +Generate completion scripts for AstroCloud commands. You can modify the generated scripts and add them to the appropriate directory to customize your shell autocompletion behavior.
The only purpose of this command is to make shorthands for other CLI commands through autocompletion. We can say that this minimizes keystrokes, but that seems self evident.  

I think this is the sort of thing that is only touched by folks who are looking for it in the first place. If anything, we could provide more technical support and examples for various shells here (see [GH's docs](https://cli.github.com/manual/gh_completion) for another example of this)

2022-01-26 12:18 UTC, jwitz commented on cloud/cli-reference/astrocloud-deploy.md
> +| ------- | ---------------------------------------------------- | --------------------------------- |
I like Options because you can specify both flags or non-flag (ie. no `--`) items there. This is what GitHub does: https://cli.github.com/manual/gh_gist_create

We don't need to specify subcommands anymore because we have a different page for each subcommand. Like in the example you linked `login` and `logout` are now their own separate pages. This makes more sense than trying to link to actions together in a table just because they're at the same level in the command.

2022-01-26 12:20 UTC, jwitz commented on cloud/cli-reference/astrocloud-deployment-list.md
> +List all Deployments that you have access to.
My bad here, it's for your current Workspace. The option below makes it show across all Workspaces

2022-01-26 12:28 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-init.md
> +| `--name`            | Name of your Astronomer project                                                                                    | Any string                  |
Still says airflow-version according in the latest version of CLI

2022-01-26 12:33 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-kill.md
> +This command is most often used to restart a cluster when testing new DAGs or settings in a non-production environment. After using `astro dev kill`, you can restart your environment with `astro dev
If the doc we end up linking out to will have the same information as we include here, I think it's better to just link out to the doc and maintain one source of truth.

2022-01-26 12:36 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-logs.md
> +Show webserver and scheduler logs from your local Airflow environment.
I thought part of the value add of Astronomer Cloud was abstracting away Kubernetes infrastructure. Do we want to mention containers here if that's not necessary to understand what the command does?

2022-01-26 12:45 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-start.md
> +## Description
Definitely description, Overview is a typo

2022-01-26 12:49 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-start.md
> +Build your Astronomer project into a Docker image, spin up Airflow containers on your local machine, and run your project in a local Airflow environment.
This is another part where I think it makes more sense to not have as much duplicative information in the reference doc. We should link out to the main doc and rely on that for explaining the Airflow components. Imo this reference should just serve as a quick, well, reference for someone who wants each option listed out in their browser or likes reading docs more than CLI help text.

2022-01-26 12:54 UTC, jwitz commented on sidebarsCloud.js
> +        },
This menu will start collapsed by default in the sidebar, so you won't see these commands unless you're intentionally clicking into the reference

2022-01-26 13:05 UTC, jwitz commented
@paolaperaza New draft should be more consistent based on the notes you made. My main comments had to do with linking out to external docs vs. including more information in the reference (I think we should link out more/ include less in the reference in an attempt to maintain single sources of truth).

At least in the CLI references I checked (Azure, Heroku, AWS, GitHub) there are no sample outputs. I think this is appropriate given that outputs might look slightly different for users, and the fact that any user referencing this will likely have the CLI ready to test these commands themselves. Also increases maintenance time if we end up changing help text/ CLI workflows over different versions.

2022-02-01 15:07 UTC, sunkickr requested changes

2022-02-01 15:15 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-init.md
> +| `--name`            | Name of your Astronomer project                                                                                    | Any string                  |
Which one, `name` or `airflow-version`?

2022-02-01 16:28 UTC, jwitz commented
This PR should now have changes based on @sunkickr 's comments, which should all be resolved

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-auth-login.md
> +```
The `cloud.astronomer.io` is still optional right?

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-completion.md
> +astrocloud completion <shell>
Should this be `astrocloud completion <shell> > <local-path>`?

What happens if a user literally just runs `astrocloud completion zsh`?

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-completion.md
> +```
Is this just for zsh? Or is this the same across shells?

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-deploy.md
> +You can specify a Deployment's namespace in the command, or leave the command options blank to select from a list of all Deployments that you have access to. To retrieve a Deployment's namespace, go
```suggestion
If you run `astrocloud deploy`, you'll be prompted to select from a list of all Deployments that you have access to across Workspaces. To automate this action more easily, you can bypass this prompt and specify a Deployment's namespace in the command. To retrieve a Deployment's namespace, go to the Deployment's information page in the Astronomer UI and copy the value under **Namespace**.
```

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-deployment-list.md
> +# Shows Deployments from all Workspaces that you're authenticated to
```suggestion
# Shows Deployments from all Workspaces that you have access to
```

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-ps.md
> +List all Docker containers running in your local Airflow environment, including the Airflow Webserver, Scheduler, and Postgres database. This command works similarly to [`docker ps`](https://docs.doc
Might be nice to list the metadata that gets outputed on this command? E.g.

- Container ID
- Created
- Status
- Ports
- Names

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-start.md
> +Build your Astronomer project into a Docker image and spin up local a local Docker container for each Airflow component.
```suggestion
Build your Astronomer project into a Docker image and restart all local containers for each Airflow component to run this Docker image.
```

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-start.md
> +This command can be used regularly to start and run any Astronomer project locally. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
```suggestion
This command can be used regularly to run an Astronomer project locally and apply changes as you test and troubleshoot DAGs. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
```

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-workspace-switch.md
> +Switch to another Workspace. After running the command, you are presented with a list of all Workspaces that you have access to. Then, to switch to a given Workspace, enter the number next to the Wor
```suggestion
Switch to another Workspace. After running the command, you will be prompted to select from a list of all Workspaces in your Organization that you have access to. To switch to a given Workspace, enter the number next to the Workspace's name in the list.
```

2022-02-01 16:32 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-workspace-switch.md
> +- [`astrocloud workspace switch`](cli-reference/astrocloud-workspace-list.md)
```suggestion
- [`astrocloud workspace list`](cli-reference/astrocloud-workspace-list.md)
```

2022-02-01 16:40 UTC, sunkickr commented on cloud/cli-reference/astrocloud-workspace-list.md
> +Show a list of all Workspaces that you have access to.
@paolaperaza yes

2022-02-01 16:44 UTC, sunkickr commented on cloud/cli-reference/astrocloud-auth-login.md
> +```
yes users should just use `astrocloud auth login`. `astrocloud auth login cloud.astronomer.io` is redundant. `cloud.astronomer.io` is the only option and is the default

2022-02-01 16:46 UTC, sunkickr commented on cloud/cli-reference/astrocloud-completion.md
> +Generate completion scripts for Astronomer Cloud commands. You can modify the generated scripts and add them to the appropriate directory to customize your command line autocompletion behavior.
Example: if you type `astrocloud au` and click tab `astrocloud auth` should appear press tab again you would get `astrocloud auth login` again you would get `astrocloud auth logout`. Iv never used it but apparently some people on gen 1 use it

2022-02-01 16:48 UTC, sunkickr commented on cloud/cli-reference/astrocloud-completion.md
> +astrocloud completion <shell>
where did you see `astrocloud completion <shell> > <local-path>`? Iv never seen that before

2022-02-01 16:48 UTC, sunkickr commented on cloud/cli-reference/astrocloud-completion.md
> +```
works the same for bash

2022-02-01 16:52 UTC, jwitz commented on cloud/cli-reference/astrocloud-completion.md
> +```
just for zsh, adding some more info here to make it clear that this is all one example

2022-02-01 16:52 UTC, sunkickr commented on cloud/cli-reference/astrocloud-deploy.md
> +
that makes sense to me. not how it is laid out in cobra CLI but may lead to less confusion

2022-02-01 16:53 UTC, sunkickr commented on cloud/cli-reference/astrocloud-dev-logs.md
> +| `--webserver`            | Show only Webserver logs                                                                                  | ``                 |
There are no workers locally since it is running the local executor

2022-02-01 17:08 UTC, jwitz commented on cloud/cli-reference/astrocloud-dev-start.md
> +This command can be used regularly to start and run any Astronomer project locally. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
Not keen on mentioning troubleshooting if we're not linking out to troubleshoot docs, esp since the command itself isn't necessarily tied to troubleshooting in the same way that `astro dev kill` is

2022-02-01 17:43 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-completion.md
> +Generate completion scripts for Astronomer Cloud commands. You can modify the generated scripts and add them to the appropriate directory to customize your command line autocompletion behavior.
```suggestion
Generate completion scripts for Astronomer Cloud CLI commands. You can modify the generated scripts and add them to the appropriate directory to customize your command line autocompletion behavior.

For example, you could set automation such that typing `astrocloud au` autocompletes to `astrocloud auth` if you press **TAB** on your keyboard and `astrocloud auth login` or `astrocloud auth logout` if you press **TAB** again.

This command is helpful for users interacting with the CLI on a regular basis.
```

2022-02-01 17:47 UTC, paolaperaza approved these changes
Ok I think this LGTM!

2022-02-01 17:47 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-completion.md
> +astrocloud completion <shell>
Ok - I'll defer to you two, but I just got confused by the example -

`$ astrocloud completion zsh > /usr/local/share/zsh/site-functions/_astrocloud`

2022-02-01 17:47 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-start.md
> +Build your Astronomer project into a Docker image and spin up local a local Docker container for each Airflow component.
Yea das fine - I replaced `restart` with just `start`

2022-02-01 17:53 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-completion.md
> +Generate completion scripts for Astronomer Cloud commands. You can modify the generated scripts and add them to the appropriate directory to customize your command line autocompletion behavior.
Added suggestion based on this example since there's (currently) no other place for it

2022-02-01 17:54 UTC, paolaperaza commented on cloud/cli-reference/astrocloud-dev-logs.md
> +| `--webserver`            | Show only Webserver logs                                                                                  | ``                 |
whoops im dumb - ignore!

2022-02-01 17:55 UTC, paolaperaza commented
Actually! One more thing. Can we rename this from `CLI Reference Guide` to `CLI Command Reference`?

2022-02-01 18:12 UTC, sunkickr approved these changes

2022-02-03 22:07 UTC, paolaperaza approved these changes
Adjusting naming on all files from "Guide" to "Command Reference" but this LGTM

2022-02-03 22:07 UTC, paolaperaza commented on sidebarsCloud.js
> +          label: 'CLI Reference Guide',
```suggestion
          label: 'CLI Command Reference',
```

2022-02-03 22:07 UTC, paolaperaza commented on cloud/cli-reference.md
> +sidebar_label: 'CLI Reference'
```suggestion
sidebar_label: 'CLI Command Reference'
```

2022-02-03 22:12 UTC, merged