Add ready-to-use minimal Deployment template
astronomer/docs pull request #2965
Opened 2023-10-19 07:32 UTC by manmeetkaur

Resolves #2885

2023-10-19 13:57 UTC, jwitz requested changes
@manmeetkaur overall looks good. I have an idea for how to reconfigure the options for creating the template file, lmk what you think!

2023-10-19 13:57 UTC, jwitz commented on astro/deployment-file-reference.md
> +The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for a Deployment with CeleryExecutor. This section is not applicable to Deployments running with the Kubernetes exe
```suggestion
The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for Deployments that use the celery executor. 
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +1. To create a new Deployment you can either copy and save the following template to a `yaml` file, or follow the steps in [Create a template file for a Deployment](#create-a-template-file-or-deploym
```suggestion
1. Run the following command to create a template file based on an existing Deployment and export it to your local machine:

    ```sh
    astro deployment inspect <deployment-id> --template > template-file.yaml
    ```

```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
```suggestion
  :::tip

  To create a template file that's not based on an existing Deployment, you can alternatively copy one of the following templates into an empty file named `template-file.yaml` on your local machine:
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +          {label: 'Hosted Dedicated', value: 'hosted-dedicated'},
```suggestion
          {label: 'Standard cluster', value: 'standard'},
          {label: 'Dedicated cluster', value: 'dedicated'},
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +      groupId= "create-a-cluster"
```suggestion
      groupId= "create-a-deployment-using-a-template-file"
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +      defaultValue="hosted-shared"
```suggestion
      defaultValue="standard"
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +  <TabItem value="hosted-shared">
```suggestion
  <TabItem value="standard">
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +  <TabItem value="hosted-dedicated">
```suggestion
  <TabItem value="dedicated">
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +  The `cluster_name` field must include the name of the dedicatd cluster that exists in your Astro Organization. For possible values of `region`, see [Available regions for your cloud provider](resou
```suggestion
  
  The `cluster_name` field must include the name of the dedicated cluster that exists in your Astro Organization.
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +  Note that for a Deployment on a Standard cluster, both the `region` and `cluster-name` parameters contain the region name as per your cloud provider. See [Available regions for your cloud provider]
```suggestion
  
  Note that for Deployments on a standard cluster, the `region` and `cluster-name` parameters must botrh contain the region name for the standard cluster. See [Available regions for your cloud provider](resource-reference-hosted.md#standard-cluster-configurations). 
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
```suggestion
  
  These are the minimum values required to create a Deployment using a template file. Any configurations not specified are set to default values. To add more configurations, see [Deployment file reference](deployment-file-reference.md).
  
  :::
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +  Before you use this template file to create a Deployment, keep the following in mind:
```suggestion
2.  Adjust the template file values for the Deployment you want to create. When working with template files, keep the following in mind:
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - The `name` field must include a unique name for the Deployment in the Workspace.
```suggestion
    - The `name` field must include a unique name within the Workspace. 
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - For possible values of `cloud_provider`, `executor` and `scheduler_size`, see [Options for `astro deployment create`](cli/astro-deployment-create.md#options).
```suggestion
    - The possible values for `cloud_provider`, `executor`, and `scheduler_size` are the same possible values when you create a Deployment with [`astro deployment create`](cli/astro-deployment-create.md#options). 
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +          runtime_version: 9.1.0
```suggestion
```
Do you know if it's possible to not set this and have it default to latest? Would make maintaining these docs a lot easier in the future.

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
```suggestion
```
This tip isn't related to Deployment files specifically

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
>  2. Run the following command to create the Deployment:
```suggestion
3. Run the following command to create the Deployment:
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
>  3. (Optional) Either open the Cloud UI or run the following command to confirm that you successfully created your Deployment:
```suggestion
4. (Optional) Either open the Cloud UI or run the following command to confirm that you successfully created your Deployment:
```

2023-10-19 13:57 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
I still thinking copying a the configuration from a Deployment is the most reliable way to get a working template file with the correct configurations. For that reason, I think we should include this minimal template, but as a tip for users who can't or don't want to copy from an existing Deployment. It also helps provide a single definitive path for someone who just wants this to work - no workflow choices are necessary if they follow these steps as-is.

2023-10-25 12:09 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
hmm.. tbh I think it is important because it refers a core component of a Deployment and hence a Deployment file. There is a value-add in referring this for a new Astro user.

2023-10-25 13:03 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +          executor: KubernetesExecutor
```suggestion
          executor: CeleryExecutor
```

Just realized we make the default here KE, but it's still celery executor in the Cloud UI. Might be better to keep things as consistent with the UI as possible.

2023-10-25 13:03 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
Why is a new Astro user creating Deployments with a Deployment file? I think we can assume that someone trying to automate Deployment creation has some working knowledge of Deployments. 

Similarly then, why are we not also linking to explain scheduler size, executor, cluster type, etc?

2023-10-27 06:13 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
May be I did not explain it well the term "new" . So assume I am an Astro user who is 3 months old and I am ready to "productionize", so I choose to automate the deployment creation stuff. I am not going to remember all the Airflow version vis-a-vis Runtime, so all I want is to be able to click a link to find the relation between these versions. I can also go to Cloud UI and click on create a deployment and find the version or just search the docs to find that - but if this link is easily accessible, it would be really nice. :)

Also, I did add the link to the command reference of options which explains about scheduler size, executor and cluster ; but it does not about the versions. 

This is my thought process, at the end it is a team call. :)

2023-10-27 06:21 UTC, manmeetkaur commented on astro/manage-deployments-as-code.md
> +          runtime_version: 9.1.0
missed responding to this, I have only included fields that are minimally required (not sure if that is a word 🤔 ) by testing almost each field. And even if it is not, I would still recommend putting it here for clarity. What I would suggest and wanted but couldn't research was - to embed the SiteVariable like we have in other pages.

2023-10-31 20:10 UTC, lzdanski reviewed
Found a couple typos and tried to clarify some things

2023-10-31 20:10 UTC, lzdanski commented on astro/deployment-file-reference.md
> +To delete an environment variable, remove the lines that contain its key, its value, and other associated fields, then reapply the file to the Deployment. Any variables which exist on the Deployment
```suggestion
When you inspect a Deployment, the value of secret environment variables do not appear in the Deployment file.  

To delete an environment variable, remove the lines that contain its key, its value, and other associated fields. Then, reapply the file to the Deployment. Any variables that exist on the Deployment, but are not included in the most recently applied Deployment file, are deleted. 
```

2023-10-31 20:10 UTC, lzdanski commented on astro/deployment-file-reference.md
> +The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for Deployments that use celery executor. This section is not applicable to a Deployment that uses Kubernetes execu
```suggestion
The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for Deployments that use celery executor. This section is not applicable to Deployments that use Kubernetes executor.
```

2023-10-31 20:10 UTC, lzdanski commented on astro/deployment-file-reference.md
> +If you don't enter specific values for the `default` worker queue for a Deployment, default values based on the worker types available on your cluster are applied. Each additional worker queue must i
```suggestion
If you don't enter specific values for the `default` worker queue for a Deployment, Astro uses default values based on the worker types available on your cluster. Each additional worker queue must include a `name` and `worker_type`. The Astro CLI uses default values for any other unspecified fields.
```

2023-10-31 20:10 UTC, lzdanski commented on astro/manage-deployments-as-code.md
> +
My impression of this page is that it's ideally for users at that **200 level** familiarity of Astro. They maybe have made some deployments from various resources, tried tutorials and use cases, but are now either getting ready to move into a more mature model and just want a way of testing this process with a minimal template _or_ are doing some kind of exploration/POC and don't have anything of their own that they want to use. The minimal template allows users to learn the process with something that's been tried and tested by us, without having to diagnose the source of problems that might be coming from their own Deployment files.

This also gives all users the same frame of reference to start with before identifying what their customizations would need to be in case when they copy from an existing Deployment or try to make their own from scratch there _is_ something that causes a problem.

2023-11-01 10:22 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +
I don't mind which strategy is put in the tip box, I just feel strongly that we should have a single path for users getting started instead of starting them out with an "or" decision point.

2023-11-01 10:24 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
Thinking this over, I still feel it's better to only include information here that's specific to using a Deployment file, rather than information related generally to creating a Deployment.

2023-11-01 10:31 UTC, jwitz approved these changes
The structure of this is still not quite right, but I'm happy to merge and do a follow-up so that we get the content out there. 

We currently have steps to _create a template file_ in "Create a Deployment using a template file", instead of "_Create a template file_ or Deployment file". Unless we change the headers, we're being inconsistent with where we put the content.

2023-11-01 10:31 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +1. To create a new Deployment you can either copy and save the following template to a `yaml` file, or follow the steps in [Create a template file for a Deployment](#create-a-template-file-or-deploym
```suggestion
1. Copy one of the following templates to a local `yaml` file:
```

2023-11-02 15:41 UTC, lzdanski commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
As someone who _regularly_ gets errors due to problems with my runtime version and Astro projects, I agree that this is a value-add to have a pointer for declaring a runtime version here. I'm mainly thinking about users who are moving to managing deployments as code instead of potentially working through the UI or with `astro dev init`. Maybe we can come back to it if we get negative feedback or reviews from other folks outside our team?

2023-11-03 12:02 UTC, jwitz approved these changes

2023-11-03 12:02 UTC, jwitz commented on astro/deployment-file-reference.md
> +By default, each variable is created as a non-secret variable. To set any new or existing environment variables as secret in, specify `is_secret: true` in the same section as the key and value. For e
```suggestion
By default, each variable is created as a non-secret variable. To set any new or existing environment variables as secret, specify `is_secret: true` in the same section as the key and value. For example: 
```

2023-11-03 12:02 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - For choosing the correct `runtime_version`, refer to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) and [Astro Runtime release
```suggestion
    - See to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) to choose your Astro Runtime version.
```

2023-11-03 12:03 UTC, jwitz commented on astro/manage-deployments-as-code.md
> +    - See to [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) to choose your Astro Runtime version.
```suggestion
    - See [Airflow and Astro Runtime version parity](runtime-image-architecture.md#astro-runtime-and-apache-airflow-parity) to choose your Astro Runtime version.
```

2023-11-03 12:03 UTC, merged