0.23.12 Changelog
astronomer/docs pull request #298
Opened 2021-03-23 18:21 UTC by jwitz

This PR only addresses the changelog component of our 0.23.12 docs. Additional changes to other docs will arrive in a separate PR (to be linked here).

I wrote small descriptions for the changes listed [here](https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.23.12+). If these look good, I'll additionally include them in our v0.23 docs.

2021-03-23 19:15 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Hyphenated Helm release names cause the 0.23 upgrade script to break. ([Source](https://github.com/astronomer/astronomer/pull/1026))
this was not part of the Astro platform 0.23.11 artifact, but part of the upgrade script only. I dont think we need to include this.

2021-03-23 19:16 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Users with the Deployment Editor role, regardless of their workspace permissions, are denied access to the Airflow UI endpoint. ([Source](https://github.com/astronomer/astronomer/pull/1010)
The pull request and the bug fix are unrelated I think. 

This bug was fixed in AC.

2021-03-23 19:18 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> -Latest Patch Release: **v0.23.9**
What happened to 0.23.11, did we not publish release notes for it?

2021-03-23 20:31 UTC, paolaperaza requested changes
@jwitz Went through the v0.23.12 GitHub issues and made some copy suggestions here to add a bit more context to some line-items.

I also made a comment on this, but I'd say we should add a section for Airflow 1.10.15 and then patch AC versions that have security fixes with corresponding links to changelogs - lmk what you think.

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- Refactored and improved security for quay.io/astronomer images.
Hm, what images are we talking about here? Our Airflow/AC images, or platform ones? If it's just `ap-registry` and `ap-db-bootstrapper` (per what I see in GH), I might just specify those, otherwise the `quay.io/astronomer` path is too general.

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- Refactored and improved security for quay.io/astronomer images.
If we're talking about AC and there were a bunch of security fixes in 1.10.15 and in other AC patches, I'd lean towards having a specific section for that, which even links out to changelog for those patches and for 1.10.15 itself.

Given the 1.10.15 release, I might even do `### Support for Airflow 1.10.15` and then `### Support for latest Astronomer Certified Patch Releases` like we do here: https://www.astronomer.io/docs/enterprise/v0.16/resources/release-notes

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- Removed E2E testing from some images to improve security.
What Gh issue does this map to?

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: fixed CVEs in:
```suggestion
- BugFix: Addressed CVEs found in the following platform images:
```

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix:  Setting `AIRFLOW__KUBERNETES__FS_GROUP:50000` in the Astronomer UI doesn't force the fsGroup setting in the pod template. ([Source](https://github.com/astronomer/airflow-chart/pull/190))
```suggestion
- BugFix: Setting `AIRFLOW__KUBERNETES__FS_GROUP:50000` in the Astronomer UI doesn't force the fsGroup setting in the pod template. ([Source](https://github.com/astronomer/airflow-chart/pull/190))
```

Is `in the pod template` referring to the `pod_template` file?

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Nginx ingress scraping only scraped one pod at a time. ([Source](https://github.com/astronomer/astronomer/pull/1010))
```suggestion
- BugFix: Nginx ingress scraping for Prometheus was previously configured with the `service` role and could only scrape and report metrics for one pod at a time. Now, that pod is set to have the `endpoints` role and can collect aggregated metrics from all nginx replicas. ([Source](https://github.com/astronomer/astronomer/pull/1010))
```

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Users with the Deployment Editor role, regardless of their workspace permissions, are denied access to the Airflow UI endpoint. ([Source](https://github.com/astronomer/astronomer/pull/1010)
Ya, I wouldn't include this here - this is in AC 1.10.15.

Changelog where this is referenced: https://github.com/astronomer/ap-airflow/blob/master/1.10.15/CHANGELOG.md
Commit: https://github.com/astronomer/airflow/commit/950028f93e1220d49629aea10dfbaf1173b8910b

2021-03-23 20:31 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: New schedulers are unable to adopt running/orphaned pods (Kubernetes executor tasks) due to a permissions error. ([Source](https://github.com/astronomer/airflow-chart/pull/191))
```suggestion
- BugFix: New Airflow Schedulers are unable to adopt a running Kubernetes Executor task due to a permissions error, causing that task to be set to `Queued` and then terminated. ([Source](https://github.com/astronomer/airflow-chart/pull/191))
```

2021-03-23 21:18 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- Network Load Balancer (NLB) is now the default AWS load balancer. Previously, the default was Classic Load Balancer.
hmm .. now that we have the ability to configure the behavior of Ingress resources in a generic way by adding annotations, I think we have removed the change to make nlb the default load balancer on EKS and are letting users do it themselves. Is that right @danielhoherd ?

2021-03-23 21:24 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- Refactored and improved security for quay.io/astronomer images.
There are a whole number of platform images that were updated in this release. ap-registry, ap-db-bootstrapper, ap-elasticsearch, ap-fluentd, ap-curator, ap-nginx, ap-nginx-es, ap-grafana, ap-kibana, ap-nats-server, bitnami/postgresql, quay.io/prometheus/node-exporter, ap-postgres-exporter (I referred to this commit: https://github.com/astronomer/astronomer/commit/4e3fc85b493eefb3c29ed17ed2a8914744e28ce8)

2021-03-23 21:25 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- Removed E2E testing from some images to improve security.
https://github.com/astronomer/issues/issues/2631

2021-03-23 21:26 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- Values of Variables defined in Astronomer UI now properly reflect values in Kubernetes secret.
Absolutely a bug!

2021-03-23 21:29 UTC, vishwas-astro commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: fixed CVEs in:
There are more than just 2 images where we have resolved vulnerabilities. Please see my above comment.

2021-03-24 13:11 UTC, jwitz commented on enterprise/next/09_resources/01_release-notes.md
> +- Values of Variables defined in Astronomer UI now properly reflect values in Kubernetes secret.
I cut the last clause from this, as stating it rendered incorrectly implies that it wasn't doing the expected behavior we mention here.

2021-03-24 13:30 UTC, jwitz commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix:  Setting `AIRFLOW__KUBERNETES__FS_GROUP:50000` in the Astronomer UI doesn't force the fsGroup setting in the pod template. ([Source](https://github.com/astronomer/airflow-chart/pull/190))
It looks like its named `pod-template-file` in the PR, so I think just adding "file" here will be enough context.

2021-03-24 13:45 UTC, jwitz commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Nginx ingress scraping only scraped one pod at a time. ([Source](https://github.com/astronomer/astronomer/pull/1010))
I'm a little confused about what voice we take for a BugFix. I've seen previous bugs framed as the broken behavior (written as if it's still happening), whereas this one seems to focus on the current fixed behavior.  Do you have an opinion going forward about how we want to frame these?

2021-03-24 13:55 UTC, jwitz commented
@paolaperaza Thanks for the comments and helping me through my first go at this! There's a few outstanding questions from Vishwas, but otherwise I think I've integrated everything here.

2021-03-24 18:00 UTC, paolaperaza approved these changes
LGTM @jwitz ! Thanks for taking this on.

Note: Make sure to change `Release Date:` to reflect actual release date before this is merged.

2021-03-24 18:00 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +- Removed E2E testing from some images to improve security.
```suggestion
- Removes an `e2eTest` image that is no longer maintained from Astronomer's `default.yaml` file.
```

I think this wording is more accurate given what I see here: https://github.com/astronomer/astronomer/pull/1033

2021-03-24 18:00 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +- Airflow task logs are no longer missing in the Airflow UI on IKS + 0.23.9. ([Source](https://github.com/astronomer/astronomer/pull/1023))
```suggestion
- Airflow task logs are no longer missing in the Airflow UI for IKS environments running Astronomer v0.23.9. ([Source](https://github.com/astronomer/astronomer/pull/1023))
```

2021-03-24 18:00 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +- Nginx ingress scraping for Prometheus now scrapes and report metrics for all pods at once, as opposed to one pod at a time. ([Source](https://github.com/astronomer/astronomer/pull/1010))
```suggestion
- Nginx ingress scraping for Prometheus now scrapes and reports metrics for all `nginx` replicas in aggregate, as opposed to one pod at a time. ([Source](https://github.com/astronomer/astronomer/pull/1010))
```

2021-03-24 18:02 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- BugFix: Nginx ingress scraping only scraped one pod at a time. ([Source](https://github.com/astronomer/astronomer/pull/1010))
Addressed in separate meeting - resolving!

2021-03-24 18:09 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +    - `ap-vendor/fluentd`
This list feels a lil long - maybe list these images horizonatally? I.e.:

> - Addressed CVEs found in the following platform images: `ap-curator`, `ap-db-bootstrapper`, `ap-fluentd`...

2021-03-29 14:01 UTC, paolaperaza reviewed
@jwitz Came back to this PR as I wrote up the email for Cloud customers and made some additional comments - let me know what you think.

> Note: I'm waiting on confirmation from Vishwas, but if the platform issues related to Airflow 2.0.1 were fixed in this release, we'll have to add a section around support for that version of Airflow.

2021-03-30 14:39 UTC, paolaperaza approved these changes
Two quick comments on wrong links @jwitz, but this looks good. TY!

2021-03-30 14:39 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +[Airflow 2.0.1](https://github.com/apache/airflow/releases/tag/2.0.1) brings key fixes and performance improvements to some of the new features that arrived with [Airflow 2.0](https://www.astronomer.
```suggestion
[Airflow 2.0.1](https://github.com/apache/airflow/releases/tag/2.0.1) brings key fixes and performance improvements to some of the new features that arrived with [Airflow 2.0](https://www.astronomer.io/docs/cloud/stable/customize-airflow/upgrade-to-airflow-2).
```

cloud link hur

2021-03-30 14:39 UTC, paolaperaza commented on enterprise/v0.23/09_resources/01_release-notes.md
> +[Airflow 2.0.1](https://github.com/apache/airflow/releases/tag/2.0.1) brings key fixes and performance improvements to some of the new features that arrived with [Airflow 2.0](https://www.astronomer.
```suggestion
[Airflow 2.0.1](https://github.com/apache/airflow/releases/tag/2.0.1) brings key fixes and performance improvements to some of the new features that arrived with [Airflow 2.0](https://www.astronomer.io/blog/introducing-airflow-2-0).
```

Ugh we don't have an "Upgrade to Airflow 2.0" doc on Enteprise 😞

2021-03-30 14:54 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +- Dispose connections when running tasks with os.fork & CeleryExecutor [(#13265)](https://github.com/apache/airflow/pull/13265)
@jwitz Should we add:

> 
> To upgrade to AC 2.0.1, add our new Debian image to your Dockerfile:
> 
> ```
> FROM quay.io/astronomer/ap-airflow:2.0.1-buster-onbuild
> ```
> 
> For detailed guidelines on how to upgrade Airflow on Astronomer, read [Upgrade Airflow](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions). For more information on 2.0.1, check out the [Airflow Release](https://github.com/apache/airflow/releases/tag/2.0.1) or the corresponding [AC 2.0.1 changelog](https://github.com/astronomer/ap-airflow/tree/master/2.0.1/buster).

2021-03-30 14:54 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +- Dispose connections when running tasks with os.fork & CeleryExecutor [(#13265)](https://github.com/apache/airflow/pull/13265)
(and the same for 1.10.15)?

2021-03-30 15:21 UTC, jwitz commented
@paolaperaza @vishwas-astro Just updated this PR to:

1. Remove mentions of Airflow 2.0.1 support
2. Add a link to our upgrade docs
3. Make Cloud release notes consistent with Enterprise for some earlier versions

2021-03-30 15:31 UTC, kaxil commented on cloud/stable/06_resources/01_release-notes.md
> +### Support for Airflow 2.0.1
+1

2021-03-30 15:46 UTC, paolaperaza reviewed
3 more small comments based on latest changes @jwitz

2021-03-30 15:46 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +- BugFix: A SysAdmin Service Account created via the Houston API does not have right to see all Workspaces and can only be seen by a SysAdmin user in the Workspace(s) they're a part of.
```suggestion
```

Not applicable to Cloud 👀

2021-03-30 15:46 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +- BugFix: Upgrade from Airflow 2.0.0 to Airflow 2.0.1 via the Astronomer CLI fails
```suggestion
```

The first not applicable to Cloud, the second no longer given 2.0.1 drop 😞

2021-03-30 15:46 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +For local development guidelines, read [Get Started with Airflow 2.0](https://www.astronomer.io/guides/get-started-airflow-2).
```suggestion

Astronomer now offers full support for [Airflow 2.0](https://www.astronomer.io/blog/introducing-airflow-2-0/), a momentous open-source release that includes a refactored Scheduler, over 30 UI/UX improvements, a new REST API, and much more.

In support for Airflow 2.0, Astronomer has:

- Support for [Multiple Schedulers](https://www.astronomer.io/blog/airflow-2-scheduler) (*added in v0.22.3*)
- A mechanism to ensure that users migrate to Airflow 1.10.14+ prior to upgrading to 2.0.0+ (*added in v0.23.5*)
- Support for Airflow's ["upgrade check"](https://airflow.apache.org/docs/apache-airflow/v0.23/upgrade-check.html) in the Astronomer CLI (`$ astro dev upgrade-check`) (*added in v0.23.5*)

For guidelines on how to upgrade, read [Upgrade to Airflow 2.0 on Astronomer](https://www.astronomer.io/docs/cloud/stable/customize-airflow/upgrade-to-airflow-2).
```

2021-03-30 15:47 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +For local development guidelines, read [Get Started with Airflow 2.0](https://www.astronomer.io/guides/get-started-airflow-2).
Kinda weird because these things were all added in previous versions (not the case for Enterprise). I think it's cool to keep them, but I did suggest adding the corresponding platform versions at which time that functionality technically became available.

2021-03-30 15:48 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +### Support for Airflow 2.0.1
Oh man, we were behind on that announcement 😞  Should be addressed now.

2021-03-30 15:57 UTC, paolaperaza commented on enterprise/next/09_resources/01_release-notes.md
> +- Network Load Balancer (NLB) is now the default AWS load balancer. Previously, the default was Classic Load Balancer.
@vishwas-astro confirmed today that this line is correct! Resolving.

2021-03-30 16:00 UTC, paolaperaza commented on cloud/stable/06_resources/01_release-notes.md
> +For more information on upgrading to Airflow 1.10.15 on Astronomer, read [Upgrade Airflow](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions).
@jwitz Let's add these additional resources/links? I know they're both in the upgrade doc, but I can't see how adding them here for reference would hurt.

> For detailed guidelines on how to upgrade Airflow on Astronomer, read [Upgrade Airflow](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions). For more information on 1.10.15, check out the [Airflow Release](https://airflow.apache.org/docs/apache-airflow/1.10.15/changelog.html) or the corresponding [AC 1.10.5 changelog](https://github.com/astronomer/ap-airflow/blob/master/1.10.5/CHANGELOG.md).

2021-03-30 17:10 UTC, merged