Enterprise patch upgrade instructions
astronomer/docs pull request #30
Opened 2020-09-04 19:53 UTC by paolaperaza

This PR addresses this GH Issue: https://github.com/astronomer/issues/issues/1633

I updated our existing "Upgrade Astronomer" doc ([lives here](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-astronomer/)) with:

- An overview of our upgrade policy
- Explanation of platform versioning
- Instructions for patch upgrades, adopted from: https://github.com/astronomer/astronomer/tree/master/bin/migration-scripts#patch-version-updates

The README in the repo I linked above has a lot more info in terms of checking to make sure pod are up, instructions for minor upgrades etc. I wasn't sure what all to include but decided to start narrow to make sure we're clear/accurate and then add info as needed.

@sjmiller609 Since I believe you wrote up those instructions, can you give this a look and make sure it's accurate? A few specific questions:

- Is there a step we can add for customers to "confirm" the patch upgrade was successful?
- Is the script you provided supposed to be prescriptive or do users need to modify it further somehow?
- Any suggestions on language around Airflow chart changes? Will patch releases by definition not include changes to the airflow chart?
- Is this still accurate given eventual consistency?
> The patch upgrade process will NOT affect running tasks if `upgradeDeployments.enabled=false`

2020-09-04 20:05 UTC, danielhoherd commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Ensure you have a copy of your Astronomer `config.yaml`
I don't know if ours does, but some renderers treat the lack of a blank line between content and headings differently, so we should probably be consistent with these.
```suggestion

### Ensure you have a copy of your Astronomer `config.yaml`
```

2020-09-04 20:06 UTC, jpweber commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +> **Note:** Astronomer v0.16.5 and beyond includes "Eventual Consistency" functionality that allows for Airflow Deployments to remain unaffected through a platform upgrade that includes changes to [t
I would suggest we don't put the phrase "eventual consistency" in our docs here. We have used it as jargon internally, but the real meaning of the term is different from what we're describing. I don't want to create confusion with customers that think we mean something else. 

May I suggest something like 
Astronomer v0.16.5 and beyond includes an improved upgrade process that allows Airflow Deployments to remain unaffected through a platform upgrade that includes changes to [the Airflow Chart](https://github.com/astronomer/airflow-chart)

2020-09-08 01:00 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Ensure you have a copy of your Astronomer `config.yaml`
Good callout, @danielhoherd ! Typo on my part. Fixed.

2020-09-08 01:02 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +> **Note:** Astronomer v0.16.5 and beyond includes "Eventual Consistency" functionality that allows for Airflow Deployments to remain unaffected through a platform upgrade that includes changes to [t
Good call, @jpweber - wasn't sure on that one. Adjusted!

2020-09-08 03:39 UTC, paolaperaza commented
Alright, just applied that feedback - thanks all. @sjmiller609 Let me know if you have any final thoughts on those q's above and approve if this looks good to you.

2020-09-08 15:10 UTC, sjmiller609 requested changes

2020-09-08 15:10 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +            -f ./config.yaml \
```suggestion
            -f ./config.yaml \
            --reset-values \
```

2020-09-08 15:10 UTC, sjmiller609 commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +            -f ./config.yaml \
this is necessary to get the new default values instead of using previous default values.

2020-09-08 16:12 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +            -f ./config.yaml \
Done! Thanks @sjmiller609

2020-09-08 16:13 UTC, sjmiller609 approved these changes

2020-09-08 16:16 UTC, paolaperaza commented
Thanks all. Merging.

2020-09-08 16:16 UTC, merged