Snowpark Learn PR
astronomer/docs pull request #3084
Opened 2023-11-13 23:35 UTC by astronautyates

* Create usecase_snowpark_customer_analytics

* Rename usecase_snowpark_customer_analytics to use-case_snowpark_customer_analytics

* Update use-case_snowpark_customer_analytics

* Rename use-case_snowpark_customer_analytics to use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Create test.py

* Create startfile.py

* Add files via upload

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Add files via upload

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Update use-case_snowpark_customer_analytics.md

* Apply suggestions from code review

Try fixing build

---------

2023-11-14 00:12 UTC, kentdanas requested changes
@astronautyates have to run to an appt so only got through the first couple sections, but I will review the rest tomorrow morning! Leaving initial comments here in case you have a chance to address them before I review the rest.

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This guide demonstrates how to use Apache Airflow to orchestrate a machine learning pipeline leveraging the Snowpark provider and Snowpark ML for feature engineering and model tracking. While Snowpar
```suggestion
This use case demonstrates how to use Apache Airflow to orchestrate a machine learning pipeline leveraging the Snowpark provider and Snowpark ML for feature engineering and model tracking. While Snowpark ML has its own support for models similar to scikit-learn, this code demonstrates a "bring-your-own" model approach showing the use of open-source scikit-learn along with Snowpark ML model registry and model serving in an Airflow task rather than Snowpark user-defined function (UDF).  
```
Do we have Snowpark provider docs we can link to here?

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +## Set-up the project
```suggestion
## Clone the project
```
Let's keep the language on the headers consistent with other published use cases.

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This demo also shows the use of the Snowflake XCOM backend which supports security and governance by serializing all task in/output to Snowflake tables and stages while storing in the Airflow XCOM ta
```suggestion
This demo also shows the use of the Snowflake XCom backend which supports security and governance by serializing all task in/output to Snowflake tables and stages while storing in the Airflow XCom table a URI pointer to the data.
```

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +- sourcing structured, unstructured and semistructured data from different systems
```suggestion
- Sourcing structured, unstructured and semistructured data from different systems.
```
Same edits with all the other bullets - capitalize first word

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This demonstration shows how to build a customer analytics dashboard.  Sissy-G Toys is a fictitious online retailer for toys and games.  The GroundTruth customer analytics application provides market
```suggestion
This demonstration shows how to build a customer analytics dashboard for a fictitious online retailer for toys and games. The application uses machine learning models for audio transcription, natural language embeddings and sentiment analysis on structured, semi-structured and unstructured data.
```

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +title: "Production-ready ML with Airflow, Snowpark, and Weaviate"
```suggestion
title: "ML for Customer Analytics with Airflow, Snowpark, and Weaviate"
```
What do you think of this title? I think we should be a little more specific than "ML", since a lot of these use cases are ML-related.

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +- AIRFLOW_CONN_SNOWFLAKE_DEFAULT
Let's put these in a text block like they appear in the .env file, instead of in bullet form. I think that will make it clearer what the user is supposed to update.

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +![A screenshot of the environment file structure](/img/use_case_images/snowpark_weaviate_use_case/use-case-snowpark_weaviate_filestructure_3.png)
```suggestion
```
I don't think the screenshot is necessary here since we're not referring to any of the files other than .env

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This demo assumes the use of a new Snowflake trial account with admin privileges.  A database named 'DEMO' and schema named 'DEMO' will be created in the DAG.  Running this demo without admin privile
This could be pulled out into a :::note box, and put below the text box with the env contents that need to be updated.

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +NOTE: Database and Schema names should be CAPITALIZED due to a bug in Snowpark ML.
```suggestion
:::note

Database and Schema names should be CAPITALIZED due to a bug in Snowpark ML.

:::
```

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +After the command finishes, open the the [Airflow UI](http://localhost:8080/) and press trigger the `customer_analytics` DAG using the play button. Then, monitor its status as it completes via the gr
```suggestion
After the command finishes, open the the [Airflow UI](http://localhost:8080/) and trigger the `customer_analytics` DAG using the play button. Then, monitor its status as it completes via the graph view.
```

2023-11-14 00:12 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +![A screenshot of the Airflow UI with active Customer Analytics DAG](/img/use_case_images/snowpark_weaviate_use_case/use-case-snowpark_weaviate_activeplaybutton_4.png)
Let's move the screenshot below the paragraph describing the docker containers.

2023-11-14 17:01 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This task group generates embeddings for our training comment data, twitter comment data, and for our transcribed support call data. These embeddings are generated as part of importing them into the
```suggestion
This task group generates embeddings for the training comment data, twitter comment data, and the transcribed support call data. These embeddings are generated as part of importing them into the Weaviate vector database. 
```

2023-11-14 17:03 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This task creates or replaces staging table within Snowflake, and then uses Snowpark python to extract call data and load it into that staging table. This stage is a directory table which means that
```suggestion
This task creates or replaces a staging table within Snowflake, and then uses Snowpark Python to extract call data and load it into that staging table. This stage is a directory table which means that the structure can be queried like any other table.
```

2023-11-14 17:03 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This task group uses Snowpark python to transform the structured data to get them in the proper format for the presentation layer and joining with prediction on the unstructured data and the sentimen
```suggestion
This task group uses Snowpark Python to transform the structured data into the proper format for the presentation layer and joining with prediction on the unstructured data and the sentiment classifier. 
```

2023-11-14 17:09 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This task group creates parallel tasks to upload many structured datasets from an Astronomer hosted S3 bucket into our Snowflake database.
```suggestion
This task group creates parallel tasks to upload structured datasets from an Astronomer hosted S3 bucket into the Snowflake database. 
```
Is the Astronomer hosted S3 bucket a public one that's storing the pre-processed data? Maybe we just say "public S3 bucket"? If I read "astronomer hosted S3 bucket" my initial thought is that's something I need to set up a version of myself, or need access to Astronomer, which I don't think is the case here.

2023-11-14 17:09 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +The second task group, “structured_data”, uses several dynamically generated task groups to load many structured datasets into our Snowflake database, before transforming them using snowpark, all in
```suggestion
The second task group, “structured_data”, uses several dynamically generated task groups to load many structured datasets into the Snowflake database, before transforming them using Snowpark, all in parallel. 
```

2023-11-14 17:10 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +In order to speed up the demo process the data has already been ingested into Weaviate and vectorized.  The data was then backed up and stored in the cloud for easy restore. This task will download t
```suggestion
In order to speed up the demo process, the data has already been ingested into Weaviate and vectorized.  The data was then backed up and stored in the cloud for easy restore. This task will download the backup.zip and make it available in a docker mounted filesystem for the `restore_weaviate` task.
```

2023-11-14 18:47 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +sidebar_label: "ML with Snowpark and Airflow"
Done i think!

2023-11-14 18:52 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +This guide demonstrates how to use Apache Airflow to orchestrate a machine learning pipeline leveraging the Snowpark provider and Snowpark ML for feature engineering and model tracking. While Snowpar
yep, updated

2023-11-14 18:56 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +This demo assumes the use of a new Snowflake trial account with admin privileges.  A database named 'DEMO' and schema named 'DEMO' will be created in the DAG.  Running this demo without admin privile
Cool think I got the syntax right

2023-11-14 18:58 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +![A screenshot of the Airflow UI with active Customer Analytics DAG](/img/use_case_images/snowpark_weaviate_use_case/use-case-snowpark_weaviate_activeplaybutton_4.png)
Done!

2023-11-14 18:59 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +This task group creates parallel tasks to upload many structured datasets from an Astronomer hosted S3 bucket into our Snowflake database.
Yep, sounds good i'll change it

2023-11-14 19:02 UTC, astronautyates commented
All resolved! LMK if I screwed anything up or you have further comments!

2023-11-14 21:17 UTC, kentdanas commented on sidebarsLearn.js
> +          'use-case-ml-airflow-snowpark-weaviate
```suggestion
          'use-case-ml-airflow-snowpark-weaviate'
```

2023-11-14 21:23 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This project consists of one DAG, [customer_analytics](https://github.com/astronomer/airflow-snowparkml-demo/blob/main/dags/customer_analytics.py) which demonstrates an end-to-end ML application work
@astronautyates think this comment was missed.

2023-11-14 21:24 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +Task ‘create_snowflake_objects’:
@astronautyates this one was missed too - this is the biggest change I'm requesting. Let me know if you have questions here.

2023-11-14 21:24 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +
@astronautyates this one too.

2023-11-14 21:26 UTC, kentdanas commented
@astronautyates looks like some of my comments weren't addressed. There are still some suggested edits, and some requests on structuring changes. Maybe everything in my second round came through in another email (that happens to me sometimes)? In any case, let me know if you have questions on the rest of it.

2023-11-15 13:55 UTC, astronautyates commented
Oh weird, sorry I didn't see any of these when I was reviewing in github,
will re-check rn!


On Tue, Nov 14, 2023 at 4:26 PM Kenten Danas ***@***.***>
wrote:

> @astronautyates <https://github.com/astronautyates> looks like some of my
> comments weren't addressed. There are still some suggested edits, and some
> requests on structuring changes. Maybe everything in my second round came
> through in another email (that happens to me sometimes)? In any case, let
> me know if you have questions on the rest of it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astronomer/docs/pull/3084#issuecomment-1811350123>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFYZZTMG3AVVV7VJGWEYYTYEPOYZAVCNFSM6AAAAAA7J5TYWKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJRGM2TAMJSGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-15 14:08 UTC, TJaniF commented
> Oh weird, sorry I didn't see any of these when I was reviewing in github, will re-check rn!

This is one of my biggest GH pet-peeves, if you change a line that had a comment on it the comment vanishes from the default "Files changed" view as "Outdated" and can be hard to refind among all other resolved and outdated comments. Happens to me all the time and when there are a lot of overlapping comments/suggestions I copy them into a file while working to not loose any 😅

2023-11-15 14:29 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +- AIRFLOW_CONN_SNOWFLAKE_DEFAULT
Done!

2023-11-15 14:32 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +This project consists of one DAG, [customer_analytics](https://github.com/astronomer/airflow-snowparkml-demo/blob/main/dags/customer_analytics.py) which demonstrates an end-to-end ML application work
Done, let me know if you think it needs addtional description

2023-11-15 14:33 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +Task ‘create_snowflake_objects’:
Forsure, will implement right now.

2023-11-15 15:32 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +This task creates or replaces staging table within Snowflake, and then uses Snowpark python to extract call data and load it into that staging table. This stage is a directory table which means that
Updated this section pretty thoroughly before reviewing this, think updates were in line with the goal here

2023-11-15 15:35 UTC, astronautyates commented
Yeah for some reason it had all of Kenten's later comments under hidden even though I had never read them..... Anyways, think I got all the comments covered now but let me know if I missed any again!

2023-11-15 21:34 UTC, kentdanas requested changes
@astronautyates this is looking good! A couple other pretty minor comments, and then this is good to move on to copy editing from @jwitz or @lzdanski

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# Setup Tasks
```suggestion
### Setup Tasks
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# Structured Data Ingestion and Transformation
```suggestion
### Structured data ingestion and transformation
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# Unstructured Data Ingestion and Transformation
```suggestion
### Unstructured data ingestion and transformation
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# Model Training
```suggestion
### Model training
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# Creating Reporting Tables
```suggestion
### Create reporting tables
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +# See Also
```suggestion
# See also
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +- https://docs.astronomer.io/learn/airflow-snowpark
This list looks good, but let's update these to linked text. So something like
- Documentation: [setup/teardown tasks](https://docs.astronomer.io/learn/airflow-setup-teardown)
- Tutorial: [orchestrating weaviate with Airflow](https://docs.astronomer.io/learn/airflow-weaviate)
etc.

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +This demo assumes the use of a new Snowflake trial account with admin privileges.  A database named 'DEMO' and schema named 'DEMO' will be created in the DAG.  Running this demo without admin privile
Only this paragraph should be part of the note box. The first paragraph about opening the .env and updating it should be regular text.

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +** The Snowflake `account` field of the connection should use the new `ORG_NAME-ACCOUNT_NAME` format as per [Snowflake Account Identifier policies](https://docs.snowflake.com/en/user-guide/admin-acco
```suggestion
The Snowflake `account` field of the connection should use the new `ORG_NAME-ACCOUNT_NAME` format as per [Snowflake Account Identifier policies](https://docs.snowflake.com/en/user-guide/admin-account-identifier).  The ORG and ACCOUNT names can be found in your Snowflake trial confirmation email or in the Snowflake login link (ie. `https://xxxxxxx-yyy11111.snowflakecomputing.com/console/login`).
```

2023-11-15 21:34 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +
For each of these subsections in Project code, I think we need a sentence up front describing what the section is. So for this one, something like "The first couple of tasks in the DAG setup the structure needed to run the model, including creating the necessary Snowflake objects, downloading data, and checking the Snowpark model registry". And then something similar for the other sections.

2023-11-28 18:21 UTC, kentdanas approved these changes
@astronautyates one more comment from me (clarifying an older comment), but preemptively approving assuming those changes. Otherwise this can move on to copy editing. @lzdanski @jwitz can we get a review here please? (this one is not time sensitive)

2023-11-28 18:21 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +
@astronautyates sorry for the confusion - I meant adding a sentence __in__ the subsection. So under `### Setup Tasks`, describe generally what the tasks in the section do, not all up front under Project Code. The descriptions there look fine, so just move them into the relevant sections. I think it's a bit confusing to start a section off directly with code.

2023-11-30 18:20 UTC, lzdanski reviewed
@astronautyates - this is an awesome demonstration! I have a lot of editorial comments, mainly things for consistency in the style/voice we've got elsewhere in these types of materials. I'm not quite done with my full review, but I wanted to go ahead and get some feedback sent your way. I'll finish up my comments later today

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +Database and Schema names should be CAPITALIZED due to a bug in Snowpark ML.
```suggestion
Capitalize `database` and `schema` names due to a bug in Snowpark ML.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +The Snowflake `account` field of the connection should use the new `ORG_NAME-ACCOUNT_NAME` format as per [Snowflake Account Identifier policies](https://docs.snowflake.com/en/user-guide/admin-account
```suggestion
Use the the new `ORG_NAME-ACCOUNT_NAME` format for the Snowflake `account` field of the connection as explained in the [Snowflake Account Identifier policies](https://docs.snowflake.com/en/user-guide/admin-account-identifier).  You can find the `ORG` and `ACCOUNT` names in your Snowflake trial confirmation email or in the Snowflake login link, for example, `https://xxxxxxx-yyy11111.snowflakecomputing.com/console/login`.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +To run the example project, first make sure Docker Desktop is running. Then, open your project directory and run:
```suggestion
1. To run the example project, first make sure Docker Desktop is running. 

2. Then, open your project directory in terminal and run:
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +After the command finishes, open the the [Airflow UI](http://localhost:8080/) and trigger the `customer_analytics` DAG using the play button. Then, monitor its status as it completes via the graph vi
```suggestion
3. After the command finishes, open the the [Airflow UI](http://localhost:8080/) and trigger the `customer_analytics` DAG by clicking the play button. Then, monitor its status as it completes via the graph view.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +Once the DAG has completed, you can view the results in a Streamlit customer analytics dashboard.
```suggestion
After the DAG completes, you can view the results in a Streamlit customer analytics dashboard. 
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +Streamlit has been installed alongside the Airflow UI in the webserver container, and there's a script in the include directory called `streamlit_app.py` that you'll use to create the dashboard.
```suggestion
Streamlit is installed alongside the Airflow UI in the webserver container, and there's a script in the `include` directory called `streamlit_app.py` that you use to create the dashboard.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +To do so, first go to your project's root directory and connect to the webserver container with the Astro CLI
```suggestion
1.  Go to your project's root directory and connect to the webserver container with the Astro CLI by running the following command.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +Then, run the following command to start Streamlit.
```suggestion
2. Run the following command to start Streamlit.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +You can then open the [streamlit application](http://localhost:8501) in a browser. All of the customer analytics produced by your DAG will be visualized here, and if you've added an Open-AI key to yo
```suggestion
3. Open the [streamlit application](http://localhost:8501) in a browser to see a visualization of all the customer analytics that your DAG produces. If you added an Open-AI key to your `.env` file, you can use the chatbot functionality to search for customer reviews by keyword.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +This project consists of two DAGs, a basic example `snowpark_ml_dag` DAG, and a much more complex [customer_analytics DAG.](https://github.com/astronomer/airflow-snowparkml-demo/blob/main/dags/custom
```suggestion
This project consists of two DAGs, a basic example `snowpark_ml_dag` DAG, and a much more complex [customer_analytics DAG.](https://github.com/astronomer/airflow-snowparkml-demo/blob/main/dags/customer_analytics.py). This guide focuses on the `customer_analytics` DAG, which demonstrates an end-to-end ML application workflow using OpenAI embeddings with a Weaviate vector database. The `customer_analytics` DAG also includes examples of Snowpark decorators, the Snowflake XCom backend, and the Snowpark ML model registry. 

The Astro CLI commands include additional Docker-based services for Weaviate and Streamlit.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +        """
Should some of this description be introduced before the code example?

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +- Task `create_snowflake_objects`: Our first task creates Snowflake objects (databases, schemas, stages, etc.) prior to running any tasks, since we are assuming you are starting with a fresh trial ac
```suggestion
- Task `create_snowflake_objects`: The first task creates Snowflake objects (like databases, schemas, and stages) prior to running any tasks, since this demonstrations assumes you started with a fresh trial account. The task creation uses the Airflow setup/teardown task feature, and has a corresponding clean up task at the end of the DAG. This means that no matter what, Airflow deletes temp tables used for this project after usage to prevent unnecessary consumption, mimicking how you might use them in a production setting! 
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +- Task `download_weaviate_backup`: In order to speed up the demo process, the data has already been ingested into Weaviate and vectorized.  The data was then backed up and stored in the cloud for eas
```suggestion
- Task `download_weaviate_backup`: To speed up the demonstration process, the data you use has been ingested  into Weaviate and vectorized in advance.  The data was then backed up and stored in the cloud for easy restore. This task downloads the `backup.zip` and makes it available in a Docker mounted filesystem for the `restore_weaviate` task.
```

2023-11-30 18:20 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +- Task `restore_weaviate`: This task exists speeds up the demo for subsequent runs. By restoring prefetched embeddings to Weaviate, the later tasks will skip embeddings and only make calls to OpenAI
```suggestion
- Task `restore_weaviate`: This task speeds up the demo for subsequent runs. By restoring prefetched embeddings to Weaviate, later tasks skip embeddings and only make calls to OpenAI for data it hasn't yet embedded.
```

2023-11-30 23:28 UTC, lzdanski reviewed
This is a fantastic use case. I'll need to work through it myself sometime because I have a docs related project I think could be very interesting to tinker with. Again, I made a lot of comments, but they kind of address a consistent grammar thing I'm seeing, which is passive voice use. It's hard to write in active voice about DAGs, tasks, and code, but it's important for people just learning the process and example to be able to clearly identify what Thing is performing which Action on what Object. Passive voice doesn't communicate those relationships very directly and some languages don't have it all. It's tricky!

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +- `twitter_sentiment` Task: Similar in structure to the call_sentiment task, this task also retrieves vectors and properties from Weaviate for the class CustomerComment. It processes the data in the
```suggestion
- `twitter_sentiment` Task: Similar in structure to the `call_sentiment` task, this task also retrieves vectors and properties from Weaviate for the class `CustomerComment`. The task processes the data in the same way, using a model from Snowflake's Model Registry to predict sentiment scores. It outputs a Snowpark dataframe that includes Twitter comment data augmented with their respective sentiment scores.
```

Excellent. Super clear!

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +After the model has genereated its predictions, the results are cleaned and organized into presentation tables for viewing via a streamlit application.
```suggestion
After the model has generated its predictions, the next tasks cleans and organizes the results into presentation tables for viewing using a Streamlit application. 
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +- `Create_Presentation_Tables` Task: The `create_presentation_tables` task is designed to consolidate and process various data sources to create tables specifically for presentation in a Streamlit ap
```suggestion
- `Create_Presentation_Tables` Task: The `create_presentation_tables` task consolidates and processes various data sources to create tables specifically for presentation in a Streamlit app. This function takes five Snowpark tables as input: `attribution_df`, `mrr_df`, `customers_df`, `pred_calls_table`, and `pred_comment_table`. The task processes each of these tables to generate new tables suited for visual presentation and analysis. The following shares a summary of each step:
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Customer Data Processing: Enhances the customers_df table by adding a rounded 'Customer Lifetime Value' (CLV) column.
```suggestion
  - Customer Data Processing: Enhances the `customers_df` table by adding a rounded 'Customer Lifetime Value' (CLV) column.
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Sentiment Analysis: Combines sentiment data from call and comment tables. It calculates the average sentiment score for each customer based on call and comment data. The final sentiment score is
```suggestion
  - Sentiment Analysis: Combines sentiment data from `pred_calls_table` and `pred_comment_table` tables. It calculates the average sentiment score for each customer based on call and comment data. The final sentiment score is the average of these two scores, and customers are bucketed into sentiment categories. This processed data is saved as the `PRES_SENTIMENT` table.
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Advertising Spend Analysis: Processes the attribution_df table to understand the revenue generated from different advertising mediums. The data is grouped by the medium, and the revenue is summed
```suggestion
  - Advertising Spend Analysis: Processes the `attribution_df` table to understand the revenue generated from different advertising mediums. The data is grouped by the medium, and the revenue is summed up for each group. The task saves the table as `PRES_AD_SPEND`.
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Customer Lifetime Value (CLV) Analysis: Creates a comprehensive view of customer lifetime value by joining customers_df with sentiment data. It sorts the data by CLV and includes various customer
```suggestion
  - Customer Lifetime Value (CLV) Analysis: Creates a comprehensive view of customer lifetime value by joining `customers_df` with sentiment data. It sorts the data by CLV and includes various customer details. This table, named `PRES_CLV`, is valuable for understanding the high-value customers and their sentiment scores.
```
For understanding the customers or identifying them?

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Churn Analysis: Analyzes churn by joining customer data with MRR data and sentiment scores. It filters for customers who have churned and sorts them by their last active month. This table, PRES_C
```suggestion
  - Churn Analysis: Analyzes churn by joining customer data with MRR data and sentiment scores. It filters for customers who have churned and sorts them by their last active month. This table, `PRES_CHURN`, is critical for identifying recently churned customers and understanding their value and sentiment.
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Saving Raw Sentiment Data: The raw sentiment data for customer calls (pred_calls_table) and Twitter comments (pred_comment_table) are saved as PRED_CUSTOMER_CALLS and PRED_TWITTER_COMMENTS, respe
```suggestion
  - Saving Raw Sentiment Data: The raw sentiment data for customer calls (`pred_calls_table`) and Twitter comments (`pred_comment_table`) are saved as `PRED_CUSTOMER_CALLS` and `PRED_TWITTER_COMMENTS`, respectively.
```

2023-11-30 23:28 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +  - Saving Attribution Touches: The attribution_df table is saved as ATTRIBUTION_TOUCHES, which holds detailed data on customer interactions and their revenue attribution.
```suggestion
  - Saving Attribution Touches: The `attribution_df` table is saved as `ATTRIBUTION_TOUCHES`, which holds detailed data on customer interactions and their revenue attribution.
```

2023-12-04 19:03 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +  - Customer Lifetime Value (CLV) Analysis: Creates a comprehensive view of customer lifetime value by joining customers_df with sentiment data. It sorts the data by CLV and includes various customer
Understanding them, their purchase history, usage trends etc

2023-12-04 19:07 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +```
Done!

2023-12-04 19:09 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +        """
Great idea!

2023-12-04 19:11 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +- Task `jaffle_shop`: This task begins by aggregating orders to calculate each customer's first and most recent order dates, as well as their total number of orders. Next, it joins the payments data
Fixed

2023-12-04 19:21 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +- `train_sentiment_classifier` Task: After the structured and unstructured data has been extracted, transformed/transcribed, and loaded, it is used to train a sentiment classifier model in Snowpark.
Yeah I think the line on model tuning/optimizaiton warrants removing to avoid confusion, and editing to make clearer overall in line with your suggestions

2023-12-04 19:40 UTC, astronautyates commented
Think I've covered all changes, let me know if I missed anything!

2023-12-11 22:44 UTC, lzdanski reviewed
@astronautyates - looking good! Just a few minor comments about formatting and a couple of typos!

2023-12-11 22:44 UTC, lzdanski commented on learn/use-case_snowpark_customer_analytics.md
> +```python
I've got some mixed thoughts about the size of this code block. Fully maximized, I can't skim all the code and it's long enough that it's a little difficult to ready. Maybe @TJaniF or @kentdanas have thoughts about how y'all have handled similar formatting in other places in Learn?

2023-12-12 19:16 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +```python
Yeah it's tricky - generally we break up big chunks of code with descriptive text and more, smaller blocks. In this particular case, this chunk of code happens to be a single logical piece of the pipeline (it's a single task group), so it doesn't break up neatly into smaller pieces. (This pipeline is general is a lot meatier than other things we publish). 

One thing we could do is not include all the code in general. These Use Cases aren't designed for people to copy code from them - they're meant to add a descriptive walkthrough (and SEO) to a repo that somebody would clone in its entirety. So we could for instance, include one of the nested task groups as a representative example, and just add a `...` and a note in the text to indicate that there is more code in the full example. @astronautyates do you think there's a logical way to do that here?

2023-12-21 20:29 UTC, astronautyates commented on learn/use-case_snowpark_customer_analytics.md
> +```python
So with the block that was previously below being moved up to split the sections I think it's more readable now, but lmk what y'all think. Edited in line with your comments about moving the explanations ahead of the respectives code blocks

2023-12-22 17:37 UTC, kentdanas approved these changes
@astronautyates this looks good to me, I say let's go ahead and publish and we can make adjustments for the length later if needed.

2023-12-22 17:37 UTC, kentdanas commented on learn/use-case_snowpark_customer_analytics.md
> +```python
It is definitely better now. I still think the code blocks are pretty long, but I'm inclined to publish as-is rather than trying to take some of the code out, and see how it does (if we get negative feedback we can change it). We won't have too many that are this dense, so I'm not super concerned about process for this.

2024-01-02 19:03 UTC, merged