Update GCP workload identity setup
astronomer/docs pull request #3088
Opened 2023-11-14 14:59 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/2922

2023-11-14 16:06 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment workload identity to assume an existing service account on y
@chomipi88 Is the main reason you would do this alternative setup? If not, what's the primary benefit here?

2023-11-14 16:11 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +    - Run the following command to create an environment variable that connects your Deployment to your GCP secrets backend:
@chomipi88 I didn't know how to add the "Leverage the Astro Workload Identity" option here, lmk the specific steps I should add ([based on the content in the original issue](https://github.com/astronomer/docs/issues/2922))

2023-11-14 16:12 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +    astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "proj
Does this command only grant you access to the secrets backend, or is this a general setup to access all resources in the GCP project?

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment workload identity to assume an existing service account on y
```suggestion
[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment workload identity to assume an existing service account on your GCP project. Complete this setup if you want your Deployment to only use its authenticated identity to generate short-lived credentials for a service account that has the authorization that your use case requires, rather than persistent and static service account key. 
```

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment workload identity to assume an existing service account on y
made a suggestion below

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +1. [Create a service account](https://cloud.google.com/iam/docs/service-accounts-create) in the Google project that you want your Deployment to access. Copy the service account ID to user later in th
Also requires granting this service account the necessary permissions to the target service (eg. GCS Bucket)

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
Specifically the user needs to grant this role to the Deployment's workload identity TO the service account they created in step 1 (or an existing SA).

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
```suggestion
3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's workload identity. See [Grant a single role](https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role).
```

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +    - Run the following command to create an environment variable that connects your Deployment to your GCP secrets backend:
The first option is configuring the impersonation chain on the connection as per: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#configuring-the-connection:~:text=request%20only%20once.-,Impersonation%20Chain,-Optional%20service%20account

The second option is configuring the impersonation chain on the operator as per: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#direct-impersonation-of-a-service-account
Important to note that the `impersonation_chain` passed to the operator takes precedence.

2023-11-14 18:59 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +    astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "proj
This third option is to configure the secrets backend for a particular deployment where connections and variables could be stored.

2023-11-15 14:03 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +1. [Create a service account](https://cloud.google.com/iam/docs/service-accounts-create) in the Google project that you want your Deployment to access. Copy the service account ID to user later in th
```suggestion
1. [Create a service account](https://cloud.google.com/iam/docs/service-accounts-create) in the GCP project that you want your Deployment to access. Grant the service account any permissions that the Deployment will need in your GCP project. Copy the service account ID to user later in this setup.
```

2023-11-15 14:33 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
How would you limit it so that it can only generate a token for the specific SA? Is there a specific [condition](https://cloud.google.com/iam/docs/conditions-overview) we should tell them to add?

2023-11-15 14:35 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +    - Run the following command to create an environment variable that connects your Deployment to your GCP secrets backend:
```suggestion
    - To access resources in a secrets backend, run the following command to create an environment variable that grants access to the secrets backend:
```

2023-11-15 14:36 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +        - **Impersonation Chain**: Enter the ID of the service account that your Deployment should impersonate.
```suggestion
        - **Impersonation Chain**: Enter the ID of the service account that your Deployment should impersonate.
   - Specify the impersonation chain at the operator level. See [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#direct-impersonation-of-a-service-account). Note that if you configure both a connection type and an operator, the operator-level configuration takes precedence.
```

2023-11-15 14:37 UTC, jwitz commented
@chomipi88 Just one last question to resolve, then I think this should be good to go: https://github.com/astronomer/docs/pull/3088#discussion_r1394288355

2023-11-15 15:33 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
The specific condition is granting the Astro Deployment WI the `Service Account Token Creator` role on their specific target SA.
This means the Astro Deployment WI can **only** generate short lived tokens for the specific target SA.

2023-11-15 15:34 UTC, chomipi88 commented
@melugoyal appreciate your review here as well

2023-11-15 16:27 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
Right, I was trying to figure out how to actually apply that condition. [The GCP docs](https://cloud.google.com/docs/authentication/use-service-account-impersonation) only mention the role, but not the limiting condition

2023-11-15 16:57 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
Ah its a matter of granting the principal (Astro Deployment WI) the role mentioned to the service account.
https://cloud.google.com/iam/docs/manage-access-service-accounts?_ga=2.156967740.-620980664.1671590357
<img width="1574" alt="image" src="https://github.com/astronomer/docs/assets/87984472/d852f77d-9ad2-4fa7-8831-c76324e8426d">

2023-11-15 17:00 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +1. [Create a service account](https://cloud.google.com/iam/docs/service-accounts-create) in the GCP project that you want your Deployment to access. Grant the service account any permissions that the
typo: `to user later`

2023-11-15 17:00 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +    astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow-connections", "variables_prefix": "airflow-variables", "proj
we already have [separate instructions for Google secrets backend](https://deploy-preview-3088--gallant-neumann-56599d.netlify.app/astro/secrets-backend/gcp-secretsmanager#step-3-configure-secret-manager-on-astro-using-workload-identity-recommended), do we want to duplicate that here?

2023-11-15 17:00 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
what do we mean by "principal account"? that's the first time using this term; maybe we just say "to the service account you just created"?

it might be better to just link to the impersonation docs? https://cloud.google.com/docs/authentication/use-service-account-impersonation#required-roles

2023-11-15 17:00 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +        - **Impersonation Chain**: Enter the ID of the service account that your Deployment should impersonate.
might be worth mentioning they need Google provider >= 10.8.0 for this to work

2023-11-15 17:00 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +   - Specify the impersonation chain at the operator level. See [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#direct-impersonatio
instead of saying "at the operator level", probably better to say "in code when instantiating a Google Cloud Operator"

2023-11-15 17:10 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +#### Alternative setup: Use GCP Service Account Impersonation
maybe it doesn't matter, but do we want to recommend this as an alternative or the recommended way?

2023-11-15 17:19 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +#### Alternative setup: Use GCP Service Account Impersonation
Given the coming work on pre-defined, I do agree that we should start positioning impersonation as the recommended way.

2023-11-15 17:26 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +#### Alternative setup: Use GCP Service Account Impersonation
Based on the language around it I assumed it was the alternative, but happy to frame it as the default method

2023-11-15 17:29 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
I thought the "principal" is the _impersonating_ service account, which in this case would be the Deployment workload identity. I used "principal" here because it's in the GCP docs and because it distinguishes the Deployment service account from the service account being impersonated.

2023-11-15 17:29 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
```suggestion
3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to your Deployment's workload identity, also known as the _principal_ service account. See [Grant a single role](https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role).
```

2023-11-15 17:30 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
Maybe it makes more sense to start with the Deployment language first and then clarify with the principal language, see my suggestion below

2023-11-15 17:31 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +        - **Impersonation Chain**: Enter the ID of the service account that your Deployment should impersonate.
```suggestion
        - **Impersonation Chain**: Enter the ID of the service account that your Deployment should impersonate.
        
        Note that this implementation requires `apache-airflow-providers-google >= 10.8.0`. See [Add Python, OS-level packages, and Airflow providers](https://docs.astronomer.io/astro/cli/develop-project#add-python-os-level-packages-and-airflow-providers).
```

2023-11-15 17:32 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +   - Specify the impersonation chain at the operator level. See [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#direct-impersonatio
```suggestion
   - Specify the impersonation chain in code when you instantiate a Google Cloud operator. See [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#direct-impersonation-of-a-service-account). Note that if you configure both a connection type and an operator, the operator-level configuration takes precedence.
```

2023-11-15 17:38 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +#### Alternative setup: Use GCP Service Account Impersonation
@jwitz yes pls let's do that. should of called that out sooner... my bad.

2023-11-15 17:50 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
```suggestion
2. In the Cloud UI, select your Deployment, then click **Details**. Copy the Deployment's **Workload Identity**.
3. In the Google Cloud Console, open the **IAM & admin** menu, then open the service account you just created. 
4. In the **Actions** column, click **Manage Permissions**, then click **Grant Access**. In the window that appears, enter your Deployment's workload identity ID in the **Add Principals** field and select the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) in the **Assign Roles** field.
```

2023-11-15 17:56 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
This screenshot was a life saver, just updated the setup to lead users exactly here.

2023-11-15 18:01 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
Jake is right. The principal would be the Deployment WI.

2023-11-15 22:41 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +3. Grant the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) IAM role to the principal account, also known as your Deployment's
i mean that's my point, i'm not sure that terminology is well-understood

2023-11-15 22:44 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +4. In the **Actions** column, click **Manage Permissions**, then click **Grant Access**. In the window that appears, enter your Deployment's workload identity ID in the **Add Principals** field and s
```suggestion
4. In the **Actions** column, click **Manage Permissions**, then click **Grant Access**. In the window that appears, enter your Deployment's workload identity service account in the **Add Principals** field and select the [`Service Account Token Creator`](https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountTokenCreator) in the **Assign Roles** field.
```

2023-11-16 09:54 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +Complete this alternative setup if you want a more simple setup and can tolerate your Deployment having long-lasting credentials to your Google Cloud project.
```suggestion
Complete this alternative, simpler setup if you can tolerate your Deployment having long-lasting credentials to your Google Cloud project.
```

2023-11-16 17:02 UTC, lzdanski reviewed
A small formatting thing and a couple questions! Mostly qualitative curiosity.

2023-11-16 17:40 UTC, melugoyal commented on astro/authorize-deployments-to-your-cloud.md
> +Complete this alternative, simpler setup if you can tolerate your Deployment having long-lasting credentials to your Google Cloud project.
also, i wouldn't say this has the downside of long-lasting credentials; technically that's the case with both. maybe just say something like "use this option if you don't have an existing Google service account you'd like your Astro Workload Identity to impersonate"

2023-11-17 11:29 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +#### Authorize your Deployment through GCP Service Account Impersonation
Yeah it's a tab thing, but there's a better solution here and I'm being a bit lazy!

2023-11-17 11:29 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +4. In the **Actions** column, click **Manage Permissions**, then click **Grant Access**. In the window that appears, enter your Deployment's workload identity service account in the **Add Principals*
It's not a full new window, so I like using modal here

2023-11-17 11:29 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +Complete this alternative, simpler setup if you can tolerate your Deployment having long-lasting credentials to your Google Cloud project.
```suggestion
Complete this alternative setup if you don't have an existing Google service account that your Deployment workload identity can impersonate.
```

2023-11-17 13:15 UTC, lzdanski approved these changes
tested out the new headers and found they don't work as H3's. But everything else LGTM

2023-11-17 13:15 UTC, lzdanski commented on astro/authorize-deployments-to-your-cloud.md
> +### Authorize your Deployment through GCP Service Account Impersonation
Ok so I think we do have to have these headers as H4 - right now, half of the right nav just doesn't really work depending on which tab you're on (AWS or GCP). What a strange docusaurus quirk. I think they either have to be H3 and identical between tabs, or H4 -
<img width="289" alt="Screenshot 2023-11-17 at 8 09 25 AM" src="https://github.com/astronomer/docs/assets/25642903/7cc886ef-66e3-42da-ab4e-0444a19e0956">

2023-11-17 13:15 UTC, lzdanski commented on astro/authorize-deployments-to-your-cloud.md
> +### Step 2: Create an Airflow connection
```suggestion
#### Step 2: Create an Airflow connection
```

2023-11-17 13:15 UTC, lzdanski commented on astro/authorize-deployments-to-your-cloud.md
> +### Authorize your Deployment through GCP Service Account Impersonation
```suggestion
#### Authorize your Deployment through GCP Service Account Impersonation
```

2023-11-17 13:15 UTC, lzdanski commented on astro/authorize-deployments-to-your-cloud.md
> +### Alternative setup: Grant an IAM role to your Deployment workload identity
```suggestion
#### Alternative setup: Grant an IAM role to your Deployment workload identity
```

2023-11-17 13:15 UTC, lzdanski commented on astro/authorize-deployments-to-your-cloud.md
> +### Step 1: Authorize the Deployment in your cloud
```suggestion
#### Step 1: Authorize the Deployment in your cloud
```

2023-11-17 14:56 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +### Authorize your Deployment through GCP Service Account Impersonation
Oh I think I need to lower the frontmatter requirement by 1 level, then it should work

2023-11-17 14:56 UTC, jwitz commented on astro/authorize-deployments-to-your-cloud.md
> +toc_max_heading_level: 3
```suggestion
toc_max_heading_level: 2
```

2023-11-21 14:29 UTC, jwitz commented
@chomipi88 Is this good to go?

2023-11-21 14:53 UTC, chomipi88 requested changes
LGTM pending these few items

2023-11-21 14:53 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment workload identity to assume an existing service account on y
```suggestion
[GCP service account impersonation](https://cloud.google.com/docs/authentication/use-service-account-impersonation) allows your Deployment's workload identity to assume an existing service account in your GCP project. This is the most secure authorization setup because your Deployment only uses generated, short-lived credentials for a service account, rather than a persistent and static service account key. 
```

2023-11-21 14:53 UTC, chomipi88 commented on astro/authorize-deployments-to-your-cloud.md
> +3. In the Google Cloud Console, open the **IAM & admin** menu, then open the service account you just created.
```suggestion
3. In the Google Cloud Console, open the **IAM & Admin > Service Accounts** menu, then open the service account you just created. 
```

2023-11-22 18:35 UTC, chomipi88 approved these changes
lgtm

2023-11-23 13:26 UTC, merged