Add info about --global config options for Astro CLI
astronomer/docs pull request #3095
Opened 2023-11-15 18:04 UTC by lzdanski

Resolves #3094

2023-11-15 18:28 UTC, odaneau-astro commented
Can we add the following on either the astro config get or set pages:

> Astro configurations can be set at two different scopes: globally or by project. 
> For project-specific configurations, the settings are stored in a file named /.../<your-project-folder>/.astro/config.yaml within your project directory. This file is generated when you run `astro dev init` in your project folder.
> Global configurations, on the other hand, are stored in a central location. In Linux, this location is /home/<username>/.astro/config.yaml.

2023-11-15 20:51 UTC, lzdanski commented on astro/cli/configure-cli.md
> +For project-specific configurations, Astro stores the settings in a file named `/...//.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your proje
@odaneau-astro - do we know the location for Mac/windows? Should I ask the CLI team?

2023-11-15 21:14 UTC, odaneau-astro commented on astro/cli/configure-cli.md
> +For project-specific configurations, Astro stores the settings in a file named `/...//.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your proje
You can't use the Astro CLI on Windows directly. You have to use WSL / Linux.
On Mac, it should be in ~/.astro/config.yaml. 
I can't confirm since I'm on Windows, but it's easy to check with `ls -la`.

2023-11-16 15:49 UTC, jwitz requested changes
Requesting changes because I'm p sure I changed the technical meaning a bit in my suggestions, just wanna make sure I'm understanding the usage!

2023-11-16 15:49 UTC, jwitz commented on astro/cli/configure-cli.md
> +You can view or modify the `astro/config.yaml` file for your current astro projects by using the `--global` flag with `astro config set [option] --global` and `astro config get`. Setting a configurat
```suggestion
You can view or modify the default configuration for all Astro projects using the `--global` flag. Setting a configuration globally applies it across all current and new projects, and the configuration is saved in a central location. For example, the configurations are stored in `~/.astro/config.yaml` on Mac OS and `/home//.astro/config.yaml` on Linux. You can then override the global configuration at the project level by running `astro config set` without the flag.
```

2023-11-16 15:49 UTC, jwitz commented on astro/cli/configure-cli.md
> +The following example shows how to set a port for your local Airflow webserver to `8081` from the default of `8080` for all your Astro projects:
```suggestion
The following example shows how to set the local Airflow webserver port to `8081` for all Astro projects on your local machine:
```

2023-11-16 15:49 UTC, jwitz commented on astro/cli/astro-config-set.md
> +| `-g`, `--global` | Modify global CLI configuration settings. | None            |
I'd either link to the new topic here or clarify the description so it's clear what "global" means.

2023-11-16 15:49 UTC, jwitz commented on astro/cli/configure-cli.md
> +For project-specific configurations, Astro stores the settings in a file named `/...//.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your proje
```suggestion
For project-specific configurations, Astro stores the settings in a file named `.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your project folder. Global configurations, however, are stored in a central location with the Astro executable.  
```

2023-11-16 15:49 UTC, jwitz commented on astro/cli/configure-cli.md
> +You can view or modify the `astro/config.yaml` file for your current astro projects by using the `--global` flag with `astro config set [option] --global` and `astro config get`. Setting a configurat
Something that might be worth clarifying: if you already have a config.yaml file set on a given project, and you update a config globally, is that config also applied to the project or does the local file still take precedence?

2023-11-16 15:49 UTC, jwitz commented on astro/cli/reference.md
> +- `g`, `--global`: You can globally configure certain properties for your Astro CLI by using this flag with the `astro config` command. See [Configure the CLI](configure-cli.md#global-configuration-o
```suggestion
- `g`, `--global`: You set global configurations for the Astro CLI by running `astro config --global`. See [Configure the CLI](configure-cli.md#global-configuration-options) for more information.
```

2023-11-16 16:16 UTC, odaneau-astro commented on astro/cli/configure-cli.md
> +You can view or modify the `astro/config.yaml` file for your current astro projects by using the `--global` flag with `astro config set [option] --global` and `astro config get`. Setting a configurat
@sunkickr : Could you help answer @jwitz here?

2023-11-16 16:18 UTC, odaneau-astro commented on astro/cli/configure-cli.md
> +For project-specific configurations, Astro stores the settings in a file named `/...//.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your proje
Just to clarify this one: when installed manually from GH releases the Astro executable can be located anywhere on PATH. on the other hand, the astro global config location will not change.

2023-11-17 13:34 UTC, lzdanski commented on astro/cli/astro-config-get.md
> +| `-g`, `--global` | View global CLI configuration settings. | None            |
```suggestion
| `-g`, `--global` | View global CLI configuration settings. See [Set global configurations](configure-cli.md#set-global-configurations). | None            |
```

2023-11-17 13:34 UTC, lzdanski commented on astro/cli/astro-config-set.md
> +| `-g`, `--global` | Modify global CLI configuration settings. | None            |
```suggestion
| `-g`, `--global` | Modify global CLI configuration settings. See [Set global configurations](configure-cli.md#set-global-configurations). | None            |
```

2023-11-22 17:51 UTC, jwitz approved these changes
Minor comments. Might have gone overboard explaining the overriding behavior, so please adjust my suggestions or remove an instance if you think it's too much!

2023-11-22 17:51 UTC, jwitz commented on astro/cli/configure-cli.md
> +You can view or modify the `astro/config.yaml` file for your current astro projects by using the `--global` flag with `astro config set [option] --global` and `astro config get`. Setting a configurat
```suggestion
Use the `--global` flag with `astro config set [option] --global` to set a configuration for all current and new Astro projects on your machine. Your global Astro CLI configuration is saved in a central location on your machine. For example, the configurations are stored in `~/.astro/config.yaml` on Mac OS and `/home//.astro/config.yaml` on Linux.

Note that you can override global configurations by setting a [project-level configuration](#set-project-configuration). If an Astro project contains an `.astro/config.yaml` file, any configuration values in that file take precedence over the same global configuration values.
```

2023-11-22 17:51 UTC, jwitz commented on astro/cli/configure-cli.md
> +For project-specific configurations, Astro stores the settings in a file named `.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your project fol
```suggestion
For project-specific configurations, Astro stores the settings in a file named `.astro/config.yaml` in your project directory. This file is generated when you run `astro dev init` in your project folder. Global configurations, however, are stored in a central location with the Astro executable. If a configuration is set in a project configuration file, it always overrides configurations the same configuration in the global configuration file.
```

2023-11-22 18:14 UTC, merged