Pinecone integration learn
astronomer/docs pull request #3098
Opened 2023-11-16 21:14 UTC by astronautyates

2023-11-17 01:19 UTC, kentdanas requested changes
Looking great @astronautyates! I know you're updating the DAG tomorrow, but a couple of other comments in here you can address at the same time.

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +sidebar_label: "Pinecone"
Need to add this to sidebarLearn.js so it shows up in the sidebar

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +- A Pinecone account with an API key. You can use a free tier account for this example.
Can we link here to where ever you go to create a pinecone account?

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +1 ::: Arrival (2016) ::: sci-fi ::: A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.
Just a suggestion, but maybe we should include a different movie list here than what we used for Weaviate. For variety :)

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +```python
Let's put this DAG in the `code-samples` folder and import it into the doc. Code in there gets run through a linter and some basic checks during the build process which helps us maintain everything over time. You can look at the weaviate one for an example of how to do it https://github.com/astronomer/docs/blob/main/learn/airflow-weaviate.md

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +@dag(schedule="@daily",
Lets make the schedule `None` here. I think for example DAGs in tutorials better to have them not run unless manually triggered, just to help people avoid any unexpected issues.

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +- `import_data_func` Function: This function reads movie data from a text file, processes it to extract titles, years, genres, and descriptions, and then vectorizes the descriptions using TF-IDF (Ter
Does this run every time the DAG is parsed? If it's not running as a task, should it be one?

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +
Let's add a screenshot of the graph view of the DAG here, so people have a sense of what it looks like.

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +```text
Update this to include the movie suggestion?

2023-11-17 01:19 UTC, kentdanas commented on learn/airflow-pinecone.md
> +2. In the Airflow UI, go to the connections managment UI and create a new pinecone connection following the example in the screenshot below:
We should add a bit more detail here beyond just the screenshot. Like lets say explicitly that the connection needs to be named `pinecone`, and any relevant info about what the pinecone environment is, etc.

2023-11-17 22:58 UTC, astronautyates commented on learn/airflow-pinecone.md
> +```python
I'm gonna let Tamara do that if that's ok just since she's re-writing it to work w/o the openAI key issues

2023-11-17 22:58 UTC, astronautyates commented on learn/airflow-pinecone.md
> +- `import_data_func` Function: This function reads movie data from a text file, processes it to extract titles, years, genres, and descriptions, and then vectorizes the descriptions using TF-IDF (Ter
Upodated so no longer relevant

2023-11-17 23:02 UTC, astronautyates commented on learn/airflow-pinecone.md
> +```text
Waiting on getting it to work still unfortunately, hopefully Tamara can sub here with a final example

2023-11-17 23:03 UTC, astronautyates commented on learn/airflow-pinecone.md
> +2. In the Airflow UI, go to the connections managment UI and create a new pinecone connection following the example in the screenshot below:
added!

2023-11-19 23:48 UTC, TJaniF commented on sidebarsLearn.js
> +        'Pinecone'
```suggestion
        'Pinecone',
```

2023-11-19 23:52 UTC, TJaniF commented on sidebarsLearn.js
> +        'Pinecone',
```suggestion
        'airflow-pinecone',
```

2023-11-20 15:42 UTC, TJaniF reviewed
@astronautyates Thank you for getting this PR up :) 

@kentdanas I made some changes based on the Slack discussion and your comments, ready for a second look from you :)

2023-11-20 21:25 UTC, kentdanas approved these changes
Looks great, thanks @TJaniF for the updates. This one is ready for copy editing.

2023-11-20 23:24 UTC, TJaniF reviewed
Thank you @kentdanas :) 
@jwitz and @lzdanski another one for you, very similar structure to the Weaviate tutorial :)

2023-11-22 10:27 UTC, jwitz approved these changes
Looks great! Just some minor copy updates

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +## Step 3 Create your DAG
```suggestion
## Step 3: Create your DAG
```

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +Create a new file called `series_data.txt` in the `include` directory, then copy and paste the following information into the file:
```suggestion
1. In your Astro project `include` directory, create a file called `series_data.txt`. 
2. Copy and paste the following text into the file:
```

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +Create a new file called `series_data.txt` in the `include` directory, then copy and paste the following information into the file:
Tried making this consistent with other high level steps where we use numbered lists

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +```
````suggestion
    ```text
    1 ::: Star Trek: Discovery (2017) ::: sci-fi ::: Ten years before Kirk, Spock, and the Enterprise, the USS Discovery discovers new worlds and lifeforms using a new innovative mushroom based propulsion system. 
    2 ::: Feel Good (2020) ::: romance ::: The series follows recovering addict and comedian Mae, who is trying to control the addictive behaviors and intense romanticism that permeate every facet of their life.
    3 ::: For All Mankind (2019) ::: sci-fi ::: The series dramatizes an alternate history depicting "what would have happened if the global space race had never ended" after the Soviet Union succeeds in the first crewed Moon landing ahead of the United States.
    4 ::: The Legend of Korra (2012) ::: anime ::: Avatar Korra fights to keep Republic City safe from the evil forces of both the physical and spiritual worlds.
    5 ::: Mindhunter (2017) ::: crime ::: In the late 1970s, two FBI agents broaden the realm of criminal science by investigating the psychology behind murder and end up getting too close to real-life monsters.
    6 ::: The Umbrella Academy (2019) ::: adventure ::: A family of former child heroes, now grown apart, must reunite to continue to protect the world.
    7 ::: Star Trek: Picard (2020) ::: sci-fi ::: Follow-up series to Star Trek: The Next Generation (1987) and Star Trek: Nemesis (2002) that centers on Jean-Luc Picard in the next chapter of his life.
    8 ::: Invasion (2021) ::: sci-fi ::: Earth is visited by an alien species that threatens humanity's existence. Events unfold in real time through the eyes of five ordinary people across the globe as they struggle to make sense of the chaos unraveling around them.
    ```
````

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +1. In your `dags` folder, create a file called `query_series_vectors.py`.
```suggestion
1. In your Astro project `dags` folder, create a file called `query_series_vectors.py`.
```

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +2. Copy the following code into the file.
```suggestion
2. Copy the following code into the file:
```

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +1. Run `astro dev start` in your Astro project to start Airflow and open the Airflow UI at `localhost:8080`.
```suggestion
1. Open your Astro project, then run `astro dev start` to run Airflow locally.
```

2023-11-22 10:27 UTC, jwitz commented on learn/airflow-pinecone.md
> +When watching `For All Mankind` make sure to have a tab with [Wikipedia](https://en.wikipedia.org) open to compare the alternate timeline with ours. Also don't forget to hydrate and move around every
Is the hydration thing a reference to something in the show? If not, I would update to:

"And don't forget to hydrate and stretch, it can get stressful!" or something like that

2023-11-22 14:53 UTC, TJaniF reviewed
Thank you @jwitz ! :) 

Accepted all suggestions and made a suggestion for the binge watching tip in a comment :)

2023-11-22 14:53 UTC, TJaniF commented on learn/airflow-pinecone.md
> +When watching `For All Mankind` make sure to have a tab with [Wikipedia](https://en.wikipedia.org) open to compare the alternate timeline with ours. Also don't forget to hydrate and move around every
No, not a direct reference no... I thought about it and looked a couple of quotes but can't really think of something that stands out enough to fit in here

```
“Flying a spacecraft isn’t like driving a car. It doesn’t just go where you point it.”
```

maybe this one? 🤔 Not sure if it works but it is distinctive enough and said by one of the main characters. Then I'd make it

```
And remember, flying spacecraft isn’t like driving a car. It doesn’t just go where you point it.
```


my initial idea was just to give generic advice about being watching a series 😅 . But I like your reference idea better. I would not call the series stressful, I mean it is tense at times but mostly interesting and inspiring (and kinda sad in a way the closer they get to our time in their alternate timeline because at least in some aspects, for now, they have the better one).

2023-11-23 15:04 UTC, merged