Runtime 9.6 release notes
astronomer/docs pull request #3120
Opened 2023-11-23 13:09 UTC by jwitz

2023-11-23 13:12 UTC, ephraimbuddy approved these changes

2023-11-23 13:31 UTC, phanikumv approved these changes

2023-11-24 11:06 UTC, phanikumv requested changes
Blocking the PR until the runtime team is ready to release 9.6.0

2023-12-01 16:30 UTC, lzdanski commented
Looks like a duplicate PR was merged for this release:
- https://github.com/astronomer/docs/pull/3134
- https://github.com/astronomer/docs/pull/3140

2023-12-01 16:30 UTC, closed without merging