Add note to astro-cli docker setup
astronomer/docs pull request #3191
Opened 2023-12-14 19:11 UTC by feluelle

2023-12-14 19:17 UTC, aliotta approved these changes

2023-12-15 11:51 UTC, jwitz requested changes
Content looks good, but is it okay if I move it into this into the docs related to `astro deploy` instead of the installation guide? I think it makes more sense to keep the content closer to where the error might be experienced.

Also to clarify, does this also apply to `astro deploy --dags` or just the regular image deploy?

2023-12-15 11:51 UTC, jwitz commented on astro/cli/install-cli.md
> +Error response from daemon: pull access denied for barren-ionization-0185/airflow, repository does not exist or may require 'docker login'
```suggestion
push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
...
Unable to find image 'barren-ionization-0185/airflow:latest' locally
Error response from daemon: pull access denied for barren-ionization-0185/airflow, repository does not exist or may require 'docker login'
```

2023-12-15 11:51 UTC, jwitz commented on astro/cli/install-cli.md
> +When using Docker Desktop make sure that the setting "Use containerd for pulling and storing images" is turned off. Otherwise, you might run into issues when executing the `astro deploy` command, suc
```suggestion
When you use Docker Desktop, ensure that the [**Use containerd for pulling and storing images**](https://docs.docker.com/desktop/containerd/#turn-on-the-containerd-image-store-feature) setting is turned off. Otherwise, you might receive errors when you run `astro deploy` such as:

```

2023-12-15 11:51 UTC, jwitz commented on astro/cli/install-cli.md
> +```
```suggestion
```text
```

2023-12-15 14:29 UTC, feluelle commented
> Content looks good, but is it okay if I move it into this into the docs related to `astro deploy` instead of the installation guide? I think it makes more sense to keep the content closer to where the error might be experienced.

Yes, please move it where it makes the most sense. :)

> Also to clarify, does this also apply to `astro deploy --dags` or just the regular image deploy?

Only to image deploy.

2023-12-15 14:31 UTC, feluelle commented on astro/cli/install-cli.md
> +Error response from daemon: pull access denied for barren-ionization-0185/airflow, repository does not exist or may require 'docker login'
The first error was when running with `-f` i.e. `astro deploy <deployment-id> -f`

The second error was just `astro deploy <deployment-id>`

2023-12-18 13:09 UTC, merged