Azureworkloadidentity docs
astronomer/docs pull request #3208
Opened 2023-12-20 19:36 UTC by astronautyates

2023-12-21 17:50 UTC, kentdanas requested changes
@astronautyates great start here. Leaving some requests for changes, let me know if you have questions about any of them.

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +sidebar_label: "Azure Workload Identity"
This needs to be added to sidebarLearn.js so it shows up in the menu

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +:::Note
```suggestion
:::note

```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +:::
```suggestion

:::
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Prerequisites
We're listing the Astro CLI and locally running project here for prereqs, but the main content is for adding the connection in Astro. I would suggest we list an Astro deployment as the prereq, and then add a note that you can also use workload identity when running OSS Airflow, but your steps might differ slightly, and link to the docs: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/azure.html

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed id
```suggestion
In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed identity. To simplify this process, Astro has command generator located in a pop up menu under the **Details** tab of your Deployment overview. 
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +If you plan to use the same workload identity for multiple deployments, you'll need to run this command for each individual deployment. However, all deployments will use the same credentials for thei
```suggestion
If you plan to use the same workload identity for multiple Deployments, you'll need to run this command for each individual Deployment. However, all deployments will use the same credentials for their connection, allowing you to share the same connection to multiple deployments at the same time via the [Astro Connection Management System](https://www.astronomer.io/solutions/connection-management/). Currently because of limits Azure has set on the number of resources allowed to leverage the same Workload Identity, the same connection can only be shared across 5 deployments. 
```
Let's move this text below the screenshot, and pull the first two sentences out of the note box (leave the Azure limit of 5 in the note).

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +![details-screen](/img/examples/connection-azure-workload-identity-1.png)
Can you put a box around the workload identity section in the screenshot? It's hard to find in the who thing. You can also crop the screenshot so anything below the 'Advanced' box or to the right of workload identity isn't included, which will make it easier to read.

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +The two credentials it requires, Managed Identity Name and Resource Group, are both available from the Managed Identity resource overview screen, as shown in the screenshot below:
```suggestion
The two required credentials, Managed Identity Name and Resource Group, are both available from the Azure Managed Identity resource overview screen: 
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +After you've entered those credentials into the pop up menu, copy the code block from under `Run in terminal:` and either open the Azure CLI directly from the web portal, or from a local terminal win
```suggestion
After you've entered those credentials into the pop up menu, copy the code block from under `Run in terminal:` and either open the Azure CLI directly from the web portal, or from a local terminal window that has the Azure CLI installed. Then, paste the code block and run it to create your Workload Identity. After the Workload Identity has been created and authenticated to the Deployment, you'll be returned a json package that contains all the necessary details for adding the connection to Airflow. Specifically, you'll need to copy the `clientId` and `tenantId` fields. 
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +![create_connectionmenu](/img/examples/connection-azure-workload-identity-4.png)
Let's crop this screenshot so there's not as much blank space, and put boxes around the Environment tab on the left and the + connection button.

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Adding Connection via the Airflow UI
```suggestion
## Create your connection using the Airflow UI
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Adding Connection via the Astro UI
```suggestion
## Create your connection using the Astro environment manager
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +To create your connection in Airflow, open up the Connections menu and create a new connection, then select `Azure` as the connection type. Then, enter the `clientId` and `tenantId` fields from befor
```suggestion
If you are not running Airflow on Astro, or if you prefer to manage connections directly from Airflow, you can add the connection using the Airflow UI. 

In the Airflow UI, go to **Admin** > **Connections**. Click **+** to add a new connection, then select `Azure` as the connection type. Enter the `clientId` and `tenantId` fields you retrieved from [Get connection details](#get-connection-details). You can also specify a `subscriptionId` for a specific service if you need to do so. 
```

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +To create your connection in Airflow, open up the Connections menu and create a new connection, then select `Azure` as the connection type. Then, enter the `clientId` and `tenantId` fields from befor
Can we add a screenshot of the connection form in this section?

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Adding Connection via the Airflow UI
We should note here that you need to have the Azure package installed in your environment - similar to this doc https://docs.astronomer.io/learn/connections/azure-data-factory#create-your-connection

2023-12-21 17:50 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Adding Connection via the Airflow UI
Are the form names here still just clientID and tenantID? The Airflow docs seem to indicate that you need to set `managed_identity_client_id` and `workload_identity_tenant_id`, which makes me wonder if these need to go in `extras` if they're not specific fields? Or did you not use those at all when you set it up? https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/azure.html

2023-12-22 15:06 UTC, astronautyates commented on learn/connections/azure-workload-identity.md
> +sidebar_label: "Azure Workload Identity"
Done

2023-12-22 17:39 UTC, kentdanas commented on sidebarsLearn.js
> +        'azure-workload-identity',
```suggestion
        'connections/azure-workload-identity',
```
This should fix the build error

2023-12-22 17:57 UTC, kentdanas requested changes
Thanks for the updates here @astronautyates. A few other requested changes.

2023-12-22 17:57 UTC, kentdanas commented on sidebarsLearn.js
> +        'connections/azure-workload-identity',
Nitpicky, but let's keep this alphabetized. So it would be the last of the Azure integrations.

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +You can also use the Azure workload identity connection option when running Open Source Airflow, however your steps might vary slightly. For further documentation, please refer to the [office Airflow
```suggestion
You can also use the Azure Workload Identity connection option when running OSS Airflow, however your steps might vary slightly. For further documentation, please refer to the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/azure.html)
```

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +## Prerequisites
Should we add the Azure CLI here? Maybe with a note that you can also run Azure CLI commands through the Azure web portal?

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed id
```suggestion
In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed identity. To simplify this process, Astro has a command generator located in a pop up menu under the **Details** tab of your Deployment overview.
```

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +![command_creation_popup](/img/examples/connection-azure-workload-identity-2.png)
```suggestion
![command_creation_popup](/img/examples/connection-azure-workload-identity-2.png)

If you plan to use the same workload identity for multiple deployments, you'll need to run this command for each individual deployment. However, all deployments will use the same credentials for their connection, allowing you to share the same connection to multiple deployments at the same time via the [Astro Connection Management System](https://www.astronomer.io/solutions/connection-management/).
```

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +![details-screen](/img/examples/connection-azure-workload-identity-1.png)
Cropping looks good, but still need to add a box around the Workload Identity section here

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +The two required credentials, Managed Identity Name and Resource Group, are both available from the Azure Managed Identity resource overview screen:
Reading through this again, I think it would make sense to start the section with this part, since the user will need to get these credentials before they go to Astro. You can keep the first intro sentence (about running commands in the Azure CLI) - then have this description of getting credentials - then go into the Astro UI and what to do with them.

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +Then, select the Azure workload identity option from the grid menu, where you'll be presented with the following screen to enter the `clientId` and `tenantId` fields from before. If you need to speci
```suggestion
Then, select the Azure workload identity option from the grid menu and enter your `clientId` and `tenantId`. If you need to specify a `subscriptionId` for a specific service, you can open up the **More options** drop down menu to do so. 
```

2023-12-22 17:57 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +In the Airflow UI, go to **Admin** > **Connections**. Click **+** to add a new connection, then select `Azure` as the connection type. Enter the `clientId` and `tenantId` fields you retrieved from [G
Not sure if GH didn't record my original comment here, but can we add a screenshot of the connection field in the Airflow UI? We should also add a note about needing the Azure provider package installed. (and it probably makes sense to break this up into numbered steps like we do in the other connection guides).

2023-12-29 20:42 UTC, astronautyates commented on learn/connections/azure-workload-identity.md
> +## Adding Connection via the Airflow UI
Nope didn't have to use those at all when I set them up, just the two given fields on the connection form.

2024-01-02 18:12 UTC, kentdanas approved these changes
Thanks @astronautyates this looks good! A few more minor comments, otherwise good to move on to copy editing.

@jwitz @lzdanski can we get a review on this please?

2024-01-02 18:12 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +- The [Azure CLI](https://learn.microsoft.com/en-us/cli/azure/). You can also run Azure CLI commands through the Azure web portal as well!
```suggestion
- The [Azure CLI](https://learn.microsoft.com/en-us/cli/azure/) or access to the Azure web portal.
```

2024-01-02 18:12 UTC, kentdanas commented on learn/connections/azure-workload-identity.md
> +![details-screen](/img/examples/connection-azure-workload-identity-1.png)
Can you adjust the box so it doesn't include the CI/CD enforcement section?

2024-01-03 11:41 UTC, jwitz requested changes
Thank you for putting this together @astronautyates ! Because we already have docs for the Astro setup, I made some edits to consolidate some steps and emphasize the Airflow UI setup. These edits should make the doc easier to maintain in the future, should we ever change the Astro setup. Let me know if this works, and I can take another pass from there.

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +- An Azure Entra ID Managed Identity that you want your Astro workloads in this deployment to run as. For information on how to create one, please refer to the [Azure documentation](https://learn.mic
```suggestion
- A Microsoft Entra [managed identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp).
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +:::
```suggestion
:::info 
If you want to use Microsoft Entra Workload ID with a generic Apache Airflow project, your setup steps might vary. See [Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/azure.html).
:::
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed id
```suggestion
To create a workload identity for your Airflow environment, you first need to link your Airflow environment to your Entra ID managed identity.

1. In your Azure portal, open the **Managed Identities** menu.
2. Search for your managed identity, click **Properties**, then copy its **Name**, **Client ID**, **Tenant ID**, and **Resource group name**.
3. Run the following command to create a workload identity for your Airflow environment [INSERT COMMAND]
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +In order to create a workload identity for your deployment that leverages your Entra ID managed identity, you'll need to execute an Azure CLI command that links your Airflow deployment and managed id
Because learn prioritizes OSS learners, I'd like to see a full set of steps that assumes you're _not_ using Astro, including a copyable command similar to what the environment manager shows. We only have partial steps for OSS users at the moment.

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +
```suggestion
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +## Create your connection using the Astro environment manager
```suggestion
## Create your connection

To create your connection in the Airflow UI:

1. In the Airflow UI, go to **Admin** > **Connections**.
2. Click **+** to add a new connection, then select **Azure** as the connection type.
3. Enter the `clientId` and `tenantId` fields you retrieved from [Get connection details](#get-connection-details) and enter them into the **Managed Identity Client ID** and **Workload Identity Tenant ID** fields respectively. You can also specify a **subscriptionId** for a specific service if required.
4. Click **Save**.
```

2024-01-03 11:41 UTC, jwitz commented on static/img/examples/connection-azure-workload-identity-6.png
Nit on the screenshot, can we use some realistic values for the input here?

2024-01-03 11:41 UTC, jwitz commented on static/img/examples/connection-azure-workload-identity-3.png
Minor nit, is it possible to crop out the "Subscription" part of this ?

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +If you plan to use the same workload identity for multiple deployments, you'll need to run this command for each individual deployment. However, all deployments will use the same credentials for thei
```suggestion
If you're using Astro, follow the steps in [Authorize Deployments to Cloud resources](https://docs.astronomer.io/astro/authorize-deployments-to-your-cloud?tab=azure#setup) to create a workload identity for your Deployment.
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +
```suggestion
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +```json
Since we already have a documented setup for Astro, I linked out to that to simplify the setup steps

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +```
```suggestion
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +To create your connection in Astro, open up the Environment tab and use the `+ connection` button to create a new connection.
```suggestion
To create your connection in Astro, follow the steps to [create a new connection in the Astro Environment Manager](https://docs.astronomer.io/astro/create-and-link-connections). Select the **Azure workload identity** connection type and enter your **Client ID** and **Tenant ID**. If you need to specify a **Subscription ID** for a specific service, you can open up the **More options** dropdown menu and add it there.
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +
```suggestion
```

2024-01-03 11:41 UTC, jwitz commented on learn/connections/azure-workload-identity.md
> +
Deleting this because this note is already included in the linked Astro setup.

2024-01-04 17:17 UTC, jwitz commented on sidebarsLearn.js
> +        'connections/azure-workload-identity',
```suggestion
        'connections/entra-workload-identity',
```

2024-01-04 17:22 UTC, jwitz requested changes
Super close here! Just one question about the example command

2024-01-04 17:48 UTC, jwitz commented on learn/connections/entra-workload-identity.md
> +id: entra-workload-id
```suggestion
id: entra-workload-identity
```

2024-01-08 10:41 UTC, jwitz commented on learn/connections/entra-workload-identity.md
> +    az identity federated-credential create --name siderean-battery-0433-$workload --identity-name 042-t49320-jg9j42390-yhjy9t-jgbjnhwre9 --resource-group vk-9043=qj-tqg9vhn24809ht-ghgv9-023qhu0-rt -
Bump

2024-01-08 10:42 UTC, jwitz requested changes
@astronautyates Are values like `https://westus2.oic.prod-aks.azure.com/b84efac8-cfee-467a-b223-23b9aea1486d/f1346028-6d70-4fde-b691-a7a9fa947caf` and `system:serviceaccount:siderean-battery-0433:siderean-battery-0433-kpo` the same for all OSS users? If not, we need to instruct how to pull the equivalent values from Azure. These look like the values Astro will automatically pull into a command for a Deployment, which shouldn't work for OSS users. pls correct me if I'm wrong tho

2024-01-08 15:54 UTC, astronautyates commented
No you're right, they won't be the same for OSS users, so it's going to be
very difficult to provide standardized directions for non-Astro users to
find similar values, OSS set ups vary immensely, and adding those
instructions provides no extra benefit to us, so Kenten and I agreed that
leaving it to only show the Astro instructions.

On Mon, Jan 8, 2024 at 5:43 AM Jake Witz ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @astronautyates <https://github.com/astronautyates> Are values like
> https://westus2.oic.prod-aks.azure.com/b84efac8-cfee-467a-b223-23b9aea1486d/f1346028-6d70-4fde-b691-a7a9fa947caf
> and system:serviceaccount:siderean-battery-0433:siderean-battery-0433-kpo
> the same for all OSS users? If not, we need to instruct how to pull the
> equivalent values from Azure. These look like the values Astro will
> automatically pull into a command for a Deployment, which shouldn't work
> for OSS users. pls correct me if I'm wrong tho
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astronomer/docs/pull/3208#pullrequestreview-1808729927>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFYZZQWESIJQNTEK3MF7JLYNPETRAVCNFSM6AAAAABA5KLDI2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBYG4ZDSOJSG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-10 13:46 UTC, jwitz commented
@astronautyates My bad, I didn't realize the OSS setup was so YMMV. I compiled some of my edits in a second PR branching off of this one, if that looks good to you then we can merge everything together into main: https://github.com/astronomer/docs/pull/3260

2024-01-10 17:12 UTC, jwitz approved these changes
Got approvals in the branch PR, so this LGTM to me now! Thanks for bearing with me @astronautyates 😅

2024-01-10 18:11 UTC, astronautyates commented
No problem Jake! Yep we make it look so easy so totally understandable to
assume others would be!

On Wed, Jan 10, 2024 at 12:12 PM Jake Witz ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Got approvals in the branch PR, so this LGTM to me now! Thanks for bearing
> with me @astronautyates <https://github.com/astronautyates> 😅
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astronomer/docs/pull/3208#pullrequestreview-1813716003>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFYZZXEITNLVPRUFH6K25DYN3DWXAVCNFSM6AAAAABA5KLDI2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJTG4YTMMBQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-11 11:05 UTC, merged