Add secrets backend preview deployment info
astronomer/docs pull request #3249
Opened 2024-01-05 22:21 UTC by lzdanski

Resolves #3248 

@jwitz - need some feedback about this draft -?
- Needs some more explanation about what this is and why/when to use it?
- Is this the right place for it to live? Or should it be in the existing Secrets backend docs (https://docs.astronomer.io/astro/secrets-backend section) or over in the Preview deployments section (https://docs.astronomer.io/astro/ci-cd-templates/template-overview#preview-deployment-templates)?

2024-01-08 12:05 UTC, jwitz reviewed
I think this is the right place, but if the only difference between the two templates is the new action step then I think we can condense this into a single template. This seems more like a configuration option for previews than a feature that needs dedicated docs.

What if we:
- Keep it as a single GH action, without tabs
- Created an inline comment in the template before the `Create Secret Variables` step that explains what the step does, how to use it, and whether you should delete it (if you don't have a secrets backend)
- Elaborate on the secrets backend functionality where you currently have `You can choose to use`, with a link out to https://docs.astronomer.io/astro/secrets-backend to explain how you actually configure AIRFLOW__SECRETS__BACKEND_KWARGS

2024-01-08 15:50 UTC, paolaperaza commented on astro/ci-cd-templates/github-actions.md
> +You can choose to use
?

2024-01-09 14:48 UTC, sunkickr requested changes

2024-01-09 14:48 UTC, sunkickr commented on astro/ci-cd-templates/github-actions.md
> +              astro deployment variable update --deployment-id ${{steps.create-dep-prev.outputs.preview-id}} AIRFLOW__SECRETS__BACKEND_KWARGS=${{ secrets.AIRFLOW__SECRETS__BACKEND_KWARGS }} --secret
`steps.create-dep-prev.outputs.preview-id` does not work unless you have a step with id set to `create-dep-prev`. For example:

```
steps:
    - name: Create Deployment Preview
      uses: astronomer/deploy-action@v0.3
      with:
        action: create-deployment-preview
        deployment-name: "test"
      id: create-dep-prev 
```

2024-01-09 14:48 UTC, sunkickr commented on astro/ci-cd-templates/github-actions.md
> +2. Set the following [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the repository hosting your Astro project. This in
I'm not sure that these values would always be in your projects `.env` file. You get the token value when you create an API token and there are many places a user could store this. Same thing with the kwargs. You get them while you are setting up a secrets backend. For these they usually saved as an env var in some way but that doesn't have to be in the `.env` file

2024-01-09 14:48 UTC, sunkickr commented on astro/ci-cd-templates/github-actions.md
> +            deployment-id: <main-deployment-id>
```suggestion
            deployment-id: <main-deployment-id>
          id: create-dep-prev
```
This step needs the id defined to be used in later steps

2024-01-12 11:43 UTC, jwitz requested changes
Overall looking good! Just had some specific thoughts around how we're framing the benefit/ usage for secrets backend. Requesting changes because I might be wrong with my interpretation and want to make sure I understand the feature before we merge

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +### Standard Deployment preview
```suggestion
### Standard Deployment preview template
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +### Secrets backend Deployment preview
```suggestion
### Deployment preview template with secrets backend implementation
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +You can choose to save your access credential information in either Github Secrets or with your own secrets backend. If you use a [secrets backend](secrets-backend.md) to manage your credentials, you
From what I can tell from the feature and templates, the purpose of the secrets backend is not to access the same type of credentials that you would access from GitHub secrets. GH secrets stores credentials related to CI/CD itself, while the secrets backend stores information that your Deployment needs to run work, such as connection information, DAG-level variables, etc.

Maybe we can shift the framing away from just "credentials" and instead refer to "Airflow objects and credentials stored in your secrets backend." Our secrets backend docs are framed primarily about configuring backends to store Airflow connections and variables

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +Unlike the standard Deployment preview setup, you need to add some additional configuration information to both your GitHub Secrets and GitHub workflow include information about your Secrets Backend
```suggestion
Unlike the standard Deployment preview setup, you need to add some additional configuration to GitHub including information. Specifically, this template makes use of the `AIRFLOW__SECRETS__BACKEND_KWARGS` environment variable to store information and credentials for your secrets backend.
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +If you use a [secrets backend](secrets-backend.md) to manage your access credentials and other sensitive information, you can configure your Github Action to use and store them while working with Dep
```suggestion
If you use a [secrets backend](secrets-backend.md) to manage your access credentials and other sensitive information, you can configure your Github Action to grant preview Deployments access to your secrets backend. This means that DAGs in the preview Deployment can access secrets such as Airflow variables and connections for testing purposes.
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +2. Set the following [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the repository hosting your Astro project. This in
Agreed, I don't think we should assume that the user configuring CI/CD has set up secrets backend at the local level first. It's possible that an admin user is configuring this pipeline with credentials that the DAG author doesn't have access to, so we should assume the use has a fresh slate going into this setup.

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +  - Secret: `<your-kwargs>`
```suggestion
  - Key 1: `ASTRO_API_TOKEN`
  - Secret 1: `<your-token>`
  - Key 2: `AIRFLOW__SECRETS__BACKEND_KWARGS`
  - Secret 2: `<your-kwargs>`
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +2. Set the following [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the repository hosting your Astro project. This in
```suggestion
2. Set the following [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the repository hosting your Astro project. This includes your Astro API Token, so that GitHub has permissions to deploy code to your Deployments or Workspaces, and your secrets backend information stored in `AIRFLOW__SECRETS__BACKEND_KWARGS`. See [Configure a secrets backend](secrets-backend.md) for more information about configuring your secrets backend as an environment variable.
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +  Refer to the [secrets backend](secrets-backend.md) overview and procedures docs to learn more about setting up a secrets backend and defining your `AIRFLOW__SECRETS__BACKEND_KWARGS`.
```suggestion
```

2024-01-12 11:43 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +### Secrets backend Deployment preview
It's wordy, but I also don't think a "Secrets backend preview" is a framing that users will be familiar with.

2024-01-15 12:12 UTC, jwitz approved these changes
Just some minor formatting and wording changes, otherwise LGTM!

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +If you use a [secrets backend](secrets-backend.md) to manage your access credentials and other sensitive information, you can configure your Github Action to grant preview Deployments access to your
```suggestion
If you use a [secrets backend](secrets-backend.md) to manage Airflow objects such as variables and connections, you can configure your action to grant preview Deployments access to your secrets backend. This means that DAGs in the preview Deployment can access your secret Airflow objects for testing purposes.
```

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +- A [Secrets backend](secrets-backend.md).
```suggestion
- A [secrets backend](secrets-backend.md).
```

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +  ```
````suggestion
    ```
````

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +  ```
This should fix the error I'm seeing in preview, but I'd double check just in case it's something else as well

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +  - Secret 2: `<your-kwargs>`
```suggestion
    - **Key 1**: `ASTRO_API_TOKEN`
    - **Secret 1**: `<your-token>`
    - **Key 2**: `AIRFLOW__SECRETS__BACKEND_KWARGS`
    - **Secret 2**: `<your-kwargs>`
```

2024-01-15 12:12 UTC, jwitz commented on astro/ci-cd-templates/github-actions.md
> +Unlike the standard Deployment preview setup, you need to add some additional configuration to GitHub including information. Specifically, this template makes use of the `AIRFLOW__SECRETS__BACKEND_KW
```suggestion
This template makes use of the `AIRFLOW__SECRETS__BACKEND_KWARGS` environment variable to store information and credentials for your secrets backend.
```

2024-01-16 21:37 UTC, lzdanski commented
addressed changes from sunkickr via slack. merging.

2024-01-16 21:39 UTC, merged