Suggested hibernation docs tweaks
astronomer/docs pull request #3254
Opened 2024-01-08 18:25 UTC by ianbuss

2024-01-09 14:31 UTC, jwitz requested changes
@ianbuss Thank you for these edits! I also threw in some example crons for users, can you check those and let me know if there's any other examples we should add? After that looks good, I'll merge this

2024-01-09 14:31 UTC, jwitz commented on astro/deployment-settings.md
```suggestion
:::tip

You can use the following example cron expressions to implement common Deployment hibernation schedules:

| Schedule | Start schedule | End schedule |
|----------|----------------|---------------|
| Hibernate from 5:00 PM to 9:00 AM| 0 17 * * * | 0 9 * * * |
| Hibernate on weekends (Friday 5:00PM to Monday 9:00AM | 0 17 * * 5 | 0 9 * * 1 |

:::
```

2024-01-09 14:31 UTC, jwitz commented on astro/deployment-settings.md
Resolves https://github.com/astronomer/docs/issues/3251

2024-01-09 14:31 UTC, jwitz commented on astro/deployment-settings.md
> +:::
```suggestion
:::warning

Cron schedules are set in UTC. If you're running a Deployment in another time zone, you must convert the cron expression for your time zone to UTC. For example, if you want your Deployment to hibernate at 17:00 EST, you  use `0 22 * * *` (22:00 UTC) as the cron expression.

:::
```

2024-01-09 14:31 UTC, jwitz commented on astro/deployment-settings.md
> +3. Select the appropriate option from the dialog: if you need to wake immediately for an indefinite period and ignore any configured schedules, select **Wake until further notice**. If you know how l
```suggestion
3. Select one of the following options for how you want your Deployment to wake up:

    - **Wake until further notice**: Your Deployment wakes up immediately for an indefinite period and ignores any configured hibernation schedules. 
    - **Wake until set time and date**: Specify a time that the Deployment should go back into hibernation after waking up. 
    - *Remove override and return to normal schedule**: The Deployment returns to following your configured hibernation schedules.
    4. Click **Confirm**.
```

2024-01-09 14:36 UTC, jwitz commented
Btw `git pull origin main` should resolve the build issues

2024-01-10 15:00 UTC, ianbuss commented
@jwitz have updated, please take another look.

2024-01-10 15:57 UTC, jwitz commented on astro/deployment-settings.md
> +:::
Bumping bc this suggestion might have gotten lost in the merge

2024-01-10 15:57 UTC, jwitz approved these changes
LGTM! Bumped one suggestion that might have gotten buried from the last review

2024-01-11 10:11 UTC, merged