[0.34] DAG only deploys
astronomer/docs pull request #3269
Opened 2024-01-12 15:03 UTC by jwitz

2024-01-22 17:25 UTC, jwitz commented on software/deploy-cli.md
> +[Insert instructions]
Need tech review here, not sure what the config is for this

2024-01-22 17:25 UTC, jwitz commented on software/deploy-cli.md
> +DAG-only deploys are enabled by default on all Deployments on Astronomer Software. When they are enabled, you must still do a full project deploy when you make a change to any file in your Astro proj
```suggestion
When this feature is enabled, you must still do a full project deploy when you make a change to any file in your Astro project that is not in the `dags` directory, or when you [upgrade Astro Runtime](manage-airflow-versions.md).
```

2024-01-22 17:26 UTC, jwitz commented
@rishkarajgi Please tag in any other tech reviewers who should check this doc for accuracy, thanks!

2024-01-22 20:31 UTC, danielhoherd commented on software/deploy-cli.md
> +[Insert instructions]
this is going to be a GUI configured feature that is enabled or disabled per-airflow-deployment. @pgvishnuram is the SME for the astronomer chart features.

2024-02-05 14:16 UTC, pgvishnuram commented on software/deploy-cli.md
> +[Insert instructions]
customer can leverage both api and ui for enabling or disabling  dag_deploy for per-airflow-deployment

2024-02-05 17:18 UTC, danielhoherd commented on software/configure-deployment.md
> +## Code deploy mechanisms
We changed this to "Code deploy mechanisms" but we reference them as "DAG deploys" everywhere else. Should we change this back? We should define our terminology and stick with it.

2024-02-05 17:26 UTC, danielhoherd commented on software/configure-deployment.md
> +## Code deploy mechanisms
I see below that we are using "Code deploy" elsewhere, but I think maybe we should define in these docs what the difference between "Code deploy" and "DAG deploy" are.

2024-02-05 17:30 UTC, danielhoherd commented on software/deploy-cli.md
> +To run your code on Astronomer Software, you need to deploy it to a Deployment. You can deploy part or all of an Astro project to an Astro Deployment using the Astro CLI.
Above I see us using both "Airflow Deployment" and the bare "Deployment", and I feel like being more specific makes it easier to understand. Also, shouldn't we avoid using "Astro" since this is not at all related to that product?
```suggestion
To run your code on Astronomer Software, you need to deploy it to an Airflow Deployment. You can deploy part or all of an Astronomer project to an Airflow Deployment using the Astro CLI.
```

2024-02-05 17:32 UTC, danielhoherd commented on software/deploy-cli.md
> +When you deploy a project, the Astro CLI builds your all files in your Astro project, including DAGs, into a Docker image. It then pushes this mage to an image registry on your Astronomer Software cl
Again we're using "Astro" here. Our product naming sure makes it hard to talk about our products in a clear way. :(

2024-02-05 17:36 UTC, danielhoherd commented on software/deploy-cli.md
> +This command returns a list of Airflow Deployments available in your Workspace and prompts you to pick one. After you execute the command, all files in your Astro project directory are built into a n
```suggestion
This command returns a list of Airflow Deployments available in your Workspace and prompts you to pick one. After you execute the command, all files in your Astronomer project directory are built into a new Docker image, the image is pushed to the Astronomer Software registry, and the Docker containers for all Airflow components in the Airflow Deployment are restarted.
```

2024-02-05 17:37 UTC, danielhoherd commented on software/configure-deployment.md
> +By default, you can deploy DAGs to an Airflow Deployment by building them into a Docker image and pushing that image to the Astronomer Registry via the CLI or API. This workflow is described in [Depl
Maybe instead of referring to "code" we should stick to "Astronomer Project"?

2024-02-05 17:39 UTC, danielhoherd commented on software/configure-deployment.md
> +By default, you can deploy DAGs to an Airflow Deployment by building them into a Docker image and pushing that image to the Astronomer Registry via the CLI or API. This workflow is described in [Depl
Oh, but I guess there's "Astro CLI" and "Astro Runtime"...

2024-02-05 17:45 UTC, danielhoherd commented on software/deploy-dags.md
> +- You can use DAG deploys to update your DAGs when you have slow upload speed on your internet connection.
We should probably rephrase this to be more objective rather than subjective:
```suggestion
- DAG deploys transmit significantly less data in most cases, which makes them quicker than image deploys when upload speeds to the Airflow Deployment are slow.
```

2024-02-05 17:45 UTC, danielhoherd commented on software/deploy-dags.md
> +By default, the Astro CLI only supports complete project image deploys. To enable DAG-only deploys:
```suggestion
By default, the Astro CLI is configured for complete project image deploys. To enable DAG-only deploys:
```

2024-02-05 17:47 UTC, danielhoherd commented on software/deploy-dags.md
> +To trigger a DAG-only deploy, run the following command from the terminal:
```suggestion
Run the following terminal command to trigger a DAG-only deploy:
```

2024-02-05 17:48 UTC, danielhoherd commented on software/deploy-dags.md
> +You can still run `astro deploy` to trigger a complete project deploy. When you do this, the Astro CLI builds all project files into a Docker image except for your DAGs, which it deploys through the
```suggestion
You can still run `astro deploy` to trigger a complete project deploy. When you do this, the Astro CLI builds all project files except for your DAGs into a Docker image, then deploys the dags using the DAG deploy mechanism.
```

2024-02-05 17:49 UTC, danielhoherd commented on software/deploy-dags.md
> +- The Astro CLI bundles the DAG code as a TAR file and pushes it to the server.
```suggestion
- The Astro CLI bundles the DAG code as a gzipped TAR file and uploads it to the server.
```

2024-02-05 17:50 UTC, danielhoherd commented on software/deploy-dags.md
> +Each Deployment includes a Pod that processes DAG only deploys called the `dag-server`. When a user triggers a DAG-only deploy to a Deployment:
```suggestion
Each Deployment includes a Pod that processes DAG only deploys called the `dag-server`, and each Airflow pod has a sidecar container to download new dags when they are available. When a user triggers a DAG-only deploy to a Deployment:
```

2024-02-05 17:55 UTC, danielhoherd commented on software/deploy-dags.md
> +- The Airflow components download the new DAG code from the DAG downloader sidecar and begin running the code.
```suggestion
- The DAG downloader in each Airflow component downloads the new DAGs from the DAG server.
- Airflow scans the dags directory on its configured interval and processes the changed files.
```

https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dag-dir-list-interval

2024-02-05 17:55 UTC, danielhoherd commented on software/deploy-dags.md
> +- Tasks that are `running` continue to run on existing workers and are not interrupted unless the task does not complete within 24 hours of the code deploy.
```suggestion
- Tasks that are `running` continue to run on existing workers and are not interrupted unless the task does not complete within 24 hours of the DAG deploy.
```

2024-02-05 17:56 UTC, danielhoherd commented on software/deploy-dags.md
> +- One or more new workers are created alongside your existing workers and immediately start executing scheduled tasks based on your latest code.
Is this true? I think the existing worker just scans the files and processes them. AFAIK no new workers are created.

2024-02-06 09:05 UTC, rujhan-arora-astronomer requested changes

2024-02-06 11:25 UTC, jwitz commented on sidebarsSoftware.js
> +            'deploy-cli',
These are just URL titles, I probably won't change these in this PR since this is a legacy link that will require redirects if we rename it

2024-02-06 11:25 UTC, jwitz commented on software/configure-deployment.md
> +- Deploy [project images](deploy-cli.md) or [DAGs only](deploy-dags.md) using the Astro CLI.
```suggestion
- Deploy [project images](deploy-cli.md) or [DAGs only](deploy-dags.md) using the Astro CLI. Deploying a project image is the only way to deploy Airflow-level configurations and dependencies to a Deployment.
```

2024-02-06 11:25 UTC, jwitz commented on software/configure-deployment.md
> +Astronomer Software supports a few different methods for deploying code to a Deployment. You can:
```suggestion
Deploying code is the process of moving code from your local machine to an Astronomer Software Deployment. A code deploy can include an entire Astro project as a Docker image, or just the code in your Astro project `dags` directory. Astronomer Software supports a few different methods for deploying code to a Deployment. You can:
```

2024-02-06 11:25 UTC, jwitz commented on software/configure-deployment.md
> +By default, you can deploy DAGs to an Airflow Deployment by building them into a Docker image and pushing that image to the Astronomer Registry via the CLI or API. This workflow is described in [Depl
Yup, Astro project is product neutral.

2024-02-06 11:25 UTC, jwitz commented on software/configure-deployment.md
> +You can also enable [DAG only deploys](deploy-dags.md) to deploy only your `dags` directory without building a Docker image.
```suggestion
You can also enable [DAG only deploys](deploy-dags.md) to deploy only your `dags` directory without building a Docker image. Note that you will still need access to Docker to authenticate to Astronomer Software before you can deploy DAGs.
```

2024-02-06 11:25 UTC, jwitz commented on software/deploy-cli.md
> +sidebar_label: 'Deploy code using the CLI'
```suggestion
sidebar_label: 'Deploy a project image'
```

2024-02-06 11:25 UTC, jwitz commented on software/deploy-dags.md
> +- If you have a CI/CD process that includes both DAG and image-based deploys, you can use your repository's permissions to control which users can perform which kinds of deploys.
This bullet is about applying permissions at the repository level, rather than the Astronomer level. E.g. you can set it on GitHub so that only specific users can commit to the DAGs folder and others can commit to `requirements.txt`

2024-02-06 11:25 UTC, jwitz commented on software/deploy-dags.md
> +- If you have a CI/CD process that includes both DAG and image-based deploys, you can use your repository's permissions to control which users can perform which kinds of deploys.
This bullet is about applying permissions at the repository level, rather than the Astronomer level. E.g. you can set it on GitHub so that only specific users can commit to the DAGs folder and others can commit to requirements.txt

2024-02-06 11:25 UTC, jwitz commented on software/deploy-dags.md
> +- One or more new workers are created alongside your existing workers and immediately start executing scheduled tasks based on your latest code.
Whoops this is leftover from Astro, deleting

2024-02-06 11:25 UTC, jwitz commented on software/deploy-dags.md
> +- One or more new workers are created alongside your existing workers and immediately start executing scheduled tasks based on your latest code.
```suggestion
```

2024-02-06 11:27 UTC, jwitz commented on software/configure-deployment.md
> +## Code deploy mechanisms
The conceptual hierarchy goes:
Code deploys (high level) >  DAG deploys / Project image deploys 

Our UI doesn't make this super clear at the moment, I submitted an issue for it https://github.com/astronomer/issues/issues/6133

2024-02-06 11:28 UTC, jwitz commented on software/deploy-dags.md
> +astro deploy --dags
```suggestion
astro deploy --dags <deployment-id>
```

2024-02-06 11:29 UTC, jwitz commented on software/deploy-dags.md
> +When you run `astro deploy` to deploy a complete project image, your non-DAG files are deployed as a Docker image while your DAG files are deployed directly to the `dag-server`.
```suggestion
When you run `astro deploy` to deploy a complete project image, the Astro CLI builds all project files including your DAGs into a Docker image as described in [Deploy a project image](deploy-cli.md).
```

2024-02-08 14:55 UTC, danielhoherd commented on software/deploy-dags.md
> +When you enable DAG-only Deployments, all DAGs in your Deployment will be erased. To continue running your DAGs, you must redeploy them using `astro deploy --dags`.
```suggestion
When you enable DAG-only Deployments, all DAGs in your Deployment will be removed. To continue running your DAGs, you must redeploy them using `astro deploy --dags`. 
```

2024-02-08 14:59 UTC, danielhoherd commented on software/deploy-dags.md
> +4. Redeploy any DAGs that were erased as a result of the configuration change. See [Trigger a DAG-only deploy](#trigger-a-dag-only-deploy)
```suggestion
4. Deploy your DAGs. This step is required when enabling the dag-deploy feature, which removes dag files that were deployed with the image. See [Trigger a DAG-only deploy](#trigger-a-dag-only-deploy)
```

2024-02-09 14:14 UTC, danielhoherd commented on software/deploy-dags.md
> +When you enable DAG-only Deployments, all DAGs in your Deployment will be removed. To continue running your DAGs, you must redeploy them using `astro deploy --dags`.
Hmm. Actually this isn't true either. astro-cli now does a double-deploy when dag-deploy is enabled. It will deploy the image and then immediately afterwards deploy the dags. It's too early in the morning for me to come up with good wording for how this works though.

2024-02-09 14:15 UTC, danielhoherd commented on software/deploy-dags.md
> +4. Redeploy your DAGs using `astro deploy --dags`. See [Trigger a DAG-only deploy](#trigger-a-dag-only-deploy). This step is required due to all DAGs in your deployed image being erased when you enab
```suggestion
4. Redeploy your DAGs using `astro deploy --dags`. See [Trigger a DAG-only deploy](#trigger-a-dag-only-deploy). This step is required due to all DAGs in your deployed image being removed from the airflow deployment when you enable the feature. 
```

2024-02-09 14:29 UTC, jwitz commented on lastUpdated.sh
> +    git push
```suggestion
    git status
```

2024-02-09 14:37 UTC, danielhoherd commented on software/configure-deployment.md
> +This mechanism builds your DAGs into a Docker image alongside all other files in your Astro project directory, including your Python and OS-level packages, your Dockerfile, and your plugins.
```suggestion
This mechanism builds your DAGs into a Docker image alongside all other files in your Astro project directory, including your Python and OS-level packages, your Dockerfile, and your plugins.
```

2024-02-09 14:40 UTC, danielhoherd commented on software/configure-deployment.md
> +You can also enable [DAG only deploys](deploy-dags.md) to deploy only your `dags` directory without building a Docker image. Note that you will still need access to Docker to authenticate to Astronom
Is this true @rujhan-arora-astronomer ? Do we need docker to auth with the app? If true, that seems like a bug to me.

2024-02-09 15:02 UTC, danielhoherd commented on software/configure-deployment.md
> +### Volume-based DAG deploys
```suggestion
### NFS Volume-based DAG deploys
```

2024-02-09 15:02 UTC, danielhoherd commented on software/configure-deployment.md
> +### Volume-based DAG deploys
Also below on line 177 we should say "dag deploy mechanism.

2024-02-09 15:05 UTC, danielhoherd commented on software/deploy-cli.md
> +When you deploy a project, the Astro CLI builds your all files in your Astro project, including DAGs, into a Docker image. It then pushes this mage to an image registry on your Astronomer Software cl
```suggestion
When you deploy a project, the Astro CLI builds your all files in your Astro project, including DAGs, into a Docker image. It then pushes this image to an image registry on your Astronomer Software cluster where your Deployment accesses the image and uses it to run Airflow containers.
```

2024-02-09 15:06 UTC, danielhoherd commented on software/deploy-cli.md
> +- [Deploy DAGs using git-sync](deploy-nfs.md).
No line item for dag-deploy?

2024-02-09 15:10 UTC, danielhoherd commented on software/deploy-cli.md
> +This command returns a list of Airflow Deployments available in your Workspace and prompts you to pick one. After you execute the command, all files in your Astro project directory are built into a n
IMHO we should reduce the usage of the word "Docker" overall, and especially when we are talking about k8s, because Docker is not part of k8s. Technically these are OCI containers, and they run in containerd. k8s used to use docker, but no longer does. OCI containers were defined using the Docker container spec, so they are related to Docker, but modern containers are technically not "docker containers"
```suggestion
This command returns a list of Airflow Deployments available in your Workspace and prompts you to pick one. After you execute the command, all files in your Astro project directory are built into a new Docker image, the image is pushed to the Astronomer Software registry, and the containers for all Airflow components in the Deployment are restarted.
```

2024-02-09 15:21 UTC, danielhoherd commented on software/deploy-dags.md
> +You can still run `astro deploy` to trigger a complete project deploy. When you do this, the Astro CLI builds all project files including your DAGs into a Docker image as described in [Deploy a proje
I think we should improve this wording. The current wording "Astro CLI builds all project files including your DAGs into a Docker image" implies that it is relevant that the dags are included in the image, when it's not. those dags will never be seen by a dag-deploy enabled deployment.

2024-02-09 15:22 UTC, danielhoherd commented on software/deploy-dags.md
> +## How DAG-only deploys work
It's interesting that we included this section. We do not appear to include a section like this for any other implementation.

2024-02-12 14:00 UTC, rishkarajgi commented on software/deploy-dags.md
> +Each Deployment includes a Pod that processes DAG only deploys called the `dag-server`, and each Airflow component has a sidecar container to download new DAGs when they are available. When a user tr
These are internal implementation details. I don't this we should be revealing these in the pretext of IP

2024-02-12 14:13 UTC, danielhoherd commented on software/deploy-dags.md
> +Each Deployment includes a Pod that processes DAG only deploys called the `dag-server`, and each Airflow component has a sidecar container to download new DAGs when they are available. When a user tr
my concern is less about IP, since this is all viewable source, but more that these details do not directly affect users, and may change in the future.

2024-02-12 16:23 UTC, jwitz commented on software/deploy-dags.md
> +- Airflow scans the dags directory on its configured interval and processes the changed files.
```suggestion
```

2024-02-12 16:23 UTC, jwitz commented on software/deploy-dags.md
> +When you run `astro deploy` to deploy a complete project image, the Astro CLI builds all project files including your DAGs into a Docker image as described in [Deploy a project image](deploy-cli.md).
```suggestion
```

2024-02-12 16:24 UTC, jwitz commented on software/deploy-dags.md
> +    This means that DAG runs could fail due to downstream tasks running code from a different source than their upstream tasks. DAG runs that fail this way need to be fully restarted from the Airflow
```suggestion

If you deploy DAGs to a Deployment that is running a previous version of your code, then tasks that are `running` continue to run on existing workers and are not interrupted unless the task does not complete within 24 hours of the DAG deploy.

These new workers execute downstream tasks of DAG runs that are in progress. For example, if you deploy to Astronomer when `Task A` of your DAG is running, `Task A` continues to run on an old Celery worker. If `Task B` and `Task C` are downstream of `Task A`, they are both scheduled on new Celery workers running your latest code.

This means that DAG runs could fail due to downstream tasks running code from a different source than their upstream tasks. DAG runs that fail this way need to be fully restarted from the Airflow UI so that all tasks are executed based on the same source code.
```

2024-02-12 16:26 UTC, jwitz commented on software/deploy-dags.md
> +
```suggestion
```

2024-02-12 16:28 UTC, merged