Update secrets backend procedure- AWS Paramstore
astronomer/docs pull request #3273
Opened 2024-01-12 20:38 UTC by lzdanski

Addresses #2921

2024-01-15 12:35 UTC, jwitz requested changes
Given that we're translating Dockerfile instructions to .env here, we should get some tech review. Adding @manmeetkaur as she has some experience in this area!

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +In this step, you add two environment variables that define the type of Secrets backend you want to use.
```suggestion
In this step, you add two environment variables that grant Airflow access to your secrets backend.
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +- `AIRFLOW__SECRETS__BACKEND` defines the type of Secrets Backend you want to use and the Airflow provider package required to use it.
```suggestion
- `AIRFLOW__SECRETS__BACKEND` defines the type of secrets backend you want to use and the Airflow provider package required to use it.
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +- `AIRFLOW_SECRETS_BACKEND_KWARGS` defines the arguments needed for Airflow to initiate with your secrets backend tool.
```suggestion
- `AIRFLOW_SECRETS_BACKEND_KWARGS` specifies the values needed for Airflow to connect to your secrets backend tool.
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +You can [define the role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#api_assumerole) that Airflow has to read, write, and delete secrets in your secrets backend
```suggestion
If you manage permissions using [roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#api_assumerole), you can specify a role that Airflow assumes to read, write, and delete secrets in your secrets backend. Specify the role's ARN using `role_arn` in `AIRFLOW__SECRETS__BACKEND_KWARGS` as shown in the following example:
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AIRFLOW__SECRETS__BACKEND="airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend"
```suggestion
    AIRFLOW__SECRETS__BACKEND=airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables"}'
```suggestion
    AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables"}
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AIRFLOW__SECRETS__BACKEND="airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend"
The GH suggestion on this one is wilding out for some reason, the only suggestion here is to just remove `env`/ quotes and keep all other formatting/ spacing the same.

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AIRFLOW__SECRETS__BACKEND="airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend"
We have to be quite careful with formatting here, I think the variables in the ZD article are based on defining them in Dockerfile rather than .env

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables", "role_arn": "arn:aws:iam::############:role/Airflow_ParameterStoreRole"}
```suggestion
AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables", "role_arn": "arn:aws:iam::############:role/Airflow_ParameterStoreRole"}'
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AWS_DEFAULT_REGION=$AWS_REGION
```suggestion
    AWS_ACCESS_KEY_ID=<your-aws-access-key-id>
    AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key>
    AWS_DEFAULT_REGION=<your-aws-region>
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    - `AWS_ACCESS_KEY_ID`
Is this the format you'll be looking for in AWS to find these values? We should use just the plain text formatting if not

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +1. Retrieve the following access credentials that your Deployment needs to access the secrets backend from [AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html).
```suggestion
1. Retrieve the following values from [AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html):
```

2024-01-15 12:35 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
```suggestion
- An AWS access key for an identity that has the required permissions to interact with Parameter Store from Airflow. If you're using IAM roles, this access key should be for the identity that owns the IAM role.

```

2024-01-17 08:09 UTC, manmeetkaur commented on astro/secrets-backend/aws-paramstore.md
> +In this step, you add two environment variables that define the type of Secrets backend you want to use.
I am inclining towards using a combination of both the statements, because that is what these vars are doing. Something like " ... that define the type of secrets backend Airflow will use and the configuration values to connect to that secrets backend". It is not "grant" access, because "grant" is taken care by the role or the credentials passed.

2024-01-17 09:26 UTC, manmeetkaur commented on astro/secrets-backend/aws-paramstore.md
> +    ENV AWS_DEFAULT_REGION=$AWS_REGION
I am little worried about specifying the credentials in the `.env` file, for the following reasons :
- we should clarify that `.env` should not be committed to source control and should be part of `.gitignore` 
- If this same Astro project needs to be deployed to Astro Deployment, then how will the deployment read the `.env` variables ? Then we need to move them to the `Dockerfile` or to the Cloud UI
- In our [Authenticate to Cloud Services](https://docs.astronomer.io/astro/cli/authenticate-to-clouds) doc, we are suggesting a diff way to access from local, (which is actually diff from what I recommend)

please let me know if you want to chat @lzdanski :)

2024-01-17 09:26 UTC, manmeetkaur commented on astro/secrets-backend/aws-paramstore.md
> +2. (Optional) Remove the environment variables from your `.env` file or store your `.env` file in a safe location, where you won't accidentally push to protect your credentials in `AIRFLOW__SECRETS__
So, I would recommend here to change this from an `Optional` step to a `Required` one and include the `.env` in `.gitignore`. Alternatively, you can suggest to remove. Also, in this page, we have not covered anything that puts secrets in the KWARGS, so might be confusing for a user why we are saying "to protect your credentials" ?

2024-01-17 09:26 UTC, manmeetkaur commented on astro/secrets-backend/aws-paramstore.md
I think we should say AWS IAM Credentials which means AWS Access Key ID and AWS Access Key Secret; And, this is only required if we are going to test from local; because for Astro, we recommend using roles.

2024-01-18 10:38 UTC, jwitz commented
@manmeetkaur Fully agreed that we should document both the `.env` setup as well as the Dockerfile setup!

The [local CLI authentication docs](https://docs.astronomer.io/astro/cli/authenticate-to-clouds) serve as a lower-effort way to get authenticated to a cloud using your own user credentials, whereas this doc covers how to use a designated IAM role for production use cases. At least that's how Olivier explained it to me when he created that doc.

I agree that the `.env` setup is a bit complicated, but the variables do end up in the Cloud UI at the end of the setup, which is what we recommend:
![Screenshot 2024-01-18 at 10 34 40 AM](https://github.com/astronomer/docs/assets/74574233/740e19e4-96af-4497-a113-bad8d64656b7)

@lzdanski  Maybe we need to have a better explanation of the test local > Cloud UI workflow. Technically the local testing is an optional step that has no impact on exporting the variables to the Cloud UI, but there's no mention of that in the doc as of now

2024-01-22 19:32 UTC, lzdanski commented
@jwitz - took another stab after our synch this morning. Will set something up with @manmeetkaur to go over our outstanding questions! I think I'm getting bogged down in how many options we have for configuring env vars in general. I think we should definitely pick one to use as examples for these secrets backends and then we can put in the overview a description of the approach + that other options exist and links to the other paths. That way we can address the difference in our [Authenticate to Cloud Services](https://docs.astronomer.io/astro/cli/authenticate-to-clouds) doc

2024-01-23 13:10 UTC, jwitz requested changes
I think we need to update some of the later steps in light of the dockerfile changes, but initial edits are looking good

2024-01-23 13:10 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    You can also choose to add the configuration variables to your `.env` file instead of your Dockerfile. Instead of using the variable format, `ENV <environment-variable-name>`, you just declare `<
```suggestion
    If you want to more easily swap out secrets backends configurations on Astro, you can add these variables to your `.env` file instead of your Dockerfile. If you do this alternate setup, you must change `ENV <environment-variable-name>` in the code block above to `<environment-variable-name>` And remove the quotations surrounding the value. For example, you would add the following to your `.env` to define `AIRFLOW_SECRETS_BACKEND`:
    
    ```text 
 
 
 AIRFLOW__SECRETS__BACKEND=airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
     ```

    Then, when you deploy to Astro, you [export these variables to a Deployment as environment variables](https://docs.astronomer.io/astro/manage-env-vars#manage-environment-variables-locally). Anyone with Workspace Operator permissions can then change out your Deployment secrets backend configuration without having to redeploy your project. 
```
Tried to add more "Why" for this alternative setup, and mentioned the other annoying change between formats. TBH this seems like a good use case for https://docusaurus.io/docs/markdown-features/#details

2024-01-23 13:10 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +    You can also choose to add the configuration variables to your `.env` file instead of your Dockerfile. Instead of using the variable format, `ENV <environment-variable-name>`, you just declare `<
(also GH messed up the preview formatting sorry about that)

2024-01-23 13:10 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +## Step 5: Deploy environment variables to Astro
```suggestion
## Step 5: Deploy to Astro
```
Because we're not using environment variables in the core setup anymore, we need to update this setup to just be `astro deploy`

2024-01-23 13:10 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +2. Remove the environment variables from your Dockerfile or store your Dockerfile in a safe location, where you won't accidentally push to protect your credentials in `AIRFLOW__SECRETS__BACKEND_KWARG
```suggestion
:::warning

To avoid exposing credentials for your secrets backend, Astronomer recommends storing the value of `AIRFLOW__SECRETS__BACKEND_KWARGS` as a secret in the repository where you maintain your Astro project.

:::
```

2024-01-23 13:10 UTC, jwitz commented on astro/secrets-backend/aws-paramstore.md
> +2. Remove the environment variables from your Dockerfile or store your Dockerfile in a safe location, where you won't accidentally push to protect your credentials in `AIRFLOW__SECRETS__BACKEND_KWARG
Not quite sure whether this is the best practice or not, but I don't think we can tell users to delete the variable from Dockerfile - if they deploy without the variable, it will erase their secrets backend config from the Deployment. WDYT @manmeetkaur

2024-01-29 11:56 UTC, jwitz commented
@lzdanski I still have some outstanding comments, lmk what you think about those and I'll take another look!

2024-05-22 13:47 UTC, closed without merging