Added 4 new Houston mutation examples to docs
astronomer/docs pull request #329
Opened 2021-04-20 20:57 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/102
Resolves https://github.com/astronomer/docs/issues/230

Rounded up our existing Houston API issues into this PR. Example mutations came from PRs, forum posts, and slack discussions.

While I was in here, I tidied up some of the language in the other mutation examples. It wasn't comprehensive, but it should make these examples easier to read.

2021-04-20 20:58 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +		            $deploymentId: <deployment-uuid>
@rbankston I assumed that this field refers to the UUID?

2021-04-20 20:59 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +			                  id
@rbankston Just curious, what to these last few sections do within the mutation? Are these variables that need to be replaced, or are these just part of the mutation?

2021-04-20 21:02 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +    workspaceUuid: astro_workspace_uuid,
@rbankston This wasn't in quotations in Pete's example, but I feel like it should be given that Deployment UUID is defined as a string. Can you confirm the correct formatting here, and also check the rest of the variables to make sure I'm defining the values in the correct format?

2021-04-20 21:02 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +mutation updateDeploymentVariables {
@rbankston I took this off of Slack, so it could probably use some additional scrutiny.

2021-04-21 16:53 UTC, rbankston approved these changes
Looks good and added feedback for some sections

2021-04-21 16:53 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +    workspaceUuid: astro_workspace_uuid,
Yeah in my examples I've put it in quotations https://github.com/astronomer/cre-graphql/blob/main/mutations/mutationCreateDeployment.graphql

2021-04-21 16:53 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +			                  id
I've only gotten then to work using this format because of the role portion and the adding:

{
  "role": "DEPLOYMENT_ADMIN",
  "deploymentId": "<UUID>",
  "email": "<email-address>"
}
as variables in the query variable field

2021-04-21 16:53 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +mutation updateDeploymentVariables {
That would create a system admin service account

2021-04-21 18:54 UTC, jwitz commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +mutation updateDeploymentVariables {
How so? I thought that was handled by `mutation CreateSystemServiceAccount`

2021-04-21 18:56 UTC, jwitz commented
Thank you for the feedback @rbankston! I've updated this to include changes for https://github.com/astronomer/docs/issues/330 and left a reply to one of your comments. Could you give this another look and respond to any outstanding questions? Thanks again.

2021-04-22 15:24 UTC, paolaperaza requested changes
Awesome to see us getting this into our docs! Dropped some suggestions/corrections - let me know what you think and I'll do a second pass.

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +1. In the Astronomer UI, acquire an API token via https://app.BASEDOMAIN/token. Alternatively, you can use the **API Key** of a [service account](https://www.astronomer.io/docs/enterprise/v0.23/deplo
```suggestion
1. In the Astronomer UI, navigate to https://app.gcp0001.us-east4.astronomer.io/token and copy the API token. Alternatively, identify the **API Key** of a [service account](https://www.astronomer.io/docs/enterprise/v0.23/deploy/ci-cd#step-1-create-a-service-account).   
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +3. Expand the `HTTP Headers` section on the bottom left of the page.
```suggestion
3. Navigate to Astronomer's [Houston API GraphQL Playground](https://houston.gcp0001.us-east4.astronomer.io/v1).
4. Expand the `HTTP Headers` section on the bottom left of the page.
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +4. Paste the API token you acquired from Step 1 in the following format: `{"authorization": "TOKEN"}`
```suggestion
5. Paste the API token you acquired from Step 1 in the following format: `{"authorization": "<api-token>"}`
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +To create a Deployment, you'll need
```suggestion
To create a Deployment, you'll need:
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +  releaseName
```suggestion
```graphql
mutation CreateDeployment {
  createDeployment(
    workspaceUuid: "workspace_uuid",
    type: "airflow",
    label: "<your-deployment-label>",
    config: {executor:"<airflow-executor>"}
)
{
  releaseName
```

Here, executor can be `LocalExecutor`, `CeleryExecutor`, or `KubernetesExecutor`.

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +2. A Deployment UUID
```suggestion
2. A Deployment ID
```

I _think_ we're standardizing on Deployment ID in the CLI/API.

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +If you don't already have a Deployment UUID, first run the query in the "Query an Airflow Deployment" section above.
```suggestion
If you don't already have a Deployment ID, run `astro deployment list` via the Astronomer CLI or follow the steps in the "Query an Airflow Deployment" section above.
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +2. A Deployment UUID
```suggestion
2. A Deployment ID
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +If you don't already have a Deployment UUID, first run the query in the "Query an Airflow Deployment" section above.
```suggestion
If you don't already have a Deployment ID, run `astro deployment list` via the Astronomer CLI or follow the steps in the "Query an Airflow Deployment" section above.
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +
Spacing here looks a little wonky - re copy paste maybe?

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +To programmatically update environment variables, you'll need:
Something wonky here with the styling - maybe double check code blocks above? Looks like this H3 header isn't being rendered correctly, but I'm not sure why 🧐

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +1. A Deployment UUID
```suggestion
1. A Deployment ID
```

2021-04-22 15:24 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +If you don't already have a Deployment UUID, first run the query in the "Query an Airflow Deployment" section to retrieve it.
```suggestion
If you don't already have a Deployment ID, run `astro deployment list` via the Astronomer CLI or follow the steps in the "Query an Airflow Deployment" section above.
```

2021-04-22 15:25 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +1. In the Astronomer UI, acquire an API token via https://app.BASEDOMAIN/token. Alternatively, you can use the **API Key** of a [service account](https://www.astronomer.io/docs/enterprise/v0.23/deplo
(We'll still want this to be `BASEDOMAIN` for Enterprise docs, but since there's only 1 URL here for Cloud let's just make it easier for users)

2021-04-22 15:25 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +3. Expand the `HTTP Headers` section on the bottom left of the page.
Felt like we were missing a step - where do you go after the user grabs the auth token from Astro UI?

2021-04-22 15:52 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +2. A Deployment UUID
Yeah I agree, wasn't sure though because the value in the mutation itself is called a UUID.

2021-04-22 15:54 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +
Ralph confirmed this was alright in an earlier comment, I think it's wonky because the technique itself is wonky: Defining variables and then using those variables in a separate call.

2021-04-22 15:55 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +To programmatically update environment variables, you'll need:
When I render this in both GitHub and Atom it looks fine... I think GitHub is getting caught on some sort of version control thing, which is often where this format comes from.

2021-04-22 19:07 UTC, jwitz commented
@paolaperaza I think this is ready for another look. Touched base with Ralph and, after testing some of the mutations, tweaked them to be better. Also added some more information about how to retrieve a Workspace ID and about some additional variables.

2021-04-22 23:08 UTC, rbankston commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +
can move everything to the left a bit so it looks like:

```
mutation AddDeploymentUser(
	$userId: Id
	$email: String!
	$deploymentId: Id!
	$role: Role!
) {
	deploymentAddUserRole(
		userId: $userId
		email: $email
		deploymentId: $deploymentId
		role: $role
	) {
		id
		user {
			username
		}
		role
		deployment {
			id
			releaseName
		}
	}
}
```

Is the same thing but formatted a little bit differently

2021-04-22 23:13 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +		            $deploymentId: <deployment-uuid>
lines 201-204 should just look like:

```
AddDeploymentUser(
		$userId: Id
		$email: String!
		$deploymentId: Id!
		$role: Role!
	)
```

Those are something the graphql query interprets in a specific way and don't need to be changed to run the query

2021-04-22 23:15 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +		            $deploymentId: <deployment-uuid>
![Screen Shot 2021-04-22 at 7 14 38 PM](https://user-images.githubusercontent.com/130836/115796011-07262500-a39f-11eb-9ae4-4146121d71af.png)

2021-04-22 23:16 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +mutation updateDeploymentVariables {
oh I replied in the spot never mind me

2021-04-22 23:25 UTC, rbankston commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +mutation updateDeploymentVariables {
Actually had to change it a little bit to:

mutation UpdateDeploymentVariables {
  updateDeploymentVariables(
    deploymentUuid: "Deployment Id",
  	releaseName: "release name",
    environmentVariables: [
      {key: "TEST",
      value: "SOME_DATA",
      isSecret: false},
      {key: "TEST1",
      value: "SOME_OTHER_DATA",
      isSecret: true}
    ]
  ) {
    key
    value
    isSecret
  }
}

2021-04-23 18:21 UTC, paolaperaza reviewed
One more quick set of comments, @jwitz !

2021-04-23 18:21 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +```
@jwitz I might be getting tripped up with the format of this mutation (which you confirmed is ok), but are these all values that users have to replace? Might reformat to make clear what users need to replace and what values will actually be generated from this command.

e.g.

```
$userId: Id
		$email: <user-email-address>
		$deploymentId: <your-deployment-id>
		$role: <desired-user-role>
```

2021-04-23 18:21 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +Then, in the **Query Variables** tab, add the following:
Not sure what this Query Variables tab is - is this a tab from a query referenced above in the doc?

2021-04-23 18:21 UTC, paolaperaza commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +2. Open Astronomer's [Houston API GraphQL Playground](https://houston.gcp0001.us-east4.astronomer.io/v1).
```suggestion
2. Open Astronomer's Houston API GraphQL Playground at https://houston.BASEDOMAIN/v1.
```

2021-04-23 18:24 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +```
Nope, these values are defined by the query table below. There shouldn't be any user-specified values in the actual mutation.

2021-04-23 18:26 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +Then, in the **Query Variables** tab, add the following:
Query variables tab appears next to the HTTP headers tab. It's pretty clear where it is within the UI, so I didn't feel the need to specify further.

![Screen Shot 2021-04-23 at 1 24 50 PM](https://user-images.githubusercontent.com/74574233/115914223-e7d6d880-a42e-11eb-856b-79026fa39dc1.png)

2021-04-23 18:27 UTC, jwitz commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +      isSecret: true}
Eep my bad, this was copied from Ralph's snippet. Will update!

2021-04-23 18:41 UTC, jwitz commented
@paolaperaza back to you! left some replies to your comments.

2021-04-23 19:04 UTC, paolaperaza approved these changes
@jwitz Word, thank you for clarifying my questions! Two more tiny comments, but approving preemptively 😊  Assume you'll address and merge as soon as you're ready. Thank you for this!

2021-04-23 19:04 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +```
Oh word, ok!

2021-04-23 19:04 UTC, paolaperaza commented on cloud/stable/05_manage-astronomer/02_houston-api.md
> +Then, in the **Query Variables** tab, add the following:
Oh roger - totally missed that because I wasn't looking at the Playground myself. Agreed that this is self-evident!

2021-04-23 19:04 UTC, paolaperaza commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +2. Open Astronomer's [Houston API GraphQL Playground](https://houston.BASEDOMAIN/v1).
Oppp - so this won't work because `BASEDOMAIN` is a thing they have to replace to get the URL! It's sort of annoying but you may just have to keep the whole URL unfurled

2021-04-23 19:04 UTC, paolaperaza commented on enterprise/v0.23/06_manage-astronomer/04_houston-api.md
> +Here, `<user-role>` can be `DEPLOYMENT_ADMIN`, `DEPLOYMENT_EDITOR`, or `DEPLOYMENT_VIEWER`.
Maybe bring this down, since it's under **Query Variables** that users have to replace stuff? Otherwise you sort of think you have to set `user-role` above, which it seems like you don't.

(Same thing for Cloud!)

2021-04-23 19:12 UTC, merged