Fix wording about CSM
astronomer/docs pull request #3305
Opened 2024-01-19 15:19 UTC by lzdanski

Resolves #3302

2024-01-19 15:24 UTC, collinmcnulty requested changes
This additional backporting is really at Astronomer's discretion, and I don't want to give the impression that a support ticket requesting a backport is likely to change that.

2024-01-19 15:24 UTC, collinmcnulty commented on astro/runtime-version-lifecycle-policy.md
> +Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions. To request a fix for a specific b
```suggestion
Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions.
```

2024-01-19 15:24 UTC, collinmcnulty commented on software/runtime-version-lifecycle-policy.md
> +Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions. To request a fix for a specific b
```suggestion
Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions.
```

2024-01-19 15:24 UTC, collinmcnulty commented on software_versioned_docs/version-0.30/runtime-version-lifecycle-policy.md
> +Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions. To request a fix for a specific b
```suggestion
Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions.
```

2024-01-19 15:24 UTC, collinmcnulty commented on software_versioned_docs/version-0.32/runtime-version-lifecycle-policy.md
> +Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions. To request a fix for a specific b
```suggestion
Occasionally, Astronomer might deviate from the defined response policy and backport a bug or security fix to releases other than the latest stable and LTS versions.
```

2024-01-22 18:57 UTC, jwitz approved these changes

2024-01-22 18:57 UTC, merged