Update docs for arrival of the Astronomer Cloud CLI
astronomer/docs pull request #331
Opened 2022-01-27 16:18 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/257

Updating all references to the CLI across Astronomer Cloud docs. This should remain a draft PR and unmerged until we have a release date and complete changelog for the newest version of the CLI.

2022-02-01 05:32 UTC, paolaperaza reviewed
A few comments back here @jwitz - mostly around release notes.

- Want to take and let me know what you think?
- Did you take a look at the 2nd half of my previous suggestions? Hadn't been committed or commented on - lmk!

Double tapped @sunkickr here too 😊

2022-02-01 05:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +In addition to being a complete CLI tool, the Astronomer Cloud CLI includes several improvements to both local project development and Astronomer Cloud management. These changes are summarized in the
```suggestion
The Astronomer Cloud CLI (`astrocloud`) is now generally available as the official command-line tool for Astronomer Cloud. It is a direct replacement of the previously released `/.astro` executable.

The Astronomer Cloud CLI sets the foundation for more robust functionality in the future and includes several significant improvements to both the local development experience as well as use cases specific to Astronomer Cloud. These changes are summarized in the following sections.

The Astronomer Cloud CLI can be installed via Homebrew. Commands take the form of:

```sh
astrocloud <command> # E.g. `astrocloud dev start`
```

We strongly recommend that all users [install the Astronomer Cloud CLI](install-cli.md) and delete the `astro` executable as soon as possible. The release of the Astronomer Cloud CLI will not impact existing Deployments and DAGs. As of February 2022, the previously released `/.astro` CLI will no longer be maintained by our team in the context of Astronomer Cloud.

```

2022-02-01 05:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +The token generated by these logins lasts longer than before. As long as you remained logged in via the UI, expect that you will have to authenticate via the CLI only once every few months.
```suggestion
Authenticating to Astronomer Cloud via the Astronomer CLI has been significantly simplified. Instead of forcing the user to copy paste a token from a browser, our improved authentication flow consists solely of a single login via the Astronomer UI.

When you run `astrocloud auth login`, your web browser automatically opens to an Astronomer UI login screen. Once you confirm that the login process was triggered from your command line, you can log in. If you're already logged in via the web browser, then you are automatically authenticated via the CLI.

Notably, the Astronomer CLI is built with refresh tokens and does not require users to re-authenticate every 24 hours. As long as you remain authenticated via the Astronomer UI, your session via the Astronomer CLI will remain valid. Expect that you will be asked to authenticate to the Astronomer CLI only once every few months instead of on a daily basis.
```

@sunkickr Would be good to have a technical explanation here - what triggers a user to have to log in again via CLI? Do you have to re-auth to UI within every 24 hours or something like that? this should also go beyond release notes - maybe in the `astro auth login` page?

2022-02-01 05:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +- After running `astrocloud dev start`, the CLI now shows you the the health status of your containers as they spin up.
```suggestion
- After running `astrocloud dev start`, the CLI now shows you the status of all Airflow Docker containers as they are created on your local machine.
```

@sunkickr Was this not happening before? Is this not the 1/3 > 2/3 > 3/3 thing?

2022-02-01 05:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +### Improved Authentication Flow
It might be nice to do a GIF here - what do we think? Would actually include this in our docs as well, not just release notes.

2022-02-01 05:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
>  ## v1.0.0
So that versioning doesn't get confusing - is it worth renaming earlier sections with -

- `## v1.0.0 (astro)`
- `## v.1.0.1 (astro`

Or something like that?

2022-02-01 05:32 UTC, paolaperaza commented on cloud/install-cli.md
> +Now that you've installed the Astronomer Cloud CLI, you're ready to create an Astronomer project and start developing locally. For instructions, read [Create an Astronomer Project](create-project.md)
@sunkickr I still think we should do this - we need to give some explicit path to using this new binary for existing customers. In steps, what do we tell them to do?

2022-02-01 10:46 UTC, jwitz commented on cloud/cli-release-notes.md
> +In addition to being a complete CLI tool, the Astronomer Cloud CLI includes several improvements to both local project development and Astronomer Cloud management. These changes are summarized in the
I'm just going to update the last sentence slightly to make it clear that there's no "automatic" impact on your existing Deployments.

2022-02-01 10:50 UTC, jwitz commented on cloud/cli-release-notes.md
> +The token generated by these logins lasts longer than before. As long as you remained logged in via the UI, expect that you will have to authenticate via the CLI only once every few months.
Language in the first paragraph feels a bit harsh on the previous login. I know it's much better than before, but let's foreground the improvements instead of starting off with how it used to be.

2022-02-01 11:00 UTC, jwitz commented on cloud/install-cli.md
> +To install and use the Astronomer Cloud CLI, you must have:
Docker is a prerequisite for both Mac and Windows. Do you think we should add prerequisites to the tabs themselves.

2022-02-01 11:16 UTC, jwitz commented on cloud/install-cli.md
> +Now that you've installed the Astronomer Cloud CLI, you're ready to create an Astronomer project and start developing locally. For instructions, read [Create an Astronomer Project](create-project.md)
I think the best way to approach this would be a `warning` level note in the Prerequisites stating "If you are using the executable binary, make sure to [steps for deleting executable] before completing this installation. For more info, see release notes"

2022-02-01 11:26 UTC, jwitz commented on cloud/cli-release-notes.md
> +### Improved Authentication Flow
Huh thought I answered something about this elsewhere - I tried making a set up for this, but I had trouble anonymizing it. If we write an issue, I can spend some time setting up a separate Mac user/ Astro login so that my mac info/ login isn't floating out there on the web.

Also - if we do any reskinning here, this .gif is gonna look out of date pretty fast. Should we just wait for the rebrand before embarking on any major asset creation?

2022-02-01 11:26 UTC, jwitz commented
@paolaperaza some responses to suggestions in here, but overall added things as you suggested them! I had two small thoughts about the CLI install doc and the release notes.

2022-02-01 16:26 UTC, sunkickr requested changes

2022-02-01 16:26 UTC, sunkickr commented on cloud/test-and-troubleshoot-locally.md
> +To have the Scheduler check for DAGs more frequently than every 30 seconds, you can set the `min_file_process_interval` to any number of seconds less than 30.
A user could also set this env var to number greater than 30 to decrease the amount of CPU being used to parse dags

2022-02-01 17:33 UTC, jwitz commented on cloud/develop-project.md
>  - Modifying the ports at which the Airflow Webserver or Postgres database start on if another service is already running on those same ports (8080 and 5432, respectively). You can override this defau
We are tracking this in a separate issue (https://github.com/astronomer/docs/issues/337) so probably not in the scope for this PR

2022-02-01 17:34 UTC, jwitz commented on cloud/install-cli.md
> +To install and use the Astronomer Cloud CLI, you must have:
Got it, probably best to add prerequisites to the tabs themselves and make them platform specific

2022-02-01 18:11 UTC, jwitz commented
@sunkickr Made changes based on your review. There are now separate prerequisites for Mac and Windows, and I now link out to our scaling Airflow guide in our Test and Troubleshoot doc instead of recommending specific performance improvements. 

I tried adding prereqs to each individual installation tab, but Docusaurus piled up all of the headers in the righthand sidebar such that it looked like there were two separate Prerequisites sections for the same doc. For now, it's probably best to leave it out of the tab structure.

2022-02-01 18:20 UTC, sunkickr commented on cloud/cli-release-notes.md
> +The token generated by these logins lasts longer than before. As long as you remained logged in via the UI, expect that you will have to authenticate via the CLI only once every few months.
I am pretty sure the UI uses refresh tokens too. You would need to re-auth when the refresh token expires which happens every couple months. A refresh token may also expire if a users permissions dramatically changed Auth0 wasn't really clear on that. I think they mean if a user loses access to something

2022-02-01 18:30 UTC, sunkickr reviewed
LGTM

2022-02-01 18:30 UTC, paolaperaza approved these changes
@jwitz This LGTM! Before you merge -

Can you actually _remove_ the new content we added to `test-and-troubleshoot-locally` and just throw that in a separate PR? I think there's a tiny bit more work there but I don't want to hold this PR up

2022-02-01 18:30 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +### Improved Authentication Flow
Yea, that's totally fine - can you just create a GH issue on this so we don't forget? I'm cool to move forward with this PR without it

2022-02-01 18:30 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +Authenticating to Astronomer Cloud via CLI consists solely of a single login via the Astronomer UI. When you run `astrocloud auth login`, your web browser now automatically opens to an Astronomer UI
```suggestion
Authenticating to Astronomer Cloud via the CLI no longer requires manually passing authentication tokens and instead consists of a simple, browser-based login process.

When you run `astrocloud auth login`, a new page in your web browser automatically opens to the Astronomer UI login screen. This screen will first ask you to confirm that the login process was triggered from the CLI and then allow you to log in. If you were already logged to the Astronomer UI in a previous session, then you will be automatically authenticated via the CLI without being prompted again.
```

2022-02-01 18:30 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +When you run `astrocloud auth login`, your web browser automatically opens to an Astronomer UI login screen. Once you confirm that the login process was triggered from your command line, you can log
```suggestion
```

2022-02-01 18:30 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +- After running `astrocloud dev start`, the CLI now shows you the status of all Airflow Docker containers as they are created on your local machine.
```suggestion
- You can now run `astrocloud dev start` without having to disable [Docker Buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/). This resolves a [common issue](https://forum.astronomer.io/t/buildkit-not-supported-by-daemon-error-command-docker-build-t-airflow-astro-bcb837-airflow-latest-failed-failed-to-execute-cmd-exit-status-1/857) where users with Docker Buildkit enabled could not run this command.
- After running `astrocloud dev start`, the CLI shows you the status of all Airflow Docker containers as they are created on your local machine. Now, it's easier to know that if the Airflow UI is unavailable, it's likely because the Airflow Webserver container is still spinning up.
```

2022-02-01 18:30 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +- After running `astrocloud dev start`, the CLI now shows you the status of all Airflow Docker containers as they are created on your local machine.
@sunkickr Does it actually list the status of all containers, or is this just the Webserver feedback?

2022-02-01 18:30 UTC, paolaperaza commented on cloud/install-cli.md
> +If you currently use the `astro` executable file to run CLI commands, you must delete this file and any related system environment variables or symbolic links before installing the Astronomer Cloud C
```suggestion
If you currently use the `astro` executable file to run CLI commands, we strongly recommend that you upgrade to the Astronomer Cloud CLI. To do this:

1. Delete the `astro` file from your local directories
2. Install the Astronomer Cloud CLI by following the steps above

Make sure to delete any related system environment variables or symbolic links to `astro` if you set them. Upgrading to Astronomer Cloud CLI will not affect running tasks or existing Deployments.
```

2022-02-01 18:30 UTC, paolaperaza commented on cloud/install-cli.md
> +Now that you've installed the Astronomer Cloud CLI, you're ready to create an Astronomer project and start developing locally. For instructions, read [Create an Astronomer Project](create-project.md)
Agreed, shouldn't be permanent! Added a suggestion to Jake's addition above. Resolving this convo for RN!

2022-02-01 18:30 UTC, sunkickr approved these changes

2022-02-01 18:31 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +In addition to being a complete CLI tool, the Astronomer Cloud CLI includes several improvements to both local project development and Astronomer Cloud management. These changes are summarized in the
not sure I follow the "automatic" vs not - I think it's just "there will be no impact" - automatic or otherwise - there wouldn't be a "manual" impact either?

2022-02-01 18:32 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +The token generated by these logins lasts longer than before. As long as you remained logged in via the UI, expect that you will have to authenticate via the CLI only once every few months.
Tweaked wording here in a different comment line - I agree on not being too harsh, but for the context of release notes I do think a "before" and "after" is important

2022-02-01 18:32 UTC, sunkickr commented on cloud/cli-release-notes.md
> +- After running `astrocloud dev start`, the CLI now shows you the status of all Airflow Docker containers as they are created on your local machine.
just webserver but the webserver is dependent on postgres and scheduler containers

2022-02-01 18:33 UTC, sunkickr commented on cloud/cli-release-notes.md
> +- `astrocloud deploy` now shows a list of your Deployments organized by when each Deployment was created.
It was actually a random order

2022-02-02 16:48 UTC, sunkickr commented
we may need to get the steps in this issue into one of these docs:
https://github.com/astronomer/cloud-cli/issues/59

2022-02-03 16:26 UTC, sunkickr commented
@jwitz the migration details look good to me

2022-02-03 18:10 UTC, jwitz commented on cloud/cli-release-notes.md
> +- After running `astrocloud dev start`, the CLI now shows you the status of all Airflow Docker containers as they are created on your local machine.
Constance mentioned in the equivalent Enterprise release notes that it might be better to frame the Buildkit as a positive (enable Buildkit vs. don't disable it)

2022-02-03 18:49 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +Release date: February 1, 2022
```suggestion
Release date: February 3, 2022
```

2022-02-03 22:00 UTC, paolaperaza approved these changes

2022-02-03 22:00 UTC, paolaperaza commented on cloud/cli-release-notes.md
> +### Improved Authentication Flow
```suggestion
### New Authentication Flow
```

2022-02-03 22:04 UTC, merged