Update Deployment Settings and hosted reference docs
astronomer/docs pull request #3317
Opened 2024-01-23 18:11 UTC by lzdanski

Resolves #3311

2024-01-23 19:23 UTC, lzdanski commented
@jwitz - there's a lot of file touches in this PR to fix the linking, but the big changes are

- deployment-settings.md (moved content out)
- deployment-details.md (new page)
- deployment-resources.md (new page)

2024-01-25 13:57 UTC, jwitz requested changes
Overall content split looks good, had some suggestions for naming and the overview page. Because this is a heavy refactor, can you also rebase from `main` so that Docusaurus starts checking for broken anchor links? Thanks!

2024-01-25 13:57 UTC, jwitz commented on astro/deployment-resources.md
> +sidebar_label: 'Configure resources'
```suggestion
sidebar_label: 'Deployment resources'
```
To make consistent with the other sidebar title

2024-01-25 13:57 UTC, jwitz commented on astro/deployment-resources.md
> +Update Deployment resource settings to optimize performance and reduce the cost of running Airflow in the cloud.
```suggestion
Your Deployment resources are the computational resources Astro uses to run Airflow in the cloud. Update Deployment resource settings to optimize performance and reduce the cost of running Airflow in the cloud.
```

2024-01-25 13:57 UTC, jwitz commented on astro/deployment-details.md
> +title: 'Deployment settings'
```suggestion
sidebar_label: 'Deployment details'
title: 'Deployment details'
```

2024-01-25 13:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Transfer a Deployment to another Workspace in your Organization.
```suggestion
```
This isn't included in the details doc atm

2024-01-25 13:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Add or delete a Deployment alert email.
```suggestion
- Deployment names and descriptions.
- Deployment contact emails.
- Rules for what types of deploys are allowed.
```
It felt odd to present a list of verbs to describe the noun of "details", so framing this around objects in stead of actions

2024-01-25 18:13 UTC, lzdanski commented on astro/deployment-resources.md
> +sidebar_label: 'Configure resources'
I think we should go the other direction and switch to "configure deployment resources'/ 'configure deployment details' because these are all actions in the doc

2024-01-29 15:50 UTC, paolaperaza commented on astro/configure-worker-queues.md
> +### Hosted worker types
Inconsistent H3 title between Hosted vs. Hybrid?

2024-01-30 16:15 UTC, lzdanski commented on astro/deployment-resources.md
> +### Scheduler size
```suggestion
```

2024-01-30 16:15 UTC, lzdanski commented on astro/configure-worker-queues.md
> +### Hybrid worker type setup
change back to note

2024-01-30 16:15 UTC, lzdanski commented on astro/configure-worker-queues.md
> +### Hosted worker types
bump to before the hybrid note

2024-01-31 15:57 UTC, jwitz approved these changes
Just some edits for the overview, otherwise LGTM!

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
> +Use [Deployment details](deployment-details.md) to manage the administration of your Deployment. This includes includes actions like updating information about your Deployment or transferring it to a
```suggestion 
[Deployment details](deployment-details.md) are high level settings that define how users can interact with the Deployment. These settings include:
```

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Delete a Deployment.
```suggestion
```

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Delete a Deployment.
Let's cut this for not since it's kind of the odd one out and might be refactored in the future

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
> +- Rules for what types of deploys are allowed.
```suggestion
- Rules for what types of deploys are allowed.
- Your Deployment's current Workspace.
```

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  After you create an Astro Deployment, you can modify its settings using the Cloud UI and Astro CLI to tailor its performance. There are two categories of options for configuring your Astro Deployment
```suggestion
After you create an Astro Deployment, you can modify its settings using the Cloud UI and Astro CLI to tailor its performance. There are two categories of Deployment configurations: Deployment _details_ and _resources_.
```

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Delete a Deployment.
Or frame it as a noun somehow

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
> +You also have [configuration options](deployment-resources.md) that allow you to customize the resource use, infrastructure, and performance of your Deployment. This means you can optimize how your D
```suggestion
[Deployment resources](deployment-resources.md) let you customize the resource use, infrastructure, and performance of your Deployment. Use these settings to optimize Deployment processing, optimize compute resources and cost, and enable advanced use cases with intensive workloads. The following configuration options are available for customizing your resource use:
```

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  - Configure Kubernetes Pod resources.
There's a bullet in here called "Update your Airflow configuration". Maybe we should make this more specific as: "Customize your Airflow environment through environment variables"

2024-01-31 15:57 UTC, jwitz commented on astro/deployment-settings.md
>  This document focuses on configuring Deployments through the Cloud UI. To configure Deployments as code using the Astro CLI, see [Manage Deployments as code](manage-deployments-as-code.md).
```suggestion
These documents focus on configuring Deployments through the Cloud UI. To configure Deployments as code using the Astro CLI, see [Manage Deployments as code](manage-deployments-as-code.md).
```

2024-01-31 15:57 UTC, jwitz commented on static/_redirects
> +/astro/resource-reference-hosted#worker-type /astro/deployment-resources#hosted-worker-types 301
FYI sadly as of today, Netlify does NOT detect broken anchors even though docusaurus does. Thankfully you've already fixed the relative links to these locations, but I need to work with Katie so that full URLs shared outside of the site are also redirected properly

2024-02-02 19:15 UTC, lzdanski commented on static/_redirects
> +/astro/resource-reference-hosted#worker-type /astro/deployment-resources#hosted-worker-types 301
another finding - the anchor link checker will make duplicate reports of anchor link problems in partials/ .mdx files!

2024-02-02 19:18 UTC, lzdanski commented
Have addressed all review feedback - ready to merge first thing Monday AM. (Don't want to merge a major IA restructure on Friday afternoon)

2024-02-05 14:33 UTC, merged