Fix runtime version policy wording
astronomer/docs pull request #3339
Opened 2024-01-26 22:35 UTC by lzdanski

Resolves #3338

2024-01-30 12:27 UTC, jwitz requested changes
Made some changes based on how I understand the issue, but overall this is definitely an improvement!

2024-01-30 12:27 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.md
> +For each major Runtime version, only the latest `minor.patch` version receives fixes. Because Runtime versions are immutable, anytime new features or fixes are added to the Astro Runtime, they are re
```suggestion
For each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you to upgrade your Astro Runtime version to see if it resolves the issue.
```
> Because Runtime versions are immutable, anytime new features or fixes are added to the Astro Runtime, they are released as a patch version of the Runtime.

Sadly this is not accurate, bug fixes also are delivered through minor versions.

2024-01-30 12:27 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.md
> +If you report an issue with an Astro Runtime version that is not latest patch, the Astronomer Support team might ask that you to upgrade if the reported issue requires a bug fix. For example if you r
```suggestion
For example, if you report an issue occurring on a Deployment running Astro Runtime 9.0.0, Astronomer support might ask you to first upgrade to the latest `9.minor.patch` version before troubleshooting your issue any further. If the issue still persists after upgrading, any fixes to that issue will be delivered in a new minor or patch release.
```

2024-01-30 12:27 UTC, jwitz commented on software/runtime-version-lifecycle-policy.md
> +For each major Runtime version, only the latest `minor.patch` version receives fixes. Because Runtime versions are immutable, anytime new features or fixes are added to the Astro Runtime, they are re
Same edits as for Astro

2024-01-31 21:00 UTC, rwalshe requested changes
'For example, if you report an issue occurring on a Deployment running Astro Runtime 9.0.0, Astronomer support might ask you to first upgrade to the latest `9.minor.patch` version before troubleshooting your issue any further. If the issue still persists after upgrading, any fixes to that issue will be delivered in a new minor or patch release.'

May I suggest that we also state that 'Astronomer policy provides backward-compatibility guarantees for upgrades within a major version'.  This will give confidence and reduce pushback if we tell customers to upgrade the minor.patch.

2024-01-31 23:21 UTC, rwalshe approved these changes

2024-02-01 08:02 UTC, ephraimbuddy commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
```suggestion
Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you upgrade your Astro Runtime version to see if that resolves the issue.
```

2024-02-01 09:24 UTC, phanikumv commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
+1 to Ephraim's suggestion

2024-02-01 09:24 UTC, phanikumv commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
cc @rishkarajgi can you confirm on above point^

2024-02-01 10:04 UTC, rishkarajgi commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
We use this url for Runtime updates - https://updates.astronomer.io/astronomer-runtime
And Runtime 10 is listed. So I'm assuming the Runtime support policy us agnostic of the product (Astro/Software)

2024-02-01 11:11 UTC, ephraimbuddy commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
Then I think here should be updated to include runtime 10 or am I missing something?

2024-02-01 13:23 UTC, jwitz commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
Yes it should, sorry the Software version is lagging slightly behind the Astro version. @lzdanski This is doc is definitely a candidate for https://docusaurus.io/docs/markdown-features/react#importing-markdown

2024-02-01 17:49 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
```suggestion
For each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you upgrade your Astro Runtime version to see if that resolves the issue.
```
Not sure these concepts are related though "however"

2024-02-01 17:56 UTC, jwitz reviewed
Some final suggestions that apply to all versions, but let's hold on this until we can confirm the backwards compatibility line as an official support policy

2024-02-01 17:58 UTC, lzdanski commented on software/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
```suggestion
For each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you upgrade your Astro Runtime version to see if that resolves the issue. Astronomer guarantees backwards compatibility for upgrades completed within a given supported major version. 
```

2024-02-01 17:58 UTC, lzdanski commented on software_versioned_docs/version-0.30/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version, however for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
```suggestion
For each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you upgrade your Astro Runtime version to see if that resolves the issue. Astronomer guarantees backwards compatibility for upgrades completed within a given supported major version. 
```

2024-02-01 17:58 UTC, lzdanski commented on software_versioned_docs/version-0.32/runtime-version-lifecycle-policy.md
> +Astronomer policy provides backward-compatibility guarantees for upgrades within a major version however, for each supported major Runtime version, bug fixes are delivered only through new `minor.pat
```suggestion
For each supported major Runtime version, bug fixes are delivered only through new `minor.patch` versions. If you report an issue with a supported Astro Runtime image that is not on the latest `minor.patch` version, Astronomer Support might ask that you upgrade your Astro Runtime version to see if that resolves the issue. Astronomer guarantees backwards compatibility for upgrades completed within a given supported major version. 
```

2024-02-01 18:53 UTC, jwitz approved these changes
Just updated my original suggestions to have softer language ("guarantees" > "strives to ensure"), with that this LGTM!

2024-02-01 19:21 UTC, lzdanski commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
```suggestion
| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
| [10](runtime-release-notes.md#astro-runtime-1000)                    | 2.8             | December 18, 2023  | June 2024               |
```

2024-02-01 19:34 UTC, lzdanski commented on software/runtime-version-lifecycle-policy.md
> +| [9](https://docs.astronomer.io/astro/runtime-release-notes#astro-runtime-900) (LTS) - Latest Patch | 2.7             | August 18, 2023    | January 2025            |
Added v10 to software runtime table

2024-02-01 19:46 UTC, lzdanski commented
Merging with Richard + Jake's approvals. Thanks all.

2024-02-01 19:55 UTC, merged