Restructure GitHub Actions CI/CD
astronomer/docs pull request #3340
Opened 2024-01-27 22:40 UTC by lzdanski

Resolves #3312

2024-01-30 15:49 UTC, lzdanski commented on astro/ci-cd-templates/github-actions.md
>  GitHub Action templates use the Astronomer-maintained `deploy-action`, which is available in the [GitHub Marketplace](https://github.com/marketplace/actions/deploy-apache-airflow-dags-to-astro). This
Shift the scope of this page to an overview of the choice between the three different templates, then add the list, maybe add an "before you begin" section to describe what needs to go into it.

2024-01-30 15:50 UTC, lzdanski commented on astro/ci-cd-templates/github-actions.md
>  - Choose a deploy type based on the files that were changed in a commit. This allows you to use the same template for DAG deploys and image deploys.
remove duplicative headers, replace with "Available templates"

2024-01-30 15:56 UTC, lzdanski commented on astro/ci-cd-templates/github-actions.md
>  - Choose a deploy type based on the files that were changed in a commit. This allows you to use the same template for DAG deploys and image deploys.
remove this page entirely and redistribute

2024-02-02 11:20 UTC, jwitz commented on astro/ci-cd-templates/github-actions-private-network.md
> +If you do not have access to Astronomer's `deploy-action`, use one of the following [private network templates](#private-network-templates). These templates also work for if you use GitHub Enterprise
```suggestion
If you don't have access to the Astronomer [deploy action](https://github.com/astronomer/deploy-action) because you can't access the public internet from your GitHub repository, use one of the following private network templates to deploy to Astro. 
```
Not sure how that header made it past the CI checks!

2024-02-02 11:21 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deploy-action.md
> +    groupId= "deploy-action-templates"
```suggestion
    groupId= "setup"
```

2024-02-22 20:42 UTC, lzdanski commented
@jwitz - I've been chipping away at this and I think it's ready for another review cycle, it feels so close to done

2024-02-23 11:52 UTC, jwitz requested changes
This is super super close! Just a few suggestions for how to clean up the overview sections, but the structure is exactly where it needs to be

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deploy-action.md
> +title: GitHub Actions templates for deploys to Astro
```suggestion
title: GitHub Actions templates for deploying code to Astro
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +title: GitHub Actions templates for preview Deployments
```suggestion
title: GitHub Actions templates for deploying code to preview Deployments on Astro
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +
```suggestion
```
Deleting this on the basis of the line "Each implementation might have additional requirements", which implies that the top level prerequisites apply to all sub-topics.

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +- A [Deployment](create-deployment.md).
```suggestion
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +- A [secrets backend](secrets-backend.md).
```suggestion
- A [secrets backend](secrets-backend.md), such as Hashicorp Vault.
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +The Astronomer [deploy action](https://github.com/astronomer/deploy-action/tree/deployment-preview#deployment-preview-templates) includes several sub-actions that can be used together to create a com
```suggestion
The Astronomer [deploy action](https://github.com/astronomer/deploy-action/tree/deployment-preview#deployment-preview-templates) includes several sub-actions that can be used together to create a complete [Deployment preview](ci-cd-templates/template-overview.md#preview-deployment-templates) pipeline, a configuration that allows you to test your code changes in an ephemeral development Deployment before promoting your changes to a production Astro Deployment.
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +The Deployment preview templates use GitHub secrets to manage the credentials needed for GitHub to authenticate to Astro. You can also use a secret to store the credentials for your [secrets backend]
```suggestion
The Deployment preview templates use GitHub secrets to manage the credentials needed for GitHub to authenticate to Astro. You can specify the credentials for your [secrets backend](secrets-backend.md) so that preview Deployments have access to secret Airflow variables or connections during tests. See [Deployment preview template with secrets backend implementation](#deployment-preview-template-with-secrets-backend-implementation).
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +
```suggestion
```
Trying to find ways to trim this overview, since you have to scroll quite a bit before getting to the actual setup

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deployment-preview.md
> +Each implementation might have additional requirements.
```suggestion
Specific templates might have additional requirements.
```

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deploy-action.md
> +- Create a preview Deployment to test your code before deploying to production. A Deployment preview is an Astro Deployment that mirrors the configuration of an existing Deployment.
Link to other doc here, or take this bullet out?

2024-02-23 11:52 UTC, jwitz commented on astro/ci-cd-templates/github-actions-deploy-action.md
> +:::
Should we move this note to the end of the overview section since it applies to a relatively small group of users?

2024-02-23 15:12 UTC, lzdanski commented on astro/ci-cd-templates/github-actions-deploy-action.md
> +- Create a preview Deployment to test your code before deploying to production. A Deployment preview is an Astro Deployment that mirrors the configuration of an existing Deployment.
```suggestion
- Create a [preview Deployment](cli/github-actions-deployment-preview.md) to test your code before deploying to production. A Deployment preview is an Astro Deployment that mirrors the configuration of an existing Deployment.
```

2024-02-26 11:31 UTC, jwitz approved these changes
This LGTM! Awesome work

2024-02-26 14:19 UTC, merged