Reporting Dashboard docs
astronomer/docs pull request #3341
Opened 2024-01-28 20:51 UTC by lzdanski

Resolves #3315

2024-01-29 15:36 UTC, paolaperaza commented on astro/reporting-dashboard.md
> +Astro provides [a Dashboard](https://cloud.astronomer.io/dashboards) with a consolidated view of important metrics about your Organization's use of Astro. This includes data about your Deployment per
Add sentence about "why" you use these dashboards or what they can help you understand

2024-01-29 15:44 UTC, paolaperaza commented on astro/reporting-dashboard.md
> +Only users with **Organization Owners** and **Organization Admins** [user permissions](user-permissions.md#organization-roles) can access reporting Dashboards.
Consider just adding the "how to access" at the bottom of the overview section since it's so short

2024-01-29 15:46 UTC, paolaperaza commented on astro/reporting-dashboard.md
> +## Export data from reporting Dashboards
I'd move this down to the bottom

2024-01-29 15:46 UTC, paolaperaza commented on astro/reporting-dashboard.md
> +This tab allows you to quickly inspect the activity and performance of your Deployments, and compare them to one another which means you can quickly identify any Deployments, DAGs, or tasks that have
Run on sentence?

2024-01-29 15:46 UTC, paolaperaza commented on astro/reporting-dashboard.md
> +All Dashboards include sharing how recently the data was updated in the **Data available through**.
Capital "D" or not? Or are we using interchangeably with `report`?

2024-01-30 11:51 UTC, jwitz requested changes
A few organization and content suggestions throughout. Some general style things I noticed:
- We should refer to individual tabs as "dashboards", not "tabs" or "views". The menu in general is "Deployments".
- We should use `-` instead of `*` for bullets
- Currently no information about how data is collected/ displayed (I think it would be good to mention Sigma here)

Lastly, I wonder how hard this doc will be to maintain in the future if the changes to the dashboards are made outside of the normal release cadence. How will the docs team be notified about name changes and display changes? This leads me to think we might want to be a little more abstract with some of the data details, or to not include them at all and instead focus on improving the help text within the dashboards themselves

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +The **Deployment Detail** report shows a table of all your non-deleted Deployments in your Organization, indexed by Workspace Name. You can filter this table by **Workspace Name** or **Deployment Nam
```suggestion
The **Deployment Detail** report shows a table of all Deployments in your Organization, indexed by Workspace Name. For each Deployment, the dashboard shows your Deployment configurations as awell as usage metrics including task run counts, DAG run counts, and operator counts.
```
- Are there any dashboards where you can view deleted Deployments? If not, then the distinction here seems unnecessary
- Are these task RUN counts or just task counts? I assume it's the former if it's a usage dashboard. But we should confirm

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +This report view also highlights if you have any Deployments that use a version of the Astro Runtime that are either unsupported or are expected to reach end of maintenance in the next six months.
```suggestion
Use this dashboard to check that your Deployment has the appropriate resources based on the number of DAGs it runs. You can also use this dashboard to check whether your Astro Runtime version is in support or needs to be upgraded.
```

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +If you have a service level agreement (SLA) where your DAGs need to complete by a certain consistent time, you can use this view to compare DAG completion times with an SLA time. This view can help y
```suggestion
The DAG SLA dashboard allows you to simulate a service level agreement (SLA) for when a DAG should complete and then compare your DAG runs against the SLA. Use this dashboard to ensure that your Organization meets your SLA obligations, or to create and alert on new SLAs.

To use this dashboard, you must first define an SLA and the DAGs which should be compared against the SLA.
```

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +If you have a service level agreement (SLA) where your DAGs need to complete by a certain consistent time, you can use this view to compare DAG completion times with an SLA time. This view can help y
This one is tricky because you can actually configure an SLA at the DAG or task level in code, and this dashboard is only a simulation of those SLAs. It has no affect/ connection to real SLAs that users might have configured. 

That might be worth clarifying, and we also might want to ask product whether we should recommend users "Alert on" a metric SLA instead of configuring their own SLA in DAGs or Astro Alerts.

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +The report generates a line graph that shows the **Median End Time** of the DAG, the **Average End Time**, and the **SLA** time you defined.
```suggestion
The report generates a line graph that shows the **Median End Time** of the DAG, the **Average End Time**, compared to the **SLA** time you defined.
```

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +## Billing Details (Hosted Only)
Any reason we chose a different title from the dashboard name?

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +In the **Cost Breakdown** tab of your Dashboard, you can find detailed information regarding your accumulated cost per time period, depending on the Workspace Name and Deployment.
```suggestion
In the **Cost Breakdown** tab of your Dashboard, you can find detailed information about how much you spend on Astro over time for each of your Workspaces and Deployments. Use this data alongside your other dashboards to identify the biggest opportunities for cost reduction in your Organization.
```

2024-01-30 11:51 UTC, jwitz commented on astro/reporting-dashboard.md
> +You can examine how your Deployments and Workspaces use Operators, and the frequency that their tasks succeed and fail.
```suggestion
You can examine how your Deployments and Workspaces use Operators, and the frequency that their tasks succeed and fail. Use this data to identify types of operators that could be replaced with more efficient alternatives, or to find operators that fail more than expected. 
```

2024-02-01 14:41 UTC, lzdanski commented on astro/reporting-dashboard.md
> +## Billing Details (Hosted Only)
It got changed!

2024-02-06 23:40 UTC, lzdanski commented on astro/reporting-dashboard.md
> +    - **Alert when...** to define criterial when Astro will send you a data export of the element or dashboard
It does sound different, but the actual action is a data export like the others, it's just done conditionally I think?

2024-02-07 14:29 UTC, jwitz requested changes
This doc is a joy to read and navigate now! Just a few follow up suggestions and ideas that I missed on my first pass

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +![Quickly examine summaries about your Organization's DAG activity at the DAG and Workspace level.](/img/docs/dash-organization-overview.png)
```suggestion
![The main section of the Organization Overview dashboard, showing Deployments and task counts over time as a bar chart](/img/docs/dash-organization-overview.png)
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +By examining your data at the Organization level, you can quickly identify Deployments with large numbers of failing tasks by simply looking at the graphs or charts for outliers. Then, you can filter
```suggestion
By examining your data at the Organization level, you can identify Deployments with large numbers of failing tasks by looking at the graphs or charts for outliers. Then, you can filter by time period to see if there have been similar events in the past and when.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +The **Deployment Detail** dashboard shows a table of all Deployments in your Organization, indexed by Workspace Name. For each Deployment, the dashboard shows your Deployment configurations as well a
```suggestion
The **Deployment Detail** dashboard shows a table of all Deployments in your Organization, indexed by Workspace name. For each Deployment, the dashboard shows your Deployment configurations as well as use metrics like task run counts, DAG run counts, and operator counts.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +Use this dashboard to check that your Deployment has the appropriate resources based on the number of DAGs it runs. You can also use this dashboard to check whether your Astro Runtime version is curr
```suggestion
Use this dashboard to check that your Deployment has the appropriate resources based on the number of DAGs it runs. You can also use this dashboard to check whether a Deployment's Astro Runtime version is currently supported.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +### Set up an SLA
```suggestion
### Create an SLA simulation
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +    - **Alert when...** to define criterial when Astro will send you a data export of the element or dashboard
I think the use case is different. A user might complete a manual export when they want data for a report or a presentation. But a user setting up an alert is doing so because they want to be alerted when something is wrong in the system, and they want the data presented to them immediately when said thing happens. 

Given the discrepancy in use cases, I don't think it hurts to have these documented as separate topics. We should also see whether the product team expects users to configure these alerts as part of their overall alerting infrastructure - for example, do we want users to replace their Airflow code level SLAs with our own SLA dashboard alerts?

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +In the **Cost Breakdown** tab of your Dashboard, you can find detailed information about how much you spend on Astro over time for each of your Workspaces and Deployments. Use this data alongside you
```suggestion
In the **Cost Breakdown** dashboard, you can find detailed information about how much you spend on Astro over time for each of your Workspaces and Deployments. Use this data alongside your other dashboards to identify the biggest opportunities for cost reduction in your Organization.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +To create an SLA, you must first define an SLA and then select the DAGs you want to compare it to.
```suggestion
To simulate an SLA, you must first define an SLA and then apply it to specific DAGs.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +The DAG SLA dashboard allows you to simulate a service level agreement (SLA) for when a DAG should complete and then compare how frequently your DAG runs complete within the SLA. Use this dashboard t
```suggestion
The DAG SLA dashboard allows you to simulate a service level agreement (SLA) for when a DAG should complete and then compare how frequently your DAG runs complete within the SLA. Use this dashboard to check how frequently your Organization meets your SLA obligations, or to create an alert when specific SLAs are breached.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +You can examine how your Deployments and Workspaces use Operators, and the frequency that their tasks succeed and fail. Use this data to identify types of operators that could be replaced with more e
```suggestion
The **Operator Use** dashboard shows how your Deployments and Workspaces use Operators, as well as how often tasks succeed and fail when using specific operators. Use this data to identify types of operators that could be replaced with more efficient alternatives, or to find operators that fail more than expected. This dashboard provides data to answer the questions, *What are the top operators used across my organization?* and *Which workspace is using the selected operators the most?*.
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +You can filter your data, export reports, or set up an email alert, which sends a copy of the data to an email address under certain circumstances.
```suggestion
```
Seems like a general description unrelated to the dashboard

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +title: "Reporting dashboard"
```suggestion
title: "View metrics across your Organization with Astro reporting dashboards"
```

2024-02-07 14:29 UTC, jwitz commented on astro/reporting-dashboard.md
> +sidebar_label: 'Reporting dashboard'
```suggestion
sidebar_label: 'Reporting dashboards'
```

2024-02-07 14:29 UTC, jwitz commented on sidebarsAstro.js
> +        "reporting-dashboard",
Would it make sense to put this in "View metrics"? It also begs the question of what we should do with [this page](https://docs.astronomer.io/astro/organization-metrics), which is a reallllyyyy legacy metric that was really only relevant when we were charging customers per successful task run. I wouldn't mind shoving that page in Reference or renaming it to give this new doc front billing as _the_ center for Org metrics

2024-02-07 14:29 UTC, jwitz commented on static/img/docs/dash-DAG-SLA.png
These screenshots need 1 pixel black borders - I will say though, they show up in a surprisingly reasonable size on the rendered preview!

2024-02-07 14:50 UTC, lzdanski commented on static/img/docs/dash-DAG-SLA.png
Yes these aren't the final edits, just wanted to get something in there as placeholders in case there's more UI changes before we're ready to publish

2024-02-07 14:55 UTC, lzdanski commented on sidebarsAstro.js
> +        "reporting-dashboard",
1. I'm happy with moving it to `view metrics`!
2. I think that when this feature goes to GA we move the old Organization legacy metric to reference, unless we get feedback that we can go ahead and do that

2024-02-07 17:34 UTC, conorbev approved these changes
lgtm

2024-02-09 01:45 UTC, lzdanski commented on astro/reporting-dashboard.md
> +    - **Alert when...** to define criterial when Astro will send you a data export of the element or dashboard
@jwitz right now there's some work going on with the alerting/exporting functionality. How do you feel about me commenting this section out until that gets resolved so that we can get the page out and keep following with additional functionality?

2024-02-09 01:45 UTC, lzdanski commented on astro/reporting-dashboard.md
> +## DAG SLA
@jwitz this is another section that might get temporarily commented out until we get UI updates aligned with docs updates.

2024-02-09 11:38 UTC, jwitz commented on astro/reporting-dashboard.md
> +Astro provides a collection of dashboards that include important metrics about your Organization's use of Astro. These dashboards include:
Yes agreed on all fronts! Let's keep "dashboards" and also use "elements"

2024-02-09 11:39 UTC, jwitz commented on astro/reporting-dashboard.md
> +    - **Alert when...** to define criterial when Astro will send you a data export of the element or dashboard
Sounds good!

2024-02-09 11:41 UTC, jwitz commented on astro/reporting-dashboard.md
> +This tab allows you compare the activity and performances of Deployments to one another. You can identify Deployments, DAGs, or tasks that have had recent behavior changes or are performing in an une
```suggestion
This tab allows you to compare the activity and performances of Deployments to one another. You can identify Deployments, DAGs, or tasks that have had recent behavior changes or are performing in an unexpected way. For example, you can filter the data shown by time period, Workspace name, or Deployment name, to view data such as the number of successful or failed tasks within Workspaces or Deployments. Hovering your cursor over any of the charts brings up a detailed view of the data, indexed by date.
```

2024-02-09 16:30 UTC, jwitz approved these changes
LGTM! Great debut for a great feature

2024-02-09 16:30 UTC, jwitz commented on astro/reporting-dashboard.md
> +This dashboard shows the average and median ending time of a specific DAG run, aggregated by a chosen time period, month, week or day. You can use this view to visually inspect when particular DAGs c
```suggestion
This dashboard shows the average and median ending time of a specific DAG run, aggregated by a chosen time period, month, week or day. You can use this view to visually inspect when particular DAGs complete their first run, which allows you to see trends over time. Check this dashboard when you make changes to Deployment resources or DAG code to track their effects on performance over time.
```

2024-02-09 17:26 UTC, merged