Add incident details screenshot to deployment health doc
astronomer/docs pull request #3349
Opened 2024-01-31 00:00 UTC by TJaniF

From the meeting today @paolaperaza :)

2024-01-31 15:20 UTC, paolaperaza approved these changes
Thoughts on this? @lzdanski @jwitz Will let you guys look this over

2024-01-31 15:30 UTC, jwitz requested changes
Had some thoughts about the last few steps but otherwise LGTM!

2024-01-31 15:30 UTC, jwitz commented on astro/deployment-health-incidents.md
> +At least one task is configured to run on a worker queue that does not exist. Instances of this task will remain in the queued state until the worker queue is created. When this incident is triggered
```suggestion
At least one task is configured to run on a worker queue that does not exist. Instances of this task will remain in the queued state until the worker queue is created. To resolve this incident:
```

2024-01-31 15:30 UTC, jwitz commented on astro/deployment-health-incidents.md
> +1. Hover over the incident and click **View details**.
```suggestion
1. Hover over the Deployment health status and click **View details** for the incident.
```

2024-01-31 15:30 UTC, jwitz commented on astro/deployment-health-incidents.md
> +2. See the DAG and task IDs that reference a worker queue that does not exist. The name of the **QUEUE** reflects how the worker queue is referenced in your task definition.
```suggestion
2. Check the DAG and task IDs that reference the non-existent worker queue. The non-existent worker queue name referenced from your DAG code is listed under **Queue**.
```

2024-01-31 15:30 UTC, jwitz commented on astro/deployment-health-incidents.md
> +3. Copy the worker queue name under **QUEUE** and either create a new worker queue with that exact name or rename an existing worker queue in your Deployment to match it. As long as a worker queue wi
```suggestion
3. For each affected DAG, create a new worker queue with the exact name as shown in **Queue** or update your DAG code to reference an existing worker queue. See [Configure worker queues](configure-worker-queues.md#assign-tasks-to-a-worker-queue).
```
Is there a reason we're avoiding updating DAG code here? It's possible that someone could have made a typo in their DAG config, in which case it would make more sense to update the code than to create a misspelled worker queue.

2024-01-31 15:30 UTC, jwitz commented on astro/deployment-health-incidents.md
> +![Deployment health incident details](/img/docs/health-status-details.png)
I'm not a fan of large screenshots without something specific for the reader to focus on. It's especially distracting given that the message in the alert is not identical to what we have in this doc.

2024-02-01 14:30 UTC, paolaperaza commented on astro/deployment-health-incidents.md
> +![Deployment health incident details](/img/docs/health-status-details.png)
Yes good call Jake. Let's delete the screenshot for now and let me actually also modify the copy here to match the doc. You're right that you can either create the worker queue OR update your task code. 

Then once I've done that, we can:

- Highlight the `DAG ID > queue > task ID`
- make the screenshot a little smaller

2024-02-01 18:42 UTC, jwitz commented on astro/deployment-health-incidents.md
> +Astro automatically monitors your Deployments and sends messages when your Deployment isn't running optimally or as expected. These messages are known as _Deployment incidents_. To get view informati
```suggestion
Astro automatically monitors your Deployments and sends messages when your Deployment isn't running optimally or as expected. These messages are known as _Deployment incidents_. To view information about the incident, hover over the incident and click **View details**.
```

2024-02-02 00:17 UTC, TJaniF commented
> Sorry for the direct commit @TJaniF but this now LGTM!

Haha, no worries! 
I am actually a little unsure how to best resolve the merge conflict, i.e. which table version you prefer... I timed my PR perfectly to cause that, apologies. 

Made the screenshot smaller and added a highlight around the IDs in case you want to use it down the line :)

2024-02-02 10:22 UTC, jwitz commented
I'll let you do the honours @TJaniF ! ✅

2024-02-02 11:04 UTC, merged