Isolated environments guide
astronomer/docs pull request #3385
Opened 2024-02-12 13:27 UTC by TJaniF

2024-02-13 12:40 UTC, TJaniF commented
@kentdanas finally have the first draft ready :) 
I'll let you have a first look and if you agree with the general structure/content I would poke the long thread about this topic for SME review about our recommendations and Fritz about the IsolatedOperator :)

2024-02-13 22:16 UTC, kentdanas requested changes
@TJaniF this is great, so much helpful information here. Requesting a few structural changes, mostly in the first couple sections. Let me know if you want to discuss any of it.

2024-02-13 22:16 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +To use the `@task.virtualenv` decorator or the PythonVirtualenvOperator to create a virtual environment with the same Python version as your Airflow environment but potentially conflicting packages,
```suggestion
The Virtualenv operator (`@task.virtualenv` or PythonVirtualenvOperator) creates a new virtual environment each time the task runs.
```

2024-02-13 22:16 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +
If you are only specifying different package versions, you do not need to create or specify a Python binary.

2024-02-13 22:16 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +If you want to build a virtual environment at runtime with a different Python version than your Airflow environment, you can use the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-pr
```suggestion
If your task requires a different Python version than your Airflow environment, need to install that Python version in your Airflow environment so the Virtualenv task can use it. You can use the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv) to install a different Python version in your Dockerfile.
```

2024-02-13 22:16 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +Due to compatibility issues, other objects from the context such as `ti` cannot be passed to isolated environments, see the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/late
```suggestion
Due to compatibility issues, other objects from the context such as `ti` cannot be passed to isolated environments. For more, see the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/latest/howto/operator/python.html#id1).
```

2024-02-13 22:16 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +If you need to use Airflow and Airflow providers module inside your virtual environment, use the `@task.virtualenv` decorator or the PythonVirtualenvOperator instead of the `@task.external_python` de
```suggestion
If you need to use Airflow or an Airflow providers module inside your virtual environment, use the `@task.virtualenv` decorator or the PythonVirtualenvOperator instead of the `@task.external_python` decorator or the ExternalPythonOperator.
```

2024-02-14 19:16 UTC, TJaniF commented
Thank you @kentdanas, it looks much better now, I think! :)

2024-02-14 20:40 UTC, kentdanas approved these changes
@TJaniF this looks great! I think much easier to get the gist of things up front now. Left a few other minor comments, but preemptively approving for content. Let's get some copy editing and SME eyes on it.

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +![Graph of options for isolated environments in Airflow.](/img/guides/airflow-isolated-environments_isolated_env_options_graph.png)
Put the graph after the bulleted list?

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +The virtual environment decorators have operator equivalents with the same functionality. Astronomer recommends to use the decorators over the operators, as they simplify handling of [XCom](airflow-p
```suggestion
The virtual environment decorators have operator equivalents with the same functionality. Astronomer recommends using decorators where possible because they simplify handling of [XCom](airflow-passing-data-between-tasks.md).
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +Using a pre-existing virtual environment is faster and recommended if you need to reuse your virtual environment across multiple tasks. Creating a new virtual environment at runtime is slower but can
```suggestion
Using a pre-existing virtual environment is faster and recommended if your virtual environment can be used by multiple tasks. Creating a new virtual environment at runtime is slower but can be useful if you need to install different packages for each run of your task. The new environment can be cached by providing a `venv_cache_path`.
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +The IsolatedOperator, `@task.kubernetes` decorator or KubernetesPodOperator all you to have full control over the environment and resources used but they require you need to have access to a Kubernet
```suggestion
Another consideration when choosing an operator is the infrastructure you have available. Operators that run tasks in Kubernetes pods allow you to have full control over the environment and resources used, but they require a Kubernetes cluster. Operators that run tasks in Python virtual environments are easier to set up, but do not provide the same level of control over the environment and resources used.
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +Astronomer recommends to use the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv) to create a Python binary. See, [`@task.external_python`](#external-python-operator).
```suggestion
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +*Only if you need to use a different Python version than your Airflow environment.
```suggestion
*Only required if you need to use a different Python version than your Airflow environment.
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +Which option you choose depends on your use case and the requirements of your task. The table below provides an overview of the different options and their use cases.
```suggestion
Which option you choose depends on your use case and the requirements of your task. The table below shows which operators are best for which use cases.
```

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +Using a pre-existing virtual environment is faster and recommended if you need to reuse your virtual environment across multiple tasks. Creating a new virtual environment at runtime is slower but can
Actually, could we just add a line to the table "reuse the same virtual env for multiple tasks" and then remove this paragraph? And "Install different packages for each run of your task", etc. Some of the other details could be saved for the individual sections.

2024-02-14 20:40 UTC, kentdanas commented on learn/airflow-isolated-environments.md
> +
lol clearly missed the "text suggestion" on this one - sounds like just a very assertive comment 😁

2024-02-15 12:10 UTC, TJaniF commented
Thank you @kentdanas ! 

@jwitz @lzdanski Ready for you :) I will also post this for SME review in the Slack discussion about the EPO guide to make sure our recommendations on what to do when you want Airflow inside of the venv are sound and send it to Fritz for review of how we talk about the IsolatedOperator.

2024-02-16 19:59 UTC, lzdanski reviewed
Lots of small grammar things!

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +The Kubernetes operator (`@task.kubernetes` decorator or KubernetesPodOperator) runs an Airflow task in a dedicated Kubernetes pod. The `@task.kubernetes` decorator is used to run any custom Python c
```suggestion
The Kubernetes operator, `@task.kubernetes` decorator or KubernetesPodOperator, runs an Airflow task in a dedicated Kubernetes pod. You can use the `@task.kubernetes` to run any custom Python code in a separate Kubernetes pod on a Docker image with Python installed, while the KubernetesPodOperator runs any existing Docker image.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To use the `@task.kubernetes` decorator or the KubernetesPodOperator, you need provide a Docker image as well as have access to a Kubernetes cluster. The example below shows how to use the modules to
```suggestion
To use the `@task.kubernetes` decorator or the KubernetesPodOperator, you need to provide a Docker image and have access to a Kubernetes cluster. The following example shows how to use the modules to run in a task in a separate Kubernetes pod in the same namespace and Kubernetes cluster as your Airflow environment. For more information on how to use the KubernetesPodOperator, see [Use the KubernetesPodOperator](kubepod-operator.md) and [Run the KubernetesPodOperator on Astro](https://docs.astronomer.io/astro/kubernetespodoperator).
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To get a list of all parameters of the `@task.virtualenv` decorator / PythonVirtualenvOperator, see the [Astronomer Registry](https://registry.astronomer.io/providers/apache-airflow/versions/latest/m
```suggestion
To get a list of all parameters of the `@task.virtualenv` decorator or PythonVirtualenvOperator, see the [Astronomer Registry](https://registry.astronomer.io/providers/apache-airflow/versions/latest/modules/pythonvirtualenvoperator).
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To use the BuildKit the [Docker BuildKit Backend](https://docs.docker.com/build/buildkit/) needs to be enabled. This is the default as of Docker Desktop version 23.0 but might need to be enabled manu
```suggestion
To use the BuildKit, the [Docker BuildKit Backend](https://docs.docker.com/build/buildkit/) needs to be enabled. This is the default starting in Docker Desktop version 23.0, but might need to be enabled manually in older versions of Docker.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +If your task requires a different Python version than your Airflow environment, you need to install that Python version in your Airflow environment so the Virtualenv task can use it. You can use the
```suggestion
If your task requires a different Python version than your Airflow environment, you need to install the Python version your task requires in your Airflow environment so the Virtualenv task can use it. Use the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv) to install a different Python version in your Dockerfile.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Since the `requirements` parameter of the PythonVirtualenvOperator is [templatable](templating.md), you can use [Jinja templating](templating.md) to pass information at runtime, for example to instal
```suggestion
Since the `requirements` parameter of the PythonVirtualenvOperator is [templatable](templating.md), you can use [Jinja templating](templating.md) to pass information at runtime. For example, you can use a Jinja template to install a different version of pandas for each run of the task.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +You can pass information into the PythonVirtualenvOperator by using a [Jinja template](templating.md) retrieving [XCom](airflow-passing-data-between-tasks.md) values from the [Airflow context](airflo
```suggestion
You can pass information into the PythonVirtualenvOperator by using a [Jinja template](templating.md) to retrieve [XCom](airflow-passing-data-between-tasks.md) values from the [Airflow context](airflow-context.md). To pass information out of the PythonVirtualenvOperator, return it from the `python_callable`.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +You can pass information into and out of the `@task.virtualenv` decorated task the same way as you would when interacting with a `@task` decorated task, see also [Introduction to the TaskFlow API and
```suggestion
You can pass information into and out of the `@task.virtualenv` decorated task using the same process as you would when interacting with a `@task` decorated task. See [Introduction to the TaskFlow API and Airflow decorators](airflow-decorators.md) for more detailed information.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +The Virtualenv operator (`@task.virtualenv` or PythonVirtualenvOperator) creates a new virtual environment each time the task runs. If you are only specifying different package versions, you do not n
```suggestion
The Virtualenv operator (`@task.virtualenv` or PythonVirtualenvOperator) creates a new virtual environment each time the task runs. If you only specify different package versions, you do not need to create or specify a Python binary.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +After restarting your Airflow environment you can use this Python binary by referencing the environment variable `ASTRO_PYENV_<my-pyenv-name>`. If you are using an alternative method to create you Py
```suggestion
After restarting your Airflow environment, you can use this Python binary by referencing the environment variable `ASTRO_PYENV_<my-pyenv-name>`. If you choose an alternative method to create you Python binary, you need to set the `python` parameter of the decorator or operator to the location of your Python binary.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +You can add any Python packages to the virtual environment by putting it into a separate requirements file, in our example using the name `epo_requirements.txt`. Make sure to pin all package versions
```suggestion
You can add any Python packages to the virtual environment by putting them into a separate requirements file. In this example, by using the name `epo_requirements.txt`. Make sure to pin all package versions.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To use the BuildKit the [Docker BuildKit Backend](https://docs.docker.com/build/buildkit/) needs to be enabled. This is the default as of Docker Desktop version 23.0 but might need to be enabled manu
```suggestion
To use the BuildKit, the [Docker BuildKit Backend](https://docs.docker.com/build/buildkit/) needs to be enabled. This is the default as of Docker Desktop version 23.0, but might need to be enabled manually in older versions of Docker.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +The easiest way to create a Python environment when using the Astro CLI is with the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv). The BuildKit can be used by adding
```suggestion
The easiest way to create a Python environment when using the Astro CLI is with the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv). The BuildKit can be used by adding a comment on the first line of the Dockerfile as shown in the following example. Adding this comment enables you to create virtual environments with the `PYENV` keyword.
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To use the `@task.external_python` decorator or the ExternalPythonOperator you need to create a separate Python environment to reference. You can use any Python binary created by any means.
```suggestion
To use the `@task.external_python` decorator or the ExternalPythonOperator, you need to create a separate Python environment to reference. You can use any Python binary created by any means. 
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +The virtual environment decorators have operator equivalents with the same functionality. Astronomer recommends using decorators where possible because they simplify handling of [XCom](airflow-passin
```suggestion
The virtual environment decorators have operator equivalents with the same functionality. Astronomer recommends using decorators where possible because they simplify the handling of [XCom](airflow-passing-data-between-tasks.md).
```

2024-02-16 19:59 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Which option you choose depends on your use case and the requirements of your task. The table below shows which operators are best for which use cases.
```suggestion
Which option you choose depends on your use case and the requirements of your task. The table below shows which operators are best for particular use cases.
```

2024-02-19 11:22 UTC, TJaniF reviewed
Thank you @lzdanski ! 

Accepted all but one suggestions, there I think my original sentence was misleading and I tried to clarify :)

2024-02-21 19:46 UTC, lzdanski reviewed
Some small grammar things and suggestions for reformatting the tables. I see what you're going for there, but there's a few best practice things for working in markdown that mean they need a few tweaks. Happy to explain more or to jump in!

lastly - we need a redirect for this new page from the old URL. Let me know if you need help with that!

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +id: airflow-isolated-environments
Because this is a new page with a new ID, i'm getting a 404 error when I go to the old `external-python-operator` page URL in the preview. You'll need to add a redirect to the redirect file, and this would probably [be a good line to add it below](https://github.com/astronomer/docs/blob/d711fbdc64f8307960227658984cfdf9237dd0c9/static/_redirects#L15). 

It should look something like:
```
/learn/external-python-operator /learn/airflow-isolated-environments 301
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +- Installing Airflow itself, or Airflow provider packages in the environment provided to the `@task.external_python` decorator or the ExternalPythonOperator, can lead to unexpected behavior. If you n
```suggestion
- You [cannot pass all Airflow context variables](https://airflow.apache.org/docs/apache-airflow/latest/howto/operator/python.html#id1) to a virtual decorator, since Airflow does not support serializing `var`, `ti`, and `task_instance` objects. See [Use Airflow context variables in isolated environments](#use-airflow-context-variables-in-isolated-environments).
- You do not have access to your [secrets backend](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/secrets-backend/index.html) from within the isolated environment. To access your secrets, consider passing them in through [Jinja templating](templating.md). See [Use Airflow variables in isolated environments](#use-airflow-variables-in-isolated-environments).
- Installing Airflow itself, or Airflow provider packages in the environment provided to the `@task.external_python` decorator or the ExternalPythonOperator, can lead to unexpected behavior. If you need to use Airflow or an Airflow providers module inside your virtual environment, Astronomer recommends using the `@task.virtualenv` decorator or the PythonVirtualenvOperator instead. See [Use Airflow packages in isolated environments](#use-airflow-packages-in-isolated-environments).
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +| Install different packages for each run of a task | | | | :white_check_mark: (traditional operator) | | :white_check_mark: (traditional operator) |
I've got a couple of concerns about some of the new things going on in this table - with the header links and the white check marks. This [screen reader example](https://youtu.be/ACmYzyN0b3U?feature=shared) describes an HTML encoded table, but markdown exports everything that's described in the "accessible table" example except the caption. But the main takeaway is that a screen reader reads aloud, verbatim, the content encoded in the individual table headers and the table cells, so we try and make sure that the table cell only has the data that information that is actually required. 

If we had a symbol for a check mark that was an icon that could be read by a screen reader as "supported" or "yes" I would definitely be all for this format, but tables cause a lot of problems for anyone using keyboard navigation in general or with a screenreader.

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +
```suggestion
*Only required if you need to use a different Python version than your Airflow environment.
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +The easiest way to create a Python environment when using the Astro CLI is with the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv). The BuildKit can be used by adding
```suggestion
The ExternalPython operator, `@task.external_python` decorator or ExternalPythonOperator, runs a Python function in an existing virtual Python environment, isolated from your Airflow environment. To use the `@task.external_python` decorator or the ExternalPythonOperator, you need to create a separate Python environment to reference. You can use any Python binary created by any means. 

The easiest way to create a Python environment when using the Astro CLI is with the [Astronomer PYENV BuildKit](https://github.com/astronomer/astro-provider-venv). The BuildKit can be used by adding a comment on the first line of the Dockerfile as shown in the following example. Adding this comment enables you to create virtual environments with the `PYENV` keyword.
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Installing Airflow itself and Airflow provider packages in isolated environments can lead to unexpected behavior and is not recommended. If you need to use Airflow and Airflow providers module inside
```suggestion
Installing Airflow itself and Airflow provider packages in isolated environments can lead to unexpected behavior and is not recommended. If you need to use Airflow and Airflow providers module inside your virtual environment, Astronomer recommends to choose the `@task.virtualenv` decorator or the PythonVirtualenvOperator. See [Use Airflow packages in isolated environments](#use-airflow-packages-in-isolated-environments).
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +To run any Python function in your virtual environment, provide it to the `python_callable` parameter of the ExternalPythonOperator and set the `python` parameter to the location of your Python binar
```suggestion
To run any Python function in your virtual environment,  define the `python_callable` parameter of the ExternalPythonOperator with your Python function, and set the `python` parameter to the location of your Python binary.
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Installing Airflow itself and Airflow provider packages in isolated environments can lead to unexpected behavior and is generally not recommended. See, [Use Airflow packages in isolated environments]
```suggestion
Installing Airflow itself and Airflow provider packages in isolated environments can lead to unexpected behavior and is generally not recommended. See [Use Airflow packages in isolated environments](#use-airflow-packages-in-isolated-environments).
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Add the pinned versions of the packages you need to the `requirements` parameter of the `@task.virtualenv` decorator. The decorator creates a new virtual environment at runtime.
```suggestion
Add the pinned versions of the packages to the `requirements` parameter of the `@task.virtualenv` decorator. The decorator creates a new virtual environment at runtime.
```

2024-02-21 19:46 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +Due to compatibility issues, other objects from the context such as `ti` cannot be passed to isolated environments. For more information, see the [Airflow documentation](https://airflow.apache.org/do
```suggestion
Some variables from the [Airflow context](airflow-context.md) can be passed to isolated environments, for example the `logical_date` of the DAG run. Due to compatibility issues, other objects from the context such as `ti` cannot be passed to isolated environments. For more information, see the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/latest/howto/operator/python.html#id1).
```

2024-02-22 12:15 UTC, TJaniF reviewed
Thank you @lzdanski ! 
I updated the use case tables to hopefully make more sense with a screen reader. In the first table I am a little on the fence whether to had each option on a newline like now or allow some to be on the same line (it does not fit for all of them, so really just a "what looks better" question 😅 )

2024-02-26 21:11 UTC, lzdanski approved these changes
Very small grammar feedback! This looks great!

2024-02-26 21:11 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +| Use Case | Implementation Options |
This looks great!

2024-02-27 10:26 UTC, TJaniF commented on learn/airflow-isolated-environments.md
> +| Use Case | Implementation Options |
Thank you! 😊

2024-02-27 11:30 UTC, merged