1.23 CLI Release Docs
astronomer/docs pull request #3388
Opened 2024-02-12 19:40 UTC by lzdanski

Resolves #3307

2024-02-13 14:23 UTC, jwitz requested changes
Some questions about the release notes content, but otherwise LGTM! Thanks for tackling this

2024-02-13 14:23 UTC, jwitz commented on astro/cli/astro-deployment-create.md
> +| `--default-task-pod-memory`         | (Astro Hosted only) The default task pod memory to use for the Deployment. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kub
```suggestion
| `--default-task-pod-cpu`         | (Astro Hosted only) The default task Pod CPUs to use for the Deployment. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kubernetes-pod) for more information. |    A numeric value such as `0.25`. This number cannot exceed the values you configured in your [Default pod resources](deployment-resources.md#configure-kubernetes-pod-resources) in the UI or in your Deployment configuration file.                                                    |
| `--default-task-pod-memory`         | (Astro Hosted only) The default task pod memory to use for the Deployment in Gi. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kubernetes-pod) for more information. |   A numeric value followed by `Gi`, such as `0.5Gi`. This number cannot exceed the values you configured in your [Default pod resources](deployment-resources.md#configure-kubernetes-pod-resources) in the UI or in your Deployment configuration file.                               |
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/astro-deployment-create.md
> +| `--default-task-pod-memory`         | (Astro Hosted only) The default task pod memory to use for the Deployment. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kub
Kinda odd that they need to specify Gi for the memory, but don't need to specify a unit for CPU. Is there another unit they can use?

2024-02-13 14:23 UTC, jwitz commented on astro/cli/astro-deployment-update.md
> +| `--default-task-pod-cpu`       | (Astro Hosted only) The default task pod CPU to use for the Deployment. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kubernetes-
Same edits here as for the other command reference

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +These flags have been updated, but will continue to work with a deprecation notice.
```suggestion
The following flags have been updated, but will continue to work with a deprecation notice until the next major release of the Astro CLI:
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +- `astro deployment create --enforce-cicd` is now `astro deployment create --cicd-enforcement`.
```suggestion
- `astro deployment logs --key-word` is a new flag that allows you to search your audit logs for an exact key word or phrase.
- `astro deployment create --cluster-type` is now `astro deployment create --type`.
- `astro deployment create --enforce-cicd` is now `astro deployment create --cicd-enforcement`.
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +- `astro deployment create --enforce-cicd` is now `astro deployment create --cicd-enforcement`.
The first one is sort of the odd one out here, should we put this under "additional improvements instead?

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +### Other changes
```suggestion
### Additional improvements
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +If you use a [Deployment file](deployment-file-reference.md) to manage your Deployments as code, there are some new and changed fields.
```suggestion
[Deployment files](deployment-file-reference.md) now include some new and updated fields for Deployment configuration to match the options available in the Cloud UI.
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +You can now use the new `default_task_pod_cpu`, `default_task_pod_memory`, and `default_worker_type` fields in a Deployment file to update your Kubernetes workers instead of creating or updating a Ku
```suggestion
You now use the `default_task_pod_cpu`, `default_task_pod_memory`, and `default_worker_type` fields in a Deployment file to update your Kubernetes workers instead of creating or updating a Kubernetes default worker queue.
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +With this new functionality, you can't use the following commands to change your Kubernetes worker configuration if you've configured your Deployment file:
```suggestion
With this new functionality, you can no longer use the following commands to update a Deployment running the Kubernetes executor:
```
Does this need a breaking change warning?

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +- `astro deployment update --from-file`
Why would these no longer work if we just added fields to support KE configs?

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +### New fields to update Kubernetes worker types, CPU, and memory
```suggestion
### Kubernetes worker configurations are now consistent with the Astro Cloud UI
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +- `default_task_pod_cpu`, `default_task_pod_memory`, `resource_quota_cpu`, and `resource_quota_memory` are new fields for Hosted deployments.
```suggestion
- (_Astro Hosted only_) `default_task_pod_cpu`, `default_task_pod_memory`, `resource_quota_cpu`, and `resource_quota_memory` are new fields for Astro Hosted deployments.
```
We could even get rid of the parentheses and just rely on the statement itself

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +<HostedBadge/>
Idk if I love inline usage of the badges, it looks a little out of place amongst the bullet points

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +### Changes to Deployment file configurations
Should we move the Deployment file information from the previous note into here?

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +- Inputs for the `executor` field are now `CELERY` and `KUBERNETES` are the new inputs for the executor field. `CeleryExecutor` and `KubernetesExecutor` still work, but cause deprecation notices. Thi
```suggestion
- `cluster_name` is no longer used for standard Deployment files.
- `scheduler_size` is no longer case sensitive.
- Possible values for `cloud_provider` are now `gcp`, `aws`, and `azure`. This input is not case sensitive.
- Possible values for `deployment_type` are now `standard`, `dedicated`, and `hybrid`. This input is not case sensitive
- Possible values for for the `executor` field are now `celery` and `kubernetes`. `CeleryExecutor` and `KubernetesExecutor` still work, but they cause deprecation notices. This input is not case sensitive, so, for example, `celeryexecutor` still works.
```

2024-02-13 14:23 UTC, jwitz commented on astro/cli/release-notes.md
> +### Changes to Deployment file configurations
```suggestion
### Changes to Deployment file configurations

The following changes have been made to the format of [Deployment files](deployment-file-reference.md):
```

2024-02-13 14:23 UTC, jwitz commented on astro/deployment-details.md
> +- Code auto-deploys to the specified Deployment if you do a manual code deploy with the CLI.
```suggestion
```
I'm changing this text in a separate PR, but separately is this line right? I thought code is automatically rejected if you do a manual deploy.

2024-02-13 14:23 UTC, jwitz commented on astro/deployment-file-reference.md
> +The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for Deployments that use Celery executor. This section is not applicable to Deployments that use Kubernetes executo
```suggestion
The `worker_queues` section defines the [worker queues](configure-worker-queues.md) for Deployments that use the Celery executor. This section is not applicable to Deployments that use Kubernetes executor.
```

2024-02-13 14:37 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `--default-task-pod-memory`         | (Astro Hosted only) The default task pod memory to use for the Deployment. See [Customize a task's Kubernetes Pod](kubernetes-executor.md#customize-a-tasks-kub
This came up in the help text. CPU doesn't require a unit at all apparently, but maybe @sunkickr can let us know if we need the units at all for memory or if it's just a numeric input?

2024-02-13 14:37 UTC, lzdanski commented on astro/cli/release-notes.md
> +With this new functionality, you can't use the following commands to change your Kubernetes worker configuration if you've configured your Deployment file:
@sunkickr - remind me again, is this now "will work but with a deprecation warning" or "won't work at all?"

2024-02-13 14:37 UTC, lzdanski commented on astro/deployment-details.md
> +- Code auto-deploys to the specified Deployment if you do a manual code deploy with the CLI.
yep i got it backwards!

2024-02-13 21:46 UTC, sunkickr requested changes

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/astro-deployment-logs.md
> +| `-c`,`--log-count`  | The number of log lines to show. The default is `500`                                    | Any integer less than or equal to 500
I am not sure what the max number of logs are that you can search for but I believe it is higher than 500. 500 is just the default. As far as I know the max would be total number of logs accumulated so far. If you asked for more logs than existed than just the ones that existed would be returned

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/release-notes.md
> +The following flags have been updated, but will continue to work with a deprecation notice until the next major release of the Astro CLI:
They will continue to work with a deprecation notice until this release is deprecated. They will stop working when  v1.25.0 is released

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/release-notes.md
> +- `astro deployment update --from-file`
`astro deployment create --from-file` and `astro deployment update --from-file` are affected by the change but will still work. Before you had to make you changes to the worker-queue field and now you have use the new fields of `default_worker_type`(For hybrid), `default_task_pod_cpu` and `default_task_pod_memory`(for hosted)

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/release-notes.md
> +Instead, you can use the new `--default-task-pod-cpu`, `--default-task-pod-memory`, `--resource-quota-cpu`, or `--resource-quota-memory` flags with [`astro deployment create`](astro-deployment-create
you can also use new fields in the deployment file

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/release-notes.md
> +- Possible values for `deployment_type` are now `standard`, `dedicated`, and `hybrid`. This input is not case sensitive
should we also indicate the old values of hosted_shared, hosted_dedicated, and hosted_standard still work?

2024-02-13 21:46 UTC, sunkickr commented on astro/cli/release-notes.md
> +- Possible values for for the `executor` field are now `celery` and `kubernetes`. `CeleryExecutor` and `KubernetesExecutor` still work, but they cause deprecation notices. This input is not case sens
There is not deprecation notice for `CeleryExecutor` and `KubernetesExecutor` inputs. Those will continue to work indefinitely for now

2024-02-13 21:46 UTC, sunkickr commented on astro/deployment-file-reference.md
> +    worker_queues: ## worker_queues is only when executor is CELERY now
```suggestion
    worker_queues: ## worker_queues is only used when executor is CELERY
```

2024-02-13 21:46 UTC, sunkickr commented on astro/deployment-file-reference.md
> +        workspace_name:
we should give an example for cluster_name and workspace_name

2024-02-13 21:46 UTC, sunkickr commented on astro/deployment-file-reference.md
> +		alert_emails:
maybe add example alert_emails

2024-02-13 21:46 UTC, sunkickr commented on astro/deployment-file-reference.md
> +        - name: default
We should add the field `default_worker_type` and note that it is only used when the executor is kubernetes

2024-02-13 22:30 UTC, lzdanski commented on astro/cli/astro-deployment-logs.md
> +| `-c`,`--log-count`  | The number of log lines to show. The default is `500`                                    | Any integer less than or equal to 500
```suggestion
| `-c`,`--log-count`  | The number of log lines to show. The default is `500`                                    | Any integer. If you request a number of log lines to show that exceeds the total number of logs, then it shows all existing logs.                                                     |
```

2024-02-13 22:30 UTC, lzdanski commented on astro/cli/release-notes.md
> +The following flags have been updated, but will continue to work with a deprecation notice until the next major release of the Astro CLI:
```suggestion
The following flags have been updated, but will continue to work with a deprecation notice until the v1.25.0 release of the Astro CLI:
```

2024-02-13 22:30 UTC, lzdanski commented on astro/cli/release-notes.md
> +- Possible values for for the `executor` field are now `celery` and `kubernetes`. `CeleryExecutor` and `KubernetesExecutor` still work, but they cause deprecation notices. This input is not case sens
```suggestion
- Possible values for for the `executor` field are now include `celery` and `kubernetes`. `CeleryExecutor` and `KubernetesExecutor` still work. This input is not case sensitive, so, for example, `celeryexecutor` still works.
```

2024-02-13 22:30 UTC, lzdanski commented on astro/cli/release-notes.md
> +- Possible values for `deployment_type` are now `standard`, `dedicated`, and `hybrid`. This input is not case sensitive
```suggestion
- Possible values for `deployment_type` now include `standard`, `dedicated`, and `hybrid` in addition to the existing values of `hosted_shared`, `hosted_dedicated`, and `hosted_standard`. This input is not case sensitive
```

2024-02-13 22:30 UTC, lzdanski commented on astro/deployment-file-reference.md
> +        workspace_name:
Do we have any dedicated examples or should I use something from a random generator? I left fields blank where I wasn't sure if we needed to redact/if they were real from the example you shared. (random ID generator: https://www.getuniqueid.com/cuid)

2024-02-13 22:30 UTC, lzdanski commented on astro/deployment-file-reference.md
> +        - name: default
Does that mean it appears in both `configuration` and `worker_types`? We currently have it listed on line 116

2024-02-14 12:33 UTC, jwitz requested changes
Sorry I totally missed reviewing the Deployment resources changes, have a big thought there but everything else LGTM

2024-02-14 12:33 UTC, jwitz commented on astro/cli/release-notes.md
> +With this new functionality, the following commands to update a Deployment running the Kubernetes executor continue to work, but display a deprecation notice:
```suggestion
With this new functionality, the following commands continue to work for Deployments running the Kubernetes executor, but they display a deprecation notice:
```

2024-02-14 12:33 UTC, jwitz commented on astro/cli/release-notes.md
> +- `astro deployment update --from-file`
@lzdanski I think it's slightly misleading to include these commands, as the commands themselves haven't changed but rather the fields you pass to them. I'd use this release note to focus specifically on the worker queue commands and leave the Deployment file information to the latter note

2024-02-14 12:33 UTC, jwitz commented on astro/deployment-resources.md
> +        {label: 'Deployment file', value: 'deployment-file'},
This is a really complex structure that, assuming we want it here, would apply to all other resource sections. I assumed that we never documented Deployment file setups or Astro CLI setups here because those were considered automation workflows, and thus discussed in detail within core configuration docs. 

My suggestion here is:
- Add notes to the beginning of the doc to explain that these settings can also be updated using a Deployment file or the Astro CLI.  Then link to https://docs.astronomer.io/astro/manage-deployments-as-code
- Avoid topic-level tabs to simplify this doc

2024-02-14 17:32 UTC, jwitz approved these changes
LGTM!

2024-02-14 17:32 UTC, jwitz commented on astro/deployment-resources.md
> +::: info
```suggestion
:::info
```

2024-02-14 17:32 UTC, jwitz commented on astro/deployment-resources.md
> +You can also configure default pod limits and resources with the [`astro deployment create`](cli/astro-deployment-create.md) and [`astro deployment update`](cli/astro-deployment-update.md) Astro CLI
```suggestion
To manage Kubernetes resources programmatically, you can set default Pod limits and resources with the [`astro deployment create`](cli/astro-deployment-create.md) and [`astro deployment update`](cli/astro-deployment-update.md) Astro CLI commands, or by adding the configurations to a [Deployment file](deployment-file-reference.md).
```

2024-02-14 19:40 UTC, sunkickr commented on astro/cli/release-notes.md
> +- The CLI no longer auto-selects the Deployments where your code deploys when you use it for Deployments that don't have CI/CD enforcement. Or, it also does not auto-select a Deployment if you have t
The auto-select doesn't change based on CI/CD enforcement.
Auto-select works this way now:
- by default auto-select is disabled. You will need to select a deployment if you are logged into the CLI as a user.
- If you used a token/key to login by setting one of the environment variables `ASTRO_API_TOKEN`, `ASTRONOMER_KEY_ID`, or `ASTRONOMER_KEY_SECRET` auto-select is enabled. This is important because it ensures that users with CI/CD scripts that rely on auto-select will continue to work
- There is a new config `auto_select`. If it is set to true in the config file like `auto_select: true` auto-select will always be enabled

2024-02-14 19:42 UTC, sunkickr commented on astro/deployment-file-reference.md
> +        - name: default
`worker_type` is under `worker_queue` which is only for Celery deployments:

- `worker_queue.worker_type` is for Celery
- `default_worker_type` is for Kubernetes

2024-02-14 19:51 UTC, sunkickr commented on astro/cli/release-notes.md
> +- The CLI no longer auto-selects the Deployments where your code deploys when you use it for Deployments that don't have CI/CD enforcement. Or, it also does not auto-select a Deployment if you have t
Also we should probably be more clear on what auto-select is. Auto-select is where the CLI automatically selects a deployment if there is only one available to the user in the workspace that is currently selected as the CLIs context. auto-select will be turned off by default because it has caused users to deploy to the wrong deployment in the past(they didn't know what workspace they were in, used wrong deployment token, etc...)

2024-02-14 20:27 UTC, sunkickr approved these changes

2024-02-14 21:26 UTC, merged