Sudarshan dbcleanup job documentation
astronomer/docs pull request #3397
Opened 2024-02-13 16:19 UTC by sudarshan-uc

Correcting the information for dbcleanup plugin and adding more information that would help clarify what the plugin does.

2024-02-15 12:21 UTC, jwitz commented on software/configure-deployment.md
> +You can run a cron job to automatically archive task and DAG metadata from your Deployment. This job runs [`airflow db clean`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variab
```suggestion
You can run a cron job to automatically archive task and DAG metadata from your Deployment. This job runs [`airflow db clean`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#clean) programmatically for all of your Deployments and exports the results each Deployment as files to your external storage service. To run this job for a Deployment, you must install the Astronomer-maintained `airflow-dbcleanup-plugin` on the Deployment. This plugin executes the cleanup job from your Deployment's `webserver` Pod. 
```
Is it a results file for each Deployment, or is it a single file for all Deployment results? Assuming it's the former.

2024-02-15 12:34 UTC, jwitz requested changes
A few functionality questions, but otherwise looks good!

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +> Note: the plugin `airflow-dbcleanup-plugin` v1.0.1 already exists in Runtime version 8.0.0 and above. Step 1. can be skipped.
```suggestion
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
>  1. For each of your Deployments, add the following line to the `requirements.txt` file of your Deployment's Astro project. Replace `<latest-version>` with the latest available version in the [`airflo
```suggestion
1. For Deployments running Runtime 7 or earlier, add the following line to the `requirements.txt` file of your Deployment's Astro project. Replace `<latest-version>` with the latest available version in the [`airflow-dbcleanup-plugin` GitHub repository](https://github.com/astronomer/airflow-dbcleanup-plugin/releases).
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
```suggestion

    You can skip this step for Deployments running Astro Runtime 8 or later.
    
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +2. Configure the credentials for the external storage service so that webserver pod can export the log file of cleanup plugin in JSON or URI Format. You can use the credential for the external storag
```suggestion
2. Authorize your Deployments to your external storage service so that the webserver Pod can export the results of your cleanup jobs in JSON or URI Format. You can authorize your Deployment using one of the following methods:
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +- `Kubernetes Secrets` ( See [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret) to configure via kibernetes secrets.). The secret can be created i
```suggestion

    - Configure an [Airflow connection] in the Deployment that connects to your external storage service.
    - To configure a global connection for all Deployments, create a [Kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret) containing an Airflow connection to your external storage service. The connection must be defined in either JSON or URI format. To pass the secret to all the Deployments, annotate the secret using the following command: 
    
    ```sh
    kubectl annotate secret <secret-name> "astronomer.io/commander-sync"="platform=astronomer"
    ```
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +- `Kubernetes Secrets` ( See [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret) to configure via kibernetes secrets.). The secret can be created i
- Do they still need to annotate the secret if they use ` providerEnvSecretName: "<your-secret-name>"` in their Helm config? 

- If you choose the first option, are there any special values that are required for the Airflow connection? How does the Deployment know what connection ID to use for exporting the file?

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +Warning: This cleanup removes information that is created before days specified in `olderThan` variable and will clean up even if the information is actively required by running dags and tasks.
```suggestion
The cleanup job deletes any data that's older than the number of days specified in your `olderThan` configuration. Ensure that none of your historical data is required to run current DAGs or tasks before enabling this feature. 
```

2024-02-15 12:34 UTC, jwitz commented on software/configure-deployment.md
> +:::
```suggestion
:::tip

Set `dryRun: true` to test this feature without deleting any data. When dry runs are enabled, the cleanup job will only print the data that it plans to modify in the serial output of the webserver Pod. To view the dryRun events of the cleanup job, check the logs of your webserver Pod for each Deployment.

:::
```

2024-02-15 13:33 UTC, sudarshan-uc commented on software/configure-deployment.md
> +You can run a cron job to automatically archive task and DAG metadata from your Deployment. This job runs [`airflow db clean`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variab
Each deployment will have its own file in external storage with the deployment name as file name.

2024-05-14 14:09 UTC, jwitz approved these changes

2024-05-14 14:11 UTC, merged