Astro CLI 1.24 release notes and reference documentation
astronomer/docs pull request #3423
Opened 2024-02-19 12:23 UTC by jwitz

2024-02-19 12:24 UTC, jwitz commented on astro/cli/release-notes.md
> +You can additionally now create new development Deployments and configure long-term hibernation schedules for them using `astro deployment create`.
```suggestion
Additionally, you can create new development Deployments and configure long-term hibernation schedules for them using `astro deployment create`.
```

2024-02-19 12:24 UTC, jwitz commented on astro/deployment-file-reference.md
> +        is_development_mode: true
Definitely need tech review on placing/ format of this file

2024-02-19 12:24 UTC, jwitz commented on astro/cli/release-notes.md
> +## Astro CLI 1.24.0
Any other small changes or bug fixes we should include?

2024-02-19 12:35 UTC, feluelle commented on astro/cli/astro-deployment-hibernate.md
> +astro deployment hibernate [one of --until/ --for/ --resumeschedule]
```suggestion
astro deployment hibernate [one of --until/ --for/ --resume-schedule]
```

2024-02-19 12:35 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +astro deployment hibernate [one of --until/ --for/ --resumeschedule]
```suggestion
astro deployment hibernate [one of --until/ --for/ --resume-schedule]
```

2024-02-19 12:35 UTC, feluelle commented on astro/deployment-file-reference.md
> +            is_enabled: true
```suggestion
        hibernation_schedules:
          - hibernate_at: "1 * * * * "
            wake_at: "2 * * * *"
            description: "My hibernation description"
            enabled: true
```

I believe these need to be slightly different:

[Reference](https://github.com/astronomer/astro-cli/blob/9c48fb0be44df45db61e5a7f796c367957a634e7/cloud/deployment/fromfile/fromfile_test.go#L1075-L1079) (from PR) | [Design Doc](https://www.notion.so/astronomerio/Development-Deployment-CLI-Design-1c171af388d64e5ebc9f39ab136165b3?pvs=4#2063656dbf0a42a2b2635adbfcda6921)

2024-02-20 10:16 UTC, feluelle commented on astro/cli/astro-deployment-hibernate.md
> +| `-d, --for`              | Specify the hibernation period using a duration.                      | Any amount of time in the format `XmYhZm`            |
```suggestion
| `-d, --for`              | Specify the hibernation period using a duration.                      | Any amount of time in the format `XhYm`            |
```

[This](https://pkg.go.dev/time#ParseDuration) is what we use internally.

> ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

But a user should only pass either number of `h`, `m` or both like `2h45m`.

2024-02-20 10:16 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `XmYhZm`            |
https://github.com/astronomer/docs/pull/3423/files#r1495567322

2024-02-20 10:17 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `XmYhZm`            |
Same here. https://github.com/astronomer/docs/pull/3423#discussion_r1495567322

2024-02-20 10:47 UTC, jwitz commented on astro/cli/astro-deployment-wake-up.md
> +| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `XmYhZm`            |
```suggestion
| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `YhZm`            |
```

2024-02-20 11:12 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `YhZm`            |
```suggestion
| `-d, --for`              | Specify the awake period using a duration.                          | Any amount of time in the format `XhYm`            |
```
To use the same format as above 😬

2024-02-20 11:12 UTC, feluelle approved these changes

2024-02-20 18:01 UTC, sunkickr commented
Does this add the CORE API endpoints to docs too? or do we have another PR for that? Along with the development deployments for CLI the API endpoints will now be on v1beta1

2024-02-21 13:22 UTC, jwitz commented
@sunkickr Can you clarify? Not sure where we'd update docs due to the core API changes - we have Core API endpoints documented but only as a general API resource: https://docs.astronomer.io/astro/api/iam-api-reference

2024-02-21 18:55 UTC, lzdanski approved these changes
There were some punctuation inconsistencies in one of these tables + not sure about the release date? All my feedback is minor, so going ahead and approving.

Tested the .mdx -> .md rel-link change which LGTM

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `--wait`                    | Wait for the new Deployment to have a [healthy](deployment-health-incidents.md) status before completing the command
```suggestion
| `--wait`                    | Wait for the new Deployment to have a [healthy](deployment-health-incidents.md) status before completing the command.                                                                                                                                       | None                                                                                                                                                                                                                                                                                       |
```

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `--deployment-file`         | Location of the template file that specifies the configuration of the new Deployment. File can be in either JSON or YAML format. See [Create a Deployment with a Deploy
```suggestion
| `--deployment-file`         | Location of the template file that specifies the configuration of the new Deployment. File can be in either JSON or YAML format. See [Create a Deployment with a Deployment File](manage-deployments-as-code.md#create-a-deployment-using-a-template-file). | A valid file path for YAML or JSON template file                                                                                                                                                                                                                                           |
```

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `--dag-deploy`              | Enables DAG-only deploys for the Deployment. The default is `disable`
```suggestion
| `--dag-deploy`              | Enables DAG-only deploys for the Deployment. The default is `disable`.                                                                                                                                                                                      | Either `enable` or `disable`.                                                                                                                                                                                                                                                              |
```

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `-c`, `--cluster-id`        | (Astro Hybrid and Astro Hosted dedicated clusters only) The cluster in which you want to create a Deployment
```suggestion
| `-c`, `--cluster-id`        | (Astro Hybrid and Astro Hosted dedicated clusters only) The cluster in which you want to create a Deployment.                                                                                                                                               | A valid [cluster ID](manage-hybrid-clusters.md#view-clusters).                                                                                                                                                                                                                             |
```

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/astro-deployment-create.md
> +| `-p`, `--cloud-provider`    | The Cloud Provider to use for your Deployment. The default is `gcp`
```suggestion
| `-p`, `--cloud-provider`    | The Cloud Provider to use for your Deployment. The default is `gcp`.                                                                                                                                                                                        | For standard clusters, possible values are `aws` and `gcp`. For dedicated clusters, possible values are `aws`, `azure`, and `gcp`.                                                                                                                                                         |
```

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/release-notes.md
> +Release date: February 19, 2024
```suggestion
Release date: February 21, 2024
```
Did this change or are we publishing retroactively?

2024-02-21 18:55 UTC, lzdanski commented on astro/cli/release-notes.md
> +You can now use the Astro CLI to hibernate or wake up a development Deployment. These commands work well in automated processes where a Deployment requires flexibility for when it hibernates. Note th
```suggestion
You can now use the Astro CLI to hibernate or wake up a development Deployment. These commands work well in automated processes where a Deployment requires flexibility for when it hibernates. Note that you can hibernate a Deployment only if you enable **Development Mode** when you [create the Deployment](create-deployment.md).
```

2024-02-21 22:42 UTC, sunkickr commented
@jwitz we've added new CORE API endpoints that users can use to hibernate/wake up deployments. Wondering how those get added to the general API docs

2024-02-21 23:02 UTC, sunkickr commented on astro/cli/release-notes.md
> +Release date: February 19, 2024
The release date will be Feburary 22nd

2024-02-21 23:15 UTC, sunkickr commented on astro/cli/release-notes.md
> +## Astro CLI 1.24.0
There a few more changes in this release:

- workload-identity flag and field for astro deployment create/update and the deployment file - https://github.com/astronomer/astro-cli/pull/1550
- new `astro organization role list` command - https://github.com/astronomer/astro-cli/pull/1554
- fixed an issue were `deployment variable list --save` did not work for secret variables - https://github.com/astronomer/astro-cli/pull/1558
- fixed an issue where updating a Deployment with a deployment file did not work with a deployment API token - https://github.com/astronomer/astro-cli/pull/1559
- new commands for user/team role management. Still trying to figure out if this will be in the release. It is main but I don't know much about it - https://github.com/astronomer/astro-cli/pull/1553

2024-02-21 23:15 UTC, sunkickr commented
The release will be tomorrow. I added a list of features and fixes in the release to a comment above

2024-02-22 11:15 UTC, jwitz commented
@sunkickr Added all the changes you listed. Doc changes for custom roles can wait until the core feature released and documented

2024-02-22 15:56 UTC, sunkickr approved these changes

2024-02-27 20:54 UTC, feluelle requested changes

2024-02-27 20:54 UTC, feluelle commented on astro/cli/astro-deployment-hibernate.md
> +astro deployment hibernate [one of --until/ --for/ --resume-schedule]
Oh this has changed. resume-schedule is now remove-override

2024-02-27 20:57 UTC, feluelle requested changes
Please check the entire document again for the following change

2024-02-27 20:57 UTC, feluelle commented on astro/cli/astro-deployment-hibernate.md
> +| `-r, --resume-schedule`  | Remove any existing override and resume regular hibernation schedule. | None                                                 |
Same here. It is just the flag name that changed

2024-02-27 20:57 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +astro deployment hibernate [one of --until/ --for/ --resume-schedule]
And here

2024-02-27 20:57 UTC, feluelle commented on astro/cli/astro-deployment-wake-up.md
> +| `-r, --resume-schedule`  | Remove any overrides and resume regular hibernation schedule.       | None                                                 |
And here

2024-02-27 21:04 UTC, lzdanski commented on astro/cli/astro-deployment-hibernate.md
> +| `-r, --resume-schedule`  | Remove any existing override and resume regular hibernation schedule. | None                                                 |
```suggestion
| `-r, --remove-override`  | Remove any existing override and resume regular hibernation schedule. | None                                                 |
```

2024-02-27 21:04 UTC, lzdanski commented on astro/cli/astro-deployment-hibernate.md
> +astro deployment hibernate [one of --until/ --for/ --resume-schedule]
```suggestion
astro deployment hibernate [one of --until/ --for/ --remove-override]
```

2024-02-27 21:04 UTC, lzdanski commented on astro/cli/astro-deployment-wake-up.md
> +astro deployment hibernate [one of --until/ --for/ --resume-schedule]
```suggestion
astro deployment hibernate [one of --until/ --for/ --remove-override]
```

2024-02-27 21:04 UTC, lzdanski commented on astro/cli/astro-deployment-wake-up.md
> +| `-r, --resume-schedule`  | Remove any overrides and resume regular hibernation schedule.       | None                                                 |
```suggestion
| `-r, --remove-override`  | Remove any overrides and resume regular hibernation schedule.       | None                                                 |
```

2024-02-27 21:13 UTC, feluelle commented
One more thing: 

Should we mention that hibernation is a private preview feature in the cli docs somewhere? If we don't already?

@sunkickr @kushalmalani wdyt?

2024-02-27 21:15 UTC, feluelle commented
Feel free to dismiss my review once my comments got addressed. :)

2024-02-27 21:20 UTC, feluelle approved these changes
Approving to unblock

2024-02-27 21:21 UTC, lzdanski commented on astro/cli/release-notes.md
> +Release date: February 22, 2024
```suggestion
Release date: February 27, 2024
```

2024-02-27 21:50 UTC, merged

2024-02-28 08:55 UTC, feluelle commented
> One more thing: 
> 
> Should we mention that hibernation is a private preview feature in the cli docs somewhere? If we don't already? (Like an info/note box or so)
> 
> @sunkickr @kushalmalani wdyt?

Or @lzdanski @jwitz ofc? Do we mention this is anywhere?