Houston API docs refresh
astronomer/docs pull request #3434
Opened 2024-02-21 14:59 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/3413

2024-02-21 14:59 UTC, jwitz commented on software/houston-api.md
> +## Resolving Houston API errors
I left a placeholder topic here because I'd really like to include some troubleshooting tips for the Houston API. Tech reviewers, if you have any experience here please let me know!

2024-02-21 15:00 UTC, jwitz commented on software/houston-api-examples.md
When reviewing this file, please check:

- Are the queries formatted correctly? 
- Are the queries "Best practice"? As in, are they a realistic example of usage?

2024-04-29 22:58 UTC, fhaynes requested changes
A lot of the queries needed some syntax fixing. I tested each one in the houston playground. Let me know if any of the changes don't make sense. 

I also made some suggestions for some grammar changes.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
That query did not work in the playground. This should, though:
```graphql
query workspaceDeployment {
  workspaceDeployment(
    releaseName: "mathematical-probe-2087"
    workspaceUuid: "ck35y9uf44y8l0a19cmwd1x8x"
  )
  {
    id
    status
    createdAt
    updatedAt
    roleBindings {
      id, 
      role, 
      user {
        username,
        emails {
          primary
        }
      }
    } 
  }
}```

It did not like the empty user object `user{}`. You have to specify at least something to come back, I think.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +query User {
This query works fine

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +    runtimeVersion: "{{RUNTIME_VER}}"
Is this a templated string that didn't get resolved?

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation CreateDeployment {
This mutation will not work, I don't think, and it failed in the playground. This works, however:
```graphql
mutation CreateNewDeployment{
  createDeployment(
    workspaceUuid: "<workspace-id>",
    type: "airflow",
    label: "<deployment-name>",
    executor:CeleryExecutor,
    runtimeVersion: "{{RUNTIME_VER}}"
  ) {
  id
  }
}
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation upsertDeployment(
This one is OK, though note that the config field of Deployment is scheduled to be deprecated, iirc.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +The following query adds a user to a Deployment as a Deployment viewer,. then returns the user and Deployment information back to the requester.
Grammar error here, with the `,.` thing.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation AddDeploymentUser(
If you want to use variables in your example, you must either specify the type, like this:
```graphql
mutation AddDeploymentUser(
  $userId: Id!, 
  $email: String!, 
  $deploymentId: Id!,
  $role: Role!
)
{
		deploymentAddUserRole(
			userId: $userId
			email: $email
			deploymentId: $deploymentId
			role: $role
		) {
			id
			user {
				username
			}
			role
			deployment {
				id
				releaseName
			}
		}
	}
```

Or you can provide default arguments, like this:
```graphql
mutation AddDeploymentUser(
  $userId:Id! = "f9182b1d-2f7c-4d33-920b-2124b1660d83", 
  $email: String! = "usertoadd@mycompany.com", 
  $deploymentId: Id! = "<some_id>",
  $role: Role! = DEPLOYMENT_VIEWER
)
{
		deploymentAddUserRole(
			userId: $userId
			email: $email
			deploymentId: $deploymentId
			role: $role
		) {
			id
			user {
				username
			}
			role
			deployment {
				id
				releaseName
			}
		}
	}
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation removeUser {
User does not have a field named `uuid`. Did you mean `id`?

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +    $role: Role! = WORKSPACE_USER
`WORKSPACE_USER` is not one of the values of the Role enum. It has `WORKSPACE_VIEWER`, `WORKSPACE_EDITOR`, and `WORKSPACE_ADMIN`

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +      deploymentRoles: $deploymentRoles
This variable ($deploymentRoles) is not specified above.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation createSystemRoleBinding (
Need to specify the types of the arguments:
```graphql
mutation createSystemRoleBinding (
    $userId: ID! = "<user-id>"
    $role: Role! = SYSTEM_ADMIN
) {
  createSystemRoleBinding(
    userId: $userId
    role: $role
  ) {
    id
  }
}
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +mutation UpdateDeploymentVariables {
The variable types will need to be specified here as well

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +The Houston API allows you to build applications that provision and manage resources on Astronomer Software. You can use the Houston API to perform CRUD operations on entities scoped to the Astronome
```suggestion
The Houston API allows you to build applications that provision and manage resources on Astronomer Software. You can use the Houston API to perform CRUD operations on entities scoped to the Astronomer platform, including Airflow Deployments, Workspaces, and Users.
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +## Schema overview
```suggestion
## Schema Overview
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +You then need to add your token as an `authorization` header to your Houston API requests. For example, the following curl command uses `'authorization: <my-api-token>'` to authenticate a request to
```suggestion
You then need to add your token as an `Authorization` header to your Houston API requests. For example, the following curl command uses `'Authorization: <my-api-token>'` to authenticate a request to add a new Workspace user:
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +## Resolving Houston API errors
```suggestion
## Resolving Houston API Errors
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +## Resolving Houston API errors
Using the browser's inspect tool is probably the most common one I use, client side. I can go into more detail on using it, if you want.

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +- [Houston API examples](houston-api-examples.md)
```suggestion
- [Houston API Examples](houston-api-examples.md)
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api.md
> +## See also
```suggestion
## See Also
```

2024-04-29 22:58 UTC, fhaynes commented on software/houston-api-examples.md
> +    $role: Role! = WORKSPACE_USER
It also has `USER`

2024-04-30 12:15 UTC, jwitz commented on software/houston-api-examples.md
> +    runtimeVersion: "{{RUNTIME_VER}}"
This will render as the latest available runtime version in the docs. We use this formatting so that we can update the Runtime version from one place and apply it to all docs.

2024-04-30 12:54 UTC, jwitz commented on software/houston-api.md
> +- [Houston API examples](houston-api-examples.md)
We use sentence case for doc and topic titles on docs

2024-04-30 13:17 UTC, jwitz commented on software/houston-api.md
> +## Resolving Houston API errors
Let's hold off on this for now and do a follow-up PR that's dedicated to this topic, this is already a lot to review/ publish in one go

2024-05-02 14:11 UTC, jwitz commented on software/houston-api-examples.md
@fhaynes Is there an example "Create a Workspace" query we can add here? If you provide the raw query, I can write the docs around it.

2024-05-14 23:13 UTC, lzdanski reviewed
Some review comments! Also, I see this PR has some conflicts.

2024-05-14 23:13 UTC, lzdanski commented on software/houston-api-examples.md
> +- The user's email address. Additionally, ensure that the user has already begun creating an account on the platform. They must have signed up for an account, and Astronomer Software must already hav
**Additionally, ensure that the user has already begun creating an account on the platform.** - this is a little confusing a description I think. 
```suggestion
- The user's email address. This needs to be the email address that the user provided when they began creating an account on the platform. They must have signed up for an account, and Astronomer Software must already have generated an invite token for the user. 
```

2024-05-15 15:40 UTC, jwitz commented on software/houston-api-examples.md
> +- The role to add the user as. Can be `DEPLOYMENT_ADMIN`, `DEPLOYMENT_EDITOR`, or `DEPLOYMENT_VIEWER`.
I think so? Show me where we bold them though, maybe it makes sense to do that here

2024-05-15 16:06 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.mdx
> +>>>>>>> 4d74812f48985d721113075b5a1b1415f2842ed7:astro/runtime-version-lifecycle-policy.mdx
```suggestion
All major Astro Runtime versions belong to the Astro Runtime stable release channel. The LTS release channel is a subset of the stable release channel and includes additional stability, reliability, and support. For more information on how Astro Runtime is versioned, see [Runtime versioning](runtime-image-architecture.mdx#runtime-versioning).
```

2024-05-16 13:08 UTC, lzdanski commented on software/houston-api-examples.md
> +- The role to add the user as. Can be `DEPLOYMENT_ADMIN`, `DEPLOYMENT_EDITOR`, or `DEPLOYMENT_VIEWER`.
https://docs.astronomer.io/astro/configure-worker-queues#worker-queue-settings

2024-05-22 21:39 UTC, lzdanski approved these changes
My feedback are really small style/voice things LGTM

2024-05-22 21:39 UTC, lzdanski commented on software/houston-api-examples.md
> +and can return any of the fields under `Type Details`, such as:
```suggestion

 The `workspaceDeployment` query can return also any of the fields under `Type Details`, such as:
```

2024-05-22 21:39 UTC, lzdanski commented on software/houston-api-examples.md
> +For instance, you can run the following query to retrieve the Deployment's:
```suggestion
For example, you can run the following query to retrieve the Deployment's:
```

2024-05-22 21:39 UTC, lzdanski commented on software/houston-api-examples.md
> +- **Workspace ID**: To retrieve this value, run `astro workspace list`. Alternatively, open a Workspace in the Software UI and copy the value after `/w/` in your Workspace URL (for example `https://a
```suggestion
- **Workspace ID**: To retrieve this value, run `astro workspace list`. Alternatively, open a Workspace in the Software UI and copy the value after `/w/` in your Workspace URL, for example `https://app.basedomain/w/<workspace-id>`.
```

2024-05-22 21:39 UTC, lzdanski commented on software/houston-api-examples.md
> +The query returns the requested details for all users who exactly match the values provided for the `userSearch`. For example, the following query would retrieve the requested values for any user acc
```suggestion
The query returns the requested details for all users who exactly match the values provided for the `userSearch`. For example, the following query would retrieve the requested values for any user accounts with the email `name@mycompany.com`:
```

2024-05-22 21:39 UTC, lzdanski commented on software/houston-api-examples.md
> +To create a Deployment, you need Workspace Admin permissions and a **Workspace ID**. To retrieve this value, run `astro workspace list`. Alternatively, open a Workspace in the Software UI and copy th
```suggestion
To create a Deployment, you need Workspace Admin permissions and a **Workspace ID**. To retrieve this value, run `astro workspace list`. Alternatively, open a Workspace in the Software UI and copy the value after `/w/` in your Workspace URL, for example `https://app.basedomain/w/<workspace-id>`.
```

2024-05-23 10:14 UTC, merged