Add max node clarification
astronomer/docs pull request #3440
Opened 2024-02-22 23:18 UTC by lzdanski

Resolves #3400

2024-02-28 11:51 UTC, jwitz commented on astro/manage-hybrid-clusters.md
> +In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit. However, settin
```suggestion
In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 20 to make sure that each worker queue can scale to its limit. 
```
I might be reading this wrong, but isn't this just a fix to some incorrect math? Perviously, we say:

>Maximum node count for a node pool must always be equal to or greater than the sum of all maximum possible workers across all worker queues that are configured with that worker node type.

In the example we provide, the "sum of all maximum possible workers across all worker queues" would be 20, so I don't think we would even allow 15 to be configured in the first place.

Also if it does end up being 20, maybe we should change the example numbers so that the calculated max node figure is different from the default of 20

2024-02-28 11:52 UTC, jwitz requested changes
One technical question, I'm not quite sure why we're still listing the 15 figure

2024-02-29 15:44 UTC, lzdanski commented on astro/manage-hybrid-clusters.md
> +In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit. However, settin
@ophie200 - Can you give us some clarification here? Is it possible to have a smaller number than the total maximum worker counts (sum of maximum worker counts per each worker queue)?

2024-03-15 16:54 UTC, lzdanski commented on astro/manage-hybrid-clusters.md
> +In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit. However, settin
@ophie200 - Clarification question:

Does Maximum worker count need to equal the node pool size? I think that's what's tripping us up here in clarifying this.  If max worker count = max node pool size, then this is wrong and it should be a total of 20 instead of 15.

2024-05-13 15:13 UTC, jwitz commented on astro/manage-hybrid-clusters.md
> +In this scenario, the maximum node count for the `m5.2xlarge` node pool in your cluster must be equal to or greater than 15 to make sure that each worker queue can scale to its limit. However, settin
So basically, we want to document two numbers:
- "20" which is the _actual_ limit
- "Less than 20" which is what you can set if you don't expect Deployments to hit max worker count that often

I updated my suggestion to reflect this, after that it's good to merge

2024-05-22 15:37 UTC, merged