Update Get Started tutorial Part 1 with the Astronaut DAG
astronomer/docs pull request #3462
Opened 2024-02-27 14:54 UTC by TJaniF

2024-02-27 21:50 UTC, kentdanas requested changes
@TJaniF I think this is looking good! Suggested moving a couple things around, so I'll take another look after that's done. Let me know if you want to chat about anything.

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +- `/dags`: A directory of DAG files. Each Astro project includes one example DAG `example_astronauts`. For more information on DAGs, see [Introduction to Airflow DAGs](dags.md).
```suggestion
- `/dags`: A directory of DAG files. Each Astro project includes one example DAG: `example_astronauts`. For more information on DAGs, see [Introduction to Airflow DAGs](dags.md).
```

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
>  - The [Astro CLI](https://docs.astronomer.io/astro/cli/install-cli).
We should probably say a version or greater here, since previous versions won't contain the astronauts example DAG.

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +To provide a basic demonstration of an ETL pipeline, this DAG queries the [Open Notify API](https://github.com/open-notify/Open-Notify-API) to get a list of all astronauts currently in space, passes
```suggestion
To provide a basic demonstration of an ETL pipeline, this DAG queries the [Open Notify API](https://github.com/open-notify/Open-Notify-API) to get a list of all astronauts currently in space, passes that list to a second task, and dynamically prints a statement to the Airflow logs for each astronaut. 
```

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +    To access information about dynamically mapped task instances of a a dynamically mapped task, click the green square of the task instance and then click on **[] Mapped task** to get a list of all
I think we should add a note here that this tutorial doesn't discuss dynamic task mapping in depth, but it is a frequently used feature and you can find more info at [link to the doc], etc. Otherwise it seems a bit out of place to mention the feature but not define it.

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +    - The first task, `get_astronauts`, queries the [Open Notify API](https://github.com/open-notify/Open-Notify-API) for information about astronauts currently in space. The task returns the list of
I think this description should go in Step 4 when we first introduce the DAG. Here it seems a little repetitive, and odd that we don't mention that earlier when looking at all the views of the DAG.

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +## Step 6: Make a change to the example DAG
Honestly I'm not sure this step really adds anything educationally - can we remove it and go straight to writing a new DAG?

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +    Adding a docstring to your DAG is a best practice. It helps you and others understand what the DAG does and how it works and it can be converted to a [DAG Doc] by setting `doc_md=__doc__` in the
```suggestion
    Adding a docstring to your DAG is a best practice. It helps you and others understand what the DAG does and how it works and it can be converted to a [DAG Doc](custom-airflow-ui-docs-tutorial.md) by setting `doc_md=__doc__` in the DAG definition. 
```
Double check me on the link here :)

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +    An operator is a Python class containing the logic to define the work to be completed by a single task. This second task `print_reaction` uses the [BashOperator](https://registry.astronomer.io/pr
```suggestion
    For common tasks in Airflow, you can use pre-built operators instead of writing your own function. An operator is a Python class containing the logic to define the work to be completed by a single task. This second task, `print_reaction`, uses the [BashOperator](https://registry.astronomer.io/providers/apache-airflow/versions/latest/modules/bashoperator) to run a bash command that prints `This is awesome!` to the logs. The first parameter of the task (`task_id`) defines the name of the task that appears in the Airflow UI. 
```
Link to operators guide here?

2024-02-27 21:50 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +To view your new DAG in the Airflow UI, enter `http://localhost:8080/` in your browser. As long as Airflow is running, it automatically picks up any new changes in your `/dags` directory. Existing fi
```suggestion
Go back to the Airflow UI to view your new DAG. Airflow will parse the `/dags` directory for changes to existing files  every 30 seconds and new files every 5 minutes.
```
They should already have the Airflow UI up at this point in the tutorial, so I think we can simplify.

2024-02-28 00:25 UTC, TJaniF reviewed
Thank you @kentdanas ! I accepted all the changes and restructured :)

2024-02-28 17:19 UTC, kentdanas approved these changes
@TJaniF I think this looks good. I want to chat about it in our sync with edu team tomorrow, but let's go ahead and loop in docs team for edits.

2024-02-28 17:19 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +- `print_astronaut_craft`: is a dynamically mapped Airflow task. Creating one dynamically mapped task instance for each astronaut in space, which each prints a statement to the logs for one astronaut
```suggestion
- `print_astronaut_craft`: is a dynamically mapped Airflow task. It creates one dynamically mapped task instance for each astronaut in space, which prints a statement to the logs for that astronaut. Dynamic task mapping is a versatile feature of Airflow that allows you to create a variable number of tasks at runtime. This feature is covered in more depth in the [Create dynamic Airflow tasks](dynamic-tasks.md) guide.
```

2024-02-28 17:19 UTC, kentdanas commented on learn/get-started-with-airflow.md
> +When you tell Airflow to print something to the terminal, the output appears in Airflow task logs. Task logs are an important feature for troubleshooting DAGs. If a task in your DAG fails, task logs
```suggestion
When one of your tasks prints something, the output appears in Airflow task logs. Task logs are an important feature for troubleshooting DAGs. If a task in your DAG fails, task logs are the best place to investigate why.
```

2024-02-29 13:15 UTC, TJaniF reviewed
Thanks @kentdanas :) 

@jwitz and @lzdanski ready for you! This is just an interim version pending a larger restructuring of the Get Started content the goal for now is to standardize on the example_astronauts DAG we'll talk more about it in the sync today.

2024-03-01 11:22 UTC, jwitz approved these changes
Looks great! New example DAGs are excellent, and I think this strikes the right balance between introduction and explanatory content. My edits skewed towards making this _more_ introductory, so definitely push back and lmk if I accidentally removed a key concept

2024-03-01 11:22 UTC, jwitz commented on learn/get-started-with-airflow.md
> +    - `schedule`: The frequency the DAG runs. There are many options to define the schedule of a DAG, including as a [timedelta object](https://docs.python.org/3/library/datetime.html#timedelta-objec
```suggestion
    - `schedule`: The frequency at which the DAG runs. If you don't set this value, the DAG runs every 24 hours after the `start_date`. In this example, the DAG is scheduled to run whenever the `example_astronauts` DAG's `get_astronauts` task completes successfully using an Airflow dataset. There are many options to define the schedule of a DAG. For more information, see [DAG scheduling and time tables in Airflow](https://docs.astronomer.io/learn/scheduling-in-airflow).
```
Simplified some of the linking here to focus on "schedule" as a concept rather than datasets

2024-03-01 11:22 UTC, jwitz commented on learn/get-started-with-airflow.md
> +    For common tasks in Airflow, you can use pre-built [operators](what-is-an-operator.md) instead of writing your own function. An operator is a Python class containing the logic to define the work
```suggestion
    For common operations, you can use pre-built [operators](what-is-an-operator.md) instead of writing your own function. An operator is a Python class containing the logic to define the work to be completed by a single task. `print_reaction` uses the [BashOperator](https://registry.astronomer.io/providers/apache-airflow/versions/latest/modules/bashoperator) to run a bash command.
```
We mention task ID earlier, so cutting this explanation

2024-03-01 11:22 UTC, jwitz commented on learn/get-started-with-airflow.md
> +3. The `my_astronauts_dag` is scheduled to run whenever the `current_astronauts` [Dataset](airflow-datasets.md) is updated by a successful run of the `get_astronauts` task in the `example_astronauts`
```suggestion
3. The `my_astronauts_dag` is scheduled to run whenever the `current_astronauts` dataset is updated by a successful run of the `get_astronauts` task in the `example_astronauts` DAG. Trigger another manual run of the `example_astronauts` DAG to see the `my_astronauts_dag` run again after the `get_astronauts` task completes.
```
If there's a doc link we want to link to many times, it might be worth including in a "See also" section a the bottom of the doc. There's a lot of links in the doc at the moment, and I worry that new users might get overwhelmed if they start clicking around into new guides.

2024-03-01 11:22 UTC, jwitz commented on learn/get-started-with-airflow.md
> +    You can put this decorator on top of any Python function to turn your code into an Airflow task. This is one of the features that makes Airflow so powerful: Any action that can be defined in Pyth
```suggestion
    You can put this decorator on top of any Python function to turn your code into an Airflow task. This is one of the features that makes Airflow so powerful: Any action that can be defined in Python, no matter how complex, can be orchestrated using Airflow.
    
    Each task in an Airflow DAG requires a unique `task_id`. Here we can see why that's important: the `num_people_in_space` task can call the unique `get_astronauts` task to pull the data it generated from XCom.
```

2024-03-01 11:22 UTC, jwitz commented on learn/get-started-with-airflow.md
> +    The `@task` decorator is used to define a task in the TaskFlow API. By default, the `task_id` is the name of the Python function. Each task in an Airflow DAG requires a unique `task_id`. This `pr
```suggestion
    The `@task` decorator lets you define Python functions with very little boilerplate code. This is the syntax of the TaskFlow API, which is Airflow's lightweight framework for defining tasks. This `print_num_people_in_space` task pulls the number of people in space from XCom and prints it to the logs. Learn more about XCom in the [Pass data between tasks](airflow-passing-data-between-tasks.md) guide.
```
This is the first proper introduction of the concept of the TaskFlow API, so we should add a half sentence about why it exists.

2024-03-04 12:18 UTC, jwitz commented on learn/get-started-with-airflow.md
> +    To access information about [dynamically mapped](dynamic-tasks.md) task instances of a a dynamically mapped task, click the green square of the task instance and then click on **[] Mapped task**
I thought "mapping task" / "mapped task" might be clear clear, although you could also say the mapping task was "mapped" to each instance. Hmmmm need to think about this more

2024-03-04 12:20 UTC, jwitz commented on learn/get-started-with-airflow.md
> +8. Save your code.
We do have this ability! See: https://docusaurus.io/docs/markdown-features#details . It has to be in a "details" block, but that might be nice as a way to label the content while it's still condensed.

2024-03-04 12:21 UTC, jwitz commented on learn/get-started-with-airflow.md
> +8. Save your code.
Let me know if you'd like me to implement it, tbh I think having the full project code will be helpful for the 2nd tutorial

2024-03-04 14:15 UTC, TJaniF commented on learn/get-started-with-airflow.md
> +8. Save your code.
ooh nice! I made an attempt at implementing it and yeah can add it to the 2nd tutorial as well :)

2024-03-05 09:40 UTC, jwitz approved these changes
Love the details implementation!

2024-03-05 09:40 UTC, jwitz commented on learn/get-started-with-airflow.md
> +9. Save your code. Your DAG should look like this:
```suggestion
9. Save your code. Your completed DAG should look like this:
```

2024-03-29 15:34 UTC, merged