Reporting Dashboard alerts
astronomer/docs pull request #3495
Opened 2024-03-01 22:53 UTC by lzdanski

Resolves #3489

2024-03-04 14:27 UTC, jwitz requested changes
Jotting some initial feedback and questions here, will take a closer look after those are resolved

2024-03-04 14:27 UTC, jwitz commented on sidebarsAstro.js
> +            label: "Reporting Dashboard",
```suggestion
            label: "Reporting dashboards,
```

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +sidebar_label: 'Set up reporting data exports'
```suggestion
sidebar_label: 'Export reporting data'
```

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dashboard.md
> +sidebar_label: 'View Organization reporting dashboards'
```suggestion
sidebar_label: 'Access dashboards'
```

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +## Email a data export
```suggestion
### Export reporting data to email
```

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +## Download data
```suggestion
## Download reporting data
```

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +In the **Export** menu, you can choose to download up to 1.0 M rows of data in a particular file format.
Thinking about Ask Astro usage here and also general readability - I wouldn't mind being redundant and adding the steps for accessing the dashboard to each of these topics.

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +In the **Export** menu, you can choose to download up to 1.0 M rows of data in a particular file format.
What happens when you try to download more than 1.0 M rows of data? And is this 1.0 Megabytes or Million? Not seen this unit before

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +Hover over the dashboard element whose data you want to export, and then expand the additional options menu to choose to either **Export** your data or **Alert when** to email your data to you when i
```suggestion
As an Astro administrator, you might want to export reporting data to share with other team members or to keep a record of key performance indicators. Astro supports several different methods for exporting reporting data based on how and when you want to receive the data. Specifically, you can export data:

- Manually through the Cloud UI.
- On a regular schedule.
- Whenever a certain condition is met, such as a metric reaching a specific threshold.

When you export reporting data, Astro exports the last 1.0M of data from a specific dashboard in the file format of your choice. Use this document to learn about the different ways you can trigger the export process.
```
Tried to add more of a general summary here.

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +Instead of downloading your data directly, you can choose to email it to a specified address by choosing **Export** > **Send now**. Enter the recipient's email address and optionally edit the subject
Similar comment here, can we have specific numbered steps instead of a paragraph for the process of exporting? Including accessing the dashboards page to begin with

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +## Email a data export
Added as a subtopic because this seems like an extension of the manual export topic.

2024-03-04 14:27 UTC, jwitz commented on astro/reporting-dash-exports.md
> +When you configure a data export or alert that is sent to an email address, you can choose to run the report with their level of user permissions by clicking **Run queries as recipient** in the **Mor
```suggestion
If you need to send data to a member of your team with fewer permissions on Astro, you can export the report with the recipient's level of user permissions by clicking **Run queries as recipient** in the **More options** section.
```

2024-03-04 17:58 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +## Email a data export
I realize that's how it seems, but they're two separate functions and flows. If I were to cluster them its. Exporting as a download is a one click process, but the email export requires a few more steps and can bump users into setting up an alert.

- Download data

- Export data in an email
|- scheduled data export in email
- Set up an alert

2024-03-04 18:17 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +In the **Export** menu, you can choose to download up to 1.0 M rows of data in a particular file format.
This threw me back to a suppressed applied enviro class I took, capitalized `M` is short for mega/million (10^6) as [a standard unit](https://en.wikipedia.org/wiki/Metric_prefix). I wrote it long form for convenience. `Megabyte` is actually `1 million bytes`, we just never call it that conventionally.

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dashboard.md
>  Dashboards help you quickly identify opportunities to optimize how your team uses Airflow at different organizational levels, such as across your Organization, within Workspaces, in specific Deployme
``
For example, you can use the **Deployment Detail** dashboard to identify unexpected DAG behaviors, without requiring you to examine the DAGs results in the Airflow UI. Instead, you can quickly switch between DAGs in a dashboard to identify trends like unusually high compute use, and then check the **Cost Breakdown** dashboard to identify any associated costs incurred by that behavior.
``

This is not true at the moment, though we could envision implementing something that does that in the future. The deployment detail tab doesn't give you any information at the dag level  and while the dag detail tab does, you wouldn't use it identify unexpected dag behaviors + it can be quite time consuming to switch between all the dags in a deployment. In terms of benefits, you could talk of identifying deployments that need upgrading (deployment tab), trace the source of a increase in cloud costs (cost breakdown) or assess whether critical dags comply with SLA (dag detail)

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dashboard.md
>  Dashboards help you quickly identify opportunities to optimize how your team uses Airflow at different organizational levels, such as across your Organization, within Workspaces, in specific Deployme
```and tasks within DAGs.
```
would suggest instead 'operators used within dags'

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dashboard.md
> +To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this page d
```suggestion
To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this page directly at [https://cloud.astronomer.io/dashboards](https://cloud.astronomer.io/dashboards). In addition to viewing the dashboards in the Astro UI, you can also [export and email individual reports](reporting-dash-exports.md).
```

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dash-exports.md
> +1. To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this pag
```suggestion
1. To view Astro reporting dashboards, click your Organization name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this page directly at [https://cloud.astronomer.io/dashboards](https://cloud.astronomer.io/dashboards).
```

need to correct in other places as well

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dash-exports.md
> +2. Open the **Export** menu.
specify something along the lines of:  "on the graph or table of which you want to export an image or the underlying data"

2024-03-04 20:51 UTC, mazoulai commented on astro/reporting-dash-exports.md
> +5. (Optional) To send more than one report, click **+ Add**, and then select the report you want to send and its file format.
Would also indicate that you can export the entire dashboard at once (select entire page) or even all of the dashbaords at once (select entire workbook)

2024-03-04 21:26 UTC, lzdanski commented on astro/reporting-dashboard.md
>  Dashboards help you quickly identify opportunities to optimize how your team uses Airflow at different organizational levels, such as across your Organization, within Workspaces, in specific Deployme
```suggestion
Dashboards help you quickly identify opportunities to optimize how your team uses Airflow at different organizational levels, such as across your Organization, within Workspaces, in specific Deployments, and operators within DAGs. For example, you can use the **Organization Overview** or **Deployment Detail** dashboard to identify unexpected activity, without requiring you to examine the DAGs results in the Airflow UI. Instead, you can quickly check your dashboards to identify trends like unusually high or low rates of task successes, and then check the **Cost Breakdown** dashboard to identify any associated costs incurred by that behavior.
```

2024-03-04 21:26 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +2. Open the **Export** menu.
```suggestion
2. Open the **Export** menu on the chart or table that you want to export.
```

2024-03-05 12:06 UTC, jwitz commented on astro/reporting-dash-exports.md
> +1. To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this pag
Until we have a smoother process for accessing org settings, I think it's better to call out the larger, more prominent clickable object here, which in this case is the Workspace name.

2024-03-05 12:19 UTC, jwitz commented on astro/reporting-dash-exports.md
> +1. To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, and then click **Dashboards**. You can also access this pag
```suggestion
1. To view Astro reporting dashboards, click your Workspace name in the upper left corner of the Astro UI, click **Organization Settings**, then click **Dashboards**. You can also access this page directly at [https://cloud.astronomer.io/dashboards](https://cloud.astronomer.io/dashboards).
```

2024-03-05 12:23 UTC, jwitz commented on astro/reporting-dash-exports.md
> +2. Open the **Export** menu for the reporting element you want to schedule an email export for and select **Schedule**.
```suggestion
2. Open the **Export** menu for the reporting element you want to schedule an email export for and select **Schedule exports...**.
```

2024-03-05 12:26 UTC, jwitz commented on astro/reporting-dash-exports.md
> +If you toggle **Condition** when setting up your schedule, it allows you to configure a conditional data export, or *reporting dashboard alert*. Instead of sending a report at a specific time interva
```suggestion
4. Specify a regular **Frequency** for the export or a **Condition** for when to trigger the export. If you define both a regular frequency and a condition, the export will trigger on both schedules.
```

2024-03-05 12:26 UTC, jwitz commented on astro/reporting-dash-exports.md
> +If you toggle **Condition** when setting up your schedule, it allows you to configure a conditional data export, or *reporting dashboard alert*. Instead of sending a report at a specific time interva
I assume this is how it works? Noticed the **Frequency** button doesn't go away when you turn on the **Condition** tab.

2024-03-05 12:28 UTC, jwitz commented on astro/reporting-dash-exports.md
> +## Set up a reporting dashboard alert
```suggestion
## Create a reporting dashboard alert
```

2024-03-05 12:31 UTC, jwitz commented on astro/reporting-dash-exports.md
> +Like with an emailed dashboard report, when you receive a dashboard alert in an email, the sender appears as **Sigma Computing**. The subject line also includes the name of the dashboard element's da
We say "Like with an emailed dashboard report", but this alert is fundamentally identical to a report export right? I think it's good to have two separate topics because there are different use cases for schedules and alerts, but we should be clear that the alert is just a conditionally scheduled report export.

2024-03-05 14:28 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +Like with an emailed dashboard report, when you receive a dashboard alert in an email, the sender appears as **Sigma Computing**. The subject line also includes the name of the dashboard element's da
The report export and emailed dashboard report are identical. One is just downloaded immediately and the other is emailed to an address as an attachment.

2024-03-05 14:48 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +If you toggle **Condition** when setting up your schedule, it allows you to configure a conditional data export, or *reporting dashboard alert*. Instead of sending a report at a specific time interva
I tried this but couldn't get it to work :/

2024-03-05 16:08 UTC, jwitz commented on astro/reporting-dash-exports.md
> +title: "Export data reports and set up alerts"
```suggestion
title: "Export Astro reporting data"
```

2024-03-05 16:09 UTC, jwitz commented on astro/reporting-dash-exports.md
> +<img src={require("../static/img/docs/dash-export-alert.png").default} alt="Configure the conditions that trigger the reporting dashboard to send you a data report for a particular dashboard element.
```suggestion
    <img src={require("../static/img/docs/dash-export-alert.png").default} alt="Configure the conditions that trigger the reporting dashboard to send you a data report for a particular dashboard element." style={{ width: "60%", maxWidth: "400px", height: "auto" }} />
```

2024-03-05 16:33 UTC, lzdanski commented on astro/reporting-dashboard.md
>  Dashboards help you quickly identify opportunities to optimize how your team uses Airflow at different organizational levels, such as across your Organization, within Workspaces, in specific Deployme
Made some fixes to clarify current functionality.

2024-03-05 16:48 UTC, conorbev reviewed
Just a couple of comments.

2024-03-05 16:48 UTC, conorbev commented on astro/deployment-metrics.md
> +These metrics contain information about the Kubernetes Pods running your workers and schedulers. Different worker and scheduler Pods will appear on these charts as differently colored lines.
Unrelated to Dashboards!

But I don't think this needs to mention Kubernetes Pods because it's a Celery worker that the chart is showing, customer doesn't need to know that it happens to be running on K8s infra under the covers.

`These metrics contain infrastructure utilization information about your workers and schedulers. Unique worker and scheduler instances will appear on these charts as differently colored lines.`

2024-03-05 16:48 UTC, conorbev commented on astro/reporting-dash-exports.md
> +    If you need to send data to a member of your team with fewer permissions on Astro, you can export the report with the recipient's level of user permissions by clicking **Run queries as recipient*
This is interesting.

I think I would leave this part out because access to all the data in these reports is binary. You either have the owner role/org billing admin role ( and therefore have all access ) or you don't.

So any user will fewer permissions than you defacto doesn't have access to this data at all.

I think the tip here is almost the reverse, and I did have one private preview user mention this:

"Oh I don't want to make person A be an org billing admin, but, I can just export them a view of this data once in a while if they need it and have it emailed to them".

2024-03-05 16:50 UTC, lzdanski commented on astro/deployment-metrics.md
> +These metrics contain information about the Kubernetes Pods running your workers and schedulers. Different worker and scheduler Pods will appear on these charts as differently colored lines.
```suggestion
These metrics contain infrastructure use information about your workers and schedulers. Unique worker and scheduler instances appear on these charts as different colored lines.
```

2024-03-05 17:03 UTC, lzdanski commented on astro/reporting-dash-exports.md
> +Organization reporting dashboards are only available at the Enterprise product tier.
```suggestion
Organization reporting dashboards are only available if you have an Enterprise product plan.
```

2024-03-05 17:10 UTC, merged