Update intro guide
astronomer/docs pull request #3499
Opened 2024-03-04 16:29 UTC by TJaniF

2024-03-06 01:57 UTC, kentdanas requested changes
@TJaniF this is looking great. Left a couple of initial comments, but I will review again tomorrow with fresh eyes.

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +## Quickstart
```suggestion
## Get started
```
I don't love using "Quickstart" since we also have the Quickstart in the same sidebar category, which is something different. Also, do you think we should link to the tutorials here if we're recommending that path for more hands-on learning?

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +## Milestones
```suggestion
## Airflow history
```
I think "milestones" could possibly be misunderstood as learning milestones or something else. I think we can keep it as "history", even with a bulleted list like this.

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +## Quickstart
Also - I wonder if we actually just put this in the intro, instead of in its own section? Since we're not really providing a lot of guidance, maybe having it stand out as the first section doesn't make sense.

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- **CI/CD for data pipelines**: With all the logic of your workflows defined in Python, it is possible to implement best practice CI/CD processes for your data pipelines.
```suggestion
```
Since this is a pretty long list, I'd suggest taking CICD out. It's pretty specific, and not a built-in function of Airflow.

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +Airflow is used by many data professionals with a wide range of backgrounds and use cases in [companies of all sizes and types](https://github.com/apache/airflow/blob/main/INTHEWILD.md). Data enginee
```suggestion
Airflow is used by many data professionals at [companies of all sizes and types](https://github.com/apache/airflow/blob/main/INTHEWILD.md). Data engineers, data scientists, ML engineers, and data analysts all need to perform actions on data in a complex web of dependencies. With Airflow, you can orchestrate these actions and dependencies in a single platform, no matter which tools you are using and how complex your pipelines are.
```

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- **ETL/ELT for analytics**: [90% of Airflow users](https://airflow.apache.org/survey/), use it for Extract-Transform-Load (ETL) and Extract-Load-Transfrom (ELT) patterns related to data analytics, w
```suggestion
- **ETL/ELT for analytics**: [90% of Airflow users](https://airflow.apache.org/survey/) use it for Extract-Transform-Load (ETL) and Extract-Load-Transfrom (ELT) patterns. Often, these pipelines support critical operational processes. For an example use case, see [ELT with Airflow and dbt Core](use-case-airflow-dbt.md).
```

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- **ETL/ELT for analytics**: [90% of Airflow users](https://airflow.apache.org/survey/), use it for Extract-Transform-Load (ETL) and Extract-Load-Transfrom (ELT) patterns related to data analytics, w
Similar to the use cases page update, I would keep this to ETL/ELT, and update the next one to just "business operations".

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- **Spinning up and down infrastructure**: Airflow can be used to spin up and down infrastructure, for example, to run create and delete temporary tables in a database or spin up and down a Spark clu
```suggestion
- **Managing infrastructure**: Airflow can be used to spin up and down infrastructure, for example, to run create and delete temporary tables in a database or spin up and down a Spark cluster. For an example use case, see [Use Airflow setup/ teardown to run data quality checks in an MLOps pipeline](use-case-setup-teardown-data-quality.md).
```

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +<summary>Click to view the full DAG code used for the Screenshot</summary>
😮 did not know we could do this!

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- [Astronomer Learn](https:/docs.astronomer.io/learn/): (you are here!) A collection of guides and tutorials on Airflow.
```suggestion
```

2024-03-06 01:57 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- [Astronomer Registry](https://registry.astronomer.io/): A collection of Airflow providers, with detailed information about each provider and its operators, as well as example DAGs showing how to us
```suggestion
```
Removing a few of these since the list is pretty long.

2024-03-07 22:59 UTC, kentdanas requested changes
@TJaniF great update - a couple of additional comments after second review. Let me know if you want to chat about any of them.

2024-03-07 22:59 UTC, kentdanas commented on learn/intro-to-airflow.md
>  ## Airflow components
I think we should actually remove the Airflow components section, and instead have a section for "Running Airflow", that would say there are many ways to run Airflow, but the easiest is run locally with the CLI, run in production on Astro, for more info about the components of Airflow see the components guide.

2024-03-07 22:59 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- [Astro CLI](https://docs.astronomer.io/astro/cli/get-started): The easiest way to run a local Airflow environment.
```suggestion
```
Removing since we will link above in my new suggested section. And then we can keep this to more high level resource "centers"

2024-03-07 22:59 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- **Airflow plugins**: Airflow plugins are a way to further extend the functionality of Airflow. For more information, see [Airflow plugins](using-airflow-plugins.md). Note that [custom hooks and ope
How would you feel about not including plugins here? As you'll notice from some of my other comments, overall I want to make this guide a bit more concise :) and I think plugins are not something a brand new person is likely to come in looking for specifically, nor would it hurt if they started using Airflow without knowing what they are. The rest of this list seems pretty critical (although _maybe_ we could remove the API bullet.....?)

2024-03-07 22:59 UTC, kentdanas commented on learn/intro-to-airflow.md
> +### Core concepts
```suggestion
### Running pipelines
```
Let me know what you think of these suggestions - I don't love "core concepts" and "building blocks", because it doesn't really tell me what the concepts are about, and I would say operators/decorators/providers are "core" concepts in Airflow. At the same time, I'm not sure something like "DAG runs"/"Writing DAGs" is right, because maybe people don't know what a DAG is. So I'm trying to make them more specific, but still general enough that they're easily understandable.

2024-03-07 22:59 UTC, kentdanas commented on learn/intro-to-airflow.md
> +### Building blocks
```suggestion
### Writing pipelines
```

2024-03-08 10:50 UTC, TJaniF reviewed
Thank you @kentdanas ! Made the changes and added a couple of comments. :)

2024-03-08 10:50 UTC, TJaniF commented on learn/intro-to-airflow.md
> +## Quickstart
I think that makes sense, I did not think of the doubling with the side bar somehow 🤦 

The getting started tutorials are already mentioned in the "Other ways to Learn" Sections, so I think this section can go entirely. :)

2024-03-08 10:50 UTC, TJaniF commented on learn/intro-to-airflow.md
> +<summary>Click to view the full DAG code used for the Screenshot</summary>
Same! @jwitz showed me in the Get started tutorial review. I will be using that everywhere now 😃

2024-03-08 10:50 UTC, TJaniF commented on learn/intro-to-airflow.md
> +### Core concepts
Yeah, I struggled naming those subsections 😅 
I like the running vs writing pipelines distinction!

2024-03-08 10:50 UTC, TJaniF commented on learn/intro-to-airflow.md
> +- **Airflow plugins**: Airflow plugins are a way to further extend the functionality of Airflow. For more information, see [Airflow plugins](using-airflow-plugins.md). Note that [custom hooks and ope
I'm ok with kicking out the plugins for simplicity, I mean I didn't know what they did for the first few months I was writing DAGs, so definitely not a crucial intro topic. 😅 The main reason I added them here was for the note about not putting custom operators in there anymore but I think new users wont be writing custom modules anyways and this is explained in detail in the custom operator guide. 

Hmmm... the API bullet. I am on the fence about that one because it feels like one of the concepts that can unlock so many use cases but can be hard to discover? It is probably not relevant for the "classical" new DAG author but relevant for anyone wanting to use Airflow in some larger framework. But I might be biased because I look for API information and docs a lot in other tool's documentation 😅

2024-03-08 10:50 UTC, TJaniF commented on learn/intro-to-airflow.md
>  ## Airflow components
I like that idea :)

2024-03-14 18:56 UTC, kentdanas approved these changes
@TJaniF this looks great content-wise. A few other minor comments. Once those are addressed feel free to move on to copy editing.

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- 2015: Airflow started as an open source project at Airbnb. In 2015, Airbnb was growing rapidly and struggling to manage the vast quantities of internal data it generated every day. To satisfy the n
```suggestion
Over the past ten years, Airflow has grown to be the open source standard for data orchestration:

- 2015: Airflow started as an open source project at Airbnb. In 2015, Airbnb was growing rapidly and struggling to manage the vast quantities of internal data it generated every day. To satisfy the need for a robust scheduling tool, [Maxime Beauchemin](https://maximebeauchemin.medium.com/) created Airflow to allow Airbnb to quickly author, iterate, and monitor batch data pipelines.
```
I always learned you weren't supposed to start paragraphs/sections with a bullet, so adding a brief lead-in sentence.

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +### Running pipelines
I know it was my suggestion, but now I'm not actually sure I like "running" here, because maybe that points too much to something like schedules, or running Airflow. What about "Pipeline basics"?

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +## Running Airflow
I think running Airflow should go before Airflow concepts

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +There are many ways to run Airflow, Astronomer recommends:
```suggestion
There are many ways to run Airflow, some of which are easier than others. Astronomer recommends: 
```

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- To use the open-source [**Astro CLI**](https://docs.astronomer.io/astro/cli/get-started-cli) to run Airflow locally. The Astro CLI is the easiest way to create a local Airflow instance running in [
```suggestion
- Using the open-source [**Astro CLI**](https://docs.astronomer.io/astro/cli/get-started-cli) to run Airflow locally. The Astro CLI is the easiest way to create a local Airflow instance running in [Docker](https://www.docker.com/) and is free to use for everyone.
```

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +- To use [**Astro**](https://astronomer.io/try-astro) to run Airflow in production. A free trial is available.
```suggestion
- Using [**Astro**](https://astronomer.io/try-astro) to run Airflow in production. Astro is a fully-managed SaaS application for data orchestration that helps teams write and run data pipelines with Apache Airflow at any level of scale. A free trial is available.
```

2024-03-14 18:56 UTC, kentdanas commented on learn/intro-to-airflow.md
> +To learn more about other options for running Airflow, see [the Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html). All Airflow installations includ
```suggestion
All Airflow installations include the mandatory Airflow components as part of their infrastructure: the webserver, the scheduler, the database, and the executor. See [Airflow components](airflow-components.md) for more information.
```
I'm making this even more opinionated :) We link to the official Airflow docs in the resources section, but otherwise I don't think we need to mention other ways of running Airflow in a doc of ours. If people want that, they can go find it themselves.

2024-03-15 12:16 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 

@lzdanski and @jwitz ready for you :) Kenten and I are very open to different section title suggestions 😅

2024-03-15 12:16 UTC, TJaniF commented on learn/intro-to-airflow.md
> +### Running pipelines
I think Pipeline basics would work. `Pipeline terminology` might be more accurate but sounds a little boring 😅 I'll change it to pipeline basics and will make a note for Jake that we are very open to other section titles :)

2024-03-18 11:05 UTC, TJaniF commented on learn/intro-to-airflow.md
> +Now that you have a basic understanding of Apache Airflow, you are ready to write your first DAG by following the the [Get started with Apache Airflow](get-started-with-airflow.md) tutorial.
```suggestion
Now that you have a basic understanding of Apache Airflow, you are ready to write your first DAG by following the [Get started with Apache Airflow](get-started-with-airflow.md) tutorial.
```

2024-03-29 15:38 UTC, kentdanas commented
@jwitz @lzdanski I think we're just waiting on a copy edit on this one? Doesn't look like either of you have reviewed yet.

2024-04-01 19:35 UTC, lzdanski reviewed
Some small phrasing things!

2024-04-01 19:35 UTC, lzdanski commented on learn/intro-to-airflow.md
> +Some commonly used building blocks like the BashOperator, the `@task` decorator or the PythonOperator are part of core Airflow and automatically installed in all Airflow instances. Additionally, many
```suggestion
Some commonly used building blocks, like the BashOperator, the `@task` decorator, or the PythonOperator, are part of core Airflow and automatically installed in all Airflow instances. Additionally, many operators are maintained separately to Airflow in **Airflow provider packages**, which group modules interacting with a specific service into a package.
```

2024-04-01 19:35 UTC, lzdanski commented on learn/intro-to-airflow.md
> +Of course there is much more to Airflow than just DAGs and tasks. Here are a few additional concepts and features that you are likely to encounter:
```suggestion
While there are much more to Airflow than just DAGs and tasks, here are a few additional concepts and features that you are likely to encounter:
```

2024-04-01 19:35 UTC, lzdanski commented on learn/intro-to-airflow.md
> +- **XComs**: XCom is short for "cross-communication", you can use XCom to pass information between your Airflow tasks. For more information, see [Passing data between tasks](airflow-passing-data-betw
```suggestion
- **XComs**: XCom is short for *cross-communication*, you can use XCom to pass information between your Airflow tasks. For more information, see [Passing data between tasks](airflow-passing-data-between-tasks.md).
```

2024-04-02 11:13 UTC, TJaniF reviewed
@lzdanski thank you! Accepted all suggestions and made the suggested changes :)

2024-04-02 11:13 UTC, TJaniF commented on learn/intro-to-airflow.md
> +- **Tool agnosticism**: Airflow can connect to any application in your data ecosystem that allows connections through an API and prebuilt modules exist for many common data tools.
yeah, I tried to phrase it without using the term `operator` since we don't assume any Airflow knowledge for this guide. Also `modules` is the term that encompasses sensors, operators, triggers and decorators, but yeah I agree it is not widely used. 

How about splitting it into 2 sentences and using `operator` and linking to the operators 101 guide on it?

2024-04-02 11:13 UTC, TJaniF commented on learn/intro-to-airflow.md
> +- **Managing infrastructure**: Airflow can be used to spin up and down infrastructure, for example, to run create and delete temporary tables in a database or spin up and down a Spark cluster. For an
I think both exist, but I agree we use tear down in the setup/teardown feature so good to standardize on that :)

2024-04-02 13:41 UTC, lzdanski approved these changes

2024-04-02 14:22 UTC, merged