Update DAGs guide
astronomer/docs pull request #3519
Opened 2024-03-14 01:22 UTC by TJaniF

2024-03-15 19:31 UTC, kentdanas requested changes
@TJaniF this is a great update. Requesting changes because I suggested some stuff be moved around, so I'll take another look after. Let me know Mon if you want to chat about any of this.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +Within an Airflow DAG, each node represents a task or task group, and each edge represents a dependency between tasks or task groups.
```suggestion
Within an Airflow DAG, each node represents a task and each edge represents a dependency between tasks. 
```
I know technically a node could be a task group, but want to keep this super simple up front because it could easily be the first guide somebody reads. Also, while you can take some actions on the entire task group, I still think realistically they're more like a collection of nodes than they are a node themselves.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +DAGs are defined in Python code and visualized in the Airflow UI. They can be as simple as a single task or as complex as containing hundreds of tasks, task groups, and complicated dependencies.
```suggestion
DAGs are defined in Python code and visualized in the Airflow UI. They can be as simple as a single task or as complex as hundreds or thousands of tasks with complicated dependencies.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +In Airflow, a DAG is a data pipeline or workflow defined in Python code. DAGs are the main organizational unit in Airflow. They contain a collection of tasks with defined dependencies between them th
I would actually take the first part of this "In Airflow, a DAG is a data pipeline or workflow defined in Python code. DAGs are the main organizational unit in Airflow. They contain a collection of tasks with defined dependencies between them that you want to execute on a schedule." and make it the intro paragraph. And put the intro first paragraph here. Definitely important to cover the mathematical structure and how it maps to tasks/dependencies, but I think these two sentences are more approachable (and more the practical definition), and should come first.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **Directed**: There is a clear direction of flow between tasks. A task can either be upstream, downstream or parallel to another task.
```suggestion
- **Directed**: There is a clear direction of flow between tasks. A task can either be upstream, downstream, or parallel to another task.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +Aside from these requirements, DAGs in Airflow can be as complicated as you need! You can define tasks running in parallel, sequentially, conditional branches and visually group tasks together in [ta
```suggestion
Aside from these requirements, DAGs in Airflow can be as complicated as you need! You can define tasks that will run in parallel or sequentially, implement conditional branches, and visually group tasks together in [task groups](task-groups.md).
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +Each task in a DAG is one unit of work performed. Tasks can be anything from a simple Python function to a complex data transformation or a call to an external service. They are defined using [Airflo
```suggestion
Each task in a DAG performs one unit of work. Tasks can be anything from a simple Python function to a complex data transformation or a call to an external service. They are defined using [Airflow operators](what-is-an-operator.md) or [Airflow decorators](airflow-decorators.md). The dependencies between tasks can be set in different ways, see [Managing Dependencies](managing-dependencies.md).
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- DAG dependency layout: The layout of the tasks in the DAG run graph. This tells you in what direction to read the DAG run graph. You can change the layout in the dropdown menu.
```suggestion
```
This is nitpicky, but since there's a lot going on in the screenshot, I would remove this one. It's pretty self explanatory, and I don't think something people change all that often.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- `logical date`: The point in time for which the DAG run is scheduled. This date and time is not necessarily the same as the actual moment the DAG run is executed, see [Scheduling](scheduling-in-air
```suggestion
- `logical date`: The point in time for which the DAG run is scheduled. This date and time is not necessarily the same as the actual moment the DAG run is executed. See [Scheduling](scheduling-in-airflow.md) for more information.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +The previous screenshot shows 4 successful DAG runs, one for each DAG run type:
If we remove the dependency layout from the screenshot you may be able to zoom in a little more. Right now at least on my screen I can't see the DAG run type indicators in the grid at all beyond little blobs.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +A DAG run graph in the Airflow UI contains information about the DAG run, as well as the status of each task instance in the DAG run. The following screenshot shows the same simple DAG as in the prev
Probably should define task instance up above as well

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **backfill**: The first DAG run shown was created by a [backfill](rerunning-dags.md#backfill). You can see a little circle arrow on the DAG run bar.
```suggestion
- **backfill**: The first DAG run shown was created by a [backfill](rerunning-dags.md#backfill). You can see a circled arrow on the DAG run bar.
```
Double check me on this - it is a circle wiht an arrow in it, right?

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **manual**: The third DAG run was started manually by a user in the Airflow UI or using the Airflow CLI. You can see a little play icon on the DAG run bar.
```suggestion
- **manual**: The third DAG run was started manually by a user in the Airflow UI or using the Airflow CLI. You can see a play icon on the DAG run bar.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **dataset_triggered**: The fourth DAG run was started by a [dataset](airflow-datasets.md). You can see a little dataset icon on the DAG run bar.
```suggestion
- **dataset_triggered**: The fourth DAG run was started by a [dataset](airflow-datasets.md). You can see a dataset icon on the DAG run bar.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **Dynamically mapped task group**: A task group can be dynamically mapped like an individual task. The number of mapped task group instances is shown in `[]` behind the task group id. See [Mapping
```suggestion
```
To keep this a bit simpler, let's remove this bullet and the notation in the screenshot. I added a suggested note in the dynamic tasks bullet that you can also map a task group. Mostly I think "regular task groups" could be confusing

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **Regular task group**: A task group is a tool to logically and visually group tasks in an Airflow DAG. See [Airflow task groups](task-groups.md) for more information.
```suggestion
- **Task group**: A task group is a tool to logically and visually group tasks in an Airflow DAG. See [Airflow task groups](task-groups.md) for more information.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **Dynamically mapped task**: A task that is [dynamically created](dynamic-tasks.md) at runtime based on changing user defined input. The number of task instances is shown in `[]` behind the task id
```suggestion
- **Dynamically mapped task**: A task that is [dynamically created](dynamic-tasks.md) at runtime based on changing user defined input. The number of task instances is shown in `[]` behind the task id. Task groups can also be dynamically mapped.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- **Dataset**: As of Airflow 2.9, datasets are shown in the DAG graph. If a DAG is scheduled on a dataset it will be shown upstream of the first task of the DAG, if a task in the DAG updates a datase
```suggestion
- **Dataset**: Datasets are shown in the DAG graph. If a DAG is scheduled on a dataset, it will be shown upstream of the first task of the DAG. If a task in the DAG updates a dataset, it is shown after the respective task as in the previous screenshot. See [Airflow datasets](airflow-datasets.md) for more information.
```
I know this will be pretty new for a while, but saving us the effort of removing it later. It doesn't change how you write a DAG, so I think it's okay to leave out the version.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +### DAG run status
Let's put this under the higher level section "what is a DAG run" under the screenshot, not in a separate subsection.

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +- `start_date`: The date and time after which the DAG starts being scheduled. None that the first actual run of the DAG may be later than this date depending on how you define the schedule. See [DAG
```suggestion
- `start_date`: The date and time after which the DAG starts being scheduled. Note that the first actual run of the DAG may be later than this date depending on how you define the schedule. See [DAG scheduling and timetables in Airflow](scheduling-in-airflow.md) for more information. This parameter may be required depending on your Airflow version and `schedule`.
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +Additionally you can set DAG-level callbacks in the DAG definition, see [DAG-level callbacks](error-notifications-in-airflow.md#airflow-callbacks) for more information.
I think we need a "see also" section at the end here that links to the resources we recommend next (probably the getting started tutorials)

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +### Understand a complex DAG run graph
```suggestion
### Example complex DAG run
```

2024-03-15 19:31 UTC, kentdanas commented on learn/dags.md
> +### Read a DAG run graph
```suggestion
### DAG run properties
```
Another one where I might need to contemplate the best section naming (and am open to other suggestions!). I don't love "DAG run graph" because if somebody said that to me I'm not sure I would immediately understand what it was, and in the end all of the things described are not inherently part of the graph, they're just displayed there.

2024-03-18 11:35 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 
I implemented the changes (and added some comments to the complex DAG code, I had forgotten about that). Ready for another look :)

2024-03-18 17:17 UTC, kentdanas approved these changes
@TJaniF this looks great! A few other minor comments, otherwise good to move on to copy editing and wait for 2.9 release.

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +Astronomer recommends creating one Python file for each DAG and naming it after the `dag_id` as a best practice for organizing your Airflow project. At scale it is common to dynamically generate DAGs
```suggestion
Astronomer recommends creating one Python file for each DAG and naming it after the `dag_id` as a best practice for organizing your Airflow project. For certain advanced use cases it may be appropriate to dynamically generate DAGs using Python code, see [Dynamically generate DAGs in Airflow](dynamically-generating-dags.md) for more information.
```

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +Astronomer recommends creating one Python file for each DAG and naming it after the `dag_id` as a best practice for organizing your Airflow project. At scale it is common to dynamically generate DAGs
I'm a little on the fence of whether to leave the comment on dynamically generating DAGs in at all, mostly because I don't want to direct people to that from an intro-level guide, and would much rather have people use dynamic task mapping. I think the counter argument is that people do sometimes need to do this, and might be looking for it early on in their Airflow journey. Wdyt? I could be swayed either way.

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +In Airflow, you can configure when and how your DAG runs by setting parameters in the DAG object. DAG-level parameters affect how the entire DAG behaves, as opposed to task-level parameters which onl
I think it would be worth actually stating up front here that this section has _all_ the DAG-level parameters you can define, since the lack of that consolidated info anywhere else is the reason we're keeping this long section.

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +- `dag_id`: The name of the DAG. This must be unique for each DAG in the Airflow environment. When using the `@dag` decorator and not providing the `dag_id` parameter name, the function name is used
Random thought - but maybe we could have tabs for these sections of different parameters and then it wouldn't be such a wall of text? If you have info in a tab that isn't selected, will it still show up if you search the doc? That would be one reason to potentially not do this if it would mess up searching.

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +- [Introduction to Apache Airflow](intro-to-airflow.md) for an overview of Airflow concepts.
```suggestion
```
This is in the assumed knowledge section, so it shouldn't be a next step.

2024-03-18 17:17 UTC, kentdanas commented on learn/dags.md
> +## See also
Maybe also include an intro webinar in here? So tutorial, webinar, or guides on operators/decorators seem like a good list of next steps that isn't overwhelming.

2024-03-19 00:02 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 
I made the changes. For the DAG parameter section I tried putting it into tables but I am not sure I like it, not it is a wall of tables instead a wall of text 😅 . 

But both tabs and details would hide keywords from ctr F searches and with the general search the content in tabs does show up but it does not necessarily open the right tab when you click on the search result... 🤔

2024-04-02 11:19 UTC, jwitz requested changes
New content looks great! Requesting changes because I think we could maybe cut some of the DAG parameter content towards the end - it gets very detailed for what is otherwise a core introductory guide for DAGs.

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +- **Dynamically mapped task**: A task that is [dynamically created](dynamic-tasks.md) at runtime based on changing user defined input. The number of task instances is shown in `[]` behind the task id
```suggestion
- **Dynamically mapped tasks**: A dynamically mapped task is [created dynamically](dynamic-tasks.md) at runtime based on user-defined input. The number of dynamically mapped task instances is shown in brackets (`[]`) behind the task ID.
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +- **Dataset**: Datasets are shown in the DAG graph. If a DAG is scheduled on a dataset, it is shown upstream of the first task of the DAG. If a task in the DAG updates a dataset, it is shown after th
```suggestion
- **Branching tasks**: A branching task creates a conditional branch in the DAG. See [Branching in Airflow](airflow-branch-operator.md) for more information.
- **Edge labels**: Edge labels appear on the edge between two tasks. These labels are often helpful to annotate branch decisions in a DAG graph. 
- **Task groups**: A task group is a tool to logically and visually group tasks in an Airflow DAG. See [Airflow task groups](task-groups.md) for more information.
- **Setup/teardown tasks**: When using Airflow to manage infrastructure, it can be helpful to define tasks as setup and teardown tasks to take advantage of additional intelligent dependency behavior. Setup and teardown tasks appear with diagonal arrows next to their task IDs and are connected with a dotted line. See [Use setup and teardown tasks in Airflow](airflow-setup-teardown.md) for more information.
- **Datasets**: Datasets are shown in the DAG graph. If a DAG is scheduled on a dataset, it is shown upstream of the first task of the DAG. If a task in the DAG updates a dataset, it is shown after the respective task as in the previous screenshot. See [Airflow datasets](airflow-datasets.md) for more information.
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +DAGs in Airflow are defined in a Python script that is placed in an Airflow project's `DAG_FOLDER`, which is `dags/` when using the [Astro CLI](https://docs.astronomer.io/astro/cli/get-started-cli).
```suggestion
A DAG can be defined with a Python file placed in an Airflow project's `DAG_FOLDER`, which is `dags` when using the [Astro CLI](https://docs.astronomer.io/astro/cli/get-started-cli). Airflow automatically parses all files in this folder every 5 minutes to check for new DAGs, and it parses existing DAGs for code changes every 30 seconds. You can force a new DAG parse using [`airflow dags reserialize`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#reserialize), or `astro dev run dags reserialize` using the Astro CLI.
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +There are two main ways to define a DAG:
```suggestion
There are two types of syntax you can use to structure your DAG:
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +TaskFlow API and traditional syntax can be freely mixed, see [Mixing TaskFlow decorators with traditional operators](airflow-decorators.md#mixing-taskflow-decorators-with-traditional-operators) for m
```suggestion
TaskFlow API and traditional syntax can be freely mixed. See [Mixing TaskFlow decorators with traditional operators](airflow-decorators.md#mixing-taskflow-decorators-with-traditional-operators) for more information. 

The following is an example of the same DAG written using each type of syntax.
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +<summary>Click to view the full DAG code used for the Screenshot</summary>
```suggestion
<summary>Click to view the full DAG code used for the screenshot</summary>
```

2024-04-02 11:19 UTC, jwitz commented on learn/dags.md
> +Some parameters relate to adding information to the DAG or change its appearance in the **Airflow UI**:
This is a looot of info to include at the end of the guide, and reference some terms that have yet to be introduced in the guide, such as jinja. Could we save this for a separate guide so that we only cover the "core" parameters for this introductory guide?

2024-04-02 13:52 UTC, TJaniF reviewed
Thank you for the review @jwitz !

And yeah I agree the DAG level parameters section became a bit unwieldy... I separated it out into its own guide now :) 

cc: @kentdanas

2024-04-02 15:53 UTC, jwitz approved these changes
LGTM! The DAGs page is definitely more manageable now, plus it's great to still publish the quick table reference of DAG parameters

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +Some parameters relate to adding information to the DAG or change its appearance in the Airflow UI:
```suggestion
Some parameters add documentation to a DAG or change its appearance in the Airflow UI:
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +Some parameters relate to adding information to the DAG or change its appearance in the Airflow UI:
Link to our DAG docs guide?

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +There are four basic DAG-level parameters. It is a best practice to always set these parameters:
```suggestion
There are four basic DAG-level parameters. It is best practice to always set these parameters in any DAG:
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +Three other helpful parameters relate to scaling in Airflow. For more information see [Scaling Airflow to optimize performance](airflow-scaling-workers.md):
```suggestion
Some parameters can be used to scale your DAG's resource usage in Airflow. See [Scaling Airflow to optimize performance](airflow-scaling-workers.md) for more information.
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +Astronomer customers can use Astro alerts instead of or in addition to Airflow callbacks. See [When to use Airflow or Astro alerts for your pipelines on Astro](https://docs.astronomer.io/astro/best-p
```suggestion
On Astro, you can use Astro alerts instead of or in addition to Airflow callbacks. See [When to use Airflow or Astro alerts for your pipelines on Astro](https://docs.astronomer.io/astro/best-practices/airflow-vs-astro-alerts) for more information.
```

2024-04-02 15:53 UTC, jwitz commented on learn/dags.md
> +The DAGs in the previous section have the following basic parameters defined:
```suggestion
The DAGs in the previous section have the following basic parameters defined. It's best practice to always define these parameters for any DAGs you create:
```

2024-04-02 15:53 UTC, jwitz commented on learn/dags.md
> +There are many more DAG-level parameters, see the [DAG-level parameters](airflow-dag-parameters.md) guide for a complete list.
```suggestion
There are many more DAG-level parameters that let you configure anything from resource usage to the DAG's appearance in the Airflow UI. See [DAG-level parameters](airflow-dag-parameters.md) for a complete list.
```

2024-04-02 15:53 UTC, jwitz commented on learn/dags.md
> +- **Graph**: A DAG is a graph, which is a structure consisting of nodes and edges. In Airflow, nodes are tasks and edges are dependencies between tasks.
```suggestion
- **Graph**: A DAG is a graph, which is a structure consisting of nodes and edges. In Airflow, nodes are tasks and edges are dependencies between tasks. Defining workflows as graphs helps you visualize the entire workflow in a way that's easy to navigate and conceptualize.
```

2024-04-02 15:53 UTC, jwitz commented on learn/dags.md
> +After a DAG meets these requirements, it can be as simple or as complicated as you need! You can define tasks that run in parallel or sequentially, implement conditional branches, and visually group
```suggestion
Beyond these requirements, a DAG can be as simple or as complicated as you need! You can define tasks that run in parallel or sequentially, implement conditional branches, and visually group tasks together in [task groups](task-groups.md).
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +description: "Learn about all DAG-level parameters in Airflow."
```suggestion
description: "Learn about all important DAG-level parameters in Airflow."
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +title: "DAG-level parameters"
```suggestion
title: "DAG-level parameters in Airflow" 
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +## Basic
```suggestion
## Basic DAG-level parameters
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +## UI-related
```suggestion
## UI parameters
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +## Jinja templating
```suggestion
## Jinja templating parameters
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +## Callbacks
```suggestion
## Callback parameters
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +See [Airflow callbacks](error-notifications-in-airflow.md#airflow-callbacks) for more information.
```suggestion
```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +
```suggestion

These parameters help you configure the behavior of [Airflow callbacks](error-notifications-in-airflow.md#airflow-callbacks).

```

2024-04-02 15:53 UTC, jwitz commented on learn/airflow-dag-parameters.md
> +## Other
```suggestion
## Other parameters
```

2024-04-02 17:28 UTC, TJaniF reviewed
Thank you @jwitz ! :)

2024-04-02 17:28 UTC, TJaniF commented on learn/airflow-dag-parameters.md
> +description: "Learn about all DAG-level parameters in Airflow."
It is actually pretty much all of them haha, but I still think saying `important` makes sense, even if just to future proof.

2024-04-08 14:07 UTC, TJaniF commented on learn/airflow-dag-parameters.md
> +| `max_consecutive_failed_dag_runs`   | (experimental) The maximum number of consecutive failed DAG runs, after which the scheduler will disable this DAG. |
```suggestion
| `max_consecutive_failed_dag_runs`   | (experimental, added in Airflow 2.9) The maximum number of consecutive failed DAG runs, after which the scheduler will disable this DAG. |
```

2024-04-08 14:22 UTC, merged