Create a unified, airgapped Software installation procedure
astronomer/docs pull request #3521
Opened 2024-03-14 17:54 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/3415

This PR achieves a few things:

- Creates a single document for all future Astronomer Software installs (ie no more cloud-specific documents)
- Establishes "airgapped" as the default installation context
- Adds steps for configuring additional security and resource management features that are essential to running Astronomer Software

I haven't yet deleted the other installation guides in order to have them as reference for review, but soon this will be the only available installation doc for Astronomer Software.

2024-03-15 15:48 UTC, jwitz commented on software/install-airgapped.md
> +</TabItem>
```suggestion
</TabItem>
</Tabs>
```

2024-05-11 15:20 UTC, rob-1126 commented
Hold, not finished, just opening a draft PR to have a way to preview the build.

2024-05-24 18:25 UTC, rob-1126 commented
@jwitz I'm done with my first pass and am going to tag-team in @cdabella @nsAstro @ReadytoRocc  to help read for content. Can you a stab and fixing style/voice/foibles and breaking out each Addendum item to its own page.

2024-05-24 18:26 UTC, rob-1126 commented
@jwitz @lzdanski I'll be out all next week but will be back Monday the third.

2024-06-07 15:40 UTC, rob-1126 approved these changes

2024-06-08 19:38 UTC, lzdanski reviewed
Github is getting a little mad with how many comments I've made so I'm doing this in two review phases.

2024-06-08 19:38 UTC, lzdanski commented on software/install-airgapped.md
> +4. Construct an email connection string and store it in a secret named `astronomer-tls` in the astronomer platform namespace. Make sure to *url-encode* the username and password if they contain speci
```suggestion
1. Obtain a set of SMTP credentials from your email administrator for you to use to send email from Astronomer Software. When you request an email address and display name, remember that these emails are not designed for users to reply directly to them. Request all the following information:
     * Email address
     * Email display name requirements. Some email servers require a **From** line of: `Do Not Reply <donotreply@example.com>`. 
     * SMTP username. This is usually the same as the email address.
     * SMTP password
     * SMTP hostname
     * SMTP port
     * Whether or not the connection supports TLS
     
     :::info 

    If there is a `/` or any other escape character in your username or password, you may need to [URL encode](https://www.urlencoder.org/) those characters.

    :::
    
2. Ensure that your Kubernetes cluster has access to send outbound email to the SMTP server.
3. Change the configuration in `values.yaml` from `noreply@my.email.internal` to an email address that is valid to use with your SMTP credentials.
4. Construct an email connection string and store it in a secret named `astronomer-tls` in the Astronomer platform namespace. Make sure to *url-encode* the username and password if they contain special characters.
```

2024-06-08 19:38 UTC, lzdanski commented on software/install-airgapped.md
> +    In general, an SMTP URI is formatted as `smtps://USERNAME:PASSWORD@HOST/?pool=true`. The following table contains examples of what the URI will look like for some of the most popular SMTP service
```suggestion
    In general, an SMTP URI is formatted as `smtps://USERNAME:PASSWORD@HOST/?pool=true`. The following table contains examples of the URI for some of the most popular SMTP services:
```

2024-06-08 19:38 UTC, lzdanski commented on software/install-airgapped.md
> +:::
I think we want this note earlier in the section.

2024-06-08 19:38 UTC, lzdanski commented on software/install-airgapped.md
> +Replace `<desired-storage-class>` in the following configuration with the storage class you wish to use for each respective component. You can remove the configuration for any component where using t
```suggestion
Skip this step if your cluster defines a volume storage class, and you want to use it for all volumes associated with Astronomer Software and its Airflow Deployments.

Astronomer strongly recommends that you do not back up any volumes used for Astronomer Software with mechanical hard drives.

Replace `<desired-storage-class>` in the following configuration with the storage class you want to use for each respective component. You can remove the configuration for any component where using the default storage is acceptable. 
```

2024-06-08 20:33 UTC, lzdanski requested changes
**incredible** rewrite! I know I left a huge number of comments, but these rewrites capture a lot of small formatting, voice, style, and structure pieces that will help with clarity and make it easier for us to move some bigger pieces around if we decide we need to. Thank you for all your hard work, this looks great!

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 17: Determine what version of Astronomer Software to install {#determine-what-version-of-astronomer-software-to-install}
```suggestion
## Step 17: Determine which version of Astronomer Software to install {#determine-version-of-astronomer-software}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Astronomer recommends new Astronomer Software installations use the most recent version available in either the Stable or Long Term Support (LTS) release-channel. Keep this version at hand for the fo
```suggestion
Astronomer recommends new Astronomer Software installations use the most recent version available in either the Stable or Long Term Support (LTS) release-channel. Keep this version number available for the following steps.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +If you have internet access to `https://helm.astronomer.io` run the following command on the machine you will be installing Astronomer Software on:
```suggestion
If you have internet access to `https://helm.astronomer.io`, run the following command on the machine where you want to install Astronomer Software:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +If you don't have internet access to `https://helm.astronomer.io`, download the Astronomer Software Platform helm chart file corresponding to the version of Astronomer Software you are installing or
```suggestion
If you don't have internet access to `https://helm.astronomer.io`, download the Astronomer Software Platform Helm chart file corresponding to the version of Astronomer Software you are installing or upgrading to from `https://helm.astronomer.io/astronomer-<version number>.tgz`. For example, for Astronomer Software v0.34.1 you would download `https://helm.astronomer.io/astronomer-0.34.1.tgz`. This file does not need to uploaded to an internal chart repository.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Create a file named `upgrade.sh` in your [platform-deployment project-directory](#platform-deployment-project-directory) containing the script below. Specify the following values at the beginning of
```suggestion
Create a file named `upgrade.sh` in your [platform-deployment project-directory](#platform-deployment-project-directory) containing the following script. Specify the following values at the beginning of the script:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +The images and tags which are required for your Software installation depend on the version of Astronomer you're installing. To gather a list of exact images and tags required for your Astronomer ver
```suggestion
The images and tags that are required for your Software installation depend on the version of Astronomer you want to install. To gather a list of exact images and tags required for your Astronomer version:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 21: Fetch Airflow/ Astrp Runtime updates {#fetch-airflow-updates}
```suggestion
## Step 21: Fetch Airflow/Astro Runtime updates {#fetch-airflow-updates}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +By default, Astronomer checks for Airflow/ Astro Runtime updates once a day at midnight by querying `https://updates.astronomer.io/astronomer-runtime`, which returns a JSON file with details about th
```suggestion
By default, Astronomer checks for Airflow/Astro Runtime updates once a day at midnight by querying `https://updates.astronomer.io/astronomer-runtime`, which returns a JSON file with details about the latest available Astro Runtime versions. However, this URL is not accessible in an airgapped environment. There are several options for making these updates accessible in an airgapped environment:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +The following topic provides an example implementation of hosting the Airflow updates JSON files in your airgapped environment and accessing them using an Nginx endpoint. Depending on your organizati
```suggestion
This procedure provides an example implementation for how to host the Airflow updates JSON files in your airgapped environment and then access them using an Nginx endpoint. Depending on your organization's platform and use cases, your own installation might vary from this setup.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 22: Openshift only - apply openshift-specific configuration {#openshift-configuration}
```suggestion
## Step 22: (OpenShift only) Apply OpenShift-specific configuration {#openshift-configuration}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Astronomer Software on Openshift is only supported when using [a third-party ingress-controller](#elect-to-use-a-third-party-ingress-controller) and using the [logging sidecar](#configure-sidecar-log
```suggestion
Astronomer Software on OpenShift is only supported when using [a third-party ingress-controller](#elect-to-use-a-third-party-ingress-controller) and using the [logging sidecar](#configure-sidecar-logging) feature of Astronomer Software. The above configuration enables both of these items.
```
This probably needs to get moved to before the code example - we try to give descriptions/heads up about any restrictions or limitations *before* the code examples that they relate to. Kind of a just in case, because most people skip the text sandwiched between a code block and the next header.

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +You may restrict the airflow-management components of Astronomre Software to a list of pre-defined namespaces and configure it to operate without a ClusterRole by following instructions in [Configure
```suggestion
You can restrict the Airflow management components of Astronomer Software to a list of predefined namespaces and configure it to operate without a ClusterRole by following the instructions in [Configure a Kubernetes namespace pool for Astronomer Software](namespace-pools.md) and setting `global.clusterRoles` to `false`. 
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +You may replace this privileged daemonset with unprivileged logging sidecars by following instructions at [Export logs using container sidecars](export-task-logs.md#export-logs-using-container-sideca
```suggestion
You can replace this privileged Daemonset with unprivileged logging sidecars by following instructions in [Export logs using container sidecars](export-task-logs.md#export-logs-using-container-sidecars).
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 26: Pre-creating the load balancer {#creating-the-load-balancer}
```suggestion
## Step 26: Create the load balancer {#creating-the-load-balancer}
```
Any reason why this is pre-create instead of just create?

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +If you're using a third-party ingress controller or provisioning domain names for ingress objects using external DNS, skip this step.
```suggestion
Skip this step if you're using a third-party ingress controller or provisioning domain names for ingress objects using external DNS.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Perform a preliminary install of Astronomer Software to trigger the load-balancer creation. This installation will intentionally and timeout after 30 seconds, but it will cause the load balancer to b
```suggestion
To install and function, Astronomer Software platform components require DNS entries to point to a load balancer associated with your ingress controller.

Perform a preliminary install of Astronomer Software to trigger your ingress controller to create the load balancer. This installation intentionally times out after 30 seconds, but it causes the ingress controller to still create the load balancer.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +- `CHART_NAME`: Set to `astronomer/astronomer` if fetching platform images from the internet. Otherwise, specify the filename if you're installing from a file (for example `astronomer-0.34.1.tgz`).
```suggestion
- `CHART_NAME`: Set to `astronomer/astronomer` if fetching platform images from the internet. Otherwise, specify the filename, if you're installing from a file. For example `astronomer-0.34.1.tgz`.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Run `kubectl -n <astronomer platformm namespace> get service -l component=ingress-controller` and verify that a service-type LoadBalancer resource has been created and received an External IP in a ra
```suggestion
Run `kubectl -n <astronomer platformm namespace> get service -l component=ingress-controller` and verify that a `service-type LoadBalancer` resource was created and that it received an External IP in a range that is accessible to your end-users, but **not** accessible to the general internet. For example:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +If the Astronomer Software platfrom chart is uninstalled and re-installed, the ingress controller will virtually always receive a new IP address, which requires DNS entries to be updated.
```suggestion
If you uninstall and re-install the Astronomer Software platform chart, the ingress controller almost always receives a new IP address, which requires updating the DNS entries.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +In lower environments, you may set `nginx.loadBalancerIP` in `values.yaml` to the External-IP address:
```suggestion
In lower environments, you can set `nginx.loadBalancerIP` in `values.yaml` to the External-IP address:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +This option allows the cluster to request same Load Balancer IP at creation time. Practically, re-builds immediately following teardowns can almost always receive the same IP address, but re-issuance
```suggestion
This option allows the cluster to request the same Load Balancer IP at creation time. Rebuilds immediately following teardowns can almost always receive the same IP address, but issuance is not guaranteed and installations will fail if the IP address has been assigned elsewhere, or is otherwise not available. Therefore, this option should not be used in higher environments unless you have taken special measures to guarantee the same IP address is reissued.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 27: Configure DNS for the integrated ingress controller {#intigrated-ingress-controller-dns-configuration}
```suggestion
## Step 27: Configure DNS for the integrated ingress controller {#integrated-ingress-controller-dns-configuration}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Run `$ kubectl get svc -n <astronomer platform namespace>`to view your load balancer's CNAME, located under the `EXTERNAL-IP` column for the `astronomer-nginx` service. It should look similar to the
```suggestion
Run `$ kubectl get svc -n <astronomer platform namespace>`to view your load balancer's CNAME, located in the `EXTERNAL-IP` column for the `astronomer-nginx` service and look similar to the following:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Install the Astronomer Software Helm chart using `upgrade.sh` (recommended for your first install) or directly from helm.
```suggestion
Install the Astronomer Software Helm chart using `upgrade.sh`, which is recommended for your first install, or directly from Helm.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 29: Verify Pods are up {#verify-pods-are-up}
```suggestion
## Step 29: Verify Pods creation {#verify-pods}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +All pods should be in Running status. E.g.:
```suggestion
All pods should be in Running status. For example, 
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +## Step 30: Verify you can access the Software UI {#verify-you-can-access-the-software-ui}
```suggestion
## Step 30: Verify you can access the Software UI {#verify-software-ui}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +The following `merge_yaml.py` script can be used to merge YAML excerpts into `values.yaml` automatically. This script requires python and the `ruamel.yaml` package, which you can install using `pip i
```suggestion
When merging YAML configurations into `values.yaml`, you can merge manually or with a tool of your choosing.

You can use the following`merge_yaml.py` script to merge YAML excerpts into `values.yaml` automatically. This script requires both Python and the `ruamel.yaml` package, which you can install using `pip install ruamel.yaml`.
To run the program, ensure that `merge_yaml.py`, `values.yaml`, and the `yaml` file that contains the configuration you want to add are all in your project directory. Then, run:
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Astronomer Software can be configured to not send outbound email.
```suggestion
You can configure Astronomer Software to not send outbound email.
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +### Configure Astronomer Software to trust private certificate authorities (CAs) {#configuring-private-cas}
```suggestion
### Configure Astronomer Software to trust private certificate authorities (CAs) {#configure-private-cas}
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +1. Store the CA's root public certificate to an [Opaque Kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) in the Astronomer namespace with a descriptive name,
```suggestion
1. Store the CA's root public certificate to an [Opaque Kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) in the Astronomer namespace with a descriptive name, such as `private-root-ca`, by running the following command.

    :::tip
    
    Before you run this command, keep the following in mind:
    
     - The root certificate you specify should be the certificate of the authority that signed the Astronomer certificate. This is not the certificate associated with Astronomer or any other service.
    - The name of the secret file must be `cert.pem` for your certificate to be trusted properly.
    - The file must contain only a single certificate, it can't be a certificate bundle.
    
    :::

```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +    Before you run this command, keep the following in mind:
```suggestion
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +    - The file must contain only a single certificate, it may not be a certificate bundle.
```suggestion
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +If your users will be deploying images to a container registry (including the integrated container registry) that uses a TLS certificate signed by a private CA, Docker Desktop needs to be configured
```suggestion
If your users will deploy images to a container registry, including the integrated container registry, that uses a TLS certificate signed by a private CA, you need to configure Docker Desktop to trust the CA's public certificate. 
```

2024-06-08 20:33 UTC, lzdanski commented on software/install-airgapped.md
> +Obtain a copy of the CAs public certificate in pem format and place it in `/etc/docker/certs.d`:
```suggestion
Obtain a copy of the CA's public certificate in pem format and place it in `/etc/docker/certs.d`:
```

2024-06-10 18:47 UTC, rob-1126 commented on software/install-gcp-standard.md
> +<!-- ARCHIVED - DO NOT MAKE UPDATES TO THIS DOC OR PUBLISH -->
Do you have a way to set up a direct from those old urls to the new guide? If not, just put a callout at the top.

2024-06-10 21:11 UTC, rob-1126 commented on software/namespace-pools.md
> +3. For each namespace in your pool, run `kubectl -n <airflow namespace> apply -f commander.yaml`.
changed to explicitly refer to the config option at 
astronomer.houston.config.deployments.preCreatedNamespaces . You can't have too many examples - if we need a better one ticket is separately though just to help get this out the door.

2024-06-10 21:12 UTC, rob-1126 commented on software/renew-tls-cert.md
> +2. Follow the instructions for requesting a TLS certificate from your organization's security team as described in [Step 4: Configure TLS](install-airgapped.md#requesting-and-validating-an-astronomer
I agree but let's tiptoe past the graveyard here and revisit after PR lands if needed. In practice users know hot to renew their TLS certs AND increasingly this rotation is automatic.

2024-06-10 21:19 UTC, rob-1126 commented on software/install-airgapped.md
> +Replace `<desired-storage-class>` in the following configuration with the storage class you wish to use for each respective component. You can remove the configuration for any component where using t
taking your suggestions but just commint directly to branch

2024-06-10 21:23 UTC, rob-1126 commented on software/install-airgapped.md
> +:::
We don't have a good alternative if they DON't want all the image tags - in reality they prune by hand. This guide could and the list probably should probably should be pulibhsed as part of our standard release process not assembled by users. Let's keep as-is and revisit opportunistically after this lands.

2024-06-10 21:24 UTC, rob-1126 commented on software/install-gcp-standard.md
> +<!-- ARCHIVED - DO NOT MAKE UPDATES TO THIS DOC OR PUBLISH -->
Can you rename this gide from install-airgapped to install-detailed and set up a similar redirect for this as well? We anticipate most future customers will be airgapped but it is the new doc for all installs.

2024-08-07 18:42 UTC, TJaniF reviewed
LGTM from a clarity and formatting perspective. Had a couple of small comments. :)

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +Kubernetes must be able to pull images from one or more container registries for Astronomer Software to function. By default, Kubernetes only trusts publicly signed certificates.  This means that by
```suggestion
Kubernetes must be able to pull images from one or more container registries for Astronomer Software to function. By default, Kubernetes only trusts publicly signed certificates. This means that by default, Kubernetes does not honor the list of certificates [trusted by the Astronomer Software platform](#configuring-a-private-certificate-authority).
```

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +While configuring the Kubernetes list of cluster certificates is a customer responsibility, Astronomer Software includes an optional component that can, for certain Kubernetes cluster configurations,
```suggestion
While configuring the Kubernetes list of cluster certificates is a customer responsibility, Astronomer Software includes an optional component that can, for certain Kubernetes cluster configurations, add certificates defined in `global.privateCaCerts` to the list of certificates trusted by Kubernetes. This can be enabled by setting `global.privateCaCertsAddToHost.enabled` and `global.privateCaCertsAddToHost.addToContainerd` to `true` in your `values.yaml` file and setting `global.privateCaCertsAddToHost.containerdConfigToml` to:
```

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +### Configure your install use a custom image repository for platform images {#use-custom-image-repository-for-platform-images}
```suggestion
### Configure your install to use a custom image repository for platform images {#use-custom-image-repository-for-platform-images}
```

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +If you don't have internet access to `https://helm.astronomer.io`, download the Astronomer Software Platform Helm chart file corresponding to the version of Astronomer Software you are installing or
```suggestion
If you don't have internet access to `https://helm.astronomer.io`, download the Astronomer Software Platform Helm chart file corresponding to the version of Astronomer Software you are installing or upgrading to from `https://helm.astronomer.io/astronomer-<version number>.tgz`. For example, for Astronomer Software v0.34.1 you would download `https://helm.astronomer.io/astronomer-0.34.1.tgz`. This file does not need to be uploaded to an internal chart repository.
```

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +# upgradeDeployments false ensures that Airflow charts are not upgraded when this script is ran
```suggestion
# upgradeDeployments false ensures that Airflow charts are not upgraded when this script is run
```

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +The images and tags that are required for your Software installation depend on the version of Astronomer you want to install. To gather a list of exact images and tags required for your Astronomer ve
```suggestion
The images and tags that are required for your Software installation depend on the version of Astronomer Software you want to install. To gather a list of exact images and tags required for your Astronomer Software version:
```

not 100% sure if I read this right

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +By default, Astronomer checks for Airflow/Astro Runtime updates once a day at midnight by querying `https://updates.astronomer.io/astronomer-runtime`, which returns a JSON file with details about the
```suggestion
By default, Astronomer Software checks for Airflow/Astro Runtime updates once a day at midnight by querying `https://updates.astronomer.io/astronomer-runtime`, which returns a JSON file with details about the latest available Astro Runtime versions. However, this URL is not accessible in an airgapped environment. There are several options for making these updates accessible in an airgapped environment:
```

Again, pls double check

2024-08-07 18:42 UTC, TJaniF commented on software/install-airgapped.md
> +To disable email transmission and email verision of users attempting to access the platform:
```suggestion
To disable email transmission and email verification of users attempting to access the platform:
```

?

2024-08-08 12:20 UTC, rob-1126 commented on software/renew-tls-cert.md
> +2. Follow the instructions for requesting a TLS certificate from your organization's security team as described in [Step 4: Configure TLS](install-airgapped.md#requesting-and-validating-an-astronomer
good catch, will fix

2024-08-08 12:22 UTC, rob-1126 commented on software/third-party-ingress-controllers.md
> +Label the namespace containing your ingress controller with the `network.openshift.io/policy-group=ingress` label. However, the label can vary based on the specific policy and configuration on your c
let's let sleeping dogs lie on this one. I'm not even sure this DOES anything and I don't think its required but disproving it is a low-priority.

2024-08-08 15:14 UTC, merobi-hub approved these changes

2024-08-08 15:14 UTC, merobi-hub commented on software/third-party-ingress-controllers.md
> +Label the namespace containing your ingress controller with the `network.openshift.io/policy-group=ingress` label. However, the label can vary based on the specific policy and configuration on your c
```suggestion
Label the namespace containing your ingress controller with the `network.openshift.io/policy-group=ingress` label. The label can vary based on the specific policy and configuration on your cluster, however. For example, you might run the following:
```

2024-08-08 15:14 UTC, merobi-hub commented on software/third-party-ingress-controllers.md
> +Alternatively, see [Use Openshift Ingress Sharding](https://docs.openshift.com/container-platform/4.15/networking/ingress-sharding.html) to create an additional Ingress instance with the required rou
```suggestion
Alternatively, see [Use Openshift Ingress Sharding](https://docs.openshift.com/container-platform/4.15/networking/ingress-sharding.html) to create an additional Ingress instance with the required `routeAdmission` policy.
```

2024-08-08 15:14 UTC, merobi-hub commented on software/third-party-ingress-controllers.md
> +Alternatively, see [Use Openshift Ingress Sharding](https://docs.openshift.com/container-platform/4.15/networking/ingress-sharding.html) to create an additional Ingress instance with the required rou
Not sure if you consider this to be code or not, but it looks like it could be...

2024-08-09 13:25 UTC, merobi-hub approved these changes

2024-08-13 15:38 UTC, rob-1126 commented
What are next steps here? I'm showing Paola is the only pending reviewer but she's no longer active at Astronomer.

2024-08-13 19:09 UTC, closed without merging