New DAGs menu
astronomer/docs pull request #3528
Opened 2024-03-15 22:08 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/3405

Resolves https://github.com/astronomer/docs/issues/3407

Resolves https://github.com/astronomer/docs/issues/3406

2024-03-20 13:47 UTC, TJaniF commented on astro/astro-dags-overview.md
> +- On Astro, the Astro UI renders [Airflow tags](https://airflow.apache.org/docs/apache-airflow/stable/howto/add-dag-tags.html) defined in your DAGs. Use tags to let you filter DAGs across all Deploym
```suggestion
- On Astro, the Astro UI renders [Airflow tags](https://airflow.apache.org/docs/apache-airflow/stable/howto/add-dag-tags.html) defined in your DAGs. Use tags to filter DAGs across all Deployments from a single screen.
```

2024-03-20 13:50 UTC, TJaniF commented on astro/astro-dags-overview.md
> +On Astro, in addition to the Airflow UI, you have access to the **DAGs** page. From here, you can manage DAG and task runs for any Deployment in your Workspace. See [View logs](view-logs.md) [Manage
```suggestion
On Astro, in addition to the Airflow UI, you have access to the **DAGs** page. From here, you can manage DAG and task runs for any Deployment in your Workspace. See [View logs](view-logs.md) and [Manage DAG runs](manage-dags.md) for more information.
```

2024-04-05 12:37 UTC, jwitz commented on astro/dags-overview.md
> +Astro includes additional features for alerting on specific DAG status, such as Astro alerts. There are some circumstances where Astronomer recommends configuring Astro alerts instead of Airflow SLAs
```suggestion
Astro includes additional features for alerting on specific DAG status, such as Astro alerts. There are some circumstances where Astronomer recommends configuring Astro alerts instead of Airflow SLAs or failure notifications. See [When to use Airflow or Astro alerts for your pipelines on Astro](best-practices/airflow-vs-astro-alerts.md).
```

2024-04-05 20:13 UTC, lzdanski reviewed
Close! I really like this structure and it makes so much more sense with the new organization.

2024-04-05 20:13 UTC, lzdanski commented on astro/manage-dags.md
> +As a data engineer or data
```suggestion
As a data engineer or data scientist, you might need to view details about your DAGs' performance, including viewing the task logs, manually marking DAGs as `succeeded` or `failed`, or retrying DAGs.
```

2024-04-09 21:17 UTC, lzdanski reviewed
There's a conflict to fix and a small nitpick but it's looking 99% done to me!

2024-04-09 21:17 UTC, lzdanski commented on astro/dags-overview.md
> +To develop and run DAGs on Astronomer products, they must belong to an Astro project. An _Astro project_ contains all files required to run your DAGs both locally and on Astronomer. In addition to DA
```suggestion
To develop and run DAGs on Astronomer products, your DAGs must belong to an Astro project. An _Astro project_ contains all files required to run your DAGs both locally and on Astronomer. In addition to DAG files, an Astro project includes dependencies, your Astro Runtime version, and any other files your workers need access to when you run tasks.
```
pronoun/antecedent nitpick

2024-05-28 14:44 UTC, paolaperaza requested changes
Nice job here @lzdanski + @jwitz ! Sorry for the delay in reviewing 🙈 I left a few comments, some of them a tiny bit structural but nothing major. The IA changes LGTM. 

Could you take another cut at it and I'll review again (faster this time)?

2024-05-29 08:58 UTC, jwitz commented on astro/dags-overview.md
> +Astro includes several features that enhance the Airflow development experience, from DAG creation to testing. Use this documentation to learn about all of the key differences between development on
Rather than include that info here, I would instead link to this doc from our migration guides. It's more likely that a user will find this doc on their migration journey if it's linked from the migration documentation

2024-05-29 09:00 UTC, jwitz commented on astro/dags-overview.md
> +Astro includes several features that enhance the Airflow development experience, from DAG creation to testing. Use this documentation to learn about all of the key differences between development on
I'm also not loving the second sentence, which makes it sound like a compliance burden to switch over to Astro development. I'm gonna try rewriting it to frame the migration experience more positively.

2024-05-29 09:41 UTC, jwitz commented on astro/dags-overview.md
> +- **Local Airflow environment**: You can run DAGs on your local machine using the Astro CLI. This development method is most useful if you need to quickly iterate and test changes, such as when fixin
Ah you know what, the Airflow UI doesn't need an internet connection per se but you DO need the internet to download the Runtime image for the first time.

2024-05-29 09:42 UTC, jwitz commented on astro/dags-overview.md
> +- **Deployment**: When you deploy your DAGs to Astro, they run on a managed Deployment. Use Deployments to run production code, or create a development Deployment to test changes over a longer period
This is more about where the DAGs run, rather than the act of deploying itself, hence the OG title

2024-05-29 09:52 UTC, jwitz commented on astro/dags-overview.md
> +## DAG feature integrations
Eh I disagree that these aren't integrations - I intentionally grouped features that exist on Airflow, but that we enhance in Astro. But not all of these are DAG-specific, so I changed that a bit

2024-05-29 09:58 UTC, jwitz commented on astro/dags-overview.md
> +- Astro has built-in infrastructure to run the KubernetesPodOperator and Kubernetes executor, such as default Pod limits and requests. Resource limits and requests are set by default on Astro Deploym
Is the fact that Astro runs on Kubernetes the reason we are much more reliably running k8s-based tasks?

2024-05-29 10:40 UTC, jwitz commented
@paolaperaza Ready for final review I think!

2024-06-03 14:06 UTC, paolaperaza approved these changes
A few final comments here @jwitz! I won't block merging this PR as I know it's been hanging and a little time sensitive at this point, but take a look and see if you can squeeze in my feedback

2024-06-03 14:06 UTC, paolaperaza commented on astro/dags-overview.md
> +Astro includes additional features, such as Astro alerts, for alerting on specific DAG statuses. There are some circumstances where Astronomer recommends configuring Astro alerts instead of Airflow S
```suggestion
Astro supports a set of alerting features that in many cases replace Airflow SLAs or failure notifications that are supported in the open source project and that you would otherwise configure. There are some circumstances where Astronomer recommends configuring Astro alerts instead of Airflow SLAs or failure notifications because it can simplify your DAG code and make it easier to manage alerts across multiple DAGs. See [When to use Airflow or Astro alerts for your pipelines on Astro](best-practices/airflow-vs-astro-alerts.md).
```

You can potentially find better wording here but I would add a half sentence that explicitly states that this might affect how you write your DAGs. I.e. If you use Astro alerts, you can likely DELETE a bunch of code and make your DAGs easier to read. We kind of allude to that but let's connect the dots for the reader more directly

2024-06-03 14:06 UTC, paolaperaza commented on astro/dags-overview.md
> +Although Astronomer's open source packages are not built into Astro, Astronomer recommends implementing them when possible to simplify your Airflow pipelines. Tools like the Astro SDK include prebuil
This is confusing at first -- what open source packages are we talking about? I would add a half sentence introduction to the fact that Astro has these (which I guess is just 2) and name them.

Would also consider saying "See this section for more" maybe just to make it clear

2024-06-03 15:23 UTC, jwitz commented on astro/dags-overview.md
> +Although Astronomer's open source packages are not built into Astro, Astronomer recommends implementing them when possible to simplify your Airflow pipelines. Tools like the Astro SDK include prebuil
```suggestion
In addition to its commercial products, Astronomer maintains several open source packages that enhance Apache Airflow. Although Astronomer's open source packages are not built into Astro, Astronomer recommends implementing them when possible to simplify your Airflow pipelines. Tools like the Astro SDK include prebuilt operators that eliminate boiler plate code from your Airflow DAGs.
```

2024-06-03 15:25 UTC, jwitz commented on astro/dags-overview.md
> +Whether you're building your project locally or deploying to Astro, you can run unit tests with the Astro CLI to ensure that your code meets basic standards before you run your DAGs. See [Test your D
```suggestion
Whether you're building your project locally or deploying to Astro, you can run unit tests with the Astro CLI to ensure that your code meets basic standards before you run your DAGs. The Astro CLI includes a default set of unit tests which you can run alongside your own tests in a single testing sequence. See [Test your DAGs](https://docs.astronomer.io/astro/cli/test-your-astro-project-locally) for more information.
```

2024-06-03 15:26 UTC, jwitz commented on astro/dags-overview.md
> +On Astro, you have access to the **DAGs** page in addition to the Airflow UI. From here, you can manage DAG and task runs for any Deployment in your Workspace. See [View logs](view-logs.md) [Manage D
```suggestion
In the Astro UI, you have access to the **DAGs** page in addition to the Airflow UI. From here, you can manage DAG and task runs for any Deployment in your Workspace. See [View logs](view-logs.md) [Manage DAG runs](manage-dags.md) for more information.

Astronomer recommends using the UI that best fits the need your team. If you prefer managing your DAGs from a single place and find the way that the way the Astro page is designed helpful, you don't need to use the Airflow UI. If you're a longtime user of Apache Airflow, you might feel more comfortable in the Airflow UI and don't need to use the Astro UI.
```

2024-06-03 15:27 UTC, jwitz commented on astro/dags-overview.md
> +In the Astro UI, you have access to the **DAGs** page in addition to the Airflow UI. From here, you can manage DAG and task runs for any Deployment in your Workspace. See [View logs](view-logs.md) [M
```suggestion
In the Astro UI, you have access to the **DAGs** page in addition to the Airflow UI. From here, you can manage DAG and task runs for any Deployment in your Workspace. 
```

2024-06-03 15:29 UTC, jwitz commented on astro/dags-overview.md
> +## Airflow feature integrations
```suggestion
## Airflow feature enhancements
```

2024-06-03 15:29 UTC, merged