[2.9 updates] New XCom backend content
astronomer/docs pull request #3566
Opened 2024-03-27 13:25 UTC by TJaniF

2024-04-02 21:11 UTC, kentdanas approved these changes
Oof sorry, realized I had made comments last week and then not submitted them 🤦‍♀️  This looks good! Some minor comments, but otherwise good to move on to copy editing.

2024-04-03 10:03 UTC, TJaniF reviewed
Thank you @kentdanas ! 

@jwitz and @lzdanski ready for you :)

2024-04-04 16:55 UTC, jwitz requested changes
One question about the naming of the object store xcom backend, otherwise LGTM!

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +Airflow [XComs](airflow-passing-data-between-tasks.md) allow you to pass data between tasks. By default, Airflow uses the [metadata database](airflow-database.md) to store XComs, which works well for
```suggestion
Airflow [XComs](airflow-passing-data-between-tasks.md) allow you to pass data between tasks. By default, Airflow uses the [metadata database](airflow-database.md) to store XComs, which works well for local development but has limited performance. If you configure a custom XCom backend, you can define where and how Airflow stores XComs, as well as customize serialization and deserialization methods.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +- Why you might want to use a custom XCom backend.
```suggestion
- When you should use a custom XCom backend.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +- Saving XComs in multiple locations simultaneously.
```suggestion
- You need more storage space for XComs than the Airflow metadata database can offer.
- You're running a production environment where you require custom retention, deletion, and backup policies for XComs.
- You want to access XComs without accessing the metadata database.
- You want to restrict types of allowed XCom values.
- You want to save XComs in multiple locations simultaneously.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +Common reasons to use a custom XCom backend include:
Do we recommend a custom backend for all prod workflows? It might be nice to have a single "hero" reason before this list even starts.

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +It is also possible to use custom XCom backends to define custom serialization and deserialization methods for XComs if adding a serialization method to a class or registering a custom serializer is
```suggestion
You can also use custom XCom backends to define custom serialization and deserialization methods for XComs if you need to add a serialization method to a class, or if registering a custom serializer is not feasible. See [Custom serialization and deserialization](#custom-serialization-and-deserialization) for more information.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +Additionally, some provider packages offer custom XCom backends that you can use out of the box, for example the [Snowpark provider](airflow-snowpark.md) which contains a custom XCom backend for Snow
```suggestion
Additionally, some provider packages offer custom XCom backends that you can use out of the box. For example, the [Snowpark provider](airflow-snowpark.md) contains a custom XCom backend for Snowflake.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +- **Custom XCom backend class**: Use this method when you want to further customize how XComs are stored, for example simultaneously storing XComs in two different locations.
```suggestion
- **Custom XCom backend class**: Use this method when you want to further customize how XComs are stored, for example to simultaneously store XComs in two different locations.
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +Airflow 2.9+ added the possibility to create a custom XCom backend using the Object Storage feature. Object Storage custom XCom backends are part of the [Common IO](https://registry.astronomer.io/pro
```suggestion
Airflow 2.9+ added the possibility to create a custom XCom backend using object storage. The Object Storage XCom Backend is part of the [Common IO](https://registry.astronomer.io/providers/apache-airflow-providers-common-io/versions/latest) provider and can be defined using the following environment variables:
```

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +- **Object Storage custom XCom backend**: Use this method to create a custom XCom backend when you want to store XComs in a cloud-based object storage service like AWS S3, GCP Cloud Storage, or Azure
Should we say "this option is recommended if you have no specific requirements beyond needing more XCom storage" or something similar?

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +### Use the Object Storage XCom backend
```suggestion
### Use the Object Storage XCom Backend
```
Is this the official name of the feature? Maybe there's another way to describe it, but that's the impression I'm getting

2024-04-04 16:55 UTC, jwitz commented on learn/airflow-custom-xcom-backends.md
> +In cases where you need to pass data objects through XCom that are not supported you have several options:
```suggestion
If you need to pass data objects through XCom that are not supported, you have several options:
```

2024-04-05 10:39 UTC, TJaniF reviewed
Thank you @jwitz ! :) 
Accepted all changes and hopefully answered your question

2024-04-05 10:39 UTC, TJaniF commented on learn/airflow-custom-xcom-backends.md
> +### Use the Object Storage XCom backend
Yes, https://airflow.apache.org/docs/apache-airflow-providers-common-io/stable/xcom_backend.html :)

2024-04-05 13:25 UTC, jwitz approved these changes
LGTM!

2024-04-05 13:25 UTC, jwitz commented on learn/custom-xcom-backend-strategies.md
> +- **Object Storage Custom XCom Backend**: Use this method to create a custom XCom backend when you want to store XComs in a cloud-based object storage service like AWS S3, GCP Cloud Storage, or Azure
```suggestion
- **Object Storage Custom XCom Backend**: Use this method to create a custom XCom backend when you want to store XComs in a cloud-based object storage service like AWS S3, GCP Cloud Storage, or Azure Blob Storage. This option is recommended if you need to store XComs in a single remote location, and the Object Storage Custom XCom Backend threshold and compression options meet your requirements.
```

2024-04-05 13:25 UTC, jwitz commented on learn/custom-xcom-backends-tutorial.md
> +The Object Storage Custom XCom Backend available in the [Common IO provider](https://airflow.apache.org/docs/apache-airflow-providers-common-io/stable/index.html) is the easiest way to store XComs in
```suggestion
The Object Storage XCom Backend available in the [Common IO provider](https://airflow.apache.org/docs/apache-airflow-providers-common-io/stable/index.html) is the easiest way to store XComs in a remote object storage solution.
```
Being picky here, but does this name make more sense? The "Custom" feels out of place, and I can't find anywhere where the complete name is used in docs

2024-04-05 13:32 UTC, TJaniF commented on learn/custom-xcom-backends-tutorial.md
> +The Object Storage Custom XCom Backend available in the [Common IO provider](https://airflow.apache.org/docs/apache-airflow-providers-common-io/stable/index.html) is the easiest way to store XComs in
That... is right 👀 I could have sworn... 😅

2024-06-11 19:48 UTC, merged