[2.9] Misc Learn updates
astronomer/docs pull request #3574
Opened 2024-03-28 13:25 UTC by TJaniF

PR to contain all learn updates that are not part of other PRs.

2024-03-29 18:44 UTC, kentdanas requested changes
@TJaniF these updates look good. Requesting changes just to follow up on a few of the structural things I brought up - let me know what you think on those.

2024-03-29 18:44 UTC, kentdanas commented on learn/airflow-decorators.md
> +- Task decorator (`@task.bash()`) which creates a [BashOperator](bashoperator.md#how-to-use-the-bash-decorator) task.
```suggestion
- Bash decorator (`@task.bash()`) which creates a [BashOperator](bashoperator.md#how-to-use-the-bash-decorator) task.
```
Let me know if this isn't accurate, but I think helpful to distinguish it from the Python "task decorator"

2024-03-29 18:44 UTC, kentdanas commented on learn/bashoperator.md
> +## How to use the bash decorator
I think one of Laura's comments on this doc when we did the audit was that it's kind of a long list of unrelated examples, and maybe we could improve that layout. Not that I want to re-do the doc as part of this update, but bringing that up here because my initial thought was maybe we should instead have two simple examples in tabs (one for traditional, one for decorator) in the "How to use the operator" section. That wouldn't necessarily leave room for your second example (which is cool! did not know you could do that), but I also wonder how common that use case is? Let me know what you think.

2024-03-29 18:44 UTC, kentdanas commented on learn/error-notifications-in-airflow.md
> +- `on_skipped_callback` : Invoked when a task is skipped. Added in Airflow 2.9, this callback only exists at the task level and is only invoked, when an AiflowSkipException is raised, not when a task
```suggestion
- `on_skipped_callback` : Invoked when a task is skipped. Added in Airflow 2.9, this callback only exists at the task level, and is only invoked when an AiflowSkipException is raised, not when a task is skipped due to other reasons like a trigger rule. See [Callback Types](http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html#callback-types).
```

2024-03-29 18:44 UTC, kentdanas commented on learn/dynamic-tasks.md
> +### Display custom map index names
While we're here, let's remove the references to Airflow 2.3. Over a year is long enough for it to be an established feature :)

2024-03-29 18:44 UTC, kentdanas commented on learn/dynamic-tasks.md
> +By default, the `map_index` shown in the Airflow UI for dynamically mapped tasks is their integer index, that corresponds to the order in which the tasks were created. In Airflow 2.9 and later, you c
I almost wonder if we should just make adding custom task names part of the default example earlier in the section, and not give it its own subsection. And then add a note that its optional, and if you don't include that code, you get the integer list? Mostly for the sake of not making the guide so long, and also because it seems like adding custom names will be a best practice we promote in most cases. WDYT?

2024-03-29 18:44 UTC, kentdanas commented on learn/airflow-datasets.md
> +### Updating a dataset
These updates look good. We should also probably add a note about these options to the scheduling guide? (ugh, I hate that that one will get even longer).

2024-04-02 13:10 UTC, TJaniF reviewed
Thank you @kentdanas ! I implemented all changes and added some comments to the restructuring ones :)

2024-04-02 20:17 UTC, kentdanas approved these changes
Looks good! I left a couple more comments, most of which are not related to your actual update (annoying of me, I know 😄 ). Otherwise good to get this copy edited.

2024-04-02 20:17 UTC, kentdanas commented on learn/airflow-datasets.md
> -Datasets and data-aware scheduling were made available in [Airflow 2.4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#airflow-2-4-0-2022-09-19). DAGs that access the same da
Also not related to the release (sorry) - but given we're going to be pushing datasets a lot, I think we should probably not have this guide in `Advanced`. Maybe under `DAGs`? `Basics` seems like a bit of a stretch, although it is covered in scheduling, so....:shrug: (also feel free to tell me "fine, but we need to take care of that in a different PR")

2024-04-02 20:17 UTC, kentdanas commented on learn/rerunning-dags.md
> -The `retry_delay` parameter (default: `timedelta(seconds=300)`) defines the time spent between retries. As of Airflow 2.6, you can set a maximum value for the retry delay in the core Airflow config `
Would it make sense to add the new max_retries (or whatever it's called?) param in here? Not sure where else it would go, or if we need to mention it at all

2024-04-02 20:17 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> -description: "Get to know Airflow scheduling concepts and different ways to schedule a DAG. Learn how timetables in Airflow 2.2 bring new flexibility to DAG scheduling."
oof a 2.2 reference 😅

2024-04-02 20:17 UTC, kentdanas commented on learn/scheduling-in-airflow.md
> -Datasets and data-driven DAG dependencies were introduced in Airflow 2.4. You can now make Airflow detect when a task in a DAG updates a data object. Using that awareness, other DAGs can be scheduled
Again, sorry for a comment not actually related to your update - but can we move this section above Timetables (because nobody actually uses those), and rename to "data-aware scheduling", which is what we use in the other guide and the Airflow docs? (I think we had at some point said maybe we would move away from "awareness" because it could be misinterpreted, but we didn't do that).

2024-04-03 10:41 UTC, TJaniF reviewed
Thank you @kentdanas ! :) 

@jwitz and @lzdanski I think this is the last one now ready for you. It started as "I just need a few minor changes" and then well... sorry! next time I'll try to split them out more even if I don't think a guide needs that big of a change 😅

2024-04-03 10:41 UTC, TJaniF commented on learn/airflow-components.md
> -description: "Understand the core components of Apache Airflow 2.0+. Review their functions and find out which components to run for specific use cases."
@kentdanas You said something about a 2.2 reference... that was not the oldest one 😅

2024-04-03 10:41 UTC, TJaniF commented on learn/airflow-datasets.md
> -Datasets and data-aware scheduling were made available in [Airflow 2.4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#airflow-2-4-0-2022-09-19). DAGs that access the same da
I am all for moving out of advanced, I could even see it in basics, I kinda think of Datasets as on the same level as task dependencies eventually! will move it to `Basics` and see what that looks like :) 

Eventually maybe the sidebar needs a bit of a different organization. I was thinking about that yesterday, I wonder how much the higher views on the BashOperator guide are caused by it being the first guide in the Basics list 🤔

2024-04-03 10:41 UTC, TJaniF commented on learn/rerunning-dags.md
> -The `retry_delay` parameter (default: `timedelta(seconds=300)`) defines the time spent between retries. As of Airflow 2.6, you can set a maximum value for the retry delay in the core Airflow config `
👍 It currently only exists in the new DAG parameter guide, will add it here as well :)

2024-04-03 10:41 UTC, TJaniF commented on learn/scheduling-in-airflow.md
> -Datasets and data-driven DAG dependencies were introduced in Airflow 2.4. You can now make Airflow detect when a task in a DAG updates a data object. Using that awareness, other DAGs can be scheduled
Haha, I almost moved it up when I was writing this section, I think then the title `DAG scheduling and timetables in Airflow` should also change. Maybe just to `Schedule DAGs in Airflow`? 

(I really want to rewrite this whole guide with a structure closer to what I used in the schedule webinar with a table of options at the start, but not in this PR)

2024-04-03 18:30 UTC, lzdanski reviewed
Did a first pass of the smaller changes, will follow up with the last 9 files.

2024-04-03 18:30 UTC, lzdanski commented on learn/dynamically-generating-dags.md
> +[Fine-tuning your scheduler](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/scheduler.html#fine-tuning-your-scheduler-performance) should help resolve potential p
```suggestion
[Fine-tuning your scheduler](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/scheduler.html#fine-tuning-your-scheduler-performance) helps resolve potential performance issues. There is no single right way to implement or scale dynamically generated DAGs, but the flexibility of Airflow means there are many ways to arrive at a solution that works for your organization.
```

2024-04-03 18:30 UTC, lzdanski commented on learn/dynamically-generating-dags.md
> +You can use [dynamic task mapping](dynamic-tasks.md) to write DAGs that dynamically generate parallel tasks at runtime. Dynamic task mapping is a first-class Airflow feature, and is suitable for many
```suggestion
You can use [dynamic task mapping](dynamic-tasks.md) to write DAGs that dynamically generate parallel tasks at runtime. Dynamic task mapping is a first-class Airflow feature, and suitable for many dynamic use cases. Due to its higher degree of support and stability, Astronomer recommends exploring dynamic task mapping for your use case before implementing the dynamic DAG generation methods described in this guide.
```

2024-04-03 18:30 UTC, lzdanski commented on learn/deferrable-operators.md
> +Deferrable operators leverage the Python [asyncio](https://docs.python.org/3/library/asyncio.html) library to efficiently run tasks waiting for an external resource to finish. This frees up your work
```suggestion
Deferrable operators leverage the Python [asyncio](https://docs.python.org/3/library/asyncio.html) library to efficiently run tasks waiting for an external resource to finish. This frees up your workers and allows you to use resources more effectively. In this guide, you'll review deferrable operator concepts and learn how to use deferrable operators in your DAGs.
```

2024-04-03 18:30 UTC, lzdanski commented on learn/airflow-isolated-environments.md
> +- Your task requires a **different version of Python** than your Airflow environment. Apache Airflow is compatible with and available in Python 3.8, 3.9, 3.10, 3.11 and 3.12. The Astro Runtime has [i
```suggestion
- Your task requires a **different version of Python** than your Airflow environment. Apache Airflow is compatible with and available in Python 3.8, 3.9, 3.10, 3.11, and 3.12. The Astro Runtime has [images](https://quay.io/repository/astronomer/astro-runtime?tab=tags) available for all supported Python versions, so you can run Airflow inside Docker in a reproducible environment. See [Prerequisites](https://airflow.apache.org/docs/apache-airflow/stable/installation/prerequisites.html) for more information.
```

2024-04-03 18:30 UTC, lzdanski commented on learn/airflow-components.md
> +- **[CeleryKubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/celery_kubernetes.html)**: Allows you to run both, a CeleryExecutor and a KubernetesExecut
```suggestion
- **[CeleryKubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/celery_kubernetes.html)**: Allows you to run both a CeleryExecutor and a KubernetesExecutor in the same Airflow instance. The `queue` parameter determines which executor that a specific task uses. You need to install both, the [Celery](https://registry.astronomer.io/providers/apache-airflow-providers-celery/versions/latest) and [CNCF Kubernetes](https://registry.astronomer.io/providers/apache-airflow-providers-cncf-kubernetes/versions/latest) providers to use this executor.
```

2024-04-03 19:23 UTC, lzdanski reviewed
Final round of the first pass!

2024-04-03 19:23 UTC, lzdanski commented on learn/rerunning-dags.md
> +The `retry_delay` parameter (default: `timedelta(seconds=300)`) defines the time spent between retries. You can set a maximum value for the retry delay in the core Airflow config `max_task_retry_dela
```suggestion
The `retry_delay` parameter (default: `timedelta(seconds=300)`) defines the time spent between retries. You can set a maximum value for the retry delay in the core Airflow config, `max_task_retry_delay` (`AIRFLOW__CORE__MAX_TASK_RETRY_DELAY`), which, by default, is set at 24 hours. Or, for individual tasks, you can set the maximum retry delay with the parameter, `max_retry_delay`.
```

2024-04-04 12:02 UTC, TJaniF reviewed
Thank you @lzdanski ! I accepted all suggestions :)

2024-04-04 18:44 UTC, lzdanski approved these changes
A couple small things but checked the files in preview where I made review comments!

2024-04-04 18:44 UTC, lzdanski commented on learn/airflow-datasets.md
> +
Something to note for a future edit - the final screenshot in line 394 doesn't have a border and does have a lot of white space. 
<img width="937" alt="Screenshot 2024-04-04 at 2 20 16 PM" src="https://github.com/astronomer/docs/assets/25642903/d6c9f376-3e23-491d-b704-a00927ab2bec">

2024-04-04 18:44 UTC, lzdanski commented on learn/dynamic-tasks.md
> +![Screenshot of the Airflow UI showing three dynamically mapped task instances created with the code snippets above.](/img/guides/dynamic-tasks_simple_example.png)
It looks like this image is good, but there are some in this doc that are very large and we have a way of adjusting their size. Here's an [example PR](https://github.com/astronomer/docs/pull/3471/files#diff-46845690b2bda32977484718718ed19b60ebe7e604287f2a4fb6fee663486b74R16)

2024-04-05 11:56 UTC, TJaniF reviewed
Thank you @lzdanski ! 
Those big screenshots were also outdated so I changed that section entirely and added a smaller screenshot and a gif :)

2024-04-08 14:29 UTC, merged