Astro deployment token docs
astronomer/docs pull request #3581
Opened 2024-03-29 17:09 UTC by lzdanski

Resolves #3580

2024-04-03 15:18 UTC, aliotta commented on astro/cli/astro-deployment-token-create.md
> +astro deployment token create
add --deployment-id flag here

2024-04-03 15:18 UTC, aliotta commented on astro/cli/astro-deployment-token-list.md
> +astro deployment token list
add --deployment-id flag here

2024-04-03 15:18 UTC, aliotta commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate <token-ID> [flags]
add --deployment-id flag here

2024-04-03 15:19 UTC, aliotta commented on astro/cli/astro-deployment-token-update.md
> +astro deployment token update
add --deployment-id flag here

2024-04-09 12:10 UTC, jwitz requested changes
It looks like one of the commands doesn't have the right options documented, but otherwise this is close!

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-list.md
> +| `DESCRIPTION` | (Optional) A description of the API Token.                           | String    |
```suggestion
| `DESCRIPTION` | The description of the API Token.                           | String    |
```
Column will always exist I assume

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-list.md
> +| `SCOPE`       | Whether the API Token is for Deployment, Workspace, or Organization. | String    |
```suggestion
| `SCOPE`       | Whether the API Token is scoped to a Deployment, Workspace, or Organization. | String    |
```

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-list.md
> +| `CEATED BY`   | The name of the person who created the token.                        | String    |
```suggestion
| `CEATED BY`   | The name of the user entity who created the token.                        | String    |
```
Could be an automated process

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token rotate --deployment-id=clukapi6r000008l58530cg8i [flags]
```suggestion
astro deployment token rotate --deployment-id=clukapi6r000008l58530cg8i --name "My token"
```

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate --deployment-id=<deployment-id> <token-ID> [flags]
This usage is inconsistent with the example below. How is the token ID specified, and is it required?

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-rotate.md
> +| `-c`,`--clean-output`           |    Print only the token as output. For use of the command in scripts.                                              | N/A |
```suggestion
| `-c`,`--clean-output`           |    Print only the token as output. Use when writing scripts that run the command.                                           | N/A |
```

2024-04-09 12:10 UTC, jwitz commented on astro/cli/astro-deployment-token-update.md
> +astro deployment token update --deployment-id=clukapi6r000008l58530cg8i
For whatever the eventual flags are, let's add a realistic example that configures a few different details about the token

2024-04-09 12:10 UTC, jwitz commented on astro/cli/release-notes.md
> +- **Stable versions**: {{CLI_VER_LATEST}}, {{CLI_VER_2}}, and {{CLI_VER_3}}. See [Astro CLI release and lifecycle policy](cli/release-lifecycle-policy.md) for more information about stable CLI versio
```suggestion
- **Stable versions**: {{CLI_VER_LATEST}}, {{CLI_VER_2}}, and {{CLI_VER_3}}. See [Astro CLI release and lifecycle policy](cli/release-lifecycle-policy.md) for more information about support for CLI versions.
```

2024-04-09 17:35 UTC, lzdanski commented on astro/cli/astro-deployment-token-create.md
> +astro deployment token create --deployment-id=<deployment-id>
Yes, `deployment-id` is required for all commands!

2024-04-09 17:38 UTC, lzdanski commented on astro/cli/astro-deployment-token-create.md
> +| `-e`,`--expiration`           |    Expiration of the token in days. If the flag isn't used the token won't have an expiration.                                                | Must be between 1 and
@aliotta - there's a typo in the CLI help string if this is the case. 

```
  -e, --expiration int       Expiration of the token in days. If the flag isn't used the token won't have an expiration. Must be between 1 and 3650 days.
```

2024-04-09 18:27 UTC, lzdanski commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate --deployment-id=<deployment-id> <token-ID> [flags]
@aliotta can you share an example? the help text isn't quite clear about the syntax

2024-04-09 21:13 UTC, aliotta commented on astro/cli/astro-deployment-token-create.md
> +astro deployment token create --deployment-id=<deployment-id>
yep can confirm it is required

2024-04-09 21:13 UTC, aliotta commented on astro/cli/astro-deployment-token-create.md
> +| `-e`,`--expiration`           |    Expiration of the token in days. If the flag isn't used the token won't have an expiration.                                                | Must be between 1 and
ah yeah good eyes will get a PR up for that

2024-04-09 21:15 UTC, aliotta commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate --deployment-id=<deployment-id> <token-ID> [flags]
roate -> rotate

token-ID is not required and should go before the --deployment-id flag

2024-04-09 21:15 UTC, aliotta commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate --deployment-id=<deployment-id> <token-ID> [flags]
example 

astro deployment token rotate MYTOKENID --deployment-id=DEPID

or

astro deployment token rotate --deployment-id=DEPID

2024-04-10 16:42 UTC, lzdanski commented on astro/cli/astro-deployment-token-rotate.md
> +astro deployment token roate --deployment-id=<deployment-id> <token-ID> [flags]
```suggestion
astro deployment token rotate <token-id> --deployment-id=<deployment-id>  [flags]
```

2024-04-11 14:55 UTC, aliotta commented on astro/cli/astro-deployment-token-update.md
> +|`--cicd-enforcement`           |    When enabled CI/CD Enforcement where deploys to deployment must use an API Key or Token. This essentially forces Deploys to happen through CI/CD.
all these option look incorrect
<img width="1241" alt="Screenshot 2024-04-11 at 10 06 13 AM" src="https://github.com/astronomer/docs/assets/8050013/02096b84-fa17-4594-af7f-9d614175ced7">

2024-04-11 14:56 UTC, aliotta commented on astro/cli/astro-deployment-token-update.md
> +astro deployment update --deployment-id=<deployment-id> [flags]
this is incorrect

2024-04-11 14:56 UTC, aliotta commented on astro/cli/astro-deployment-token-update.md
> +astro deployment update --deployment-id=<deployment-id> [flags]
astro deployment token update --deployment-id=<deployment-id>

2024-04-11 15:05 UTC, lzdanski commented on astro/cli/astro-deployment-token-update.md
> +astro deployment update --deployment-id=<deployment-id> [flags]
```suggestion
astro deployment token update --deployment-id=MOCK_DEP_ID
```

2024-04-11 16:14 UTC, jwitz approved these changes
Core reference LGTM, but I need to follow up on our language surrounding Deployment API tokens. I realized that we don't have any documentation about assigning Org/ Workspace API tokens to a Deployment, which would change some of the language here but also requires some core doc changes. Writing an issue for that now

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-rotate.md
> +Rotate an Astro [Deployment API Token](deployment-api-tokens.md)
```suggestion
Rotate an Astro [Deployment API Token](deployment-api-tokens.md).
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-update.md
> +Update an Astro [Deployment API Token](deployment-api-tokens.md)
```suggestion
Update an Astro [Deployment API Token](deployment-api-tokens.md).
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-delete.md
> +# delete a deployment token
```suggestion
# Delete a Deployment API token
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-list.md
> +List your Astro [Deployment API Token](deployment-api-tokens.md)
```suggestion
List all [API tokens](deployment-api-tokens.md) belonging to a Deployment.
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-list.md
> +To use your API token in an automated process, see [Authenticate an automation tool](automation-authentication.md).
```suggestion
To use an API token in an automated process, see [Authenticate an automation tool](automation-authentication.md).
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-delete.md
> +Delete a [Deployment API Token](deployment-api-tokens.md).
@aliotta Can you also use this command to remove Organization API tokens that have been assigned to a Deployment?

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-update.md
> +astro deployment token update TOKEN_ID --deployment-id=clukapi6r000008l58530cg8i
```suggestion
astro deployment token update <token-id> --deployment-id=clukapi6r000008l58530cg8i
```

2024-04-11 16:14 UTC, jwitz commented on astro/cli/astro-deployment-token-update.md
> +astro deployment token update --deployment-id=clukapi6r000008l58530cg8i -name=TOKEN_NAME
```suggestion
astro deployment token update --deployment-id=clukapi6r000008l58530cg8i --name="Token name"
```

2024-04-11 16:19 UTC, aliotta commented on astro/cli/astro-deployment-token-delete.md
> +Delete a [Deployment API Token](deployment-api-tokens.md).
no. I have a seperate PR that adds this functionality but it adds it as a separate command.

2024-04-11 16:20 UTC, aliotta approved these changes

2024-04-11 21:09 UTC, merged