Add custom templating to templating.md
astronomer/docs pull request #3592
Opened 2024-04-01 21:13 UTC by odaneau-astro

2024-04-01 21:15 UTC, fritz-astronomer approved these changes

2024-04-02 20:25 UTC, kentdanas requested changes
@odaneau-astro thanks for this addition, I think this is a helpful example. A couple requested changes on the formatting, let me know if you have questions on anything.

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +So far, we've detailed how to pass Jinja template syntax to Operators' templateable fields. But what if you need to template a field not listed in the Operator's `template_fields`?
```suggestion
If you need to template a field that is not listed in the operator's `template_fields`, you can either set the `template_fields` attribute on a task or create a custom operator.
```

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +There are two ways to work around this problem. Either set the template_fields attribute on a Task or create a custom Operator.
```suggestion
```

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +Here is how you would use each method to template the `cwd` field of the BashOperator.
```suggestion
The following example shows how to use each method to template the `cwd` field of the BashOperator.
```

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +1. Set the template_fields attribute of the task itself:
Rather than having numbered steps here, since this is showing two different methods, rather than sequential steps, can we show this information in two tabs? You can see an example of how to implement in the previous section where we have tabs for TaskFlow API and Traditional syntax examples.

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +   Once the Task is defined and assigned to a Python variable, you can reassign its template_fields. This allows jinja templating for any field not templated by default.
```suggestion
   Once the task is defined and assigned to a Python variable, you can reassign its template_fields. This allows Jinja templating for any field that is not templated by default. 
```

2024-04-02 20:25 UTC, kentdanas commented on learn/templating.md
> +templating_dag()
This should be indented to match the rest of the code snippet. Because it isn't, it's treating this line as regular text, and starting a new code block for the following section. (you can check the deploy preview link on the PR to make sure it's rendering properly)

2024-04-03 14:52 UTC, kentdanas commented on learn/templating.md
> +Prefer this method if you need to template a field repeatedly.
```suggestion
This method is preferred if you need to template a field repeatedly.
```

2024-04-03 14:53 UTC, kentdanas approved these changes

2024-04-03 14:55 UTC, merged