Software 0.34.1 release notes
astronomer/docs pull request #3601
Opened 2024-04-03 17:17 UTC by jwitz

2024-04-04 16:55 UTC, jwitz commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software. (tentative for 0.34.1)
```suggestion
- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software.
```

2024-04-04 16:56 UTC, jwitz commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software. (tentative for 0.34.1)
@rishkarajgi Did this make it in?

2024-04-04 16:56 UTC, jwitz commented on software/release-notes.md
> +- Fixed an issue where the Airflow Helm chart could override scheduler affinities set at a global level (tentative for 0.34.1)
@rishkarajgi Did the second bug fix make it in?

2024-04-05 14:24 UTC, rishkarajgi commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software. (tentative for 0.34.1)
@jwitz this one did not make it, we need to omit this

2024-04-05 14:50 UTC, rishkarajgi commented on software/release-notes.md
> +- Fixed an issue where the Airflow Helm chart could override scheduler affinities set at a global level (tentative for 0.34.1)
Second bug fix did not make it

2024-04-05 15:20 UTC, rishkarajgi approved these changes
lgtm

2024-04-05 18:38 UTC, danielhoherd commented on software/release-notes.md
> +- You can now specify an image pull secret for the `privateCaCertsAddToHost.certCopier` image so that you can pull the image from a private registry.
```suggestion
- You can now specify an image pull secret for the `privateCaCertsAddToHost.certCopier` image so that it can pull the image from a private registry.
```

2024-04-05 18:41 UTC, danielhoherd commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software.
@Simpcyclassy @rishkarajgi did we implement this?

2024-04-05 18:46 UTC, danielhoherd requested changes
LGTM except the inclusion of one feature that I think we may not have done. I'd like to hear back from @rishkarajgi or @Simpcyclassy about it before we merge these docs.

2024-04-05 19:27 UTC, Simpcyclassy commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software.
No, this was not included in this release.

2024-04-05 19:30 UTC, Simpcyclassy commented on api/fern/fern.config.json
>  }
Do you need to add a new line after here?

2024-04-08 10:20 UTC, jwitz commented on software/release-notes.md
> +- The Software UI now includes a notification system so that Astronomer support can post messages related to specific versions of Astronomer Software.
```suggestion
```

2024-04-08 19:56 UTC, lzdanski reviewed
changed date for release

2024-04-08 19:56 UTC, lzdanski commented on software_versioned_docs/version-0.32/release-notes.md
> +Release date: April 5, 2024
```suggestion
Release date: April 8, 2024
```

2024-04-08 19:56 UTC, lzdanski commented on software_versioned_docs/version-0.33/release-notes.md
> +Release date: April 5, 2024
```suggestion
Release date: April 8, 2024
```

2024-04-08 20:10 UTC, lzdanski commented on software_versioned_docs/version-0.30/release-notes.md
> +Release date: April 5, 2024
```suggestion
Release date: April 8, 2024
```

2024-04-08 20:15 UTC, lzdanski commented on software/release-notes.md
> +Release date: April 5, 2024
```suggestion
Release date: April 8, 2024
```

2024-04-08 20:28 UTC, danielhoherd commented on software_versioned_docs/version-0.33/release-notes.md
> +## 0.34.1
Why is 0.34.1 in the version-0.33/release-notes.md file ?

2024-04-08 20:32 UTC, danielhoherd approved these changes
Content LGTM.

2024-04-08 21:40 UTC, merged