Lean cleanup DAG tutorial
astronomer/docs pull request #3641
Opened 2024-04-15 13:53 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/3639

2024-04-15 13:54 UTC, jwitz commented on code-samples/dags/cleanup-dag-tutorial/db_cleanup.py
> +astronomer_db_cleanup_dag()
```suggestion
astronomer_db_cleanup_dag()

```

2024-04-15 13:55 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +- [List more specifics]
Any other side effects we should mention here?

2024-04-15 13:55 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +- Only trigger a database cleanup if you need to. If your Airflow scheduler is running normally, there's no need to clean the DB. On Astro, you will receive alerts when specific tables contain enough
More usage warnings here would be great, these are just the ones I can think of off the top of my head

2024-04-15 23:54 UTC, kentdanas reviewed
@jwitz this is a great start, left some initial comments.

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +In addition to storing configuration about your Airflow environment, the Airflow [metadata database](https://docs.astronomer.io/learn/airflow-database) stores data about past and present task runs. T
```suggestion
In addition to storing configuration about your Airflow environment, the Airflow [metadata database](https://docs.astronomer.io/learn/airflow-database) stores data about past and present task runs. Airflow never automatically removes metadata, so the longer you use it, the more task run data is stored in your metadata DB. Over a long enough time, this can result in a bloated metadata DB, which can affect performance across your Airflow environment.
```

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +Read this section carefully before implementing this DAG in any production Airflow environments.
I almost wonder if we should move this up into the intro and update to "Read the Warnings section....", in case anybody happens to scroll over it (not that they couldn't do that anyway, but maybe this would help)

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +- The DAG will fail if it runs for longer than five minutes, which can happen when you have an exceptionally large amount of data to delete. If this happens to you, use the DAG's params to reduce the
Is this true generally, or only on Astro? I think Felix said the latter, but we should clarify.

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +    It includes one task, `clean_db`, that runs the `airflow db clean` with the params you specify at Runtime. The params let you specify:
```suggestion
    It includes one task, `clean_db`, that runs `airflow db clean` with the params you specify at Runtime. The params let you specify:
```

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +    - What age of data to delete. Any data that was created before the specified time will be deleted.
I think in all of these bullets worth stating what the default is, in case people don't read the DAG code

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +    - Whether to run the cleanup as a dry run, meaning that no data is deleted.
```suggestion
    - Whether to run the cleanup as a dry run, meaning that no data is deleted. The DAG will return the SQL that would be executed based on other parameters you have specified.
```

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +## Step 2: Run your DAG
It seems like this would be more useful if the step was to deploy the DAG to astro and run as needed? Or if we want to explicitly tell people to run locally so they can "practice" with it, maybe we should state that.

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +To keep your Airflow environment running at optimal performance, you can clean the metadata DB using the `airflow db clean` command. This tutorial walks you through how to implement a cleanup DAG in
```suggestion
To keep your Airflow environment running at optimal performance, you can clean the metadata DB using the Airflow CLI `airflow db clean` command. This command was created as a way to safely clean up your metadata DB; you should never modify the Airflow metadata DB directly, as this can cause dependency issues and corrupt your Airflow instance. This tutorial walks you through how to implement a cleanup DAG in Airflow so that you can clean your database using the command directly from the Airflow UI.
```
Feel free to adjust where we put this, but I think the extra context is helpful.

2024-04-15 23:54 UTC, kentdanas commented on learn/cleanup-dag-tutorial.md
> +## Step 1: Create your DAG
Somewhere (in this section? the intro?) we should add a note that this DAG has been optimized for Astro users, and while it's still relevant for OSS users, they may want to review and change some of the defaults.

2024-04-16 10:02 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +When a table in the metadata DB is larger than 50GB, you might start to experience degraded scheduler performance. This can result in:
Is there a more general figure that we could use here for all Airflow environments? This is when the alert triggers on Astro, but I imagine it can start to get slower a lot quicker for other enviros. What figure can OSS users check to see if a table is getting too big?

2024-04-16 10:15 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +## Step 1: Create your DAG
Is it though? By default it deletes the data in all tables older than 90 days, which doesn't seem too Astro specific to me, but I might be missing some context here

2024-04-16 10:26 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +Read this section carefully before implementing this DAG in any production Airflow environments.
I moved this slightly higher, but not all the way to the beginning so as to avoid https://en.wikipedia.org/wiki/Banner_blindness

2024-04-16 10:27 UTC, jwitz commented
Thank you @kentdanas! Agreed with all of your comments, just left one additional question

2024-04-16 14:56 UTC, jedcunningham commented on learn/cleanup-dag-tutorial.md
> +- `task_fail`
xcom, rendered_task_instance_fields, more so than task_reschedule and task_fail. I don't think dags is a risk either.

The order feels a bit odd to me also.

2024-04-16 14:56 UTC, jedcunningham commented on learn/cleanup-dag-tutorial.md
> +To keep your Airflow environment running at optimal performance, you can clean the metadata DB using the Airflow CLI `airflow db clean` command. This command was created as a way to safely clean up y
```suggestion
To keep your Airflow environment running at optimal performance, you can clean the metadata DB using the Airflow CLI `airflow db clean` command. This command was created as a way to safely clean up your metadata DB without querying it directly. This tutorial walks you through how to implement a cleanup DAG in Airflow so that you can clean your database using the command directly from the Airflow UI.
```

"querying" vs "modifying", and I'd drop the reason since FKs in theory should avoid corruption.

2024-04-16 14:56 UTC, jedcunningham commented on learn/cleanup-dag-tutorial.md
> +- Only trigger a database cleanup if you need to. If your Airflow scheduler is running normally, there's no need to clean the DB. On Astro, you will receive alerts when specific tables contain enough
I'm not a fan of saying "no need unless there is pain". It is good hygiene and ideally folks do it proactively.

2024-04-29 15:20 UTC, rawwar commented on learn/cleanup-dag-tutorial.md
> +- [List more specifics]
I can think of two web server issues:
1. Gunicorn timeout when a query takes a longer time to complete. 
2. Slower UI loading

2024-04-29 17:55 UTC, collinmcnulty requested changes
I like this overall, and as long as the other

2024-04-29 17:55 UTC, collinmcnulty commented on learn/cleanup-dag-tutorial.md
> +## Step 1: Create your DAG
I think this is the answer to your question above about 50 GB. That's difficult for us to know in other environments, so just state this is for Astro

2024-04-29 17:55 UTC, collinmcnulty commented on learn/cleanup-dag-tutorial.md
> +- On Astro, the DAG will fail if it runs for longer than five minutes, which can happen if you have an exceptionally large amount of data to delete. If this happens, use the DAG's params to reduce th
Reducing the number of tables won't help. The timeout is per table.

2024-04-29 17:55 UTC, collinmcnulty commented on learn/cleanup-dag-tutorial.md
> +- Delete older data before newer data. The older the deleted data, the less likely it is to affect your currently running DAGs.
It's not possible to delete new data before old data with this DAG

2024-04-29 17:55 UTC, collinmcnulty commented on learn/cleanup-dag-tutorial.md
> +- An Astro project
An Airflow project, nothing too Astro specific here

2024-04-29 18:56 UTC, josh-fell commented on code-samples/dags/cleanup-dag-tutorial/db_cleanup.py
> +    BashOperator(
Might be cool to see the new `@task.bash` TaskFlow decorator too (if you can toggle examples of how to implement the code like what's done elsewhere).

Something like (untested of course):
```py
@task.bash
def cleanup_db(params) -> str:
    bash_command = (
        "airflow db clean --clean-before-timestamp {{ params.clean_before_timestamp }} "
        "--skip-archive --verbose --yes"
    )

    if params.dry_run:
        bash_command += "--dry-run "

    if params.tables:
        bash_command += "--tables {{ params.tables|join(', ') }}"

    return bash_command
```

2024-04-29 19:04 UTC, kentdanas commented on code-samples/dags/cleanup-dag-tutorial/db_cleanup.py
> +    BashOperator(
As much as I am pro-@task.bash decorator, I don't think we need to present multiple ways of authoring the same DAG here - if there's a notable benefit to using the decorator for this use case specifically, let's just switch to that. We do that in our other guides where the purpose is "how to write a DAG that does XYZ" to show different potential styles - but the purpose here isn't how to write the DAG, it's "how to clean up your database", so I don't see a lot of benefit for showing different style options.

2024-04-29 21:14 UTC, RNHTTR commented on code-samples/dags/cleanup-dag-tutorial/db_cleanup.py
> +    BashOperator(
IMO the notable benefit is pushing people toward Taskflow. My 2 cents is that if it's between classic and task decorated, we should go with task decorated

2024-04-30 07:41 UTC, feluelle commented on code-samples/dags/cleanup-dag-tutorial/db_cleanup.py
> +    BashOperator(
Yeah, and also likely a lot of people would have to rewrite it to match their airflow version if we use the decorator. Don't get me wrong, I like the decorator syntax much more, but I think it would be more user-friendly to give them a DAG that they could directly run.

2024-04-30 07:42 UTC, feluelle commented on learn/cleanup-dag-tutorial.md
> +- On Astro, the DAG will fail if it runs for longer than five minutes, which can happen if you have an exceptionally large amount of data to delete. If this happens, use the DAG's params to reduce th
That is correct. The timeout is per query, and since the cleanup task runs a (cleanup) query per table it won't help.

2024-04-30 07:48 UTC, feluelle commented on learn/cleanup-dag-tutorial.md
> +- Delete older data before newer data. The older the deleted data, the less likely it is to affect your currently running DAGs.
I think what we want to say is to start by deleting very old records. For example, start with older than 180 days, before deleting data older than 90 days.

2024-05-06 13:34 UTC, collinmcnulty commented on learn/cleanup-dag-tutorial.md
> +- Delete older data before newer data. The older the deleted data, the less likely it is to affect your currently running DAGs.
I would state that directly then. This sentence strongly implies that it's possible to end up with a hole in your data.

2024-05-07 16:29 UTC, RNHTTR submitted a review, later dismissed
Instead of using a BashOperator, could we use [run_cleanup](https://github.com/apache/airflow/blob/main/airflow/utils/db_cleanup.py#L393)? We could use a mapped operator that runs smaller cleanup tasks in parallel instead of trying to clean up everything beyond 90 days, which could cause a statement timeout

2024-05-07 18:15 UTC, feluelle commented
@RNHTTR we could do the same with BashOperator. It doesn't have to be a python task to use task mapping.

Users could still run into statement timeout issues when using chunking mechanism, because they don't know what chunk size to use.

If we want to do it more intelligently, we would have to do table lookups first, which we also should only do with care. We have https://github.com/astronomer/astro/issues/13887 to do that automatically. So I think we should keep this tutorial DAG rather simple.

2024-05-10 23:22 UTC, kaxil commented
> @RNHTTR we could do the same with BashOperator. It doesn't have to be a python task to use task mapping.
> 
> Users could still run into statement timeout issues when using chunking mechanism, because they don't know what chunk size to use.
> 
> If we want to do it more intelligently, we would have to do table lookups first, which we also should only do with care. We have [astronomer/astro#13887](https://github.com/astronomer/astro/issues/13887) to do that automatically. So I think we should keep this tutorial DAG rather simple.

Agreed. Also the functions under utils might change in Airflow. Can we merge this PR, please?

2024-05-10 23:24 UTC, kaxil commented
I would like us to publish something on the website asap. We can always improve on it once it is there. Don't let the perfect be the enemy of the good :)

2024-05-15 10:13 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +- An Astro project
Our standard for tutorials is to say "Astro project", since we instruct users to run the DAG with the Astro CLI and you can't use an OSS Airflow project for that.

2024-05-15 14:32 UTC, collinmcnulty approved these changes

2024-05-15 15:28 UTC, kentdanas approved these changes

2024-05-15 15:48 UTC, kaxil approved these changes

2024-05-15 21:31 UTC, lzdanski requested changes
Some clarity recommendations and typo fixes

2024-05-15 21:31 UTC, lzdanski commented on learn/cleanup-dag-tutorial.md
> +8. Check that the `airflow db cleanup` command completed successfully. Note that you created a new Astro project, the run will not show much data to be deleted.
```suggestion
8. Check that the `airflow db cleanup` command completed successfully. Note that if you created a new Astro project, the run will not show much data to be deleted. 
```

2024-05-15 21:31 UTC, lzdanski commented on learn/cleanup-dag-tutorial.md
> +In this step, you'll run the DAG in a local Airflow environment to practice the workflow for cleaning metadata DB data. In reality, you would first deploy this DAG to a production environment, such a
```suggestion
In this step, run the DAG in a local Airflow environment to practice the workflow for cleaning metadata DB data. When using this process for a production environment, you would first deploy this DAG to a production environment, such as an Astro Deployment, then run the DAG only when your metadata DB is getting full.
```

2024-05-16 09:21 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +- When specifying the `clean_before_timestamp` value, use as late of a data as possible. The older the deleted data, the less likely it is to affect your currently running DAGs.
Typo on "data" here, but I think this should still be the "latest date". If you select a recent date, it will delete all data before the recent date, when we specifically want users only to delete later data if possible.

2024-05-16 09:22 UTC, jwitz commented on learn/cleanup-dag-tutorial.md
> +- On Astro, the DAG will fail if it runs for longer than five minutes, which can happen if you have an exceptionally large amount of data to delete. If this happens, use the DAG's params to reduce th
Same here, a more recent time will cause more data to be deleted.

2024-05-16 13:02 UTC, lzdanski commented on learn/cleanup-dag-tutorial.md
> +- When specifying the `clean_before_timestamp` value, use as late of a data as possible. The older the deleted data, the less likely it is to affect your currently running DAGs.
Wouldn't that be the "oldest date" then? When I read "latest date" to me that translates to "most recent," not the "most distant in the past"?

2024-05-16 13:05 UTC, lzdanski reviewed
I think that "latest" isn't specific enough for this context - we should use "older" and "newer" or "More and less recent" because it appears "latest" has two very different interpretations among us!

2024-05-16 13:05 UTC, lzdanski commented on learn/cleanup-dag-tutorial.md
> +- When specifying the `clean_before_timestamp` value, use as late of a date as possible. The older the deleted data, the less likely it is to affect your currently running DAGs.
```suggestion
- When specifying the `clean_before_timestamp` value, use as old a date as possible. The older the deleted data, the less likely it is to affect your currently running DAGs.
```

2024-05-16 13:05 UTC, lzdanski approved these changes
One final wording tweak but LGTM

2024-05-16 15:37 UTC, merged