Add diagrams for GitHub Integration
astronomer/docs pull request #3670
Opened 2024-04-23 16:43 UTC by lzdanski

2024-04-24 06:39 UTC, jwitz requested changes
I am so excited for these to get published! Just a few comments around readability and one labeled component

2024-04-24 06:39 UTC, jwitz commented on static/img/docs/github-integration-map.png
Having "Mapped" in the description here throws me off a bit, the repo isn't mapped so much as the branches are, and their mapping is already communicated by the arrows.

Also same deal here with the boxes, they're hard to see against the black backdrop

2024-04-24 06:39 UTC, jwitz commented on static/img/docs/github-integration-deploy.png
Really nice communication of the feature, I love how it doesn't assume any prior knowledge about CI/CD. Only feedback would be to make the boxes a little more visible, maybe with a thin white border or by making the boxes themselves lighter?

2024-04-24 06:39 UTC, jwitz commented on astro/deploy-github-integration.md
> +<img src={require("../static/img/docs/github-integration-map.png").default} alt="A diagram showing how branches in a GitHub repository directly correlate to specific Deployments in an Astro Workspace
Might need to play around with the dimensions in the style, currently the images are appearing v tiny. 
![Screenshot 2024-04-24 at 7 38 16 AM](https://github.com/astronomer/docs/assets/74574233/41c77295-54e9-4ed8-93f3-19250c946897)

2024-04-25 17:28 UTC, lzdanski commented on astro/deploy-github-integration.md
> +<img src={require("../static/img/docs/github-integration-deploy.png").default} alt="A diagram showing how when an engineer commits code to a branch, then after merging the branch to GitHub, the Astro
Tried experimenting with different size browser windows and it looks really readable at different sizes? Think I need to add the max dimensions?
<img width="1249" alt="Screenshot 2024-04-25 at 1 27 54 PM" src="https://github.com/astronomer/docs/assets/25642903/ade0d8ec-7b31-4907-a0ef-d242a25c71eb">

<img width="504" alt="Screenshot 2024-04-25 at 1 28 27 PM" src="https://github.com/astronomer/docs/assets/25642903/b1b19b86-5a7c-4b79-adb4-6164cedfe83f">

2024-04-26 11:32 UTC, jwitz approved these changes
New sizes look GREAT! LGTM!

2024-04-26 11:32 UTC, merged