1.26 CLI Release
astronomer/docs pull request #3671
Opened 2024-04-23 16:52 UTC by lzdanski

* Add release notes
* Add docs for new CLI commands that allow for scoping Organization/Workspace API Tokens to specific Deployments/Workspaces Related - https://github.com/astronomer/astro-cli/pull/1611

2024-04-23 21:13 UTC, aliotta approved these changes

2024-04-24 13:27 UTC, jwitz requested changes
This is coming together, structure of the files looks good! Some general notes for the second pass:

- Because the commands are so similar in functionality, I only edited one of the docs. I trust you to apply the same edits similarly to the other docs.
- I found a few copy-paste mishaps, please check the other docs for similar inconsistencies
- It would be good to have more realistic values in the `Examples` sections.

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--org-token-name` | The name of the Organization API token you want to add to your Deployment. | Any string                                                        |
```suggestion
| `--org-token-name` | The name of the Organization API token you want to remove from the Deployment. | Any string.                                                        |
```

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--deployment-id` | The Deployment ID you want to scope an Organization API Token to. | Any Deployment ID                                                      |
```suggestion
| `--deployment-id` | The Deployment ID you want to remove an API token from. | Any Deployment ID.                                                      |
```

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +astro deployment organization-token remove --deployment-id=<my-deployment-id> --org-token-name=my-org-token
```suggestion
astro deployment organization-token remove --deployment-id=clvduhrvd000008l842ohcpvb --org-token-name="My org token"
```
The examples section is only useful if we show what the actual values would look like. Otherwise it's a repeat of the usage section.

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--workspace-id` | The Workspace assigned to the Deployment. | Any Workspace ID                                                      |
```suggestion
| `--workspace-id` | The Workspace to which the Deployment belongs. | Any Workspace ID                                                      |
```

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--deployment-id` | The Deployment ID you want to scope an Organization API Token to. | Any Deployment ID                                                      |
This needs rewriting, looks like the options for the create command. You shouldn't be able to update the org token name from the Deployment level.

2024-04-24 13:27 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +
```suggestion
## astro deployment organization-token update

Update the role an Organization API token has within a Deployment.
```

2024-04-24 13:36 UTC, jwitz commented on astro/cli/release-notes.md
> +### Scope Organization and Workspace API tokens to Deployments and Workspaces
```suggestion
### New commands to assign Organization and Workspace API tokens at different levels
```

2024-04-24 13:36 UTC, jwitz commented on astro/cli/release-notes.md
> +- [`astro workspace token organization-token`](https://docs.astronomer.io/astro/cli/astro-workspace-token-organization-token)
```suggestion
- [`astro workspace token organization-token`](https://docs.astronomer.io/astro/cli/astro-workspace-token-organization-token)

For more information about this feature, see:

- [Assign an Organization or Workspace API token to a Deployment](deployment-api-tokens.md#assign-an-organization-or-workspace-api-token-to-a-deployment).
- [Assign an Organization API token to a Workspace](https://docs.astronomer.io/astro/workspace-api-tokens#assign-an-organization-api-token-to-a-workspace)
```

2024-04-24 13:36 UTC, jwitz commented on astro/cli/release-notes.md
> +You can centralize your API Token management by using the Astro CLI to add an Organization or Workspace API token to a specific Deployment or Workspace. This allows you to use a single API Token acro
```suggestion
You can now use the Astro CLI to manage Organization and Workspace API tokens at the Workspace and Deployment level using the following commands:
```

2024-04-24 13:36 UTC, jwitz commented on astro/deployment-api-tokens.md
> +:::
```suggestion
```
We don't have this callout for any other process in the doc, and I'm hesitant to start shouting out the CLI now that the API exists. Can we leave these notes out for now and maybe discuss their use together as a team?

2024-04-24 13:36 UTC, jwitz commented on astro/cli/release-notes.md
> +- Fixed a bug that caused some input checks for `astro deployment upgrade-checks` to invalidate some valid inputs.
```suggestion
- Fixed an issue where existing secret environment variables in a Deployment file could be applied to the Deployment with an empty value. The secret variable value now persists.
- Fixed an issue where `astro deployment inspect` generated an incorrect Airflow API URL.
- Fixed a bug that caused some input checks for `astro deployment upgrade-checks` to fail against valid inputs.
```

2024-04-24 14:05 UTC, lzdanski commented on astro/cli/astro-deployment-token-organization-token.md
> +| `SCOPE`          | The scope level the API Token provides permissions for. Can be `ORGANIZATION` or `WORKSPACE`. | String
I think you're right, i would expect it to always be organization.

2024-04-24 14:14 UTC, lzdanski commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--deployment-id` | The Deployment ID you want to scope an Organization API Token to. | Any Deployment ID                                                      |
Hey @aliotta - thoughts about this? Here's what the help text in the CLI says:

```
Update an Organization API token's Deployment Role
$astro deployment token organization-token update [ORG_TOKEN_ID] --name [token name] --role [DEPLOYMENT_ADMIN or a custom role name].

Current Context: Astro

Usage:
  astro deployment token organization-token update [ORG_TOKEN_ID] [flags]

Flags:
  -h, --help                    help for update
  -n, --org-token-name string   The name of the Organization API token you want to update in a Deployment. If the name contains a space, specify the entire name within quotes "" 
  -r, --role string             The Deployment role to update the Organization API token. Possible values are DEPLOYMENT_ADMIN or a custom role name.

Global Flags:
      --deployment-id string   deployment where you would like to manage tokens
      --verbosity string       Log level (debug, info, warn, error, fatal, panic (default "warning")
      --workspace-id string    workspace assigned to deployment
 ```

2024-04-24 15:03 UTC, jwitz approved these changes
A few more bugs, once those are addressed this is good to merge. Only thing I didn't directly address was the format of the usage sections in `astro workspace token organization-token`. After we confirm the right format there, we should make them consistent in style with the other docs before merging.

2024-04-24 15:03 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token add <ORG_TOKEN_ID> --org-token-name=ORGANIZATION-NAME --role=WORKSPACE_MEMBER
```suggestion
astro workspace organization-token add <ORG_TOKEN_ID> --org-token-name=ORGANIZATION-NAME --role=<workspace-role>
```

2024-04-24 15:28 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token update <ORG_TOKEN_ID> --org-token-name=ORGANIZATION-TOKEN-NAME --workspace-id=<workspace-id> --role=WORKSPACE_MEMBER
```suggestion
astro workspace organization-token update <organization-token-id> --org-token-name=<organization-token-name> --workspace-id=<workspace-id> --role=<workspace-role>
```

2024-04-24 15:28 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token add <ORG_TOKEN_ID> --workspace-id=clvdx7z3c000008kv5tdw5tc5 --org-token-name=MY-ORGANIZATION --role=WORKSPACE_AUTHOR
```suggestion
astro workspace organization-token add <ORG_TOKEN_ID> --workspace-id=clvdx7z3c000008kv5tdw5tc5 --org-token-name="My organization token" --role=WORKSPACE_AUTHOR
```

2024-04-24 15:28 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token remove <ORG_TOKEN_ID> --org-token-name=ORG-TOKEN-NAME
```suggestion
astro workspace organization-token remove <organization-token-id> --org-token-name=<organization-token-name>
```

2024-04-24 15:28 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token add <ORG_TOKEN_ID> --org-token-name=ORGANIZATION-NAME --role=<workspace-role>
```suggestion
astro workspace organization-token add <organization-token-id> --org-token-name=<organization-token-name> --role=<workspace-role>
```

2024-04-24 15:48 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token add <ORG_TOKEN_ID> --org-token-name="My Organization" --role=WORKSPACE_OWNER
```suggestion
astro workspace organization-token add --org-token-name="My Organization" --role=WORKSPACE_OWNER
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token remove --org-token-name="My org token"
```suggestion
astro workspace organization-token remove
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token update --org-token-name=<organization-token-name> --workspace-id=<workspace-id> --role=<workspace-role>
```suggestion
astro workspace organization-token update --workspace-id=<workspace-id> --role=<workspace-role>
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-workspace-token-organization-token.md
> +astro workspace organization-token remove --org-token-name=<organization-token-name>
```suggestion
astro workspace organization-token remove
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +astro deployment organization-token update --org-token-name=<org-token-name> --deployment-id=<my-deployment-id> --role=DEPLOYMENT_ADMIN
```suggestion
astro deployment organization-token update --deployment-id=<my-deployment-id> --role=DEPLOYMENT_ADMIN
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +astro deployment organization-token remove --deployment-id=<my-deployment-id> --org-token-name=<org-token-name>
```suggestion
astro deployment organization-token remove --deployment-id=<my-deployment-id> 
```

2024-04-24 15:52 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +astro deployment organization-token add --deployment-id=<my-deployment-id> --role=DEPLOYMENT_ADMIN --org-token-name=<org-token-name> --workspace-id=<workspace-id>
```suggestion
astro deployment organization-token add --deployment-id=<my-deployment-id> --role=DEPLOYMENT_ADMIN --workspace-id=<workspace-id>
```

2024-04-24 17:31 UTC, jwitz commented on astro/cli/astro-deployment-token-organization-token.md
> +| `--deployment-id`        | The Deployment ID where you want to manage tokens. | Any Deployment ID.                                                                    |
```suggestion
| `--deployment-id`        | The ID of the Deployment where you want to manage tokens. | Any Deployment ID.                                                                    |
```

2024-04-24 17:33 UTC, merged