Add Cloud IDE note
astronomer/docs pull request #3679
Opened 2024-04-25 18:58 UTC by lzdanski

Resolves #3602

2024-04-26 12:04 UTC, jwitz requested changes
Looking at the original Slack comment, I think this is more related to repository setup rather than connecting a data pipeline to an external resource. We should put this note in https://docs.astronomer.io/astro/cloud-ide/deploy-project#commit-your-project-to-a-git-repository instead

2024-04-26 12:04 UTC, jwitz commented on astro/cloud-ide/configure-project-environment.md
> +- In order to connect the Cloud IDE to a 3rd party resource, such as GitLab, the resource cannot be private. It must be public.
```suggestion
- To connect the Cloud IDE to a 3rd party resource, such as GitLab, the resource must be publicly accessible.
```

2024-04-26 12:04 UTC, jwitz commented on astro/cloud-ide/quickstart.md
> +:::note
```suggestion
:::info
```

2024-04-26 12:04 UTC, jwitz commented on astro/cloud-ide/quickstart.md
> +In order to connect the Cloud IDE to a 3rd party resource, such as GitLab, the resource cannot be private. It must be public.
Not sure we need the note in the quickstart? I don't see an opportunity for anyone to connect to a 3rd party resource in this setup.

2024-04-26 18:02 UTC, lzdanski commented
I think i've got the "format document" setting enabled on my VScode to address extra whitespace. So there's one file that shouldn't have any content changes, just removing trailing whitespace.

2024-04-29 10:22 UTC, jwitz approved these changes

2024-04-29 10:22 UTC, jwitz commented on astro/cloud-ide/configure-project-environment.md
> +- To connect the Cloud IDE to a 3rd party resource, such as GitLab, the resource must be publicly accessible.
```suggestion
```

2024-04-29 10:22 UTC, jwitz commented on astro/cloud-ide/deploy-project.md
> +- A Git repository hosted with a supported Git vendor.
```suggestion
- A Git repository hosted with a supported Git vendor. The Git repository must be publicly accessible.
```

2024-04-29 10:22 UTC, jwitz commented on astro/cloud-ide/deploy-project.md
> +:::
```suggestion
```
I think it makes more sense to keep this info close to the other prerequisites

2024-04-29 17:11 UTC, merged