Add notes about cluster type and networking
astronomer/docs pull request #3680
Opened 2024-04-25 20:29 UTC by lzdanski

Resolves #3470

2024-04-26 12:13 UTC, jwitz commented on astro/connect-aws.md
> +:::
```suggestion
Deployments also have their own external IP addresses, but these addresses are dynamically generated and can break your connections if they change. A cluster-level external IP address persists, ensuring your cluster can access your cloud resources as long as the cluster exists.
```
I don't think the tip is necessary here -the paragraph flows nicely after the proceeding one as a complete explanation, and we're not providing any alternative setup/ recommendations that usually serve as the basis for a tip

2024-04-26 14:24 UTC, manmeetkaur approved these changes
👍 once we add a bit of clarity for standard cluster customers.

2024-04-26 18:06 UTC, lzdanski commented on astro/connect-aws.md
> +:::
@manmeetkaur I think I'm confused. Doesn't that directly contradict the description in all of these docs that Standard clusters support adding the external IP to the allowlist?

2024-04-29 18:45 UTC, lzdanski commented on astro/connect-aws.md
> +### Allowlist external IP addresses
shift scope and clarify that deployment external IP addresses can be used, however, it might be useful for some dedicated users to work with the cluster-level external ip addresses.

2024-04-30 15:58 UTC, jwitz requested changes
Requesting changes based on a few technical questions I had, otherwise LGTM

2024-04-30 15:58 UTC, jwitz commented on astro/connect-aws.md
> +3. In the **Other** section, you can find the **External IPs** associated with the Deployment.
```suggestion
3. In the **Other** section, you can find the **External IPs** associated with the Deployment.
4. Add the IP addresses to the allowlist of any external services that you want your Deployment to access. 
```

2024-04-30 15:58 UTC, jwitz commented on astro/connect-aws.md
> +### Allowlist external IP addresses
```suggestion
### Allowlist a Deployment's external IP addresses on AWS
```

2024-04-30 15:58 UTC, jwitz commented on astro/connect-aws.md
> +### Allowlist external IP addresses
All of the edits here also apply to the other cloud docs

2024-04-30 15:58 UTC, jwitz commented on astro/connect-aws.md
> +If you use Dedicated clusters and want to allowlist external IP addresses at the cluster level, instead of per-Deployment, you can find the list of external IP addresses the cluster uses in your **Or
```suggestion
If you use Dedicated clusters and want to allowlist external IP addresses at the cluster level instead of at the Deployment level, you can find the list cluster-level external IP addresses in your **Organization settings**.
```

2024-04-30 15:58 UTC, jwitz commented on astro/deployment-details.md
> +## Find a Deployment's external IP address
Is it one or multiple? In the steps it implies multiple

2024-04-30 15:58 UTC, jwitz commented on astro/deployment-details.md
> +Deployments have associated external IP addresses.
```suggestion
Each Astro Deployment has its own external IP addresses. Allowlist these addresses on any external service as a first step to create a connection between the Deployment and the service.
```

2024-04-30 15:58 UTC, jwitz commented on astro/deployment-details.md
> +:::note
```suggestion
:::info
```
I really should disable our ability to use `note` in `docusaurus.config.js`, but in general we should never be using this type of admonition

2024-04-30 15:58 UTC, jwitz commented on astro/deployment-details.md
> +If you are using a Standard Cluster and need to look up your external IP address for your cluster, you can use the Deployment External IP address.
```suggestion
On standard clusters, the external IP address for the cluster is identical to the external IP address for all Deployments in the cluster.
```
How is this information useful for standard cluster users? I'm not seeing the use case for why you would need to allowlist an entire cluster instead of just a Deployment.

2024-04-30 15:58 UTC, jwitz commented on astro/networking-overview.md
> +Depending on the type of cloud provider you want to create a networking connection with and whether you have a standard or a dedicated cluster in your Astro Deployment, you have different configurati
```suggestion
```

2024-04-30 15:58 UTC, jwitz commented on astro/networking-overview.md
> +Depending on the type of cloud provider you want to create a networking connection with and whether you have a standard or a dedicated cluster in your Astro Deployment, you have different configurati
This paragraph splits up the continuation of the public > private point in this topic, and isn't a recommendation. I don't think it's necessary at this point to include this information here - it'll become clear what types of options are supported when the user goes to check on the doc for their specific cloud.

2024-04-30 16:20 UTC, lzdanski commented on astro/deployment-details.md
> +If you are using a Standard Cluster and need to look up your external IP address for your cluster, you can use the Deployment External IP address.
Sorry! Standard users don't have *any* cluster level information about external IP addresses. If their platform admin wanted to allowlist at the cluster level, they can't. It has to be done at the deployment level.

2024-04-30 16:28 UTC, manmeetkaur approved these changes
LGTM! just left two comments.

2024-05-01 16:58 UTC, lzdanski commented on astro/connect-gcp.md
> +- Using [static external IP addresses](#allowlist-external-ip-addresses).
```suggestion
- Using [static external IP addresses](#allowlist-a-deployments-external-ip-addresses-on-gcp).
```

2024-05-01 18:12 UTC, lzdanski commented on astro/connect-aws.md
> +All Astro clusters include a set of external IP addresses that persist for the lifetime of the cluster. When you create a Deployment in your workspace, Astro assigns it one of these external IP addre
```suggestion
All Astro clusters include a set of external IP addresses that persist for the lifetime of the cluster. When you create a Deployment in your workspace, Astro assigns the external IP addresses to it. To facilitate communication between Astro and your cloud, you can allowlist these external IPs in your cloud. If you have no other security restrictions, this means that any cluster with an allowlisted external IP address can access your AWS resources through a valid Airflow connection.
```

2024-05-01 18:14 UTC, lzdanski commented on astro/deployment-details.md
> +## Find a Deployment's external IP address
```suggestion
## Find Deployment external IP addresses
```

2024-05-02 10:00 UTC, jwitz commented on astro/deployment-details.md
> +:::
```suggestion
```
> Sorry! Standard users don't have any cluster level information about external IP addresses. If their platform admin wanted to allowlist at the cluster level, they can't. It has to be done at the deployment level.

Based on your previous comment, this admonition isn't accurate anymore

2024-05-02 10:00 UTC, jwitz approved these changes

2024-05-06 18:29 UTC, merged