Add cross-deployment dependencies guide
astronomer/docs pull request #3684
Opened 2024-04-26 18:32 UTC by merobi-hub

This adds a Learn guide on cross-deployment dependencies using Astro Alerts.

To-dos (assuming we want to go with this general approach):
- provide the datasets, possibly via a GH download of the whole project-?
- add screenshots
- add Best Practices guidance
- add traditional syntax alternatives with tabs
- complete See Also section

2024-04-29 19:35 UTC, kentdanas requested changes
@merobi-hub can chat about this tomorrow, but this is a great outline to start. I left a few suggestions, but generally, this will go under Astro/best practices, and I think we should follow the same outline of the alerting one: https://docs.astronomer.io/astro/best-practices/airflow-vs-astro-alerts

So for this, I think we would have:
- Intro (like you have)
- Feature overview (brief, bullets for Astro Alerts and datasets, link to relevant docs)
- Best practice guidance (when to use each method)
- Astro Alerts example (with prereqs and implementation, what you have already)
- Datasets example

2024-04-29 19:35 UTC, kentdanas commented on learn/cross-deployment-dependencies.md
> +title: "Cross-deployment dependencies"
We'll actually want to put this under astro/best-practices, not on Learn. So it goes in a different folder, and needs to be added to the SidebarsAstro.js so it shows up in the menu

2024-04-29 19:35 UTC, kentdanas commented on learn/cross-deployment-dependencies.md
> +In some cases, locating all related tasks in one DAG is not possible no matter how hard you try to follow best practices. And sometimes the TaskFlow you want to create includes tasks not only in diff
```suggestion
[Cross-DAG dependencies](cross-dag-dependencies.md) refers to cases where you create dependencies between separate DAGs, rather than locating all related tasks in one DAG. This is particularly relevant if you have DAGs that are dependent but are owned and managed by different teams. It is sometimes necessary to implement these cross-DAG dependencies where the DAGs do not exist in the same Airflow deployment. For example, one team in your org might want to make a task dependent on a dataset's being updated by a DAG owned by a different org and, hence, located in a different deployment. 
```
Given the nature of this doc, we can do away with "all related tasks in the same DAG is best practice" :) Also "TaskFlow" is the name for an API in Airflow that allows for writing DAGs with decorators (like @task) - different from the generic concept of the flow of tasks in your DAGs (naming is always confusing :)

2024-05-03 23:18 UTC, kentdanas requested changes
@merobi-hub this is looking great - I think the structure is spot-on. Left some comments on adjustments throughout for you to start with next week.

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +Astro Alerts, configurable in the Astro UI, fire on DAG failure or success, a task taking longer than expected, or a DAG not completing in time. Alerts are a no-code option best for cases when DAGs d
I think we can clarify the guidance in this and the next paragraph a bit. A couple bits of general feedback, and we can chat about how that would best be implemented in the text here if that's helpful :)

- I think you're on track with alerts being a good no-code option here. But I would phrase it as when DAGs do not already use the datasets feature (since "datasets" is confusingly both a feature and a concept).
- What do you mean by "few pipelines in an organization"? Let's clarify how that related specifically to choosing a method.
- When talking about using the datasets feature, I would focus less on it being a more natural way of authoring, and more on it offering more flexibility around cross-dag (and cross-deployment) dependencies. Like we talked about before, datasets allow you to implement a many:1 DAG dependency where astro alerts would not. It's also easier to implement a 1:many dependency with datasets (at least today, you can't do this in astro alerts without creating many alerts), and allows you to implement the dependency at the task level (when you said "triggering at the DAG level" - did you mean task level)?
- Generally this might be easier to present in two bulleted lists - one for scenarios where you should choose alerts, and one for when you should choose datasets.

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- Airflow operators. See [Operators 101](https://docs.astronomer.io/learn/what-is-an-operator.md).
```suggestion
```
I don't think we need operators here specifically.

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +This example shows you how to create dependencies between DAGs in different Astro deployments using Astro's Alerts feature. Cross-deployment dependencies can also be configured using the Airflow API.
```suggestion
This example shows you how to create dependencies between DAGs in different Astro deployments using Astro's Alerts feature.
```

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- The [Astro CLI](https://docs.astronomer.io/astro/cli/overview).
```suggestion
```
They can do all of this within astro, nothing local needed :)

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- Two [Astro projects](https://docs.astronomer.io/astro/cli/develop-project#create-an-astro-project).
```suggestion
```
Removing in favor of updating the prior bullet

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- Two [Astro Deployments](https://docs.astronomer.io/astro/create-deployment).
```suggestion
- Two [Astro Deployments](https://docs.astronomer.io/astro/create-deployment), each containing at least one DAG.
```

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +2. Navigate to Alerts in the workspace sidebar and create a new alert.
Let's link to our alerting doc in the text here, so people can go there if they need more guidance

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +4. In the deployment dropdown menu, select the deployment containing the DAG.
```suggestion
4. In the deployment dropdown menu for the `DAG Trigger` communication channel, select the deployment containing the downstream DAG.
```
We should probably use "upstream" and "downstream" DAG like we do in the cross-DAG dependencies guide, and define them here up front (also like we do in that one) for consistency

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +5. In the `DAG NAME` dropdown, select the DAG.
```suggestion
5. In the `DAG NAME` dropdown, select your downstream DAG.
```

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +This section explains how to use the [Airflow API's Datasets endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Dataset) to trigger a consumer DAG in another
Let's explain here why we're using a listener to implement this. Listeners aren't by definition related to datasets, so this is actually opinionated guidance we're providing.

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +Running the DAG in the first deployment should trigger the DAG in the second. While HttpOperator could also be used to trigger the consumer, an advantage of this approach is that the DAG will run whe
Ah, didn't read far enough with my last comment :) let's move some of this context up into the implementation section.

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +            url=f"{deployment_url}/api/v1/dags/{dag_id}/dagRuns",
shouldn't this line be updated to the datasets endpoint?

2024-05-03 23:18 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +    schedule="0 0 * * 0",
If this is the downstream DAG, shouldn't it have a dataset schedule that matches the dataset URI defined in the listener code? (file://include/bears in that example)

2024-05-06 16:07 UTC, merobi-hub commented on sidebarsAstro.js
> +        'best-practices/airflow-vs-astro-alerts',
Done!

2024-05-08 18:40 UTC, merobi-hub commented on astro/best-practices/cross-deployment-dependencies.md
> +Astro Alerts, configurable in the Astro UI, fire on DAG failure or success, a task taking longer than expected, or a DAG not completing in time. Alerts are a no-code option best for cases when DAGs d
@kentdanas thanks for the feedback -- the section has been revised to address these points

2024-05-08 21:32 UTC, kentdanas requested changes
@merobi-hub this is looking great! A couple of final suggested changes from my side and then I'll look one more time.

In the meantime, I think this is solid content-wise and we can also move on to copy editing. @lzdanski you want to take this one?

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +To determine whether an Astro Alert or the Datasets feature is the right solution for your use case, consider their different purposes.
```suggestion
To determine whether an Astro Alert or the Datasets feature is the right solution for your use case, consider the following guidance. 
```
Updating this section to be a little more directly prescriptive.

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +**Astro Alerts:**
```suggestion
**Astro Alerts:**

Astro alerts can be used to implement cross-deployment DAG dependencies using the DAG trigger communication channel. They are simple to implement and are the preferred method in the following situations: 
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- fire on DAG failure or success, a task taking longer than expected, or a DAG not completing in time.
```suggestion
- If you need to implement a dependency trigger based on any DAG state other than success, such as a DAG failure, a task taking longer than expected, or a DAG not completing by a certain time. 
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- offer a no-code option for creating simple dependencies between DAGs.
```suggestion
- If you need to implement a simple one to one cross-deployment dependency (one upstream DAG triggers one downstream DAG) and do not want to update your DAG code.
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- are best for cases when DAGs do not already use the Datasets feature and when it is easy to identify the relevant dependent DAGs, which is not always the case in larger organizations.
```suggestion
- When your DAGs do not already use the Datasets feature and when it is easy to identify the relevant dependent DAGs, which is not always the case in larger organizations. 
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +**Airflow Datasets:**
```suggestion
**Airflow Datasets:**

Datasets represent a significant evolution in the way Airflow can be used to define dependencies and, for some users, offer a more natural way of expressing pipelines than traditional DAGs. They offer more flexibility for cross-deployment dependencies than Astro alerts, are the preferred method in the following scenarios:
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- represent a significant evolution in the way Airflow can be used to orchestrate pipelines and, for some users, offer a more natural way of expressing pipelines than traditional DAGs.
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- provide more flexibility around cross-DAG and cross-deployment dependencies than Alerts. For example, Datasets allow you to implement a many-to-one DAG dependency such that a DAG can be made depend
```suggestion
- You need to implement dependencies in a many-to-one pattern, such that a DAG can be made dependent on the completion of multiple other DAGs or tasks. This is not possible using Astro Alerts.
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +- provide an easier way to create a one-to-many dependency such that multiple DAGs or tasks are triggered by one DAG or task.
```suggestion
- You need to implement dependencies in a one-to-many pattern, such that multiple DAGs or tasks are triggered by one DAG or task. This is also possible using Astro Alerts, but requires a separate alert for each dependency.
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +7. Run both DAGs and verify that the alert is functioning as expected.
```suggestion
7. Run the upstream DAG and verify that the alert triggers and the downstream DAG runs as expected.
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +This section explains how to use a listener in combination with the [Airflow API's Datasets endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Dataset) to tr
```suggestion
This section explains how to use a listener in combination with the [Airflow API's Datasets endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Dataset) to trigger the downstream DAG in another deployment when a dataset is updated. Typical dataset implementation only works for DAGs in the same Airflow deployment, but by using the API, this pattern can be implemented across deployments.
```
"consumer" is used in teh context of datasets, but I think to make this more straightforward we can use "downstream" for this guide.

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +While HttpOperator could also be used to trigger the consumer, an advantage of using a listener is that the DAG will run whenever the dataset is updated -- regardless of which DAG is performing the u
```suggestion
While HttpOperator could also be used to make the API request to update the dataset, an advantage of using a listener is that the dataset will be updated and the downstream DAG will run whenever _any_ DAG updates the dataset. This avoids the need to implement an API call in every upstream DAG that updates the same dataset.
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +    print("I am always listening for any Dataset changes and I heard that!")
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +        print("Oh! This is the bears dataset!")
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +)
```suggestion
```
What the DAG does isn't actually relevant here, so removing some of the storage stuff for simplicity. Maybe double check I didn't create a syntax issue though :)

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +from airflow.io.path import ObjectStoragePath
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +    tags=["on_dataset_changed listener", "2-8"],
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +        r = requests.get("https://placebear.com/300/300")
```suggestion
        print("Update the bears dataset")
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +            print(f"Failed to retrieve image. Status code: {r.status_code}")
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +    def get_bear(base):
```suggestion
    def get_bear():
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +    get_bear(base=BASE_PATH_INGEST)
```suggestion
    get_bear()
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +import requests
```suggestion
```

2024-05-08 21:32 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +4. Put the DAG from the tutorial in the same project's `dags` folder. Then, referring to the guidance in [Connections and variables](https://docs.astronomer.io/astro/manage-connections-variables), mo
```suggestion
4. Add the following DAG to your Astro project.
```

2024-05-09 16:32 UTC, kentdanas approved these changes

2024-05-09 17:11 UTC, lzdanski requested changes
Got a couple questions and some stylistic things to fix!

2024-05-09 17:11 UTC, lzdanski commented on astro/best-practices/cross-deployment-dependencies.md
> +6. Deploy a DAG of any kind to your downstream deployment, using a `dag_id` of `consumer_dag` and scheduling it on the same dataset in the `producer_dag`.
```suggestion
6. Deploy a DAG of any kind to your downstream Deployment. In this DAG, use a `dag_id` of `consumer_dag` and schedule it on the same dataset in the `producer_dag`.
```

2024-05-09 17:11 UTC, lzdanski commented on astro/best-practices/cross-deployment-dependencies.md
> +After deploying both projects to their respective deployments on Astro, you should see your `consumer_dag` being triggered automatically by runs of your `producer_dag`. If the downstream DAG is not f
```suggestion
After deploying both projects to their respective Deployments on Astro, you should see runs of your `producer_dag` trigger your `consumer_dag` automatically. If the downstream DAG is not firing, verify that the upstream Deployment's environment variables, the `API_KEY`  and `DEPLOYMENT_URL`, correspond to the downstream Deployment's API Token and Deployment URL. Also, a properly functioning listener will emit an API response payload containing DAG run information related to the dataset. Check the task logs for output that looks similar to this:
```

It's a little confusing that we have users configuring the API_KEY variable but using information from a Token. Is that correct?

2024-05-09 18:20 UTC, merobi-hub commented on astro/best-practices/cross-deployment-dependencies.md
> +[Cross-DAG dependencies](https://docs.astronomer.io/learn/cross-dag-dependencies.md) serve a common use case: configuring a DAG to run when a separate DAG or a task in another DAG completes or update
Hi @lzdanski , think this edit changes the meaning slightly because it's suggesting that the DAG being in a separate deployment is a consequence of wanting to make the task dependent (or something like that). How about: "For example, you might want to make a task dependent on an a dataset update in a DAG that is owned by a different team and, hence, located in a separate deployment."?

2024-05-09 18:26 UTC, merobi-hub commented on astro/best-practices/cross-deployment-dependencies.md
> +After deploying both projects to their respective deployments on Astro, you should see your `consumer_dag` being triggered automatically by runs of your `producer_dag`. If the downstream DAG is not f
We could change `token` to `key` in the request. Would that take care of it?

2024-05-09 18:52 UTC, merobi-hub commented on astro/best-practices/cross-deployment-dependencies.md
> +3. Give the alert a name you'll remember, select an alert type (e.g., `DAG Success`), and then select `DAG Trigger` as the communication channel.
Thank you -- this is good to know

2024-05-09 19:48 UTC, kentdanas approved these changes
@merobi-hub looks great! A few final minor edits - mostly to get the code syntax highlighting in there. After that, good to merge!

2024-05-09 19:48 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +Datasets represent a significant evolution in the way Airflow can be used to define dependencies and, for some, offer a more natural way of expressing pipelines than traditional DAGs. Datasets offer
```suggestion
Datasets represent a significant evolution in the way Airflow can be used to define dependencies and, for some, offer a more natural way of expressing pipelines than traditional DAGs. Datasets offer more flexibility for cross-deployment dependencies than Astro alerts, and are the preferred method in the following scenarios:
```

2024-05-09 19:48 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +1. In your upstream Deployment, which is the Deployment  for which you did **not** create an API Token, use **Variables** in the Astro UI to create an environment variable for your API token, and use
```suggestion
1. In your upstream Deployment, which is the Deployment for which you did **not** create an API Token, use **Variables** in the Astro UI to create an environment variable for your API token, and use `API_TOKEN` for the key.
```

2024-05-09 19:48 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +```
```suggestion
```python
```
This will add syntax highlighting in the rendered version :)

2024-05-09 19:48 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +```
```suggestion
```python
```

2024-05-09 19:48 UTC, kentdanas commented on astro/best-practices/cross-deployment-dependencies.md
> +```
```suggestion
```python
```

2024-05-09 20:52 UTC, merged