Pushing Astronomer Certified Architecture doc to main docset
astronomer/docs pull request #372
Opened 2021-05-25 14:46 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/369

Changes the "Image Architecture" doc in our AC `next` folder to cater towards our platform users and added it to our main docset. Commenting in places where I wasn't able to confirm technical information from source code alone.

2021-05-25 14:47 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +|**2.0.0**|1.0.0|1.1.0|1.0.0|1.0.1|1.0.4|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|1.0.0|
@kaxil I was able to find `pip-build-restraints` only for 2.0.0 onwards. For the earlier versions, did we install provider packages by default, and if so where I can I find what versions we used?

2021-05-25 14:52 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +| ----------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------- |
@paolaperaza I included all variables that were different than how they are in OSS Airflow. I wasn't able to find some of these in `ap-airflow`, though we definitely have them in `docker-airflow` (specifically, the first Airflow environment variables). Were these scrapped?

2021-05-25 14:53 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +| Astronomer Certified | [amazon](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html) |[azure](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/
@paolaperaza I'm not totally sold on this format yet 🤔  as you can see, it's pretty unwieldy. Definitely open to any thoughts you have on restructuring this.

2021-06-01 16:48 UTC, paolaperaza requested changes
@jwitz Great start on this! Delayed review, but give these comments a look and let me know what you think.

Additional high-level thoughts:
- We might need to emphasize/better describe how AC is different/better than OSS Airflow. I had done some of that here for `docker-airflow`: https://hub.docker.com/repository/docker/astronomerio/docker-airflow. Maybe some language you can steal?
- I think there's a way for us to be more clear/explicit in that the Python Wheel really doesn't have much that's different than OSS Airflow, and that most of this doc only applies to the Docker image/Dockerfile. We do that mostly, but I might re-read and make sure we're not leaving room for confusion. Maybe even just saying something like - "If you want to run the Astronomer Certified Python Wheel, you can still reference the logic baked into our Dockerfile and manually add it yourself." For more info, see "Installing Dependencies".... or something like that

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +description: "Reference documentation for every component used to build Astronomer Certified."
- Thoughts on "Docker Image Architecture" for navTitle?
- Might change description to something like:
    - "Reference documentation for the Astronomer Certified Docker image for Apache Airflow, including pre-installed packages and versioning."

Open to different wording here - the Airflow there feels a little too much, but wondering if we can get it in there for SEO.

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +The Astronomer Certified image for Apache Airflow extends the community-developed Airflow image in a way that makes running Airflow more secure, reliable, and extensible. It is the default image for
```suggestion
The Astronomer Certified image for Apache Airflow extends the community-developed Airflow image in a way that makes running Airflow more secure, reliable, and extensible. It is the default image for Airflow Deployments on Astronomer.
```

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +This guide provides reference information for the key components of Astronomer Certified, as well as information on its release and distribution.
This sentence sounds a bit weird to me, mostly because I don't think of "Astronomer Certified" as having "components", even though Airflow does. Most of what our Dockerfile really does is set some "logic" for how Airflow components will be created and what else will be installed on our machine.

Try to rephrase? Will come back to this.

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +The Astronomer Certified Docker image is built from the Python wheel. In addition to the Python wheel's bug fixes, the Docker image includes dependencies for increasing the security and extensibility
Not just dependencies! Also "logic" that ensures a great user experience

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +The Python wheel is the "core" of Astronomer Certified. It is composed of open source Airflow, plus bug fixes extend the support lifespan of each version.
- *bug and security fixes
- Python wheel being described as the "core" seems a bit superficial - it's more like "the Docker image inherits from the Python wheel"

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +Every component of the Astronomer Certified Docker image is available as source code on [GitHub](https://github.com/astronomer/ap-airflow). Every supported version of the Astronomer Certified Python
We may want to create a table or bullet list here that links out to the Dockerfile for each version of Airflow so that users don't have to go to to that repo and find it (it's not intuitive). For instance:

- Airflow 2.1: https://github.com/astronomer/ap-airflow/blob/master/2.1.0/buster/Dockerfile
- Airflow 2.0.2: https://github.com/astronomer/ap-airflow/blob/master/2.0.2/buster/Dockerfile

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +In this example, the `*` will pull the latest Astronomer Certified patch release of Airflow 2.0.1. This version might include additional bug and security fixes not present in the corresponding open s
We don't define what a "patch" version of Astronomer Certified is here, and I think I'd like to breakdown major/minor/patch/hot-fix more clearly. Did we talk about pulling versioning details out of "Upgrade Airflow" ([relevant section here](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions#patch-versions-of-astronomer-certified)) and into this doc?

Alternatively, we can put versioning stuff in the "AC Support Policy" doc and link that here. WDYT?

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +In this example, the `*` will pull the latest Astronomer Certified patch release of Airflow 2.0.1. This version might include additional bug and security fixes not present in the corresponding open s
Some helpful already-written language here: https://hub.docker.com/repository/docker/astronomerio/docker-airflow

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +Astronomer Certified is distributed both as a Python wheel and a Docker image. These distributions vary slightly in scope and dependencies.
```suggestion
Astronomer Certified is distributed both as a Python wheel and a Debian-based Docker image. These distributions vary slightly in scope and dependencies.
```

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +Astronomer Certified is distributed both as a Python wheel and a Docker image. These distributions vary slightly in scope and dependencies.
Should prob include the version of Debian somewhere. Should we have a brief "Docker image" overview section that has things like:

- Python: 3.7, 3.8
- Database: PostgreSQL (11, 12), MySQL (5.7, 8.0+)
- System Distribution: Debian 10 (Buster)

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +If you use the Astronomer Certified Docker image, these environment variables are defined in your Dockerfile. Environment variables in your Dockerfile can be overwritten with a runtime command, such
Can they _only_ be set in your Dockerfile? Do we want to make clear that if you're using the Astronomer Platform, these can be set elsewhere too, and link out to our Platform doc?

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +| ----------------------------------------------- | ----------------------------------------------------------------------------- | ------------------------------------------------- |
Good question. I think these were originally in our docker-airflow _Docker Compose files_, but not in the actual Dockerfile. What we have for `ap-airflow` today is just the Dockerfile, no Docker Compose files - I'm not totally sure that we need them, but will follow up with the team for now.

I'd say anything you don't find in the Dockerfile, delete here 🤷‍♀️

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +| Astronomer Certified | [amazon](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html) |[azure](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/
Nice! I honestly think this is fine? Not meant to be read-able really - but offers a source of truth and reference for someone looking for 1 value (which I have to think is most use cases).

2021-06-01 16:48 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +- virtualenv: Adds support for running Python tasks in local virtual environments
I may be missing it, but I don't think I see the following extras in our 2.0.2 dockerfile: `dask`, `ldap`

https://github.com/astronomer/ap-airflow/blob/master/2.0.2/buster/Dockerfile

2021-06-02 15:19 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +This guide provides reference information for the key components of Astronomer Certified, as well as information on its release and distribution.
The Dockerfile itself is just logic, but I consider "components" here to mean the additional packages we need to run the image. Maybe "building blocks" could be used as a more generalized term?

2021-06-02 15:24 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +The Python wheel is the "core" of Astronomer Certified. It is composed of open source Airflow, plus bug fixes extend the support lifespan of each version.
Maybe this is where we can communicate the similarity of the Python wheel to OSS, which I'm sure some people would want to see written in plain language. Is it fair to say that the Python wheel is "functionally identical" to OSS?

2021-06-02 15:33 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +In this example, the `*` will pull the latest Astronomer Certified patch release of Airflow 2.0.1. This version might include additional bug and security fixes not present in the corresponding open s
Eep, I don't have access to that repo! But in general, I think it probably makes more sense to include detailed versioning info in our support doc, since that's where we'll be describing the support lifecycle for each of those version types.

2021-06-02 15:42 UTC, jwitz commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +Astronomer Certified is distributed both as a Python wheel and a Docker image. These distributions vary slightly in scope and dependencies.
I created a new section for this and included information about the system requirements for the Python wheel, which seem to differ slightly from this list here. Will need to confirm with a tech reviewer though.

2021-06-04 03:18 UTC, paolaperaza approved these changes
A few final tweaks, but this looks good to me @jwitz ! Thanks for getting this through 😊

2021-06-04 03:18 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +If you run the Astronomer Certified Docker image without the Astronomer platform, environment variables are defined in your Dockerfile. They can be overwritten with a runtime command, such as `docker
```suggestion
If you run the Astronomer Certified Docker image without the Astronomer platform, environment variables are defined in your Dockerfile. They can be overwritten with a runtime command, such as `docker run`. If you're running the Astronomer Certified Docker image with the Astronomer platform, there are a few ways you can configure environment variables. For more information, read [Environment Variables](docs/enterprise/v0.25/deploy/environment-variables).
```

Tweaking this just because Env Vars don't _have_ to be set in the Astro UI (they can also be set in Dockerfile, or .env locally)

2021-06-04 03:18 UTC, paolaperaza commented on enterprise/v0.25/10_certified-image/01_image-architecture.md
> +When an Airflow service is started, it checks a file for runtime environment variables.
```suggestion
When an Airflow service is started, it checks a file for runtime environment variables. These are equivalent to values defined in Airflow's `airflow.cfg` file.
```

2021-06-07 15:51 UTC, merged