Astro Security one pager
astronomer/docs pull request #372
Opened 2022-02-08 17:35 UTC by chomipi88

First iteration of the Astro Security one pager

2022-02-15 16:52 UTC, chomipi88 commented
ready for review!

2022-02-16 10:59 UTC, jwitz requested changes
General wording here LGTM, I just have two high level requests:

1. The secrets management doc should be a section in the security doc, since we're not really introducing any new information there. And in that case, I also don't think we need to link out to our resilience and recovery docs if we list those concepts just above in the same one pager
2. To keep the one pager specific, let's structure each section just like Data Protection, where doc links are introduced with a "For more information" sentence.

2022-02-16 10:59 UTC, jwitz commented on cloud/secrets-management.md
> +sidebar_label: 'Secrets Management'
I'm not sure this needs to be its own doc, since it doesn't really have any new information. Seems to fit well as a section in the security doc tho

2022-02-16 10:59 UTC, jwitz commented on cloud/deployment-metrics.md
> -## DAG Runs
Assuming this was unintentional

2022-02-16 10:59 UTC, jwitz commented on cloud/security.md
> +Astronomer Cloud operates on a [model of shared responsibility](shared-responsibility-model.md), which means that both the Astronomer team and Astronomer customers are responsible for the security of
I'd rather have all doc links at the end of these sections, with like "For more information, read Shared Responsibility". It helps to keep consistency across each section

2022-02-16 13:55 UTC, chomipi88 commented
> General wording here LGTM, I just have two high level requests:
> 
> 1. The secrets management doc should be a section in the security doc, since we're not really introducing any new information there. And in that case, I also don't think we need to link out to our resilience and recovery docs if we list those concepts just above in the same one pager
> 2. To keep the one pager specific, let's structure each section just like Data Protection, where doc links are introduced with a "For more information" sentence.

1. The generic blurb on the security one pager does not break down the methods of secrets management we support. It merely introduces the topic and the dedicated page breaks down the solutions and integrations we offer. This doc will be extended as we introduce more advanced / cloud native methods to integrate with secrets managers.
2. I'm good with that. I had removed the links from the headers as it wasn't a great UX and did not align with any of our other docs pages.

2022-02-16 13:58 UTC, chomipi88 commented on cloud/secrets-management.md
> +sidebar_label: 'Secrets Management'
In addition to my other reply, this is an important enough and regularly inquired about topic that would help our sales/field teams quickly get prospects the response they are looking for.
More "meat" will be added here but wanted to get this out the door asap.

2022-02-16 13:59 UTC, chomipi88 commented on cloud/deployment-metrics.md
> -## DAG Runs
I don't believe I made any changes to this doc

2022-02-16 15:08 UTC, chomipi88 commented on cloud/security.md
> +Astronomer Cloud operates on a [model of shared responsibility](shared-responsibility-model.md), which means that both the Astronomer team and Astronomer customers are responsible for the security of
Done

2022-02-16 15:08 UTC, chomipi88 commented
@jwitz ready again

2022-02-16 16:03 UTC, jwitz approved these changes
One last attempt to sway you on the secrets page, but otherwise LGTM. I think my issue here is that this content generally _shouldn't_ belong in technical docs, but that's the only place we currently have to publish it. In the future, would love to work on creating a platform for this kind of content akin to https://databricks.com/product/enterprise-security

2022-02-16 17:11 UTC, merged