Local Team docs
astronomer/docs pull request #3741
Opened 2024-05-15 14:11 UTC by jwitz

2024-06-08 21:08 UTC, lzdanski requested changes

2024-06-10 13:04 UTC, rujhan-arora-astronomer requested changes

2024-06-10 13:04 UTC, rujhan-arora-astronomer commented on software/import-idp-groups.md
> +            enabled: false
This local.teams.enabled flag should be set to true in order to use this feature.

2024-06-10 13:04 UTC, rujhan-arora-astronomer commented on astro/best-practices/cross-deployment-dependencies.md
> +Cross-deployment dependencies require special implementation because some methods, like the TriggerDagRunOperator, ExternalTaskSensor and direct Airflow Dataset dependencies, are only designed for DA
I don't think the title of this PR is correct, since it has so many other changes other than local teams feature.

2024-06-13 15:05 UTC, lzdanski commented on astro/best-practices/cross-deployment-dependencies.md
> +Cross-deployment dependencies require special implementation because some methods, like the TriggerDagRunOperator, ExternalTaskSensor and direct Airflow Dataset dependencies, are only designed for DA
We often wrap up smaller docs edits into PR's that include feature docs if there's minor wording changes that can be improved on the same page.

2024-06-13 15:05 UTC, lzdanski commented on software/import-idp-groups.md
> +            enabled: false
```suggestion
        local:
          enabled: true
          teams:
            enabled: true
```

2024-06-25 22:57 UTC, tonyHuinker commented on software/import-idp-groups.md
> +If you want to create a Team of Astronomer users who don't belong to an IdP group, you can enable local Team creation.
"If you want to create a Team of Astronomer users, and the team doesn't map to a group in the IdP, you can enable local team creation."

This is more about being able to create the *team* object that doesn't exist in the idp, not necessarily users that don't exist int he idp.

2024-06-25 22:59 UTC, tonyHuinker commented on software/import-idp-groups.md
> +If you want to create a Team of Astronomer users who don't belong to an IdP group, you can enable local Team creation.
I would also name this section "create local teams", not create local users.

2024-06-26 05:50 UTC, rujhan-arora-astronomer requested changes

2024-06-26 05:50 UTC, rujhan-arora-astronomer commented on software/import-idp-groups.md
> +If you want to create a Team of Astronomer users who don't belong to an IdP group, you can enable local Team creation.
True. Users can be idp users too. So, it should be named as -> ## Create local Teams.
If you want to create a Team of Astronomer users locally, you can enable local Team creation.

2024-06-26 05:50 UTC, rujhan-arora-astronomer commented on software/import-idp-groups.md
> +3. Give the team a name and a description, then select all local users that you want in the Team.
"select all the users", instead of "select all local users"

2024-06-26 11:52 UTC, lzdanski commented on software/import-idp-groups.md
> +## Create Teams for local users
```suggestion
## Create local Teams
```

2024-06-26 11:52 UTC, lzdanski commented on software/import-idp-groups.md
> +If you want to create a Team of Astronomer users who don't belong to an IdP group, you can enable local Team creation.
```suggestion
If you want to create a Team of Astronomer users, and the team doesn't map to a group in the IdP, you can enable local team creation. 
```

2024-06-26 11:53 UTC, lzdanski commented on software/import-idp-groups.md
> +3. Give the team a name and a description, then select all local users that you want in the Team.
```suggestion
3. Give the team a name and a description, then select all the users that you want in the Team.
```

2024-06-26 12:13 UTC, rujhan-arora-astronomer approved these changes

2024-06-26 13:04 UTC, merged