Update upgrade-astronomer.md
astronomer/docs pull request #3755
Opened 2024-05-17 13:55 UTC by RNHTTR

According to the [maintenance policy](https://docs.astronomer.io/software/release-lifecycle-policy#stable), only 0.34 is supported at this time.

2024-05-17 17:08 UTC, lzdanski requested changes

2024-05-17 17:08 UTC, lzdanski commented on software/upgrade-astronomer.md
> +| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> 0.24 |
```suggestion
| 0.27            | 0.29 or later  | 0.27 -> 0.28 -> 0.34 |
| 0.26            | 0.29 or later  | 0.26 -> 0.28 -> 0.34 |
| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> 0.34 |
```

Is 0.24 right??

2024-05-20 12:03 UTC, jwitz commented on software/upgrade-astronomer.md
> +| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> 0.24 |
```suggestion
| 0.29            | 0.31 or later  | 0.29 -> 0.30 -> Target version |
| 0.27            | 0.29 or later  | 0.27 -> 0.28 -> Target version |
| 0.26            | 0.29 or later  | 0.26 -> 0.28 -> Target version |
| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> Target version |
```
This would future proof the doc so we don't have to change this table with every support policy change

2024-05-20 19:55 UTC, lzdanski approved these changes

2024-05-20 23:19 UTC, RNHTTR commented
I sort of think we should keep this as `0.34` instead of "Target Version". WDYT @tonyHuinker

2024-05-21 19:33 UTC, lzdanski commented on software/upgrade-astronomer.md
> +| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> Target version |
```suggestion
| 0.29            | 0.31 or later  | 0.29 -> 0.30 -> 0.34 |
| 0.27            | 0.29 or later  | 0.27 -> 0.28 -> 0.34 |
| 0.26            | 0.29 or later  | 0.26 -> 0.28 -> 0.34 |
| 0.25            | 0.29 or later  | 0.25 -> 0.28 -> 0.34 |
```

Talked with @RNHTTR about this, and we decided to keep the specific version as a recommendation. Sometimes users can be hesitant to jump many versions in an upgrade, when we make a specific recommendation it helps.

2024-05-21 19:48 UTC, merged