Best Practices guide on upgrading Astro Runtime
astronomer/docs pull request #3767
Opened 2024-05-20 19:35 UTC by merobi-hub

This adds a Best Practices guide on upgrading Astro Runtime.

2024-05-21 21:09 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +sidebar_label: "Upgrading Astro"
```suggestion
sidebar_label: "Upgrading Astro Runtime"
```
unless this it too long (but the others are longer so should be okay) - to clarify that's it's not the Astro platform that is being upgraded

2024-05-21 21:11 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +Keeping the version of Astro Runtime in your projects up-to-date is highly recommended as new versions are released regularly to apply bug fixes, security fixes, and improvements not only to Astro bu
```suggestion
Keeping the version of Astro Runtime in your projects up-to-date is highly recommended as new versions are released regularly to apply bug fixes, security fixes, and improvements to Airflow.
```

2024-05-21 21:12 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +Upgrades can apply breaking changes, particularly in the case of new major versions. The Astro CLI has built-in functionality to identify and help resolve problems. We recommend making use of these f
```suggestion
Upgrades can apply breaking changes, particularly in the case of new major versions. With new minor versions of Airflow, it is typically provider package upgrades that cause issues. The Astro CLI has built-in functionality to identify and help resolve problems. We recommend making use of these features prior to upgrades.
```

2024-05-21 21:15 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +## Best practice guidance
Let's mention our runtime maintenance policy here: https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#astro-runtime-maintenance-policy. And add the guidance that you should be aware of how long your version will be supported and give yourself plenty of time to upgrade.

2024-05-21 21:16 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +## Best practice guidance
Related to above comment, let's also add that Enterprise customers can use org dashboards to monitor the version of all their deployments https://docs.astronomer.io/astro/organization-dashboard#deployment-detail

2024-05-21 21:16 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +- Creating and managing [Deployment](https://docs.astronomer.io/astro/create-deployment)s.
```suggestion
- Creating and managing [Deployments](https://docs.astronomer.io/astro/create-deployment).
```

2024-05-21 21:17 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +### Prepare for upgrades
```suggestion
## Prepare for upgrades
```

2024-05-21 21:17 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +#### Pin provider versions
```suggestion
### Pin provider versions
```

2024-05-21 21:18 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +In this guide, you'll learn:
Let's add org dashboards to this list (but note for Enterprise only)

2024-05-21 21:18 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +New major versions of Astro Runtime can include major upgrades to built-in provider packages that can sometimes include breaking changes.
```suggestion
New major versions of Astro Runtime (which correspond to minor versions of Airflow) can include major upgrades to built-in provider packages that can sometimes include breaking changes.
```

2024-05-21 21:20 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +#### Run upgrade tests
```suggestion
### Run upgrade tests
```

2024-05-21 21:22 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +### Upgrade the Astro Runtime version and deploy to Astro
```suggestion
## Upgrade the Astro Runtime version and deploy to Astro
```

2024-05-21 21:22 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +### Rolling back deployments
```suggestion
## Rolling back deployments
```

2024-05-21 21:22 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +See also [Upgrade Astro Runtime](https://docs.astronomer.io/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli).
```suggestion
## See also 

- [Upgrade Astro Runtime](https://docs.astronomer.io/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli).
```

2024-05-21 21:37 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +### Prepare for upgrades
I left some comments on formatting below, but now that I look at it, I didn't realize we had the step by step upgrading instructions in https://docs.astronomer.io/astro/upgrade-runtime. I'm not sure there's benefit to repeating any of those steps here (and generally we're trying to avoid duplicating content for maintenance purposes). But I think the benefit of this doc could be to say 1) best practice guidance is to do _all_ the optional steps in that doc, and 2) use features like org dashboards and rollbacks for upgrading promptly with guardrails. Also want to pose this to the docs team and see what they think.

2024-05-22 15:58 UTC, merobi-hub commented on astro/best-practices/upgrading-astro.md
> +### Prepare for upgrades
@kentdanas I cut out the duplicative step-by-step guidance and reframed/reorganized the doc to make it higher-level and supplemental. In doing this, I felt that the section headings no longer made sense, so this includes edits to those, as well. Please lmk what you think!

2024-05-22 15:59 UTC, merobi-hub commented
@kentdanas This includes minor wording fixes in the maintenance policy doc that I spotted while making revisions to the guide. Would be happy to revert them, though.

2024-05-22 16:59 UTC, kentdanas requested changes
@merobi-hub this looks great. My comments are just moving things around, to have one best practice guidance section with 3 subsections. Definitely double check me on the formatting, I may not have gotten it right editing directly in GH :)

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +<p align="center">
In the deploy preview it doesn't look like these are centering. But I think if you tab them in under the bullet point they'll align with the bullet.

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +In this guide, you'll learn about best practices to follow when:
```suggestion
In this guide, you'll learn about best practices to follow when upgrading Astro Runtime, including:
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +- Upgrading Astro Runtime.
```suggestion
- Monitoring for needed upgrades with Organization Dashboards and the Astro Runtime maintenance and lifecycle policy.
- Preparing to upgrade safely with upgrade tests. 
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +Keeping the version of Astro Runtime in your projects up-to-date is highly recommended as new versions are released regularly to apply bug fixes, security fixes, and improvements.
```suggestion
Keeping the version of Astro Runtime in your projects up-to-date is highly recommended as new versions are released regularly to apply bug fixes, security fixes, and improvements. Astro provides features to help with every step of the upgrade process.
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +
```suggestion
### Monitoring for upgrades

It is best practice to upgrade your Deployments to new Astro Runtime versions as promptly as possible.

Enterprise users can use organization dashboards to check whether a Deployment's Astro Runtime version is currently supported. See [Organization dashboard](https://docs.astronomer.io/astro/organization-dashboard#deployment-detail) for details. This is especially helpful in cases where your organization has many Deployments to track.

We also recommend reviewing the [Astro Runtime maintenance and lifecycle policy](https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#astro-runtime-maintenance-policy) for maintenance duration information so you have plenty of time to upgrade before the maintenance window for your current version closes.

```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +We also recommend reviewing the [Astro Runtime maintenance and lifecycle policy](https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#astro-runtime-maintenance-policy) for maintenance du
```suggestion
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +Upgrades can include breaking changes, particularly in the case of new major versions. Provider package upgrades in new minor versions of the underlying Airflow package can also cause issues. The Ast
```suggestion
### Upgrading smoothly 

Upgrades can include breaking changes, particularly in the case of new major versions. Provider package upgrades in new minor versions of the underlying Airflow package can also cause issues. The Astro CLI has [built-in functionality](https://docs.astronomer.io/astro/cli/test-your-astro-project-locally#test-before-an-astro-runtime-upgrade) to keep such changes from breaking your DAGs. We recommend making use of this feature prior to every upgrade.
```
Let's also move the contents of "Upgrading Astro Runtime" into this subsection.

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +
```suggestion
### Rolling back Deployments
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +:::
```suggestion
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +## Upgrading Astro Runtime
Mentioned above, but let's move this under the best practices subsection above. So we just have one section talking about each, since we aren't going into implementation details here.

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +In the case of emergencies, a rollback to a previous deploy can be used to downgrade the Astro Runtime version. Astro's rollback functionality, akin to Git's `revert` feature, makes use of Astro's de
```suggestion
In the case of emergencies, a rollback to a previous deploy can be used to downgrade the Astro Runtime version. Astro's rollback functionality, akin to Git's `revert` feature, makes use of Astro's deploy history. Rollbacks revert project code only, keeping environment variables and other configuration unchanged. Also, downgrading erases any data related to newer features. For these reasons, we recommend viewing rollbacks only as a measure of last resort.


:::danger

Astronomer recommends triggering Deployment rollbacks only as a last resort for recent deploys that aren't working as expected. Deployment rollbacks can be disruptive, especially if you triggered multiple deploys between your current version and the rollback version. See [What happens during a deploy rollback](https://docs.astronomer.io/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli:~:text=What%20happens%20during%20a%20deploy%20rollback).

:::

:::tip

The `upgrade-test` command can also be used to test the current Runtime version against a _downgraded_ version.

:::
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +The only way to downgrade the version of Astro Runtime in a Deployment is to trigger a rollback to a previous deploy on Astro. To do so, follow the guidance in [Roll back to previous deploys using de
```suggestion
```

2024-05-22 16:59 UTC, kentdanas commented on astro/best-practices/upgrading-astro.md
> +## General best practices
```suggestion
## Best practice guidance
```

2024-05-22 17:50 UTC, kentdanas approved these changes
Looks great! @jwitz @lzdanski this one is ready for a quick copy edit

2024-05-24 14:00 UTC, jwitz requested changes
This is shaping up great! Requesting changes because I'd like to reframe the "Upgrade Smoothly" step to focus more on reading the documentation rather than the specific CLI steps within the docs.

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +Astro includes features that make upgrading to the latest version of Astro Runtime easy and, more importantly, safe. When taking advantage of these features, you should keep a few best practices in m
```suggestion
Astro includes features that make upgrading to the latest version of Astro Runtime easy and, more importantly, safe. When leveraging these features, follow these best practices ensure that your Deployments remain stable after you upgrade:
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +## Overview
```suggestion
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +## Overview
Because the first section is an overview itself, we tend not have an explicit "Overview" topic to simplify the doc and get to the core content faster

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +In this guide, you'll learn about best practices to follow when upgrading Astro Runtime, including:
```suggestion
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +- Performing a rollback to an earlier deployment and Runtime version in an emergency.
```suggestion
- Monitor for upgrade opportunities using [Organization dashboards](https://www.astronomer.io/docs/astro/organization-dashboard), as well as by following the [Astro Runtime maintenance and lifecycle policy](https://www.astronomer.io/docs/astro/runtime-version-lifecycle-policy). 
- Check [Upgrade Astro Runtime](https://docs.astronomer.io/astro/upgrade-runtime) for advisories on the specific version you're upgrading to.
- Prepare to upgrade safely using [upgrade tests](https://www.astronomer.io/docs/astro/cli/test-your-astro-project-locally#test-before-an-astro-runtime-upgrade). 
- In the case of a malfunction after upgrading, revert to your original Astro Runtime version using [deploy rollbacks](https://www.astronomer.io/docs/astro/deploy-history).

Use this document to learn more about each of these best practices for upgrading Astro Runtime.
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +Keeping the version of Astro Runtime in your projects up-to-date is highly recommended as new versions are released regularly to apply bug fixes, security fixes, and improvements. Astro provides feat
```suggestion
It's best practice to keep your running Astro Runtime versions up-to-date. Astro Runtime upgrades include new Airflow features, as well as bug fixes, security fixes, and improvements to Astro. 

```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +It is best practice to upgrade your Deployments to new Astro Runtime versions as promptly as possible.
```suggestion
```
This feels redundant to the first point

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +Enterprise users can use organization dashboards to check whether a Deployment's Astro Runtime version is currently supported. See [Organization dashboard](https://docs.astronomer.io/astro/organizati
```suggestion
Astro users on the Enterprise tier can use Organization dashboards to check whether their currently running Astro Runtime versions are currently supported, as well as how much time is left before they become unsupported. This is especially helpful in cases where your organization has many Deployments to track. See [Organization dashboards](https://docs.astronomer.io/astro/organization-dashboard#deployment-detail) for steps to access these dashboards.
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +We also recommend reviewing the [Astro Runtime maintenance and lifecycle policy](https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#astro-runtime-maintenance-policy) for maintenance du
```suggestion
If you don't have the Enterprise tier of Astro, you can still reference the [Astro Runtime maintenance and lifecycle policy](https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#astro-runtime-maintenance-policy) to see when you'll need to upgrade your Deployments to a new version of Astro Runtime.
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +### Upgrading smoothly
```suggestion
### Performing an upgrade
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +Upgrades can include breaking changes, particularly in the case of new major versions. Provider package upgrades in new minor versions of the underlying Airflow package can also cause issues. The Ast
```suggestion
Astro Runtime upgrades can include breaking changes, especially when you upgrade to a new major version. Provider package upgrades in new minor versions of the underlying Airflow package can also cause issues. The Astro CLI has [built-in functionality](https://docs.astronomer.io/astro/cli/test-your-astro-project-locally#test-before-an-astro-runtime-upgrade) to keep such changes from breaking your DAGs. Astronomer recommends making use of this feature prior to every upgrade.
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +		```text
Is this the dependency compare report? Maybe we should just take a single example from this list and elaborate on it in some more detail. Right now, I'm not sure a user could make use of this block on its own.

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +### Upgrading smoothly
Both of these actions are included as steps in [Upgrade Astro Runtime](https://www.astronomer.io/docs/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli). I'd prefer if we made the main focus of this topic "Use the process documented in [Upgrade Astro Runtime](https://www.astronomer.io/docs/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli) as the basis for all upgrades. It gives step-by-step guidance on completing an upgrade, as well as version specific advice. In particular, the following steps should be followed for a smooth upgrade:"

It's a subtle edit, but I'd like to frame reading the doc as the primary best practice, and to get that stated as soon as possible in the topic.

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +### Rolling back Deployments
```suggestion
### Roll back Deployments after a broken upgrade
```

2024-05-24 14:00 UTC, jwitz commented on astro/best-practices/upgrading-astro.md
> +In the case of emergencies, a rollback to a previous deploy can be used to downgrade the Astro Runtime version. Astro's rollback functionality, akin to Git's `revert` feature, makes use of Astro's de
```suggestion
In the case of emergencies, you can roll back to your previous deploy to downgrade the Astro Runtime version. Astro's rollback functionality is similar to the Git `revert` command. Rollbacks revert project code only, keeping environment variables and other configuration unchanged. Also, downgrading erases any data related to newer features. For these reasons, Astronomer recommends using rollbacks only as a last resort.
```

2024-05-28 15:28 UTC, ephraimbuddy commented on astro/best-practices/upgrading-astro-runtime.md
> +		- A Dependency Compare report listing the upgrades, additions and removals coming in the new Astro version and underlying Airflow package. For example, a "Major Updates" section lists the packages
```suggestion
		- A Dependency Compare report listing the upgrades, additions and removals coming in the new Astro runtime version and underlying Airflow package. For example, a "Major Updates" section lists the packages receiving new major versions, and a "Minor Updates" lists the packages receiving new minor versions:
```
?

2024-05-30 09:04 UTC, jwitz approved these changes
Just minor formatting, otherwise LGTM! This will be a great doc to have as reference

2024-05-30 09:04 UTC, jwitz commented on astro/best-practices/upgrading-astro-runtime.md
> +For more details about the `upgrade-test` command, see [Testing your Astro project locally](https://docs.astronomer.io/astro/cli/test-your-astro-project-locally#test-before-an-astro-runtime-upgrade).
```suggestion
For more details about the `upgrade-test` command, see [Testing your Astro project locally](cli/test-your-astro-project-locally.md#test-before-an-astro-runtime-upgrade).
```

2024-05-30 09:04 UTC, jwitz commented on astro/best-practices/upgrading-astro-runtime.md
> +### Roll back Deployments after a broken upgrade
```suggestion
### Roll back Deployments after a broken upgrade

```

2024-05-30 09:04 UTC, jwitz commented on astro/best-practices/upgrading-astro-runtime.md
> +- [Upgrade Astro Runtime](https://docs.astronomer.io/astro/upgrade-runtime#step-3-optional-run-upgrade-tests-with-the-astro-cli).
```suggestion
- [Upgrade Astro Runtime](upgrade-runtime.md#step-3-optional-run-upgrade-tests-with-the-astro-cli).
```

2024-05-30 09:04 UTC, jwitz commented on astro/best-practices/upgrading-astro-runtime.md
> +description: "How to upgrade your version of Astro Runtime safely and rollback if necessary."
```suggestion
description: "A list of best practices to ensure that your Astro Runtime upgrades are safe and easy."
```

2024-05-30 16:38 UTC, merged