Qdrant integration tutorial
astronomer/docs pull request #3771
Opened 2024-05-22 20:45 UTC by merobi-hub

This adds a Learn guide based on [Semantic querying with Airflow and Astronomer](https://qdrant.tech/documentation/examples/qdrant-airflow-astronomer/).

2024-05-23 21:11 UTC, kentdanas requested changes
@merobi-hub thanks for this! Suggestions are all to bring it in line with the formatting and language we use for our other integration tutorials. You may need to double check indentation and numbering, but otherwise should be straightforward.

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +### Run the DAG
```suggestion
## Step 5: Run your DAG
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +Head over to your terminal and run `astro dev start`.
```suggestion
1. Run `astro dev start` in your Astro project to start Airflow and open the Airflow UI at `localhost:8080`.
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +A local Airflow container should spawn. You can now access the Airflow UI at http://localhost:8080. Visit our DAG by clicking on **books_recommend**.
```suggestion
2. In the Airflow UI, run the `books_recommend` DAG by clicking the play button. You'll be asked for input about your book preference.
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +Hit the **PLAY** button on the right to run the DAG. You’ll be asked for input about your preference, with the default value already filled in.
```suggestion
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +![Qdrant demo DAG](/img/integrations/qdrant-demo-dag.png)
Let's move this screenshot up into the Write the DAG section where you describe the tasks.

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +After your DAG run completes, you should be able to see the output of your search in the logs of the `search_qdrant` task.
```suggestion
3. View the output of your search in the logs of the `search_qdrant` task.
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +There you have it, an Airflow pipeline that interfaces with Qdrant! Feel free to fiddle around and explore Airflow. The following references might come in handy.
```suggestion
```

2024-05-23 21:11 UTC, kentdanas commented on learn/airflow-qdrant.md
> +- [Astronomer Documentation](https://docs.astronomer.io/)
```suggestion
```

2024-05-28 19:10 UTC, kentdanas approved these changes
Looks great @merobi-hub! A few very minor comments, otherwise good to have this copy edited. @jwitz @lzdanski if one of you could take a quick look that would be awesome :)

2024-05-28 19:10 UTC, kentdanas commented on learn/airflow-qdrant.md
> +```bash
If you tab these in they'll render in line with the numbered steps

2024-05-28 19:10 UTC, kentdanas commented on learn/airflow-qdrant.md
> +## Step 3: Add the data corpus
```suggestion
## Step 3: Add your data
```

2024-05-28 19:10 UTC, kentdanas commented on learn/airflow-qdrant.md
> +Add the following configuration to your `.env` file to create Airflow connections between Airflow and HuggingFace and Qdrant.
```suggestion
Add the following to your `.env` file to create Airflow connections between Airflow and HuggingFace and Qdrant. Make sure to update with your HuggingFace access token and Qdrant instance details.
```

2024-05-30 21:17 UTC, lzdanski requested changes

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +Airflow is useful when running operations in Qdrant based on data events or building parallel tasks for generating vector embeddings. By using Airflow, you can set up monitoring and alerts for your p
```suggestion
Airflow provides useful operational and orchestration when running operations in Qdrant based on data events or building parallel tasks for generating vector embeddings. By using Airflow, you can set up monitoring and alerts for your pipelines for full observability.
```

something like that? shift from active voice and a little more specific in relating the qdrant operations to Airflow options?

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +- A [HuggingFace token](https://huggingface.co/docs/hub/en/security-tokens) to generate embeddings.
Everytime I see `huggingface` it makes me think of Alien.

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +2. To use Qdrant within Airflow, install the Qdrant Airflow provider by adding the following to your `requirements.txt` file:
```suggestion
2. To use Qdrant in Airflow, install the Qdrant Airflow provider by adding the following to your `requirements.txt` file:
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +    ```
```suggestion

    ```text
    apache-airflow-providers-qdrant==1.1.0
    ```
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +Add the following to your `.env` file to create Airflow connections between Airflow and HuggingFace and Qdrant. Make sure to update with your HuggingFace access token and Qdrant instance details.
```suggestion
Add the following code to your `.env` file to create Airflow connections between Airflow and HuggingFace and Qdrant. Make sure to update the sample code with your HuggingFace access token and Qdrant instance details.
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +Paste the following sample data into a file called `books.txt` within your `include` directory.
```suggestion
Paste the following sample data into a file called `books.txt` in your `include` directory.
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +2. Copy the following code into the file.
```suggestion
2. Copy the following code into the `books_recommend.py` file.
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +    ```python
You might want to put this code into the `details` formatting feature. It lets users expand/hide the code examples in a formatted box. The end of the `Hosted worker types` docs section has one - https://www.astronomer.io/docs/astro/configure-worker-queues#hosted-worker-types

```
<details>
<strong> Recommend books DAG</strong>

code
</details>
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +This DAG consists of 6 tasks that generate embeddings in parallel for the data corpus and perform semantic retrieval based on user input.
```suggestion
This QDrant Demo DAG consists of six tasks that generate embeddings in parallel for the data corpus and perform semantic retrieval based on user input.
```
numbers fewer than 10 are colloquially spelled out.

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +- `init_collection`: This task initializes a collection in the Qdrant database, where we will store the vector representations of the book descriptions. The `recreate_collection()` function deletes a
```suggestion
- `init_collection`: This task initializes a collection in the Qdrant database, where you store the vector representations of the book descriptions. The `recreate_collection()` function deletes a collection first if it already exists. Trying to create a collection that already exists throws an error.
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +- `embed_user_preference`: Here, we take a user’s input and convert it into a vector using the same pre-trained model used for the book descriptions.
```suggestion
- `embed_user_preference`: This task takes a user’s input and converts it into a vector using the same pre-trained model used for the book descriptions.
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +    ![Qdrant demo DAG](/img/integrations/qdrant-demo-dag.png)
```suggestion
    ![Screenshot of the graph view for the Qdrant demo DAG, with the each of the six steps shown.](/img/integrations/qdrant-demo-dag.png)
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +    ![Qdrant reference input](/img/integrations/qdrant-reference-input.png)
```suggestion
    ![Qdrant reference input shows an example of the UI where Airflow prompts you to enter your book preference.](/img/integrations/qdrant-reference-input.png)
```

2024-05-30 21:17 UTC, lzdanski commented on learn/airflow-qdrant.md
> +    ![Qdrant output](/img/integrations/qdrant-output.png)
```suggestion
    ![Screenshot of the Qdrant output example, that shows the title and description of the book recommendation.](/img/integrations/qdrant-output.png)
```

2024-05-31 15:04 UTC, lzdanski approved these changes
One small thing! I think this will help emphasize that the code is in the expandable section. Looks fantastic!

2024-05-31 15:04 UTC, lzdanski commented on learn/airflow-qdrant.md
> +2. Copy the following code into the `books_recommend.py` file.
```suggestion
2. Copy the following **Recommend books DAG** code into the `books_recommend.py` file.
```

2024-05-31 15:48 UTC, merged