Remove priority definitions and add escalation policy
astronomer/docs pull request #3772
Opened 2024-05-22 21:35 UTC by RNHTTR

2024-05-23 18:24 UTC, collinmcnulty approved these changes

2024-05-29 14:06 UTC, lzdanski requested changes
These are mostly style and voice changes! The commit I made makes the severity examples actual headers (H3 level) instead of just **bold**, so that you can link directly to them from a ticket if you need to explain why something was changed from P2 to P3 or a similar scenario.

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +Additionally, if the immediate problem is solved but there are follow up investigations ongoing, those follow ups will be conducted in a separate ticket at a lower priority.
```suggestion
Additionally, if the immediate problem is solved, but follow-up investigations continue, those investigations are conducted in a separate ticket at a lower priority.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +Ability to use Astro is severely impaired but does not affect critical, previously working pipelines in production.
```suggestion
Your ability to use Astro is severely impaired, but does not affect any critical, previously working pipelines in production.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- You are unable to deploy code to your Deployment, but existing DAGs and tasks are running as expected.
```suggestion
- You can't deploy code to your Deployment, but existing DAGs and tasks run as expected.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- A newly deployed production DAG is not working, even though it ran successfully in a development or test environment.
```suggestion
- A newly deployed production DAG is not working, even though it worked successfully in a development or test environment.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- A newly deployed DAG is not working in a development Deployment, even though it ran successfully in a local environment using the Astro CLI.
```suggestion
- A newly deployed DAG is not working in a development Deployment, even though it worked successfully in a local environment using the Astro CLI.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- You need to [modify a Hybrid cluster setting](manage-hybrid-clusters.md) that affects your cluster's performance but isn't required to run tasks, such as changing the size of your cluster's databas
```suggestion
- You need to [modify a Hybrid cluster setting](manage-hybrid-clusters.md) that affects your cluster's performance, but isn't required to run tasks, such as changing the size of your cluster's database or adding a new VPC peering connection.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- Astro CLI usage is impaired (for example, there are incompatibility errors between installed packages).
```suggestion
- Astro CLI usage is impaired. For example, there are incompatibility errors between installed packages.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +- You have lost the ability to use a [Public Preview](https://docs.astronomer.io/astro/feature-previews) feature that does not affect general services.
```suggestion
- You lost the ability to use a [Public Preview](https://docs.astronomer.io/astro/feature-previews) feature that does not affect general services.
```

2024-05-29 14:06 UTC, lzdanski commented on astro/astro-support.md
> +Astro is fully usable but you have a question for our team.
```suggestion
Astro is fully usable, but you have a question for the Support team.
```
Does this need to be specific? Support? Dev? General team?

2024-05-29 16:20 UTC, RNHTTR commented on astro/astro-support.md
> +Here are the four ticket priorities with descriptions and examples for each:
I don't think this is accurate. We have 4 priorities (P1 through P4), and there are examples for each, but the priorities themselves aren't examples.

2024-05-29 16:34 UTC, pgagnon commented on astro/astro-support.md
> +Business and Enterprise customers can request escalated support for an existing ticket. To request a support escalation, email escalations@astronomer.io with the following information:
I think we clarify what outcome customers can expect from an escalation.

2024-05-29 16:35 UTC, lzdanski commented on astro/astro-support.md
> +Here are the four ticket priorities with descriptions and examples for each:
Here's a take-two on it!

2024-05-29 18:04 UTC, RNHTTR commented on astro/astro-support.md
> +Business and Enterprise customers can request escalated support for an existing ticket. To request a support escalation, email escalations@astronomer.io with the following information:
how's this?

2024-05-29 18:27 UTC, pgagnon commented on astro/astro-support.md
> +Business and Enterprise customers can request escalated support for an existing ticket. To request a support escalation, email escalations@astronomer.io with the following information:
👍

2024-05-29 18:31 UTC, lzdanski submitted a review, later dismissed
One final suggestion!

2024-05-29 18:31 UTC, lzdanski commented on astro/astro-support.md
> +When an escalation request is made, the on-call shift manager will be alerted to the ticket and will evaluate the escalation request. The on-call shift manager will either assume ownership of the tic
```suggestion
When you make an escalation request, it alerts the on-call shift manager to the ticket, who evaluates the escalation request. The on-call shift manager either assumes ownership of the ticket or ensures meaningful and timely progress is made on the ticket.
```

2024-05-30 18:43 UTC, lzdanski approved these changes

2024-05-30 18:44 UTC, merged