Astronomer Software 0.34.2 release notes
astronomer/docs pull request #3775
Opened 2024-05-23 16:23 UTC by jwitz

2024-05-24 13:15 UTC, danielhoherd commented on software/release-notes.md
> +Release date: May 23, 2024
Needs to be updated

2024-05-24 13:17 UTC, danielhoherd commented on software/version-compatibility-reference.md
> +| 0.34.2                      | 1.10.0                                |
```suggestion
| 0.34.2                      | 1.10.1                                |
```

2024-05-31 04:53 UTC, rishkarajgi commented on software/release-notes.md
> +Release date: May 23, 2024
Please update to May 31

2024-05-31 06:58 UTC, Priyanka13Astro commented on software/version-compatibility-reference.md
> +| 0.34.2                      | 1.10.0                                |
now the supported airflow Helm chart version is 1.10.2

2024-05-31 07:10 UTC, Priyanka13Astro commented on software/release-notes.md
> +- Fixed an issue where upgrading within the 0.34 series could disrupt external Elasticsearch configurations.
Github link not mentioned

2024-05-31 10:00 UTC, jwitz commented on software/release-notes.md
> +Release date: May 23, 2024
```suggestion
Release date: May 31, 2024
```

2024-05-31 12:44 UTC, pgvishnuram commented on software/release-notes.md
> +- Fixed an issue where
is this is double typo

2024-05-31 13:38 UTC, danielhoherd requested changes
Seems mostly good. There are some comments that need to be addressed before merging.

2024-05-31 16:05 UTC, Simpcyclassy commented on software/release-notes.md
> +- Fixed an issue where
```suggestion
```

2024-05-31 17:12 UTC, jwitz commented on software/release-notes.md
> +- Fixed an issue where tasks on a Deployment could start to fail if the Deployment used a custom resource strategy, used the Kubernetes executor, and attempted to run many tasks at once. <!-- https:/
```suggestion
- Fixed an issue where larger DAG deploys had significant performance issues.
- Fixed an issue where Deployments using custom resources would be reverted to using AUs when you upgraded the Astronomer Software platform using Helm. 
- Fixed an issue where the default `astroUnitsEnabled` value in `values.yaml` was not respected when creating Deployments via the Houston API, resulting in Deployment creation failing when the resource strategy is not explicitly specified. 
- Fixed an issue where using a service account to deploy DAGs without the Astro CLI would result in the service account's `lastUsedAt` value not updating as expected.
- Fixed an issue where creating Deployments would fail when using the the `airflowStratV2` PGBouncer calculation strategy. 
- Fixed an issue where upgrading within the 0.34 series could disrupt external Elasticsearch configurations.
- Fixed an issue where tasks on a Deployment could start to fail if the Deployment used a custom resource strategy, used the Kubernetes executor, and attempted to run many tasks at once. 
```

2024-05-31 17:13 UTC, jwitz commented
Addressed comments, merging!

2024-05-31 17:13 UTC, merged