Add deploy with API details
astronomer/docs pull request #3779
Opened 2024-05-23 21:19 UTC by lzdanski

Resolves #3750

2024-05-28 10:39 UTC, jwitz requested changes
Some initial feedback, I think the steps for each deploy type need some more love / detail. I can't find any information about locating a user's image repository or image tag, which are both essential to running this script. I would expect to be able to follow the steps to trigger a deploy manually, even if I need to view other docs as well. Right now, that's not the case.

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +While you can deploy code to Astro using the GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro A
```suggestion
While you can deploy code using the Astro GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro API is the most straightforward way to deploy code and requires very few additional dependencies, meaning it is compatible with most CI/CD configurations.
```

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +While you can deploy code to Astro using the GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro A
We mention lack of Docker in the original edit as a benefit, but I see Docker commands all over the scripts and steps. Can we get clarification on what the actual benefit is here? I think customers are more interested in that you no longer have to install the Astro CLI itself, rather than Docker.

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +Instead of using the other code deploy options, you can instead use the Astro API Deploy endpoints to perform `IMAGE_ONLY`, `DAG_ONLY`, or both `IMAGE_AND_DAG` Deploys.
```suggestion
If the Astro API has access to your Astro project files, you can use the Astro API `deploy` endpoints to complete an image deploy or DAG deploy. You can then implement scripts to automate deploys as a workaround to not using the Astro CLI or Astro GitHub integration.
```
How does this code-level detail help the user understand the utility of the API? IMO we are surfacing this too soon - I tried to elaborate more on the benefit of the API and the general practice of deploying code using the API

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +This guide contains an example of an entire deploy flow and the respective scripts that you can use to deploy code with the Astro API using bash scripts. It also includes an example of a script that
```suggestion
This best practice guide walks through the steps that are necessary to deploy code to Astro using the Astro API. It also provides example bash scripts that implement these steps for different types of deploy workflows in your own CI/CD pipelines.
```
Second sentence repetitive of first or am I missing a detail

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +This guide highlights the following Astro features to use for automating code deploys:
```suggestion
This guide highlights the following Astro features:
```

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +- At least one Astro Deployment
Link to create a deployment docs?

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    - `AIRFLOW_PROJECT_PATH` - The path where your Airflow project exists.
```suggestion
    - `AIRFLOW_PROJECT_PATH` - The path where your Airflow project exists.
```
Rewrite to "Astro project" across the whole guide? And what if you're only deploying DAGS?

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +- The following values configured:
Why are we referring to these as the script environment variable values rather than the actual objects? E.g. `ORGANIZATION_ID` > Your Organization ID

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    - `DEPLOYMENT_ID`
We don't explain how to find these values in this doc, nor do we link to where to find that info. We should do at least one of those.

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    - `DEPLOYMENT_ID`
The configuration is in the script, so these don't have to be preconfigured.

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    docker login images.astronomer.cloud -u cli -p $ASTRO_API_TOKEN
`ASTRO_API_TOKEN` doesn't necessarily need to be configured as an environment variable, what if we just said `<your-astro-api-token>` so that users can configure the API token as they see fit?

2024-05-28 10:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +1. Create the `Deploy`
This step provides very little context for the actual action the user would be taking. Even if we don't provide a whole API example call, we should at least explain that this is the construction of an API call and also explain how to get those 4 values.

2024-05-29 21:05 UTC, kentdanas commented
@lzdanski is there a reason we're putting this in the Best Practices section instead of the Deploy code section? I think of the Best practices as higher level guidance on when to use which Astro features or combinations of features, but this is only talking about one method of deploying (e.g. for a best practice doc on deploying, I would expect guidance on when to use which method out of all the ones available). It seems to me like it should be under Deploy code as another option there, but maybe I'm missing something

2024-05-30 15:12 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +While you can deploy code using the Astro GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro API
```suggestion
While you can deploy code using the Astro GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro API is the most straightforward way to deploy code without using the Astro CLI and requires very few additional dependencies, meaning it is compatible with most CI/CD configurations.
```

2024-05-31 09:39 UTC, jwitz requested changes
A lot more tech review, I still think there's missing steps and info. Edits should apply to all other sections as well

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +- At least one [Astro Deployment](create-deployment.md)
```suggestion
- Sufficient permissions to deploy code to your Astro Deployments.
- At least one [Astro Deployment](create-deployment.md).
- An [Astro project](cli/develop-project.md) that's accessible from the machine where you're using the Astro API.
```

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +## With DAG-only deploy enabled
```suggestion
## With DAG-only deploys enabled
```

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +1. Create the `Deploy` API call using the `IMAGE_AND_DAG` type. This action creates an object that represents the intent to deploy code to a Deployment.
```suggestion
1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `IMAGE_AND_DAG`. This action creates an object that represents the intent to deploy code to a Deployment. See the [Astro API documentation](https://www.astronomer.io/docs/api/platform-api-reference/deploy/create-deploy) for request usage and examples.
```

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    :::note
```suggestion
    :::info
```
Pls no more notes 🙏 😭 🙏 😭🙏 😭🙏 😭🙏 😭🙏 😭🙏 😭

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    Make sure to clean up the `dags.tar` file after uploading.
Would it make more sense to have this after the next step?

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +7. Upload the tar file by making a `PUT` call using the `dagsUploadURL` that you retrieved in Step 2. In this call, it is mandatory to pass the following. Then, save the `versionID` from the response
- To what endpoint?
- Second sentence seems to be missing some details.
- I don't see the relation between the code fence and the step.

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +8. Finalize the deploy. See [Finalize the deploy](https://docs.astronomer.io/docs/api/platform-api-reference/deploy/finalize-deploy) for more information about the API request.
```suggestion
8. Using your `DeployId`, make a request to finalize the deploy. See [Astro API documentation](https://docs.astronomer.io/docs/api/platform-api-reference/deploy/finalize-deploy) for more information about formatting the API request.
```
FYI in case this doesn't get reviewed before I leave, we should really update these docs.

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +1. Create the `Deploy` API call using the `IMAGE_AND_DAG` type. This action creates an object that represents the intent to deploy code to a Deployment.
The user also needs to copy the `DeployID` that's returned in this step! That's a required value for finalizing the deploy later on.

2024-05-31 09:39 UTC, jwitz commented on astro/best-practices/deploy-with-api.md
> +    - On `Success`, the deploy process has completed. Pass `versionID` in the requested body.
I don't understand this process at all. If the deploy was finalized and succeeded, why do we need to pass any more information?

2024-06-18 22:56 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +    Make sure to clean up the `dags.tar` file after uploading.
We can do this after the upload is completed

2024-06-18 22:57 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +7. Upload the tar file by making a `PUT` call using the `dagsUploadURL` that you retrieved in Step 2. In this call, it is mandatory to pass the following. Then, save the `versionID` from the response
the url is generated in the CreateDeploy Endpoint

2024-06-18 22:59 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +    - On `Success`, the deploy process has completed. Pass `versionID` in the requested body.
On Step 7, we are uploading the dags tarball to the blob storage, but our services have no idea what versionId was uploaded since that information is only known when the upload is completed. Passing the VersionId in finalizeDeploy is what triggers the deploys process

2024-06-19 04:43 UTC, sunkickr commented on astro/best-practices/deploy-with-api.md
> +While you can deploy code using the Astro GitHub Integration, the Astro CLI, or by configuring a CI/CD pipeline, you might prefer to use the Astro API to automate deploying code. Using the Astro API
This is good with me

2024-06-19 04:44 UTC, sunkickr commented on astro/best-practices/deploy-with-api.md
> +If the Astro API has access to your Astro project files, you can use the Astro API `deploy` endpoints to complete an image deploy or DAG deploy. You can then implement scripts to automate deploys as
good with me

2024-06-19 04:45 UTC, sunkickr commented on astro/best-practices/deploy-with-api.md
> +## With DAG-only deploy enabled
I'm actually not sure what we usually call this

2024-06-19 04:46 UTC, sunkickr commented on astro/best-practices/deploy-with-api.md
> +1. Create the `Deploy` API call using the `IMAGE_AND_DAG` type. This action creates an object that represents the intent to deploy code to a Deployment.
@kushalmalani could you confirm?

2024-06-19 04:50 UTC, sunkickr commented on astro/best-practices/deploy-with-api.md
> +    docker login images.astronomer.cloud -u cli -p $<your-api-token>
@kushalmalani what do you think?

2024-06-19 04:57 UTC, sunkickr approved these changes
I think we should make many of the changes suggested by @jwitz. Other than that this PR looks good

2024-06-20 19:12 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +    docker login images.astronomer.cloud -u cli -p $<your-api-token>
Yes, the $ sign is only for the script.

2024-06-20 19:12 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +1. Create the `Deploy` API call using the `IMAGE_AND_DAG` type. This action creates an object that represents the intent to deploy code to a Deployment.
Yes, that is right. You need the deployId to perform FinalizeDeploy

2024-06-20 21:18 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +3. Build the image using the `imageRepository` and `imageTag` values that you retrieved in Step 2, as well as your Astro project path.
```suggestion
3. Build the image using the `imageRepository` and `imageTag` values that you retrieved in Step 1, as well as your Astro project path.
```

2024-06-20 21:18 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +4. Push the image using the `imageRepository` and `imageTag` values that you retrieved in Step 2.
```suggestion
4. Push the image using the `imageRepository` and `imageTag` values that you retrieved in Step 1.
```

2024-06-24 03:54 UTC, paolaperaza approved these changes
A few minor comments here @lzdanski! Awesome job putting this together 🎉

2024-06-24 03:54 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +The following steps describe the different actions that the script performs to deploy a complete Astro project.
```suggestion
The following steps describe the different actions that the script performs to deploy a complete Astro project. A project deploy INCLUDES...
```

I'd very briefly clarify what this means!

2024-06-24 03:54 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +### Project deploy
```suggestion
### Complete project deploy
```

Maybe this helps?

2024-06-24 03:54 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +### Project deploy
Just be consistent if you end up changing the above, if not nothing here

2024-06-24 03:54 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +## Trigger deploys when files change
Is this actually the absolute recommended way above the H2 process defined above? If so I might make it more explicit in the overview of this doc as a whole, change the title to be `(Recommended)`, or be more explicit below?

2024-06-24 13:38 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `DAG_ONLY`. Store the values for `id` and `dagsUploadURL` that are returned in the r
```suggestion
1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `DAG_ONLY`. Store the values for `x-ms-version-id` and `dagsUploadURL` that are returned in the response to use in the following steps.
```

2024-06-24 13:39 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +3. Upload the tar file by making a `PUT` call using the `dagsUploadURL` that you retrieved in Step 2. In this call, it is mandatory to pass the `x-ms-blob-type` as `BlockBlob`. Then, save the `versio
```suggestion
3. Upload the tar file by making a `PUT` call using the `dagsUploadURL` that you retrieved in Step 2. In this call, it is mandatory to pass the `x-ms-blob-type` as `BlockBlob`. Then, save the `x-ms-version-id` from the response header.
```

2024-06-24 13:39 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +   - On `Success`, your DAGs have successfully uploaded and a `versionID` of the DAGs tarball is generated. Pass this `versionID` in the requested body to finish your updates.
```suggestion
   - On `Success`, your DAGs have successfully uploaded and a `x-ms-version-id` of the DAGs tarball is generated. Pass this `versionID` in the requested body to finish your updates.
```

2024-06-24 13:40 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +   - On `Success`, your DAGs have successfully uploaded and a `versionID` of the DAGs tarball is generated. Pass this `versionID` in the requested body to finish your updates.
```suggestion
   - On `Success`, your DAGs have successfully uploaded and a `x-ms-version-id` of the DAGs tarball is generated. Pass this `x-ms-version-id` in the requested body to finish your updates.
```

2024-06-24 13:41 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +### Project deploy
```suggestion
### Complete project deploy
```

2024-06-24 14:19 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +## Trigger deploys when files change
I think i might like to have this as an **Example** implementation vs a recommended maybe? @kushalmalani, what do you think?

2024-06-24 14:34 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +This best practice guide walks through the steps that are necessary to deploy code to Astro using the Astro API. It also provides example bash scripts that implement these steps for different types o
```suggestion
This best practice guide walks through the steps that are necessary to deploy code to Astro using the Astro API. It also provides example bash scripts that implement these steps for different types of deploy workflows in your own CI/CD pipelines. This example uses Docker to build the image, but you can use a similar tool like [kaniko](https://github.com/GoogleContainerTools/kaniko). You can also use a different scripting language, like Python, instead of bash.
```

2024-06-24 14:44 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +If you have DAG-only deploys enabled, you can create scripts for complete project deploys, DAG-only deploys, or image-only deploys. The following sections include a step by step description of the wo
```suggestion
If you have DAG-only deploys enabled, you can create scripts for complete project deploys, DAG-only deploys, or image-only deploys. The following sections include a step by step description of the workflow followed by a bash script that executes the workflow.

See [Deploy code to Astro](deploy-code.md) for more information about the different ways to update your DAGs and Airflow images.
```

2024-06-24 14:45 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +You can only use complete project deploys if you have DAG-only deploys disabled. Image-only and DAG-only deploys do not work.
```suggestion
You can only use complete project deploys if you have DAG-only deploys disabled. Image-only and DAG-only deploys do not work.

See [Deploy code to Astro](deploy-code.md) for more information about the different ways to update your DAGs and Airflow images.
```

2024-06-24 14:45 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `DAG_ONLY`. Store the values for `id` and `dagsUploadURL` that are returned in the r
```suggestion
The following script allows you to update only your DAG files. Refer to [DAG deploys](deploy-dags.md) to learn the details about how Astro deploys DAGs. 

1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `DAG_ONLY`. Store the values for `id` and `dagsUploadURL` that are returned in the response to use in the following steps.
```

2024-06-24 14:48 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +### Image-only deploy
```suggestion
### Image-only deploy

The following script allows you to update only your Astro project by building and deploying a new Docker image. Refer to [What happens during a project deploy](deploy-project-image.md#what-happens-during-a-project-deploy) to learn the details about how Astro deploys image updates. 
```

2024-06-24 14:57 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +## Trigger deploys when files change
Yes its definitely recommended, since it gives them the best experience with astro.

2024-06-25 14:59 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +   - On `Success`, your DAGs have successfully uploaded and a `versionID` of the DAGs tarball is generated. Pass this `versionID` in the requested body to finish your updates.
```suggestion
   - On `Success`, your DAGs have successfully uploaded and a `x-ms-version-id` of the DAGs tarball is generated. Pass this `x-ms-version-id` in the requested body to finish your updates.
```

2024-06-25 15:10 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +## Trigger deploys when files change
Okay @paolaperaza + @kushalmalani, overview + the section have been updated

2024-06-25 15:18 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +This recommended process requires that you enable DAG-only deploys.
Can we link the page to enable DAG deploys

2024-06-25 15:18 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +If the Astro API has access to your Astro project files, you can use the `deploy` endpoints in the Astro API to complete either an image deploy or DAG-only deploy. You can then implement scripts to a
```suggestion
If the Astro API has access to your Astro project files, you can use the `deploy` endpoints in the Astro API to complete either an image and dag deploy, image-only deploy or DAG-only deploy. You can then implement scripts to automate deploys as an alternative to using the Astro CLI or the Astro GitHub integration.
```

2024-06-25 15:42 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +This recommended process requires that you enable DAG-only deploys.
```suggestion
This recommended process requires that you enable [DAG-only deploys](deploy-dags.md).
```

2024-06-25 15:46 UTC, kushalmalani commented on astro/best-practices/deploy-with-api.md
> +   - On `Success`, your DAGs have successfully uploaded and a `x-ms-version-id` of the DAGs tarball is generated. Pass this `x-ms-version-id` in the requested body to finish your updates.
```suggestion
   - On `Success`, your DAGs have successfully uploaded and a `x-ms-version-id` of the DAGs tarball is generated in the response headers. Pass this `x-ms-version-id` in the requested body to finish your updates.
```

2024-06-25 15:51 UTC, kushalmalani approved these changes

2024-06-25 22:30 UTC, paolaperaza approved these changes
Final final comments here @lzdanski! This is an awesome doc.

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +These use cases assume you have:
```suggestion
This guide assumes that you have:
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +The following script allows you to update only your DAG files. Refer to [DAG deploys](deploy-dags.md) to learn the details about how Astro deploys DAGs.
```suggestion
The following script allows you to update only your DAG files. Refer to [Deploy DAGs](deploy-dags.md) to learn the details about how Astro deploys DAGs.
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `DAG_ONLY`. Store the values for `id` and `dagsUploadURL` that are returned in the r
```suggestion
1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your request, specify `type` as `DAG_ONLY`. Store the values for `id` and `dagsUploadURL` that are returned in the response to use in the following steps.
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +3. Upload the tar file by making a `PUT` call using the `dagsUploadURL` that you retrieved in Step 2. In this call, it is mandatory to pass the `x-ms-blob-type` as `BlockBlob`. Then, save the `x-ms-v
```suggestion
3. Upload the tar file by making a `PUT` request using the `dagsUploadURL` that you retrieved in Step 2. In this request, it is mandatory to pass the `x-ms-blob-type` as `BlockBlob`. Then, save the `x-ms-version-id` from the response header.
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +1.  Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `IMAGE`. Store the value for the `DeployID` that is returned. This action creates a
```suggestion
1.  Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your request, specify `type` as `IMAGE`. Store the value for the `DeployID` that is returned. This action creates an object that represents the intent to deploy code to a Deployment.  See the [Astro API documentation](https://www.astronomer.io/docs/api/platform-api-reference/deploy/create-deploy) for request usage and examples.
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `IMAGE`. Store the values for `id`, `imageRepository`, and `imageTag` that are retur
❌  Is this a duplicate step 1?

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +3. Log in to Docker
```suggestion
3. Log in to Docker with your Astro API token.
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +## (Recommended) Trigger deploys when files change
Can we put this as the first H2 if it's recommended?

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +## (Recommended) Trigger deploys when files change
```suggestion
## (Recommended) Dynamic deploys based on files changed
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +### Recommended workflow
```suggestion
### Dynamic deploys workflow
```

2024-06-25 22:30 UTC, paolaperaza commented on astro/best-practices/deploy-with-api.md
> +### Recommended workflow
I feel like we're missing just 1 intro sentence here. I read the steps and I'm a little bit like -- "Am I supposed to be doing anything?" It sounds like this is just explaining what the script does

2024-06-26 13:19 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +1. Make a `POST` request to the `Deploy` endpoint to create a new `deploy` object. In your call, specify `type` as `IMAGE`. Store the values for `id`, `imageRepository`, and `imageTag` that are retur
Sure is!

2024-06-26 13:20 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +        This action creates an object that represents the intent to deploy code to a Deployment. See the [Astro API documentation](https://www.astronomer.io/docs/api/platform-api-reference/deploy/cre
```suggestion
```

2024-06-26 13:22 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +## (Recommended) Trigger deploys when files change
So i think the *Recommended* part is misleading, it's not recommended necessarily above the other three options, it's the recommended way to *combine* the three.

2024-06-26 16:09 UTC, lzdanski commented on astro/best-practices/deploy-with-api.md
> +## (Recommended) Trigger deploys when files change
clarified in expanded overview and intro section

2024-06-26 16:11 UTC, lzdanski commented
Jake's review is stale. merging

2024-06-26 16:11 UTC, merged