Best practices guide on DAG writing on Astro
astronomer/docs pull request #3797
Opened 2024-05-31 18:15 UTC by merobi-hub

This builds on @TJaniF's work in progress to add a guide on writing DAGs optimized for Astro.

2024-06-03 19:16 UTC, kentdanas requested changes
@merobi-hub looking good. Most of my comments are to remove some stuff (so hopefully easy update!) to keep this more focused on just developing DAGs and what goes in them. Will require a little reframing of the best practices section - let me know if you have questions on that - but otherwise I think the content is good.

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +### Follow DevOps best practices
Let's remove this section. I think we should keep this guide to only best practices for writing DAGs (what tools to use for writing them, and what should go in the code that might be different from OSS Airflow), not also deploying them (we have deployment stuff in other best practices and can always write more).

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +### Kubernetes and Astro
Similar to above comment, let's axe this section as well

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +### Follow DAG-writing best practices
None of this section is Astro related, we can remove

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +## Best practice guidance
I commented below on removing a few sections in here. Overall I think the ones we need to keep are on development (Cloud IDE, CLI), and Astro features that would change DAG code (what is currently in Leverage Astro resources for improved Airflow management, maybe we call this "DAG code on Astro" or something like that).

So, let's have two sub-sections in here, one for each of those sets of guidance. For development, the sections on Cloud IDE and CLI are good content-wise, but I would add a few sentences on when you might choose one or the other (or both). 

For the Leverage Astro resources for improved Airflow management stuff, we should make clear that these are features that require DAG code changes (or in the case of connections, adding config in Astro instead of Airflow), and describe why somebody would choose those. When we say "your DAGs will just run on Astro", we should frame this section as "here are some changes you may consider making when migrating or writing new DAGs"

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +## Astro DAG Example
I think we can axe the whole example - all of the features we're talking about here (once we remove some stuff) are straightforward to implement and clearly described in their respective docs.

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +title: 'Optimize Airflow DAGs for Astro'
Why do we have the title as "optimize"? I would keep it the same as teh sidebar "DAG writing on Astro" unless there was a specific reason we chose this

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +While this best practice guide focuses on writing Airflow DAGs for Astro, all [general Airflow best practices](https://docs.astronomer.io/learn/dag-best-practices) are also recommended.
```suggestion
This guide describes best practices for taking advantage of Astro features when writing DAGs. While this focuses on writing Airflow DAGs for Astro, all [general Airflow best practices](https://docs.astronomer.io/learn/dag-best-practices) are also recommended.
```

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- [KubernetesPodOperator](kubernetespodoperator.md). Supports running specific tasks in dedicated Kubernetes pods on Astro.
```suggestion
```

2024-06-03 19:16 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- [CI/CD on Astro](set-up-ci-cd.md). A recommended architecture for testing and deployment supported by pre-built templates.
```suggestion
```

2024-06-04 16:22 UTC, kentdanas approved these changes
@merobi-hub looks pretty good! A couple of other suggestions, otherwise let's move on to copy editing.

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +Compared to open-source Airflow, Astro offers a distinct feature set for managing deployments that you should consider not only when writing new DAG code but also when migrating DAGs to Astro. Althou
```suggestion
Compared to open-source Airflow, Astro offers a distinct feature set for optimizing your Airflow use. Some of these features impact individual DAGs, and you should consider them not only when writing new DAG code but also when migrating DAGs to Astro. You don't need to make changes to existing DAGs when you migrate them, but by implementing some small changes you can get access to an upgraded experience when it comes to managing connections, defining and storing environment variables, allocating resources, and implementing alerts.
```

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +::: note
```suggestion
```

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +:::
```suggestion
```

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +Making use of these features can require DAG code changes or adding config in Astro instead of Airflow.
```suggestion
Making use of the following features can require DAG code changes or adding config in Astro instead of Airflow. Astronomer recommends considering these features during DAG development to streamline the development process and make use of everything Astro has to offer.
```

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- **[Astro Cloud UI Environment Manager](https://docs.astronomer.io/astro/manage-connections-variables)** for managing connections. Allows you to define connections once and use them in multiple depl
```suggestion
- **[Astro Cloud UI Environment Manager](https://docs.astronomer.io/astro/manage-connections-variables)** for managing connections. This allows you to define connections once and use them in multiple deployments (with or without overrides for individual fields), as well as in your local development environment. Connections in the Environment Manager are stored in the Astronomer managed secrets backend. Using the Environment Manager requires adding packages to your Astro project and adding config in Astro.
```
Which packages are required?

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- **[Deployment environment variables](environment-variables.md)** for storing environment variables. A number of approaches are supported. For example, you can mark variables as secret for storage i
I think we should add something in here about why you would want to use deployment environment variables over other ways of managing them.

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- **[Worker queues](https://docs.astronomer.io/astro/configure-worker-queues)** for optimizing task execution efficiency. Worker queues allow you to define sets of workers with specific resources tha
```suggestion
- **[Worker queues](https://docs.astronomer.io/astro/configure-worker-queues)** for optimizing task execution efficiency. Worker queues allow you to define sets of workers with specific resources that execute tasks in parallel. You can assign tasks to specific worker queues to optimize resource usage. This feature is an improvement over OSS Airflow pools, which only manage concurrency and not resources. You can use both worker queues and pools in combination. Config in Astro and DAG code modification are required to use this feature.
```

2024-06-04 16:22 UTC, kentdanas commented on astro/best-practices/dag-writing-on-astro.md
> +- **[Astro Alerts](alerts.md)** for setting up alerts for your DAGs. For more information, see [When to use Airflow or Astro alerts for your pipelines on Astro](airflow-vs-astro-alerts.md). Config in
Here let's also add something brief on why you might want to use them - and then can link out to the other best practice guide for more info (as you do now)

2024-06-07 11:05 UTC, TJaniF approved these changes
This is great! 
Added a few optional suggestions :)

2024-06-07 11:05 UTC, TJaniF commented on astro/best-practices/dag-writing-on-astro.md
> +- **[Deployment environment variables in the Astro UI](environment-variables.md)** for storing environment variables. Common uses of environment variables include adding tokens or URLs required by yo
```suggestion
- **[Deployment environment variables in the Astro UI](environment-variables.md)** for storing environment variables. Common uses of environment variables include adding tokens or URLs required by your DAGs, integrating with third-party tooling to export metrics, customizing core settings of Airflow or Airflow Providers, and storing Airflow connections and variables. A number of approaches are supported. For example, you can mark variables as secret for storage in the Astronomer managed secrets backend. You can store [Airflow variables](https://docs.astronomer.io/learn/airflow-variables), which are Airflow native key-value pairs, as environment variables as well by using the format `AIRFLOW_VAR_MYVARIABLENAME`. You can also manage environment variables using your Astro project Dockerfile and, locally, your project `.env` file. Astro project modification and additional configuration in Astro may be required depending on the strategy chosen.
```

Another clarification suggestion in case users very new to Airflow read this to hopefully make the concept of Airflow variables more distinct from all other kinds of variables 😅

2024-06-07 11:05 UTC, TJaniF commented on static/img/docs/airflow-cicd-3-branches.png
I think this is not needed anymore? I can't see where it is used in the new doc :)

2024-06-07 14:02 UTC, lzdanski approved these changes

2024-06-07 14:03 UTC, merged