Ephemeral Storage public preview
astronomer/docs pull request #3804
Opened 2024-06-03 19:33 UTC by lzdanski

Resolves #3362

Release notes here: https://github.com/astronomer/docs/pull/3803

2024-06-03 19:42 UTC, lzdanski commented
Preview here: https://deploy-preview-3804--gallant-neumann-56599d.netlify.app/docs/astro

2024-06-04 13:38 UTC, jwitz requested changes
Some formatting suggestions, will take one more pass after changes to make sure everything renders correctly

2024-06-04 13:38 UTC, jwitz commented on astro/celery-executor.md
> +        **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker. This storage volume is transient and allows for the temporary storage and processing of data. The worker is
```suggestion
    **Storage**: Choose the amount of ephemeral storage in GiB that each worker has. This storage volume is transient and allows for temporary storage and processing of data within the worker. The worker is assigned 10 GiB, the minimum, by default. The maximum quota is 100GiB. Only ephemeral storage requests that are greater than the default minimum of 10GiB are chargeable. Note that this feature is in [Public Preview](feature-previews.md).
```

2024-06-04 13:38 UTC, jwitz commented on astro/celery-executor.md
> +
```suggestion
```

2024-06-04 13:38 UTC, jwitz commented on astro/celery-executor.md
> +
```suggestion
```

2024-06-04 13:38 UTC, jwitz commented on astro/celery-executor.md
> +        **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker. This storage volume is transient and allows for the temporary storage and processing of data. The worker is
We should make this inline with the rest of the steps. The info block is titled to communicate the public preview detail, but then we encapsulate the entire documentation within the info block. Public preview is in safe enough of a state that we can show this setting alongside all others, only including a brief mention of its preview status at the end.

2024-06-04 13:38 UTC, jwitz commented on astro/deployment-resources.md
> +     For Astro Hosted environments, if you set your **CPU** and **Memory** resource requests to be less than the maximum limit, Astro automatically requests the maximum limit that you set. This means
Why is the ephemeral storage charging line up here?

2024-06-04 13:38 UTC, jwitz commented on astro/deployment-resources.md
> +        **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker in the Astro UI. This storage volume is transient and allows for the temporary storage and processing of dat
Basically identical edits to the Celery one, I don't think this needs a separate info block

2024-06-04 13:47 UTC, lzdanski commented on astro/deployment-resources.md
> +     For Astro Hosted environments, if you set your **CPU** and **Memory** resource requests to be less than the maximum limit, Astro automatically requests the maximum limit that you set. This means
Because I forgot to make the same edit here as I made in celery page! 👍 thanks for the catch

2024-06-04 14:22 UTC, jwitz approved these changes

2024-06-04 14:22 UTC, jwitz commented on astro/celery-executor.md
> +    - **Storage**: Choose the amount of ephemeral storage in GiB that each worker has. This storage volume is transient and allows for temporary storage and processing of data within the worker. The
```suggestion
    - **Storage**: Choose the amount of ephemeral storage in GiB that each worker has. This storage volume is transient and allows for temporary storage and processing of data within the worker. The worker is assigned the minimum 10 Gib by default. The maximum quota is 100 GiB. Only ephemeral storage requests that are greater than the default minimum of 10 GiB are chargeable. Note that this feature is in [Public Preview](feature-previews.md).
```

2024-06-04 14:22 UTC, jwitz commented on astro/deployment-resources.md
> +        - **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker in the Astro UI. This storage volume is transient and allows for the temporary storage and processing of d
```suggestion
        - **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker in the Astro UI. This storage volume is transient and allows for the temporary storage and processing of data. The worker is assigned the minimum 0.25 GiB by default. The maximum possible quota is 100 GiB. Only ephemeral storage requests that are greater than the default minimum of 0.25 GiB are chargeable. Note that this feature is in [Public Preview](feature-previews.md).
```

2024-06-04 15:09 UTC, chomipi88 commented on astro/celery-executor.md
> +    - **Storage**: Choose the amount of ephemeral storage in GiB that each worker has. This storage volume is transient and allows for temporary storage and processing of data within the worker. The
```suggestion
    - **Storage**: Choose the amount of ephemeral storage in GiB that each worker has. This storage volume is transient and allows for temporary storage and processing of data within the worker. The worker is assigned the minimum 10 GiB by default. The maximum quota is 100 GiB. Only ephemeral storage requests that are greater than the default minimum of 10 GiB are chargeable. Note that this feature is in [Public Preview](feature-previews.md).
```

2024-06-04 15:09 UTC, chomipi88 commented on astro/deployment-resources.md
> +        - **Storage**: Choose the amount of ephemeral storage in GiB assigned to each worker in the Astro UI. This storage volume is transient and allows for the temporary storage and processing of d
```suggestion
        - **Storage**: Choose the amount of ephemeral storage in GiB assigned to each pod in the Astro UI. This storage volume is transient and allows for the temporary storage and processing of data. The pod is assigned the minimum 0.25 GiB by default. The maximum possible quota is 100 GiB. Only ephemeral storage requests that are greater than the default minimum of 0.25 GiB are chargeable. Note that this feature is in [Public Preview](feature-previews.md).
```

2024-06-04 15:09 UTC, chomipi88 commented on astro/kubernetes-executor.md
>  ### Example: Set CPU or memory limits and requests
Can we add `ephemeral-storage` to the example?

2024-06-04 15:17 UTC, lzdanski commented on astro/kubernetes-executor.md
>  ### Example: Set CPU or memory limits and requests
I need someone to help me with the code!

2024-06-04 16:43 UTC, chomipi88 approved these changes
Pls hold publishing until today's control plane prod release

2024-06-04 19:23 UTC, merged