Best practices guide on repo structure and CI/CD
astronomer/docs pull request #3835
Opened 2024-06-07 16:00 UTC by merobi-hub

Adds a best practices guide with options and recommendations for structuring a code repo and setting up CI/CD.

2024-06-25 23:47 UTC, kentdanas requested changes
@merobi-hub this is looking good! Some minor comments throughout

2024-06-25 23:47 UTC, kentdanas commented on astro/best-practices/repo-structure.md
> +1. Maintain a *single* Git repository for all files in a *single* Astro project (one-to-one).
We should be careful here whether we want to use "astro project" or "astro Deployment" - I think of "astro project" as the set of files created when you do `astro dev init` with the CLI, rather than the Deployment. I think it would be clearer if we used "Deployment" here like you do in the subheaders below, and "project" would only come into it in the case where you have multiple projects in the same repo.

2024-06-25 23:47 UTC, kentdanas commented on astro/best-practices/repo-structure.md
> +Repository options for setting up one-to-one deploys with CI/CD include AWS S3. Supported CI/CD tools include Jenkins, GitHub Actions, and AWS CodeBuild. For details about setting up CI/CD workflows
Not sure I understand this part - why is S3 a repository option (but also the only one listed)?. And why are we only listing 3 CI/CD tools, even though we have templates for others?

2024-06-25 23:47 UTC, kentdanas commented on astro/best-practices/repo-structure.md
> +This strategy requires [DAG-only deploys](https://www.astronomer.io/docs/astro/deploy-dags#enable-or-disable-dag-only-deploys-on-a-deployment) on the target Deployment and CI/CD pipeline setup for bo
I would actually put this up under the `this strategy requires` bullets, and maybe bold dag-only deploys since it's pretty critical that this strategy won't work without it.

2024-06-25 23:47 UTC, kentdanas commented on astro/best-practices/repo-structure.md
> +:::warning
This seems more like an info than a warning?

2024-06-25 23:47 UTC, kentdanas commented on astro/best-practices/repo-structure.md
> +### Option 3: one repository with multiple permanent branches to multiple Deployments with CI/CD
Maybe we should add a "most common" badge or something in this one? I assume this is generally what we would recommend

2024-06-26 15:06 UTC, merobi-hub commented on astro/best-practices/repo-structure.md
> +### Option 3: one repository with multiple permanent branches to multiple Deployments with CI/CD
Sounds good, and I'm exploring options supported by github markdown. There aren't many, unfortunately...

2024-06-26 18:48 UTC, merobi-hub commented
@kentdanas wdyt of this tip box instead of a badge?
<img width="967" alt="Screenshot 2024-06-26 at 14 45 14" src="https://github.com/astronomer/docs/assets/68482867/85850a8e-b9f8-4f84-9aa7-00dfed8ad5b0">

2024-06-27 15:18 UTC, merobi-hub commented
@kentdanas Do you have a preference as far as a tip admonition or a badge for the third option? Happy to adjust the color, padding, etc., of the badge, too.
![Screenshot 2024-06-27 at 11 15 16](https://github.com/astronomer/docs/assets/68482867/54a71152-1ca3-415f-8bdc-067bcfe85721)

2024-06-27 16:35 UTC, kentdanas commented
> @kentdanas Do you have a preference as far as a tip admonition or a badge for the third option? Happy to adjust the color, padding, etc., of the badge, too. ![Screenshot 2024-06-27 at 11 15 16](https://private-user-images.githubusercontent.com/68482867/343838116-54a71152-1ca3-415f-8bdc-067bcfe85721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDY0MDgsIm5iZiI6MTcxOTUwNjEwOCwicGF0aCI6Ii82ODQ4Mjg2Ny8zNDM4MzgxMTYtNTRhNzExNTItMWNhMy00MTVmLThiZGMtMDY3YmNmZTg1NzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE2MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Nzc4YWI5MTZkMzk0OTdlYmRkYTE1MzQwZDQwYjAzYzQ2MmEzMDJjZDg4OWU0NzI4ZTNjNDU0ZGM0ZTA0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPzRpnbn4dlYqttghSDAkHbsvdFwCiJISsytrmHTAPE)

I would put it below the header, similar to how we have the hosted only badges https://www.astronomer.io/docs/astro/deployment-health-incidents#deployment-incidents. Otherwise I think it looks good.

2024-06-27 16:36 UTC, kentdanas approved these changes
We might consider swapping options 2 and 3, since 3 is more closely related to 1 and is the most common. Otherwise I think this looks good. Let's get an AFaaS review before publishing, but otherwise good to move on to copy editing.

2024-06-28 18:31 UTC, fritz-astronomer commented on astro/deploy-github-integration.md
> +Astronomer's built-in GitHub integration is the fastest way to implement CI/CD for Apache Airflow and deploy code to Astro. Astro’s automatic deploy system both eliminates the need to implement GitHu
what a weird change 😅

2024-06-28 18:47 UTC, fritz-astronomer requested changes

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +1. Maintain a *single* Git repository for all files in a *single* Astro Deployment (one-to-one).
this is either incorrect or confusingly worded.

often, you'll have
- One git repo, many branches
- One Astro Project
- Many Astro Deployments (dev, prod, etc)

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +3. Host multiple Astro projects in a *single* repository for deployment to *multiple* Astro Deployments (one-to-many).
sentence might need copyedit

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +All the CI/CD strategies that Astro supports require utilization of a version control tool such as [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/). Implementation of version cont
To be pedantic - the version control tool here is `git`. Github and Gitlab are hosted providers for git repositories. Might need to reword

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +All the CI/CD strategies that Astro supports require utilization of a version control tool such as [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/). Implementation of version cont
I'm also not even sure if we'd work with other vcs tools?? I ... feel like we would but they are so uncommon these days. I don't think I've ever seen SVN + CICD in the wild :)

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +### Option 1: one repository to one Deployment
Copyedit, the caps feel weird. And repeating nitpick above that "one deployment" is wrong

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +Creating a single Git repository for each Astro project is the strategy Astronomer recommends for smaller teams (under 30 members) in organizations where a single team is responsible for both develop
I'm not sure I agree on the "size" comment here, or the wording is throwing me a bit. This approach works for a large customer with thousands of developers _**but**_ you would often have a different Astro Project for different teams - does that fit with what you're saying here?

Maybe remove the 'smaller teams' and '(30 members)'. I don't think there exists a development team with dozens/hundreds of members.

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You can't take this approach and simultaneously collect DAGs used in multiple Deployments in a single repository.
can't _easily_ ? You could still package stuff with this approach, and pull in the package. Though I don't think I've seen people package centralized DAGs. (I don't think I've seen centralized DAGs often, regardless)

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You can't also keep Deployment configuration code separate from DAG code, which is required when you want to [manage Deployments programmatically](https://www.astronomer.io/docs/astro/manage-deploy
Not entirely following this last part?

You could have a deployment with yaml or terraform in one repo, and dags in the other, and separate people have access to each repo? I suppose that makes sense.
I've recommended customers configure Github to reject commits to certain files by non-CODEOWNERS, but that's a pretty specific feature to that platform

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You can set up and maintain a somewhat complex CI/CD pipeline.
wording feels clunky

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +A common use case for multiple repositories is keeping configuration code separate from DAG code. Astronomer recommends this approach when:
maybe worth mentioning something like "You may have separate teams for managing deployments and maintaining the DAGs that run on them" here

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +This strategy is required when [configuring Deployments programmatically](https://www.astronomer.io/docs/astro/manage-deployments-as-code).
That's not true

2024-06-28 18:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +### Option 3: one repository with multiple permanent branches to multiple Deployments with CI/CD <Highlight color="#9478d2">Most common</Highlight>
if this is most common, we should put it first

The other wording made it sound different
> 3. Host multiple Astro projects in a *single* repository for deployment to *multiple* Astro Deployments (one-to-many).

You can have, and I've seen, multiple teams with multiple astro projects in one repo
```
\
| -- astro_project_a
| -- astro_project_b
\ -- -- .github/actions.workflow.yaml
\ -- -- dags/
\ -- -- Dockerfile
| -- astro_project_c
```
etc

2024-07-01 13:22 UTC, merobi-hub commented on astro/deploy-github-integration.md
> +Astronomer's built-in GitHub integration is the fastest way to implement CI/CD for Apache Airflow and deploy code to Astro. Astro’s automatic deploy system both eliminates the need to implement GitHu
uh, just a grammar fix

2024-07-01 15:55 UTC, fritz-astronomer commented on astro/deploy-github-integration.md
> +Astronomer's built-in GitHub integration is the fastest way to implement CI/CD for Apache Airflow and deploy code to Astro. Astro’s automatic deploy system both eliminates the need to implement GitHu
Oh! Sorry! I didn't see that you got rid of `both` - I thought it was just a github glitch with the way it was highlighting it
<img width="224" alt="image" src="https://github.com/astronomer/docs/assets/80706212/c823abe8-baa5-4cef-b650-31ad31064da2">

2024-07-01 16:26 UTC, merobi-hub commented on astro/deploy-github-integration.md
> +Astronomer's built-in GitHub integration is the fastest way to implement CI/CD for Apache Airflow and deploy code to Astro. Astro’s automatic deploy system both eliminates the need to implement GitHu
Oh got it! NP!

2024-07-01 16:28 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +- You can't take this approach and simultaneously collect DAGs used in multiple Deployments in a single repository.
@fritz-astronomer  My thought here was that it's more involved to restrict access at the subdirectory level in GitHub than at the repo level. From that perspective, does the bullet work, or do you think it should still be changed?

2024-07-01 16:52 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +- You can't also keep Deployment configuration code separate from DAG code, which is required when you want to [manage Deployments programmatically](https://www.astronomer.io/docs/astro/manage-deploy
Deleted the third bullet here

2024-07-01 16:52 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +This strategy is required when [configuring Deployments programmatically](https://www.astronomer.io/docs/astro/manage-deployments-as-code).
Deleted the block

2024-07-02 15:33 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You can't take this approach and simultaneously collect DAGs used in multiple Deployments in a single repository.
I'd still say "can't easily" (or something) rather than have someone see "can't" stop something they needed to do

2024-07-22 18:52 UTC, fritz-astronomer requested changes

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +All the CI/CD strategies that Astro supports require Git plus either [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/). Implementation of version control is a longstanding software
```suggestion
Implementation of version control is a longstanding software development best practice that enables:
```
That's not true. We have templates for plenty of other systems and work with **any** system that can just run the astro CLI

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You have separate teams managing Deployments and maintaining the DAGs that run on them.
```suggestion
When your DAGs are critical to your business, the ability to test your DAGs is critical, as well. Setting up automated deploys from multiple permanent branches of a single repository allows you to implement a robust testing regime for the code you intend to deploy to production. 
```
Not sure any of those are really required

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- At least two Astro Deployments.
```suggestion
- At least two Astro Deployments, each representing an environment.
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- It supports separate environment configurations. If you use Snowflake, for example, your development Deployment on Astro can use a virtual data warehouse for development (`DWH Dev`), and your produ
```suggestion
- It supports separate environment configurations. For example, your development Deployment query a development database, and your production Deployment can query a production database without needing complex logic to switch between the two.
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- Restricting access to Astro settings or to particular Astro projects is more complicated to implement and maintain in subdirectories.
```suggestion
```
Not sure that makes sense? Both the "subdirectories" and the access piece feel incorrect

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +### Option 2: One repository to one or multiple Deployments
```suggestion
### Option 2: One repository to one Deployment
```
One repository to multiple deployments is above. 
This would need to be a team that just has a prod version of Airflow and nothing else.
I'm not entirely sure we should recommend this at all, but 🤷 that might just be me

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +Creating a single Git repository for each Astro project is the strategy Astronomer recommends for smaller teams in organizations where a single team is responsible for both developing DAGs and mainta
This would also apply to the prior strategy

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You can't take this approach and simultaneously collect DAGs used in multiple Deployments in a single repository.
```suggestion
```
1) Can't easily. You can.
2) This is about one deployment, so that doesn't even really make sense to bring up?

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You have more options when it comes to maintaining Deployments and deploying code.
```suggestion
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- Managing Astro settings is potentially much easier, as keeping configuration code in a separate repository enables the use of a single repository for configuring multiple Deployments.
```suggestion
- Keeping project configuration separate from DAG Code enables the use of a single repository for configuring multiple Deployments.
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +A common use case for multiple repositories is keeping configuration code separate from DAG code. Astronomer recommends this approach when:
```suggestion
A common use case for multiple repositories is keeping Astro Project configuration (such as the `Dockerfile`, `requirements.txt`, or Deployment Configuration-as-Code) separate from DAG code. Astronomer recommends this approach when:
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- You must keep any local copies of an Astro project synchronized with multiple repositories in order to test Deployment code locally and ensure that updates from your configuration repository do not
```suggestion
- You must keep any local copies of an Astro project synchronized with multiple repositories in order to test Deployment code locally.
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +- Team members might have inconsistencies in their local environments if they lack access to the configuration repository. For this reason, Astronomer recommends [setting up a dev Deployment](manage-
```suggestion
- Team members might have inconsistencies in their local environments if they lack access to the configuration repository. For this reason, Astronomer recommends [setting up a Dev Deployment](manage-dev-deployments) where DAG authors can see and modify project configurations for testing purposes.
```

2024-07-22 18:52 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +4. Host multiple Astro projects in one repository for deployment to multiple Astro Deployments (one-to-many).
```suggestion
Astro supports a number of CI/CD strategies. You can:
1. Host one Astro project in one repository for deployment to multiple Astro Deployments (one-to-many), based on branches.
2. Host one Astro project in one Git repository for deployment to one Astro Deployment (one-to-one).
3. Separate your DAGs from other files and maintain multiple repositories for one Astro Deployment (many-to-one).
4. Host multiple Astro projects in one repository for deployment to multiple Astro Deployments (one-to-many).
```
They should match the order of the sections, I feel like.
You didn't mention #4, below 🤷

2024-07-26 14:58 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +All the CI/CD strategies that Astro supports require Git plus either [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/). Implementation of version control is a longstanding software
Thanks. I received other feedback critical of mentioning other VCS options because Git is so common. But it makes sense to revert.

2024-07-26 15:47 UTC, fritz-astronomer commented on astro/best-practices/repo-structure.mdx
> +All the CI/CD strategies that Astro supports require Git plus either [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/). Implementation of version control is a longstanding software
Those are all git based, though :) 
We don't have any SVN CICD templates. 
Just there's _**lots**_ of online git repository services.

Specifically, I think you should just remove being specific about github/gitlab - It's confusing. 

Not that you need to mention SVN or etc

2024-07-29 16:56 UTC, kentdanas approved these changes

2024-07-29 16:56 UTC, kentdanas commented on astro/best-practices/repo-structure.mdx
> +In addition to choosing a repository strategy suited to your use case, Astronomer recommends implementing CI/CD and version control.
Should we update this section to not start with a paragraph about CI/CD? Maybe remove this and start wtih the "implementing version control"

2024-07-29 16:59 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +In addition to choosing a repository strategy suited to your use case, Astronomer recommends implementing CI/CD and version control.
Changed this as you were reviewing. WDYT of the latest? Should we still cut the CI/CD stuff here?

2024-07-29 17:48 UTC, merobi-hub commented on astro/best-practices/repo-structure.mdx
> +In addition to choosing a repository strategy suited to your use case, Astronomer recommends implementing CI/CD and version control.
@kentdanas I moved the vcs and CI/CD stuff to a new section at the end. happy to cut it, but wondering what you think of this approach.

2024-07-29 20:11 UTC, kentdanas commented on astro/best-practices/repo-structure.mdx
> +In addition to choosing a repository strategy suited to your use case, Astronomer recommends implementing CI/CD and version control.
@merobi-hub this is much better, I think it looks great! Good to publish from my side

2024-07-29 21:12 UTC, merged