Trigger rule guide
astronomer/docs pull request #3877
Opened 2024-06-24 13:28 UTC by TJaniF

Because the current top results for `airflow trigger rules` on google is Airflow 1.x docs and then some AI generated confusing stuff.

2024-06-25 23:29 UTC, kentdanas requested changes
Just a question on the necessity of the examples. Otherwise looks great!

2024-06-25 23:29 UTC, kentdanas commented on learn/airflow-trigger-rules.md
> +Additionally to the trigger rules, you have the option of defining a DAG in which any task failure stops the DAG execution, setting all tasks that are still running to `failed` and marking any tasks
```suggestion
There are several advanced Airflow features that influence trigger rules. You can define a DAG in which any task failure stops the DAG execution by setting [DAG parameter](airflow-dag-parameters.md) `fail_stop` to `True`. This will set all tasks that are still running to `failed` and marking any tasks that have not run yet as `skipped`. Note that you cannot have any trigger rule other than `all_success` in a DAG with `fail_stop` set to `True`.
```

2024-06-25 23:29 UTC, kentdanas commented on learn/airflow-trigger-rules.md
> +Another advanced feature that influences trigger rules are [Setup and Teardown tasks](airflow-setup-teardown.md), a special type of task to create and delete resources.
```suggestion
[Setup and Teardown tasks](airflow-setup-teardown.md) are a special type of task to create and delete resources that also influence trigger rules.
```

2024-06-25 23:29 UTC, kentdanas commented on learn/airflow-trigger-rules.md
> +One common scenario where you might need to implement trigger rules is if your DAG contains conditional logic such as [branching](airflow-branch-operator.md). In these cases, `one_success` or `none_f
```suggestion
One common scenario where you might need to implement trigger rules is if your DAG contains conditional logic such as [branching](airflow-branch-operator.md). In these cases, `one_success` or `none_failed` are likely more helpful than `all_success`, because unless all branches are run, at least one upstream task will always be in a `skipped` state.
```

2024-06-25 23:29 UTC, kentdanas commented on learn/airflow-trigger-rules.md
> +## Examples
Maybe a silly question, but....do you think we really need all these examples? In my mind most of the trigger rules are fairly self explanatory, and I haven't seen much confusion about them aside from people not knowing they exist. I would lean towards keeping only the ones which are not as straight forward (although I'm not sure what that would be....), or having a section that covers edge cases (although aside from branching, not sure what an edge case would be?)

2024-06-27 16:20 UTC, kentdanas approved these changes
Looks great! I like the blog post idea for the screenshots

2024-06-27 16:28 UTC, TJaniF commented
Thank you @kentdanas ! :) 
And yes, lets do the blog post (might even get published before the guide 🤔 )

@lzdanski from the future: welcome back from vacation! 🌴  This is a short new guide, not urgent! :)

2024-07-02 20:25 UTC, kentdanas commented
@merobi-hub if you wouldn't mind giving this a copy edit whenever you have a few minutes

2024-07-09 13:34 UTC, merobi-hub commented on learn/airflow-branch-operator.md
>  Finally, note that with the `@task.branch` decorator your Python function *must* return at least one task ID for whichever branch is chosen (i.e. it can't return nothing). If one of the paths in your
```suggestion
Finally, note that with the `@task.branch` decorator your Python function *must* return at least one task ID for whichever branch is chosen (in other words, it can't return nothing). If one of the paths in your branching should do nothing, you can use an EmptyOperator in that branch.
```

2024-07-09 13:35 UTC, merobi-hub commented on learn/airflow-dag-parameters.md
> +| `fail_stop`               |  In Airflow 2.7+ you can set this parameter to `True` to stop DAG execution as soon as one task in this DAG fails. Any tasks that are still running are marked as `failed
```suggestion
| `fail_stop`               |  In Airflow 2.7+, you can set this parameter to `True` to stop DAG execution as soon as one task in this DAG fails. Any tasks that are still running are marked as `failed`, and any tasks that have not run yet are marked as `skipped`. Note that you cannot have any [trigger rule](airflow-trigger-rules.md) other than `all_success` in a DAG with `fail_stop` set to `True`. |
```

2024-07-09 13:37 UTC, merobi-hub commented on learn/use-case-setup-teardown-data-quality.md
> +No matter the outcome of the data quality checks in the `validate` task group, the pipeline will continue because the `sql_check_done` task uses the [trigger rule](airflow-trigger-rules.md) `all_done
```suggestion
No matter the outcome of the data quality checks in the `validate` task group, the pipeline will continue because the `sql_check_done` task uses the [trigger rule](airflow-trigger-rules.md) `all_done` to be successful always. 
```

2024-07-09 13:41 UTC, TJaniF commented
> LGTM! Found some punctuation & style issues unrelated to your changes and made suggestions to fix.

Haha, thank you! :)

2024-07-09 13:42 UTC, merged