Private link\endpoints update
astronomer/docs pull request #3888
Opened 2024-06-28 20:49 UTC by afastronomer

Changes were made for the #3873 issue.

2024-07-08 19:15 UTC, lzdanski requested changes

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-aws.md
> +To request additional endpoints, or assistance connecting to other AWS services please follow the next steps:
```suggestion
To request additional endpoints, or assistance connecting to other AWS services, complete the following steps:
```

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-aws.md
> +- Prepare a list of the AWS Services which require Endpoints (e.g. SQS, Lambda, DynamoDB).
```suggestion
- Prepare a list of your AWS Services that require Endpoints, such as SQS, Lambda, or DynamoDB.
```

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-aws.md
> +- Contact [Astronomer support](https://cloud.astronomer.io/open-support-request) and provide this information for the further steps.
```suggestion
- Contact [Astronomer support](https://cloud.astronomer.io/open-support-request) and provide this information for next steps.
```

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-aws.md
> +- Open a list of your clusters in [Cloud UI](https://cloud.astronomer.io/clusters).
```suggestion
- Open a list of your clusters in the [Astro UI](https://cloud.astronomer.io/clusters).
```

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-aws.md
> +- Add to request a preferable DNS name for Endpoint, if Route53 alias is required for the proper connectivity (i.e. Snowflake, EKS). Otherwise you can skip this step.
```suggestion
- Click on the target cluster and retrieve the value for the `ACCOUNT ID` field.
- Go to your VPCe Service configuration and add `arn:aws:iam::<Astro account_id>:role/astronomer-remote-management` into a list of the Allowed principals.
- Contact [Astronomer support](https://cloud.astronomer.io/open-support-request) and provide a VPCe Service name for the custom Service.
- (Optional)  If Route53 alias is required for the proper connectivity by your service such as Snowflake EKS, add a preferable DNS name for the Endpoint to your request. Otherwise, you can skip this step.
```

2024-07-08 19:15 UTC, lzdanski commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
Does Azure have their own docs about the Group ID? some concerns about linking to a blog.

2024-07-08 19:43 UTC, afastronomer commented on astro/connect-aws.md
> +- Prepare a list of the AWS Services which require Endpoints (e.g. SQS, Lambda, DynamoDB).
Can we add "including, but not limited to SQS, Lambda, or DynamoDB"?

2024-07-08 19:45 UTC, afastronomer commented on astro/connect-aws.md
> +- Add to request a preferable DNS name for Endpoint, if Route53 alias is required for the proper connectivity (i.e. Snowflake, EKS). Otherwise you can skip this step.
"such as Snowflake or EKS"

2024-07-08 20:16 UTC, afastronomer commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
Unfortunately they do not have such list. Person in blog collected it manually through Azure Console or API calls.

2024-07-10 16:54 UTC, chomipi88 approved these changes

2024-07-17 16:47 UTC, ReadytoRocc commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
We could alternatively include the Azure CLI commands to obtain the group IDs.

2024-07-18 17:27 UTC, afastronomer commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
@lzdanski what about this URL https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/private-link/private-endpoint-overview.md#private-link-resource ?

2024-07-23 16:36 UTC, lzdanski commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
That URL Looks good to me - will substitute it in!

2024-07-23 16:37 UTC, lzdanski commented on astro/connect-azure.md
> +- [Group ID](https://blog.blksthl.com/2023/03/22/the-complete-list-of-groupids-for-private-endpoint-privatelink-service-connection/)
```suggestion
- [Group ID](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/private-link/private-endpoint-overview.md#private-link-resource )
```

2024-07-23 16:37 UTC, lzdanski approved these changes

2024-07-23 16:46 UTC, merged