New doc for cluster policies
astronomer/docs pull request #3891
Opened 2024-07-01 14:20 UTC by manmeetkaur

closes issue #3508

2024-07-01 18:27 UTC, kentdanas requested changes
@manmeetkaur thank you for submitting this - this is awesome! And I agree it will be great to follow it up with a best practices guide on Astro. I left some suggested edits - mainly I think we need to give a little more context in the instructions on what is going on. But otherwise the structure of the doc and content looks great.

@merobi-hub would you mind also copy editing this?

2024-07-01 18:27 UTC, kentdanas commented on sidebarsLearn.js
> +            'airflow-cluster-policies'
Can we move this up so the sidebar stays alphabetized? Should go before Custom XCom backends

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +These policies allow administrators to centrally manage how Airflow users or DAG writers are interacting with the Airflow Cluster. They can modify or restrict their capability based on organization p
```suggestion
These policies allow administrators to centrally manage how Airflow users or DAG writers are interacting with the Airflow Cluster. Cluster policies can modify or restrict user's capability based on organization policy or ensure that users conform to common standards. For example, you may want to ensure all DAGs have `tags` before being deployed to production.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +These cluster policies can be used to:
```suggestion
Cluster policies can be used to:
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- Check if the DAGs/Tasks meet certain standards
```suggestion
- Check if DAGs/Tasks meet certain standards
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- Setting default arguments on DAGs/Tasks
```suggestion
- Set default arguments on DAGs/Tasks
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- Perform custom routing/skipping logic on the DAGs or Tasks
```suggestion
- Perform custom routing/skipping logic on DAGs or Tasks
```
I'm not sure what this means - not sure if that's my own knowledge gap, or if it would be helpful to add some additional context here for the avg user?

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +In this guide, you'll learn about the types of cluster policies, how these policies work, and how to implement these in Airflow.
```suggestion
In this guide, you'll learn about the types of cluster policies, how they policies work, and how to implement them in Airflow.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- `dag_policy`: This policy is applicable to a DAG object, and takes a DAG object `dag` as a parameter. It runs at load time of the DAG from the `DagBag`.
```suggestion
There are three types of cluster policies you can use in Airflow:

- `dag_policy`: This policy is applicable to a DAG object, and takes a DAG object `dag` as a parameter. It runs at the time the DAG is loaded from the `DagBag`.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +## Main types of cluster policies
```suggestion
## Types of cluster policies
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- `dag_policy`: This policy is applicable to a DAG object, and takes a DAG object `dag` as a parameter. It runs at load time of the DAG from the `DagBag`.
Taking out "main" here since based on the description it seems like there are only 3. If there are actually more, but we're only talking about these 3, we should say that explicitly and explain why.

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +## How the cluster policies work
```suggestion
## How cluster policies work
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Cluster policies can be implemented using either the `airflow_local_settings.py` or the `pluggy` interface. Any attributes defined using cluster policies take precedence over the attributes defined i
```suggestion
Cluster policies can be implemented using either your `airflow_local_settings.py` file or the `pluggy` interface. Any attributes defined using cluster policies take precedence over the attributes defined in your DAG or Task. 
```
Do we need to add a follow-up sentence here about how they're implemented in Astro? I know you cover that below, but might be helpful to mention it here in case somebody is reading through the whole guide.

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +The DAG and Task cluster policies can raise the `AirflowClusterPolicyViolation` exception to indicate that the DAG or Task they were passed are not compliant and should not be loaded. This is excepti
```suggestion
Once implemented, if any DAGs or tasks are not compliant with your set policies, the policy will raise the `AirflowClusterPolicyViolation` exception and the DAG will not be loaded. This is exception is displayed on the Airflow web UI as an `import error`. 
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +You can use `AirflowClusterPolicySkipDag` exception to skip a DAG. Note that this exception will not be displayed on the Airflow web UI.
Can we add a bit more context here on what this means or why you would want to use it?

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +DAG policy allows you to overwrite or reconfigure DAG’a parameters as required. It allows you to:
```suggestion
The DAG policy allows you to overwrite or reconfigure a DAG’s parameters based on the criteria you set. It allows you to: 
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +**Example implementations:**
```suggestion
Some example implementations include:
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce default owner for the DAGs.
```suggestion
- Enforce a default owner for your DAGs.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce development DAGs do not run in production.
```suggestion
- Ensure development DAGs do not run in production.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Note that, `dag_policy` is applied before `task_policy` and after the DAG has been completely loaded. Hence, overriding the `default_args` parameter has no effect using `dag_policy`. If you want to o
```suggestion
Note that the `dag_policy` is applied before the `task_policy` and after the DAG has been completely loaded. Hence, overriding the `default_args` parameter has no effect using `dag_policy`. If you want to override the default operator settings, use task policies instead.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Task policy allows you to overwrite or reconfigure a task’s parameters.
```suggestion
The task policy allows you to overwrite or reconfigure a task’s parameters. 
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +**Example implementations:**
```suggestion
Some example implementations include:
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +**Example implementations:**
```suggestion
Some example implementations include:
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +**Example implementation:**
```suggestion
Some example implementations include:
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +### Pod mutation hook
Why is this one not listed above under types of cluster policies?

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using using the `pluggy` interface. `pluggy` is used for plugin management, and gives the ability to have multiple implementations of the policy functions. You can impleme
```suggestion
Policies can be implemented using using the `pluggy` interface. `pluggy` is used for plugin management, and allows you to have multiple implementations of the policy functions. You can implement `pluggy` interface using a setup-tools entrypoint in a custom module.
```

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using using the `pluggy` interface. `pluggy` is used for plugin management, and gives the ability to have multiple implementations of the policy functions. You can impleme
`You can implement `pluggy` interface using a setup-tools entrypoint in a custom module.`
Is this something we would expect the average airflow user to know how to do? Is there documentation on doing this somewhere else that we could link to? Or is this what you're describing below?

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +```bash
You'll want to indent these code blocks so they render within the numbered sections.

2024-07-01 18:27 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Create a package with the following structure for your plugin named `my_plugin`.
We should have instructions up front here on where you add this package - is it in the `plugins` folder if working from an Astro project?

2024-07-02 12:02 UTC, manmeetkaur commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using using the `pluggy` interface. `pluggy` is used for plugin management, and gives the ability to have multiple implementations of the policy functions. You can impleme
that is what I am describing. but may be i could elaborate if it's not self-explanatory.

2024-07-08 12:22 UTC, manmeetkaur commented
@kentdanas also want to include this diagram in the doc, I don't have snagit anymore, could you please add the 1px border and add to the PR ? Thanks! 
![Docs Diagrams - cluster policies](https://github.com/astronomer/docs/assets/75730393/28e79752-c267-4409-8603-478f45bf9c04)

2024-07-24 15:26 UTC, odaneau-astro requested changes
Great job on this! Looking forward to having this published on the website.
I left a few comments below.

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +- Stop a DAG from being executed by raising a `AirflowClusterPolicyViolation` exception
```suggestion
- Stop a DAG from being executed by raising an `AirflowClusterPolicyViolation` exception.
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
#### Example
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
Add a title here to allow users to quickly jump to examples from the navigation menu.

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
#### Example
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +### Task Instance mutation hook
Before Runtime 11, Task Instance Mutation Hook wasn't applied consistently (https://github.com/apache/airflow/pull/38440)
Not sure how we want to mention this.

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
#### Example
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +This policy is applicable to Kubernetes Pod created at run time when using the `KubernetesPodOperator` or `KubernetesExecutor`. This is an original policy function that allows altering `kubernetes.cl
```suggestion
This policy is applicable to Kubernetes Pod created at run time when using the `KubernetesPodOperator` or `KubernetesExecutor`. This is a policy function that allows altering `kubernetes.client.models.V1Pod` object before they are passed to the Kubernetes client for scheduling.
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +This could be used, for instance, to add sidecar or init containers to every worker pod launched. For example, you could use an init container to preload environment configuration or a sidecar contai
If we say in the tip below that Airflow doesn't allow this, maybe let's use a different example.

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
#### Example
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using using the `pluggy` interface. `pluggy` is used for plugin management, and allows you to have multiple implementations of the policy functions. You can implement `plu
```suggestion
Policies can be implemented using the `pluggy` interface. `pluggy` is used for plugin management, and allows you to have multiple implementations of the policy functions. You can implement `pluggy` interface using a setup-tools entrypoint in a custom module.
```

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +Using the `pluggy` method is available only in Airflow version 2.6 and above. For versions earlier than 2.6, you can use `config/airflow_local_settings.py` file under your `$AIRFLOW_HOME` to define y
This is not possible in Astro, Consider removing or clarifying

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +You can build a package for the cluster policies you want to apply to your Airflow environment. You can add this package to the `include` folder of your Astro project. You could then install it by [c
I would recommend using the `plugin` folder instead.

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +3. In `setup.cfg` add the following:
You don't need setup.cfg if you are using pyproject.toml
See https://astronomer.slack.com/files/U01QJUJR4TW/F05MAKRCDAN/pluggy_example.zip

2024-07-24 15:26 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +4. Build the `wheel` file:
Building a wheel is optional.

2024-07-25 16:10 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- `task_policy` : This policy is applicable to a Task object. It gets executed when the task is created during parsing of the task from DagBag at load time. This means that the whole task definition
```suggestion
- `task_policy` : This policy is applicable to a Task object. It gets executed when the task is created during parsing of the task from `DagBag` at load time. This means that the whole task definition can be altered in the task policy. It does not relate to a specific task running in a `DagRun`. The `task_policy` defined is applied to all the task instances that will be executed in the future.
```

2024-07-25 16:11 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- `task_instance_mutation_hook` : This policy is applicable to a Task Instance, which is an instance of a Task object and is created at run time. It takes a TaskInstance object `task_instance` as a p
```suggestion
- `task_instance_mutation_hook` : This policy is applicable to a Task Instance, which is an instance of a Task object and is created at run time. It takes a TaskInstance object, `task_instance`, as a parameter. This policy applies not to a task but to the instance of a task that relates to a particular `DagRun`. It is only applied to the currently executed run (in other words, instance) of that task. The policy is applied to a task instance in an Airflow worker before the task instance is executed, not in the DAG file processor. 
```

2024-07-25 16:12 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- `task_instance_mutation_hook` : This policy is applicable to a Task Instance, which is an instance of a Task object and is created at run time. It takes a TaskInstance object `task_instance` as a p
Nit-picky changes here. Our style guidelines don't allow Latin abbreviations such as "i.e."

2024-07-25 16:14 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- `task_instance_mutation_hook` : This policy is applicable to a Task Instance, which is an instance of a Task object and is created at run time. It takes a TaskInstance object `task_instance` as a p
```suggestion
- `task_instance_mutation_hook` : This policy is applicable to a Task Instance, which is an instance of a Task object and is created at runtime. It takes a TaskInstance object `task_instance` as a parameter. This policy applies not to a task but to the instance of a task that relates to a particular `DagRun`. It is only applied to the currently executed run (i.e. instance) of that task. The policy is applied to a task instance in an Airflow worker before the task instance is executed, not in the dag file processor. 
```

2024-07-25 16:15 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Cluster policies can be implemented using either your `airflow_local_settings.py` file or the `pluggy` interface. Any attributes defined using cluster policies take precedence over the attributes def
```suggestion
Cluster policies can be implemented using either your `airflow_local_settings.py` file or the `pluggy` interface. Any attributes defined using cluster policies take precedence over the attributes defined in your DAG or Task. On Astro, you can only implement policies using the `pluggy` interface.
```

2024-07-25 16:16 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Once implemented, if a DAG or task is not compliant with your set policies, the policy will raise the `AirflowClusterPolicyViolation` exception and the DAG will not be loaded. This exception is displ
Nit-picky passive voice fix. Style guidelines say to avoid passive voice

2024-07-25 16:18 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +This means that the DAG processor still parses all DAG files even if it is skipped using a DAG policy.
```suggestion
This means that the DAG processor still parses all DAG files even if you skip one using a DAG policy.
```

2024-07-25 16:19 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Mutate a DAG object after it is loaded in the DagBag.
```suggestion
- Mutate a DAG object after it is loaded in the `DagBag`.
```

2024-07-25 16:20 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce a default owner for your DAGs.
```suggestion
- Enforcing a default owner for your DAGs.
```

2024-07-25 16:20 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce certain tags for DAGs, either default or based on conditions.
```suggestion
- Enforcing certain tags for DAGs, either default or based on conditions.
```

2024-07-25 16:20 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Ensure development DAGs do not run in production.
```suggestion
- Ensuring development DAGs do not run in production.
```

2024-07-25 16:20 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Stop a DAG from being executed by raising an `AirflowClusterPolicyViolation` exception.
```suggestion
- Stopping a DAG from being executed by raising an `AirflowClusterPolicyViolation` exception.
```

2024-07-25 16:21 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce a task timeout policy.
```suggestion
- Enforcing a task timeout policy.
```

2024-07-25 16:21 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Override a `on_success_callback` or `on_failure_callback` for a task.
```suggestion
- Overriding a `on_success_callback` or `on_failure_callback` for a task.
```

2024-07-25 16:22 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Mutates tasks after they have been added to a DAG.
```suggestion
- It mutates tasks after they have been added to a DAG.
```

2024-07-25 16:23 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +The task policy allows you to overwrite or reconfigure a task’s parameters.
```suggestion
A task policy allows you to overwrite or reconfigure a task’s parameters. 
```

2024-07-25 16:23 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- It expects a `BaseOperator` as a parameter and you can configure skip/deny exceptions.
```suggestion
- It expects a `BaseOperator` as a parameter, and you can configure skip/deny exceptions.
```

2024-07-25 16:25 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Task Instance policy allows you to alter task instances before being queued by the Airflow scheduler. This is different from the `task_policy` function, which inspects and mutates tasks “as defined”,
```suggestion
Task Instance policy allows you to alter task instances before the Airflow scheduler queues them. This is different from the `task_policy` function, which inspects and mutates tasks “as defined”. By contrast, task instance policies inspect and mutate task instances before execution.
```

2024-07-25 16:25 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Enforce a specific queue for certain Airflow Operators.
```suggestion
- Enforcing a specific queue for certain Airflow Operators.
```

2024-07-25 16:25 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Modify a task instance between retries.
```suggestion
- Modifying a task instance between retries.
```

2024-07-25 16:26 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Note that since priority weight is determined dynamically using weight rules, you cannot alter the `priority_weight` of a task instance within the Task Instance mutation hook.
```suggestion
Note that since Airflow determines priority weight dynamically using weight rules, you cannot alter the `priority_weight` of a task instance within the Task Instance mutation hook.
```

2024-07-25 16:27 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +This policy is applicable to Kubernetes Pod created at run time when using the `KubernetesPodOperator` or `KubernetesExecutor`. This is a policy function that allows altering `kubernetes.client.model
```suggestion
This policy is applicable to Kubernetes Pod created at runtime when using the `KubernetesPodOperator` or `KubernetesExecutor`. This is a policy function that allows altering an `kubernetes.client.models.V1Pod` object before Airflow passes it to the Kubernetes client for scheduling.
```

2024-07-25 16:28 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +This could be used, for instance, to alter the resoures for a Pod or to add sidecar or init containers to every worker pod launched. Astro, however, does not allow adding init or sidecar containers.
```suggestion
For instance, one could use this to alter the resources for a Pod or to add sidecar or init containers to every worker pod launched. Astro, however, does not allow adding init or sidecar containers. [Astro](https://www.astronomer.io/docs/astro/deployment-metrics) provides advanced logging, metrics collection, and multiple ways to manage your environment without the need to run separate containers to collect stats or apply environment settings.
```

2024-07-25 16:28 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Set resource requests and limits.
```suggestion
- Setting resource requests and limits.
```

2024-07-25 16:29 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Increase resources assigned to a Pod.
```suggestion
- Increasing resources assigned to a Pod.
```

2024-07-25 16:38 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using the `pluggy` interface. `pluggy` is used for plugin management, and allows you to have multiple implementations of the policy functions. You can implement `pluggy` i
```suggestion
You can implement policies using the `pluggy` interface. `pluggy` is useful for plugin management, allowing you to have multiple implementations of the policy functions. You can implement a `pluggy` interface using a setup-tools entrypoint in a custom module.
```

2024-07-25 16:39 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Using the `pluggy` method is available only in Airflow version 2.6 and above. For versions earlier than 2.6, you can use `config/airflow_local_settings.py` file under your `$AIRFLOW_HOME` to define y
```suggestion
The `pluggy` method is available only in Airflow version 2.6 and above. For versions earlier than 2.6, you can use the `config/airflow_local_settings.py` file under your `$AIRFLOW_HOME` to define your [policies](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/cluster-policies.html#how-do-define-a-policy-function). Note that Astro only allows using `pluggy` to implement cluster policies.
```

2024-07-25 16:40 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +You can build a package for the cluster policies you want to apply to your Airflow environment. You can add this package to the `plugin` folder of your Astro project. You could then install it by [cu
```suggestion
You can build a package for the cluster policies you want to apply to your Airflow environment. You can add this package to the `plugin` folder of your Astro project. You can then install it by [customizing your `Dockerfile`](https://www.astronomer.io/docs/astro/cli/customize-dockerfile). 
```

2024-07-25 16:40 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +2. Define the policies in `policy.py`
```suggestion
2. Define the policies in `policy.py`:
```

2024-07-25 16:40 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +3. (Optional) Build the python package to generate the `wheel` file.
```suggestion
3. (Optional) Build the python package to generate the `wheel` file:
```

2024-07-25 16:44 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +3. Copy over the plugin package to the `plugins` dirctory of an Astro project.
```suggestion
3. Copy over the plugin package to the `plugins` directory of your Astro project. 
```

2024-07-25 16:44 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +4. Add the following line to your `Dockerfile`
```suggestion
4. Add the following line to your `Dockerfile`:
```

2024-07-25 16:46 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +5. For local Airflow, run `astro dev restart` to rebuild the Astro project. For Astro, run `astro deploy` to build and deploy to your Deployment.
```suggestion
5. Run `astro dev restart` to rebuild the Astro project locally. Run `astro deploy` to build and deploy to your Astro Deployment.
```

2024-07-25 16:48 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +5. For local Airflow, run `astro dev restart` to rebuild the Astro project. For Astro, run `astro deploy` to build and deploy to your Deployment.
```suggestion
5. For local Airflow, run `astro dev restart` to restart your local Astro instance. For Astro, run `astro deploy` to build and deploy to your Deployment.
```

2024-07-25 16:49 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Cluster policies are a set of functions that Airflow administrators can define to mutate or perform custom logic on a few important Airflow objects:
```suggestion
Cluster policies are sets of functions that Airflow administrators can define to mutate or perform custom logic on a few important Airflow objects:
```

2024-07-25 16:49 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +These policies allow administrators to centrally manage how Airflow users or DAG writers are interacting with the Airflow Cluster. Cluster policies can modify or restrict a user's capability based on
```suggestion
These policies allow administrators to centrally manage how Airflow users or DAG writers are interacting with the Airflow Cluster. Cluster policies can modify or restrict a user's capability based on organization policy or ensure that users conform to common standards. For example, you might want to ensure all DAGs have `tags` in your production Airflow environment.
```

2024-07-25 16:50 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- Astro CLI. See [Get started with Astro CLI](https://www.astronomer.io/docs/astro/cli/get-started-cli)
```suggestion
- The Astro CLI. See [Get started with Astro CLI](https://www.astronomer.io/docs/astro/cli/get-started-cli)
```

2024-07-25 16:51 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +There are three types of cluster policies you can use in Airflow:
```suggestion
You can use three types of cluster policies in Airflow:
```

2024-07-25 16:52 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +- `task_policy` : This policy is applicable to a Task object. It gets executed when the task is created during parsing of the task from DagBag at load time. This means that the whole task definition
```suggestion
- `task_policy` : This policy is applicable to a Task object. It gets executed when the task is created during parsing of the task from DagBag at load time. This means that the whole task definition can be altered in the task policy. It does not relate to a specific task running in a `DagRun`. The defined `task_policy` is applied to all the task instances that will be executed in the future.
```

2024-07-25 17:00 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Cluster policies are a set of functions that Airflow administrators can define to mutate or perform custom logic on a few important Airflow objects:
```suggestion
Cluster policies are sets of rules that Airflow administrators can define to mutate or perform custom logic on a few important Airflow objects:
```

2024-07-25 17:21 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +Using the `pluggy` method is available only in Airflow version 2.6 and above. For versions earlier than 2.6, you can use `config/airflow_local_settings.py` file under your `$AIRFLOW_HOME` to define y
```suggestion
The `pluggy` method is available only in Airflow version 2.6 and above. For versions older than 2.6, you can use the `config/airflow_local_settings.py` file on your `$AIRFLOW_HOME` to define your [policies](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/cluster-policies.html#how-do-define-a-policy-function). Note that Astro only allows using `pluggy` for implementing cluster policies.
```

2024-07-25 17:43 UTC, merobi-hub commented on learn/airflow-advanced-cluster-policies.md
> +5. For local Airflow, run `astro dev restart` to rebuild the Astro project. For Astro, run `astro deploy` to build and deploy to your Deployment.
```suggestion
5. Run `astro dev restart` to refresh your local Airflow instance. Run `astro deploy` to build and deploy to your Astro Deployment.
```

2024-07-25 21:21 UTC, kentdanas reviewed
@manmeetkaur left a few more comments for you, and Michael did some copy editing. Tamara also updated the screenshot, but it looks like that still needs to be added to the guide. Once all that is taken care of let me know and we should be good to get this merged!

2024-07-25 21:21 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +:::tip Alternate setup
Can we add some context here on when/why you might choose this alternate setup?

2024-07-25 21:21 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Policies can be implemented using the `pluggy` interface. `pluggy` is used for plugin management, and allows you to have multiple implementations of the policy functions. You can implement `pluggy` i
@manmeetkaur you're not actually describing how to use a setup-tools entrypoint in a custom module in this doc, are you? Is there an Airflow doc or something we could link to?

2024-07-25 21:21 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +### Setup your Astro project
```suggestion
### Step 2: Setup your Astro project
```

2024-07-25 21:21 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +2. Run `astro dev init` to initialize a new Astro project or open your Astro project.
Isn't this the same as step 1 above?

2024-07-25 21:21 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
In this guide, we describe how to use `pluggy` to implement cluster policies for an Astro project. If you are not using Astro, a similar implementation is possible but steps may vary slightly depending on your Airflow setup.
```
@manmeetkaur check me on how you want to word this - but I think we need something here stating that this is an astro-specific implementation, since most of Learn is OSS-focused.

2024-07-26 13:53 UTC, odaneau-astro requested changes

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +Cluster policies can be used to, for example, centrally:
```suggestion
Here are some common use cases for cluster policies:
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +- Verify a DAG's `catchup` parameter based on production or development environment
Another common one is setting is_paused_upon_creation to True for non-prod deployments to save costs.

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
```suggestion
## How to implement a cluster policy
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +## How cluster policies work
Consider splitting the content of the paragraph above into two parts. 
The way it is currently structured, we cover both the different types of policies and how they work in the same block. Since we have a section specifically for "How cluster policies work" with a diagram, we should rephrase above to only have the 4 types, then address how they work under the diagram.

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
The paragraphs after this do not match with the title. Let's add a new title.

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +
We should also consider combining this section with the Implementation section below as we are jumping from topic to topic a bit right now.

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +The best way to implement cluster policies is to build a package for them that you apply to your Airflow environment. You can add this package to the `plugins` folder of your Astro project and instal
```suggestion
The simplest way to implement cluster policies is to build a package for them that you apply to your Airflow environment. You can add this package to the `plugins` folder of your Astro project and install it by [customizing your `Dockerfile`](https://www.astronomer.io/docs/astro/cli/customize-dockerfile). This method uses `setuptools` entrypoint for your project. Read more about python packaging [here](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/). 
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +│       ├── policy.py
```suggestion
│       └── policy.py
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +│   ├── plugin_package/
```suggestion
│   └── plugin_package/
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +├── README.md
```suggestion
└── README.md
```

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +    dependencies = ["apache-airflow>=2.6"]
You may want to enforce python versions as well.

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +    RUN pip install include/plugin_package-0.1.0-py3-none-any.whl
The instructions say to copy the wheel in the plugins folder, but the commands reference the include folder.
You could also drop it at the root of the project and copy it yourself.
Also, it's nice to use wildcards in Dockerfile to support package upgrades without code changes in Dockerfile. 

COPY my_package-*.whl /usr/local/airflow
RUN pip install /usr/local/airflow/my_package-*.whl && rm /usr/local/airflow/my_package-*.whl

2024-07-26 13:53 UTC, odaneau-astro commented on learn/airflow-advanced-cluster-policies.md
> +    RUN pip install include/plugin_package-0.1.0-py3-none-any.whl
package name is my_package in the pyproject.toml. I'm pretty sure the built wheel will be named my_package... . Worth testing it.

2024-07-26 13:53 UTC, odaneau-astro commented on static/img/guides/airflow-advanced-cluster-policies_diagram.png
Refer to Astro's [Brand Style Guide](https://docs.google.com/presentation/d/1uGie2Ys4YHsKGl5aTAL_YdYxFQ6Qisms8mMF96BsX04/edit?usp=sharing) to use the right fonts and colors on this diagram.

2024-07-26 17:35 UTC, kentdanas approved these changes

2024-07-26 17:35 UTC, kentdanas commented on learn/airflow-advanced-cluster-policies.md
> +Task Instance policy allows you to alter task instances before the Airflow scheduler queues them. You can implement Task Instance policy using the function `task_instance_mutation_hook`. This is diff
```suggestion
A Task Instance policy allows you to alter task instances before the Airflow scheduler queues them. You can implement a Task Instance policy using the function `task_instance_mutation_hook`. This is different from the `task_policy` function, which inspects and mutates tasks “as defined”. By contrast, task instance policies inspect and mutate task instances before execution. It takes a TaskInstance object, `task_instance`, as a parameter. This policy applies not to a task but to the instance of a task that relates to a particular `DagRun`. It is only applied to the currently executed run (in other words, instance) of that task. The policy is applied to a task instance in an Airflow worker before the task instance is executed, not in the DAG file processor. 
```

2024-07-26 17:41 UTC, merged