0.35.1 release notes
astronomer/docs pull request #3917
Opened 2024-07-14 19:54 UTC by lzdanski

PR's to merge-in:

- [ ] Fix version support tables
- [ ] Update distribution info that was dropped in refactor

2024-07-14 20:09 UTC, lzdanski commented on software/release-notes.md
> +    - [GHSA-m425-mq94-257g]() -> https://nvd.nist.gov/vuln/detail/CVE-2023-44487 ?
@himabindu07 -I wasn't sure if i should link to the underlying CVE or to the `go` issue: https://github.com/grpc/grpc-go/security/advisories/GHSA-m425-mq94-257g

2024-07-14 20:09 UTC, lzdanski commented on software/release-notes.md
> +- Fixed a bug where if you had DAG-only deploys enabled, it was possible for users in one Deployment to access DAGs in other Deployments, even if the user did not have access to other DAG-only Deploy
@danielhoherd - how does this wording look?

2024-07-14 20:40 UTC, lzdanski commented on software/runtime-image-architecture.mdx
@RNHTTR - Partiall addresses https://github.com/astronomer/docs/issues/3905

2024-07-15 17:58 UTC, rishkarajgi commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. Each pod requires a n
How much do we need to go down on the severity of the bug fix in public facing notes? Can mentioning the capability this bug enables potentially attract bad actors in itself as this is now in public notes
`it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions`
cc: @danielhoherd @tonyHuinker

2024-07-15 18:03 UTC, lzdanski commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. Each pod requires a n
```suggestion
Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. This issue occurs in Software versions 0.34.0-0.34.2 and 0.35. To mitigate the issue you can:
```
How does this look? A similar phrasing is also in the [upgrade considerations](https://github.com/astronomer/docs/pull/3917/files#diff-cc9f2660bf7ec0036ab0ace29568f4a1f3cc08f023e59da9909235a0ba1577acR225) and might need to be reworded as well.

2024-07-15 18:20 UTC, rishkarajgi commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. Each pod requires a n
This can be omitted - `This issue occurs in Software versions 0.34.0-0.34.2 and 0.35.0`

2024-07-15 18:22 UTC, rishkarajgi commented on software/release-notes.md
> +
these can be omitted as well

2024-07-15 18:22 UTC, danielhoherd commented on software/release-notes.md
> +- Fixed a bug where if you had DAG-only deploys enabled, it was possible for users in one Deployment to access DAGs in other Deployments, even if the user did not have access to other DAG-only Deploy
No, I don't think that wording accurately describes the problem.

> Fixed a bug where a DAG-only deploy dag-server was accessible from any kubernetes namespace.

2024-07-15 18:51 UTC, lzdanski commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. Each pod requires a n
Removed thanks!

2024-07-15 18:56 UTC, lzdanski commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. Each pod requires a n
@danielhoherd - can you please review this most recent version? Looks like your comment is on an outdated one.

2024-07-15 19:09 UTC, tonyHuinker approved these changes

2024-07-15 19:10 UTC, danielhoherd commented on software/version-compatibility-reference.md
> +The following table shows version compatibility information for all currently supported versions of Astronomer Software and some legacy versions. Check [Astro Software lifecycle schedule](release-lif
```suggestion
The following table shows version compatibility information for all currently supported versions of Astronomer Software and some legacy versions. Check [Astronomer Software lifecycle schedule](release-lifecycle-policy.md#software-lifecycle-schedule) for more information about supported versions of Astronomer Software.
```

2024-07-15 19:20 UTC, danielhoherd commented on software/upgrade-astronomer.md
> +Due to an issue with the [DAG-only Deploy](deploy-dags.md#configure-dag-only-deploys-on-a-deployment) feature in Astronomer Software version 0.34.0-0.34.2 and 0.35, there is a risk that users could p
```suggestion
Due to an issue with the [DAG-only Deploy](deploy-dags.md#configure-dag-only-deploys-on-a-deployment) feature in Astronomer Software version 0.34.0-0.34.2 and 0.35.0, there is a risk that users could potentially access DAGs across different namespaces or Airflow deployments without proper permissions. This issue does not affect Deployments that do not use DAG-only deploys.
```

2024-07-15 19:21 UTC, danielhoherd commented on software/upgrade-astronomer.md
> +Due to an issue with the [DAG-only Deploy](deploy-dags.md#configure-dag-only-deploys-on-a-deployment) feature in Astronomer Software version 0.34.0-0.34.2 and 0.35, there is a risk that users could p
If we are mentioning 0.34.x here, should we change the title here to say "resolved in 0.35.1 and 0.34.3" ? Or should we remove all mentions of 0.34.x until we've released 0.34.3?

2024-07-15 19:26 UTC, danielhoherd commented on software/release-notes.md
> +Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access DAGs across different namespaces or Airflow deployments without proper permissions. See [Upgrade consider
```suggestion
Fixed an issue where if you had a DAG-only deploy, it was possible for users to access its dag-server from any other kubernetes namespace. See [Upgrade considerations for 0.34 and 0.35](https://www.astronomer.io/docs/software/upgrade-astronomer#upgrade-to-astronomer-software-034-or-035) for more details about the security fix.
```

2024-07-15 19:29 UTC, danielhoherd requested changes
The 0.35.x related changes in here look mostly good. I left some suggestions though that I think make a significant difference in understanding the problem.

2024-07-15 19:34 UTC, lzdanski commented on software/upgrade-astronomer.md
> +Due to an issue with the [DAG-only Deploy](deploy-dags.md#configure-dag-only-deploys-on-a-deployment) feature in Astronomer Software version 0.34.0-0.34.2 and 0.35, there is a risk that users could p
I'd prefer to keep this just 0.35.x and follow with 0.34 info when we do 0.34 release later this week. Will make adjustments because we're not ready for 0.34.3 release notes today.

2024-07-15 19:35 UTC, lzdanski commented on software/upgrade-astronomer.md
> +- If you use version 0.34.0-0.34.2 and 0.35, upgrade to the 0.34.3 or 0.35.1 as soon as they are available.
```suggestion
- Do not use DAG-only Deploys if you use version 0.35
- If you have not upgraded to version 0.35, wait until the next major release to upgrade your Software version
- If you use version 0.35, upgrade to 0.35.1 as soon as they are available.
```

2024-07-15 20:12 UTC, danielhoherd approved these changes
LGTM. 0.34 references are gone. Wording has been updated to an accurate description of the problem.

2024-07-16 01:23 UTC, lzdanski commented on software/release-notes.md
> +Fixed an issue where if you had a DAG-only deploy, it was possible for users to access its dag-server from any other kubernetes namespace. See [Upgrade considerations for 0.35](https://www.astronomer
```suggestion
Fixed an issue where if you had DAG-only deploys enabled, it was possible for users to access its dag-server from any other kubernetes namespace. See [Upgrade considerations for 0.35](https://www.astronomer.io/docs/software/upgrade-astronomer#upgrade-to-astronomer-software-035) for more details about the security fix.
```

2024-07-16 01:26 UTC, lzdanski commented on software/upgrade-astronomer.md
> +- If you use version 0.35, upgrade to 0.35.1 as soon as they are available.
```suggestion
- If you use version 0.35, upgrade to 0.35.1 as soon as they are available
```

2024-07-16 01:29 UTC, lzdanski commented
reviewed in preview and had multiple software team reviews. Can fast follow with any style/ build fixes if needed. Merging.

2024-07-16 01:29 UTC, merged