Best Practices guide on managing resources
astronomer/docs pull request #3933
Opened 2024-07-16 17:29 UTC by merobi-hub

This adds a guide on managing resources with a focus on when you would want to use the Terraform provider or the API as opposed to the UI.

2024-07-22 16:21 UTC, vandyliu approved these changes

2024-07-22 17:01 UTC, kushalmalani reviewed
Left one nit for a typo, but overall looks good

2024-07-22 17:01 UTC, kushalmalani approved these changes

2024-07-22 17:27 UTC, ichung08 commented on astro/best-practices/managing-resources.md
> +Astro recommends the Terraform Provider or Astro API when you need to manage resources programmatically. Typically, teams manage Deployments as code as they start managing instances at scale. Benefit
Is the emphasis here only on Deployments and not for other resources?

2024-07-22 18:14 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +Astro recommends the Terraform Provider or Astro API when you need to manage resources programmatically. Typically, teams manage Deployments as code as they start managing instances at scale. Benefit
Good catch, thank you. Replaced Deployments with resources here.

2024-07-22 18:15 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +Astro supports a number of approaches to managing [Deployment resources](https://www.astronomer.io/docs/astro/deployment-settings#deployment-resources), so you can provision the resources you need wh
Fixed these issues with others in a commit.

2024-07-22 19:08 UTC, ichung08 approved these changes
Approving for terraform section - changes look good thanks!

2024-07-22 22:21 UTC, kentdanas requested changes
This is looking good @merobi-hub! A couple questions throughout where we might want to add additional info.

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +id: managing-resources
Needs to be added to the sidebar

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +title: 'Managing resources on Astro'
Should we make the title "Managing Deployment resources on Astro" since that's how they're referred to in the text and other docs? Having just "resources" could be interpreted a few ways, including how to manage infra, etc.

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +Astro supports several approaches to managing [Deployment resources](https://www.astronomer.io/docs/astro/deployment-settings#deployment-resources), so you can provision the resources you need whethe
```suggestion
Astro supports several approaches to managing [Deployment resources](https://www.astronomer.io/docs/astro/deployment-settings#deployment-resources), so you can provision Deployments with the configuration you need whether you are just starting or you are deploying projects programmatically at scale.
```

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +Astro recommends the Astro UI for managing resources if you do not need to deploy or modify project config programmatically. If you are on a small team getting started or you are an individual dev cr
```suggestion
Astro recommends the Astro UI for managing resources if you do not need to deploy or modify project config programmatically. If you are a small team getting started or you are an individual dev creating projects on an ad hoc basis, the Astro UI will likely meet your needs when managing resources. In addition to all the options you need in order to create and customize resources, you will get guidance directly in the UI that will help ensure that your instance is right-sized for your use case.
```

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +Astro recommends the Terraform Provider or Astro API when you need to manage resources programmatically. Typically, teams manage resources as code as they start managing instances at scale. Benefits
Do we want to say "Astronomer recommends"? Since Astro is the name of the product, but it's "us" that are providing the recommendations.

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +Astro recommends the Terraform Provider or Astro API when you need to manage resources programmatically. Typically, teams manage resources as code as they start managing instances at scale. Benefits
As another benefit, I would mention that this makes it much faster to manage large numbers of deployments, especially onboarding new teams, etc.

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +## Managing resources programmatically
What about Deployment files and Deployment template files? I think those should be an option in here as well. https://www.astronomer.io/docs/astro/manage-deployments-as-code

2024-07-22 22:21 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +
I wonder if this doc is one where we might consider having a table upfront similar to the one we have in Choosing airflow or astro alerts https://www.astronomer.io/docs/astro/best-practices/airflow-vs-astro-alerts#recommended-alerts. With different scenarios, and then check boxes for which one is best. That might be helpful for anybody just looking for a quick "what are my options" check

2024-07-23 13:37 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +title: 'Managing resources on Astro'
I'm not sure. Some of the feedback suggested that focusing on Deployments only was too narrow because you can manage more than Deployments with the API and Terraform provider. And this functionality is referenced in the doc, so maybe for consistency we keep it broad?

2024-07-23 13:38 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +Astro recommends the Terraform Provider or Astro API when you need to manage resources programmatically. Typically, teams manage resources as code as they start managing instances at scale. Benefits
Ugh, typo!

2024-07-23 14:42 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +Astro recommends the Astro UI for managing resources if you do not need to deploy or modify project config programmatically. If you are on a small team getting started or you are an individual dev cr
Fixes applied in sidebars update commit

2024-07-23 21:20 UTC, merobi-hub commented on astro/best-practices/managing-resources.md
> +
Sounds great, added one in the most recent commit

2024-07-23 21:21 UTC, merobi-hub commented
Table of scenarios:
<img width="1134" alt="Screenshot 2024-07-23 at 17 15 42" src="https://github.com/user-attachments/assets/381de510-1f05-4f45-b399-541589028677">

2024-07-24 20:57 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +title: 'Managing resources on Astro'
Gotcha, makes sense. Fine to keep it as is

2024-07-24 21:03 UTC, kentdanas approved these changes
Looks great! A few minor comments, otherwise good to copy edit and publish next week for go time!

2024-07-24 21:03 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +Astronomer recommends choosing the following approaches for these common scenarios:
Can we add a sentence here (or maybe after the table?) that says something like "For more information on each of these options and when to chose, see the sections below"

2024-07-24 21:03 UTC, kentdanas commented on astro/best-practices/managing-resources.md
> +- [Deployment files](https://www.astronomer.io/docs/astro/manage-deployments-as-code). You can configure Deployments programmatically using Deployment files, which you can generate automatically from
Can we add a "Astronomer recommends this approach when...." sentence to this one too, so it's clear when to choose this vs the other two options?

2024-07-26 14:16 UTC, merged