add additional workload-identity role-bindings
astronomer/docs pull request #3940
Opened 2024-07-17 15:00 UTC by rob-1126

One of our VIP customers wanted more information about the service-accounts and a listing of all those that might need xcom access. This updates our previously incomplete list and adds a bit more detail to make this VIP happy.

2024-07-17 15:02 UTC, rob-1126 commented
resuscitates PR 3862

2024-07-18 18:19 UTC, lzdanski commented on software/integrate-iam.md
> +## Granting Access to Airflow components using XCom and secrets backends {sas-that-use-backends}
```suggestion
## Granting Access to Airflow components using XCom and secrets backends {#sas-that-use-backends}
```

2024-07-18 18:31 UTC, lzdanski requested changes
Some questions for you about what components/software is doing which actions?

2024-07-18 18:31 UTC, lzdanski commented on software/integrate-iam.md
> +Astronomer Software creates a set of service-accounts for each Airflow instance it manages. The following roles can require access to Airflow Xcom backends or secrets backends to function:
```suggestion
Astronomer Software creates a set of service accounts for each Airflow instance it manages. The following roles can require access to Airflow Xcom backends or secrets backends to function:
```

2024-07-18 18:31 UTC, lzdanski commented on software/integrate-iam.md
> +| `<release name>-triggerer`         | User-provided DAG code is interpreted at task run time and might incorporate references to values stored in secrets storage or XCom.            |
"user provided code is interpreted" by Astronomer Software? By Airflow? What is doing the interpreting for each of these?

2024-07-18 18:31 UTC, lzdanski commented on software/integrate-iam.md
> +| `<release name>-webserver`         | Provides users a mechanism to view and set secrets and to view XCom entries.|
```suggestion
| `<release name>-webserver`         | Provides a mechanism for you to view XCom entries and to view and set secrets. |
```

Again, who is the user?

2024-07-18 18:31 UTC, lzdanski commented on software/integrate-iam.md
> +| `<release name>-cleanup`           |  Accesses task instances and other data that might include serialized references to values stored in secrets backends or XCOM backends.       |
The `_ -cleanup` service account accesses task instances..?

2024-07-23 17:46 UTC, lzdanski requested changes

2024-07-23 17:46 UTC, lzdanski commented on software/integrate-iam.md
> +| `<release name>-triggerer`         | User-provided DAG code is interpreted by the triggerer at task run-time and might incorporate references to values stored in secrets storage or XCom.
```suggestion
| `<release name>-scheduler`         | Regularly interprets your DAG code by the scheduler to determine which tasks are part of DAGs and might incorporate references to values stored in secret storage or XCom.                  |
| `<release name>-worker`            | Regularly interprets your DAG code by the worker at task runtime and might incorporate references to values stored in secret storage or XCom.             |
| `<release name>-triggerer`         | Regularly interprets your DAG code by the triggerer at task run-time and might incorporate references to values stored in secrets storage or XCom.            |
```

is this correct?

2024-08-06 12:58 UTC, lzdanski approved these changes

2024-08-06 15:04 UTC, merged