3963 dbt on astro
astronomer/docs pull request #3964
Opened 2024-07-22 20:43 UTC by lzdanski

Resolves #3963 
Relates to #3960

2024-07-23 15:23 UTC, merobi-hub commented on astro/deploy-dbt-project.md
> +Use dbt on Astro, so you can now deploy your dbt projects directly to Astro, without changes tied to updates with your DAGs or full image code deploys. When you use a dbt project deploy, Astro bundle
```suggestion
Use dbt on Astro, so you can now deploy your dbt projects directly to Astro, without changes tied to updates to your DAGs or full image code deploys. When you use a dbt project deploy, Astro bundles all files in your dbt project and pushes them to Astro, where they are mounted on your Airflow containers so that your DAGs can access them.
```

2024-07-23 15:23 UTC, merobi-hub commented on astro/deploy-dbt-project.md
> +Use dbt on Astro, so you can now deploy your dbt projects directly to Astro, without changes tied to updates with your DAGs or full image code deploys. When you use a dbt project deploy, Astro bundle
This sentence didn't scan for me at first, so thought that this change might make it clearer.

2024-07-23 15:24 UTC, merobi-hub commented on astro/deploy-history.md
> +For each deploy, the **Deploy History** table shows the user that made the deploy, when they made the deploy, what image they used, the type of deploy, and any descriptions they added to the deploy.
```suggestion
For each deploy, the **Deploy History** table shows the user who made the deploy, when they made the deploy, what image they used, the type of deploy, and any descriptions they added to the deploy.
```

2024-07-23 15:25 UTC, merobi-hub commented on astro/deploy-history.md
> +    - DAG only deploy
```suggestion
    - DAG-only deploy
```

2024-07-23 15:26 UTC, merobi-hub approved these changes

2024-07-23 17:57 UTC, iancmoritz requested changes
Added a few notes, hope this helps! Otherwise, I think this is great for our Private Preview:) 

Can we note down the line to add an example use case of Cosmos <> dbt Deploys? Not pressing, but this would be helpful to users down the line.

2024-07-23 17:57 UTC, iancmoritz commented on astro/deploy-dbt-project.md
> +``bash
<img width="1054" alt="Screenshot 2024-07-23 at 1 50 43 PM" src="https://github.com/user-attachments/assets/f04dfbbe-69f0-454b-8af2-9d823ebe4d3b">
Think there's a formatting thing here that makes it not show as bash in PR preview!

2024-07-23 17:57 UTC, iancmoritz commented on astro/deploy-dbt-project.md
> +astro dbt deploy --mount-path /usr/local/airflow/dbt/example-dbt-project
Should this link to the CLI documentation on the commands at all? Could be helpful

2024-07-23 17:57 UTC, iancmoritz commented on astro/deploy-dbt-project.md
> +Use dbt on Astro, so you can now deploy your dbt projects directly to Astro, without changes tied to updates to your DAGs or full image code deploys. When you use a dbt project deploy, Astro bundles
```suggestion
Use dbt Deploys to deploy your dbt projects directly to Astro without changing your DAGs or making an image deploy. This is ideal for deploying dbt code that lives outside of your Astro project 

When you use a dbt project deploy, Astro bundles all files in your dbt project and pushes them to Astro, where they are mounted on your Airflow containers so that your DAGs can access them.
```

2024-07-23 17:57 UTC, iancmoritz commented on astro/deploy-dbt-project.md
> +If you have a dbt project in a different location than your Astro Project, such as a different folder in your local environment or at a different path, you can specify the mount path.
```suggestion
If your dbt code is accessed at a different path or folder than the default path, specify the mount path.
```

2024-07-23 17:57 UTC, iancmoritz commented on astro/deploy-history.md
> +You can roll back to any deploy within the last three months. If your last deploy was more than three months ago, you can only roll back to that deploy. After the rollback completes, the **Deploy His
```suggestion
You can roll back to any deploy within the last three months. If your last deploy was more than three months ago, you can only roll back to that deploy. After the rollback completes, the **Deploy History** table shows your rollback deploy as the most recent deploy and includes both your rollback description and rollback deploy time. Your Docker image tag, DAG bundle name, and dbt bundles are the same as the previous version you rolled back to. The historic deploy that you rolled back to still appears in chronological order in the table.
```

2024-07-23 17:58 UTC, lzdanski commented on astro/deploy-dbt-project.md
> +``bash
```suggestion
```bash
```

2024-07-23 18:00 UTC, lzdanski commented on astro/deploy-dbt-project.md
> +astro dbt deploy --mount-path /usr/local/airflow/dbt/example-dbt-project
Agreed. Right now because they are in separate PR's, it will throw a build error, so it has to be a fast follow after we merge tomorrow

2024-07-24 16:33 UTC, paolaperaza approved these changes
Made a couple comments and suggestions here @lzdanski.

The last few things i'd love to see here and that @iancmoritz I'd expect you to help with are:
- Can we list out the benefits of having dbt project separately from Airflow code if that's what we're recommending
- Link to "other ways to build your dbt project" (aka via image method) if/when we have that ready
- Context on `dbt project delete` and `dbt project add` or whatever those commands are
- Link to example GitHub Action CI/CD script or at least (in the immediate term) acknowledgement that this is a process you can do. Right now it reads like these CLI commands are the only way to do it.

@lzdanski Did we update CLI command reference as well with those commands?

2024-07-24 16:33 UTC, paolaperaza commented on astro/deploy-dbt-project.md
> +- An Astro Project that includes your dbt project
```suggestion
- An Astro project
- A dbt project
```

I feel like separate right? Because the Astro project is in theory in a different repo? Or either way -- it's a separate thing?

2024-07-24 16:33 UTC, paolaperaza commented on astro/deploy-dbt-project.md
> +
```suggestion
## Step 1: Deploy your full Astro image

In order to first deploy a dbt project to Astro, Astronomer recommends that you have an Astro project already running on your Deployment with DAGs that need to read from dbt. That way, your dbt project will be read and used when you deploy it.

If you are using a new Deployment, first deploy your Astro project with the Astro CLI by running:
```

2024-07-24 16:33 UTC, paolaperaza commented on astro/deploy-dbt-project.md
> +
Does this make sense? I didn't specify what would happen if you DON'T do this but basically.. this step is optional. It's just that if you do a dbt deploy without doing an image deploy then "nothing happens" bc there are no DAGs to call your dbt stuff if that makes sense

2024-07-24 16:33 UTC, paolaperaza commented on astro/deploy-dbt-project.md
> +```
@iancmoritz Can you explain what dbt delete is? No context here 🤔 Do you have to do it?

2024-07-24 16:36 UTC, lzdanski commented
> Made a couple comments and suggestions here @lzdanski.
> 
> The last few things i'd love to see here and that @iancmoritz I'd expect you to help with are:
> 
> * Can we list out the benefits of having dbt project separately from Airflow code if that's what we're recommending
> * Link to "other ways to build your dbt project" (aka via image method) if/when we have that ready
> * Context on `dbt project delete` and `dbt project add` or whatever those commands are
> * Link to example GitHub Action CI/CD script or at least (in the immediate term) acknowledgement that this is a process you can do. Right now it reads like these CLI commands are the only way to do it.
> 
> @lzdanski Did we update CLI command reference as well with those commands?

CLI changes in this PR: https://github.com/astronomer/docs/pull/3960, they got to me through separate channels

2024-07-24 16:44 UTC, lzdanski commented on astro/deploy-dbt-project.md
> +To learn more about running dbt core or dbt Cloud with Apache Airflow, see [Orchestrate dbt Core jobs with Airflow](/learn/airflow-dbt.md).
```suggestion
To learn more about running dbt core or dbt Cloud with Apache Airflow, see [Orchestrate dbt Core jobs with Airflow](https://www.astronomer.io/docs/learn/airflow-dbt).
```

2024-07-24 20:00 UTC, iancmoritz commented
> Made a couple comments and suggestions here @lzdanski.
> 
> The last few things i'd love to see here and that @iancmoritz I'd expect you to help with are:
> 
> * Can we list out the benefits of having dbt project separately from Airflow code if that's what we're recommending
> * Link to "other ways to build your dbt project" (aka via image method) if/when we have that ready
> * Context on `dbt project delete` and `dbt project add` or whatever those commands are
> * Link to example GitHub Action CI/CD script or at least (in the immediate term) acknowledgement that this is a process you can do. Right now it reads like these CLI commands are the only way to do it.
> 
> @lzdanski Did we update CLI command reference as well with those commands?

1. I don't think we should list too many benefits of having dbt code separately. I'm working on this story, but we should moreso emphasize that _if_ you have your dbt code separate, there's now a way to deploy it to Astro.
For some benefits, feel free to mention:
a. Your teams writing dbt can stay separate from the teams managing Airflow DAGs
b. ou don't have to include the dbt code in the image / You can deploy dbt code without an image deploy

2. Do we have examples of this in our Cosmos walkthrough?

3. Yeah can we bring in the context from the CLI command docs? I thought that was helpful. Also, emphasize that astro dbt delete is simply to remove the bundle from the image if it's no longer needed, and if there are changes it can be overwritten with an astro dbt deploy to the same mount path

4. Honestly I don't have this in a way I'd like to link in our docs yet.

2024-07-24 21:44 UTC, lzdanski commented
Received reviews from relevant stakeholders and technical reviewers. Merging.

2024-07-24 21:45 UTC, merged