Update export-datadog.md with new tags
astronomer/docs pull request #3969
Opened 2024-07-23 19:59 UTC by astro-anand

Updated datadog metrics export to include information on new tags that are readily available with the new astronomer logging provider.

2024-07-24 14:38 UTC, lzdanski commented on astro/export-datadog.md
> +  By default, Astro uses the tags `source=astronomer` and `service=astronomer-task-logs`. Astro automatically adds dag_id, task_id, run_id, and try_number tags to logs sent to Datadog. The minimum ru
```suggestion
  By default, Astro uses the tags `source=astronomer` and `service=astronomer-task-logs`. Astro automatically adds `dag_id`, `task_id`, `run_id`, and `try_number` tags to logs sent to Datadog.
  
  The minimum Astro Runtime versions to add specific tags to logs are 9.15.0, 10.9.0, and 11.5.0. To export logs to Datadog with a different Runtime version, upgrade `astronomer-providers-logging` to at least `1.5.1` in the `requirements.txt` file.
```

2024-07-24 14:40 UTC, lzdanski commented on astro/export-datadog.md
> +  By default, Astro uses the tags `source=astronomer` and `service=astronomer-task-logs`. Astro automatically adds dag_id, task_id, run_id, and try_number tags to logs sent to Datadog. The minimum ru
We also need to add to the prerequisites (I can't add directly to the PR):

- To export logs with specific tags, the minimum Astro Runtime versions is 9.15.0, 10.9.0, or 11.5.0 for all cloud providers.

2024-07-24 14:42 UTC, lzdanski requested changes
Final change - can't add it in a comment, but this needs to be added to the prerequisites in line 22: 
```
  - To add specific tags to export logs, use a minimum Runtime version of 9.15.0, 10.9.0, and 11.5.0 for all cloud providers.
```

2024-07-24 14:47 UTC, astro-anand commented
> Final change - can't add it in a comment, but this needs to be added to the prerequisites in line 22:
> 
> ```
>   - To add specific tags to export logs, use a minimum Runtime version of 9.15.0, 10.9.0, and 11.5.0 for all cloud providers.
> ```



> Final change - can't add it in a comment, but this needs to be added to the prerequisites in line 22:
> 
> ```
>   - To add specific tags to export logs, use a minimum Runtime version of 9.15.0, 10.9.0, and 11.5.0 for all cloud providers.
> ```

Could you clarify what the cloud providers context adds? This info is specific to the min Astro runtime versions that natively have the updated astronomer logging package.

2024-07-24 21:48 UTC, lzdanski commented
> > Final change - can't add it in a comment, but this needs to be added to the prerequisites in line 22:
> > ```
> >   - To add specific tags to export logs, use a minimum Runtime version of 9.15.0, 10.9.0, and 11.5.0 for all cloud providers.
> > ```
> 
> Could you clarify what the cloud providers context adds? This info is specific to the min Astro runtime versions that natively have the updated astronomer logging package. Maybe I need to clarify that if using major version 9, the minimum version is 9.15.0, if using major version 10.x -> 10.9.0, if using major version 11.x -> 11.5.0

Sure! Right now in our pre-reqs we have a different minimum runtime version required, which is `9` for GCP and `9.1` for AWS + Azure. If you must use 9.15, 10.9, or 11.5 to use the tags, then if we add this to the pre-reqs, we should clarify that this requirement is for all providers. Is it a little redundant? yes, but it is slightly ambiguous to have a cloud provider specific runtime requirement for the feature overall, but not something similar for this feature. https://github.com/astronomer/docs/pull/3969/files#diff-3ec861ec68fd1bd29151eff564502b924b9e3789a988c5a2cc88cf349733c54eR21

2024-07-25 14:49 UTC, lzdanski commented on astro/export-datadog.md
> +  The minimum Astro Runtime versions in which logs are enriched with task instance data are 9.15.0, 10.9.0, and 11.5.0 across all cloud providers. To export logs to Datadog with a different Astro Run
> To export logs to Datadog with a different Astro Runtime version, ...

Do you mean `to export logs **with the enriched task instance data** with a **lower** Astro runtime version, upgrade...`? The `different Astro Runtime version` is a little ambiguous.

2024-07-29 15:07 UTC, lzdanski approved these changes

2024-07-29 15:07 UTC, merged