0.35.2 Release Notes
astronomer/docs pull request #3986
Opened 2024-07-29 19:12 UTC by lzdanski

2024-07-31 14:29 UTC, danielhoherd commented on software/migrate-to-runtime.md
> + enableListAllRuntimeVersions: true
This probably isn't enough info. The full helm value they need to provide is:
```suggestion
astronomer:
  houston:
    config:
      deployments:
        enableListAllRuntimeVersions: true
```

2024-07-31 14:30 UTC, tonyHuinker requested changes
I think we need to change the wording on yanked. 

We do not actually prevent users from creating or upgrading to yanked versions, we are merely giving them extra information about which versions are yanked.  

FWIW, this seemed to be the same as on Astro.  I tested just now and I was able to upgrade to a Yanked Version

2024-07-31 14:31 UTC, danielhoherd commented on software/migrate-to-runtime.md
> +After enabling this configuration, the System Administrator can see the equivalent version of Astro Runtime in the **Migrate to Runtime-[Version number]** button. Note that all AC equivalent Runtime
```suggestion
After enabling this configuration, the System Administrator can see the equivalent version of Astro Runtime in the **Migrate to Runtime-[Version number]** button. Note that all AC equivalent Runtime versions prior to 2.2.5 are deprecated.
```

2024-07-31 14:31 UTC, rishkarajgi commented on software/manage-airflow-versions.md
> +You cannot create new Deployments or upgrade to the following versions of Runtime 11, which are `yanked`. These [restricted runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-v
We aren't restricting but just warning users on yanked versions

2024-07-31 14:33 UTC, danielhoherd commented on software/release-notes.md
> +  ```
```suggestion
    ```yaml
    fluentd:
      priorityClassName: <valid-class-name>
    prometheus-node-exporter:
      priorityClassName: <valid-class-name>
  ```
```

2024-07-31 14:33 UTC, danielhoherd commented on software/release-notes.md
> +    enableListAllRuntimeVersions: true
Same comment as above about needing more context here.

2024-07-31 14:36 UTC, danielhoherd commented on software/release-notes.md
> +- Fixed a bug in the deploy revision history page in the Astro Software UI that caused the date range query to fail if you set it to less than 90 days for the cleanup policy.
```suggestion
- Fixed a bug in the deploy revision history page in the Astronomer Software UI that caused the date range query to fail if you set it to less than 90 days for the cleanup policy.
```

2024-07-31 15:24 UTC, lzdanski commented on software/manage-airflow-versions.md
> +##### Restricted versions of Runtime 11
```suggestion
##### Yanked versions of Runtime 11
```

2024-07-31 15:24 UTC, lzdanski commented on software/manage-airflow-versions.md
> +You cannot create new Deployments or upgrade to the following versions of Runtime 11, which are `yanked`. These [restricted runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-v
```suggestion
Use caution if you create new Deployments or upgrade to the following versions of Runtime 11, which are `yanked`. These [Runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-versions) warn you about upgrading to or creating a Deployment with a version that contains a known limitation or bug.
```

2024-07-31 15:24 UTC, lzdanski commented on software/manage-airflow-versions.md
> +##### Restricted versions of Runtime 9
```suggestion
##### Yanked versions of Runtime 9
```

2024-07-31 15:24 UTC, lzdanski commented on software/manage-airflow-versions.md
> +You cannot create new Deployments or upgrade to the following versions of Runtime 9, which are `yanked`. These [restricted runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-ve
```suggestion
Use caution if you create new Deployments or upgrade to the following versions of Runtime 9, which are `yanked`. These [Runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-versions) warn you about upgrading to or creating a Deployment with a version that contains a known limitation or bug.
```

2024-07-31 15:24 UTC, lzdanski commented on software/manage-airflow-versions.md
> +Astro Runtime version 8.0.0 is a restricted version of the Astro Runtime (`yanked`), which means you can't create Deployments on Astro with this runtime version. These [restricted runtime versions](r
```suggestion
Astro Runtime version 8.0.0 is a `yanked` version of the Astro Runtime, which means you are advised not to create Deployments with this runtime version. These [Runtime versions](runtime-version-lifecycle-policy.mdx#restricted-runtime-versions) warn you about upgrading to or creating a Deployment with a version that contains a known limitation or bug.
```

2024-07-31 15:24 UTC, lzdanski commented on software/migrate-to-runtime.md
> +
```suggestion

If you use the dotted notation, use the configuration `astronomer.houston.config.deployments.enableListAllRuntimeVersions=true`. 
```

2024-07-31 15:44 UTC, lzdanski commented on software/runtime-version-lifecycle-policy.mdx
> +There are some restricted versions of the Astro runtime that have known bugs and can't be used even if you enabled [deprecated Astro Runtime versions](https://docs.astronomer.io/astro/upgrade-runtime
```suggestion
There are some restricted versions of the Astro runtime that have known bugs and shouldn't be used.
```

2024-07-31 16:32 UTC, danielhoherd commented on software/migrate-to-runtime.md
> +If you use the dotted notation, use the configuration `astronomer.houston.config.deployments.enableListAllRuntimeVersions=true`.
We probably don't need this. Sorry, I should've been more clear when suggesting the change that it was just a reference for us to easily see what was going on. We don't want to steer people towards using the mechanism that uses this dotted notation.

2024-07-31 16:33 UTC, lzdanski commented on software/migrate-to-runtime.md
> +If you use the dotted notation, use the configuration `astronomer.houston.config.deployments.enableListAllRuntimeVersions=true`.
```suggestion
```

2024-07-31 16:33 UTC, danielhoherd commented on software/release-notes.md
> +Or use the alternative dot notation configuration, `astronomer.houston.config.deployments.enableListAllRuntimeVersions=true`.
Apologies again about suggesting this. We should remove it and just go with the yaml snip above.

2024-07-31 16:34 UTC, danielhoherd commented on software/release-notes.md
> +            enableListAllRuntimeVersions: true
Whitespace is really important in yaml, and these indentations are wrong.
```suggestion
    astronomer:
      houston:
        config:
          deployments:
            enableListAllRuntimeVersions: true
```

2024-07-31 16:41 UTC, lzdanski commented on software/migrate-to-runtime.md
> +        enableListAllRuntimeVersions: true
astronomer:
      houston:
        config:
          deployments:
            enableListAllRuntimeVersions: true
```

2024-07-31 16:42 UTC, tonyHuinker approved these changes

2024-07-31 17:00 UTC, danielhoherd approved these changes

2024-08-01 15:03 UTC, lzdanski commented on software/release-notes.md
> +Release date: July 31, 2024
```suggestion
Release date: August 1, 2024
```

2024-08-01 19:37 UTC, danielhoherd approved these changes

2024-08-01 20:23 UTC, tonyHuinker approved these changes

2024-08-01 21:05 UTC, merged