DNS options update
astronomer/docs pull request #4009
Opened 2024-08-02 22:15 UTC by afastronomer

This PR is related to #4002 issue

2024-08-05 21:02 UTC, lzdanski requested changes
Let's get the AWS one ready and then I can move over the changes to make the others consistent - do these look ok?

2024-08-05 21:09 UTC, afastronomer commented on astro/connect-aws.md
> +Private hosted zones can be created for refleting particular DNS records in the customer environment. This solution doesn't require any changes or additional configurations at the customer side. Priv
Zones will be created on Astro side by CRE team.

2024-08-05 21:10 UTC, afastronomer commented on astro/connect-aws.md
> +- List of DNS records for the Private zone
"Private" zone is a type name (another type is "Public"). That's why I used capitalization.

2024-08-12 13:25 UTC, lzdanski approved these changes

2024-08-12 15:06 UTC, afastronomer commented
LGTM

2024-08-12 19:21 UTC, merged