Update pre-created namespace docs
astronomer/docs pull request #421
Opened 2022-02-25 12:22 UTC by jwitz

This PR reconfigures the namespace doc to better capture the considerations and workflow of configuring the feature. Most content changes here come from @cmarteepants, original draft here : https://www.notion.so/astronomerio/Configure-a-Pre-Created-Namespace-Pool-for-Deployments-604b249843ff4da0a8cfa474cb045622

2022-02-25 15:06 UTC, cmarteepants requested changes
I like how you cleaned up my writing. My concern is that we trimmed down the "When To Use Pre-Created Namespaces" too much

2022-02-25 15:06 UTC, cmarteepants commented on software/pre-create-namespaces.md
> +By configuring a pool of pre-created namespaces, Astronomer Software requires permissions only for the individual namespaces you configure. If your organization does not want Astronomer Software to h
More general comment, but I think we should return the example, and Kube explanation on namespace vs cluster permissions - for both internal and external purposes. It gives Customer Success and Sales talking points. What are "sensitive resources" and why is it a problem to give Astronomer Software cluster-level permissions?

2022-02-25 15:06 UTC, cmarteepants commented on software/pre-create-namespaces.md
> +         verbs: ["create", "delete", "get", "patch"]
Line 105-107 should be removed. We don't actually need it. Sorry, will update notion doc.

2022-02-25 16:06 UTC, jwitz commented on software/pre-create-namespaces.md
> +By configuring a pool of pre-created namespaces, Astronomer Software requires permissions only for the individual namespaces you configure. If your organization does not want Astronomer Software to h
I added back a bit of info from the original draft, mainly that the resources in question are secrets and that the permissions are a problem only if you are in a cluster with other applications.

2022-02-28 18:02 UTC, cmarteepants approved these changes

2022-03-01 03:08 UTC, paolaperaza approved these changes
A few wording suggestions here @jwitz but this LGTM - will let you finish it up.

I ended up suggesting that some high-level additions be made to the top level section even though they were already sort of covered in the `Technical Deep Dive` as I thought they were logically necessary to make the statements above.

Will be good to get this one out! Love the prescriptive guidance and tone. 👏

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +- kubectl with access to the cluster hosting Astronomer Software.
Links?

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +2. Save this file and name it `commander.yaml`.
Should this file be called something else depending on the namespace? If the user repeats steps 1-3, they'll have a ton of files named the same thing

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +## Step 1: Configure Namespaces for use with Astronomer Software
```suggestion
## Step 1: Create a Pool of Namespaces
```

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +## Step 2: Configure Astronomer Software
```suggestion
## Step 2: Configure Astronomer to Use Namespace Pool
```

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +After enabling the Pre-Created Namespace Pool, the namespaces you registered earlier will appear as an option when creating a new Deployment via the Software UI.
```suggestion
After enabling the pre-created namespace pool, the namespaces you registered earlier will appear as an option when creating a new Deployment via the Software UI.
```

We're not capitalizing above

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +Alternatively, when you create Deployments via the CLI, you will be prompted to select one of the available namespaces for your new Deployment.
```suggestion
To create a Deployment via the Astronomer CLI, you will be prompted to select one of the available namespaces for your new Deployment.
```

2022-03-01 03:08 UTC, paolaperaza commented on software/pre-create-namespaces.md
> +If no namespaces are available, you will receive an error when creating new Deployments in both the CLI and UI. To reuse a pre-created namespace, you first need to return the namespace to the pool by
```suggestion
If no namespaces are available, you will receive an error when creating new Deployments in both the Astronomer CLI and Software UI. To reuse a namespace that's already in use, the corresponding Deployment has to first be deleted. Once a Deployment is deleted, its namespace will be released back to the namespace pool and can be used for a new Deployment.
```

2022-03-01 11:34 UTC, jwitz commented on software/pre-create-namespaces.md
> +After configuring this feature, users will be required to select a namespace from the pool whenever they create a new Deployment. After they create a Deployment, the namespace they select will no lon
Moving that first sentence to the next section, I think it fits better there

2022-03-01 11:40 UTC, jwitz commented on software/pre-create-namespaces.md
> +## Step 1: Configure Namespaces for use with Astronomer Software
I don't think this is technically correct. You are just creating the namespaces here - they aren't yet configured as a pool or grouped together, that happens in the Helm config.

2022-03-01 11:41 UTC, jwitz commented on software/pre-create-namespaces.md
> +2. Save this file and name it `commander.yaml`.
I think you can continually apply the same file with different values, and Kube will just continue adding namespaces regardless of the file name. I can make it clear that the file can be reused

2022-03-01 11:50 UTC, jwitz commented on software/pre-create-namespaces.md
> +If no namespaces are available, you will receive an error when creating new Deployments in both the CLI and UI. To reuse a pre-created namespace, you first need to return the namespace to the pool by
Not sure why we shifted all language from active to passive here. I feel confident in the first version of this paragraph

2022-03-01 11:51 UTC, merged

2022-03-01 15:33 UTC, cmarteepants commented on software/pre-create-namespaces.md
> +2. Save this file and name it `commander.yaml`.
Yes, it really doesn't matter _what_ the file is called. You can reuse the same one, and just update the namespaces. Or you can have one per namespace if you are saving them for reference somewhere.