Astro 2/28 Release Notes
astronomer/docs pull request #426
Opened 2022-02-28 13:33 UTC by jwitz

Template PR for this week's Astro release. SMEs, please either:

- Directly update the PR with bullet points describing your change
- Comment in the PR describing your change, and I'll add it to the file myself

I'll cross reference these changes to those available in the Staging PR to make sure that we capture all changes!

2022-03-03 14:25 UTC, jwitz commented on astro/cli-release-notes.md
> +When you run this command, the CLI runs several quick tests to ensure that your DAG code doesn't call any missing values. This includes calling all OS-level variables, Airflow Connections, and Airflo
```suggestion
When you run this command, the CLI runs several quick tests to ensure that your DAG code doesn't call any missing values. This includes calling all OS-level variables, Airflow Connections, and Airflow Variables to check whether each of those objects has a value. Additionally, this command runs prebuilt unit test using Pytest. These unit tests are the same ones that are included by default with your project as described in [Test DAGs Locally with Pytest](test-and-troubleshoot-locally.md#test-dags-locally-with-pytest).
```

2022-03-03 14:26 UTC, jwitz commented on astro/cli-release-notes.md
> +Generally speaking, `astrocloud dev parse` is a more robust but less customizable testing command than `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, the
```suggestion
Generally speaking, `astrocloud dev parse` is a more robust but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we recommend using `astrocloud dev parse` as your primary testing tool. 
```

2022-03-03 14:27 UTC, jwitz commented on astro/cli-release-notes.md
> +These are the same configurations that you can set via the **Edit Configuration** page in the Cloud UI. For more information about these configurations, see [Configure a Deployment](configure-deploym
```suggestion
These are the same configurations that you can set via the **Edit Configuration** button in the Cloud UI. For more information about these configurations, see [Configure a Deployment](configure-deployment.md).
```

2022-03-03 14:27 UTC, jwitz commented on astro/release-notes.md
> +If a new user joins your Organization without having first been invited to a Workspace, their first login to the Cloud UI will now bring them to the default Organization view. From here, they can sta
```suggestion
If a new user joins your Organization without having first been invited to a Workspace, their first login to the Cloud UI will now bring them to the default Organization view. From here, they can start creating new Workspaces as an Organization Member:
```

2022-03-03 16:54 UTC, jwitz commented on astro/cli-release-notes.md
> +You can now use `astrocloud dev parse` to catch errors caused by missing OS Variables, Airflow Connections, and Airflow Variables in your DAGs,
```suggestion
You can now use `astrocloud dev parse` to run predefined collection of tests which ensure that essential aspects of your code are correctly formatted.
```

2022-03-03 16:55 UTC, jwitz commented on astro/cli-release-notes.md
> +When you run this command, the CLI runs several quick tests to ensure that your DAG code doesn't call any missing values. This includes calling all OS-level variables, Airflow Connections, and Airflo
```suggestion
When you run this command, the CLI runs several quick tests to ensure that your DAG code doesn't call any missing values. Specifically, it calls all OS-level variables, Airflow Connections, and Airflow Variables to check whether each of those objects has a value. Additionally, this command runs prebuilt unit tests on your Astro project using Pytest. These unit tests are the same ones that are included by default with your project as described in [Test DAGs Locally with Pytest](test-and-troubleshoot-locally.md#test-dags-locally-with-pytest).
```

2022-03-03 16:59 UTC, jwitz commented on astro/cli-release-notes.md
> +Generally speaking, `astrocloud dev parse` is a more robust but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we recom
```suggestion
Generally speaking, `astrocloud dev parse` is a more convenient but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we recommend using `astrocloud dev parse` as your primary testing tool. 
```

2022-03-03 22:35 UTC, sunkickr requested changes
Just need to update the wording on the `dev parse` command

2022-03-03 22:35 UTC, sunkickr commented on astro/cli-release-notes.md
> +`astrocloud deploy` no longer pushes code to your Deployment if the CLI detects basic errors in your DAGs. If any of your projects contain these errors, then certain deploys might stop working after
I think you need to say somewhere in here that the this will only happen if you are using runtime 4.1.0 and above

2022-03-03 22:35 UTC, sunkickr commented on astro/cli-release-notes.md
> +To better protect your Deployments from unexpected errors, `astrocloud deploy` now automatically applies tests from `astrocloud dev parse` to your Astro project before pushing new code to a Deploymen
I would say it is just one test that checks for errors. The other "tests" are excluding variables and connections

2022-03-03 22:35 UTC, sunkickr commented on astro/cli-release-notes.md
> +When you run this command, the CLI runs several quick tests to ensure that your DAG code doesn't call any missing values. This includes calling all OS-level variables, Airflow Connections, and Airflo
This needs to be updated see comments I left on other PR

2022-03-03 22:40 UTC, chomipi88 requested changes

2022-03-04 10:16 UTC, jwitz commented on astro/cli-release-notes.md
> +You can now use `astrocloud dev parse` to catch errors caused by missing OS Variables, Airflow Connections, and Airflow Variables in your DAGs,
Yeah this is better for release notes - wasn't sure when we were going to publish the other PRs, so wanted to get as much info here first and update it accordingly once we had more supporting docs

2022-03-04 10:47 UTC, jwitz commented on astro/cli-release-notes.md
> +To better protect your Deployments from unexpected errors, `astrocloud deploy` now automatically applies tests from `astrocloud dev parse` to your Astro project before pushing new code to a Deploymen
I think we should still put focus on "original behavior" in any breaking change notes. The implication of the base note is that you need to start checking DAGs for errors, so don't think we need to repeat this advice in the warning note.

2022-03-04 10:49 UTC, jwitz commented on astro/cli-release-notes.md
> +These are the same configurations that you can set via the **Edit Configuration** button in the Cloud UI. For more information about these configurations, see [Configure a Deployment](configure-deplo
I don't think we imply anywhere that you can update envars or API keys, so generally not a fan of saying what something "doesn't" do unless there's an alternative or additional consideration there.

2022-03-04 10:51 UTC, jwitz commented
Updated for review! @paolaperaza @sunkickr these release notes might need to be updated after we finalize our language in the other PR, but for now this should be good for getting the info out there.

2022-03-04 15:24 UTC, sunkickr requested changes
removed describing parse as running multiple tests

2022-03-04 15:24 UTC, sunkickr commented on astro/cli-release-notes.md
> +`astrocloud dev parse` is a new Astro CLI command that allows you to run a set of basic tests against your Astro project to ensure that essential aspects of your code are properly formatted.
```suggestion
`astrocloud dev parse` is a new Astro CLI command that allows you to run a basic test against your Astro project to ensure that essential aspects of your code are properly formatted.
```

2022-03-04 15:24 UTC, sunkickr commented on astro/cli-release-notes.md
> +This includes the DAG integrity test that is run with `astro dev pytest`, as well as checks to ensure that your DAGs will run on the Airflow Webserver.
```suggestion
This includes the DAG integrity test that is run with `astro dev pytest` which checks that your DAGs will run on the Airflow Webserver.
```

2022-03-04 16:52 UTC, sunkickr approved these changes
LGTM

2022-03-04 18:05 UTC, jwitz commented on astro/release-notes.md
> +- The usage threshold for bars in the **Worker CPU** and **Worker Memory** charts to appear red has been reduced from 95% to 90%.
```suggestion
- The usage threshold for bars in the **Worker CPU** and **Worker Memory** charts to appear red has been reduced from 95% to 90%. This is to make sure that you get an earlier warning if your Workers are close to hitting their resource limits.
```

2022-03-04 18:08 UTC, merged