Update docs for API key functionality
astronomer/docs pull request #433
Opened 2022-03-01 15:24 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/429

2022-03-01 17:57 UTC, jwitz commented on astro/airflow-api.md
> +To retrieve an access token, [create a Deployment API key](api-keys.md#create-an-api-key) on Astro and run the following API request:
@sunkickr I wasn't sure what implications your changes had for Airflow API requests. Our example requests still use tokens, so for now I think we still need to keep info about requesting access tokens in this doc. Is that right?

2022-03-01 17:57 UTC, jwitz commented on astro/airflow-api.md
> +To retrieve your Deployment URL, open your Deployment in the Cloud UI and click Open Airflow. The URL for the Airflow UI is your Deployment URL. It includes the name of your Organization and a short
```suggestion
To retrieve your Deployment URL, open your Deployment in the Cloud UI and click **Open Airflow**. The URL for the Airflow UI is your Deployment URL. It includes the name of your Organization and a short Deployment ID. For example, your Deployment URL will look similar to `https://mycompany.astronomer.run/dhbhijp0`.
```

2022-03-01 17:57 UTC, jwitz commented on astro/api-keys.md
> +- Its key ID and secret are valid indefinitely and can be used to access Deployments without additional authentication.
```suggestion
- Its key ID and secret are valid indefinitely and can be used to access Deployments without manual authentication.
```

2022-03-01 17:57 UTC, jwitz commented on astro/ci-cd.md
> +2. Build your Astro project into a Docker image and push the image to your Deployment.
I condensed these into one step since it's technically the same command/ step

2022-03-01 17:57 UTC, jwitz commented on astro/ci-cd.md
> +    env:
@sunkickr Could use confirmation here that indentation is correct

2022-03-01 17:57 UTC, jwitz commented on astro/ci-cd.md
> +    name: CI/CD
```suggestion
    name: Astronomer CI - Deploy Code
```

2022-03-01 17:57 UTC, jwitz commented on astro/ci-cd.md
> +    brew install astronomer/cloud/astrocloud@1.2.0
@sunkickr I extrapolated from your example and updated the Jenkins script as well. Are you able to verify this or should I tag another SME?

2022-03-01 17:57 UTC, jwitz commented on astro/deploy-code.md
> +To validate your code before deploying it to Astro, you can run `astrocloud deploy --pytest`. The `--pytest` flag runs all pytests in your project's `tests` directory. If any of these tests fail, you
```suggestion
To validate your code before deploying it to Astro, you can run `astrocloud deploy --pytest`. Adding the `--pytest` flag makes the CLI run all pytests in your project's `tests` directory. If any of these tests fail, your code deploy will also fail.
```

2022-03-02 15:46 UTC, jwitz commented
@paolaperaza Some outstanding technical questions here, but the content itself is now ready for review!

2022-03-02 22:48 UTC, paolaperaza requested changes
@sunkickr @jwitz Just took a look here - made some copy suggestions and had some structural Qs as well. Primarily -

- I agree we should scrap the Access Token piece from the Deployment API Key doc and just add to Airflow API since it's the only use case where it's needed
- Should we not add a "Using Deployment API Keys" section to that doc and instead add that content to `Deploy Code` doc?
- The overview of Deployment API Keys seems a little repetitive and not succinct - @jwitz curious if you think there's a chance to re-work there
- Had some questions in CI/CD doc

2022-03-02 22:48 UTC, paolaperaza commented on astro/api-keys.md
>  - It can deploy code to Astro (customizable permissions coming soon).
```suggestion
- It can be used to deploy code to Astro via [CI/CD](ci-cd.md).
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/api-keys.md
>  This guide provides steps for creating and deleting Deployment API keys.
```suggestion
This guide provides steps for creating and deleting Deployment API keys. Customizable permissions coming soon.
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/api-keys.md
> -- Its key ID and secret are valid indefinitely and can be used to fetch a short-lived access token that assumes the permissions of the Deployment API key. This access token is required by the Astro A
Should we delete this, or reframe so that it's Airflow API specific only?

> Its key ID and secret are valid indefinitely and can be used to fetch a short-lived access token that assumes the permissions of the Deployment API key. This access token can be used to make requests to the [Airflow REST API](airflow-api.md).

2022-03-02 22:48 UTC, paolaperaza commented on astro/api-keys.md
> +## Using Deployment API Keys
```suggestion
## Using Deployment API Keys in Astro CLI
```

I'm a little hesitant to title this header as a general "using Deployment API Keys" since the two primary use cases we've laid out already have their own docs.

I'm thinking either we -
- Make this section specific to Astro CLI and not try to keep it as an umbrella OR
- We don't add anything here and instead create a `Deploy via CLI with Deployment API Key` to the bottom of our [Deploy Code doc](https://docs.astronomer.io/astro/deploy-code#step-1-authenticate-to-astro)

This is really the content that's missing and I'm not sure this doc is actually the best place for it. @jwitz @sunkickr What do you guys think?

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +- A Deployment ID. To find this, open your Deployment in the Cloud UI and copy the unique string at the end of the URL (e.g. `cktogz2eg847343yzo9pru1b0d` is the ID in `https://cloud.astronomer.io/<wo
```suggestion
- A Deployment ID. To find this, open your Deployment in the Cloud UI and copy the unique string at the end of the URL (e.g. `cktogz2eg847343yzo9pru1b0d` is the ID in `https://cloud.astronomer.io/<workspaceId>/deployments/cktogz2eg847343yzo9pru1b0d`). You can also find this value by running `astrocloud deployment list` via the Astro CLI.
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +1. Access your Deployment using API key credentials. These credentials must be set as OS-level environment variables called `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET`.
```suggestion
1. Require and reference Deployment API key credentials. These credentials must be set as OS-level environment variables called `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET`. This can be done on your local machine or within your CI/CD tool of choice.
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +2. Build your Astro project into a Docker image and push the image to your Deployment.
```suggestion
2. Install the Astro CLI
3. Build your Astro project into a Docker image and push the image to your Deployment. This is done by running `astrocloud deploy`.
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +$ astrocloud deploy <your-deployment-id>
Does this bash script assume you're running it from a machine that has the Astro CLI installed?

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +$ astrocloud deploy <your-deployment-id>
```suggestion
# Set Deployment API key credentials as environment variables
$ export ASTRONOMER_KEY_ID="<your-api-key-id>"
$ export ASTRONOMER_KEY_SECRET="<your-api-key-secret>"

# Access your Astro project
$ cd <your-astronomer-project>

# Push your Astro project to your Deployment on Astro
$ astrocloud deploy <your-deployment-id>
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +$ astrocloud deploy <your-deployment-id>
Tweaked copy here. More generally, spacing seems like best practice to me?

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> -    ```
Do we feel like users just don't really need to actually run this script, so we should provide guidelines for it?

2022-03-02 22:48 UTC, paolaperaza commented on astro/ci-cd.md
> +      ## Sets environment variable
```suggestion
      ## Sets Deployment API key credentials as environment variables
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/deploy-code.md
> +Astro makes it easy for your team to test Airflow DAGs locally and push them to a Deployment in a Production or Development environment. The following diagram shows how your Astro project can be pack
```suggestion
Astro makes it easy for your team to test Airflow DAGs locally and push them to a Deployment in a production or development environment. The following diagram shows how your Astro project can be packaged and deployed to Astro via the Astro CLI:
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/deploy-code.md
> +Astro makes it easy for your team to test Airflow DAGs locally and push them to a Deployment in a Production or Development environment. The following diagram shows how your Astro project can be pack
@jwitz I sort of still feel like the architecture diagram still makes more sense below where we can really dig in... the line here that references it is probably an error/typo. WDYT?

2022-03-02 22:48 UTC, paolaperaza commented on astro/deploy-code.md
> +For more information about running Pytests, see [Test and Troubleshoot](test-and-troubleshoot-locally.md#test-dags-locally-with-pytest).
```suggestion
As one way to validate your code before deploying it to Astro, you can run `astrocloud deploy --pytest`. Adding the `--pytest` flag triggers the CLI to run all tests in the `tests` directory of your Astro project with [pytest](https://docs.pytest.org/en/7.0.x/). If any of these tests fail, your code deploy will also fail. This can help you prevent your team from deploying DAGs to Astro that aren't production-grade.

For more information about testing DAGs with pytest, see [Test and Troubleshoot Locally](test-and-troubleshoot-locally.md#test-dags-locally-with-pytest).
```

2022-03-02 22:48 UTC, paolaperaza commented on astro/deploy-code.md
> +For more information about running Pytests, see [Test and Troubleshoot](test-and-troubleshoot-locally.md#test-dags-locally-with-pytest).
A little more color here. @sunkickr Is it proper to say `run pytests` or is it `run tests with pyest`? Something for our style guide 👀

2022-03-02 22:48 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +## Test DAGs Locally with Pytest
`pytest` is the name of a package and a proper non - should it not be capitalized here? https://docs.pytest.org/en/7.0.x/

2022-03-02 22:48 UTC, paolaperaza commented on astro/airflow-api.md
> +To retrieve an access token, [create a Deployment API key](api-keys.md#create-an-api-key) on Astro and run the following API request:
Keeping this comment but realizing after the fact that this is what you did here 👍

2022-03-02 22:50 UTC, paolaperaza commented on astro/ci-cd.md
> +          astrocloud deploy <deployment-id>
Do we still need to have this up top?

 ```
env:
          DEPLOYMENT_ID: <deployment-id>
```

Or I guess since it's only mentioned once (as opposed to many times before) the user could just replace it... maybe make that explicit?

2022-03-03 10:11 UTC, jwitz commented on astro/api-keys.md
>  This guide provides steps for creating and deleting Deployment API keys.
Realizing this is duplicative of the intro sentence , but also I think any sort of "coming soon" statement would be better suited in the bulleted list.

2022-03-03 10:13 UTC, jwitz commented on astro/api-keys.md
> -- Its key ID and secret are valid indefinitely and can be used to fetch a short-lived access token that assumes the permissions of the Deployment API key. This access token is required by the Astro A
Just removing the first bit, since that's repetitive of an earlier point.

2022-03-03 10:14 UTC, jwitz commented on astro/test-and-troubleshoot-locally.md
> +## Test DAGs Locally with Pytest
We are using title case for h2s, so it would still be capitalized

2022-03-03 10:33 UTC, jwitz commented on astro/ci-cd.md
> +2. Build your Astro project into a Docker image and push the image to your Deployment.
I updated these steps a bit given that installing the CLI is definitely a standalone, necessary step for any pipeline.

2022-03-03 10:34 UTC, jwitz commented on astro/ci-cd.md
> +$ astrocloud deploy <your-deployment-id>
Random aside, but why are we starting to say "Deployment on Astro"? I thought a while back we decided just to say Deployment, since you really can't deploy anywhere else. Lmk what you think about this, and I'll add it to the style guide

2022-03-03 10:36 UTC, jwitz commented on astro/ci-cd.md
> -    ```
I removed this because the original script was so complex that it was actually easier to run the script. But now that it's only four commands, I don't see the utility in abstracting that into a different shell script

2022-03-03 10:38 UTC, jwitz commented on astro/ci-cd.md
> +          astrocloud deploy <deployment-id>
We do make that explicit:

"Add the following to a new file in `.github/workflows`, making sure to replace `<organization-id>` and `<deployment-id>` with the values for your Deployment:"

2022-03-03 11:01 UTC, jwitz commented
@paolaperaza This is ready for review again. A few key takeaways/ comments:

1. I do think we need some sort of "Using API keys" section for Deployment API keys, if only to link out to the appropriate docs that provide more context for using them. I don't want anyone to feel lost in that doc, as we only really connect using these keys to other functionality in the Overview. That doesn't seem like a strong enough place alone to provide that context.
2. I updated the high level CI/CD steps to better reflect what's going on in the pipelines. I think you're right to add "install the CLI" as a specific step, since that's something specific to the pipeline workflow
3. We should no longer provide that shell script because the new "high level" workflow is easy to run on its own. It seems like more work to have people bundle those commands and execute them as a shell script than to just run them standalone and have control over the process.

2022-03-03 19:42 UTC, sunkickr requested changes

2022-03-03 20:13 UTC, paolaperaza reviewed
A few mo' comments

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +1. Access Deployment API key credentials. These credentials must be set as OS-level environment variables called `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET`. This can be done on your local machin
```suggestion
1. Access Deployment API key credentials, which should be stored as OS-level environment variables.
```

It looks like we specify in each of the templates that you have to set Deployment ID and Secret and what not -- maybe just remove the extra detail

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +3. Build your Astro project into a Docker image, authenticate to Astro using your Deployment API key, and push the image to your Deployment.
```suggestion
3. Run `astrocloud deploy`. This builds your Astro project into a Docker image, authenticates to Astro using your Deployment API key, and pushes the image to your Deployment.
```

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +          astrocloud deploy <deployment-id>
Ope, didn't see. Whoops.

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +          brew install astronomer/cloud/astrocloud@1.2.0
```suggestion
          brew install astronomer/cloud/astrocloud
```

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +    env:
@jwitz I don't see Organization ID referenced tho - don't we not need that anymore?

![image](https://user-images.githubusercontent.com/31111752/156644805-45e94f0c-eff5-410f-b87b-a8dbd528d081.png)

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
>      TAG=deploy-`date "+%Y-%m-%d-%HT%M-%S"`
```suggestion
```

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +    brew install astronomer/cloud/astrocloud@1.2.0
```suggestion
    brew install astronomer/cloud/astrocloud
```

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
> +    # Install the Astro CLI
```suggestion
    # Install the latest version of the Astro CLI
```

2022-03-03 20:13 UTC, paolaperaza commented on astro/ci-cd.md
>      TAG=deploy-`date "+%Y-%m-%d-%HT%M-%S"`
Do we need `ORGANIZATION_ID` here?

2022-03-03 21:11 UTC, sunkickr reviewed
should we note in the CI/CD doc that users can check pytests there too and that failed pytests can stop bad deploys

2022-03-03 21:11 UTC, sunkickr commented on astro/ci-cd.md
> +3. Build your Astro project into a Docker image, authenticate to Astro using your Deployment API key, and push the image to your Deployment.
I think this is good specifies that it all happens in the `astrocloud deploy`

2022-03-03 21:11 UTC, sunkickr commented on astro/ci-cd.md
> +    env:
we don't need organization id anymore the CLI can get it from deployment id

2022-03-03 21:11 UTC, sunkickr commented on astro/ci-cd.md
>      TAG=deploy-`date "+%Y-%m-%d-%HT%M-%S"`
nope

2022-03-03 21:19 UTC, sunkickr commented on astro/ci-cd.md
> +    brew install astronomer/cloud/astrocloud@1.2.0
I don't thin that you build.sh anymore

2022-03-04 11:07 UTC, jwitz commented on astro/airflow-api.md
> +If you need to call the Airflow API only once, you can retrieve a single 24-hour access token at `https://cloud.astronomer.io/token`.
It's accurate, but I also think it's explaining something self-evident. Because it's a token accessed via a web UI, there's no way to automate that in a pipeline. I'm in favor of giving readers some benefit of the doubt in terms of what they inherently understand about a given functionality.

2022-03-04 11:18 UTC, jwitz commented on astro/ci-cd.md
> +1. Access Deployment API key credentials. These credentials must be set as OS-level environment variables called `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET`. This can be done on your local machin
I think we need to state outside of the templates exactly what the env vars need to be named. Otherwise, it could be mistaken that those names are just part of a "template" setup when they are actually a technical requirement.

2022-03-04 11:23 UTC, jwitz commented on astro/ci-cd.md
> +    env:
@sunkickr Is there any danger of someone always using the "latest" CLI in their pipeline? I'm thinking in terms of breaking changes.

I can make this version number update dynamically whenever we release a new CLI, but we should explicitly decide whether users should always be pulling latest

2022-03-04 11:33 UTC, jwitz commented
@paolaperaza @sunkickr Back to youse! Two outstanding questions:

1. In our CI/CD pipelines, can we safely recommend that users always download the latest CLI release if it might contain breaking changes?
2. @sunkickr what do you mean that we don't need to run `build.sh` for the jenkins script anymore? Can we just run the shell commands in that `script` field without needing a `build` file?

2022-03-04 15:45 UTC, sunkickr commented
@jwitz 

1. I would think that the main functionality of `astrocloud deploy` shouldn't change but I know it's changing in 1.3.0 and may change again. But we should eventually get to a point where we only add features to `astrocloud deploy` in the form of flags but not change the main flow. Since things are still changing a lot we can pin the version. Can we get the version that we pin in the docs to change dynamically and always be the latest CLI version?
2. yes we can just run the command in the `script` field without needing a `build` file. The build file was only needed because the prior script contained the `\` character which was off the jenkins compiler

2022-03-04 16:53 UTC, sunkickr approved these changes
LGTM

2022-03-04 18:08 UTC, merged