Create sys admin via cli
astronomer/docs pull request #44
Opened 2020-09-25 13:13 UTC by shmanu017

Added steps to create SysAdmin via CLI

2020-09-25 14:08 UTC, paolaperaza requested changes
Thanks for doing this @shmanu017 ! Added a few comments - happy to take a look again later today or whenever you have time to reply back.

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +#### Create SysAdmin User via CLI
@shmanu017 Can you bump up this section to above "Verify SysAdmin Access"? I'd say these headers can go:

Assign Users System-Level Roles > Create SysAdmin User via Astro CLI > Verify SysAdmin Access

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +Get name of one of Houston pods(switch to base namespace: astronomer (default))
How would a user get a Houston pod? If it's switching to the namespace, add the command in here maybe?

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +- Get a Prisma security token via `kubectl -n astronomer exec astronomer-houston-****** -ti -- npm run token` (filling in that name in place of Houston in this case)
I'd here say:

> Now, get a Prisma security token by running:
> 
> ```
> $ kubectl -n astronomer exec astronomer-houston-****** -ti -- npm run token
> ```
> 
> Make sure to substitute your full Houston pod name above.

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +- Run `kubectl -n astronomer port-forward svc/astronomer-prisma 4466:4466`
> Then, run:
> 
> ```
> $ kubectl -n astronomer port-forward svc/astronomer-prisma 4466:4466
> ```

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +- Click on `HTTP Headers` in the bottom left and set `{"Authorization": "<token from 1st step>"}`
Is this the prisma security token? I'd specify! So,

```
{"Authorization": "<prisma-security-token>"}
```

(Or replace with another token)

2020-09-25 14:08 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
> +#### Create SysAdmin User via CLI
Alright, reading through this again - this isn't through the CLI, then right? This is more through Houston? Ignorant q, but when would users prefer to add a SysAdmin via this method?

I think if you included one more sentence with context of what this method is, that'd be helpful!

2020-09-25 14:09 UTC, paolaperaza commented
Ah, @shmanu017 I just saw the second file you added on the SSL Cert. Can you actually take that commit out of this PR and open up a new one for that doc, just so we can review/talk about it separately? Sorry I didn't notice earlier!

cc: @pritt20

2020-09-25 14:31 UTC, shmanu017 commented
@paolaperaza I have made all the necessary changes as requested, Please review the document.

2020-09-28 18:20 UTC, shmanu017 commented
https://www.notion.so/astronomerio/Create-SysAdmin-via-cli-b463bf83242a4735b8bfa29a7b32ccf1

Making an internal Q&A note

2020-09-28 18:20 UTC, closed without merging