Updated installation steps for Celery workers
astronomer/docs pull request #442
Opened 2021-08-30 18:26 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/441

I think it's okay to include this solution as-is for now, since we are already editing the override files of other Airflow components.

2021-08-30 18:27 UTC, jwitz commented on enterprise/v0.25/08_astronomer-certified/02_single-node-install.md
> +    sudo systemctl edit astronomer-certified@worker.service
@BasPH I assume this command will also not work due to the 2.0 changes. Is there an alternative way to access/edit the appropriate file?

2021-09-06 09:23 UTC, BasPH commented on enterprise/v0.25/08_astronomer-certified/02_single-node-install.md
> +    sudo systemctl edit astronomer-certified@worker.service
Correct. In the case of https://github.com/astronomer/docs/issues/441, workers run on separate machines, so editing the systemd file there doesn't clash with other Airflow processes.

For a single node install, I don't see any other way than to duplicate the systemd unit file and edit the ExecStart line specifically for `airflow celery` commands:

```
ExecStart=/home/astro/airflow-venv/bin/airflow celery %i
```

2021-09-14 20:02 UTC, jwitz commented
@BasPH I took a shot at implementing your feedback without an environment to test in. Let me know which specific commands to include if this still isn't correct.

2021-09-15 13:53 UTC, BasPH requested changes
@jwitz One small thing to change, otherwise looks good

2021-09-15 13:53 UTC, BasPH commented on enterprise/v0.25/08_astronomer-certified/02_single-node-install.md
> +    sudo -e /etc/systemd/system/astronomer-certified@worker.service
Since this is a new, 2nd, "astronomer-certified" systemd file, we must change the name to avoid clashing with the 1st systemd file.

```suggestion
    sudo -e /etc/systemd/system/astronomer-certified-worker.service
```

2021-09-15 13:53 UTC, BasPH commented on enterprise/v0.25/08_astronomer-certified/02_single-node-install.md
> +    WantedBy=multi-user.target
Would add newlines just like above for readability

```suggestion
    [Unit]
    Description=Airflow %I daemon
    After=network-online.target cloud-config.service
    Requires=network-online.target
    
    [Service]
    ExecStartPre=/home/astro/airflow-venv/bin/airflow db upgrade
    EnvironmentFile=${AIRFLOW_HOME}/sys-config
    User=astro
    Group=astro
    Type=simple
    WorkingDirectory=${AIRFLOW_HOME}
    ExecStart=/home/astro/airflow-venv/bin/airflow celery %i
    Restart=always
    RestartSec=5s
    
    [Install]
    WantedBy=multi-user.target
```

2021-09-15 13:53 UTC, BasPH commented on enterprise/v0.25/08_astronomer-certified/02_single-node-install.md
> +3. Enable the Worker service by running the following command:
Will also need to update line 305 to `sudo systemctl enable astronomer-certified-worker.service`

2021-09-15 14:10 UTC, jwitz commented
@BasPH I changed the commands in both lines 307 and 313, otherwise I did exactly as you suggested here

2021-09-15 14:10 UTC, BasPH approved these changes

2021-09-15 20:16 UTC, merged