Smtp configuration
astronomer/docs pull request #45
Opened 2020-09-25 14:53 UTC by pritt20

New SMTP configuration document

2020-11-05 23:24 UTC, paolaperaza commented
Self-note to make sure this doc covers issues customer had in this support ticket: https://astronomer.zendesk.com/agent/tickets/2897

2020-11-09 14:08 UTC, ianstanton requested changes
@pritt20 A lot of good examples here. Thank you for throwing this together. We'll be able to add more examples as we run into them! My only request is to mock up the mailgun example with dummy account info.

2020-11-09 14:08 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/09_smtp-configuration.md
> +        smtpUrl:smtps://postmaster%40mg.astronomer.io:daf255573ca4f22c699c6c0c4ab2dfb0@smtp.mailgun.org/?pool=true
I would mock this up as an example vs using our mailgun account info

2021-01-05 12:36 UTC, pritt20 commented on enterprise/v0.16/06_manage-astronomer/09_smtp-configuration.md
> +        smtpUrl:smtps://postmaster%40mg.astronomer.io:daf255573ca4f22c699c6c0c4ab2dfb0@smtp.mailgun.org/?pool=true
Thanks for pointing that out @ianstanton !! I've made the required changes under mailgun smtp example url

2021-01-05 21:01 UTC, ianstanton requested changes
Some indentation suggestions

2021-01-05 21:01 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/09_smtp-configuration.md
> +        smtpUrl: smtp://xyz%40example.com:password@smtp.office365.com:587/?requireTLS=true
```suggestion
email:
  reply: "xyz@example.com"
  enabled: true
  smtpUrl: smtp://xyz%40example.com:password@smtp.office365.com:587/?requireTLS=true
```

2021-01-05 21:01 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/09_smtp-configuration.md
> +	smtpUrl: smtp://smtp-relay.example.com:25/?ignoreTLS=true
```suggestion
email:
  enabled: true
  reply: "xyz@example.com"
  smtpUrl: smtp://smtp-relay.example.com:25/?ignoreTLS=true
```

2021-01-07 20:55 UTC, ianstanton approved these changes
@pritt20 content looks good to me. Assigning @jwitz as reviewer for formatting / editing purposes!

2021-02-09 17:07 UTC, ianstanton commented
@jwitz @paolaperaza Do you guys think this should be merged and posted to our website? I feel it is useful.

2021-02-09 23:02 UTC, jwitz commented
@ianstanton apologies for falling behind on this PR! definitely agree this is good info to have in docs, I just need some extra time to edit this and strategize over how to best include this info in our Enterprise setup. 

For instance: right now we have SMTP as a [prerequisite](https://www.astronomer.io/docs/enterprise/v0.23/install/aws/install-aws-standard#prerequisites), should this be its own step within the installation guide vs. an entirely separate guide? And how do we tell people to add these variable YAML objects to our example Helm chart? Gonna muse over this and post my plan here once it's finalized.

2021-02-11 22:27 UTC, jwitz commented
Hi @pritt20 , thank you for writing this. I'm going to close this PR, as I've edited your content and found a place for it in our Enterprise installation guides over at PR https://github.com/astronomer/docs/pull/247. I'd appreciate your review over there!

2021-02-11 22:27 UTC, closed without merging