Astro CLI 1.3.0 core doc changes
astronomer/docs pull request #455
Opened 2022-03-03 17:01 UTC by jwitz

Changes to the CLI Reference guide and core Astro docs related to the release of CLI 1.3.0. Once CLI release notes are merged, I'll update this PR to link out to new reference docs within release notes.

2022-03-03 19:26 UTC, paolaperaza reviewed
A few comments here @jwitz - take a look and I'll do another final pass

2022-03-03 19:26 UTC, paolaperaza commented on astro/cli-reference/astrocloud-dev-parse.md
> +Additionally, this command runs prebuilt unit tests on your Astro project using Pytest. These unit tests are the same ones that are included by default with your project as described in [Run Tests wi
```suggestion
Run basic tests against your Astro project in a local Airflow environment. Specifically, this command runs two tests:

 - A test that parses all references to environment variables, Airflow Connections, and Airflow Variables in your DAGs to verify that each of those objects has a value. This ensures that your DAGs don't call an object that does not exist.
 - The DAG integrity test that's included in your Astro project by default and is run on `astrocloud dev pytest`. 
 
For more information on testing DAGs locally, read [Run Tests with the Astro CLI](test-and-troubleshoot-locally.md#run-tests-with-the-astro-cli).
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/cli-reference/astrocloud-dev-parse.md
> +| `-e`, `--env`       | The filepath to your environment variables. The default is `.env`)                            | Any valid filepath within your Astro project    |
```suggestion
| `-e`, `--env`       | The filepath to your environment variables. The default is `.env`.                            | Any valid filepath within your Astro project    |
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/deploy-code.md
> +This command returns a list of Airflow Deployments available in your Workspace and prompts you to pick one.
```suggestion
This command returns a list of Deployments available in your Workspace and prompts you to pick one.
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/deploy-code.md
> +If your code passes the unit tests, the CLI builds your Astro project directory into a new Docker image pushes this image to Astro.
```suggestion
After selecting a Deployment, the CLI runs several unit tests to ensure that your DAGs don't contain basic syntax and import errors. If any of these tests fail, the deploy will also fail. If your code passes the unit tests, the CLI builds your Astro project directory into a new Docker image pushes this image to Astro.
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#), a testing framework for Python. These tests can be run locally
```suggestion
`astrocloud dev pytest` runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#), a testing framework for Python. These tests are run locally against all DAGs in your Astro project and are optimized to catch code-level errors that may not be easily detectable otherwise.
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +By default, the `tests` includes a default DAG integrity test called `test_dag_integrity.py`. This test checks that:
```suggestion
By default, the `tests` directory in your Astro project includes a default DAG integrity test called `test_dag_integrity.py`. This test checks that:
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#), a testing framework for Python. These tests can be run locally
@jwitz I feel like we should explicitly call out `astrocloud dev pytest` as a command/instruction? I kinda liked how it was explicitly introduced before (in the section below)

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs this default test alongside any other custom tests that you add to the `tests` directory. For more information about this command, see the [CLI Command Reference](cli-ref
> To run this default test against your DAGs, run the following Astro CLI command:
> 
> ```sh
> astro dev pytest
> ```
> 
> This command will also run any other custom tests in the `tests` directory of your project. For more information about this command, see the [CLI Command Reference](cli-reference/astrocloud-dev-pytest.md).

I feel like I still like something like ^this more

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +The first of these tests ensures that your DAG code doesn't call any missing values. Specifically, it calls all of your DAGs' OS-level variables, Airflow Connections, and Airflow Variables to check w
```suggestion
The `astrocloud dev parse` Astro CLI command runs a predefined set of tests which ensure that essential aspects of your code are correctly formatted.

Specifically, this command runs two tests:

-  A test that parses all environment variables, Airflow Connections, and Airflow Variables in your DAGs to verify that each of those objects has a value. This ensures that your DAGs don't call any values that don't exist.
 - The DAG integrity unit test that is included in your Astro project by default and runs with `astrocloud dev pytest`.
```

2022-03-03 19:26 UTC, paolaperaza commented on astro/cli-reference/astrocloud-dev-parse.md
> +Additionally, this command runs prebuilt unit tests on your Astro project using Pytest. These unit tests are the same ones that are included by default with your project as described in [Run Tests wi
@jwitz TBH I almost feel like you could remove this detail and just link out to the CLI doc at the end (the H2 header that covers both pytest and parse)

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +Generally speaking, `astrocloud dev parse` is a more convenient but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we r
This is great guidance -- appreciate seeing this

2022-03-03 19:26 UTC, paolaperaza commented on astro/test-and-troubleshoot-locally.md
> +Generally speaking, `astrocloud dev parse` is a more convenient but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we r
Should we switch up the sections here? Introduce parse as the basic general command and then pytest as a more customizable option

2022-03-03 22:01 UTC, paolaperaza commented on astro/deploy-code.md
> +If your code passes the unit tests, the CLI builds your Astro project directory into a new Docker image pushes this image to Astro.
@sunkickr What's the error users will see when this stuff fails?

2022-03-03 22:23 UTC, sunkickr requested changes
Overall some feedback on how we are positioning the parse command

2022-03-03 22:23 UTC, sunkickr commented on astro/cli-reference/astrocloud-deploy.md
>  For teams operating at scale, this command can be automated via a [CI/CD pipeline](ci-cd.md) by using [Deployment API keys](api-keys.md) in the request. When `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_S
We also need to add that this command will parse all your DAGs and check them for import and syntax errors. That users will need to use -f to deploy dags that have errors

2022-03-03 22:23 UTC, sunkickr commented on astro/cli-reference/astrocloud-deployment-update.md
> +astrocloud deployment <deployment-id> <flags>
```suggestion
astrocloud deployment update <deployment-id> <flags>
```

2022-03-03 22:23 UTC, sunkickr commented on astro/cli-reference/astrocloud-dev-parse.md
> +Additionally, this command runs prebuilt unit tests on your Astro project using Pytest. These unit tests are the same ones that are included by default with your project as described in [Run Tests wi
Honestly I think we should just say that this command just lets you know if your DAGs have errors or not.(syntax import, processable DAG code etc...). We can say that it is running a test located `.astrocloud/test_dag_integrity_default.py` but don't need to say exactly how it works. Also it explicitly does not give errors for missing variables and connections. Many users said that this one thing they may not have locally but they don't want it stop their deploys

2022-03-03 22:23 UTC, sunkickr commented on astro/deploy-code.md
> +If your code passes the unit tests, the CLI builds your Astro project directory into a new Docker image pushes this image to Astro.
I wouldn't say it runs unit tests, Id say it parses your DAGs. the main point of the tests are to keep bad code that could take a DAG down if pushed. I wouldn't want a user to think that we are enforcing any kind of code structure with a unit tests

2022-03-03 22:23 UTC, sunkickr commented on astro/deploy-code.md
> +To force a deploy even if your project fails unit tests, you can run `astrocloud deploy --force`.
```suggestion
To force a deploy even if your project had DAG errors, you can run `astrocloud deploy --force`.
```

2022-03-03 22:23 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#), a testing framework for Python. These tests can be run locally
Pytest should be thought of as for testing and prase should be thought of has quick check of the DAGs to see if they render. pytest you can write custom tests parse you cannot. I agree that we should a section about about using parse. maybe say something like run `astrocloud dev parse` to quickly see if you DAGs are error free and if they would render in the webserver and run

2022-03-03 22:23 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs this default test alongside any other custom tests that you add to the `tests` directory. For more information about this command, see the [CLI Command Reference](cli-ref
you can also run a specific tests `astrocloud dev pytest <specify test file>`

2022-03-03 22:23 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +The first of these tests ensures that your DAG code doesn't call any missing values. Specifically, it calls all of your DAGs' OS-level variables, Airflow Connections, and Airflow Variables to check w
Again with the first point the opposite is true. second point again we should just emphsis that the command checks for airflow and python errors. It makes sure that DAGs render

2022-03-03 22:23 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +Generally speaking, `astrocloud dev parse` is a more convenient but less customizable version of `astro dev pytest`. If don't have any specific test files that you want to run on your DAGs, then we r
yeah I think so. I see parse being more widely used. Users of parse shouldn't have to know what pytest is to use it

2022-03-04 12:31 UTC, jwitz commented on astro/test-and-troubleshoot-locally.md
> +`astrocloud dev pytest` runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#), a testing framework for Python. These tests can be run locally
@paolaperaza Not sure what you mean here, do you mean that the command should be on its own line?

2022-03-04 12:44 UTC, jwitz commented
@paolaperaza @sunkickr Made some changes here, high level changes include trying to avoid "unit test" / "series of tests" when talking about `astrocloud dev parse`

2022-03-04 15:20 UTC, sunkickr requested changes
Got ride of describing parse as running multiple tests. Update description of pytest

2022-03-04 15:20 UTC, sunkickr commented on astro/cli-reference/astrocloud-deploy.md
> +This command bundles all files in your Astro project and pushes them to Astro. Before completing the process, it runs several tests against all DAGs in your Astro project. If any of the tests fail, t
```suggestion
This command bundles all files in your Astro project and pushes them to Astro. Before completing the process, it tests your DAGs in your Astro project for errors. If this test fails, the deploy to Astro will also fail. This is the same test which runs locally with `astrocloud dev parse`.
```

2022-03-04 15:20 UTC, sunkickr commented on astro/cli-reference/astrocloud-dev-parse.md
> +Parse the DAGs in a locally hosted Astro project. For more information about testing DAGs locally, read [Run Tests with the Astro CLI](test-and-troubleshoot-locally.md#run-tests-with-the-astro-cli).
```suggestion
Parse the DAGs in a locally hosted Astro project to quickly check them for errors. For more information about testing DAGs locally, read [Run Tests with the Astro CLI](test-and-troubleshoot-locally.md#run-tests-with-the-astro-cli).
```

2022-03-04 15:20 UTC, sunkickr commented on astro/deploy-code.md
> +After you select a Deployment, the CLI parses your DAGs to ensure that they don't contain basic syntax and import errors. These tests are equivalent to those that run on `astro dev parse` in a local
```suggestion
After you select a Deployment, the CLI parses your DAGs to ensure that they don't contain basic syntax and import errors. This test is equivalent to the one that runs during `astrocloud dev parse` in a local Airflow environment. If any of your DAGs fail this parse, the deploy to Astro will also fail.
```

2022-03-04 15:20 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +This command runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#). These tests are run locally against all DAGs in your Astro project and are
```suggestion
This command runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#). With pytest users can test custom python code and operators locally without having to start an airflow project and run DAGs or tasks.
```

2022-03-04 15:20 UTC, sunkickr commented on astro/test-and-troubleshoot-locally.md
> +This command runs all tests in your project's `tests` directory with [pytest](https://docs.pytest.org/en/7.0.x/index.html#). These tests are run locally against all DAGs in your Astro project and are
Users can write pytests that can test any python code they would like not just DAGs

2022-03-04 16:49 UTC, sunkickr approved these changes
LGTM

2022-03-04 18:09 UTC, merged