Astro library documentation
astronomer/docs pull request #477
Opened 2022-03-09 11:35 UTC by jwitz

As a minimum viable docset, I’m planning to host two docs on Astro:

- **Install Astro SDK**: A doc explaining how to set up your project to run Astro, basically the first two pages of this doc: https://docs.google.com/document/d/1bZuwyG6oG95d_obdPd70whCFZzXLZH15EB57tHqcHRo/edit#. This will be slightly repetitive to the README
- **Python SDK**: A doc explaining how to use the key components of the Python SDK, much of this content will be taken from the old README. SQL SDK doc will follow

These docs will live under the Develop tab on [docs.astronomer.io](http://docs.astronomer.io/)

This is still WIP pending on some product naming decisions. Please ignore specific names of items for now - let's focus on nailing the technical reference and making the code examples as useful as we can

2022-03-09 11:37 UTC, jwitz commented on astro/python-sdk.md
> +Before you can complete any data transformations, you need to define input and output tables for Airflow. You can do this in either of the following ways:
Are "input tables" and "output tables" the highest level concept here, or is it "database context"? I have trouble deciding which of these terms to use throughout the documentation.

2022-03-09 11:39 UTC, jwitz commented on astro/python-sdk.md
> +To interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable.
```suggestion
To interact with any external storage services, you need to first configure them as Airflow connections. For example, to interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable of your project.
```

2022-03-09 11:39 UTC, jwitz commented on astro/python-sdk.md
> +After loading tables into your DAG, you can transform them. The `aql.transform` function serves as the "T" of the ETL system. Each step of the transform pipeline creates a new table from the `SELECT`
```suggestion
After extracting tables into your DAG, you can transform them. The `aql.transform` function serves as the "T" of the ETL system. Each step of the transform pipeline creates a new table from the `SELECT` statement. Tasks can pass these tables as if they were native Python objects.
```

2022-03-09 11:41 UTC, jwitz commented on astro/python-sdk.md
> +from astro import sql as aql
Could either @dimberman or @tatiana please rewrite this example to use the `paglia` dataset? :)

2022-03-09 12:41 UTC, tatiana commented on astro/install-astro-sdk.md
> +    - Run `pip install astro-projects`.
@jwitz you already mentioned in the PR description, but just a reminder this will also probably change.

2022-03-09 13:07 UTC, tatiana commented on astro/python-sdk.md
> +- Define input and output tables as arguments when you call an `aql.transform` function.
The `output` table parameter is optional. If not passed, we create a temporary table, automatically naming it.

2022-03-09 13:07 UTC, tatiana commented on astro/python-sdk.md
> +## Creating Input and Output Tables
Perhaps this first section could be "Starting point", and explain the possible source data for an Astro Python SDK workflow:
* an existing table in a database
* a file

This would connect neatly with the following section, which explains the `Table` abstraction

2022-03-09 17:09 UTC, kentdanas commented on astro/install-astro-sdk.md
> +sidebar_label: 'Astro SDK'
I find the "Astro SDK" sidebar label for this one a bit confusing, since the whole section is "Astro SDK" and this doc is about installation specifically. Maybe it could be "Astro SDK Installation" or something like that?

2022-03-09 17:14 UTC, kentdanas commented on astro/install-astro-sdk.md
> +2. Set the following environment variable either in the `.env` of your Astro project or in a Deployment on Astro:
Unsolicited feedback, so feel free to ignore me....but I think it could be helpful in the install section to mention the possibility of setting a schema, since this would be done using an env var (assuming that process hasn't changed).  We mention briefly in the Python SDK doc that a `temp` schema is used and can be bulk deleted, but don't mention the possibility of specifying a different one. In my mind this would be relevant for anybody doing setup for the project. 

But, a call for @tatiana to make, since I may not be up to date with the process for that :)

2022-03-10 13:41 UTC, tatiana commented on astro/python-sdk.md
> +If you want to ensure that the output of your task is a table that can be deleted at any time for garbage collection, you can declare it as a nameless `TempTable`. This places the output into your `t
It may be worth to give some context in this section:
- many Astro operations (eg. load, transform, append, merge) would output the results into a table
- if the user does not explicitly declare the output_table argument, Astro will imply that is a temporary table
- the two differences of temporary tables are: they are named automatically by astro and they are created using a temporary schema, currently declared using the envvar: XXX

The idea behind having a temporary schema is that it would make it easy for the user to remove those tables, when they are no longer needed.  At the moment (0.6.0), Astro has not implemented any strategy to automatically clean these databases.
I added two tickets for us to cover this:
* https://github.com/astro-projects/astro/issues/186
* https://github.com/astro-projects/astro/issues/187

2022-03-10 13:41 UTC, tatiana commented on astro/python-sdk.md
> +The following example DAG sets `output_table` to a nameless `TempTable`, meaning that any output from this DAG will be deleted once the DAG completes. If you wanted to keep your output, you would sim
At the moment, this does not happen.  Astro 0.6.0 does not delete the temporary tables.

2022-03-10 13:42 UTC, tatiana commented on astro/python-sdk.md
> +You can load CSV or parquet data from either local, S3, or GCS storage into a SQL database with the `load_file` function. The result of this function can be used as an input table in your DAG.
Not only CSV and parquet - there are more files supported, it may be worth referring to Astro README (github.com/astro-projects/astro/) or the full support. HTTP endpoints are also supported.

As of Astro 0.7.0, the load operation also supports loading into an in-memory Pandas dataframe - as opposed to a SQL table

2022-03-10 13:42 UTC, tatiana commented on astro/python-sdk.md
> +To interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable.
If the user does not give conn_id, the load file is able to load objects from GCS & S3 by using standard GCP, AWS cloud credentials. We don't force users to have an Airflow Connection.

2022-03-10 13:56 UTC, tatiana commented on astro/python-sdk.md
> +from astro import sql as aql
@jwitz I just added a ticket to make sure we don't forget about this:
https://github.com/astro-projects/astro/issues/188

2022-03-10 13:58 UTC, tatiana commented on astro/python-sdk.md
> +To create a dataframe, you can pass a SQL table into the `adf` function. This function converts SQL tables into dataframes without any additional configuration, meaning that you can automatically fin
I believe we should just use `aql.dataframe` to refer to this decorator.
To rename the decorator seems confusing and unnecessary.

2022-03-10 14:04 UTC, tatiana commented on astro/install-astro-sdk.md
> +2. Set the following environment variable either in the `.env` of your Astro project or in a Deployment on Astro:
That's great feedback, @kentdanas !
At the moment Astro users can set optional an environment variable, which is used as the default schema to create temporary tables: `AIRFLOW__ASTRO__SQL_SCHEMA`

2022-03-10 14:07 UTC, tatiana reviewed
Thank you very much for the great work, @jwitz !

Since the project is maturing, a few parts of the original documentation were outdated. I'll try to give feedback as details change.

It is not fully clear to me which documentation will live in the Astronomer official docs and which documentation will stay within Astro's repo, using Sphinx. I'll loop in @kaxil, so he helps us to be consistent in this regard between the `astronomer-providers` and `Astro` project.

2022-03-10 14:47 UTC, jwitz reviewed
Just added another round of changes based on the most recent review. Some outstanding questions are:

- What is the name of the library? (TBD)
- Should we mention TempTables if they are still a bit experimental? If so, how do those users clean them up?

2022-03-10 14:47 UTC, jwitz commented on astro/python-sdk.md
> +2. In your Astro project, create an Airflow connection to the dataset using the following command:
This is a tricky one.. For future tutorials, and as we open source the Astro CLI, I'd prefer to frame our docs around the assumption that someone is working in a project that was initialized by `astro dev init`. WDYT @paolaperaza ?

2022-03-10 14:47 UTC, jwitz commented on astro/python-sdk.md
> +## Creating Input and Output Tables
That's mostly what I was trying to do here - this `##` header summarizes the next four `###` sections. What if I broke this into two separate `##` sections.  

Do you think it would be better to introduce the `Table` object separately and then follow up with a section on how to use `Tables` as inputs/ outputs?

2022-03-10 14:47 UTC, jwitz commented on astro/python-sdk.md
> +To interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable.
What would the `aql.load_file` function params would look like if you didn't specify a `conn_id`?

2022-03-10 14:47 UTC, jwitz commented on astro/python-sdk.md
> +Before you can complete any data transformations, you need to define input and output tables for Airflow. You can do this in either of the following ways:
Interesting, it seems like the better structure for this doc is to describe the Classes (Table, TempTable, etc) and then describe what you can do with them (load files, convert to dataframe, etc). There's too many ways to bypass having both an input table and an output table for that structure to be the defining concept of this SDK.

2022-03-10 14:47 UTC, jwitz commented on astro/python-sdk.md
> +If you want to ensure that the output of your task is a table that can be deleted at any time for garbage collection, you can declare it as a nameless `TempTable`. This places the output into your `t
Can we provide any advice on how to clean up the TempTables?

2022-03-13 01:22 UTC, dimberman requested changes
Thank you for your work on this @jwitz!

Added som initial comments but we're getting close!

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +In the following example, your SQL table is defined in the DAG instantiation. In each subsequent task, you only pass in an input table argument because `astro` automatically passes in the additional
I want to be careful here that people don't think that the table HAS to be called input_table. It can be anything you want.

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +If you want to ensure that the output of your task is a table that can be deleted at any time for garbage collection, you can declare it as a nameless `TempTable`. This places the output into your `t
@jwitz the advice would be that you can delete and recreate the schema

```
DROP SCHEMA tmp_astro CASCADE; CREATE SCHEMA tmp_astro;

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +        # TempTable will not persist after DAG finishes
```suggestion
        # TempTable will not persist after DBA cleans temp schema
```

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +To interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable.
@jwitz if you don't specify a conn_id, then we assume that you are pulling from the local filesystem. To pull from s3 you'll need to supply a `file_conn_id`

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +- Wrapping a value in single brackets (like `{customer_table}`) indicates the value will be rendered as a SQL table.
@jwitz we no longer do this, now everything is wrapped in double brackets.

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +If you need to perform a SQL operation that doesn't return a table but might require a table as an argument, you can use `@aql.run_raw_sql`.
You could mention a few examples:

1. Creating a table
2. Dropping a table
3. Altering a table
4. Adding an index (e.g. if you want to merge other tables into it)

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +@aql.run_raw_sql
One other thing to mention about `run_raw_sql` is that we allow people to put in custom `handler` function so you can return whatever you want given the cursor for that query.

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +@aql.dataframe
```suggestion
@dataframe
```

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +To create a dataframe, you can pass a SQL table into the `aql.dataframe` function. This function converts SQL tables into dataframes without any additional configuration, meaning that you can automat
```suggestion
To create a dataframe, you can pass a SQL table into the `astro.dataframe` function. This function converts SQL tables into dataframes without any additional configuration, meaning that you can automatically finish your data processing in a Pythonic context.
```

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +
@jwitz one other big feature is that you can add an output_table to the dataframe function and it will pass your resulting dataframe back into SQL!
e.g.
```
my_dataframe_func(df=actor, output_table=TempTable(conn_id="my_snowflake_conn))
```

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +        },
@tatiana I'm not sure we've fully worked out how the parameters work, right?

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +### Rendering a Set of Models
@tatiana have we agreed on calling these models?

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +SELECT * FROM my_astro_table;
```suggestion
SELECT * FROM {{test_astro}};
```

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +To define a downstream query, specify the upstream table in the downstream query's frontmatter as an object in the `template_vars` frontmatter. For example, the following frontmatter would define the
@jwitz we no longer need `template_vars`. Simply creating a jinja `{{table name}}` is sufficient to create dependency

2022-03-13 01:22 UTC, dimberman commented on astro/python-sdk.md
> +Because all database contexts and dependencies are defined in your `.sql` files, you only need to run `aql.render` once to execute your queries as successive Airflow tasks.
```suggestion
Because all database contexts and dependencies are defined in your `.sql` files, you only need to run `aql.render` once to execute your queries as successive Airflow tasks.
```
```suggestion
Because all database contexts and dependencies are defined in your `.sql` files, you only need to run `aql.render` once to execute your queries as Airflow tasks with set dependencies.
```

2022-03-14 22:19 UTC, jwitz commented on astro/python-sdk.md
> +To interact with S3, you must first set an S3 Airflow connection in the `AIRFLOW__ASTRO__CONN_AWS_DEFAULT` environment variable.
Ah now I'm kinda confused, to confirm: Is there no way to load from a hosted data source without first creating an Airflow connection?

2022-03-14 22:23 UTC, jwitz commented on astro/python-sdk.md
> +@aql.run_raw_sql
Can you share an example of this?

2022-05-03 04:22 UTC, paolaperaza commented
@jwitz Since it looks like the Astro library is still undergoing quite a few changes, going to go ahead and close this PR for now just so it doesn't crowd our list of otherwise actionable PRs. Thankfully, the branch is still there and the history of this PR is preserved.

Once we're ready, we can revisit!

2022-05-03 04:22 UTC, closed without merging