Add private repository steps to Astro
astronomer/docs pull request #494
Opened 2022-03-14 15:54 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/459

Going to comment throughout, but one open question I had was whether we can generalize this setup for more than just GitHub repos. What has to change in the Dockerfile so that these steps can be used with any private repo?

2022-03-14 16:33 UTC, jwitz commented on astro/develop-project.md
> +At a high level, this setup creates a custom Dockerfile that builds your project with the appropriate credentials to access your private GitHub repository. Any private Python packages specified in yo
```suggestion
At a high level, this setup creates a custom Dockerfile that builds your Astro project with the appropriate credentials to access your private GitHub repository. Any private Python packages specified in your `requirements.txt` file can then be pulled from your repository and installed when you build your project into a Docker image.
```

2022-03-14 16:33 UTC, jwitz commented on astro/develop-project.md
> +### Step 2. Build a New Image
```suggestion
### Step 2. Build a New Docker Image
```

2022-03-14 16:35 UTC, jwitz commented on astro/develop-project.md
> +To build your project into a Docker image:
```suggestion
To build a new Docker image from your `dockerfile.build` file:
```

2022-03-14 16:36 UTC, jwitz commented on astro/develop-project.md
> +2. Replace the contents of your `Dockerfile` with the following:
```suggestion
2. Replace the contents of your Astro project's `Dockerfile` with the following:
```

2022-03-14 16:48 UTC, jwitz commented on astro/develop-project.md
> +## Build a Project with Python Packages from a Private GitHub Repository
```suggestion
## Install Python Packages from a Private GitHub Repository
```

2022-03-14 16:49 UTC, jwitz commented on astro/develop-project.md
> +- A private GitHub repository that contains
```suggestion
- A private GitHub repository that contains your private Python packages.
```

2022-03-15 15:38 UTC, aspain commented
One more question @jwitz  - If a customer needed to bring in DAGs from a separate repo, would this same process still apply?

2022-03-15 16:34 UTC, paolaperaza reviewed
Thanks @jwitz - this looks great to me. Two things to look into -

- Let's add `-base` image to the instructions and acknowledge it's not typically the default
- Maybe a step 3 that clarifies how people can actually install these?

Looks great though - we're close

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +- The [Astronomer CLI](install-cli.md).
```suggestion
- The [Astro CLI](install-cli.md).
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +- A private GitHub repository that contains your private Python packages.
```suggestion
- A private GitHub repository that contains your Python packages.
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +2. In `Dockerfile.build`, add `AS stage` to the `FROM` line which specifies your Runtime image. For example, if you use Runtime 4.0.10, your `FROM` line would be:
```suggestion
2. In `Dockerfile.build`, add `AS stage` to the `FROM` line which specifies your Astro Runtime image. For example, if you use Runtime 4.2.0, your `FROM` line would be:
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +2. In `Dockerfile.build`, add `AS stage` to the `FROM` line which specifies your Runtime image. For example, if you use Runtime 4.0.10, your `FROM` line would be:
Might as well use latest version? Worth doing the runtime version env vars here or nah?

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +   quay.io/astronomer/astro-runtime:4.0.10 AS stage
```suggestion
   quay.io/astronomer/astro-runtime:4.2.0 AS stage
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +  If you use a `-base` version of Runtime, you need to replace this image with a non-`base` version before building your project from a private registry.
```suggestion
  If you use a `-base` version of Astro Runtime, you need to replace this image with a non-`base` version before building your project from a private registry.
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +  If you use a `-base` version of Runtime, you need to replace this image with a non-`base` version before building your project from a private registry.
I actually think it's the other way around as what it was with `-onbuild`. Typically, customers DON'T use `-base` images, but I think they SHOULD in this scenario because they're basically customizing what happens with non-base = the former `onbuild`. Need to confirm if ^this is the place for it

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +  :::
Maybe a tip here?

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file, making sure to replace `<authorized-key>` with your SSH key file name:
Should it not be `<ssh-key>`? What does GitHub officially call it

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-quay.io/astronomer/ap-airflow:2.1.4 .
```suggestion
    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-quay.io/astronomer/astro-runtime-4.2.0 .
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +   ```
```suggestion
   For example, if your base Runtime image was `quay.io/astronomer/astro-runtime:4.2.0`, this line would be:

   ```
   FROM custom-astro-runtime:4.2.0
   ```
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +Your Astro project can now utilize Python packages from your private GitHub repository. To build and run your updated project, you can either [run your project locally](develop-project.md#build-and-r
```suggestion
Your Astro project can now utilize Python packages from your private GitHub repository. To test your DAGs, you can either [run your project locally](develop-project.md#build-and-run-a-project-locally) or [deploy to Astro](deploy-cli.md).
```

2022-03-15 16:34 UTC, paolaperaza commented on astro/develop-project.md
> +### Step 2. Build a Custom Docker Image
Stupid Q - Is it worth creating a step 3 that says "ok now add your python package to your project"? Is that just adding the names of them into your `requirements.txt` and then it just works because of the image you're building?

Might be worth clarifying at the end

2022-03-15 20:35 UTC, jwitz commented on astro/develop-project.md
> +2. In `Dockerfile.build`, add `AS stage` to the `FROM` line which specifies your Runtime image. For example, if you use Runtime 4.0.10, your `FROM` line would be:
I'm not fussed about using env vars in "For example" instances because it's just as likely that a user is configuring this for an earlier Runtime version. Also I have yet to figure out how to use env vars in plain text - they only seem to work within a preformatted code block

2022-03-15 21:42 UTC, jwitz commented on astro/develop-project.md
> +### Step 2. Build a Custom Docker Image
Don't think this is stupid at all- actually, digging back through the original issue, it looks like we never had full confirmation about what should actually be in this Docker file.

2022-03-15 21:50 UTC, jwitz commented
@paolaperaza I think this is good wording wise, but your question about `Dockerfile.build` led me down a rabbit hole through the past PRs for this change. As it turns out, we never fully confirmed the appropriate commands to put in this file, and in this case the original Software documentation might still have details that we need to add

From what I remember, @danielhoherd and I had a discussion about the best practices for mounting an SSH key during build. The new `RUN --mount=type=...` command and Buildkit step was derived from https://github.com/astronomer/houston-api/blob/865576e87bb0e10bad9a97993ea4888a5f0e6d03/Dockerfile#L36, but I don't think I ever fully formatted it to fit with a general Astro build.

I've tried synthesizing the original configuration with this new recommendation, so we definitely need some technical review/ confirmation before merging. @cmarteepants would you be able to verify our `Dockerfile.build` in light of your experience mentioned [here](https://astronomer.slack.com/archives/C01N2DM2ZS8/p1641337386129800)?

2022-03-15 22:12 UTC, paolaperaza commented on astro/develop-project.md
> +2. In `Dockerfile.build`, add `AS stage` to the `FROM` line which specifies your Runtime image. For example, if you use Runtime 4.0.10, your `FROM` line would be:
Ok word that's cool

2022-04-05 17:21 UTC, cmarteepants approved these changes
LGTM 👍

2022-04-12 21:42 UTC, stuart23 commented on astro/develop-project.md
> +3. In `Dockerfile.build` after the `FROM` line specifying your Runtime image, add the following configuration. Make sure to replace `<url-to-packages>` with the URL leading to the directory with your
I am unsure what <url-to-packages> means? This is not mentioned outside of here. I think we need to include an example requirements.txt file with a `git+git@github.com:<organization>/<repository>.git` line

2022-04-12 22:12 UTC, jwitz commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-4.2.0 .
```suggestion
    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<ssh-key>" -t custom-astro-runtime-4.2.0 .
```

2022-04-13 18:40 UTC, stuart23 requested changes

2022-04-13 18:40 UTC, stuart23 commented on astro/develop-project.md
> +   quay.io/astronomer/astro-runtime:4.2.10 AS stage1
Consider adding `FROM` back to the start of this line

2022-04-13 18:40 UTC, stuart23 commented on astro/develop-project.md
> +3. In `Dockerfile.build` after the `FROM` line specifying your Runtime image, add the following configuration. Make sure to replace `<url-to-packages>` with the URL leading to the directory with your
I am unsure what `<url-to-packages>` means? This is not mentioned outside of here. I think we need to include an example requirements.txt file with a `git+git@github.com:<organization>/<repository>.git` line

2022-04-13 18:40 UTC, stuart23 commented on software/customize-image.md
> +   quay.io/astronomer/ap-airflow:2.2.5-onbuild AS stage1
Consider adding `FROM` back to the start of this line

2022-04-13 18:41 UTC, stuart23 commented on astro/develop-project.md
> +3. In `Dockerfile.build` after the `FROM` line specifying your Runtime image, add the following configuration. Make sure to replace `<url-to-packages>` with the URL leading to the directory with your
requirements.txt is now added above. **"Make sure to replace `<url-to-packages>` with the URL leading to the directory with your Python packages"** is now obsolete

2022-04-14 15:45 UTC, paolaperaza reviewed
Hm, I think we've got a few final details to sort out here @jwitz. Can you take a look at our comments here? I especially think we need to confirm/make sure that the right image here for Astro is `-base` of Runtime.

I didn't review Software but will do after you make changes. Note: AC doesn't have a `-base`, it just removes the `-onbuild`, so those steps will have to be different.

I'll take another look from there, and hopefully @stuart23 you can too 🙏

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +- An [SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private GitHub repo(s).
```suggestion
- A [GitHub SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private repo(s).
```

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +For example, to install the `mypackage1` & `mypackage2` from `myorganization`, as well as `numpy v 1.22.1`, you would add the following to `requirements.txt`:
```suggestion
For example, to install `<your-package-1>` and `<your-package-2>` from `<your-github-organization>`, as well as `numpy v 1.22.1`, you would add the following to `requirements.txt`:
```

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +git+ssh://git@github.com/myorganization/mypackage2.git
```suggestion
git+ssh://git@github.com/<your-github-organization>/<your-package-1>.git
git+ssh://git@github.com/<your-github-organization>/<your-package-2>.git
```

@jwitz I feel like we're breaking placeholder values here? We should either:

- Direct users to follow these instructions and replace these placeholders with their own values
- Or create an example that is not meant to be copy-pasted but that more clearly defines the example values. For example, `myorganization` might be Astronomer

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +  If you don't want keys in this file to be pushed back up to your GitHub repo, consider adding this file to `.gitignore`.
```suggestion
  If you don't want keys in this file to be pushed back up to your GitHub repository, consider adding this file to `.gitignore`.
```

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-4.2.0 .
Let's also replace `4.2.0` here with `4.2.10` as specified above? Doesn't it also have to be `astro-runtime-4.2.10-base`?

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file, making sure to replace `<ssh-key>` with your SSH key file name:
```suggestion
1. Run the following command to create a new Docker image from your `Dockerfile.build` file, making sure to replace `<ssh-key>` with your SSH key file name and `<astro-runtime-image>` with your versioned Astro Runtime image from Step 2:
```

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +    For example, if you have `quay.io/astronomer/astro-runtime:4.2.0` in your `Dockerfile.build`, this command would be:
```suggestion
    For example, if you have `quay.io/astronomer/astro-runtime:4.2.10-base` in your `Dockerfile.build`, this command would be:
```

2022-04-14 15:45 UTC, paolaperaza commented on astro/develop-project.md
> +   FROM custom-<airflow-image>
```suggestion
   FROM custom-<astro-runtime-image>
```

2022-04-14 17:46 UTC, jwitz commented on astro/develop-project.md
> +This topic provides instructions for building your Astro project using Python packages from a private GitHub repository. At a high level, this setup creates a custom Docker image that mounts an SSH k
Updated the wording slightly here

2022-04-14 17:47 UTC, jwitz commented on astro/develop-project.md
> +For example, to install the `mypackage1` & `mypackage2` from `myorganization`, as well as `numpy v 1.22.1`, you would add the following to `requirements.txt`:
What do you mean? `<your-package-1>` would be both the name of the package and the repo, since they're 1:1. The full URL is just the path to the repo.

2022-04-14 17:49 UTC, jwitz commented on astro/develop-project.md
> +git+ssh://git@github.com/myorganization/mypackage2.git
Not sure we're braking placeholder conventions because we use the placeholders above, and this is an example of that format. These values will always be custom so I don't think it's necessary to get any more specific with an example use case.

2022-04-14 17:51 UTC, jwitz commented on astro/develop-project.md
> +  If you use a non-`base` distribution of Runtime, you need to replace it with the more customizable `base` distribution before building your project from a private registry. For more information, se
Cutting some info out here that is explained by the doc that we link out to

2022-04-14 18:03 UTC, stuart23 commented on astro/develop-project.md
> +For example, to install the `mypackage1` & `mypackage2` from `myorganization`, as well as `numpy v 1.22.1`, you would add the following to `requirements.txt`:
We are using package & repo interchangeably here - do you think this is causing confusion?

2022-04-14 18:03 UTC, jwitz commented
@paolaperaza @stuart23 All comments should be resolved now! I also took any suggestions from Astro and applied them to the Software version of the doc.

2022-04-14 18:07 UTC, stuart23 commented on astro/develop-project.md
> +  If you currently use the default distribution of Astro Runtime, replace your existing image with its corresponding `-base` distribution as demonstrated in the example above. This `-base` distributi
sidenote: this is such a good explanation of the difference between the runtime and base images! Thankyou!

2022-04-15 04:51 UTC, paolaperaza approved these changes
LGTM! Final copy tweaks here but I think we're ready. @stuart23 LAST thing - I addressed your comment on the potential confusion between repo <> package. I admittedly didn't realize those were 1:1, so clarified here.

Give it a ✅ if this looks good to you - you requested changes, so I think we need it 😊

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +To build from a private repository, you need:
```suggestion
To install Python packages from a private GitHub repository on Astro, you need:
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +- A [GitHub SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private GitHub repo(s).
```suggestion
- A [GitHub SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private GitHub repository.

This setup assumes that each custom Python package is hosted within its own private GitHub repository. Installing multiple custom packages from a single private GitHub repository is not supported.
```

@stu Good call on clarifying the 1:1 relationship between a package and a repo -- I agree we've been using them interchangeably. This work?

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +For example, to install the `mypackage1` & `mypackage2` from `myorganization`, as well as `numpy v 1.22.1`, you would add the following to `requirements.txt`:
```suggestion
For example, to install `mypackage1` & `mypackage2` from `myorganization`, as well as `numpy v 1.22.1`, you would add the following to your `requirements.txt` file:
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +git+ssh://git@github.com/<organization-name>/<repository>.git
```suggestion
git+ssh://git@github.com/<your-organization-name>/<your-private-repository>.git
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +  If you currently use the default distribution of Astro Runtime, replace your existing image with its corresponding `-base` distribution as demonstrated in the example above. This `-base` distributi
```suggestion
  If you currently use the default distribution of Astro Runtime, replace your existing image with its corresponding `-base` image as demonstrated in the example above. The `-base` distribution is built to be customizable and does not include default build logic. For more information on Astro Runtime distributions, see [Distributions](runtime-version-lifecycle-policy.md#distribution).
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +    - Complete the standard installation of OS-level packages in `packages.txt`.
```suggestion
    - Install any OS-level packages specified in `packages.txt`.
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +    - Securely mount your SSH key during build, which ensures that the key itself is not stored in the resulting Docker image filesystem or metadata.
```suggestion
    - Securely mount your SSH key at build time. This ensures that the key itself is not stored in the resulting Docker image filesystem or metadata.
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file, making sure to replace `<ssh-key>` with your SSH key file name and `<runtime-image>` with your Runtime ima
```suggestion
1. Run the following command to create a new Docker image from your `Dockerfile.build` file, making sure to replace `<ssh-key>` with your SSH key file name and `<astro-runtime-image>` with your Astro Runtime image:
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<ssh-key>" -t custom-<runtime-image> .
```suggestion
    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<ssh-key>" -t custom-<astro-runtime-image> .
```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +    For example, if you have `quay.io/astronomer/astro-runtime:4.2.10` in your `Dockerfile.build`, this command would be:
```suggestion
    For example, if you have `quay.io/astronomer/astro-runtime:4.2.10-base` in your `Dockerfile.build`, this command would be:
```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
> +To build from a private repository, you need:
```suggestion
To install Python packages from a private GitHub repository on Astronomer Software, you need:
```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
> +- A [GitHub SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private GitHub repo(s).
```suggestion
- A [GitHub SSH Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) authorized to access your private GitHub repo(s).

This setup assumes that each custom Python package is hosted within its own private GitHub repository. Installing multiple packages from a single private GitHub repository is not supported.
```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
```suggestion

This example assumes that the name of each of your Python packages is identical to the name of its corresponding GitHub repository. In other words,`mypackage1` is both the name of the package and the name of the repository.

```

2022-04-15 04:51 UTC, paolaperaza commented on astro/develop-project.md
> +
```suggestion

This example assumes that the name of each of your Python packages is identical to the name of its corresponding GitHub repository. In other words,`mypackage1` is both the name of the package and the name of the repository.

```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
> +To add a Python package from a private repository to your Software project, specify the repository's SSH URL in your project's `requirements.txt` file. This URL should be formatted as `git+ssh://git@
```suggestion
To add a Python package from a private repository to your Software project, specify the repository's SSH URL in your project's `requirements.txt` file. This URL should be formatted as `git+ssh://git@github.com/<your-github-organization-name>/<your-private-repository>.git`.
```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
> +  If you use an `-onbuild` distribution of Certified, you need to replace it with the more customizable base distribution before building your project from a private registry. This base distribution
```suggestion
  If you use the default distribution of Astronomer Certified, make sure to remove the `-onbuild` part of the image. The Astronomer Certified distribution that does not specify `-onbuild` is built to be customizable and does not include default build logic. For more information, see [Distributions](ac-support-policy.md#distribution)
```

2022-04-15 04:51 UTC, paolaperaza commented on software/customize-image.md
> +    - Install Python-level packages from your private repository as specified in your `requirements.txt` file.
```suggestion
    - Install any OS-level packages specified in `packages.txt`.
    - Securely mount your GitHub SSH key at build time. This ensures that the key itself is not stored in the resulting Docker image filesystem or metadata.
    - Install all Python-level packages in `requirements.txt` file, including those from a private GitHub repository.
```

2022-04-15 05:01 UTC, paolaperaza commented on software/customize-image.md
> +This setup assumes that each custom Python package is hosted within its own private GitHub repository. Installing multiple packages from a single private GitHub repository is not supported.
@stuart23 Clarifying sentence 1

2022-04-15 05:01 UTC, paolaperaza commented on software/customize-image.md
> +This example assumes that the name of each of your Python packages is identical to the name of its corresponding GitHub repository. In other words,`mypackage1` is both the name of the package and the
@stuart23 Clarifying sentence 2

2022-04-15 17:06 UTC, stuart23 approved these changes
:kissing_heart::ok_hand:

2022-04-20 17:42 UTC, paolaperaza commented
MERGING finally! Thanks @stuart23 + @conorbev for the thorough reviewing & help here 🚀

2022-04-20 17:43 UTC, merged