Lineage UI documentation
astronomer/docs pull request #544
Opened 2022-03-28 15:38 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/499

Original draft: https://www.notion.so/astronomerio/Lineage-Tab-Docs-7ee22b7009ff4c19b61023dace2180b8

2022-03-28 15:39 UTC, jwitz commented on astro/lineage.md
> +### Using the Compare Tab
```suggestion
### Compare Lineage Between Runs Using the Compare Tab
```

2022-04-08 23:14 UTC, paolaperaza requested changes
@jwitz There is so much content here! Great start. My initial thought is:

- Let's think about splitting out the overview if possible
- Let's try to add more visuals here. TBH not sure on best practices here but let's do some brief research on how other folks do it.
- Let's standardize language & introduce new "terms" early on so that the user doesn't lose context throughout

I think in general the structure of this "per view" is right. Give my comments a look and do another detailed pass. I'll take a look again from there.

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +## Navigating the Lineage Graph
I feel like we're using `Lineage Graph` and `Lineage tab` interchangeably, but we might need to take a step back here and have a small section that explains:

- Explore
- Issues
- Lineage

And then dive into the 3rd of course in the most detail. I have Conor feedback that there shouldn't be two tabs named "lineage" ha but for now we should just standardize on distinct naming

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +- Each dataset represents a data source that your tasks interact with, such as a Snowflake database.
```suggestion
- Each job represents an individual step in your data pipeline. This could be an Airflow task within a DAG or a Spark job in Databricks.
- Each dataset represents a data source that your tasks interact with. This could be a Snowflake database.
```

Stupid Q - Could dataset be something other than a database?

Stupid Q - the nodes here _could_ be

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +In the lineage tab, Astronomer renders your data pipeline as a set of **dataset** and **job** nodes connected in a graph:
```suggestion
In the lineage tab, Astronomer renders your data pipeline as a set of **dataset** and **job** nodes connected by directed vertices in a graph:
```

You introduce the word `directed vertices` below -- maybe just use it in context first to make it clear?

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +Directed vertices connect jobs to datasets and vice versa. A single vertex will never connect two jobs or two datasets together.
```suggestion
Directed vertices connect jobs to datasets and visa versa. A single vertex will never connect two jobs or two datasets to each other.
```

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +You can navigate the graph by clicking and dragging your mouse across the screen. You can zoom in/out to a specific part of the graph by scrolling with your mouse wheel/ mousepad or by clicking the m
```suggestion
To navigate the graph, click and drag your mouse across the screen or zoom in or out by scrolling. You can also click the magnifying glass icons in the information pane on the bottom-left of the screen.
```

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +- **Quality checks (Dataset only)**: The status of each completed data quality check for a dataset
```suggestion
- **Namespace**: The namespace of the Deployment in which the job ran.
- **Name**: The DAG ID and task ID of the job, formatted as `<dag-id>.<task-id>`
- **Run information (job only)**: Metadata and status information about a job run
- **Quality checks (dataset only)**: The status of each completed data quality check for a dataset
```

What happens if this is a spark job -- is namespace empty?

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +## Navigating the Lineage Graph
Honestly it might be good to take a general/wide screenshot or GIF of the lineage graph and like put boxes around the sections to show:

- Graph
- Node
- Information Pane

Kind of a challenge to put this view into words! Maybe we can do some research on how observability/visual tools document stuff?

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +Clicking on the key icon in the information pane opens the graph legend. The legend provides a visual guide to help you distinguish between:
```suggestion
Clicking on the key icon in the information pane opens the graph legend. The legend provides a visual guide to help you distinguish between:
```

Does this key icon have a name?

2022-04-08 23:14 UTC, paolaperaza commented on astro/lineage.md
> +- Completed, running, failed, and aborted dataset checks
Are we capitalizing job and dataset or nah? Let's add to style guide

2022-04-11 15:23 UTC, jwitz commented on astro/lineage.md
> +sidebar_label: 'Data Lineage'
Hoping to put the overview in "Reference", so I think it's okay to keep this general. Hoping that this is the only lineage-related doc under "Observability"

2022-04-11 15:24 UTC, jwitz commented on astro/lineage.md
> +title: "Observe Deployments Through Data Lineage"
Explore sounds a bit introductory, if we're going for utility I think we should be specific about what people can do with lineage (observe)

2022-04-11 15:27 UTC, jwitz commented on astro/lineage.md
> +This guide explains how to navigate the Lineage graph and filter its data to better diagnose potential issues with your data pipelines.
Cutting this down p significantly, I think that the overview sentence should cut to the chase. We can use some of this language in the following paragraphs.

2022-04-11 17:27 UTC, jwitz commented on astro/lineage.md
> +## Navigating the Lineage Graph
In the future we could toy with having more detailed screenshots, but I'm hesitant to compile too much information into an inaccessible format. For now, I took the overview screenshot and used it here, then described and example of a job/ dataset/ vertex within the context of the screenshot.

2022-04-11 17:29 UTC, jwitz commented on astro/lineage.md
> +In the lineage tab, Astronomer renders your data pipeline as a set of **dataset** and **job** nodes connected in a graph:
We can use the phrase "directed graph" to describe this without having to get into the details of vertices, which I think is cleaner

2022-04-11 17:43 UTC, jwitz commented on astro/lineage.md
> +- Each dataset represents a data source that your tasks interact with, such as a Snowflake database.
"This could" makes it less clear whether the example is of a data source/ step or a dataset/job (grammatically, it should be the former). 

I don't think a dataset could be anything other than a database. The type of database might vary, but if you're managing data in any way you have to interact with a database/set

2022-04-11 17:45 UTC, jwitz commented on astro/lineage.md
> +Directed vertices connect jobs to datasets and vice versa. A single vertex will never connect two jobs or two datasets together.
never heard visa before, p sure it's vice

2022-04-11 17:48 UTC, jwitz commented on astro/lineage.md
> +- **Quality checks (Dataset only)**: The status of each completed data quality check for a dataset
From what I understand, if the Spark job was triggered by a DAG in a namespace, then the job will also appear under that namespace grouping. Can you confirm @conorbev ?

2022-04-11 17:49 UTC, jwitz commented on astro/lineage.md
> +Clicking on the key icon in the information pane opens the graph legend. The legend provides a visual guide to help you distinguish between:
Nope, it definitely should because there's some important settings in there. One for PB?

2022-04-11 17:50 UTC, jwitz commented on astro/lineage.md
> +- Completed, running, failed, and aborted dataset checks
Let's not capitalize them, and yeah I'll add that to style!

2022-04-11 17:58 UTC, jwitz commented on astro/lineage.md
> +### Using the Compare Tab
Should we make this an `h2` even though it's part of the information pane?

2022-04-11 23:06 UTC, jwitz commented on sidebarsAstro.js
> +        'lineage',
```suggestion
        'data-lineage',
```

2022-04-18 22:06 UTC, conorbev commented on astro/lineage.md
> +- **Lineage:** By default, renders a data lineage graph for your most recent pipeline run
`By default, renders a data lineage graph for your most recent pipeline run` --> `By default, renders your most recently viewed graph. First click on a job or dataset of interest from the Explore or Issues pages if no default has been set yet.`

2022-04-18 22:06 UTC, conorbev commented on astro/lineage.md
> +- **Explore:** Summarizes the performance of all data pipeline runs over the last year and lists your most recent pipeline runs
Add: `. Click on any run to view its Lineage graph`

2022-04-18 22:06 UTC, conorbev commented on astro/lineage.md
> +- **Issues:** Shows information about each job or dataset that caused an issue during a pipeline run
Add: `. Click on any job or dataset issue to view its Lineage graph.`

2022-04-21 04:16 UTC, paolaperaza commented on astro/lineage.md
> +The **Lineage** tab is available to all members of your Astro Organization. It includes real-time metadata genealogy and analytics across Deployments. This information is rendered as a graph that spa
```suggestion
The Lineage tab on Astro has three primary views:

- An **Explore** page that includes a real time view of all jobs that emit data lineage in your ecosystem. This includes metadata for Airflow tasks as well as jobs from other tools you may have integrated, such as Spark or dbt. This view also summarizes total job runs over time for up to one year.
- An **Issues** page that shows information about any job or dataset that may have caused an issue for a running pipeline.
- A **Lineage** page with a graph view that visualize data movements across DAGs, tasks, and Deployments. The graph primarily shows relationships between datasets and which pipelines and tasks actually connect them.

Generally speaking, these views can help you map your organization's data ecosystem and diagnose errors that may otherwise be difficult to identify across environments and tools. For example, if an Airflow task failed because it was unable to load data into an S3 bucket, you might go to the **Lineage** tab on Astro to determine the source of the problematic data and the point at which it became invalid.

Views in the **Lineage** tab are available to all members of your Organization on Astro.
```

2022-04-21 04:16 UTC, paolaperaza commented on astro/lineage.md
> +Because data lineage maps the full journey of your datasets, you can use this information to diagnose errors you detect from your Deployment logs and metrics. For example, if there was an error in an
```suggestion
```

2022-05-03 00:02 UTC, conorbev requested changes

2022-05-03 00:02 UTC, conorbev commented on astro/data-lineage.md
> +By default, the **Lineage** page shows the last lineage graph you accessed. To see high level metrics about all of your job runs and access lineage graphs for different Deployments, open the **Explor
remove: `for different Deployments`

I think we should add something like:

`For Airflow tasks the job name will be <dag_id>.<task_id>. For example the job: "example_dag_basic.extract" indicates the **extract** task running within the **example_dag_basic** DAG.`

2022-05-03 01:15 UTC, paolaperaza commented on astro/data-lineage.md
> +### Using the Quality Tab
```suggestion
### Check for Data Quality
```

2022-05-03 01:15 UTC, paolaperaza commented on astro/data-lineage.md
> +The **Quality** tab appears in the information pane whenever you select a dataset node from the graph. It contains both high level charts that provide information about the entire dataset, as well as
```suggestion
Whenever you select a dataset from the lineage graph, the **Quality** tab appears in the information pane. This tab shows a list of columns that correspond to your dataset.

If you integrate with [Great Expectations](https://docs.greatexpectations.io/docs/), this tab also shows:

- The number of rows in your dataset over time
- The amount of megabytes consumed by your dataset over time
- Successes and failures of data quality checks

If Great Expectations is not configured, this metadata will not be available.
```

2022-05-03 01:15 UTC, paolaperaza commented on astro/data-lineage.md
> +Use the **Quality** tab to detect looking for sudden, unexplained changes in your dataset that could indicate an upstream failure. The following topics explain each available chart in the tab.
```suggestion
Use the **Quality** tab to detect unexpected changes or statistical variance in your dataset that could indicate a problem. The following topics explain each available chart in the tab.
```

2022-05-03 01:26 UTC, jwitz commented on astro/data-lineage.md
> +Data lineage is a critical part of data orchestration tooling.  The **Lineage** tab on Astro has three pages:
"Astro homepage" isn't a term we've used before, why wouldn't we say Cloud UI here?

2022-05-03 01:28 UTC, jwitz commented on astro/data-lineage.md
> +- **Explore**: A real-time overview of all jobs that emit data lineage across your Organization
We can only anchor on job if it's a header in the doc, for now I can include a general link to the concepts doc at the end of the overview section.

2022-05-03 01:31 UTC, jwitz commented on astro/data-lineage.md
> +## View the Lineage Graph for a Deployment
The lineage graph includes all of these things, so I'm not sure it makes sense to say the "graph of a [component]". A lineage graph is organized by Deployment/namespace, right @conorbev?

2022-05-03 01:36 UTC, jwitz commented on astro/data-lineage.md
> +To view the lineage graph for one of your Deployments, search for a DAG or task in the Deployment with the search bar at the top of the UI.
I would add "from other tools with lineage integrations"

2022-05-03 01:46 UTC, jwitz commented on astro/data-lineage.md
> +Clicking a search result will open the **Lineage** page and show the lineage graph for the Deployment's most recent DAG run.
Might make sense to include that other note in either the compatibility or integrations doc, since it's a little more actionable there. Feels slightly out of place here.

2022-05-03 01:48 UTC, jwitz commented on astro/data-lineage.md
> +By default, when you directly access the **Lineage** page from the left-hand menu, the page shows your most recently accessed lineage graph. If you go to the **Lineage** page before first accessing a
Modified this slightly

2022-05-03 01:50 UTC, jwitz commented on astro/data-lineage.md
> +In the following example, `insert` is a job that exists as part of the `etl_menu_items` grouping. A vertex connects `insert` to the `menu_items` dataset to indicate that `insert` interacted with data
I don't mind `group`

2022-05-03 02:11 UTC, jwitz commented on astro/data-lineage.md
> +The Bytes chart shows the total size of the dataset over time. A sudden increase in dataset size usually means something has changed in the definition of the data. For example, a new column might hav
Holding off on this info for now based on Slack discussion

2022-05-03 02:28 UTC, jwitz commented
Should be ready for review again! All comments (save for those related to BQ/ GE) have been addressed.

2022-05-04 17:29 UTC, conorbev commented on astro/data-lineage.md
> +- **Explore**: A real-time overview of all jobs that emit data lineage across your Organization
Do you think it's overkill then to perhaps just add another sentence at the end here saying: `In Airflow a Task maps to an OpenLineage Job` ?

2022-05-04 17:29 UTC, conorbev commented on astro/data-lineage.md
> +The search results include the namespace that emitted the matching event. If an Astro Deployment emitted the lineage event, then this namespace will match Deployment's namespace as shown in the **Dep
I think: `show the lineage graph for the Deployment's most recent job run.` --> `show the lineage graph for the selected job or dataset.`

2022-05-04 17:29 UTC, conorbev commented on astro/data-lineage.md
> +Dataset and job statuses are based on checks of metadata attached to your data. To see the specifics of why a database check failed, you can click on the failed database node and check the **Quality*
`database check failed` --> `dataset failed`

2022-05-04 17:29 UTC, conorbev commented on astro/data-lineage.md
> +- **Explore**: A real-time overview of all jobs that emit data lineage across your Organization
I just assume that reading this page could be a lot of users first exposure to the term "job".

2022-05-04 17:29 UTC, conorbev commented on astro/data-lineage.md
> +
Reading this again, I think we should add another info section something like:

```
:::info

If the Lineage graph only shows you a single node it indicates that the job you selected did not emit any input or output datasets, likely because it is from a Task isn't using an [Airflow Operator that is supported out of the box.](link to supported operators doc). You will still be able to view the duration of this job over time. 
```

^ if we think 3 info boxes is too many I feel like this one ( or some edited version of it ) is probably even more important than the "most recent run" one.

2022-05-04 22:43 UTC, jwitz reviewed
One reply @conorbev , otherwise added your suggestions as you wrote them

2022-05-04 22:43 UTC, jwitz commented on astro/data-lineage.md
> +- **Explore**: A real-time overview of all jobs that emit data lineage across your Organization
I added "A job can be an Airflow task or another process configured to emit lineage data to Astronomer, such as a Spark job."

2022-05-05 16:27 UTC, jwitz commented on astro/data-lineage.md
> +
```suggestion

:::info 
This functionality is early access and under active development. If you have any questions or feedback about this feature, reach out to [Astronomer Support](https://support.astronomer.io/).
:::

```

2022-05-05 20:14 UTC, paolaperaza approved these changes

2022-05-05 20:15 UTC, merged