Lineage integrations documentation
astronomer/docs pull request #560
Opened 2022-04-04 21:38 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/501

This is an Astro docs version of our embedded Datakin docs: https://astro-dev-astronomer.datakin.com/onboarding

The base content hasn't changed much. Primary changes are:

- Updated overview section to include less introductory information about lineage
- Added some shoutouts to the embedded docs
- Reworded steps on how to configure the OpenLineage API key
- Updated links to be internal to Astro documentation. removed some remnants from DK

2022-04-05 14:21 UTC, jwitz commented on astro/lineage-integrations.md
> +This key is required in each of the following integration guides.
```suggestion
For more information about how to configure this API key in external systems, read the following integration guides. 
```

2022-04-06 04:59 UTC, rossturk approved these changes
Lgtm!

2022-04-11 23:03 UTC, jwitz commented on astro/lineage-integrations.md
> +id: lineage-integrations
```suggestion
sidebar_label: 'Set Up Data Lineage'
title: "Enable Data Lineage for External Systems"
id: set-up-data-lineage
```

2022-04-12 16:00 UTC, TohnJhomas approved these changes
LGTM

2022-04-25 17:15 UTC, conorbev requested changes
The URL for ingesting data should no longer be prefixed with `api.`

I left comments on the areas in this doc that need updating as a result.

2022-04-25 17:15 UTC, conorbev commented on astro/lineage-integrations.md
> +    OPENLINEAGE_URL=https://api.<your-astro-base-domain>
remove `api.` part so this becomes: `OPENLINEAGE_URL=https://<your-astro-base-domain>`

2022-04-25 17:15 UTC, conorbev commented on astro/lineage-integrations.md
> +   spark.openlineage.url https://api.<your-astro-base-domain>
remove `api.` part so this becomes: `spark.openlineage.url https://<your-astro-base-domain>`

2022-04-25 17:15 UTC, conorbev commented on astro/lineage-integrations.md
> +   OPENLINEAGE_URL=https://api.<your-astro-base-domain>
remove `api.` part so this becomes: `OPENLINEAGE_URL=https://<your-astro-base-domain>`

2022-04-25 17:15 UTC, conorbev commented on astro/lineage-integrations.md
> +              openlineage_host: https://api.<your-astro-base-domain>
remove `api.` part so this becomes: `openlineage_host: https://<your-astro-base-domain>`

2022-04-25 17:15 UTC, conorbev commented on astro/lineage-integrations.md
> +     .config('spark.openlineage.host', 'https://api.<your-astro-base-domain>')
remove `api.` part so this becomes: `.config('spark.openlineage.host', 'https://<your-astro-base-domain>')`

2022-05-05 00:33 UTC, jwitz commented on astro/lineage-integrations.md
> +To confirm that your setup was successful, run a `dbt` model in your project. After you run this model, open the **Lineage** tab in the Cloud UI and go to the **Explore** page. If the setup was succe
```suggestion
To confirm that your setup was successful, run a dbt model in your project. After you run this model, open the **Lineage** tab in the Cloud UI and go to the **Explore** page. If the setup was successful, you should see the run that you triggered in the **Most Recent Runs** table.
```

2022-05-05 00:37 UTC, jwitz commented on sidebarsAstro.js
> +        'lineage-integrations',
```suggestion
        'set-up-data-lineage',
```

2022-05-05 20:10 UTC, paolaperaza approved these changes

2022-05-05 20:11 UTC, conorbev approved these changes
lgtm

2022-05-05 20:12 UTC, merged