Create section for installing from private package repos
astronomer/docs pull request #597
Opened 2022-04-13 15:51 UTC by stuart23

2022-04-14 20:30 UTC, jwitz commented
@stuart23 Is the technical content here finalized? One we merge the other private repo PR, I'm going to jump in here and use Docusaurus' [tabs](https://docusaurus.io/docs/markdown-features/tabs) feature to condense these setups into a single section, since overall they're pretty similar. Won't get to this until I'm back from vacation on May 2nd though!

2022-04-14 21:43 UTC, stuart23 commented
@jaketf, @paolaperaza and I were just talking about separating these by tabs - I think it's a great idea! The technical details should be final, but you may want to play with some of the wording.

Happy to close the PR, or leave it here in draft mode until you return. Have a great vacation! :sunglasses::desert_island:

2022-05-06 23:06 UTC, stuart23 commented
Had another customer request to do this https://astronomer.zendesk.com/agent/tickets/9443

2022-05-13 18:06 UTC, jwitz commented on astro/develop-project.md
> +        {label: 'Linux', value: 'linux'},
```suggestion
```

2022-05-13 18:31 UTC, jwitz requested changes
Nice PR @stuart23 ! I jumped in to the branch to add tab formatting, but kept my other changes as suggestions in case you had thoughts on my wording. Let me know what you think, and I'll do one final pass to make sure the formatting looks OK before merging.

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +`requirements.txt`. For packages listed on private PyPI indices, or whos source code is stored in a private git repository, the build process requires some extra steps.
```suggestion
Python packages can be installed from public and private locations into your image. To install public packages listed on [PyPI](https://pypi.org/search/), follow the steps in [Add Python and OS-level Packages](add-python-and-os-level-packages). To install packages listed on private PyPI indices or a private git-based repository, you need to complete additional configuration in your project.
```

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +be injected before the ONBUILD instructions are executed.
```suggestion
Depending on where your private packages are stored, use one of the following setups to install your packages to an Astro project by customizing your Runtime image. 
```

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +This topic provides instructions for building your Astro project using Python packages from a private PyPI index. In some organizations, python packages will be prebuilt and pushed to a hosted privat
```suggestion
This topic provides instructions for building your Astro project using Python packages from a private PyPI index. In some organizations, python packages are prebuilt and pushed to a hosted private pip server (such as pypiserver or Nexus Repository) or managed service (such as PackageCloud or Gitlab). At a high level, this setup requires specifying your private packages in `requirements.txt`, creating a custom Docker image that changes where pip looks for packages, and building your project with this Docker image.
```

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-5.0.0 .
I don't think this example has been updated for the new setup

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +   Your Astro project can now utilize Python packages from your private GitHub repository. To test your DAGs, you can either [run your project locally](develop-project.md#build-and-run-a-project-loca
```suggestion
   Your Astro project can now utilize Python packages from your private PyPi index. To test your DAGs, you can either [run your project locally](develop-project.md#build-and-run-a-project-locally) or [deploy to Astro](deploy-code.md).
```

2022-05-13 18:31 UTC, jwitz commented on astro/develop-project.md
> +
```suggestion
```

2022-05-18 16:12 UTC, stuart23 commented
@jwitz checked it in Netlify and it is :kissing_heart::ok_hand:

I was thinking of adding the following extra tidbit at line 586, but do you think it's too in-the-weeds/best-practices?

    :::tip

    It is usually advised not to inject secrets literally as they can be easily uncovered using `docker history` on the image. In this case, a multi-stage build method is being used, and the secret is not in scope for stage3, and will not appear in the history.

    :::

2022-05-19 19:04 UTC, jwitz commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-5.0.0 .
Pingin on this again

2022-05-19 19:04 UTC, jwitz commented on software/customize-image.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-ap-airflow:2.2.5 .
Same thing here

2022-05-19 19:08 UTC, jwitz approved these changes
I think this is almost done @stuart23 ! There's just one more reference to GitHub in the PyPi docs that maybe needs to be fixed for both Astro and Software, but other than that this LGTM

The other note you suggested doesn't help users make a decision or take action during this build, so I'd advise against including it. If you want, you could add another inline comment to the Dockerfile that explains why our Stage 3 step is safe, but don't stress it either way

2022-05-19 19:11 UTC, stuart23 commented on software/customize-image.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-ap-airflow:2.2.5 .
:woozy_face: My bad

2022-05-20 19:02 UTC, merged