Add instructions for pre-build images with Github Actions
astronomer/docs pull request #614
Opened 2022-04-21 19:19 UTC by stuart23

2022-04-21 19:21 UTC, stuart23 commented
I know we might convert the CI/CD options to tabs (I think that would look great). How do we want to group multiple Github actions methods?

2022-05-06 14:44 UTC, stuart23 commented
@jwitz @paolaperaza @kwcanuck this is ready for review.

2022-05-06 15:45 UTC, stuart23 commented on astro/ci-cd.md
> +- The Private Key file that was used to authenticate to GitHub is still available.
You prefer "The Private Key file that _you_ used..." over "The Private Key file that _was_ used"?

2022-05-13 19:20 UTC, jwitz requested changes
Jumped in and added some tabs here @stuart23 , but before I do any inline editing I wanted to see if you could generalize the setup in light of your other PR (https://github.com/astronomer/docs/pull/597). Right now it looks based on the private GitHub repo setup, can we change this so that it works for either private package setup? Either by using comments in the YAML or by having more general variable names that are not GitHub dependent.

2022-05-27 18:41 UTC, jwitz commented
@stuart23 Is this ready for review again? There's some changes to the CLI coming Tuesday that might change the commands included in this pipeline, so probably won't merge until then. But I can give you quick review and make sure it's ready to go

2022-06-02 07:24 UTC, stuart23 commented
Hey @jwitz the body of it is ready. I would like a second opinion on the readability - especially given that it is covering two potential use cases (private Github repo & private Pypi index) in one instruction set. The copy can also be tweaked if you want.

2022-06-02 19:41 UTC, jwitz commented
Sweet, gonna wait for the dust to settle on the CLI front and then I'll give this another look copy-wise

2022-06-03 20:44 UTC, jwitz requested changes
@stuart23 Sorry but I'm still confused about the scope here. Originally I thought this pipeline was going to be for _all_ customizable image use cases. Instead of generalizing, it looks like we've created a pipeline template for a very specific use case.

We should either: 
- be explicit about the fact that these templates are for users building python packages from a private reg. If this is the case, then it might even be better to document the pipelines in https://docs.astronomer.io/astro/develop-project#install-python-packages-from-private-sources to keep everything in one place
- generalize this template further so that it applies to most custom image use cases. That would involve generalizing what we put in `build-args`, `ssh`, etc. We can still mention the other private reg setup here as an example, but we'd want to focus mostly on a broader range of users. 

I'll let you decide what route to take since you are closer to the users and have a better understanding of what info they're after. Let me know if you want to jump in to the PR again and make any of these changes myself, I'm available!

2022-06-03 20:44 UTC, jwitz commented on astro/ci-cd.md
> +This setup assumes the following prerequisites:
```suggestion
#### Prerequisites
```

2022-06-03 20:44 UTC, jwitz commented on astro/ci-cd.md
> +- If installing from a private PyPi Index, you have a username and password to authenticate to the index.
```suggestion
To complete this setup, you need:

- An Astro project with a custom Runtime image. For an example implementation of this, see [Install Python Packages from Private Sources](develop-project.md#install-python-packages-from-private-sources).
```

2022-06-03 20:44 UTC, jwitz commented on astro/ci-cd.md
> +            astrocloud deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
```suggestion
            brew install astronomer/tap/astro
            astro deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
```

2022-06-03 20:44 UTC, jwitz commented on astro/ci-cd.md
> +            astrocloud deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
```suggestion
            brew install astronomer/tap/astro
            astro deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
```

2022-06-08 16:45 UTC, jwitz approved these changes

2022-06-08 17:34 UTC, merged