Update airflow-api.md
astronomer/docs pull request #636
Opened 2022-04-26 23:04 UTC by RNHTTR

* Make the long single-line curl request on multiple lines
* fix typo in python code block
* escape new lines in curl requests
* replace stylized quotations that might cause issues for some users

2022-04-27 23:51 UTC, paolaperaza approved these changes
Love it! This looks great. Thanks @RNHTTR. Feel free to merge whenever you're ready!

2022-04-28 00:26 UTC, paolaperaza reviewed
@RNHTTR Actually! I see that you included a Python and cURL request for the Software version of this PR: https://github.com/astronomer/docs/pull/635/files#

Before we merge this, can you:

- Add the example Python request for "Trigger DAG" (make sure execution date isn't specified)
- Add an example cURL request for "List Pools"

2022-05-03 05:04 UTC, paolaperaza reviewed
@RNHTTR Thanks for another round! I made some copy suggestions, and didn't actually get a chance to look through all the example requests. I think I'd still like to maintain a format where we give each example request an H3 `###` such that they show up on the right-hand side menu on docs and are more easily searchable.

2022-05-03 05:04 UTC, paolaperaza commented on astro/airflow-api.md
> +With the information from Step 1, you can now execute requests against any supported endpoints in Airflow's [Rest API Reference](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-
@RNHTTR I still think it's helpful to give a step that is "self-service" in that it tells you what you need to know to look at Airflow docs and make your own requests. And then we jump into examples. WDYT?

2022-05-03 12:46 UTC, RNHTTR commented on astro/airflow-api.md
>  You can use Airflow's [REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html) to automate various Airflow workflows in your Deployments.
IMO, it's possible to need the API even if you're a small team with a small number of DAGs. Like if you wanted some automated workflow based on some external system.

2022-05-03 12:48 UTC, RNHTTR commented on astro/airflow-api.md
> +For example, if you're looking to externally trigger DAG runs without accessing your Airflow Deployment directly, you can make an HTTP request (in Python, cURL etc.) to the [corresponding endpoint](h
Access to the API isn't limited to Python/cURL; a user can use any programming language, Postman, etc. I think the grammar changes here are good though.

2022-05-03 12:51 UTC, RNHTTR commented on astro/airflow-api.md
> +All calls to your Deployment's Airflow API require:
What do you think of "Calls to the Airflow REST API for a Deployment on Astro require:"? I think the "If specific to a Deployment on Astro" kind of implies that there are some general Airflow REST API calls that can be made across all Deployments on Astro, but each Deployment requires its own URL.

2022-05-03 12:53 UTC, RNHTTR commented on astro/airflow-api.md
> +In automated processes (such as a [CI/CD pipeline](https://docs.astronomer.io/astro/ci-cd)), we recommend including logic to generate a fresh access token. For example, adding a step in in a CI/CD pi
I think this is probably fine, but I figured it makes sense to include processes beyond CI/CD, because I believe there are probably scenarios where people need to make API calls from a system outside a CI/CD process, and that would similarly require logic for generating a fresh access token every 24 hours. Thoughts?

2022-05-03 13:04 UTC, RNHTTR commented on astro/airflow-api.md
> +With the information from Step 1, you can now execute requests against any supported endpoints in Airflow's [Rest API Reference](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-
I like specifically breaking out the examples in their own header to make it more explicit that there are a lot more endpoints that can be hit. I think we could be even more explicit by saying something like "The examples included here are a small sample of what's possible with the [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html)"

I think we should still call back to "Step 1" for the Deployment URL & access token, because lazy people like me will skip to step 2 :D

2022-05-04 00:25 UTC, jwitz requested changes
@RNHTTR Great PR here, you've got a good knack for writing in our Astro docs voice! Added some comments, marking requesting changes because I think the example section is a bit too guide-y. If we include more examples of API calls, I think they should exist under an `## Example Requests` header, with a `###` level header for each separate example. Let me know if you want me to jump into the PR myself to work on that detail, it's mostly formatting so I don't mind at all!

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +For example, if you're looking to externally trigger DAG runs without accessing your Airflow Deployment directly, you can make an HTTP request (in Python, cURL etc.) to the [corresponding endpoint](h
The "for example" means that the described use case is one of many that you can use, so I don't see an issue with being specific here about Python/ cURL.

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +All calls to your Deployment's Airflow API require:
@RNHTTR I like that wording!

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +In automated processes (such as a [CI/CD pipeline](https://docs.astronomer.io/astro/ci-cd)), we recommend including logic to generate a fresh access token. For example, adding a step in in a CI/CD pi
I've not heard of a situation like that yet, and we certainly don't have it documented. IMO I'd rather not elude to an undocumented workflow and instead focus on the CI/CD use case.

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +To retrieve your Deployment URL, open your Deployment in the Cloud UI and click **Open Airflow**. The URL for the Airflow UI is your Deployment URL minus `/home`. It includes the name of your Organiz
```suggestion
To retrieve your Deployment URL, open your Deployment in the Cloud UI and click **Open Airflow**. The Deployment URL is the URL for the Airflow UI homepage up until `/home`. It includes the name of your Organization and a short Deployment ID. For example, a Deployment with an ID `dhbhijp0` that is part of an Organization called `mycompany` would have a Deployment URL of `https://mycompany.astronomer.run/dhbhijp0`.
```

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +With the information from Step 1, you can now execute requests against any supported endpoints in Airflow's [Rest API Reference](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-
I'd drop the "From Step 1" bit if we end up making this a Step 2

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> +For example, to retrieve a list of all DAGs in a Deployment, you can run a `GET` request to the [`dags` endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operat
```suggestion
For example, to retrieve a list of all DAGs in a Deployment, you can run a `GET` request to the [`dags` endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dags) using cURL:
```

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
```suggestion
```

2022-05-04 00:25 UTC, jwitz commented on astro/airflow-api.md
> -### List All Pools
I liked when we had headers for each example call, @RNHTTR would you mind if I jumped into this PR and updated some of this content to match the existing formatting?

2022-05-04 01:03 UTC, RNHTTR commented on astro/airflow-api.md
> -### List All Pools
By all means! It'd be great if you jumped in and took it over the finish line :)

2022-05-04 14:46 UTC, jwitz approved these changes
Alright @RNHTTR just jumped in to make the final changes here! You should be good to merge, but it would be great if you had time to look through the last few commits I made to ensure that I didn't accidentally say something technically inaccurate. Cheers!

2022-05-04 19:34 UTC, merged

2022-05-04 19:35 UTC, RNHTTR commented
Thanks y'all!!! @paolaperaza  @jwitz

2022-05-04 22:36 UTC, paolaperaza commented
Thank YOU @RNHTTR ! Glad we got this over the finish line