Refactored "Airflow Versioning" Doc
astronomer/docs pull request #68
Opened 2020-11-09 18:36 UTC by paolaperaza

This PR refactors our existing Airflow Versioning doc to incorporate 0.22 changes to the user experience of upgrading Airflow versions. Resolves: https://github.com/astronomer/issues/issues/2109

- [ ]  Change Title to "Manage Airflow Versions"
- [ ]  Add redirect to new URL
- [ ]  via Astro CLI
- [ ]  via Astro UI
- [ ]  Error Scenarios
- [ ]  Cancel Upgrade
- [ ] Add Screenshots

2020-11-09 21:57 UTC, vishwas-astro requested changes

2020-11-09 21:57 UTC, vishwas-astro commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +> **Note:** If you'd like to change your selected version of Airflow to upgrade to, you can do so at anytime as long as long as you re-click **Upgrade** after making your selection.
"as long as long as" -> "as long as"

2020-11-09 21:57 UTC, vishwas-astro commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +Airflow upgrade process has been successfully canceled. Your Deployment was not interrupted and you are still running Airflow 1.10.5.
1.10.5 is an example here, right? Can you make that clear?

2020-11-09 21:57 UTC, vishwas-astro commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
>  Astronomer supports both Alpine Linux and Debian-based images. Alpine is a widely-used lightweight distribution of Linux that keeps our default images slim and performant. For users leveraging Machin
Do we want to leave this reference to both alpine and debian images alone for now?

2020-11-09 21:57 UTC, vishwas-astro commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +For our platform's full collection of Docker Images, reference [Astronomer on Docker Hub](https://hub.docker.com/r/astronomerinc/ap-airflow/tags).
Should we change this link to quay.io? @danielhoherd may be able to help you with that.

2020-11-09 21:57 UTC, vishwas-astro commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
>  Astronomer supports both Alpine Linux and Debian-based images. Alpine is a widely-used lightweight distribution of Linux that keeps our default images slim and performant. For users leveraging Machin
never mind. I just saw your update later in the PR.

2020-11-09 22:08 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +1. Initialize the Airflow Upgrade via the Astronomer UI or CLI
Good call, I can make this more explicit - changed!

2020-11-09 22:08 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +2. Change the FROM statement in your project's Dockerfile to reference the new AC image of your choice
Changed!

2020-11-09 22:08 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +> **Note:** If you'd like to change your selected version of Airflow to upgrade to, you can do so at anytime as long as long as you re-click **Upgrade** after making your selection.
Whoops, thank you - changed

2020-11-09 22:27 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +Airflow upgrade process has been successfully canceled. Your Deployment was not interrupted and you are still running Airflow 1.10.5.
Yes. Done!

2020-11-09 22:29 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +For our platform's full collection of Docker Images, reference [Astronomer on Docker Hub](https://hub.docker.com/r/astronomerinc/ap-airflow/tags).
Yea, we should - @danielhoherd can you send me the correct link? Is it this one? https://quay.io/repository/astronomer/ap-airflow?tab=tags

2020-11-09 22:37 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
> +For our platform's full collection of Docker Images, reference [Astronomer on Docker Hub](https://hub.docker.com/r/astronomerinc/ap-airflow/tags).
Daniel H confirmed that's the correct link - changed

2020-11-09 22:56 UTC, vishwas-astro commented
LGTM, once you add the screenshots. Thanks for addressing all my comments @paolaperaza

2020-11-09 22:57 UTC, vishwas-astro approved these changes

2020-11-12 17:26 UTC, paolaperaza commented
Merging this! Thanks all. @ryanahamilton will confirm website redirect with you.

2020-11-12 17:26 UTC, merged