Astro CLI Tab - Overview, Quickstart, and Configure CLI docs
astronomer/docs pull request #711
Opened 2022-05-19 22:57 UTC by jwitz

Resolves https://github.com/astronomer/docs/issues/653

This PR contains the new non-reference documentation in the Astro CLI tab:

- **Overview**: A product-focused intro to the CLI, goal is to get people into the quickstart as soon as possible
- **Quickstart**: A streamlined guide for installing the CLI and getting an Astro project running locally
- **Configure the CLI** (unfinished): A more in-depth guide for configuring the CLI, meant to be referenced by experienced users/ troubleshooters.

2022-05-20 15:15 UTC, jwitz commented on astro/cli/cli-quickstart.md
> +The Astro CLI is the easiest way to run Apache Airflow on your machine. By the end of this quickstart, you'll be able to run an Airflow project on your local machine with just a few commands.
```suggestion
The Astro CLI is the easiest way to run Airflow on your local machine. By the end of this quickstart, you'll be able to run an Airflow project on your local machine with just a few commands. 
```

2022-05-20 21:31 UTC, jwitz commented on astro/cli/configure-cli.md
> +[Upgrade steps for Windows]
@sunkickr Can you help me write upgrade and uninstall steps for both Windows and Linux? Do they just need to delete their existing executable and download a new one?

2022-05-23 20:35 UTC, sunkickr requested changes
Looks good just added some information about install, and use of the CLI

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +2. Based on your CPU, run one of the following commands to download the Astro CLI executable into your project directory.
These links only work for pre-releases. Once we release v1 users will need to go to https://github.com/astronomer/astro-cli/releases to find the release they want a download it. For example if they want the release for windows AMD 64 for v0.29.0 they would go to https://github.com/astronomer/astro-cli/releases/tag/v0.29.0 and click on 
astro_0.29.0_windows_amd64.zip  this should automatically unzip the file into there downloads folder next they will add the executable to either their Astro project to run as ./astro or add it to PATH to run globally

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +2. Based on your CPU, run one of the following commands to download the Astro CLI executable into your project directory.
Linux and mac users can use can use install.astronomer.io to install the CLI directly to PATH. We should not have users mess with PATH if don't need to. For linux we should just ask users to run

```
curl -sSL install.astronomer.io | sudo bash -s
```

Or ask them to run this command for a specific version

```
curl -sSL https://install.astronomer.io | sudo bash -s -- v1.0.0
```

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +brew install astronomer/cloud/astro
```suggestion
brew install astronomer/tap/astro
```

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +brew install astronomer/cloud/astro
This command will give the user the latest version of the CLI

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Upgrade steps for Windows]
To upgrade for windows the user will need to go to https://github.com/astronomer/astro-cli/releases to find the latest release for their os, download it, then replace the old executable in PATH or their project with the new executable

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Upgrade steps for Linux]
To upgrade to the latest version in linux the user just needs to run

```
curl -sSL install.astronomer.io | sudo bash -s
```

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Upgrade steps for Windows]
yes, I add some details in my comment on upgrading windows above

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +brew uninstall astronomer/cloud/astro
```suggestion
brew uninstall astronomer/tap/astro
```

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Upgrade steps for Windows]
Specifically to uninstall they need to remove the the executable from PATH or the their project directory and delete it

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Uninstall steps for Windows]
Remove astrocloud executable from PATH. Would need to look more into how to do this exactly

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +[Uninstall steps for Linux]
Remove the astrocloud executable from PATH

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/configure-cli.md
> +2. Run `astro dev init` to generate a new `.astro` directory in your project. This subdirectory might be hidden in graphical file browsers. You can show hidden files using `⌘ + Shift + .` on Mac or b
We should note that when the user runs `astro dev init` they will need to say yes to message asking them if they would like to continue because the directory is not empty

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/overview.md
> +- Manage user permissions in Astro Workspaces and Deployments.
You can do this from Software but not Astro yet with the CLI

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/overview.md
> +- Manage user permissions in Astro Workspaces and Deployments.
may be better to just say that you can manager Astro Workspaces and Deployments. Also maybe we should add a fourth point saying that you can run and test your DAGs locally

2022-05-23 20:35 UTC, sunkickr commented on astro/cli/quickstart.md
> +It might take a few minutes for the Airflow UI to be available. As you wait for the Webserver container to start up, you might need to refresh your browser.
The user will be notified by CLI out put once their webserver is available

2022-05-25 15:06 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +
```suggestion
```

2022-05-25 15:06 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +To install the latest version of the Astro CLI, run the following command:
```suggestion

#### Installation

To install the latest version of the Astro CLI, run the following command:
```

2022-05-25 15:06 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +1. Go to the [**Releases** page of the Astro CLI GitHub](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and CPU architecture, download one of the `.zip` file
```suggestion
1. Go to the [**Releases** page of the Astro CLI GitHub repository](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and CPU architecture, download one of the `.zip` files available on this page.
```

2022-05-25 15:07 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +1. Go to the [**Releases** page of the Astro CLI GitHub](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and CPU architecture, download one of the `.zip` file
What are all the possible values depending on `CPU architecture`? I see `amd64` - is there something else users would pick between? I'd list em out if so

2022-05-25 15:07 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +    For example, if you wanted to install v1.0.0 of the Astro CLI on a Windows Machine with an AMD 64 architecture, you would download `astro_1.0.0-converged_windows_amd64.zip`.
```suggestion
    For example, to install v1.0.0 of the Astro CLI on a Windows Machine with an AMD 64 architecture, download `astro_1.0.0-converged_windows_amd64.zip`.
```

2022-05-25 15:08 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +3. Save `astro.exe` in a secure location on your machine and add its filepath in the Windows PATH environment variable. For more information about configuring the PATH environment variable, read [Jav
```suggestion
3. Save `astro.exe` in a secure location on your machine and add its filepath as a Windows PATH environment variable. For more information about configuring the PATH environment variable, read [Java documentation](https://www.java.com/en/download/help/path.html).
```

2022-05-25 15:09 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +- [Docker Engine](https://docs.docker.com/engine/install/) (v0.13.1 or higher).
```suggestion
- [Docker Engine](https://docs.docker.com/engine/install/) (v0.18.9 or higher).
```

@sunkickr This prob needs to be `v18.09` or higher right? I think 0.13.1 was requirement years ago for Software... assume we should bump it up?

2022-05-25 15:11 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +brew install astronomer/tap/astro@0.XX
```suggestion
brew install astronomer/tap/astro@<major.minor.patch-version>

If you specify only a major version, the latest minor and patch version that corresponds will be installed automatically.
```

@sunkickr This true?

2022-05-25 15:14 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +
```suggestion

If you specify only a major version, the latest minor and patch version that corresponds will be installed automatically.
```

Same thing here - @jwitz There might be a better way to phrase this

2022-05-25 15:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +To upgrade the Astro CLI, you can run the same command as you did to install the CLI for the first time:
```suggestion
To upgrade the Astro CLI to the latest version, you can run the same command as you did to install the CLI for the first time:
```

2022-05-25 15:15 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +
```suggestion
<TabItem value="windows">

To upgrade the Astro CLI on Windows, follow the steps below.
```

2022-05-25 15:16 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +1. Remove the existing `astro.exe` file on your machine.
```suggestion
1. Remove the `astro.exe` file on your machine that corresponds to your currently running version.
```

2022-05-25 15:16 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +2. Go to the [**Releases** page of the Astro CLI GitHub](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and CPU architecture, download one of the `.zip` file
```suggestion
2. Go to the [**Releases** page of the Astro CLI GitHub repository](https://github.com/astro-projects/astro-cli/releases). Based on the version of the CLI you want to upgrade to and your CPU architecture, download one of the `.zip` files available on this page.
```

2022-05-25 15:17 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +    For example, if you wanted to install v1.0.0 of the Astro CLI on a Windows Machine with an AMD 64 architecture, you would download `astro_1.0.0-converged_windows_amd64.zip`.
```suggestion
    For example, if you wanted to upgrade to v1.0.0 of the Astro CLI on a Windows machine with an AMD 64 architecture, you would download `astro_1.0.0-converged_windows_amd64.zip`.
```

2022-05-25 15:17 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +4. Save the new `astro.exe` file that you just unzipped in a secure location on your machine and add its filepath in the Windows PATH environment variable. For more information about configuring the
```suggestion
4. Save the new `astro.exe` file that you just unzipped in a secure location on your machine and add its filepath as a Windows PATH environment variable. For more information about configuring the PATH environment variable, read [Java documentation](https://www.java.com/en/download/help/path.html).
```

2022-05-25 15:18 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +To uninstall the Astro CLI, run the following command:
```suggestion
To uninstall the Astro CLI on Mac, run:
```

2022-05-25 15:18 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +To uninstall the Astro CLI:
```suggestion
To uninstall the Astro CLI on Windows:
```

2022-05-25 15:18 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +1. Delete `astro.exe`.
```suggestion
2. Delete the `astro.exe` file from your machine.
```

2022-05-25 15:18 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +To uninstall the Astro CLI, run the following command:
```suggestion
To uninstall the Astro CLI on Linux, run the following command:
```

2022-05-25 15:20 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +- You used a pre-1.0 version of the Astro CLI. For these versions, the CLI executable was `astrocloud`.
```suggestion
- You're currently using the `astrocloud` CLI executable.
```

2022-05-25 15:23 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +
```suggestion

For more information on Astro CLI v1.0.0, see [Astro CLI Release Notes](cli-release-notes.md).

```

2022-05-25 15:24 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +2. Delete `astrocloud.exe`.
```suggestion
2. Delete the `astrocloud.exe` file from your machine.
```

2022-05-25 15:30 UTC, paolaperaza commented on astro/cli/quickstart.md
> +## Step 1: Install the Astro CLI
if we DO keep these instructions, check out my comments in Configure CLI and let's bring those changes here

2022-05-25 15:33 UTC, paolaperaza commented on astro/cli/quickstart.md
> +This command builds your project and spins up 3 Docker containers on your machine, each for a different Airflow component:
```suggestion
This command builds your project and spins up 4 Docker containers on your machine, each for a different Airflow component:
```

2022-05-25 15:36 UTC, paolaperaza commented on astro/cli/quickstart.md
> +The Astro CLI is the easiest way to run Apache Airflow on your machine. By the end of this quickstart, you'll be able to run an Airflow project on your local machine with just a few commands.
```suggestion
The Astro CLI is an open source command line for modern data orchestration. It is the easiest way to run Apache Airflow on your machine. By the end of this quickstart, you'll have an Airflow environment running locally with just a few commands. From there, you can start building your project with your own DAGs, dependencies, and tests.
```

Once we finish up this round of reviews, I actually want to review this section again and think about other ways we can talk about our value add specifically and WHY this is the best experience (e.g. mention Astro Runtime)

2022-05-25 15:40 UTC, paolaperaza commented on astro/cli/quickstart.md
> +- If you're ready to deploy your project to a production environment on Astro, see [Deploy Code](deploy-code.md).
This is great @jwitz. I think we can actually make this a _little_ more comprehensive by:

- Reworking Step 5 to be "Access the Airflow UI" to get the first "aha" moment, but no DAGs there yet...
- Adding Step 6: Push DAGs Locally (astro dev start, talk about the example DAGs that we ship with)
- Adding Step 7: See DAGs in Airflow UI (see your DAGs! you can see logs, modify task state, do whatever you want)

2022-05-25 15:40 UTC, paolaperaza commented on astro/cli/quickstart.md
> +## Next Steps
Let's also link out to "Test and Troubleshoot Locally" doc

2022-05-25 16:47 UTC, jwitz commented on astro/cli/configure-cli.md
> +1. Remove the existing `astro.exe` file on your machine.
There should only be one of these on their machine at the time, I think adding this extra line will be more confusing than clarifying

2022-05-25 17:23 UTC, jwitz commented on astro/cli/quickstart.md
> +The Astro CLI is the easiest way to run Apache Airflow on your machine. By the end of this quickstart, you'll be able to run an Airflow project on your local machine with just a few commands.
That's cool, but let's try to focus that information in our Overview doc and keep the quickstart pointed. They should see the value of the CLI through how easy the quickstart is, not by how much detail we include in the docs.

2022-05-25 17:25 UTC, jwitz commented on astro/cli/quickstart.md
> +## Step 1: Install the Astro CLI
There's more minimal information here about the install, for example I excluded info about installing a specific version. For a quickstart I think it's important to have a self-contained doc. We can then send this doc to a prospect or really anyone without them having to interact with any other docs or get in the weeds with configuration.

2022-05-25 17:43 UTC, jwitz commented on astro/cli/quickstart.md
> +- If you're ready to deploy your project to a production environment on Astro, see [Deploy Code](deploy-code.md).
The DAGs will be there be default though, right? We can give guidance on how to see those DAGs in Step 5 and what they do, but I don't think this step process is equivalent to what a user will experience.

2022-05-25 17:48 UTC, jwitz commented
@paolaperaza Lots of updates coming your way! I accepted most suggestions, with the exception of some of the high level comments for the quickstart. Left replies where that was the case.

2022-05-25 20:16 UTC, jwitz commented on astro/cli/configure-cli.md
> +- [Docker Engine](https://docs.docker.com/engine/install/) (v0.13.1 or higher).
```suggestion
- [Docker Engine](https://docs.docker.com/engine/install/) (v0.18.9 or higher).
```

2022-05-25 20:53 UTC, jwitz commented on astro/cli/quickstart.md
> +- [Docker Engine](https://docs.docker.com/engine/install/) (v0.13.1 or higher).
```suggestion
- [Docker Engine](https://docs.docker.com/engine/install/) (v0.18.9 or higher).
```

2022-05-25 20:53 UTC, jwitz commented on astro/cli/configure-cli.md
> +#### Prerequisites
@kwcanuck I adapted your CLI instructions update for this PR, could you please review this Windows setup to make sure I captured all of the changes that you and Constance discussed? Feel free to ignore the rest of the PR, thanks!

2022-05-26 04:04 UTC, paolaperaza approved these changes
Final comments here @jwitz ! Give them a look and feel free to merge whenever we're ready.

2022-05-26 04:04 UTC, paolaperaza commented on astro/cli/quickstart.md
> +Once you install the CLI, there are a few different paths you can take:
```suggestion
Once you install the CLI and have an Astro project running locally, you can:
```

2022-05-26 04:04 UTC, paolaperaza commented on astro/cli/quickstart.md
> +- If you're ready to deploy your project to a production environment on Astro, see [Deploy Code](deploy-code.md).
```suggestion
- To write and test your own DAGs locally and configure your local Airflow environment, see [Develop Project](develop-project.md).
- To view logs, set up unit tests for your DAGs, or troubleshoot your local Airflow environment, see [Test and Troubleshoot Locally](test-and-troubleshoot-locally.md).
- To deploy DAGs to an environment managed by Astronomer, see [Deploy Code](deploy-code.md). If you're not a customer but might be interested in Astro, [reach out to us](https://www.astronomer.io/get-started).
- To learn more about the available commands in the CLI, see the [CLI Command Reference](cli/reference.md) or run `astro help`.
```

2022-05-26 04:04 UTC, paolaperaza commented on astro/cli/quickstart.md
> +- If you're ready to deploy your project to a production environment on Astro, see [Deploy Code](deploy-code.md).
Rephrase/re-ordered some of these but I think LGTM

2022-05-26 04:06 UTC, paolaperaza commented on astro/cli/configure-cli.md
> +1. Go to the [**Releases** page of the Astro CLI GitHub](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and CPU architecture, download one of the `.zip` file
Fair enough

2022-05-26 04:08 UTC, paolaperaza commented on astro/cli/quickstart.md
> +- If you're ready to deploy your project to a production environment on Astro, see [Deploy Code](deploy-code.md).
Yes I think this is fine - for some reason I actually had missed the `astro dev start` step and thought that we had skipped over it. Once a user runs that command, they should see example DAGs yes so I think let's keep it there for now

2022-05-26 04:08 UTC, paolaperaza commented on astro/cli/quickstart.md
> +The Astro CLI is the easiest way to run Apache Airflow on your machine. By the end of this quickstart, you'll be able to run an Airflow project on your local machine with just a few commands.
Agreed on having the crux of that info in `Overview` instead of here

2022-05-26 12:09 UTC, kwcanuck commented on astro/cli/configure-cli.md
> +3. Add the filepath for the directory containing `astro.exe` as a PATH environment variable. For example, if `astro.exe` was stored in `C:\Users\username\astrocloud.exe`, you would add `C:\Users\user
This text doesn't match what is provided in the updated `install-cli.md` file. The text should be consistent. What file should be updated?

2022-05-26 12:12 UTC, kwcanuck commented on astro/cli/configure-cli.md
> +#### Prerequisites
@jwitz the procedures do not currently match at all. For consistency, the procedures should be identical. I recommend copying my revision, or updating install-cli.md in the `Clarify-Windows-CLI-Installation-Instructions-(344)` branch to match your content.

2022-05-26 13:23 UTC, sunkickr commented on astro/cli/configure-cli.md
> +1. Go to the [**Releases** page of the Astro CLI GitHub repository](https://github.com/astro-projects/astro-cli/releases). Based on your desired CLI version and the CPU architecture of your machine,
Yes, once Astro CLI is released their won't be a command to install on windows. Windows users will need to download the binary from this page https://github.com/astro-projects/astro-cli/releases

2022-05-26 13:24 UTC, sunkickr commented on astro/cli/configure-cli.md
> +3. Add the filepath for the directory containing `astro.exe` as a PATH environment variable. For example, if `astro.exe` was stored in `C:\Users\username\astrocloud.exe`, you would add `C:\Users\user
@jwitz what does if `astro.exe` was stored in `C:\Users\username\astrocloud.exe` mean? why are we mentioning astrocloud here?

2022-05-26 13:33 UTC, sunkickr commented on astro/cli/configure-cli.md
> +4. Add the filepath for the directory containing the new `astro.exe` as a PATH environment variable. For example, if `astro.exe` was stored in `C:\Users\username\astrocloud.exe`, you would add `C:\Us
should this be `C:\Users\username\astro.exe`

2022-05-26 13:39 UTC, sunkickr commented on astro/cli/configure-cli.md
> +If you manually updated the `.astrocloud/config.yaml` file of an existing Astro project:
They need to run astro dev init regardless of if they manually updated the `.astrocloud/config.yaml`

2022-05-26 13:40 UTC, sunkickr commented on astro/cli/configure-cli.md
> +    If the CLI prompts you about whether you want to create a project in a non-empty directory, enter `Yes`. The CLI will only create files that aren't yet in your directory. In this case, the only f
it also creates `./astro/test_dag_integrity_default.py`

2022-05-26 13:40 UTC, sunkickr commented on astro/cli/configure-cli.md
> +If you manually updated the `.astrocloud/config.yaml` file of an existing Astro project:
Users also need to run `astro dev init` if they are moving from astro v0 to astro v1

2022-05-26 17:16 UTC, jwitz commented on astro/cli/configure-cli.md
> +3. Add the filepath for the directory containing `astro.exe` as a PATH environment variable. For example, if `astro.exe` was stored in `C:\Users\username\astrocloud.exe`, you would add `C:\Users\user
Typo on the `astrocloud` front, but now I'm wondering about whether we're adding `astrocloud.exe` or its directory as the PATH

2022-05-26 17:18 UTC, jwitz commented on astro/cli/configure-cli.md
> +#### Prerequisites
@kwcanuck There are some details with the CLI v1.0.0 installation that have changed from previous versions, such as where you download the CLI from. I updated these instructions to match your PR in terms of details related to running the executable, but some steps had to change for this latest release

2022-05-26 22:22 UTC, sunkickr approved these changes

2022-05-26 23:53 UTC, merged