Improve Upgrade Astro Runtime doc
astronomer/docs pull request #712
Opened 2022-05-20 17:00 UTC by paolaperaza

Resolves: #638

This PR addresses a few things:

- Adds more guiding language to the `Overview` with general considerations for Astro Runtime upgrades
- Adds a new `Prerequisites` section
- Adds a new step to verify local upgrade in the Airflow UI
- Makes references to `Dockerfile` consistent
- Adds screenshots of Airflow UI both locally and on Astro (since they're different)
- Fixes inconsistent references to Astro Runtime 5

2022-05-20 22:05 UTC, jwitz requested changes
Thanks for this PR @paolaperaza ! I left some comments and questions throughout, so requesting changes in case there's anything we should go over together.

2022-05-20 22:05 UTC, jwitz commented on astro/upgrade-runtime.md
> +Once you've tested your new Astro Runtime version locally, upgrade your Deployment on Astro to that version. To do so, run:
```suggestion
To push your upgraded project to an Astro Deployment, run:
```

2022-05-20 22:05 UTC, jwitz commented on astro/upgrade-runtime.md
> +This command will prompt you to select the Deployment you want to upgrade. Then, it will build your Astro project with your new version of Astro Runtime and push it to your Deployment on Astro.
```suggestion
For more information about deploying project code to Astro, see [Deploy Code](deploy-code.md).
```
This info was duplicative of what's in Deploy Code, and I also think that the CLI does a good enough job of showing what the user needs to do to finish the deploy.

2022-05-20 22:05 UTC, jwitz commented on astro/upgrade-runtime.md
> +## Step 4: Confirm Your Upgrade
```suggestion
## Step 4: Confirm Your Upgrade on Astro
```

2022-05-20 22:05 UTC, jwitz commented on astro/upgrade-runtime.md
> +Astro Runtime 5 is based on Airflow 2.3 includes changes to the schema of the Airflow metadata database. When you first upgrade to any Runtime 5 version, consider the following:
```suggestion
Astro Runtime 5, based on Airflow 2.3, includes changes to the schema of the Airflow metadata database. When you first upgrade to Runtime 5, consider the following:
```

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +New versions of Astro Runtime are released regularly to support new features from both Astro and Apache Airflow. To take advantage of new functionality, as well as bug and security fixes, we recommen
Fair enough!

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +New versions of Astro Runtime are released regularly to support new features from both Astro and Apache Airflow. To take advantage of new functionality, as well as bug and security fixes, we recommen
Good question, not sure - let's discuss today

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +Follow this guide to upgrade the Astro Runtime version of a local Airflow environment and/or an Astro Deployment. You can use these steps to upgrade to any major, minor, or patch version of Astro Run
```suggestion
Follow this guide to upgrade Astro Runtime locally or for a Deployment on Astro. You can use these steps to upgrade to any major, minor, or patch version.
```

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +- We strongly recommend testing new versions of Astro Runtime locally before upgrading a Deployment on Astro.
Hm I actually do think we should keep it as a product "guideline" - the instructions below are steps, but I'd actually like to add this additional color just to enforce steering people in the right direction

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +Follow this guide to upgrade the Astro Runtime version of a local Airflow environment and/or an Astro Deployment. You can use these steps to upgrade to any major, minor, or patch version of Astro Run
Hm I don't wanna say a `local Astro project` - I think we've discussed this! The Astro project is a set of files that just "is" - it's just either running in a local Airflow environment or deployed to Astro.

I do agree the wording wasn't amazing though so I simplified a bit

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +- If a version of Astro Runtime includes changes to the schema of the metadata database, the upgrade may take longer than usual. During this time, tasks will continue to run but new tasks will not be
Yea this is a good call

2022-05-23 13:42 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +    ```
Fair enough - agreed!

2022-05-23 13:46 UTC, paolaperaza commented
Thanks for the review @jwitz ! Applied almost all of your suggestions and left a couple of comments for discussion. LMK what you think.

2022-05-23 14:40 UTC, jwitz approved these changes
Final few comments, but LGTM!

2022-05-23 14:40 UTC, jwitz commented on astro/upgrade-runtime.md
> +Follow this guide to upgrade the Astro Runtime version of a local Airflow environment and/or an Astro Deployment. You can use these steps to upgrade to any major, minor, or patch version of Astro Run
Just removed "local" from my suggestion and now I think it works!

2022-05-23 14:40 UTC, jwitz commented on astro/upgrade-runtime.md
> +- We strongly recommend testing new versions of Astro Runtime locally before upgrading a Deployment on Astro.
If you want to enforce this even more, I think it's probably better to put it directly in the step as opposed to this considerations section. This isn't like the other considerations in the list because we're telling the user to do something as opposed to providing contextual information about product/ support. Could see people glossing over the Overview and jumping straight to steps because they assume it's all contextual information and nothing prescriptive.

2022-05-24 04:31 UTC, paolaperaza commented on astro/upgrade-runtime.md
>  To test your upgrade locally:
```suggestion
We strongly recommend testing new versions of Astro Runtime locally before upgrading a Deployment on Astro. 

To test your upgrade locally:
```

2022-05-24 04:31 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +Follow this guide to upgrade Astro Runtime locally or for a Deployment on Astro. You can use these steps to upgrade to any major, minor, or patch version.
```suggestion
Follow this guide to upgrade Astro Runtime locally or for a Deployment on Astro. You can use these steps to upgrade to any major, minor, or patch version of Astro Runtime.
```

2022-05-24 04:31 UTC, paolaperaza commented on astro/upgrade-runtime.md
> +Follow this guide to upgrade the Astro Runtime version of a local Airflow environment and/or an Astro Deployment. You can use these steps to upgrade to any major, minor, or patch version of Astro Run
I also don't wanna say "an astro project" OR a "deployment" - it's both your project, just one is local and one is on astro. i did improve wording here tho.

2022-05-24 04:40 UTC, paolaperaza commented
Merging! Thanks @jwitz ✅

2022-05-24 04:40 UTC, merged