Add new dev cmds to Software CLI Reference guide
astronomer/docs pull request #751
Opened 2022-05-31 21:28 UTC by sunkickr

This PR adds documentation for astro dev parse, pytest, and restart to the software CLI reference guide

2022-06-01 02:56 UTC, paolaperaza requested changes
@sunkickr A few questions back to you actually on functionality/differences between Astro and Software on these - lemme know what you think and I'll take another pass

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +This command requires Astro Runtime version `4.1.0`+ or for `pytest` to be present in your `requirments.txt` file. For more information, see [Astro Runtime Release Notes](https://docs.astronomer.io/a
```suggestion
This command requires the [pytest](https://docs.pytest.org/en/7.1.x/contents.html) package. To install it to your Astro project, add `pytest` to your `requirements.txt` file.
```

@sunkickr Do we actually need `pytest` for this parse command? If so, I assume we want to scrap this Runtime note and just tell people to add `pytest`. And no expected issues on that with AC?

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +This command requires Astro Runtime version `4.1.0`+ or for `pytest` to be present in your `requirments.txt` file. For more information, see [Astro Runtime Release Notes](https://docs.astronomer.io/a
Looks like this requirement isn't listed for Astro: https://docs.astronomer.io/astro/cli-reference/astrocloud-dev-parse

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +:::
Same thing here

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +Run unit tests for your data pipelines on Astro with `pytest`, a testing framework for Python. When you run this command, the Astro CLI creates a local Python environment that includes your DAG code,
```suggestion
Run unit tests for your data pipelines with `pytest`, a testing framework for Python. When you run this command, the Astro CLI creates a local Python environment that includes your DAG code, dependencies, and Astronomer Certified Docker image. The CLI then runs any pytests in the `tests` directory of your Astro project and shows you the results of those tests in your terminal.
```

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +Stop your Airflow environment, rebuild your Astronomer project into a Docker image, and restart your Airflow environment with the new Docker image.
```suggestion
Stop your Airflow environment, rebuild your Astro project into a Docker image, and restart your Airflow environment with the new Docker image.
```

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +This command can be used to rebuild an Astronomer project and run it locally. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
```suggestion
This command can be used to rebuild an Astro project and run it locally. For more information, read [Develop and Run a Project Locally](develop-project.md#build-and-run-a-project-locally).
```

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +`astro dev pytest <pytest-filepath>` to run specfic Pytests on your DAGs. use `<pytest-filepath>` to specify a specific test.
```suggestion
`astro dev pytest <pytest-filepath>` to run specfic Pytests on your DAGs. Use `<pytest-filepath>` to specify a specific test. 
```

2022-06-01 02:56 UTC, paolaperaza commented on software/cli-reference.md
> +
Any reason these flags are different than in Astro CLI docs? I know it's mentioned up top, but do we not add `<pytest-filepath>` too?

<img width="862" alt="image" src="https://user-images.githubusercontent.com/31111752/171318661-10f828b0-2e16-41ab-bac0-9536d13a0a10.png">

2022-06-01 03:01 UTC, sunkickr commented on software/cli-reference.md
> +This command requires Astro Runtime version `4.1.0`+ or for `pytest` to be present in your `requirments.txt` file. For more information, see [Astro Runtime Release Notes](https://docs.astronomer.io/a
if you have the right runtime image you don't need pytest. if you don't have the right runtime image you do need pytest

2022-06-01 15:51 UTC, sunkickr commented on software/cli-reference.md
> +This command requires Astro Runtime version `4.1.0`+ or for `pytest` to be present in your `requirments.txt` file. For more information, see [Astro Runtime Release Notes](https://docs.astronomer.io/a
we added pytest to runtime so users would not need to add pytest to requirements

2022-06-02 14:54 UTC, jwitz commented on software/cli-reference.md
> +This command requires Astro Runtime version `4.1.0`+ or for `pytest` to be present in your `requirments.txt` file. For more information, see [Astro Runtime Release Notes](https://docs.astronomer.io/a
Does the CLI have error handling for this? Ie if someone runs the command before Runtime 4.1.0, the CLI tells them what went wrong and how to get `pytest`? If so, we should remove this note and always assume that a user is running latest.

2022-06-02 15:02 UTC, jwitz commented
@sunkickr I moved this PR to https://github.com/astronomer/docs/pull/759 because I can easily merge it into v0.28 versioned docs from there. Also made some quick changes here so that it's hopefully ready to merge

2022-06-02 15:02 UTC, closed without merging