Email alerts guide rewrite
astronomer/docs pull request #77
Opened 2020-11-18 23:46 UTC by jwitz

Resolves issue https://github.com/astronomer/issues/issues/2204. This was originally written as part of a writing exercise during the interview process, so there might be some sections that are technically vague or inaccurate (in terms of the language used). Hoping PR lets me practice integrating feedback via GitHub while also resulting in a great doc!

2020-11-19 01:38 UTC, danielhoherd requested changes
Looking good! Not quite there yet, but great progress!

2020-11-19 01:38 UTC, danielhoherd commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_PASSWORD={Your SendGrid API Key from step 3}
There is no step 3. This step also talks about an "API key from step 3", but that step seems to be missing.
https://github.com/astronomer/docs/blob/b9233eda591ce99b6631e1b6786140ef93059e17/cloud/stable/04_customize-airflow/04_airflow-alerts.md

2020-11-19 01:38 UTC, danielhoherd commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
>    title = "TEST MESSAGE: THIS IS A MODIFIED TEST"
Python is normally indented by 4 spaces, so we should make sure the markdown rendered view shows 4 spaces of indentation. It currently shows one space of indentation.

2020-11-19 01:38 UTC, danielhoherd commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Because you’re only sending emails for internal administrative purposes, a single sender identity is sufficient for integrating with Astronomer. The email address you verify here is used as the sende
Can we please try to enforce normal single quotes `'` instead of nonstandard quotes like `’`. If these whatever-else-they-are quotes end up in code snippets they could cause problems.

2020-11-19 01:38 UTC, danielhoherd commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowDeploymentUnhealthy` | Airflow deployment is unhealthy or not completely available. |
I've noticed that our tables are messily formatted. It would be great if we could enforce a formatting of the tables, which is possible if we add the `prettier` pre-commit hook. If this is something we want to do I can do this in a separate PR because it'll cause a huge number of other markdown formatting changes (272 files changed, which could save us a LOT of manual formatting work). Otherwise, let's clean these up manually or by using some other markdown formatter like a vscode plugin or whatever.

2020-11-19 23:32 UTC, paolaperaza requested changes
@jwitz Just threw you a bunch of comments! Super appreciate you digging in here - some of the comments were product-specific stuff, so zero worries - and then some were copy/language that you're definitely free to take/leave and play around with.

Go ahead and dig back in here and I'll give it another look tomorrow! Thanks again - you've inherited a poorly-written doc with this one so any changes we make will be a huge improvement :)

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Click `Update` to save the configuration and redeploy to propagate to your deployment.
```suggestion
Select **+ Add ** to save your Environment Variables and **Deploy Changes** to push them to your Airflow Deployment. 
```

Maybe add screenshot of the Env Var view? 
![image](https://user-images.githubusercontent.com/31111752/99734805-6fd84100-2a91-11eb-9341-9b75b31e4612.png)

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Click `Update` to save the configuration and redeploy to propagate to your deployment.
I'd actually add a note in here as well that you can make these Env Vars secret! Especially since one of them is an SMTP password that a Deployment Admin may not want others to see. This is a relatively new feature, but we actually added it largely because users complained about having these SMTP creds in plain-text.

More info about making Env Vars secret here: https://www.astronomer.io/docs/cloud/stable/deploy/environment-variables/

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Prerequisite**: This setup requires an AWS account and use of the [AWS Management Console](https://aws.amazon.com/console/).
We should standardize how we present "Prerequisites" - I think other docs usually have it in some header and then a bullet point list - what do you think?

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Go to: `AWS Console` > `Simple Email Service` > `Email Addresses` and add the email addresses you want to deliver mail to.
```suggestion
Go to: **AWS Console** > **Simple Email Service** > **Email Addresses** to add and verify the email addresses you want to receive alerts to.
```

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +From here, open the account each email address you specified and verify them through the email sent by Amazon.
Hm awk sounding sentence here - what are we asking the user to do?

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In the AWS Console, go to `Simple Email Service` > `SMTP Settings` and use the `Create My SMTP Credentials` button to generate a username and password. This will look similar to an access and secret
```suggestion
In the AWS Console, go to **Simple Email Service** > **SMTP Settings** and use the **Create My SMTP Credentials** button to generate a username and password. This will look similar to an access and secret access key. Write down this username and password for later, as well as the Server Name and Port.
```

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Note:** You won't be able to access these values again, so consider storing them in a password manager.
```suggestion
> **Note:** You won't be able to access these values again, so consider storing them in a password manager.
```

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Note:** You won't be able to access these values again, so consider storing them in a password manager.
^ For "Notes", we've mostly standardized to almost always be in this format:

```
> **Note:**
```

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_HOST={The address of AWS server you chose in step 3. For instance, in US-EAST-1 this would be email-smtp.us-east-1.amazonaws.com}
Hm this is a bit too long - I'd say keep these brackets simple and if we need to explain more things, add 'em to the bottom. Here, let's help the user on the expected syntax and length of the "SMTP Host".

So, `{my.smtp.host}` - I think an actual example would be {smtp.sendgrid.net}

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +## Subscribe to Deployment Alerts
```suggestion
## Subscribe to Deployment Alerts on Astronomer
```

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In Astronomer’s UI, you can subscribe to deployment-level alerts in the `Alerts` tab. These alerts tell you how your deployments are performing across the entire platform. For instance, it might tell
This has changed! Alerts are now in **Deployment** > **Settings** > **Email Alerts**

I would add a screenshot - 

![image](https://user-images.githubusercontent.com/31111752/99735638-f5102580-2a92-11eb-9650-ef678fd70c5d.png)

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowDeploymentUnhealthy` | Airflow deployment is unhealthy or not completely available. |
@danielhoherd Yes, I totally agree - I've run into that problem a few times and tbh didn't quite know how to best approach it. If you're familiar with the `prettier` pre-commit hook, I'm down to try it? Or a VSCode plugin as well.

@jwitz Maybe you know of something? Will defer to you both!

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +When you subscribe to the AirflowSchedulerUnhealthy Alert in Astronomer’s UI, an alert checks to see if the scheduler is heartbeating every 5 seconds. If the scheduler stops heartbeating for more tha
A bit weird phrasing here - the alert itself doesn't "check", but it "fires" if x thing happens. I don't mind the OG description here? Feel free to play with it though

2020-11-19 23:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Need to customize an alert?** Customers with Enterprise-level Astronomer can modify any Astronomer-released alert according to their organization’s needs.
Oh! We can delete this, since this doc is Cloud-only now. The stuff for Enterprise doc is still relevant, though we might want to chat about how we want to handle that.

In a recent Astro release, we added the ability for Enterprise users to customize Prometheus alerts - https://github.com/astronomer/issues/issues/1764

2020-11-20 14:38 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_PASSWORD={Your SendGrid API Key from step 3}
Whoops, step 3 is copied in now. Let me know what you think of my nested step formatting - Markdown isn't great with nested steps, and I could use HTML to make those appear nicely on the website.

2020-11-20 14:51 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +# Monitor Airflow Deployments with Alerts
I added an Overview header just below this. I saw on some other docs that you have the h1 title for the page followed by a brief Overview section, so I think it makes sense to replicate that structure here.

2020-11-20 15:05 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +## Configure a Simple Mail Transfer Protocol Service for Task Alerts
In another commit, I changed the title to 'Subscribe to Task-Level Alerts'. Definitely easier to understand and more consistent with the Deployment-level language.

2020-11-20 15:06 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +* [DAG and Task-level alerts](#configure-a-simple-mail-transfer-protocol-service-for-task-alerts) use a Simple Mail Transfer Protocol (SMTP) service to alert you via email when something you specify
Did this, but with an Oxford Comma ;)

2020-11-20 15:09 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +## Subscribe to Deployment Alerts
Resolved in a separate commit (made links to title consistent elsewhere)

2020-11-20 15:20 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Because you’re only sending emails for internal administrative purposes, a single sender identity is sufficient for integrating with Astronomer. The email address you verify here is used as the sende
Purged all of these quotations in a separate commit. I'll keep an eye out for any more of these as I'm continuing to edit our docs.

2020-11-20 17:31 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In Astronomer’s UI, you can subscribe to deployment-level alerts in the `Alerts` tab. These alerts tell you how your deployments are performing across the entire platform. For instance, it might tell
Added a screen shot and updated the text to be accurate!

2020-11-20 17:37 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In your Astronomer deployment, go to `Deployments` > `Configure` > `Env Vars` and add the following variables:
Sounds good! Making notes on this for the style guide 👍

2020-11-20 17:39 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Prerequisite**: This setup requires an AWS account and use of the [AWS Management Console](https://aws.amazon.com/console/).
I'm not a huge fan of one-bullet lists, but I can see putting it as a header since it's similar in scope to the build steps we have, which are also in headers.

2020-11-20 17:55 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +The following topics contain setup steps for two free and popular SMTP services:
I think we could go h1=guide, h2+ = topic. I like topic because it can be used to describe anything from setup steps to considerations, ie. it's content-agnostic. Whatever we decide on, I agree - let's keep it standard so people know what they expect when clicking on one of these links.

2020-11-20 17:57 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowDeploymentUnhealthy` | Airflow deployment is unhealthy or not completely available. |
I added a prettier plugin to Atom which runs every time I save a document. I think it looks better now!
<img width="878" alt="Screen Shot 2020-11-20 at 10 56 49 AM" src="https://user-images.githubusercontent.com/74574233/99833355-17e81b80-2b1f-11eb-8bc2-bb63bf5bf2ca.png">

2020-11-20 18:08 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Need to customize an alert?** Customers with Enterprise-level Astronomer can modify any Astronomer-released alert according to their organization’s needs.
Removed the Prometheus stuff. Yeah, let's talk about what language we want to use when referencing Enterprise stuff in Cloud docs. Probably a discussion that extends beyond this doc.

2020-11-20 18:10 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +When you subscribe to the AirflowSchedulerUnhealthy Alert in Astronomer’s UI, an alert checks to see if the scheduler is heartbeating every 5 seconds. If the scheduler stops heartbeating for more tha
Yeah, I think I was operating on some pre-hire misunderstandings here. Reverted to the OG wording.

2020-11-20 18:20 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +From here, open the account each email address you specified and verify them through the email sent by Amazon.
Forgot the word for inbox here -___- clarified in another commit.

2020-11-20 18:26 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_HOST={The address of AWS server you chose in step 3. For instance, in US-EAST-1 this would be email-smtp.us-east-1.amazonaws.com}
I'd like to keep any user-provided content consistent with how we format it for things like their username and password, so I went with {Your SMTP host}.

2020-11-20 20:17 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +The following topics contain setup steps for two free and popular SMTP services:
Spoke with Paola over Zoom: I'll refer to any linkable heading as 'topics' going forward.

2020-11-20 21:02 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Prerequisite**: This setup requires an AWS account and use of the [AWS Management Console](https://aws.amazon.com/console/).
Updated to an h4 heading!

2020-11-20 21:03 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Click `Update` to save the configuration and redeploy to propagate to your deployment.
Added screenshots and Secret? info for both SMTP setups.

2020-11-20 21:05 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Prerequisite**: To perform this setup, you need to have built error notifications as described in the [Error Notifications in Airflow](https://www.astronomer.io/guides/error-notifications-in-airflo
I'm hesitant to have identical information to the guide we're linking out to. I agree, though, that this isn't much of a prereq, so I moved it into the overview itself.

2020-11-20 21:05 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
>    title = "TEST MESSAGE: THIS IS A MODIFIED TEST"
Sounds good! Updated the code sample below.

2020-11-20 23:56 UTC, paolaperaza requested changes
Final few comments @jwitz !!

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +# Monitor Airflow Deployments with Alerts
@jwitz I think we don't do H1s in many places - I'd honestly just scrap this header. I'm feeling like the title tells the user what this whole thing is about and the overview walks through the two biggest topics it covers.
WDYT?

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +#### 1. [Create a New Account](https://signup.sendgrid.com)
```suggestion
#### 1. [Create a SendGrid Account](https://signup.sendgrid.com)
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +a) In SendGrid, go to Email API > Integration Guide. Follow the steps to generate a new API key using SendGrid's Web API and cURL.
```suggestion
a) In SendGrid, go to **Email API** > **Integration Guide**. Follow the steps to generate a new API key using SendGrid's Web API and cURL.
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +#### 4. Add SendGrid Credentials to your Astronomer Deployment
```suggestion
#### 4. Add SendGrid Credentials to your Airflow Deployment
```

Weirdly enough, we say `Airflow Deployment` - if you have to specify, I'd say `Airflow Deployment on Astronomer` or `Local Airflow Deployment`

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In your Astronomer Deployment on Astronomer's UI, go to the **Variables** tab for your deployment and add the following Environment Variable using the **+Add** button:
```suggestion
Now, navigate to your Airflow Deployment in the Astronomer UI. In the **Variables** tab, add the following Environment Variables using the **+Add** button:
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_PASSWORD={Your SendGrid API Key from step 3}
```suggestion
AIRFLOW__SMTP__SMTP_PASSWORD={YOUR_SMTP_PASSWORD}
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +AIRFLOW__SMTP__SMTP_MAIL_FROM={Your SendGrid email sender from step 2}
```suggestion
AIRFLOW__SMTP__SMTP_MAIL_FROM={email@astronomer.io}

The SendGrid API Key from Step 3 will be your `SMTP_PASSWORD` above and your SendGrid Email Sender from Step 2 should be set as your 'SMTP_MAIL_FROM`.
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +To prevent unauthorized users in your Workspace from seeing sensitive information, we recommend selecting the **Secret?** checkbox for your email and password profile variables.
```suggestion
> **Note:** If you'd like to hide your SMTP password and/or email address from being visible to other Workspace users in plain-text, we recommend marking these Environment Variables as secret by checking the **Secret?** check-box on the right when you first set them. Once an Environment Variable is saved as a secret, it will no longer be visible in plain-text to any user in your Workspace. For more details, refer to ["Environment Variables on Astronomer"](https://www.astronomer.io/docs/cloud/stable/deploy/environment-variables/).
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +To prevent unauthorized users in your Workspace from seeing sensitive information, we recommend selecting the **Secret?** checkbox for your email and password profile variables.
Thoughts on this as a "note"? I do like ^this language, but can go either way on the note versus not!

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In your Astronomer Deployment on Astronomer's UI, go to the **Variables** tab for your deployment and add the following Environment Variables:
```suggestion
Now, navigate to your Airflow Deployment in the Astronomer UI. In the **Variables** tab, add the following Environment Variables using the **+Add** button:
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +To prevent unauthorized users in your Workspace from seeing sensitive information, we recommend selecting the **Secret?** checkbox for your email and password profile variables.
Apply change I suggested on secret Env Vars here too!

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +## Limit Alerts to the DAG Level
```suggestion
## Limit Alerts to the Airflow DAG Level
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +By default, email alerts configured via the `email_on_failure` param ([source](https://github.com/apache/airflow/blob/master/airflow/models/baseoperator.py)) are handled at the task level. If a handf
```suggestion
By default, email alerts configured via the `email_on_failure` param ([source](https://github.com/apache/airflow/blob/master/airflow/models/baseoperator.py)) are handled at the task level. If some number of your tasks fail, you'll receive an individual email for each of those failures.
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +In Astronomer's UI, you can subscribe to deployment-level email alerts in the Settings page for a deployment. These alerts tell you how a deployment is performing. For instance, it might tell you whe
```suggestion
In the Astronomer UI, you can subscribe to deployment-level email alerts in the **Settings** tab of your Airflow Deployment. Our platform monitors the health of your Airflow Deployment and triggers an alert if any of Airflow's core components are underperforming or if you've initiated a faulty action. For instance, you may receive an alert if your Airflow Scheduler is unhealthy, if tasks are failing at an abnormal rate, or if you've attempted to upgrade to a version of Airflow that does not match the corresponding Docker image in your Dockerfile. Unlike task-level alerts, deployment-level alerts are sent by Astronomer and do not require a separate SMTP configuration.
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
>  This alert fires when the scheduler is not heartbeating every 5 seconds for more than 3 minutes:
```suggestion
This alert fires when the Airflow Scheduler is not heart beating every 5 seconds, for more than 3 minutes:
```

2020-11-20 23:56 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Need to customize an alert?** Customers with Enterprise-level Astronomer can modify any Astronomer-released alert according to their organization's needs.
Again, I'd remove this! No need to include Enterprise here I don't think.

2020-11-20 23:59 UTC, paolaperaza commented
@jwitz Keep in mind that before we merge, you have to transfer all of your changes to the corresponding "Airflow Alerts" files in the Enterprise folder - so in `/next`, `/0.16`, etc. You should be able to make the exact same changes there for now and we can build on 'em later.

2020-11-21 00:13 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +title: "Monitor Airflow Deployments with Alerts"
I'm a big fan of action-oriented titles, so I like keeping Monitor on there. Also, if this title is in the navigation pane on the left, it might be a little redundant to see "on Astronomer" in the Astronomer docs. Come to think of it, I think we should also be explicit about "emails" on here too, since that's what people might be looking for as we enact our opt-out plans.

What about simply, "Monitor Airflow with Email Alerts"?

2020-11-21 00:15 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +## Limit Alerts to the DAG Level
We should have a bigger (style guide) discussion about when to specify something like this vs. when to trust that the reader knows what we're talking about. Given that Airflow is in the title here, I don't think it's totally necessary to have it in this title but I'm also not fussed either way.

2020-11-21 00:17 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +**Need to customize an alert?** Customers with Enterprise-level Astronomer can modify any Astronomer-released alert according to their organization's needs.
Ahh got it, misunderstood your previous comment.

2020-11-25 15:59 UTC, paolaperaza approved these changes

2020-11-26 00:33 UTC, danielhoherd approved these changes
Long live v0.14.

LGTM.

2020-11-26 01:16 UTC, danielhoherd commented
@jwitz This is a beast of a PR, and this change set probably should have been done over several PRs. For instance...

1. Fix formatting changes such as heading indentations, whitespace changes, code block stuff
2. Fix titles, section headings, etc.
3. Fix Content related to one sub-section of the documentation. EG: only fix things related to enterprise deployments in one PR, then other in other PRs.

Doing this will likely add a bit of extra work, because sections may be related to each other. For instance, links may need to be updated more than once. This extra work is just collateral damage from reducing the change set from a huge, iterative PR that is hard to grok in its entirety every time reviewers have to come back to review changes, and is an accepted bit of overhead in exchange for an improved PR workflow.

I know this because I've done beast PRs like this before. Make an effort to pay attention to your change sets in the future, and rework them down into multiple PRs if needed, just to make things easier for the people who have to verify your work. You don't want your great work to be overshadowed by the burden of reviewing it!

2020-11-26 04:33 UTC, paolaperaza commented
Merging this! Thanks a ton @danielhoherd for the review + both thoughtful and helpful feedback, and @jwitz for leading the effort here. We're only getting better from here! 🚀

2020-11-26 04:33 UTC, merged