Software 0.29 Docs Copy Edit
astronomer/docs pull request #780
Opened 2022-06-06 18:43 UTC by kwcanuck

Resolves #773

2022-06-06 22:52 UTC, jwitz requested changes
This is a fantastic edit @kwcanuck . I feel guilty requesting changes because this is technically stuff I should have caught the first time around, but I left so many comments that I think it's worth checking in again once they're resolved, specifically for the Upgrade Airflow doc.

2022-06-06 22:52 UTC, jwitz commented on software/export-task-logs.md
> +- Task logs are written to a shared directory .
```suggestion
- Task logs are written to a shared directory.
```

2022-06-06 22:52 UTC, jwitz commented on software/export-task-logs.md
> +- The Vector sidecar reads logs from the shared directory and writes them to ElasticSearch .
```suggestion
- The Vector sidecar reads logs from the shared directory and writes them to ElasticSearch.
```

2022-06-06 22:52 UTC, jwitz commented on software/export-task-logs.md
> +With this implementation, the Vector sidecars each utilize 100m cpu and 384Mi memory. More compute and memory resources are used for exporting logs with sidecars than when using a Fluentd Daemonset.
Should we use a word like "tradeoff", "disadvantage", etc here? This is the main reason that people _wouldn't_ want to implement the feature, so I wouldn't mind making it more clear that this is something to consider strongly before doing this implementation. 

If we want to keep the copy as is, perhaps we could put this in a `:::caution` note?

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +Every Astronomer build must include a `Dockerfile` that references an Astronomer Certified (AC) or Astro Runtime Docker image. AC and Astro Runtime Docker images are production-ready distributions of
Perhaps we should tag Paola on this decision, but I feel like we explain this better elsewhere in our docs, like in https://docs.astronomer.io/software/deploy-cli#overview. I'd be cool to cut out all of this information entirely and go straight to talking about the upgrade process. 

If anything, we should use this overview to explain the importance of upgrading. "Regularly upgrading your Software Deployments ensures that your Deployments stay in support and are running the most reliable, feature-rich version of Airflow available."

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +- Change the FROM statement in your project's `Dockerfile` to reference an AC or Astro Runtime image that corresponds to your current Airflow version. See [Customize Your Image](customize-image.md).
```suggestion
- Change the FROM statement in your project's `Dockerfile` to reference an Astronomer Certified (AC) or Astro Runtime image that corresponds to your current Airflow version. See [Customize Your Image](customize-image.md).
```

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
>  >
```suggestion
```
Delete the remaining `>` in this block. This also super optional setup, so maybe we can enclose this information in a `:::tip` or `:::info` box

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +An upgrade doesn't interrupt or otherwise impact your Airflow Deployment or trigger a code change - it signals to Astronomer your _intent_ to upgrade.
```suggestion
An upgrade doesn't interrupt or otherwise impact your Airflow Deployment. It only signals to Astronomer your intent to upgrade.
```

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +The Software UI and CLI only provide Airflow versions that are _later_ than the version currently running in your `Dockerfile`. For example, Airflow `1.10.7` is not available for an Airflow Deploymen
```suggestion
The Software UI and CLI only provide Airflow versions that are later than the version currently running in your `Dockerfile`. For example, Airflow `1.10.7` is not available for an Airflow Deployment running `1.10.10`.
```
This information seems like it belongs in `Available Airflow Versions`

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +Run `$ astro auth login <base-domain>` to confirm you're authenticated.
Worth having numbered steps here?

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +Copy the `Deployment ID` and run:
```suggestion
Copy the `DEPLOYMENT ID` for the Deployment you want to upgrade and run:
```

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +This command lists the available Airflow versions you can select and prompts you for a selection. For example, a user upgrading from Airflow 1.10.5 to Airflow 1.10.12 has the following options:
This code block has such old versions of Airflow and goes against our agreed stance that having long blocks of output text is a maintenance hassle.. Let's just tell people to "This command lists the available Airflow versions. Select the version of Airflow you want to upgrade to" And cut the example.

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +All 3 running Docker containers for each of the Airflow components (Webserver, Scheduler, Postgres) stop.
```suggestion
All 4 running Docker containers for each of the Airflow components (Webserver, Scheduler, Postgres, Triggerer) stop. 
```

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
>  ### 2. Choose your new Astronomer Image
We've got some inconsistent title casing across these headers. Should we just do everything in title case to make it easy to maintain?

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +2. Go to `About` > `Version`.
```suggestion
2. Go to **About** > **Version**. 
```
Because it's a UI element vs CLI text

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
> +You can cancel an Airflow Deployment upgrade at any time if you have NOT changed the Astronomer image in your `Dockerfile` and deployed it.
```suggestion
You can cancel an Airflow Deployment upgrade at any time if you haven't yet changed the Astronomer image in your `Dockerfile` and deployed it.
```

2022-06-06 22:52 UTC, jwitz commented on software/manage-airflow-versions.md
>  In the Software UI, select **Cancel** next to **Airflow Version**.
```suggestion
Using the Software UI, select **Cancel** next to **Airflow Version**.
```

2022-06-06 22:52 UTC, jwitz commented on software/namespace-pools.md
> +Pre-created namespaces provide the following benefits:
```suggestion
A pre-created namespace pool provides the following benefits:
```

2022-06-06 22:52 UTC, jwitz commented on software/namespace-pools.md
> +- It limits the cluster-level permissions your organization needs to give to Astronomer Software.  Astronomer Software requires permissions only for the individual namespaces you configure. Pre-creat
```suggestion
- It limits the cluster-level permissions your organization needs to give to Astronomer Software. Astronomer Software requires permissions only for the individual namespaces you configure. Pre-created namespaces are recommended when your organization does not want to give Astronomer Software cluster-level permissions in a multi-tenant cluster.
```

2022-06-06 22:52 UTC, jwitz commented on software/namespace-pools.md
> +- Delegate the creation of each namespace, including roles and rolebindings, to the Astronomer helm chart. This option is suitable for most Organizations.
```suggestion
- Delegate the creation of each namespace, including roles and rolebindings, to the Astronomer helm chart. This option is suitable for most organizations.
```
Please don't hate me for this.... okay so "Organizations" is an RBAC entity _only_ in Astro. So when we say organizations here, we mean the actual group of people using Astronomer instead of the system user type.

2022-06-07 11:24 UTC, kwcanuck commented on software/export-task-logs.md
> +With this implementation, the Vector sidecars each utilize 100m cpu and 384Mi memory. More compute and memory resources are used for exporting logs with sidecars than when using a Fluentd Daemonset.
@jwitz I removed _downside_ as it's jargon and might not be easily understood by users whose first language is not English.  The same concern applies to _tradeoff_. 

Caution and Info callouts should be used sparingly. In this instance, I don't think it's necessary as the information appears in a small block of text and is easily spotted. However, I enclosed the text in a caution block as a compromise. 

We should probably discuss why the callout titles ARE CAPITALIZED. I don't think this format is necessary as it's visually distracting. It could be easily addressed with a CSS tweak.

2022-06-07 11:33 UTC, kwcanuck commented on software/manage-airflow-versions.md
> +Every Astronomer build must include a `Dockerfile` that references an Astronomer Certified (AC) or Astro Runtime Docker image. AC and Astro Runtime Docker images are production-ready distributions of
@jwitz I was trying to go light with my edit and retain as much of the existing text as possible. I have taken your suggestion and eliminated most of the text and added a short introductory statement. 

You'll never get an argument from me when you recommend removing text!

2022-06-07 11:42 UTC, kwcanuck commented on software/manage-airflow-versions.md
> +Run `$ astro auth login <base-domain>` to confirm you're authenticated.
@jwitz I had the same thought! I initially tried making in a numbered task, but I wasn't happy with the formatting. I have tried again and I hope the formatting looks OK.

2022-06-07 11:52 UTC, kwcanuck commented on software/manage-airflow-versions.md
> +This command lists the available Airflow versions you can select and prompts you for a selection. For example, a user upgrading from Airflow 1.10.5 to Airflow 1.10.12 has the following options:
@jwitz I have modified the task to accommodate your edit recommendation.

2022-06-07 11:58 UTC, kwcanuck commented on software/manage-airflow-versions.md
>  ### 2. Choose your new Astronomer Image
@jwitz I have updated the titles for consistency. I think we need to have a larger discussion about titles. It's not clear to me why we are using title case and not sentence case for titles. Sentence case is a more common standard now and gives documentation a more modern appearance. It's also easier for writers to implement.

2022-06-07 12:02 UTC, kwcanuck commented on software/manage-airflow-versions.md
>  In the Software UI, select **Cancel** next to **Airflow Version**.
@jwitz the edit is correct. _Using_ is not correct. We are telling users where they should complete the action - **_in_** the Software UI.

2022-06-07 12:05 UTC, kwcanuck commented on software/namespace-pools.md
> +- Delegate the creation of each namespace, including roles and rolebindings, to the Astronomer helm chart. This option is suitable for most Organizations.
@jwitz we need to clarify the use of _Organization_ and _organization_ is our style guide. The recommendation needs to be clear and easy to implement.

2022-06-08 12:03 UTC, kwcanuck commented on software/export-task-logs.md
> +With this implementation, the Vector sidecars each utilize 100m cpu and 384Mi memory. More compute and memory resources are used for exporting logs with sidecars than when using a Fluentd Daemonset.
@jwitz the text is now enclosed in a caution annotation. This issue is resolved.

2022-06-08 12:08 UTC, kwcanuck commented on software/manage-airflow-versions.md
> +Copy the `Deployment ID` and run:
@jwitz the change has been implemented as discussed. Resolving this comment.

2022-06-08 12:25 UTC, merged