New Astro Runtime Image Doc
astronomer/docs pull request #785
Opened 2022-06-07 14:35 UTC by kwcanuck

Resolves #73.

@paolaperaza I have prepared a **VERY** preliminary draft of the Astro Runtime Image doc. You'll need to provide the missing information, or direct me to its location. Hopefully, what I have prepared is in the ballpark.

CC: @jwitz

2022-06-09 17:19 UTC, kwcanuck commented
@paolaperaza I have updated the topic to include the changes you requested. Here is some feedback:

- I need someone to provide the supported Python version for each Astro Runtime package.

- I don't recommend consolidating tables as it could make the information difficult to decipher. Discrete tables let users locate information quickly. They are also easier to create and manage.

- I don't recommend adding future looking statements to technical documentation. The removal of these statements can be missed when the functionality becomes available. Also, they can cause embarrassment if the feature or functionality is delayed or dropped. I have added the statement, but I would recommend removing it.

@jwitz I need your feedback on the **Provider Packages** table. If you recall, you were going to initiate a Slack discussion about providing detailed version information in the table. If you're buried, just provide the name of the SME who should be engaged and I'll start the conversation. Providing a list of available providers without version information seems the better solution for maintenance, but I'm not sure customers will agree!

2022-06-10 15:27 UTC, jwitz commented
@kwcanuck Let's not add version info to the provider packages. Looking at the [Runtime Dockerfile](https://github.com/astronomer/astro-runtime/blob/main/image/Dockerfile), it looks like we use the same [`constraint](https://github.com/apache/airflow#installing-from-pypi)` files published by OSS Airflow to determine what version of each of these packages we install. I'll leave it up to you as to how to communicate this information, but the bottom line is that Runtime installs the same version of these packages as you would automatically install for the equivalent OSS Airflow version.

Additionally, the package list is slightly different for Runtime vs. Certified. Let's turn this section into a bulleted list with the following packages:

- amazon 
- elasticsearch 
- celery
- google
- password
- cncf.kubernetes
- postgres
- redis
- statsd
- virtualenv
- openlineage-airflow
- astronomer-providers 

We might also want to give additional information about the last two packages because those are the main "unique" packages installed to Runtime.  Let me know if you have any other questions!

2022-06-15 12:41 UTC, kwcanuck commented
All edits discussed for the Astro Runtime image doc discussed at [the team standup 2022-06-14](https://www.notion.so/astronomerio/Docs-Team-Agenda-Weekly-5dd2e2344f194332a7066bfa57a4d83f) are now complete. Awaiting Python and Parity information.

2022-06-16 16:14 UTC, paolaperaza requested changes
A few comments here @kwcanuck - back to you! Requesting changes because I want to make sure we get the "feature" list and product framing right.

2022-06-16 16:14 UTC, paolaperaza commented on software/runtime-image-architecture.md
> +To determine the supported provider package version for a specific Astronomer Software release, see the release notes. Run the following command to determine the provider package versions that are su
```suggestion
If a release of Astro Runtime includes a change to the installed version of a provider package that is maintained by Astronomer (`astronomer-providers` or `openlineage-airflow`), that version change will be reflected in [Astro Runtime Release Notes](runtime-release-notes.md).

To determine the version of a provider package installed in your current Astro Runtime image, run:
```

I'd like to not make the "To determine the supported provider package version" statement an explicit call to action, because:

- I don't want users to filter through release notes to find versions
- We don't actually update versions in there for ALL provider packages -- just for `astronomer-providers` and `openlineage-airflow` because we maintain those
- I think this statement is informational, not actionable

Let's also make sure to actually link to release notes here

2022-06-16 16:14 UTC, paolaperaza commented on software/runtime-image-architecture.md
> +## Python Packages
```suggestion
## Python Versioning
```

This is about which version of Python is supported by which version of Astro Runtime -- nothing to do with "packages". Given that it's a versioning matrix, what are your thoughts on consolidating this table with the `Astro Runtime and Apache Airflow Parity` below?

2022-06-16 16:14 UTC, paolaperaza commented on software/runtime-image-architecture.md
> +## System Dependencies
This isn't really "System Dependencies" (i.e. packages) -- this is more `OS Distribution` that this image is built with. It will always be a type and version. Thoughts on consolidating this with the table above?

Similar to: https://docs.astronomer.io/software/version-compatibility-reference#astronomer-certified

2022-06-16 18:04 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +- The `astronomer-providers` package. This package is an open source collection of Apache Airflow providers and modules that is maintained by Astronomer. It includes deferrable versions of popular op
I don't think a `## Features` heading is helpful or necessary. They are often viewed as marketing content and skipped. It's better to leave it in the overview in the hope it is read.

2022-06-16 18:06 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +- Compatibility with the Astronomer Platform.
I have removed the content.

2022-06-16 18:19 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +- astronomer-providers
The changes have been implemented.

2022-06-16 18:31 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +To determine the supported provider package version for a specific Astronomer Software release, see the release notes. Run the following command to determine the provider package versions that are su
@paolaperaza I don't think a separate section is required. This information is in a logical location and is easy to locate. It follows related information.

2022-06-16 18:36 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +## Python Packages
@paolaperaza it's better to keep this information seperate to make it easier for users to locate quickly.

2022-06-16 18:38 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +## System Dependencies
@paolaperaza I prefer keeping this information separate.

2022-06-16 22:18 UTC, jwitz requested changes
A few more comments about the architecture details here, but I also just realized that the new doc is currently in the Software docset. I'll look at this again after you create an equivalent architecture doc in Astro.

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +- Astronomer Providers (astronomer-providers)
```suggestion
- Amazon (`apache-airflow-providers-amazon`)
- Elasticsearch (`apache-airflow-providers-elasticsearch`)
- Celery (`apache-airflow-providers-celery`)
- Google (`apache-airflow-providers-google`)
- Password (`apache-airflow-password`)
- Cloud Native Computing Foundation (CNCF) Kubernetes (`apache-airflow-cncf.kubernetes`)
- PostgreSQL (Postgres) (`apache-airflow-providers-postgres`)
- Redis (`apache-airflow-providers-redis`)
- StatsD (`apache-airflow-statsd`)
- Virtualenv (`apache-airflow-virtualenv`)
- OpenLineage with Airflow (`openlineage-airflow`)
- Astronomer Providers (`astronomer-providers`)
```

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +- Astronomer Providers (astronomer-providers)
All of these packages have links on PyPi as well, up to you whether we should hyperlink those. For example" https://pypi.org/project/openlineage-airflow/

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +The `astronomer-providers` package is a collection of Apache Airflow OSS providers and modules. The package is installed on Astro Runtime by default and is maintained by Astronomer. The package inclu
Let's move this information to before the versioning information

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +If an Astro Runtime release includes changes to an installed version of a provider package that is maintained by Astronomer (`astronomer-providers` or `openlineage-airflow`), the version change is do
```suggestion
### Provider Package Versioning

If an Astro Runtime release includes changes to an installed version of a provider package that is maintained by Astronomer (`astronomer-providers` or `openlineage-airflow`), the version change is documented in the [Astro Runtime Release Notes](/astro/runtime-release-notes.md).
```

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +| **5.0.x**                                       |       **2.3.0**                                                                        |
```suggestion
| **3.0.x**                                       |       **2.1.x**                                                                       |
| **4.0.x**                                       |       **2.2.x**                                                                    | 
| **4.1.x**                                       |       **2.2.x**                                                                    |
| **4.2.x**                                       |       **2.2.x**                                                                      | 
| **5.0.x**                                       |       **2.3.x**                                                                        | 
```
I'd also be fine with removing the patch references altogether

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +## Python Versioning
I'm not sure whether it's worth maintaining the individual patch versions of Python in this table. Python patch versions usually only contain bug fixes, and users are much more worried about minor/ major versions that have breaking changes. We should just have a single sentence here saying "All Astro Runtime images are compatible only with Python 3.9."

2022-06-16 22:18 UTC, jwitz commented on astro/runtime-version-lifecycle-policy.md
> +- [Astro Runtime Architecture](/software/runtime-image-architecture.md)
```suggestion
- [Astro Runtime Architecture](runtime-image-architecture.md)
```
We will want to have an almost identical version of the Runtime architecture doc in the Astro docset. The only difference will be that the Astro doc shouldn't have any reference to Certified.

2022-06-16 22:18 UTC, jwitz commented on software/runtime-image-architecture.md
> +For more information about the features that are available in Astro Runtime releases, see the [Astro Runtime Release Notes](/astro/runtime-release-notes).
```suggestion
For more information about the features that are available in Astro Runtime releases, see the [Astro Runtime Release Notes](https://docs.astronomer.io/astro/runtime-release-notes).
```
When you cross link to an Astro doc, you have to use the entire link. Our site considers these two docsets to be in their own uncrossable universes, so relative linking doesn't work like expected.

2022-06-16 22:19 UTC, jwitz commented on software/runtime-image-architecture.md
> +| **3.0.x**                                       |      **3.9.6**                                                                        |
Any reason we're bolding the version numbers? I'm cool with no styling, since there's nothing we need to distinguish from here.

2022-06-17 14:17 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +- Astronomer Providers (astronomer-providers)
@jwitz links added.

2022-06-17 14:18 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +The `astronomer-providers` package is a collection of Apache Airflow OSS providers and modules. The package is installed on Astro Runtime by default and is maintained by Astronomer. The package inclu
@jwitz done.

2022-06-17 14:29 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +## Python Versioning
@jwitz Done.

2022-06-17 14:31 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +| **3.0.x**                                       |      **3.9.6**                                                                        |
@jwitz this was the format in an existing doc. I thought this was the standard.

2022-06-17 14:41 UTC, kwcanuck commented
@jwitz  an equivalent architecture doc has been created in Astro. Let me know where in the TOCs these topics should be located.

All edits submitted to date have been implemented or responses have been provided.

2022-06-17 15:25 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +- Debian 11.3 or later (bullseye). See [Installing Debian 11.3](https://www.debian.org/releases/bullseye/debian-installer/).
Per conversation in standup, let's do:

- Rename this section from `System Dependencies` to `System Distribution`
- Simplify our statement here to, `Astro Runtime images are based on Debian 11.3 (Bullseye)`...

2022-06-17 15:26 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Astro Runtime supports Python package version 3.9.
```suggestion
Astro Runtime supports Python 3.9.
```

2022-06-17 15:27 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.x                                                                        |
@kwcanuck Can you add the patch Airflow versions in here? We can keep the `x` for Runtime

2022-06-17 15:37 UTC, jwitz commented on astro/runtime-image-architecture.md
> +If your organization is using Software version 0.29 or later, you can deploy Astro Runtime images. Astro Runtime includes the following features:
Possible headers:

`## Differences Between Runtime and Apache Airflow`
`## Differences Between Runtime and the Apache Airflow Docker Image`
`## Benefits of Runtime Compared to Apache Airflow`

2022-06-17 16:42 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.x                                                                        |
@paolaperaza I have returned  the patch Airflow versions.

2022-06-17 16:43 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +- Debian 11.3 or later (bullseye). See [Installing Debian 11.3](https://www.debian.org/releases/bullseye/debian-installer/).
@paolaperaza implemented as requested.

2022-06-17 16:50 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +If your organization is using Software version 0.29 or later, you can deploy Astro Runtime images. Astro Runtime includes the following features:
@jwitz and @paolaperaza I went with _Differences Between Astro Runtime and Apache Airflow_

2022-06-21 19:35 UTC, jwitz reviewed
I marked a few places where the doc is inconsistent between versions, but overall this looks great! I'd wait for @paolaperaza 's final approval though per our discussion this morning.

2022-06-21 19:35 UTC, jwitz commented on astro/runtime-image-architecture.md
> +If your organization is using Software version 0.29 or later, you can deploy Astro Runtime images. Astro Runtime includes the following features:
I see this in the Software version of the doc, but not the Astro version.

2022-06-21 19:35 UTC, jwitz commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.x                                                                        |
Again, see this in the Software doc but not the Astro doc.

2022-06-21 19:35 UTC, jwitz commented on software/runtime-image-architecture.md
> +## System Distribution
This needs to be updated per the comment in the Astro doc.

2022-06-21 19:42 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +If your organization is using Software version 0.29 or later, you can deploy Astro Runtime images. Astro Runtime includes the following features:
@jwitz added.

2022-06-21 19:43 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.x                                                                        |
@jwitz updated.

2022-06-21 19:44 UTC, kwcanuck commented on software/runtime-image-architecture.md
> +## System Distribution
@jwitz sorry, I'm not clear what edit is required here.

2022-06-27 12:52 UTC, kwcanuck commented
@paolaperaza and @jwitz all edits requested to date have been added to the doc. It's ready for final review.

2022-06-27 14:42 UTC, jwitz approved these changes
Two minor comments, otherwise LGTM! If you have time, it would also be great to update the capitalization for this PR in accordance with the new [style guidelines](https://www.notion.so/astronomerio/Astronomer-Style-Guide-5d2389d462734e149d2e66a5cf606228), but I can also handle that after the fact.

2022-06-27 14:42 UTC, jwitz commented on astro/runtime-image-architecture.md
> +The `astronomer-providers` package is a collection of Apache Airflow OSS providers and modules. The package is installed on Astro Runtime by default and is maintained by Astronomer. The package inclu
Besides the doc links, this seems identical to what's in the bulleted list. Let's either:

- Cut these paragraphs entirely and rely on the bulleted list to do the explaining. 
- Very briefly introduce the packages in the bulleted list and expand on them more in these paragraphs.

2022-06-27 15:32 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +The `astronomer-providers` package is a collection of Apache Airflow OSS providers and modules. The package is installed on Astro Runtime by default and is maintained by Astronomer. The package inclu
@jwitz I have removed the paragraph.

2022-06-28 14:15 UTC, kwcanuck commented
@paolaperaza this PR is ready for your review. Thanks!

2022-06-29 15:45 UTC, paolaperaza reviewed
@kwcanuck Take another look here -- I didn't review the Software doc. Let's make changes to Astro first and then you can apply the ones that are applicable to Software.

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +- OpenLineage with Airflow.  OpenLineage standardizes the definition of data lineage, the metadata that forms lineage data, and how data lineage data is collected from external systems. OpenLineage w
```suggestion
- Timely support for new patch, minor, and major versions of Apache Airflow. This includes bug fixes that have not been released in open source but are backported to Astro Runtime.
- Exclusive features to enrich the task execution experience, including smart task concurrency defaults and high availability configurations.
- The `astronomer-providers` package. This package is an open source collection of Apache Airflow providers and modules maintained by Astronomer. It includes deferrable versions of popular operators such as `ExternalTaskSensor`, `DatabricksRunNowOperator`, and `SnowflakeOperator`. See [Astronomer deferrable operators](deferrable-operators.md#astronomer-deferrable-operators).
- The `openlineage-airflow` package. [OpenLineage](https://openlineage.io/) standardizes the definition of data lineage, the metadata that forms lineage data, and how data lineage data is collected from external systems. This package enables data lineage on Astro. See [OpenLineage and Airflow](https://docs.astronomer.io/astro/data-lineage-concepts#openlineage-and-airflow).
- A custom logging module that ensures Airflow task logs are reliably available to the Astro data plane and Astronomer Software.
- A custom security manager that enforces user roles and permissions as defined by Astro and Astronomer Software. See [User permissions](user-permissions.md).
- A custom Airflow UI that includes links to Astronomer resources and exposes the currently running Docker image tag in the footer of all UI pages.
```

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +- OpenLineage with Airflow.  OpenLineage standardizes the definition of data lineage, the metadata that forms lineage data, and how data lineage data is collected from external systems. OpenLineage w
Ok @kwcanuck here's my list! Feel free to tweak from here but I think it's a good place to start and covers our bases -- will have to update when new executor comes out

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +For more information about the features that are available in Astro Runtime releases, see the [Astro Runtime Release Notes](https://docs.astronomer.io/astro/runtime-release-notes).
```suggestion
For more information about the features that are available in Astro Runtime releases, see the [Astro Runtime release notes](https://docs.astronomer.io/astro/runtime-release-notes). To install or upgrade Astro Runtime, see [Upgrade Runtime](https://docs.astronomer.io/astro/upgrade-runtime).
```

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Astro Runtime versions are released regularly and use [Semantic Versioning](https://semver.org/). Astronomer ships major, minor, and patch releases of Astro Runtime in the format of `major.minor.patc
```suggestion
Astro Runtime versions are released regularly and use [semantic versioning](https://semver.org/). Astronomer ships major, minor, and patch releases of Astro Runtime in the format of `major.minor.patch`.
```

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +- **Patch** versions are released for bug and security fixes that resolve unwanted behavior.
```suggestion
- **Major** versions are released for significant feature additions. This includes new major or minor versions of Apache Airflow as well as API or DAG specification changes that are not backwards-compatible.
- **Minor** versions are released for functional changes. This includes new patch versions of Apache Airflow as well as API or DAG specification changes that are backwards-compatible.
- **Patch** versions are released for bug and security fixes that resolve unwanted behavior. This includes new patch versions of `astronomer-providers` and `openlineage-airflow`.
```

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +If your organization is using Software version 0.29 or later, you can deploy Astro Runtime images. Astro Runtime includes the following features:
Honestly I'm still wanting to call this `## Features` or `## Benefits` -- I'd rather have the section have a general name to avoid anything that could be interpreted as combative and then in the introductory sentence make it a more explicit comparison.

So:

> ## Features
> 
> If your organization is using Astro, deploying Astro Runtime is required and central to the value of our product. In addition to enabling Apache Airflow on Astronomer, it includes components, configurations, and libraries that enhance performance, usability, and reliability of data orchestration:

Looking at this for inspo: https://docs.databricks.com/runtime/dbr.html. What do you guys think?

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Astro Runtime is distributed as a Debian-based Docker image. The Docker image is functionally identical to open source Apache Airflow. However, Astro Runtime includes performance and stability improv
```suggestion
Astro Runtime is distributed as a Debian-based Docker image.
```

I think let's remove this -- repetitive with our statements above?

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Astro Runtime Docker images are hosted on the Astronomer Docker registry and enable Airflow on Astro. All Astro projects require that you specify an Astro Runtime image in your Dockerfile, and all De
```suggestion
For a list of all Astro Runtime Docker images, see [Quay.io](https://quay.io/repository/astronomer/astro-runtime?tab=tags).

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +The Dockerfiles for all supported Astro Runtime images are located in the [Astronomer `astro-runtime` GitHub repository](https://github.com/astronomer/astro-runtime).
```suggestion
```

This is a private GH repo, so unfortunately cannot include it

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +An **LTS** qualifier identifies Long Term Support versions of Astro Runtime.
```suggestion
Every version of Astro Runtime correlates to an Apache Airflow version. All Deployments on Astro must run only one version of Astro Runtime, but you can run different versions of Astro Runtime on different Deployments within a given cluster or Workspace.

For a list of supported Astro Runtime versions and more information on the Astro Runtime maintenance policy, see [Astro Runtime versioning and lifecycle policy](runtime-version-lifecycle-policy.md).
```

- Added some of the versioning-specific language from below up here
- I think let's remove the LTS thing -- the versioning itself won't reflect that status, only our documentation and company policies will. I think just linking to the other doc which is dedicated to describing that in detail is fine?

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Astro Runtime Docker images are hosted on the Astronomer Docker registry and enable Airflow on Astro. All Astro projects require that you specify an Astro Runtime image in your Dockerfile, and all De
Moved this language up to the versioning section. Also went back and forth on "see this list for all" or just "this is where they're hosted" -- will defer to you.

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +- Astronomer Providers [`astronomer-providers`](https://pypi.org/project/astronomer-providers/)
I think let's add Microsoft -- https://astronomer.slack.com/archives/C01N2DM2ZS8/p1655915600729669

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +If an Astro Runtime release includes changes to an installed version of a provider package that is maintained by Astronomer (`astronomer-providers` or `openlineage-airflow`), the version change is do
```suggestion
If an Astro Runtime release includes changes to an installed version of a provider package that is maintained by Astronomer (`astronomer-providers` or `openlineage-airflow`), the version change is documented in the [Astro Runtime release notes](runtime-release-notes.md).
```

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +docker run --rm {image} pip freeze | grep apache-airflow-provider
```suggestion
docker run --rm {image} pip freeze | grep <provider>
```

- We typically use `<>` to delineate placeholder values that users should replace with their own
- Not all providers are official Apache Airflow providers, eg. our own so let's keep this general

2022-06-29 15:45 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.0                                                                        |
This is what people want to see the most -- let's bring it up in this doc ABOVE provider package section. Maybe we have this as an H3 under `## Versioning`?

2022-06-29 16:28 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +Astro Runtime supports Python 3.9. This is the only version of Python that Astro Runtime supports. If your data pipelines require an unsupported Python version, Astronomer recommends that you use the
@paolaperaza I recommend against adding _currently_. Also, the existing text is clear and concise. There is no ambiguity.

2022-06-29 16:30 UTC, kwcanuck commented on astro/runtime-image-architecture.md
> +| 5.0.x                                       |       2.3.0                                                                        |
@paolaperaza the content has been moved as requested. I would recommend keeping the heading a level 2 as it makes it easier to locate and scan within the topic.

2022-06-30 05:03 UTC, paolaperaza reviewed
@kwcanuck Thank you again! Last round here...can you go back and:

1. update the software doc with almost all of the changes we made on Astro version of the doc? Some things may not be applicable, but most should be
2. I think we need to cut out some things that are now repetitive in the lifecycle policy doc. Namely:
   - Description of Astro Runtime. Now, we can be more brief there!
   - Do we need to explain versioning there? Let's just link to new doc
   - Do we need to explain distribution there? Let's just remove and link to new doc

I'll do a final (final) pass from there! Really excited for this doc.

2022-06-30 05:03 UTC, paolaperaza commented on software/runtime-image-architecture.md
> +- The `astronomer-providers` package. This package is an open source collection of Apache Airflow providers and modules that is maintained by Astronomer. It includes deferrable versions of popular op
Update this list with Astro doc changes? Copy it over and we might need to subtract/replace docs links but I think it's mostly 1:1

2022-06-30 17:46 UTC, paolaperaza approved these changes
Thank you @kwcanuck! A few minor comments but I'll let you finish off. Just make sure to:

- Check me on the order of sections in the architecture doc. It feels a little off still but I'll defer to y ou
- Let's add back the backport policy to the versioning policy doc -- it's not in architecture so I don't want to get rid of that content

Whatever changes you make to Astro architecture just make them in Software too

2022-06-30 17:46 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +## Provider packages
Move this as an H2 above, below `### Astro Runtime and Apache Airflow parity` and above `### Provider versioning`? I see that you've grouped all the "versioning" topics together, but I suppose it's a little weird that we talk about provider versioning before we even define providers.

2022-06-30 17:46 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +On Astro, Astro Runtime exclusively supports the [Celery executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html).
```suggestion
In all local environments created with the Astro CLI, Astro Runtime runs the [Local executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/local.html). On Astro, Astro Runtime exclusively supports the [Celery executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html).
```

2022-06-30 17:46 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +Every version of Astro Runtime correlates to an Apache Airflow version. All Deployments on Astro must run only one version of Astro Runtime, but you can run different versions of Astro Runtime on dif
```suggestion
Every version of Astro Runtime correlates to an Apache Airflow version. All Deployments on Astro must run only one version of Astro Runtime, but you can run different versions of Astro Runtime on different Deployments within a given cluster or Workspace. See [Create a Deployment](create-deployment.md#create-a-deployment).
```

2022-06-30 17:46 UTC, paolaperaza commented on astro/runtime-image-architecture.md
> +To install or upgrade Astro Runtime, see [Upgrade Runtime](https://docs.astronomer.io/astro/upgrade-runtime).
This could go below table?

2022-06-30 17:46 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> -If there is a critical vulnerability in the Security Scan results that causes concern for your organization, contact [Astronomer Support](https://support.astronomer.io/).
@kwcanuck I think we have to include the Backport policy and the security scan results at the bottom no?

2022-06-30 17:47 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
>  description: Learn how Astronomer releases and maintains Astro Runtime, the core component that powers a differentiated Apache Airflow experience on Astro.
Thoughts on sidebar label being: `Astro Runtime versioning and lifecycle policy`? Sometimes I see the menu and it's misleading that we don't say this policy is specific for Runtime

2022-06-30 18:03 UTC, kwcanuck commented on astro/runtime-version-lifecycle-policy.md
> -If there is a critical vulnerability in the Security Scan results that causes concern for your organization, contact [Astronomer Support](https://support.astronomer.io/).
@paolaperaza a little overzealous with the purging. Replaced this content.

2022-06-30 18:35 UTC, merged