Provide Additional Clarity About Runtime Vulnerability Fixes
astronomer/docs pull request #786
Opened 2022-06-08 14:36 UTC by kwcanuck

Resolves #769.

To resolve issue 769, I added a new section titled _The Quay Common Vulnerabilities and Exposures Report_ to the existing section _Backport Policy for Bug and Security Fixes_ in _[Astro Runtime Versioning and Lifecycle Policy](https://docs.astronomer.io/astro/runtime-version-lifecycle-policy)_. This seemed the simplest solution.

2022-06-09 12:54 UTC, astrorfox requested changes

2022-06-09 12:54 UTC, astrorfox commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to identify high-level threats. Many of the medium and low-level vulnerabilities identifie
This is a tricky part to speak to...all dependencies are Astronomer's responsibility, even if that means we rely on others for the fix. I would tend to approach this more broadly to speak to how we work with maintainers of underlying dependencies and release updates with fixes as soon as they're reasonably available.

I would also address the fact that exploitability ratings are generic and we assess the risk in context of Astro Runtime images running in Astro, which can often reduce the risk.

2022-06-09 12:56 UTC, kwcanuck commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to identify high-level threats. Many of the medium and low-level vulnerabilities identifie
@astrorfox ca you provide some alternate text, or edit the existing statement? Alternatively, can you direct me to source material that might help with the creation of this text?

2022-06-09 13:51 UTC, kwcanuck commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to identify high-level threats. Many of the medium and low-level vulnerabilities identifie
Thanks for the quick feedback @astrorfox! Much appreciated. I have added the new text to the topic and will await feedback from @paolaperaza or @jwitz.

2022-06-09 16:04 UTC, jwitz approved these changes
LGTM from a copy standpoint ✅

2022-06-14 14:51 UTC, paolaperaza reviewed
This is great @kwcanuck - thanks. I jotted down some quick thoughts, but let's chat live today and we can decide/wrap this up. 🙏

2022-06-14 14:51 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> +When Astronomer identifies a significant Astro Runtime bug, a fix is backported to all Long Term Support (LTS) versions and the latest stable version. Astronomer recommends that you upgrade Astro Run
```suggestion
When Astronomer identifies a significant bug in Astro Runtime, a fix is backported to all Long Term Support (LTS) versions and the latest stable version. To avoid the impact of previously identified bugs, Astronomer recommends that you upgrade Astro Runtime if you are not using the latest stable version.
```

- Inconsistent of `latest, stable` vs. `latest stable`
- I'd like to avoid saying "upgrade to Astro Runtime to avoid scheduling delays and data loss" because the reality is that latest stable versions have historically had breaking changes. I think stating that impact is a bit too "severe" for what we're talking about and I'd rather keep it as a blanket statement of "to get the latest bug fixes and avoid impact of living with those bugs"

@kwcanuck Let me know what you think - we can chat quick too

2022-06-14 14:51 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> +When Astronomer identifies a significant Astro Runtime security vulnerability, a fix is backported and made available as a patch version for all stable and LTS versions in maintenance. A significant
```suggestion
When Astronomer identifies a significant security vulnerability in Astro Runtime, a fix is backported and made available as a patch version for all stable and LTS versions in maintenance. A significant security issue is defined as an issue with significant impact and exploitability.
```

Suggesting this because it's not so much that the security vulnerability is a property of Astro Runtime -- it's specific to an external tool but found packaged WITHIN Runtime

2022-06-14 14:51 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to determine if the vulnerabilities identified in the report pose a risk to organizations
I don't feel super strongly, but does this need to be its own section? Would it be cleaner to have a "note" below the above section that is "optional" to read?

2022-06-14 14:51 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to determine if the vulnerabilities identified in the report pose a risk to organizations
Should also be consistent in contacting support vs. CS on bug fixes and vulnerabilities -- can discuss

2022-06-14 15:11 UTC, paolaperaza commented on astro/runtime-version-lifecycle-policy.md
> +Astronomer is aware of the Quay Common Vulnerabilities and Exposures (CVE) report and monitors it frequently to determine if the vulnerabilities identified in the report pose a risk to organizations
Discussed and agreed on having it be its own section

2022-06-14 19:11 UTC, merged