Build a Custom Docker Image Updates
astronomer/docs pull request #788
Opened 2022-06-08 15:59 UTC by kwcanuck

Resolves #721.

@BasPH could you perform a technical review of this doc change? Thanks!

2022-06-08 16:31 UTC, stuart23 commented
Hold up on this plz. This has worked in the past, so unless something changed in the CLI, it should not need changing.

2022-06-08 16:38 UTC, kwcanuck commented
Thanks for the quick feedback @stuart23. This change is on a branch, so it won't be merged until the change has been reviewed and approved. If it isn't necessary, I'll close it. Holding pattern engaged.

2022-06-14 12:53 UTC, kwcanuck commented
@BasPH I have added your edits and the doc is ready for your review.

2022-06-14 14:04 UTC, kwcanuck commented
@stuart23 with regard to your comment about removing the "push & pull instructions to ECR". can you confirm that you want to restore the procedure to its previous state and only keep the note I added today?

2022-06-14 14:13 UTC, stuart23 commented
IMHO this is the only update needed (my copywriting sucks though, sorry!) https://github.com/astronomer/docs/compare/stuart23-custom-arch

2022-06-14 15:51 UTC, BasPH commented on astro/develop-project.md
> +2. Update the following entry in the  `Dockerfile`::
```suggestion
2. Update the following entry in the  `Dockerfile`:
```

2022-06-14 15:51 UTC, BasPH commented on astro/develop-project.md
> +        :::
I wanted to check the alignment in the preview because there's a different number whitespaces used, but somehow the preview isn't displaying these changes?

2022-06-14 15:51 UTC, BasPH commented on astro/develop-project.md
> +        :::
Also, leaving "custom-astro-runtime" here would stay in sync with the other code samples.

2022-06-14 15:55 UTC, BasPH commented on astro/develop-project.md
> +        :::
I found there's 2 sections ("Private GitHub Repo" and "Private PyPi Index"), and this only makes changes in the private PyPi index section. Please update the "Private GitHub Repo" section with the same changes, because the same applies there.

2022-06-14 15:56 UTC, BasPH commented on astro/develop-project.md
> +        :::
Alignment is messing up the formatting:

![image](https://user-images.githubusercontent.com/6249654/173622241-7ec8f5fc-9832-486e-ab21-1486cdd23edb.png)

See https://deploy-preview-788--gallant-neumann-56599d.netlify.app/astro/develop-project#install-python-packages-from-private-sources -> select "Private PyPi Index" tab

2022-06-14 18:00 UTC, kwcanuck commented on astro/develop-project.md
> +        :::
@BasPH all of the issues you have identified have been corrected. Thanks!

2022-06-14 18:02 UTC, stuart23 requested changes

2022-06-14 18:02 UTC, stuart23 commented on astro/develop-project.md
> +    FROM --platform=linux/amd64 astrobase:latest
This should be `FROM --platform=linux/amd64 custom-astro-runtime:5.0.0`

2022-06-14 18:23 UTC, stuart23 requested changes

2022-06-14 18:23 UTC, stuart23 commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --build-arg PIP_EXTRA_INDEX_URL=https://${<repo-username>}:${<repo-password>}@<private-pypi-repo-domain-name> -t custom-astro-r
This should not have changed

2022-06-14 18:23 UTC, stuart23 commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --build-arg PIP_EXTRA_INDEX_URL=https://${<repo-username>}:${<repo-password>}@<private-pypi-repo-domain-name> -t custom-<airflo
This should not have changed

2022-06-14 18:23 UTC, stuart23 commented on astro/develop-project.md
> +    For example, if you have `quay.io/astronomer/astro-runtime:5.0.0` in your `Dockerfile.build`, this command would be:
This should not have changed

2022-06-14 18:23 UTC, stuart23 commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file. Replace the pip repository and associated credentials values with your own.
This should not have changed

2022-06-14 18:27 UTC, kwcanuck commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --build-arg PIP_EXTRA_INDEX_URL=https://${<repo-username>}:${<repo-password>}@<private-pypi-repo-domain-name> -t custom-<airflo
Corrected

2022-06-14 18:28 UTC, kwcanuck commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file. Replace the pip repository and associated credentials values with your own.
Corrected. Copy and paste errors.

2022-06-14 18:30 UTC, kwcanuck commented on astro/develop-project.md
> +    For example, if you have `quay.io/astronomer/astro-runtime:5.0.0` in your `Dockerfile.build`, this command would be:
Corrected.

2022-06-14 19:29 UTC, stuart23 approved these changes
:kissing_heart::ok_hand:

2022-06-14 21:00 UTC, jwitz approved these changes
A few minor comments, but otherwise LGTM! Check the preview site to ensure that the note renders correctly before merging. If it's still showing up weird, let me know by tagging me back in the PR and I'll try to troubleshoot it.

2022-06-15 12:07 UTC, kwcanuck commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
@stuart23 can you confirm the original text I wrote is correct? If not, could you clarify your request? It's not clear from your comment what should be changed in the text.

2022-06-15 14:08 UTC, stuart23 commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
Yep Ron, you are correct

2022-06-15 14:34 UTC, kwcanuck commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
@jwitz the current text is accurate, so I won't be implementing your edit suggestion.

2022-06-16 07:52 UTC, BasPH commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<ssh-key>" -t custom-<astro-runtime-image>.
The dot here doesn't indicate the end of the line, but actually refers to the path for the "Docker context", i.e. the directory to include for the `docker build` ([docs](https://docs.docker.com/engine/reference/commandline/build/#build-with-path)). Hence, the whitespace is required.

```suggestion
    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<ssh-key>" -t custom-<astro-runtime-image> .
```

2022-06-16 07:52 UTC, BasPH commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-5.0.0-base.
Same here
```suggestion
    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-5.0.0-base .
```

2022-06-16 07:52 UTC, BasPH commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
Same nitpick, but it's the machine architecture, not OS architecture
```suggestion
    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your machine and the image architecture are different. For example, this is the format for the Apple M1 architecture:
```

2022-06-16 07:52 UTC, BasPH commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
Same here
```suggestion
    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your machine and the image architecture are different. For example, this is the format for the Apple M1 architecture:
```

2022-06-16 13:14 UTC, kwcanuck commented on astro/develop-project.md
> +    DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --progress=plain --ssh=github="$HOME/.ssh/<authorized-key>" -t custom-astro-runtime-5.0.0-base.
Thanks @BasPH!

2022-06-16 13:25 UTC, kwcanuck commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
I'll use computer instead of machine as that is the recommended standard. Thanks!

2022-06-16 13:33 UTC, kwcanuck commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your operating system and the image architecture are differe
See previous comment. Thanks!

2022-06-16 17:23 UTC, paolaperaza commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your computer and the image architecture are different. For
```suggestion
    Astro runtime base images are built on AMD64 architecture. You must add the architecture name to the `FROM` statement when your computer and the image architecture are different. For example, this is the format for the Apple M1 architecture:
```

2022-06-16 17:24 UTC, paolaperaza commented on astro/develop-project.md
> +1. Run the following command to create a new Docker image from your `Dockerfile.build` file. Replace the pip repository and associated credentials values with your own.
```suggestion
1. Run the following command to create a new Docker image from your `Dockerfile.build` file. Replace the pip repository and associated credential values with your own.
```

2022-06-16 20:03 UTC, BasPH commented on astro/develop-project.md
> +    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your ocomputer and the image architecture are different. For
Small typo, otherwise LGTM!

```suggestion
    Astro runtime base images are built on the `linux/amd64` architecture. You must add the architecture name to the `FROM` statement when your computer and the image architecture are different. For example, this is the format for the Apple M1 architecture:
```

2022-06-16 20:11 UTC, BasPH approved these changes

2022-06-16 20:15 UTC, merged