Added New Test and Troubleshoot the KubernetesPodOperator Locally Topic to Astro
astronomer/docs pull request #798
Opened 2022-06-13 18:06 UTC by kwcanuck

Resolves #603.

@jwitz and @paolaperaza this is a preliminary draft and will likely need significant edits.

2022-06-16 18:10 UTC, dstandish approved these changes

2022-06-16 18:10 UTC, dstandish commented on astro/kubepodoperator-local.md
> +        is_delete_operator_pod=True,
```suggestion
```

2022-06-17 12:36 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +### Step 2: Instantiate the KubernetesPodOperator
@dstandish can you clarify your concern? Are you requesting the removal of  _Add a KubernetesPodOperator Task_ or  _Run Your Container_?

2022-06-20 15:24 UTC, dstandish commented on astro/kubepodoperator-local.md
> +### Step 2: Instantiate the KubernetesPodOperator
no concern, do what you like, just from quick glance seemed like you were repeating an example

2022-06-21 17:58 UTC, jwitz requested changes
A few suggestions and questions here @kwcanuck , mainly requesting changes related to how we have some redundant steps for testing locally. I also think this is a great opportunity for using some tabs to split up the OS-specific steps.

2022-06-21 18:27 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +The latest versions of Docker for Windows and Mac let you run a single node Kubernetes cluster locally. If you are using Windows, see [Setting Up Docker for Windows and WSL to Work Flawlessly](https:
@jwitz these aren't prerequisites. They are links to supplementary information. 

There are two versions of Docker being discussed; Windows and Mac. Therefore, _version_ should be plural (versions).  

Here is the modified text:

_The latest versions of Docker for Windows and Mac both support running a single-node Kubernetes cluster locally._

2022-06-21 18:28 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +1. Install Microk8s. See [Microk8s](https://microk8s.io/).
@jwitz as there is only a single prerequisite, it is better to incorporate it into the task. One less heading.

2022-06-21 18:55 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +
@jwitz I was reviewing the content today and had the same thought. :)

I have added tabs where I think it is necessary.

2022-06-21 19:13 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +2. Update the `CERT_AUTHORITY_DATA`, `CERT_CLIENT_DATA`, and `CERT_KEY_DATA` values in the `config` file with the values for your organization.
@jwitz is there an edit you're recommending?

2022-06-21 19:14 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +Run `astro dev start` to build this config into your image.
@jwitz I think this information should remain with the example syntax.

2022-06-21 19:15 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +### Linux
@jwitz done. Take a look and provide your feedback.

2022-06-27 12:54 UTC, kwcanuck commented
@paolaperaza and @jwitz all edits requested to date have been added to the doc. It's ready for final review.

2022-06-27 15:51 UTC, jwitz requested changes
One more proposal for the doc structure here, but besides that just minor feedback!

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +    The `clusters.cluster.name` should be searchable as `docker-desktop` in your local `$HOME/.kube``config` file.
```suggestion
    The `clusters.cluster.name` should be searchable as `docker-desktop` in your local `$HOME/.kube/config` file.
```

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +2. Update the `CERT_AUTHORITY_DATA`, `CERT_CLIENT_DATA`, and `CERT_KEY_DATA` values in the `config` file with the values for your organization.
Whoops not sure why this suggestion didn't go through! I recommended using `<cert-authority-data>` etc to match our placeholder value styling. Currently they look like system environment variables. Just updated the suggestion to reflect that. If you do make this change, these values should also change in the code block itself.

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +## Next Steps ##
```suggestion
## Next Steps
```

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +## Test the KubernetesPodOperator Locally
I'm all for having islands when it saves you from jumping between different documents, but repeating the same information and code sample in a single doc and linking internally feels less intuitive. Really, the only differences for this content are that the example is code is less detailed and we don't put `Step 1/2/3` for the first topics. 

What's the benefit of having this duplicate section instead of organizing the entire document as a procedure? I'd prefer doing the latter by removing this topic and framing the other topics as steps. Because a user is likely to only need to "Set up Kubernetes" and "Update the kubeconfig file" once per environment, I don't think it's necessary to frame that topic as a general documentation outside of a procedure.

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +## Set up Kubernetes
```suggestion
## Step 1: Set up Kubernetes
```
See my comment later on about this suggestion. This is an example of what I'm talking about.

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +The `config_file` points to the `/include/.kube/config` file you just edited.
I'm cool with "create an instance"!

In your alternatives, the namespace/ configuration is part of the example explanation, but I want that to be a part of what we instruct the user to do as a requirement whenever they run KPO. So like:

`To use the KubernetesPodOperator, you must define the configuration for your pod, including its namespace and runtime image, when you create an instance of the operator. This sample syntax runs the `hello-world` Docker image in a different namespace based on whether you're running the DAG locally or on Astro.`

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +You can use the following example DAG to test your configurations. This DAG runs the `hello-world` Docker image in a different cluster based on whether you're running the DAG locally or on Astro.
```suggestion
You can use the following example DAG to test your configurations. This DAG runs the `hello-world` Docker image in a different namespace based on whether you're running the DAG locally or on Astro. 
```

2022-06-27 15:51 UTC, jwitz commented on astro/kubepodoperator-local.md
> +        image="my-image",
These are all placeholder values, but we don't really describe them as such. We should either use our normal placeholder syntax or have more documentation about what to fill in here.

2022-06-27 18:37 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +You can use the following example DAG to test your configurations. This DAG runs the `hello-world` Docker image in a different cluster based on whether you're running the DAG locally or on Astro.
@jwitz with the previous edit, this text has been removed.

2022-06-27 18:42 UTC, kwcanuck commented
@jwitz your latest edits have been addressed, Please review and provide your approval or additional edit requests.

2022-06-28 12:30 UTC, kwcanuck commented on software/kubepodoperator-local.md
> +2. Update the `certificate-authority-data`, `client-certificate-data`, and `client-key-data` values in the `config` file with the values for your organization.
@jwitz I recommend that we establish a policy of NOT cloning topics until the review cycle is complete. Keeping topics synchronized is very challenging.

2022-06-28 12:36 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +sidebar_label: 'Run the KubernetesPodOperator Locally'
@jwitz I don't think this change is necessary.

2022-06-28 13:10 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +sidebar_label: 'Run the KubernetesPodOperator Locally'
@jwitz I implemented these changes.

2022-06-28 13:16 UTC, kwcanuck commented
@paolaperaza all of Jake's edits have been implemented. You can now complete your review.

2022-06-28 13:16 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +<TabItem value="windows and mac">
@jwitz the topics have been updated and now are identical (save a few minor differences).

2022-06-28 13:16 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +## Run Your Container
@jwitz the topics have been updated and now are identical (save a few minor differences).

2022-06-29 17:13 UTC, paolaperaza reviewed
@kwcanuck This is super well-done, thank you. Added some mostly minor comments - take a look and I'll do a final pass?

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +To use the KubernetesPodOperator, you must define the configuration for your pod, including its namespace and runtime image, when you create an instance of the operator. This sample syntax runs the `
```suggestion
To use the KubernetesPodOperator, you must define the configuration of each task and the Kubernetes Pod in which it runs, including its namespace and Docker image.

This example DAG runs a `hello-world` Docker image. The namespace is determined dynamically based on whether you're running the DAG in your local environment or on Astro. If you are using Linux, the `cluster_context` is `microk8s`. The `config_file` points to the edited `/include/.kube/config` file.
```

I think the Docker image here actually does _not_ have to be a Runtime image -- that's sort of the magic of it. The Pod is still based on Runtime because the worker or scheduler is, but users can run arbitrary images in there

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +# environment namespace when deployed to Astronomer.
```suggestion
# environment namespace when deployed to Astro.
```

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +Optional. Review the logs for any pods that were created by the operator for issues.
```suggestion
Optional. Review the logs for any Pods that were created by the operator for issues.
```

P sure we landed on `Pods` in style guide

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +Run `kubectl get pods -n $namespace` or `kubectl logs {pod_name} -n $namespace` to examine the logs for the pod that just ran. By default, `docker-for-desktop` runs pods in the `default` namespace.
Should `kubectl` be a prerequisite? https://kubernetes.io/docs/reference/kubectl/

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +Run `kubectl get pods -n $namespace` or `kubectl logs {pod_name} -n $namespace` to examine the logs for the pod that just ran. By default, `docker-for-desktop` runs pods in the `default` namespace.
```suggestion
Run `kubectl get pods -n $namespace` or `kubectl logs {pod_name} -n $namespace` to examine the logs for the Pod that just ran. By default, `docker-for-desktop` runs Pods in the `default` namespace.
```

2022-06-29 17:13 UTC, paolaperaza commented on astro/kubernetespodoperator.md
> +sidebar_label: 'KubernetesPodOperator (Deployed)'
```suggestion
sidebar_label: 'KubernetesPodOperator (On Astro)'
```

I think we say Astro, or nothing?

2022-06-29 17:44 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +The `KubernetesPodOperator` completes work within Kubernetes Pods in a Kubernetes cluster. Test the `KubernetesPodOperator` locally before running it in a production Kubernetes cluster.
@paolaperaza I have revised the introductory statement using some of the content you provided:

The `KubernetesPodOperator` is an Airflow operator that completes tasks in Kubernetes Pods. The `KubernetesPodOperator` provides an isolated, containerized execution environment for each task and lets you run custom Docker images and Python versions, set task-level resource requests, and more.

On Astro, the Kubernetes infrastructure required to run the `KubernetesPodOperator` is built in. To test the `KubernetesPodOperator` operator locally, you need a local Kubernetes environment.

2022-06-29 17:49 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +        task_id="task-one",
@paolaperaza good catch. This has been corrected. Thanks!

2022-06-29 18:00 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +Run `kubectl get pods -n $namespace` or `kubectl logs {pod_name} -n $namespace` to examine the logs for the pod that just ran. By default, `docker-for-desktop` runs pods in the `default` namespace.
@paolaperaza fixed.

2022-06-30 04:39 UTC, paolaperaza approved these changes
We good! Final comments but I'll let you finish off. Thanks @kwcanuck  ✅

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +The latest versions of Docker for Windows and Mac let you run a single node Kubernetes cluster locally. If you are using Windows, see [Setting Up Docker for Windows and WSL to Work Flawlessly](https:
```suggestion
The latest versions of Docker for Windows and Mac let you run a single node Kubernetes cluster locally. If you are using Windows, see [Setting Up Docker for Windows and WSL to Work Flawlessly](https://docs.docker.com/desktop/windows/install/). If you are using Mac, see [Docker Desktop for Mac user manual](https://docs.docker.com/desktop/mac/). It isn't necessary to install [Docker Compose](https://docs.docker.com/compose/).
```

- I think `Docker Compose` is proper noun? https://docs.docker.com/compose/
- We prob shouldn't link to some person's personal blog post from 2020. Tried to find the right links from Docker docs but you can double check me on these!

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +1. Go to the `$HOME/.kube` directory that was created when you enabled Kubernetes in Docker and copy the `config` file into the `/include/.kube/` folder in your Astro project. The `config` file conta
```suggestion
1. Go to the `$HOME/.kube` directory that was created when you enabled Kubernetes in Docker and copy the `config` file into the `/include/.kube/` folder in your Astro project. The `config` file contains all the information the KubernetesPodOperator uses to connect to your cluster. For example:
```
```suggestion
1. Go to the `$HOME/.kube` directory that was created when you enabled Kubernetes in Docker and copy the `config` file into the `/include/.kube/` folder in your Astro project. The `config` file contains all the information the KubePodOperator uses to connect to your cluster. For example:
```

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +Run `astro dev start` to build this config into your image.
```suggestion
Once you've updated the definition of KubernetesPodOperator tasks in your Astro project, run `astro dev start` with the Astro CLI to test your DAGs in a local Airflow environment.
```

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +Optional. Use the `kubectl` command line tool to review the logs for any pods that were created by the operator for issues. If you haven't installed the `kubectl` command line tool, see [Install Tool
```suggestion
Optional. Use the `kubectl` command line tool to review the logs for any Pods that were created by the operator for issues and help with troubleshooting. If you haven't installed the `kubectl` command line tool, see [Install Tools](https://kubernetes.io/docs/tasks/tools/#kubectl).
```

2022-06-30 04:39 UTC, paolaperaza commented on software/kubepodoperator-local.md
> +The latest versions of Docker for Windows and Mac let you run a single node Kubernetes cluster locally. If you are using Windows, see [Setting Up Docker for Windows and WSL to Work Flawlessly](https:
Same changes here if you agree

2022-06-30 04:39 UTC, paolaperaza commented on software/kubepodoperator-local.md
>  from datetime import datetime, timedelta
I'd maybe update the start date in this DAG -- not required but it does say 2019 lol

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +    'start_date': datetime(2019, 1, 1),
```suggestion
    'start_date': datetime(2022, 1, 1),
```

2022-06-30 04:39 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +        task_id="task-one",
placeholder values?

2022-06-30 04:41 UTC, paolaperaza commented on astro/kubepodoperator-local.md
> +The `KubernetesPodOperator` completes work within Kubernetes Pods in a Kubernetes cluster. Test the `KubernetesPodOperator` locally before running it in a production Kubernetes cluster.
Perfect

2022-06-30 11:21 UTC, kwcanuck commented on software/kubepodoperator-local.md
> +The latest versions of Docker for Windows and Mac let you run a single node Kubernetes cluster locally. If you are using Windows, see [Setting Up Docker for Windows and WSL to Work Flawlessly](https:
Done.

2022-06-30 11:23 UTC, kwcanuck commented on software/kubepodoperator-local.md
>  from datetime import datetime, timedelta
Done

2022-06-30 11:24 UTC, kwcanuck commented on astro/kubepodoperator-local.md
> +        task_id="task-one",
These are the pre-defined values for the sample DAG. A user doesn't change these values.

2022-06-30 11:35 UTC, merged