New Topic for Astro Support Request Form
astronomer/docs pull request #822
Opened 2022-06-16 12:46 UTC by kwcanuck

Resolves #817.

2022-06-16 14:22 UTC, paolaperaza reviewed
A few initial comments here @kwcanuck - give this another pass.

Before we merge, I'd like for either @collinmcnulty or @stuart23 to review this as well to ensure everything here is accurate from a CRE perspective

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +title: 'Astro Support'
Thoughts on this being `Submit a Support Request`

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +If you're an Astro user and need answers to common questions, the following resources are available:
```suggestion
If you're an Astro user and need answers to common questions, the following resources are available in addition to documentation:
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +- [Airflow Guides](https://www.astronomer.io/guides/airflow-and-hashicorp-vault)
```suggestion
- [Airflow Guides](https://www.astronomer.io/guides/)
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +- Call +1 (831) 777-2768
Should verify if this phone number is still valid

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +- Always indicate priority
Feels like a lot of text to just have this line or "section" be a bullet point. Any way we can play around with headers or break up this section to be more readable?

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    - **P1:** Critical systems are unavailable, no workaround is immediately available
```suggestion
    - **P1:** Critical impact, service is unusable in production
```

This is a screenshot of our ticket intake requests -- should match language

![image](https://user-images.githubusercontent.com/31111752/174088804-99265938-aa0d-464a-92d6-f93469ca2055.png)

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    - **P1:** Critical systems are unavailable, no workaround is immediately available
Can you apply these to the other set of priorities?

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +        - The Scheduler is not heartbeating, and restarting didn't fix the issue.
```suggestion
        - Your tasks are not running and restarting them didn't fix the issue.
```

Customers on Astro don't have direct access to restart the scheduler, nor do we give them metrics to know (explicitly) whether or not the scheduler is heartbeating

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +        - There is an Astronomer outage, such as downtime in the Astronomer Docker Registry.
```suggestion
        - Astronomer is experiencing an incident or downtime that is affecting your data pipelines in production.
```

I think these are all _reasons_, but really the symptom is: "my tasks aren't running"

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    - **P2:** Significant Astronomer/Astronomer-owned Airflow functionality is impaired, but your organization is still able to run essential DAGs.
```suggestion
    - **P2:** High impact. Ability to use Astro is severely impaired but does not affect critical pipelines in production.
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +        - Task logs are missing in the Airflow UI.
```suggestion
        - The Airflow UI is unavailable.
        - You are unable to deploy code to your Deployment, but existing DAGs and tasks are running as expected.
        - Task logs are missing in the Airflow UI.
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    - What project/deployment does this question/issue apply to?
```suggestion
```

The user doesn't need to provide this information if they're submitting a support request via the Cloud UI, in which case it's auto-populated. Should we make that clear here?

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    - Have you made any recent changes to your Airflow deployment, code, or image?
```suggestion
    - Have you made any recent changes to your Deployment or running DAGs?
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +    If you've already taken note of any task-level Airflow logs or Astronomer platform logs, don't hesitate to send them as a part of your original ticket.
```suggestion
    If you've already taken note of task logs or Airflow component logs, send them as a part of your request.
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +If you're using Astro version 5.0.4 or later, you can submit your support request in the Cloud UI.
```suggestion
```

Astro is version less to the user -- this feature becomes available to all users at once 😊  Entirely separate from Astro Runtime

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +3. Click **Submit**.
Let's add a screenshot of the form here?

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +If you're new to Astronomer, you'll need to create an account on the [Astronomer Support Portal](https://support.astronomer.io) to submit a support request. If you're working with a team and want to
```suggestion
If you're new to Astronomer, you'll need to create an account on the [Astronomer Support Portal](https://support.astronomer.io) to submit a support request. If you're working with a team and want to view support tickets created by other team members, use your work email or the domain you share with your team members for your account. If your team uses more than one email domain (for example, @astronomer.io), contact Astronomer and ask to have it added manually to your organization.
```

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +## Submit a Support Request on the Astronomer Support Portal
Let's add a line here that we generally recommend creating support requests via the Cloud UI, or at least frame this as an alternative? Also mention that you'll be asked to provide information about your issue

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +3. Click **Submit**.
Let's also add a note that once you submit a request via the Cloud UI, correspondence will happen over email. Will defer to you on phrasing -- but just to answer the question of "do I check back in Cloud UI for a response or will I get an email?"

2022-06-16 14:22 UTC, paolaperaza commented on astro/support.md
> +> **Note:** To add a teammate to an existing support request, cc them in a followup message within the email thread that was automatically generated when the ticket was created.
Is this line redundant with the info above? Let's also try to use one of the standard notes, maybe a `:::tip`

2022-06-16 14:29 UTC, kwcanuck commented on astro/support.md
> +title: 'Astro Support'
@paolaperaza that works. Implemented. It could be shortened to _Request Support_, or _Request Astro Support_. Users have multiple options for getting support - not just the support request forms.

2022-06-16 14:45 UTC, kwcanuck commented on astro/support.md
> +    - **P2:** Significant Astronomer/Astronomer-owned Airflow functionality is impaired, but your organization is still able to run essential DAGs.
Updated as requested.

2022-06-16 14:49 UTC, kwcanuck commented on astro/support.md
> +    - What project/deployment does this question/issue apply to?
@paolaperaza it doesn't matter what method is used to report an issue. This information is helpful when trying to resolve an issue. Users don't need to select a Workspace or Deployment in the Cloud UI - it's optional despite being auto-populated. That's why I added Optional to the field descriptions.

2022-06-16 14:57 UTC, kwcanuck commented on astro/support.md
> +3. Click **Submit**.
@paolaperaza I don't think a screenshot is necessary here. It's a simple form and the behavior that occurs after clicking **Submit** is obvious.  

I have added this statement below the last procedure step: 

When Astronomer Support start working on your issue, you'll receive email notifications. To check the status of a support request, sign in to the [Astronomer Support Portal](https://support.astronomer.io).

2022-06-16 15:04 UTC, kwcanuck commented on astro/support.md
> +## Submit a Support Request on the Astronomer Support Portal
@paolaperaza I have added this sentence to this section:

_Astronomer recommends that you submit support requests in the Cloud UI._ 

I'm not sure this is necessary as the first task is submitting a support request with the Cloud UI. If users ignore this, they obviously want to use the support portal. Your call.

I don't think we need to mention that the user will need to "provide information about their issue". This is obvious - the support request form has mandatory fields that a user must complete.

2022-06-16 15:10 UTC, kwcanuck commented on astro/support.md
> +> **Note:** To add a teammate to an existing support request, cc them in a followup message within the email thread that was automatically generated when the ticket was created.
@paolaperaza two different items - one is asking users to add a team email or domain name when they create an account, and the other is telling users how to add teammates to _existing_ support requests.

I have added the information to a tip callout.

2022-06-16 19:11 UTC, jwitz requested changes
@kwcanuck Overall LGTM, just a few style suggestions. Gonna request changes just because I want to double check the sidebar / header formatting if you end up taking those suggestions.

2022-06-16 19:11 UTC, jwitz commented on astro/support.md
> +3. Click **Submit**.
I imagine that the screenshot of the form is gonna change a lot since it was just developed, but a screenshot of where the **Submit Report Request** button might be good either here or in release notes.

2022-06-16 19:11 UTC, jwitz commented on astro/support.md
> +## Submit a Support Request on the Astronomer Support Portal
I don't see this change in the section below, was it resolved / rolled back elsewhere?

2022-06-16 19:11 UTC, jwitz commented on astro/support.md
> +    The more context you can give, the better we can help you.
```suggestion
    If you've already taken note of task logs or Airflow component logs, send them as a part of your request. The more context you can give, the better we can help you.
```

2022-06-16 19:15 UTC, kwcanuck commented on astro/support.md
> +## Submit a Support Request on the Astronomer Support Portal
Odd. It was added. So many changes are being added. it might have been overwritten. Added again.

2022-06-16 19:21 UTC, kwcanuck commented on astro/support.md
> +3. Click **Submit**.
@jwitz what is the recommended format for images and where are they stored?

2022-06-16 19:31 UTC, stuart23 commented
I don't have the bandwidth RN but I would love to review this. When do you need it by?

2022-06-16 19:33 UTC, kwcanuck commented on astro/support.md
> +If you're an Astro user and haven't found the answer in Astronomer documentation, the following resources are available:
@jwitz I updated this to: _If you're an Astro user and haven't been able to resolve an issue using Astronomer documentation_. I didn't add additional as it isn't necessary.

2022-06-16 19:41 UTC, kwcanuck commented on astro/support.md
> +- Always indicate priority
@jwitz I've tried using headings and it appears to have messed up the formatting. Maybe you can do better? In my opinion, the bullets were a better solution.

2022-06-16 19:45 UTC, kwcanuck commented on astro/support.md
> +If you're new to Astronomer, you'll need to create an account on the [Astronomer Support Portal](https://support.astronomer.io) to submit a support request. If you're working with a team and want to
@jwitz you can't submit a support request on the Astronomer Support Portal without an account.

2022-06-16 19:47 UTC, kwcanuck commented on astro/support.md
> +- Communicate with Astronomer Support
@jwitz are you adding punctuation to all lists? This seems very formal and unnecessary. My two cents.

2022-06-16 19:55 UTC, kwcanuck commented on astro/support.md
> +    The more context you can give, the better we can help you.
@jwitz I revised it to: _If you've already copied task logs or Airflow component logs, send them as a part of your request_

2022-06-16 19:57 UTC, kwcanuck commented on astro/support.md
> +
@jwitz I added them to make it easier to parse the content when writing and editing. It doesn't appear to cause any issues.

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +- File a support request on the [Astronomer Support Portal](https://support.astronomer.io/hc/en-us)
I believe we want users to use the in product support form as their primary means of requesting support. We should state that here.

In the rare cases where they cannot submit a request via the Cloud UI (eg. cannot log in, Cloud UI is down), then use one of the alternatives.

@christine-sherry what do you think?

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +1. In the Cloud UI, click **Help** > **Submit Support Request**.
Screenshot of the location in the UI would help guide the user. This is going to remain static.

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +1. In the Cloud UI, click **Help** > **Submit Support Request**.
Also may want to add that this can be accessed for all pages in Cloud UI

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +    - **Deployment**: Optional. Select the Deployment where the issue is occurring. This list is auto-populated when you submit a support request from a Workspace or a Deployment.
Correction: This list is auto-populated when you submit a support request from a Deployment.

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +    When Astronomer Support start working on your issue, you'll receive email notifications. To check the status of a support request, sign in to the [Astronomer Support Portal](https://support.astro
An auto-generated email is sent to the user(s) when the ticket is submitted/created in Zendesk. Future email comms will be sent when Astronomer responds to the ticket.

2022-06-16 21:09 UTC, chomipi88 commented on astro/astro-support.md
> +## Monitor Existing Support Requests
Support requests submitted via Cloud UI will be managed over email.
Our goal is to have less people trying to register and log into Zendesk as it is a manual and cumbersome process with a poor user experience.

2022-06-17 11:06 UTC, kwcanuck commented on astro/astro-support.md
> +- File a support request on the [Astronomer Support Portal](https://support.astronomer.io/hc/en-us)
@chomipi88 this statement appears in the section titled _Submit a Support Request on the Astronomer Support Portal_:

_Astronomer recommends that you submit support requests in the Cloud UI_

Also, having the Cloud Ui appear as the first item in the list of options implies that using the Cloud UI is the preferred method.

2022-06-17 11:18 UTC, kwcanuck commented on astro/astro-support.md
> +1. In the Cloud UI, click **Help** > **Submit Support Request**.
@chomipi88 I added an image similar to this:

![support-request-location](https://user-images.githubusercontent.com/104205257/174287823-6d615190-7257-4ffb-8b68-b98ba3c57d13.png)

We don't provide images of the entire UI when we need to highlight a specific control. Only the portion of the screen with the control is shown. This is sufficient to help users locate the correct location.

If the control can be accessed anywhere in the UI, there s no need to indicate this.

2022-06-17 11:23 UTC, kwcanuck commented on astro/astro-support.md
> +    - **Deployment**: Optional. Select the Deployment where the issue is occurring. This list is auto-populated when you submit a support request from a Workspace or a Deployment.
@chomipi88 in my experience, Deployments and Workspaces are auto-populated and available within a Workspace _and_ a Deployment.  Happy to demonstrate.

2022-06-17 11:27 UTC, kwcanuck commented on astro/astro-support.md
> +    When Astronomer Support start working on your issue, you'll receive email notifications. To check the status of a support request, sign in to the [Astronomer Support Portal](https://support.astro
@chomipi88 the text now reads  _You'll receive an email when your ticket is created and follow-up emails as Astronomer Support processes your request_.

2022-06-17 11:52 UTC, kwcanuck commented on astro/support.md
> +3. Click **Submit**.
@jwitz I added the screenshot. It will likely need updating to match the standards.

2022-06-17 15:23 UTC, jwitz commented on astro/support.md
> +If you're an existing customer, sign in to the Astronomer Support Portal and create a new support request.
Are they doing this through the UI? When I open the form submission on the UI, I'm not prompted to log in. Or is this meant to communicate the alternative to using the Cloud UI?

2022-06-17 16:38 UTC, kwcanuck commented on astro/support.md
> +If you're an existing customer, sign in to the Astronomer Support Portal and create a new support request.
@jwitz you're not prompted to log in because you already have access. This is what new users without access see:

![image](https://user-images.githubusercontent.com/104205257/174340286-ec7a9f94-4545-47a0-a40a-a2d561d5a998.png)

As you can see, if you're not an existing user, "you'll need to create an account".

2022-06-17 16:43 UTC, jwitz approved these changes
Final review from me @kwcanuck ! Tag me back if you have any questions about my suggestions under "Submit a Support Request on the Astronomer Support Portal"

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +- Submit a support request in the [Cloud UI](#submit-a-support-request-in-the-cloud-ui)
```suggestion
- Submit a support request in the [Cloud UI](astro-support.md#submit-a-support-request-in-the-cloud-ui)
```

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +    - **Priority**: Select the severity of your issue. For severity level explanations, see [Best Practices for Submitting Support Requests](#best-practices-for-submitting-support-requests).
```suggestion
    - **Priority**: Select the severity of your issue. For severity level explanations, see [Best Practices for Submitting Support Requests](astro-support.md#best-practices-for-support-request-submissions).
```

2022-06-17 16:43 UTC, jwitz commented on astro/support.md
> +---
Remember to delete this file!

2022-06-17 16:43 UTC, jwitz commented on astro/support.md
> +    - **Priority**: Select the severity of your issue. For severity level explanations, see [Best Practices for Submitting Support Requests](astro-support.md#best-practices-for-submitting-support-req
```suggestion
    - **Priority**: Select the severity of your issue. For severity level explanations, see [Best Practices for Submitting Support Requests](astro-support.md#best-practices-for-support-request-submissions).
```

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +If you're an existing customer, sign in to the Astronomer Support Portal and create a new support request.
Are they doing this through the UI? When I open the form submission on the UI, I'm not prompted to log in. Or is this meant to communicate the alternative to using the Cloud UI?

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +If you're an existing customer, sign in to the Astronomer Support Portal and create a new support request.
```suggestion
If you're an existing customer, sign in to the [Astronomer Support Portal](https://support.astronomer.io) and create a new support request.
```

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +Astronomer recommends that you submit support requests in the Cloud UI.
```suggestion
Astronomer recommends that you submit support requests in the Cloud UI. If you can't access the Cloud UI for any reason, you can also submit report requests through the [Astronomer Support Portal](https://support.astronomer.io).
```
I think we should account for situations where the control plane is down, someone is having auth issues, etc.

2022-06-17 16:43 UTC, jwitz commented on astro/astro-support.md
> +If you're new to Astronomer, you'll need to create an account on the [Astronomer Support Portal](https://support.astronomer.io) to submit a support request. If you're working with a team and want to
```suggestion
If you're new to Astronomer, you'll need to create an account on the Astronomer Support Portal to submit a support request. If you're working with a team and want to view support tickets created by other team members, use your work email or the domain you share with your team members for your account. If your team uses more than one email domain (for example, `@astronomer.io`), contact Astronomer and ask to have the additional domains added to your organization.
```

2022-06-17 16:56 UTC, kwcanuck commented on astro/support.md
> +---
@jwitz sorry, delete what file?

2022-06-17 16:57 UTC, kwcanuck commented on astro/astro-support.md
> +If you're an existing customer, sign in to the Astronomer Support Portal and create a new support request.
@jwitz you're not prompted to log in because **you already have access**s. This is what new users without access see:

![image](https://user-images.githubusercontent.com/104205257/174343660-9e54ce81-f2c9-4591-b602-5ef890ac6e46.png)

As you can see, if you're not an existing user, "you'll need to create an account".

2022-06-17 17:00 UTC, kwcanuck commented on astro/astro-support.md
> +Astronomer recommends that you submit support requests in the Cloud UI.
@jwitz I used _If you can't access the Cloud UI, you can submit support requests on the [Astronomer Support Portal](https://support.astronomer.io)._

2022-06-17 17:33 UTC, jwitz commented on astro/astro-support.md
> +id: support
```suggestion
id: astro-support
```

2022-06-17 18:27 UTC, chomipi88 commented
LGTM... merge away!

2022-06-17 19:48 UTC, stuart23 commented on astro/astro-support.md
> +To add a teammate to an existing support request, cc them in a followup message within the email thread that was automatically generated when the ticket was created.
```suggestion
To add a teammate to an existing support request, cc them when replying on the support ticket email thread.
```

2022-06-17 20:19 UTC, christine-sherry commented on astro/astro-support.md
> +- File a support request on the [Astronomer Support Portal](https://support.astronomer.io/hc/en-us)
@chomipi88 I agree, let's call it out as the preferred method in our docs. Thanks guys!

2022-06-18 00:47 UTC, paolaperaza approved these changes
@kwcanuck A few final comments here. This might be something we need to follow up on after it's published to address nuances in framing or feedback from others BUT I think it's in a good place and reflects reality.

Take a look at my comments but I'll give the preemptive ✅

2022-06-18 00:47 UTC, paolaperaza commented on astro/astro-support.md
> +    You'll receive an email when your ticket is created and follow-up emails as Astronomer Support processes your request. To check the status of a support request, sign in to the [Astronomer Support
```suggestion
    You'll receive an email when your ticket is created and every time an Astronomer team member replies to your request. To check the status of support requests, you can also sign in to the [Astronomer Support Portal](https://support.astronomer.io).
```

Feels a little too robotic to say "as Astronomer Support processes your request". I also added the word `also` given that you can check the status of a request by opening up your email thread, but _also_ you can check it in the support portal?

2022-06-18 00:47 UTC, paolaperaza commented on astro/astro-support.md
> +If you're new to Astronomer, you'll need to create an account on the Astronomer Support Portal to submit a support request. If you're working with a team and want to view support tickets created by o
```suggestion
If you're new to Astronomer, you'll need to create an account on the Astronomer Support Portal to submit a support request. We recommend that you create an account with the same email address you use to log in to Astro. If you're working with a team and want to view support tickets created by other team members, make sure to use an email address with the domain you share with other team members for your account (for example, `@astronomer.io`). If your team uses more than one email domain, contact Astronomer and ask to have the additional domains added to your organization.
```

List example in first instance of `domain`?

2022-06-18 00:47 UTC, paolaperaza commented on astro/astro-support.md
> +- Communicate with Astronomer Support.
```suggestion
- Review and comment on other requests from your team.
- Monitor the status of all requests in your organization.
```

2022-06-18 01:16 UTC, paolaperaza commented on astro/support.md
> +If you're an Astro user and need answers to common questions, the following resources are available:
Resolving this for now since I made a comment on your suggestion in my latest review. I'd like to keep this as a "positive" and complementary statement

2022-06-18 01:18 UTC, paolaperaza commented on astro/support.md
> +- Always indicate priority
@kwcanuck In my latest review, it looks like you made these guidelines H3 headers, which addresses my concern. Resolving.

2022-06-18 01:19 UTC, paolaperaza commented on astro/support.md
> +3. Click **Submit**.
Strong agree -- it's actually hard to know where this form lives so I think including a screenshot is important. Resolving.

2022-06-20 11:17 UTC, kwcanuck commented on astro/astro-support.md
> +If you're an Astro user and haven't been able to resolve an issue using Astronomer documentation, the following resources are available:
@paolaperaza this was updated to: _In addition to product documentation, the following resources are available to help you resolve issues:_

2022-06-20 11:19 UTC, kwcanuck commented on astro/astro-support.md
> +If you're experiencing a more serious issue and need Astronomer expertise, you can use one of the following methods to contact Astronomer Support:
@paolaperaza typically, you want to limit the frequency users contact support. Support calls are expensive and time consuming. Using the term "serious" indicates that users should try resolving an issue on their own first before contacting Astronomer.  As Astronomer grows, you might want to revisit this.

2022-06-20 11:26 UTC, kwcanuck commented on astro/astro-support.md
> +    - **Deployment**: Optional. Select the Deployment where the issue is occurring. This list is auto-populated when you submit a support request from a Workspace or a Deployment.
@paolaperaza I discussed this at length with Piotr [2022-06-17](https://astronomer.slack.com/archives/D03ETDQ6F09/p1655487950378409).

Here is some of the highlights from our conversation:

![image](https://user-images.githubusercontent.com/104205257/174591565-03151661-bd4c-44f7-a105-966560075a7c.png)

![image](https://user-images.githubusercontent.com/104205257/174591759-aa9ae5d4-f9c4-4edc-8baa-bd1322d7e8c5.png)

The current text is accurate. If you want to discuss it further, let me know.

2022-06-20 11:28 UTC, kwcanuck commented on astro/astro-support.md
> +    - **Priority**: Select the severity of your issue. For severity level explanations, see [Best Practices for Submitting Support Requests](astro-support.md#best-practices-for-support-request-submis
@paolaperaza I added _Select the severity of your issue based on how the issue is affecting your organization_

2022-06-20 11:39 UTC, kwcanuck commented on astro/astro-support.md
> +    You'll receive an email when your ticket is created and follow-up emails as Astronomer Support processes your request. To check the status of a support request, sign in to the [Astronomer Support
@paolaperaza the current text is accurate. Emails are not always "replies". Whenever a ticket is modified or information is added, users receive an email notification. I tested it - the support team in India responded quite quickly! : )

Tone is subject to interpretation by every reader. What is robotic to you might be conversational to other readers. The use of contractions (you'll) indicates that this text is conversational and "conversational, friendly, and respectful without being overly colloquial or frivolous". The Google Developer Documentation Style Guide reminds writers that they should "provide information to someone who's looking for it and may be in a hurry". So, sentence length and structure need to as brief as possible. The longer a sentence and the more information packed it, the more difficult it is to read quickly. 

I have updated the text to: _You'll receive an email when your ticket is created and follow-up emails as Astronomer Support replies to your request. To check the status of a support request, you can also sign in to the Astronomer Support Portal_

2022-06-20 11:45 UTC, kwcanuck commented on astro/astro-support.md
> +If you're new to Astronomer, you'll need to create an account on the Astronomer Support Portal to submit a support request. If you're working with a team and want to view support tickets created by o
@paolaperaza Here is how the text now appears:

_If you're new to Astronomer, you'll need to create an account on the Astronomer Support Portal to submit a support request. Astronomer recommends that you use the same email address that you use to access Astro for your account. If you're working with a team and want to view support tickets created by other team members, use your work email or the domain you share with other team members for your account (for example, `@astronomer.io`). If your team uses more than one email domain (for example, `@astronomer.io`), contact Astronomer and ask to have the additional domains added to your organization._

I try and avoid the use of _we_.

2022-06-20 11:53 UTC, merged