Update View Scheduler Logs Topic to Include Task Logs
astronomer/docs pull request #831
Opened 2022-06-20 14:18 UTC by kwcanuck

Resolves #565

2022-06-22 16:21 UTC, jwitz requested changes
Base content looks great @kwcanuck! Requesting changes mainly about the titling strategy.

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +
```suggestion
Review logs in the Cloud UI or in Airflow to troubleshoot and resolve issues with your data pipelines.

```

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +id: view-logs
Whenever we change a file name, we should do the following:

- Add a redirect from the old link in `static/_redirects` (in this case, `/astro/scheduler-logs /astro/cli/astro-view-logs 301`)
- Find and replace all instances of internal links (in this case, `scheduler-logs.md` > `view-logs.md`

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +title: 'View Logs'
```suggestion
title: 'View Airflow Logs'
```
Do you think it's worth having this distinction? Not sure there's any plans for this now, but in the future there could be other forms of logging that could necessitate additional docs, such as platform logging or usage logging. This might future proof us and avoid another file name change in the future. 

Another option would be "Airflow Logs", which also accounts for a future in which we might have features for Airflow logs that go beyond "viewing".

If you do go for one of these suggestions, let's change the file name/ sidebar/ redirects as well.

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +## Access Airflow Component Logs
```suggestion
## Access Airflow Component Logs (Local Development Only)
```

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +To continue monitoring logs, run `astro dev logs --follow`. The `--follow` flag ensures that the latest logs continue to appear in your terminal window. For more information about this command, see [
```suggestion
To continue monitoring logs, run `astro dev logs --follow`. The `--follow` flag ensures that the latest logs continue to appear in your terminal window. For more information about this command, see [CLI Command Reference](cli/astro-dev-logs.md).
```

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +Airflow task logs are available in the Airflow UI. Task logs can help you troubleshoot a specific task instance that failed or retried.
```suggestion
Airflow task logs are available in the Airflow UI on both local and deployed Airflow environments. Task logs can help you troubleshoot a specific task instance that failed or retried.
```

2022-06-22 16:21 UTC, jwitz commented on astro/view-logs.md
> +1. Open a browser and go to `http://localhost:8080`.
```suggestion
1. Access the Airflow UI. To access the Airflow UI for a Deployment, open the Deployment in the Cloud UI and click **Open Airflow**. To access the Airflow UI for a local environment, open your browser and go to `http://localhost:8080`.
```
Open to rewording this, but we should account for both the Deployment and local experience in these steps.

2022-06-22 16:50 UTC, kwcanuck commented on astro/view-logs.md
> +title: 'View Logs'
@jwitz the topic discusses accessing log information in the Cloud UI _and_ in Airflow. So, this topic is not specific to Airflow logs. The generic _View Logs_ title works best, I think. Perhaps I haven't interpreted your comments correctly?

2022-06-22 16:56 UTC, jwitz commented on astro/view-logs.md
> +title: 'View Logs'
@kwcanuck You can view logs in the Cloud UI, but scheduler logs are still Airflow logs because the scheduler is a component of Airflow, not of Astro. The Cloud UI is just one way to view these logs (the other is to use the `scheduler` flag when checking logs locally.

2022-06-22 16:58 UTC, kwcanuck commented on astro/view-logs.md
> +title: 'View Logs'
@jwitz I don't think the distinction is necessary. Your call. File changes are not a big issue (despite the risk of broken links).

2022-06-22 17:06 UTC, kwcanuck commented on astro/view-logs.md
> +1. Open a browser and go to `http://localhost:8080`.
@jwitz added this text with minor changes.

2022-06-22 17:08 UTC, kwcanuck commented
@jwitz thanks again for the thorough review. I have addressed all of your comments and edit requests.

2022-06-22 19:44 UTC, jwitz commented on astro/view-logs.md
> +title: 'View Logs'
Gonna tag @paolaperaza here on the final call!

2022-06-23 16:49 UTC, jwitz commented on static/_redirects
> +/astro/scheduler-logs /astro/cli/astro-view-logs 301
```suggestion
/astro/scheduler-logs /astro/view-logs 301
```

2022-06-23 16:50 UTC, paolaperaza commented on astro/view-logs.md
> +## Access Airflow Component Logs (Local Development Only)
```suggestion
## Access Airflow Component Logs Locally
```

2022-06-23 19:42 UTC, jwitz commented on astro/test-and-troubleshoot-locally.md
```suggestion

## View Airflow Logs

You can use the Astro CLI to view logs for Airflow tasks components from your local Airflow environment. This is useful if you want to troubleshoot a specific task instance, or if your Airflow environment suddenly stops working after a code change. See [View Logs](view-logs.md).

```

2022-06-23 19:45 UTC, jwitz commented on astro/view-logs.md
> +description: View Deployment Airflow logs in the Cloud UI.
```suggestion
description: View logs for your data pipelines both locally and on Astro.
```

2022-06-23 19:45 UTC, jwitz commented on astro/view-logs.md
> +## View Airflow Scheduler Logs
```suggestion
## View Airflow scheduler logs
```

2022-06-23 19:46 UTC, jwitz commented on astro/view-logs.md
> +## Access Airflow Component Logs Locally
```suggestion
## Access Airflow component logs locally
```

2022-06-23 19:46 UTC, jwitz commented on astro/view-logs.md
> +To show logs for your Airflow Scheduler, Webserver, or metadata database locally, run the following command:
```suggestion
Airflow webserver, worker, and triggerer logs are not available for Astro Deployments.

To show logs for your Airflow scheduler, webserver, or metadata database locally, run the following command:
```

2022-06-23 19:47 UTC, jwitz commented on astro/view-logs.md
> +5. Optional. To view the Scheduler logs for another Deployment, select a different Deployment in the **Select a deployment list**.
```suggestion
You can access the recorded scheduler logs for a 24 hour period for a Deployment on the Cloud UI **Scheduler Logs** page. When a Deployment generates more than 500 logs in 24 hours, only the most recent 500 logs are available. Logs are color-coded to simplify log type identification. The scheduler logs can help you understand why specific tasks failed.

1. In the Cloud UI, select a Workspace.
2. Click **Logs**.

    ![Logs icon and button](/img/docs/log-location.png)

3. Select a Deployment in the **Select a deployment list**.
4. Optional. Select the log level and click **Apply**. These are the available options:

    - **Error**: Emitted when a process fails or does not complete. For example, these logs might indicate a missing DAG file, an issue with your scheduler's connection to the Airflow database, or an irregularity with your scheduler's heartbeat.
    - **Warn**: Emitted when Airflow detects an issue that may or may not be of concern but does not require immediate action. This often includes deprecation notices marked as `DeprecationWarning`. For example, Airflow might recommend that you upgrade your Deployment if there was a change to the Airflow database or task execution logic.
    - **Info**: Emitted frequently by Airflow to show that a standard scheduler process, such as DAG parsing, has started. These logs are frequent but can contain useful information. If you run dynamically generated DAGs, for example, these logs will show how many DAGs were created per DAG file and how long it took the Scheduler to parse each of them.

5. Optional. To view the scheduler logs for another Deployment, select a different Deployment in the **Select a deployment list**.
```

2022-06-23 19:48 UTC, jwitz approved these changes

2022-06-23 21:13 UTC, jwitz commented on astro/manage-workspaces.md
> +- **Logs:** View Scheduler logs for Deployments in the Workspace. For more information, see [Scheduler Logs](view-logs.md).
```suggestion
- **Logs:** View Scheduler logs for Deployments in the Workspace. For more information, see [View logs](view-logs.md).
```

2022-06-23 21:13 UTC, jwitz commented on astro/test-and-troubleshoot-locally.md
> +You can use the Astro CLI to view logs for Airflow tasks and components from your local Airflow environment. This is useful if you want to troubleshoot a specific task instance, or if your environmen
```suggestion
You can use the Astro CLI to view logs for Airflow tasks and components from your local Airflow environment. This is useful if you want to troubleshoot a specific task instance, or if your environment suddenly stops working after a code change. See [View logs](view-logs.md).
```

2022-06-23 21:14 UTC, merged