Added New Write Data to the `/tmp` Directory Section
astronomer/docs pull request #836
Opened 2022-06-22 13:11 UTC by kwcanuck

Resolves #354 

@aspain I have created a preliminary draft of a new section titled _Write Data to the `/tmp` Directory_. I didn't have a lot of background information, so I did the best I could. Could you review the new content and provide your edits or approval? I would like your feedback and approval before it is peer reviewed.

2022-06-27 12:48 UTC, kwcanuck commented
@jwitz this is ready for your review.

2022-06-27 13:51 UTC, paolaperaza requested changes
@kwcanuck Thanks for picking this up -- definitely something we should document. The language in here all looks 💯, but I'm nervous that there's a little bit more context and framing we could and should include to best guide users on this.

There are a lot of ways to pass data between tasks or otherwise write temporary data on Astro, so I'd like to dig in one level deeper here to document a more comprehensive recommendation and set of details to describe how this actually works. Requesting changes just for that reason.

@aspain @frankcash Would love your guidance -- the more you guys can share on what you'd recommend to customers and how you understand this flow to work, the better. If there's really not more to it and my hesitation isn't warranted, let us know too

2022-06-27 13:51 UTC, paolaperaza commented on astro/develop-project.md
> +When you need to temporarily save data for testing or other purposes, you can create and save temporary files in the `/tmp` directory. As the name implies, the `/tmp` directory is a temporary locatio
@frankcash @aspain This may be a stupid question -- but where is actually is the `/tmp` directory? Is it something a user has to create? Reading this, a new user might think that a `/tmp` directory should be part of their Astro project.

Wondering how we frame this function between local development and on Astro. Is this a directory that exists on Astro by the nature of us running Airflow?

2022-06-27 13:51 UTC, paolaperaza commented on astro/develop-project.md
> +```
There are a lot of more production-ready ways to pass data between tasks, as showcased here: https://www.astronomer.io/guides/airflow-passing-data-between-tasks/

Do we think we should frame this method as "testing only"? What other limitations or benefits might be worth calling out to educate the user?

2022-06-27 13:51 UTC, paolaperaza commented on astro/develop-project.md
> +When you need to temporarily save data for testing or other purposes, you can create and save temporary files in the `/tmp` directory. As the name implies, the `/tmp` directory is a temporary locatio
Also, where is this data actually stored? In the metadata DB, or on workers, or something else?

2022-06-27 14:28 UTC, aspain commented on astro/develop-project.md
> +When you need to temporarily save data for testing or other purposes, you can create and save temporary files in the `/tmp` directory. As the name implies, the `/tmp` directory is a temporary locatio
@paolaperaza each of the containers (postgres, scheduler, triggerer, webserver) appear to have a `/tmp` folder out-of-the-box, but when we save files via tasks, they are placed on the workers. 

> Is this a directory that exists on Astro by the nature of us running Airflow?
yes

2022-06-27 15:02 UTC, kwcanuck commented on astro/develop-project.md
> +```
@aspain and @paolaperaza do you want to close this PR?

2022-06-29 10:56 UTC, kwcanuck reviewed
All edits submitted to date have been added.

2022-10-24 13:04 UTC, kwcanuck commented on astro/develop-project.md
> +```
@aspain and @paolaperaza this PR has been sitting for almost four months. Should I close it?

2022-11-24 14:41 UTC, kwcanuck commented
No response to direct Slack inquiry Monday, November 7, 2022. Closing for now as it hasn't been determined if this should move forward. It can reopened if it will proceed.

2022-11-24 14:41 UTC, closed without merging