Add Authorizing Astro Access to Amazon Web Services Resources
astronomer/docs pull request #878
Opened 2022-07-05 12:48 UTC by kwcanuck

Resolves #856

2022-07-05 12:50 UTC, kwcanuck commented
During the preliminary review process, @dnarain-astro discovered that the only way users can get the cluster ID is by contacting Astro Support. Deepak indicated that this information should be provided in the Cloud UI and that he would work to get this shortcoming addressed.

2022-07-05 21:50 UTC, jwitz requested changes
@kwcanuck A few questions in here, requesting changes mainly on the questions related to the trust policy editing steps. But overall the content looks good!

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +1. Create an AWS IAM role with a trust policy that allows access to a specific AWS resource. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/Use
```suggestion
1. Create an AWS IAM role with a trust policy that allows access to specific AWS resources. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html).
```
Pretty sure you can specify multiple resources in the policy

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +To allow Astro to access Amazon Web Services (AWS) resources, you need to define the resources that are accessible and then create an Airflow connection.
```suggestion
To grant an Astro cluster access to resources from other AWS services, you need to define the resources that are accessible and then create an Airflow connection.
```

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +```text
```suggestion
```text {8}
```

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +}
Is this section supposed to be here? Looks like the previous block but with Deepak's email 🤔 and if so, does this ARN value have to be updated as well?

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +```text
Cool Docusaurus feature lets you highlight lines in a code block: https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-metadata-string

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +6. Click **Edit trust policy** and update the `arn` value:
Update the `arn` value with what? Also, why didn't we do this to the trust policy in step 1?

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +8. Connect AWS to Airflow. See [Managing connections to Apache Airflow](https://docs.aws.amazon.com/mwaa/latest/userguide/manage-connections.html).
```suggestion
8. Create an Airflow connection to AWS for each Deployment that requires the resources you connected. See [Managing connections to Apache Airflow](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html).
```

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +8. Connect AWS to Airflow. See [Managing connections to Apache Airflow](https://docs.aws.amazon.com/mwaa/latest/userguide/manage-connections.html).
We probably don't want to use any AWS documentation related to Airflow, as that's mostly info which is exclusive to MWAA!

2022-07-05 21:50 UTC, jwitz commented on astro/connect-external-services.md
> +2. Contact [Astronomer support](https://support.astronomer.io) and request your cluster ID.
```suggestion
2. In the Cloud UI, open the **Clusters** tab and copy the cluster's **ID**.
```

2022-07-06 00:29 UTC, jwitz commented on astro/connect-external-services.md
> +2. Contact [Astronomer support](https://support.astronomer.io) and request your cluster ID.
Whoops scratch this, didn't realize the value was only available in dev environments!

2022-07-06 11:48 UTC, kwcanuck commented on astro/connect-external-services.md
> +## Authorize Astro access to Amazon Web Services resources
@jwitz it depends on the documentation, but Amazon does define the full name of the service occasionally. I try and follow the recommendation in the Microsoft Style Guide:

_**Avoid using an acronym for the first time in a title or heading**, unless it's a keyword that you need to place in the title or heading for SEO. If the first use of the acronym is in a title or heading, introduce the acronym (in parentheses, following the spelled-out term) in the following body text._

It seems that the Google Developer Style Guide allows acronyms to be used in titles, but states that writers should "...spell out the abbreviation in the first paragraph that follows the heading or title".

My preference is always to avoid acronyms in titles and define the acronym on first use. 

I have defined the acronym where it is first used, so we can use _AWS_ here.

2022-07-06 11:53 UTC, kwcanuck commented on astro/connect-external-services.md
> +1. Create an AWS IAM role with a trust policy that allows access to a specific AWS resource. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/Use
@jwitz good point. Fixed.

2022-07-06 11:56 UTC, kwcanuck commented on astro/connect-external-services.md
> +To allow Astro to access Amazon Web Services (AWS) resources, you need to define the resources that are accessible and then create an Airflow connection.
@jwitz I used _To grant an Astro cluster access to AWS service resources..._

2022-07-06 12:03 UTC, kwcanuck commented on astro/connect-external-services.md
> +}
@jwitz not sure why this still appears in the topic as it was removed previously. Good catch.

2022-07-06 12:08 UTC, kwcanuck commented on astro/connect-external-services.md
> +6. Click **Edit trust policy** and update the `arn` value:
@jwitz you need to create the IAM role and trust policy FIRST and then it can be modified. Also, a user won't have the cluster ID until it is provided by Astronomer support.

The placeholders identify what needs to be modified: dataplane-AWS-account-ID, role-name, and cluster-ID.  iT's clear when you follow the instructions.

2022-07-06 15:37 UTC, jwitz commented on astro/connect-external-services.md
> +6. Click **Edit trust policy** and update the `arn` value:
Yeah I think with the line highlighting now this is clear! Was a bit more confused when the other policy block was there, but it's all good now.

2022-07-06 15:37 UTC, jwitz approved these changes
LGTM!

2022-07-08 14:59 UTC, kwcanuck commented
@dnarain-astro this content is now ready for your review.

2022-07-12 22:57 UTC, dnarain-astro commented on astro/connect-external-services.md
> +1. Create an AWS IAM role with a trust policy that allows access to AWS resources. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_
Is it obvious that this needs to be done in their account or should we add "In the source AWS account, create an "?

We should link to this AWS document instead: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions_create-policies.html

The document you've linked shows how to delegate access to an AWS service, but we're going to be delegating access to a non-AWS service

2022-07-12 22:58 UTC, dnarain-astro commented on astro/connect-external-services.md
> +2. Contact [Astronomer support](https://support.astronomer.io) and request your cluster ID.
Do we need a screenshot of the new cloud UI? Or just saying that its available in the Clusters tab of the CloudUI sufficient?

2022-07-13 13:17 UTC, kwcanuck commented on astro/connect-external-services.md
> +To grant an Astro cluster access to AWS service resources, you need to define the resources that are accessible and then create an Airflow connection.
@dnarain-astro I have updated the text to:

_To grant an Astro cluster access to AWS service resources, you use AWS IAM roles to delegate access to the Astro cluster from the source account._

2022-07-13 13:19 UTC, kwcanuck commented on astro/connect-external-services.md
> +1. Create an AWS IAM role with a trust policy that allows access to AWS resources. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_
@dnarain-astro I have updated the text and the link.

2022-07-13 13:29 UTC, kwcanuck commented on astro/connect-external-services.md
> +To grant an Astro cluster access to AWS service resources, you need to define the resources that are accessible and then create an Airflow connection.
@dnarain-astro the text currently states:

_...for each Deployment..._

I think it's clear that an Airflow connection is required "per deployment". Also, we shouldn't be using _per_ in our documentation.

2022-07-13 20:34 UTC, dnarain-astro approved these changes

2022-07-13 22:13 UTC, dnarain-astro commented on astro/connect-external-services.md
> +To grant an Astro cluster access to AWS service resources, you use AWS IAM roles to delegate access to the Astro cluster from the source account.
I asked a friendly FE to walk through these steps for clarity and they weren't clear which account I meant when I said "source account".  Can we clarify this by saying "delegate access to the Astro Dataplane account from your account containing the data service". 

PS: I also realized we shouldn't be saying cluster - we want customers to think of Astro as a service running in an aws account (the cluster is an implementation detail)

2022-07-13 22:14 UTC, dnarain-astro commented on astro/connect-external-services.md
> +1. Create an AWS IAM role In the source AWS account with a trust policy that allows access to AWS resources. See [Creating roles and attaching policies (console)](https://docs.aws.amazon.com/IAM/late
Should we say Non-dataplane account to avoid any confusion which AWS account we are referring to?

2022-07-13 22:15 UTC, dnarain-astro commented on astro/connect-external-services.md
> +2. In the Cloud UI, click **Clusters** and then copy the value displayed **Cluster ID** column for the Astro cluster you want to delegate access to AWS service resources.
Astro UI (Cloud UI is what we call it internally)

2022-07-13 22:15 UTC, dnarain-astro commented on astro/connect-external-services.md
> +3. In the AWS Management Console, go to the Identity and Access Management (IAM) dashboard.
Clarify that its the non-dataplane account's AWS console

2022-07-14 12:26 UTC, kwcanuck commented on astro/connect-external-services.md
> +To grant an Astro cluster access to AWS service resources, you use AWS IAM roles to delegate access to the Astro cluster from the source account.
@dnarain-astro I have added the edit you requested.

2022-07-14 12:28 UTC, kwcanuck commented on astro/connect-external-services.md
> +1. Create an AWS IAM role In the source AWS account with a trust policy that allows access to AWS resources. See [Creating roles and attaching policies (console)](https://docs.aws.amazon.com/IAM/late
@dnarain-astro I have clarified the text.

2022-07-14 20:42 UTC, paolaperaza commented on astro/connect-external-services.md
> +## Authorize Astro access to AWS resources
```suggestion
## Use AWS IAM roles to authorize access to Astro
```

2022-07-14 20:43 UTC, paolaperaza commented on astro/connect-external-services.md
> +To grant an Astro cluster access to a service that is running in an AWS account not managed by Astronomer, use AWS IAM roles. IAM roles on AWS are often used to manage the level of access a specific
```suggestion
To grant an Astro cluster access to a service that is running in an AWS account not managed by Astronomer, use AWS IAM roles. IAM roles on AWS are often used to manage the level of access a specific user, object, or group of users has to a resource. This includes an Amazon S3 bucket, Redshift instance, or secrets backend.
```

2022-07-14 20:53 UTC, paolaperaza commented on astro/connect-external-services.md
> +2. Create an AWS IAM role in the AWS data service account that allows access to AWS resources. See [Creating roles and attaching policies (console)](https://docs.aws.amazon.com/IAM/latest/UserGuide/a
```suggestion
2. Create an IAM role in the AWS account that contains your AWS service. See [Creating a role to delegate permissions to an AWS service](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html).
```

2022-07-14 21:12 UTC, merged