Add Logging In Topics to Astro and Software Docs
astronomer/docs pull request #888
Opened 2022-07-06 16:44 UTC by kwcanuck

Resolves #871

2022-07-06 23:29 UTC, jwitz requested changes
Nice first draft @kwcanuck , dropped some suggestions and clarifications on both docs. Requesting changes on some of the Software CLI processes since they're a bit trickier than the Astro process!

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +2. Open a browser and go to your organization's Astronomer Software base domain.
```suggestion
2. Open a browser and go to `<basedomain>.astronomer.io`.
```
We only define a base domain later in the doc, should we add a line about it here?

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +3. Select one of the following options to access the Astronomer Software UI:
Same comment as in the Astro doc

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +You can use the Astronomer Software UI and the Astro CLI to view and modify your workspaces, clusters, environment variables, tasks, and users. Your user credentials need to be authenticated before y
Same thoughts here as in the Astro doc

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +1. Go to https://cloud.astronomer.io/ and create an Astronomer account.
Same thoughts here as in the Astro doc

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +In the Astro CLI you can run a local Airflow environment, apply code changes, view logs for all Airflow components, create deployments, and modify environment variables.
Same thoughts here as in the Astro doc

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +1. Install and configure the Astro CLI. See [Get started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started).
We should still link to the Software version of this doc, given that we still have weirdness between Software and Astro CLI versions/ usage: https://docs.astronomer.io/software/install-cli

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +3. Enter your email address and press **Enter**.
This process is a bit different for Software. If you have access to a Software environment you can try for yourself, but what generally happens is that:
1. astro login
2. The CLI prompts you for either your login credentials or a blank input. If you enter a blank input, you are provided a link for retrieving an Oauth token from your browser
3. You open the provided link to the Software UI in a web browser, log in using the Software UI (if you aren't logged in already), copy an OAuth token from the Software UI and paste that into the CLI. The screen with the Oauth token is only accessible from the link provided by the CLI
4. Enter either your username + password or the token into the CLI.

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +    If this is your first time logging in, the Astronomer Authorize App dialog appears. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.
This doesn't happen on Software

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +    astro login
```suggestion
    astro login <basedomain>
```

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +    astro context switch <basedomain>
You would probably want to run `astro context list` first to see what contexts are available before switching.

2022-07-06 23:29 UTC, jwitz commented on software/log-in-to-software.md
> +Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you're aut
```suggestion
Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another.
```
Let's not add too much about the benefits of this process, as the main beneficiaries are going to be Astronomer team members. Most customers will only have one domain/ product to worry about, and will not likely need to make use of the command like this.

2022-07-07 11:30 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    - To authenticate with your Google account, click **Continue with Google**, choose an account, enter your username and password, and then click **Sign In**.
@jwitz it should be _self-evident_ that some of the authentication options such as Okta need to be preconfigured. Providing the list of available options might help potential customers understand that they can continue to use their preferred authentication methodology if they choose Astro. Also, these are the options available in the UI and they should be documented.

2022-07-07 11:41 UTC, kwcanuck commented on software/log-in-to-software.md
> +3. Select one of the following options to access the Astronomer Software UI:
@jwitz see my previous response.

2022-07-07 12:08 UTC, kwcanuck commented on software/log-in-to-software.md
> +1. Go to https://cloud.astronomer.io/ and create an Astronomer account.
@jwitz see my previous response.

2022-07-07 12:10 UTC, kwcanuck commented on software/log-in-to-software.md
> +1. Install and configure the Astro CLI. See [Get started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started).
Done

2022-07-07 18:23 UTC, jwitz reviewed
@kwcanuck a few more replies here! I'll take one final pass after you respond.

2022-07-07 18:23 UTC, jwitz commented on astro/log-in-to-astro.md
> +1. Go to https://cloud.astronomer.io/ and create an Astronomer account.
I get that, but for the most part users can't create a standalone account [without first being invited](https://docs.astronomer.io/astro/add-user). I just tried creating an account with my personal email and ran into problems. 

As it stands, this step is not technically accurate. If we need "Create an account" docs in the future let's make those, but for now I think that step provides more confusion than guidance.

2022-07-07 18:23 UTC, jwitz commented on astro/log-in-to-astro.md
> +You can use the Cloud UI and the Astro CLI to view and modify your workspaces, clusters, environment variables, tasks, and users. Your user credentials need to be authenticated before you can use the
I get your perspective (especially after your time at Okta 😉 ), but I think the typical Astronomer user - someone who either is working with Python data pipelines or administrating a cloud service - is familiar with the value add of authentication. 

Additionally, most users utilize some sort of SSO for their log in. If they use this SSO on other products, then they're familiar with its importance and role in the enterprise ecosystem.

If we had individual user signups/ accounts this would be a different story, but all Astronomer users are part of tech-familiar organizations at the moment.

2022-07-07 18:23 UTC, jwitz commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run the `astro login x` command to authenticate to a base domain, and then run the `astro context switch x` command to define t
```suggestion
You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to define the default base domain on your machine. 
```
I prefer to use "machine" over "computer" because it's common for users to host multiple OSes/ environments on a single computer. They could also be running the CLI within a hosted environment that they have to access from their physical computer. We consider all of these environments machines, whether they're virtual or physical.

2022-07-07 18:23 UTC, jwitz commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run the `astro login x` command to authenticate to a base domain, and then run the `astro context switch x` command to define t
Actually I just noticed that this is not what we have in the style guide 🤔  maybe worth a discussion.

2022-07-07 18:23 UTC, jwitz commented on software/log-in-to-software.md
> +A base domain or URL (Uniform Resource Locator) is the static element of a website address. For example, when you visit the Astronomer website, the address bar always displays https://www.astronomer.
```suggestion
A base domain or URL (Uniform Resource Locator) is the static element of a website address. For example, when you visit the Astronomer website, the address bar always displays `https://www.astronomer.io` no matter what page you access on the Astronomer website.
```

2022-07-07 18:23 UTC, jwitz commented on software/log-in-to-software.md
> +Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you're aut
Right, I guess my thought is that we don't want to confuse Astro / Software users into thinking that this is more essential of a process than it is. 

If we keep the sentence, we need to change "cluster" to "installation" for Software. It might be better to also say "This is primarily used for" vs. "This can be useful for" so that it communicates "Hey, this is here for this purpose, and if you're not using it for that purpose then you probably don't need to be using it at all!"

2022-07-07 18:23 UTC, jwitz commented on astro/log-in-to-astro.md
> +Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you're aut
```suggestion
Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This is primarily used for working between Astro and Astronomer Software installations.
```
It's extremely unlikely that an Astro user will ever have to manage this.

2022-07-07 18:23 UTC, jwitz commented on software/log-in-to-software.md
> +    - Copy the OAuth token, paste it in the command prompt after **oAuth Token**, and then press **Enter**.
Should we remove these details because CLI tells you exactly what you need to do here? We could just say "Follow the CLI's instructions for your authentication method" or something like that

2022-07-07 18:49 UTC, kwcanuck commented on software/log-in-to-software.md
> +Every cluster is assigned a base domain. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you're aut
@jwitz I think the text is fine as is and becomes very awkward when it is changed to _This is primarily used for_. The definition of _useful_ is:

_**able to be used for a practical purpose** or in several ways._

I have changed _clusters_ to _installation_ in the software topic.

2022-07-07 18:53 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run the `astro login x` command to authenticate to a base domain, and then run the `astro context switch x` command to define t
@jwitz for your reference:

![image](https://user-images.githubusercontent.com/104205257/177850280-bdcc3794-b625-49e9-8e8c-4915b50e77e6.png)

![image](https://user-images.githubusercontent.com/104205257/177850385-b92164d2-7aa4-4491-b803-8b8106b4c359.png)

2022-07-07 18:57 UTC, kwcanuck commented on software/log-in-to-software.md
> +    - Copy the OAuth token, paste it in the command prompt after **oAuth Token**, and then press **Enter**.
@jwitz you're not explicitly told what to do. There are some instructions, but it's better to have the entire process documented. If we keep making assumptions and removing content, nothing will be left and there will be no point publishing this content.

2022-07-07 19:03 UTC, kwcanuck commented
@jwitz I have implemented or responded to your edit recommendations and the docs are now ready for your review.

2022-07-08 16:35 UTC, jwitz commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run the `astro login x` command to authenticate to a base domain, and then run the `astro context switch x` command to define t
> It's OK to use machine in content for technical audience and in content about virtualization to describe both physical machines and virtual machines.

Based on this definition, it seems like we _should_ be using machine no? Our product relies on multiple machines, both virtual and physical, in a single workflow. For example, on Software you might test an Airflow project on your local machine (computer), then push that project to a secure cloud environment where you can then deploy it from a virtual machine. 

When we say "Define the default basedomain on your computer", that doesn't account for the multitude of machine contexts that you can set the basedomain in. And given that most people using `astro context switch` are advanced technical users, I think they will understand what we mean by machine. There's enough leeway in this definition to justify the use here.

2022-07-08 16:36 UTC, jwitz commented on astro/log-in-to-astro.md
> +    If you're the first person in an Organization to authenticate, you're added as a Workspace Admin to a new Workspace named after your Organization. You can add other team members to the Workspace
```suggestion 
If you're the first person in an Organization to authenticate, you're added as a Workspace Admin to a new Workspace named after your Organization. You can then add other team members to the Workspace. See [Add a user](add-user.md).
```

2022-07-08 16:36 UTC, jwitz commented on astro/log-in-to-astro.md
> +    If you're the first person in an Organization to authenticate, you're added as a Workspace Admin to a new Workspace named after your Organization. You can add other team members to the Workspace
I don't think this needs to be indented because it's not a logical component of step 2.

2022-07-08 16:41 UTC, jwitz commented on astro/log-in-to-astro.md
> +
```suggestion

## Prerequisites 

- An Astronomer account.
- The [Astro CLI](cli/get-started.md)

```

2022-07-08 16:41 UTC, jwitz commented on astro/log-in-to-astro.md
> +1. Install and configure the Astro CLI. See [Get started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started).
If you take the suggestion about the prerequisites above, remove this.

2022-07-08 16:41 UTC, jwitz commented on software/log-in-to-software.md
> +1. Install and configure the Astro CLI. See [Get started with the Astro CLI](https://docs.astronomer.io/software/install-cli).
Same comment as in Astro

2022-07-08 16:45 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run the `astro login x` command to authenticate to a base domain, and then run the `astro context switch x` command to define t
@jwitz as a compromise, I recommend using "...define the default base domain on your computer and virtual machines". This addresses your concern and adheres to the recommended standard.

2022-07-08 16:49 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    If you're the first person in an Organization to authenticate, you're added as a Workspace Admin to a new Workspace named after your Organization. You can add other team members to the Workspace
@jwitz this information is considered a _step result_ (the result of an action a user completed).  Typically, step results are indented to align with the procedure step because they are part of the task; they are the outcome.

2022-07-08 17:16 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +1. Install and configure the Astro CLI. See [Get started with the Astro CLI](https://docs.astronomer.io/astro/cli/get-started).
Done

2022-07-11 16:00 UTC, paolaperaza reviewed
@kwcanuck Thank you for putting this together! Left some quick comments. I suspect we can share a bit more info on the details of the auth process on Astro given that it unfortunately confuses some users today.

Tagging @nicholasfilippi as well since he's been leading the evolution of the Astro Account. Nick, want to take a look at this PR when you get a chance? Would be good to get a review from @chomipi88 as well.

2022-07-11 18:16 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +You can use the Cloud UI and the Astro CLI to view and modify your workspaces, clusters, environment variables, tasks, and users. Your user credentials need to be authenticated before you can use the
@paolaperaza I removed _clusters_ and added _deployments_.

2022-07-11 18:18 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +- An Astronomer account.
@paolaperaza the linked topic is not how an account is created. Instead, it provides instructions for adding users. They are two different tasks.  Originally, I linked to an account creation topic, but Jake asked that I remove it.

2022-07-11 18:26 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +1. Go to `https://account.astronomer.io/`, enter your email address, and then click **Continue**.
@paolaperaza using https://cloud.astronomer.io/login takes you here:

![image](https://user-images.githubusercontent.com/104205257/178332038-39fd7e31-b831-4030-aa19-bc74d9e722a6.png)

Using https://account.astronomer.io/ takes you here:

![image](https://user-images.githubusercontent.com/104205257/178332206-72ec8009-3db2-451d-96fa-1059358f29e5.png)

The procedure recommends using https://account.astronomer.io/ because it is one less click (**Continue with your Astro Account**) and it's accurate. Test the two URLs and see the results.

2022-07-11 18:34 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    If this is your first time logging in, the Astronomer Authorize App dialog appears. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.
@paolaperaza I have gone through this process and the behavior is obvious. I don't think there is any need for screenshots.

2022-07-11 18:43 UTC, kwcanuck commented
@paolaperaza I have added or responded to your edit requests and questions. The doc is now ready for your review.

2022-07-13 05:42 UTC, paolaperaza reviewed
Ah sorry Rob, this one has to many tiny details. Back to you one more time. 🙏

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +3. Press **Enter** to connect your account to Astronomer.
```suggestion
3. Press **Enter** again to connect your account to Astronomer. This automatically opens a tab in your browser that prompts you to authenticate via the Cloud UI.

If this is your first time logging in on your device, the **Astronomer Authorize App** dialog appears in your browser. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.

Once authenticated, you will see confirmation in the Cloud UI and in the Astro CLI that your login was successful and that your device is now connected. The name of your default Workspace in the Astro CLI will also appear. To switch Workspace contexts after you log in, see [`astro workspace switch`](astro/cli/astro-workspace-switch.md).
```

- I think important to list this workspace command
- We're missing a step that accounts for actually entering your credentials?

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +
```suggestion
```

Made edits above

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +A base domain or URL is the static element of a website address. For example, when you visit the Astronomer website, the address bar always displays `https://www.astronomer.io` no matter what page yo
```suggestion

To use both Astro and Astronomer Software at the same time with the Astro CLI, you must authenticate to each product individually by specifying a corresponding base domain.

A base domain or URL is the static element of a website address. For example, when you visit the Astronomer website, the address bar always displays `https://www.astronomer.io` no matter what page you access on the Astronomer website.
```

Feels a little weird to start this section with an explanation of what a URL is and no context on why the user might be reading this -- took your approach of adding a need-based statement up top before diving in into the context.

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +Astronomer product offerings use unique base domains. For all Astro users, the base domain is `cloud.astronomer.io`. For Astronomer Software, every individual cluster is assigned a base domain and yo
```suggestion
For Astro users, the base domain is `cloud.astronomer.io`. For Astronomer Software, every individual cluster has a base domain that you must authenticate to in order to access it. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you need to move from an Astronomer Software installation to Astro and are using the Astro CLI to perform actions on both accounts.
```

- "unique base domain" isn't necessarily true across the board since Astro is all the same, I think let's just delete
- You don't get assigned a base domain! users pick it

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to define the
These steps seem off to me. I think this view is more reflective of expected UX, though admittedly it's not amazing yet:

> 1. To view the list of base domains that you have access to, run:
>    ```
>    astro context list
>    ```
>    This list will show only the base domains that you have connected to in the past from your current machine.
> 
> 2. To authenticate to a specific base domain, run:
>    ```
>    astro login <base-domain>
>    ```
>
> 3. To switch to that base domain, run:
>        ```
>        astro context switch <base-domain>
>        ```
>        This command is necessary to make sure that your CLI commands are run against the base domain that you just authenticated to.

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +    ```
Suggested alternative step order above -- 

- I wouldn't make `astro context list` last, though I can see the argument to make it the confirmation step. 
- If we do keep it, remove wording for "and to confirm your default base domain". I think the default base domain has to be set elsewhere, not here
- I think `astro context list` is important as a first command for the user to know, "ok where am I authenticated to right now and what base domains do I have access to"

2022-07-13 05:42 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to define the
I don't actually think the description of `astro context switch` is true -- https://docs.astronomer.io/astro/cli/astro-context-switch

I think it just literally switches you to it, but it doesn't permanently set it as default or anything. I think you do that elsewhere in the CLI

2022-07-13 15:27 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +3. Press **Enter** to connect your account to Astronomer.
@paolaperaza there have been so many edits, I'm losing track of who requested changes. I _think_ this information appeared in previous iterations of this doc, but it was removed. Sometimes, edits are being edited! 

I have verified the sequence:

1. In the Astro CLI, run the following command:

    ```sh
    astro login
    ```
2. Enter your email address and press **Enter**.

![image](https://user-images.githubusercontent.com/104205257/178767935-270e88f6-1a98-4f24-b1f4-f63071fe48c1.png)

3. Press **Enter** to connect your account to Astronomer.

![image](https://user-images.githubusercontent.com/104205257/178768220-e489bb3f-4034-4dcb-aace-7a3fc0056d7a.png)

4. Select one of the following options to access the Cloud UI:

![image](https://user-images.githubusercontent.com/104205257/178769614-de6ad597-b2ed-4509-94d1-ce37218dc1aa.png)

Success messages:

![image](https://user-images.githubusercontent.com/104205257/178771362-802d02fc-ea31-4a71-897d-80c496145d65.png)

![image](https://user-images.githubusercontent.com/104205257/178771557-fdcd6cae-88b6-4d7f-8c1f-132690cfb10d.png)

2022-07-13 15:30 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +
@paolaperaza this text describes different behavior than the . If a user has not logged in previously (ever) this is the sequence. At least it was when I tested it! ; )

2022-07-13 16:13 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to define the
@paolaperaza I have changed the sequence. I think the existing text works - I found some of the text you proposed confusing and hard to parse quickly. Happy to discuss it.

2022-07-13 16:15 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    ```
@paolaperaza as indicated in the previous comment, the sequence has been adjusted.

2022-07-13 16:17 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to define the
@paolaperaza the text has been updated.

2022-07-14 04:34 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +3. Press **Enter** to connect your account to Astronomer.
You're right! The steps here are what I'm seeing -- but it doesn't look like current status of the OR has them! We'd be missing step 3, which is "enter your user credentials" > login > continue.

Does that make sense?

2022-07-14 04:59 UTC, paolaperaza approved these changes
Alrighty @kwcanuck - a few comments here but I think it's been long enough. Will let you finish off! Thanks for doing the diligence here and bearing with me.

2022-07-14 04:59 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +    Confirmation messages appear in the Cloud UI and in the Astro CLI indicating that your login was successful and that your machine is now connected. The name of your default Workspace in the Astro
```suggestion
    Confirmation messages appear in the Cloud UI and in the Astro CLI indicating that your login was successful and that your device is now connected. The name of your default Workspace in the Astro CLI also appears. To switch Workspace contexts after you log in, see [astro workspace switch](https://docs.astronomer.io/astro/cli/astro-workspace-switch).
```

2022-07-14 04:59 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +
You are right! Also losing track of what state this was in when I commented. Apologies!

2022-07-14 04:59 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +You can authenticate to multiple domains from a single base domain. You run `astro login` to authenticate to a base domain, and then run the `astro context switch <basedomain>` command to switch to a
```suggestion
You can authenticate to multiple domains from a single base domain.
```

- Is this the same thing/repetitive with the steps?
- What do we mean by being able to authenticate to multiple domains from a single one? Do you just mean with the same Astro CLI?

2022-07-14 04:59 UTC, paolaperaza commented on astro/log-in-to-astro.md
> +1. Run the following command to view a list of base domains for all Astronomer installations that you can access and to confirm your default base domain:
```suggestion
1. Run the following command to view a list of Astronomer base domains that you have access to. The base domain that is highlighted in green is your current context.
```

2022-07-14 04:59 UTC, paolaperaza commented on sidebarsAstro.js
> +            'log-in-to-astro',
Had we said to put this doc in the "Get Started" menu? I think it makes more sense there -- this menu is supposed to be "admin" actions, and of course logging in is widely used

2022-07-14 04:59 UTC, paolaperaza commented on sidebarsSoftware.js
>          items: [
Same here actually? Also get started in software?

2022-07-14 04:59 UTC, paolaperaza commented on software/log-in-to-software.md
> +You can use the Astronomer Software UI and the Astro CLI to view and modify your workspaces, clusters, environment variables, tasks, and users. Your user credentials need to be authenticated before y
Port over Astro doc description we landed on? (Replacing w Software -- but same exact idea?

2022-07-14 04:59 UTC, paolaperaza commented on software/log-in-to-software.md
> +
Probably need to add a line that these options are only available if you configure them. Link to: https://docs.astronomer.io/software/integrate-auth-system

2022-07-14 04:59 UTC, paolaperaza commented on software/log-in-to-software.md
> +Use the Astro CLI to [deploy code to Astro](https://docs.astronomer.io/astro/deploy-code) and create and manage Deployments. Astronomer uses refresh tokens to make sure that you don’t need to log in
Copy Astro description here?

Also, this is a link to deploy code doc in Astro, not Software

2022-07-14 04:59 UTC, paolaperaza commented on software/log-in-to-software.md
> +When you need to access Astro and Astronomer Software with the Astro CLI at the same time, you need to authenticate to each product individually by specifying a base domain for each Astronomer instal
```suggestion
To access multiple installations of Astronomer Software with the Astro CLI at the same time, you need to authenticate to each cluster individually by specifying its base domain. This is also applicable if you are using both Astro and Astronomer Software. 
```

Something more like this for Software?

2022-07-14 04:59 UTC, paolaperaza commented on software/log-in-to-software.md
> +For Astro users, the base domain is `cloud.astronomer.io`. For Astronomer Software, every cluster has a base domain that you must authenticate to in order to access it. If your organization has multi
```suggestion
For Astronomer Software, every cluster has a base domain that you must authenticate to in order to access it. If your organization has multiple clusters, you can run Astro CLI commands to quickly move from one base domain to another. This can be useful when you need to move from an Astronomer Software installation to Astro and are using the Astro CLI to perform actions on both accounts.
```

2022-07-14 12:53 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    Confirmation messages appear in the Cloud UI and in the Astro CLI indicating that your login was successful and that your machine is now connected. The name of your default Workspace in the Astro
@paolaperaza does this text refer to a computer? If so, our style guide indicates that _computer_ should be used and not _device_. jake appears to prefer machine despite on style guide stating:

Most of the time, don't use _machine_ to mean a computer. Use _computer_ instead.

2022-07-14 12:58 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +1. Run the following command to view a list of base domains for all Astronomer installations that you can access and to confirm your default base domain:
@paolaperaza I didn't see a a "base domain highlighted in green". Also, we shouldn't be using color references for accessibility reasons. I have modified the text you requested.

2022-07-14 13:07 UTC, kwcanuck commented on sidebarsAstro.js
> +            'log-in-to-astro',
@paolaperaza in a discussion in a our stand up we agreed on the current location for these topics. I have moved them to the location you requested.

2022-07-14 13:12 UTC, kwcanuck commented on sidebarsSoftware.js
>          items: [
@paolaperaza I have relocated the topic.

2022-07-14 13:15 UTC, kwcanuck commented on software/log-in-to-software.md
> +You can use the Astronomer Software UI and the Astro CLI to view and modify your workspaces, clusters, environment variables, tasks, and users. Your user credentials need to be authenticated before y
@paolaperaza with all the edits, it's extremely challenging keeping everything synchronized. This edit has been implemented.

2022-07-14 13:19 UTC, kwcanuck commented on software/log-in-to-software.md
> +
@paolaperaza done.

2022-07-14 14:34 UTC, jwitz approved these changes
@kwcanuck Some final comments, otherwise LGTM! Throw it back to me if you have any questions about my suggestions surrounding Software authentication flow

2022-07-14 14:34 UTC, jwitz commented on astro/log-in-to-astro.md
> +You can use the Cloud UI and the Astro CLI to view and modify your workspaces, deployments, environment variables, tasks, and users. You need to authenticate your user credentials when you're using t
```suggestion
You need to authenticate your user credentials when you're using the Cloud UI or the Astro CLI for development on Astro. After you authenticate, you can view and modify your Workspaces, Deployments, environment variables, tasks, and users. 
```

2022-07-14 14:34 UTC, jwitz commented on astro/log-in-to-astro.md
> +    If this is your first time logging in, the Astronomer Authorize App dialog appears. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.
```suggestion
    If this is your first time logging in from the Astro CLI, the Astronomer Authorize App dialog appears. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.
```

2022-07-14 14:34 UTC, jwitz commented on astro/log-in-to-astro.md
> + 4. Select one of the following options to access the Cloud UI:
If you're already logged into the Cloud UI, this step won't happen. The CLI will recognize your UI credentials and immediately log you in. Should we account for that in docs? A user might not see this screen and think that something went wrong with their authentication.

2022-07-14 14:34 UTC, jwitz commented on astro/log-in-to-astro.md
> +When you need to access Astro and Astronomer Software with the Astro CLI at the same time, you need to authenticate to each product individually by specifying a base domain for each Astronomer instal
```suggestion
To access Astro and Astronomer Software with the Astro CLI at the same time, you need to authenticate to each product individually by specifying a base domain for each Astronomer installation.
```

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +You can use the Astronomer Software UI and the Astro CLI to view and modify your workspaces, deployments, environment variables, tasks, and users. You need to authenticate your user credentials when
Same (general) comment here as in the Astro doc

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +- The [Astro CLI](cli/get-started.md)
```suggestion
- The [Astro CLI](cli/get-started.md).
```
My preference would be no punctuation on lists this small, but it's your call.

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +    - To authenticate with your GitHub account, click **Log in with GitHub**, and then follow the prompts.
I thought I had commented on this before, but for a lot of users only a few of these options will appear based on how the organization has configured IdP. Offering some alternative wording at the start of the step, but at a minimum we should remove this bulleted list entirely.

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +2. Select one of the following options to access the Astronomer Software UI:
```suggestion
2. Log in to the Software UI using one of the authentication methods that has been configured by your organization.
```

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +When you need to access multiple installations of Astronomer Software with the Astro CLI at the same time or you need to use Astro and Astronomer Software at the same time, you need to authenticate t
```suggestion
To access multiple installations of Astronomer Software with the Astro CLI at the same time or use Astro and Astronomer Software at the same time, you need to authenticate to each cluster individually by specifying its base domain. 
```

2022-07-14 14:34 UTC, jwitz commented on software/log-in-to-software.md
> +2. Select one of the following options to access the Astronomer Software UI:
Uncapitalizing organization here because it's in the Software context, where organization is not an RBAC entity.

2022-07-14 14:40 UTC, kwcanuck commented on astro/log-in-to-astro.md
> +    If this is your first time logging in, the Astronomer Authorize App dialog appears. Click **Accept** to allow Astronomer to access your profile and email and allow offline access.
@jwitz this text appears in a task titled _Log in to the Astro CLI_. I don't think this clarification is necessary.

2022-07-14 14:42 UTC, kwcanuck commented on astro/log-in-to-astro.md
> + 4. Select one of the following options to access the Cloud UI:
@jwitz we can't account for every scenario. If a user doesn't see what is described and logs in successfully, they will understand the behavior move on.

2022-07-14 14:45 UTC, kwcanuck commented on software/log-in-to-software.md
> +- The [Astro CLI](cli/get-started.md)
@jwitz is this preference documented in our style guide? If not, it should be. Also, it's easier for writers to follow a standard when it's implemented consistently. You've been using punctation in lists elsewhere, so it should be applied here.

2022-07-14 14:46 UTC, kwcanuck commented on software/log-in-to-software.md
> +    - To authenticate with your GitHub account, click **Log in with GitHub**, and then follow the prompts.
@jwitz you can argue about this with @paolaperaza . She asked that I add the information again. I'm not removing it a second time! :)

2022-07-14 14:47 UTC, kwcanuck commented on software/log-in-to-software.md
> +2. Select one of the following options to access the Astronomer Software UI:
@jwitz again, these capitalization standards are hard to follow and implement consistently.

2022-07-14 14:54 UTC, merged

2022-07-14 15:57 UTC, jwitz commented on software/log-in-to-software.md
> +    - To authenticate with your GitHub account, click **Log in with GitHub**, and then follow the prompts.
Is this the comment you are talking about? https://github.com/astronomer/docs/pull/888#discussion_r920748984

I don't interpret this as "add the login information back in". I think she's asking for the additional sentence on line 30 of this PR "To integrate an identity provider (IdP) with Astronomer Software, see [Integrate an auth system on Astronomer Software](integrate-auth-system.md)."

This is separate from my comment, which is that this bulleted list should be cut entirely because no user will ever see all these options - especially InternalOkta, which is only for testing purposes.

2022-07-14 16:23 UTC, kwcanuck commented on software/log-in-to-software.md
> +    - To authenticate with your GitHub account, click **Log in with GitHub**, and then follow the prompts.
@jwitz sorry, I'm confused by you statement. The text you have identified already appears in the topic. I don't think we need to add this twice.

**Software:**

![image](https://user-images.githubusercontent.com/104205257/179030028-13e66d7f-b9cd-4408-bfd2-1dd0b429efa1.png)

**Astro:**

![image](https://user-images.githubusercontent.com/104205257/179030262-b11fda94-e2b5-45db-8b04-5bb8cf3fa76f.png)

Perhaps I don't understand the issue? Also, Paola asked that I list the identity providers as they appear in the UI.