Terraform fixes
astronomer/docs pull request #89
Opened 2020-12-02 21:02 UTC by jwitz

Definitely closes https://github.com/astronomer/issues/issues/1883, and potentially closes https://github.com/astronomer/issues/issues/1626. If there's a really popular specific use case that utilizes this kind of configuration (that people might search for in Google :)) let me know!

2020-12-04 13:40 UTC, paolaperaza requested changes
@jwitz Lookin good here! Made some comments - will look back in here later today so we can wrap this up. Once we're ready, I'd also love @vparekh94 or @ianstanton to look over these changes if either of them have a spare min.

2020-12-04 13:40 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +Run the following command to create a new file called `config.yaml`:
Users who are making changes/modifying should already have created a `config.yaml`, but I do agree it's good to give users some guidance if for whatever reason that's not the case.

I'd say something like:

> First, make your config changes to your existing `config.yaml` file as necessary. For an example file that includes all values you could override, refer to our [Houston API source code](https://github.com/astronomer/houston-api/blob/main/config/default.yaml).
> 
> If you're just getting started with Astronomer and don't have that file created yet, refer back to our installation guide for your cloud provider.
> 
> - [AWS](https://www.astronomer.io/docs/enterprise/v0.16/install/aws/install-aws-standard#6-configure-your-helm-chart)
> - [GCP](https://www.astronomer.io/docs/enterprise/v0.16/install/gcp/install-gcp-standard#7-configure-your-helm-chart)
> - [Azure](https://www.astronomer.io/docs/enterprise/v0.16/install/azure/install-azure-standard#6-configure-your-helm-chart)

2020-12-04 13:40 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 2. Open the new file and reconfigure the variables.
I'd scrap this section and bring up some of the content in here to the section above. Looks like there are 2 files users could modify:

- https://github.com/astronomer/astronomer/blob/master/values.yaml
- https://github.com/astronomer/houston-api/blob/main/config/default.yaml

Maybe explain the difference between the two and otherwise I think the process here is the same, though I could be missing something. Also - both of these repos will be private soon if not already, so it may be tricky to link to that `/astronomer/astronomer` source code.

We have some files copied over to the docs repo for exactly this reason, so I actually think this is what we should be linking out to - https://github.com/astronomer/docs/tree/main/enterprise/v0.16/reference

2020-12-04 13:40 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +Astronomer is deployed on Kubernetes with the [Helm](https://helm.sh) package manager. After completing your installation with Terraform, we recommend updating your configuration through Helm as desc
I'd actually try to be a bit more specific here on when users should use Terraform and when they should make config changes with Helm, since it sounds like it causes a decent amount of confusion.

Expand this section with another sentence or two mayb?

2020-12-04 13:43 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Populate a .yaml file with your current configuration.
(If we end up talking about two files here instead of just `config.yaml`, mental note to modify this title then

2020-12-04 14:14 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Deployment-level---
No idea! 0_o Thanks for catching it.

2020-12-04 14:16 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +
Definitely - what happened here was I was accidentally working in this branch on some Airflow alerts stuff. To fix that, I copied from `main` back into this branch, so none of this is new content (though it probably appears as such here).

2020-12-04 14:18 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify Your Current Platform Version
Sounds good - This feature is only available in v0.16+ right? Because that's the only place this topic appears at the moment.

2020-12-04 14:21 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Astronomer Configuration Without Upgrading
Went even simpler with this: "Update Your Platform Configuration"

2020-12-04 14:58 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +If you want to reconfigure specific variables used on your Astronomer platform, such as resource allocation limits, you can do so without upgrading to a new version.
Sounds good - Updated the text for this.

2020-12-04 14:59 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Populate a .yaml file with your current configuration.
Ah I see, didn't realize that `config.yaml` use was common across our docs and essential to installation.

2020-12-04 15:00 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +Run the following command to create a new file called `config.yaml`:
Do we still want to leave the helm command in there if they've somehow lost the file, or need it updated with their org's current values? Also, how do we feel about using the word 'organization' for Enterprise customers?

2020-12-04 15:01 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 2. Open the new file and reconfigure the variables.
I decided to just link out to the last file here and avoided explaining the difference between those repos. And instead of referring to 'source code' (since that's going private), I used the phrase 'default configuration file'.

2020-12-04 15:03 UTC, jwitz commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +Astronomer is deployed on Kubernetes with the [Helm](https://helm.sh) package manager. After completing your installation with Terraform, we recommend updating your configuration through Helm as desc
I can be more firm with our prescription on using Helm, but based on what Kris told me we really don't want people using Terraform after installation. I'll defer to @vparekh94 or @ianstanton on that though, since I'm definitely not familiar with Terraform usage.

2020-12-04 17:52 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify Your Current Platform Version
Good question - I'd think it applies to versions lower than 0.16 but I'm not 100% sure - I'd have @ianstanton double check on this.

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +You can reconfigure your Astronomer platform without upgrading your Astronomer version using Helm. This is useful for [integrating an Auth system](https://www.astronomer.io/docs/enterprise/v0.16/mana
I'd add some "umph"/a little more context here here and remove `reconfigure` (sort of implies that you're doing something "again" which isn't really the case) -

> There are a few ways to customize Astronomer to fit the needs of your team. For example, you may choose to:
> - Integrate an Auth System
> - Change resource allocation limits
> - Add a registry backend
>
> To apply the platform configuration changes above and any others that exclude the initial installation and Astronomer version upgrades, follow the steps below.
> 

Sidenote: I think there's an extra space in the `change resource allocation limits` link - can't tell for sure but just double check the url is tied to the description.

Alsoooo I'm a big fan of bullet points/lists to break things up visually if there's every 2+ items on something. WDYT?

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Open your `config.yaml` file.
Do we want to standardize on adding `.` in H4s? I'd opt to _not_ + I think that's the case in most other docs, but maybe double check and let's make sure we standardize that

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
Still thinking about dis title - I might like `Customize` your Platform Configuration even more actually? Users here are typically coming here to make relatively permanent changes to make x thing work better for them or to leverage x feature or functionality - not so much "updating" stuff.

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +```
Curious to get @ianstanton's thoughts but I actually wouldn't add these instructions here - customers should 100p only be coming to this doc if they've already installed the platform.

If they don't have a `config.yaml` file that means they didn't follow install instructions and should go back there to follow our entire guidelines around getting this file created with the right default values and what not

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +To update any of your existing key-value pairs, simply modify the existing value in `config.yaml`. To update a setting that hasn't yet been configured, copy the .yaml key-value pair you want to updat
> `To update any of your existing key-value pairs, simply modify the existing value in `config.yaml`

This sounds a bit awk. I'd say maybe -

> To override any existing key-value pairs, modify them directly in your `config.yaml` file. To add a new set of values that you don't specify already, copy the corresponding key-value pair from the default configuration file into your own `config.yaml` and modify the value from there.
>
> Once you've changed all necessary key-value pairs, make sure they're in the exact same order and indentation as those listed in the default configuration file we provided above. An indentation error could cause a value to not be properly applied.


GREAT call specifying that users make sure things are indented correctly - you'd be surprised how many people mess that up + subsequently don't see their changes applied once they run helm uprade.

2020-12-04 18:21 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +
Make sure we standardize spacing - here it looks like there's a full line before the command but in the following instruction the command goes in the line directly under it.

I'd defer to keeping a line in between, so:

> Run this:
>
> `$ blah blah`

2020-12-04 19:45 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Open your `config.yaml` file.
I think we should definitely use a period for steps, especially if we aren't going to capitalize steps as titles. For other h4 usages though (such as titles) I agree that we shouldn't use periods.

2020-12-04 19:51 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
I think `Customize` is too strong of a word for what users are doing here, which is updating the values of variables which are pre-determined in the system. I associate customization more with personal changes built *on top* of existing infrastructure, for instance if someone could write and deploy their own key-value pairs. Would `Reconfigure Your Platform` work?

2020-12-04 19:52 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
Or `Configure`, based on your comment above.

2020-12-04 20:07 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +You can reconfigure your Astronomer platform without upgrading your Astronomer version using Helm. This is useful for [integrating an Auth system](https://www.astronomer.io/docs/enterprise/v0.16/mana
As long as we add an extra bullet point for the default config file, I think bullets work. While I'm usually in agreement about their ability to break things up, I think bulleted lists have a connotation of comprehensively mapping the possible options for something, which is why I didn't originally use it. I think the version in my new commit looks good!

Updated that last sentence to the "Cellar Door" of technical documentation: "To do so:"

2020-12-04 20:10 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +```
If they will be more successful by just using the file generated in those installation processes, then I agree we should remove this part.

2020-12-04 20:23 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +
Done! Agreed on this formatting.

2020-12-04 20:27 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +To update any of your existing key-value pairs, simply modify the existing value in `config.yaml`. To update a setting that hasn't yet been configured, copy the .yaml key-value pair you want to updat
Put my spin on this, but agreed that it needed some tightening up - thanks!

2020-12-04 22:07 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +Astronomer is deployed on Kubernetes with the [Helm](https://helm.sh) package manager. After completing your installation with Terraform, we recommend updating your configuration through Helm as desc
@jwitz Yea, I think for that same reason I think it's worth re-iterating that here just to be _extra_ clear that Enterprise customers should not be using Terraform following the platform install

2020-12-04 23:45 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify Your Current Platform Version
Actually, sorry - yes! This section applies to the "patch upgrade" instructions, which are only available and only apply for 0.16.x - they should also be in the `/next` folder though.

2020-12-07 14:24 UTC, jwitz commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +Astronomer is deployed on Kubernetes with the [Helm](https://helm.sh) package manager. After completing your installation with Terraform, we recommend updating your configuration through Helm as desc
Just made a commit for this comment in v0.16. Will push to the rest of the versions if you think it's sound!

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
@jwitz It looks like the instructions to upgrade patch versions in this doc are not numbered and don't have periods. Since we're modifying this doc as a whole, do you want to apply the formatting from the section below here as well to make sure we're standardizing, at least within the same file?

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
@jwitz I'm looking at our ["Integrate an Auth System" doc](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/integrate-auth-system) and it looks like the command listed there is:

`$ helm upgrade <platform-release-name> -f config.yaml --version=<platform-version> astronomer/astronomer -n <your-namespace>`

I think the command you have listed does the same thing, but it looks like we should:

1. Specify that `--version=<your current version>` --> `--version=<platform-version>` (users have a lot of versions to deal with, so we should specify "version of what")
2. We may have also assumed `platform-release-name` and `your-namespace`

Maybe verify with @ianstanton real quick on technical accuracy, but if both are accurate maybe just replace the command you have here with the one from the other doc.

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
It also looks like other docs have users run:

```
$ helm ls --namespace <your-namespace>
```

Maybe add?

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
+ consider an example:

> For example, if you're running Astronomer v0.16.10 and your platform release name is `astronomer`, you might run:
> 
> ```
> $ helm upgrade astronomer -f config.yaml --version=0.16.10 astronomer/astronomer -n astronomer
> ```

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
```suggestion
$ helm3 get values -n <namespace> <platform-release-name>
```

2020-12-07 14:44 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +* [Azure AKS Installation Guide](https://www.astronomer.io/docs/enterprise/v0.16/install/azure/install-azure-standard#6-configure-your-helm-chart)
```suggestion
This file was created when you installed Astronomer using one of the following guides:

* [AWS EKS Installation Guide](https://www.astronomer.io/docs/enterprise/v0.16/install/aws/install-aws-standard#6-configure-your-helm-chart)
* [GCP GKE Installation Guide](https://www.astronomer.io/docs/enterprise/v0.16/install/gcp/install-gcp-standard#7-configure-your-helm-chart)
* [Azure AKS Installation Guide](https://www.astronomer.io/docs/enterprise/v0.16/install/azure/install-azure-standard#6-configure-your-helm-chart)
```

2020-12-07 14:47 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +Run the following command to create a new file called `config.yaml`:
@jwitz Resolving this convo since I think you covered this change. I do like the term "organization" - don't think it's specific to Enterprise versus Cloud though for the most part.

I also really like using "team" + would prob use that over organization since at the Enterprise level we work with a lot of different _teams_ within "organizations" (companies) - and each team might have different setup/platform installed.

2020-12-07 14:49 UTC, paolaperaza commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +Astronomer is deployed on Kubernetes with the [Helm](https://helm.sh) package manager. After completing your installation with Terraform, we recommend updating your configuration through Helm as desc
@jwitz Perfect yes just saw your commit - that looks great!

2020-12-07 14:50 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +You can reconfigure your Astronomer platform without upgrading your Astronomer version using Helm. This is useful for [integrating an Auth system](https://www.astronomer.io/docs/enterprise/v0.16/mana
Great point on the bullet lists - add that to the style guide! Not something I would've been thinking about. I'm cool with your changes here!

2020-12-07 14:51 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Open your `config.yaml` file.
Ah ok, so period for steps but not necessarily all H4s ✅  That sounds good - add to style guide!

2020-12-07 14:52 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
@jwitz Oh yea that's super fair pushback on the "Customize". How about: `Configure Platform Settings`?

2020-12-07 14:58 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +* [Azure AKS Installation Guide](https://www.astronomer.io/docs/enterprise/v0.16/install/azure/install-azure-standard#6-configure-your-helm-chart)
(Just added a space here)

2020-12-07 19:42 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
Could we do `Configure Platform Settings Between Upgrades`? I'm worried that if we don't mention upgrades in the title, the section will look a little out of place in the `Upgrade Astronomer` section.

2020-12-07 19:43 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
Ah yeah, didn't realize these were steps haha. I'll format these in v0.16

2020-12-07 19:55 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
Seems like the commands can be run in any order, since the one I wrote is how Kris ran it on his terminal, but I def think it's best to be consistent across usages. 

I like having the hyphen names for the user-entered variables. How do you feel about always prefixing `your-` to any variable name if it needs to be added by a user?

2020-12-07 19:56 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
Did this but added `your-` to the variable name.

2020-12-11 18:12 UTC, ianstanton requested changes

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.12/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
These commands will vary depending on the minor version they are running. I believe we introduced helm 3 support in 0.15, so if they are on 0.13 or below the commands will slightly differ (I see this doc is on the 0.12 page).

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.13/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
These commands will vary depending on the minor version they are running. I believe we introduced helm 3 support in 0.15, so if they are on 0.13 or below the commands will slightly differ (I see this doc is on the 0.13 page).

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
Change `helm3` to `helm`

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
The command directly above uses namespace and release-name `astronomer`. We can assume the same here and change both `<namespace>` and `<release name of astronomer>` to `astronomer`.

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
We should mention here that this example command assumes the `namespace` and `release-name` are both `astronomer`. A customer may have different values.

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n <your-namespace> upgrade <your-platform-release name> astronomer/astronomer --version=<your-platform-version> -f config.yaml
We give this example in this `v0.16` doc, but I didn't see it in the others.

2020-12-11 18:12 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm upgrade astronomer -f config.yaml --version=0.16.10 astronomer/astronomer -n astronomer
Not the worst thing in the world, but I noticed the `helm` example commands are written in different order. This won't hurt functionality, but it would be good to choose one command format for us to stick with across all docs.

2020-12-11 18:48 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 list --all-namespaces | grep astronomer
Sounds good, changing this across all instances you mention. I noticed we use "shell session" coloring on this command but not others. Is that appropriate for all helm commands? For reference, here's what it looks like on our website. 
![Screen Shot 2020-12-11 at 12 47 55 PM](https://user-images.githubusercontent.com/74574233/101942418-b871ae80-3ba6-11eb-81ce-2d3354372c62.png)

2020-12-11 18:54 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
How likely is it that customers will have different values here? If it's anything more frequent than "extremely rare", then it's probably better for us to use pointy brackets with generic values rather than `astronomer` across all uses of the command (ie. `<namespace>` and `<release name of astronomer>`)

2020-12-11 18:55 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
We could simply add a line that says "Note that for most customers, <namespace> and <release name of astronomer> will both be the default value of Astronomer" or something like that

2020-12-11 19:06 UTC, jwitz commented
Thanks for the feedback @ianstanton! I should've told you this before, but I'm using v0.16 as the working directory for any changes (just pushed changes there) - after review, I'll push those changes to the rest of the files. Based on your review, I have a few more questions:

* What would the commands look like for v0.12 and v0.13 (that you mentioned would be different)?
* Is it appropriate to use "Shell session" styling on these commands?
* Can we provide more guidance on how customers can find their namespace and platform release name? I took the example out, because I realized it's not easy to parse when both the namespace and release name are "astronomer". It's probably better for us in the long-run to use pointy brackets whenever there's a user-entered value in a command.

2020-12-15 15:07 UTC, jwitz commented on enterprise/v0.13/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
What are the specific commands we should use in earlier versions?

2020-12-15 15:07 UTC, jwitz commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
Resolving based on comments elsewhere.

2020-12-15 15:07 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n <your-namespace> upgrade <your-platform-release name> astronomer/astronomer --version=<your-platform-version> -f config.yaml
Resolving based on comments elsewhere

2020-12-15 15:08 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm upgrade astronomer -f config.yaml --version=0.16.10 astronomer/astronomer -n astronomer
Nice call, this should be fixed in the latest version!

2020-12-15 15:08 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
Resolving based on comments elsewhere

2020-12-15 15:08 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer> >config.yaml
Resolving based on comments elsewhere

2020-12-15 15:09 UTC, jwitz commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
Decided that this was a confusing example, so updated these commands to only use generic variables. Is there more info we can provide on where they can find their `namespace` and `release-name`, or should those things be self-evident?

2020-12-15 20:42 UTC, ianstanton commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 list --all-namespaces | grep astronomer
@jwitz Yep, you can use shell session coloring with these commands for consistency.

2020-12-15 20:43 UTC, ianstanton commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
It's not rare for a customer to use different values here.

2020-12-15 20:51 UTC, ianstanton commented on enterprise/v0.13/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm3 get values -n <namespace> <release name of astronomer>
The earlier versions (that use helm 2) will not use a `-n` (namespace) flag. Example: `helm get values astronomer -n astronomer` becomes `helm get values astronomer` if using helm 2.

2020-12-15 20:57 UTC, ianstanton commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
Namespace _should_ be self-evident. You can list all namespaces on your kubernetes cluster with `kubectl get ns`, but it is up to the customer to know which they used to install Astronomer. Release name can be found with `helm ls -n <namespace>`.

2020-12-15 21:41 UTC, ianstanton commented
@jwitz 

> * What would the commands look like for v0.12 and v0.13 (that you mentioned would be different)?

Astronomer v0.12 and v0.13 used Helm 2. In Helm 2, releases were not scoped at the  namespace level. Here are some example command translations (helm 3 -> helm 2):

`helm get values -n <namespace> <release name of astronomer> > config.yaml`
becomes
`helm get values <release name of astronomer> > config.yaml`

`helm list --all-namespaces | grep astronomer`
becomes
`helm list | grep astronomer`

`helm -n <your-namespace> upgrade <your-plarform-release-name> astronomer/astronomer --version=<your-platform-version> -f config.yaml`
becomes
`helm upgrade <your-plarform-release-name> astronomer/astronomer --version=<your-platform-version> -f config.yaml`

> * Is it appropriate to use "Shell session" styling on these commands?

These are shell commands, so I would say it is appropriate. Check the format of similar commands across the website to ensure consistency (If you think we shouldn't be using them _anywhere_, that's fine.)


> * Can we provide more guidance on how customers can find their namespace and platform release name? I took the example out, because I realized it's not easy to parse when both the namespace and release name are "astronomer". It's probably better for us in the long-run to use pointy brackets whenever there's a user-entered value in a command.

This will be determined on initial installation. For example, a user could decide to use `astro-prod-1` as their namespace and `astro` as their release name (`helm install astro -f config.yaml astronomer/astronomer -n astro-prod-1`). A user can list all helm releases on the cluster with `helm ls -A`. They can also list all namespaces on the cluster with `kubectl get ns`. If they forget where they installed Astronomer, they'll be able to look at the pods in each namespace and determine which they used.

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Ensure you have a copy of your Astronomer config.yaml file.
@jwitz How do we want to standardize "steps"? Do we want to list `### Step 1: Ensure...` as we do in Cloud Quickstart? If so, let's make sure that's the case across the board for this doc

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Ensure you have a copy of your Astronomer config.yaml file.
Also, if I'm reading correctly - is this an H4 under an H2?

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +You can configure platform-wide settings without needing to upgrade Astronomer versions. Using Helm, any of the settings your platform uses, including ones available in the Astronomer UI, can be upda
```suggestion
You can configure platform-wide settings without needing to upgrade Astronomer versions. Using Helm, any of the settings your platform uses can be updated through a few simple commands. For example, you can use Helm to:
```

Platform configuration changes aren't really the ones that show up in the Astronomer UI, so I'd say it's weird to call out that example here. I'd just leave it as ^that

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +If you don't know the value for `<your-platform-release-name>`, you can find it by running `helm ls -n <your-namespace>`.
```suggestion
If you don't know the value for `<your-platform-release-name>`, find it by running:

`$ helm ls -n <your-platform-namespace>`
````

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n <your-namespace> upgrade <your-platform-release-name> astronomer/astronomer --version=<your-platform-version> -f config.yaml
I'd specify `<your-platform-namespace>` here - individual deployments have namespaces and then the platform has a namespace, so worth specifying I think

2020-12-16 01:26 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +## Update Your Platform Configuration
Since this comment thread is outdated I'm resolving and following up in 0.16 file!

2020-12-16 01:27 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
Made a separate comment on this, but should we be adding `Step 1:` like we do in Cloud Quickstart? Or do we not want to standardize that?

2020-12-16 01:31 UTC, paolaperaza requested changes

2020-12-16 01:31 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n <your-namespace> upgrade <your-platform-release-name> astronomer/astronomer --version=<your-platform-version> -f config.yaml
@jwitz Following up on a different comment, but I'm still seeing this command be different than the ones we have in other docs. Should it be:

```
$ helm upgrade <your-platform-release-name> -f config.yaml --version=<your-current-platform-version> astronomer/astronomer -n <your-platform-namespace>
```

2020-12-16 01:35 UTC, paolaperaza commented on enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
@jwitz I think this is a good tid-bit - since this is the "source of truth" on how to run these commands, I think we should add these examples so people have the right values. Can you add:

- Guidance on how to find namespace
- Guidance on how to find Astronomer Release Name

2020-12-16 01:37 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n astronomer upgrade astronomer astronomer/astronomer --version=<your current version> -f config.yaml
@jwitz Looks like you went down the route of adding brackets with fill-in variables since it's very common for customers to have platform namespace + platform release name _not_ as `astronomer`

2020-12-16 14:19 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
I went with more formal steps for the Quickstart because people just getting started might appreciate something a little more detailed and clean for an initial install. Also, because of the various substeps for each step, I thought having a more distinguished structure for the top-level steps would make it easy to follow. In the future, a potential standard we could establish is writing out `Step` if it's at the h2 level and writing only the number at the h3 level. Let me know what you think about that!

2020-12-16 14:36 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +#### 1. Ensure you have a copy of your Astronomer config.yaml file.
Good catch, updated headings throughout the document. Got a bit of tunnel vision with Ian's comments, so I hadn't updated this doc to match the style guidelines we've since put in place. Updating that now!

2020-12-16 14:39 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +You can configure platform-wide settings without needing to upgrade Astronomer versions. Using Helm, any of the settings your platform uses, including ones available in the Astronomer UI, can be upda
Sounds good! Updated in latest commit.

2020-12-16 14:45 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +If you don't know the value for `<your-platform-release-name>`, you can find it by running `helm ls -n <your-namespace>`.
Made both suggestions for finding values into a single tip box, since it's not necessarily essential to the actual step we're describing. Before, it looked like you should have run those commands **after** running the main command.

2020-12-16 15:09 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +$ helm -n <your-namespace> upgrade <your-platform-release-name> astronomer/astronomer --version=<your-platform-version> -f config.yaml
Going forward, should we have a style for commands? I could see having commands + subcommands coming first, followed by all flags in alphabetical order. I tried this for the two commands in this section of the doc, let me know if you think it works.

2020-12-16 15:25 UTC, jwitz commented
Thanks for the comments @paolaperaza ! All changes based on your comments are in commit e0eb87e485e16ae9481e442e35bd0f0c2301b146. I also responded to a few comments with some potential style guide additions to consider.

2020-12-21 17:13 UTC, paolaperaza reviewed
@jwitz I just added a few final comments! Per our conversation in Slack, a few things:

- Let's split out everything that follows "Configure Platform Settings Between Upgrades" to a new, standalone doc in the "Manage Astronomer" section of the Enterprise menu. It can be called something like, "Apply a Platform Configure Change." This doc should be present only in the `0.16` and `/next` folders.
- Let's standardize adding `your` to reference of `config.yaml`
- Check out my comments on the helm commands at the end of this doc

I'll loop back so we can finally finish this off! Thanks.

2020-12-21 21:44 UTC, jwitz commented on enterprise/next/03_install/01_aws/02_install-aws-terraform.md
> +We recommend using Terraform only for your initial installation of Astronomer. Afterwards, all post-install upgrades and configurations to Astronomer should be completed using the [Helm](https://helm
For Next docs, should we assume that relative links will increment the file structure like so? Wasn't sure whether to use 0.17 in the filepath or `next`.

2020-12-21 21:45 UTC, jwitz commented
@paolaperaza created the new docs! Since the doc is only a single process with steps, I used the same step naming conventions we used for the Quickstart guide. Added one small question about using relative filepaths for `Next` Enterprise docs, but other than that this should be good to go.

2020-12-22 16:02 UTC, paolaperaza requested changes

2020-12-22 16:02 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
@jwitz It looks like this `/next` file for "Upgrade Astronomer" doesn't have the same format as 0.16  - did we want to apply the steps method?

2020-12-22 16:02 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### 1. Ensure You Have a Copy of Your Astronomer config.yaml File
@jwitz Did we decide on bringing this down to not capitalized title since it's an H3?

2020-12-22 16:02 UTC, paolaperaza commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +We're working on a more robust and reliable upgrade process for our next Astronomer Enterprise "Long-term Support" quarterly release scheduled for Winter 2020.
```suggestion
We're working on a more robust and reliable upgrade process for our next Astronomer Enterprise "Long-term Support" quarterly release scheduled for Winter 2021.
```

2020-12-22 18:02 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +- How to apply a platform configuration change
Yep!

2020-12-22 18:03 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +We're working on a more robust and reliable upgrade process for our next Astronomer Enterprise "Long-term Support" quarterly release scheduled for Winter 2020.
Fixing for both this doc and in 0.16

2020-12-22 18:04 UTC, jwitz commented on enterprise/next/06_manage-astronomer/06_configure-platform.md
> +title: "Configure Your Astronomer Platform"
Good call, I like that reasoning. Updated!

2020-12-22 18:11 UTC, jwitz commented on enterprise/next/06_manage-astronomer/06_configure-platform.md
> +> **Tip:** The value for `<your-platform-namespace>` can be found in your list of active namespaces. To show this list, run:
Agreed it'd be nice to have CSS styling differentiating the two. I always considered a Note to be something that can cause a reader reconsider or alter their setup actions. I styled this as a tip since it's not really necessary to read if you already know what these names are, and it's not really specific to the setup either. For something this size, I like categorizing it as a tip so readers don't read through assuming it's essential for setup.

2020-12-22 18:18 UTC, jwitz commented on enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
> +### Verify your Current Platform Version
Yep, got focused on the new doc and forgot to update the Upgrade doc with new standards as well. Good catch

2020-12-22 18:18 UTC, jwitz commented on enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
> +### 1. Ensure You Have a Copy of Your Astronomer config.yaml File
Yep, got focused on the new doc and forgot to update the Upgrade doc with new standards as well. Good catch

2020-12-22 18:21 UTC, jwitz commented
Thanks @paolaperaza, all version info and titling should be accurate now!

2020-12-22 19:07 UTC, paolaperaza commented on enterprise/next/06_manage-astronomer/06_configure-platform.md
> +> **Tip:** The value for `<your-platform-namespace>` can be found in your list of active namespaces. To show this list, run:
Good call - I'm in for that!

2020-12-22 23:35 UTC, paolaperaza approved these changes
Alright, @jwitz ! I think we are finally done with this one. Huge thanks for the thoughtfulness in our back-and-forths - I'm confident in this last iteration.

Let's ship!

2020-12-23 00:01 UTC, merged