Add Datadog Integration Topic to Software Docs
astronomer/docs pull request #896
Opened 2022-07-08 14:46 UTC by kwcanuck

Resolves #883

2022-07-08 17:33 UTC, jwitz approved these changes
Some minor suggestions, but overall LGTM!

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +   ```
```suggestion
    ```yaml
    datadog:  
      confd:
        openmetrics.yaml: |-
          instances:
            # The airflow statsd endpoint to query from
            - prometheus_url: http://<deployment-release-name>-statsd.<platform-namespace>.svc:9102/metrics
              namespace: "<platform-namespace>"
              metrics:
                - "*"
    ```
```

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +2. Open the `values.yaml` file and add this entry:
```suggestion
2. Open the [Datadog `values.yaml` configuration file](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml) and add a new configuration under `datadog.confd.openmetrics.instances` for each Deployment you want to integrate with Datadog:
```

I know that Astronomer's config file is called `config.yaml`, but it might still be helpful to distinguish this as the Datadog helm chart.

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +   ```
I'm pretty sure this is what these values are referenced as in our public docs, with the Deployment release name being for Deployments only (https://docs.astronomer.io/software/configure-deployment#customize-release-names) and the release name being where the entire Astronomer platform is installed (we recommend customers use `astronomer` for this during their install).

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +2. Open the `values.yaml` file and add this entry:
This is a bit of an awkward phrasing because we tell customers to "Integrate Datadog with Software", but the actual integration is on a per-Deployment basis. Maybe it makes more sense to frame this doc in the context of integrating a Deployment instead of the entire platform? Your call

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +3. Optional. Add additional entries for your other Airflow instances. For example:
If we frame this doc in the context of integrating a single Deployment, I agree that this is optional. But a Software user is likely to get all of this configuration done at once and "forget it" if they're configuring at a platform level, in which case configuring multiple Deployments would not be optional. 

My preference would be to frame the setup as "do this for each Deployment you want to integrate with Datadog", meaning that we would only have one non-optional example of how to add multiple Deployments to the configuration. This is likely how Software admins will use this feature.

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +          namespace: "<airflow-release-namespace>"
```suggestion
        # The airflow statsd endpoint to query from
        - prometheus_url: http://<first-deployment-release-name>-statsd.<platform-namespace>.svc:9102/metrics
          namespace: "<platform-namespace>"
          metrics:
            - "*"
        - prometheus_url: http://<second-deployment-release-name>-statsd.<platform-namespace>.svc:9102/metrics
          namespace: "<platform-namespace>"
```

2022-07-08 17:33 UTC, jwitz commented on software/integrate-datadog.md
> +   ```
Also, is it worth telling people how to retrieve their Deployment release names here? It's available in the Software UI under settings:
![Screen Shot 2022-07-08 at 11 28 16 AM](https://user-images.githubusercontent.com/74574233/178041323-92622043-6836-45ff-a6ea-6ba33adaae9e.png)

Come to think of it I should probably document this somewhere other than the CLI reference guide, which is the only place that content is available 😬

2022-07-08 17:36 UTC, kwcanuck commented on software/integrate-datadog.md
> +Integrate your Datadog instance with Astronomer Software to view Airflow metrics in Datadog. These metrics can include running DAG (Directed Acyclic Graphs) processes, task data, pool data, and execu
@jwitz force of habit. As discussed previously, acronyms are always defined on first use. If the Astronomer standard is not to define _DAG_ on first use, it should be noted in the style guide.

2022-07-08 17:42 UTC, kwcanuck commented on software/integrate-datadog.md
> +3. Optional. Add additional entries for your other Airflow instances. For example:
@jwitz I disagree. I think the procedure is presented correctly in its current form. If Software users want to configure multiple Deployments at once, I think it's clear how this can be accomplished. We're both making assumptions about the audience. My experience tells me this is the better option. If you feel strongly about a change, we can discuss it.

2022-07-08 17:42 UTC, stuart23 requested changes

2022-07-08 17:42 UTC, stuart23 commented on software/integrate-datadog.md
> +Integrate your Datadog instance with Astronomer Software to view Airflow metrics in Datadog. These metrics can include running DAG processes, task data, pool data, and executor data. To view a comple
```suggestion
Integrate your Datadog account with Astronomer Software to view Airflow metrics in Datadog. These metrics can include running DAG processes, task data, pool data, and executor data. To view a complete list of the Airflow metrics collected by the Datadog Agent, see [Data Collected](https://docs.datadoghq.com/integrations/airflow/?tabs=host#data-collected). 
```

DD is SaaS. The customer does not have an instance.

2022-07-08 17:42 UTC, stuart23 commented on software/integrate-datadog.md
> +5. Optional. Run the following command to confirm your confuguration changes were implemented:
```suggestion
5. Optional. Run the following command to confirm your configuration changes were implemented:
```

2022-07-08 17:48 UTC, stuart23 requested changes

2022-07-08 17:48 UTC, stuart23 commented on software/integrate-datadog.md
> +5. Optional. Run the following command to confirm your configuration changes were implemented:
```suggestion
5. Optional: Confirming your configuration changes were implemented. First find the Datadog agent pod using `kubectl get pods -n datadog`, and then use the run the following command:
```

The pod name below is dynamic

2022-07-08 17:48 UTC, stuart23 commented on software/integrate-datadog.md
> +    kubectl exec -it dd-test-datadog-f4vhx -n astronomer -- bash -c 'agent status' Defaulting container name to agent.
```suggestion
    kubectl exec -it <dd-test-datadog pod name> -n astronomer -- bash -c 'agent status' Defaulting container name to agent.
```

Pod name is dynamic

2022-07-08 17:48 UTC, stuart23 commented on software/integrate-datadog.md
> +    kubectl exec -it dd-test-datadog-f4vhx -n astronomer -- bash -c 'agent status' Defaulting container name to agent.
@rbankston is `dd-test` templated from the release name??

2022-07-08 18:12 UTC, kwcanuck commented on software/integrate-datadog.md
> +   ```
@jwitz I added this statement below the procedure step and command example:

_To locate the Deployment release name, select a Deployment in Astronomer Software and copy the value displayed in the **Release Name** field._

2022-07-08 20:44 UTC, stuart23 commented
Please hold on for a moment - I am not happy with this section yet. Just following up with Viraj about where `dd-test` comes from.
![image](https://user-images.githubusercontent.com/8843676/178067583-cccf01cd-834f-49c9-bb86-7099d72c323d.png)

2022-07-09 01:00 UTC, stuart23 commented
Sorry for hijacking your PR @kwcanuck - I wasn't happy with the optional step and so I broke it out into a tip callout. Please let me know your thoughts

2022-07-11 11:18 UTC, kwcanuck commented
@stu

2022-07-11 15:02 UTC, stuart23 commented
This should live somewhere that is locatable from google.

I am just trying to advocate for the customer here, who had a pretty frustrating experience trying to get to these instructions that we have readily available.

2022-07-11 15:59 UTC, cmarteepants commented
@stuart23 Sure, I get that. Docs are not the right place, and I'm not approving this. Forum posts show up on google, that is the most appropriate location for now.

2022-07-12 14:21 UTC, kwcanuck commented
@stuart23 and @cmarteepants as this information won't be added to the documentation, can I close this PR? @stuart23 perhaps you can create a forum post for this content?

2022-07-15 11:35 UTC, kwcanuck commented
Closing this PR as the content that was created will not appear in the documentation. @stuart23 or @cmarteepants to determine an alternate methodology for providing the content to users.

2022-07-15 11:35 UTC, closed without merging