Cloud alerts
astronomer/docs pull request #90
Opened 2020-12-02 21:29 UTC by jwitz

Closes https://app.zenhub.com/workspaces/docs-5fb535258b4e61000eac76cf/issues/astronomer/issues/2283. Technical reviewers, please help me answer the following questions: 

- Could any of the alerts benefit from more detailed information on the conditions that fire the alerts? For instance, is it helpful to define the 'acceptable rate' for a heartbeat in the AirflowSchedulerUnhealthy alert? What is the actual storage limit for temporary data? 
- Are the follow-up steps for each alert accurate? I'm particularly worried about which resource allocations I tell people to adjust in the follow-ups that mention Airflow 2.0.
- Should we tell customers to mention anything specific when following the 'Contact your Astronomer representative' follow-up?

2020-12-03 18:57 UTC, jwitz commented
Adding @wolfier and @krisdock for review per @paolaperaza's recommendation. I'd really appreciate your review on the follow-up actions, which are new for this draft and might save us some support ticket effort in the future.

2020-12-07 15:24 UTC, paolaperaza requested changes
Thanks for this @jwitz! I just left a few comments here. I'm mostly not confident in approving the recommended action items since I'm not as familiar with all of these use cases - will lean on you @krisdock @wolfier.

The more specific we can be of what is happening, the better - how much Memory/CPU? What's the max ephemeral storage?

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Refer to the following chart for more information on each deployment-level alert you might receive from Astronomer, as well as follow-up steps for improving the health of your affected Deployments.
```suggestion
Refer to the chart below for more information on each Deployment-level alert you might receive from Astronomer, as well as corresponding remediation steps we recommend for your affected Deployment.
```

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowDeploymentUnhealthy` | The Airflow Deployment is unhealthy or not completely available. | Contact your Astronomer representative. |
```suggestion
| `AirflowDeploymentUnhealthy` | The Airflow Deployment is unhealthy or not completely available. | Reach out to [Astronomer Support](https://support.astronomer.io). |
```

Astronomer Cloud users/customers don't have a "representative" since our CS team doesn't have enough dedicated resources to reach all of them directly (and they likely won't be able to respond in an actionable way to notice of these alerts either), so I think our best bet is to send these folks to our support team.

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowEphemeralStorageLimit` | The Airflow Deployment is nearing its limit for storing temporary data. | Ensure that you are continually removing unused temporary data in your Airflow tasks. |
```suggestion
| `AirflowEphemeralStorageLimit` | The Airflow Deployment is nearing its limit for storing temporary data. | Make sure to continually remove unused temporary data in your Airflow tasks. |
```

Or even: 

`Remove unused temporary data in your Airflow tasks.`

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowSchedulerUnhealthy` | The Airflow scheduler's heartbeat has dropped below the acceptable rate. | Contact your Astronomer representative. |
```suggestion
| `AirflowSchedulerUnhealthy` | The Airflow scheduler's heartbeat has dropped below the acceptable rate. | Reach out to [Astronomer Support](https://support.astronomer.io). |
```

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
Yikes really not sure what the recommended action item is here, so double check with @wolfier or @krisdock here - these guidelines sound like they're more telling you what's happening and what "should" happen but not so much how to get there.

When we mention `Server resources` though - is it Webserver, Scheduler, or Worker AU's they have to increase?

2020-12-07 15:24 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | The Airflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 10 minutes. | Either increase the Deployment's al
Do we know what the memory quota is? The Airflow Webserver just parses DAG files and powers the Airflow UI so I'm not immediately seeing a connection - maybe just double check? Is it Webserver, Scheduler or Worker resources that would help? Or some combination?

2020-12-07 19:17 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Deployment-level---
Done!

2020-12-07 19:29 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +Refer to the following chart for more information on each deployment-level alert you might receive from Astronomer, as well as follow-up steps for improving the health of your affected Deployments.
Made a different suggestion on this, since I realized this my original wording is grammatically inconsistent (the follow-up step _is_ more information, so we are not showing that "as well as" more information). Also tied to make it more active.

2020-12-07 19:37 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
Whoops - I meant to write Webserver Resources there. And yeah, I agree we shouldn't move forward with this until Allan or Kris get eyes on it.

2020-12-08 17:26 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowPodQuota` | The Airflow Deployment is near its pod quota; it's been using over 95% of it's pod quota for over 10 minutes. | Either increase the Deployment's allocated Webserver and Schedule
Assuming this was for the `AiflowPodQuota`. Should this be the only follow-up to recommend the Extra Capacity slider, rather than the allocated resources sliders?

2020-12-08 17:27 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | The Airflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 10 minutes. | Either increase the Deployment's al
Sounds good! Updated

2020-12-08 17:29 UTC, krisdock commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowPodQuota` | The Airflow Deployment is near its pod quota; it's been using over 95% of it's pod quota for over 10 minutes. | Either increase the Deployment's allocated Webserver and Schedule
@jwitz correct. the resource sliders are specific to cpu/mem on the specific related components (webserver, scheduler, workers). the only thing that affects the pod quota is the extra capacity slider.

2020-12-08 18:43 UTC, wolfier commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | The Airflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 10 minutes. | Either increase the Deployment's al
@jwitz, you should check the actual [prometheus alerts](https://prometheus.gcp0001.us-east4.astronomer.io/rules) to verify the definition. For example `ContainerMemoryNearTheLimitInDeployment` is the collection of all the pods with some exceptions.

```
 (container_memory_working_set_bytes{container=~".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)",container_name!~"POD|istio-proxy"} / container_spec_memory_limit_bytes{container=~".*(scheduler|scheduler-gc|webserver|worker|statsd|pgbouncer|metrics-exporter|redis|flower)",container_name!~"POD|istio-proxy"}) * 100 > 95 < +Inf
```

I would ask someone on infra to help you understand what those metrics mean.

2020-12-08 18:54 UTC, wolfier commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
Server resources is most likely referring to the scheduler since the scheduler is what pushes the tasks through its lifecycle. However, since tasks are going into the scheduled/queued state that means the scheduler is functioning correctly most likely. The executor could be at fault for not sending the tasks to the workers.

The more likely scenario is that the worker does not have the ability to consume the tasks from the queue. Then the solution becomes increasing worker productivity* for the Executor, which are generally KubernetesExecutor or CeleryExecutor.

Increasing worker productivity is a subject for another day ;p 

Basically tuning the worker/scheduler would resolve this alert and I don't think it's as simple as bumping resources.

2020-12-08 19:52 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | The Airflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 10 minutes. | Either increase the Deployment's al
Sounds good! Updated all of the inaccurate thresholds in the latest pull

2020-12-08 20:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowPodQuota` | The Airflow Deployment is near its pod quota; it's been using over 95% of it's pod quota for over 10 minutes. | Either increase the Deployment's Extra Capacity in the Astronomer
Typo on `over 95% of it's pod quota` --> `over 95% of its pod quota`

2020-12-08 20:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowSchedulerUnhealthy` | The Airflow scheduler's heartbeat has dropped below the acceptable rate. | Reach out to [Astronomer Support](https://support.astronomer.io). |
```suggestion
| `AirflowSchedulerUnhealthy` | The Airflow Scheduler's heartbeat has dropped below the acceptable rate. | Reach out to [Astronomer Support](https://support.astronomer.io). |
```

I think we typically capitalize Scheduler + Webserver - maybe something to standardize? Do we know what the acceptable rate of the heartbeat is?

2020-12-08 20:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
- Should this be "If your tasks _aren't_ running as expected, increase...."?
- What resources should they modify?
- Instead of "Redesign your DAGs" I'd say -  "Lower Airflow Concurrency or Parallelism so that fewer tasks are concurrently pending."

2020-12-08 20:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
Could maybe even link out to: https://www.astronomer.io/guides/airflow-scaling-workers

2020-12-08 20:32 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | A container in your Aiirflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 60 minutes. | Either increase th
typo on "it's" v" its"

2020-12-08 20:33 UTC, paolaperaza commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | A container in your Aiirflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 60 minutes. | Either increase th
(on `ContainerMemoryNearTheLimitInDeployment`)

2020-12-08 20:57 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowTasksPendingIncreasing` | The Airflow Deployment is creating tasks faster than it's clearing them. | Ensure that your tasks are running and completing correctly. If your tasks are running a
I think they should do these things if their tasks _are_ running as expected, eg. their DAGs are properly creating and running tasks, but there still isn't enough resources to handle the number of pending tasks they have. 

Based on the article you linked out, I assume that the allocated resource they need to update will vary based on how they decide to increase concurrency/parallelism. In that case, I thin kit makes sense to link out to the guide for more information.

2020-12-08 20:57 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `ContainerMemoryNearTheLimitInDeployment` | A container in your Aiirflow Deployment is near its memory quota; it's been using over 95% of it's memory quota for over 60 minutes. | Either increase th
Fixed!

2020-12-08 21:00 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowSchedulerUnhealthy` | The Airflow scheduler's heartbeat has dropped below the acceptable rate. | Reach out to [Astronomer Support](https://support.astronomer.io). |
Good to know, I'll add that to the style guide.

It looks to be "no heartbeat for more than one minute" based on this line in the Prometheus code: `rate(airflow_scheduler_heartbeat{type="counter"}[1m]) == 0`
I'll add that in!

2020-12-08 21:04 UTC, jwitz commented on cloud/stable/04_customize-airflow/04_airflow-alerts.md
> +| `AirflowPodQuota` | The Airflow Deployment is near its pod quota; it's been using over 95% of it's pod quota for over 10 minutes. | Either increase the Deployment's Extra Capacity in the Astronomer
bleh, fixed

2020-12-08 22:28 UTC, paolaperaza approved these changes
Awesome @jwitz - this final round looks good to me!

2020-12-08 22:30 UTC, merged