Add New Documentation for Installing Astro on Azure
astronomer/docs pull request #928
Opened 2022-07-19 13:41 UTC by kwcanuck

Resolves #915, resolves #916, resolves #917, resolves #918

2022-07-19 13:46 UTC, kwcanuck commented
@dnarain-astro preliminary drafts of the new documentation for installing Astro on Azure are now ready for your review. The documentation requires a thorough technical review and there are many places where existing GCP or AWS information has been left as placeholders. When performing your review, please compare the content to the existing AWS and GCP topics to make sure important information is not missing. If you need help locating the existing topics, let me know. Also, if you prefer to meet to discuss your edits, send me a Slack message with your availability.

@jwitz no need for your review yet. I'll let you know when this content is ready for your review.

2022-07-19 17:17 UTC, melugoyal commented on astro/install-azure.md
> +- A minimum quota of 40 standard DDv5 series vCPUs. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/per
i'm not sure that using v4 for the system node pools and v5 for the worker node pools was a cautious/intended/correct decision. maybe we should revisit this and it'll also simplify the docs. cc @goutamtadi1

2022-07-19 17:17 UTC, melugoyal commented on astro/install-azure.md
> +- An Azure user with Owner permissions. See [Azure built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-roles).
do we want to specify "Owner permissions for the intended subscription" or maybe that's implied?

2022-07-19 17:17 UTC, melugoyal commented on astro/install-azure.md
> +- Optional. Your custom CIDR ranges for Astronomer service connections. The default is 72.20.0.0/19.
this should be `172.20.0.0/19`

2022-07-19 17:17 UTC, melugoyal commented on astro/install-azure.md
> +If you don't specify a preferred configuration for your organization, Astronomer support creates a cluster in `us-central1` with the default configurations for Astro on Azure. See [Azure resource ref
this looks like a gcp region. should be `centralus`?

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +- An Azure Subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported.
We use the words "clean" for AWS, but not for GCP - in retrospect we should have had on GCP as well .  Should we add clean Azure subscription here?

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +- An Azure user with Owner permissions. See [Azure built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-roles).
The same user should have both permissions.  The right verbiage would be: An Azure Active Directory user with the following role assignments: 
* Azure AD Builtin Role "Application Administrator"
* Azure Bultin Role "Owner" with the assignable scope set to the entire subscription

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +- Microsoft Azure Cloud Shell or PowerShell.
Its Azure CLI (I started with cloud shell, but then forgot to update the doc as I moved to az cli).  FYI, the azure cloud shell is just a shell with the Azure CLI installed, so this covers both scenarios - Azure CLI installed on my laptop, or Cloud Shell

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +- A minimum quota of 16 standard DDv4 series vCPUs. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/per
We haven't figured out the quota requirements yet, so expect this number to change in the near future.

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +        {label: 'Azure Cloud Shell', value: 'azure'},
Same comment as before - we can say Azure CLI (which is a superset of the cloud shell) because the instructions were expanded to cover both cases

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +
This adds the Astronomer Service Principal to their Azure Active Directory (even though the command says create - it really isnt a create but an add)

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +    ```
I see you've broken out each line into its own section (I don't know what to call it!), but on GCP we just put all the related commands into the same section so it was one copy/paste operation.  Not sure which is correct (I prefer having it all together so its one copy), but I wanted to point out the inconsistency between the docs.

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +    while [ $(az feature list --query "[?contains(name, 'Microsoft.Compute/EncryptionAtHost')].{State:properties.state}" -o tsv) != "Registered" ] do
Grr this whole syntax got ruined in the copy from shell->notion. This can't be copy pasted as is :-(

There should be <CR> before and after "sleep 60" 

```
while [ $(az feature list --query "[?contains(name, 'Microsoft.Compute/EncryptionAtHost')].{State:properties.state}" -o tsv) != "Registered" ]
do
echo "Still waiting for Feature Registration (EncryptionAtHost) to complete, this can take up to 15 minutes"

sleep 60

done
```

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +    az provider register --namespace Microsoft.Compute
Same comment as easier about the blocks/sections - should this be in the same section as the rest of the script?

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +        {label: 'Powershell', value: 'powershell'},
I see that Microsoft calls it PowerShell (P and S are capitalized) FYI

2022-07-20 01:26 UTC, dnarain-astro commented on astro/install-azure.md
> +    Register-AzProviderFeature -FeatureName EncryptionAtHost -ProviderNamespace Microsoft.Compute while ( (Get-AzProviderFeature -FeatureName EncryptionAtHost -ProviderNamespace Microsoft.Compute).Re
This too got completely ruined in the tranffer from shell->notion->markdown. there should be a <CR>/newline before while

2022-07-20 13:34 UTC, kwcanuck commented on astro/install-azure.md
> +- An Azure user with Owner permissions. See [Azure built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-roles).
@dnarain-astro I have updated the text. It has been modified for readability and to match the language used by Microsoft.

2022-07-20 13:35 UTC, kwcanuck commented on astro/install-azure.md
> +- Optional. Your custom CIDR ranges for Astronomer service connections. The default is 72.20.0.0/19.
@melugoyal this edit has been implemented.

2022-07-20 13:36 UTC, kwcanuck commented on astro/install-azure.md
> +If you don't specify a preferred configuration for your organization, Astronomer support creates a cluster in `us-central1` with the default configurations for Astro on Azure. See [Azure resource ref
@dnarain-astro can you confirm this edit?

2022-07-20 13:41 UTC, kwcanuck commented on astro/install-azure.md
> +- Activate your Astro data plane by registering Azure features and adding the Astronomer Service Principal to your subscription.
@dnarain-astro I've done my best with the information you've provided. This text will probably need further refinement.

2022-07-20 13:46 UTC, kwcanuck commented on astro/install-azure.md
> +- An Azure Subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported.
@dnarain-astro I have added "clean" to the text.

2022-07-20 13:51 UTC, kwcanuck commented on astro/install-azure.md
> +- A minimum quota of 16 standard DDv4 series vCPUs. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/per
@dnarain-astro please provide this information when you have it.

2022-07-20 13:54 UTC, kwcanuck commented on astro/install-azure.md
> +
@dnarain-astro this change has been implemented.

2022-07-20 13:56 UTC, kwcanuck commented on astro/install-azure.md
> +    ```
@dnarain-astro I have updated the documentation as requested.

2022-07-20 13:59 UTC, kwcanuck commented on astro/install-azure.md
> +    az provider register --namespace Microsoft.Compute
@dnarain-astro sorry, I'm not clear what edit you are requesting, Can you edit the code sample directly and I'll commit your changes.

2022-07-20 14:19 UTC, chomipi88 commented on astro/install-azure.md
> +If you don't specify a preferred configuration for your organization, Astronomer support creates a cluster in `centralus` with the default configurations for Astro on Azure. See [Azure resource refer
This is linking to a GCP doc

2022-07-20 14:30 UTC, kwcanuck commented on astro/install-azure.md
> +- A clean Azure Subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported.
@chomipi88 I've done my best with the wording. It might need additional refinement.

2022-07-20 14:33 UTC, kwcanuck commented on astro/install-azure.md
> +## Step 2: Activate the data plane
@chomipi88 this is the heading used in the AWS and GCP docs. I have updated it to _Prepare for data plane activation_, but it's now inconsistent with the other documentation.

2022-07-20 14:35 UTC, chomipi88 commented on astro/install-azure.md
> +- A clean Azure Subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported.
@dnarain-astro thoughts on the phrasing here?

For security reasons, Azure subscriptions with existing tooling running and/or Azure Policies aren't supported.

2022-07-20 14:35 UTC, kwcanuck commented on astro/install-azure.md
> +If you don't specify a preferred configuration for your organization, Astronomer support creates a cluster in `centralus` with the default configurations for Astro on Azure. See [Azure resource refer
@chomipi88 good catch. This has been updated.

2022-07-20 14:37 UTC, kwcanuck commented on astro/resource-reference-azure.md
> +sidebar_label: "Azure resource reference"
@chomipi88 you're correct! I currently don't have those details. Can you or @dnarain-astro provide them?

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +    az provider register --namespace Microsoft.Compute
Ignore it, I meant to add this to the Powershell section but added it here as well.

2022-07-20 18:29 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +sidebar_label: "Azure resource reference"
Yes, will do in the other doc.

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subsciption must include an Azure management group that doesn't apply
```suggestion
- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be include an Azure management group that doesn't apply Azure policies. See [What are Azure management groups?](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview).
```
```suggestion
- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be included in an Azure management group that doesn't apply Azure policies. See [What are Azure management groups?](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview).
```

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +- An Azure AD user with the following role assignemnets:
```suggestion
- An Azure AD user with the following role assignments:
```

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +- Microsoft Azure Cloud Shell or PowerShell.
```suggestion
- Microsoft Azure CLI or Azure Az PowerShell module.  See [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and [Install Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps)
```

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +- The Azure CLI installed on your computer or Azure Cloud Shell. See [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).
Please delete this line, its now redundant

2022-07-20 18:29 UTC, dnarain-astro commented on astro/install-azure.md
> +    subid=$(az account show --query id --output tsv)
```suggestion
    subid=$(az account show --query id --output tsv)
    az role assignment create --assignee a67e6057-7138-4f78-bbaf-fd9db7b8aab0 --role Owner --scope /subscriptions/$subid
```

2022-07-20 18:41 UTC, kwcanuck commented on astro/install-azure.md
> +- A minimum quota of 40 standard DDv5 series vCPUs. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/per
@dnarain-astro I have adjusted the text. Please review and confirm accuracy.

2022-07-20 18:46 UTC, kwcanuck commented on astro/install-azure.md
> +- The Azure CLI installed on your computer or Azure Cloud Shell. See [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).
@dnarain-astro the text has been removed.

2022-07-20 20:33 UTC, chomipi88 commented on astro/install-azure.md
> +If you don't specify a preferred configuration for your organization, Astronomer support creates a cluster in `us-central1` with the default configurations for Astro on Azure. See [Azure resource ref
`centralus` is a valid Azure region out of Iowa, USA

2022-07-21 14:22 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +The default maximum node count for all nodes across your cluster is 20. A cluster's node count is most affected by the number of worker Pods that are executing Airflow tasks. See [Worker autoscaling
@paolaperaza is this still accurate? or is this max now just for the default worker node group?

2022-07-21 14:22 UTC, chomipi88 commented on astro/resource-reference-azure.md
> +|Standard_D4ds_v4 (Default)      | 24         | 4 vCPUs  | 16    GiB MEM |
Fairly certain these AU values are not accurate. The default is a bigger machine but has a smaller max AU then D2ds_v4

2022-07-21 14:23 UTC, kwcanuck commented on astro/resource-reference-azure.md
> +|Standard_D4ds_v4 (Default)      | 24         | 4 vCPUs  | 16    GiB MEM |
@chomipi88 you or @dnarain-astro will need to provide the maximum AU numbers. This is still a work in progress...

2022-07-21 15:55 UTC, dnarain-astro commented on astro/install-azure.md
> +- A minimum quota of 48 Standard Ddv5-series or Dv5-series vCPUs in the deployment region. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-u
Rob, just FYI - we need 48 Ddv5 vCPUs to install the cluster with the default. 

IF the customer chooses to override the default (and use Dv5 series), then they ALSO need to make sure they have quota for Dv5 - we still need the Ddv5 quota in this case.

Not sure what's the clearest way of saying that, so making it a comment and not a suggestion.

2022-07-21 15:57 UTC, dnarain-astro commented on astro/install-azure.md
> +- Microsoft Azure CLI or Azure Az PowerShell module.  See [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and [nstall the Azure Az PowerShell module](http
```suggestion
- Microsoft Azure CLI or Azure Az PowerShell module.  See [How to install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps).
```

2022-07-21 16:14 UTC, dnarain-astro reviewed
Clarified the quota section, fixed a small typo - I think that's it.

2022-07-21 17:27 UTC, kwcanuck commented on astro/install-azure.md
> +- A minimum quota of 48 Standard Ddv5-series or Dv5-series vCPUs in the deployment region. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-u
@dnarain-astro it wasn't clear what update you are requesting. However, I attempted to modify the text. Please review and provide your edits.

2022-07-21 17:47 UTC, dnarain-astro commented on astro/data-plane-activation.md
> +- [ ] An Azure Subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported
```suggestion
- [ ] A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be included in an Azure management group that doesn't apply Azure policies. See [What are Azure management groups?](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview).
```

2022-07-22 21:25 UTC, dnarain-astro approved these changes

2022-07-22 21:25 UTC, dnarain-astro commented on astro/install-azure.md
> +    ```sh
Migrate this into the previous block - so its 
echo "Registration Complete"
az provider register --namespace Microsoft.Compute
```

2022-07-22 21:25 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5 - 4/16/150 (Default)
```suggestion
- Standard_D4d_v5 - 4 vCPU/16GB
```

2022-07-22 21:25 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8d_v5 - 8/32/300
```suggestion
- Standard_D8d_v5 - 8 vCPU/32GB
```

2022-07-22 21:25 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8d_v5 - 8/32/300
```suggestion
- Standard_D8d_v5 - 8 vCPU/32GB
```

2022-07-22 21:25 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8_v5 - 8/32
```suggestion
- Standard_D8_v5 - 8 vCPU/32GB
```

2022-07-22 21:25 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +
FYI, I removed the disk sizes from the machine descriptions (since we may change it between. now and GA - I can come back in and ask for them to be updated later closer to GA)

2022-07-25 11:40 UTC, kwcanuck commented on astro/install-azure.md
> +    ```sh
The code example has been removed as requested. Thanks!

2022-07-25 11:42 UTC, kwcanuck commented on astro/install-azure.md
> +    ```sh
@dnarain-astro the code example has been updated as requested.

2022-07-25 11:50 UTC, kwcanuck commented
This was the feedback from @dnarain-astro: 

_"...from now on out, its just me picking nits   From my perspective, we are good to go except for the bit where we do the AU math and give you the numbers for the table at the end of the resources doc)"._

@jwitz this PR is now ready for your review. There _might_ be minor changes in the coming days, but I want to get this new documentation peer reviewed before your scheduled vacation. Thanks!

2022-07-25 15:47 UTC, jwitz approved these changes
Overall this looks great @kwcanuck , just left a few comments. Didn't touch the latter part of the resource reference as much because that will already be changing significantly with the arrival of worker queues.

2022-07-25 15:47 UTC, jwitz commented on astro/data-plane-activation.md
> +<TabItem value="azure">
I think we've always organized the three clouds in terms of their perceived popularity, which normally meant that we would mention Azure last after GCP. This order still makes sense because it's alphabetical, but if we go for that then we should make a style note of it and be consistent throughout the other docs.

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be included in an Azure management group that doesn
```suggestion
- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be included in an Azure management group that doesn't apply Azure policies. See [What are Azure management groups](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview).
```
Avoid double punctuation?

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +    - `Owner` with permission to create and manage subscription resources of all types. See [Azure built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-rol
"Azure built-in roles" has the same link as the previous doc, it might need to be updated.

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +- A minimum quota of 48 Standard Ddv5-series vCPUs in the deployment region. You can use Dv5-series vCPUs, but you'll need 96 vCPUs; 48 Ddv5-series vCPUs and 48 Dv5-series vCPUs. To adjust your quota
```suggestion
- A minimum quota of 48 Standard Ddv5-series vCPUs in the deployment region. You can use Dv5-series vCPUs, but you'll need 96 total vCPUs composed of 48 Ddv5-series vCPUs and 48 Dv5-series vCPUs. To adjust your quota limits up or down, see [Increase VM-family vCPU quotas](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/per-vm-quota-requests).
```

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +See [Log in to Astro](log-in-to-astro.md).
We don't have a prerequisite for an Astronomer account, nor do we have steps for creating one in the log in doc. For the time being, I would replicate what we have in the AWS install doc for this step: https://docs.astronomer.io/astro/install-aws#step-1-access-astro

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +    done
```suggestion
    done
    ```
```

2022-07-25 15:47 UTC, jwitz commented on astro/install-azure.md
> +- Optional. Your custom CIDR ranges for Astronomer service connections. The default is 172.20.0.0/19.
```suggestion
- Optional. Your custom CIDR ranges for Astronomer service connections. The default is `172.20.0.0/19`.
```

2022-07-25 15:47 UTC, jwitz commented on astro/resource-reference-azure.md
> +Unless otherwise specified, new Clusters on Microsoft Azure are created with a set of default resources that are considered appropriate for most use cases.
```suggestion
Unless otherwise specified, new clusters on Microsoft Azure are created with a set of default resources that are considered appropriate for most use cases.
```

2022-07-25 17:06 UTC, kwcanuck commented on astro/data-plane-activation.md
> +<TabItem value="azure">
@jwitz I went with an alphabetical order as it made the most sense to me. I _think_ this is how most users will approach the docs. I'll leave it for now, but I'll update it later if necessary.

2022-07-25 17:08 UTC, kwcanuck commented on astro/install-azure.md
> +- A clean Azure subscription. For security reasons, Azure subscriptions with existing tooling running aren't supported. Also, the subscription must be included in an Azure management group that doesn
@jwitz the question mark was part of the doc title, but I agree it probably should be removed.

2022-07-25 18:08 UTC, kwcanuck commented on astro/install-azure.md
> +    - `Owner` with permission to create and manage subscription resources of all types. See [Azure built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-rol
@jwitz good catch. This has been corrected.

2022-07-25 18:11 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5 - 4 vCPU/16GB
```suggestion
- Standard_D4_v5
```

2022-07-25 18:12 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5 - 4 vCPU/16GB
```suggestion
- Standard_D4d_v5
```

2022-07-25 18:12 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8d_v5 - 8/32/300
```suggestion
- Standard_D8d_v5
```

2022-07-25 18:12 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8d_v5 - 8 vCPU/32GB
```suggestion
- Standard_D4_v5 
```

2022-07-25 18:13 UTC, dnarain-astro commented on astro/resource-reference-azure.md
> +- Standard_D8_v5 - 8 vCPU/32GB
```suggestion
- Standard_D8_v5

2022-07-25 18:17 UTC, kwcanuck commented on astro/install-azure.md
> +See [Log in to Astro](log-in-to-astro.md).
@jwitz I have updated the procedure.

2022-07-27 08:11 UTC, shri-astro approved these changes

2022-07-27 17:54 UTC, goutamtadi1 commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5
@melugoyal did we move all instances to v5?

2022-07-27 17:56 UTC, kwcanuck commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5
@dnarain-astro provided this information and he can confirm if it is still accurate.

2022-07-27 18:02 UTC, melugoyal commented on astro/resource-reference-azure.md
> +- Standard_D4d_v5
yup

2022-07-27 20:13 UTC, dnarain-astro commented on astro/install-azure.md
> +    done
```suggestion
    done
    echo "Registration Complete"
    az provider register --namespace Microsoft.Compute
```

2022-07-27 20:14 UTC, dnarain-astro commented on astro/install-azure.md
> +    az provider register --namespace Microsoft.Compute
```suggestion
```

2022-07-27 20:15 UTC, dnarain-astro commented on astro/install-azure.md
> +    echo "Registration Complete"
```suggestion
```

2022-07-27 20:16 UTC, dnarain-astro requested changes
Some of the cli commands were out of sequence, made suggestions to get them in the right order.

2022-07-28 15:27 UTC, dnarain-astro approved these changes

2022-07-28 18:40 UTC, melugoyal approved these changes

2022-07-29 18:48 UTC, dnarain-astro commented on astro/install-azure.md
> +    ```sh
```suggestion
    ```sh
    subid=$(az account show --query id --output tsv)
```

2022-07-29 19:45 UTC, merged