Fix cloud quickstart
astronomer/docs pull request #93
Opened 2020-12-08 18:47 UTC by petedejoy

This PR realigns our quickstart positioning to better fit our new customer onboarding process being pushed in our new website.

2020-12-08 20:24 UTC, paolaperaza requested changes
@petedejoy Spotted a typo/made one comment - lemme know once you fix and I'll pop back in here and merge! Good call to make these changes.

2020-12-08 20:24 UTC, paolaperaza commented on cloud/README.md
> +If you're interested in giving Astronomer Cloud a spin, you can start a free 14-day trial by [reaching out to us here](/get-astronomer?ref=docs). is the best way to get started. You're welcome to sig
```suggestion
If you're interested in trying out Astronomer Cloud, start a free 14-day trial by [reaching out to us here](/get-astronomer?ref=docs). You're welcome to sign up at anytime, no credit card required.
```

2020-12-08 20:24 UTC, paolaperaza commented on cloud/README.md
> +If you're interested in giving Astronomer Cloud a spin, you can start a free 14-day trial by [reaching out to us here](/get-astronomer?ref=docs). is the best way to get started. You're welcome to sig
("Giving Astronomer Cloud a spin" feels like too much like lingo/not accessible, so simplified it)

2020-12-09 00:53 UTC, paolaperaza commented on cloud/README.md
> +If you're interested in giving Astronomer Cloud a spin, you can start a free 14-day trial by [reaching out to us here](/get-astronomer?ref=docs). is the best way to get started. You're welcome to sig
Ok I fixed this :)

2020-12-09 01:01 UTC, paolaperaza commented
@petedejoy After giving this original PR a quick review I realized that this doc (which is the first touchpoint for new users) was embarrassingly out of date given Airflow 2.0 and latest platform changes. There's still more that can be better, but I did a first pass at updating this. Feel free to review!

2020-12-09 02:22 UTC, petedejoy commented
Great changes, going to merge this, thanks @paolaperaza!

2020-12-09 02:22 UTC, merged