Add Elasticsearch as an External Logging Service Topic
astronomer/docs pull request #951
Opened 2022-07-25 13:06 UTC by kwcanuck

Resolves #267

2022-07-26 17:41 UTC, kwcanuck commented on software/export-task-logs.md
> +  ![Elastic Gear icon location](/img/docs/elasticsearch-gear-icon.png)
@jwitz I agree with your concern. However, this icon isn't easy to locate - trust me, I know!

2022-07-26 17:46 UTC, kwcanuck commented on software/export-task-logs.md
> +    ```text
@jwitz this output confirms the Elasticsearch Deployment endpoint was created successfully. It's an optional step. I'll confirm with the SMEs of it can be removed.

2022-07-26 17:53 UTC, kwcanuck commented on software/export-task-logs.md
> +  ```yaml
@jwitz I have done my best to format the code blocks correctly.

2022-08-02 04:19 UTC, stuart23 commented on software/export-task-logs.md
> +5. Optional. Test the Elasticsearch Deployment endpoint:
Elasticsearch is the (main) component in the Elastic stack. The elastic stack includes Kibana and some other stuff we never use

2022-08-02 04:22 UTC, stuart23 commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
```suggestion
    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar to test the connection.
```

Not sure you 'click' enter

2022-08-02 04:23 UTC, stuart23 commented on software/export-task-logs.md
> +    ```text
Affirm. Could just include something generic like "if successful, you will be presented with details of the Elastic Cluster."

2022-08-02 04:25 UTC, stuart23 commented on software/export-task-logs.md
> +6. Run the following command to download the Astronomer Helm chart:
These steps are not needed. I can't remember why I included them. I think it was just to ensure that the chart being used is 0.27+

2022-08-02 04:26 UTC, stuart23 commented on software/export-task-logs.md
> +        {label: 'Kubernetes cluster', value: 'kubernetes cluster'},
```suggestion
        {label: 'Kubernetes secret', value: 'kubernetes secret'},
```

2022-08-02 04:29 UTC, stuart23 commented on software/export-task-logs.md
> +    secret: "<secret>"
```suggestion
    secret: "<encoded credentials>"    
```
From someone who has not been exposed to this, is it obvious that <secret> refers to the output of the above step? I think <encoded credentials> might be more straightforward

2022-08-02 04:29 UTC, stuart23 commented on software/export-task-logs.md
> +    # secret encoded from above step
```suggestion
    # credentials encoded from above step
```
See comment on next line

2022-08-02 04:30 UTC, stuart23 commented on software/export-task-logs.md
> +<TabItem value="kubernetes cluster">
```suggestion
<TabItem value="kubernetes secret">
```

2022-08-02 04:32 UTC, stuart23 commented on software/export-task-logs.md
> +After you've created an Elastic deployment and endpoint, you have two options to save your Elastic deployment credentials. You can update your Software `config.yaml` file, or you can create a secret
```suggestion
After you've created an Elastic deployment and endpoint, you have two options to store your Elastic deployment credentials. You can store them directly in your Software helm values, or you can create a secret in your Software Kubernetes cluster.
```

2022-08-02 04:33 UTC, stuart23 commented on software/export-task-logs.md
> +
Can we also reference the updating config.yaml instructions here please: https://docs.astronomer.io/software/apply-platform-config

2022-08-02 04:34 UTC, stuart23 commented on software/export-task-logs.md
> +4. Run the following command to upgrade the Astronomer Software release version in the `config.yaml` file:
If we reference the [Apply a Software platform configuration change
](https://docs.astronomer.io/software/apply-platform-config) instructions, we can omit this step as it is already covered

2022-08-02 04:36 UTC, stuart23 commented on software/export-task-logs.md
> + kubectl create secret generic elasticcreds --from-literal elastic=elastic:samplepassword --namespace=<your-platform-namespace>
```suggestion
 kubectl create secret generic elasticcreds --from-literal elastic=<username>:<password> --namespace=<your-platform-namespace>
```

2022-08-02 04:37 UTC, stuart23 commented on software/export-task-logs.md
> +4. Run the following command to upgrade the Astronomer Software release version in the `config.yaml` file:
Again, we can probably omit this step if we refer to

2022-08-02 04:39 UTC, stuart23 requested changes
Thanks @kwcanuck for putting this together. I have tried to take some of the lessons I have learnt from you and Jake to make it a bit more intuitive, let me know if you would like to get together over it.

2022-08-02 11:21 UTC, kwcanuck commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
@stuart23 if you simply add the endpoint to the Address bar and don't click **Enter**, nothing happens. Clicking **Enter** is a necessary step. To test it for yourself, enter _https://test-for-docs.es.us-central1.gcp.cloud.es.io_ in your browser Address bar and then do nothing. Do you see the authentication prompt? No. If you press **Enter**, you will.

2022-08-02 11:23 UTC, kwcanuck commented on software/export-task-logs.md
> +6. Run the following command to download the Astronomer Helm chart:
@stuart23 I assumed that this was a confirmation step and also that you wanted to make sure the chart was downloaded. I have removed the steps as requested.

2022-08-02 11:34 UTC, kwcanuck commented on software/export-task-logs.md
> +4. Run the following command to upgrade the Astronomer Software release version in the `config.yaml` file:
@stuart23 this is a simple step. It's better to provide the necessary information here rather than unnecessarily force a user to link to another topic.

2022-08-02 11:35 UTC, kwcanuck commented on software/export-task-logs.md
> +
@stuart23 this is a self-contained, simple task. There is no need to link to another topic as the user is unlikely to understand the relevance.

2022-08-02 11:36 UTC, kwcanuck commented on software/export-task-logs.md
> +4. Run the following command to upgrade the Astronomer Software release version in the `config.yaml` file:
@stuart23 see my previous comment.

2022-08-02 11:38 UTC, kwcanuck commented
@stuart23 I have addressed all of your change requests. Please review and then unblock the merge. If you have questions, please contact me, or let me know when you're available. Thanks!

2022-08-02 11:40 UTC, kwcanuck commented on software/export-task-logs.md
> +    ```text
@stuart23 thanks for confirming. I think that it's obvious that this is an optional step and why it is being performed.

2022-08-02 12:27 UTC, stuart23 commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
People using this guide have an assumed level of technical competency, so they will know how to open a URL in a browser. 
I was just struggling with the verb 'click', as to me it implies a mouse click. If this is how we should instruct people to visit a URL then that's fine.

2022-08-02 12:58 UTC, stuart23 approved these changes
Looks Great @kwcanuck!

2022-08-02 12:58 UTC, kwcanuck commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
@stuart23 thanks for the clarification. Actually, the instruction should be **Press** as this is a keyboard action. I have updated the text. Good catch!

2022-08-02 13:01 UTC, stuart23 commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
Sorry for the nitpicking! I know you are detail oriented, so I hope you don't mind

2022-08-02 13:03 UTC, kwcanuck commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then click **Enter**.
@stuart23 not at all. I appreciate your keen eye.

2022-08-04 15:42 UTC, paolaperaza commented on software/export-task-logs.md
> +## Forward Deployment task logs to Elasticsearch
@kwcanuck Did you wanna have a prerequisites section here? Or not needed?

2022-08-04 17:44 UTC, kwcanuck commented on software/export-task-logs.md
> +## Forward Deployment task logs to Elasticsearch
@paolaperaza this is a straightforward process, so there is no need for a prerequisites list.

2022-08-04 17:48 UTC, kwcanuck commented on software/export-task-logs.md
> +    - Open a new browser window, paste the endpoint you copied in step 4 in the **Address** bar, and then press **Enter**.
@paolaperaza the user doesn't copy the endpoint from the **Address** bar.  It's copied when they select a link on the Elasticsearch dashboard. So, this change is not accurate.

2022-08-04 17:54 UTC, kwcanuck commented on software/export-task-logs.md
> +
@paolaperaza I added the link, but I think it's unnecessary for the reasons previously stated. If users want or need more information, they can quickly locate it by searching. Also, adding too many links can cause issues when topic titles change, or the topics are removed. The less linking, the easier a documentation set is to manage and maintain. Link rot is a big problem for many companies.

2022-08-08 07:32 UTC, stuart23 commented on software/export-task-logs.md
> +After you've created an Elastic deployment and endpoint, you have two options to store your Elastic deployment credentials. You can store the credentials in your Astronomer Software helm values, or a
The preference question was resolved by Rob.

2022-08-08 07:33 UTC, stuart23 approved these changes

2022-08-08 17:09 UTC, paolaperaza approved these changes
LGTM @kwcanuck ! Thank you, this is a big one 🚀

2022-08-08 17:26 UTC, cmarteepants requested changes

2022-08-08 17:26 UTC, cmarteepants commented on software/export-task-logs.md
> +## Forward Airflow task logs to Elasticsearch
Would rewrite this as "Use an External Elasticsearch for Airflow Task Logs" (but with better English). 

As written, because of existing docs, it sounds like we are sending Airflow Task Logs to the Astronomer ElasticSearch AND external elasticsearch (like we do when forwarding Airflow Task Logs to S3). We are not, we're using the external elasticsearch as a an alternative to the one that ships with Astronomer.

2022-08-08 17:26 UTC, cmarteepants commented on software/export-task-logs.md
> +Add Airflow task logs from your Astronomer Deployment to an existing Elasticsearch instance on [Elastic Cloud](https://www.elastic.co/cloud/) to centralize log management and analysis. Centralized lo
@stuart23 @rob-1126 Curious as to why we decided to make this doc Elastic Cloud specific. We can use any elasticsearch - self-hosted or the cloud managed ones like on AWS, not just the Elastic Cloud one. Maybe we say that this is an example using an Elasticsearch instance on Elastic Cloud?

2022-08-08 17:34 UTC, kwcanuck commented on software/export-task-logs.md
> +## Forward Airflow task logs to Elasticsearch
@cmarteepants I have updated the title to: _Use Elasticsearch for Airflow task log management_

2022-08-08 17:38 UTC, kwcanuck commented on software/export-task-logs.md
> +Add Airflow task logs from your Astronomer Deployment to an existing Elasticsearch instance on [Elastic Cloud](https://www.elastic.co/cloud/) to centralize log management and analysis. Centralized lo
@cmarteepants we typically document the most common scenario. In this case, it was assumed that Elastic Cloud would be the most common scenario. Also, we're a cloud company and it makes sense to promote the cloud when possible. Ultimately, the procedures should be similar and users should be able to complete them successfully using our content as a reference.

2022-08-08 17:39 UTC, cmarteepants commented on software/export-task-logs.md
> +## Forward Airflow task logs to Elasticsearch
Better, but we need to say it's an external one to differentiate with the one we ship with. As is, title applies to all scenarios.

2022-08-08 17:41 UTC, kwcanuck commented on software/export-task-logs.md
> +## Forward Airflow task logs to Elasticsearch
@cmarteepants I have updated the title to: _Use an external Elasticsearch instance for Airflow task log management_

2022-08-08 18:08 UTC, cmarteepants approved these changes

2022-08-08 18:10 UTC, merged